containers/podman

- Makefile
- cmd/podman-mac-helper/install.go
- cmd/podman-mac-helper/main.go
- cmd/podman-mac-helper/service.go
- cmd/podman-mac-helper/uninstall.go
- cmd/podman/machine/init.go
- cmd/podman/machine/set.go
- docs/source/markdown/podman-machine-init.1.md
- docs/source/markdown/podman-machine-set.1.md
- docs/source/markdown/podman-machine.1.md
- pkg/machine/config.go
- pkg/machine/connection.go
- pkg/machine/qemu/claim_darwin.go
- pkg/machine/qemu/claim_unsupported.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
This PR provides a comparable low-touch experience to the current windows API forwarding approach by introducing a privileged helper that runs under launchd. 
Fixes #11462 
Fixes #11397 
Fixes #11389 
Fixes #11422
Additional changes in this PR
- podman machine can now be configured to run as rootful or rootless by passing `--rootful=true`|`false` to `init`
- Added new `podman machine set` command to change this after init (and in the future other settings that can be changed)
- Switched Windows to rootless default to match mac default
- `podman machine start` now advises how to switch to rootful 
- Windows is now updated to pull podman4 from the copr repo like on mac
The reasons for this approach are:
1.  docker.sock is immediately under /var/run which is not writable to users
2. /var/run …
> Mac API forwarding using a privileged docker socket claim helper

- pkg/util/utils_linux.go
Previously, devices with a major/minor number >256 would fail to be
detected.  Switch to using bitwise conversion (similar to
sys/sysmacros in C).
Currently, minor numbers for attached devices cannot exceed 256 as we use a modulo to determine the device's minor number.
In the current Linux kernel, it is currently possible to have much larger ID's than this, and if this happens podman will error as the modulo will produce an incorrect result.  Consider the following where I created a large minor-numbered device via a custom driver:
```bash
WARN[0000] Could not locate device 242:65536 on host    
[]
```
This patch uses bitwise maths to determine the ID's from the `stat` syscall, and should future-proof both the minor and major device numbers, at least for a little while.  Check the …
> Calculate device major/minor using bitshift

- test/e2e/volume_plugin_test.go
We could remove the container running the volume plugins, before the containers using the volume plugins; this could cause
unmounting the volumes to fail because the plugin could not be contacted.
> Fix a potential flake in volume plugins tests

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
We've got some python tests running in CI, and they're really hard
to troubleshoot. This PR:
1) colorizes python unittest lines (ok / skipped / fail), and
2) links to source files
The color is nice for skimming, but it's the linking that might
make it much easier to diagnose future failures.
(Context: failure today in test/python/docker/compat/test_images.py)
> [CI:DOCS] logformatter: handle python logs

- libpod/oci_conmon_linux.go
- test/system/800-config.bats
- test/system/helpers.bash
The `CONTAINERS_CONF` environment variable can be used to override the configuration file, which is useful for testing.  However, at the moment this variable is not propagated to conmon.  That means in particular, that conmon can't propagate it back to podman when invoking `--exit-command`.  The mismatch in configuration between the starting and cleaning up podman instances can cause a variety of errors.
This patch also adds two related test cases.  One checks explicitly that the correct `$CONTAINERS_CONF` value appears in conmon's environment.  The other checks for a possible specific impact of this bug: if we use a nonstandard name for the runtime (even if its path is just a regular crun), then the podman container cleanup invoked at container exit will fail. That has the effect of …
> Propagate CONTAINERS_CONF to conmon

- troubleshooting.md
* Mention overlay option for --rootfs. Overlay description text
is from commit 020d81f113ea1e11398ea77495cc4b8e05a91d38
by Qi Wang
> [CI:DOCS] troubleshooting: mention overlay option for --rootfs

- troubleshooting.md
Expand the bit about needing to allocate UIDs so that we don't appear to imply that adding a range of 10000 IDs to /etc/subuid will allow people to use UID 1000000, which isn't in the range that we'd map a range of that size to.
TLS is an acronym, so capitalize when we're talking about the protocol.
TLS verification is about encryption, not authentication.
> [CI:DOCS] troubleshooting.md: tweak subuid paragraph, encryption

- test/system/001-basic.bats
We're running into problems that are impossible to diagnose
because we have no idea if the SUT is using netavark or CNI.
We've previously run into similar problems with runc/crun,
or cgroups 1/2.
This adds a one-line 'echo' with important system info. Now,
when viewing a full test log, it will be possible to view
system settings in one glance.
> System tests: show one-line config overview

- cmd/podman/main.go
- test/system/001-basic.bats
- test/system/300-cli-parsing.bats
Add a extra `See 'podman command --help'` to the error output.
With this patch you now get:
```
$ podman run -h
Error: flag needs an argument: 'h' in -h
See 'podman run --help'
```
Fixes #13082
Fixes #13002
> provide better error on invalid flag

- cmd/podman/registry/remote.go
- docs/source/markdown/podman.1.md
- test/system/001-basic.bats
Closes #13242
Note: I am not sure how to actually test anything, I blindly tried to add a test, hoping your CI will run it for me !
> Option --url and --connection should imply --remote.

- pkg/util/utils.go
- pkg/util/utils_supported.go
To prevent duplication and potential bugs we should use the same
GetRuntimeDir function that is used in c/common.
> use GetRuntimeDir() from c/common

- cmd/podman/play/kube.go
- docs/source/markdown/podman-play-kube.1.md
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- test/e2e/play_build_test.go
`podman play kube` tries to build images even if `--build` is set to
false so lets honor that and make `--build` , `true` by default so it
matches the original behavior.
Closes: https://github.com/containers/podman/issues/13285
> kube: honor `--build=false` if specified.

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
- test/e2e/images_test.go
- test/python/docker/compat/test_images.py
> Fix AssertionError: 'alpine' not found in 'docker.io/docker/desktop-kubernetes'

- test/system/helpers.bash
When a test which creates a network fail it will not remove the network.
The teardown logic should remove the networks. Since there is no --all
option for network rm we use network prune --force.
> system tests: cleanup networks on teardown

- cmd/podman/common/completion.go
- cmd/podman/common/create.go
- cmd/podman/containers/clone.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- cmd/podman/pods/create.go
- docs/source/markdown/podman-container-clone.1.md
- docs/source/markdown/podman-container.1.md
- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/options.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/domain/entities/containers.go
- pkg/domain/entities/engine_container.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/tunnel/containers.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/oci.go
- pkg/specgen/generate/pod_create.go
- pkg/specgenutil/createparse.go
- pkg/specgenutil/specgen.go
- test/e2e/container_clone_test.go
podman container clone takes the id of an existing continer and creates a specgen from the given container's config
recreating all proper namespaces and overriding spec options like resource limits and the container name if given in the cli options
this command utilizes the common function DefineCreateFlags meaning that we can funnel as many create options as we want
into clone over time allowing the user to clone with as much or as little of the original config as they want.
the current supported flags are:
--id (ctr to clone)
--destroy (remove the original container)
--name (new ctr name)
--cpus (sets cpu period and quota)
--cpuset-cpus
--cpu-period
--cpu-rt-period
--cpu-rt-runtime
--cpu-shares
--cpuset-mems
--memory
> Implement Podman Container Clone

- libpod/networking_linux.go
- libpod/runtime.go
- libpod/runtime_cstorage.go
- libpod/runtime_ctr.go
- libpod/runtime_img.go
- libpod/runtime_pod.go
- libpod/runtime_pod_linux.go
- libpod/runtime_volume.go
- libpod/runtime_volume_linux.go
This primarily served to protect us against shutting down the Libpod runtime while operations (like creating a container) were happening. However, it was very inconsistently implemented (a lot of our longer-lived functions, like pulling images, just didn't implement it at all...) and I'm not sure how much we really care about this very-specific error case?
Removing it also removes a lot of potential deadlocks, which is nice.
> Remove the runtime lock

- cmd/podman/images/trust_show.go
- docs/source/markdown/podman-image-trust.1.md
- pkg/domain/infra/abi/trust.go
- pkg/trust/config.go
- pkg/trust/trust.go
- test/e2e/trust_test.go
- test/system/750-trust.bats
- test/trust_set_test.json
> Cleanup display of trust with transports

- libpod/container_inspect.go
- libpod/runtime_ctr.go
- test/system/070-build.bats
When removing a container created with a --volumes-from a container
created with a built in volume, we complain if the original container
still exists.  Since this is an expected state, we should not complain
about it.
Fixes: https://github.com/containers/podman/issues/12808
> Don't log errors on removing volumes inuse, if container --volumes-from

- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/kube_test.go
convert the propagation mode specified for the mount to the expected
Linux mount option.
> kube: honor mount propagation mode

- troubleshooting.md
I'm adding this PR as a sketch, because I haven't checked the details yet.
It might very well be that systemd version 248 is needed instead of systemd version 249.
This PR
https://github.com/systemd/systemd/pull/17967
gives an indication that the requirement is systemd v248.
> [CI:DOCS] troubleshooting: mention machinectl and systemd-run

- cmd/podman/containers/commit.go
- docs/source/markdown/podman-commit.1.md
- libpod/container_commit.go
- pkg/api/handlers/compat/images.go
- pkg/api/handlers/libpod/images.go
- pkg/api/server/register_images.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_commit_options.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/commit_test.go
Allow users to commit containers into a single layer.
Usage
```bash
podman container commit --squash <name>
```
Closes: https://github.com/containers/podman/issues/12889
> container-commit: support `--squash` to squash layers into one if users want.

- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/play_test.go
this fixes https://github.com/containers/podman/issues/13115
the change tries to imitate k8s behavior.
when limits are not set the container's limits are all CPU and all RAM
when requests are missing then they are equal to limits
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>
> play kube: set defaults to container resources

- docs/source/markdown/podman-generate-systemd.1.md
Generating unit files for a pod requires the pod to be created with an
infra container (see `--infra=true`).  An infra container runs across
the entire lifespan of a pod and is hence required for systemd to manage
the life cycle of the pod's main unit.
This issue came up on the mailing list.
> [CI:DOCS] generate-systemd: pod requires an infra container

- docs/source/markdown/podman-play-kube.1.md
- pkg/domain/infra/abi/play.go
If you run `podman play kube` on a yaml file that only contains
configMaps, podman will fail with the error:
Error: YAML document does not contain any supported kube kind
This is not strictly true; configMaps are a supported kube kind. The
problem is that configMaps aren't a standalone entity. They have to be
used in a container somewhere, otherwise they don't do anything.
This change adds a new message in the case when there only configMaps
resources. It would be helpful if podman reported which configMaps are
unused on every invocation of kube play. However, even if that feedback
were added, this new error messages still helpfully explains the reason
that podman is not creating any resources.
Signed-off-by: Jordan Christiansen <xordspar0@gmail.com>
> Improve the error message for usused configMaps

- libpod/util.go
Previously just showing name of the package, followed by
the path repeated again (already stated on the line above)
BEFORE:
```
conmon:
package: 'conmon: /usr/libexec/podman/conmon'
path: /usr/libexec/podman/conmon
```
```
name: crun
package: 'crun: /usr/bin/crun'
path: /usr/bin/crun
```
```
slirp4netns:
executable: /usr/bin/slirp4netns
package: 'slirp4netns: /usr/bin/slirp4netns'
```
AFTER
```
conmon:
package: conmon_100:2.0.30-2_amd64
path: /usr/libexec/podman/conmon
```
```
name: crun
package: crun_100:1.2-2_amd64
path: /usr/bin/crun
```
```
slirp4netns:
executable: /usr/bin/slirp4netns
package: slirp4netns_100:1.1.8-3_amd64
```
> Show version of the deb package in info output

- podman.spec.rpkg
@baude @mheon @Luap99 @rhatdan PTAL
> copr packaging: use generic macros for tmpfiles and modules load dirs

- contrib/cirrus/runner.sh
> Clarify v2 API testing for podman vs docker clients

- cmd/podman/volumes/exists.go
- cmd/podman/volumes/mount.go
- cmd/podman/volumes/unmount.go
- docs/source/markdown/podman-volume-mount.1.md
- docs/source/markdown/podman-volume-unmount.1.md
- docs/source/markdown/podman-volume.1.md
- libpod/volume.go
- libpod/volume_internal_linux.go
- pkg/domain/entities/engine_container.go
- pkg/domain/entities/volumes.go
- pkg/domain/infra/abi/volumes.go
- pkg/domain/infra/tunnel/volumes.go
- test/system/160-volumes.bats
Fixes: https://github.com/containers/podman/issues/12768
> Add podman volume mount support

- cmd/podman/pods/logs.go
- docs/source/markdown/podman-pod-logs.1.md
- libpod/container_log_linux.go
- test/e2e/logs_test.go
Fixes containers#13261
Signed-off-by: Xueyuan Chen <X.Chen-47@student.tudelft.nl>
> Add the names flag for pod logs

- Makefile
- pyproject.toml
- test/python/docker/__init__.py
- test/python/docker/compat/common.py
- test/python/docker/compat/constant.py
- test/python/docker/compat/test_containers.py
- test/python/docker/compat/test_images.py
- test/python/docker/compat/test_system.py
- test/python/docker/conftest.py
* Add which python client is being used to run tests, see "python
client" below.
* Remove redundant code from test classes
* Update/Add comments to modules and classes
======================================================= test session starts ========================================================
platform linux -- Python 3.10.0, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
python client -- DockerClient
rootdir: /home/jhonce/Projects/go/src/github.com/containers/podman
plugins: requests-mock-1.8.0
collected 33 items
test/python/docker/compat/test_containers.py ...s..............  [ 54%]
test/python/docker/compat/test_images.py ............  [ 90%]
test/python/docker/compat/test_system.py ...  [100%]
Note: Follow-up PRs will verify the test results and expand the tests.
Signed-off-by: Jhon …
> Refactor docker-py compatibility tests

- pkg/util/utils.go
- pkg/util/utils_supported.go
This reverts commit fc5cf812c81a10f8a021aae11df5f12ab2a6f6f6.
> Revert "use GetRuntimeDir() from c/common"

- RELEASE_NOTES.md
- version/version.go
Tag v4.0.2 already added to the `Bump to v4.0.2` commit.
> Release v4.0.2

- go.mod
- go.sum
- test/system/070-build.bats
- vendor/github.com/containers/image/v5/oci/layout/oci_dest.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/github.com/containers/storage/containers.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- vendor/github.com/containers/storage/errors.go
- vendor/github.com/containers/storage/images.go
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/store.go
- vendor/github.com/containers/storage/utils.go
- vendor/modules.txt
Commits explained in bullet points.
* Bump  `c/storage` to `main/d06b0f `
* Bump  `c/image` to `main/9a9cd9`
New Names API in `c/storage` and `c/image` ensures that `Name` modification operations are `race-free`.
* Adds a test to verify `parallel/concurrent` builds via podman don't race against each other.
Read more about problem statement here: https://github.com/containers/buildah/pull/3794 and containers/podman#13339
> deps: bump to race-free `c/image` and `c/storage` along with test to verify `concurrent/parallel` builds

- RELEASE_PROCESS.md
The current PR process for release bump has the HEAD commit which bumps
version/version.go to the form `release+1-dev`. This makes Cirrus
publish release artifacts with `release+1-dev` and not `release`.
For example, the msi generated at https://cirrus-ci.com/task/5403901196238848
says podman-v4.0.3-dev.msi .
Building locally by checking out the released tag would generate the
correct artifacts and would also be faster and more convenient.
@mheon @ashley-cui @TomSweeneyRedHat @rhatdan @baude PTAL
/cc @containers/podman-maintainers 
DO NOT MERGE without LGTMs from @mheon and @ashley-cui
> RELEASE_PROCESS.md: build artifacts locally

- libpod/runtime_pod_linux.go
- test/e2e/containers_conf_test.go
do not attempt to use cgroups with pods if the cgroups are disabled.
A similar check is already in place for containers.
Closes: https://github.com/containers/podman/issues/13411
> libpod: pods do not use cgroups if --cgroups=disabled

- libpod/stats.go
- pkg/cgroups/cpu.go
[NO NEW TESTS NEEDED}
Backport of #4423 to the v1.6.4-rhel branch so that it
can be included into RHEL 8.2
This fixes the was that CPU is reported from the
`podman stats` command.  This fix was first put into
podman v1.7.0
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=2060095
> [v1.6.4-rhel] stats: report correctly CPU usage

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
Error out if the kube yaml passed to play kube has more
than one container or init container with the same name.
Fixes https://github.com/containers/podman/issues/13332
> Throw an error if kube yaml has duplicate ctr names

- pkg/api/handlers/compat/exec.go
This PR closes #13222 and continues from [PR941](https://github.com/containers/common/pull/941). 
It uses the `ExitCommandDelay` configuration value in order to reduce the clutter of many exec process idling in the background. This now allows you to configure this. I currently tested it for the default value and a smaller value by checking the processes and how much time they take to exit and debugged the int value, which was correctly set by changing it in `containers.conf`. In case we need a unit test or any documentation for this, please let me know!
Signed-off-by: Rover van der Noort <s.r.vandernoort@student.tudelft.nl>
> Add ExitCommandDelay configuration use in API exec handler

- pkg/machine/config.go
- pkg/machine/ignition.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/qemu/options_darwin_arm64.go
* Enable support of virtfs in Podman and darwin.  At the time of this writing, it requires a special patch not yet included in upstream qemu.
* Prefer to use a specially built qemu to support virtfs.  The qemu is installed under libexec/podman.
Signed-off-by: brent baude <brentbaude@brents-Mac-mini.localdomain>
> MacOS improvements

- libpod/networking_linux.go
- test/e2e/run_networking_test.go
Display network info of a joined network namespace upon inspect
Join network namespace and query interfaces/IPs/gateway
Closes: https://github.com/containers/podman/issues/13150
Signed-off-by: 😎 Mostafa Emami <mustafaemami@gmail.com>
> Inspect network info of a joined network namespace

- test/e2e/system_service_test.go
pprof tests are way too flaky, and are causing problems for
community contributors who don't have privs to press Re-run.
There has been no activity or interest in fixing the bug,
and it's not something I can fix. So, just disable the test.
> Skip flaky pprof tests

- troubleshooting.md
* Mention the command "podman unshare chown 0:0 dir1/a"
that changes file ownership to the regular user's UID and GID on
the host.
> [CI:DOCS] troubleshooting.md: mention "podman unshare chown 0:0 path"

- cmd/podman/machine/rm.go
- docs/source/markdown/podman-machine-rm.1.md
- pkg/machine/qemu/machine.go
If you want to remove a running machine, you can now pass the --force/-f
to podman machine rm and the machine will be stopped and removed without
confirmations.
Fixes: #13448
> machine rm -f stops and removes machine

- pkg/machine/qemu/machine.go
Improves the install instructions to include a machine restart which is required after the helper agent is installed. 
See #13456 
> Improve agent install message to add restart instructions

- pkg/specgen/generate/oci.go
- test/e2e/run_device_test.go
The default rule should be set at the head of device configuration.
Otherwise, rules for user devices are overridden by the default rule so
that any access to the user devices are denied.
Signed-off-by: Hironori Shiina <shiina.hironori@jp.fujitsu.com>
> Set default rule at the head of device configuration

- go.mod
- pkg/domain/infra/abi/play.go
- vendor/modules.txt
Many dependencies already import gopkg.in/yaml.v2, podman is the only
user of the v3 version except  github.com/stretchr/testify but this is
only a testing dependency so it will not end up in the binary.
This change reduces the podman binary size from 54740 to 54260 KB on my
system.
> use gopkg.in/yaml.v2 instead of v3

- cmd/podman/common/create_opts.go
- test/apiv2/20-containers.at
The permissions on disk were wrong since we were not converting to
octal.
Fixes: https://github.com/containers/podman/issues/13108
[NO NEW TESTS NEEDED] Since we don't currently test using the docker
client
> Fix handling of tmpfs-mode for tmpfs creation in compat mode

- cmd/podman/play/kube.go
- docs/source/markdown/podman-play-kube.1.md
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- test/system/700-play.bats
This option was requested so that users could specify alternate
locations to find context directories for each image build. It
requites the --build option to be set.
Partial Fix: https://github.com/containers/podman/issues/12485
> Add --context-dir option to podman play kube

- hack/install_golangci.sh
avoid this warn:
```
golangci/golangci-lint info installed ./bin/golangci-lint
golangci/golangci-lint err this script is deprecated, please do not use it anymore. check https://github.com/goreleaser/godownloader/issues/207
```
> CI: fix golangci-lint installation

- docs/source/conf.py
* Remove the ending text "(1)" to avoid it from being
displayed in the web tab title for a command man page
on the web. Often such a text indicates that a web
page got an update. For instance GitHub issues shows
the number of new comments that have been written
after the user's last visit.
Fixes #13438
> [CI:DOCS] Remove "(1)" from web tab text

- cmd/podman/play/kube.go
- docs/source/markdown/podman-play-kube.1.md
- pkg/api/handlers/libpod/play.go
- pkg/bindings/play/types.go
- pkg/bindings/play/types_kube_options.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/tunnel/play.go
- pkg/specgen/generate/kube/kube.go
- test/system/700-play.bats
Allow users to add annotions in the podman play kube command.
This PR Also fixes the fact that annotations in the pod spec were
not being passed down to containers.
Fixes: https://github.com/containers/podman/issues/12968
> Add podman play kube --annotation

- podman.spec.rpkg
fix conditionals and buildtags to enable rhel8 builds
@containers/podman-maintainers PTAL.
> podman.spec.rpkg: enable rhel8 builds on copr

- pkg/bindings/containers/attach.go
- pkg/bindings/containers/term_unix.go
- pkg/bindings/containers/term_windows.go
- pkg/signal/signal_unix.go
On Windows:
- Fixes "Failed to obtain TTY size" (the size call needs to be against stdout, the rest stdin)
- Adds support for vt100+ input so that cursor keys + escape work
- Implements window resizing via a polling methodology (only reliable solution on windows)
On Mac and other Unixes
- Added SIGWINCH support for all OSs that have it 
> Fixes TTY & resizing on Mac and Windows

- pkg/specgen/generate/oci.go
- test/e2e/run_device_test.go
Backports: #13421 Set default rule at the head of device configuration
by @hshiina
The default rule should be set at the head of device configuration.
Otherwise, rules for user devices are overridden by the default rule so
that any access to the user devices are denied.
This has been requested to backport and to include in RHEL 8.6 and 9.0.
The exception process is underway.
Addresses these BZs for the backport:
https://bugzilla.redhat.com/show_bug.cgi?id=2059296
https://bugzilla.redhat.com/show_bug.cgi?id=2062835
> [v4.0] Backport Set default rule at the head of dev config

- cmd/podman/common/create.go
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal_linux.go
- libpod/define/container_inspect.go
- libpod/options.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/create_test.go
Adds support for optional --chrootdirs=x to specify chroot dirs. Special files such as /etc/hosts will be automatically mounted into x/etc/hosts and so on.
Closes #12691
> Add support for --chrootdirs

- libpod/networking_slirp4netns.go
When enable_ipv6=true is set for slirp4netns (default since podman v4),
we will try to set the accept sysctl. This sysctl will not exist on
systems that have ipv6 disabled. In this case we should not error and
just ignore the extra ipv6 setup.
Also the current logic to wait for the slirp4 setup was kinda broken, it
did not actually wait until the sysctl was set before starting slirp.
This should now be fixed by using two `sync.WaitGroup`s.
Fixes #13388
> slirp: fix setup on ipv6 disabled systems

- Makefile
- pkg/bindings/containers/checkpoint.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_restore_options.go
pkg/bindings is considered stable. We cannot make changes that would
break any users. If someone uses this field their code would fail to
compile. Since the fix is obviously correct we will keep it but also
add the old field back in to keep compatibility with old code.
When both fields are set ImportArchive is preferred over ImportAchive.
Fixes changes from commit 217197340c8f
> fix breaking change in pkg/bindings

- cmd/podman/system/version.go
When podman is build without git commit information it will print a
empty newline instead. This is undesirable and a regression introduced
in commit 7d22cc88ef38.
To test build podman with `go build -mod=vendor -o bin/podman ./cmd/podman`
and check the output of bin/podman version with and without this commit.
> fix empty newline in version output

- docs/source/markdown/podman-network-create.1.md
This option is required with netavark, else you get:
Error: macvlan driver needs at least one subnet specified, DHCP is not supported with netavark
> [CI:DOCS]: Mention netavark limitations for macvlan/ipvlan drivers

- libpod/runtime.go
- test/apiv2/20-containers.at
- test/apiv2/test-apiv2
- test/e2e/systemd_activate_test.go
- test/utils/utils.go
* On SIGTERM, podman service will return exit code 0. SIGKILL will return exit code 1. This better matches expected behavior from `systemctl stop podman.service`
* Add e2e test to cover case above plus ensuring containers are still running after podman.service is stopped via `systemctl stop podman.service`
See https://bugzilla.redhat.com/show_bug.cgi?id=2052697
> Exit code change BZ #2052697

- pkg/domain/infra/abi/play.go
This commit set the containers RawImageName to default image name
specified in Pod YAML, so the containers could be used via autoupdate
feature, which needs the RawImageName to be set.
Currently RawImageName is set only for the create/run/clone podman
commands.
Previously if `auto-update` command was executed on containers created by `podman play kube` we got ouput:
```yaml
$ podman auto-update --dry-run
UNIT                     CONTAINER                       IMAGE                                 POLICY      UPDATED
Error: registry auto-updating container "7f519304b0081d142b8f1802a50ed0ce7832bcc6862b44e12bd9510120b93c41": raw-image name is empty
```
> Set rawimage for containers created via play kube

- pkg/specgen/generate/pod_create.go
- test/system/010-images.bats
- test/system/070-build.bats
- test/system/200-pod.bats
- test/system/helpers.bash
Make sure to ignore local {container,docker}ignore files when building a
local pause image.  Otherwise, we may mistakenly not be able to copy
catatonit into the build container.
Fixes: #13529
> podman create: building local pause image: do not read ignore files

- .cirrus.yml
- Makefile
Github no longer supports the unauthenticated git protocol, so switch
to using https instead.
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> [v4.0-rhel] Backport: Fix windows win-sshproxy build

- libpod/oci_conmon_linux.go
Inside the podman machine vm we always remove the hostip from the port
mapping because this should only be used on the actual host. Otherwise
you run into issues when we would bind 127.0.0.1 or try to bind a
host address that is not available in the VM.
This was already done for cni/netavark ports and slirp4netns but not for
the port bindings inside libpod which are only used as root.
[NO NEW TESTS NEEDED] We still do not have machine tests!
Fixes #13543
> podman machine: remove hostip from port

- cmd/podman/machine/start.go
- pkg/machine/qemu/machine.go
Fixes #13510
Machine instances created on podman 3 will be incompatible with podman current podman remote.
Let them run in a reduced mode and warn there will be problems and should be recreated. 
Output:
```
Starting machine "podman-machine-default"
ERRO[0000] machine "podman-machine-default" is incompatible with this release of podman and needs to be recreated, starting for recovery only 
INFO[0000] waiting for clients...                       
INFO[0000] new connection from  to /var/folders/w6/95wf1cp50bz9rdm74r_pdyw40000gs/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
!!! ACTION REQUIRED: INCOMPATIBLE MACHINE !!!
This machine was created by an older podman release that is incompatible
with this release of podman. It has been started in a limited operational
mode to …
```
> Tolerate old machine images, but warn they should be recreated

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
We already link to ginkgo sources, now add links to bats.
Ugly, because we need to hardcode containers/podman (git
repo) and test/system (test file path): those can't be
determined from the log results like they can in ginkgo.
> logformatter: link to bats sources on error

- Makefile
Github no longer supports the unauthenticated git protocol, so switch
to using https instead.
https://github.blog/2021-09-01-improving-git-protocol-security-github/
> [v4.0] Backport: Fix windows win-sshproxy build

- test/e2e/network_create_test.go
We need to use different ipv6 subnets for the tests since they can
collide otherwise when the tests are run in parallel.
In the future we should rethink hardcoding subnets for ipv4/ipv6. This
will make it impossible to run these tests if the subnet is already used
on the host.
Example log: https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5711403297275904/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-network-create-with-multiple-subnets-dual-stack-with-gateway-and-range--1
> fix dual stack network e2e flake

- test/compose/slirp4netns_opts/tests.sh
Reading from the nc socket is flaky because docker-compose only starts
the containers. We cannot know at this point if the container did already
send the message. Give the container 5 seconds time to send the message
to prevent flakes.
This happened rarely with compose v1 but it looks like it will happen a
lot more with compose v2.
Example failure log:
https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6567556239589376/html/compose_v2-podman-fedora-35-rootless-host.log.html
> fix compose test flake

- cmd/podman/machine/rm.go
- cmd/podman/machine/start.go
- docs/source/markdown/podman-machine-rm.1.md
- pkg/machine/config.go
- pkg/machine/ignition.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/qemu/options_darwin_arm64.go
This backports the incompatible machine handling PR and 4 other dependent PRs (list below)
NOTE: That this treats all machines created by podman versions older than 4.0.2 + brew as incompatible and must be recreated (Not just 3.x).  Since 4.0.0 and 4.0.1 were not released on MacOS, in practice this should not be observed. This is also technically the most correct since #13409 changes the uid of the machine uid to match the host user's uid, impacting compatibility of future 4.x releases that expect this to be the case (e.g. volume mounts using a 4.0.1 created machine won't match)
#13523 - Tolerate old machine (Fixes #13510)
#13562 - Fix type-o and cleanup doc punctuation (requested through review)
#13466 - machine rm -f (Fixes #13448)
#13465 - Improve install message (Fixes #13456)
#13409 …
> [v4.0] Backport handling of incompatible machines

- cmd/podman/machine/rm.go
- docs/source/markdown/podman-machine-rm.1.md
Minor cleanup that came out of a backport review:  
https://github.com/containers/podman/pull/13560#discussion_r830373870
> Fix type-o and cleanup doc punctuation

- docs/source/markdown/podman-system-service.1.md
There was a small typo in documentation, `--security-opt label=disable` was written as `--security-opt label:disable` instead.
Fixes https://github.com/containers/podman/issues/13526
> [CI:DOCS] Fix inconsistency in documentation

- cmd/podman/images/rm.go
- docs/source/markdown/podman-rmi.1.md
- pkg/api/handlers/libpod/images.go
- pkg/api/server/register_images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_remove_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/system/010-images.bats
Add an `--ignore` flag to `podman image rm` to instruct ignoring image
if a specified image does not exist and to not throw an error.  Other
commands (e.g., `podman container rm`) already support this flag.
Such an `--ignore` flag can come in handy in clean-up scripcts such as
the teardown phases in the Podman tests.
> podman rmi --ignore

- .golangci.yml
- Makefile
- cmd/podman/containers/start.go
- libpod/oci_conmon_linux.go
- pkg/machine/qemu/machine.go
* supports Go 1.18
* disable a number of new linters
* fix minor stylecheck issues
@containers/podman-maintainers @cevich
> bump golangci-lint to v1.45.0

- test/system/200-pod.bats
One of the pod tests was leaving a stray image behind,
causing scary red warnings in CI logs. Clean that up.
Also, now that #13541 has merged, use 'rmi --ignore' instead of
ignoring exit status from rmi
> pod system tests: clean up stray image

- libpod/container_internal.go
drop a warning for runc not supporting cgroup v2 on Fedora 31.
> libpod: drop warning for Fedora 31

- libpod/container_internal.go
- test/e2e/healthcheck_run_test.go
Containers started with `--no-healthcheck` are configured to contain no
health-check and test configured as `NONE`. Podman shows wrong status as
such use cases.
Following commit fixes the faulty behavior of stauts field for
containers started with `--no-healthcheck`
Closes: https://github.com/containers/podman/issues/13578
> healthcheck: stop showing wrong status when `--no-healthcheck` is set

- libpod/runtime_pod_linux.go
do not print a warning on cgroup removal if it doesn't exist.
Closes: https://github.com/containers/podman/issues/13382
> libpod: drop warning if cgroup doesn't exist

- hack/make-and-check-size
Add a CI check to prevent unwanted bloat in binary images,
by building a baseline (pre-PR) binary then comparing file
sizes post-PR.
We piggyback onto the existing 'Build Each Commit' CI check
because it gives us an easy way to run 'make' against the
parent commit.
This is part 1 of 2: adding the script, not the Makefile rule.
We can't add the Makefile rule now because the script it would
invoke does not exist in the parent commit.
> Binary growth check, part 1 of 2

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
ginkgo netavark logs (and, to a lesser extent, cni logs)
are unreadable because the hide-boring-opts code did not
know about --network-backend. Now it does.
Manually filtered an existing netavark log to confirm there
are no other new options we should know about.
> Fix unreadable netavark logs

- test/compose/slirp4netns_opts/tests.sh
We cannot use local var outside of a function. We have to use a global
one.
Log: https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5970023511490560/html/compose_v2-podman-fedora-35-root-host.log.html
> fix compose test error in retry logic

- docs/source/markdown/podman-build.1.md
The documentation files for `Containerfile` and `containerignore` have been moved from the `buildah` repository to the `common` repository.
ref: https://github.com/containers/buildah/commit/488e8654ea
> [CI:DOCS] docs: Fix links to Containerfile and containerignore

- contrib/msi/podman.wxs
Fixes duplicate installer entries after multiple installs
Observed in #13303
> Add Windows installer support for upgrades

- cmd/podman/images/import.go
- docs/source/markdown/podman-import.1.md
- pkg/api/handlers/libpod/images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_import_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/import_test.go
Allows users to set `--os` , `--arch` and `--variant` of the image
created from the custom import.
Following is useful when user is already aware of the values which are
correct for the rootfs which is being imported
Closes: https://github.com/containers/podman/issues/13291
> import: allow users to set `--os`, `--arch` and `--variant` of image imports

- .cirrus.yml
- contrib/cirrus/cirrus_yaml_test.py
The 'Total Success' task only ever executes when all dependencies are
successful.  Since other task names can vary across different OS releases,
their artifact URLs will be inconsistent over time.  When a non
`[CI:DOCS]` build is successful, gather all binary/release artifacts
in a new task which depends on 'Total Success'.  This will provide a
uniform name and URL for downstream users.  For example:
https://api.cirrus-ci.com/v1/artifact/github/containers/podman/artifacts/binary.zip
or
https://api.cirrus-ci.com/v1/artifact/github/containers/podman/artifacts/binary/ ***FILENAME***
Where ***FILENAME*** is one of:
* `podman`
* `podman-remote`
* `rootlessport`
* `podman-release-386.tar.gz`
* `podman-release-amd64.tar.gz`
* `podman-release-arm64.tar.gz`
* `podman-release-arm.tar.gz`
* …
> [CI:BUILD] Cirrus: Publish binary artifacts on success

- libpod/container_exec.go
Every exec session run attached will, on exit, do two things: it will signal the associated `podman exec` that it is finished (to allow Podman to collect the exit code and exit), and spawn a cleanup process to clean up the exec session (in case the `podman exec` process died, we still need to clean up). If an exec session is created that exits almost instantly, but generates a large amount of output (e.g. prints thousands of lines), the cleanup process can potentially execute before `podman exec` has a chance to read the exit code, resulting in errors. Handle this by detecting if the cleanup process has already removed the exec session before handling the error from reading the exec exit code.
[NO NEW TESTS NEEDED] I have no idea how to test this in CI.
Fixes #13227
> Fix a potential race around the exec cleanup process

- pkg/machine/qemu/machine.go
When starting a VM that has been configured with volume mounts, the podman client attempts to connect via
TCP to localhost, which runs gvproxy to proxy an ephemeral port to the VM's ssh port.  Previously, gvproxy
was listening on all interfaces and IP addresses, but this behavior has changed to listening only on the
IPv4 loopback address.
Without this change, if a newer build of gvproxy is used, a podman machine configured with volume mounts
will hang forever after "podman machine start" with "Waiting for VM ...".
Signed-off-by: Burt Holzman <burt@fnal.gov>
> Explicitly use IPv4 to check if podman-machine VM is listening

- libpod/define/containerstate.go
- libpod/pod.go
- libpod/stats.go
- pkg/api/handlers/compat/containers_stats.go
- pkg/domain/infra/abi/containers.go
When you run podman stats, the first interval always shows the wrong cpu
usage. To calculate cpu percentage we get the cpu time from the cgroup
and compare this against the system time between two stats. Since the
first time we do not have a previous stats an empty struct is used
instead. Thus we do not use the actual running time of the container but
the current unix timestamp (time since Jan 1 1970).
To fix this we make sure that the previous stats time is set to the
container start time, when it is empty.
[NO NEW TESTS NEEDED] No idea how I could create a test which would have
a predictable cpu usage.
See the linked bugzilla for a reproducer.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2066145
> podman stats: calc CPU percentage correctly

- docs/source/markdown/podman-machine-set.1.md
It is not quite clear what the difference between `podman machine set
--rootful` and `podman system connection default` is.
Add a small note with the difference, the --rootful option will also
affect the socket forwarding.
Fixes #13515
> [CI:DOCS] podman machine set: clarify --rootful option

- podman.spec.rpkg
podman-remote is considered stable and follows the same semver as
podman.
Fixes a question on the podman mailing list.
https://lists.podman.io/archives/list/podman@lists.podman.io/thread/2DVCU5Z54U4PI5ROTBQXHDBLQSAXAHFU/
> [CI:DOCS] Remove experimental warning from podman-remote rpm

- cmd/podman/common/create.go
- docs/source/markdown/podman-container-clone.1.md
- pkg/domain/infra/abi/containers.go
- pkg/specgen/generate/container.go
- test/e2e/container_clone_test.go
Closes: https://github.com/containers/podman/issues/3979
> container: allow clone to an existing pod

- pkg/machine/qemu/machine.go
We store the full path to qemu in the machine config. When the path
changes on the host the machine can longer be started. To fix it we get
the path again when we fail to start the machine due the missing binary.
We want to store and use the full path first because otherwise existing
machines can break when the qemu version changed.
[NO TESTS NEEDED] We still have no machine tests.
Fixes https://github.com/containers/podman/issues/13394
> podman machine start: lookup qemu path again if not found

- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/manifests.go
* Branch forced 4.0 only endpoints, which broke bindings
* Fix manifest endpoints
* Fix lint error, in new code
> Fix manifest 4.0 endpoints

- go.mod
- go.sum
- test/e2e/login_logout_test.go
- vendor/github.com/containers/common/pkg/auth/auth.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Update the login tests to reflect the latest changes to allow http{s}
prefixes (again) to address bugzilla.redhat.com/show_bug.cgi?id=2062072.
Backport of commit 57cdc21b0057.
> [v4.0] vendor c/common@v0.47.5

- Makefile
- contrib/cirrus/runner.sh
- hack/make-and-check-size
Add a CI check to prevent unwanted bloat in binary images,
by building a baseline (pre-PR) binary then comparing file
sizes post-PR.
Part 1 (#13518) added a new script that runs multiple 'make's,
comparing image sizes against an original, and failing loudly
if growth is too big. An override mechanism is defined.
This is part 2 of 2: adding the CI rule. We couldn't do that
in part 1, because the rule would call a script that didn't
exist in the pre-PR commit.
> Binary growth check, part 2 of 2

- libpod/oci_conmon_linux.go
Issue #10927 reports `container create failed (no logs from conmon): EOF`
errors. Since we do not know the root cause it would be helpful to try
to get as much info as possible out of the error.
(buffer).ReadBytes() will return the bytes read even when an error
occurs. So when we get an EOF we could still have some valuable
information in the buffer. Lets try to unmarshal them and if this fails
we add the bytes to the error message.
This does not fix the issue but it might help us getting a better error.
> readConmonPipeData: try to improve error

- libpod/networking_machine.go
When a user has a http proxy configured the VM will use it. However
since gvproxy can only be reached internally from within the VM the port
forwarding HTTP API call should not be redirected to the proxy.
Fixes #13628
> podman machine: fix port forwarding with proxy

- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container_internal_linux.go
- test/system/250-systemd.bats
systemd expects the container_uuid environment variable be set
when it is running in a container.
Fixes: https://github.com/containers/podman/issues/13187
> When running systemd in a container set container_uuid

- contrib/msi/podman.wxs
Fixes duplicate installer entries after multiple installs
Backport of #13567
> [v4.0] Add Windows installer support for upgrades

- cmd/podman/images/import.go
- cmd/podman/images/load.go
- cmd/podman/images/scp.go
- cmd/podman/inspect/inspect.go
- cmd/podman/pods/create.go
- cmd/podman/secrets/inspect.go
- cmd/podman/system/dial_stdio.go
- cmd/podman/utils/error.go
- libpod/networking_linux.go
- libpod/networking_slirp4netns.go
- pkg/bindings/containers/attach.go
- pkg/bindings/containers/logs.go
- pkg/bindings/errors.go
- pkg/bindings/images/build.go
- pkg/domain/infra/abi/images_test.go
- pkg/machine/pull.go
- pkg/machine/qemu/machine.go
- pkg/rootless/rootless.go
- pkg/rootless/rootless_linux.go
- pkg/specgen/generate/kube/volume.go
- pkg/specgen/generate/storage.go
- pkg/specgenutil/specgen.go
- pkg/systemd/generate/pods.go
- pkg/util/utils.go
- test/e2e/run_test.go
When podman gets an error it prints out "Error: " before
printing the error string.  If the error message starts with
error, we end up with
Error: error ...
This PR Removes all of these stutters.
logrus.Error() also prints out that this is an error, so no need for the
error stutter.
> Remove error stutter

- contrib/cirrus/setup_environment.sh
- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_add_options.go
- pkg/bindings/manifests/types_modify_options.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
Signed-off-by: Jason Montleon <jmontleo@redhat.com>
> Resolves #13629 Add RegistryAuthHeader to manifest push

- docs/source/markdown/podman-images.1.md
This PR adds the missing documentation for image filtering, while also adding option to negate which comes from issue https://github.com/containers/podman/issues/13270 with PR https://github.com/containers/common/pull/971.
Signed-off-by: rvandernoort <s.r.vandernoort@student.tudelft.nl>
> [CI:DOCS]: Update docs for image filters

- go.mod
- go.sum
- pkg/namespaces/namespaces.go
- pkg/specgen/container_validate.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/namespaces.go
- vendor/github.com/containers/common/libimage/filters.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/pkg/seccomp/default_linux.go
- vendor/github.com/containers/common/pkg/seccomp/seccomp.json
- vendor/modules.txt
Vendor common to introduce the filters from PR https://github.com/containers/common/pull/971 such that we can mege the docs update in PR https://github.com/containers/podman/pull/13607 originally from issue #13270.
Signed-off-by: rvandernoort <s.r.vandernoort@student.tudelft.nl>
> Vendor c/common for filters

- docs/source/markdown/podman-generate-systemd.1.md
As currently written, it isn't clear that loginctl enable-linger <username> also starts user services at boot.
here is a quote from the enable-linger command in the systemd docs:
"If enabled for a specific user, a user manager is spawned for the user at boot and kept around after logouts."
https://www.freedesktop.org/software/systemd/man/loginctl.html
Signed-off-by: Adam Maryniuk <adamaze@gmail.com>
> [CI:DOCS] clarifying "loginctl enable-linger" section in doc

- libpod/container_internal.go
- libpod/volume.go
- pkg/bindings/images/build.go
- pkg/domain/infra/abi/system.go
- pkg/machine/ignition.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
- pkg/specgen/generate/config_linux.go
- pkg/util/utils.go
- pkg/util/utils_linux.go
- test/e2e/pod_rm_test.go
WalkDir should be faster the Walk, since we often do
not need to stat files.
[NO NEW TESTS NEEDED] Existing tests should find errors.
> Switch all calls to filepath.Walk to filepath.WalkDir

- libpod/events/config.go
- libpod/events/events.go
- libpod/runtime_ctr.go
- test/e2e/rename_test.go
Following PR ensures that podman generates a valid event on `podman
container rename` where event specifies that it is a rename event and
container name switched to the latest name.
Closes: https://github.com/containers/podman/issues/13670
> libpod, event: generate a valid event on container `rename` operation

- test/e2e/manifest_test.go
Signed-off-by: John Matthews <jwmatthews@gmail.com>
Fixes #13650
> Fixes errors from 'manifest push' being dropped in remote case

- libpod/networking_slirp4netns.go
I do not see why we should only log an error. If slirp4netns is
requested but not installed we should error.
> network setup: fail if slirp4netns is not installed

- .github/dependabot.yml
- Updated dependabot to get updates for GitHub actions.
GitHub sends Dependabot alerts when we detect vulnerabilities affecting your repository
as well as when there are new updates to the dependency.
https://docs.github.com/en/code-security/dependabot/dependabot-alerts/about-dependabot-alerts
A vulnerability is a problem in a project's code that could be exploited to damage the confidentiality, integrity, or availability of the project or other projects that use its code. Vulnerabilities vary in type, severity, and method of attack.
When your code depends on a package that has a security vulnerability, this vulnerable dependency can cause a range of problems for your project or the people who use it.
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> Updated dependabot to GitHub actions

- .github/workflows/check_cirrus_cron.yml
- .github/workflows/issue-labeler.yml
- .github/workflows/multi-arch-build.yaml
- .github/workflows/pr-title.yml
- .github/workflows/stale.yml
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also dependabot supports upgrades based on SHA.
> [CI:DOCS] Pin actions to a full length commit SHA

- docs/source/markdown/podman-image-unmount.1.md
- docs/source/markdown/podman-network-prune.1.md
- docs/source/markdown/podman-pod-pause.1.md
- docs/source/markdown/podman-unmount.1.md
- docs/source/markdown/podman-unpause.1.md
- docs/source/markdown/podman-volume-ls.1.md
- docs/source/markdown/podman-volume-unmount.1.md
This commit adjusts example sections across several man pages
to the format seen in other pages.
Signed-off-by: Patrycja Guzik <patrycja.k.guzik@gmail.com>
> [CI:DOCS]  Unify examples section across several man pages

- hack/make-and-check-size
This won't actually be seen except by someone who takes the
time to clickety-click into Cirrus - but that's better than
not showing it at all.
> size-check: display binary size and growth

- libpod/oci_conmon_exec_linux.go
- pkg/specgen/generate/security.go
- test/e2e/run_test.go
The kernel never sets the inheritable capabilities for a process, they
are only set by userspace. Emulate the same behavior.
Closes: CVE-2022-27649
Signed-off-by: Giuseppe Scrivano [gscrivan@redhat.com](mailto:gscrivan@redhat.com)
(cherry picked from commit https://github.com/containers/podman/commit/aafa80918a245edcbdaceb1191d749570f1872d0)
> [4.0-rhel] do not set the inheritable capabilities

- libpod/define/version.go
- pkg/bindings/system/system.go
- test/e2e/version_test.go
Signed-off-by: John Matthews <jwmatthews@gmail.com>
Fixes #13690 
As requested in #13690 this exposes an 'Os' field in version output to aid existing scripts that rely on docker's behavior of `docker version -f {{.Server.Os}} `.   I added 'Os' to both the Client and Server output assuming it'd be desired, but #13690 only asked for 'Server'
> Add 'Os' to be queried via 'version' output

- libpod/oci_conmon_exec_linux.go
- pkg/specgen/generate/security.go
- test/e2e/run_test.go
The kernel never sets the inheritable capabilities for a process, they
are only set by userspace.  Emulate the same behavior.
Closes: CVE-2022-27649
(cherry picked from commit aafa80918a245edcbdaceb1191d749570f1872d0)
> [4.0] do not set the inheritable capabilities

- contrib/systemd/system/podman.service.in
enable cgroup delegation when running as a systemd service so all the
available controllers are correctly detected.
Closes: https://github.com/containers/podman/issues/13710
> systemd: enable all cgroups when running as a service

- libpod/networking_slirp4netns.go
- test/system/500-networking.bats
The slirp4netns port forwarder was not updated to make use of the new
port format. This results in a problem when port ranges are used since
it does not read the range field from the port.
Update the logic to iterate through all ports with the range and
protocols. Also added a system test for port ranges with slirp4netns,
rootlesskit and the bridge network mode.
Fixes #13643
> fix slirp4netns port forwarding with ranges

- .cirrus.yml
- test/upgrade/test-upgrade.bats
- removed: v1.9.0, v2.0.6
+ added:   v3.4.0
(Cannot add v4 because there's no such image on quay. As soon
as one appears, we should add it.)
> Upgrade tests: reexamine cross-testing matrix

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
`podman play kube` creates a new volume for configmap, if same configmap
is applied again volume can be re-used, there is no need to remove and
re-create the volume again
Closes: https://github.com/containers/podman/issues/13715
> kube: `configmap` volume should be reused if already exists

- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/kube.go
- libpod/pod_api.go
- pkg/domain/infra/abi/containers.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/oci.go
- pkg/specgenutil/volumes.go
- test/e2e/pod_create_test.go
the infra Inherit function was not properly passing pod volume information to new containers. alter the inherit function and struct to use the new `ConfigToSpec` function used in clone pick and choose the proper entities from a temp spec and validate them on the spegen side rather than passing directly to a config
resolves #13548
> fix pod volume passing and alter infra inheritance

- pkg/bindings/images/build.go
- test/e2e/build_test.go
- test/e2e/common_test.go
- test/e2e/libpod_suite_remote_test.go
- test/utils/utils.go
Ensure a directory added to .containerignore on client is not included
in tar sent to remote podman API service
* Clean up podman invocations to not include duplicate --remote and
--url flags
* Use pkill vs. pgrep when cleaning up podman API service in tests
* Add exit code when logging error when testing
Closes #13535
> Add build test for .containerignore tar file

- contrib/fedora-minimal/Dockerfile
- contrib/fedora-minimal/README.md
- libpod/oci_conmon_linux.go
- pkg/specgen/generate/security.go
- test/e2e/config.go
- test/e2e/exec_test.go
- test/e2e/images_test.go
- test/e2e/run_test.go
The kernel never sets the inheritable capabilities for a process, they
are only set by userspace.  Emulate the same behavior.
Closes: CVE-2022-27649
(cherry picked from commit aafa80918a245edcbdaceb1191d749570f1872d0)
> [v3.0.1-rhel] do not set the inheritable capabilities

- pkg/specgenutil/volumes.go
- test/e2e/run_volume_test.go
This fixes #13756.
All the mechanics to create anonymous volumes is already present, but
there's still a validation preventing that path from being taken.  We
remove the validation, which allows the volume to be created
successfully.
Signed-off-by: Andrew Aylett <andrew@aylett.co.uk>
> Allow creating anonymous volumes with --mount

- .github/workflows/check_cirrus_cron.yml
- .github/workflows/issue-labeler.yml
- .github/workflows/pr-title.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> [CI:DOCS] Set permissions for GitHub actions

- cmd/podman/common/create.go
- cmd/podman/common/create_opts.go
- cmd/podman/containers/create.go
- pkg/domain/entities/pods.go
- pkg/specgenutil/specgen.go
- test/e2e/run_test.go
- test/system/030-run.bats
do not force a value of OOMScoreAdj=0 if it is wasn't specified by the
user.
Closes: https://github.com/containers/podman/issues/13731
> specgen: do not set OOMScoreAdj by default

- cmd/podman/containers/logs.go
- cmd/podman/pods/logs.go
- docs/source/markdown/podman-logs.1.md
- docs/source/markdown/podman-pod-logs.1.md
- libpod/container_log.go
- libpod/container_log_linux.go
- libpod/container_log_unsupported.go
- libpod/logs/log.go
- libpod/oci_conmon_linux.go
- pkg/domain/entities/containers.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/containers.go
- test/e2e/logs_test.go
Created an option to colourise ```pod logs``` with an option ```--color```.  You can recreate with the following steps:
1. Create a pod with containers
```bash
bin/podman pod create --name=pod_testlogs; bin/podman run --name=testlogs_loop1_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop1: $i"; sleep 1; done'; bin/podman run --name=testlogs_loop2_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop2: $i"; sleep 3; done';
```
2. Logs with colour:
```bash
bin/podman pod logs --tail=10 -f --color pod_testlogs
```
3. Kill all pods and remove containers:
```bash
bin/podman kill --all; bin/podman rm --all; bin/podman pod rm --all
```
Closes #13266
> pod logs enhancements: option to color logs

- test/apiv2/35-networks.at
Since netavark does not support dhcp yet we have to create a macvlan
network with a static subnet. Since we do not use the network to run
containers the actual subnet does not matter.
> test/apiv2: support netavark

- docs/source/markdown/podman-init.1.md
- docs/source/markdown/podman-kill.1.md
- docs/source/markdown/podman-pod-kill.1.md
This commit adjusts example sections across several man pages to the format seen in other pages.
Follow up PR #13682
> [CI:DOCS] Unify examples section across several man pages: init/kill

- docs/source/markdown/podman-pod-rm.1.md
- docs/source/markdown/podman-pod-start.1.md
- docs/source/markdown/podman-pod-unpause.1.md
This commit adjusts example sections across several man pages to the format seen in other pages.
Follow up PR #13682 and #13771
> [CI:DOCS] Unify examples section across several man pages: pod rm/start/unpause

- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
commit f6562e8572160d2d7034ad29b102ce9b6e21a37e didn't properly
backport this feature.
> [v1.6.4-rhel] spec: do not set inheritable caps for --privileged

- cmd/podman/images/list.go
- docs/source/markdown/podman-images.1.md
- pkg/api/handlers/compat/images.go
- pkg/api/server/register_images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_list_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images_list.go
- pkg/domain/infra/tunnel/images.go
- test/system/010-images.bats
Add a --size option to podman images to allow for disabling computing
the size of listed images.  If listing images is critical to
performance, user may chose to turn off size computation to speed things
up.
Context: #13755
> images --size

- libpod/container_inspect.go
- libpod/define/container_inspect.go
- test/e2e/create_test.go
- test/e2e/pod_create_test.go
- test/system/200-pod.bats
Convert container entrypoint from string to an array inorder to make
sure there is parity between `podman inspect <ctr>` and `docker inspect <ctr>`
Closes: https://github.com/containers/podman/issues/13803
> container,inspect: convert `Entrypoint` to an array instead of a string

- cmd/podman/common/completion.go
- cmd/podman/networks/create.go
- docs/source/markdown/podman-network-create.1.md
- test/e2e/run_networking_test.go
Add a new flag to set the ipam-driver. Also adds a new ipam driver none
mode which only creates interfaces but does not assign addresses.
Fixes https://github.com/containers/podman/issues/13521
> network create: add support for ipam-driver none

- test/system/040-ps.bats
Buildah issue 3544 has been fixed and vendored into podman.
We can reenable a long-skipped test.
> System tests: reenable ps --external test

- pkg/bindings/README.md
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
This is necessary until https://github.com/containers/podman/issues/6866 is (really) fixed.
> [CI:DOCS] pkg/bindings: document requirements for use

- docs/source/markdown/podman-run.1.md
PR after reading
https://github.com/containers/podman/discussions/12848
* Remove the statement that rootless --userns=auto does not work.
* Mention that --userns=keep-id consumes all subuids and subgids.
> [CI:DOCS] Rewrite rootless --userns=auto docs

- .cirrus.yml
Every weekday when the `check_cirrus_cron` github-actions
workflow runs. It checks the status of all cirrus-cron jobs.  If a build
is found with a 'FAILED' status, it triggers an alert e-mail to be sent.
However, the `test_image_build` is marked as a manually-triggered,
resulting in a perpetual status of 'EXECUTING', even if there were
failures.  Fix this by only allowing the problematic task to run in pull
requests without the `[CI:DOCS]` magic keyword.
> [CI:BUILD] Cirrus: Fix unsupported cirrus-cron build status

- pkg/machine/qemu/machine.go
Certain paths like `../containers/podman/machine/my-test/podman.sock`
do not exist when machine is not started, so removing a machine before
starting it will result in ENOENT for such paths, so ignore `ENOENT` for such cases.
Reproducer:
```console
podman machine init
podman machine rm
```
Closes: https://github.com/containers/podman/issues/13834
This does not adds a new feature.
> machine,rm: Ignore `ENOENT` while cleaning machine paths

- libpod/runtime_ctr.go
- pkg/specgenutil/volumes.go
- pkg/util/mountOpts.go
- test/e2e/run_volume_test.go
`--mount` should allow setting driver specific options using
`volume-opt` when `type=volume` is set.
This ensures parity with docker.
Closes: https://github.com/containers/podman/issues/13387
> run, mount: allow setting driver specific option using `volume-opt=`

- cmd/podman/common/create_opts.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/specgen/specgen.go
- test/apiv2/20-containers.at
- test/apiv2/containers.no_hosts.conf
The API endpoints should properly honour the `no_hosts=true` setting in
containers.conf.
Fixes #13719
> API: use no_hosts from containers.conf

- docs/source/markdown/podman-generate-systemd.1.md
- pkg/systemd/generate/containers.go
- pkg/systemd/generate/containers_test.go
Fixes: #13337
I added newline only on options IE Begin with "-"
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
Replaces: https://github.com/containers/podman/pull/13680
> Pretty print systemd services file

- test/system/045-start.bats
Bad code got committed by accident: test description on run_podman
line, not test line.
Did not seem to affect tests, but fix it anyway.
> System tests: fix oops in start --filter tests

- RELEASE_NOTES.md
- libpod/oci_conmon_exec_linux.go
- pkg/specgen/generate/security.go
- test/e2e/run_test.go
- version/version.go
Addresses the recent CVE for distributions that cannot upgrade to Podman v4.0 (e.g. F35)
> Bump to v3.4.5

- go.mod
- go.sum
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
- vendor/modules.txt
This is intended to replace #13610 and skip the update to `v0.3.1` which had the following issues:
* an `init` function caused the executable size to grow without giving library clients the option to opt-out
* an misconfigured spec definition caused the internal validation (which should have been disabled) to fail.
> build(deps) bump github.com/container-orchestrated-devices/container-device-interface from 0.3.0 to 0.3.2

- README.md
- RELEASE_NOTES.md
- version/version.go
3.4.5 wasn't rebased fully so we missed a minor security patch. Cut another release to fix.
> [CI:DOCS] Bump to v3.4.6

- cmd/podman/common/create_opts.go
- test/apiv2/20-containers.at
For better docker compatibility we should use the bridge network mode as
default for rootless. This was already done previously but commit
535818414c2a introduced this regression in v4.0.
Since the apiv2 test are only run rootful we cannot catch this problem
in CI.
> compat api: use network mode bridge as default

- pkg/api/handlers/compat/containers_attach.go
There's a potential race condition where we attempt to attach to a container immediately after it's been stopped, but before the cleanup process has run on it. The existing code doesn't allow an attach to containers in the Stopped state (cleanup process has not run) but does allow an attach to containers in the Exited state (cleanup process has run). This doesn't make very much sense and there's no technical reason to restrict attach to only Exited containers, so allow attaching to Stopped containers.
[NO NEW TESTS NEEDED] Testing this is very racy - we need to get in before the cleanup process runs, which isn't really deterministic when we're invoked from a script - like the CI tests.
> Allow HTTP attach to stopped containers

- cmd/podman/images/list.go
- docs/source/markdown/podman-images.1.md
- pkg/api/handlers/compat/images.go
- pkg/api/server/register_images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_list_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images_list.go
- pkg/domain/infra/tunnel/images.go
- test/system/010-images.bats
This reverts commit e133a06d2f4a3e94bfbd60b647046f2f515c9c24.
@nalind found a proper fix in c/storage [1] to address the performance
issue.  So we really don't need the flag anymore.  Note the flag has
never made it into any release.
[1] https://github.com/containers/storage/commit/d76b3606fc9ca975bf436379f91105f0fac1555f
> Revert "images --size"

- libpod/container_log_linux.go
- test/system/035-logs.bats
--tail=1 is not working f you restart a container with journald logging.
We see the exit status and then call into the logging a second time
causing all of the logs to print.
Removing the tail log on exited seems to fix the problem.
Fixes: https://github.com/containers/podman/issues/13098
> Fix --tail log on restart problem

- test/system/015-help.bats
Current error messages are really awful, and cause great
suffering every time someone adds a new subcommand. Let's
see if these are better.
> System tests: Usage checks: better error messages

- cmd/podman/common/create.go
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container_config.go
- libpod/container_internal_linux.go
- libpod/options.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/run_passwd_test.go
It allows to customize the entry that is written to the `/etc/passwd`
file when --passwd is used.
Closes: https://github.com/containers/podman/issues/13185
> run, create: add --passwd-entry

- cmd/podman/common/create.go
- docs/source/markdown/podman-container-clone.1.md
- pkg/specgen/generate/container_create.go
- test/e2e/container_clone_test.go
`DefineCreateFlags` was excluding clone from using the memory-swappiness flag leading the value to be zero
when our deafult is -1. Rearrange the if/else to give clone these memory related options
resolves #13856
> Fix Memory Swappiness passing in Container Clone

- libpod/events.go
- libpod/events/config.go
- libpod/events/events.go
- libpod/events/logfile.go
- libpod/events/logfile_test.go
- test/system/090-events.bats
Add a new function to logfile.go for rotating and deleting
the events log file once the log file and its contents
exceed the maximum size limit.
Also add tests to verify log rotation for different
scenarios.
> Add log rotation based on log size

- cmd/podman/machine/init.go
- docs/source/markdown/podman-machine-init.1.md
By default, mount the user's homedir into the vm at the same location.
any volumes defined on the cli will then override the default mount.
Also, added --no-volumes to disable volume mounts alltogether.
> Mount $HOME:$HOME by default in podman machine init

- docs/source/markdown/podman-container-inspect.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/options.go
- libpod/runtime_ctr.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/generate/security.go
- pkg/specgenutil/specgen.go
- test/system/190-run-ipcns.bats
> Add support for ipc namespace modes "none, private, sharable"

- cmd/podman/machine/list.go
- docs/source/markdown/podman-machine-list.1.md
The podman machine ls command would benefit from a --quiet flag which
would only print the machine names without the extra information.  It
also implies --noheader as well.  This can be helpful for scripting with
the podman cli.
> Add --quiet to machine ls

- hack/xref-helpmsgs-manpages
Use quotes to indicate the command, and remove some duplication
> [CI:DOCS] manpage vs --help checker: better error messages

- pkg/api/handlers/libpod/containers_create.go
- pkg/specgenutil/specgen.go
- test/apiv2/python/rest_api/test_v2_0_0_container.py
In specgen, the CLI creation route uses the given memory limit to define the swap value (if not already specified). added a route to this piece of code from within the api handlers
resolves #13145
> Translate Memory Limit to Swap in API

- cmd/podman/common/completion.go
- docs/source/markdown/podman-events.1.md
> Add missing events to podman-events man page

- cmd/podman/registry/remote.go
- docs/source/markdown/podman.1.md
- test/system/001-basic.bats
Addresses #13393 and replaces #13357.  Many thanks to
@Romain-Geissler-1A for the initial submission and discussions.
> [v4.0] Option --url and --connection should imply --remote

- pkg/machine/wsl/machine.go
> Respect "Rootful" when starting WSL API Forwarding

- pkg/specgen/generate/container.go
- test/e2e/healthcheck_run_test.go
Set appropriate defaults for `--interval` when
processing a Healthcheck from ContainerImage and `HEALTHCHECK` is used from `Dockerfile`.
Closes: https://github.com/containers/podman/issues/13912
> healthcheck: set default healthcheck `Interval` if not specified in image

- Makefile
- test/e2e/benchmarks_test.go
- test/utils/utils.go
Add a proof of concept for benchmarking Podman.  The benchmarks are
implemented by means of the end-to-end test suite but hidden behind
a `benchmarks` build tag.  Running `make localbenchmarks` will run
`test/e2e` with the specific build tag and set ginkgo's "focus" to
the specific "Podman Benchmark Suite" to only run this spec and skip
all others.
ginkgo will print a report before terminating listing the CPU and memory
stats for each benchmark.  New benchmarks can easily be added via the
`newBenchmark` function that also supports adding an `init()` function
to each benchmark which allows for performing certain setups for the
specific benchmark.  For instance, benchmarking `podman start` requires
creating a container beforehand.
Podman may be called more than once in the main function of …
> benchmarking Podman: proof of concept

- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-play-kube.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/networking_slirp4netns.go
We already have ipv6 enabled as default via the containers.conf setting.
However the documentation did not reflect this. Also if no options were
set in contianers.conf it would have ipv6 disabled.
We can now remove the extra option from containers.conf.
Also fix another outdated option description for host.containers.internal
and add that the options can also be set in contianers.conf.
Fixes #13914
> slirp4netns: actually make ipv6 default

- test/e2e/common_test.go
Use of `$DEBUG` is highly likely to clash.  Fortunately this one is in
a very specific/special context, so a rename fix should be perfectly
adequate.
See also https://github.com/containers/automation/pull/96
and https://github.com/containers/podman/issues/13932
> Fix e2e tests referencing generic env. var.

- cmd/podman/containers/checkpoint.go
- cmd/podman/containers/restore.go
- docs/source/markdown/podman-container-checkpoint.1.md
- docs/source/markdown/podman-container-restore.1.md
- go.mod
- go.sum
- libpod/container_api.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/define/annotations.go
- pkg/api/handlers/libpod/containers.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_checkpoint_options.go
- pkg/checkpoint/checkpoint_restore.go
- pkg/checkpoint/crutils/checkpoint_restore_utils.go
- pkg/criu/criu.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/checkpoint_image_test.go
- vendor/github.com/checkpoint-restore/checkpointctl/lib/metadata.go
- vendor/modules.txt
This is an enhancement proposal for the checkpoint / restore feature of Podman that enables container migration across multiple systems with standard image distribution infrastructure.
A new option `--create-image <image>` has been added to the `podman container checkpoint` command. This option tells Podman to create a container image.  This is a standard image with a single layer, tar archive, that that contains all checkpoint files. This is similar to the current approach for container migration using `--export` / `--import`.
The checkpoint image can be pushed to a container registry and pulled on a different system.  It can also be exported locally with `podman image save` and inspected with `podman inspect`. Inspecting the image would display additional information (stored as …
> Add support for checkpoint image

- README.md
- RELEASE_NOTES.md
Also update README and ensure we point to v4.0.3 as the latest release, instead of v3.4.7 (which is newer chronologically but not by actual version).
> [CI:DOCS] Update release notes for v4.0.3 and v3.4.7

- contrib/cirrus/pr-should-include-tests
- contrib/cirrus/runner.sh
A common pattern is to submit PRs that update only tests or docs.
When the only changes are to test/e2e, there is no point in running
test/system, and vice versa.
When the only changes are to docs, there is no point in running either.
> Optimization: skip tests in some circumstances

- test/upgrade/test-upgrade.bats
On F36 / podman 4, at the time of this commit there is no
`/etc/containers/storage.conf` installed by default.  Since the
test volume-mounts this file into the container, it was failing.  Fix
this by using a conditional volume-mount based on the file existing (or
not).
> Fix upgrade tests assuming storage.conf exists

- hack/make-and-check-size
When going through the rebase+build loop, the repository state won't
match the exact branch or PR history.  This results in the `Building:
XYZSHA` indications being entirely useless.  Fix this by at least
including the title line of the commit being built.  This will allow a
human to make sense of any size-check failure WRT their view of history.
> Fix size-check to display more context

- test/e2e/common_test.go
- test/e2e/libpod_suite_remote_test.go
- test/utils/utils.go
When this option was added to the e2e tests, there was no CI Automation
support for running remote tests w/ netavark.  When added, many
e2e test errors/failures are generated due to this option not being
valid for the remote client.  Fix this in the tests by conditionally
adding the option if the test is running the remote client.
> Fix using --network-backend on podman-remote

- libpod/container_inspect.go
- libpod/define/container_inspect.go
- test/e2e/create_test.go
- test/e2e/pod_create_test.go
- test/system/200-pod.bats
It seems this breaks older version of `podman-remote` users hence it
looks like this patch would be a better candidate for podman `5.0`
Problem
* Client with `4.0` cannot interact with a server of `4.1`
Plan this patch for podman `5.0`
This reverts commit 0cebd158b6d8da1828b1255982e27fe9224310d0.
> Revert "container,inspect: convert Entrypoint to array instead of a string

- test/system/520-checkpoint.bats
When run on an F36 host using netavark/aardvark-dns, for whatever
underlying reason most checkpoint/restore tests are emitting an error
similar to:
`criu: Symbol `__rseq_offset' has different size in shared object,
consider re-linking`
This extraneous output is causing the basic checkpoint system test to
fail.  Since, all other testing of checkpoint/restore feature is
passing (also with the extraneous message) loosen the system test
sensitivity to match.
> Workaround criu re-linking output in system test

- .cirrus.yml
- contrib/cirrus/setup_environment.sh
Newer versions of git (like `2.35`) fail on certain operations (like
`rebase` and `am`) without a local identity.  Add a fake one from the
start, with a clearly identifiable test-value to avoid problems at
runtime.
**Note:** This has to be done twice to cover all tasks that need it.  I tried to avoid the duplication, but it wound up being more complex :confounded:
> Cirrus: Fix missing git-enforced runtime identity

- cmd/podman/containers/clone.go
- docs/source/markdown/podman-container-clone.1.md
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- test/e2e/container_clone_test.go
add the option -f to force remove the parent container if --destory is specified
resolves #13917
> podman container clone -f

- test/system/000-TEMPLATE
- test/system/001-basic.bats
- test/system/015-help.bats
- test/system/030-run.bats
- test/system/035-logs.bats
- test/system/040-ps.bats
- test/system/045-start.bats
- test/system/050-stop.bats
- test/system/065-cp.bats
- test/system/070-build.bats
- test/system/090-events.bats
- test/system/120-load.bats
- test/system/160-volumes.bats
- test/system/180-blkio.bats
- test/system/190-run-ipcns.bats
- test/system/200-pod.bats
- test/system/250-systemd.bats
- test/system/255-auto-update.bats
- test/system/400-unprivileged-access.bats
- test/system/410-selinux.bats
- test/system/450-interactive.bats
- test/system/500-networking.bats
- test/system/520-checkpoint.bats
- test/system/600-completion.bats
- test/system/750-trust.bats
- test/system/helpers.bash
Problem: the system test 'is()' checker was poorly thought out.
For example, there is no way to check for inequality or for
absence of a substring.
Solution, step 1: introduce new assert(), copied almost verbatim
from buildah, where it has been successful in addressing the
gaps in is().
The logical next step is to search the tests for 'die' and
for 'run', looking for negative assertions which we can
replace with assert(). There were a lot, and in the process
I found a number of ugly bugs in the tests themselves. I've
taken the liberty of fixing these.
Important note: at this time we have both assert() and is().
Replacing all instances of is() would be impossible to review.
> system tests: add assert(), and start using it

- cmd/podman/machine/init.go
- cmd/podman/machine/set.go
- contrib/cirrus/logformatter
- contrib/podmanimage/README.md
- contrib/remote/containers.conf
- docs/source/markdown/podman-build.1.md
- docs/source/markdown/podman-image-scp.1.md
- docs/source/markdown/podman-machine-init.1.md
- docs/source/markdown/podman-machine-set.1.md
- libpod/networking_slirp4netns.go
- pkg/bindings/README.md
- pkg/domain/infra/abi/images.go
- pkg/machine/config.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
- rootless.md
- test/e2e/exec_test.go
- test/e2e/mount_rootless_test.go
- test/e2e/network_test.go
- test/system/270-socket-activation.bats
- test/system/helpers.bash
We are inconsistent on the name, we should stick with rootfull.
[NO NEW TESTS NEEDED] Existing tests should handle this and no tests for
machines exists yet.
> Switch all rootful to rootfull

- pkg/specgenutil/volumes.go
- test/e2e/run_volume_test.go
Following commit ensures that csv escaping is supported while using
inline `--mount=type=......` flag with `podman run` by using
`encoding/csv` to parse options instead of performing a `split.String(`
by `comma`.
Closes: https://github.com/containers/podman/issues/13922
> specgen-volumes: parse `--mount` using csv-reader instead of split.

- cmd/podman/common/completion.go
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
- pkg/domain/infra/runtime_libpod.go
- pkg/namespaces/namespaces.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/namespaces.go
- pkg/util/utils.go
- test/e2e/run_userns_test.go
- test/e2e/toolbox_test.go
- test/system/030-run.bats
- test/system/065-cp.bats
- test/system/075-exec.bats
- test/system/160-volumes.bats
- test/system/170-run-userns.bats
- test/system/500-networking.bats
From a security point of view, it would be nice to be able to map a
rootless usernamespace that does not use your own UID within the
container.
This would add protection against a hostile process escapping the
container and reading content in your homedir.
> Add support for --userns=nomap

- docs/source/markdown/podman-build.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-play-kube.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/container_internal_linux_test.go
- libpod/networking_linux.go
- pkg/specgen/container_validate.go
- test/e2e/pod_infra_container_test.go
- test/e2e/run_dns_test.go
- test/e2e/run_networking_test.go
- test/system/030-run.bats
- test/system/200-pod.bats
- test/system/500-networking.bats
- vendor/github.com/containers/common/libnetwork/etchosts/hosts.go
- vendor/github.com/containers/common/libnetwork/etchosts/ip.go
- vendor/github.com/containers/common/libnetwork/etchosts/util.go
- vendor/modules.txt
Use the new logic from c/common to create the hosts file. This will help
to better align the hosts files between buildah and podman.
Also this fixes several bugs:
- remove host entries when container is stopped and has a netNsCtr
- add entries for containers in a pod
- do not duplicate entries in the hosts file
- use the correct slirp ip when an userns is used
Features:
- configure host.containers.internal entry in containers.conf
- configure base hosts file in containers.conf
Fixes https://github.com/containers/podman/issues/12003
Fixes https://github.com/containers/podman/issues/13224
libpod: fix c.Hostname() to respect the utsNsCtr
When we lookup the hostname for a given container we have to check if
the container is joined to another utsns and use this hostname then
instead.
This …
> use etchosts package from c/common

- Makefile
- contrib/cirrus/logformatter
- contrib/cirrus/runner.sh
- test/apiv2/python/rest_api/fixtures/podman.py
When executing on F36, starting the podman service in debug-mode causes aardvark to run in debug mode.  This does unexpected things with file-descriptors leading to a test-hang.  Thanks to @Luap99 for the fix.  See also https://github.com/containers/automation_images/pull/128 and https://github.com/containers/podman/pull/13934
Fixes https://github.com/containers/podman/issues/13932
> Fix hang in apiv2 test_connect

- libpod/networking_linux.go
SHA-1 is prone to collisions.
This will likely break connectivity between old containers started
before update and containers started after update. It will also fail to
cleanup old netns. A reboot will fix this, so a reboot is recommended
after update.
Edit: Update commit message.
> libpod/networking_linux.go: switch to sha256 hash generation

- pkg/domain/filters/containers.go
- test/apiv2/20-containers.at
Do not use a list of statuses outside of libpod to validate container
statuses.  Removing status was never added to the list.
Fixes: https://github.com/containers/podman/issues/13986
> Allow filtering of "removing", it is a valid status

- contrib/cirrus/runner.sh
A suspected race on uploading gopath cache is causing the docker-py (and
possibly other) tasks to fail unpredictably with an error from `make`
regarding missing `bin/podman`.  Since this failure is affecting all
development activity, apply a quick/dirty fix to the failing task, by
simply rebuilding the binary.  A more comprehensive/long-term fix will
be worked in a future PR.
> Cirrus: Fix cirrus cache race on bin/podman

- cmd/podman/containers/ps.go
go1.18 deprecates `strings.Title()`. However for our use case this is
still fine. The recommended replacement is adding about 400kb binary
size so lets keep using this for now.
> [CI:DOCS] fix staticcheck linter warning for deprecated function

- Makefile
- cmd/podman/machine/init.go
- hack/golangci-lint.sh
- pkg/machine/e2e/basic_test.go
- pkg/machine/e2e/config.go
- pkg/machine/e2e/config_basic.go
- pkg/machine/e2e/config_init.go
- pkg/machine/e2e/config_inspect.go
- pkg/machine/e2e/config_list.go
- pkg/machine/e2e/config_rm.go
- pkg/machine/e2e/config_ssh.go
- pkg/machine/e2e/config_start.go
- pkg/machine/e2e/config_stop.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/e2e/list_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/e2e/rm_test.go
- pkg/machine/e2e/ssh_test.go
- pkg/machine/e2e/start_test.go
- pkg/machine/e2e/stop_test.go
- pkg/machine/fcos.go
- pkg/machine/qemu/machine.go
This PR introduces a test suite for podman machine.  It can currently be
run on developers' local machines and is not part of the official CI
testing; however, the expectation is that any work on machine should
come with an accompanying test.
At present, the test must be run on Linux.  It is untested on Darwin.
There is no Makefile target for the test.  It can be run like `ginkgo -v
pkg/machine/test/.`.  It should be run as a unprivileged user.
> Add podman machine test suite

- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
Fix for most builds on `main` being red:
https://cirrus-ci.com/github/containers/podman/main
> [CI:BUILD] Cirrus: Re-fix build-cache miss on main

- cmd/podman/common/create_opts.go
- go.mod
- go.sum
- libpod/networking_linux.go
- libpod/networking_machine.go
- pkg/machine/ignition.go
- pkg/machine/wsl/machine.go
- pkg/specgen/volumes.go
- pkg/specgen/winpath.go
- pkg/specgen/winpath_linux.go
- pkg/specgen/winpath_unsupported.go
- pkg/specgen/winpath_windows.go
- pkg/specgenutil/specgenutil_test.go
- pkg/specgenutil/volumes.go
- vendor/github.com/containers/common/libnetwork/etchosts/ip.go
- vendor/github.com/containers/common/libnetwork/netavark/network.go
- vendor/github.com/containers/common/libnetwork/network/interface.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_freebsd.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/machine/machine.go
- vendor/modules.txt
Based on WSL2 9p support: remaps windows paths to /mnt/<drive> locations for
both podman and Docker API clients.
For example:
` podman run -it -v C:\Users\Jason:/blah ubi8-micro sh`
Additionally unixified paths sometimes used by Docker clients are supported
` podman run -it -v /c/Users/Jason:/blah ubi8-micro sh`
This also works with mount paths:
` .\docker run -it --mount 'type=bind,source=C:\Users\Jason,destination=/blah' alpine sh`
Finally, windows paths can be used on Linux in the WSL session to enable workflows where users are running process under the native Linux prompt yet accessing data on their Win drives.
This code is only active if either the podman-remote client is windows (in which case there is client side path remapping), or if the podman backend is configured as a WSL …
> Implement Windows volume/mount support

- pkg/rootless/rootless_linux.go
As noticed while debugging #13992, do not join the rootless user NS as a
Linux remote client.
[NO NEW TESTS NEEDED] as existing tests should continue to work.
> remote: do not join user NS

- contrib/cirrus/runner.sh
The originally intent for skipping tests based on change-content was to
optimize the PR workflow.  However, a mistake in a conditional is
causing almost all tasks running for Cron and branches to be skipped.
Fix this by checking for an empty '$CIRRUS_PR' variable.  This value is
always empty when operating outside of PRs.
[Example branch job skipping all/most tests](https://cirrus-ci.com/build/5990816991674368)
> Cirrus: Fix skipping all/most tests

- Makefile
- hack/podman-registry-go/registry.go
- test/e2e/benchmarks_test.go
Add more benchmarks for the most common and performance-critical image
commands.  Benchmarks for `podman build` should go into a separate
section.
> benchmarks: add more image benchmarks

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
We need to use the host network when it is set in the config and
--network was not used.
This regression was added in 3e9af2029f1f.
Fixes #14015
> play kube respect hostNetwork

- cmd/podman/play/kube.go
- libpod/define/annotations.go
- libpod/kube.go
- pkg/domain/infra/abi/play.go
- pkg/machine/e2e/config_init.go
- pkg/machine/e2e/machine_test.go
- test/system/700-play.bats
Kubernetes only allows 63 characters in an annotation.  Make sure
that we only add 63 or less charaters when generating kube. Warn
if containers or pods have longer length and truncate.
Discussion: https://github.com/containers/podman/discussions/13901
Fixes: https://github.com/containers/podman/issues/13962
> Truncate annotations when generating kubernetes yaml files

- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_manifest.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/test/manifests_test.go
- test/apiv2/01-basic.at
- version/version.go
I think we forgot to bump the version in the main branch. It should be
v4.1.0-dev now.
> Bump version to v4.1.0-dev

- cmd/podman/machine/set.go
- docs/source/markdown/podman-machine-set.1.md
- pkg/machine/config.go
- pkg/machine/e2e/config_set.go
- pkg/machine/e2e/set_test.go
- pkg/machine/qemu/machine.go
- pkg/machine/qemu/machine_test.go
- pkg/machine/wsl/machine.go
Allow podman machine set to change CPUs, Memory and Disk size of a QEMU machine after its been created.
Disk size can only be increased.
If one setting fails to be changed, the other settings will still be applied.
Fixes: https://github.com/containers/podman/issues/13633
> Allow changing of CPUs, Memory, and Disk Size

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/logcollector.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
- test/e2e/run_networking_test.go
Update to F36 CI VM Images + Testing netavark/aardvark-dns on F36+
***Depends on:***
* Cirrus: Fix missing git-enforced runtime identity #13956
* Fix using --network-backend on podman-remote #13957
* Workaround criu re-linking output in system test #13958
* Fix hang in apiv2 test_connect #13959
* Fix upgrade tests assuming storage.conf exists #13960
> Update to F36 CI VM Images + Testing netavark/aardvark-dns

- cmd/podman/images/history.go
- docs/source/markdown/podman-history.1.md
- test/system/110-history.bats
Fixes: https://github.com/containers/podman/issues/14012
> Add CreatedSince & CreatedAt format fields to podman image history

- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/e2e/rm_test.go
- pkg/machine/e2e/set_test.go
- pkg/machine/e2e/ssh_test.go
- pkg/machine/e2e/start_test.go
- pkg/machine/e2e/stop_test.go
- pkg/machine/qemu/machine.go
As Ed has pointed out, the form of Expect(session).To(Exit(0)) provides
much better error messages.  Let's make Ed happy.
> Produce better test error messages

- cmd/podman/images/search.go
- docs/source/markdown/podman-search.1.md
Truncate by default to avoid long descriptions from rendering the output
unreadable.
Fixes: #14044
> podman search: truncate by default

- docs/source/markdown/podman-volume-create.1.md
- libpod/options.go
- libpod/runtime_volume_linux.go
- libpod/volume.go
- libpod/volume_internal.go
- pkg/domain/infra/abi/parse/parse.go
- test/test_podman_baseline.sh
add a new option to completely disable xfs quota usage for a volume.
xfs quota set on a volume, even just for tracking disk usage, can
cause weird errors if the volume is later re-used by a container with
a different quota projid.  More specifically, link(2) and rename(2)
might fail with EXDEV if the source file has a projid that is
different from the parent directory.
To prevent such kind of issues, the volume should be created
beforehand with `podman volume create -o o=noquota $ID`
Closes: https://github.com/containers/podman/issues/14049
> volume: add new option -o o=noquota

- pkg/machine/e2e/config.go
- pkg/machine/e2e/list_test.go
- pkg/machine/qemu/machine.go
add a test to make sure machines are not running while still starting
in order to do this,
I added a parameter to `run()` to delineate whether
or not the command should block or not. The non blocking run allows for tests
to get and use the `machineSession` pointer and check the exit code to see if it has finished.
also fix a bug (created by #13996) that before started, the machines would 
always say "LastUp" and "Created" Less than one second ago
> podman machine starting test

- libpod/pod.go
`pod.CgroupPath()` currently includes a codepath that is never accessed,
which is supposed to start the infra ctr and obtain the cgroup path from there
that is never necessary/safe because p.state.CgroupPath is never empty
> remove unused codepath for creating/running ctr in a pod

- libpod/runtime_pod_linux.go
It solves a race where a container cleanup process launched because of
the container process exiting normally would hang.
It also solves a problem when running as rootless on cgroup v1 since
it is not possible to force pids.max = 1 on conmon to limit spawning
the cleanup process.
Partially copied from https://github.com/containers/podman/pull/13403
Related to: https://github.com/containers/podman/issues/14057
[NO NEW TESTS NEEDED] it doesn't add any new functionality
> libpod: unlock containers when removing pod

- .github/PULL_REQUEST_TEMPLATE.md
Initial step toward automating the collection & generation
of release notes: add a markdown release-note block to our
PR template. This will be reaped by an existing Kubernetes
tool and gathered into a document that can be used as a
starting point for future releases.
Many more followup steps to come.
> [CI:DOCS] Github PR template: add release-note block

- libpod/container_internal_linux.go
- test/system/500-networking.bats
When a container is run in the host network namespace we have to keep
the same resolv.conf content and not use the systemd-resolve detection
logic.
But also make sure we still allow --dns options.
Fixes #14055
```release-note
podman create/run --network host will use the correct nameservers from the host [#14055](https://github.com/containers/podman/issues/14055)
```
> libpod: host netns keep same /etc/resolv.conf

- hack/buildah-vendor-treadmill
More safety checks for the treadmill script:
* for --sync:
- issue warning if HEAD is not a vendor commit
- if run-buildah-bud-tests fails, leave the working dir
for user to investigate. And offer a long helpful warning.
* for --pick:
- check branch merge-base (of your vendor-update branch),
compare against that of the treadmill PR. If treadmill
is newer, bail, and suggest rebasing. This would've
saved us some time in #14005.
> [CI:DOCS] buildah-vendor-treadmill script: yet more checks

- cmd/rootlessport/main.go
- cmd/rootlessport/wsl.go
- cmd/rootlessport/wsl_test.go
Resolves a WSL problem where traffic from only one stack is relayed
Fixes #12292
> Use simulated dual-stack binds when using WSL

- Makefile
go get is deprecated, we should use go install instead.
Also for some reason go get -u golang.org/x/tools/cmd/goimports is
broken at the moment, thus failing CI jobs where we have to install
this. Switching to go install seems to fix it.
```release-note
None
```
> CI: emergency fix for broken go get

- hack/buildah-vendor-treadmill
Major revamp: instead of stacking a vendor commit on top of
the treadmill changes, do it the other way around: vendor,
then apply treadmill diffs.
Reason: the build-all-new-commits test. Sigh. It fails in the
common case where our treadmill changes include a new struct
element in cmd/podman/images/build.go
Why this is good: well, superficially, it's more intuitive.
Why this is horrible: omg the rebasing games are a nightmare.
When the vendor commit is on top (HEAD), it's ultra-trivial
to drop it, rebase the treadmill changes on main, then add
a new vendor-buildah commit on top. As you can see from the
diffs in this PR, treadmill-as-HEAD introduces all sorts
of complex dance steps in which things can go catastrophically
wrong and you can lose all your treadmill patches. I try very
hard to …
> Treadmill script: revamp

- pkg/systemd/generate/pods.go
- pkg/systemd/generate/pods_test.go
Unless specified in the create command of the pod, enforce the exit
policy to "stop".  With "stop", a pod is stopped when the last container
exits and does not continue running.  This behavior integrates much
better into systemd which is now able to tell whether the service
running as pod is actually running/active or not.
I just realized that we don't exercise (i.e., install and run) units generated for pods yet.  That's far from ideal.  I will extend the system tests in a future commit.
> generate systemd: pods: set exit policy

- cmd/podman/machine/init.go
- cmd/podman/machine/inspect.go
- cmd/podman/machine/list.go
- cmd/podman/machine/machine.go
- cmd/podman/machine/rm.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- cmd/podman/main.go
- cmd/podman/system/connection.go
- cmd/podman/validate/noop.go
- libpod/events/config.go
- libpod/events/events.go
- libpod/events/events_linux.go
- libpod/events/memory.go
- test/e2e/common_test.go
- test/e2e/system_service_test.go
Note: Automated tests WIP issues regarding holding socket open under ginkgo framework
```release-note
If developer provides a unix domain socket whose name matches machine_events.*\.sock in  XDG_RUNTIME_DIR/podman
or by setting the environment variable PODMAN_MACHINE_EVENTS_SOCK, then podman machine will publish events to
that socket using the Event type from the events package rendered in JSON.
```
> Add podman machine events

- Makefile
go get is deprecated, we should use go install instead.
Also for some reason go get -u golang.org/x/tools/cmd/goimports is
broken at the moment, thus failing CI jobs where we have to install
this. Switching to go install seems to fix it.
```release-note
None
```
> [v4.0] CI: emergency fix for broken go get

- Makefile
go get is deprecated, we should use go install instead.
Also for some reason go get -u golang.org/x/tools/cmd/goimports is
broken at the moment, thus failing CI jobs where we have to install
this. Switching to go install seems to fix it.
```release-note
None
```
> [v4.0-rhel] CI: emergency fix for broken go get

- cmd/podman/machine/machine.go
We should only open the socket when needed and not always at init time.
```release-note
None
```
> machine events: only open sockets when needed

- libpod/oci_attach_linux.go
when reading from the attach socket, treat ECONNRESET in the same way
as EOF.
Closes: https://github.com/containers/podman/issues/11446
```release-note
```
> libpod: treat ECONNRESET as EOF

- cmd/podman/machine/init.go
- cmd/podman/machine/inspect.go
- cmd/podman/machine/list.go
- cmd/podman/machine/machine.go
- cmd/podman/machine/platform.go
- cmd/podman/machine/platform_windows.go
- cmd/podman/machine/rm.go
- cmd/podman/machine/set.go
- cmd/podman/machine/ssh.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- cmd/podman/system/reset.go
- cmd/podman/system/reset_machine.go
- cmd/podman/system/reset_machine_unsupported.go
- docs/source/markdown/podman-system-reset.1.md
- pkg/machine/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
- test/e2e/system_reset_test.go
podman system reset did not clean up machines fully, leaving some config
files, and breaking machines. Now it removes all machines files fully.
```release-note
Podman system reset now properly deletes all podman machines and associated files. 
```
> podman system reset removed machines incorrectly

- cmd/podman/system/service_abi.go
- libpod/runtime.go
- pkg/api/server/server.go
- pkg/domain/infra/abi/system.go
- pkg/util/utils.go
- test/e2e/info_test.go
- test/e2e/play_kube_test.go
- test/e2e/system_connection_test.go
- test/e2e/system_service_test.go
- test/system/272-system-connection.bats
Rather than assuming a filesystem path, the API service URI is recorded
in the libpod runtime configuration and then reported as requested.
Note: All schemes other than "unix" are hard-coded to report URI exists.
Fixes #12023
>  Report correct RemoteURI

- docs/tutorials/rootless_tutorial.md
The `usermod` calls in rootless_tutorial.md were only adding a very narrow range for subuids and subgids, which will cause failures with containers where a file is owned by a user or group with a uid/gid > 1001.
> Fix usermod call in rootless_tutorial.md

- libpod/container.go
- pkg/domain/infra/abi/containers.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- test/e2e/container_clone_test.go
since the network config is a string map, json.unmarshal does not recognize
the config and spec as the same entity, need to map this option manually
resolves #13713
> pass networks to container clone

- test/e2e/manifest_test.go
- test/e2e/pull_test.go
A series of commits to speed up the e2e tests.  I focused on the pull tests but did not finish going through all of them due to time constraints. There is still much potential for speed ups and I bet there are more low-hanging fruits.
Please refer to the individual commits for change descriptions.
```release-note
None
```
> e2e cleanups

- cmd/podman/images/build.go
- docs/source/markdown/podman-build.1.md
Disable `build --output` for remote clients and update docs.
This does not any new feature instead disables existing feature for `podman-remote`
Fixes: https://github.com/containers/podman/pull/14118#discussion_r865754944 by @Luap99
> build: disable and hide `--output` for podman-remote clients

- libpod/container_internal_linux_test.go
- libpod/container_internal_test.go
- libpod/lock/file/file_lock_test.go
- pkg/hooks/hooks_test.go
- pkg/hooks/monitor_test.go
- pkg/hooks/read_test.go
- pkg/machine/qemu/config_test.go
- pkg/specgen/generate/kube/play_test.go
```release-note
None
```
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
if err != nil {
t.Fatal(err)
}
defer os.RemoveAll(dir)
// now
tmpDir := t.TempDir()
}
```
> test: use `T.TempDir` to create temporary test directory

- README.md
- RELEASE_NOTES.md
- version/version.go
Add release notes, bump the version the README points to, and set development version to 4.2.0-dev. No ci:docs to make sure the last bit doesn't break our tests, like 4.1.0 did (we should have fixed that, but it doesn't hurt to check...)
> Update main branch to reflect 4.1.0 release

- libpod/container.go
- pkg/specgen/generate/container.go
Reading the networks requires an extra db operation. Most c.Config() callers
do not need them so create a new function which returns the config with
networks.
```release-note
None
```
> libpod: add c.ConfigWithNetworks()

- libpod/oci_conmon_exec_linux.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/play_kube_test.go
currently tags cause a panic due to an uninitialized map. Initialize the map
and add parsing to make sure we are only tagging with journald
resolves #13356
> play kube log tag handling

- test/e2e/search_test.go
the alpine image used previously returns a description that contains
'...':
$ podman search --format json alpine | fgrep ...\"\,
"Description": "alpine 3.7 with bash, perl, gzip, wget...",
```release-note
None
```
> test: fix "podman search format json"

- contrib/cirrus/lib.sh
- contrib/cirrus/runner.sh
The test-skipping optimization is failing as rootless on non-main,
because $DEST_BRANCH is not set. Solution: check for envariable,
skip test if missing. (This was part of my original PR, but was
accidentally removed in #14013)
Fixes: #14131
> test skipper: check for $DEST_BRANCH

- libpod/container.go
fixup https://github.com/containers/podman/issues/14146
```release-note
None
```
> fix: Container.cGroupPath() skip empty line to avoid false error logging

- Makefile
This path should never, ever, ever be included in `$PATH` as it is
almost guaranteed to cause serious and non-obvious breakage in CI.  Fix
it and include a warning comment.
```release-note
None
```
> Cirrus: Fix Makefile including 'hack' in $PATH

- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
There are several runtime contexts (rootless and container) where
`$DEST_BRANCH` is needed but was not supplied.  A prior commit
(c4865767171b) removed the default value, `main` which was being
set incorrectly when CI ran on release branches.  Fix this by ensuring
the variable is non-empty upon entry to `setup_environment.sh`, then
ensure it gets passed through to child environments by way of the
`/etc/ci_environment` file.  This will maintain compatibility with
both CI and `hack/get_ci_vm.sh` use.
Also Ref: https://github.com/containers/podman/issues/14131
```release-note
None
```
> Cirrus: Guarantee $DEST_BRANCH is passed through

- docs/source/markdown/podman-auto-update.1.md
- docs/source/markdown/podman-history.1.md
- docs/source/markdown/podman-system-connection-list.1.md
As part of work done in #14046, fix bugs found in man pages,
basically just moving a few descriptions to the right place
and removing some undesired asterisks.
```release-note
None
```
> [CI:DOCS] man pages: fix inconsistencies

- libpod/oci_conmon_linux.go
- test/system/260-sdnotify.bats
Send the main PID only once.  Previously, `(*Container).start()` and
the conmon handler sent them ~simultaneously and went into a race.
I noticed the issue while debugging a WIP PR.
```release-note
Fix --sdnotify=conmon to sent the MAINPID once and not twice.
```
@giuseppe @rhatdan @flouthoc @Luap99 PTAL
> sdnotify: send MAINPID only once

- cmd/podman/common/completion.go
- cmd/podman/common/completion_test.go
The completion logic currently suggest also the functions that are
defined for this type. However this did not work correctly when it was
defined as pointer to that type on not the actual type.
This commit fixes that problem. To test you can compare the difference
between `podman stats --format {{.[TAB]` with and without this commit.
```release-note
Improve shell completion for the --format option.
```
> shell completion --format: work with pointer functions

- cmd/podman/machine/machine.go
- cmd/podman/machine/machine_unix.go
- cmd/podman/machine/machine_windows.go
- pkg/util/utils_windows.go
Carries over machine events using unix sockets on Windows
Also addresses  a current nag on every machine command:
```
PS C:\Users\jason> podman machine stop
Machine "podman-machine-default" stopped successfully
time="2022-05-06T16:18:12-05:00" level=warning msg="Failed to get runtime dir, machine events will not be published: this function is not implemented for windows"
```
```release-note
Fixes runtime warning on podman machine commands on Windows
```
> Add support for machine events on Windows

- hack/buildah-vendor-treadmill
Buildah got vendored into podman last week, and the script
went kablooie because of ever-so-slight conflicts between
what was in the treadmill PR (#13808) and what ultimately
got merged (#14127) which was obviously better (hey, I tried).
After a buildah vendor, there really isn't any point to keeping
the treadmill commits - we're much better off just restarting
with two fresh empty placeholder commits. Do so.
Also, mild cleanup.
> [CI:DOCS] Treadmill script: add --reset option

- libpod/info.go
- libpod/info_test.go
Signed-off-by: Sandro Casagrande <sc.casagrande@gmail.com>
**Description**
Using podman inside an lxc container I faced a situation where `podman info` failed with the following message:
```
Error: error getting host info: unable to parse user value "": strconv.ParseFloat: parsing "": invalid syntax
```
**Steps to reproduce the issue**
I installed latest stable version lxc from snap
```
$ lxc version                               
Client version: 5.1
Server version: 5.1
```
started an Ubuntu 22.04 container and inside built the latest release of podman
```
$ podman version
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Git Commit:   e4b03902052294d4f342a185bb54702ed5bed8b1
Built:        Fri May 13 23:22:38 2022
OS/Arch:      linux/amd64
``` …
> Robust whitespace split of cpu utilization line from /proc/stat

- cmd/podman/machine/machine.go
- cmd/podman/machine/machine_unix.go
- cmd/podman/machine/machine_windows.go
- pkg/util/utils_windows.go
Cherry-picks #14206 #14229 to resolve the warning message generated on all podman machine commands.
```release-note
Fixes runtime warning on podman machine commands on Windows
```
> [v4.1] Cherry-pick windows machine events

- pkg/specgen/generate/pause_image.go
- test/system/170-run-userns.bats
Use the host UID and host GID mapping when building the local pause
image for a Pod with a custom mapping.  Otherwise, the mappings are off
and the build fails. Propagating the mapping to the build container is
not needed since the pause image ships merely a copied `catatonit` from
the host.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2083997
```release-note
Fix a bug where the pause image of a Pod with a custom ID mapping could not be built (https://bugzilla.redhat.com/show_bug.cgi?id=2083997).
```
> [BZ #2083997] pod: build pause image in custom user NS

- pkg/machine/wsl/machine.go
Also migrate old machines that were missing this setting
Fixes #13965
```release-note
Fixes premature container termination on Windows when API forwarding is not running
```
> Update WSL machine OS to enable user lingering

- RELEASE_NOTES.md
- version/version.go
Cut a fresh v3.0.x release including a single change: an update to the Go module version, from v2 to v3 (we forgot the bump originally, it only landed in v3.1). The intention is to allow a v3.0 API client using our bindings to be used against a v3.0 API server. There is no need to update packages with this version; it is intended solely for users connecting to the API.
> Bump to v3.0.2

- libpod/runtime.go
Code is not directly reading XDG_RUNTIME_DIR, it is reading a value in
the state that may initially be from XDG_RUNTIME_DIR, but then is
overriden by a value from the boltdb that podman stores some state in.
XDG_RUNTIME_DIR and the RunRoot path may not have the same value, so
complaining about XDG_RUNTIME_DIR here may cause confusion when trying
to debug things.
```release-note
Be more precise about the problem when  RunRoot is not writable
```
> Don't complain about XDG_RUNTIME_DIR, Closes  #1424

- libpod/runtime_ctr.go
Removing exec sessions is guaranteed to evict them from the DB, but in the case of a zombie process (or similar) it may error and
block removal of the container. A subsequent run of `podman rm` would succeed (because the exec sessions have been purged from the DB), which is potentially confusing to users. So let's just continue, instead of erroring out, if removing exec sessions fails.
[NO NEW TESTS NEEDED] I wouldn't want to spawn a zombie in our test VMs even if I could.
Fixes #14252
Signed-off-by: Matthew Heon <matthew.heon@pm.me>
```release-note
Fixed a bug where removing a container with a zombie exec session would fail the first time, but succeed for subsequent calls ([#14252](https://github.com/containers/podman/issues/14252)).
```
> Make errors on removing exec sessions nonfatal

- pkg/api/handlers/compat/images_build.go
- test/apiv2/10-images.at
Podman API `libpod/build` accepts paramemter `remote` which overrides
`dockerfile` but currently parameter is no-op. Following commit adds
support for `remote` parameter in libpod API.
See: https://docs.podman.io/en/v3.2.3/_static/api.html#operation/ImageBuildLibpod
Closes: https://github.com/containers/podman/issues/13831
> api: make no-op `remote` functional in `/libpod/build`

- pkg/specgen/generate/pod_create.go
- test/system/170-run-userns.bats
Use the host UID and host GID mapping when building the local pause
image for a Pod with a custom mapping.  Otherwise, the mappings are off
and the build fails. Propagating the mapping to the build container is
not needed since the pause image ships merely a copied `catatonit` from
the host.
Backport-of: commit c45d51899a8190bd3797cdee71b74b912a634c71
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2083997
```release-note
Fix a bug where the pause image of a Pod with a custom ID mapping could not be built (https://bugzilla.redhat.com/show_bug.cgi?id=2083997).
```
@mheon @rhatdan @TomSweeneyRedHat PTAL
> [v4.1] [BZ #2083997] pod: build pause image in custom user NS

- pkg/api/handlers/compat/images_remove.go
- test/apiv2/10-images.at
Fixes: https://github.com/containers/podman/issues/14208
```release-note
```
> Deleting an n use image should return conflict not system error

- .cirrus.yml
- .gitignore
- Makefile
- contrib/cirrus/pr-should-include-tests
- pkg/api/Makefile
- podman.spec.rpkg
This removes about 100 lines from the top-level Makefile.
Please review commit by commit, and see commit messages for details.
Note some of these changes are standing on the assumption that Go >= 1.16 is used (which is true since we use things like filepath.WalkDir which require go 1.16).
> Makefile: simplify for modern Go

- .golangci.yml
- cmd/podman/common/create_test.go
- cmd/podman/containers/kill.go
- cmd/podman/containers/rm.go
- cmd/podman/containers/stop.go
- libpod/container_internal_linux.go
- pkg/api/handlers/compat/containers.go
- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build_unix.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/parse/parse.go
- pkg/domain/infra/abi/system.go
- pkg/k8s.io/apimachinery/pkg/api/resource/amount.go
- pkg/k8s.io/apimachinery/pkg/api/resource/quantity.go
- pkg/specgen/generate/config_linux.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/oci.go
- test/e2e/login_logout_test.go
- test/e2e/network_test.go
- test/e2e/run_networking_test.go
- test/e2e/system_df_test.go
- utils/utils.go
Detects unneccessary type conversions and helps in keeping the code base
cleaner.
```release-note
None
```
> linter: enable unconvert linter

- cmd/podman/common/completion.go
- cmd/podman/common/inspect.go
- cmd/podman/containers/inspect.go
- cmd/podman/images/inspect.go
- cmd/podman/images/save.go
- cmd/podman/inspect/inspect.go
- cmd/podman/networks/inspect.go
- cmd/podman/volumes/export.go
- cmd/podman/volumes/import.go
- cmd/podman/volumes/inspect.go
- libpod/events/config.go
see individual commits
```release-note
None
```
> shell completion: use more constants in the code

- .github/dependabot.yml
Followup to https://github.com/openshift/release/pull/28686
in which we ask openshift-ci-bot to enforce a release-note
label on new PRs.
Dependabot PRs do not need release notes. Add a config setting
(copied from cri-o) that tells dependabot to set release-note-none
on new PRs.
```release-note
None
```
> dependabot: add release-note-none label

- docs/tutorials/podman-for-windows.md
```release-note
None
```
I corrected a typo in the below document.
- podman-for-windows.md
When we would like to perform volume mounts from Windows paths into a Linux container,  should use podman option `-v`.  
Without `-v`,  an error occurred.
```powershell
podman run -it /c/Users/User/myfolder:/myfolder ubi8-micro ls /myfolder
Error: invalid reference format
```
In addiotn, I add option `--rm`.  This is because doing so will prevent unnecessary containers from remaining on the host.
```powershell
podman run -v c:\Users\User\myfolder:/myfolder ubi8-micro ls /myfolder
podman container ls -a 
CONTAINER ID  IMAGE                                         COMMAND           CREATED        STATUS                    PORTS       NAMES
2d4e534a3e5e  registry.access.redhat.com/ubi8-micro:latest  ls …
```
> [CI:DOCS] fix podman-for-windows.md

- libpod/events.go
- libpod/events/events.go
- libpod/runtime.go
- libpod/runtime_renumber.go
- pkg/autoupdate/autoupdate.go
- test/system/255-auto-update.bats
Create an auto-update event for each invocation, independent if images
and containers are updated or not.  Those events will be indicated in
the events already but users will now know why.
Fixes: #14283
```release-note
`podman auto-update` will now create an event.
```
> auto update: create an event

- .cirrus.yml
The caching update made in
https://github.com/containers/podman/pull/14016 neglected to attend to
the "git repo." needs of this task.  Fix this so images can build.
Also, make this optional task only appear when the `[CI:BUILD]` magic
string is used.  No reason to tempt every PR author to press a
mysterious button labeled 'trigger'.
```release-note
None
```
> [CI:BUILD] Cirrus: Fix building multiarch images

- libpod/boltdb_state.go
For various (mostly legacy) reasons, Podman presently maintains a unified namespace for pods and containers - IE, we cannot have both a pod and a container named "test" at the same time. To implement this, we use a global database table of every pod and container ID (and another of every pod and container name).
These entries should be added when containers/pods are added, and removed when containers/pods are removed, with the database's transactional integrity providing a guarantee that this is batched with the overall removal and that the DB should remain sane and consistent no matter what. As such, we treat a dangling ID as a hard error that stops the use of Podman.
Unfortunately, we have someone run into this last Friday. I'm still not certain how exactly their DB got into this state, …
> Instead of erroring, clean up after dangling IDs in DB

- .cirrus.yml
CI on the `v4.1` branch uses netavark & aardvark-dns packages built into
the VM images.  However there were several leftover env. var.
definitions from a previous solution, which may be confusing to future
maintainers.  Delete them.
```release-note
None
```
> [v4.1] Cirrus: Remove unused netavark/aardvark variables

- pkg/api/handlers/utils/images.go
- test/apiv2/70-short-names.at
Fix a bug in the resolution of images in the Docker compat API.
When looking up an image by a short name, the name may match
an image that does not live on Docker Hub.  The resolved name
should be used for normalization instead of the input name to
make sure that `busybox` can resolve to `registry.com/busybox`
if present in the local storage.
Fixes: #14291
```release-note
Fix a bug in the resolution of images in the Docker compat API when resolving short names for images that do not live on Docker Hub.
```
> fix compat image resolution

- cmd/podman/root.go
Currently this list is not exported from c/storage and the group
decided this will not be changed.
```release-note
NONE
```
> [CI:DOCS] Remove TODO re: storage-driver

- pkg/api/handlers/compat/images_build.go
- test/apiv2/10-images.at
Match with docker API and suppress step errors when field quiet is set.
Closes: https://github.com/containers/podman/issues/14315
> compat, build: suppress `step` errors when `quiet=1` is set

- cmd/podman/common/completion.go
- pkg/signal/signal_common.go
- pkg/signal/signal_linux.go
- pkg/signal/signal_linux_mipsx.go
- pkg/signal/signal_unix.go
- pkg/signal/signal_unsupported.go
There is no good way to recommend labels for podman container runlabel.
Add the missing max-size log option. These are the only documented
options so the completion should not suggest something different.
Add proper --stop-signal completion. It will now complete all supported
signal names both upper and lowercase depending on the user input. Also
it work with and without the SIG prefix.
Fixing the TODOs in this file are more complicated since they describe
bigger features.
```release-note
Improved shell completion for podman create/run --stop-signal.
```
> cmd/podman/common/completion.go: fix FIXMEs

- cmd/podman/pods/ps.go
- test/system/015-help.bats
- Look for and prevent lower-case arg descriptions:
podman cmd [arg]
- Look for and prevent optional-mandatory misordering:
podman cmd [ARG] ARG
- Tighter whitespace checks (and fix podman pod ps)
- simplify a no-longer-necessary mess! #8635 fixed the
horrible "CONTAINER | IMAGE" strings (with spaces),
so there's no longer a need to special-case those.
The one-extra-arg check is now much cleaner.
Minor refactoring.
```release-note
None
```
> help-message system test: catch more cases

- cmd/podman/pods/create.go
- cmd/podman/volumes/create.go
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-volume-create.1.md
- test/system/200-pod.bats
I am constantly attempting to add the podname to the last
argument to podman pod create. Allowing this makes it match
podman volume create and podman network create.
It does not match podman container create, since podman container create
arguments specify the arguments to run with the container.
Still need to support the --name option for backwards compatibility.
```release-note
podman pod create now accepts a name argument.
```
> Allow podman pod create to accept name argument

- libpod/runtime.go
- libpod/runtime_worker.go
Simplify the work-queue implementation by using a wait group. Once all
queued work items are done, the channel can be closed.
The system tests revealed a flake (i.e., #14351) which indicated that
the service container does not always get stopped which suggests a race
condition when queuing items.  Those items are queued in a goroutine to
prevent potential dead locks if the queue ever filled up too quickly.
The race condition in question is that if a work item queues another,
the goroutine for queuing may not be scheduled fast enough and the
runtime shuts down; it seems to happen fairly easily on the slow CI
machines.  The wait group fixes this race and allows for simplifying
the code.
Also increase the queue's buffer size to 10 to make things slightly
faster.
[NO NEW TESTS NEEDED] as we …
> work queue: simplify and use a wait group

- cmd/podman/pods/create.go
- docs/source/markdown/podman-pod-create.1.md
- test/system/200-pod.bats
Fixes: https://github.com/containers/podman/issues/13422
No
```release-note
Podman pod create --share now supports "+" prefix, allowing users to add to default namespaces
```
> Allow podman pod create --share +pid

- test/e2e/run_networking_test.go
I am not 100% sure if this is actually causing the problem but I was
able to reproduce locally and this change fixed it there. Without the `-n`
option iptables tries to reverse lookup the ips to domain names. This is
extremely slow for unknown reasons. Given the large amount of iptables
entries due parallel test runs it will not succeed in the default 90 sec
timeout.
```release-note
None
```
> fix f35 integration test network flake

- docs/source/markdown/podman-kill.1.md
- libpod/container.go
- libpod/container_api.go
- libpod/container_config.go
- libpod/container_exec.go
- libpod/container_internal_linux.go
- test/e2e/kill_test.go
Most of these are no longer relevant, just drop the comments.
Most notable change: allow `podman kill` on paused containers. Works just fine when I test it.
```release-note
The `podman kill` command now works on paused containers.
```
> First batch of resolutions to FIXMEs

- cmd/podman/containers/rm.go
Refactor test for deadlock by comparing error text vs. actual
ErrWillDeadlock constant. When running with --remote the error
constant will always be not equal to the error returned by the API.
```release-note
NONE
```
> Support remote deadlock errors in rm

- .cirrus.yml
- hack/install_golangci.sh
This test frequently fails and is of little use on a release-branch and
for any backports that may occur in the future.  Simply remove it.
```release-note
None
```
> [v3.2.3-rhel] Disable static v3.2.3 rhel

- docs/play_kube_support.md
Add a doc to outline which kube yaml fields the play
kube command currently supports.
This will be updated as more fields are supported in
the future.
```release-note
Add doc outlining the kube yaml fields supported by podman play kube
```
> [CI:DOCS] Add play kube support docs

- CONTRIBUTING.md
A new string was added in 521c0cb and the old one removed with 2ed31f9
```release-note
None
```
> [CI:DOCS] Fix test block bypass instructions

- cmd/podman/parse/net.go
- cmd/podman/pods/ps.go
The TODO in cmd/podman/pod/ps.go has already been fixed. Filters is now a []string
Fix up the parseEnv function in cmd/podman/parse/net.go to differentiate
between a label and env when parsing.
Don't do a system lookup when parsing labels.
```release-note
None
```
> Fix TODO in pod/ps.go and parse/net.go

- contrib/cirrus/ext_svc_check.sh
- contrib/cirrus/lib.sh
- contrib/cirrus/runner.sh
Most were simply deleted, the main one addressed is in the
"pre-testing" `ext_svc_check.sh` script.  It will now verify
accessibility of several key test images we maintain in `quay.io`.
```release-note
None
```
> [CI:DOCS] Cirrus: Fix several TODOs

- troubleshooting.md
Add a small note to troubleshooting docs regaring version parity between
podman-client and podman-server when looking for bug fixes.
Closes: https://github.com/containers/podman/issues/12660
> [CI:Docs]: note regarding version compatablity between server and client for bug fixes.

- cmd/podman/containers/checkpoint.go
- cmd/podman/containers/cleanup.go
- cmd/podman/containers/init.go
- cmd/podman/containers/kill.go
- cmd/podman/containers/mount.go
- cmd/podman/containers/port.go
- cmd/podman/containers/restart.go
- cmd/podman/containers/restore.go
- cmd/podman/containers/rm.go
- cmd/podman/containers/stop.go
- cmd/podman/containers/unmount.go
- cmd/podman/networks/reload.go
- cmd/podman/pods/kill.go
- cmd/podman/pods/pause.go
- cmd/podman/pods/restart.go
- cmd/podman/pods/rm.go
- cmd/podman/pods/start.go
- cmd/podman/pods/stop.go
- cmd/podman/pods/unpause.go
- cmd/podman/validate/args.go
These two functions were doing the exact same thing just
with cidfile and pod-id-file separately. Combine the functionality
to one function to remove repetative code.
Fix the TODO in cmd/podman/validate/args.go
```release-note
None
```
> Combine the CheckAllLatest CID and PodID functions

- libpod/define/pod_inspect.go
This PR partially addresses #14160 by fixing one instance of `net.IP` being represented as `[]uint8` in the swagger API spec. This fix does not work for the following models, because they contain arrays of `net.IP`.
- `ContainerNetworkConfig#dns_server`
- `NetOptions#dns_server`
- `NetworkConnectOptions#static_ips`
- `PerNetworkOptions#static_ips`
- `PodNetworkConfig#dns_server`
- `PodSpecGenerator#dns_server`
- `SpecGenerator#dns_server`
```release-note
None
```
> Fix swagger model of `InspectPodResponse`

- cmd/podman/machine/init.go
Allowing custom flags to provider has the potential to break all the
hand-crafted commands currently in use. This could become a support
nightmare.
```release-note
NONE
```
> Remove TODO comment

- troubleshooting.md
After lgtming the latest from @flouthouc, I spotted one
more minor typo in the troubleshooting guide.  This corrects it.
```release-note
None
```
> [CI:DOCS] Quick typo for troubleshooting

- libpod/container_api.go
- libpod/container_copy_linux.go
- pkg/api/handlers/compat/containers_archive.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/archive.go
Update method signatures and structs to pass option to buildah code
```release-note
NONE
```
> Add API support for NoOverwriteDirNonDir

- libpod/define/info.go
- libpod/info.go
The Authorization field lists the plugins for granting access to the
Docker daemon. This field will always be nil for Podman as there is no
daemon. The field is included for compatibility.
```release-note
NONE
```
> Add Authorization field to Plugins for Info

- pkg/specgenutil/specgen.go
- test/system/030-run.bats
In docker, the format of no-new-privileges is
"no-new-privileges:true". However, for Podman
all that's required is "no-new-privileges", leading to issues
when attempting to use features desgined for docker in podman.
Adding support for the ":" format to be used along with the "="
format, depedning on which one is entered by the user.
fixes #14133
```release-note
Fixes a bug in the parsing of --security-opt
```
> no-new-privileges format

- cmd/podman/volumes/export.go
- cmd/podman/volumes/import.go
- docs/source/markdown/podman-volume-import.1.md
- docs/source/markdown/podman-volume.1.md
- test/e2e/volume_create_test.go
When the volume does not exist we should output an error stating so and
not some generic one.
Fixes #14411
```release-note
None
```
> podman volume export/import: give better error

- libpod/container_config.go
- test/e2e/checkpoint_test.go
When a container does not use the default podman netns, for example
--network none or --network ns:/path a restore would fail because the
specgen check validates that c.config.StaticMAC is nil but the
unmarshaller sets it to an empty slice.
While we could make the check use len() > 0 I feel like it is more
common to check with != nil for ip and mac addresses.
Adding omitempty tag makes the json marshal/unmarshal work correctly.
This should not cause any issues.
Fixes #14389
```release-note
Fixed a bug where podman container restore would fail if the container used --network none or ns:/path 
```
> fix podman container restore without CreateNetNS

- Makefile
Some of the targets overwrite $GOOS. Since podman-remote-static should
always build for linux we can force linux GOOS here.
Fixes #14201
```release-note
None
```
> Makefile: force podman-remote-static to linux

- test/e2e/logs_test.go
The test calls podman run -d followed by podman logs. There is no
guarantee the the container or conmon has written all its output.
Adding an extra podman wait should fix this.
Fixes #14362
```release-note
None
```
> fix "tail 800 lines: journald" flake

- contrib/systemd/system/podman-restart.service.in
Fixes https://github.com/containers/podman/issues/14434
Added ExecStop to gracefully stop containers on shutdown. Added Wants= and After= to make sure startup/shutdown order is correct (like podman generate systemd does).
(new pull request with signoff, replaces #14442)
Signed-off-by: Andrin Brunner <andrin@acloud.one>
```release-note
None
```
> podman-restart.service: Add ExecStop and dependencies to fix shutdown 

- pkg/machine/config.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/qemu/machine.go
For consumers of the podman.sock who want a predictable way to find the
podman sock, we now include it under 'ConnectionConfig' in podman
machine inspect.
Fixes: #14231
```release-note
podman machine inspect now shows the exported podman socket for external use.
```
> expose podman.sock in machine inspect

- libpod/networking_linux.go
- test/e2e/network_connect_disconnect_test.go
Hardcoding the interface name is a bad idea. We have no control over the
actual interface name since the user can change it.
The correct thing is to read them from the network status. Since the
contianer can have more than one interface we have to add the RX/TX
values. The other values are currently not used.
For podman 5.0 we should change it so that the API can return the
statistics per interface and the client should sum the TX/RX for the
command output. This is what docker is doing.
Fixes #13824
```release-note
podman stats now works correctly with custom network interface names and when network disconnect was used.
```
> podman stats: work with network connect/disconnect

- .cirrus.yml
- hack/install_golangci.sh
- test/e2e/search_test.go
This is important for the stability of CI in case of a future backport
that happens to be incompatible with netavark/aardvark `main`.  Since CI
doesn't run very often on the podman `v4.0` branch, an incompatible change
may not be noticed.  Fix this by switching off of the `main` branch onto
a netavark/aardvark release branches.
```release-note
None
```
> [v4.0] Cirrus: Use fixed netavark/aardvark-dns branch

- .cirrus.yml
- hack/install_golangci.sh
This is important for the stability of CI in case of a future backport
that happens to be incompatible with netavark/aardvark `main`.  Since CI
doesn't run very often on the podman `v4.0` branch, an incompatible change
may not be noticed.  Fix this by switching off of the `main` branch onto
a netavark/aardvark release branches.
```release-note
None
```
> [v4.0-rhel] Cirrus: Use fixed netavark/aardvark-dns branch

- pkg/specgen/container_validate.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/generate/pod_create.go
- pkg/specgen/namespaces.go
- pkg/specgen/namespaces_test.go
When podman-remote is used we should not resolve the default network
mode on the client. Defaults should be set on the server. In this case
this is important because we have different defaults for root/rootless.
So when the client is rootless and the server is root we must pick the
root default.
Note that this already worked when --network was set since we did not
parsed the flag in this case. To reproduce you need --network=default.
Also removed a unused function.
[NO NEW TESTS NEEDED] I tested it manually but I am not sure how I can
hook a test like this up in CI. The client would need to run as rootless
and the server as root or the other way around.
Fixes #14368
```release-note
The default network mode is now assigned by the server and not the client.
```
> pkg/specgen: parse default network mode on server

- cmd/podman/common/create.go
- cmd/podman/common/default.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- pkg/specgenutil/createparse.go
- pkg/specgenutil/specgen.go
- test/system/160-volumes.bats
Fixes: https://github.com/containers/podman/issues/14230
Yes
```release-note
Podman now supports image_volume_mode setting in containers.conf, which allows you to modify the system defaults for the podman run/create --image-volume option.
```
> Support setting image_volume_mode in containers.conf

- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
This also unifies the documentation for `podman create` and `podman run`.
`podman create` is a 1:1 copy of `podman run`, so you might wanna review `podman run` only. `podman pod create` is also a copy, but with a different note.
```release-note
None
```
> [CI:DOCS] Document protocol usage for --publish

- Makefile
- contrib/cirrus/runner.sh
Fixes #14021
Substitution values built from `$(shell ...)` output can easily be empty
due to the shell's default `pipefail` behavior.  This can also hide
non-zero exit codes, similarly resulting in empty values being set.
While not a perfect fix, the situation is improved by using the
`err_if_empty` function in all cases where empty values would be
unexpected.  Also remove the definitions for `GIT_BRANCH` and
`GIT_BRANCH_CLEAN` which don't seem to actually be used anywhere
(including in code).
```release-note
None
```
> Makefile: Handle unexpected empty var. values

- cmd/podman/common/create.go
- docs/source/markdown/podman-build.1.md
- docs/source/markdown/podman-container-clone.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
In podman run --help, the message said megabyte, gigabyte, etc. In reality podman takes mebibytes, gibibytes, etc.
[CI:DOCS]
Signed-off-by: Karthik Elango <kelango@redhat.com>
Fixes: https://github.com/containers/podman/issues/14187 
```release-note
Changed help message from megabytes to mebibytes.
```
> [CI:DOCS] changed megabyte to mebibyte

- cmd/podman/images/load.go
- docs/source/markdown/podman-image-scp.1.md
- test/system/120-load.bats
The comma-separated podman load output isn't conducive for using the
subsequent images. For tarballs with multiple images, the comma
separator must be manually identified and a suitable range identified.
Docker CLI on the other hand, has one image identifier per line:
```
Loaded image: repo1/name1:latest
Loaded image: repo1/name1:tag1
Loaded image: repo2/name2:tag1
```
(as of Docker version 20.10.16, build aa7e414).
Switch `podman load` to this format for consistency and usability.
`Signed-off-by: Alexander Scheel <alex.scheel@hashicorp.com>`
---
```release-note
podman load CLI now mirrors docker load's imported image list output format
```
/cc: @baude
> Align docker load and podman load output

- pkg/specgen/generate/namespaces.go
- test/e2e/pod_infra_container_test.go
the function `GetDefaultNamespaceMode` for pods checks if we are sharing each namespace
and if not, returns the default which in the case of a network is slirp.
add a switch case for explicitly checking if the pod's network mode is host
and if so, return specgen.Host for the container
resolves #13763
```release-note
None
```
> fix pod network handling with a host network

- pkg/machine/qemu/machine.go
In #13466 the ability to force remove a machine while it's running was
added but it did not first stop the machine, all files get deleted but
the qemu VM would essentially be orphaned.
```release-note
Force removing a machine now stops the machine before deleting the files.
```
> Stop machine before force removing files

- test/e2e/save_test.go
Save at most three images and sort them by size.  The test started to
flake as _all_ local images were saved which is not neccessary.
Fixes: #14468
```release-note
None
```
@edsantiago @Luap99 @flouthoc PTAL
> test/e2e/save_test.go: fix flake

- pkg/api/handlers/libpod/play.go
Quick fix in play.go to use logDriver to set the correct
log driver rather than overwriting query.LogDriver.
```release-note
None
```
> Use logDriver instead of query.LogDriver for podman play kube

- cmd/podman/system/reset.go
- libpod/options.go
- libpod/reset.go
- libpod/runtime.go
- pkg/domain/infra/abi/system.go
- pkg/domain/infra/runtime_abi.go
- pkg/domain/infra/runtime_libpod.go
Firstly, reset is now managed by the runtime itself as a part of initialization. This ensures that it can be used even with runtimes that would otherwise fail to be created - most notably, when the user has changed a core path (runroot/root/tmpdir/staticdir).
Secondly, we now attempt a best-effort removal even if the store completely fails to be configured.
Third, we now hold the alive lock for the entire reset operation. This ensures that no other Podman process can start while we are running a system reset, and removes any possibility of a race where a user tries to create containers or pull images while we
are trying to perform a reset. 
[NO NEW TESTS NEEDED] we do not test reset last I checked.
Fixes #9075
```release-note
Fixed a bug where the `podman system reset` command could race …
```
> Improve robustness of `podman system reset`

- libpod/container_log.go
- test/e2e/logs_test.go
The backend should not convert partial lines to full log lines. While
this works for most cases it cannot work when the last line is partial
since it will just be lost. The frontend logic can already display
partial lines correctly. The journald driver also works correctly since
it does not such conversion.
Fixes #14458
```release-note
podman logs will now correctly display all output when the last line did not end with an newline.
```
> podman logs k8s-file: do not reassemble partial log lines

- test/e2e/play_kube_test.go
This PR removes some leftovers in `play kube` e2e tests used for ginkgo `focus` option  
Signed-off-by: Cosmin Tupangiu <cosmin@redhat.com>
```release-note
None
```
> Cleanup the leftovers in `play kube` e2e test used for ginkgo focus option

- .github/PULL_REQUEST_TEMPLATE.md
- contrib/podmanimage/README.md
@cevich recently renamed all the files named Dockerfile to Containerfile
in this directory.  Touching up the README.md to reflect that.
Also, as I was doing the submit, I noticed a couple of nits in the PR
request template and cleaned those up.
```release-note
None
```
> [CI:DOCS] PodmanImage Readme touchup

- docs/source/markdown/podman-build.1.md
- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
- test/buildah-bud/apply-podman-deltas
Feature of additional build context added here https://github.com/containers/buildah/pull/3978
already exists on `podman` following PR just enables this feature of
`podman-remote` and `podman on macOS` setups.
Follow up to : https://github.com/containers/podman/pull/14320
```
Enables additional build context for podman-remote and macOS using --build-context
```
> remote: enable support for additional `--build-context` on macOS and remote

- test/e2e/build_test.go
Setting the build context to a dedicated subdir makes sure that the test does not
flake when running in parallel, as the test is isolated from other tests
that may dump secrets in a higher level context dir.
This should have been done in
https://github.com/containers/podman/pull/13457, as this makes that PR
actually work.
Fixes: https://github.com/containers/podman/issues/13417
```release-note
None
```
> Fix secret-verify-leak flake: set build context to subdir

- contrib/podmanimage/stable/Containerfile
- contrib/podmanimage/stable/storage.conf
- contrib/podmanimage/testing/Containerfile
- contrib/podmanimage/upstream/Containerfile
This was an accidental leftover from an in-development implementation.
The `sed` command further down entirely replaces the file in the image.
Strip out the unnecessary 'storage.conf' ADD instruction.
Ref: https://github.com/containers/podman/pull/14437
```release-note
None
```
> [CI:BUILD] Minor: Remove useless addition of storage.conf

- README.md
We really should be advertising our Mac and Windows support more prominently.
Next step will be to update the Mac/Windows tutorials (honestly, it's kind of a mess right now; there are 3 separate tutorials on Mac/the remote client, and none of them are complete) and link the result from the readme.
> [CI:DOCS] Add some Readme updates around machine

- libpod/runtime.go
make the error clearer and state that images created by other tools
might not be visible to Podman when it overrides the graph driver.
Closes: https://github.com/containers/podman/issues/13970
```release-note
None
```
> runtime: make error clearer

- libpod/container_internal.go
- test/system/500-networking.bats
When a container with a userns is created the network setup is special.
Normally the netns is setup before the oci runtime container is created,
however with a userns the container is created first and then the network
is setup. In the second case we never saved the container state
afterwards. Because of it, podman inspect would not show the network info
and network teardown will not happen.
This worked with local podman  because there was a save() call later in the
code path which then also saved the network status. But in the podman API
code path this save never happened thus all containers started via API had
this problem.
Fixes #14465
```release-note
Fixed a bug where network cleanup was not happening when a container used a custom user namespace and were initialized via API …
```
> libpod: store network status when userns is used

- pkg/specgen/generate/container_create.go
- test/e2e/pod_create_test.go
infra was overriding options that it should be appending rather than resetting.
fix this by appending the given container's spec to the compatible options before marshaling/unmarshaling
resolves #14454
```release-note
None
```
> Infra Inheritance patch

- libpod/container_config.go
- libpod/container_internal_linux.go
- libpod/options.go
- pkg/specgen/generate/config_linux.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/oci.go
- pkg/util/utils_linux.go
- test/e2e/run_privileged_test.go
If a privileged container is running, stops, and the devices on the host
change, such as a USB device is unplugged, then a container would no
longer start. Previously, the devices from the host were only being
added to the container once: when the container was created. Now, this
happens every time the container starts.
I did this by adding a boolean to the container config that indicates
whether to mount all of the devices or not, which can be set via an option.
During spec generation, if the `MountAllDevices` option is set in the
container config, all host devices are added to the container.
Additionally, a couple of functions from `pkg/specgen/generate/config_linux.go`
were moved into `pkg/util/utils_linux.go` as they were needed in
multiple packages.
Closes #13899
Signed-off-by: Jake …
> Privileged containers can now restart if the host devices change

- contrib/podmanimage/stable/Containerfile
- contrib/podmanimage/testing/Containerfile
- contrib/podmanimage/upstream/Containerfile
The Containerfiles were built with sed -i, which is leading to empty
storage.conf files. This will cause Podman in a container to print
warning information about storage.driver not being set to something.
[NO NEW TESTS REQUIRED]
No
```release-note
None
```
> [CI:DOCS] Podman images generated with empty /etc/containers/storage.conf

- .cirrus.yml
This check is breaking on PRs and branches, for example:
```
Rebasing (5/24)
error: could not apply e6ed1d4bf... cirrus: update image
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase
--abort".
Could not apply e6ed1d4bf... cirrus: update image
Auto-merging .cirrus.yml
CONFLICT (content): Merge conflict in .cirrus.yml
make: *** [Makefile:269: build-all-new-commits] Error 1
```
Stop running this check rather than debugging/fixing it because this is
a release branch that will not likely ever see a PR containing more than
one commit.
```release-note
None
```
> [v3.2.3-rhel] Cirrus: Avoid build-each-commit check

- test/apiv2/10-images.at
- test/apiv2/12-imagesMore.at
- test/apiv2/15-manifest.at
- test/apiv2/20-containers.at
- test/apiv2/60-auth.at
- test/apiv2/test-apiv2
Mostly fix a bad design decision I made early on, re: registry.
old: registry starts once, runs to the end
new: registry is brought up on demand, then stopped
Reason: there are times when we need a password-controlled
registry, and times when we need it open.
As long as I'm in here, I've also cleaned up some confusing code
and fixed things so tests can run rootless again.
```release-note
None
```
> apiv2 tests: clean up

- libpod/oci_conmon_linux.go
Previous PR #12394 tried to address this, but made a mistake: containers that have just exited do not move to the Exited state but rather the Stopped state - as such, the code would never have run (there is no way we start `podman kill`, and the container
transitions to Exited while we are doing it - that requires holding the container lock, which Kill already does).
Fix the code to check Stopped as well (we omit Exited entirely but it's a cheap check and our state logic could change in the
future). Also, return an error, instead of exiting cleanly - the Kill failed, after all. ErrCtrStateInvalid is already handled by the sig-proxy logic so there won't be issues.
```release-note
Fixed a bug where Podman could print error messages when signals were forwarded to a container via …
```
> Do not error on signalling a just-stopped container

- test/e2e/build_test.go
Fixes #14184
Docs: https://onsi.github.io/gomega/#making-asynchronous-assertions
```release-note
None
```
> Fix Remote filtering embedded directory test

- test/apiv2/test-apiv2
APIv2 tests are flaky after this morning's merge of #14543.
Symptom:
test-apiv2: Timed out (10s) waiting for service (/dev/tcp/localhost/5564)
journal shows:
registry[7421]: panic: unable to configure authorization (htpasswd):
no access controller registered with name: none
Possible cause:
Mix of REGISTRY_AUTH=none with REGISTRY_AUTH_HTPASSWD_* vars.
https://github.com/distribution/distribution/issues/1168
Solution:
only set _HTPASSWD_* vars when AUTH=htpasswd
```release-note
None
```
> APIv2 tests: (try to) fix flaky registry panic

- docs/source/markdown/podman-build.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
Fixes: https://github.com/containers/podman/issues/13939
```release-note
Clarifies documentation on mount propagation with named or internal volumes
```
> [CI:DOCS] Mount propagation works with named volumes

- pkg/systemdgen/systemdgen.go
- pkg/systemdgen/systemdgen_test.go
Allow a webserver to come backup after it is restarted by systemd.
This was backported to all other Podman releases already, but not to
v1.6.4 at the time.  However, this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=2091721 is asking for the
fix.
Backport of https://github.com/containers/podman/commit/05a0bf7c07e5
```release-note
None
```
> [v1.6.4-rhel] Fix webserver startup w/ systemd

- pkg/machine/qemu/options_darwin_arm64.go
When calling QEMU, the CPU arch should be host, and highmem should be on, or else the VM start fails.
Fixes: https://github.com/containers/podman/issues/14303
```release-note
Fixed a bug where podman machine fails to start with memory > 3072 on M1
```
> Fix M1 QEMU flags

- cmd/podman/containers/stats.go
- libpod/stats.go
- pkg/api/handlers/compat/containers_stats.go
- test/e2e/pause_test.go
- test/e2e/stats_test.go
command
Previously, if a container was not running, and the user ran the `podman
stats` command, an error would be reported: 
```
Error: container state improper
```
Podman now reports stats as the fields' default values for their
respective type if the container is not running:
```
$ podman stats --no-stream demo
ID            NAME        CPU %       MEM USAGE / LIMIT  MEM %       NET IO      BLOCK IO    PIDS        CPU TIME    AVG CPU %
4b4bf8ce84ed  demo        0.00%       0B / 0B            0.00%       0B / 0B     0B / 0B     0           0s          0.00%
```
Closes: #14498
```release-note
Fixed a bug where using the `podman stats` command on a non-running container would return an error instead of zeroed values
```
> Non-running containers now report statistics via the `podman stats`

- test/buildah-bud/apply-podman-deltas
Fix bad design decision (mine) by adding a simple usage check to 'skip'
and 'skip_if_remote' functions: if invoked without test-name args,
fail loudly and immediately.
Background: yeah, their usage is not intuitive. Making the first arg
be a comment helps with _reading_ the code, but not _writing_ new
additions. A developer in a hurry could write "skip this-test" and,
until now, that would be a silent NOP.
Tested by adding broken skip/skip_if_remote calls inline; I confirm
that the line number and funcname usage is correct.
```release-note
None
```
> buildah-bud tests: add arg sanity check

- .cirrus.yml
- test/apiv2/test-apiv2
This would've caught a regression that #14549 had to fix.
Let's try to prevent the next regression.
```release-note
None
```
> CI: APIv2 tests: add rootless

- pkg/machine/qemu/options_darwin_arm64.go
this allows users to use a qemu installation that is
not in the default /usr/local/bin location
a user can configure engine.helper_binaries_dir key
or update PATH to include the installation location
to find the qemu binary
```release-note
None
```
> [macos: podman-machine] look for firmware (edk2-code-fd) based on the path of qemu binary

- libpod/container_internal_linux.go
- test/e2e/run_volume_test.go
if /run is on a volume do not create the file /run/.containerenv as it
would leak outside of the container.
Closes: https://github.com/containers/podman/issues/14577
```release-note
If /run is on a volume then the file `/run/.containerenv` is not created automatically anymore
```
> container: do not create .containerenv with -v SRC:/run

- hack/golangci-lint.sh
- libpod/container_log_linux.go
- libpod/events/journal_linux.go
Lint the systemd code and fix the reported problems.
The remoteclient tag is no longer used so I just removed it.
```release-note
None
```
> golangci-lint: add systemd build tag

- cmd/podman/system/service_abi.go
- libpod/events/journal_linux.go
- test/e2e/systemd_activate_test.go
Commit 5fa6f686db added a regression which was fixed in eb71712626f9.
Apply the same fix again to prevent a panic and return a proper error
instead.
To not regress again I added a e2e test which makes sure we do not panic.
```release-note
None
```
> systemd socket activation: check listener to prevent panic

- pkg/machine/keys.go
Fixes #14416 
Yes
```release-note
- Fix: #14416 : `machine init` fails when ran from C:\Windows\System32 on Windows
```
> Fix: Use absolute path to WSL binary to create ssh keys for `machine init` on Windows (Issue #14416)

- .golangci.yml
- Makefile
- test/e2e/systemd_activate_test.go
Update to the latest golangci-lint version. v1.46 added new linters.
I disabled nonamedreturns and exhaustruct since they enforce a certain
code style and using them would require big changes to the code base.
The nosprintfhostport is new and I fixed one problem in the tests. While
the test itself is fine because it uses ipv4 only the linter still looks
good because the sprintf use will fail for ipv6 addresses.
```release-note
None
```
> golangci-lint: update to v1.46.2

- CONTRIBUTING.md
- prerequisites in Fedora section has libseccomp-devel.x86_64 named twice
- bin/podman flag "-h" does not work, "--help" is required
```release-note
None
```
> [CI:DOCS] fix typos in prerequisites for Fedora and make binaries sections

- test/system/410-selinux.bats
With runc 1.1, we have the following failure:
```
```
which is caused by the fact that runc 1.1 uses newer opencontainers/selinux
package, which changes custom errors to standard os.PathError instances (so
that they can be unwrapped if needed).
Fix the test case accordingly. NOT TESTED.
```release-note
NONE
```
> test/system/410-selinux: fix for newer runc

- test/system/070-build.bats
- test/system/250-systemd.bats
I noticed 'rmi -a' in a test. I tried to fix it. Hilarity ensued.
'rmi -a' is evil: it forces a fresh pull of our test image,
which in turn almost guarantees a flake some day. We avoid
it, but once in a while it slips in.
While fixing it, I noticed a bevy of other problems that
needed cleanup.
```release-note
None
```
> system tests: avoid rmi -a ... plus cleanup

- docs/source/markdown/podman-system-service.1.md
The manpage for `podman system service` should mention that this is not safe for external consumption unless you are comfortable giving anyone who accesses it full root on the system.
```release-note
NONE
```
> [CI:DOCS] Make it clear the REST API could be a security issue

- cmd/podman/main.go
- test/system/015-help.bats
`podman -h` currently returns an error:
`Error: pflag: help requested`
This bug was introduced in 44d037898ebc, the problem is that we wrap the
error and cobra lib checks with `==` for this one and not errors.Is().
I have a PR upstream to fix this but for now this also works.
```release-note
Fixed a bug where `podman -h` did not show the help output.
```
> fix "podman -h" help output

- cmd/podman/common/completion.go
- cmd/podman/common/create.go
- cmd/podman/common/create_opts.go
- cmd/podman/containers/clone.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- cmd/podman/pods/clone.go
- cmd/podman/pods/create.go
- docs/source/markdown/podman-pod-clone.1.md
- docs/source/markdown/podman-pod.1.md
- libpod/pod.go
- pkg/domain/entities/engine_container.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/pods.go
- pkg/domain/infra/tunnel/pods.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/pod_create.go
- pkg/specgenutil/specgen.go
- test/e2e/pod_clone_test.go
implement podman pod clone, a command to create an exact copy of a pod while changing certain config elements
current supported (new) flags are:
--name, change the pod name
--destroy, remove the original pod
--start, run the new pod on creation
and all infra-container related flags from podman pod create (namespaces etc)
resolves #12843
```release-note
Allow user to clone pods using the CLI. New options include --start --destroy and --name
```
> implement podman pod clone

- pkg/domain/entities/pods.go
podman pod clone somehow snuck by the new linter code that went in while it was in flight
fix that here
```release-note
None
```
> linter fix from #14299

- .cirrus.yml
This is causing the remote system tests to fail when run on on `main`.
```release-note
None
```
> Cirrus: Fix build. dep. missed in #14521

- .cirrus.yml
As [per spec](https://yaml.org/type/merge.html):
>If the value associated with the key is a single mapping node, each of its key/value pairs is inserted into the current mapping, _unless the key already exists in it_.
A bit more detailed explanation: https://github.com/cirruslabs/cirrus-cli/issues/530#issuecomment-1158822585.
Resolves https://github.com/containers/podman/issues/14623.
> .cirrus.yml: fix matrix expansion by properly merging YAML mappings

- .cirrus.yml
As release branches age, it becomes less valuable to execute
comprehensive CI testing.  Further given occasional flakes, it becomes
more burdensome to maintain.  Trim back some non-essential testing tasks
for improved long-term reliability and reduced maintenance.
```release-note
None
```
> [v3.2.3-rhel] Cirrus: Prune testing tasks for long-term reliability

- .cirrus.yml
- hack/install_golangci.sh
As release branches age, it becomes less valuable to execute
comprehensive CI testing.  Further given occasional flakes, it becomes
more burdensome to maintain.  Trim back some non-essential testing tasks
for improved long-term reliability and reduced maintenance.
```release-note
None
```
> [v3.3.1-rhel] Cirrus: Prune testing tasks for long-term reliability

- pkg/api/handlers/compat/containers_stats.go
- test/apiv2/20-containers.at
use the memory limit specified for the container instead of reading it
from the cgroup.  It is not reliable to read it from the cgroup since
the container could have been moved to a different cgroup and in
general the OCI runtime might create a sub-cgroup (like crun does).
Closes: https://github.com/containers/podman/issues/14676
```release-note
The HTTP handler shows the memory limit as specified at creation time 
```
> api: show the memory limit specified for the container

- pkg/api/handlers/libpod/containers.go
- test/apiv2/20-containers.at
When we return no containers we just return `[]` but we still have to keep
the content type header `application/json` so external tools can correctly
parse the output.
Fixes #14647
```release-note
Fixed a bug where the /libpod/containers/json endpoint did not return the application/json content type header when the container list is empty.
```
> API: containers/json always set application/json content type

- cmd/podman/common/completion.go
- libpod/container_config.go
- libpod/container_internal_linux.go
- libpod/networking_linux.go
* Replace "setup", "lookup" with "set up", "look up"
when used as verbs.
```release-note
None
```
> [CI:DOCS] "setup" -> "set up" in source code comments

- docs/source/markdown/podman-network-ls.1.md
- pkg/domain/infra/abi/network.go
- test/apiv2/35-networks.at
- test/e2e/network_test.go
add the ability to filter networks by their dangling status via:
`network ls --filter dangling=true/false`
Fixes: #14595
```release-note
Added support for `network ls --filter dangling=true/false`
```
> allow filter networks by dangling status

- go.mod
- pkg/domain/infra/abi/play.go
- vendor/modules.txt
> Update to use gopkg.in/yaml.v3

- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_modify_options.go
- test/e2e/manifest_test.go
It seems API needs json names for `OSVersion` and `OSFeatures` in `es_model`
ref: https://github.com/containers/podman/blob/main/pkg/domain/entities/manifest.go#L42
So at bindings end ensure that we honor `es_model` naming convention when
we perform marshaling otherwise API will ignore these fields
Closes: https://github.com/containers/podman/issues/12774
> bindings: manifest should follow `es_model` naming convention while marshalling `OSVersion` and `OSFeatures`

- cmd/winpath/main.go
- contrib/msi/podman.wxs
- docs/remote-docs.sh
- docs/standalone-styling.css
- docs/tutorials/podman-for-windows.md
Until  msitools is released with the UI featureset in main, we are limited to a basic progress bar. After install it's not clear to the user the installation is actually done or what steps they should take next. To improve the UX, this PR opens the Windows tutorial after a successful install.
Changes:
- Render Windows tutorial to standalone html file and include it in the install
- Modify the winpath helper to have a hidden open command to support the installer
- Change installer to open the tutorial after a successful installation (unless a quiet install is selected)
```release-note
Change Windows installer to open tutorial after install
```
> Open Windows tutorial after MSI installation

- cmd/podman/utils/utils.go
'podman system prune' command always outputs "Deleted Images" message,
even though there is no dangling or unused image to remove.
This message should be output only if dangling or unused image exists.
```release-note
None
```
> Fix system prune output message

- pkg/bindings/connection.go
- pkg/bindings/containers/attach.go
- pkg/bindings/containers/containers.go
We are only doing logrus.Info on a couple of bindings. I see no reason
to only do this on a couple, seems like debugging information more then
useful to the caller. We had a complaint about this so removing.
Fixes: https://github.com/containers/podman/issues/13504
None
```release-note
None
```
> Remove logrus.Infof on bindings start and attach

- contrib/cirrus/logformatter
- contrib/cirrus/runner.sh
One day we may use AWS for part of CI. Do you want to maintain
two separate code paths in this script for linking to artifacts
in multiple cloud providers? Can you say no? I knew you could.
Cirrus already knows the location of the artifacts and provides
a transparent mechanism for accessing them. Use it.
This PR exposed a nasty bug in our environment-variable handling:
envariables passed through to the containerized environment were
being double-space-escaped, so "FOO=a b" ended up as "FOO=a\ b"
(with a backslash), with one consequence being invalid URLs.
The solution is simple: run 'podman -e FOO', not '-e FOO=value'.
Finally, reinstate the environment-variable dump (in comments).
I had removed this in a moment of panic over leaking secrets,
but no, that doesn't happen.
See #14569 for …
> logformatter: link to logs using Cirrus API

- test/e2e/checkpoint_test.go
Since it may be a while before we get a true fix: add a
workaround for podman-remote checkpoint tests, in which
we pause until the 'run --rm' container is truly truly gone.
I've tried to make it as easy as possible to clean up
the workaround code once the bug is fixed.
Oh, also, remove "-it" from a podman-run. It makes no sense
and only results in nasty orange warning messages.
```release-note
None
```
> Workaround for bug 14653 (checkpoint flake)

- contrib/podmanimage/README.md
Add a reference to where/how podman is compiled for the 'upstream'
flavored image.
```release-note
None
```
> [CI:DOCS] Minor update to podmanimage upstream docs

- test/e2e/image_scp_test.go
- test/e2e/system_connection_test.go
podman image scp and podman system connection tests were querying an existing website during testing.
Change to a URL that will never exist given an improper domain extension
also just generally clean up a few things in both scp and connection testing
resolves #14699
```release-note
None
```
> fix system connection and scp testing

- libpod/boltdb_state.go
- libpod/boltdb_state_internal.go
- libpod/container_api.go
- libpod/container_internal.go
- libpod/define/errors.go
- libpod/events.go
- libpod/oci_conmon_linux.go
- libpod/state.go
- pkg/api/handlers/utils/containers.go
- pkg/domain/infra/abi/containers.go
- test/system/030-run.bats
Taking over #14559 from @vrothberg and trying to get CI to pass.
No changes (besides a rebase) yes, I just want to verify we have the same symptoms.
```release-note
Fix a bug in the wait logic to enable Podman on Gitlab runner.
```
> Followon to #14559

- cmd/podman/machine/init.go
podman machine start contains more logic than just the simple vm.Start()
call. Instead of duplicating this into inti we just call start().
[NO NEW TESTS NEEDED] I have no way to test this right now.
Fixes #14640
```release-note
`podman machine init --now` now respects the proxy environment variables like `podman machine start`.
```
> podman machine init --now: respect proxy envs

- cmd/podman/machine/list.go
- pkg/machine/e2e/list_test.go
A small bug fix - closes #14682.
It seems like previously if `--format` was changed then `listFlag.noHeading` is changed accordingly however `printHeader` is used to determine whether to print header or not.
```release-note
None
```
> Fix machine list: --format implies --noheading

- test/system/150-login.bats
- test/system/500-networking.bats
- test/system/helpers.bash
The test must ensure that all ports in the range are free not just
the first. This flakes often because port 5355 is always in use by
systemd-resolved on fedora.
Fixes #14716
```release-note
None
```
> Fix "podman run port forward range" flake

- libpod/container_exec.go
- libpod/events.go
- libpod/events/config.go
- libpod/events/events.go
- libpod/events/journal_linux.go
- libpod/healthcheck.go
- pkg/domain/entities/events.go
- test/apiv2/27-containersEvents.at
- test/e2e/events_test.go
Previously, health status events were not being generated at all. Both
the API and `podman events` will generate health_status events.
```
{"status":"health_status","id":"ae498ac3aa6c63db8b69a37583a6eae1a9cefbdbdbeeadcf8e1d66d745f0df63","from":"localhost/healthcheck-demo:latest","Type":"container","Action":"health_status","Actor":{"ID":"ae498ac3aa6c63db8b69a37583a6eae1a9cefbdbdbeeadcf8e1d66d745f0df63","Attributes":{"containerExitCode":"0","image":"localhost/healthcheck-demo:latest","io.buildah.version":"1.26.1","maintainer":"NGINX Docker Maintainers \u003cdocker-maint@nginx.com\u003e","name":"healthcheck-demo"}},"scope":"local","time":1656082205,"timeNano":1656082205882271276,"HealthStatus":"healthy"}
```
```
2022-06-24 11:06:04.886238493 -0400 EDT container health_status …
```
> Show Health Status events

- pkg/domain/filters/volumes.go
- test/e2e/volume_ls_test.go
- test/system/160-volumes.bats
closes #14583  
```release-note
Added Regexp support to filtering volumes by name
```
> Use Regexp in volume ls --filter name

- pkg/machine/qemu/machine.go
Currently podman machine list never shows the starting state.
Fixes: https://github.com/containers/podman/issues/14738
No
```release-note
None
```
> Show starting state when machine is starting

- pkg/domain/infra/abi/pods.go
- test/system/200-pod.bats
the "pod ps" command first retrieves the list of all pods, then
iterates over the list to inspect each pod.  This introduce a race
since a pod could be deleted in the meanwhile by another process.
Solve it by ignoring the define.ErrNoSuchPod error.
Closes: https://github.com/containers/podman/issues/14736
```release-note
Now podman ps doesn't race with podman pod rm
```
> pod: ps does not race with rm

- pkg/api/handlers/compat/containers.go
- test/apiv2/20-containers.at
Some background for this PR is in discussion #14641. In short, ever so often a container inspect will return a `status.status` of `initialized` from the Docker compat socket.
From the discussion I found these lines which tries to fix a "configured" status to "created".
https://github.com/containers/podman/blob/c936d1e61154b6826e9d8df46e9660aba6c86cfe/pkg/api/handlers/compat/containers.go#L291-L294
However, commit 141de8686289 (Revamp Libpod state strings for Docker compat) removed the "configured" return value from the `String()` method called on line 291 above. Thus, making the `if` check redundant as it will never hit. But the same commit also introduces a return for "initialized" which this `if` should probably have been adapted for.
Tests added to prevent a regression
Signed-off-by: …
> Docker compat returning unknown "initialized" for `status.status`

- cmd/podman/root.go
- test/e2e/checkpoint_test.go
[cfg.RuntimePath](https://github.com/containers/podman/blob/8e88abda85f7bf44b6857ad5d62c8ef58206fce5/cmd/podman/root.go#L146) was set to default runtime, so the empty string check fails. Instead we could check if the flag was changed.
It is a minor bug that was already mentioned in the issue below, so I didn't think I should create a new issue. Please let me know if this is a requirement.
Fixes: #11945
Signed-off-by: Zeyad Yasser <zeyady98@gmail.com>
```release-note
None
```
> Fix runtime check during restore

- go.mod
- go.sum
- vendor/github.com/containers/common/libimage/normalize.go
- vendor/github.com/containers/common/libimage/platform.go
- vendor/github.com/containers/common/libimage/pull.go
- vendor/github.com/containers/common/libimage/runtime.go
- vendor/modules.txt
Pull in fixes for platform checks to silence annoying warnings when
pulling images by platforms using uname values.
Fixes: #14669
```release-note
None
```
> vendor containers/common

- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
After `podman machine stop` successfully exits the `qemu` process may still be running, which can cause issues, especially if an attempt is made to start the machine again.
In my trials I found the `qemu` process normally takes about 1s to exit after `podman machine stop`, which means `podman machine stop && podman machine start` can create problems, for example. I've also found that the `qemu` process could hang from time to time after an attempted stop. I'm able to reproduce this most reliably by stopping the machine while a container is running, it then takes about 90s for the `qemu` process to exit. This last example should be an issue on its own, but all this to say `podman machine stop` should only exit after `qemu` does.
In this PR we use the `-pidfile` flag when running `qemu` and …
> Make `podman machine stop` wait for qemu to exit

- pkg/bindings/manifests/manifests.go
- pkg/bindings/test/manifests_test.go
- pkg/domain/entities/manifest.go
Bindings already support `Remove` which removes a manifest from the list
following function adds support for removing entire manifest for local
storage.
Similar functionality can be also used indirectly by using `Remove` defined in
image bindings
Closes: https://github.com/containers/podman/issues/14735
```
Bindings: Manifest package now exposes ManifestRemove to remove manifest list from local storage
```
> bindings: Add support for `Delete` for deleting manifest list from local storage.

- contrib/podmanimage/stable/Containerfile
- contrib/podmanimage/testing/Containerfile
- contrib/podmanimage/upstream/Containerfile
Drop a reference as to why the `rpm --setcaps...` line is needed, along
with a `TODO` reminder to check if it's still needed.
```release-note
None
```
> [CI:DOCS] Update podmanimage comment.

- cmd/podman/machine/init.go
- cmd/podman/machine/inspect.go
- cmd/podman/machine/list.go
- cmd/podman/machine/machine.go
- cmd/podman/machine/rm.go
- cmd/podman/machine/set.go
- cmd/podman/machine/ssh.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- docs/source/markdown/podman-machine-init.1.md
- docs/source/markdown/podman-machine-inspect.1.md
- docs/source/markdown/podman-machine-list.1.md
- docs/source/markdown/podman-machine-rm.1.md
- docs/source/markdown/podman-machine-set.1.md
- docs/source/markdown/podman-machine-ssh.1.md
- docs/source/markdown/podman-machine-start.1.md
- docs/source/markdown/podman-machine-stop.1.md
- docs/source/markdown/podman-machine.1.md
- test/e2e/system_reset_test.go
Podman Machine crashes if run as root, as we need the UID of the core user to match the UID of the user on the host. If the user on the host is root, the core UID and the Root UID collide, causing a the VM not to boot.
```release-note
Allow `podman machine` to only be run rootless, as the VM refuses to boot when run as root. 
```
> Only allow Rootless runs of Podman Machine

- libpod/container_api.go
- libpod/container_internal.go
- libpod/runtime_ctr.go
- test/system/050-stop.bats
- test/system/055-rm.bats
This bug was introduced in https://github.com/containers/podman/pull/8906.
When we use `podman rm/restart/stop/kill etc...` command to
the container running with `--rm`, the OCI runtime directory
remains at `/run/<runtime name>` (root user) or
`/run/user/<user id>/<runtime name>` (rootless user).
This bug could cause other bugs.
For example, when we checkpoint the container running with
`--rm` (podman checkpoint --export) and restore it
(podman restore --import) with crun, error message
`Error: OCI runtime error: crun: container '<container id>'
already exists` is outputted.
This error is caused by an attempt to restore the container with
the same container ID as the remaining OCI runtime's container ID.
Therefore, I fix that the `cleanupRuntime()` function runs to
remove the OCI runtime …
> Fix: Prevent OCI runtime directory remain

- pkg/api/handlers/libpod/images.go
- pkg/api/server/register_images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_remove_options.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/manifest_test.go
ImagesBatchRemoval and ImageRemoval now honors and accepts
`LookupManifest` parameter which further tells libimage to resolve to
manifest list if it exists instead of actual image.
Following PR also makes `podman-remote manifest rm` functional which was
broken till now.
Closes: https://github.com/containers/podman/issues/14763
```release-note
* podman-remote manifest rm now actually removes only manifest list and not image
* libpod REST API for image removal now supports additional LookupManifest parameter
which allows end-users to remove manifest instead of images.
```
> api,images: add support for `LookupManifest` to `Image removal` REST API

- cmd/podman/system/service_abi.go
- utils/utils_supported.go
at startup, when running on a cgroup v2 system, check if the current process is running in the root cgroup and move it to a sub-cgroup, otherwise Podman is not able to create cgroups and move processes there.
Closes: https://github.com/containers/podman/issues/14573   
[NO NEW TESTS NEEDED] it needs nested podman
```release-note
podman system service automatically creates a sub-cgroup when running in the root cgroup
```
> service: do not run under the root cgroup

- pkg/specgenutil/specgen.go
- pkg/specgenutil/specgenutil_test.go
- test/system/030-run.bats
Fix the parse for the cgroup devices rule to correctly handle the
wildcard syntax for the device major.
Also make sure the device major and minor are not negative numbers.
```release-note
Podman parses correctly the wildcard for the device major number to `--device-cgroup-rule`
```
> specgen: fix parsing of cgroup devices rule

- pkg/specgen/volumes.go
- test/e2e/run_volume_test.go
When mounting paths as overlay mounts we end up passing source as is to
`lowerdir` options, resolve all relative paths in such cases for overlay
mounts.
Closes: https://github.com/containers/podman/issues/14797
```release-note
Allows users to use relative values with mounting paths directly as overlay. Example `-v .:/target:O`
```
> overlay,mount: convert source to absolute path for `overlay` mounts of paths

- docs/tutorials/remote_client.md
This flag does not work (e.g. on Fedora 36) and not appear to be required (anymore?).
```release-note
None
```
> [CI:DOCS] Remove -s from systemctl enable --now sshd

- test/e2e/pod_create_test.go
the test is not doing what it believes to do.  The containers are not
supposed to be joining the infra container cgroup.
In addition, the result is validated only on cgroup v1 systems (that
are not used in the CI).
We may want to add it back, or a variant of it, once the
--device-read-bps option applies to the pod parent cgroup.
```release-note
None
```
> test: drop pod-create --device-read-bps test

- cmd/podman-mac-helper/install.go
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-pod-clone.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container.go
- pkg/k8s.io/apimachinery/pkg/api/resource/amount.go
- pkg/k8s.io/apimachinery/pkg/api/resource/math.go
- pkg/specgen/volumes.go
- pkg/specgenutil/volumes.go
- test/e2e/play_kube_test.go
- test/e2e/run_test.go
- test/system/060-mount.bats
- troubleshooting.md
> [CI:DOCS] Fix spelling "read only" -> "read-only"

- test/e2e/common_test.go
- test/e2e/run_aardvark_test.go
The retry logic in digshort() did not work because dig always exits with
0 even when the domain name is not found. To make it work we have to
check the standard output.
We work on fixing the underlying issue in aardvark/netavark but
this will take more time.
Fixes #14173
Fixes #14171
```release-note
None
```
> fix flake in aardvark tests

- libpod/runtime.go
- libpod/runtime_cstorage.go
- libpod/runtime_ctr.go
- libpod/runtime_img.go
- libpod/runtime_migrate.go
- libpod/runtime_pod.go
- libpod/runtime_pod_linux.go
- libpod/runtime_renumber.go
- libpod/runtime_volume.go
- libpod/runtime_volume_linux.go
- pkg/api/handlers/compat/containers.go
- pkg/api/handlers/libpod/pods.go
- pkg/api/handlers/libpod/volumes.go
- pkg/api/handlers/utils/errors.go
- pkg/bindings/manifests/manifests.go
- pkg/domain/infra/abi/containers.go
- pkg/errorhandling/errorhandling.go
- pkg/errorhandling/errorhandling_test.go
- utils/utils.go
We now use the golang error wrapping format specifier `%w` instead of the deprecated github.com/pkg/errors package.
Part of #14784 
```release-note
None
```
> libpod/runtime: switch to golang native error wrapping

- cmd/podman/containers/clone.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- pkg/specgen/generate/container.go
- pkg/specgen/specgen.go
- test/e2e/build/Containerfile.with-platform
- test/e2e/run_test.go
Following PR adds support for running containers from a manifest list
present on localstorage. Before this PR podman only supports running
containers from valid images but not from manifest list.
So `podman run -it --platform <some> <manifest-list> command` should
become functional now and users should be able to resolve images on the
bases of provided `--platform` string.
Example
```
podman manifest create test
podman build --platform linux/amd64,linux/arm64 --manifest test .
podman run --rm --platform linux/arm64/v8 test uname -a
```
Closes: https://github.com/containers/podman/issues/14773
```release-note
Add supports for running containers from manifest list with --platform
```
> specgen,run: support running container from valid manifest list using `--platform`

- hack/podman-registry-go/registry.go
- test/e2e/common_test.go
- test/testvol/main.go
- utils/ports.go
- utils/utils_supported.go
- utils/utils_windows.go
We now use the golang error wrapping format specifier `%w` instead of the deprecated github.com/pkg/errors package.
```release-note
None
```
> hack/test/utils: switch to golang native error wrapping

- .cirrus.yml
- hack/golangci-lint.sh
- hack/install_golangci.sh
- test/e2e/search_test.go
As release branches age, it becomes less valuable to execute
comprehensive CI testing.  Further given occasional flakes, it becomes
more burdensome to maintain.  Trim back some non-essential testing tasks
for improved long-term reliability and reduced maintenance.
```release-note
None
```
> [v3.0.1-rhel] Cirrus: Prune testing tasks for long-term reliability

- pkg/machine/config_test.go
- pkg/machine/qemu/config_test.go
- pkg/machine/qemu/machine_test.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/play_test.go
int can be 32 or 64 bit depending on the architecture.
The total memory is int64 so we have to use int64 for the value as
well otherwise we get an overflow on 32 bit systems.
Fixes https://github.com/containers/podman/issues/14819
```release-note
Fixed a bug with podman play kube on 32 bit systems where the total memory was calculated incorrectly.
```
> envVarValueResourceFieldRef: use int64 for value

- .cirrus.yml
- hack/install_golangci.sh
- test/e2e/search_test.go
As release branches age, it becomes less valuable to execute
comprehensive CI testing.  Further given occasional flakes, it becomes
more burdensome to maintain.  Trim back some non-essential testing tasks
for improved long-term reliability and reduced maintenance.
```release-note
None
```
> [v3.4] Cirrus: Prune testing tasks for long-term reliability

- libpod/container_api.go
- test/system/130-kill.bats
Make sure `Sync()` handles state transitions and exit codes correctly.
The function was only being called when batching which could render
containers in an unusable state when running concurrently with other
state-altering functions/commands since the state must be re-read from
the database before acting upon it.
Fixes: #14761
No release notes needed as it's fixing a bug that hasn't been released yet.
```release-note
None
```
> Sync: handle exit file

- pkg/machine/qemu/machine.go
Connecting with `podman machine ssh` can results in the following warning:
```
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_CA.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_CA.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_CA.UTF-8)
/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_CA.UTF-8)
```
Best would probably be to remove `LC_ALL` (and other locale and lang env vars) from `/etc/ssh/sshd_config.d/50-redhat.conf` in the CoreOS image, but I'm not terribly sure how, so this is a quick alternative.
```release-note
Silence setlocale warning in machine ssh
```
> Silence setlocale warnings from `podman machine ssh`

- cmd/podman/system/df.go
- test/e2e/system_df_test.go
Previously, `podman system df --format "{{json .}}"` would not output
`Size` and `Reclaimable` like `podman system df` would.
```
{"Type":"Images","Total":5,"Active":0,"Size":39972240,"Reclaimable":39972240}
{"Type":"Containers","Total":0,"Active":0,"Size":0,"Reclaimable":0}
{"Type":"Local Volumes","Total":0,"Active":0,"Size":0,"Reclaimable":0}
```
Closes: #14769
```release-note
Fixed a bug where `podman system df --format "{{ json . }}"` would not output the `Size` and `Reclaimable` fields (#14769)
```
> Podman system df JSON format outputs `Size` and `Reclaimable`

- libpod/define/healthchecks.go
- libpod/healthcheck.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgenutil/specgen.go
- test/compose/disable_healthcheck/docker-compose.yml
- test/compose/disable_healthcheck/tests.sh
Previously, if a container had healthchecks disabled in the
docker-compose.yml file and the user did a `podman inspect <container>`,
they would have an incorrect output:
```
"Healthcheck":{
"Test":[
"CMD-SHELL",
"NONE"
],
"Interval":30000000000,
"Timeout":30000000000,
"Retries":3
}
```
After a quick change, the correct output is now the result:
```
"Healthcheck":{
"Test":[
"NONE"
]
}
```
Closes: #14493
```release-note
Fixed a bug where disabling healthchecks in a docker-compose.yml file was improperly handled (#14493)
```
> Docker-compose disable healthcheck properly handled

- cmd/podman/common/completion.go
- cmd/podman/pods/unpause.go
- pkg/domain/infra/abi/pods.go
- pkg/domain/infra/tunnel/pods.go
- test/e2e/pod_pause_test.go
Update the podman pod unpause to only show the paused
containers with autocomplete.
Fix a typo in the help command.
Update the unpause function to only attempt an unpause
on pasued pods instead of all the pods.
Update the tests accordingly.
```release-note
podman pod unpause only shows paused pods when using autocomplete
```
> Fix podman pod unpause TODO

- hack/install_golangci.sh
The golangci installer (which is curl pipe sh, ewww) installs
into $BINDIR, which it gets from the caller's environment.
Make sure we set it explicitly.
```release-note
None
```
> golangci install: explicitly set BINDIR

- cmd/podman/common/create.go
- cmd/podman/containers/create.go
- cmd/podman/pods/create.go
- docs/source/markdown/podman-pod-clone.1.md
- docs/source/markdown/podman-pod-create.1.md
- libpod/container.go
- libpod/container_inspect.go
- libpod/define/pod_inspect.go
- libpod/pod_api.go
- pkg/specgen/container_validate.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/generate/pod_create.go
- test/e2e/pod_clone_test.go
- test/e2e/pod_create_test.go
add support for the --uts flag in pod create, allowing users to avoid
issues with default values in containers.conf.
uts follows the same format as other namespace flags:
--uts=private (default), --uts=host, --uts=ns:PATH
resolves #13714
```release-note
Users can now specify the --uts option when creating pods, specifying a pod wide uts mode for all containers.
```
> podman pod create --uts support

- docs/play_kube_support.md
Update play kube docs with supported fields for
configMap and deployment kinds.
Fixes https://github.com/containers/podman/pull/14318
```release-note
Update supported kube fields for configMap and deployment kind in play kube docs
```
> Update play kube docs

- cmd/podman/machine/info.go
- cmd/podman/machine/machine.go
- docs/source/markdown/podman-machine-info.1.md
- docs/source/markdown/podman-machine.1.md
- pkg/machine/config.go
- pkg/machine/e2e/config_info.go
- pkg/machine/e2e/info_test.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
Add podman machine info command, which displays info about the machine
host as well as version info.
```release-note
Add podman machine info command, which displays info about the machine
host as well as version info.
```
> Podman machine info

- test/system/500-networking.bats
- test/system/helpers.bash
Wrong variable.
Fixes: #14854
```release-note
None
```
> port forward range test: fix an oops

- docs/source/markdown/podman-machine-init.1.md
- pkg/machine/qemu/machine.go
Yes, but defaults are unchanged.
```release-note
Support specification of the 9p security model for `podman machine` volumes ([#13784](https://github.com/containers/podman/issues/13784)).
```
Please see this bug for background information:
https://github.com/containers/podman/issues/13784
Thanks,
Corey
> make 9p security model configurable; document

- .cirrus.yml
- Makefile
- contrib/cirrus/cirrus_yaml_test.py
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
The podman-machine integration tests are designed to execute on
bare-metal, since they perform significant work with virtual-machines.
This test is costly to run at scale, so it is limited to being manually
triggered by developers (for now).  A 'trigger' button will appear in the
task status page of the Github WebUI once all test dependencies are met.
In the Cirrus-CI WebUI, there is also a 'pre-trigger' button that may be
pressed if a developer doesn't wish to wait. Also:
* Add a `localmachine` target in the `Makefile` on the off-chance
developers wish to execute locally.  Update the `ginkgo-run` target
to accommodate re-use by the new `localmachine` target.
* Exclude `podman_machine` task from `success` dependency verification.
This also involves adding an exception to …
> Cirrus: Add podman-machine integration test

- libpod/container_internal_linux.go
- test/e2e/run_volume_test.go
Backport #14582 to the v4.1.1-rhel branch per customer request.
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2097694
```release-note
None
```
> [v4.1.1-rhel] container: do not create .containerenv with -v SRC:/run

- cmd/podman/machine/list.go
- pkg/domain/entities/machine.go
- pkg/machine/e2e/list_test.go
- pkg/machine/qemu/machine.go
machine test: fix endless loop in test
The problem is that this could loop forever as long as podman start doe
snot exit (which could happen due bugs). Also since there no timeout
between the machine list calls the test is using the full cpu and this
causes the system to slow down making the machine start command even
slower. IMO it is enough to only check the status every three seconds.
pkg/machine/e2e: do not import from cmd/podman
It should be avoided to import cmd/podman/... packages from outside of
cmd/podman. This can lead in weird hard to debug import paths but also
can have negative consequences when imported in unit tests. In this case
it will set XDG_CONFIG_HOME and thus the machine tests this dir over the
tmp HOME env variable which is set at a later point. This caused machine …
> pkg/machine/e2e: do not import from cmd/podman

- hack/podman-registry
- test/e2e/libpod_suite_test.go
- test/e2e/manifest_test.go
manifest_test:authenticated_push() is the final test left to
fix before merging #14397. The reason it's failing _seems_ to be
that podman is running with a mix of netavark and CNI, and
that _seems_ to be because this test invokes hack/podman-registry
which invokes plain podman without whatever options used in e2e.
Starting a registry directly from the test is insane: there is
no reusable code for doing that (see login_logout_test.go and
push_test.go. Yeesh.)
Solution: set $PODMAN, by inspecting the podmanTest object
which includes both a path and a list of options. podman-registry
will invoke that. (It will also override --root and --runroot.
This is the desired behavior).
Also: add cleanup. If auth-push test fails, stop the registry.
Also: add a sanity check to podman-registry script, …
> manifest_test: safer registry setup and teardown

- cmd/podman/common/completion.go
- cmd/podman/common/create.go
- docs/source/markdown/podman-build.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
Make sure that the docs for pull policies is consistent with Buildah and
reflects the implementation.
Further improve the help messages and auto completions.
Fixes: #14846
```release-note
Improve the documentation of pull policies for `podman-{build,create,run}`.
```
> improve pull-policy documentation

- test/apiv2/01-basic.at
- version/version.go
Docker bumped their API, so we should do the same.
Fixes #14204
```release-note
The Compat API now supports the v1.41 API.
```
> Bump Compat API maximum version to v1.41

- cmd/podman/containers/wait.go
- pkg/api/handlers/utils/containers.go
- pkg/domain/infra/abi/containers.go
- test/system/035-logs.bats
Podman wait should not be defaulting to just stopped.  By default
wait API waits for stopped and exited.  We should not override this on
the client side.
```release-note
podman wait an now take multiple --condition flags
```
> podman wait can take multiple conditions

- docs/source/markdown/podman-info.1.md
* Add example "Extracting the list of container registries with a Go template".
(The example was already present but in a much shorter form)
* Add example "Extracting the list of container registries from JSON with jq".
* Add shell completion instructions
```release-note
None
```
> [CI:DOCS] podman-info.1.md: update examples (now also shell completion and jq)

- cmd/podman/networks/prune.go
- cmd/podman/utils/utils.go
- pkg/domain/entities/network.go
- pkg/domain/entities/system.go
- pkg/domain/infra/abi/system.go
- pkg/domain/infra/tunnel/network.go
- test/e2e/prune_test.go
Refactored the networkPrune function to improve readability.
This commit unifies the structure containing the pruned network name
from `entities.NetworkPruneReport` to `reports.PruneReport`.
```release-note
None
```
> Refactored networkPrune function

- libpod/container_api.go
- libpod/container_internal.go
- libpod/oci_conmon_linux.go
- test/system/130-kill.bats
Please refer to the individual commits for change descriptions.  I am fairly confident it'll fix https://github.com/containers/podman/issues/14859 but lets see what CI (and long-term flakes) tell.
@mheon PTAL
No release notes needed as it's fixing unreleased issue.
```release-note
None
```
> exit code improvements

- libpod/kube.go
- pkg/domain/infra/abi/generate.go
- test/e2e/generate_kube_test.go
If a pod is created with ipc sharing, allow adding
separate ports for each container to the kube yaml
and also set the pod level hostname correctly.
Fixes https://github.com/containers/podman/issues/13030
```release-note
Set ports and hostname correctly in the generated kube yaml.
```
> Add ports and hostname correctly in kube yaml

- libpod/oci_conmon_linux.go
Empty path to runtime binary was printed instead of a real path.
Before fix:
TRAC[0000] found runtime ""
TRAC[0000] found runtime ""
After:
TRAC[0000] found runtime "/usr/bin/crun"
TRAC[0000] found runtime "/usr/bin/runc"
Signed-off-by: Mikhail Khachayants <khachayants@arrival.com>
```release-note
None
```
> fix wrong log message on Trace level

- contrib/cirrus/logformatter
Reason: task IDs are unique and permanent; linking by
build ID and task name is non-unique, because Re-run.
Fixes: #14863
```release-note
None
```
> logformatter: link by *task ID*, not build ID

- pkg/machine/qemu/machine.go
qemu fails when the same `fw_cfg` options is used more than once.
Since the current logic always adds a new option on each machine load
this will fail on the second start.
We can fix this by checking if the option is already set and replace but
I think it is easier to just not commit the option in the config and add
it dynamically on start. User that hit this bug have to recreate the
machine.
Fixes #14636
Fixes #14837
```release-note
Fixed a bug where podman machine with proxy variables could not be started more than once.
```
> podman machine: do not commit proxies into config file

- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
Closes #14906
```release-note
None
```
> [CI:DOCS] man pages: remove non-existent option builtin-volume

- .cirrus.yml
- contrib/cirrus/runner.sh
We're still not testing runc in CI (#14833), and it may be weeks
or months before we can, due to criu/glibc nightmare, but one day
we'll be back on track, then later on we'll update VMs again,
and screw it up, and lose runc, and not notice, and RHEL will
break, and oh noes headless chicken again, repeat repeat.
We can do better. Use .cirrus.yml to explicitly define which
VMs should use which runtimes, and enforce it early in the
CI build step. This should never fail (uh huh) in a PR,
only in one of the update-VM PRs.
```release-note
None
```
> [CI:DOCS] CI: sanity check for desired runtime

- cmd/podman/common/create.go
- docs/source/markdown/podman-container-clone.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
- test/e2e/run_cpu_test.go
Add support for -c as an alias for --cpu-shares to be compatible with
Docker.
```release-note
Add support for -c as an alias for --cpu-shares to be compatible with Docker.
```
> Docker uses "-c" to mean "--cpu-shares" in create and run

- pkg/machine/e2e/list_test.go
Fix last machine test
The list --format json test case had a typo like error.
```release-note
None
```
> Fix machine test for list

- docs/source/markdown/podman-container-clone.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
These three man pages have some similar text.
https://github.com/containers/podman/blob/edbfbfcda18f57c89a9657ba453c51977a7796a9/docs/source/markdown/podman-run.1.md?plain=1#L247-L256
https://github.com/containers/podman/blob/edbfbfcda18f57c89a9657ba453c51977a7796a9/docs/source/markdown/podman-create.1.md?plain=1#L231-L239
https://github.com/containers/podman/blob/edbfbfcda18f57c89a9657ba453c51977a7796a9/docs/source/markdown/podman-container-clone.1.md?plain=1#L91-L99
I assume podman-run.1.md is the correct one (i.e. using __--cpu-shares=__ instead of __-c=__)
```release-note
None
```
> [CI:DOCS] man pages: replace -c with --cpu-shares

- docs/MANPAGE_SYNTAX.md
- docs/source/markdown/podman-build.1.md
- docs/source/markdown/podman-commit.1.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-generate-kube.1.md
- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-image-trust.1.md
- docs/source/markdown/podman-images.1.md
- docs/source/markdown/podman-import.1.md
- docs/source/markdown/podman-info.1.md
- docs/source/markdown/podman-kube-play.1.md
- docs/source/markdown/podman-machine-info.1.md
- docs/source/markdown/podman-machine-init.1.md
- docs/source/markdown/podman-machine-set.1.md
- docs/source/markdown/podman-manifest-add.1.md
- docs/source/markdown/podman-manifest-annotate.1.md
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-pod-clone.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-pod-inspect.1.md
- docs/source/markdown/podman-push.1.md
- docs/source/markdown/podman-run.1.md
- docs/source/markdown/podman-stats.1.md
- docs/source/markdown/podman-system-connection-add.1.md
- docs/source/markdown/podman-system-connection-remove.1.md
- docs/source/markdown/podman-volume-create.1.md
- docs/source/markdown/podman-volume-inspect.1.md
- docs/source/markdown/podman-volume-ls.1.md
- hack/xref-helpmsgs-manpages
Followup to #14906, in which a nonexistent option was found
in a man page. The xref script was designed to catch that,
but I was too lax in my parsing: the option was documented
using wrong syntax, and the script didn't catch it.
Solution: do not allow *any* unrecognized cruft in the
option description lines. And fix all improperly-written
entries to conform to the rule:
**--option**=*value(s)*
Two asterisks around option, which must have two dashes. One
asterisk around value(s).
This is going to cause headaches for some people adding new
options, but I don't think I can fix that: there are many
factors that make an unparseable line. Adding 'hint' code
would make the script even more complex than it is. I have
to assume that our contributors are smart enough to look
at surrounding context …
> [CI:DOCS] man page checker: enforce stricter options format

- cmd/podman/containers/stop.go
- cmd/podman/validate/args.go
- docs/source/markdown/podman-stop.1.md
- pkg/api/handlers/compat/containers_stop.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- pkg/domain/infra/tunnel/helpers.go
- test/e2e/stop_test.go
Filter flag is added for podman stop and podman --remote stop. Filtering logic is implemented in
getContainersAndInputByContext(). Start filtering can be manipulated to use this logic as well to limit redundancy.
Signed-off-by: Karthik Elango <kelango@redhat.com>
```release-note
Add --filter flag for podman stop
```
> Podman stop --filter flag

- .cirrus.yml
Instead of requiring developers to search for a magic button, make the
task trigger at the time a special PR label is added.  Update comments
accordingly.
```release-note
None
```
> Cirrus: Trigger podman-machine task by label

- docs/tutorials/README.md
- docs/tutorials/socket_activation.md
Closes #14908
```release-note
None
```
> [CI:DOCS] Add socket_activation.md

- cmd/podman/images/pull.go
- docs/source/markdown/podman-pull.1.md
- test/e2e/pull_test.go
I added the shorthand option for `podman pull --all-tags`. Like Docker,
Podman can now do `podman pull -a`.
Addresses a task from #14917
```release-note
Added `podman pull -a` as a shorthand for `podman pull --all-tags`
```
> Podman pull --all-tags shorthand option

- pkg/machine/config.go
- pkg/machine/fcos.go
- pkg/machine/fedora.go
- pkg/machine/pull.go
When initing machines, we download a machine image, and uncompress and
copy the image for the actual vm image. When a user constantly pulls new
machines, there may be a buildup of old, unused machine images. This
commit cleans ups the unused cached images.
Changes:
- If the machine is pulled from a URL or from the FCOS releases, we pull
them into XDG_DATA_HOME/containers/podman/machine/vmType/cache
- Cache cleanups only happen if there is a cache miss, and we need to
pull a new image
- For Fedora and FCOS, we actually use the cache, so we go through the
cache dir and remove any images older than 2 weeks (FCOS's release cycle), on a cache miss.
- For generic files pulled from a URL, we don't actually cache, so we
delete the pulled file immediately after creating a machine image
- For …
> Clean up cached machine images

- libpod/runtime_volume_linux.go
NFS Servers will thrown ENOTSUPP error if you attempt to
chown a directory to the same UID and GID as the directory
already has. If volumes are stored on NFS directories this
throws an ugly error and then works on the next try.
Bottom line don't chown directories that already have the correct
UID and GID.
Fixes: https://github.com/containers/podman/issues/14766
[NO NEW TESTS NEEDED] Difficult to setup an NFS Server in testing.
```release-note
None
```
> Use SafeChown rather then chown for volumes on NFS

- pkg/machine/fedora.go
- pkg/machine/pull.go
- Also save the file using this convention.
- Change the general pull mechanism to print the local file
as opposed to the remote to enable this - no change in
observed behavior on mac
```release-note
NONE
```
> Improve download message on Windows

- .cirrus.yml
We are not shipping podman4 on f35, so it's not worth CI time at
this point.
@cevich PTAL
/cc @containers/podman-maintainers 
```release-note
None
```
> Cirrus: comment out f35 for podman4

- test/system/250-systemd.bats
- test/system/251-system-service.bats
Followup to #14957, which added a new test that doesn't
actually belong in the 250-systemd.bats file. It was
copy-pasted from another test that doesn't belong there.
Move both tests to a new .bats file, because (1) they
need a custom cleanup, and (2) one of the tests should
very definitely run under podman-remote, and the 250
bats file has a global skip_if_remote().
```release-note
None
```
> system tests: new system-service bats file

- cmd/podman/containers/pause.go
- pkg/domain/infra/abi/pods.go
`podman pod pause` doesn't work for cgroups v1 rootless container
as `podman pause` does.
```release-note
None
```
> "podman pod pause" return error if cgroups v1 rootless container

- docs/source/markdown/podman-kube-play.1.md
- libpod/define/annotations.go
- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
Update the init container type default to once instead
of always to match k8s behavior.
Add a new annotation that can be used to change the init
ctr type in the kube yaml.
Fixes https://github.com/containers/podman/issues/14877
```release-note
Add a new annotation to allow users to define the init container type in a kube yaml for podman play kube. Change the default init container type to `once`.
```
> Update init ctr default for play kube

- docs/source/markdown/podman-network-create.1.md
[CI-DOCS]
document the podman network create -o=isolate which allows networks to cut themselves off
from external connections.
resolves #5805
```release-note
document isolate option for network create
```
> [CI:DOCS] document isolate option for network create

- pkg/machine/fedora.go
Small follow-up to  #14962
```release-note
NONE
```
> Fix potential body leak on mid-stream read error when fetching artifact version

- libpod/container_log.go
- libpod/container_log_linux.go
- libpod/events/journal_linux.go
- libpod/events/logfile.go
When running a single podman logs this is not really important since we
will exit when we finish reading the logs. However for the system
service this is very important. Leaking goroutines will cause an
increased memory and CPU ussage over time.
Both the the event and log backend have goroutine leaks with both the
file and journald drivers.
The journald backend has the problem that journal.Wait(IndefiniteWait)
will block until we get a new journald event. So when a client closes
the connection the goroutine would still wait until there is a new
journal entry. To fix this we just wait for a maximum of 5 seconds,
after that we can check if the client connection was closed and exit
correctly in this case.
For the file backend we can fix this by waiting for either the log line
or context …
> fix goroutine leaks in events and logs backend

- test/utils/utils.go
To make debugging easier we should see the command and its output when a
failure happens.
```release-note
None
```
> e2e: show command and output when a timeout happens

- libpod/container_internal_linux.go
- test/e2e/run_passwd_test.go
create the /etc/passwd file is it is missing in the image.
Closes: https://github.com/containers/podman/issues/14966
```release-note
If it is needed, create automatically the /etc/passwd file when it is missing in the image
```
> libpod: create /etc/passwd if missing

- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
It was not obvious enough in the scripts how much of a snowflake this
environment is.  Fix that with lots of capitalized words and asterisks.
```release-note
None
```
> [CI:DOCS] Cirrus: Add prominent gitlab warning

- cmd/podman/common/create.go
- docs/source/markdown/podman-container-clone.1.md
- docs/source/markdown/podman-pod-clone.1.md
- docs/source/markdown/podman-pod-create.1.md
- libpod/define/pod_inspect.go
- libpod/options.go
- libpod/pod.go
- libpod/pod_api.go
- libpod/runtime_pod_linux.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/oci.go
- pkg/specgen/generate/pod_create.go
- pkg/specgenutil/specgen.go
- test/system/200-pod.bats
added the following flags and handling for podman pod create
--memory-swap
--cpuset-mems
--device-read-bps
--device-write-bps
--blkio-weight
--blkio-weight-device
--cpu-shares
given the new backend for systemd in c/common, all of these can now be exposed to pod create.
most of the heavy lifting (nearly all) is done within c/common. However, some rewiring needed to be done here
as well!
```release-note
expose resource limts flags: 
--memory-swap
--cpuset-mems
--device-read-bps
--device-write-bps
--blkio-weight
--blkio-weight-device 
--cpu-shares
to podman pod create
```
> resource limits for pods

- pkg/api/handlers/libpod/images.go
- pkg/api/handlers/libpod/images_push.go
- pkg/api/server/register_images.go
- pkg/bindings/images/images.go
- pkg/bindings/images/push.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_push_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/push_test.go
`podman-remote push` has shown absolutely no progress at all. Fix that
by doing essentially the same as the remote-pull code does.
The get-free-out-of-jail-card for backwards compatibility is to let the
`quiet` parameter default to true.  Since the --quioet flag wasn't
working before either, older Podman clients do not set it.
Also add regression tests to make sure we won't regress again.
Fixes: #14971
```release-note
Fix a bug where `podman-remote push` would not print any progress.
```
@mheon a v4.2 candidate
> remote push: show copy progress

- cmd/podman/machine/info.go
- cmd/podman/machine/ssh.go
- hack/golangci-lint.sh
- pkg/domain/entities/machine.go
- pkg/machine/e2e/basic_test.go
- pkg/machine/e2e/config_basic_test.go
- pkg/machine/e2e/config_info_test.go
- pkg/machine/e2e/config_init_test.go
- pkg/machine/e2e/config_inspect_test.go
- pkg/machine/e2e/config_list_test.go
- pkg/machine/e2e/config_rm_test.go
- pkg/machine/e2e/config_set_test.go
- pkg/machine/e2e/config_ssh_test.go
- pkg/machine/e2e/config_start_test.go
- pkg/machine/e2e/config_stop_test.go
- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/info_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/e2e/list_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/e2e/rm_test.go
- pkg/machine/e2e/set_test.go
- pkg/machine/e2e/ssh_test.go
- pkg/machine/e2e/start_test.go
- pkg/machine/e2e/stop_test.go
Rename all files to _test.go and rename the package to e2e_test. This
makes the linter less strict about things like dot imports.
Add some unused nolint directives to silence some warnings, these can be
used to find untested options so someone could add tests for them.
Fixes #14996
This also contains some more fixes for the machine tests, see the commits.
```release-note
None
```
> enable linter for pkg/machine/e2e

- pkg/api/handlers/compat/images.go
- pkg/api/handlers/compat/images_push.go
Progress bar in JSONMessage is missing compared to docker output both in
pull and push. Additionaly, pull was not using JSONMessage while push
was using this type.
Signed-off-by: Jakub Guzik <jguzik@redhat.com>
```release-note
Compat REST API: image push and pull have now progress bars
```
> Compat API: unify pull/push and add missing progress info

- .cirrus.yml
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
- test/e2e/build_test.go
- test/e2e/checkpoint_image_test.go
- test/e2e/checkpoint_test.go
- test/e2e/info_test.go
- test/e2e/kill_test.go
- test/e2e/manifest_test.go
- test/e2e/network_connect_disconnect_test.go
- test/e2e/pod_create_test.go
- test/e2e/run_test.go
- test/system/005-info.bats
- test/system/030-run.bats
- test/system/160-volumes.bats
- test/system/170-run-userns.bats
- test/system/200-pod.bats
- test/system/251-system-service.bats
- test/system/400-unprivileged-access.bats
- test/system/500-networking.bats
- test/utils/utils.go
...and enable the at-test-time confirmation, the one that
double-checks that if CI requests runc we actually use runc.
This exposed a nasty surprise in our setup: there are steps to
define $OCI_RUNTIME, but that's actually a total fakeout!
OCI_RUNTIME is used only in e2e tests, it has no effect
whatsoever on actual podman itself as invoked via command
line such as in system tests. Solution: use containers.conf
Given how fragile all this runtime stuff is, I've also added
new tests (e2e and system) that will check $CI_DESIRED_RUNTIME.
Image source: https://github.com/containers/automation_images/pull/146
Since we haven't actually been testing with runc, we need
to fix a few tests:
- handle an error-message change (make it work in both crun and runc)
- skip one system test, "survive service …
> Bump VMs, to Ubuntu 2204 with cgroups v1

- pkg/api/handlers/compat/networks.go
- test/apiv2/35-networks.at
- test/compose/test-compose
Docker uses "bridge" as default network name so some tools expect this
to work with network list or inspect. To fix this we change "bridge" to
the podman default ("podman") name.
Fixes #14983
```release-note
The network endpoints for the docker compat API will now correctly use "bridge" as default network name.
Networks created via the docker compat API are now always isolated from each other (e.g. network1 cannot connect to network2) to match the docker behaviour. 
```
> compat api: allow default bridge name for networks

- pkg/api/handlers/libpod/containers_create.go
- test/apiv2/20-containers.at
Make sure containers created via API have the correct umask from
containers.conf set.
Fixes #15036
```release-note
Containers created via the libpod API now use the correct umask from containers.conf.
```
> API: libpod/create use correct default umask

- Makefile
- docs/remote-docs.sh
- docs/source/markdown/podman-import.1.md
podman-remote has a dependency on $(SRCBINDIR), because on
Mac and Windows that's a special dir that may not exist.
But depending on a directory means depending on its mtime,
which changes every time a file in it is updated, which
means running 'make' twice in a row will rebuild podman-remote
for no good reason.
Solution: GNU Make has the concept of "order-only" prerequisites,
precisely for this situation. Use it. Since it's an obscure
feature, document it.
Fixes: #14756
(Also, drive-by edit to remove a stray misdocumented non-option)
```release-note
minor Makefile cleanup to eliminate an unnecessary duplicate build of podman-remote
```
> Makefile: use order-only prereq for podman-remote

- cmd/podman/containers/pause.go
- cmd/podman/containers/unpause.go
- docs/source/markdown/podman-pause.1.md
- docs/source/markdown/podman-unpause.1.md
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/pause_test.go
--latest  : pause/unpause the latest container.
--filter  : pause/unpause the filtered container.
--cidfile : Read container ID from the specified file and pause/unpause the container.
```release-note
User can use podman pause/unpause --latest, --cidfile, --filter option.
```
> Add pause/unpause --latest, --cidfile, --filter

- libpod/container_api.go
Improve the error message when looking up the exit code of a container.
The state of the container may help us track down #14859 which flakes
rarely and is impossible to reproduce on my machine.
```release-note
None
```
@edsantiago @mheon PTAL
> container wait: improve error message

- libpod/runtime_pod_linux.go
do not attempt to lock all containers on pod rm since it can cause
deadlocks when other podman cleanup processes are attempting to lock
the same containers in a different order.
Closes: https://github.com/containers/podman/issues/14929
```release-note
solved a race condition in `podman rm` and `podman pod rm` that could cause adeadlock of the Podman process
```
> libpod: do not lock all containers on pod rm

- cmd/podman/networks/create.go
- cmd/podman/networks/inspect.go
- commands-demo.md
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-kube-play.1.md
- docs/source/markdown/podman-network-connect.1.md
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-network-inspect.1.md
- docs/source/markdown/podman-network-ls.1.md
- docs/source/markdown/podman-network-rm.1.md
- docs/source/markdown/podman-network.1.md
- docs/source/markdown/podman-pod-create.1.md
- docs/source/markdown/podman-run.1.md
- docs/tutorials/basic_networking.md
Most network commands/features work with both netavark and CNI. When
we added added netavark most docs were not vetted and thus still use CNI
network, it should just say network.
Fixes #14990
```release-note
None
```
> [CI:DOCS] docs: remove CNI word where it is not applicable

- test/e2e/common_test.go
- test/e2e/libpod_suite_remote_test.go
- test/e2e/manifest_test.go
- test/utils/utils.go
I honestly do not understand all this extra option parsing here but
there is really no reason to exclude  the option for remote, all the
other global options are also set there.
This fixes a problem with mixed cni/netavark use because the option was
unset.
Fixes #15017
```release-note
None
```
> integration test: fix network backend option with remote

- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- pkg/specgenutil/specgen.go
- test/e2e/run_test.go
- test/system/030-run.bats
pod resource limits introduced a regression where `FinishThrottleDevices` was not called for create/run
```release-note
None
```
> fix container create/run throttle devices

- test/e2e/benchmarks_test.go
And a new one for `run --detach`.
```release-note
None
```
@mheon @Luap99 @rhatdan PTAL
We can add more benchmarks in the future.
> benchmarks: fix create test

- pkg/bindings/test/images_test.go
- test/buildah-bud/apply-podman-deltas
- test/e2e/checkpoint_test.go
- test/e2e/containers_conf_test.go
- test/e2e/run_test.go
- test/system/520-checkpoint.bats
Some refer to issues that are closed. Some, I have no idea if
they're fixed or not, we'll find out in CI.
```release-note
Increase test coverage by removing outdated skips
```
> Semiperiodoc cleanup of obsolete FIXMEs

- pkg/api/handlers/compat/images_build.go
- pkg/api/handlers/compat/images_search.go
- pkg/api/handlers/libpod/images_push.go
- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_images.go
- pkg/api/server/register_manifest.go
- test/apiv2/12-imagesMore.at
- test/apiv2/15-manifest.at
Option defaults in API must be the same as in CLI.
```
% podman image push --help
% podman image pull --help
% podman manifest push --help
% podman image search --help
```
All of these CLI commands them have --tls-verify=true by default:
```
--tls-verify  require HTTPS and verify certificates when accessing the registry (default true)
```
As for `podman image build`, it doesn't have any means to control
`tlsVerify` parameter but it must be true by default.
```release-note
none
```
> Set TLSVerify=true by default for API endpoints

- pkg/machine/qemu/machine.go
Before making / mutable/immutable, podman-machine checks if the mount is
being done in /home or /mnt. However the current check is always going
to be true:
```
!strings.HasPrefix(mount.Target, "/home") || !strings.HasPrefix(mount.Target, "/mnt")
```
is false when mount.Target starts with "/home" and mount.Target starts
with "/mnt", which cannot happen at the same time.
The correct check is:
```
!strings.HasPrefix(mount.Target, "/home") && !strings.HasPrefix(mount.Target, "/mnt")
```
which can also be written as:
```
!(strings.HasPrefix(mount.Target, "/home") || strings.HasPrefix(mount.Target, "/mnt"))
```
The impact is not too bad, it results in extra 'chattr -i' calls which
should be unneeded.
**If** the chattr -i call is unneeded for /mnt and /home, then no, there …
> machine: Fix check which is always true

- cmd/podman/pods/create.go
- docs/source/markdown/podman-pod-create.1.md
- test/e2e/pod_infra_container_test.go
for podman pod create, when we are not sharing any namespaces there is no point for the infra container.
This is especially true since resources have also been decoupled from the container recently.
handle this on the cmd level so that we can still create infra if set explicitly
resolves #15048
```release-note
when using podman pod create --share, if --share=none or --share="" is specified, the pod's infra container is not created
```
> pod create --share none should not create infra

- .cirrus.yml
> [v3.0.1-rhel] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
> [v3.2.3-rhel] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
> [v3.3.1-rhel] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
> [v4.0] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
> [v4.0-rhel] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
> [V3.4.2 rhel] [CI:DOCS] Cirrus: Use the latest imgts container

- .cirrus.yml
> [v3.4] [CI:DOCS] Cirrus: Use the latest imgts container

- pkg/domain/filters/containers.go
- pkg/domain/filters/pods.go
- pkg/domain/filters/volumes.go
- pkg/domain/infra/abi/containers.go
- pkg/util/filters.go
- pkg/util/filters_test.go
- test/e2e/prune_test.go
network and container prune could not handle the label!=... filter. vendor in c/common to fix this and
add some podman level handling to make everything run smoothly
resolves #14182
```release-note
--label=filter!=key now works as expected
```
> prune filter handling

- cmd/podman/containers/rm.go
- cmd/podman/images/rm.go
- cmd/podman/networks/rm.go
- cmd/podman/pods/rm.go
- cmd/podman/volumes/rm.go
- test/system/010-images.bats
- test/system/055-rm.bats
- test/system/160-volumes.bats
- test/system/200-pod.bats
- test/system/500-networking.bats
This Patch will cause podman COMMAND rm --force bogus exit with 0.
This is how Docker works, so Podman should follow this to allow existing
scripts to convert from Docker to Podman.
Fixes: https://github.com/containers/podman/issues/14612
Signed-off-by: wufan <1991849113@qq.com>
```release-note
podman COMMAND rm -f BOGUS: Command will now exit with 0 if the only error is OBJECT does not exist.
```
> When removing objects specifying --force,podman should exit with 0

- cmd/podman/containers/restore.go
- test/e2e/checkpoint_test.go
If there is a match for both container and image, we restore the container.
Fixes: https://github.com/containers/podman/issues/15055
```release-note
podman can restore a container which name is equal to a image name
```
> Fix: Restore a container which name is equal to a image name

- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
This bug is reproduced when we execute the following command:
1. `podman manifest add <manifest list> <images exist on local storage>`
2. `podman manifest push --rm <manifest list> dir:<directory>`
If pushing succeeds, it is expected to remove only a manifest list.
However, manifest list remains on local storage and images are removed.
This commit fixes `podman manifest push --rm` to remove only a manifest list.
Fixes: https://github.com/containers/podman/issues/15033
```release-note
We can use "podman manifest push --rm" to remove the correct manifest list.
```
> Fix: manifest push --rm removes a correct manifest list

- libpod/container_internal.go
Allow the cleanup process (and others) to transition the container from 
`stopping` to `exited`.  This fixes a race condition detected in #14859 
where the cleanup process kicks in _before_ the stopping process can    
read the exit file.  Prior to this fix, the cleanup process left the    
container in the `stopping` state and removed the conmon files, such    
that the stopping process also left the container in this state as it
could not read the exit files.  Hence, `podman wait` timed out (see the
23 seconds execution time of the test [1]) due to the unexpected/invalid
state and the test failed.
Further turn the warning during stop to a debug message since it's a
natural race due to the daemonless/concurrent architecture and nothing
to worry about.
[NO NEW TESTS NEEDED] since we can …
> cleanup: transition from `stopping` to `exited`

- .cirrus.yml
- contrib/cirrus/runner.sh
- test/e2e/config_arm64.go
- test/system/030-run.bats
- test/system/075-exec.bats
- test/system/150-login.bats
- test/system/200-pod.bats
- test/system/260-sdnotify.bats
- test/system/410-selinux.bats
- test/system/helpers.bash
```release-note
None
```
Piggybacks on https://github.com/containers/podman/pull/14569
> Cirrus: enable Fedora 36 aarch64 tasks on EC2

- Makefile
- contrib/cirrus/pr-removes-fixed-skips
- contrib/cirrus/pr-removes-fixed-skips.t
If a PR says "Fixes #123", make sure it removes skips and/or
FIXME comments that reference issue 123.
```release-note
Internal (CI): better cross-checks between PR "Fixes" messages and skips/comments in code
```
> CI: new check for leftover skips/fixmes

- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/system/030-run.bats
Fixes https://github.com/containers/podman/issues/15049
```release-note
podman run --rm ... commands that fail will no longer leave the container behind, it will be removed.
```
> With --rm option remove container if podman run fails

- pkg/api/server/handler_api.go
- pkg/api/server/register_containers.go
- pkg/api/server/register_events.go
- pkg/api/server/register_images.go
Introduce an API Handler wrapper that uses a larger buffer (8k) to help legacy clients that expect a full message to appear  in every read(). While not fully solvable on the server side, it will significantly boost their probability of working.
Resolves #15037
```release-note
none
```
> Use 8k buffer to help clients w/ broken parsing

- cmd/podman/manifest/push.go
- docs/source/markdown/podman-manifest-push.1.md
- docs/source/markdown/podman-push.1.md
- pkg/api/handlers/libpod/images_push.go
- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_push_options.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/images.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
Add flag "--compression-format" to "podman manifest push" both in local/remote mode. Fix usage of flag "--compression-format" for remote "podman image push". Fix usage of flags "--format", "--remove-signatures" in remote "podman manifest push".
Closes #15109.
```release-note
- Added flag "--compression-format" to "podman manifest push"
- Fixed usage of flag "--compression-format" for remote "podman image push".
- Fixed usage of flags "--format" and "--remove-signatures" in remote "podman manifest push"
```
Note about the quality of this pull request: I definitely have no idea what I am doing, this is purely based on copy/pasting ;)
> [Closes 15109] Add flag "--compression-format" to "podman manifest push" (and other fixes)

- docs/source/markdown/podman-volume-import.1.md
Current directories and files stay the same with the current implementation as long as the tarball does not contain a directories or files with the same name.
The added sentence shall clarify that behavior so other users do not need to test this like I did.
Signed-off-by: Felix Stupp <me+github@banananet.work>
```release-note
None
```
> [CI:DOCS] man podman-volume-import: Clarify that merge happens

- test/e2e/manifest_test.go
Verifies https://github.com/containers/common/pull/1105 by adding a new test `inspect manifest and verify OCI annotation`
and old tests should not break.
```release-note
manifest: inspect now supports OCI annotations
```
> manifest,test: `inspect` should contain `OCI` annotations.

- cmd/podman/kube/down.go
- cmd/podman/kube/play.go
- docs/source/markdown/podman-kube-down.1.md
- docs/source/markdown/podman-kube-play.1.md
- docs/source/markdown/podman-kube.1.md
- test/system/700-play.bats
The "podman kube down" reads in a structured file of
Kubernetes YAML and removes pods based on the Kubernetes kind described in the YAML,
similiar to "podman play kube --down". Users will still be able to use
"podman play kube --down" and "podman kube play --down" to
perform the same function.
```release-note
Introduces "podman kube down" which removes pods created by "podman kube play/play kube".
The "--down" flag for "podman kube play --down" can still be used and is now hidden. 
```
> add "podman kube down" command

- test/e2e/mount_rootless_test.go
e2e `mount_rootless_test` did not load `podman binary path` successfully.
This PR fix this problem.
[It] podman unshare podman mount:
```
[+1596s] Running: ... unshare  mount <cid>
[+1596s] Error: exec: no command
[+1596s] output:
```
[It] podman unshare image podman mount:
```
[+1599s] Running: ... unshare  image mount quay.io/libpod/alpine:latest
[+1599s] Error: exec: no command
[+1599s] output:
```
```release-note
None
```
> Cirrus: Fix e2e tests for "mount_rootless_test"

- contrib/pkginstaller/Makefile
- contrib/pkginstaller/README.md
- contrib/pkginstaller/hvf.entitlements
- contrib/pkginstaller/package.sh
- This adds the missing signing of the qemu binary included in the pkg
- adds makefile target `notarize` to perform notarization of the built pkg installer
```
$ make ARCH=<amd64 | aarch64> CODESIGN_IDENTITY=<ID> PRODUCTSIGN_IDENTITY=<ID> NOTARIZE_USERNAME=<appleID> NOTARIZE_PASSWORD=<appleID-password> notarize
```
```release-note
None
```
> Add steps to sign included qemu and notarize the built pkg

- Makefile
- docs/Makefile
- docs/source/markdown/.gitignore
- docs/source/markdown/options/cgroup-conf.md
- docs/source/markdown/options/chrootdirs.md
- docs/source/markdown/options/env-host.md
- docs/source/markdown/options/group-add.md
- docs/source/markdown/options/hostuser.md
- docs/source/markdown/options/image-volume.md
- docs/source/markdown/options/init-path.md
- docs/source/markdown/options/init.md
- docs/source/markdown/options/mount.md
- docs/source/markdown/options/no-healthcheck.md
- docs/source/markdown/options/oom-kill-disable.md
- docs/source/markdown/options/passwd-entry.md
- docs/source/markdown/options/personality.md
- docs/source/markdown/options/pidfile.md
- docs/source/markdown/options/sdnotify.md
- docs/source/markdown/options/seccomp-policy.md
- docs/source/markdown/options/timeout.md
- docs/source/markdown/options/tz.md
- docs/source/markdown/options/umask.md
- docs/source/markdown/options/unsetenv-all.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- hack/markdown-preprocess
podman-create and -run have many options in common. To date,
these are copy-pasted and haphazardly maintained.
Solution: add an include mechanism, '@@option foo', such
that multiple md source files can fetch from one common file.
This is a Phase One commit, a very small subset of what's
possible. Purpose of this commit is ease of review. If this
passes review, much more (trickier stuff) will be forthcoming.
```release-note
Man page refactoring: add include mechanism for common options
```
> [CI:DOCS] Refactor common options in man pages

- pkg/machine/wsl/machine.go
Since we default to rootless via podman.exe, change the WSL prompt to default to the rootless user as well.
Includes two other minor changes:
- Forces machine init to always use version 2 of WSL to prevent unintentional usage of WSL1
- Masks a failing systemd service in F36 which relies on kernel functionality (psi) not present in the WSL kernel
Ideally, this PR could be included in 4.2.
Fixes #14814
Fixes #14155
```release-note
Prefer the rootless user when accessing the WSL prompt on Windows 
```
> Default to rootless via Windows WSL prompt / Lock to WSL2

- hack/markdown-preprocess
str.removeprefix() and str.removesuffix() is python 3.9+ only but we need to
support older versions for the OSX cross task.
This fixes broken CI on main.
```release-note
None
```
> fix hack/markdown-preprocess to support older python versions

- pkg/k8s.io/api/core/v1/types.go
- test/e2e/generate_kube_test.go
Secret was populating a generated kube as `null`. Add omitempty
so that when the volume source is not a secret, we do not print unnecessary info
resolves #15156
```release-note
fix a bug that was printing Secret: null even when a secret volume type is not used in a pod for podman generate kube
```
> add omitempty to Secret in k8s VolumeSource

- .cirrus.yml
- hack/get_ci_vm.sh
***Depends on:***
https://github.com/containers/automation_images/pull/160
```release-note
None
```
> [CI:DOCS] Cirrus: Support EC2 instances in hack/get_ci_vm.sh

- docs/source/conf.py
- hack/markdown-preprocess
When docs.podman.io is build on readthedocs we have to make sure to
generate the markdown pages first.
It works locally with sphinx but I have no idea if this works on the
readthedocs infra.
```release-note
None
```
> fix sphinx build to include podman-create/run page

- pkg/autoupdate/autoupdate.go
- test/system/255-auto-update.bats
Refactor `pkg/autoupdate` to pave the way for running more than one container a systemd unit to support auto updates in the context of `podman kube play`.  There are many changes but broken into smaller and easier to digest commits.  None of the changes should change behavior.
Please refer to the individual commits for change descriptions.  The remainder will be done in a separate PR to facilitate reviewing.
```release-note
None
```
> refactor pkg/autoupdate

- contrib/pkginstaller/README.md
- contrib/pkginstaller/package.sh
we were not using the correct GOARCH to build the podman remote
and podman-mac-helper binaries, this uses the ARCH value passed
to the make invocation to set the GORACH
```release-note
None
```
> pkginstaller: use correct GOARCH while building podman binaries

- .github/ISSUE_TEMPLATE.md
- cmd/podman/system/info.go
- docs/source/markdown/podman-info.1.md
podman info: hide `--debug`
It's a NOP since Podman v2.0 (#5738).
Fixes: #15185
```release-note
Hide the `--debug` flag of `podman info` as it's a NOP since Podman v2.0.
```
> podman info: hide `--debug`

- go.mod
- go.sum
- test/system/010-images.bats
- vendor/github.com/containers/common/libimage/image.go
- vendor/github.com/containers/common/libimage/runtime.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Improve the error message when attempting to remove an image that is in
use by an external/build container.  Prior, the error only indicated
that the image was in use but did not aid in resolving the issue.
Fixes: #15006
```release-note
Improve error message when attempting to remove an image in use by an external/build container.
```
> podman rmi: improve error message for build containers

- .cirrus.yml
Fixes: #15189
A while ago I updated the only_if/skip options and forgot that several
"cross build" tasks also build documentation in addition to binaries.  Re-enable
them to execute all the time, except when Cirrus-cron is making our
multi-arch images.
```release-note
None
```
> Cirrus: Run Cross builds in [CI:DOCS] mode

- cmd/podman/containers/start.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- pkg/domain/infra/tunnel/helpers.go
- test/e2e/start_test.go
Tying filtering logic for podman stop and start to same place in getContainersAndInputByContext() to reduce code redundancy
Signed-off-by: Karthik Elango <kelango@redhat.com>
```release-note
none
```
> start --filter flag changes

- hack/markdown-preprocess
go-md2man happily ignores our comment lines in most cases,
but sphinx (used in readthedocs) cannot deal with comments
if they immediately follow any other content line:
blah blah
[//]: # (my comment)
...the whole comment line is actually rendered in its output.
Only solution seems to be to add extra newlines before each
comment. Makes diff and PR review harder, but otherwise has
no effect on the rendered documents.
```release-note
None
```
> markdown-preprocess: force extra newline on comments

- pkg/machine/wsl/machine.go
**Which issue(s) this PR fixes:**
Fixes #15154 
**What this PR does / why we need it:**
This changes the order of writing config and connections to the end of the provisioning.
If the user breaks out or the WSL startup fails no connections or config is left behind.
**Does this PR introduce a user-facing change?**
```
If podman machine init fails, Podman will not add connection data for the system.
```
> Fixes #15154 Change order when config and connections are written

- cmd/podman/images/rm.go
- docs/source/markdown/podman-rmi.1.md
- pkg/api/handlers/libpod/images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_remove_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/rmi_test.go
Docker supports --no-prune for rmi which does not remove dangling parents of the specified image. Podman
should support the same for compatibility.
Task from #14917 
Signed-off-by: Karthik Elango <kelango@redhat.com>
```release-note
Added --no-prune flag for podman rmi
```
> remove image podman no prune

- .cirrus.yml
- contrib/cirrus/CIModes.md
- podman.spec.rpkg
EL8 builds are failing because hack/markdown-preprocess needs python3
which AFAICT isn't included by default in EL8 build environments.
This commit also includes an additional `[CI:COPR]` mode which is
currently runs the same tests as `[CI:DOCS]` but could differ in future.
EDIT: `s/CI:RPM/CI:COPR/g`
```release-note
None
```
@cevich @edsantiago PTAL
> [CI:COPR] podman.spec.rpkg: add python3 dependency for el8

- test/e2e/run_cleanup_test.go
`podman run -d mount cleanup test` adapt to rootless environment.
```release-note
None
```
> e2e: Add rootless mount cleanup test

- .cirrus.yml
Env. var. hasn't been used for quite a while.  Remove it and associated comments.
```release-note
None
```
> Cirrus: Remove disused env. var.

- contrib/pkginstaller/package.sh
to compile arm bits the GOARCH should be set to amd64 script
was wrongly using aarch64 instead
```release-note
None
```
> pkginstaller: use correct GOARCH value in case of arm build

- .cirrus.yml
AWS EC2 keys VM images by an utterly unreadable, horrible to use,
generated "AMI ID" value.  This is very error prone for humans in
practice, since it's impossible to tell one image from the next by
eye.  Worse, EC2 permits duplicate name-tag values, complicating
image specification further.
However fortunately, Cirrus-CI recently implemented a feature by
which AMI's may be referenced by a name-tag search - choosing
the most recent AMI found.  Since the `containers/automation_images`
build workflow always assigns a unique name + `$IMAGE_SUFFIX` value,
we can simply re-use it for both AWS and GCP image specification.
In other words as of this commit, specifying new CI VM images can
be done by simply updating the `$IMAGE_SUFFIX` value as we've always
done.  No need to call out a specific …
> [v4.2] Cirrus: Improve CI VM image updates for EC2

- .cirrus.yml
AWS EC2 keys VM images by an utterly unreadable and horrible to use "AMI
ID" value.  This is very error prone for humans to use, since it's
impossible to tell one image from the next by eye.  Worse, they permit
duplicate name-tag values (or any other tag), complicating image
selection further.
However, Cirrus-CI recently implemented a feature by which AMI's may be
referenced by name-tag search, where the most recent AMI is chosen.
Since the `containers/automation_images` build workflow always assigns
a unique `$IMAGE_SUFFIX` value (based on the $CIRRUS_BUILD_ID), we can
now simply re-use it for both AWS and GCP image specification.  In other
words to update VM images, simply update the `$IMAGE_SUFFIX` value
and you're done.
```release-note …
```
> Cirrus: Improve CI VM image updates for EC2

- pkg/bindings/images/push.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_push_options.go
- pkg/bindings/test/images_test.go
- pkg/domain/infra/tunnel/images.go
Currently bindings writes image push progress to os.Stderr.
Since os.Stderr is inconvenience for bindings caller to process the progress messages, Added this support.
Signed-off-by: Naoto Kobayashi <naoto.kobayashi4c@gmail.com>
Close #15211
```release-note
Bindings: Images package now supports writing image push progress to specified io.Writer
```
Edit:
Skipped the unit test for added option since I cannot find any existing UT using container registry; e.g. UT for binding manifest push is skipped as TODO.
- https://github.com/containers/podman/blob/main/pkg/bindings/test/manifests_test.go#L175-L177
```go
It("push manifest", func() {
Skip("TODO: implement test for manifest push to registry")
})
```
If there is a registry available for UT, I would grateful if you could tell me. Will write …
> pkg/bindings: Support writing image push progress to specified io.Writer

- cmd/podman/machine/platform.go
- pkg/machine/applehv/machine.go
- pkg/machine/config.go
- pkg/machine/qemu/machine.go
The new apple silicon processesors (m1/m2) are capable of using a performent apple
hypervisor (included in macos).  Our "virtual providers" for podman
machine are part of an interface design.  This PR provides an
implementation of the interface to begin the work for supporting the
apple hypervisor.  It is basically only a skeletal PR.
The actual code for using the hypervisor and launching a machine will
come as several new PRs following the inclusion of this one.
There will likely be code reuse between the applehv and qemu code; but
none of that code is being moved at this time.  It will be moved "on
demand" during development.
```
None
```
> Add interface for apple hypervisor

- cmd/podman/generate/spec.go
- docs/source/markdown/podman-generate-spec.1.md
- docs/source/markdown/podman-generate.1.md
- pkg/domain/entities/engine_container.go
- pkg/domain/entities/generate.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/generate.go
- pkg/domain/infra/tunnel/generate.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/pod_create.go
- test/apiv2/20-containers.at
- test/apiv2/40-pods.at
- test/e2e/generate_spec_test.go
implement a new command `podman generate spec` which can formulate a json specgen to be consumed by both the pod
and container creation API.
supported flags are
--verbose (default true) print output to the terminal
--compact print the json output in a single line format to be piped to the API
--filename put the output in a file
--clone rename the pod/ctr in the spec so it won't conflict w/ an existing entity
```release-note
introduce podman generate spec which allows users to formulate Specgen data into a json file.
```
> podman generate spec

- test/e2e/checkpoint_test.go
> I believe that these tests will now run with crun.

- go.mod
- go.sum
- libpod/container_internal_linux.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/qualified-device.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/registry.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec-dirs.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_linux.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_other.go
- vendor/github.com/container-orchestrated-devices/container-device-interface/specs-go/config.go
- vendor/modules.txt
This requires that the cdi.Registry be instantiated with AutoRefresh disabled for CLI clients.
```release-note
None
```
>  build(deps) bump CDI dependency from 0.4.0 to 0.5.0

- cmd/podman/kube/play.go
- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/container_validate.go
- libpod/define/config.go
- libpod/define/container_inspect.go
- libpod/define/sdnotify.go
- libpod/oci_conmon_linux.go
- libpod/options.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/abi/play_utils.go
- pkg/domain/infra/abi/play_utils_test.go
- pkg/specgen/container_validate.go
- pkg/specgen/generate/container_create.go
- pkg/systemd/notifyproxy/notifyproxy.go
- pkg/systemd/notifyproxy/notifyproxy_test.go
- test/system/260-sdnotify.bats
- test/system/helpers.bash
Integrate sd-notify policies into `kube play`.  The policies can be
configured for all contianers via the `io.containers.sdnotify`
annotation or for indidivual containers via the
`io.containers.sdnotify/$name` annotation.
The `kube play` process will wait for all containers to be ready by
waiting for the individual `READY=1` messages which are received via
the `pkg/systemd/notifyproxy` proxy mechanism.
Also update the simple "container" sd-notify test as it did not fully
test the expected behavior which became obvious when adding the new
tests.
```release-note
Add support for specifying sd-notify policies in `kube play`.
```
Note: this the next step toward auto-update support for `kube play`.  I will add that in another PR to make …
> kube play: sd-notify integration

- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_manifest.go
- pkg/bindings/manifests/manifests.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
`podman-remote manifest push` has shown absolutely no progress at all. Fix that by doing the same as the remote-push code does.
Like remote-push, `quiet` parameter is true by default for backwards compatibility.
Signed-off-by: Naoto Kobayashi <naoto.kobayashi4c@gmail.com>
Close #15210 
```release-note
Fix a bug where `podman-remote manifest push` would not print any progress.
```
> remote manifest push: show copy progress

- docs/source/markdown/podman-build.1.md.in
Build from URL does not supports `git://` is source is hosted on Github.
Reason: https://github.blog/2021-09-01-improving-git-protocol-security-github/
[CI:DOCS]
Similar to: https://github.com/containers/buildah/pull/4179
> [CI:DOCS] docs: specify `git` protocol is not supported for github hosted repo

- docs/Makefile
- pkg/machine/ignition_freebsd.go
- pkg/machine/qemu/options_freebsd.go
- pkg/machine/qemu/options_freebsd_amd64.go
- pkg/util/utils_freebsd.go
- pkg/util/utils_unsupported.go
This makes the pkg/util and pkg/machine modules build on FreeBSD. It also fixes 'make clean' on FreeBSD - docs/Makefile assumes that $RM is set to something which behaves like /bin/rm and this wasn't set for me for some reason.
```release-note
None
```
> FreeBSD build fixes for pkg/util and pkg/machine

- contrib/systemd/system/podman-kube@.service.in
systemd expects the value of the option to be `no` instead, but this is
already the default behavior. This fixes the following warning when
running `systemctl status` on the unit:
Failed to parse service restart specifier, ignoring: never
```release-note
podman-kube@.service.in: Remove Restart=never option with typo
```
> podman-kube@.service.in: Remove Restart=never option with typo

- .gitignore
Ignore .DS_Store, a MacOS metatdata file created by the OS.
```release-note
None
```
> [CI:DOCS] Add .DS_Store to gitignore

- docs/source/markdown/podman-images.1.md
Fixes: https://github.com/containers/podman/issues/15309
```release-note
Fix up podman images man page to add option [image] specification.
```
> [CI:DOCS] podman images and friends can take one image as argument

- cmd/podman/common/netflags.go
- test/system/500-networking.bats
Fixes one of the issues found in https://github.com/containers/podman/issues/14917
```release-note
Podman now supports podman run --dns-option  as well as --dns-opt for Docker compatibility
```
> Add Docker compatibility for --dns-option to --dns-opt

- contrib/cirrus/runner.sh
Replace TODO comment with helpful hint for future maintainers.
```release-note
None
```
> [CI:DOCS] Cirrus: Update podman-machine comment

- test/system/160-volumes.bats
- test/system/251-system-service.bats
- test/system/410-selinux.bats
Two fixes done in #14972 (the "oops test under runc again" PR
which was not backported into 4.2):
- "survive service stop" - skip. Test is only applicable
under crun.
- "volume exec/noexec" - update the expected error message
One hail-mary fix for a test failure seen in RHEL87 gating:
- "nonexistent labels" - slight tweak to expected error message
None of these fixes will actually be tested in CI, because v4.2
does not run any runc tests. We'll have to wait and see what
happens on the next RHEL build.
```release-note
Fix / skip tests failing under RHEL gating
```
> [v4.2] Skip / update some tests under runc

- docs/source/markdown/options/README.md
- docs/source/markdown/options/arch.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-run.1.md.in
- hack/markdown-preprocess
- hack/markdown-preprocess.t
Smaller, more reviewable chunks.
This is just one option, --arch. Future PRs may, if the reviewing
is easy, include multiple options. This one includes fixes to
the preprocessor script, though:
* big oops, I was not handling '<<something pod|something>>'
where 'pod' appears other than the beginning of the string.
* I was also not handling 'container<<| or pod>>', where one
side was empty.
* Behavior change: <<subcommand>>, on podman-pod-foo,
becomes just 'foo' (not 'pod foo'). This will be useful
in a future PR where we refactor --pod-id-file.
```release-notes
Continued man-page refactoring
```
> Man pages: refactor common options: arch

- docs/source/markdown/options/annotation.container.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-run.1.md.in
Refactor the --annotation option, but only between podman create,
kube play, and run.
This does not include:
* podman build:
- usage is in terms of images, not containers/pods
* manifest add, manifest annotate:
- usage is in terms of images, not containers/pods
- also, wording is slightly different
```release-note
More man page refactoring
```
> Man pages: refactor common options: --annotation

- cmd/podman/root.go
- test/system/001-basic.bats
This is another fix for https://github.com/containers/podman/issues/14917
```release-note
Podman now supports --debug, -D on the command line for Docker compatibility.
```
> Add compatibility support for --debug flag from docker

- test/system/410-selinux.bats
Followup to #14613, which was never actually tested until this
week in RHEL8 gating tests (see issue #15337).
* add missing backslash in '|' expression
* allow extra text after error (e.g., "invalid argument")
No way to test this until it makes its way into RHEL8,
so, fingers crossed.
```release-note
Fix broken (under runc) system test
```
> system tests: fix broken runc test

- cmd/podman/manifest/add.go
- cmd/podman/manifest/create.go
- cmd/podman/manifest/push.go
- docs/source/markdown/podman-manifest-create.1.md
- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_manifest.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_create_options.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
```release-note
`podman manifest create` now accepts a `--amend` flag.
The `podman manifest` `create`, `add`, and `push` commands now accept the `--insecure` flag as equivalent to `--tls-verify=false`.
```
Fixes https://github.com/containers/podman/issues/15346.
> podman manifest create: accept --amend and --insecure flags

- libpod/boltdb_state_unsupported.go
- libpod/container_copy_unsupported.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/container_internal_unsupported.go
- libpod/container_stat_unsupported.go
- libpod/container_top_unsupported.go
- libpod/container_unsupported.go
- libpod/healthcheck_unsupported.go
- libpod/info.go
- libpod/info_unsupported.go
- libpod/networking_unsupported.go
- libpod/oci_conmon_unsupported.go
- libpod/pod_top_unsupported.go
- libpod/runtime_migrate_unsupported.go
- libpod/runtime_pod_unsupported.go
- libpod/runtime_volume_unsupported.go
- libpod/stats_unsupported.go
- libpod/util_unsupported.go
- libpod/volume_internal_unsupported.go
This also moves some rootless network setup code and uses of unix.O_PATH to container_internal_linux.go. With this, it is possible to build a non-functional podman on FreeBSD.
Possibly networking_slirp4netns.go would be a more suitable place for the rootless network code.
```release-note
None
```
> Add non-linux build stubs for libpod

- .cirrus.yml
- contrib/cirrus/cirrus_yaml_test.py
- pkg/machine/e2e/basic_test.go
- test/system/200-pod.bats
Depends on https://github.com/containers/podman/pull/14801
```release-note
None
```
> Cirrus: add podman_machine_aarch64 

- cmd/podman/kube/generate.go
- test/system/710-kube.bats
> Fix podman kube generate --help to show correct help message

- cmd/podman/manifest/create.go
- docs/source/markdown/podman-manifest-create.1.md
- test/e2e/manifest_test.go
```release-note
podman manifest create -a alias for --amend added, compatible with Docker CLI.
```
> Add podman manifest create -a. Alias for --amend:Docker compatibility

- cmd/podman/containers/stats.go
- docs/source/markdown/podman-stats.1.md
- test/e2e/stats_test.go
This is for compatibility with Docker.
Partial fix for https://github.com/containers/podman/issues/14917
```release-note
podman stats now supports the --no-trunc flag
```
> Add podman stats --no-trunc option

- pkg/api/handlers/compat/containers.go
Description of the issue:
Saltstack is a tool that can be used for configuration management and one of its capabilities includes being able to manage Docker containers. One of the ways that it decides if a currently running container needs to be replaced is by starting a temporary container using the same image, then comparing the temporary container to the currently running container by querying the Docker API. 
This PR aims to resolve an issue that causes Saltstack (and possibly other configuration management  tools) to restart the container each time that it ensures the state of a running container. The root cause of the issue is that when Saltstack compares the running container to the temporary container, the `HostConfig.Binds` may be in a different order for …
> sort hc.Binds returned from compat api

- go.mod
- go.sum
- libpod/runtime.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/modules.txt
detect the conmon-rs version string and if detected disable version
check for now.
Closes: https://github.com/containers/podman/issues/15335
```release-note
None
```
> runtime: parse conmon-rs version

- test/system/710-kube.bats
- test/system/helpers.bash
This exposed a nasty bug in our system-test setup: Ubuntu (runc)
was writing a scratch containers.conf file, and setting CONTAINERS_CONF
to point to it. This was well-intentionedly introduced in #10199 as
part of our long sad history of not testing runc. What I did not
understand at that time is that CONTAINERS_CONF is **dangerous**:
it does not mean "I will read standard containers.conf and then
override", it means "I will **IGNORE** standard containers.conf
and use only the settings in this file"! So on Ubuntu we were
losing all the default settings: capabilities, sysctls, all.
Yes, this is documented in containers.conf(5) but it is such
a huge violation of POLA that I need to repeat it.
In #14972, as yet another attempt to fix our runc crisis, I
introduced a new runc-override …
> podman kube generate - add actual tests

- docs/source/markdown/.gitignore
- docs/source/markdown/options/authfile.md
- docs/source/markdown/podman-auto-update.1.md.in
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-container-runlabel.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-image-sign.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-logout.1.md.in
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-search.1.md.in
Refactor the --authfile option.
My suggestion for review:
1) run hack/markdown-preprocess-review and immediately Ctrl-Q to
quit out of diffuse, which is completely unusable for this
many files; then
2) cd /tmp/markdown-preprocess-review.diffs/authfile
- this is the directory created by the review script
3) rm podman-image-sign* podman-log* podman-search.1.md.in
- because they're essentially identical to podman-create
4) rm podman-manifest-* podman-push.*
- because they're 100% identical to podman-kube-play
5) rm podman-kube-play*
- because it's apart-from-whitespace identical to podman-build
(use "wdiff" to confirm)
6) rm podman-auto-update*
- because that's the one I chose (hence == zzz-chosen.md)
(You should obviously run your own diff/cmp before rm, to confirm
my assertions about which …
> Man pages: refactor common options: authfile

- test/apiv2/10-images.at
The apiv2 test hardcoded the tag of the alpine image.
Remove it to unblock CI.
Fixes: #15388
```release-note
None
```
> fix CI: remove hardcodeded alpine version

- docs/source/markdown/options/cert-dir.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- hack/markdown-preprocess-review
...and, tweak markdown-process-review so it can detect and
remove identical files, making review easier.
```release-note
```
> Man pages: refactor common options: cert-dir

- docs/source/markdown/options/arch.md
- docs/source/markdown/options/platform.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-run.1.md.in
After pulling/creating an image of a foreign platform, Podman will
happily use it when looking it up in the local storage and will not
pull down the image matching the host platform.
As discussed in #12682, the reasoning for it is Docker compatibility and
the fact that user already rely on the behavior.  While Podman is now
emitting a warning when an image is in use not matching the local
platform, the documentation was lacking that information.
Fixes: #15300
```release-note
Elaborate on local image lookups after pulling images of foreign platforms.
```
> [CI:DOCS] elaborate on image lookups of foreign platforms

- cmd/podman/registry/config.go
- libpod/events/events_freebsd.go
- libpod/events/events_unsupported.go
- libpod/events/logfile.go
This allows podman commands on FreeBSD to call through to libpod and is required for most commands to work. Right now, most commands are non-functional but 'podman image' is working ok.
```release-note
None
```
> Enable event logging,  tunnel and ABI mode for FreeBSD

- cmd/podman/secrets/create.go
- cmd/podman/secrets/inspect.go
- docs/source/markdown/podman-secret-create.1.md
- docs/source/markdown/podman-secret-inspect.1.md
- test/e2e/secret_test.go
```release-note
podman secret create now supports -d as alias for --driver: Docker Compatibility.
podman secret inspect supports -f as alias for --format: Docker Compatibility.
```
> podman secret create -d alias --driver, inspect -f alias --format: Docker compatibity

- docs/source/markdown/options/creds.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-container-runlabel.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-push.1.md.in
Refactor the --creds option. I went with the one in podman-pull
The main difference between all of them is the '####' line,
differences in the param descriptions. podman-pull had the
clearest one.
This is another one that hack/markdown-preprocess-review is
good for reviewing.
```release-note
```
> Man pages: refactor common options: --creds

- cmd/podman/secrets/list.go
- docs/source/markdown/podman-secret-ls.1.md
- test/e2e/secret_test.go
Add quiet/q flag to podman secret ls, which will print only the secret
ID.
```release-note
Add quiet/q flag to podman secret ls, which will print only the secret
ID.
```
> Add quiet/q flag to podman secret ls

- docs/source/markdown/.gitignore
- docs/source/markdown/options/pod-id-file.container.md
- docs/source/markdown/options/pod-id-file.pod.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-rm.1.md.in
- docs/source/markdown/podman-pod-start.1.md.in
- docs/source/markdown/podman-pod-stop.1.md.in
- docs/source/markdown/podman-run.1.md.in
Much like --cidfile (#15414), --pod-id-file has two meanings.
One is used in pod-related commands, one in container ones.
Both meanings read the file, so the read/write split used
in --cidfile is not applicable here.
podman-pod-create keeps its --pod-id-file option because
that one cannot be refactored: that's the only command (now)
that writes a pod-id file.
Reviewable using hack/markdown-preprocess-review but I
did take some liberties with the #### args because they
were wrong. And, since I had to much with the description
text anyway (resulting in diffs), I also took the liberty
of cleaning up a double space.
```release-note
```
> Man pages: refactor common options: --pod-id-file

- docs/source/markdown/options/blkio-weight.md
- docs/source/markdown/options/cpu-period.md
- docs/source/markdown/options/cpu-quota.md
- docs/source/markdown/options/cpu-rt-period.md
- docs/source/markdown/options/cpu-rt-runtime.md
- docs/source/markdown/options/cpu-shares.md
- docs/source/markdown/options/cpuset-cpus.md
- docs/source/markdown/options/cpuset-mems.md
- docs/source/markdown/options/memory-swappiness.md
- docs/source/markdown/podman-container-clone.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- pkg/specgen/generate/validate.go
- test/e2e/container_clone_test.go
- test/e2e/create_test.go
- test/e2e/generate_kube_test.go
- test/e2e/generate_spec_test.go
- test/system/030-run.bats
When an unsupported limit on cgroups V1 rootless systems
is requested, podman prints an warning message and
ignores the option/flag.
```
Target options/flags:
--cpu-period, --cpu-quota, --cpu-rt-period, --cpu-rt-runtime,
--cpus, --cpu-shares, --cpuset-cpus, --cpuset-mems, --memory,
--memory-reservation, --memory-swap, --memory-swappiness,
--blkio-weight, --device-read-bps, --device-write-bps,
--device-read-iops, --device-write-iops, --blkio-weight-device
```
Related to https://github.com/containers/podman/discussions/10152
```release-note
Warning messages are printed and ignored if we use an unsupported option on cgroups V1 rootless systems
```
> Warning messages are printed and ignored if we use an unsupported option on cgroups V1 rootless systems

- pkg/specgen/generate/container.go
- test/e2e/container_clone_test.go
the env vars are held in the spec rather than the config, so they need to be mapped manually. They are also of a different format so special handling needed to be added. All env from the parent container will now be passed to the clone.
resolves #15242
```release-note
users can now expect env variables to be passed properly when using container clone
```
> pass environment variables to container clone

- docs/source/markdown/options/cpus.container.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only on podman create and run: the --cpus option on container-clone
and pod-clone can probably be combined, but maybe later. pod-create
has unique wording that can't be combined.
This is a freebie to review: the text in both files was already
identical, and I made no changes to it. hack/markdown-preprocess-review
will agree, and show you no diffs, because there are none worth
seeing.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --cpus

- cmd/podman/kube/down.go
- cmd/podman/kube/play.go
- docs/source/markdown/podman-kube-down.1.md
- docs/source/markdown/podman-kube-play.1.md.in
- test/system/700-play.bats
`podman kube play` can create pods and containers from YAML
read from a URL poiniting to a YAML file.
For example: `podman kube play https://example.com/demo.yml`.
`podman kube down` can also teardown pods and containers created
from that YAML file by also reading YAML from a URL, provided the
YAML file the URL points to has not been changed or altered since
it was used to create pods and containers
Closes #14955 
```release-note
`podman kube play` can create pods and containers by reading YAML from a URL.
`podman kube down` can teardown pods and containers by reading YAML from a URL,
provided the YAML file the URL points to has not been changed or altered since the creation
of the pods and containers that need to be removed.
```
> podman kube play/down --read from URL

- docs/source/markdown/options/annotation.container.md
- docs/source/markdown/podman-container-runlabel.1.md.in
- docs/source/markdown/podman-image-sign.1.md.in
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
I've been doing the man-page cleanup distractedly, while
fighting other fires, and submitted some crap:
* #15339: I used single angle brackets, not double
* #15407: I only refactored --cert-dir from some man pages, not all
Easy to review with hack/markdown-preprocess-review, because all the
removed texts are identical. The only diff is that container-certs.d
is now a link.
Sorry about that. I'm going to spend more time being careful.
```release-note
none
```
> [CI:DOCS] Man pages: fix sloppiness

- libpod/boltdb_state_freebsd.go
- libpod/container_freebsd.go
- libpod/container_unsupported.go
For FreeBSD, we need the name of the 'network jail' which is the parent
of all containers in a pod. Having a separate jail for the network
configuration also simplifies the implementation of CNI plugins so we
use this pattern for solitary containers as well as pods.
```release-note
None
```
> libpod: Add definition of containerPlatformState for FreeBSD

- docs/source/markdown/options/disable-content-trust.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-run.1.md.in
A NOP option. I chose the container word, of course, and the
word 'option' instead of 'flag'. I also hyphenated where needed.
I'm choosing to eliminate the "not on remote" text, because I
don't think it's true: podman-remote happily accepts that
flag on all those commands, including build. (It's marked
as hidden on build, but still accepted).
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --disable-content-trust

- cmd/rootlessport/main.go
- pkg/machine/pull.go
- pkg/machine/qemu/machine.go
Extracting some work done during experiments implementing https://github.com/containers/podman/issues/13006
First it replaces hardcoded "/dev/null" with os specific variant provided by Go lang. `os.DevNull` was used in other places, so, I assume this is just code cleanup change.
Next it changes use of xzcat to xz as default windows build doesn't have xzcat (in a form of application copy or symlink (not supported on that platform).
From the docs https://linux.die.net/man/1/xzcat "xzcat is equivalent to xz --decompress --stdout." So, it should have no functional changes and preserve the bahavior. Used "-d" and "-c" short keys instead of full ones as there was use of "-k" in short form already.
```release-note
None
```
> Improved Windows compatibility

- docs/source/markdown/podman-build.1.md.in
When using remote podman client, not all transports work as expected. So
document this limitation.
Fixes: containers/podman#15141
```release-note
Improve documentation for --from in context of remote podman client
```
> Document restrictions on transport in FROM

- docs/source/markdown/options/device-cgroup-rule.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
I chose the version from podman-create. (This is unusual. podman-run
tends to have the better-maintained, more up-to-date version.)
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --device-cgroup-rule

- docs/source/markdown/options/ignore.md
- docs/source/markdown/podman-pod-rm.1.md.in
- docs/source/markdown/podman-pod-stop.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-stop.1.md.in
Should be an easy one to review.
Note that the podman-rmi --ignore option cannot be combined into this one.
```release-note
```
> Man pages: refactor common options: --ignore

- .packit.yaml
This commit includes the initial addition of a .packit.yaml which will
run scratch builds for active Fedora releases which get the latest
Podman using Fedora's official packaging sources.
More packit integration to come in the future.
```release-note
None
```
> Packit: Enable scratch build testing for Fedora 36, 37 and Rawhide

- cmd/podman/images/pull.go
- cmd/podman/images/push.go
- cmd/podman/manifest/push.go
- pkg/api/handlers/compat/auth.go
- pkg/api/handlers/compat/images_build.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/api/handlers/libpod/images_pull.go
- pkg/api/handlers/libpod/images_push.go
- pkg/api/handlers/libpod/manifests.go
- pkg/api/handlers/types.go
- pkg/bindings/images/pull.go
- pkg/bindings/images/push.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_pull_options.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/test/images_test.go
- pkg/bindings/test/manifests_test.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/manifest_test.go
- test/e2e/pull_test.go
- Simplify `ImagesPull` for when `Quiet` flag is on
- Use request `Context()` in API handlers
- Pass `io.Writer` when pushing images/manifests from command line
- Add `ProgressWriter` to `PullOptions`
```release-note
None
```
> Simplify ImagesPull for when Quiet flag is on

- docs/source/markdown/.gitignore
- docs/source/markdown/options/workdir.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
I chose the version from podman-run because it is the most
up-to-date, and most correct wrt current syntax guidelines.
Differences are in arg description, language, and asterisks.
```release-note
```
> [CI:DOCS] Man pages: Refactor common options: --workdir

- test/e2e/run_memory_test.go
There is not e2e/system test of --memory-swap option.
```release-note
None
```
> e2e: Add run --memory-swap test

- Makefile
- contrib/systemd/system/podman-docker.conf
- podman.spec.rpkg
Rootless Docker daemon exposes its API socket on
`$XDG_RUNTIME_DIR/docker.sock`. On tmpfiles.d, `%t` is same as
`$XDG_RUNTIME_DIR` in `--user` mode, and `/run` otherwise.
We can reuse the same config file for both mode with this change.
`systemd-tmpfiles` reads "user" configurations in
`/usr/share/user-tmpfiles.d` when `--user` mode is set.
User unit `systemd-tmpfiles-setup.service` can be enabled to alias
rootless socket through systemd-tmpfiles.
```release-note
Rootless Docker API socket alias can be exposed with user mode systemd-tmpfiles
```
> Rootless Docker API socket alias can be exposed with user mode systemd-tmpfiles

- docs/source/markdown/options/gidmap.container.md
- docs/source/markdown/options/gidmap.pod.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Two versions: one for container-related commands, one for pods.
The container one is easy: all versions matched, so I made no
changes.
The pod one is hard to review. I went with the pod-clone
version because the pod-create one looks suspicious: it
talks in terms of containers, not pods. It's possible
that I've got it wrong, and that these two cannot be
combined, so please review very carefully. I strongly
recommend using hack/markdown-preprocess-review for this one.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --gidmap

- cmd/podman/common/create.go
- docs/source/markdown/options/env-merge.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- go.mod
- pkg/api/handlers/compat/containers_create.go
- pkg/api/handlers/types.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/run_env_test.go
- vendor/modules.txt
Allow end users to preprocess default environment variables before
injecting them into container using `--env-merge`
Usage
```
podman run -it --rm --env-merge some=${some}-edit --env-merge
some2=${some2}-edit2 myimage sh
```
Closes: https://github.com/containers/podman/issues/15288
```release-note
run,create: add support for --env-merge for preprocessing default environment variables
```
> run,create: add support for `--env-merge` for preprocessing default environment variables

- docs/source/markdown/options/ipc.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
This is not an easy one to review, sorry.
I went with the version from podman-create. The differences
against podman-run are subtle: apostrophes, whitespace, and
the arg description in the '####' line. Suggestion for review:
run hack/markdown-preprocess-review, then after you finish
with that, cd /tmp/markdown<TAB>/ipc and use your favorite
two-file diff tool to compare podman-run* against zzz*.
I did not even try to combine the podman-build one; that one
is too different.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --ipc

- test/e2e/run_test.go
it is not a kernel bug.
Rootless users are not allowed to use non recursive bind mounts,
otherwise they would be able to uncover mounts that were not visible
before to them.
[CI:DOCS] it is just a comment fix.
```release-note
None
```
> test: fix comment

- pkg/env/env.go
- pkg/specgen/generate/container.go
- pkg/specgenutil/specgen.go
- test/e2e/run_env_test.go
Fixes: https://github.com/containers/podman/issues/15251
```release-note
Podman will work on systemd where environment variable keys contain spaces.
```
> Allow podman to run in an environment with keys containing spaces

- docs/source/markdown/options/pid.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
I chose the one from podman-run, but reordered ns/private
to put them in alphabetical order.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --pid

- pkg/machine/qemu/claim_unsupported.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
No user facing changes. No logic changes for platforms other than windows (and Qemu machine is not immediately available for windows after this PR, so, should be treated as code refactoring). No additional tests provided, as old behavior should be preserved and everything should be covered by the current test set.
This is another PR in the series of refactorings extracted during experiment here https://github.com/containers/podman/issues/13006
Updated isRootfull check in qemu machine for correct behavior on windows. Right now isRootless on Windows is returing false and there are a lot of places, where it is called. So, workaround to check if we have a valid Getuid result (are not running on windows) and if not - the assume rootless.
It is similar to …
> Fixes isRootful check using qemu machine on Windows

- test/e2e/run_test.go
using "slave" means that every mount operation on the host that
happens between the mount creation for `/host` and running `findmnt`
will be propagated to the container mount.  To prevent new mounts on
the host to appear in the container thus invalidating the test we
have, just create the mount as private and use `/sys` as source as it
has multiple mounts on the top but less likely to get new mounts once
it is configured.
Closes: https://github.com/containers/podman/issues/15241
```release-note
None
```
> test: use private instead of slave for the mount

- cmd/podman/parse/net.go
- cmd/podman/parse/parse.go
- cmd/podman/parse/parse_windows.go
the `podman save` command was failing on windows due to the use of a
colon between the drive letter and first directory.  the check was
intended for Linux and not windows.
Fixes #15247
```release-note
Allow the use of colons in file path for `podman save` on Windows.
```
> Allow colons in windows file paths

- test/apiv2/12-imagesMore.at
- test/apiv2/20-containers.at
- test/apiv2/23-containersArchive.at
- test/apiv2/test-apiv2
Whole slew of bugs that got introduced while I wasn't paying
attention. Most of them are of the form "let's use hand-crafted
curl commands and do our own error checking and exit uncleanly
on error and leave the system in an unstable state". To be
fair, those were done because there was no existing mechanism
for uploading JSON files or somesuch. So, add one.
```release-note
None
```
> APIv2 test cleanup

- docs/source/markdown/.gitignore
- docs/source/markdown/options/color.md
- docs/source/markdown/options/follow.md
- docs/source/markdown/options/names.md
- docs/source/markdown/options/since.md
- docs/source/markdown/options/tail.md
- docs/source/markdown/options/timestamps.md
- docs/source/markdown/options/until.md
- docs/source/markdown/podman-logs.1.md.in
- docs/source/markdown/podman-pod-logs.1.md.in
podman-logs and podman-pod-logs. Most of these were already
identical, needing no review. Exceptions:
--follow : needed some container/pod tweaking. This is the
only one that really needs careful review.
--names  : I went with the longer version
Note that podman-events has --since and --until options too, but
those are too different to be combined here.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: log-related options

- contrib/pkginstaller/Makefile
Allow the pkginstaller makefile target to take advantage of Podman's version binary, alleviating the need to manually set Podman's version (and inevitably forgetting to do so). This means the pkginstaller Makefile will automatically detect what version of Podman we're packaging.
Closes: https://github.com/containers/podman/issues/15406
```release-note
None
```
> [CI:DOCS] Automatically set podman version in pkginstaller

- pkg/api/handlers/compat/events.go
- test/apiv2/10-images.at
Change only the compat API, so we don't force a breaking change on Libpod API users.
Partial fix for #15485
```release-note
Fixed a bug where the Compat Events endpoint set an incorrect status for image removal events (`remove` instead of `delete`)
```
> Compat API image remove events now have 'delete' status

- libpod/kube.go
Don't add the same annotations as the pod yaml to the
service yaml as it is not needed.
Fixes https://github.com/containers/podman/issues/15208
```release-note
None
```
> Remove duplicate annotations in generated service yaml

- docs/source/markdown/options/systemd.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
I went with the podman-run version, which better conforms to
style conventions.
```release-note
```
> Man pages: refactor common options: --systemd

- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
- test/e2e/build/Containerfile.userns-auto
- test/e2e/run_userns_test.go
`podman-remote` and Libpod API does not supports build with
`--userns=auto` since `IDMappingOptions` were not implemented for API
and bindings, following PR implements passing `IDMappingOptions` via
bindings to API.
Closes: https://github.com/containers/podman/issues/15476
```release-note
remote,api: build with --userns=auto now works for API and remote use-cases
```
> remote,API: fix implementation of build with `--userns=auto` for API and remote use-cases.

- cmd/podman/system/service_abi.go
if we are running in a container in the root cgroup, Podman tries to
move itself to a sub-cgroup.  This could be a problem in a setup where
the cgroups are not writeable, so just log a debug message and
continue, since anyway it is a best-effort operation.
Closes: https://github.com/containers/podman/issues/15498
```release-note
None
```
> service: make move to sub-cgroup non fatal

- libpod/oci_conmon_common.go
Commit 30e7cbccc194 accidentally added a deadlock as Podman was waiting
for the exit code to show up when the container transitioned to stopped.
Code paths that require the exit code to be written (by the cleanup
process) should already be using `(*Container).Wait()` in a deadlock
free way.
[NO NEW TESTS NEEDED] as I did not manage to a reproducer that would
work in CI.  Ultimately, it's a race condition.
Fixes: #15492
```release-note
Fix a deadlock `podman kill`.
```
> libpod: UpdateContainerStatus: do not wait for container

- docs/source/markdown/podman-pod-restart.1.md
- docs/source/markdown/podman-pod-stop.1.md.in
- docs/source/markdown/podman-rename.1.md
- docs/source/markdown/podman-rm.1.md.in
This commit adjusts example sections across several man pages to the format seen in other pages.
Follow up PR #13786, #13682 and #13771.
```release-note
None
```
> [CI:DOCS] Fix example sections to follow the same format

- libpod/boltdb_state.go
- libpod/define/errors.go
- libpod/networking_linux.go
- test/e2e/network_connect_disconnect_test.go
Signed-off-by: Alessandro Rossi <al.rossi87@gmail.com>
The PR introduces a new "ErrNetworkConnected" error in libpod defines, to handle the specific case where a user tries to connect a container to a network that is already connected to it.
The user from the CLI will still receive an error, but since from API point of view the operation results in nothing to be done and the state is preserved, it should return 200, aligned with the behavior that docker has.
This should address #15499
None
```release-note
ErrNetworkConnected was introduced for when trying to connect a container to a network it is already connected to
```
> Handle an already connected network in libpod API

- test/apiv2/12-imagesMore.at
- test/apiv2/23-containersArchive.at
- test/apiv2/26-containersWait.at
- test/apiv2/40-pods.at
- test/apiv2/70-short-names.at
- test/apiv2/README.md
- test/apiv2/test-apiv2
This finishes the removal of curls and exits.
Please please please, everyone, if you see a 'curl' or 'exit'
in any new PR, reject the PR and tell me immediately so I can
help the developer do it the proper way.
Also, removed some very-very-wrong USER/UID code. Both are
reserved variables in bash. You cannot override them.
Also, added a cleanup to a system-connection test. I wasted
a lot of time because my podman-remote stopped working, all
because I had run this test as part of something unrelated.
```release-note
None
```
> APIv2 test cleanup, part 2 of 2

- docs/source/markdown/options/dns-opt.container.md
- docs/source/markdown/options/dns-search.container.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
--dns-opt and --dns-search, but only in podman-create and -run.
Went with the -run version in both cases; --dns-opt remained
unchanged, but in --dns-search I changed 'and' to 'with'.
Did not consolidate podman-build or podman-pod-create: too
different.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --dns-*

- .cirrus.yml
- .packit.sh
- .packit.yaml
Any new files installed by new PRs and those present in unreleased
versions of Podman will need additional manipulation of the
dist-git spec file in the files section to workaround the
`installed but unpackaged files` issue.
The fix-spec-file packit action is useful for this.
The default fix-spec-file action often has trouble guessing the correct
version from upstream code, so it would be beneficial to specify the
correct upstream version as well.
See: https://packit.dev/docs/actions/#fix-spec-file
```release-note
None
```
> [CI:BUILD] Packit: Re-introduce packit with fix-spec-file action

- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
- test/e2e/save_test.go
We keep getting flakes in tests that use port 5000. Try to
find and fix, by switching ports where possible, and locking
5000 when not possible (or not easy) to switch.
```release-note
none
```
> e2e tests: try to deflake 5000

- docs/source/markdown/options/http-proxy.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only between podman-create and -run. (podman-build is too
different). I went with the podman-run version.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --http-proxy

- libpod/oci_conmon_linux.go
- test/apiv2/10-images.at
Commit 30e7cbccc194 accidentally added a deadlock as Podman was waiting
for the exit code to show up when the container transitioned to stopped.
Code paths that require the exit code to be written (by the cleanup
process) should already be using `(*Container).Wait()` in a deadlock
free way.
[NO NEW TESTS NEEDED] as I did not manage to a reproducer that would
work in CI.  Ultimately, it's a race condition.
Backport-for: #15492
```release-note
Fix a deadlock `podman kill`.
```
> [v4.2] libpod: UpdateContainerStatus: do not wait for container

- docs/source/markdown/options/subgidname.md
- docs/source/markdown/options/subuidname.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Whew! This one started off identical everywhere, but the version
in podman-run got fixed in #1380, then again in #5192, with no
corresponding fixes to any of the other man pages.
I went with the podman-run version, with a small change in wording.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --subXidname

- docs/source/markdown/options/restart.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only applicable to podman-create and -run. I went with the -run
version because it is cleaner and more recently updated.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --restart

- libpod/oci_conmon_freebsd.go
I managed to miss this while factoring out moveConmonToCgroupAndSignal.
Perhaps the signalling part should move to the caller instead?
```release-note
None
```
> libpod: Make sure writeConmonPipeData is called on FreeBSD

- pkg/bindings/images/images.go
- pkg/bindings/images/pull.go
- pkg/bindings/images/push.go
- pkg/bindings/images/types.go
- pkg/bindings/internal/util/util.go
- pkg/bindings/kube/kube.go
- pkg/bindings/kube/types.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/test/types_test.go
I realized that `params.Del("SkipTLSVerify")` doesn't have any effect because keys are always lowercased. So it should really be `params.Del("skiptlsverify")`.
There's also a little bug introduced by 3bf52aa and b1d1248: if one passes `ProgressWriter` object having `Stringer` interface i.e. `bytes.Buffer` it ends up been serialized in query with `util.ToParams()`.
To circumvent both problems I propose to mark non-serializable parameters with `schema:"-"` so there's no need to delete them from resulting `url.Values`.
```release-note
none
```
> Mark some of the option fields as ignored in pkg/bindings

- docs/source/markdown/options/userns.container.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-run.1.md.in
- pkg/domain/infra/runtime_libpod.go
- pkg/namespaces/namespaces.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/namespaces.go
- pkg/util/utils.go
- test/e2e/run_userns_test.go
add two new options to the keep-id user namespace option:
- uid: allow to override the UID used inside the container.
- gid: allow to override the GID used inside the container.
For example, the following command will map the rootless user (that
has UID=0 inside the rootless user namespace) to the UID=11 inside the
container user namespace:
$ podman run --userns=keep-id:uid=11 --rm -ti  fedora cat /proc/self/uid_map
0          1         11
11          0          1
12         12      65525
Closes: https://github.com/containers/podman/issues/15294
```release-note
The --userns=keep-id now supports the options `uid` and `gid` to override the IDs used inside the user namespace
```
> podman: add uid and gid options to keep-id

- .cirrus.yml
On this branch, /usr/local/bin/swagger is fetched on each run
(vs, on current 2022-08 main, installed at VM-setup time).
Something changed, and the new binary is very strict about
bugs in our swagger comments, of which there seem to be many.
Possible solution: fix our code. Doesn't seem worth the bother
for an old branch like this one.
Possible solution: re-fetch an old version of swagger tool.
Ditto.
This solution: just skip the swagger test. It seems unlikely
that anyone will make significant API changes on this branch.
```release-note
None
```
> [v3.3.1-rhel] CI: disable swagger step

- .cirrus.yml
On this branch, /usr/local/bin/swagger is fetched on each run
(vs, on current 2022-08 main, installed at VM-setup time).
Something changed, and the new binary is very strict about
bugs in our swagger comments, of which there seem to be many.
Possible solution: fix our code. Doesn't seem worth the bother
for an old branch like this one.
Possible solution: re-fetch an old version of swagger tool.
Ditto.
This solution: just skip the swagger test. It seems unlikely
that anyone will make significant API changes on this branch.
```release-note
None
```
> [v3.2.3-rhel] CI: disable swagger step

- cmd/podman/machine/init.go
- docs/source/markdown/podman-machine-init.1.md
- pkg/machine/e2e/config_init_test.go
- pkg/machine/e2e/init_test.go
Fixes #15402 
Registers additional flag to override username during machine init.
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
```release-note
Added `--username` flag to override username used for initializing podman machine with `podman init` command.
```
> Allow to override default username via command line

- go.mod
- go.sum
- test/system/090-events.bats
- vendor/github.com/containers/common/libimage/image.go
- vendor/modules.txt
Emit untag events for each tag when removing an image.
Fixes: #15485
```release-note
Emit untag events for each tag when removing an image.
```
> podman rmi: emit untag events

- docs/source/markdown/.gitignore
- docs/source/markdown/options/signal.md
- docs/source/markdown/podman-kill.1.md.in
- docs/source/markdown/podman-pod-kill.1.md.in
Would've been an easy one, except I decided to fix the text
to conform to our guidelines. I haven't been doing this,
but in this case it's only two man pages and the text is
short enough to make for easy review.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --signal

- docs/source/markdown/podman-kube-play.1.md.in
- libpod/container.go
- libpod/options.go
- libpod/runtime_ctr.go
- pkg/domain/infra/abi/play.go
- pkg/k8s.io/api/core/v1/types.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/volume.go
- pkg/specgen/volumes.go
- test/e2e/play_kube_test.go
When a kube yaml has a volume set as empty dir, podman
will create an anonymous volume with the empty dir name and
attach it to the containers running in the pod. When the pod
is removed, the empy dir volume created is also removed.
Add tests and docs for this as well.
Fixes https://github.com/containers/podman/issues/13309
```release-note
Add support for emptyDir volumes to podman kube play.
```
> Add emptyDir volume support to kube play

- libpod/container_internal.go
If we get a SIGTERM immediately after Conmon starts but before we
record its PID in the database, we end up leaking a Conmon and
associated OCI runtime process. Inhibit shutdown using the logic
we originally wrote to prevent similar issues during container
creation to prevent this problem.
[NO NEW TESTS NEEDED] No real way to test this I can think of.
Fixes #15557
```release-note
NONE
```
> Inhibit SIGTERM during Conmon startup

- contrib/cirrus/lib.sh
Reason: looks like UIDs 1001, 1003, 1006 are already taken
in the CI VMs.
Fixes: #15573
```release-note
None
```
> Cirrus: pick UIDs/GIDs starting at 1500, not 1000

- libpod/kube.go
- test/e2e/generate_kube_test.go
Since podman doesn't set/use the needed service env
variable, always set enableServiceLinks to false in
the generated kube yaml.
Fixes https://github.com/containers/podman/issues/15478#event-7271977316
```release-note
Add enableServiceLinks: false to the generated kube yaml.
```
> Set enableServiceLinks to false in generated yaml

- docs/source/markdown/options/name.container.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only for podman-create and -run, unfortunately: all the
others are too different, and can't easily be combined.
I went with the podman-run version because it was most
recently updated in #5192.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --name

- test/system/250-systemd.bats
- test/system/710-kube.bats
See https://github.com/containers/conmon/pull/352
As of a few days ago, Ubuntu still hadn't built a fixed conmon.
Just skip the test until we get a fixed Ubuntu or until we
figure out a better solution to the test-something-RHEL8ish
problem.
UPDATE: WEIRD: this 'skip' triggered a baffling failure                                                                                                       
on Ubuntu: the "Kubernetes only allows 63 characters"                                                                                                         
warning message stopped appearing, on Ubuntu only, which
then caused the kube-generate tests to fail because they
actually checked for that. The message doesn't appear
because generate-kube is no longer spitting out a line
for …
> CI: disable flaking test on ubuntu

- pkg/machine/machine_windows.go
- pkg/machine/qemu/machine.go
- pkg/machine/qemu/machine_unix.go
- pkg/machine/qemu/machine_unsupported.go
- pkg/machine/qemu/machine_windows.go
- pkg/machine/qemu/options_windows.go
- pkg/machine/wsl/machine.go
- pkg/machine/wsl/util_windows.go
Extracting more changes done during experiment in https://github.com/containers/podman/issues/13006 and continuation of https://github.com/containers/podman/pull/15372 (split into independent PRs as the first one is already reviewed and they are pretty independent).
It was checked to compile on MacOS and Windows and as it is purely refactoring, no behavior changes are expected.
The only non platform specific change is 
```
append(cmd, []string{"-qmp", monitor.Network + ":" + monitor.Address.GetPath() + ",server=on,wait=off"}...)
```
This is a correction, because Qemu is using `unix:` (also `tcp:` for TCP) not `unix:/` to set the protocol. It was working before, because address is absolute and additional leading `/` is harmless).
On windows the only option is to use either user specific or …
> Improved Windows compatibility for machine command

- .cirrus.yml
On this branch, /usr/local/bin/swagger is fetched on each run
(vs, on current 2022-08 main, installed at VM-setup time).
Something changed, and the new binary is very strict about
bugs in our swagger comments, of which there seem to be many.
Possible solution: fix our code. Doesn't seem worth the bother
for an old branch like this one.
Possible solution: re-fetch an old version of swagger tool.
Ditto.
This solution: just skip the swagger test. It seems unlikely
that anyone will make significant API changes on this branch.
```release-note
None
```
> [v3.4] CI: disable swagger step

- libpod/define/config.go
- libpod/kube.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/generate_kube_test.go
The format used for setting the bind-mount-options annotations
in the kube yaml was incorrect and caused k8s to throw an error
when trying to play the generated kube yaml.
Fix the annotation format to match the rules of k8s.
Fixes https://github.com/containers/podman/issues/15170
```release-note
None
```
> Fix bind-mount-option annotation in gen/play kube

- pkg/api/server/register_containers.go
- pkg/api/server/register_secrets.go
* ContainerKillLibpod "signal" query default is SIGKILL.
* ContainerListLibpod "namespace" query is failed to show.
* SecretListLibpod parameters is duplicated.
* SecretList parameters is duplicated.
```release-note
None
```
> Fix swagger documentation

- .cirrus.yml
On this branch, /usr/local/bin/swagger is fetched on each run
(vs, on current 2022-08 main, installed at VM-setup time).
Something changed, and the new binary is very strict about
bugs in our swagger comments, of which there seem to be many.
Possible solution: fix our code. Doesn't seem worth the bother
for an old branch like this one.
Possible solution: re-fetch an old version of swagger tool.
Ditto.
This solution: just skip the swagger test. It seems unlikely
that anyone will make significant API changes on this branch.
```release-note
None
```
> [v3.4.2-rhel] CI: disable swagger step

- libpod/runtime.go
- libpod/runtime_test.go
A suggestion for fixing #15569. The unit test isn't pretty and it assumes implementation details. A better fix would avoid using the global RNG at all but thats harder due to the dependency on docker. The global RNG is a misfeature IMO and shouldn't really be used by anything.
```release-note
Generated container names should be random again.
```
> libpod: Ensure that generated container names are random

- docs/source/markdown/options/digestfile.md
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
Only used in two pages. I took the liberty of adding the "N/A
on remote" text to manifest-push.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --digestfile

- libpod/define/mount.go
- libpod/define/mount_freebsd.go
- libpod/define/mount_linux.go
- libpod/define/mount_unsupported.go
- pkg/specgen/volumes.go
This makes the existing define.TypeBind platform-specific and gives it the value "nullfs" on FreeBSD where that perfoms a similar function to Linux bind mounts. The code in GenVolumeMounts is changed to use TypeBind instead of hard-coding a type of "bind".
```release-note
None
```
> Add support for FreeBSD volume mounts in specgen

- test/apiv2/10-images.at
While backporting a test from main, @edsantiago asked that
the test be adjusted as noted here:
https://github.com/containers/podman/pull/15555#issuecomment-1232791752.
This PR brings those same changes to main for posterity's sake.
```release-note
None
```
> Update test per comment in #15555

- docs/source/markdown/options/label.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Went with the podman-run version, where the "example" is
in the option template as per our guidelines.
I could not include the network- or volume-create
man pages, nor podman build.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --label

- libpod/container_internal_linux.go
- pkg/specgen/namespaces.go
- test/e2e/run_test.go
Mitigates a potential permissions issue. Mirrors https://github.com/containers/buildah/pull/4200 and https://github.com/cri-o/cri-o/pull/6159/files
```release-note
NONE
```
> Add container GID to additional groups

- podman.spec.rpkg
```release-note
None
```
@rhatdan @mheon @TomSweeneyRedHat PTAL
> [CI:BUILD] Copr: Define _user_tmpfilesdir for rhel

- docs/source/markdown/podman-build.1.md.in
Fixes: https://github.com/containers/podman/issues/15626
```release-note
None
```
> [CI:DOCS] Fix list of default capabilities

- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-container-clone.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
(memory-star, i.e., several memory options) that didn't get
included in #15276. Most of them are shoo-ins; the two in
container-clone and pod-clone deserve special attention
because of the "If unspecified" wording.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --memory*
