containers/podman

- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
Fixes: https://github.com/containers/podman/issues/13979
[NO NEW TESTS NEEDED] This is not true, waiting for Ed to give me a good
test.
> Pass --tls-verify option in podman -remote build

- pkg/signal/signal_common_test.go
- pkg/specgenutil/ports_test.go
- pkg/specgenutil/util_test.go
- pkg/specgenutil/volumes_test.go
Add some lightweight unit tests to the arsenal.
> Unit tests for pkg/specgenutil pkg/signal

- pkg/machine/qemu/machine.go
Basically, CI is broken for everyone until this merges.
> [CI:DOCS] Emergency fix for new CI linter

- RELEASE_NOTES.md
- version/version.go
> [CI:DOCS] Bump to v4.1.0-rc1

- libpod/pod.go
- libpod/pod_api.go
- test/system/200-pod.bats
Fixes: https://github.com/containers/podman/issues/14028
> Report properly whether pod shares host network

- cmd/podman/machine/inspect.go
- pkg/machine/config.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/config_test.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
I was asked to refactor machine inspect output to represent more common
and basic information.  machine inspect now has information that would
be appropriate for different machines.
> Refactor machine inspect

- pkg/machine/wsl/machine.go
This is the Windows portion of #14033
- Implements podman machine inspect
- Reuses some common qemu machine types introduced in #143033
- Adds similar transparent migration for newly added fields  
> Implement machine inspect for WSL

- libpod/boltdb_state_internal.go
Since networks must always be read from the db bucket directly we should
unset them in config to avoid caller from accidentally using them.
I already tried this but it didn't work because the networks were unset
after the config was marshalled.
```release-note
None
```
> libpod: unset networks before storing container conf

- cmd/podman/machine/inspect.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/qemu/machine.go
```release-note
Implement --format flag for podman machine inspect. Example:
$ podman machine inspect foo --format '{{.Name}}'
```
> Implement --format for machine inspect

- pkg/domain/utils/utils_test.go
- pkg/env/env_test.go
Improve "code coverage" with more unit-tests.
<!--
Thanks for sending a pull request!
Please make sure you've read our contributing guidelines and how to submit a pull request (https://github.com/containers/podman/blob/main/CONTRIBUTING.md#submitting-pull-requests).
In case you're only changing docs, make sure to prefix the pull-request title with "[CI:DOCS]".  That will prevent functional tests from running and save time and energy.
Finally, be sure to sign commits with your real name.  Since by opening
a PR you already have commits, you can add signatures if needed with
something like `git commit -s --amend`.
```none
```
> Add more unit tests

- README.md
- RELEASE_NOTES.md
- docs/source/Reference.rst
- version/version.go
> [CI:DOCS] Bump to v4.1.0-RC2

- hack/podman-registry-go/registry.go
- test/e2e/benchmarks_test.go
Polish the push and pull benchmarks.  In particular, make sure to not be
network bound during these benchmarks by running a local registry and
pushing a local image that can later on be pulled.
```release-note
None
```
> benchmarks: push/pull

- README.md
- RELEASE_NOTES.md
- cmd/podman/common/create.go
- cmd/podman/common/create_opts.go
- cmd/podman/play/kube.go
- libpod/container.go
- libpod/oci_attach_linux.go
- pkg/api/handlers/libpod/play.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/utils/utils_test.go
- pkg/env/env_test.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- test/e2e/container_clone_test.go
- test/system/700-play.bats
- version/version.go
> Bump to v4.1.0

- README.md
- docs/source/Reference.rst
> [CI:DOCS] update podman version in README and API docs

- test/e2e/common_test.go
do not try to first stop and then rm but combine the two operations in
a single command.
```release-note
None
```
> test: simplify cleanup code

- cmd/podman/machine/list.go
- pkg/machine/e2e/config_init.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/e2e/list_test.go
- pkg/machine/e2e/set_test.go
Add more machine tests for flags in init, inspect, and list.
```release-note
None
```
> Add more machine tests

- Makefile
Broken in #14191, merged unintentionally
> Fix broken pwd

- go.mod
- go.sum
- test/e2e/containers_conf_test.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_darwin.go
- vendor/github.com/containers/common/pkg/config/config_freebsd.go
- vendor/github.com/containers/common/pkg/config/config_linux.go
- vendor/github.com/containers/common/pkg/config/config_windows.go
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/pkg/config/default_darwin.go
- vendor/github.com/containers/common/pkg/config/default_freebsd.go
- vendor/github.com/containers/common/pkg/config/default_linux.go
- vendor/github.com/containers/common/pkg/config/default_windows.go
- vendor/github.com/containers/common/pkg/parse/parse_unix.go
- vendor/modules.txt
> Vendor in latest containers/common

- docs/source/Tutorials.rst
- docs/tutorials/mac_win_client.md
Update tutorial list to include Podman for Windows
Also, label the remote client tutorial as advanced so that users favor the managed machine approach.
> [CI:DOCS] Update tutorial list to include Podman for Windows

- cmd/podman/machine/machine_unix.go
Not sure if it was my IDE or what, but somehow  I ended up with a repeated bogus value in the build tag as part of #14206 
Sorry I missed this.
> Cleanup strange buildtag edit

- docs/source/markdown/podman-play-kube.1.md
This PR update _play kube_ doc following PR #14266 merging.
Signed-off-by: Cosmin Tupangiu <cosmin@redhat.com>
> Update _play kube_ doc following PR #14266 merging

- cmd/podman/common/completion.go
- pkg/api/handlers/compat/images_build.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
- pkg/util/utils.go
> Fix codespell errors

- libpod/events/events.go
- libpod/pod_top_linux.go
- pkg/api/handlers/compat/images.go
- pkg/auth/auth.go
- pkg/bindings/containers/archive.go
- pkg/bindings/play/play.go
- test/system/250-systemd.bats
More cleanups of TODOs.  No functional change at all. See individual commits.
```release-note
None
```
> Todo part 2

- libpod/plugin/volume_api.go
- libpod/pod_api.go
- libpod/runtime.go
Mostly, just removing the comments. These either have been done, or are no longer a good idea.
No code changes. [NO NEW TESTS NEEDED] as such.
> Remove more FIXMEs

- libpod/healthcheck_linux.go
Make sure to wait for the systemd operations to finish when
starting/stopping healtcheck timers and services.  Also make
sure to stop the timer before the service to avoid a race
with the timer.
[NO NEW TESTS NEEDED] since it is a non-functional change and existing
tests are expected to pass.
```release-note
Fix a potential race when cleaning up systemd health-check units and timers.
```
> healthcheck: wait for systemd operations

- cmd/podman/common/completion.go
- test/system/600-completion.bats
Add shell completion for paths inside the container or image. Currently
podman run IMAGE [TAB] only uses the default shell completion which
suggests paths on the host. This is fine for some cases but often the
user wants a path which only exists in the image/container.
This commits adds support for that. Both podman create/run can now
complete the paths from the image, podman cp ctr:... now completes paths
from the actual container.
```release-note
podman create/run/cp can now autocomplete paths in the image/container via the shell completion
```
> shell completion for paths inside the image/container

- contrib/podmanimage/README.md
> [CI:DOCS] Minor: Fix podmanimage README links

- pkg/api/handlers/libpod/manifests.go
- test/apiv2/12-imagesMore.at
- test/apiv2/15-manifest.at
- test/apiv2/70-short-names.at
- test/apiv2/test-apiv2
#14459 may not be merged but lets add some test cases for the issue
```release-note
None
```
> Add missing tests for manifests API

- cmd/podman/common/completion.go
- test/system/600-completion.bats
When you try to complete a path which exists and it is a file the
completion logic did not check the parent dir for other matching file
names. To fix that we have to check if the current completion is not a
dir and use the parent dir in this case.
See the updated test for an example why this is required.
Also make sure directories are correctly completed, the shell always
adds the "/" as suffix to signal the user that this path is a directory.
In this case we do not want to automatically add a space. When the path
is a regular file we want the space after the suggestion since there is
nothing more to complete.
This better matches the normal default shell completion.
```release-note
None
```
> shell completion: fix problems with container path completion

- docs/tutorials/remote_client.md
Explicitly include copy-and-paste code line for `ssh-copy-id` because people like myself will easily forget this part and (repeatedly) overlook it in the text. :blush:
Supersedes #14445 and attempts to address review by @TomSweeneyRedHat there (but enforcing a filename instead of using a placeholder).
(And, for some reason, adding the one "Signed-off-by" added another one:)
Signed-off-by: Christopher 'm4z' Holm <them4z@gmail.com>
Signed-off-by: Christopher 'm4z' Holm <them4z@googlemail.com>
```release-note
None
```
> [CI:DOCS] Update remote_client.md

- README.md
- RELEASE_NOTES.md
Redirect links to the new release, and update the release notes.
> [CI:DOCS] Update release notes and README on Main for v4.1.1

- pkg/machine/qemu/machine.go
Interrupting a `podman machine start` (ex: with CTRL-C) would leave
`Starting: true` in the machine's config file. Due to #14469 any
subsequent starts would fail since Podman would think the machine is
still in the process of starting.
Fixed here by listening for the interrupt signal and setting `Starting:
false` in the event.
```release-note
Fix interrupting a machine start leaves the machine unstartable
```
> Fix interrupting machine start leaves the machine unstartable

- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-exec.1.md
- docs/source/markdown/podman-run.1.md
* Add docs about trailing * functionality in podman-exec.1.md
* Rewrite --env description in podman-create.1.md and podman-run.1.md
* Rewrite the --env examples in podman-create.1.md and podman-run.1.md
```release-note
None
```
> [CI:DOCS] Rewrite --env docs

- CONTRIBUTING.md
Signed-off-by: Shubham Thakur <sbmthakur@gmail.com>
```release-note
None
```
> [CI:DOCS] Fix typos

- .cirrus.yml
```release-note
NONE
```
@mheon @Luap99 @containers/podman-maintainers PTAL.
> Cirrus: update branch name

- pkg/specgen/volumes.go
- test/e2e/run_volume_test.go
podman currently does not support relative volume paths. Add parsing for relative paths in specgen, converting whatever volume was given to an absolute path.
```release-note
relative volume paths now supported
```
> podman run/create -v relative filepath support

- pkg/signal/signal_common.go
- pkg/signal/signal_linux.go
- pkg/signal/signal_linux_mipsx.go
- pkg/signal/signal_unix.go
- pkg/signal/signal_unsupported.go
> Implement CatchAll and StopCatch in signal_unix.go

- go.sum
The CI is currently broken.  Update go.sum.
```release-note
None
```
> go.sum: run make vendor

- libpod/container_internal_linux.go
- pkg/criu/criu.go
- pkg/criu/criu_linux.go
- pkg/criu/criu_unsupported.go
> Add missing criu symbols to criu_unsupported.go

- Makefile
> FreeBSD build support

- libpod/runtime_pod_linux.go
[NO NEW TESTS NEEDED] now that podman's cgroup config tries to initialize controllers, cgroupfs errors out on pod creation
we need to mimic the behavior that used to exist and only create the cgroup when running as rootful
```release-note
None, cgroupfs seems to have been acting this way before.
```
> limit cgroupfs when rootless

- pkg/machine/keys.go
- pkg/machine/qemu/machine.go
This PR covers two edge cases discovered by fiddling with machine
manually.  It is possible (like after a manual cleanup of a machine)
that a leftover qemu socket file can indicate the prescense of a machine
running.
Also, reveal the error of a Exec.Command by wrapping the generic error
around what was in stderr.
```release-note
None
```
> reveal machine error, ignore false state

- cmd/podman/machine/machine.go
- cmd/podman/machine/machine_unix.go
- cmd/podman/machine/machine_windows.go
Fix podman machine on Windows (regression introduced by #14706 )
> Fix podman machine on Windows

- troubleshooting.md
* Add troubleshooting tip
"Unexpected carriage returns are outputted on the terminal"
```release-note
None
```
> [CI:DOCS] troubleshooting: document --tty and CR

- pkg/machine/wsl/machine.go
Implements Proxy support on Windows
As with mac, podman machine start will copy over proxy settings if present in the environment. Otherwise if there are no proxies specified in the env during start, settings will be cleared to match.
Resolves #14589 
```release-note
Implement Proxy support on Windows
```
> Implement proxy support for Windows

- test/e2e/common_test.go
two minor things I've noticed while looking at another unrelated issue.
More comments in each commit.
```release-note
None
```
> two minor tweaks to common_test.go

- pkg/machine/qemu/machine.go
Issue introduced in #14828
```release-note
NONE
```
> Fix qemu machine startHostNetworking always failing

- test/e2e/manifest_test.go
Followup to #14845: use defer(), not fragile global context,
to stop registry and clean up temporary envariable. Thanks
to mitr for the suggestion.
```release-note
None
```
> Manifest test cleanup: use defer()

- commands-demo.md
- contrib/remote/containers.conf
- docs/source/markdown/podman-run.1.md
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/define/container_inspect.go
- libpod/define/errors.go
- libpod/define/volume_inspect.go
- libpod/events/nullout.go
- libpod/oci_conmon_linux.go
- libpod/runtime_volume_linux.go
- test/e2e/stop_test.go
- test/system/helpers.bash
* Correct spelling and typos.
* Improve language.
For some of the edits the sentences were only corrected in part (i.e. not the whole sentences).
Some edits might not necessarily be improvements. (Just tell me which ones to revert).
The corrected text  _This protects the container's image from modification_ has more correct language
but it could probably be rewritten to not talk about "image" as it might be a bit misleading.
(Podman users might already be confused about the difference between a container and a container image)
```release-note
None
```
> [CI:DOCS] Improve language. Fix spelling and typos.

- .github/actions/check_cirrus_cron/cron_failures.sh
Previously the reply JSON was examined for the literal presence of the
string 'error'.  This was intended to catch server or query errors and
the like.  However it's not a sound design as valid/legitimate contents
could potentially contain the string.  Fix this by using the `-e` option
to `jq`, with a filter that should always result in a non-empty/null
match.  If this fails or returns null for some reason, then it's safe to
throw a real error code & message.
**Note:** This script is reused by other repositories to check their cirrus-cron job status.  I haven't observed it actually breaking, but it's certainly a glaring weak-spot @edsantiago noticed in a similar check elsewhere.
```release-note
None
```
> [CI:DOCS] GHA: Fix dumb error check

- docs/source/Tutorials.rst
- docs/tutorials/socket_activation.md
> [CI:DOCS] Tutorials.rst: add socket activation

- docs/source/markdown/podman-manifest.1.md
rme -> rm
```release-note
None
```
> [CI:DOCS] Fix typo in manifest manpage

- pkg/machine/e2e/machine_test.go
DownloadVMImage takes an extra argument.
```release-note
None
```
> Fix machine test

- docs/source/markdown/podman-generate-systemd.1.md
Fixes #15029
```release-note
None
```
This PR clarifies things a bit. (It could probably be improved)
> [CI:DOCS] podman-generate-systemd.1.md: document --sdnotify

- docs/tutorials/socket_activation.md
* Add section "Starting a socket-activated service".
* Add section "Stopping a socket-activated service".
* Clarify in the diagrams that socket activation
only happens for the first client connection.
```release-note
None
```
> [CI:DOCS] socket_activation.md: Add start/stop sections

- contrib/cirrus/setup_environment.sh
- test/system/200-pod.bats
```release-note
None
```
@cevich PTAL
> Cirrus: use dnf instead of rpm to install packages

- cmd/podman/containers/kill.go
- cmd/podman/containers/rm.go
- cmd/podman/containers/stop.go
- docs/source/markdown/podman-rm.1.md
- libpod/runtime_ctr.go
- pkg/domain/entities/containers.go
- pkg/domain/entities/reports/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- pkg/domain/infra/tunnel/helpers.go
- test/e2e/rm_test.go
- test/system/055-rm.bats
- test/upgrade/test-upgrade.bats
--filter : remove the filtered container.
```release-note
podman rm now supports the --filter option.
```
> Add rm --filter option

- RELEASE_NOTES.md
```release-note
None
```
@TomSweeneyRedHat @rhatdan @baude @vrothberg @ashley-cui PTAL
> [CI:DOCS] v4.2.0-rc3 release notes

- cmd/podman/containers/create.go
- test/e2e/run_userns_test.go
if an explicit mapping is specified, do not accept `--userns` since it
overriden to "private".
Closes: https://github.com/containers/podman/issues/15233
```release-note
--userns is no longer accepted when an explicit mapping is specified
```
> cmd: refuse --userns if a mapping is specified

- pkg/specgen/generate/container.go
use the sandbox id instead of the name for the
io.kubernetes.cri-o.SandboxID annotation used by gVisor.
Closes: https://github.com/containers/podman/issues/15223
[NO NEW TESTS NEEDED] it is specific to gVisor
```release-note
None
```
> specgen: use sandbox id instead of name for annotation

- pkg/machine/wsl/machine.go
```release-note
Prefer the rootless user when accessing the WSL prompt on Windows 
If podman machine init fails, Podman will not add connection data for the system.
```
> [4.2] Backport WSL Machine fixes

- CONTRIBUTING.md
- README.md
- commands-demo.md
- commands.md
- contrib/hello/README.md
- contrib/podmanimage/README.md
- docs/tutorials/README.md
- docs/tutorials/basic_networking.md
- docs/tutorials/podman-derivative-api.md
- docs/tutorials/podman-for-windows.md
- docs/tutorials/podman_tutorial.md
- docs/tutorials/podman_tutorial_cn.md
- docs/tutorials/rootless_tutorial.md
- test/README.md
- test/system/TODO.md
- transfer.md
- troubleshooting.md
for podman/#15222
Signed-off-by: unknowndevQwQ <unknowndevQwQ@pm.me>
```release-note
None
```
> [CI:DOCS]: update the podman logo

- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/set_test.go
when verifying that the memory was set correctly for a podman machine instance, we check if the number is between a range because based on architecture, operating system, and memory itself this number can differ significantly.
```release-note
None
```
> check memory test based on range

- docs/source/markdown/.gitignore
- docs/source/markdown/options/add-host.md
- docs/source/markdown/options/cgroup-parent.md
- docs/source/markdown/options/cgroupns.md
- docs/source/markdown/options/cgroups.md
- docs/source/markdown/options/conmon-pidfile.md
- docs/source/markdown/options/cpu-period.md
- docs/source/markdown/options/cpu-quota.md
- docs/source/markdown/options/cpu-rt-period.md
- docs/source/markdown/options/cpu-rt-runtime.md
- docs/source/markdown/options/cpu-shares.md
- docs/source/markdown/options/cpuset-cpus.md
- docs/source/markdown/options/cpuset-mems.md
- docs/source/markdown/options/no-hosts.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-container-clone.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- hack/markdown-preprocess
- hack/markdown-preprocess-review
Continued. Harder-to-review ones this time.
```release-note
man pages: continued refactoring and cleanup of common options
```
> Man pages: refactor common options

- README.md
- RELEASE_NOTES.md
Also add the Podman Desktop project to our README.
> [CI:DOCS] Update release notes on main branch for v4.2.0 release

- README.md
- contrib/snapcraft/snap/snapcraft.yaml
- docs/tutorials/podman_tutorial.md
- docs/tutorials/podman_tutorial_cn.md
None
```release-note
Updates links to install documentation
```
> [CI:DOCS] fix updated links

- pkg/rootless/rootless_linux.go
Fixes: https://github.com/containers/podman/issues/15295
[NO NEW TESTS NEEDED] This is fairly difficult to tests unless we start downloading quay.io/podman/stable, which could lead to breaking changes when podman and released config change.
```release-note
Podman when run within a container will no longer warn about "/" being mounted without being shared.
```
> Don't warn on '/' not being shared while in a container

- utils/utils_freebsd.go
> utils: Add missing symbols for FreeBSD

- cmd/podman/containers/restart.go
- docs/source/markdown/podman-restart.1.md
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/restart_test.go
--cidfile : Read container ID from the specified file and restart the container.
--filter : restart the filtered container.
```release-note
User can use podman restart --cidfile, --filter option.
```
> Add restart --cidfile, --filter

- CONTRIBUTING.md
Signed-off-by: Danilo Lima <danilo.glima@outlook.com>
```release-note
None
```
> [CI:DOCS] Update "CONTRIBUTING" file with Debian/Ubuntu dependencies"

- version/version.go
v4.2 has been branched already.
```release-note
None
```
> version bump to 4.3.0-dev

- docs/source/markdown/options/cpu-period.md
- docs/source/markdown/options/cpu-quota.md
- docs/source/markdown/options/cpu-shares.md
- docs/source/markdown/options/cpuset-cpus.md
- docs/source/markdown/options/cpuset-mems.md
- troubleshooting.md
Add a information about `cpu-shares` option and `CPUSET` limits.
```release-note
Update how to enable resource limit delegation
```
> [CI:DOCS] Update how to enable resource limit delegation

- libpod/info.go
- libpod/info_freebsd.go
- libpod/info_linux.go
- libpod/info_unsupported.go
This moves linux-specific code into info_linux.go, leaving generic code in info.go.
```release-note
None
```
> libpod: Add support for 'podman info' on FreeBSD

- docs/source/markdown/podman-system-service.1.md
- test/apiv2/python/rest_api/fixtures/api_testcase.py
- test/apiv2/python/rest_api/v1_test_rest_v1_0_0.py
- test/system/272-system-connection.bats
- test/system/900-ssh.bats
Fixes: https://github.com/containers/podman/issues/15430
```release-note
None
```
> Fix documentation of use of tcp connections

- test/system/200-pod.bats
Misspellings, broken code, missing tests
```release-note
None
```
> System test cleanup

- cmd/podman/syslog_common.go
- cmd/podman/syslog_unsupported.go
> cmd/podman: Enable --syslog on FreeBSD

- docs/source/markdown/podman-generate-systemd.1.md
Signed-off-by: Stefano Figura <stefano@figura.im>
```release-note
None
```
> [CI:DOCS] - Fix: template name inconsistency

- .cirrus.yml
Copied from: https://github.com/containers/aardvark-dns/pull/207
```release-note
None
```
> [CI:DOCS] Cirrus: Update meta-task for EC2 image

- pkg/domain/infra/abi/terminal/sigproxy_commn.go
- pkg/domain/infra/abi/terminal/terminal_common.go
- pkg/domain/infra/abi/terminal/terminal_unsupported.go
This just moves the code to files which can be shared with freebsd.
```release-note
None
```
> pkg/domain: Add terminal support for FreeBSD

- .cirrus.yml
Ref: #15502
```release-note
None
```
> [v4.2.0-rhel] [CI:DOCS] Cirrus: Update meta task for EC2

- .cirrus.yml
Ref: https://github.com/containers/podman/issues/15502
```release-note
None
```
> [v4.2] [CI:DOCS] Cirrus: Update meta task for EC2

- docs/source/markdown/options/device-read-bps.md
- docs/source/markdown/options/device-read-iops.md
- docs/source/markdown/options/device-write-bps.md
- docs/source/markdown/options/device-write-iops.md
- docs/source/markdown/podman-create.1.md.in
Followup from #15276: add the FAQ-26 link, and fix one
broken replacement.
```release-note
more man-page cleanup
```
> [CI:DOCS] Man pages: refactor common options: --device-X-Y

- test/system/250-systemd.bats
Under proxy environment, we need to add
proxy environment variables.
Related to: #15639
```release-note
None
```
> system tests: fix systemd tests in proxy environment

- test/apiv2/10-images.at
Backport the fix for #15388 from @vrothberg to fix CI on this branch.
> [v4.2.0-rhel] Fix CI

- go.mod
- go.sum
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/pkg/system/meminfo_freebsd.go
- vendor/github.com/containers/storage/pkg/unshare/unshare_linux.go
- vendor/modules.txt
> update c/storage to latest

- libpod/container_inspect.go
- libpod/container_inspect_freebsd.go
- libpod/container_inspect_linux.go
This also helps with support for 'podman cp' which will be in a later PR.
```release-note
None
```
> Add support for 'podman inspect' on FreeBSD

- hack/bats
- hack/check_root.sh
- hack/man-page-checker
- test/apiv2/test-apiv2
- test/buildah-bud/make-new-buildah-diffs
- test/compose/test-compose
- test/system/015-help.bats
- test/system/065-cp.bats
- test/system/070-build.bats
- test/system/160-volumes.bats
- test/system/400-unprivileged-access.bats
Followup to #15616, which is not usable as it is (way, way, way
too much noise) but actually found a few real nits that should
be fixed.
```release-note
None
```
> Cleanup: fix problems reported by shell lint

- docs/tutorials/podman-for-windows.md
- docs/tutorials/podman-install-certificate-authority.md
> [CI:DOCS] added docs for installing certificate authority

- libpod/container_internal_linux.go
- pkg/specgen/namespaces.go
- test/e2e/run_test.go
Mitigates a potential permissions issue.
```release-note
- Fix for CVE-2022-2989
```
> Add container GID to additional groups

- pkg/api/server/server.go
Fixes: https://github.com/containers/podman/issues/15925
```release-note
None
```
> Remove redundant log message

- libpod/boltdb_state.go
Backport of #14321  to v3.0.1-rhel per https://bugzilla.redhat.com/show_bug.cgi?id=2126937
```release-note
NONE
```
> [v3.0.1-rhel] Backport #14321

- libpod/healthcheck.go
- test/system/220-healthcheck.bats
- test/system/250-systemd.bats
Backport #16084 to v4.2.0-rhel
> [v4.2.0-rhel] Backport #16084

- build_osx.md
The header "Install build dependencies" was not correctly formatted.
Signed-off-by: Jesse Lang <jesse@jesselang.com>
```release-note
None
```
> [CI:DOCS] Fix markdown header typo

- go.mod
- go.sum
- test/e2e/top_test.go
- vendor/github.com/containers/psgo/README.md
- vendor/github.com/containers/psgo/psgo.go
- vendor/modules.txt
Add two new format-descriptors (`uid`, `huid`) to `top` command.
Also add e2e test for above descriptors.
```release-note
New format descriptors have been added to `podman top` command:
- 'uid':  prints the effective UID of the process as the decimal representation
- 'huid':  prints the corresponding host UID of a container process
$ ./bin/podman top 67 pid,uid,huid
PID         UID         HUID
1           0           1000
```
Closes: #16009
Signed-off-by: Piotr Resztak <piotr.resztak@gmail.com>
> vendor containers/psgo@v1.8.0

- libpod/container_internal_freebsd.go
- libpod/container_top_freebsd.go
- libpod/container_top_unsupported.go
- libpod/stats_freebsd.go
- pkg/util/utils_freebsd.go
This is a simplistic implementation which runs ps(1) on the host and does not try to support 'podman pod top' - I'll tackle that in a separate PS.
```release-note
None
```
> Add support for 'podman top' on FreeBSD

- docs/source/Reference.rst
Fixes #16300
```release-note
None
```
> [CI:DOCS] update api versions on docs.podman.io

- docs/tutorials/podman-for-windows.md
Signed-off-by: Johan Van de Wauw <johan@gisky.be>
```release-note
```
> [CI:DOCS] Fix small typo in windows docs

- docs/source/markdown/podman.1.md
> [CI:DOCS] fix --tmpdir typos

- go.mod
- go.sum
- vendor/github.com/godbus/dbus/v5/.golangci.yml
- vendor/github.com/godbus/dbus/v5/README.md
- vendor/github.com/godbus/dbus/v5/auth.go
- vendor/github.com/godbus/dbus/v5/call.go
- vendor/github.com/godbus/dbus/v5/conn.go
- vendor/github.com/godbus/dbus/v5/conn_darwin.go
- vendor/github.com/godbus/dbus/v5/conn_other.go
- vendor/github.com/godbus/dbus/v5/conn_unix.go
- vendor/github.com/godbus/dbus/v5/conn_windows.go
- vendor/github.com/godbus/dbus/v5/dbus.go
- vendor/github.com/godbus/dbus/v5/decoder.go
- vendor/github.com/godbus/dbus/v5/default_handler.go
- vendor/github.com/godbus/dbus/v5/export.go
- vendor/github.com/godbus/dbus/v5/match.go
- vendor/github.com/godbus/dbus/v5/message.go
- vendor/github.com/godbus/dbus/v5/object.go
- vendor/github.com/godbus/dbus/v5/sequential_handler.go
- vendor/github.com/godbus/dbus/v5/server_interfaces.go
- vendor/github.com/godbus/dbus/v5/sig.go
- vendor/github.com/godbus/dbus/v5/transport_nonce_tcp.go
- vendor/github.com/godbus/dbus/v5/transport_unix.go
- vendor/github.com/godbus/dbus/v5/transport_unixcred_freebsd.go
- vendor/github.com/godbus/dbus/v5/variant_parser.go
- vendor/modules.txt
This pulls in https://github.com/godbus/dbus/pull/332 allowing dbus to build without cgo on FreeBSD. This will allow freebsd targets in the cross build.
```release-note
None
```
> vendor github.com/godbus/dbus/v5@4b691ce

- troubleshooting.md
Add new troubleshooting tip:
Podman run fails with "Error: unrecognized namespace mode keep-id:uid=1000,gid=1000 passed"
Update the troubleshooting tips:
"Passed-in devices or files can't be accessed in rootless container (UID/GID mapping problem)" and
"Container creates a file that is not owned by the user's regular UID" to use
"--userns keep-id:uid=$uid,gid=$gid"
instead of the command-line options --uidmap and --gidmap
```release-note
None
```
> [CI:DOCS] troubleshooting: document keep-id options

- libpod/runtime.go
When shutting down the image engine we always wait for the image even goroutine to finish writing any outstanding events. However, the loop for that always waits 100msec every iteration. This means that (depending on the phase) shutdown is always delayed up to 100msec.
This is delaying "podman run" extra much because podman is run twice (once for the run and once as cleanup via a conmon callback).
Changing the image loop to exit immediately when a libimageEventsShutdown (but first checking for any outstanding events to write) improves podman run times by about 100msec on average.
Note: We can't just block on the event loop reading the shutdown event anymore, we need to wait until it read and processed any outstanding events, so we now send the shutdown event and then block waiting for the …
> [v4.2.0-rhel] libpod: Remove 100msec delay during shutdown

- build_osx.md
Signed-off-by: Björn Mosler <dev@bjoern.mosler.ch>
```release-note
None
```
> [CI:DOCS] Fix build targets in build_osx.md.

- RELEASE_NOTES.md
- version/version.go
Release notes and Bump to v4.3.1
```release-note
None
```
> Bump to v4.3.1

- README.md
Also, bump version to v4.3.1 in the README
> [CI:DOCS] Add release keys to README

- RELEASE_NOTES.md
> [CI:DOCS] Update Main: Release notes for 4.3.1

- pkg/api/server/register_images.go
- pkg/api/server/register_networks.go
- pkg/auth/auth.go
- pkg/checkpoint/checkpoint_restore.go
- pkg/checkpoint/crutils/checkpoint_restore_utils.go
- pkg/env/env_windows.go
- pkg/k8s.io/api/apps/v1/types.go
- pkg/k8s.io/api/core/v1/annotation_key_constants.go
- pkg/k8s.io/api/core/v1/types.go
- pkg/machine/fcos.go
- pkg/machine/pull.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/util_windows.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/namespaces.go
- pkg/specgen/namespaces.go
- pkg/systemd/parser/split.go
- pkg/util/utils.go
- troubleshooting.md
> [CI:DOCS] Fix spelling and typos

- docs/source/markdown/podman-image-unmount.1.md
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-run.1.md.in
- libpod/container.go
- libpod/container_validate.go
- libpod/networking_common.go
- libpod/networking_linux.go
- libpod/networking_unsupported.go
- libpod/options.go
- libpod/runtime.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/network.go
- pkg/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- pkg/specgen/generate/ports.go
- pkg/specgen/namespaces.go
- pkg/specgen/volumes.go
- pkg/systemd/generate/containers.go
- test/e2e/checkpoint_test.go
- test/e2e/run_userns_test.go
- test/python/docker/compat/common.py
- test/python/docker/compat/test_containers.py
- test/upgrade/test-upgrade.bats
> Fix language. Mostly spelling a -> an

- docs/source/markdown/podman-volume-create.1.md
Fix a never closed emphasis.
Signed-off-by: Ingo Becker <ingo@orgizm.net>
```release-note
None
```
> [CI:DOCS] Fix manpage emphasis

- .github/ISSUE_TEMPLATE.md
> [CI:DOCS] Fix MD for Troubleshooting Guide link in GitHub Issue Template

- pkg/api/server/register_containers.go
None
```release-note
Extend podman checkpoint / restore rest API documentation
```
> [CI:DOCS] Expand and fix checkpoint restore documentation

- OWNERS
Add @n1hility to the OWNERS file.  They are maintaining various subsystems of Podman including machine on Windows.
```release-note
None
```
> [CI:DOCS] OWNERS: add  Jason T. Greene

- pkg/machine/wsl/machine.go
Fixes #16550 - Podman machine won't start due to corrupted config file
```release-note
Improve atomicity of VM state persistence on Windows to better tolerate FS corruption in cases of power loss or system failure.
```
This change uses a write + rename approach. Os.Rename() on windows maps to MoveFileEx with MOVEFILE_REPLACE_EXISTING, which is a journaled metadata update (ZwSetInformationFile) on NTFS, so atomic.
> Improve atomicity of VM state persistence on Windows

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/syslog.identifier.kube
- test/e2e/quadlet_test.go
Resolves #16593 
No, since Quadlet was not yet released
```release-note
None
```
> Quadlet Kube: Set SyslogIdentifier if was not set

- go.mod
- go.sum
- pkg/domain/infra/abi/network.go
- vendor/github.com/containers/common/libnetwork/cni/cni_types.go
- vendor/github.com/containers/common/libnetwork/cni/config.go
- vendor/github.com/containers/common/libnetwork/cni/network.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/netavark/network.go
- vendor/github.com/containers/common/libnetwork/types/network.go
- vendor/github.com/containers/common/pkg/cgroups/cgroups.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/secrets/filedriver/filedriver.go
- vendor/github.com/containers/common/pkg/secrets/secrets.go
- vendor/golang.org/x/sys/execabs/execabs_go119.go
- vendor/golang.org/x/sys/windows/syscall_windows.go
- vendor/golang.org/x/sys/windows/zsyscall_windows.go
- vendor/modules.txt
The new version adds NetworkCreateOptions. For now pass nil
No
```release-note
None
```
> Update containers common package

- test/README.md
Drop a note on how to run single tests with the remote client.
```release-note
None
```
> [CI:DOCS] test/README.md: run tests with podman-remote

- docs/source/markdown/options/ipc.md
> docs/options/ipc: fix list syntax

- docs/source/markdown/options/mount.md
- docs/source/markdown/options/volume.md
[CI:DOCS] fixup for https://github.com/containers/podman/pull/16837
```release-note
None
```
> doc: fix documentation for idmapped mounts

- .golangci.yml
- Makefile
- cmd/podman/containers/run.go
- cmd/podman/registry/config.go
- cmd/quadlet/main.go
- libpod/boltdb_state.go
- libpod/container.go
- libpod/define/annotations.go
- libpod/define/containerstate.go
- libpod/logs/reversereader/reversereader.go
- libpod/options.go
- libpod/pod_internal.go
- pkg/bindings/pods/pods.go
- pkg/channel/writer.go
- pkg/lookup/lookup.go
- pkg/rootless/rootless.go
- pkg/specgen/generate/ports_test.go
- pkg/specgen/namespaces.go
- test/e2e/images_test.go
Also fix a number of duplicate words.  Yet disable the new `dupword` linter as it displays too many false positives.
```release-note
None
```
> bump golangci-lint to v1.50.1

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/cgroups/cgroups.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
```release-note
do not start up a dbus daemon if it is not already running.
```
> [v4.2.0-rhel] vendor: bump to c/common v0.49.3

- Makefile
- cmd/quadlet/main.go
- hack/bats
- test/system/252-quadlet.bats
- test/system/helpers.bash
- test/system/helpers.systemd.bash
This adds some initial quadlet system tests. This contains only tests for regular .container and .volume files. I will let @ygalblum add kube tests later.
```release-note
None
```
> Quadlet system test

- go.mod
- go.sum
- vendor/modules.txt
> Update vendor of containters/(common, image)

- test/e2e/play_kube_test.go
- test/e2e/prune_test.go
- test/e2e/pull_test.go
- test/e2e/push_test.go
- test/e2e/quadlet_test.go
- test/e2e/run_device_test.go
- test/e2e/run_test.go
- test/utils/common_function_test.go
New fixes since my last commit 2ddf1c5cbd11.
https://github.com/nunnatsa/ginkgolinter
```release-note
None
```
> ginkgo tests: apply ginkgolinter fixes

- go.mod
- go.sum
- vendor/github.com/containers/storage/layers.go
- vendor/modules.txt
needed for: https://github.com/containers/storage/pull/1452
> [4.2.0-rhel] vendor: bump containers/storage

- test/e2e/containers_conf_test.go
Prevents overwriting of TMPDIR environment.
```release-note
None
```
> e2e: fix containers_conf_test

- cmd/podman/system/df.go
The current code modifies a global variable which works but is bad design since it could be uses elsewhere. Since we just exit after the df command this is not an issue right now but it could become one in the future.
A better fix is to implement a custom `MarshalJSON()` method on the struct which will be called if this struct will be marshaled.
Fixes some changes from 24b1e81c5d76, the test should from there should still pass.
```release-note
None
```
> system df: improve json output code

- hack/bats
- clean up hard-to-read logic
- add --remote option
- improve usage message
```release-note
None
```
> [CI:DOCS] hack/bats: various improvements

- cmd/podman/parse/net.go
- go.mod
- go.sum
- libpod/options.go
- pkg/bindings/images/build.go
- pkg/systemd/quadlet/quadlet.go
- vendor/github.com/containers/storage/.cirrus.yml
- vendor/github.com/containers/storage/drivers/driver.go
- vendor/github.com/containers/storage/pkg/idtools/usergroupadd_linux.go
- vendor/github.com/containers/storage/pkg/regexp/regexp.go
- vendor/github.com/containers/storage/pkg/regexp/regexp_dontprecompile.go
- vendor/github.com/containers/storage/pkg/regexp/regexp_precompile.go
- vendor/github.com/containers/storage/pkg/stringid/stringid.go
- vendor/github.com/containers/storage/store.go
- vendor/github.com/containers/storage/types/options.go
- vendor/modules.txt
> Use containers/storage/pkg/regexp in place of regexp

- test/e2e/systemd_activate_test.go
- When SELinux is enabled, a storage root directory should be labeled with a specific value.
- `stop podman.service` test changes a storage root directory, therefore we need to cleanup a container with --root option.
```release-note
None
```
> e2e: fix systemd_activate_test

- .cirrus.yml
> [v4.0-rhel] [CI:BUILD] Cirrus: Stop building for OSX

- docs/source/markdown/options/userns.container.md
Fixes: https://github.com/containers/podman/issues/17134
```release-note
None
```
> Cleanup documentation on --userns=auto

- .cirrus.yml
- contrib/cirrus/win-podman-machine-main.ps1
- contrib/cirrus/win-podman-machine-verify.ps1
- contrib/cirrus/wsl-env-launch.ps1
[DO NOT MERGE] Checking an image 
> [DO NOT MERGE] Checking an image 

- test/e2e/checkpoint_test.go
Closes: #14653
```release-note
None
```
> Remove workarounds for 14653 (checkpoint test failures)

- pkg/machine/fcos.go
- pkg/machine/fedora_unix.go
- pkg/machine/fedora_windows.go
- pkg/machine/pull.go
- pkg/machine/wsl/fedora.go
- pkg/machine/wsl/machine.go
Small amount of refactoring to make WSL specific stuff into the WSL package where possible.  This is in preparation for the possibility of adding more virtualization backends.
```release-note
None
```
> WSL refactoring

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/modules.txt
> [v4.4] Bump to Buildah v1.29.0

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/modules.txt
> Bump Bulidah to v1.29.0

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
Related:
https://github.com/containers/automation_images/issues/159
https://github.com/containers/automation_images/issues/161
```release-note
None
```
> Bump cirrus image with easier dependency management

- pkg/machine/pull.go
Follow-up to #17266
```release-note
NONE
```
> [CI:DOCS] Add comment to clarify error handling intention

- RELEASE_NOTES.md
- version/version.go
Final release notes and bump to v4.4.0
```release-note
None
```
> Bump to v4.4.0

- hack/perf/bz-2162111.sh
Add benchmarks for stopping the containers as well.
```release-note
None
```
Added stop for the sake of completeness.
> [CI:DOCS] hack/perf/bz-2162111.sh: measure stop

- README.md
- RELEASE_NOTES.md
- docs/source/Reference.rst
- version/version.go
> Update main to reflect v4.4.0 release

- .github/ISSUE_TEMPLATE/bug_report.yaml
Render "podman info output" in YAML for better readability.
Signed-off-by: salevdns <24809481+salevdns@users.noreply.github.com>
```release-note
None
```
> [CI:DOCS] Add YAML syntax highlighting in issue template

- docs/source/markdown/podman-events.1.md
```release-note
Document journald identifiers used in the journald events backend.
```
> [CI:DOCS] events: document journald identifiers

- test/e2e/healthcheck_run_test.go
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
```release-note
nne
```
> Fix typos in comments

- pkg/systemd/quadlet/quadlet.go
Since this is just sorting keys.
```release-note
None
```
> Sort quadlet keys to make it easier to read

- OWNERS
Both are Quadlet maintainers and active contributors. With great power, comes great responsibility.
```release-note
None
```
> [CI:DOCS] OWNERS: add @ygalblum and @alexlarsson

- RELEASE_NOTES.md
- version/version.go
Release notes + 4.4.1 bump.
```release-note
None
```
> Bump to v4.4.1

- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-volume-create.1.md
> [CI:DOCS] Cleanup some man pages to display options with line breaks

- Makefile
- contrib/cirrus/lib.sh
- libpod/define/container_inspect.go
- pkg/k8s.io/api/core/v1/types.go
- pkg/k8s.io/apimachinery/pkg/api/resource/quantity.go
- test/system/035-logs.bats
> Run codespell on codebase

- cmd/podman/system/connection/add.go
- cmd/podman/utils/error.go
- libpod/container_api.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal_common.go
- libpod/container_stat_common.go
- libpod/define/container.go
- libpod/events/nullout.go
- libpod/lock/shm/shm_lock.c
- libpod/logs/log.go
- libpod/networking_freebsd.go
- libpod/networking_linux.go
- libpod/networking_slirp4netns.go
- libpod/networking_unsupported.go
- libpod/options.go
- libpod/runtime.go
- libpod/runtime_ctr.go
- pkg/api/handlers/compat/containers_archive.go
- pkg/api/handlers/compat/volumes.go
- pkg/specgen/generate/container.go
- test/apiv2/10-images.at
- test/e2e/play_kube_test.go
- test/e2e/volume_create_test.go
- test/system/160-volumes.bats
> Fix typos. Improve language.

- cmd/podman/common/create.go
- cmd/podman/kube/generate.go
- cmd/quadlet/main.go
- contrib/cirrus/logformatter.t
- contrib/cirrus/wsl-env-launch.ps1
- docs/source/markdown/podman-network.1.md
- docs/source/markdown/podman-systemd.unit.5.md
- docs/tutorials/qemu-remote-tutorial.md
- libpod/boltdb_state.go
- libpod/options.go
- pkg/api/server/register_networks.go
- pkg/bindings/errors.go
- pkg/domain/utils/scp.go
- pkg/errorhandling/errorhandling.go
- pkg/k8s.io/apimachinery/pkg/api/resource/quantity.go
- pkg/k8s.io/apimachinery/pkg/apis/meta/v1/duration.go
- pkg/k8s.io/apimachinery/pkg/apis/meta/v1/time.go
- pkg/machine/e2e/config_ssh_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/set_test.go
- pkg/machine/e2e/ssh_test.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/oci_linux.go
- pkg/util/camelcase/README.md
- test/python/docker/compat/test_containers.py
Just a test for demo purpose. Trying out https://github.com/crate-ci/typos/
Software version used
https://github.com/crate-ci/typos/releases/tag/v1.13.10
The binary was downloaded from
https://github.com/crate-ci/typos/releases/download/v1.13.10/typos-v1.13.10-x86_64-unknown-linux-musl.tar.gz
Command that was run:
```
typos --write-changes  docs cmd cni contrib dependencies docs hack libpod pkg utils
```
```release-note
None
```
> run "typos --write-changes" 

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/basic.container
```release-note
None
```
Existing tests should handle this.
> Quadlet use crun specified in containers.conf

- docs/tutorials/mac_win_client.md
- docs/tutorials/podman-for-windows.md
> [CI:DOCS] Windows/Mac docs link update

- docs/source/markdown/podman-build.1.md.in
> docs: context is not optional for build

- RELEASE_NOTES.md
- version/version.go
As title says.
```release-note
None
```
> Bump to v4.4.2

- pkg/bindings/README.md
> [CI:DOCS] Fix user socket path in README

- cmd/podman/machine/rm.go
Update default machine to an available one in config when the current default machine is removed so podman command doesn't point to a deleted machine by default.
Fixes: https://github.com/containers/podman/issues/16483
Yes
```release-note
None
```
> fix: update the default machine value when the previously set default machine is deleted

- troubleshooting.md
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2139191
We have a timing issue when doing a build or pull of an image and a second process is removing them at the same time.  This is not a window we're going to close now, so I'm adding a note to the troubleshooting guide to document it.
```release-note
NOne
```
> [CI:DOCS] Add image not found info to troubleshooting

- test/e2e/common_test.go
- test/e2e/run_userns_test.go
> test: reenable idmap test

- docs/source/markdown/podman-run.1.md.in
```release-note
None
```
In this PR, I document changes made in https://github.com/containers/podman/issues/3967
> [CI:DOCS] fix: Document removing anonymous volumes

- contrib/cirrus/runner.sh
"Just this once", I thought, adding an obscure unmaintainable
duplication to the CI code. When will I learn?
This fixes the logformatter output filename to handle boltdb/sqlite.
```release-note
None
```
> logformatter: futureproof output filename

- Makefile
- cmd/podman/containers/export.go
- libpod/runtime_img.go
- test/e2e/run_networking_test.go
- test/e2e/systemd_activate_test.go
- test/system/030-run.bats
- test/system/150-login.bats
> Run make codespell

- test/system/520-checkpoint.bats
> test: podman checkpoint/restore the latest container

- go.mod
- go.sum
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/error.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/memory_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/processor_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/summary.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/system_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/system_settings_builder.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vmm.go
- vendor/github.com/containers/libhvee/pkg/wmiext/conversion.go
- vendor/github.com/containers/libhvee/pkg/wmiext/service.go
- vendor/modules.txt
when looking for a machine, look it up locally first to prevent accidental collision with non-podman machine vms.  in the cast of `podman machine ls`, only list podman machines found by json files
```release-note
none
```
> hyperv: lookup machine on local filesystem first

- hack/install_golangci.sh
It flakes once or twice a day:
VERSION=1.51.1 ./hack/install_golangci.sh
Installing golangci-lint v1.51.1 into ./bin/golangci-lint
golangci/golangci-lint info checking GitHub for tag 'v1.51.1'
golangci/golangci-lint crit unable to find 'v1.51.1' - use 'latest'
or see https://github.com/golangci/golangci-lint/releases for details
No visibility into why, and no special reason to believe that
retrying five seconds later will work, but it seems worth a try.
Sample log from [today](https://api.cirrus-ci.com/v1/task/5584294282788864/logs/main.log)
```release-note
None
```
> CI: retry the golangci install

- pkg/specgen/generate/container_create.go
- test/e2e/containers_conf_test.go
```release-note
`podman run --cgroup_config` defaults are now supported in containers.conf
```
> Add support for cgroup_config from containers.conf

- cmd/podman/secrets/exists.go
- docs/source/markdown/podman-secret-exists.1.md
- docs/source/markdown/podman-secret.1.md
- pkg/api/handlers/libpod/secrets.go
- pkg/api/server/register_secrets.go
- pkg/bindings/secrets/secrets.go
- pkg/domain/entities/engine_container.go
- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/tunnel/secrets.go
- test/apiv2/50-secrets.at
- test/e2e/secret_test.go
Add the command along with the abi and tunnel support Add e2e tests
Add man page
Yes
```release-note
New command - podman secret exist <name>
```
> Add support for secret exists

- contrib/cirrus/setup_environment.sh
Cherry-pick of https://github.com/containers/podman/pull/17505 to this branch.
```release-note
None
```
> [v4.4] Workaround for cdn03.quay.io flake

- test/e2e/images_test.go
The "podman pull by digest and list --all" e2e test pulls an image using a tagged reference when an image with the same ID is already present in a read-only additional image store.
This causes a new image record to be created in read-write storage.
The test then removes this entry, pulls the image again using a digested reference, and then expects the image to not have any tagged names in it when it goes to look at it again.
Newer containers/storage will ensure that at the point when the read-write image record is created, that it includes all of the data items and naming information from the read-only copy of the image, so that this information doesn't appear to be lost.
Change the test to use "untag" instead of "rmi", which should pass with either the older or newer containers/storage. …
> "podman pull by digest and list --all" test: untag instead of rmi

- RELEASE_NOTES.md
As title says. 
```release-note
None
```
> [CI:DOCS] Release notes for 4.5.0 Part 1

- docs/source/markdown/options/systemd.md
- docs/source/markdown/options/userns.container.md
- docs/source/markdown/podman-container-clone.1.md.in
- docs/source/markdown/podman-cp.1.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-pod-logs.1.md.in
- docs/source/markdown/podman-pod-ps.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-systemd.unit.5.md
- docs/source/markdown/podman-volume-create.1.md
- docs/source/markdown/podman.1.md
> [ci:docs] Capitalize all uid,gid and id words that are not options in docs

- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
Fixes #18011 
Updates container configuration and machine configuration state saving to be atomic on Linux, Mac, and Windows.
```release-note
Fixes possible configuration state corruption with podman machine during system failures on Mac, Linux, and Windows
```
> Update podman to use atomic container and machine config updates

- .github/renovate.json5
Ref: https://github.com/containers/podman/issues/18139#issuecomment-1503487244
```release-note
None
```
> [CI:DOCS] Tweak renovate configuration

- version/rawversion/version.go
We now have a v4.5 branch.
```release-note
None
```
@mheon remind me, are we doing v4.6 ?
> bump main to v4.6.0-dev

- test/e2e/run_test.go
Podman's container-name generation depends on the global RNG state being properly initialized (seeded).  Should this not happen for some reason (or it's seeded with a static value), podman will generate the exact same repeating sequence of container names (assuming no clashes with existing containers).  Add a test to confirm this is always the case.
```release-note
None
```
> Add name-generation test

- cmd/podman/kube/play.go
- libpod/container_internal.go
- test/system/251-system-service.bats
- test/system/700-play.bats
Some small things I've noticed while I was debugging a different issue.
More details in each commit
```release-note
None
```
> some small fixes

- pkg/machine/ignition.go
When initing a podman machine, we match core's UID to the UID of the user on the host. If the UID is in the subUID range, the machine throws an error. Check if the UID is within the default range for /etc/subuid (10000:1000000), and if it is, we adjust the range to not include it.
[NO NEW TESTS NEEDED] 
Mostly because this requires changing UID of the host and I don't think we should mess with it, but let me know if I should write a test.
Fixes: https://github.com/containers/podman/issues/17893
```release-note
Fixed a bug where the `podman machine init` command would create invalid machines when run with certain UID's
```
> Fix clashing subuid

- docs/source/markdown/podman-completion.1.md
Remove extra period.
```release-note
Removed extra period.
```
> [CI:DOCS] Update podman-completion.1.md

- test/e2e/play_kube_test.go
...and, add a missing error-message check.
Sample [flake log](https://api.cirrus-ci.com/v1/artifact/task/5371697788878848/html/int-podman-fedora-38-root-host-boltdb.log.html#t--podman-play-kube-seccomp-pod-level--1).
```release-note
None
```
> e2e: fix more test races (missing "wait")

- docs/source/markdown/podman-image-sign.1.md.in
> Correct markdown in docs

- pkg/machine/pull.go
Fixes: #17718
Replaces: https://github.com/containers/podman/pull/18156
```release-note
None
```
> Increase download progress to 80ch

- test/system/252-quadlet.bats
The new exit-code propagation test is racy: 'podman wait' can
fail if the service container has already been cleaned up by
systemd.
Solution: run the inspect and wait tests opportunistically, i.e.,
only if those commands succeed. If they fail, confirm that they
fail with ENOSUCHCONTAINER. This may silently lose us some
coverage ... but none of it is important. The important
test, systemctl final status, remains.
Also, as drive-bys:
- add a FIXME comment documenting another race condition
that I'm not bothering to fix right now
- give distinct names to unit files, for readability in
test failures
Fixes: #18732
```release-note
None
```
> systests: fix race in quadlet tests

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/pull.container
- test/e2e/quadlet_test.go
Update code, doc and test
Remove doc comment on pull policy
Resolves: #18779
Yes
```release-note
Quadlet - add support for Pull key in .container
```
> Quadlet - add support for Pull key in .container

- pkg/api/server/doc.go
> Fix system service manpage name in API Documentation

- test/e2e/common_test.go
Fixes: #18855
```release-note
None
```
> e2e: GetRandomIPAddress(): parallelize

- docs/source/markdown/podman-systemd.unit.5.md
Fixes #17909
```release-note
None
```
> [CI:DOCS] quadlet: adjust container unit documentation

- go.mod
- go.sum
- test/system/010-images.bats
- vendor/github.com/containers/common/libimage/pull.go
- vendor/github.com/containers/common/pkg/retry/retry.go
- vendor/golang.org/x/crypto/ssh/common.go
- vendor/golang.org/x/crypto/ssh/mac.go
- vendor/modules.txt
```release-note
Fix printing ids multiple times when using additional stores.
```
> Verify podman pull dup image only prints id once 

- Makefile
- cmd/podman/containers/exec.go
- cmd/podman/main.go
- cmd/podman/registry/remote.go
- docs/source/markdown/podmansh.1.md
- rpm/podman.spec
- test/e2e/exec_test.go
- test/system/075-exec.bats
```release-note
podmansh: New command and confined login shell
```
> New command: podmansh

- docs/source/markdown/options/env-merge.md
- pkg/specgen/generate/container.go
- test/e2e/run_env_test.go
> run,create: modify `--env-merge` behavior for non-existent vars

- cmd/podman/system/service_abi.go
- cmd/rootlessport/main.go
- go.mod
- go.sum
- libpod/container_exec.go
- libpod/container_internal.go
- libpod/container_internal_common.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
- libpod/info_linux.go
- libpod/networking_common.go
- libpod/networking_freebsd.go
- libpod/networking_linux.go
- libpod/networking_slirp4netns.go
- libpod/networking_unsupported.go
- libpod/oci_conmon_common.go
- libpod/util.go
- vendor/github.com/containers/common/libnetwork/slirp4netns/const.go
- vendor/github.com/containers/common/libnetwork/slirp4netns/slirp4netns.go
- vendor/github.com/containers/common/pkg/rootlessport/rootlessport_linux.go
- vendor/github.com/containers/common/pkg/servicereaper/service.go
- vendor/github.com/containers/common/pkg/util/util.go
- vendor/modules.txt
Most of the code moved there so if from there and remove it here.
Some extra changes are required here. This is a bit of a mess. The pipe
handling makes this a bit more difficult.
[NO NEW TESTS NEEDED] This is just a rework, existing tests must pass.
also see https://github.com/containers/common/pull/1517
```release-note
None
```
> use slirp4netns code from c/common

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] Fix example on PublishPort

- docs/source/markdown/podmansh.1.md
> [CI:DOCS] Fix up podmansh man page

- pkg/specgen/generate/oci_freebsd.go
This is limited to images that don't depend on complex cgroup or capability setups but does cover enough functionality to be useful.
```release-note
Allow running Linux images on FreeBSD using emulation.
```
> pkg/specgen: Add support for Linux emulation on FreeBSD

- test/e2e/systemd_test.go
[October 2022] While mucking around in this test, I noticed that
a test was being unnecessarily skipped in rootless. Reason was,
test was creating a /etc/systemd file, which it really shouldn't
have been doing anyway.
[Flash forward to June 2023] Ugh. This got complicated, so I
abandoned it. But it's flaking in CI, so one focus-push later,
here's everything that this PR fixes:
- create systemd unit file in proper (safe) path.
- create it *with proper podman options!!!* As in, the
whole --this --that --root --tmpdir options! Sheesh!
- use a pseudorandom service name, not just "redis"
- invoke systemctl/journalctl with --system or --user
as appropriate.
- remove unnecessary "bash -c"
- remove SkipIfRootless, but add SkipIfRemote …
> e2e: systemd test: major fixes

- rpm/podman.spec
- build dnsname the old way otherwise it fails on koji
- use the binary path for go-md2man for successful ELN builds
```release-note
None
```
> [CI:BUILD] RPM: Fix koji and ELN issues

- test/system/505-networking-pasta.bats
Fix for #17287.
```release-note
None
```
> Correct intermittent failures in pasta port range forwarding tests

- test/system/505-networking-pasta.bats
Cleanup:
- typo fix, a misspelled variable resulting in test being NOP
- remove unnecessary variable (followup to #19044)
New test:
- opportunistically add a test for new `default_rootless_network_cmd` in containers.conf (followup to #19032). Because it just made me queasy to test that only in e2e.
New sanity check:
- in `pasta_test_do()`, the convoluted multipurpose helper function, cross-reference the test name (displayed to users) vs the function args. Basically, make sure that if the test name says TCP we don't inadvertently test UDP, same with IPv4/6 and interfaces and ranges and whatnot.
```release-note
None
```
> pasta system tests: cleanup, fixes, sanity check

- test/e2e/common_test.go
- test/e2e/cp_test.go
- test/e2e/create_test.go
- test/e2e/generate_kube_test.go
- test/e2e/generate_systemd_test.go
- test/e2e/kill_test.go
- test/e2e/pause_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_rm_test.go
- test/e2e/pod_start_test.go
- test/e2e/pod_stop_test.go
- test/e2e/restart_test.go
- test/e2e/rm_test.go
- test/e2e/stop_test.go
- test/tools/go.mod
- test/tools/go.sum
- test/tools/vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generate_command.go
- test/tools/vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generate_templates.go
- test/tools/vendor/github.com/onsi/ginkgo/v2/ginkgo/generators/generators_common.go
- test/tools/vendor/github.com/onsi/ginkgo/v2/types/version.go
- test/tools/vendor/modules.txt
see commits
```release-note
None
```
> test/e2e: several fixes

- pkg/machine/qemu/machine.go
Make sure that starting a qemu machine uses proper exponential backoffs and that a single variable isn't shared across multiple backoffs.
DO NOT BACKPORT: I want to avoid backporting this PR to the upcoming 4.6 release as it increases the flakiness of machine start (see #17403). On my M2 machine, the flake rate seems to have increased with this change and I strongly suspect that additional/redundant sleep after waiting for the machine to be running and listening reduced the flakiness.  My hope is to have more predictable behavior and find the sources of the flakes soon.
```release-note
None
```
> machine start: qemu: adjust backoffs

- RELEASE_NOTES.md
- docs/source/markdown/podmansh.1.md
```release-note
None
```
@ashley-cui @rhatdan @mheon PTAL
> [CI:DOCS] tag podmansh as tech preview in RELEASE_NOTES.md

- RELEASE_NOTES.md
> [CI:DOCS] [Release Notes]: add static routes

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/api/handlers/compat/images_push.go
- test/apiv2/test-apiv2
- test/e2e/common_test.go
> Run codespell on code

- pkg/machine/applehv/claim.go
- pkg/machine/applehv/machine.go
- pkg/machine/applehv/vfkit.go
- pkg/machine/config.go
- pkg/machine/machine_unix.go
- pkg/machine/qemu/machine.go
- pkg/machine/volumes.go
* Enabled user-mode networking with gvproxy
* VirtIOFS volumes supported
```release-note
None
```
> Podman machine AppleHV pass number 3

- contrib/win-installer/build.ps1
Workaround problem with PanelSwExt.
```release-note
none
```
> Fix windows installer build

- test/system/252-quadlet.bats
quadlet volume-path system test was making invalid assumptions
about $TMPDIR, causing test to fail when TMPDIR=/var/tmp or /dev/shm
Minor cleanup too.
```release-note
None
```
> quadlet systest: fix broken tmpdir references

- test/system/252-quadlet.bats
Some quadlet tests are failing on RHEL8: test code was
using journalctl to check output from containers. This
fails on RHEL8, where default log driver is k8s-file.
Solution: use 'podman logs' instead. To do so, we need to
keep the containers alive (otherwise, quadlet seems to
delete them on exit). Do so by running 'top -b' (batch);
the currently-used 'top' was failing because not-a-tty.
```release-note
None
```
> systests: quadlet: fixes for RHEL8

- contrib/win-installer/build.ps1
Clean cherrypick of #19270
```release-note
None
```
> [v4.6] Fix windows installer

- docs/source/markdown/podman-systemd.unit.5.md
```release-note
None
```
Wasn't mentioned in the docs anywhere and took me a while to find it.
> [CI:DOCS] Add note on debugging quadlet unit files

- test/system/252-quadlet.bats
When the test expects the container to exit, force using journald in order to find its startup logs
No
```release-note
None
```
Resolves: #19296
> Quadlet system test - force journald log driver for short lived containers

- pkg/machine/qemu/machine.go
The functions for QEMU's `VM` interface implementation (`machine.go`) had quite large functions. Pulls out some code that could be moved to its own function for easier readability.
```release-note
None
```
> Reduce qemu machine function sizes

- docs/tutorials/socket_activation.md
```release-note
The echo server example in socket_activation.md has been rewritten to use quadlet instead of `podman generate systemd`
```
I used the term _container unit files_.  I don't know if there is a standard nomenclature for naming such files.
> [CI:DOCS] migrate socket_activation.md to quadlet

- cmd/podman/kube/play.go
- docs/source/markdown/podman-logs.1.md.in
- docs/source/markdown/podman-machine-os-apply.1.md
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-remote.1.md
- docs/source/markdown/podman-system-connection-add.1.md
- docs/source/markdown/podman-system-connection.1.md
- docs/source/markdown/podman-systemd.unit.5.md
- docs/source/markdown/podman.1.md
- docs/tutorials/qemu-remote-tutorial.md
- libpod/container_api.go
- libpod/container_exec.go
- libpod/container_log.go
- libpod/define/containerstate.go
- libpod/events/config.go
- libpod/events/journal_linux.go
- libpod/healthcheck.go
- libpod/networking_common.go
- libpod/networking_unsupported.go
- libpod/runtime_ctr.go
- pkg/domain/infra/tunnel/helpers.go
> Fix language, typos and markdown layout

- cmd/podman/images/sign.go
- docs/source/markdown/options/cert-dir.md
- docs/source/markdown/podman-auto-update.1.md.in
- docs/source/markdown/podman-container-restore.1.md
- docs/source/markdown/podman-container-runlabel.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-logout.1.md.in
- docs/source/markdown/podman-machine-init.1.md.in
- docs/source/markdown/podman-machine-os-apply.1.md
- docs/source/markdown/podman-pod-top.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-top.1.md.in
- docs/source/markdown/podman.1.md
- docs/tutorials/podman_tutorial.md
- docs/tutorials/rootless_tutorial.md
To make the language more efficient, only use the word "please" in these situations:
* reader is asked to do something inconvenient 
* reader is asked for permission
* reader is asked for forgiveness
If you think this modification is a good idea, I could put some more work into this PR and find some more edits to make.
References:
https://developers.google.com/style/word-list#letter-p
https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/p/please
```release-note
None
```
> Remove unnecessary use of the word "please"

- go.mod
- go.sum
- pkg/specgenutil/specgen.go
- pkg/specgenutil/volumes.go
- test/system/060-mount.bats
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/pkg/ssh/utils.go
- vendor/github.com/onsi/gomega/CHANGELOG.md
- vendor/github.com/onsi/gomega/gomega_dsl.go
- vendor/modules.txt
```release-note
--mounts can now be specified in containers.conf
```
> Add support for mounts listed in containers.conf 

- pkg/machine/qemu/machine.go
Lock the machine when stopping, removing or changing its attributes to make sure write accesses are serialized which should prevent a number of issues and inconsistencies reported.
```release-note
None
```
@ashley-cui @benoitf @rhatdan @n1hility PTAL
All QEMU commands with write access are now serialized.
> machine: QEMU: lock VM on stop/rm/set

- cmd/quadlet/main.go
- libpod/container_top_linux.go
- pkg/specgenutil/volumes.go
- test/system/252-quadlet.bats
> Codespell fixups

- docs/source/markdown/podman-stats.1.md.in
Fixes: https://github.com/containers/podman/issues/15146
```release-note
None
```
> [CI:DOCS] Improve the description of fields in podman-stats man page

- pkg/machine/applehv/machine.go
The functions for AppleHV's VM interface implementation (machine.go) had quite large functions. Pulls out some code that could be moved to its own function for easier readability.
```release-note
None
```
> Breakup applehv machine funcs

- pkg/specgenutil/specgen.go
- test/system/160-volumes.bats
Fixed: https://github.com/containers/podman/issues/19432
```release-note
None
```
> Set default userns from containers.conf file

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/log/context.go
- vendor/github.com/containers/common/libimage/manifest_list.go
- vendor/github.com/containers/common/libimage/manifests/manifests.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_local.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/multiple.go
- vendor/github.com/containers/image/v5/docker/policyconfiguration/naming.go
- vendor/github.com/containers/image/v5/internal/set/set.go
- vendor/github.com/containers/image/v5/transports/alltransports/alltransports.go
- vendor/github.com/vbatts/tar-split/archive/tar/reader.go
- vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go
- vendor/github.com/vbatts/tar-split/tar/storage/packer.go
- vendor/modules.txt
bump github.com/containers/common -> v0.55.1-0.20230801150045-44bfd82e3ed2 
bump github.com/containers/image/v5 -> v5.26.1-0.20230726142307-8c387a14f4ac
```release-note
vendor: bump `c/image` -> `8c387a14f4ac` and `c/common` -> `44bfd82e3ed2`
```
> vendor: bump `c/image` -> `8c387a14f4ac` and `c/common` -> `44bfd82e3ed2`

- cmd/podman/secrets/rm.go
- docs/source/markdown/podman-secret-rm.1.md
- pkg/domain/entities/secrets.go
- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/tunnel/secrets.go
- test/e2e/secret_test.go
Refers #18591
```release-note
Add support for `--ignore` with `secret rm`
```
> secret: add support for `--ignore` with rm

- pkg/machine/qemu/machine.go
After a failed start, we can run into (somehow inconsistent) states where the machine won't start because a previous QEMU process is still running and the PID file is being used.  Stop didn't resolve the issue as this state wasn't detected.
Allow to recover from this state by a) detecting it during start and error out with a more helpful message than the error QEMU would otherwise spit out, and b) by enabling stop to kill the dangling QEMU process - even after a failed stop.
With the changes, a recovery may look as follows:
```
_  podman git:(main) _ ./bin/darwin/podman machine start
Starting machine "podman-machine-default"
Error: cannot start VM "podman-machine-default": another instance of "/opt/homebrew/bin/qemu-system-aarch64" is already running with process ID 970: please stop and …
```
> machine: QEMU: recover from failed start

- docs/source/markdown/options/mount.md
- test/system/060-mount.bats
> Fix up man page and add test on globs

- test/system/252-quadlet.bats
Some people might expect this to work:
systemctl --wait start foo
journalctl -u foo  ---> displays output from foo
Well, it does not. Not reliably, anyway:
https://github.com/systemd/systemd/issues/28650
Shrug, okay, deal with it: write value of %T to a tmpfile
instead of relying on journal. I tested with TMPDIR=<many values>
on an SELinux system and, by golly, it works fine.
```release-note
None
```
> CI: sys: quadlet %T test: do not rely on journal

- RELEASE_NOTES.md
- RELEASE_PROCESS.md
To reflect 4.5.1 and 4.6.0 releases
```release-note
None
```
> [CI:DOCS] Update Release Notes

- docs/source/markdown/podman-machine-list.1.md.in
Fixes: https://github.com/containers/podman/issues/19462
```release-note
None
```
> [CI:DOCS] man: remove duplicate entry `.LastUp`

- cmd/podman/containers/cp.go
Fixes: #19496
```release-note
podman cp via STDIN will delete the temporary files
```
> remove temporary files when copy

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] Quadlet - provide more information about network files

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
Closes #18899
```release-note
kube: adds support for `DaemonSet`
```
> kube: add DaemonSet support

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_darwin.go
- vendor/github.com/containers/common/pkg/config/config_freebsd.go
- vendor/github.com/containers/common/pkg/config/config_linux.go
- vendor/github.com/containers/common/pkg/config/config_windows.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
```release-note
Bump github.containers/common to v0.55.3.
```
> [4.6] vendor c/common v0.55.3

- RELEASE_NOTES.md
- go.mod
- go.sum
- vendor/github.com/containers/buildah/.packit.yaml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/modules.txt
- version/rawversion/version.go
Vendor Buildah 1.31.2, release notes, version bump
```release-note
None
```
> Bump to v4.6.1

- RELEASE_NOTES.md
- RELEASE_PROCESS.md
> [CI:DOCS] Update Release Notes and Release Process

- test/system/035-logs.bats
...add a 'sleep 1' in hopes of clearing the flake.
```release-note
None
```
> New partial-line test is flaking

- .packit.yaml
> [CI:BUILD] [v4.6.1-rhel backport] Cherry pick 19543 to v4.6.1 rhel

- pkg/machine/e2e/config_rm_test.go
- pkg/machine/e2e/rm_test.go
> Update machine rm tests

- pkg/machine/e2e/start_test.go
> Update machine start tests

- libpod/networking_freebsd.go
This sums the metric values from all interfaces similar to the Linux version.
```release-note
None
```
> libpod: sum per-interface network stats for FreeBSD

- RELEASE_NOTES.md
- version/rawversion/version.go
Bump to v4.6.2, plus release notes. 
```release-note
None
```
> [v4.6] Bump to v4.6.2

- .github/workflows/check_cirrus_cron.yml
- .github/workflows/discussion_lock.yml
- .github/workflows/rerun_cirrus_cron.yml
Don't need this email as we have podman-monitor email listed wherever relevant.
```release-note
None
```
@cevich PTAL
> remove rh.container.bot@gmail.com

- docs/source/markdown/podman-machine-os-apply.1.md
> fix: default typo

- pkg/machine/e2e/basic_test.go
Added a test that checks that gvproxy properly starts and stops when running podman machine, and that containers properly forward ports to the host when running podman using machine.
```release-note
None
```
> Add port forwarding and gvproxy machine test

- docs/source/markdown/podman-kube-play.1.md.in
To avoid the error:
`Error: unable to read YAML as Kube Pod: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field Container.spec.containers.command of type string`
Also makes it easier to understand as you only need the image parameter.
```release-note
None
```
> [CI:DOCS] Update podman-kube-play.1.md.in

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] podman-systemd.unit: fix equivalents

- test/e2e/commit_test.go
Clean command-line replace, but required adding "-q" (quiet)
to all commit commands. Except one, on which I added tests
for the expected progress messages.
```release-note
None
```
> e2e: commit_test: use ExitCleanly()

- cmd/podman/kube/play.go
- docs/kubernetes_support.md
- docs/source/markdown/podman-kube-generate.1.md
- docs/source/markdown/podman-kube-play.1.md.in
- libpod/define/container.go
- libpod/kube.go
- pkg/domain/infra/abi/generate.go
- pkg/k8s.io/api/core/v1/types.go
- test/e2e/generate_kube_test.go
- test/minikube/001-kube.bats
Complements https://github.com/containers/podman/pull/19371
```release-note
Add support to generate k8s DaemonSet kind with podman kube generate.
```
> kube: add DaemonSet support for generate

- go.mod
- go.sum
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- vendor/github.com/containers/common/libimage/filter/filter.go
- vendor/github.com/containers/common/libimage/search.go
- vendor/github.com/containers/common/pkg/cgroups/cgroups.go
- vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go
- vendor/github.com/containers/common/pkg/cgroups/memory_linux.go
- vendor/github.com/containers/common/pkg/cgroups/utils.go
- vendor/modules.txt
Includes the fixes for the search filter changes.
```release-note
None
```
> bump c/common to latest main

- RELEASE_PROCESS.md
- docs/source/Reference.rst
Also update the RELEASE_PROCESS doc so maybe it will not be forgotten next time.
```release-note
None
```
> [CI:DOCS] update API docs version list

- test/e2e/create_test.go
Several manual fixes for tests that broke:
1. (the usual case): add "-q" to podman-create or -pull; or
2. Revert back to Expect(Exit(0)), and add stderr checks for
progress messages
```release-note
None
```
> e2e: create_test: use ExitCleanly()

- docs/source/markdown/options/volume.md
> [CI:DOCS] Fix some spelling and formatting  in volume options

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/Makefile
- vendor/github.com/containers/buildah/buildah.go
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/internal/tmpdir/tmpdir.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/modules.txt
As the title says.  This is in preparation for
Podman v4.7.0
```release-note
None
```
> Bump to Buildah v1.32.0

- contrib/cirrus/lib.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
Every few months we get a new CI failure that requires
scanning through logs that give no indication of what
is happening or where. Tracking down the error can
cost many hours.
Solution: pepper setup & runner scripts with showrun(), which
echoes the command _and_ displays the source filename + lineno.
```release-note
None
```
> CI: trace setup and runner scripts

- RELEASE_NOTES.md
> [CI:DOCS] bump release notes on main with the latest release

- RELEASE_NOTES.md
- version/rawversion/version.go
```release-note
None
```
Let's get https://github.com/containers/podman/pull/19993 merged first.
> New pre-release: v4.7.0-rc1

- docs/source/markdown/podman-ps.1.md
- pkg/domain/filters/containers.go
- pkg/domain/filters/pods.go
- test/apiv2/20-containers.at
- test/apiv2/python/rest_api/test_v2_0_0_container.py
No
```release-note
Add label! filter to containers and pods filters
```
> Add label! filter to container filters

- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-tag.1.md
> [CI:DOCS] Improve podman-{tag,build} man pages

- test/e2e/network_create_test.go
- test/e2e/network_test.go
...on network*_test.go
```release-note
None
```
> more ExitCleanly()

- test/system/252-quadlet.bats
Move all variable definitions to the top of the function Remove unneeded prints
No
```release-note
None
```
> Quadlet Image test - rearrange test function

- go.mod
- go.sum
- test/system/012-manifest.bats
- vendor/github.com/containers/common/libimage/layer_tree.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
```release-note
None
```
Test for: https://github.com/containers/common/pull/1651
> test: rmi should work with images w/o layers

- .cirrus.yml
- .github/workflows/fcos-podman-next-build-prepush-test.yml
- .github/workflows/fcos-podman-next-build.yml
- .packit.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
Followup on #19477
```release-note
None
```
> [CI:BUILD] followup PR for fcos with podman-next

- pkg/machine/e2e/README.md
- pkg/machine/e2e/config_unix_test.go
- pkg/machine/e2e/config_windows_test.go
- pkg/machine/e2e/machine_test.go
this pr allows us to run the machine e2e tests with the wsl provider.
```release-note
None
```
> Enable machine e2e tests for WSL

- test/e2e/play_kube_test.go
A whopper. Please review individual commits, with primary focus on the third.
```release-note
None
```
> e2e: ExitCleanly(): play_kube_test.go

- test/e2e/run_test.go
the test works only when the user owns the outer mount namespace, which is likely not the case when running in rootless mode.
Closes: https://github.com/containers/podman/issues/20076
```release-note
None
```
> test: fix rootless propagation test

- version/rawversion/version.go
```release-note
None
```
@ashley-cui @mheon @containers/podman-maintainers PTAL
> Bump version on main

- cmd/podman/farm/update.go
- test/e2e/farm_test.go
Fix farm update to verify a connection exists before removing or adding it.
Also verify that the farm we want to update exists.
Fixes https://github.com/containers/podman/issues/20080
```release-note
Fix farm update to verify farm and connection existence before updating.
```
> Fix farm update to check for connections

- pkg/machine/e2e/ssh_test.go
a couple of small corrections for the ssh tests on WSL.  we need to check for a different os type and windows emits a warning in stderr.
```release-note
None
```
> wsl: machine tests for ssh

- pkg/machine/e2e/inspect_test.go
small corrections for wsl between sockets and pipe
```release-note
None
```
> wsl: machine tests for inspect

- pkg/machine/e2e/stop_test.go
- pkg/machine/wsl/machine.go
allow the machine stop test to pass.
```release-note
None
```
> pkg/machine/e2e: wsl stop

- test/e2e/common_test.go
- test/e2e/run_networking_test.go
- test/e2e/run_test.go
- test/e2e/runlabel_test.go
Continuing progress on RUN-1907
The second commit is the important one to review.
```release-note
None
```
> e2e: ExitCleanly(): a few more

- RELEASE_NOTES.md
- version/rawversion/version.go
> New release: v4.7.0

- cmd/podman/farm/update.go
closes #20079
```release-note
None
```
> [CI:DOCS] Fix podman farm update --help examples

- docs/source/markdown/podman-load.1.md
Update podman load doc to mention support for loading in compressed files. Add an example command as well.
Fixes https://github.com/containers/podman/issues/19989
```release-note
Update podman load man page with compression support
```
> [CI:DOCS] Update podman load doc

- docs/source/markdown/podmansh.1.md
> [skip-ci] Improve podmansh(1)

- docs/source/Reference.rst
> [CI:DOCS] update swagger version on docs.podman.io

- RELEASE_NOTES.md
- version/rawversion/version.go
> New release: v4.7.1

- RELEASE_PROCESS.md
> [CI:DOCS] Add updating version on podman.io to release process

- pkg/api/handlers/libpod/containers_create.go
remove what seems to be a debugging artifact.
```release-note
None
```
> api: drop debug statement

- libpod/events/journal_linux.go
- test/system/220-healthcheck.bats
This fixes a regression caused by commit 7e6e267329, unfortunately this was not caught during review as for some reason this works fine rootless and only fails as root.
Because we set the systemd log level to notice in order to hide the unit started/stopped messages to prevent spamming the journal the issue is that this now also causes systemd to ignore the events we write to journald as we also send them as info level.
To fix this we simply send health_status events now on notice level. I decided against sending all events on notice as I think info is fine for them. Whenever the notice level is right is of course debatable but given it may contain the unhealthy message I think having this a notice should be ok.
The main reason this made it through testing is because we do not rely on the …
> healthcheck: make sure to always show health_status events

- libpod/container_top_linux.go
- pkg/api/handlers/compat/containers_top.go
- pkg/api/server/register_containers.go
- pkg/bindings/containers/containers.go
- test/e2e/top_test.go
- test/system/085-top.bats
Fixes: https://github.com/containers/podman/issues/19176
```release-note
Corrected parsing of top ps options on podman-remote.
```
> Fix output of podman --remote top

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/downforce.kube
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
Allow users to set --force for Stop command
Add doc and tests
Yes
```release-note
Quadlet - add support for setting --force for Stop command
```
> Quadlet - add support for KubeDownForce

- .golangci.yml
- Makefile
- cmd/podman/containers/stats.go
- libpod/container_internal_common.go
- libpod/container_log.go
- libpod/events.go
- libpod/lock/file/file_lock_test.go
- libpod/oci_conmon_common.go
- libpod/oci_conmon_exec_common.go
- libpod/util.go
- pkg/criu/criu_linux.go
- pkg/domain/infra/abi/pods_stats.go
- pkg/k8s.io/apimachinery/pkg/api/resource/suffix.go
- pkg/machine/e2e/config_test.go
- pkg/rootless/rootless_linux.go
- pkg/specgen/generate/kube/kube.go
- pkg/systemd/activation_test.go
- pkg/systemd/generate/containers.go
- pkg/systemd/generate/pods.go
- pkg/timetype/timestamp_test.go
- pkg/util/utils_supported.go
- test/e2e/common_test.go
- test/e2e/create_test.go
- test/e2e/events_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_create_test.go
- test/e2e/run_networking_test.go
- test/e2e/run_userns_test.go
- test/e2e/search_test.go
see commits for new linter fixes
```release-note
None
```
> Update dependency golangci/golangci-lint to v1.55.0

- pkg/machine/machine_common.go
No. This is a fix to the formatting of a log statement.
Here is a screenshot of the error:
***
```release-note
Fix logging statement
```
> Fix logging typo

- test/e2e/common_test.go
Because all registries flake.
```release-note
None
```
> ginkgo setup: retry cache pulls

- pkg/machine/applehv/machine.go
In the unusual case where the `runtimeDir` is not already created, we should do so on `machine init`.
When starting gvproxy from podman, we now ensure it is running (for applehv) but waiting for the unixgram socket to appear in the filesystem before moving on.
```release-note
None
```
> Small fixes for wacko CI environments

- docs/source/markdown/options/systemd.md
Closes: https://github.com/containers/podman/issues/20521
[CI:DOCS]
```release-note
None
```
> docs: clarify systemd cgroup mount

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v4.7.2

- cmd/podman/compose.go
> compose: fix compose provider debug message

- cmd/podman/machine/init.go
- pkg/machine/e2e/init_test.go
we should exit early if a system connection name exists with the name of the proposed podman machine (i.e. podman-machine-default).
```release-note
None
```
> check system connections before machine init

- pkg/machine/machine_common.go
this fixes #20579 
```release-note
fixed a helper message to display the right command to execute
```
> adjust string to use default machine name instead of helper path in helper message

- docs/source/markdown/podman-kube-apply.1.md
> [CI:DOCS] Try to fix the broken formatting of man podman‐kube‐apply(1).

- docs/source/markdown/podman-kube-generate.1.md
> [CI:DOCS] Fix man page display of podman-kube-generate

- contrib/cirrus/prebuild.sh
- libpod/events/journal_linux.go
- pkg/domain/infra/abi/farm.go
- test/system/500-networking.bats
- test/system/700-play.bats
- test/system/800-config.bats
> Run codespell on podman

- cmd/podman/common/create_test.go
- cmd/podman/containers/restore.go
- cmd/podman/containers/stats.go
- libpod/container_inspect.go
- pkg/api/handlers/compat/containers.go
- pkg/bindings/test/images_test.go
- pkg/bindings/test/pods_test.go
- pkg/domain/infra/abi/farm.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/abi/parse/parse.go
- pkg/k8s.io/apimachinery/pkg/api/resource/amount.go
- pkg/k8s.io/apimachinery/pkg/api/resource/math.go
- pkg/k8s.io/apimachinery/pkg/api/resource/quantity.go
- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/e2e/stop_test.go
- pkg/machine/fcos.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/containers_conf_test.go
- test/e2e/healthcheck_run_test.go
- test/e2e/play_build_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_infra_container_test.go
- test/e2e/run_device_test.go
- test/e2e/run_passwd_test.go
- test/e2e/run_test.go
- test/e2e/toolbox_test.go
A bunch of cleanups as suggested by linters/etc in JetBrains IDE.
```release-note
None
```
> Automatic code cleanups - JetBrains

- docs/source/markdown/options/userns.container.md
> [CI:DOCS] Document --userns=auto behaviour for rootless users

- go.mod
- go.sum
- pkg/rootless/rootless_linux.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/close_handle.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/console_size.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/process_modify_request.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/schema2/process_status.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
- vendor/github.com/Microsoft/hcsshim/internal/log/format.go
- vendor/github.com/Microsoft/hcsshim/internal/log/hook.go
- vendor/github.com/Microsoft/hcsshim/internal/log/nopformatter.go
- vendor/github.com/Microsoft/hcsshim/internal/protocol/guestrequest/types.go
- vendor/github.com/Microsoft/hcsshim/internal/wclayer/layerutils.go
- vendor/github.com/Microsoft/hcsshim/layer.go
- vendor/github.com/containers/storage/pkg/unshare/unshare_darwin.go
- vendor/github.com/containers/storage/pkg/unshare/unshare_linux.go
- vendor/github.com/containers/storage/pkg/unshare/unshare_unsupported.go
- vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
- vendor/modules.txt
[NO NEW TESTS NEEDED] no new functionalities are added.
```release-note
None
```
> rootless: use functionalities from c/storage

- pkg/bindings/test/images_test.go
- test/e2e/search_test.go
Someone please revert this once quay search is fixed.
```release-note
None
```
> (Temporary) Emergency CI fix: quay search is broken

- pkg/machine/qemu/config.go
Some comments from https://github.com/containers/podman/pull/20540
```release-note
None
```
> qemu,parseUSB: minor refactor

- pkg/machine/applehv/machine.go
> Avoid empty SSH keys on applehv

- docs/source/index.rst
```release-note
Add link to podman-py docs
```
> [CI:DOCS] Add link to podman py docs

- go.mod
- go.sum
- vendor/github.com/containers/libhvee/pkg/hypervctl/diskdrive_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/error.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/ethernet_port_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/resources_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/scsi_controller.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/system_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/system_settings_builder.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vmm.go
- vendor/github.com/containers/libhvee/pkg/wmiext/array.go
- vendor/github.com/containers/libhvee/pkg/wmiext/enum.go
- vendor/github.com/containers/libhvee/pkg/wmiext/error.go
- vendor/github.com/containers/libhvee/pkg/wmiext/init.go
- vendor/github.com/containers/libhvee/pkg/wmiext/instance.go
- vendor/github.com/containers/libhvee/pkg/wmiext/service.go
- vendor/modules.txt
```release-note
Update to libhvee 0.5.0 for podman machine on Microsoft HyperV
```
> Update to libhvee 0.5.0

- docs/tutorials/rootless_tutorial.md
- We can assume that cgroups v2 and rootless overlayfs are the
default everywhere.
- Remove RHEL7-only instructions
- add clear '$' and '#' prompts to rootless and root commands
- other minor consistency cleanups
Ref: #20669
```release-note
Update rootless tutorial for relevance in a cgroups-v2 and overlayfs-default world
```
> [CI:DOCS] rootless_tutorial: modernize

- RELEASE_NOTES.md
- version/rawversion/version.go
Old release notes, new release notes, plus the version bump. 
```release-note
None
```
> [v4.8] Bump to 4.8.0-rc1

- libpod/storage.go
Fixes #20411. See individual commits for details.
```release-note
None
```
> Clean up storageService.CreateContainerStorage

- RELEASE_NOTES.md
- test/apiv2/01-basic.at
- version/rawversion/version.go
Dev version bump, plus updated release notes from 4.7
```release-note
None
```
> Bump main to 5.0.0-dev

- pkg/machine/applehv/machine.go
This is #20738 from @Luap99 but with a no new tests needed annotation
<MH: Added no new tests needed to pass CI>
```release-note
None
```
> machine applehv: create better error on start failure

- libpod/options.go
- libpod/runtime.go
- pkg/domain/infra/runtime_libpod.go
these functions are not used anymore in the codebase, so drop them.
[NO NEW TESTS NEEDED] no new functionalities are added
```release-note
None
```
> libpod: drop dead code

- RELEASE_NOTES.md
- version/rawversion/version.go
As title says. 
```release-note
None
```
> [v4.8] Bump to v4.8.0

- pkg/api/server/register_kube.go
The annotations parameter was not documented, add it.
Fixes #20784
```release-note
None
```
> [CI:DOCS] swagger: document play kube annotations param

- docs/source/locale/ja/LC_MESSAGES/markdown.po
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-volume-inspect.1.md
> [CI:DOCS] Fix markdown bugs

- pkg/specgen/generate/config_linux.go
- test/e2e/run_test.go
> Get masked paths and readonly masked patchs from containers/common @rhatdan

- pkg/machine/applehv/config.go
- pkg/machine/hyperv/config.go
- pkg/machine/wsl/config.go
> machine: usb: Fix 'passtrough' typo

- test/system/075-exec.bats
- test/utils/matchers.go
Images are from https://github.com/containers/automation_images/pull/316
```release-note
None
```
> CI: unskip tests on new VMs

- cmd/podman/kube/play.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- test/system/700-play.bats
Create a buildah SystemContext from the existing cli arguments
Pass the SystemContext to the build
Add system test
No
```release-note
None
```
Resolves: #20890
> Kube Play - pass arguments to build

- Makefile
- go.mod
- pkg/trust/trust.go
- test/tools/go.mod
> Move golang requirement from 1.18 to 1.20

- Makefile
> Makefile - make sure gitvalidation is installed before calling it

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/stoptimeout.container
- test/e2e/quadlet_test.go
Allow setting the timeout for stopping the container Add test
Update man
Yes
```release-note
Quadlet - add StopTimeout key for .container file
```
Resolves: #21134
> Quadlet - add StopTimeout key for .container file

- test/system/030-run.bats
Test coverage for https://issues.redhat.com/browse/RHEL-14469
```release-note
None
```
> test/system: add test for mounting issue in the init container

- pkg/machine/applehv/machine.go
- pkg/machine/hyperv/machine.go
- pkg/machine/ignition/ready.go
- pkg/machine/qemu/machine.go
consolidated ignition ready unit file content into one function.
```release-note
None
```
> consolidate ignition ready socket unit

- libpod/runtime_ctr.go
Backported #20329 to v4.6.1-rhel per RH Jira RHEL-20910 and RHEL-20911.
```release-note
NONE
```
> Backport #20329 to v4.6.1-rhel

- pkg/machine/applehv/machine.go
Fixes a bug where a user would be unable to change a rootless machine to rootful.
Fixes: #21195
```release-note
Fixes a bug where a user would not be able to change their rootless machine to rootful using `podman machine set --rootful`
```
> Fix `podman machine set --rootful` for applehv

- pkg/machine/ignition/ignition.go
There are no security concerns here; this is a convenience for people debugging things.  Some podman-machine developers were manually setting a password over SSH for example, but this is just better than that.
(Also marking no release note as we don't expose a console by default, only when launched with --debug right now)
```release-note
None
```
> machine: Enable console autologin by default

- .cirrus.yml
- .readthedocs.yaml
- Makefile
> [CI:DOCS] Enable readthedocs build on v4.3

- README.md
> [CI:DOCS]Remove final references to varlink

- version/rawversion/version.go
Bump to v4.9.0 and then v4.9.1-dev
```release-note
None
```
> Bump to v4.9.0

- docs/source/markdown/podman-farm-create.1.md
- docs/source/markdown/podman-farm.1.md
Add some updates and clarification to the
farm docs.
```release-note
None
```
> [CI:DOCS] Update farm docs

- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-load.1.md
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-wait.1.md.in
Followup to #21285. I hope this is easier to review
than a re-push of that one.
```release-note
ongoing man page cleanup, maybe worth a broad release note but certainly not for just this PR
```
> [CI:DOCS] minor man page cleanup

- docs/source/markdown/podman-manifest-rm.1.md
- docs/source/markdown/podman-secret-ls.1.md.in
> [CI:DOCS] fix documentation formatting issues

- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/abi/secrets_test.go
- pkg/domain/utils/scp_test.go
- pkg/env/env_test.go
extract some duplicate codes and add unit test for utils, happy to contribute!
```release-note
None
```
> chore: extract duplicate codes

- pkg/domain/infra/abi/system.go
cherry-pick of https://github.com/containers/podman/pull/21017
> [v4.9] abi: drop check for IsRootless()

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
- test/e2e/run_networking_test.go
From https://github.com/containers/automation_images/pull/324
```release-note
None
```
> Test new CI VMs

- .cirrus.yml
- RELEASE_NOTES.md
- version/rawversion/version.go
As title says. 
```release-note
None
```
> Bump to v4.9.2

- pkg/machine/applehv/machine.go
- pkg/machine/applehv/stubber.go
- pkg/machine/compression/copy.go
- pkg/machine/compression/copy_test.go
- pkg/machine/compression/decompress.go
> AppleHV - make gz ops sparse

- .cirrus.yml
- vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
- vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
> [v4.0-rhel] Manually update runc vendor to address CVE-2024-21626

- .cirrus.yml
- contrib/cirrus/cirrus_yaml_test.py
> [machine-dev-5] Success depends on PM mac

- docs/source/markdown/options/userns.pod.md
> [CI:DOCS] hierarchical issues with userns parameters

- docs/source/markdown/options/userns.pod.md
> [CI:DOCS] fix userns.pod.md mapping table

- test/system/500-networking.bats
For some reason this starting to flake f38. I don't think the issue in podman rather the test start nc -l in the background so it may not yet have bound the port in the container when we try to connect. To fix this simply add some retry logic to nc.
While at it also add pasta to this test and make it use defer-assertion-failures to run all loop iterations before reporting the errors.
Fixes #21561 (hopefully)
```release-note
None
```
> fix "podman run port forward range" flake

- pkg/machine/config.go
- pkg/machine/fcos.go
This PR is only a few cleanup items where code is no longer used.  More to come I'm sure
```release-note
None
```
> Minor cleanup from podman 4

- .packit.yaml
v4.9 only for Fedora 38 and 39. Fedora rawhide and 40 will move to v5.
```release-note
None
```
Don't need ci for this.
> [v4.9] [skip-ci] packit: update fedora downstream branches

- contrib/pkginstaller/Makefile
- contrib/pkginstaller/README.md
- contrib/pkginstaller/package.sh
- contrib/pkginstaller/scripts/postinstall
Do not build and install QEMU in the pkginstaller. Instead, build, sign, and install VFKit.
```release-note
None
```
> [CI:BUILD] Add VFKit into pkginstaller, remove QEMU

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v4.9.3

- README.md
Our roadmap was completely outdated, revamp it to things we have not already done. Same for the Podman Desktop section - it's not a brand-new, unproven solution anymore.
```release-note
NONE
```
> [CI:DOCS] Readme update

- RELEASE_PROCESS.md
Test PR to see if tide merges regardless of "Total Success" passing status.
```release-note
None
```
> Test PR, add a inconsequential period to docs

- pkg/machine/qemu/stubber.go
Right now the code used the same socket for gvproxy and the qemu qmp socket, this was racy and no correct as the later overwrote the former. The correct thing is to use to separate socket paths, just use the GVProxySocket() helper like applehv does.
```release-note
None
```
> machine/qemu: use extra gvproxy socket

- pkg/machine/applehv/stubber.go
- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/init_windows_test.go
- pkg/machine/hyperv/stubber.go
- pkg/machine/qemu/stubber.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/config.go
- pkg/machine/wsl/stubber.go
- Corrects VM name conflict check with WSL
- Changes GetHyperVisorVMs to Exists to better abstract desired contract
```release-note
none
```
> Fixes VM name conflict checking with WSL

- docs/source/markdown/podman-info.1.md
> [CI:DOCS] Fix up example description of podman-info.1.md

- docs/source/markdown/podman-exec.1.md.in
> [CI:DOCS] Fix up example description of podman-exec.1.md.in

- docs/source/markdown/podman-start.1.md.in
> [CI:DOCS]  Fix up example description of podman-start.1.md.in

- docs/source/markdown/podman-pause.1.md.in
- docs/source/markdown/podman-unpause.1.md.in
> [CI:DOCS] Fix up example description of podman-pause.1.md.in

- docs/source/markdown/podman-image-diff.1.md
- docs/source/markdown/podman-image-exists.1.md
- docs/source/markdown/podman-image-inspect.1.md
- docs/source/markdown/podman-image-mount.1.md
- docs/source/markdown/podman-image-prune.1.md
- docs/source/markdown/podman-image-scp.1.md
- docs/source/markdown/podman-image-tree.1.md
- docs/source/markdown/podman-image-trust.1.md.in
- docs/source/markdown/podman-image-unmount.1.md
> [CI:DOCS] Fix up example description of podman-image commands

- docs/source/markdown/podman-rm.1.md.in
> [CI:DOCS] Fix up example description of podman-rm.1.md.in

- docs/source/markdown/podman-healthcheck-run.1.md
> [CI:DOCS] Fix up example description of podman-healthcheck-run.1.md

- docs/source/markdown/podman-farm-build.1.md.in
- docs/source/markdown/podman-farm-create.1.md
- docs/source/markdown/podman-farm-list.1.md
- docs/source/markdown/podman-farm-remove.1.md
- docs/source/markdown/podman-farm-update.1.md
> [CI:DOCS] Fix up example description of podman-farm commands

- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-logout.1.md.in
> [CI:DOCS] Fix up example description of podman-logout.1.md.in

- docs/source/markdown/podman-pod-exists.1.md
- docs/source/markdown/podman-pod-inspect.1.md.in
- docs/source/markdown/podman-pod-kill.1.md.in
- docs/source/markdown/podman-pod-logs.1.md.in
- docs/source/markdown/podman-pod-pause.1.md
- docs/source/markdown/podman-pod-restart.1.md
- docs/source/markdown/podman-pod-rm.1.md.in
- docs/source/markdown/podman-pod-start.1.md.in
- docs/source/markdown/podman-pod-stats.1.md.in
- docs/source/markdown/podman-pod-unpause.1.md
> [CI:DOCS] Fix up example description of podman-pod commands

- docs/source/markdown/podman-kill.1.md.in
> [CI:DOCS] Fix up example description of podman-kill.1.md.in

- docs/source/markdown/podman-export.1.md
- docs/source/markdown/podman-import.1.md
> [CI:DOCS] Fix up example description of podman-export/export commands

- docs/source/markdown/podman-cp.1.md
> [CI:DOCS] Fix up example description of podman-cp.1.md

- pkg/machine/e2e/config_reset_test.go
- pkg/machine/wsl/fedora.go
- test/system/500-networking.bats
> Codespell code

- docs/source/markdown/podman-diff.1.md.in
> [CI:DOCS] Fix up example description of podman-diff.1.md.in

- docs/source/markdown/podman-events.1.md
> [CI:DOCS] Fix up example description of podman-events.1.md

- docs/source/markdown/podman-create.1.md.in
> [CI:DOCS] Fix up example description of podman-create.1.md.in

- docs/source/markdown/podman-build.1.md.in
> [CI:DOCS] Fix up example description of podman-build.1.md.in

- docs/source/markdown/podman-commit.1.md
> [CI:DOCS] Fix up example description of podman-commit.1.md

- docs/source/markdown/podman-container-clone.1.md.in
- docs/source/markdown/podman-container-prune.1.md
> [CI:DOCS] Fix up example description of podman-container commands

- docs/source/markdown/podman-history.1.md
> [CI:DOCS] Fix up example description of podman-history.1.md

- docs/source/markdown/podman-port.1.md.in
> [CI:DOCS] Fix up example description of podman-port.1.md.in

- docs/source/markdown/podman-stats.1.md.in
> [CI:DOCS] Fix up example description of podman-stats.1.md.in

- docs/source/markdown/podman-push.1.md.in
> [CI:DOCS] Fix up example description of podman-push.1.md.in

- docs/source/markdown/podman-images.1.md.in
> [CI:DOCS] Fix up example description of podman-images.1.md.in

- docs/source/markdown/podman-inspect.1.md.in
> [CI:DOCS] Fix up example description of podman-inspect.1.md.in

- docs/source/markdown/podman-system-connection-add.1.md
- docs/source/markdown/podman-system-connection-default.1.md
- docs/source/markdown/podman-system-connection-list.1.md
- docs/source/markdown/podman-system-connection-remove.1.md
- docs/source/markdown/podman-system-connection-rename.1.md
- docs/source/markdown/podman-system-connection.1.md
- docs/source/markdown/podman-system-df.1.md
> [CI:DOCS] Fix up example description of podman-system commands

- test/system/255-auto-update.bats
- use PODMAN_TMPDIR, not BATS_TMPDIR, for temp file
- in teardown, do not assume that SNAME_FILE will exist
(test could fail before that file gets created)
- remove "?" ("ignore exit status") from rmi & prune.
Probably holdovers from the days before -f. If
these commands fail even with -f, we need to know.
/cc @lsm5, this addresses the zuul failure you reported
```release-note
None
```
> systests: auto-update: minor cleanup

- .cirrus.yml
Need pasta 02-20, gvisor 0.7.3
https://github.com/containers/automation_images/pull/329#issuecomment-1959742060
```release-note
None
```
> Bump VMs. New pasta, gvisor

- test/system/500-networking.bats
...commented out long long ago with a now-obsolete TODO
```release-note
None
```
> systests: enable ipv6 tests

- .cirrus.yml
- cmd/podman-mac-helper/install.go
- cmd/podman-mac-helper/main.go
- cmd/podman-mac-helper/uninstall.go
- pkg/machine/applehv/machine.go
- pkg/machine/applehv/stubber.go
- pkg/machine/applehv/vfkit.go
- pkg/machine/applehv/vfkit/config.go
[NO NEW TESTS NEEDED] Just fixing lint issues
```release-note
NONE
```
> Enable lint for Darwin and fix identified issues

- test/system/700-play.bats
I'm tired of this flake, it's hitting us ~once/day. Root cause
still unknown.
Workaround: add a READY file to the http server, and run 'curl'
until we get it. Tested in #17831 for the last two weeks, flake
has not been seen even once since then.
Closes: #21649
```release-note
None
```
> systests: kube play URL: workaround for ECONNREFUSED

- test/apiv2/20-containers.at
> [SKIP-ci] Run codespell on code

- .cirrus.yml
> [CI:BUILD] V4.9 rhel bsd backport

- docs/tutorials/podman-for-windows.md
```release-note
Changed typo in DOCS.
```
> [CI:DOCS] Update podman-for-windows.md

- cmd/podman/machine/set.go
- pkg/machine/applehv/stubber.go
- pkg/machine/define/setopts.go
- pkg/machine/e2e/init_test.go
- pkg/machine/hyperv/stubber.go
- pkg/machine/qemu/command/command.go
- pkg/machine/qemu/stubber.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/config.go
- pkg/machine/vmconfigs/machine.go
- pkg/machine/wsl/machine.go
To make it very clear in the code what unit the uint represents.
```release-note
None
```
> machine: make more use of strongunits

- go.mod
- go.sum
- vendor/modules.txt
> vendor libhvee-0.7.0

- cmd/podman/machine/init.go
- cmd/podman/machine/set.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/machine.go
see commits
```release-note
None
```
> more machine locking fixes

- cmd/podman/compose_machine.go
This can be enabled now.
```release-note
None
```
> podman compose: enable machine socket connection

- docs/tutorials/performance.md
This PR fixes a broken link that was added in 
* https://github.com/containers/podman/pull/21992
```release-note
None
```
> [CI:DOCS] performance: fix URL

- cmd/podman/machine/start.go
- pkg/machine/e2e/start_test.go
- pkg/machine/lock/lock.go
- pkg/machine/shim/host.go
- pkg/machine/wsl/config.go
see commits
```release-note
None
```
> podman machine start: make checkExclusiveActiveVM check race free 

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.0.0-RC7

- test/system/helpers.network.bash
In some environments, such as the one described in https://github.com/containers/podman/issues/20927, the default route is given as nexthop gateways. That is, it's a multipath routes with multiple gateways.
That means that pasta(1), after commit 6c7623d07bbd ("netlink: Add support to fetch default gateway from multipath routes"), can start and use a default gateway from that route.
Just like in pasta(1), in these tests, the default route indicates which upstream interface we should pick. If we ignore multipath routes, IPv6 addresses and gateway addresses themselves won't be available, so, while pasta is now able to configure the container, IPv6 tests will expect to find no address and no gateway, hence fail due to the mismatch.
Try to get gateway addresses from nexthop objects, in case …
> test/system: Add support for multipath routes in pasta networking tests

- pkg/api/handlers/compat/images_build.go
So if the remote ends discoonects then the scratch dir with context can be lefter around.
This moves the defered cleanup func to stop this happening.
None
```release-note
Make sure we always clean up the remote build context on error  
```
> Cleanup build scratch dir if remote end disconnects while passing the context

- RELEASE_NOTES.md
- version/rawversion/version.go
> v5.0.0 release

- .github/workflows/upload-win-installer.yml
> [CI:BUILD] Fix type-o

- Makefile
Add Loongarch support for libpod.
[no new tests needed]
> Add LoongArch support for libpod

- version/rawversion/version.go
v5.0 has been branched
```release-note
None
```
> bump main to 5.1.0-dev

- RELEASE_NOTES.md
- docs/source/markdown/podman-secret-ls.1.md.in
> chore: remove repetitive words

- OWNERS
> [CI:DOCS]Add Mario to reviewers list

- .github/workflows/upload-win-installer.yml
- contrib/win-installer/build.ps1
Force installed version of WiX toolset
```release-note
None
```
> [CI:DOCS] [v4.9] Fix windows installer action

- version/rawversion/version.go
This is only for the RHEL branch, where we need a 4.9.4 to fix a packaging issue.
```release-note
NONE
```
> Bump to v4.9.4-rhel

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.0.1

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] Add note about host networking to Kube PublishPort option

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] update Quadlet volume Options desc

- cmd/podman/containers/ps.go
- libpod/boltdb_state.go
- libpod/container_internal.go
- libpod/container_path_resolution.go
> [CI:DOCS] chore: fix function names in comment

- build_windows.md
- libpod/events.go
- libpod/events/events.go
- libpod/healthcheck.go
- libpod/options.go
- libpod/stats_freebsd.go
- libpod/stats_linux.go
- pkg/machine/update.go
No
```release-note
Fix some comments
```
> Fix some comments

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.0.2

- docs/source/markdown/podman-pull.1.md.in
> [CI:DOCS] format podman-pull example as code

- test/e2e/create_test.go
- test/e2e/generate_systemd_test.go
- test/e2e/kill_test.go
- test/e2e/pause_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_rm_test.go
- test/e2e/pod_start_test.go
- test/e2e/pod_stop_test.go
- test/e2e/restart_test.go
- test/e2e/rm_test.go
- test/e2e/run_test.go
- test/e2e/start_test.go
- test/e2e/stop_test.go
"tmpdir + string" does not do what you think it does.
```release-note
None
```
> e2e tests: stop littering

- .packit.yaml
- rpm/podman.spec
EL8 will go EOL soon and nothing on main will be shipped to el8.
```release-note
None
```
> [skip-ci] Packit/rpm: remove el8 jobs and spec conditionals

- Makefile
- go.mod
- go.sum
- test/buildah-bud/apply-podman-deltas
- test/buildah-bud/buildah-tests.diff
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/.packit.yaml
- vendor/modules.txt
Also bumps Go image version in makefile to unbreak vendor-in-container.
```release-note
NONE
```
> Bump buildah to fix CI

- test/e2e/run_test.go
> ExitWithError() -- run_test.go

- test/e2e/play_kube_test.go
This commit handles test/e2e/play_kube_test.go
```release-note
None
```
> ExitWithError() - play_kube_test.go

- .golangci.yml
```release-note
None
```
1. Replace the deadline parameter with the timeout parameter. see https://github.com/golangci/golangci-lint/pull/793
2. Remove useless parameters. https://golangci-lint.run/usage/linters/#errcheck & https://golangci-lint.run/usage/linters/#nolintlint
> update and remove parameter settings in `.golangci.yml`

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.0.3

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.1.0-RC1

- version/rawversion/version.go
v5.1 has been branched.
```release-note
None
```
> bump main to 5.2.0-dev

- libpod/oci_conmon_common.go
> fix: close resource file

- docs/tutorials/performance.md
* Document that pasta is now the default network driver
* Document command: `podman info -f '{{.Host.RootlessNetworkCmd}}'`
* Add note about missing network isolation
__Side note:__ 
I mentioned the command
```
$ podman info -f '{{.Host.RootlessNetworkCmd}}'
pasta
```
that will be released in Podman 5.1.0.
Fixes: https://github.com/containers/podman/issues/22748
```release-note
None
```
> [CI:DOCS] performance: update network docs

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/copier/copier.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/docker/types.go
- vendor/github.com/containers/buildah/image.go
- vendor/github.com/containers/buildah/imagebuildah/build.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/common/version/version.go
- vendor/github.com/fsouza/go-dockerclient/container.go
- vendor/github.com/openshift/imagebuilder/.travis.yml
- vendor/github.com/openshift/imagebuilder/dispatchers.go
- vendor/github.com/openshift/imagebuilder/imagebuilder.spec
- vendor/modules.txt
Bump Buildah to v1.36.0.  This is the final dance step before Podman v5.1
```release-note
None
```
> Bump Buildah to v1.36.0

- docs/source/Tutorials.rst
```release-note
None
```
Just a typo fix: command -> commands
> [CI:DOCS] fix typo in Tutorials.rst

- RELEASE_NOTES.md
- cmd/podman/main.go
- version/rawversion/version.go
> Bump to v5.1.0

- .packit.yaml
> [v4.9] [skip-ci] Packit: only keep relevant jobs

- .packit.yaml
On this branch, we only care about epel9 (rhel9) buildability.
```release-note
None
```
> [v4.9-rhel] [skip-ci] Packit: only keep essential jobs

- RELEASE_NOTES.md
- version/rawversion/version.go
Hopefully the last release from this branch, but we'll keep doing security updates until F39 is EOS.
```release-note
NONE
```
> Bump to v4.9.5

- RELEASE_NOTES.md
- libpod/container_internal.go
- libpod/healthcheck.go
- libpod/healthcheck_linux.go
- libpod/healthcheck_nosystemd_linux.go
- libpod/healthcheck_unsupported.go
- pkg/machine/apple/vfkit.go
- test/system/220-healthcheck.bats
- version/rawversion/version.go
> Bump to v5.1.1

- Makefile
- test/system/001-basic.bats
- test/system/030-run.bats
- test/system/040-ps.bats
- test/system/065-cp.bats
- test/system/070-build.bats
- test/system/252-quadlet.bats
- test/system/500-networking.bats
Like the others please see individual commits.
Part 2 https://github.com/containers/podman/pull/22826
Part 1 https://github.com/containers/podman/pull/22821
```release-note
None
```
> test/system: make some tests faster part 3

- test/e2e/build_test.go
- test/e2e/cleanup_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/diff_test.go
- test/e2e/exec_test.go
- test/e2e/exists_test.go
- test/e2e/generate_systemd_test.go
- test/e2e/images_test.go
- test/e2e/info_test.go
- test/e2e/init_test.go
Convert Exit(N) to ExitWithError(N, "expected error")
```release-note
None
```
> ExitWithError() - continued

- Makefile
- cmd/podman/containers/ps.go
- pkg/bindings/connection.go
- pkg/bindings/containers/containers.go
- pkg/bindings/images/images.go
- pkg/machine/config.go
Includes fixes for new lint warnings from unparam and usestdlibvars.
```release-note
None
```
> update golangci-lint to v1.59.1

- OWNERS
> [CI:DOCS] Add jnovy as reviewer and approver

- contrib/pkginstaller/Makefile
- contrib/pkginstaller/krunkit.entitlements
- contrib/pkginstaller/package.sh
Extend Makefile and package.sh to download, sign and bundle krunkit and its dependencies into the package.
```release-note
None
```
> macos-installer: bundle krunkit

- test/e2e/restart_test.go
- test/e2e/rm_test.go
- test/e2e/run_device_test.go
- test/e2e/run_env_test.go
- test/e2e/run_exit_test.go
- test/e2e/run_selinux_test.go
- test/e2e/run_userns_test.go
- test/e2e/run_volume_test.go
- test/e2e/run_working_dir_test.go
More Exit(x) -> ExitWithError(x, "expected message")
```release-note
None
```
> ExitWithError(): continued

- rpm/podman.spec
This subpackage will only fetch dependencies for podman-machine.
```release-note
None
```
> [skip-ci] RPM: create podman-machine subpackage

- test/e2e/run_entrypoint_test.go
- test/e2e/run_test.go
- test/e2e/secret_test.go
- test/e2e/stop_test.go
- test/e2e/system_dial_stdio_test.go
- test/e2e/top_test.go
- test/e2e/unshare_test.go
- test/e2e/wait_test.go
> ExitWithError() - more upgrades from Exit()

- .cirrus.yml
Likely a copy-paste error, it doesn't apply here.
```release-note
None
```
> [CI:DOCS] Minor: Remove unhelpful comment

- cmd/podman/system/events.go
The events code makes use of two channels, one for the events and one for the resulting error. Then in the main file we have a loop reading from both channels that should exit on first error it gets.
However in case the event channel is closed before the error channel cotains the error it could caused an early exit as it looked like all events were done. Commit c46884aa93 fixed that somewhat by checking for an error in the error channel before exiting. This however was still racy as it added a default case in the select which means the channel check is non blocking. Thus the error was not yet send into the channel.
To fix this we should make it a blocking read to wait for the error in the channel. Also the err != nil check can be removed as we either return err or nil anyway.
And as last …
> podman events: fix error race

- .cirrus.yml
- contrib/cirrus/CIModes.md
- contrib/cirrus/cirrus_yaml_test.py
When we check if source code was changed also include header files. There is only one header file currently but that can change and it may be possible that changes in this file can break things so make sure it is considered source code so that all tests are triggered.
```release-note
None
```
> cirrus: check for header files in source code check

- docs/source/markdown/podman-build.1.md.in
Fixes: #23039
```release-note
None
```
>  Improve container filenname ambiguity.

- test/system/505-networking-pasta.bats
When a system has one ipv4 and one ipv6 address hostname -I will show both causing a failure in the case where this is only one address. To fix this stop using hostname -I and use ip -4 to only list v4 addresses and the use jq to filter the output accordingly.
Fixes #23227
```release-note
None
```
> test/system: fix pasta host.containers.internal test

- go.mod
- go.sum
- vendor/github.com/containers/storage/.golangci.yml
- vendor/github.com/containers/storage/check.go
- vendor/github.com/containers/storage/drivers/aufs/aufs.go
- vendor/github.com/containers/storage/drivers/driver.go
- vendor/github.com/containers/storage/drivers/overlay/check.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- vendor/github.com/containers/storage/drivers/vfs/driver.go
- vendor/github.com/containers/storage/drivers/zfs/zfs.go
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/pkg/chrootarchive/archive_darwin.go
- vendor/github.com/containers/storage/pkg/chrootarchive/archive_unix.go
- vendor/github.com/containers/storage/pkg/chrootarchive/diff_unix.go
- vendor/github.com/containers/storage/pkg/chunked/cache_linux.go
- vendor/github.com/containers/storage/pkg/chunked/compressor/compressor.go
- vendor/github.com/containers/storage/pkg/chunked/filesystem_linux.go
- vendor/github.com/containers/storage/pkg/chunked/storage_linux.go
- vendor/github.com/containers/storage/pkg/idmap/idmapped_utils.go
- vendor/github.com/containers/storage/pkg/ioutils/fswriters.go
- vendor/github.com/containers/storage/pkg/lockfile/lockfile.go
- vendor/github.com/containers/storage/pkg/unshare/unshare_linux.go
- vendor/github.com/containers/storage/store.go
- vendor/github.com/containers/storage/types/options.go
- vendor/github.com/containers/storage/types/options_bsd.go
- vendor/github.com/containers/storage/types/options_darwin.go
- vendor/github.com/containers/storage/types/options_linux.go
- vendor/github.com/containers/storage/types/options_windows.go
- vendor/github.com/containers/storage/types/utils.go
- vendor/modules.txt
> vendor: bump c/storage

- cmd/podman/containers/run.go
- hack/xref-docker-options
No way to test this unless running on a nvidia platform.
```release-note
noop
```
> Remove references and checks for --gpus

- go.mod
- go.sum
- vendor/github.com/gorilla/schema/.editorconfig
- vendor/github.com/gorilla/schema/.gitignore
- vendor/github.com/gorilla/schema/LICENSE
- vendor/github.com/gorilla/schema/Makefile
- vendor/github.com/gorilla/schema/README.md
- vendor/github.com/gorilla/schema/cache.go
- vendor/github.com/gorilla/schema/converter.go
- vendor/github.com/gorilla/schema/decoder.go
- vendor/github.com/gorilla/schema/encoder.go
- vendor/modules.txt
Ref: [RHEL-45918](https://issues.redhat.com/browse/RHEL-45918)
```release-note
NONE
```
> [v4.4.1-rhel] Fix CVE-2024-37298

- go.mod
- go.sum
- vendor/github.com/gorilla/schema/.editorconfig
- vendor/github.com/gorilla/schema/.gitignore
- vendor/github.com/gorilla/schema/LICENSE
- vendor/github.com/gorilla/schema/Makefile
- vendor/github.com/gorilla/schema/README.md
- vendor/github.com/gorilla/schema/cache.go
- vendor/github.com/gorilla/schema/converter.go
- vendor/github.com/gorilla/schema/decoder.go
- vendor/github.com/gorilla/schema/encoder.go
- vendor/modules.txt
Addresses Ref: [OCPBUGS-36441](https://issues.redhat.com/browse/OCPBUGS-36441)
```release-note
NONE
```
> [v4.4.1-crio] Update gorilla/schema to v1.4.1 to fix CVE-2024-37298

- go.mod
- go.sum
- vendor/github.com/gorilla/schema/.editorconfig
- vendor/github.com/gorilla/schema/.gitignore
- vendor/github.com/gorilla/schema/LICENSE
- vendor/github.com/gorilla/schema/Makefile
- vendor/github.com/gorilla/schema/README.md
- vendor/github.com/gorilla/schema/cache.go
- vendor/github.com/gorilla/schema/converter.go
- vendor/github.com/gorilla/schema/decoder.go
- vendor/github.com/gorilla/schema/encoder.go
- vendor/modules.txt
Ref: [RHEL-45919](https://issues.redhat.com/browse/RHEL-45919)
```release-note
NONE
```
> [v4.2.0-rhel] Update gorilla/schema to v1.4.1 to fix CVE-2024-37298

- pkg/domain/infra/abi/containers.go
stats read from the cgroup, and in order to know the cgroup we check the pid for the cgroup. However there is a window where the pid exited and podman did not yet updated its internal state. In this case the code returns ErrCtrStopped so we should ignore this error as well.
Fixes #23334
```release-note
Fixed a race in podman stats that could cause it to exit with a "container is stopped" error when showing all containers.
```
> podman stats: fix race when ctr process exists

- libpod/sqlite_state.go
Some users want to experiment with different timeout values.
Fixes #23236
```release-note
None
```
> libpod: add hidden env to set sqlite timeout

- test/system/035-logs.bats
Continuing efforts on making system tests parallel-safe by
using unique names for containers and pods.
```release-note
None
```
> CI: system log test: use safe names

- pkg/api/handlers/compat/images_build.go
Users do not realize that the entire context directory is being copied into the podman machine when doing a podman --remote build.
Adding information about the context directory might help them understand this.
Improves: https://github.com/containers/podman/issues/23287
Not sure there is a good way to test this.
```release-note
None
```
> More information for podman --remote build and running out of space.

- test/system/700-play.bats
> CI: 700-play: fix a leaked non-safename

- test/system/065-cp.bats
Continuing efforts to make system tests parallel-safe
```release-note
None
```
> CI: cp tests: use safename

- libpod/pod_api.go
When using service containers and play kube we create a complicated set of dependencies.
First in a pod all conmon/container cgroups are part of one slice, that slice will be removed when the entire pod is stopped resulting in systemd killing all processes that were part in it.
Now the issue here is around the working of stopPodIfNeeded() and stopIfOnlyInfraRemains(), once a container is cleaned up it will check if the pod should be stopped depending on the pod ExitPolicy. If this is the case it wil stop all containers in that pod. However in our flaky test we calle podman pod kill which logically killed all containers already. Thus the logic now thinks on cleanup it must stop the pod and calls into pod.stopWithTimeout(). Then there we try to stop but because all containers are already …
> fix network cleanup flake in play kube

- pkg/api/server/register_images.go
Fix up a couple of versions in comments in the
pkg/api/server/register_images.go file.  Based on comments from #23440
```release-note
None
```
> Tweak versions in register_images.go

- contrib/cirrus/setup_environment.sh
- libpod/container_internal.go
- libpod/oci_conmon_common.go
- test/e2e/pod_create_test.go
- test/e2e/run_userns_test.go
- test/system/030-run.bats
Oops.
Fixes: #23383 
```release-note
None
```
> CI: enable root user namespaces

- test/system/700-play.bats
I broke the kube external storage test in the course of my
safename PR: _write_test_yaml() with no command generated
a pod that did not trigger the conditions required for
this test.
Solution: run a container (top). Add new checks to prevent
this gap from happening again.
```release-note
None
```
> CI: kube test: fix broken external-storage test

- version/rawversion/version.go
> Bump to v5.2.0

- contrib/cirrus/setup_environment.sh
- version/rawversion/version.go
We have v5.2 branch now.
```release-note
None
```
> Version: bump to v5.3.0-dev

- test/system/600-completion.bats
Ongoing efforts to make system tests parallel-safe
```release-note
None
```
> CI: completion system test: use safename

- test/system/060-mount.bats
Use safename for containers, volumes, images.
Build a temporary scratch image for podman image mount, so
we can safely mount/umount it (instead of $IMAGE) without
risk of other parallel tests umounting it.
Fixed some oopsies ("$vol1" is empty string, so, NOP test)
And... an experiment. I'm leaving in my 'ci:parallel' tags
and notes, so I don't have to carry them in #23275. This
is harmless, basically just noisy comments. The drawback
is, if for some reason #23275 does not pan out, I'll have
to go back and remove those tags. Right now I'm feeling
pretty comfortable about this parallelization approach tho.
```release-note
None
```
> CI: mount system test: make parallel-safe

- test/system/012-manifest.bats
Use safename instead of hardcoded "test"
Start registry once, in setup_file(), instead of requiring
individual tests to do so.
Add explicit --authfile arg to a bunch of places that now need it
Minor cleanup and improvements in test descriptions. I may have
gotten a little carried away here, but if this test ever fails
these additions will make someone's life much easier.
```release-note
None
```
> CI: manifest system tests: make parallel-safe

- test/e2e/play_kube_test.go
Two tests, both check port 80 on host, one wants it live,
the other wants it blocked. Prevent them from running
concurrently.
Fixes: #23470
```release-note
None
```
> CI: e2e: serialize root containerPort tests

- contrib/cirrus/win-sess-launch.ps1
> Add passwd validate and generate steps

- test/system/220-healthcheck.bats
Make 220-healthcheck.bats parallel-safe. Then (2nd commit) pay for
my hubris in having said that it was "easy".
```release-note
None
```
> CI: healthcheck system test: make parallel-safe

- test/system/080-pause.bats
Only one test can be parallelized. Do so, and add a comment
to the other one explaining why it can't be.
Also, add some missing error-message checks.
```release-note
None
```
> CI: 080-pause.bats: make parallel-safe

- docker/podman-docker.sh
Fixes #23628 
```release-note
None
```
> Fix podman-docker.sh under -eu shells

- cmd/podman/system/unshare.go
> remove trailing comma in example

- RELEASE_NOTES.md
- version/rawversion/version.go
> Release v5.2.2

- test/system/195-run-namespaces.bats
An easy one :-)
```release-note
None
```
> CI: parallel-safe namespaces system test

- .cirrus.yml
- test/e2e/pull_test.go
- test/e2e/run_test.go
Mostly to get pasta 08-14 but also a ton more changes elsewhere.
https://github.com/containers/automation_images/pull/383
Fixes: #23517 
```release-note
None
```
> Update CI VMs

- docs/source/markdown/podman-network-create.1.md
gateway ip in the description doesnt match the provided command
```release-note
none
```
> fix typo in podman-network-create.1.md

- Makefile
Belated followup to #21965.
All this time, we've been creating a socket and running
podman-remote --url /path/to/socket
This dates back to varlink. Remember varlink?
There's no need for it. Let's run podman system service
with no args. That's a more realistic test, and it makes
our logs cleaner as a bonus.
[Ed note: it's been working fine in my parallel-testing PR]
```release-note
None
```
> Makefile: remotesystem: use real podman server, no --url

- docs/source/markdown/options/volume.md
Fixes: #23329
```release-note
None
```
> [ci:docs] Fix description of :Z to talk about pods

- docs/source/markdown/podman-machine-init.1.md.in
No
Addresses #23763 
AFAICT the help text piece is addressed in https://github.com/containers/common/pull/2100.
> Clarify podman machine volume mounting behavior under WSL

- .cirrus.yml
- .golangci.yml
- .packit.yaml
- contrib/cirrus/prebuild.sh
- go.mod
- libpod/container_internal.go
- libpod/kube.go
- libpod/logs/log_test.go
- libpod/networking_linux_test.go
- pkg/domain/infra/abi/play_test.go
- pkg/errorhandling/errorhandling_test.go
- pkg/farm/farm.go
- pkg/farm/list_builder.go
- pkg/machine/define/vmfile_test.go
- pkg/specgen/generate/kube/play_test.go
- pkg/specgen/generate/ports.go
- pkg/specgen/generate/ports_test.go
- pkg/specgen/namespaces_test.go
- pkg/util/filters_test.go
- test/e2e/checkpoint_test.go
- test/e2e/healthcheck_run_test.go
- test/e2e/logs_test.go
- test/e2e/network_test.go
- test/e2e/pod_infra_container_test.go
- test/e2e/run_memory_test.go
- test/e2e/run_networking_test.go
see commits
```release-note
Podman now required golang 1.22 to build
```
> Update to go 1.22

- go.mod
- go.sum
- vendor/github.com/containers/storage/.cirrus.yml
- vendor/github.com/containers/storage/Makefile
- vendor/github.com/containers/storage/drivers/overlay/composefs.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- vendor/github.com/containers/storage/drivers/overlay/overlay_nocgo.go
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/pkg/chunked/cache_linux.go
- vendor/github.com/containers/storage/pkg/fileutils/exists_freebsd.go
- vendor/github.com/containers/storage/storage.conf
- vendor/github.com/containers/storage/store.go
- vendor/modules.txt
> vendor: update c/storage

- test/system/130-kill.bats
Where possible, use safename and add ci:parallel tags.
One test runs "podman kill -a", which would be unwise to run
in parallel with other tests.
```release-note
None
```
> CI: make 130-kill parallel-safe

- test/system/110-history.bats
Add ci:parallel tags for Bats, and tweak one test to be safe
```release-note
None
```
> CI: make 110-history parallel-safe

- test/system/125-import.bats
Add a bunch of safenames, and ci:parallel tags, and one
workaround for a buildah parallelization bug
```release-note
None
```
> CI: make 125-import parallel-safe

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/dns-option.pod
- test/e2e/quadlet/dns-search.pod
- test/e2e/quadlet/dns.pod
- test/e2e/quadlet_test.go
> Add DNS, DNSOption and DNSSearch to quadlet pod

- troubleshooting.md
```release-note
None
```
That `--userns=keep-id` blocks  `--userns=auto` can be a bit surprising . Let's document that. I first thought that this only happens when running rootless podman but I reproduced the same behaviour for rootful podman. The example in the troubleshooting tip uses rootless podman.
> troubleshooting: add tip about --userns=auto and --userns=keep-id

- go.mod
- go.sum
- vendor/github.com/checkpoint-restore/go-criu/v7/.golangci.yml
- vendor/github.com/checkpoint-restore/go-criu/v7/README.md
- vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go
- vendor/modules.txt
> vendor: update c/common

- troubleshooting.md
Add a troubleshooting tip about the error message
```
ERRO[0000] Cannot find mappings for user "containers": no subuid ranges found for user "containers" in /etc/subuid
Error: creating container storage: not enough unused IDs in user namespace
```
```release-note
None
```
> troubleshooting: add tip about the user containers

- docs/source/markdown/options/cache-ttl.md
> Fix typo in `docs/source/markdown/options/cache-ttl.md`

- Makefile
- pkg/bindings/test/networks_test.go
- pkg/bindings/test/secrets_test.go
- pkg/bindings/test/volumes_test.go
Silence some new warnings that should not matter here.
```release-note
None
```
> update golangci-lint to 1.61.0

- test/e2e/common_test.go
- test/system/setup_suite.bash
If we leak netns files this is not good so we should have a check for it.
Fixes #23715
```release-note
None
```
> CI: netns leak checks for system and e2e

- libpod/info.go
This PR fixes #24001, by correcting the typo in the error message. 
```release-note
None
```
> Fix typo in error message

- test/system/helpers.registry.bash
This removes the need for a tricky/fragile namespace workaround.
Huge thanks to Paul for discovering documentation on the
Registry container, and how to override config.yml settings:
https://distribution.github.io/distribution/about/configuration/#override-specific-configuration-options
Drive-by: consistentize quotes in -eVAR="value". Minor, but
makes them all easier to read with emacs/vi syntax highlighting.
```release-note
None
```
> CI: system test registry: use --net=host

- test/system/200-pod.bats
...as much as possible. Not all tests can be parallelized.
```release-note
None
```
> CI: make 200-pod parallel-safe

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.packit.yaml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/copier/xattrs.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/build.go
- vendor/github.com/containers/buildah/imagebuildah/executor.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/modules.txt
As the title says, in preparation of the Podman v5.2.3 release.
```release-note
None
```
> [v5.2] Bump Buildah to v1.37.3

- test/system/035-logs.bats
Any test that uses --events-backend=file cannot be run in parallel
due to #23750. This seems to be a hard block, unfixable.
All other tests, enable ci:parallel.
And, bring in timing fixes #23600. Thanks, @Honny1!
```release-note
None
```
> CI: parallelize logs test as much as possible

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.2.3

- test/system/260-sdnotify.bats
Potential race between starting socat (which creates a socket
file) and processes accessing said socket. Or maybe not. I
dunno, I'm grasping at straws. This is an elusive flake.
Fixes: #23798 (I hope)
```release-note
None
```
> System tests: sdnotify: wait for socket file creation

- test/system/005-info.bats
Although podman has moved on from CNI, RHEL has not. Make
sure that builds on RHEL test the desired network backend(s).
Effective immediately, gating.yaml on all RHEL branches
must set CI_DESIRED_NETWORK (=cni or =netavark)
```release-note
None
```
> CI: require and test CI_DESIRED_NETWORK on RHEL

- test/README.md
> [CI:DOCS] Document TESTFLAGS in test README file

- OWNERS
Update OWNERS file specifically around `approvers`.  Also, added Mario.
```release-note
NONE
```
> OWNERS file audit and update

- .packit.yaml
> [skip-ci] Packit: constrain koji and bodhi jobs to fedora package to avoid dupes

- test/system/055-rm.bats
There's an important reason why the healthcheck container in 055-rm
test uses 'sleep infinity' and not 'top. Document it.
And, the test itself wasn't actually working as intended. Make
it safer by confirming that the container actually enters
the "stopping" state.
```release-note
None
```
> 055-rm test: clean up a test, and document

- .packit.yaml
> [skip-ci] Packit: remove jobs not required for the v5.2-rhel branch

- README.md
I'll also throw this on Podman.io and maybe write a short blog about it there.
```release-note
Podman is changing its release model. We will now make 4 releases a year, once each in February, May, August, and November.
```
> Note in the README that we are moving to timed releases

- .cirrus.yml
https://github.com/containers/automation_images/pull/376
```release-note
None
```
> Test new VM build

- rpm/podman.spec
> [skip-ci] RPM: remove dup Provides

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/internal/parse/parse.go
- vendor/modules.txt
Addresses:
https://issues.redhat.com/browse/RHEL-62386
https://issues.redhat.com/browse/RHEL-62377
```release-note
None
```
> [v4.4.1-rhel] Update buildah for CVE-2024-9675

- README.md
Fixes https://github.com/containers/podman/issues/24244
```release-note
None
```
> readme: Add reference to pasta in the readme

- docs/source/markdown/podman-run.1.md.in
> doc: Remove whitespace before comma

- hack/buildah-vendor-treadmill
- test/buildah-bud/run-buildah-bud-tests
Many small improvements (reviewable as individual commits).
Fixes: RUN-2217
```release-note
None
```
> buildah treadmill: documentation and process updates

- DISTRO_PACKAGE.md
High-level overview of packaging, intended for Linux distros.
Closes: RUN-1356
```release-note
Document the process for packaging Podman for a new Linux distro
```
> Document packaging process

- libpod/healthcheck.go
- libpod/healthcheck_linux.go
- test/system/220-healthcheck.bats
The startup service is special because we have to transition from startup to the normal unit. And in order to do so we kill oursleves (as we are run as part of the service). This means we always exited 1 which causes systemd to keep us failure and not remove the transitent unit unless "reset-failed" is called. As there is no process around to do that we cannot really do this, thus make us exit(0) which makes more sense.
Of course we could try to reset-failed the unit later but the code for that seems more complicated than that.
Fixes: 0bbef4b830 ("libpod: rework shutdown handler flow")
Fixes: #24351
```release-note
None
```
> healthcheck: do not leak startup service

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/internal/parse/parse.go
- vendor/modules.txt
Addresses:
https://issues.redhat.com/browse/RHEL-62376
https://issues.redhat.com/browse/RHEL-62385
```release-note
None
```
> [v4.2.0-rhel] Update buildah for CVE-2024-9675

- test/system/520-checkpoint.bats
This has been running reliably for weeks in #23275
```release-note
None
```
> CI: parallelize 520-checkpoint tests

- test/e2e/play_kube_test.go
- test/framework/framework.go
- test/utils/utils.go
```release-note
fix some function names in comment
```
> chore: fix some function names in comment

- pkg/machine/e2e/config_test.go
Nobody is looking into this anyway and it just clutters the logs and will cause confusion for readers. If some day someone wants to fix the macos IO bugs they can add this back.
```release-note
None
```
> pkg/machine/e2e: remove debug

- docs/source/markdown/podman-systemd.unit.5.md
> doc: fix words repetitions

- version/rawversion/version.go
We have a v5.3 branch already.
```release-note
None
```
> [CI:ALL] Bump main to v5.4.0-dev

- .golangci.yml
- Makefile
- cmd/podman/common/completion_test.go
- cmd/podman/system/df.go
- pkg/bindings/errors.go
- pkg/domain/infra/abi/system.go
- pkg/domain/infra/tunnel/system.go
- pkg/machine/applehv/stubber.go
- pkg/machine/e2e/config_basic_test.go
- pkg/machine/e2e/config_ssh_test.go
- pkg/machine/e2e/config_start_test.go
- pkg/machine/e2e/config_system_connection_list_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/os_test.go
- pkg/machine/e2e/ssh_test.go
- pkg/machine/e2e/start_test.go
- pkg/machine/libkrun/stubber.go
- pkg/machine/qemu/stubber.go
- test/e2e/common_test.go
- fix issues found by recvcheck
- skip k8s files from recvcheck
- remove two removed linters gomnd and execinquery
```release-note
None
```
> update golangci-lint to v1.62.0

- contrib/win-installer/test-installer.ps1
Do not pull from a moving target, use a defined version so updates must happen in a PR and do not break others.
```release-note
None
```
> win-installer test: revert to v5.3.0

- .packit.yaml
Fedora 39 is now EOL.
```release-note
None
```
> [skip-ci] Packit/copr: switch to fedora-all

- test/system/155-partial-pull.bats
> Fix apparent typos in zstd:chunked tests

- .cirrus.yml
- test/e2e/common_test.go
- test/e2e/run_userns_test.go
from https://github.com/containers/automation_images/pull/396
```release-note
None
```
> Update VM images

- pkg/bindings/connection.go
Yes
I have spotted an issue when accessing remote podman host if `~/.ssh/identity` file does not exist.
```text
% podman version                                                                                                                                       
Client:       Podman Engine
Version:      5.3.1
API Version:  5.3.1
Go Version:   go1.23.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      darwin/arm64
Server:       Podman Engine
Version:      5.3.1
API Version:  5.3.1
Go Version:   go1.22.7
Built:        Thu Nov 21 00:00:00 2024
OS/Arch:      linux/arm64
```
Please note that there is no `Identity` for monster connection (I am relying on ssh-agent)
```text
% podman system connection add monster ssh://monster/run/user/1000/podman/podman.sock
% podman system connection list …
```
> Fixing ~/.ssh/identity handling

- cmd/podman/common/create_test.go
- cmd/quadlet/main_test.go
- libpod/container_internal_test.go
- pkg/domain/utils/utils_test.go
- pkg/machine/config_test.go
- pkg/machine/provider/platform_test.go
- pkg/specgen/generate/kube/play_test.go
- pkg/specgenutil/specgenutil_test.go
- pkg/util/utils_test.go
> Switch all calls of assert.Nil to assert.NoError

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v5.3.2

- docs/source/markdown/podman-kube-play.1.md.in
Follow up to ec6b0355bf9c9b90b774707b6adc49a743cbebd4
Signed-off-by: Robert Günzler <r@gnzler.io>
```release-note
None
```
> Document kube-play CDI support

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/.packit.yaml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/internal/open/open.go
- vendor/github.com/containers/buildah/internal/open/open_linux.go
- vendor/github.com/containers/buildah/internal/open/open_types.go
- vendor/github.com/containers/buildah/internal/open/open_unix.go
- vendor/github.com/containers/buildah/internal/open/open_unsupported.go
- vendor/github.com/containers/buildah/internal/types.go
- vendor/github.com/containers/buildah/internal/volumes/bind_linux.go
- vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go
- vendor/github.com/containers/buildah/internal/volumes/volumes.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay_linux.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay_unsupported.go
- vendor/github.com/containers/buildah/run.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
Fixes: https://issues.redhat.com/browse/OCPBUGS-44540, https://issues.redhat.com/browse/RHEL-67602, https://issues.redhat.com/browse/RHEL-67601
Addresses: CVE-2024-11218
```release-note
None
```
> [v4.9-rhel] CVE-2024-11218, Bump Buildah to v1.33.12

- libpod/container_internal.go
- test/system/080-pause.bats
This PR changes how containers are paused and unpaused.  Now, the timer for HealthCheck is removed when the container is paused. If the container is unpaused then a new timer for  HealthCheck is created.
1. `cid=$(podman run -dt --replace --name hc1 --health-interval 5s --healthcheck-command 'echo test' quay.io/libpod/alpine:latest)`
2. `podman pause hc1`
4. `systemctl --user status ${cid}-\*.{service,timer}`
> There should be no `systemctl` output. 
Fixes: https://github.com/containers/podman/issues/24590
Fixes: https://issues.redhat.com/browse/RUN-2468
```release-note
The HealthCheck timers are now removed when containers are paused and recreated when unpaused.
```
> Remove timer for HealthCheck when container is paused

- cmd/podman/common/completion.go
Closes: https://github.com/containers/podman/issues/25163
```release-note
None
```
> util: replace Walk with WalkDir

- .cirrus.yml
- contrib/cirrus/postbuild.sh
> new images 2025-01-31

- .cirrus.yml
- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/internal/open/open.go
- vendor/github.com/containers/buildah/internal/open/open_linux.go
- vendor/github.com/containers/buildah/internal/open/open_types.go
- vendor/github.com/containers/buildah/internal/open/open_unix.go
- vendor/github.com/containers/buildah/internal/open/open_unsupported.go
- vendor/github.com/containers/buildah/internal/parse/parse.go
- vendor/github.com/containers/buildah/internal/types.go
- vendor/github.com/containers/buildah/internal/volumes/bind_linux.go
- vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay.go
- vendor/github.com/containers/buildah/run.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
Addresses:
https://issues.redhat.com/browse/RHEL-67598
```release-note
None
```
> [v4.2.0-rhel] Update buildah for CVE-2024-11218

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/modules.txt
Bump Buildah to v1.39.0 in the main branch.
```release-note
None
```
> Bump to Buildah v1.39.0

- test/e2e/common_test.go
First use proper ginkgo error handling to ensure errors are actually reported and fail the test. Mark it as helper function to have better stack traces.
Then use a atomic write function to prevent issues with partial written files. I think this is causing CI flakes[1].
Lastly fix the file permissions, do not make it world writable and do not set the executable bit on the file.
[1] https://api.cirrus-ci.com/v1/artifact/task/5985244932734976/html/int-podman-fedora-41-root-host-sqlite.log.html#t--Podman-network-podman-network-ID-test--1
```release-note
None
```
> test/e2e: improve write/removeConf()

- .cirrus.yml
- test/system/125-import.bats
> CI: new images 2025-02-10

- Makefile
- test/e2e/logs_test.go
> update golangci-lint to v1.64.4

- completions/bash/podman
- completions/bash/podman-remote
- completions/powershell/podman-remote.ps1
- completions/powershell/podman.ps1
- go.mod
- go.sum
- vendor/github.com/spf13/cobra/README.md
- vendor/github.com/spf13/cobra/active_help.go
- vendor/github.com/spf13/cobra/bash_completionsV2.go
- vendor/github.com/spf13/cobra/cobra.go
- vendor/github.com/spf13/cobra/command.go
- vendor/github.com/spf13/cobra/completions.go
- vendor/github.com/spf13/cobra/powershell_completions.go
- vendor/modules.txt
And regenerate the completion scripts.
```release-note
None
```
> update github.com/spf13/cobra to v1.9.1

- go.mod
- go.sum
- libpod/runtime_volume_common.go
- rpm/podman.spec
- test/system/161-volume-quotas.bats
- test/system/README.md
- vendor/github.com/containers/storage/drivers/quota/projectquota_supported.go
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/pkg/archive/archive.go
- vendor/github.com/containers/storage/pkg/archive/changes.go
- vendor/modules.txt
DO NOT MERGE until c/storage https://github.com/containers/storage/pull/2264 merges.
Fixes #25368 
```release-note
Fixed a bug where volume quotas were not being applied.
```
> Fix volume quota assignment

- cmd/quadlet/main.go
- pkg/systemd/parser/unitfile.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/label-unsupported-escape.container
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet - Print warnings to avoid silent line skips
```
Fixes #25339
> Quadlet warning messages

- docs/source/markdown/options/mount.md
- libpod/container_api.go
- pkg/domain/infra/abi/play.go
see commits
```release-note
None
```
> Some minor follow up fixes from PR comments

- .cirrus.yml
- test/compose/slirp4netns_opts/setup.sh
- test/e2e/common_test.go
- test/e2e/pod_create_test.go
- test/system/252-quadlet.bats
- test/system/500-networking.bats
from https://github.com/containers/automation_images/pull/401
```release-note
None
```
> New images 2025-03-12

- cmd/podman/machine/ssh.go
- pkg/machine/e2e/ssh_test.go
Honor the rootfulness of the named Podman Machine when SSh-ing into it.
Resolves: https://github.com/containers/podman/issues/25332
```release-note
Fix a bug where SSH-ing into a rootful named Machine (not podman-machine-default) would put the user into the rootless shell.
```
> Honor rootfulness when SSH-ing into named Machine

- ROADMAP.md
Even though this is tardy, here is an update reflecting milestones and features for 1Q25.
Fixes https://issues.redhat.com/browse/RUN-2447
```release-note
None
```
> Update roadmap for Q1

- go.mod
- go.sum
- test/system/800-config.bats
- vendor/github.com/BurntSushi/toml/README.md
- vendor/github.com/BurntSushi/toml/decode.go
- vendor/github.com/BurntSushi/toml/encode.go
- vendor/github.com/BurntSushi/toml/error.go
- vendor/github.com/BurntSushi/toml/lex.go
- vendor/github.com/BurntSushi/toml/meta.go
- vendor/github.com/BurntSushi/toml/parse.go
- vendor/modules.txt
Includes one minor test fix as the line number reported as error was changed, it seems to be actually correct now.
```release-note
None
```
> vendor: update github.com/burntsushi/toml to v1.5.0

- docs/source/Introduction.rst
> Fix some code blocks in documentation

- .cirrus.yml
From https://github.com/containers/automation_images/pull/402
```release-note
None
```
> New images 2025-03-24

- pkg/machine/apple/apple.go
- pkg/machine/hyperv/stubber.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/machine.go
This is faster and, to my best knowledge, is equivalent to the old code.
```release-note
None
```
> pkg/machine/vmconfigs: simplify IsFirstBoot

- ROADMAP.md
now that the priorities have been determined, we are able to publish general roadmap items for 2W 2025.
```release-note
None
```
> Update roadmap for 2Q 2025

- test/e2e/play_kube_test.go
- test/utils/utils.go
```release-note
fix function name in comment
```
> chore: fix function name in comment

- CONTRIBUTING.md
- TRIAGE.md
> Add documentation describing how to triage issues

- MAINTAINERS.md
They start with an upper case letter, the link is already correct.
```release-note
None
```
> Maintainers.md: fix two github nicks

- hack/bats
- test/README.md
see the commits, inspired by https://github.com/containers/podman/pull/25800 Mostly trying to make things more clear to avoid any confusion.
```release-note
None
```
> update hack/bats to not PASS NOP env and update test README with more system test info

- cmd/podman/common/create_opts.go
- cmd/podman/containers/ps.go
- cmd/podman/parse/net.go
- libpod/container_internal.go
```release-note
Make function comment match function name
```
> chore: make function comment match function name

- hack/podman_cleanup_tracer.bt
- test/e2e/checkpoint_test.go
- test/system/220-healthcheck.bats
- test/system/520-checkpoint.bats
- test/system/600-completion.bats
see commits
```release-note
None
```
> Some minor flake cleanup/debugging/skips

- cmd/quadlet/main.go
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/dependent.build
- test/e2e/quadlet/dependent.container
- test/e2e/quadlet/dependent.error.container
- test/e2e/quadlet/dependent.image
- test/e2e/quadlet/dependent.kube
- test/e2e/quadlet/dependent.network
- test/e2e/quadlet/dependent.pod
- test/e2e/quadlet/dependent.volume
- test/e2e/quadlet_test.go
Yes
```release-note
Names of Quadlet units specified as systemd dependencies are automatically translated
```
> Quadlet - translate dependencies on other quadlet units

- .cirrus.yml
> New images f42

- version/rawversion/version.go
Manual step in release process for now, working on automation. 
```release-note
None
```
> [v5.5] Bump to v5.5.0-dev

- pkg/systemd/quadlet/quadlet.go
No
```release-note
None
```
No new tests on purpose to verify optimization has no regressions
> Quadlet - use helper function to initialize service struct

- pkg/machine/shim/host.go
In the instance where the user sends a signal, such as SIGINT (Ctl-c), when a Podman Machine is in the middle of starting, make sure the state doesn't get stuck in the "Currently Starting" status.
Resolves: #24416
None
```release-note
Fix a bug where a Podman Machine would have the incorrect state if sent SIGINT
```
> Handle machine start state when sent a signal

- version/rawversion/version.go
Restore v5.5 branch to v5.5.0-dev so builds not from the RC commit will show a `-dev` version, not an RC version.
```release-note
NONE
```
> Bump to v5.5.0-dev

- docs/source/markdown/options/userns.container.md
Closes: https://github.com/containers/podman/issues/26063
```release-note
None
```
> docs: fix markdown format

- version/rawversion/version.go
> Bump to v5.5.0

- .pre-commit-config.yaml
- test/tmt/system.fmf
> lint: cleanups after TMT inclusion

- test/e2e/run_device_test.go
The e2e tests for device access involving /dev/kmsg could fail intermittently.  This was due to a race condition where concurrent writes to the kernel log buffer by other processes, while the test was reading from /dev/kmsg, could cause the read to fail with ESPIPE.
Fixes: https://github.com/containers/podman/issues/23882
```release-note
None
```
> test: fix race conditions in /dev/kmsg tests

- RELEASE_NOTES.md
> Release notes for v5.5.1

- libpod/events/logfile.go
more details in each commit
found by Gemini and Claude
```release-note
None
```
> some random fixes

- docs/source/markdown/podman-container-diff.1.md.in
- docs/source/markdown/podman-container-inspect.1.md.in
- docs/source/markdown/podman-container-restore.1.md
- docs/source/markdown/podman-diff.1.md.in
- docs/source/markdown/podman-farm-create.1.md
- docs/source/markdown/podman-image-diff.1.md
- docs/source/markdown/podman-image-mount.1.md
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-inspect.1.md.in
- docs/source/markdown/podman-load.1.md
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-annotate.1.md.in
- docs/source/markdown/podman-manifest-inspect.1.md.in
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-manifest-rm.1.md
- docs/source/markdown/podman-mount.1.md.in
- docs/source/markdown/podman-network-connect.1.md
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-network-rm.1.md
- docs/source/markdown/podman-pod-stats.1.md.in
- docs/source/markdown/podman-ps.1.md
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-rmi.1.md
- docs/source/markdown/podman-save.1.md.in
- docs/source/markdown/podman-search.1.md.in
In a lot of places, `Example` -> `Examples` for consistency
Plus similar trivial fixes. All found while looking for good first issue manpage fixes
```release-note
NONE
```
> Bunch of trivial manpage fixes

- docs/source/markdown/podman-system-prune.1.md
Fixes #26358
```release-note
None
```
> Update podman system prune doc

- pkg/systemd/quadlet/quadlet.go
Reduces quadlet binary size about 170kb.
```release-note
None
```
> quadlet: remove indirect logrus import

- .cirrus.yml
- test/e2e/checkpoint_test.go
- test/system/520-checkpoint.bats
> 1. update image_fix 2. skip checkpoint_tests duo to rawhide issue

- contrib/cirrus/setup_environment.sh
- libpod/container_internal.go
- libpod/healthcheck_linux.go
- test/e2e/healthcheck_run_test.go
This backports https://github.com/containers/podman/pull/12742 to `v3.4.3-rhel`.
Jira: https://issues.redhat.com/browse/RHEL-24871
```release-note
None
```
> [v3.2.3-rhel] Backports for health check files

- Makefile
- rpm/podman.spec
> add grpcnotrace build tag to reduce binary size

- pkg/systemd/parser/unitfile.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/exec-unsupported-escape.container
- test/e2e/quadlet/reloadcmd-unsupported-escape.container
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet - print warnings when fail to parse exec or reload command
```
Fixes: #26542
> Quadlet - print warning when fail to parse

- MAINTAINERS.md
- OWNERS
They have done valuable contributions to the project over the past months.
```release-note
None
```
> Maintainers: add Lewis, Jan and Nicola as Reviewers 

- version/rawversion/version.go
> Bump to v5.6.0-RC1

- version/rawversion/version.go
> Bump to v5.6.0-rc2

- RELEASE_NOTES.md
> Update release notes for v5.6.0 final release

- ROADMAP.md
Some updates following the 3Q 2025 priority updates.  We have a lot of spikes that accompany work not listed here but given they are not true features, I am not adding them
```release-note
None
```
> 2025 3Q Roadmap Update

- contrib/cirrus/win-podman-machine-test.ps1
So we know what we are actually running on in tests.
```release-note
None
```
> ci: log wsl --version output

- version/rawversion/version.go
> Bump to v5.6.1

- pkg/machine/shim/host.go
Fixes: #26949
Signed-off-by: Jiri Dostal <jdostal@redhat.com>
```release-note
None
```
> Handle SIGPIPE to prevent machine stuck in Starting state

- pkg/api/handlers/libpod/quadlets.go
- pkg/api/handlers/swagger/responses.go
- pkg/api/server/register_quadlets.go
- pkg/api/server/server.go
- test/apiv2/36-quadlets.at
This PR introduces a new api endpoint to list quadlets.
Closes #27119 
```release-note
Add quadlet list resource for api
```
> pkg/api: api list quadlets resource
