- .cirrus.yml
We're seeing a huge number of "unknown failure" flakes,
and all seem to be in the 'clone' step, failing with:
echo "$ARTCURL..."
curl ... https://api.cirrus-ci.com/.../repo.tbz
(lots of pretty curl output lines)
curl: (22) The requested URL returned error: 502
Solution: use --retry, which will backoff-retry transient
failures. Start with a backoff of 8s, not the default 1.
```release-note
None
```
> CI: Cirrus setup: retry failed curls

- pkg/machine/wsl/machine.go
Fixes log follow operations since the corresponding k8s-file backend was previously dropped from usage (unintentionally   leaving behind the file events backend)
```release-note
Fixed log follow operations on podman machine on Windows
```
> (Windows) Drop stale config value resulting in asymmetric config

- test/system/255-auto-update.bats
- test/system/500-networking.bats
Some system tests in `255-auto-update.bats` and `500-networking.bats`
fail under proxy environment.
This PR fixes this problem.
In `255-auto-update.bats`, `Environment` parameters for proxy are added to systemd unit file.
In `500-networking.bats`, `run --http-proxy=false` is added to prevent proxy connections in connections between containers.
Signed-off-by: Tsubasa Watanabe <w.tsubasa@fujitsu.com>
```release-note
None
```
> system tests: fix some tests in proxy environment

- cmd/podman/system/events.go
- test/e2e/events_test.go
podman events --format {{.ID}} was not working since the template was
converted to a range but we only render each event individually.
Fixes #15648
```release-note
Fixed a bug where podman events would not work with a custom --format specifier.
```
> fix podman events with custom format

- docs/source/markdown/options/device.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
The refactors are starting to get harder to review - sorry.
Here the differences are pretty small, mostly changes to the
"it is a combination" wording and some asteriskization.
The more significant diffs are that there are some Notes that
are pod- or container- or build-specific; I needed to move those
from the middle to the end, then keep them in the source files
themselves. I don't think this affects readability of the
resulting man pages, but your opinion may differ.
Last important thing: I included the /dev/fuse text in the
common option, which means it will now show up in podman-build
(it was not previously there). If this text is not applicable
to podman-build, please LMK ASAP so I can just move it back
to individual source files. …
> [CI:DOCS] Man pages: refactor common options: --device

- docs/source/markdown/podman-auto-update.1.md.in
- pkg/autoupdate/autoupdate.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/kube.go
- pkg/systemd/notifyproxy/notifyproxy.go
- pkg/systemd/notifyproxy/notifyproxy_test.go
- test/system/250-systemd.bats
- test/system/255-auto-update.bats
- test/system/helpers.systemd.bash
Add auto-update support to `podman kube play`.  Auto-update policies can    
be configured for:                                                          
* the entire pod via the `io.containers.autoupdate` annotation             
* a specific container via the `io.containers.autoupdate/$name` annotation 
To make use of rollbacks, the `io.containers.sdnotify` policy should be     
set to `container` such that the workload running _inside_ the container    
can send the READY message via the NOTIFY_SOCKET once ready.  For           
further details on auto updates and rollbacks, please refer to the          
specific article [1].                                                       
Since auto updates and rollbacks bases on Podman's systemd integration,     
the k8s YAML must be executed …
> Support auto updates for Kubernetes workloads

- libpod/runtime_ctr.go
In case of a hard OS shutdown, containers may have a "removing"
state after a reboot, and an attempt to remove Pods with such
containers is unsuccessful:
error freeing lock for container ...: no such file or directory
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>
```release-note
Fixed Pods removal error after OS reboot
```
> fix Pod removal after OS hard shutdown

- libpod/events.go
- test/system/090-events.bats
```release-note
The container-related events (with ``Type`=`container`) for `Status` of `died` and `exec_died`
now carry the container's labels in the `Attributes` event field, as for instance the `start` container event
already does.
```
> Closes #15617: emit container labels for container exited and exec died events

- pkg/machine/wsl/machine.go
Fixes #14811
Changes pipe busy-wait to 20 seconds, slightly less aggressively. 
```release-note
Fixed intermittent issue with Compat API proxy startup on Windows
```
> Fix intermittent issue with Compat API proxy startup on Windows

- cmd/podman/system/reset.go
- docs/source/markdown/podman-system-reset.1.md
```release-note
None
```
**TL;DR:** I almost lost an awful amount of work.
**Story:** Yesterday, I needed to use netavark, to have the DNS feature enabled on my network. As my podman install was pre-netavark, I had to use the system reset command to enable it. It warned me that almost everything was going to be removed. As I understoot it, everything except my volumes was going to be deleted ... I asked myself, do I trust that? Well, yes, it looks like an exhaustive list, and maybe because volumes are basic enough, it may not be needed to delete them. It will just reset the core features of podman I guess, right? Do I confirm reset then? I said Yes. You know what followed.
Fortunately, I ran a backup script for my volumes very recently. But it wasn't planed in the first place. I am VERY …
> Update system reset warning message regarding deletion of volumes

- libpod/oci_conmon_attach_common.go
- libpod/oci_conmon_common.go
- libpod/oci_conmon_exec_common.go
- libpod/oci_conmon_exec_freebsd.go
- libpod/oci_conmon_exec_linux.go
This PR fixes two small problems in the conmon support code:
- Moving linux-specific capabilites code from oci_conmon_exec_common.go to the platform-specific file. This fixes a problem that stopped 'podman exec' from working on FreeBSD.
- Filtering out a confusing (but harmless) error which happened on FreeBSD when the container stdin closes.
```release-note
None
```
> Fixes for conmon support on FreeBSD

- docs/source/markdown/options/sysctl.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
As promised, harder and harder to review. Please take your time
with this one.
For IPC, I went with the list form. For net, I used the single-
sentence form instead of a one-element list.
The container/pod diffs are clumsy, sorry. Maybe it's time to
start thinking of a more flexible conditional mechanism, but
I'd really like to avoid that so I hope this is acceptable.
In the first sentence I went with 'namespaced' (final 'd') in
all instances. I also got rid of the 'new' in 'new pod' in
pod-clone.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --sysctl

- docs/source/markdown/options/privileged.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
An easy one. Went with the version from podman-run.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --privileged

- libpod/container_internal_linux.go
skip adding the /sys/fs/cgroup/systemd bind mount if it is not already present on the host.
[NO NEW TESTS NEEDED] requires a system without systemd.
Closes: https://github.com/containers/podman/issues/15647
```release-note
Do not attempt to bind mount `/sys/fs/cgroup/systemd` on cgroup v1 if the mount doesn't already exist on the host
```
> podman: skip /sys/fs/cgroup/systemd if not present

- docs/source/markdown/options/userns.pod.md
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
Another easy one. Difference is that pod-create was fixed
in #14532 (s/ignore/not allowed/) but pod-clone was not.
I went with the fixed version.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --userns (pod)

- libpod/container_internal_linux.go
- pkg/specgen/generate/namespaces.go
- test/e2e/run_test.go
Mitigates a potential permissions issue. Mirrors Buildah PR #4200 and CRI-O PR #6159.
Cherry-pick conflicts for v3.0.1-rhel branch have been addressed.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2121540
> [v3.0.1-rhel] Add container GID to additional groups

- pkg/specgen/generate/container.go
- pkg/specgen/resources_freebsd.go
- pkg/specgen/resources_linux.go
This avoids setting values in the spec which are not supported on FreeBSD - including these values causes warning messages for the unsupported features.
```release-note
None
```
> specgen/generate: Factor out setting resource limits from CompleteSpec

- libpod/kube.go
- test/e2e/generate_kube_test.go
podman does not use any service account token, so we set the automount flag
to false in podman generate kube.
```release-note
None
```
> Fix #15243 Set AutomountServiceAccountToken to false

- pkg/specgen/generate/validate.go
- test/e2e/run_cpu_test.go
`--cpu-rt-period` and `--cpu-rt-runtime` options are only supported on cgroups V2 systems.
Therefore, podman prints an warning message and ignores these options when we use cgroups V2 systems.
Related to: #15666
```release-note
Print an warning message and ignore cpu realtime options when we use cgroups V2 systems
```
> Ignore cpu realtime options on cgroups V2 systems

- cmd/podman/root.go
- pkg/domain/entities/engine.go
- test/system/001-basic.bats
Fixes: https://github.com/containers/podman/issues/14767
```release-note
podman --config test ... is now a hidden option for Docker compatibility.
```
> Add --config for Docker compatibility

- libpod/kube.go
- pkg/domain/infra/abi/play.go
- pkg/k8s.io/api/core/v1/types.go
- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
map HostUsers=false to userns=auto.
One difference with the current implementation in the Kubelet is that the podman default size is 1024 while the Kubelet uses 65536.
This is done on purpose, because 65536 is a problem for rootless as the entire IDs space would be allocated to a single pod.
```release-note
Now podman play kube honors the pod spec `HostUsers` flag
```
> kube: plug HostUsers in the pod spec

- test/system/280-update.bats
The e2e tests are incomplete, because they're just too hard
for any human to read/maintain. This defines tests in a
table, so they're easily reviewed and updated.
```release-note
None
```
> system tests for update

- cmd/podman/common/completion.go
- cmd/podman/common/create.go
- docs/source/markdown/options/health-on-failure.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/container_inspect.go
- libpod/define/healthchecks.go
- libpod/healthcheck.go
- libpod/options.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/system/220-healthcheck.bats
- test/system/250-systemd.bats
- test/system/helpers.bash
For systems that have extreme robustness requirements (edge devices, particularly those in difficult to access environments), it is important that applications continue running in all circumstances. When the application fails, Podman must restart it automatically to provide this robustness. Otherwise, these devices may require customer IT to physically gain access to restart, which can be prohibitively difficult.
Add a new `--on-failure` flag that supports four actions:
- **none**: Take no action.
- **kill**: Kill the container.
- **restart**: Restart the container.  Do not combine the `restart` action with the `--restart` flag.  When running inside of a systemd unit, consider using the `kill` or `stop` action instead to make use of systemd's restart policy.
- **stop**: Stop the …
> health check: add on-failure actions

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/modules.txt
Podman build: Add container GID to additional groups
```release-note
None
```
> [v4.2.0-rhel] vendor: bump buildah to `v1.27.1`

- libpod/oci_conmon_common.go
Fix the error handling in the fallback logic of `stop` when Podman resorts to killing a container; the error message wrapped the wrong error.
[NO NEW TESTS NEEDED] as it is a rare flake in the tests and I do not know how to reliably reproduce it.
Fixes: #15661
```release-note
Fix a bug in `podman stop` where it mistakenly returned an error when resorting to sending sigkill.
```
> stop: fix error handling

- .cirrus.yml
The win_installer task fails on the `multiarch` cirrus-cron build. This is because it depends on the `Windows Cross` (alt_build) task which is bypassed in this context.  This will cause the `repo.tbz` download to constantly throw 404s.  Fix this by skipping the win_installer task for the `multiarch` (container images) build.
```release-note
None
```
> [CI:BUILD] Cirrus: Don't run win_installer in multiarch cron

- pkg/specgen/generate/kube/kube.go
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>
```release-note
Fix CPU usage limitation in play kube for non integer values
```
> Fix CPU usage limitation in play kube for non integer values

- libpod/oci_conmon_common.go
Pass along the path so that when conmon calls podman as part of the exit command podman has the correct path.
Also adjusted the CONTAINERS_CONF lookup to match the codestyle of other environment lookups.
Resolves #15707
```release-note
Pass PATH and CONTAINERS_HELPER_BINARY_DIR environment variables to conmon calls
```
> Include PATH in conmon env.

- libpod/container_internal.go
- libpod/lock/file/file_lock.go
- pkg/api/handlers/compat/info.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/images.go
- pkg/util/utils_linux.go
- test/e2e/benchmarks_test.go
- test/e2e/container_create_volume_test.go
- test/e2e/image_sign_test.go
- test/e2e/manifest_test.go
- test/e2e/push_test.go
```release-note
None
```
This PR replaces all `ioutil.ReadDir` to `os.ReadDir`. `ioutil.ReadDir` has been deprecated in Go 1.16. The new `os.ReadDir` is a more efficient implementation than `ioutil.ReadDir`. 
The full proposal can be read here: https://github.com/golang/go/issues/41467
Reference: https://pkg.go.dev/io/ioutil#ReadDir
> refactor: use `os.ReadDir` for lightweight directory reading

- docs/source/markdown/options/volume.md
Make sure that the wording of mounting something _from_ the source _into_ the destination is consistent.
```release-note
None
```
> [CI:DOCS] --volume: consistent wording

- libpod/oci_conmon_linux.go
Commit 30e7cbccc194 accidentally added a deadlock as Podman was waiting for the exit code to show up when the container transitioned to stopped. Code paths that require the exit code to be written (by the cleanup process) should already be using `(*Container).Wait()` in a deadlock free way.
[NO NEW TESTS NEEDED] as I did not manage to a reproducer that would work in CI.  Ultimately, it's a race condition.
Backport-for: #15492
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2124716
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2125647
```release-note
Fix a potential deadlock in `podman kill`.
```
@TomSweeneyRedHat @mheon PTAL
> [v4.2.0-rhel] libpod: UpdateContainerStatus: do not wait for container

- docs/source/markdown/options/volumes-from.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Removed a spurious right-bracket; went with upper-case for options;
removed 'you's; added some <<container|pod>>s.
Hard to review because none of the existing man pages had it
quite right.
```release-note
None
```
> [CI:DOCS] Man pages: refactor common options: --volumes-from

- cmd/podman/system/events.go
- docs/source/markdown/podman.1.md
- go.mod
- go.sum
- libpod/events.go
- libpod/events/events_linux.go
- libpod/events/journal_linux.go
- libpod/events/logfile.go
- libpod/events/nullout.go
- libpod/runtime.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/abi/secrets.go
- pkg/specgen/generate/kube/play_test.go
- test/system/090-events.bats
- vendor/github.com/containers/common/libnetwork/network/interface.go
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/pkg/secrets/secrets.go
- vendor/modules.txt
podman --events-backend file events --stream=false should never hang. The
problem is that our tail library will wait for the file to be created
which makes sense when we do not run with --stream=false. To fix this we
can just always create the file when the logger is initialized. This
would also help to report errors early on in case the file is not
accessible.
podman --events-backend none events should return with an error since it
will never be able to actually list events.
Currently podman events will just fail with `Error: failed to get journal
cursor: failed to get cursor: cannot assign requested address` when the
journal contains zero podman events.
The problem is that we are using the journal accessors wrong. There is no
need to call GetCursor() and compare them manually. The …
> fix several podman events issues

- docs/source/markdown/options/rootfs.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
podman-create and -run only. The SELinux text was added
to podman-run (but not -create) in #3631, and reformatted
in #5192. I assume here that it also applies to podman-create.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --rootfs

- libpod/events/events_freebsd.go
This function changed from public to private which broke the FreeBSD build.
Sadly, adding FreeBSD to the cross build isn't currently possible since github.com/godbus/dbus relies on cgo on FreeBSD. I've tried to fix this upstream but my PR is going nowhere - I think this dependency is only needed for systemd which isn't a thing on FreeBSD so it might be possible to work around the problem in libpod by making the systemd code conditional on linux.
```release-note
none
```
> events: Fix spelling of newNullEventer

- docs/source/markdown/podman-generate-systemd.1.md
- pkg/systemd/generate/containers.go
- test/system/250-systemd.bats
Emit a warning to the user when generating a unit with --new on a container that was created with a custom --restart policy. As shown in #15284, a custom --restart policy in that case can lead to issues on system shutdown where systemd attempts to nuke the unit but Podman keeps on restarting the container.
Fixes: #15284
```release-note
Emit a warning on potential shutdown issues when using `podman generate systemd` without the `--new` flag on a container with custom restart policy.
```
> generate systemd: warn on --restart without --new

- libpod/container_internal.go
- libpod/healthcheck_linux.go
- test/system/220-healthcheck.bats
Restart the health-check timers instead of starting them.  This will surpress annoying errors stating that an already running timer cannot be started anymore.
Fixes: #15691
```release-note
Fix a misleading error log when restarting a container with running health checks.
```
> health checks: restart timers

- docs/source/markdown/options/ip.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Between podman-create, run, and pod-create. The big difference
is that I changed 'IP' to 'IPv4' in podman-pod-create, I believe
that was an oversight in #12611.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --ip

- test/system/helpers.bash
Trying to catch the wiley metacopy flake: add a debug
condition to run_podman, in system tests, to log all
instances in which output includes the metacopy warning.
The idea is to detect the very first time it happens,
and see what is triggering it.
```release-note
None
```
> TEMPORARY: instrumenting for 15488

- docs/source/markdown/options/os.pull.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only shared by podman-create, -pull, -run. No changes
made other than whitespace, so this should be a gimme.
podman-build, import, and manifest-* also have --os options,
but those are unrelated and I can't find a way to combine
any two of them.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --os (pull)

- .github/labeler.yml
- .github/workflows/labeler.yml
Belated followup to #11829: use github labeler workflow[1] to
auto-add 'kind/api-change' label to PRs in which files are
touched under pkg/api
[1] https://github.com/actions/labeler
```release-note
None
```
> [CI:BUILD] Enable github labeler, use for api-change

- docs/source/markdown/options/publish.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Almost identical between podman-create, run, and pod-create.
The "Notes" are different, so I left those duplicated between
podman-create and run, and left the different one in pod-create.
podman-container-restore also has --publish but it's unrelated.
```release-note
```
> [CI:DOCS] Man pages: Refactor common options: --publish

- cmd/podman/auto-update.go
- cmd/podman/inspect/inspect.go
- cmd/podman/machine/info.go
- cmd/podman/machine/inspect.go
- cmd/podman/machine/list.go
- cmd/podman/networks/list.go
- cmd/podman/secrets/inspect.go
- cmd/podman/secrets/list.go
- cmd/podman/system/info.go
- cmd/podman/system/version.go
- cmd/podman/volumes/list.go
- pkg/machine/e2e/inspect_test.go
- test/e2e/volume_ls_test.go
- test/system/610-format.bats
- update all commands to use the report.Formatter
- update c/common with the latest version so that report.Formatter can handle newlines
see individual commit for more information
Fixes #13446
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2059658
```release-note
The format flag now handles template strings with `\n` in it correctly.
```
> Fix go template parsing with "\n" in it

- docs/source/markdown/.gitignore
- docs/source/markdown/options/tls-verify.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-container-runlabel.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-create.1.md.in
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-search.1.md.in
Ugh. This had about five different variations among twelve files.
I went with the version from podman-create, kube play, login, pull,
push, run. The others:
- manifest-add and create did not include the "true, false, missing"
text. Now they do. (If this text is N/A to these two, please yell).
Also, these two were written with "talking" instead of "contacting"
the registry.
- podman-build had "does not work with remote", but this
does not seem to be true, so I removed it. None of the
other files had that.
- the wording in podman-search is just weird, with "if needed"
and "is listed" and unclear "insecure registries". I just
nuked it all. If that wording was deliberate, for some reason
that applies only to podman-search, please yell.
- podman-container-runlabel has one diff that I like, …
> [CI:DOCS] Man pages: refactor common options: --tls-verify

- pkg/systemd/generate/pods.go
- pkg/systemd/generate/pods_test.go
- test/e2e/generate_systemd_test.go
Change the dependencies from a pod unit to its associated container units from `Requires` to `Wants` to prevent the entire pod from transitioning to a failed state.  Restart policies for individual containers can be configured separately.
Fixes: #14546
```release-note
Change the dependencies from a pod to its containers in `generate systemd`  from `Requires=` to `Wants=` to prevent the entire pod from transitioning into the failed state when one container dies.
```
> generate systemd: fix pod dependencies

- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
The default ip is 10.0.2.2 but is always the second ip from the slirp4netns subnet, which can be changed via the cidr option.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2090166
```release-note
Improve documentation for the slirp4netns allow_host_loopback option.
```
> [CI:DOCS] improve slirp4netns allow_host_loopback docs

- docs/source/markdown/options/ip6.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Similar to yesterday's --ip. No changes to content, all I did
was variableize the instances of 'container'/'pod'.
Did not touch podman-network-connect file, but if someone
wants to look at that one and tell me whether all this long
text is applicable to it (or not), I'd appreciate it.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --ip6

- libpod/container_exec.go
- libpod/pod_internal.go
- libpod/runtime_ctr.go
- libpod/runtime_volume_linux.go
- test/e2e/common_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/create_test.go
- test/e2e/diff_test.go
- test/e2e/events_test.go
- test/e2e/logs_test.go
- test/e2e/network_connect_disconnect_test.go
- test/e2e/network_create_test.go
- test/e2e/network_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_ps_test.go
- test/e2e/ps_test.go
- test/e2e/run_networking_test.go
- test/e2e/run_staticip_test.go
- test/e2e/run_test.go
- test/e2e/volume_exists_test.go
- test/e2e/volume_plugin_test.go
In view of https://github.com/containers/storage/pull/1337, do this:
```bash
for f in $(git grep -l stringid.GenerateNonCryptoID | grep -v '^vendor/'); do
sed -i 's/stringid.GenerateNonCryptoID/stringid.GenerateRandomID/g' $f;
done
```	
(Note that this PR does not depend on one in containers/storage).
```release-note
NONE
```
> all: stop using deprecated GenerateNonCryptoID

- pkg/rootless/rootless_linux.c
PR following https://github.com/containers/podman/discussions/15685#discussioncomment-3642919 for the v3.4 branch.
Moves the optional definition of `TEMP_FAILURE_RETRY` before its first use, so that `pkg/rootless` can be successfully build on musl.
```release-note
None
```
> fix building pkg/rootless on musl

- docs/source/markdown/.gitignore
- docs/source/markdown/options/interactive.md
- docs/source/markdown/options/preserve-fds.md
- docs/source/markdown/options/tty.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-start.1.md.in
Three simple options shared among podman-create, exec, run.
I mostly went with the podman-run versions. For --tty, this
means that create and exec get the long stdout/stderr note.
(The example, though, remains only in podman-run). For -i,
mostly boldspace changes.
For --preserve-fds, podman-exec now has the "not with remote"
note (which it didn't until now)
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --preserve-fds, -it

- libpod/container_internal_common.go
- libpod/container_path_resolution.go
- libpod/container_path_resolution_test.go
- test/e2e/run_working_dir_test.go
a subdirectory that is below a mount destination is detected as a subpath.
Closes: https://github.com/containers/podman/issues/15789
```release-note
Fixed the code to check if a directory is part of a mount, so that `--volume /foo:/foo --workdir /foo/bar` doesn't fail anymore
```
> libpod: fix lookup for subpath in volumes

- pkg/domain/infra/tunnel/containers.go
- test/system/035-logs.bats
- test/system/045-start.bats
- test/system/420-cgroups.bats
Three tests were running 'container rm' on 'start'ed containers
that might not yet have exited. Fix. Also, tighten up the
tests themselves, to make even more sure that they test
what they're supposed to test.
Discovered, in CI, that 'podman-remote logs --timestamps'
was unimplemented. Thanks to @Luap99 for the fix to that.
Fixes: #15783
Fixes: #15795
```release-note
bug fix: podman-remote logs --timestamps now emits timestamps
```
> System tests: fix three races

- docs/source/markdown/options/user.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
In podman-create, exec, and run. Went with the podman-run version.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --user

- libpod/container.go
The process of saving the OCI spec is not particularly reboot-safe. Normally, this doesn't matter, because we recreate the spec every time a container starts, but if one was to reboot (or SIGKILL, or otherwise fatally interrupt) Podman in the middle of writing the spec to disk, we can end up with a malformed spec that sticks around until the container is next started. Some Podman commands want to read the latest version of the spec off disk (to get information only populated after a container is started), and will break in the case that a partially populated spec is present. Swap to just ignoring these errors (with a logged warning, to let folks know something went wrong) so we don't break important commands like `podman inspect` in these cases.
[NO NEW TESTS NEEDED] Provided reproducer …
> Ensure that a broken OCI spec does not break inspect

- test/system/610-format.bats
Followup to #15673 (--format with newlines). I cobbled up a test
for it, but I was sloppy, so the test had issues that I kept
having to band-aid. This is a cleaner way to handle podman-machine.
...and, another unexpected surprise with podman stats. It
fails under rootless cgroupsv1. We can't sweep it under the
rug via skip_if_ubuntu because tests will then fail on RHEL8.
So, add a similar mechanism for testing podman stats.
...plus a non-surprise, the 'search' test flakes. Try minimizing
that by searching only $IMAGE. If quay.io is down, other tests
will certainly fail.
```release-note
None
```
> System tests: cleanup in --format test

- .cirrus.yml
Fix error in this task happening on `main`:
Failed to force reset to 5ab...6d4: object not found!
Ref: https://cirrus-ci.com/task/6674361678561280?logs=clone#L2
```release-note
None
```
> Cirrus: Fix win_installer task clone failure

- docs/source/markdown/options/shm-size.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Mostly went with the podman-run version. For ease of review, I
kept the "you" word -- I will fix that in my in-progress
cleanup PR.
This affects lots of files, each of which had slightly different
wording, but this actually isn't as bad as it looks. The diffs
were minor, and I'm pretty sure the new refactored text applies
equally well to all the man pages.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --shm-size

- pkg/api/handlers/compat/containers_stats.go
- test/apiv2/20-containers.at
- test/apiv2/test-apiv2
Docker compatibility: cap the memory limit reported by the cgroup to the maximum available memory.
Closes: https://github.com/containers/podman/issues/15765
```release-note
compact API: Cap the memory limit to the total available memory
```
> stats: cap memory limit to the available memory

- docs/source/markdown/.gitignore
- docs/source/markdown/options/no-reset.md
- docs/source/markdown/options/no-stream.md
- docs/source/markdown/podman-pod-stats.1.md.in
- docs/source/markdown/podman-stats.1.md.in
--no-reset and --no-stream, in podman-stats and pod-stats.
Very minor tweak to --no-stream to account for pods.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: 2 stats opts

- libpod/container_graph.go
- libpod/pod_api.go
- libpod/runtime_ctr.go
- libpod/runtime_img.go
- libpod/runtime_pod_linux.go
- libpod/runtime_volume_linux.go
- test/e2e/pod_rm_test.go
Originally, during pod removal, we locked every container in the pod at once, did a number of validity checks to ensure everything was safe, and then removed all the containers in the pod.
A deadlock was recently discovered with this approach. In brief, we cannot lock the entire pod (or much more than a single container at a time) without causing a deadlock. As such, we converted to an approach where we just looped over each container in the pod, removing them individually. Unfortunately, this removed a lot of the validity checking of the earlier approach, allowing for a lot of unintended bad things. Infra containers could be removed while containers in the pod still depended on them, for example.
There's no easy way to do validity checks while in a simple loop, so I implemented a version …
> Introduce graph-based pod container removal

- hack/buildah-vendor-treadmill
...gathered up from the last few months of almost-daily runs.
The principal difference is, ditching the git-am approach in
favor of git-cherry-pick. It's so much nicer! I keep forgetting
how clumsy git-am is. With the new approach, saved checkpoints
are kept as git branches, not in an easy-to-lose text file.
And, conflict resolution is MUCH EASIER. (Conflict resolution
is necessary when, e.g., the treadmill PR includes fixes for
some new vendoring that buildah has done but not podman, then
podman vendors in that same module but fixes broken tests in
a different way than I did).
Also a lot of smaller fixes for bugs reported by @Luap99.
Thank you for testing and for letting me know of problems!
Cursory review is OK: this will not break anything in the repo,
and I've been testing/finetuning …
> [CI:DOCS] Buildah treadmill script: various fixes

- docs/README.md
- docs/source/conf.py
Followup to #15621, which (correctly) removed parentheses from
md files. Turns out, a hidden part of our readthedocs process
depended on those parentheses. Update that step so it handles
the new, correct, <space><section-number> format.
Also update local-testing documentation in README, and clean it up a little.
Fixes: #15822
~~Completely untested.~~ Now tested, and it works (at least on my laptop).
```release-note
Fix broken HTML titles in readthedocs man pages
```
> [CI:DOCS] Fix broken titles on readthedocs

- docs/source/markdown/options/dns.md
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only between podman-build, create, and run. podman-pod-create
is too different.
As usual I went with the podman-run version. This means
keeping the word "flag" (which should be "option"), for
ease of review. I will fix in my in-progress cleanup PR.
For podman-build, I removed "during the build" and changed
it to a note for that man page only.
```release-note
```
> [CI:DOCS] Man pages: Refactor common options: --dns

- .cirrus.yml
There's little practical reason to execute unit-level testing on multiple platforms, since there's so little platform interaction. Remove the unit-test runs on Ubuntu, only execute on root-full and root-less Fedora.
```release-note
None
```
> Cirrus: Only run unit-testing on Fedora.

- pkg/api/handlers/libpod/containers.go
- pkg/bindings/containers/checkpoint.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/checkpoint_test.go
This commit fixes `container checkpoint --export`
to print a rawInput or an error.
Fixes: #15743
```release-note
Now checkpoint --export prints a rawInput or an error on remote
```
> remote: checkpoint --export prints a rawInput or an error on remote

- docs/source/markdown/podman-container-inspect.1.md
- docs/source/markdown/podman-info.1.md
- docs/source/markdown/podman-pod-inspect.1.md
- docs/source/markdown/podman-pod-stats.1.md.in
- docs/source/markdown/podman-secret-inspect.1.md
- docs/source/markdown/podman-stats.1.md.in
- docs/source/markdown/podman-version.1.md
This is a resurrection of #14386. I know this will upset some people. I keep thinking about this problem, and am more committed than before to fixing it.
I believe #14046 is important. I believe we should (1) document the values that `--format` accepts, and (2) implement tests to make sure that our documentation doesn't stray from reality.
Defense: look at this PR, in particular, the two commits in it. First commit is #14386 as it was in May, second commit is what I've had to do because `podman pod inspect` and `podman stats` have added new values that I find super confusing and I actually think are wrong: `.InspectPodData` and `.ContainerStats` seem to add no value, they're just a level of indirection. I think a user playing with command completion will find them confusing.
My purpose in …
> [CI:DOCS] man pages: document some --format options

- .cirrus.yml
There's little need to execute this test for (nearly) every PR. Further, since it always executes the *latest* upstream tests, there's no need to run it on any branch other than `main`.  Arrange for it to only execute for the `main` cirrus-cron trigger.
```release-note
None
```
> Cirrus: Move gitlab test to cirrus-cron "main"

- cmd/podman/common/netflags.go
- cmd/podman/containers/create.go
- cmd/podman/pods/create.go
- cmd/podman/utils/alias.go
- docs/source/markdown/options/dns-opt.container.md
- docs/source/markdown/options/dns-option.container.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- test/e2e/generate_kube_test.go
- test/system/200-pod.bats
[NO NEW TESTS NEEDED] Existing tests cover this.
```release-note
podman run/create/build now default to using --dns-option instead of --dns-opt, (--dns-opt is still supported but deprecated)
```
> Default to --dns-option to match Docker and Buildah

- pkg/specgen/generate/container.go
- test/e2e/container_clone_test.go
podman container clone was failing when env variables had multiple `=` in them. Switch split to splitn
resolves #15836
```release-note
users can specify env variables properly in container clone
```
> podman container clone env patch

- libpod/container_internal_common.go
There is no option in Selinux labeling to only relabel the top level of a directory. The option is to either label the path shared or not shared. Changing to make sure future engineers do not assume that recurse can work.
```release-note
None
```
> label.Relabel third option is shared not recurse

- cmd/podman/registry/remote.go
- cmd/podman/root.go
- cmd/podman/system/connection/add.go
- cmd/podman/system/connection/default.go
- cmd/podman/system/connection/list.go
- cmd/podman/system/connection/remove.go
- cmd/podman/system/context.go
- docs/source/markdown/podman-system-connection-list.1.md
- pkg/rootless/rootless_linux.c
- test/system/001-basic.bats
- test/system/272-system-connection.bats
Alias
podman context use -> podman system connection default
podman context rm -> podman system connection rm
podman context create -> podman system connection add
podman context ls ->podman system connection ls
Podman context is a hidden command, but can be used for existing scripts
that assume Docker under the covers.
```release-note
podman context command is a hidden command available for Docker compatibility.
```
> Add support for podman context as alias to podman system connection

- pkg/domain/infra/tunnel/containers.go
- test/system/030-run.bats
```release-note
Bugfix to podman-remote run --attach stdin does not show container ID
```
closes #15746
> Fix podman-remote run --attach stdin to show container ID

- cmd/podman/secrets/create.go
- docs/source/markdown/podman-secret-create.1.md
- pkg/api/handlers/compat/secrets.go
- pkg/api/handlers/libpod/secrets.go
- pkg/api/server/register_secrets.go
- pkg/bindings/secrets/types.go
- pkg/bindings/secrets/types_create_options.go
- pkg/domain/entities/secrets.go
- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/tunnel/secrets.go
- test/apiv2/50-secrets.at
- test/e2e/secret_test.go
Add --label/-l label flag to secret create, and show labels when inspecting secrets. Also allow labeling secrets via libpod/compat API.
```release-note
Secrets now support labels on creation via the --label/-l flag or via API params. 
```
> Add labels to secrets

- docs/source/markdown/podman-generate-systemd.1.md
- pkg/systemd/generate/containers.go
- pkg/systemd/generate/containers_test.go
- pkg/systemd/generate/pods.go
- pkg/systemd/generate/pods_test.go
- test/e2e/generate_systemd_test.go
Fixes: https://github.com/containers/podman/issues/14897
Followup to #13814
```release-note
podman systemd generate output has been improved by adding newlines on options in the unit files.
```
> Improve generate systemd format

- Makefile
install.tools target broke a few weeks ago because it was fetching something @latest.
We can't use 'go install' nor 'got get ...@version' on this branch, so just delete the .gitvalidation steps entirely.
[manual cherry-pick of #15860]
```release-note
None
```
> [v3.4.2-rhel] fix build

- Makefile
[Manual cherry-pick of #15860]
install.tools target broke a few weeks ago because it was fetching something @latest.
We can't use 'go install' nor 'got get ...@version' on this branch, so just delete the .gitvalidation steps entirely.
```release-note
None
```
> [v3.3.1-rhel] fix build

- Makefile
install.tools target broke a few weeks ago because it was fetching something @latest.
We can't use 'go install' nor 'got get ...@version' on this branch, so just delete the .gitvalidation steps entirely.
[Manual cherry-pick of #15860, with minor conflict resolution]
```release-note
None
```
> [v3.2.3-rhel] fix build

- Makefile
install.tools target broke a few weeks ago because it was fetching something @latest.
We can't use 'go install' nor 'got get ...@Version' on this branch, so just delete the .gitvalidation steps entirely.
[hand-edited to mimic #15860. Could not cherry-pick, too many conflicts]
```release-note
None
```
> [v3.0.1-rhel] fix build

- pkg/bindings/generator/generator.go
- pkg/bindings/images/build.go
- pkg/bindings/test/auth_test.go
- pkg/bindings/test/common_test.go
- test/e2e/libpod_suite_test.go
- test/e2e/secret_test.go
Somehow these crept in or were missed by my grep.
Ref: https://github.com/containers/podman/pull/15871
Fixes: #15889
```release-note
Replace additional usage of io/ioutil (deprecated as of golang 1.16)
```
> Fix a few missed io/ioutil -> os updates

- test/system/030-run.bats
- test/system/075-exec.bats
- test/system/260-sdnotify.bats
- test/system/410-selinux.bats
Background: in order to add aarch64 tests, we had to add
emergency skips to a lot of failing tests. No attempt was
ever made to understand why they were failing.
Fast forward to today, I filed #15888 just to see if tests
are still failing. Looks like a number of them are fixed.
(Yes, magically). Remove those skips.
See: #15074, #15277
```release-note
None
```
> System tests: reenable some skipped aarch64 tests

- cmd/podman/images/save.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- test/e2e/save_test.go
Allow overwrite of the signature-policy file
similiar to other cli commands: podman load, podman pull, ...
Closes: https://github.com/containers/podman/issues/15869
Signed-off-by: 😎Mostafa Emami <mustafaemami@gmail.com>
```release-note
podman save supports `--signature-policy` flag
```
> podman-save: Add signature-policy flag

- pkg/domain/infra/abi/terminal/sigproxy_commn.go
- pkg/domain/infra/tunnel/containers.go
- pkg/domain/infra/tunnel/runtime.go
- pkg/signal/signal_common.go
- pkg/signal/signal_common_test.go
- pkg/signal/signal_linux.go
- pkg/signal/signal_linux_mipsx.go
- pkg/signal/signal_unix.go
- pkg/signal/signal_unsupported.go
- test/system/032-sig-proxy.bats
closes #14707 
```release-note
None
```
> Add support to sig-proxy for podman-remote

- contrib/pkginstaller/scripts/postinstall
- contrib/pkginstaller/scripts/preinstall
path_helper(8) appends the contents of /etc/paths.d/podman-pkg to the PATH env
```release-note
None
```
Fixes #15831 
This makes use of the solution suggested by @cfergeau in https://github.com/containers/podman/issues/15831#issuecomment-1249117498
> pkginstaller: use path_helper to add podman and helpers to path

- libpod/events.go
- libpod/events/config.go
- libpod/events/events.go
- libpod/events/journal_linux.go
- pkg/domain/entities/events.go
- test/apiv2/27-containersEvents.at
- test/e2e/events_test.go
This allows tools like Cockpit to know that the pod in question has also been updated, so they can refresh the list of containers in the pod.
Fixes #15408
```release-note
Events for containers that are part of a pod now include the ID of the pod.
```
> Events for containers in pods now include the pod's ID

- libpod/container.go
Backport of #15799 to v4.2.0-rhel for https://bugzilla.redhat.com/show_bug.cgi?id=2126697
```release-note
NONE
```
> [v4.2.0-rhel] Backport #15799

- cmd/podman/secrets/inspect.go
- docs/source/markdown/podman-secret-inspect.1.md
- test/e2e/secret_test.go
Pretty-print podman secret inspect output in a human-readable format
```release-note
Podman secret inspect now has a --pretty flag for human readable output
```
> Add --pretty to podman secret inspect

- hack/libsubid_tag.sh
Library arguments must be positioned after sources when invoking GCC.
```release-note
None
```
> Fix libsubid detection

- pkg/domain/infra/abi/play.go
- pkg/systemd/notifyproxy/notifyproxy.go
See the messages of the two commits.
```release-note
Fix a bug in the sd-notify integration of `kube play` where a READY message from a container may get lost.
```
> kube: notifyproxy: fix lost READY message

- docs/source/markdown/podman-system-service.1.md
Fixes: https://github.com/containers/podman/issues/15923
```release-note
None
```
> [CI:DOCS] man pages: fix incorrect title

- contrib/cirrus/runner.sh
At the time of this commit, there's no easier way to detect this using `golangci-lint` or the go tool (that I could find).
```release-note
None
```
> [CI:BUILD] Cirrus: Catch use of deprecated ioutils package

- docs/source/markdown/.gitignore
- docs/source/markdown/options/sig-proxy.md
- docs/source/markdown/podman-attach.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-start.1.md.in
Unusually, I discarded the podman-run version and went with
the one common to attach and start. (The defaults are left
out of the common file, because 'start' is different by
necessity). Please review extra-carefully to make sure
the new wording applies to podman-run, in particular
the "non-TTY mode" words.
```release-note
```
> [CI:DOCS] Man pages: Refactor common options: --sig-proxy

- contrib/podmanremoteimage/Containerfile
- contrib/podmanremoteimage/README.md
Try to partial address #14664
```release-note
- Add container file to build remote binary for each platform
- Add README.md file around same
```
Longer term plan is to have it attach either to quay and add github trigger to generate the image for each 4.x tag/branch. Only issue is as of now quay github trigger can only generate `amd64` images not the `arm64` one so may be we need to attach it to current cirrus CI to generate image for different arch and push to quay, same way we are doing for `quay.io/containers/podman`.
Another gap is created binaries for mac/windows are not signed one and we need to check if user try to copy those binary from the container image does it showing the signing warning.
> [CI:BUILD] Contrib: Add containerfile to create podman-remote binary image

- docs/source/markdown/options/env.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only among podman create, exec, run. The same option in
podman build, generate-systemd, and secret-create is too
different.
Should be a trivial one to review, the only difference is
a period at the end of one sentence. And, of course, the
"See Environment note" applies only to podman-create and
run, not exec, so it can't be deduplicated.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --env

- pkg/api/handlers/compat/networks.go
- test/compose/uptwice/docker-compose.yml
- test/compose/uptwice/teardown.sh
- test/compose/uptwice/tests.sh
We force the isolate option on new newtworks because that is the docker behavior. However when we inspect them they should not be displayed to the caller since they have no idea about it and docker-compose throws an error because of that.
Fixes #15580
```release-note
Fixed a bug in the network inspect compat api where an incorrect network option was displayed which caused problems for docker-compose.
```
> compat API: network inspect do not show isolate option

- docs/source/markdown/options/env-file.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
Another easy one. Option is only present in these three man pages.
I took the liberty of changing the "See note" text, making it
the same as --env. I also took the liberty of hyphenating
"line-delimited" because that's the correct thing to do.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --env-file

- cmd/podman/machine/ssh.go
- cmd/podman/root.go
- cmd/podman/system/connection/list.go
- go.mod
- go.sum
- pkg/bindings/connection.go
- pkg/domain/entities/engine.go
- pkg/domain/infra/runtime_abi.go
- pkg/domain/infra/runtime_tunnel.go
- pkg/machine/connection.go
- pkg/machine/e2e/basic_test.go
- pkg/machine/qemu/machine.go
- vendor/github.com/containers/common/libimage/platform.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/ssh/connection_golang.go
- vendor/github.com/containers/common/pkg/ssh/types.go
- vendor/github.com/containers/common/pkg/ssh/utils.go
- vendor/modules.txt
add the key used in newly initialized machines to the user's known_hosts file. This ensures that golang will be able to ssh into the machine using
podman-remote. Also, remove the /dev/null redirection for podman machine ssh's known_hosts file.
resolves #15347
```release-note
introduce the new ssh interface to podman machine, initializing new keys properly, and warning users about the upcoming change.
```
> podman machine ssh handling

- cmd/podman/machine/list.go
Machine starting now is correctly displayed on podman machine list --format json
```release-note
Machine starting now is correctly displayed on podman machine list --format json
```
> Fix machine starting state

- .cirrus.yml
Build unsigned pkginstaller in OSX Cross CI task & upload as an artifact.
```release-note
None
```
> Cirrus: Build pkginstaller in CI

- Makefile
- contrib/cirrus/setup_environment.sh
- hack/install_golangci.sh
Reintroduce .install.foo targets into Makefile, and invoke
only the bare-minimum ones needed for each individual CI
step in setup_environment.sh.
Also add a retry to the golangci-lint curl, in hopes of
dealing with network flakes. And remove the -f (fail)
because it produces unhelpful logs.
Reason: saw about 25% CI flakes yesterday due to the golangci-lint
fetch, something about a timeout, and this was especially frustrating
because none of the steps actually needed lint. Quick reminder:
avoid network fetches unless absolutely necessary.
Fixes: #15892
```release-note
None
```
> CI: only make install.tools when needed

- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/play_test.go
- When a pod with HTTP liveness probe is created using podman kube play, ensure the [Kubernetes defaults values](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes) are respected. 
- Additional curl parameter enforces returning error for HTTP error codes. 
- Uses build-in HealthCheckOnFailureAction instead of killing the container while executing the probe.
Fixes #15855 
```release-note
None
```
> fix: liveness check with http probe

- test/system/030-run.bats
Followup to #15895:
- add a normal-case test, to ensure that --privileged without
systemd continues to pass through /dev/ttyN devices
- explain why we die() if host has no ttyN devices
- I find grep -vx slightly easier to read than sed backslash-slash
- run cleanup with '-t 0', to shave ten seconds from CI run
```release-note
None
```
> System tests: light cleanup

- docs/source/markdown/options/device.md
Fixes: https://github.com/containers/podman/issues/15930
```release-note
Update man pages to describe SELinux boolean for use of system devices.
```
> [CI:DOCS] Add SELinux information about boolean for using random devices

- cmd/podman/common/completion.go
- cmd/podman/common/create.go
- docs/source/markdown/podman-create.1.md
- docs/source/markdown/podman-run.1.md
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/container_inspect.go
- libpod/define/healthchecks.go
- libpod/healthcheck.go
- libpod/options.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/system/220-healthcheck.bats
- test/system/250-systemd.bats
- test/system/helpers.bash
For systems that have extreme robustness requirements (edge devices, particularly those in difficult to access environments), it is important that applications continue running in all circumstances. When the application fails, Podman must restart it automatically to provide this robustness. Otherwise, these devices may require customer IT to physically gain access to restart, which can be prohibitively difficult.
Add a new `--on-failure` flag that supports four actions:
- **none**: Take no action.
- **kill**: Kill the container.
- **restart**: Restart the container.  Do not combine the `restart` action with the `--restart` flag.  When running inside of a systemd unit, consider using the `kill` or `stop` action instead to make use of systemd's restart policy.
- **stop**: Stop the …
> [v4.1.1-rhel] health check: add on-failure actions

- libpod/container.go
Backport of GH PR #15799 to v4.1.1-rhel branch per RHBZ 2130237
Signed-off-by: Matthew Heon <mheon@redhat.com>
```release-note
NONE
```
> [v4.1.1-rhel] Backport #15799

- pkg/k8s.io/api/core/v1/types.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/play_test.go
Follow-up on the [15958](https://github.com/containers/podman/pull/15958).
- When a pod with HTTP liveness probe is created using podman kube play, ensure the [Kubernetes defaults value for path](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes) is set correctly.
- Update the URI scheme to use lowercase and use this value in code (not used otherwise, URI are lowercase)
Fixes #15855 for the final parameter. I am sorry that I missed this in the original pull request.
```release-note
None
```
> fix: kube play liveness probe http path

- contrib/cirrus/check_go_changes.sh
- contrib/cirrus/runner.sh
Cirrus: Add golang code consistency check script
Depends on #15893
Fixes: #15913
```release-note
None
```
> [CI:BUILD] Check new go code

- test/system/001-basic.bats
I was testing --log-level by --storage-opt=mount_program=/bin/false
Stop doing that. It's just constantly breaking everything (#15698
and #15977).
I am violently of the opinion that a command-line option must
not destroy a user's system (except for --set-something, --config,
something that makes it very very clear that it is a lasting
change). I seem to be in the minority on this opinion. So, I
give up.
```release-note
None
```
> System tests: stop deep-checking log-level

- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_add_options.go
- pkg/bindings/manifests/types_modify_options.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
* `manifest add --annotation option` adds annotations field on remote environment.
* `manifest inspect` prints annotations field on remote environment.
Fixes: #15952
```release-note
Now manifest add --annotation option adds annotations field and
manifest inspect prints annotations field on remote environment.
```
> remote: fix manifest add --annotation

- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_add_options.go
- pkg/bindings/manifests/types_modify_options.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
This reverts commit 32f54a81ed797597827123b671b6e73194354327.
`pkg/bindings` is supported outside of podman and we have to keep it stable.
```release-note
None
```
> Revert "remote: fix manifest add --annotation"

- docs/source/markdown/options/log-opt.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-run.1.md.in
Simple in reality, but hard to review due to lots of little diffs:
- "Logging driver specific options" was only in podman-run; I added it
to create and kube-play.
- whitespace changes, the 'e.g.'s got consistent 4-space indentation
- the "same keys" and "supported only" sentences, I moved up to be
closer to **tag** and without intervening whitespace, because they
were unclear as they were: I believe the intent is to apply those
sentences only to **tag**, not to the **--log-opt** option itself.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --log-opt

- test/e2e/network_test.go
- test/e2e/prune_test.go
Since by default the network config dir is shared in the e2e tests any
other parallel running test could remove a network and cause this test to
fail.
Fixes #15990
```release-note
None
```
> fix "podman system prune networks" flake

- docs/source/markdown/options/network.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-kube-play.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- pkg/domain/infra/abi/play.go
- test/system/700-play.bats
I see no reason to block --network host with kube play and force users to have to set it in the yaml file.
This is just confusing when compared to the other podman create/run --network options, see discussion in #15945.
Second commit is cherry-picked from #15945 to make sure code and docs stay consistent.
```release-note
Allow podman kube play --network host. 
```
> podman kube play allow --network host

- pkg/api/handlers/libpod/containers.go
- pkg/api/server/register_containers.go
- test/e2e/checkpoint_test.go
restore endpoint was totally ignoring --pod, it was missing from the schema and from query handling on the api handlers side. add support for it here.
resolves #15018
```release-note
podman-remote restore now supports --pod properly
```
> fix restore API endpoint

- cmd/podman/containers/restore.go
- cmd/podman/containers/run.go
- cmd/podman/utils/utils.go
- test/e2e/checkpoint_image_test.go
This pull request extends the podman run command with support for checkpoint images. When `podman run` is invoked with an image that contains a checkpoint, it would restore the container from that checkpoint.
Example:
```
podman run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
podman container checkpoint --create-image checkpoint-image-1 looper
podman rm looper
podman run checkpoint-image-1
```
```release-note
The `podman run` command has been extended with support for checkpoint images.
```
> cmd/podman: add support for checkpoint images

- test/e2e/kill_test.go
- test/e2e/restart_test.go
* podman stop --all -> podman kill --all
* podman pause --filter -> podman restart --filter
```release-note
None
```
> Fix typo about e2e tests name

- contrib/podmanimage/README.md
Fixes: https://github.com/containers/podman/issues/15989
```release-note
None
```
> [CI:DOCS] Add quay-description update reminder

- docs/source/markdown/options/sign-passphrase-file.md
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
Trivial one: no human intervention needed, the man page text
was already identical between both files.
```release-note
```
> [CI:DOCS] Man pages: Refactor common options: --sign-passphrase-file

- libpod/container_inspect.go
- libpod/define/container_inspect.go
- test/system/030-run.bats
Include the digest of the image in `podman container inspect`. The image digest is a key information for auditing as it defines the identify of an image.  This way, it can be determined whether a container used an image with a given CVE etc.
```release-note
container inspect: include image digest
```
@baude PTAL
> container inspect: include image digest

- .github/ISSUE_TEMPLATE.md
Just a quick little addition to provide the command to get the package info from homebrew for those who might not know. I've added this as a CI:DOCS PR because there's no functional changes, even though it's not specifically docs.
Thanks for your time!
```release-note
None
```
> [CI:DOCS] Adds brew info podman to issue template.

- libpod/networking_linux.go
We should not keep the netns if there was a cleanup problem. Deleting the netns will also delete the virtual links inside and thus make the IPs available again for the next use.
context: https://github.com/containers/netavark/issues/302
[NO NEW TESTS NEEDED] This is very hard to trigger reliable and it would need to work with cni and netavark. This mostly happens because of specic bugs but those will be fixed and then this test would fail.
```release-note
The network namespace cleanup is now always removed even when the network teardown in CNI/netavark fails.
```
> cleanup: always delete netns mount

- cmd/podman/pods/logs.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/network.go
- test/e2e/logs_test.go
Fixed issue where executing the command `podman pod logs -l` would panic because it was indexing into an empty arguments array.
Fixes: #15556
```release-note
Fixes bug where executing `podman pod logs -l` would panic
```
> `podman pod logs -l` no longer panics

- docs/source/markdown/options/compression-format.md
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
Easy one: text was already identical across both files.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --compression-format

- contrib/cirrus/check_go_changes.sh
When running on a branch or tag, `req_env_vars()` will call `exit(1)` because `$CIRRUS_PR` is empty (as expected).  The original intention was to simply skip language checks on non-PRs.  Fix the condition to match.
```release-note
None
```
> [CI:BUILD] Cirrus: Fix tag & branch go checks failing

- docs/source/markdown/.gitignore
- docs/source/markdown/options/variant.container.md
- docs/source/markdown/options/variant.manifest.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-annotate.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-run.1.md.in
Two different texts, split into two .md files. Nontrivial, but still easy to review because the text is unchanged.
I was unable to reconcile either version with podman-build, so that file remains with a separate version.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --variant

- pkg/api/handlers/compat/images.go
Trying to print the image id on a failed inspect will result in a nil pointer panic because the image will be nil.  Replace image.id with the image name which is defined as a string without the use of inspect.
Fixes: bz#2131836
```release-note
Fixes: Bz#2131836 Nil pointer deref
```
> Prevent nil pointer deref in GetImage

- docs/source/markdown/options/features.md
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-annotate.1.md.in
Easy one: text was already identical between both files.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --features

- docs/source/markdown/podman-kube-play.1.md.in
- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
In order to allow pods to reach other pods (as in Kubernetes) they all need to be added to the same network. A network is created (if it doesn't exist) and pods created by play-kube are added to that network. When network options are passed to kube command the pods are not attached to the default kube network.
Signed-off-by: Andrei Natanael Cosma <andrei@intersect.ro>
```release-note
Behavior of play-kube is changed to create a network (podman-kube) if it doesn't exists and adds pods created by kube-play to that network, which allows pods to reach other pods - as in Kubernetes.
```
It partially overlaps with #12965
> Add pods created by play kube to a default network

- docs/source/markdown/options/pod.run.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only between podman-create and -run; the other meanings of --pod are too different. This almost didn't feel worth refactoring, except the podman-run version fixed a word and added a possibly important note about infra containers. I went with the podman-run version.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --pod

- docs/source/markdown/.gitignore
- docs/source/markdown/options/time.md
- docs/source/markdown/podman-pod-rm.1.md.in
- docs/source/markdown/podman-pod-stop.1.md.in
- docs/source/markdown/podman-restart.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-stop.1.md.in
Only in container/pod stop/rm/restart man pages; the others
(volume-rm, network-rm, system-service) are too different to refactor.
Mostly an easy one, no manual reconciliation needed apart from
the pod-vs-container difference.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --time

- .cirrus.yml
As discussed in f2f: this is the cleanest, simplest mechanism
I can think of to auto-test the Big Three dependencies: simply
run go mod edit immediately after git checkout, then run the
entire CI test suite.
If this approach works, we can set up a new CIRRUS_CRON=treadmill
job. I'm expecting it not to work, because Murphy, but want to
see what the unexpected gotchas are.
This differs significantly from the buildah treadmill, in that
buildah is almost impossible to re-vendor without manual intervention.
(In practice, so are these, but let's dream of a world in which
this will run and pass every night). (I want a pony too).
```release-note
None
```
> Proof of concept: nightly dependency treadmill

- cmd/podman/system/service_abi.go
- test/system/251-system-service.bats
If `tcp` or `unix` are missing from the URI `podman` panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x13fe9a1]
goroutine 1 [running]:
github.com/containers/podman/v4/pkg/api/server.newServer(0xc000296540, {0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x7ffca77de322, 0xe}})
/home/b0/go/src/github.com/boaz0/podman/pkg/api/server/server.go:65 +0x41
github.com/containers/podman/v4/pkg/api/server.NewServerWithSettings(...)
/home/b0/go/src/github.com/boaz0/podman/pkg/api/server/server.go:61
github.com/containers/podman/v4/cmd/podman/system.restService(0x7ffca77de322?, 0xe?, {{0x0, 0x0}, {0x0, 0x0}, 0x0, {0x7ffca77de322, 0xe}})
/home/b0/go/src/github.com/boaz0/podman/cmd/podman/system/service_abi.go:11 …
```
> Return error in podman system service if URI scheme is not unix/tcp

- pkg/specgen/generate/kube/volume.go
- test/e2e/play_kube_test.go
Consider empty directory /root and the following piece of Pod yaml:
```
volumes:
- name: my-sub-dir
hostPath:
path: /root/dir/subdir
type: DirectoryOrCreate
```
Podman failed to play such Kube with error:
```
error playing YAML file: failed to create volume "my-sub-dir": mkdir /root/dir/subdir: no such file or directory
```
k8s sources: [one](https://github.com/elastisys/kubernetes/blob/6ce065dec0780e014c471f42dcd973d72540459c/pkg/volume/hostpath/host_path.go#L440), [two](https://github.com/kubernetes/kubernetes/blob/fbb6ccc0c62d2431dc3a18a4130d7fbae5c05acd/pkg/volume/hostpath/host_path.go#L493)
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>
```release-note
Create a full path to a directory when DirectoryOrCreate is used with play kube
```
> Create a full path to a directory when DirectoryOrCreate is used

- CONTRIBUTING.md
Adds a small bit of text and a link to the OSX page for MacOS devs who might otherwise think we can't build anything locally.
No
```release-note
None
```
> [CI:DOCS] MacOS contributing docs link

- pkg/domain/infra/abi/pods.go
We have a test to verify that init containers in pods are deleted when the `--init-ctr=once` option is specified. The test creates two containers, one of them an init container, starts the pod, stops the pod, and restarts the pod, checking for the presence of a file created by the init container during the second start. We're seeing a race where the file still exists, which I'm fairly certain comes down to the SHM mount not being cleaned up after the pod is stopped.
Fortunately, we already have code to do this - just flip the bool that controls cleanup from false to true.
[NO NEW TESTS NEEDED] Fixes a difficult to reproduce race condition.
Fixes #16046
```release-note
NONE
```
> Clean up when stopping pods

- libpod/runtime.go
When shutting down the image engine we always wait for the image even goroutine to finish writing any outstanding events. However, the loop for that always waits 100msec every iteration. This means that (depending on the phase) shutdown is always delayed up to 100msec.
This is delaying "podman run" extra much because podman is run twice (once for the run and once as cleanup via a conmon callback).
Changing the image loop to exit immediately when a libimageEventsShutdown (but first checking for any outstanding events to write) improves podman run times by about 100msec on average.
> libpod: Remove 100msec delay during shutdown

- libpod/healthcheck.go
- test/system/220-healthcheck.bats
- test/system/250-systemd.bats
Make sure that the on-failure actions only kick in once the health check has passed its retries.
```release-note
Make sure that the on-failure actions only kick in once the health check has passed its retries.
```
@mheon PTAL
> health checks: make on-failure action retry aware

- cmd/podman/inspect/inspect.go
- docs/source/markdown/podman-volume-create.1.md
- go.mod
- go.sum
- libpod/boltdb_state_internal.go
- libpod/define/volume_inspect.go
- libpod/options.go
- libpod/plugin/volume_api.go
- libpod/runtime.go
- libpod/runtime_volume_linux.go
- libpod/volume.go
- libpod/volume_inspect.go
- pkg/domain/infra/abi/parse/parse.go
- test/e2e/config/containers.conf
- test/e2e/volume_plugin_test.go
- test/testvol/util.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Backport #15437 (plus supporting commit 7b3e43c1f6cf27a1cde96c0f650a793a56cebc4c) to v4.1.1-rhel per https://bugzilla.redhat.com/show_bug.cgi?id=2132814
```release-note
NONE
```
> [v4.1.1-rhel] Backport #15437

- go.mod
- go.sum
- libpod/define/volume_inspect.go
- libpod/options.go
- libpod/plugin/volume_api.go
- libpod/runtime.go
- libpod/runtime_volume_linux.go
- libpod/volume.go
- libpod/volume_inspect.go
- pkg/domain/infra/abi/parse/parse.go
- test/e2e/config/containers.conf
- test/e2e/volume_create_test.go
- test/e2e/volume_plugin_test.go
- test/testvol/util.go
- vendor/github.com/containers/common/libimage/load.go
- vendor/github.com/containers/common/libnetwork/cni/network.go
- vendor/github.com/containers/common/libnetwork/network/interface.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Backport #15437 to v4.2.0-rhel per RHBZ 2125241
```release-note
NONE
```
> [v4.2.0-rhel] Backport #15437

- pkg/api/handlers/compat/images.go
Trying to print the image id on a failed inspect will result in a nil pointer panic because the image will be nil. Replace image.id with the image name which is defined as a string without the use of inspect.
Fixes: bz#2131836
```release-note
Fixes: Bz#2131836 Nil pointer deref
```
> [v4.1.1-rhel] Prevent nil pointer deref in GetImage

- libpod/container_api.go
When you run "podman run foo" we attach to the container, which essentially blocks until the container process exits. When that happens podman immediately calls Container.WaitForExit(), but at this point the exit value has not yet been written to the db by conmon. This means that we almost always hit the "check for exit state; sleep 250msec" loop in WaitForExit(), delaying the exit of podman run by 250 msec.
More recent kernels (>= 5.3) supports the pidfd_open() syscall, that lets you open a fd representing a pid and then poll on it to wait until the process exits. We can use this to have the first sleep be exactly as long as is needed for conmon to exit (if we know its pid). If for whatever reason there is still issues we use the old sleep loop on later iterations.
This makes "time …
> Avoid unnecessary timeout of 250msec when waiting on container shutdown

- libpod/container_internal.go
- test/system/220-healthcheck.bats
Fix the "stop" on-failure action by not removing the transient systemd timer and service during container stop.  Removing the service will in turn cause systemd to terminate the Podman process attempting to stop the container and hence leave it in the "stopping" state.
Instead move the removal into the restart sequence.
```release-note
Fix the "stop" on-failure action for health checks.
```
> [v4.2.0-rhel] healthcheck: fix --on-failure=stop

- libpod/container.go
- libpod/container_api.go
- libpod/kube.go
- libpod/oci_conmon_common.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/terminal/terminal_common.go
This just gets ctr.config.Spec.Process.Terminal with some null checks, allowing several places that open-coded this to use the helper.
In particular, this helps the code in
pkg/domain/infra/abi/terminal.StartAttachCtr(), that used to do: `ctr.Spec().Process.Terminal`, which looks fine, but actually causes a deep json copy in the `ctr.Spec()` call that takes over 3 msec.
> Add and use libpod/Container.Terminal() helper

- test/system/250-systemd.bats
Basically, in the timeout loop where we checked for new CID
on the restarted container, we were running 'podman inspect'
(not 'inspect --format ID'), and comparing full hundred-line
output against single-line CID string.
While I'm in here, add 'c_' prefix to container to make it
easier for my old eyes to recognize "oh, that's a container name"
vs "is that a name? a SHA? a woozle?"
Fixes: #16075 
```release-note
None
```
> system tests: health-on-failure: fix broken logic

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/add.go
- vendor/github.com/containers/buildah/buildah.go
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/imagebuildah/util.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
Bump buildah to `v1.19.11` so it contains fix for https://github.com/advisories/GHSA-rc4r-wh2q-q6c4
Followup after: https://github.com/containers/podman/pull/16122
Closes: https://github.com/containers/buildah/issues/4307
```release-note
vendor: bump buildah to v1.19.11
```
> [release-v3.0.1-rhel] vendor: bump buildah to `v1.19.11`

- docs/source/markdown/options/os-version.md
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-annotate.1.md.in
Only between the two podman-manifest-* commands. podman-build
is too different.
Easy one, text was already identical
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --os-version

- libpod/container.go
- libpod/kube.go
- libpod/oci_conmon_linux.go
- libpod/stats_freebsd.go
- libpod/stats_linux.go
- pkg/api/handlers/compat/containers_stats.go
- pkg/domain/filters/containers.go
- pkg/domain/infra/abi/system.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/storage.go
As mentioned in https://github.com/containers/podman/pull/16117 there are more places in the codebase where we unnecessarily call these expensive functions. This removes a bunch of them by calling existing or new accessors, or in some cases by using .ConfigNoCopy() instead.
@vrothberg
> Avoid unnecessary calls to Container.Config() and Container.Spec()

- pkg/systemd/notifyproxy/notifyproxy.go
Starting listening for the READY messages on the sdnotify proxies before starting the Pod.  Otherwise, we may be missing messages.
[NO NEW TESTS NEEDED] as it's hard to test this very narrow race.
Related to but may not be fixing #16076.
```release-note
Fix a potential race condition in play kube's sdnotify support.
```
> play kube: notifyproxy: listen before starting the pod

- libpod/oci_conmon_common.go
To improve the error message reported in #16142 where the container is reported to be in the wrong state but we do not know which.  This is not a fix for #16142 but will hopefully aid in better understanding what's going on if it flakes again.
[NO NEW TESTS NEEDED] as hitting the condition is inherently racy.
```release-note
Improve an error message when killing a container.
```
> KillContainer: improve error message

- docs/source/markdown/options/annotation.manifest.md
- docs/source/markdown/podman-manifest-add.1.md.in
- docs/source/markdown/podman-manifest-annotate.1.md.in
[Note: I already refactored --annotation for container-related
commands; this one is for manifest-related commands]
This one needed reconciling: one man page said "newly added image",
the other said "specified image", I just reduced that to "image".
If that's not cool, any suggestions on how to make it better? Or,
just reject this PR, we can live with this duplication.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --annotation (manifest)

- docs/source/markdown/options/attach.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
Only between podman-create and -run; podman-start was too
different. (But please look into it, maybe there's a way
to reconcile the diffs).
Very minor formatting changes made to reconcile the two.
Easy to review using hack/markdown-preprocess-review
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --attach

- docs/source/markdown/options/detach-keys.md
- docs/source/markdown/podman-attach.1.md.in
- docs/source/markdown/podman-exec.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman-start.1.md.in
Refactored among all files that mentioned it.
DANGER WILL ROBINSON! REVIEW CAREFULLY! Here are two major
decisions I made:
1) Look at the text for podman-run, in particular the "" text.
It currently says "will use the default". As best I can
tell this is not true, so I changed it to "will disable"
which matches all the other commands.
2) The "containers.conf" text, I decided, applies to all
commands, not just podman-run (it was only present in
podman-run). If this is not the case, please yell.
Other changes are cosmetic formatting stuff, asterisks end newlines.
Hard to review with hack/markdown-preprocess-review, because all
the text is one horrible long line instead of 80-char breaks.
```release-note
```
> [CI:DOCS] Man pages: Refactor common options: --detach-keys

- hack/tree_status.sh
Print the diff at the end of the report to help better understand what's going on.
```
tree is dirty, please run "make vendor" and commit all changes.
M go.mod
M go.sum
M hack/tree_status.sh
M vendor/github.com/containers/storage/store.go
M vendor/modules.txt
---------------------- Diff below ----------------------
diff --git a/go.mod b/go.mod
index e36d3fb95c57..167d769c378f 100644
--- a/go.mod
+++ b/go.mod
@@ -17,7 +17,7 @@ require (
github.com/containers/image/v5 v5.23.0
github.com/containers/ocicrypt v1.1.6
github.com/containers/psgo v1.7.3
-       github.com/containers/storage v1.43.1-0.20221013143630-714f4fc6e80e
+       github.com/containers/storage v1.43.1-0.20221014072257-a144fee6f51c
github.com/coreos/go-systemd/v22 v22.4.0
github.com/coreos/stream-metadata-go …
```
> hack/tree_status.sh: print diff at the end

- libpod/container_api.go
- libpod/container_internal.go
- test/e2e/attach_test.go
Make sure to wait for the container to exit after kill. While the cleanup process will take care eventually of transitioning the state, we need to give a guarantee to the user to leave the container in the expected state once the (kill) command has finished.
The issue could be observed in a flaking test (#16142) where `podman rm -f -t0` failed because the preceding `podman kill` left the container in "running" state which ultimately confused the "stop" backend.
Note that we should only wait for the container to exit when SIGKILL is being used.  Other signals have different semantics.
[NO NEW TESTS NEEDED] as I do not know how to reliably reproduce the issue.  If #16142 stops flaking, we are good.
Fixes: #16142
```release-note
Fix a …
```
> kill: wait for the container

- CONTRIBUTING.md
Seems helpful to mention here that only the client can be built directly on MacOSX.
Signed-off-by: Jesse Lang <jesse@jesselang.com>
```release-note
None
```
> [CI:DOCS] Clarify that MacOSX docs are client specific

- .cirrus.yml
ref: https://github.com/containers/podman/pull/16167
According to Cirrus-support, defining and using `$CIRRUS_DEFAULT_WORK`
is responsible for causing a strange race condition on windows.  This is
impacting the agent's ability to clone with errors like:
```
Using built-in Git...
Cloning refs/heads/main...
Failed to clone: read ${CIRRUS_DEFAULT_WORK}\.git\HEAD: The process
cannot access the file because another process has locked a portion of
the file.!
```
Fix this by hard-coding a work directory for this windows task.
```release-note
None
```
> [CI:DOCS] Cirrus: Fix win installer task

- .cirrus.yml
- Makefile
- contrib/cirrus/setup_environment.sh
- hack/install_golangci.sh
- hack/install_swagger.sh
*Depends on:* #16169 
Support swagger testing and optional runtime updates similar to the current golangci-lint tool.  This allows developers to update the version of swagger at runtime if needed.  Otherwise new CI VM images will pick up the prescribed version at image build-time via `make install.tools`.
```release-note
None
```
> [CI:DOCS] Add swagger install + allow version updates in CI

- go.mod
- go.sum
- test/system/150-login.bats
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/errors.go
- vendor/github.com/containers/image/v5/oci/archive/oci_src.go
- vendor/github.com/containers/image/v5/oci/layout/oci_src.go
- vendor/github.com/containers/image/v5/oci/layout/oci_transport.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
```release-note
None
```
Update c/image from a WIP https://github.com/containers/image/pull/1299:
- to eventually benefit from the better error messages
- for now, to exercise that PR to find issues, if any
- for now, to see if any Podman tests need adjusting.
> Update for https://github.com/containers/image/pull/1299 + update tests

- pkg/bindings/images/pull.go
- pkg/bindings/images/push.go
- pkg/bindings/manifests/manifests.go
I discovered that an image pull could end up in infinite recursion if the context is cancelled while pulling. The reason is that the `break` statement only breaks the `select` instead of the `for`.  
I found a few other places in `pkg/bindings` that also seemed to have the same issue, which I included a fix for. The solution is to put a label at the `for` loop and reference that when breaking in the cases for `pull.go` and `push.go`. In `manifests.go` there were no return statement outside of the `for` loop so I opted to return an empty string along with the error `context.Canceled`. 
```release-note
Prevent OOM when context is cancelled in a few situations 
```
> Change to correct break statements to prevent infinite recursion causing OOM

- pkg/systemd/generate/containers.go
- pkg/systemd/generate/containers_test.go
Make sure to always the stop timeout for unit generated via `--new`.
Fixes: #16149
```release-note
Fix `generate systemd --new` to set the --stop-timeout for stopping containers
```
> generate systemd: set --stop-timeout for stopping containers

- pkg/rootless/rootless_linux.c
Fixes: https://github.com/containers/podman/issues/15927
```release-note
None
```
> rootless: fix return value handling

- docs/source/markdown/podman-kube-play.1.md.in
- hack/markdown-preprocess
- hack/markdown-preprocess.t
"It'll be easy", they said.
This is a two-commit PR: one of them simple and easy to review, the other one
completely bonkers. Please see individual commits. Seriously, you cannot review
this monster as one commit. And please see the warning about nroff. That needs
to be addressed before we can even think of merging this, so I'm marking Draft.
```release-note
generic md-include mechanism, to embed kubernetes_support.md into podman-kube-play man page
```
> [CI:DOCS] markdown-preprocess: add generic include mechanism

- libpod/container_api.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
This allows us to add a simple stub for FreeBSD which returns -1, leading WaitForExit to fall back to the sleep loop approach.
```release-note
None
```
> libpod: Factor out the call to PidFdOpen from (*Container).WaitForExit

- pkg/specgen/generate/storage.go
- pkg/specgen/specgen.go
- pkg/specgen/volumes.go
- pkg/specgenutil/volumes.go
- test/system/160-volumes.bats
Fixes: https://github.com/containers/podman/issues/4217
```release-note
Duplicate volume mounts as long as source and destination match are now allowed.
```
> Allow volume mount dups, iff source and dest dirs

- contrib/podmanimage/stable/podman-containers.conf
Avoids the error "Error: error preparing container xyz... for attach: crun: open /proc/sys/net/ipv4/ping_group_range: Read-only file system: OCI runtime error" when using `podman run --net bridge` inside Podman running without --security-opt unmask=ALL (or 'unmask=/proc/*')
No
```release-note
Set default_sysctls to empty for rootless podman in podman image
```
> [CI:DOCS] Podman image: Set default_sysctls to empty for rootless containers

- podman.spec.rpkg
containers-common now has a new `-extra` subpackage which handles dependencies common to podman and buildah and also depends on the main package `containers-common` itself.
The podman-next copr rebuilds containers-common from the rawhide branch
of dist-git so it will always have the latest version and will also
supersede the official containers-common packages (except on rawhide
where it will be equal).
Fixes: #16137
```release-note
None
```
> [CI:BUILD] copr: podman rpm should depend on containers-common-extra

- docs/source/markdown/podman-systemd.unit.5.md
This adds the "podman-systemd.unit(5)" manpage that describes the podman generators from a high level, and all the supported options.
```release-note
NONE
```
> Add man page for quadlet

- .cirrus.yml
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
- test/minikube/001-kube.bats
- test/minikube/helpers.bash
Install and set up minikube so that we can
create a k8s cluster for testing.
```release-note
None
```
> Set up minikube for k8s testing

- README.md
- RELEASE_NOTES.md
Add release notes, change latest release link.
```release-note
NONE
```
> [CI:DOCS] Update main to reflect v4.3.0 release

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/errors.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Update for https://github.com/containers/image/pull/1695, fixing pushes of signatures to quay.io and reads with sigstore enabled from redhat.io.
Does not tag a new release.
```release-note
Fixes reads/writes of sigstore signatures/attachments in quay.io and registry.redhat.io
```
> [v4.2.0-rhel] Update c/image to 5.22.1

- test/system/260-sdnotify.bats
- test/system/270-socket-activation.bats
gating tests failing on rawhide, and will probably fail on f36 and f37 due to long-broken bugs that are now caught by (bats, I think? new version of bash? who knows).
This is a partial cherry-pick of #16220, omitting the change to testimage (not needed here)
This fixes **some** of the broken gating tests. The rest (#16107, systemd pod cgroups) are beyond my control.
```release-note
Fix broken gating tests
```
> [v4.3] system tests: fix broken bashisms

- Makefile
This isn't useful on FreeBSD since it does not use systemd.
```release-note
None
```
> Makefile: don't install systemd generator binaries on FreeBSD

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/errors.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
```release-note
Fixes reads/writes of sigstore signatures/attachments in quay.io and registry.redhat.io
```
> [v4.3] Update c/image from release-5.23 branch

- pkg/machine/config.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
Safe guards calls to os.RemoveAll in order to prevent calls from accidently deleting the root file system in very strange edge cases. Did this by creating GuardedRemoveAll and migrated machine os.RemoveAll calls to it.
Signed-off-by: Mike Perry <mike@bitbistro.org>
Closes #15858
```release-note
None
```
> Closes: 15858 (podman system reset --force destroy machine)

- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-kube-play.1.md.in
* docs: kube play: mention restart policy
* docs: generate systemd: point to kube template
```release-note
Mention in the docs that "always" is the default restart policy for containers created via `kube play`.
```
> [CI:DOCS] kube refinements

- cmd/podman/system/df.go
- docs/source/markdown/podman-system-df.1.md
- test/e2e/system_df_test.go
Fixed the issue of `--format` and `--verbose` flags being allowed in combination with one another.
Implemented functionality for `--format json` or `--format '{{ json }}' `.
Implemented command-completion help for `--format`.
Fixes: #16204
```release-note
Fixed bug where `--format` and `--verbose` were allowed in the same command. 
Added functionality for `--format json`
Added functionality for command-completion help for `--format`
```
> Fix `system df` issues with `-f` and `-v`

- contrib/cirrus/logcollector.sh
(minor correction to package name)
```release-note
None
```
> [skip ci] logcollector: include aardvark-dns

- docs/source/markdown/podman-ps.1.md
- pkg/domain/filters/containers.go
- test/e2e/ps_test.go
Closes #16180
This PR adds regular expression support the ancestor ps filter by uisng `util.StringMatchRegexSlice` instead of comparing the exact string value.
The same function is used by the `name` filter.
Yes, it adds regular expression support when using the ancestor ps filter, examples:
```
podman ps --filter ancestor=registry.fedoraproject.org/fedora:latest
podman ps --filter ancestor=registry.fedoraproject.org
podman ps --filter ancestor=fedoraproject.*/fedora
```
```release-note
Added: Regular expression support for "podman ps --filter ancestor"
```
> adding regex support to the ancestor ps filter function

- cmd/podman/containers/create.go
- cmd/podman/pods/create.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- pkg/systemd/generate/containers.go
- pkg/systemd/generate/containers_test.go
- pkg/systemd/generate/pods.go
- pkg/systemd/generate/pods_test.go
- pkg/util/utils.go
- test/e2e/generate_systemd_test.go
- test/system/030-run.bats
Truncate the container and pod ID files instead of throwing an error. The main motivation is to prevent redundant work when starting systemd units.  Throwing an error when the file already exists is not preventing races or file corruptions, so let's leave that to the user which in almost all cases are generated (and tested) systemd units.
```release-note
Do not throw an error but truncate existing container/pod ID files.
```
@alexlarsson @containers/podman-maintainers PTAL
> container/pod id file: truncate instead of throwing an error

- pkg/systemd/notifyproxy/notifyproxy.go
The notify proxy has a watcher to check whether the container has left the running state.  In that case, Podman should stop waiting for the ready message to prevent a dead lock.  Fix this watcher but adding a loop.
Fixes the dead lock in #16076 surfacing in a timeout.  The underlying issue persists though.  Also use a timer in the select statement to prevent the goroutine from running unnecessarily long
```release-note
Fix a deadlock in the sdnotify proxy of `kube play`.
```
@edsantiago PTAL.  This does not fix #16076 but hopefully brings us one step closer to solve it.
> notifyproxy: fix container watcher

- docs/source/markdown/podman-kube-play.1.md.in
- libpod/volume.go
- pkg/api/handlers/libpod/kube.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- pkg/util/kube.go
- test/e2e/play_kube_test.go
Add a new annotation to allow the user to point to a local tar file If the annotation is present, import the file's content into the volume Add the annotation to the documentation
Add an E2E test to the new annotation
```release-note
Play Kube - support volume import using a new annotation
```
> play kube: Allow the user to import the contents of a tar file into a volume

- test/system/500-networking.bats
One test was using a hardcoded fixed port, with a comment
referring to #10806. That issue seems fixed, so let's
try switching to a pseudorandom open port.
Does not actually fix #16289 but I'm going to close that
anyway, will reopen if it recurs.
```release-note
None
```
> system tests: podman network create: use random port

- test/system/037-runlabel.bats
I have no idea what this usage means, but the test fails
on a system with no /usr/bin/podman ... and that suggests
to me that the test is broken, in that it's been using
/usr/bin/podman instead of the $PODMAN we're testing.
```release-note
None
```
> system tests: runlabel: use podman-under-test

- test/system/170-run-userns.bats
- test/system/220-healthcheck.bats
- test/system/255-auto-update.bats
- test/system/400-unprivileged-access.bats
- test/system/helpers.bash
One of the system tests was creating a volume and not cleaning up
after itself. Fix that: do cleanup in the test itself. And, add
a 'volume rm -af' to global teardown() to leave things clean for
the next tests.
While testing on a VM without `/usr/bin/podman`, found a bunch
of cases where system tests were invoking `podman` or `/usr/bin/podman`;
replaced those with `run_podman` or `$PODMAN` as appropriate.
```release-note
None
```
> System tests: big glop o' cleanup

- test/buildah-bud/run-buildah-bud-tests
- test/buildah-bud/safeimage-patch.diff
Emergency import of https://github.com/containers/buildah/pull/4377
required because the ubi8 image changed behind our backs.
On podman main, this commit will be reverted by Ed's
treadmill as soon as a new buildah is vendored into podman.
On side branches, the human doing the vendoring will need to
perform manual surgery. I hope the instructions are good enough.
```release-note
None
```
> FIXME: Temporary workaround for ubi8 CI breakage

- cmd/podman/volumes/create.go
- docs/source/markdown/podman-volume-create.1.md
- libpod/options.go
- libpod/runtime_volume_common.go
- libpod/volume.go
- pkg/api/handlers/libpod/volumes.go
- pkg/domain/entities/volumes.go
- pkg/domain/infra/abi/volumes.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.volume
- test/e2e/volume_create_test.go
This ignores the create request if the named volume already exists.
It is very useful when scripting stuff.
```release-note
New --ignore option in podman volume create
```
> Add podman volume create --ignore

- test/buildah-bud/run-buildah-bud-tests
- test/buildah-bud/safeimage-patch.diff
Emergency import of https://github.com/containers/buildah/pull/4377 required because the ubi8 image changed behind our backs.
On podman main, this commit will be reverted by Ed's treadmill as soon as a new buildah is vendored into podman.
On side branches, the human doing the vendoring will need to perform manual surgery. I hope the instructions are good enough.
```release-note
None
```
> [v4.3] FIXME: Temporary workaround for ubi8 CI breakage

- Makefile
- test/e2e/libpod_suite_remote_test.go
- test/e2e/libpod_suite_test.go
- test/e2e/play_build_test.go
- test/e2e/run_apparmor_test.go
When there is a podman pause process running the local podman ginkgo tests will join the usernamespace. This because pkg/rootless will automatically join the ns on startup when possible. To fix this we need to use the remote build tag which disables that behavior.
However since the remote tag is also used in the e2e test itself we would always run remote tests which is wrong, this is fixed by using a new `remote_testing` tag for the test.
see discussion here: https://github.com/containers/podman/pull/16309#discussion_r1006166930
```release-note
None
```
> ginkgo testing: fix podman usernamespace join

- libpod/runtime.go
Suggested fix from @anarca
```release-note
Enhanced error message about older boltdb files.
```
> Add information about where the libpod/boltdb database lives

- libpod/container_api.go
The OCI Runtime's KillContainer interface can modify container state (if the signal fails to send, as it would if the container failed immediately after starting, we will update state to pick up the fact that the container exited). As such, it can edit the DB, and needs to be run locked.
There are fortunately only a few places where this function is used, and most of them are already safe. The only exception is StartAndAttach(), which does a SIGWINCH in an unlocked portion of the function. Fortunately it's a goroutine, so just add a lock and defer unlock and it should be fixed.
[NO NEW TESTS NEEDED] I have no idea how to induce a scenario that would cause this consistently.
```release-note
NONE
```
> Ensure that StartAndAttach locks while sending signals

- libpod/pod_api.go
Fixes: #16326
Signed-off-by: Mikhail Khachayants <tyler92@inbox.ru>
```release-note
Fix deadlock between 'podman ps' and 'container inspect' commands
```
> Fix deadlock between 'podman ps' and 'container inspect' commands

- test/buildah-bud/run-buildah-bud-tests
- test/buildah-bud/safeimage-patch.diff
Emergency import of https://github.com/containers/buildah/pull/4377 required because the ubi8 image changed behind our backs.
On podman main, this commit will be reverted by Ed's treadmill as soon as a new buildah is vendored into podman.
On side branches, the human doing the vendoring will need to perform manual surgery. I hope the instructions are good enough.
```release-note
None
```
> [v4.2] FIXME: Temporary workaround for ubi8 CI breakage

- contrib/cirrus/runner.sh
- test/e2e/system_connection_test.go
- test/e2e/systemd_test.go
We've had some oopsies in system tests:
podman foo bar
run podman foo bar
...all of which should be run_podman with underscore. Those
have been passing because /usr/bin/podman is the fallback
from $PATH. In those (few) cases, we haven't actually been
testing the podman we should be testing.
Solution: nuke /usr/bin/podman and podman-remote before
invoking system and unit tests. As an extra level of
paranoia, check for other podmans in $PATH and warn
about those. The warning will likely never be seen by
a human, but I may check for them periodically.
Also: in a few cases where runner.sh invokes podman for
containerized something-something, run bin/podman instead
of podman from $PATH.
```release-note
None
```
> Test runners: nuke podman from $PATH before tests

- docs/source/markdown/podman-images.1.md
Baby steps toward merging #14046: document Go format options
for podman images.
```release-note
document Go template formats for podman images
```
> [CI:DOCS] man pages: document some --format options: images

- cmd/podman/registry/config.go
- libpod/reset.go
- pkg/systemd/dbus.go
- pkg/util/utils_supported.go
- test/system/500-networking.bats
Partial Fix for https://github.com/containers/podman/issues/14606
```release-note
None
```
> Eval symlinks on XDG_RUNTIME_DIR

- docs/source/markdown/options/userns.container.md
- docs/source/markdown/options/userns.pod.md
- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-run.1.md.in
Underscore is special in markdown. We usually escape them
properly, but these are a few that we missed. Found using:
$ ack '[A-Z]\\fI[A-Z]' docs/build/man
(plus one that I found by accident).
If anyone has ideas on how to add a commit check for these,
please speak up. I'm at a complete loss to automate this.
```release-note
Minor formatting fixes to man pages
```
> [CI:DOCS] man pages: assorted underscore fixes

- go.mod
- go.sum
- libpod/reset.go
- test/buildah-bud/apply-podman-deltas
- test/e2e/system_reset_test.go
- vendor/github.com/containers/buildah/copier/copier.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/modules.txt
Only want to report if user created local customized storage in /etc/containers/storage.conf or in
$HOME/.config/containers/storage.conf, when resetting storage.
```release-note
The `podman system reset` command will no longer prompt the user if /usr/share/containers/storage.conf file exists.
```
> Do not report that /usr/share/containers/storage.conf has been edited.

- Makefile
- pkg/machine/qemu/options_freebsd_arm64.go
- pkg/rctl/rctl.go
This removes a stale use of cgo from pkg/rctl and adds a small change to allow podman to build on FreeBSD/arm64. Adding the cross build targets should help to detect FreeBSD build breaks early.
```release-note
None
```
> Enable cross building for FreeBSD

- .cirrus.yml
These tasks only ever run on the main branch.  For whatever reason, the
meta task is throwing errors trying to update a non-existant
`build-push-${IMAGE_SUFFIX}` image.  I have no idea how/why this image
got pruned, it shouldn't have.  However, it appears so far to be a
one-off, and it's not actually needed.  Remove reference to it and
the related useless tasks on this branch.
```release-note
None
```
> [v4.1.1-rhel] Cirrus: Remove build-push tasks

- .github/workflows/check_cirrus_cron.yml
Upgrade actions/checkout and actions/upload-artifact packages from v2 to v3.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
None
> Upgrade GitHub actions packages from v2 to v3

- version/version.go
v4.3.0 has been released.
```release-note
None
```
> version bump to 4.4.0-dev

- test/buildah-bud/apply-podman-deltas
ubi8 broke our tests. Fix is #16308 (don't use images that we don't control), but it's too hard to backport to this old branch. Just skip the failing test.
```release-note
None
```
> [v4.0-rhel] Skip failing pull-arch test

- test/buildah-bud/apply-podman-deltas
ubi8 broke our tests. Fix is #16308 (don't use images that we don't control), but it's too hard to backport to this old branch. Just skip the failing test.
```release-note
None
```
> [v4.1.1-rhel] Skip failing pull-arch test

- CONTRIBUTING.md
- test/README.md
Basically, acknowledge the need for dependencies and link to Fedora specfile which is the only sane place to find such a list.
Closes: #16365
```release-note
Add note on finding system-test dependencies
```
> [CI:DOCS] offer advice on installing test dependencies

- test/buildah-bud/apply-podman-deltas
- test/buildah-bud/buildah-tests.diff
When I first enabled buildah-bud tests under podman-remote (#9887),
I got one aspect all wrong: I added a podman-remote() helper function
to match the podman() one. Turns out it's never actually called,
even when $PODMAN_BINARY=podman-remote, because functions/aliases
don't work that way.
The way it works is, those few cases in which bud.bats runs
podman are not magically remapped to podman-remote, they use
the podman() function. That's where we need to check if
we're using podman-remote, and that's where we need to
remove the registry-and-rootdir options.
With this fix, we can reenable two previously-skipped bud tests.
```release-note
None
```
> buildah bud tests: better handling of remote

- .cirrus.yml
- contrib/cirrus/win-podman-machine-verify.ps1
Add initial podman machine verification testing on Windows. 
A future PR will port the full linux machine testsuite. 
This PR should not be merged until https://github.com/containers/automation_images/pull/228 merges.
```release-note
NONE
```
> Add Windows Smoke Testing

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
Fixes: #15349
Depends on: https://github.com/containers/podman/pull/15871 https://github.com/containers/podman/pull/15890
Image build PR: https://github.com/containers/automation_images/pull/195
```release-note
None
```
> Cirrus: Update CI VM images to F37beta

- docs/source/markdown/podman-run.1.md.in
> [CI:DOCS] Fix documentation on read-only-tmpfs

- .github/actions/check_cirrus_cron/cron_failures.sh
- .github/actions/check_cirrus_cron/lib.sh
- .github/actions/check_cirrus_cron/make_email_body.sh
- .github/actions/check_cirrus_cron/rerun_failed_tasks.sh
- .github/workflows/check_cirrus_cron.yml
- .github/workflows/rerun_cirrus_cron.yml
With a seemingly ever growing list of cirrus-cron jobs running on
release branches, there are bound to be some hiccups.  Sometimes a lot
of them.  Normally any failures require a human to eyeball the logs
and/or manually re-run the job to see if it was simply a flake.  This
doesn't take long, but can be distracting and compounds over time.
Attempt to alleviate some maintainer burden by using a new github action
workflow to perform **one** automatic re-run on any failed builds.  This
task is scheduled an hour prior to a second failure check, and generation
of notification e-mail for review.
Note: If there are no failures, due to the auto. re-run or luck, no
e-mail is generated. If this proves useful in this repo, I intend to
re-use this workflow for other repo's cirrus-cron jobs. 
The …
> [CI:DOCS] [WIP] GHA: Auto. re-run failed cirrus-cron builds once

- contrib/cirrus/runner.sh
All the other Windows tasks depend on access to a podman-remote build from the Alt. Arch. `Windows Cross` task.  Re-arrange the test-skipping call to never skip here only.
Ref: https://github.com/containers/podman/pull/16399#issuecomment-1302545093
```release-note
None
```
> [CI:BUILD] Cirrus: Never skip running Windows Cross task

- cmd/podman/manifest/inspect.go
- docs/source/markdown/.gitignore
- docs/source/markdown/options/tls-verify.md
- docs/source/markdown/podman-manifest-inspect.1.md.in
- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_manifest.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_inspect_options.go
- pkg/domain/entities/engine_image.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/system/010-images.bats
- test/system/012-manifest.bats
- test/system/150-login.bats
Helps fix: https://github.com/containers/podman/issues/14917
```release-note
podman manifest inspect now supports --insecure flag for Docker compatibility
```
> Add --insecure flag to podman manifest inspect for Docker compatibility

- cmd/podman/containers/rm.go
- cmd/podman/pods/create.go
- cmd/podman/pods/rm.go
- docs/source/markdown/options/cidfile.write.md
- docs/source/markdown/podman-pod-rm.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- libpod/runtime_ctr.go
- test/system/030-run.bats
- test/system/200-pod.bats
Remove the container/pod ID file along with the container/pod.  It's primarily used in the context of systemd and are not useful nor needed once a container/pod has ceased to exist.
Fixes: #16387
```release-note
Remove container/pod ID file along with container/pod.
```
> remove container/pod id file along with container/pod

- test/e2e/images_test.go
- test/e2e/play_build_test.go
- test/e2e/prune_test.go
As far as I can tell there is no reason to use apk in these tests. They just build an image and check for it and never use the installed binary. Network calls are always unstable and therefore should be avoided when possible, this ensures no/less flakes.
Fixes #16391
```release-note
None
```
> test/e2e: do not use apk in builds

- .cirrus.yml
It's important/useful to have all VM images built around the same time as it prevents tooling/dependency divergence and therefore simpler debugging.
Ref: https://github.com/containers/automation_images/pull/195#issuecomment-1301256241
```release-note
None
```
> Cirrus: Synchronize windows image

- libpod/runtime_ctr.go
- test/upgrade/test-upgrade.bats
there is already the same check when using cgroupfs, but not when using the systemd cgroup backend.  The check is needed to avoid a confusing error from the OCI runtime.
Closes: https://github.com/containers/podman/issues/16376
[NO NEW TESTS NEEDED] it needs a pod created with an old Podman version.
```release-note
None
```
> runtime: add check for valid pod systemd cgroup

- go.mod
- go.sum
- vendor/github.com/containers/storage/drivers/overlay/idmapped_utils.go
- vendor/modules.txt
There was a bug on s390x related to clone syscall argument order. C/storage PR #1423 fixes it; this vendors into Podman to close the loop and complete the fix.
Fixes RHBZ 2140084
Signed-off-by: Matthew Heon <mheon@redhat.com>
```release-note
NONE
```
> [v4.2.0-rhel] Bump c/storage to include #1423

- Makefile
There is no equivalent equivalent on FreeBSD and this causes lint failures when packaging.
```release-note
None
```
> Makefile: don't install to tmpfiles.d on FreeBSD

- Makefile
- contrib/cirrus/CIModes.md
- contrib/podmanimage/README.md
- pkg/signal/signal_common_test.go
- pkg/specgenutil/volumes_test.go
- pkg/systemd/parser/unitfile.go
> Run codespell on code

- test/buildah-bud/run-buildah-bud-tests
- test/buildah-bud/safeimage-patch.diff
Emergency import of https://github.com/containers/buildah/pull/4377 required because the ubi8 image changed behind our backs.
On podman main, this commit will be reverted by Ed's treadmill as soon as a new buildah is vendored into podman.
On side branches, the human doing the vendoring will need to perform manual surgery. I hope the instructions are good enough.
```release-note
None
```
> [v4.2.0-rhel] FIXME: Temporary workaround for ubi8 CI breakage

- pkg/api/handlers/compat/images_build.go
- test/python/docker/compat/test_images.py
```release-note
Fix bug where if using compat API to build an image, reading the chunked response may include more JSON objects than expected per chunk.
```
Signed-off-by: Jake Torrance [jaket1234@hotmail.com](mailto:jaket1234@hotmail.com)
Closes #16360
> Fix compat build API returning two JSON objects at once

- utils/utils.go
Check for the directory /run/systemd/system, this is described in sd_booted(3). Reading /proc/1/comm will fail when /proc is mounted with the `hidepid=2` option.
Fixes #16022
```release-note
Fixes a bug with the systemd booted check when /proc is mounted with the `hidepid=2` option.
```
> fix incorrect systemd booted check

- test/system/035-logs.bats
`podman-remote` does not support `--events-backend`, which overrides a log driver. When `--events-backend` is necessary in a test for `podman-remote`, the test should be skipped.
We don't need to fix the other cases with
`_additional_events_backend()` because `_log_test_follow()` already has the same skipping logic and `_log_test_multi()` always skips a test when testing `podman-remote`.
Signed-off-by: Hironori Shiina <shiina.hironori@fujitsu.com>
```release-note
None
```
> Skip test if `--events-backend` is necessary with podman-remote

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
The only change is the version number.
```release-note
None
```
> [v4.3] Bump c/image to released v5.23.1

- docs/tutorials/README.md
- docs/tutorials/performance.md
Closes #14902 
```release-note
None
```
> [CI:DOCS] Add performance tutorial

- libpod/util.go
This reports the correct package versions in 'podman info' for conmon and ociRuntime on FreeBSD which is needed for the 005-info system test.
```release-note
None
```
> libpod: Add FreeBSD support in packageVersion

- .github/actions/check_cirrus_cron/cron_failures.sh
- .github/actions/check_cirrus_cron/lib.sh
- .github/actions/check_cirrus_cron/make_email_body.sh
- .github/actions/check_cirrus_cron/rerun_failed_tasks.sh
- .github/actions/check_cirrus_cron/test.sh
- .github/workflows/check_cirrus_cron.yml
- .github/workflows/rerun_cirrus_cron.yml
- contrib/cirrus/prebuild.sh
Testing github-actions workflows that only operate on 'main' is a major PITA when secret env. vars. are involved.  This is a major demotivation for also not testing related shell scripts.  Fix this by adding tests for the scripts and automate their execution.
Fixes: #16426
```release-note
None
```
> [CI:BUILD] Fix cirrus cirrus-cron GHA workflow scripts, add checks, and tests

- .github/workflows/check_cirrus_cron.yml
Whoops Ref: https://github.com/containers/podman/pull/16414
```release-note
None
```
> [skip-ci] GHA: Fix typo

- .github/actions/check_cirrus_cron/cron_failures.sh
Ref:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
```release-note
None
```
> [CI:DOCS] GHA: Fix typo setting output parameter

- contrib/cirrus/runner.sh
- docs/tutorials/mac_win_client.md
- docs/tutorials/podman-for-windows.md
- docs/version-check
Intended to be run from nightly Cirrus cron job.
1) Queries github for highest-sorting (not necessarily "latest") tag
2) Checks that the Windows MSI exists, fails if not
3) Cross-checks markdown files to ensure they have up-to-date links
When run interactively, it will auto-update the .md files
to show and link to the latest version. This makes it easy
for anyone to then submit an update PR.
And, it turns out that MSI is obsolete, the new thing is EXE.
Update the tutorials to reflect that.
```release-note
None
```
> [CI:DOCS] New tool, docs/version-check

- .github/workflows/check_cirrus_cron.yml
This component was recently migrated from being inline, into a dedicated script file.  This was necessary for testing.  However, it's hard to test the actual github-actions workflow YAML, and there was a typo.  Fix the reference to the script filename missing the `.sh` extension.
Ref: https://github.com/containers/podman/pull/16414
```release-note
None
```
> [CI:DOCS] GHA: Fix make_email-body script reference

- .github/workflows/rerun_cirrus_cron.yml
Because in github-actions, setting a secret variable isn't enough.  You ALSO have to set it again in your YAML.  I guess it's assumed in the name of "security" that the person with access to secrets, might not also have access to update YAML.  Crazy!
Also, while we're at it.  Bump up the execution schedule WRT the check_cirrus_cron workflow - this will give re-run jobs more time to complete.
```release-note
None
```
> [skip-ci] GHA: Fix undefined secret env. var.

- docs/source/markdown/options/security-opt.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
This was a horrible one. I basically went with the podman-run
version, with a few minor changes. See PR for discussion of
diff review.
```release-note
```
> [CI:DOCS] Man pages: refactor common options: --security-opt

- hack/xref-docker-options
Long-term followup to #14917. This adds a new one-off script, to be run periodically, which runs our man-page crossref against docker, highlighting commands and options that docker lists in its --help but we don't list in our man pages.
```release-note
None
```
> [skip ci] Formalize our compare-against-docker mechanism

- .cirrus.yml
This task runs the latest/greatest upstream gitlab unit tests.  There is no benefit to running it on a podman release-branch.  Disable it.
```release-note
None
```
> [skip-ci] Disable gitlab task

- cmd/podman/system/events.go
- commands-demo.md
- docs/source/markdown/links/podman-system-events.1
- docs/source/markdown/podman-events.1.md
- docs/source/markdown/podman-system.1.md
- test/e2e/search_test.go
- test/system/090-events.bats
- test/system/610-format.bats
- transfer.md
```release-note
podman system events now alias to podman events for Docker compatibility
```
> Add podman system events alias to podman events

- cmd/podman/volumes/create.go
- docs/source/markdown/podman-volume-create.1.md
- test/system/160-volumes.bats
```release-note
podman volume create -d option now supported.
```
> Add podman volume create -d short option for driver

- cmd/podman/manifest/inspect.go
- test/system/012-manifest.bats
> Add hidden podman manifest inspect -v option

- cmd/podman/root.go
- test/e2e/system_connection_test.go
--connection was failing due to the servicedestinations array being empty on runtime. Fix by making sure the cached config is used and properly given to the empty config.
resolves #16282
```release-note
fix --connection with cached containers.conf
```
> fix connection usage with containers.conf

- cmd/podman/containers/cp.go
- test/system/065-cp.bats
Fix a bug for special-casing "." where Podman has mistakenly been looking for a "." suffix instead of interpreting it as a path.
Add regression tests for the host-to-container, container-to-host and container-to-container use cases.  Have separate tests for each to verify that previous Podman versions fail each case.
Fixes: #16421
```release-note
Fix a bug in `podman cp` when copying directories ending with a ".".
```
> podman cp: fix copying with "." suffix

- go.mod
- go.sum
- libpod/options.go
- pkg/specgen/generate/container_create.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/types/const.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_darwin.go
- vendor/github.com/containers/common/pkg/config/config_freebsd.go
- vendor/github.com/containers/common/pkg/config/config_linux.go
- vendor/github.com/containers/common/pkg/config/config_windows.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/golang.org/x/crypto/cast5/cast5.go
- vendor/golang.org/x/crypto/salsa20/salsa/hsalsa20.go
- vendor/golang.org/x/crypto/salsa20/salsa/salsa208.go
- vendor/golang.org/x/crypto/salsa20/salsa/salsa20_ref.go
- vendor/golang.org/x/crypto/sha3/keccakf.go
- vendor/golang.org/x/crypto/ssh/messages.go
- vendor/modules.txt
Whenever image has `arch` and `os` configured for `wasm/wasi` switch to `crun-wasm` as extension if applicable, following will only work if `podman` is using `crun` as default runtime.
[NO NEW TEST NEEDED]
A test for this can we added when `crun-wasm` package is part of the CI.
```release-note
specgen,wasm: switch to crun-wasm if image is a webassembly image
```
> specgen,wasm: switch to crun-wasm wherever applicable

- contrib/pkginstaller/Makefile
this updates the Makefile qemu version to make use new qemu released at https://github.com/containers/podman-machine-qemu/releases/tag/v7.1.0-1
```release-note
None
```
> pkginstaller: bump Qemu to version 7.1.0

- docs/source/markdown/options/network.md
- docs/source/markdown/podman-network-create.1.md
Since pasta is now considered a network mode using it as network name causes a conflict. For now we will prefer the named network but in a future major version bump we want to remove this and just use pasta(1).
The docs should reflect that this name is considered deprecated.
```release-note
The network name `pasta` is deprecated and support for it will be removed in the next major release.
```
> [CI:DOCS] docs: deprecate pasta network name

- libpod/container.go
when reading from the /proc/$PID/cgroup file, treat ESRCH in the same way as ENOENT since the kernel returns ESRCH if the file was opened correctly but the target process exited before the open could be performed.
Closes: https://github.com/containers/podman/issues/16383
[NO NEW TESTS NEEDED] it is a race condition that is difficult to reproduce.
```release-note
None
```
> libpod: treat ESRCH from /proc/PID/cgroup as ENOENT

- test/e2e/play_kube_test.go
No issue filed, because I thought these were related to 16132.
They're not: they're actual test bugs, running "play kube"
without actually waiting for the container to run. Fix that.
```release-note
None
```
> Fix more podman-logs flakes

- pkg/api/handlers/compat/images_build.go
- test/apiv2/10-images.at
Docker's newer clients popuates `cacheFrom` and `cacheTo` parameter by default as empty array for all commands but buildah's design of distributed cache expects this to be a repo not image hence parse only the first populated repo and igore if empty array.
All the remote-bud tests must pass for cacheTo and cacheFrom, docker-client is not present in CI hence cannot be tested.
```release-note
compat,build: make compat build api functional
```
Closes: https://github.com/containers/podman/issues/15928
> compat,build: handle `docker's` preconfigured `cacheTo`,`cacheFrom`

- test/e2e/restart_test.go
It's so easy to forget that "podman start" is nonblocking.
So podman create, start, restart has a race where "restart"
can run before the container actually starts.
Solution: start --attach. Thanks to @vrothberg for noticing that.
There are still a handful of other suspicious-looking restarts
in this test, but all involve "top" which of course has to be
detached. Since those don't have any flakes that I know of, I
choose to ignore them.
Fixes: #16505
```release-note
None
```
> e2e tests: fix restart race

- test/system/220-healthcheck.bats
Weird one-off flake seen:
```
Error: container SHA is not running
```
The only way I can see this happening is if the healthcheck
auto-timer triggered, which seems impossible because that
should be 30s and the log timestamps show this test taking
18s. But, shrug, let's see if disabling the timer works. I
don't have high hopes that this will fix anything, but it's
probably a good idea regardless.
Also, since this test loops over different policies, include
policy name in error messages as a courtesy. (It's obtainable
anyway by scrolling up)
```release-note
None
```
> healthcheck system tests: try to fix flake

- .github/workflows/check_cirrus_cron.yml
- .github/workflows/rerun_cirrus_cron.yml
> [skip-ci] Reuse workflows

- pkg/api/handlers/compat/images_build.go
- test/apiv2/10-images.at
Backport of https://github.com/containers/podman/pull/16380
Docker's newer clients popuates `cacheFrom` and `cacheTo` parameter by default as empty array for all commands but buildah's design of distributed cache expects this to be a repo not image hence parse only the first populated repo and ignore if empty array.
Note: Upstream will start using newer API as soon as buildah exposes new API
```release-note
compat,build: make compat build api functional for newer docker-clients
```
> [release-v4.3] compat,build: handle docker's preconfigured `cacheTo`,`cacheFrom`

- cmd/podman/machine/start.go
- docs/source/markdown/podman-machine-start.1.md
- pkg/machine/config.go
- pkg/machine/e2e/config_start_test.go
- pkg/machine/e2e/start_test.go
- pkg/machine/e2e/stop_test.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
Add quiet and no-info flags to podman machine start.
No-info suppresses helpful informational tips
Quiet suppresses machine start progress output, as well as informational
tips.
Closes: https://github.com/containers/podman/issues/15525
```release-note
Add quiet and no-info flags to podman machine start
```
> Add --quiet and --no-info flags to podman machine start

- pkg/specgen/generate/pod_create.go
- test/system/200-pod.bats
Make sure to remove the pod if its creation has failed.
Fixes: #16502
```release-note
Fix a bug where a pod was partially created even when its creation has failed.
```
> remove pod if creation has failed

- cmd/podman/root.go
- pkg/domain/entities/engine.go
- test/system/001-basic.bats
Podman --noout was not suppressing output from commands that do not create the podman engine. Now, podman --noout properly suppresses output from every command.
Fixes: https://github.com/containers/podman/issues/16201
```release-note
Fixed a bug where `podman --noout` was not suppressing output from certain commands such as `podman machine` and `podman system connection`
```
> Fix podman --noout to suppress all output

- test/e2e/logs_test.go
- test/system/200-pod.bats
- test/system/helpers.bash
[backport #16437]
It looks like #16132 was my fault: a missing 'wait' for a container to exit. Let's see if this fixes the flake.
And, while poking through flake logs, I found another missing wait.
And... in wait_for_output(), address a potential race.
```release-note
none
```
> [v4.3] More log-flake work

- docs/source/markdown/options/userns.container.md
- docs/source/markdown/podman-run.1.md.in
```release-note
Better documentation for --userns=keep-id:uid=X,gid=Y
```
> [CI:DOCS] Add more documentation on UID/GID Mappings with --userns=keep-id

- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/containers_freebsd.go
- pkg/domain/infra/abi/containers_linux.go
- pkg/rootless/rootless_freebsd.c
- pkg/rootless/rootless_freebsd.go
This mainly involved implementing enough of rootless to support IsFdInherited. The function checkExecPreserveFDs seems redundant - it repeats the work of IdFdInherited and could be removed entirely. This extra check only happens for exec, not run.
```release-note
None
```
> Add support for --preserve-fds on FreeBSD for run and exec

- pkg/bindings/connection.go
- test/e2e/system_connection_test.go
if no port is specified for an ssh style url, default to 22
resolves #16509
```release-note
fix port validation for CONTAINER_HOST
```
> fix port issues for CONTAINER_HOST

- libpod/runtime_ctr.go
- pkg/domain/entities/containers.go
- pkg/domain/entities/reports/containers.go
- pkg/domain/infra/tunnel/containers.go
Including the RawInput in the API output is meaningless.
Fixes: #16497
```release-note
None
```
> Removing the RawInput from the API output

- test/system/070-build.bats
When we are using a proxy, 'podman build - basic test' will be failed on remote.
This test needs to add the '--http-proxy' option.
<details>
<summary>’podman build - basic test’ is failed</summary>
```
not ok 1 podman build - basic test
```
</details>
```release-note
None
```
> system tests: fix a system test in proxy environment

- docs/source/markdown/podman-remote.1.md
- go.mod
- pkg/bindings/connection.go
- vendor/golang.org/x/net/internal/socks/client.go
- vendor/golang.org/x/net/internal/socks/socks.go
- vendor/golang.org/x/net/proxy/dial.go
- vendor/golang.org/x/net/proxy/direct.go
- vendor/golang.org/x/net/proxy/per_host.go
- vendor/golang.org/x/net/proxy/proxy.go
- vendor/golang.org/x/net/proxy/socks5.go
- vendor/modules.txt
the podman server may run in a private network environment, and **podman-remote-client** need a proxy to connect the server.
1. only works when the env key `CONTAINER_HOST` is `tcp://`, and env key `CONTAINER_PROXY` uri is set correctly.
2. the `golang.org/x/net/proxy` interface support proxy with schema **socks5** and **socks5h**,  if want to support other kind proxy, should import a driver implement package. 
3. the default dial timeout is 75s, which is too long for proxy dialer, so I add DialContext with 3s timeout
I have test with  `CONTAINER_PROXY=socks5://user:pass@ip:port`  and `CONTAINER_PROXY=socks5://ip:port` in prod, the socks5 proxy works fine.
The tcp proxy is similar to ssh proxy, which already exists and seems no test in CI , If test needed, a proxy …
> podman-remote connect tcpURL with a 'CONTAINER_PROXY'

- docs/source/markdown/options/pids-limit.md
Correct the documented default number of pids limit from 4096 to 2048.
If 4096 is more reasonable as pids limit, the default value should be set to 4096.
https://github.com/containers/podman/blob/f7ac8a4213d71b13f358bcf1f1669d18b2d5f7e3/vendor/github.com/containers/common/pkg/config/default.go#L147-L149
Signed-off-by: Tsubasa Watanabe <w.tsubasa@fujitsu.com>
```release-note
None
```
> [CI:DOCS] Modify man page of "--pids-limit" option to correct a default value.

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
- test/e2e/quadlet/annotation.container
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/basic.container
- test/e2e/quadlet/capabilities.container
- test/e2e/quadlet/env.container
- test/e2e/quadlet/escapes.container
- test/e2e/quadlet/exec.container
- test/e2e/quadlet/image.container
- test/e2e/quadlet/install.container
- test/e2e/quadlet/label.container
- test/e2e/quadlet/name.container
- test/e2e/quadlet/noremapuser.container
- test/e2e/quadlet/noremapuser2.container
- test/e2e/quadlet/notify.container
- test/e2e/quadlet/other-sections.container
- test/e2e/quadlet/podmanargs.container
- test/e2e/quadlet/ports.container
- test/e2e/quadlet/ports_ipv6.container
- test/e2e/quadlet/shortname.container
- test/e2e/quadlet/socketactivated.container
- test/e2e/quadlet/timezone.container
- test/e2e/quadlet/user-host.container
- test/e2e/quadlet/user-root1.container
- test/e2e/quadlet/user-root2.container
- test/e2e/quadlet/user.container
- test/e2e/quadlet/volume.container
- test/e2e/quadlet_test.go
This was broken out of https://github.com/containers/podman/pull/16237 due to the discussions there. 
Basically, it isn't a fatal error to use a shortname as `Image=shortname` in a quadlet file, but it does have some non-obvious drawbacks:
* Using a shortname will cause podman to load the shortname aliases file, which on rhel is 300k and takes > 70 msecs. This delay is non-obvious and unnecessary, but most sysadmins will not be aware of it, so logging a warning is helpfule
* Shortnames do not uniquely define an image, so over time what is run by the service may change. For instance, if initially there was only `regitstry1.com/image`, but then someone installs `registry2.com/image`, then the service may switch to that.
So, the idea was to at least warn about this to ensure people are aware …
> quadlet: Warn in generator if using short names

- test/e2e/search_test.go
The current test uses registry.redhat.io which does not support unauthenticated access Replace the registry with registry.access.redhat.com which does.
See https://access.redhat.com/RegistryAuthentication for details
```release-note
None
```
> E2E Tests: change the registry for the search test to avoid authentication

- cmd/podman/common/completion.go
Depending on the backend (CNI, netavark) we support different drivers, the auto completion should only suggest the ones that are available.
This list is podman info so we can get the correct list for local and remote.
```release-note
Fixed incorrect shell completion suggestions for `podman network create --driver`.
```
> shell completion: fix hard coded network drivers

- pkg/specgen/generate/container_create.go
- test/e2e/run_userns_test.go
honor eventual options set in the containers.userns setting in the containers.conf file, e.g.:
[containers]
userns = "auto:size=8192"
```release-note
None
```
> specgen: honor user namespace value

- test/system/900-ssh.bats
- test/system/helpers.bash
The 900-ssh test is not an actual test, and I'm unable to
figure out how to make it one. Skip it for now, but add a
bunch of FIXMEs some someone can come in later and actually
implement it.
Also removed lots of dead code and misleading comments.
```release-note
None
```
> ssh system test: skip until it becomes a test

- .cirrus.yml
- Makefile
Migrate our OSX Cross build to a M1 instance, since Cirrus is sunsetting Intel-based macOS instances.
```release-note
None
```
> [CI:DOCS] Migrate OSX Cross to M1

- cmd/quadlet/main.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.kube
- test/e2e/quadlet_test.go
Currently, Quadlet support `.container` file which translated to a `podman run` call and `.volume` file which translates to `podman volume` call. This PR adds a new file type `.kube` which will translate to a `podman kube play` call. In its first version only one parameter is supported and that is the location of the K8S YAML file
```release-note
Quadlet: Add support for running podman kube play via .kube files
```
> Quadlet: Add support for running podman kube play via .kube files

- .github/workflows/rerun_cirrus_cron.yml
The checkout action by default, clones the current repository.  However, since this workflow is re-used by other repos, and it calls scripts in the podman repo, those calls will all fail.  Fix this by hard-coding the podman repo.
Ref: https://github.com/actions/checkout
```release-note
None
```
> [skip-ci] GHA: Fix cirrus re-run workflow for other repos.

- pkg/trust/policy.go
This reduces the number of places default policy path is defined to two. Ideally there would be only one but that seems to be difficult - see https://github.com/containers/image/pull/1725 for some context.
```release-note
None
```
> pkg/trust: Take the default policy path from c/common/pkg/config

- go.mod
- go.sum
- test/buildah-bud/run-buildah-bud-tests
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/copier/copier.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/modules.txt
Contains backport of https://github.com/containers/buildah/pull/4411
> [release-v4.3] vendor: bump buildah to `v1.28.1`

- Makefile
This change adds a validate-in-container make target that can be used to run the make validate target in a container instead of requiring the dependencies to be available on the system. This mirrors what is already done for the vendor target and allows additional targets to be added.
A PODMANCMD make variable is also added to allow for the podman binary to be overridden in cases where this is not available.
Signed-off-by: Evan Lezar <elezar@nvidia.com>
```release-note
None
```
> Add validate-in-container target

- libpod/container_internal.go
- test/system/220-healthcheck.bats
When restarting a container, clean up the healthcheck state by removing the old log on disk.  Carrying over the old state can lead to various issues, for instance, in a wrong failing streak and hence wrong behaviour after the restart.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2144754
```release-note
Clean up old healthcheck state during container restart.
```
> container restart: clean up healthcheck state

- cmd/podman/common/create.go
- cmd/podman/containers/create.go
- cmd/podman/images/pull.go
- cmd/podman/images/push.go
- docs/source/markdown/options/decryption-key.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-run.1.md.in
- pkg/domain/entities/images.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- pkg/util/utils.go
- test/e2e/pull_test.go
- test/e2e/push_test.go
- test/e2e/run_test.go
- test/utils/common_function_test.go
- test/utils/utils.go
This PR adds encryption decryption functionality, just like those present in buildah and skopeo. `containers/common/libimage` already supports encryption-decryption of images, so its a Podman only change.
This would allow us to encrypt the image while pushing it to a registry and decrypt the image while pulling it from a registry.
The commands would be as follows:
```
podman push --encryption-key protocol:keyfile IMAGE
podman pull --decyrption-key protocol:keyfile IMAGE 
```
Additionally,
`podman run --decryption-key <key> IMAGE [command [arg …]]`
would automatically pull the image from a registry, decrypt it using decryption key and run the container.
Signed-off-by: Tarun Gupta [gupttaru@deshaw.com](mailto:gupttaru@deshaw.com)
```release-note
Yes.
This PR adds the flag `--encryption-key` …
```
> Add encryption decryption feature

- go.mod
- go.sum
- pkg/specgen/generate/config_linux.go
- test/e2e/run_device_test.go
- vendor/github.com/containers/common/libnetwork/cni/config.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/types/network.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_local.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/modules.txt
Closes: https://github.com/containers/podman/issues/16232
Needs: https://github.com/containers/common/pull/1239
```release-note
It is now possible to specify CDI devices in the containers.conf file
```
> specgen: support CDI devices from containers.conf

- libpod/container_internal_freebsd.go
This addresses #16333 although that issue was also avoided by changes in PR #16554.
```release-note
None
```
> libpod: Add checks to avoid nil pointer dereference if network setup fails

- pkg/specgen/generate/kube/volume.go
- test/e2e/play_kube_test.go
If the secret exists, set optional in the KubeVolume to false to always use it
If the secret does not exist, if optional, set the same in the KubeVolume to skip it, otherwise fail
No
```release-note
Fix the handling of the optional field of SecretVolumeSource
```
Fixes #16636
> Kube Play: fix the handling of the optional field of SecretVolumeSource

- libpod/container_internal.go
- test/e2e/search_test.go
- test/system/220-healthcheck.bats
When restarting a container, clean up the healthcheck state by removing the old log on disk.  Carrying over the old state can lead to various issues, for instance, in a wrong failing streak and hence wrong behaviour after the restart.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2144754
```release-note
Clean up old healthcheck state during container restart.
```
> [v4.2.0-rhel] container restart: clean up healthcheck state

- pkg/machine/qemu/options_windows_amd64.go
Follow up to #15851 as it was merged before I managed to update it.
Also, I did some more investigation on  mwait_idle kernel panic. It seems that some hardware goes with this flag disabled and it is known to cause issues for Hyper-V VMs (one case documented here (for Windows VMs though) https://portal.nutanix.com/page/documents/kbs/details?targetId=kA07V000000LV1aSAG).
I didn't manage to debug down if either Hyper-V, host or both wrongly detect MONITOR/MWAIT presence, but I think putting this to `monitor=off` is also good for improved portability and wider host support.
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
```release-note
None
```
> Documenting Hyper-V QEMU acceleration settings

- libpod/stats_freebsd.go
- libpod/stats_linux.go
Fix swapped NetInput and NetOutput container stats. This resulted in `podman stats` showing outgoing traffic as NetInput and incoming traffic as NetOutput. This change might be visible or cause problems for users who are actively relying on those stats for monitoring reasons.
Signed-off-by: Ingo Becker <ingo@orgizm.net>
```release-note
Container stats for the fields NetInput and NetOutput were swapped. NetInput was showing outgoing traffic and NetOutput incoming traffic which is fixed now.
```
> Fix swapped NetInput/-Output stats

- docs/source/markdown/podman-network-create.1.md
Add documentation on the new Netavark option, `metric`, used to set default route preference for containers joined to multiple networks.
```release-note
NONE
```
> [CI:DOCS] Add information on metrics to the `network create` docs

- podman.spec.rpkg
Resolves: #16669
@rhatdan PTAL
```release-note
None
```
> [CI:BUILD] copr: enable podman-restart.service on rpm installation

- contrib/win-installer/burn.wxs
- contrib/win-installer/podman.wxs
Fixes #16265
Allow manual override of install location
Also reuse install location for previous installs if present
Example Usage: .\podman-4.3.2-setup.exe InstallFolder=C:\Other\Loc
```release-note
Allow manual override of install location in windows installer
```
> Allow manual override of install location in Windows installer

- hack/podmansnoop
Update the snoop script to also include the arguments to make the output more useful.
```
$ sudo hack/podmansnoop
PCOMM            PID     PPID    AGE(ms) ARGV
conmon           14964   14952   1.01    /usr/bin/conmon --version
podman           14952   14139   26.07   /usr/bin/podman ps
```
```release-note
None
```
@rhatdan PTAL
> [CI:docs] hack/podmansnoop: print arguments

- cmd/podman/common/create.go
- cmd/podman/healthcheck/run.go
- docs/source/markdown/options/health-startup-cmd.md
- docs/source/markdown/options/health-startup-interval.md
- docs/source/markdown/options/health-startup-retries.md
- docs/source/markdown/options/health-startup-success.md
- docs/source/markdown/options/health-startup-timeout.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- libpod/container.go
- libpod/container_config.go
- libpod/container_internal.go
- libpod/container_validate.go
- libpod/define/healthchecks.go
- libpod/healthcheck.go
- libpod/healthcheck_linux.go
- libpod/options.go
- pkg/api/handlers/libpod/healthcheck.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/healthcheck.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/healthcheck_run_test.go
TODO: Needs to be wired into `podman inspect`, needs tests written, needs manpages
Add support for startup healthchecks. A startup healthcheck is a healthcheck that runs before the main healthcheck, to accomodate slow-starting containers; inspiration is mostly from K8S startup probes, and we'll be using this as a backend for supporting those in `podman play kube` once this merges.
```release-note
Containers can now have startup healthchecks, allowing a command to be run to ensure the container is fully started before the regular healthcheck is activated.
```
> Add support for startup healthchecks

- .cirrus.yml
It's important to actually perform a windows build for a `[CI:DOCS]` PR since it verifies and includes a copy of the docs.  However, it's not necessary to actually test if the installer functions or not. That task should happen in other contexts.
```release-note
None
```
> [CI:DOCS] Skip windows-smoke when not useful

- libpod/healthcheck_unsupported.go
Extra function arguments were added in #13909.
```release-note
None
```
> libpod: Track healthcheck API changes in healthcheck_unsupported.go

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/basic.container
- test/e2e/quadlet/capabilities.container
- test/e2e/quadlet/readonly-notmpfs.container
Revert all quadlet custom defaults to whatever `podman run` does. 
No release notes should be needed, as we have the initial quadlet release note covering this.
```release-note
None
```
> Quadlet use regular defaults

- .cirrus.yml
- Makefile
- docs/remote-docs.sh
Fixes #16702 
Fixes included:
* Build documentation for the same target OS-ARCH as the requested application binaries (needed tools are still built for host)
* Limit msi build to amd64 arch as msitools doesn't support arm64 Windows as of now
* Fixes for HOME and PATH variables having whitespaces inside.
Now these commands work on MacOS M1:
* `make clean podman.msi`
* `make clean podman-remote-release-windows_arm64.zip`
* `make clean podman-remote-release-windows_amd64.zip`
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
```release-note
None
```
> Build cross-compilation fixes

- Makefile
- RELEASE_PROCESS.md
- contrib/pkginstaller/Makefile
- contrib/pkginstaller/package.sh
- contrib/podmanremoteimage/Containerfile
- contrib/podmanremoteimage/README.md
This PR changes the name of some of the binaries which go to 
https://github.com/containers/podman/releases/
It renames `podman-release-static` to `podman-release-static-linux_{amd64,arm64}`,
and renames `podman-installer-macos-aarch64.pkg` to `podman-installer-macos-arm64.pkg` 
automation/scripts relying on these file names which are not stored in
github.com/containers/podman will need to be adjusted for these changes.
This fixes https://github.com/containers/podman/issues/16612
```release-note
`podman-release-static.tar.gz` has been renamed to `podman-release-static-linux_{amd64,arm64}.tar.gz`.
`podman-installer-macos-aarch64.pkg` has been renamed to `podman-installer-macos-arm64.pkg`.
```
> Make released binary names more consistent

- Makefile
- cmd/podman/machine/os.go
- cmd/podman/machine/os/apply.go
- cmd/podman/main_experimental.go
Introduce machine os and machine os apply. Note that these are both stubs at the current moment, and do not introduce functionality. In order to build them, you must use the `experimental` build tag, or use `make podman-remote-experimental`
as there is no actual functionality and this is a WIP.
```release-note
None
```
> Introduce podman machine os commands

- contrib/cirrus/lib.sh
- contrib/cirrus/lib.sh.t
- contrib/cirrus/prebuild.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
The passthrough_env function was unnecessarily complicated,
hence fragile. Clean it up, and add regression tests.
For future reference: CI broke horribly because of this.
Rootless tests all failed with missing CI_DESIRED_NETWORK.
Root cause was that CIRRUS_CHANGE_TITLE had a trailing
space which, because of shell indirection, passthrough_env()
wrote as trailing backslash (not backslash-space) in the
/etc/ci_environment file, which then caused the next line
in the file to get glommed onto CIRRUS_CHANGE_TITLE.
[Github-only note: I've added a trailing space to the title of this PR. Github only, not git]
```release-note
None
```
> CI setup: simplify environment passthrough code 

- libpod/kube.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgenutil/specgen.go
- pkg/specgenutil/volumes.go
- test/e2e/generate_kube_test.go
- test/system/700-play.bats
The containers should be able to write to tmpfs mounted directories.
```release-note
Podman kube play with a readOnlyTmpfs Flag in the YAML can now write to tmpfs inside of container.
```
> Fix handling of readonly containers when defined in kube.yaml

- CONTRIBUTING.md
This container hasn't been used/maintained in ages, remove the related instructions from the contributions doc.
Fixes: #16415
```release-note
None
```
> [CI:DOCS] Remove broken gate-container docs

- cmd/podman/common/completion.go
- cmd/podman/containers/create.go
```release-note
--init-ctr completions now work.
```
[NO NEW TESTS NEEDED] Since I don't know how to test completions.
> Add completion for --init-ctr

- .cirrus.yml
- contrib/cirrus/runner.sh
This just verifies that a non-cgo podman binary can build for FreeBSD.
```release-note
None
```
> Add a FreeBSD cross build to the cirrus alt build task

- libpod/runtime_ctr.go
- test/e2e/run_userns_test.go
do not chown a volume when idmap is used.
Closes: https://github.com/containers/podman/issues/16724
```release-note
Now volumes that use idmap are not chowned to the UID/GID of the root in the container
```
> runtime: do not chown idmapped volumes

- pkg/api/handlers/compat/containers_create.go
- test/compose/ipam_set_ip/docker-compose.yml
- test/compose/ipam_set_ip/tests.sh
docker-compose sets the mac address in the container config and not the network endpoint config. This is ugly when you have more than one network, in this case docker just chooses the first network.
Fixes #16411
```release-note
Support the mac address field in the container config for the compat API, this ensures that the static mac from the docker-compose.yml is used.
```
> compat API: allow MacAddress on container config

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/absolute.path.kube
- test/e2e/quadlet/syslog.identifier.kube
- test/e2e/quadlet_test.go
If the provided path is relative, turn path to absolute
Add regex verification option in tests
Resolves #16590 
No since Quadlet was not released yet
```release-note
None
```
> Quadlet Kube: Add support for relative path for YAML file

- libpod/healthcheck.go
- libpod/healthcheck_linux.go
- libpod/healthcheck_nosystemd_linux.go
The podman healthchecks are implemented using systemd timers, this works great but it will never work on non system distros. Currently the logic always assumes systemd is available and will fail with an error, so users are forced to always run with `--no-healthcheck` to disable healthchecks that are defined in an image for example. This is annoying and IMO unessesary, we should just default to no healthcheck on these systems.
First, use the systemd build tag to disable it at build time if this tag is not used.
Second, use make sure systemd is used as init before trying to use healthchecks. This could be the case when we are run in a container.
[NO NEW TESTS NEEDED] We do not have any non systemd VMs in CI AFAIK.
Fixes #16644
```release-note
Healthchecks are automatically disabled if your …
```
> disable healthchecks automatically on non systemd systems

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.container
Since https://github.com/containers/podman/pull/16394 was merged we now always delete the cid file if --replace=true was specified, so we can avoid this extra command being launched.
```release-note
None
```
> quadlet: Drop ExecStartPre=rm %t/%N.cid

- cmd/quadlet/main.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/remap-auto.kube
- test/e2e/quadlet/remap-auto2.kube
- test/e2e/quadlet/remap-manual.kube
- test/e2e/quadlet_test.go
Move the handling of userns keys from ConvertContainer to a separate method
Adjust the method according to the different supported values
Use the new method in both ConvertContainer and ConvertKube 
Pass isUser to ConvertKube as well
Add tests
No
```release-note
None
```
Resolves #16594
> Quadlet Kube: Add support for userns flag

- test/e2e/common_test.go
- test/e2e/generate_kube_test.go
- test/e2e/run_networking_test.go
- test/e2e/systemd_activate_test.go
- podman generate kube inheritents the proxy environment valiable by default.
Therefore, Env field is not empty if it is set.
- systemd-socket-acrivate needs to pass an proxy environment variable.
- busybox wget with an proxy doesn't work.
Network tests should use not wget but curl.
https://gitlab.alpinelinux.org/alpine/aports/-/issues/10446
```release-note
None
```
> e2e: fix e2e tests in proxy environment

- docs/source/markdown/podman-volume-create.1.md
Ref: https://github.com/containers/podman/issues/16576
```release-note
None
```
> [CI:DOCS] Add warning about --opts,o with mount's -o

- test/e2e/run_networking_test.go
This should work since nv v1.1.
Fixes #13931
```release-note
None
```
> test/e2e: enable "podman run with ipam none driver" for nv

- test/e2e/build_test.go
- test/e2e/run_env_test.go
In a proxy environment, `http_proxy` needs to keep
the value to use a proxy.
```release-note
None
```
> e2e: keeps the http_proxy value

- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/checkpoint_image_test.go
This pull request is a follow up on https://github.com/containers/podman/pull/15868, https://github.com/containers/podman/pull/16068 and https://github.com/containers/podman/pull/16078. It extends the `podman run` command with support for checkpoint images. When `podman run` is invoked with an image that contains checkpoint annotation, it would invoke restore.
Example:
```
podman run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
podman container checkpoint --create-image checkpoint-image-1 looper  
podman run checkpoint-image-1
```
```release-note
The `podman run` command has been extended with support for checkpoint images.
```
> Add support for checkpoint images with 'podman run'

- Makefile
As well as as small fix for zipping the correct folder when building on Mac
Closes: #16746
```release-note
None
```
> Makefile: Add podman-mac-helper to darwin client zip

- pkg/domain/infra/abi/play.go
- pkg/systemd/notifyproxy/notifyproxy.go
- pkg/systemd/notifyproxy/notifyproxy_test.go
- test/system/250-systemd.bats
- test/system/260-sdnotify.bats
- test/system/700-play.bats
As outlined in #16076, a subsequent BARRIER *may* follow the READY
message sent by a container.  To correctly imitate the behavior of
systemd's NOTIFY_SOCKET, the notify proxies span up by `kube play` must
hence process messages for the entirety of the workload.
We know that the workload is done and that all containers and pods have
exited when the service container exits.  Hence, all proxies are closed
at that time.
The above changes imply that Podman runs for the entirety of the
workload and will henceforth act as the MAINPID when running inside of
systemd.  Prior to this change, the service container acted as the
MAINPID which is now not possible anymore; Podman would be killed
immediately on exit of the service container and could not clean up.
The kube template now correctly …
> kube sdnotify: run proxies for the lifespan of the service

- cmd/podman/kube/down.go
- cmd/podman/kube/play.go
- test/e2e/play_kube_test.go
If an error happening while playing a kube yaml,
clean up any pods, containers, and volumes that might have been created before the error was hit.
This improves the user experience for when they go to re-run the same yaml with their fixes and podman doesn't complain about any existing workloads from the previously failed run.
Suppress the clean up output when clean up happens after an error as the user doesn't need to see or know about that.
```release-note
Clean up containers, pods, and volumes if an error happens while playing a kube yaml file.
```
> Cleanup kube play workloads if error happens

- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/play_test.go
- pkg/specgen/generate/kube/volume.go
- test/e2e/play_kube_test.go
Fixes secret (un)marshaling for kube play.
Merges stringData into data for secrets as in k8s.
Fixes e2e tests, remove '\n' from base64 encoded data.
Correct test to check that data in secret mounted file is decoded.
Closes #16269
Closes #16625
Signed-off-by: Andrei Natanael Cosma <andrei@intersect.ro>
NO
```release-note
Fixes secret unmarshaling for kube play.
```
> Fixes secret marshaling for kube play. Merge stringData with data for secrets.

- libpod/healthcheck_linux.go
When stopping the transient systemd timer/unit which powers running health checks, make sure to ignore its dependencies.  It turns out that we're otherwise running into a timeout when running a container in a systemd unit and reboot.
An alternative may be to further tweak some attributes/options when creating the timer/unit via systemd-run but it seems safe to just ignore the dependencies and stop.
[NO NEW TESTS NEEDED] - we don't yet have means to test reboots.
Fixes: #14531
```release-note
Fix a bug where system shutdown would be delayed when running health checks on containers running in a systemd unit.
```
> health check: ignore dependencies of transient systemd units/timers

- cmd/podman/common/create.go
- cmd/podman/images/build.go
- docs/source/markdown/options/http-proxy.md
- docs/source/markdown/podman-build.1.md.in
- test/e2e/build_test.go
- test/e2e/run_env_test.go
- test/system/070-build.bats
The remote client should be allowed to specify if the container should be run with the proxy env vars. It will still use the proxy vars from the server process and not the client. This makes podman-remote more consistent with the local version and easier to use in environments where a proxy is required.
Fixes #16520
```release-note
podman-remote build set `--http-proxy` to true by default to match the other commands.
```
> remote: allow --http-proxy for remote clients

- docs/source/markdown/options/secret.md
Add documentation on how the the target option works when adding a secret to a container
Closes: https://github.com/containers/podman/issues/16649
```release-note
None
```
> [CI:DOCS] Clarify secret target behavior

- cmd/podman/images/build.go
- docs/source/markdown/podman-build.1.md
- go.mod
- go.sum
- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/copier/copier.go
- vendor/github.com/containers/buildah/define/build.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/go.mod
- vendor/github.com/containers/buildah/go.sum
- vendor/github.com/containers/buildah/imagebuildah/executor.go
- vendor/github.com/containers/buildah/pkg/cli/build.go
- vendor/github.com/containers/buildah/pkg/cli/common.go
- vendor/github.com/opencontainers/selinux/go-selinux/doc.go
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
- vendor/modules.txt
Bump Buildah to v1.27.3 which itself bumps opencontainers/selinux to 1.10.2, has fixes for the sticky bit, allows containers to be restarted in a pod when they should be, a fix for a RHEL subscription issue,
and s390x segv issues across RHEL 8.7 and 9.1 Zstreams
Addresses:
https://bugzilla.redhat.com/show_bug.cgi?id=2150416 https://bugzilla.redhat.com/show_bug.cgi?id=2150428 https://bugzilla.redhat.com/show_bug.cgi?id=2137294 https://bugzilla.redhat.com/show_bug.cgi?id=2149775 https://bugzilla.redhat.com/show_bug.cgi?id=2152027 https://bugzilla.redhat.com/show_bug.cgi?id=2152017 https://bugzilla.redhat.com/show_bug.cgi?id=2150433 https://bugzilla.redhat.com/show_bug.cgi?id=2150432 https://bugzilla.redhat.com/show_bug.cgi?id=2136928 https://bugzilla.redhat.com/show_bug.cgi?id=2149776 …
> [v4.2-rhel] Bump Buildah to v1.27.3

- hack/parse-localbenchmarks
Go benchmark results include an Average, represented as
<mean> ± <standard deviation>
This is suboptimal for many reasons:
* Some web server somewhere in our CI pipeline (Cirrus?
Google? Gitlab? I have no idea) sends the wrong mime-type
header, rendering the CSV weird-looking in a browser.
Not that it's intended for a browser, but we have to
debug/verify manually once in a while.
* The spaces and +/- makes it less machine-readable.
Solution: split the "Average" field into two: Average, and
Standard Deviation. And, as a courtesy to human readers,
add a new column with SD as a percentage.
```release-note
None
```
> parse-localbenchmarks: separate standard deviation

- cmd/podman/manifest/annotate.go
- pkg/api/handlers/libpod/manifests.go
- pkg/domain/infra/tunnel/manifest.go
- test/apiv2/15-manifest.at
- test/e2e/manifest_test.go
Now that podman manifest annotate is supported
in the remote environment.
```release-note
Now that podman manifest annotate is supported in the remote environment.
```
> Add support for podman-remote manifest annotate

- libpod/container.go
- libpod/container_internal_common.go
- libpod/options.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/volumes.go
- test/e2e/play_kube_test.go
subpath allows for only a subdirecty of a volumes data to be mounted in the container add support for the named volume type sub path with others to follow.
resolves #12929
Signed-off-by: Charlie Doern <cbddoern@gmail.com>
```release-note
add the ability to specify a volume subpath when using named volumes in podman play kube
```
> add support for subpath in play kube for named volumes

- cmd/podman/images/version.go
- test/system/070-build.bats
Fixes: https://github.com/containers/podman/issues/16793
```release-note
podman buildx --version now shows buildah version.
```
> Add podman buildx version support

- .golangci.yml
- pkg/api/handlers/swagger/errors.go
- pkg/api/handlers/swagger/models.go
- pkg/api/handlers/swagger/responses.go
- pkg/machine/e2e/config_init_test.go
golangci-lint is throwing warnings on each run:
WARN [runner] The linter 'xxxxx' is deprecated (since v1.49.0)
due to: The owner seems to have abandoned the linter.
Replaced by unused.
...for xxxxx in deadcode, structcheck, varcheck. Add those three
to the deprecated-linter list, and remove any exceptions from
the code base.
```release-note
None
```
> golangci-lint: remove three deprecated linters

- libpod/container_internal.go
- test/e2e/search_test.go
- test/system/220-healthcheck.bats
When restarting a container, clean up the healthcheck state by removing the old log on disk.  Carrying over the old state can lead to various issues, for instance, in a wrong failing streak and hence wrong behaviour after the restart.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2144754
```release-note
Clean up old healthcheck state during container restart.
```
> [v4.3.1-rhel] container restart: clean up healthcheck state

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/readwrite.container
This is another case where we're diverging from the defaults in podman.
```release-note
None
```
> quadlet: Default VolatileTmp to off

- docs/source/markdown/options/mount.md
- libpod/container_internal_common.go
- libpod/container_internal_test.go
Now that the OCI runtime specs have support for idmapped mounts, let's use them instead of relying on the custom annotation in crun.
Also add the mechanism to specify the mapping to use.  Pick the same format used by crun so it won't be a breaking change for users that are already using it.
```release-note
None
```
> libpod: use OCI idmappings for mounts

- libpod/pod_api.go
- test/system/700-play.bats
Init containers are removed once they exit, but podman reports and error that the container does not exist, when it was previously removed.  Stop reporting missing containers when removing.
```release-note
Podman will stop reporting errors on short lived init containers in pods.
```
> stop reporting errors removing containers that don't exist

- cmd/podman/common/create.go
Fixes: #16845
```release-note
List supported pull policies in the help message of podman-{create,run}.
```
> create/pull --help: list pull policies

- .cirrus.yml
- DOWNLOADS.md
- Makefile
- README.md
Fixes: https://github.com/containers/podman/issues/15960
```release-note
None
```
> [CI:BUILD] Add dedicated DOWNLOAD doc w/ links to bins

- pkg/api/handlers/compat/images_build.go
- test/apiv2/10-images.at
- test/e2e/search_test.go
Docker's newer clients popuates `cacheFrom` and `cacheTo` parameter by default as empty array for all commands but buildah's design of distributed cache expects this to be a repo not image hence parse only the first populated repo and igore if empty array.
```release-note
compat,build: make compat build api functional
```
Backport of https://github.com/containers/podman/pull/16380
> [release-v4.3.1-rhel] compat,build: handle docker's preconfigured `cacheTo`,`cacheFrom`

- docs/source/markdown/podman-machine-init.1.md
- pkg/machine/qemu/machine.go
On Mac machines security model none works, while "mapped-xattr"
causes symlinks to not work.
Update docs/source/markdown/podman-machine-init.1.md
Related: https://github.com/containers/podman/discussions/16102
Co-authored-by: Tom Sweeney <tsweeney@redhat.com>
Signed-off-by: Sorin Sbarnea <sorin.sbarnea@gmail.com>
```release-note
Security model on MacOS changed to "none"
```
Replaces: https://github.com/containers/podman/pull/16261
> Make qemu security model none 

- pkg/rootless/rootless_linux.c
- test/system/950-auth-scripts.bats
whenever the podman process is launched, it runs any file found in
these directories:
- /etc/containers/auth-scripts
- /usr/libexec/podman/auth-scripts
The current podman command line is passed as arguments to the
process.
If any of the processes fail, the error is immediately reported back
from podman that exits with the same error code.
[NO NEW TESTS NEEDED] requires a system-wide configuration.
```release-note
None
```
> rootless: add cli validator

- libpod/container_inspect.go
- libpod/networking_common.go
- libpod/pod_api.go
- libpod/util.go
- pkg/api/handlers/compat/containers.go
- test/apiv2/python/rest_api/test_v2_0_0_container.py
The docker API doesn't list exposed, but unmapped ports in `HostConfig.PortBindings`. Podman lists them with a value of `null`. This PR changes this behaviour to also omit them completely.
This is required for https://github.com/testcontainers/testcontainers-java/pull/6158
```release-note
None
```
> api: remove unmapped ports from PortBindings

- Makefile
- pkg/systemd/quadlet/podmancmdline.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.container
- test/e2e/quadlet/basic.volume
- test/e2e/quadlet_test.go
This makes quadlet respect the PODMAN env var (useful for tests) as well as using the proper podman binary installed by the build in $BINDIR. Some of the changes also had to be changed to support the changed podman binary name in the generated files.
This is a preparation for the changes in https://github.com/containers/podman/pull/16825 which has to wait for Ed to get back, but we would like to get the preparatory changes in now as they conflict with other outstanding things.
```release-note
None
```
> Quadlet handle podman binary name better

- cmd/podman/containers/wait.go
- docs/source/markdown/podman-wait.1.md.in
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/system/055-rm.bats
In the recent past, I met the frequent need to wait for a container to exit that, at the same time, may get removed (e.g., system tests in [1]).
Add an `--ignore` option to podman-wait which will ignore errors when a specified container is missing and mark its exit code as -1.  Also remove ID fields from the WaitReport.  It is actually not used by callers and removing it makes the code simpler and faster.
Once merged, we can go over the tests and simplify them.
[1] github.com/containers/podman/pull/16852
```release-note
Add a new --ignore option to podman-wait.
```
> wait: add --ignore option

- libpod/events/journal_linux.go
- test/python/docker/compat/test_containers.py
When labels map is too big we may get syslog entry truncated.
This breaks JSON parsing making event loading impossible.
```
ERRO[0016] Unable to decode event: unexpected end of JSON input
```
By default the limit is 64KiB, this PR set it to 0 == unlimited.
```release-note
fix: increased event syslog deserialization buffer 
```
related to:
* https://github.com/containers/podman/issues/16834
* https://github.com/containers/container-selinux/pull/196
> fix: event read from syslog when syslog entry too long

- contrib/systemd/system/podman-kube@.service.in
Use the new `podman kube {down,play}` commands.
[NO NEW TESTS NEEDED] as this is a purely cosmetic change.
```release-note
None
```
> podman-kube@ template: use `podman kube`

- libpod/boltdb_state.go
- libpod/container_internal_common.go
- libpod/state.go
- pkg/checkpoint/checkpoint_restore.go
- test/system/520-checkpoint.bats
With the 4.0 network rewrite I introduced a regression in 094e1d70dee1. It only covered the case where a checkpoint is restored via --import. The normal restore path was not covered since the static ip/mac are now part in an extra db bucket. This commit fixes that by changing the config in the db.
Note that there were no test for --ignore-static-ip/mac so I added a big system test which should cover all cases (even the ones that already work). This is not exactly pretty but I don't have to enough time to come up with something better at the moment.
Fixes #16666
```release-note
Fix `podman container restore --ignore-static-ip` and `--ignore-static-mac` options when restoring a normal container, i.e without `--import`. 
```
> checkpoint restore: fix --ignore-static-ip/mac

- libpod/boltdb_state.go
- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/container_validate.go
- libpod/define/container_inspect.go
- libpod/define/pod_inspect.go
- libpod/networking_common.go
- libpod/networking_freebsd.go
- libpod/networking_linux.go
- libpod/networking_unsupported.go
- libpod/options.go
- pkg/api/server/register_networks.go
- pkg/bindings/network/network.go
- pkg/bindings/network/types.go
- pkg/domain/infra/runtime_libpod.go
- pkg/machine/ignition.go
- pkg/specgen/namespaces.go
We should have done this much earlier, most of the times CNI networks just mean networks so I changed this and also fixed some function names. This should make it more clear what actually refers to CNI and what is just general network backend stuff.
```release-note
None
```
> libpod: remove CNI word were no longer applicable

- libpod/oci_conmon_common.go
- test/apiv2/20-containers.at
- test/apiv2/python/rest_api/test_v2_0_0_container.py
When we read logs there can be full or partial lines, when it is full we need to append a newline, thus the message length must be incremented by one.
Fixes #16856
```release-note
Fix a bug in the http attach endpoint where it would return an incorrect length when it was reading logs.
```
> libpod: fix header length in http attach with logs

- pkg/domain/infra/abi/images.go
- test/deny.json
- test/e2e/push_test.go
Override the signature policy to always allow pushing images from local storage, even if the default policy is set up to always disallow reading images from any location.  Fixes OCPBUGS-2383.
Pay attention to the --signature-policy option in `podman push`, so that we can test this properly.
```release-note
`podman push` no longer ignores the hidden `--signature-policy` flag.
```
> Always allow pushing from containers-storage

- docs/source/markdown/podman-network-create.1.md
On the last example of the page there a `#` instead of `$` like the other ones.
Signed-off-by: Luís Henrique Faria <luish.faria@gmail.com>
None
> [CI:DOCS] Fix typo on network docs

- pkg/systemd/quadlet/podmancmdline.go
- podman.spec.rpkg
This fixes some minor packaging issues of quadlet in the rpm specfile.
```release-note
None
```
> Quadlet packaging fixes

- cmd/quadlet/main.go
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.network
- test/e2e/quadlet/disable-dns.network
- test/e2e/quadlet/driver.network
- test/e2e/quadlet/gateway.less-subnet.network
- test/e2e/quadlet/gateway.network
- test/e2e/quadlet/gateway.no-subnet.network
- test/e2e/quadlet/internal.network
- test/e2e/quadlet/ipam-driver.network
- test/e2e/quadlet/ipv6.network
- test/e2e/quadlet/label.network
- test/e2e/quadlet/network.kube
- test/e2e/quadlet/network.quadlet.container
- test/e2e/quadlet/network.quadlet.kube
- test/e2e/quadlet/options.multiple.network
- test/e2e/quadlet/options.network
- test/e2e/quadlet/range.less-subnet.network
- test/e2e/quadlet/range.network
- test/e2e/quadlet/range.no-subnet.network
- test/e2e/quadlet/subnet-trio.multiple.network
- test/e2e/quadlet/subnet-trio.network
- test/e2e/quadlet/subnets.network
- test/e2e/quadlet_test.go
Support `.network` files to create a systemd service that runs `podman network create`
Support networks with `.network` suffix in Container and Kube to link with Quadlet created networks 
Add E2E Tests
Yes
```release-note
Quadlet: allow users to create podman networks using quadlet and link them to services created via .container and .kube files
```
Resolves: #16596
> Quadlet: add network support

- cmd/podman/machine/list.go
- cmd/podman/networks/list.go
- cmd/podman/pods/ps.go
- cmd/podman/secrets/list.go
- cmd/podman/volumes/list.go
- docs/source/markdown/.gitignore
- docs/source/markdown/options/noheading.md
- docs/source/markdown/podman-image-trust.1.md.in
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-machine-list.1.md.in
- docs/source/markdown/podman-network-ls.1.md.in
- docs/source/markdown/podman-pod-ps.1.md.in
- docs/source/markdown/podman-secret-ls.1.md.in
- docs/source/markdown/podman-volume-ls.1.md.in
- test/e2e/secret_test.go
- test/system/160-volumes.bats
- test/system/200-pod.bats
- test/system/500-networking.bats
Helps with https://github.com/containers/podman/issues/16536
```release-note
Support for -n on all listing commands with --noheading option
```
> Unify --noheading and -n to be consistent on all commands

- docs/source/markdown/podman-container-inspect.1.md.in
- pkg/specgen/generate/namespaces_linux.go
- pkg/specgen/generate/oci_freebsd.go
- pkg/specgen/generate/oci_linux.go
- pkg/specgenutil/specgen.go
- test/e2e/run_test.go
- test/system/710-kube.bats
False is the assumed value, and inspect and podman generate kube are being cluttered with a ton of annotations that indicate nothing.
```release-note
podman container inspect and podman kube generate will no longer list default annotations set to false.
```
> Stop recording annotations set to false

- libpod/runtime.go
- pkg/rootless/rootless_linux.go
always create a user namespace when running with euid != 0 since the
user is not owning the current mount namespace.
This issue happened on a Kubernetes cluster, where the pod was running
privileged but the UID was not 0, as it was configured in the image
itself.
[NO NEW TESTS NEEDED] this is useful only on Kubernetes
```release-note
A user namespace is always created when running with EUID != 0.  This is necessary to work in a Kubernetes environment where the POD is "privileged" but it is still running with a non-root user.
```
> rootless: always create userns with euid != 0

- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/network.go
While analyzing https://github.com/containers/podman/issues/15367 I read a lot of the code in pkg/domain/infra/abi. I found it to be quite hard to read and saw lot's of redundancy. This PR refactors looking up containers in a way that it's easy to add new features, and it paves the way to add the "ignore" semantics there directly.
Please refer to the individual commit messages for details.
```release-note
None
```
> Refactor looking up containers in pkg/domain/infra abi

- cmd/podman/containers/export.go
- libpod/container_api.go
- libpod/container_internal.go
- pkg/api/handlers/compat/containers_export.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/apiv2/25-containersMore.at
This allows use to use STDOUT directly without having to call open again, also this makes the export API endpoint much more performant since it no longer needs to copy to a temp file.
I noticed that there was no export API test so I added one.
And lastly opening /dev/stdout will not work on windows.
Fixes #16870
```release-note
Fix a problem with podman export on MacOS and windows where it could not export to STDOUT. 
```
> export: use io.Writer instead of file

- Makefile
- contrib/systemd/system/podman-clean-transient.service.in
- podman.spec.rpkg
This is a unit that can be enabled when using transient store mode to clean up potential leftovers from previous boots. All it does is run "podman system prune --external" once each boot.
```release-note
Added a systemd unit file that is useful for transient storage mode cleanup
```
> Add podman-clean-transient.service service

- pkg/systemd/parser/unitfile.go
- pkg/systemd/quadlet/podmancmdline.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/readwrite-notmpfs.container
- test/e2e/quadlet/readwrite.container
The ReadOnly and the RunInit keys affect options that have a variable default (configurable in containers.conf). This means we need to handle them a bit differently in quadlet to allow overriding the default. For example, we can't assume `ReadOnly=false` doesn't need to add any argument because no argument may mean read-only is enabled if the default is changed.
We now don't add any argument (leaving the default) if the key is not specified, or we always add an argument (`--foo` or `--foo=false`) if the key is specified (overriding whatever the default is).
```release-note
None
```
> quadlet: Handle booleans that have defaults better

- hack/bats
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/oneshot.container
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
These just run once and are considered successful at exist. Not much is needed to support it, but we have to avoid overwriting the type with Type=notify.
```release-note
None
```
> quadlet: Support Type=oneshot container files

- contrib/pkginstaller/scripts/postinstall
this runs the /opt/podman/bin/podman-mac-helper install in the postinstall script
Fixes #16547 
```release-note
- macOS pkg installer now installs the podman-mac-helper tool by default
```
> pkginstaller: install podman-mac-helper by default

- libpod/container_internal.go
- libpod/container_internal_test.go
This means we store things like config.json and the secret files also on tmpfs, lowering wear on disk and leaving less stuff on disk on an unclean shutdown.
This was originally in the initial transient store PR, but I removed because it triggered some test failures. Lemme see now if we can figure those out in isolation.
```release-note
None
```
> When in transient store mode, use rundir for bundlepath

- cmd/podman/containers/cleanup.go
- test/system/620-option-conflicts.bats
...make sure podman rejects being called with incompatible options
Replaces: https://github.com/containers/podman/pull/16813
Which is stuck in CI and Ed is on break.
```release-note
None
```
> New system tests for conflicting options

- pkg/specgen/generate/kube/kube.go
- test/e2e/play_kube_test.go
I made two changes in this PR.
First, I add the kube startup probe support. Since the container startup probe has already been merged (#13909), I think we can make `kube play` also support this feature.
Second, I change the implementation of the "command probe".
The current command probe implementation doesn't have the same behavior  with k8s; for example:
```yml
livenessProbe:
exec:
command:
- /bin/sh
- -c
- curl -f -s localhost:80
```
You will get the following error:
```
{
"Start": "2022-12-09T17:19:12.724152979+08:00",
"End": "2022-12-09T17:19:12.753324336+08:00",
"ExitCode": 1,
"Output": "curl: try 'curl --help' or 'curl --manual' for more information"
}
```
You can use the following yml to reproduce this problem.
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx …
```
> podman play kube support container startup probe

- cmd/podman/system/service_abi.go
Since we open /dev/null to set it as STDIN we can close it after the dup2() call. Using defer is not good enough since this function will never exit since the http server will block. This is not a problem but it reduces the open fds from the service by one.
```release-note
None
```
> podman service: close duplicated /dev/null fd

- docs/source/markdown/options/cpus.container.md
- docs/source/markdown/options/volume.md
Users are surprised when chowning large volumes how long it can take to relabel of chown the entire directory tree. This PR updates the documentation to explain this fact to the user.
Fixes: https://github.com/containers/podman/issues/16575
```release-note
Documenation on relabeling and chowning of volumes enhanced.
```
> [CI:DOCS] Explain that relabeling/chowning of volumes can take along time

- cmd/podman/system/df.go
- test/system/320-system-df.bats
Fixes: https://github.com/containers/podman/issues/16902
```release-note
Improve podman system df --format "{{ json . }}"  format to match docker output 
```
> Output Size and Reclaimable in human form for json output

- Makefile
The PYTHON variable already exists but isn't used for .install.pre-commit PHONY.
```release-note
None
```
> make: Use PYTHON var for .install.pre-commit

- pkg/domain/infra/abi/containers.go
- test/system/055-rm.bats
The function grew into a big hairy ball over time and I personally refrained from touching it as it seemed fragile.  Hence, refactor the function into something more comprehensible and maintainable. There is still potential for improvement but I want to tackle one thing at a time.
[NO NEW TESTS NEEDED] as it shouldn't change behavior.
```release-note
None
```
> infra/abi: refactor ContainerRm

- docs/source/markdown/podman.1.md
:wave: This PR fixes a few typos I noticed when looking at the documentation for transient storage mode [here](https://docs.podman.io/en/latest/markdown/podman.1.html).
```release-note
Fix typos in documentation relating to transient storage mode.
```
> [CI:DOCS]  Fix typos in man page regarding transient storage mode.

- DOWNLOADS.md
- cmd/podman/common/create.go
- cmd/podman/common/create_opts.go
- cmd/podman/containers/create.go
- pkg/api/handlers/compat/containers_create.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/storage.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- pkg/specgenutil/volumes.go
- test/system/030-run.bats
- test/system/700-play.bats
If you are running temporary containers within podman play kube
we should really be running these in read-only mode. For automotive
they plan on running all of their containers in read-only temporal
mode. Adding this option guarantees that the container image is not
being modified during the running of the container.
The containers can only write to tmpfs mounted directories.
> Add containers.conf read-only flag support 

- cmd/podman/machine/init.go
- pkg/machine/e2e/config_init_test.go
Issue #16928 rightly points out that qcow2 images are not used on all podman architectures.
Fixes: #16928
```release-note
None
```
> Remove references to qcow2

- docs/source/markdown/podman-systemd.unit.5.md
In addition, for .container add RemapUidSize and fix Network
No
```release-note
None
```
> [CI:DOCS] Quadlet Doc: Add section for .kube files

- test/system/252-quadlet.bats
> System test: quadlet kube basic test

- pkg/bindings/images/build.go
- test/e2e/build_test.go
podman-remote converts and sends absolute path as context when its an emptydir by adding additional seperator however it should correctly trim the path and not add additional seperator for such use cases.
Closes: **BZ#2145054**
```release-note
podman-remote,bindings: trim context path correctly when its `emptydir`
```
> podman-remote,bindings: trim context path correctly when its `emptydir`

- go.mod
- go.sum
- vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
- vendor/modules.txt
CI in other projects which uses podman is blocked because of missing https://github.com/containers/storage/pull/1455 Update `c/storage` to a747b27 so it contains patch from https://github.com/containers/storage/pull/1455
Closes: https://github.com/containers/crun/pull/1111#issuecomment-1368367699
```release-note
vendor: bump `c/storage` to `a747b27`
```
> vendor: bump `c/storage` to `a747b27`

- test/system/272-system-connection.bats
The test was only waiting for the port to be ready but that doesn't imply the server being ready to serve requests.  Hence, add a loop waiting for the `info` call to succeed.
Fixes: #16916
```release-note
None
```
> fix `podman system connection - tcp` flake

- test/system/255-auto-update.bats
- test/system/260-sdnotify.bats
- test/system/320-system-df.bats
- test/system/build-systemd-image
- test/system/helpers.bash
...based on f37, not f31. And make it fedora-minimal so it's
smaller. And clean up dnf so it's even smaller. And tag it
with our proper YMD tag, and commit the script that builds it.
```release-note
None
```
> Build and use a newer systemd image

- test/system/255-auto-update.bats
- test/system/272-system-connection.bats
In 'run_podman ? ...', the question mark will _usually_ be
interpreted as a literal question mark, meaning "ignore
exit status". But if there are one or more single-character
filenames in the working directory, such as droppings from
a command such as 'my-test-command > a', Very Bad Things
will happen: the test will fail with an incomprehensible
error message. Prevent that.
```release-note
None
```
> System tests: fix unquoted question marks

- test/system/220-healthcheck.bats
- test/system/252-quadlet.bats
New tests got added since I've been on PTO. Some of those tests
weren't doing cleanup, resulting in nasty red logs. Fix.
```release-note
None
```
> [minor] System tests: add missing cleanup

- test/README.md
Let users know they can use hack/bats to control the system tests they are running
No
```release-note
None
```
> [CI:DOCS] Test README - point users to hack/bats

- test/system/252-quadlet.bats
Make sure the Container unit correctly references the volume Start the Container service and not the Volume one Remove the volume
Print the name of the service when status does not match
No
```release-note
None
```
> System Test Quadlet - Volume dependency test did not test the dependency

- docs/tutorials/performance.md
The OverlayFS storage driver is called `overlay`, not `overlayfs`.
Signed-off-by: Patrick Reader <_@pxeger.com>
```release-note
None
```
(I'm assuming that a change this minor doesn't need to be in the release notes)
> [CI:DOCS] Fix instructions about setting storage driver on command-line

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/env-file.container
- test/e2e/quadlet/env-host-false.container
- test/e2e/quadlet/env-host.container
- test/e2e/quadlet_test.go
Add the new keys to the supported keys list for the Container group Pass the list of EnvironmentFile values while maintaining the order Quadlet e2e test framework: Add support for checking regex in Podman args Add relevant tests
Update man
No since Quadlet was not yet released
```release-note
None
```
Resolves: #16730
> Quadlet Container: Add support for EnvironmentFile and EnvironmentHost

- cmd/podman/kube/play.go
- test/system/250-systemd.bats
- test/system/260-sdnotify.bats
- test/system/700-play.bats
If log-driver is not set, set to passthough is service-container is set otherwise use the global default
Update the system tests
- explicitly set logdriver in sdnotify and play tests
- podman-kube template test:  Verify the default log driver for service-container
Yes
```release-note
When using --service-container the default log-driver is now passthrough
```
Resolves: #16592
> Kube Play: use passthrough as the default log-driver if service-container is set

- cmd/podman/common/create.go
- cmd/podman/common/create_opts.go
- docs/source/markdown/options/pids-limit.md
- docs/source/markdown/podman-update.1.md.in
- test/e2e/update_test.go
Adds the functionality for a user to update the PIDs limit for a container. This is one of the tasks listed in #16543. 
Signed-off-by: Jake Correnti <jakecorrenti+github@proton.me>
```release-note
Adds the functionality to update the PIDs limit for a container.
```
> Fixed `podman update --pids-limit`

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/network.quadlet.container
- test/e2e/quadlet/network.quadlet.kube
The name of the network service does not start with systemd only the podman network name
No
```release-note
None
```
> Quadlet Network - Fix the name of the required network service

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- CONTRIBUTING.md
Adding "Bug Report" and "Feature Request" templates, this will help with filing the tickets and also finding the information once filed.
Signed-off-by: Mohan Boddu <mboddu@redhat.com>
```release-note
None
```
> Update the issue templates

- pkg/domain/filters/containers.go
- test/system/160-volumes.bats
Modify the condition in line 149 in order to list container by mounting point.
Closes #16019
Signed-off-by: SamirPS <samir.akarioh@canonical.com>
This PR only permit to fix the issue #16019 
```release-note 
Fix: List container with volume filter
```
> Fix: List container with volume filter

- cmd/quadlet/main.go
- test/e2e/quadlet_test.go
Signed-off-by: Leonardo Rossetti <lrossett@redhat.com>
I've added a `-dyrun` argument to the Quadlet CLI so generated unit files are printed to stdout instead of creating a file - I found this useful when I needed to check how the end result of the generated unit file.
```release-note
Added a -dryrun cli argument to quadlet, making parsed unit files to be printed out to stdout instead of creating files.
```
> Quadlet -dryrun arg

- docs/source/markdown/podman-image-mount.1.md
- docs/source/markdown/podman-image-unmount.1.md
- docs/source/markdown/podman-logs.1.md.in
- docs/source/markdown/podman-unmount.1.md.in
- hack/xref-helpmsgs-manpages
The man-page cross-reference script checks the SEE ALSO section
to confirm that all references are to existing man pages (#12258).
However, it's a little too forgiving: it allows aliases, the
short '.so' files under the 'links/' subdirectory. That means
we could link to non-default command names, and were doing so.
As of this PR, we no longer allow that. Any podman command
referenced in SEE ALSO must be the canonical command name
(and man page). Fix existing non-canonical names, and
remove the exception so we don't allow this again.
See #16848 for discussion of context.
```release-note
None
```
> [CI:DOCS] Man page checker: require canonical name in SEE ALSO

- cmd/podman/kube/play.go
- test/e2e/play_kube_test.go
Fix a bug where kube play would print format errors such as `Error: %!s(<nil>)`.
```release-note
None
```
> kube play: fix the error logic with --quiet

- libpod/container_internal.go
- test/system/055-rm.bats
do not allow removing containers that are in the stopping state, otherwise it can lead to a race condition where a "podman rm" removes the container from the storage while another process is stopping the same container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2155828
```release-note
Fixed a race condition where a container being stopped could be removed from a separate process
```
> libpod: fix race condition rm'ing stopping containers

- .cirrus.yml
- Makefile
- contrib/cirrus/lib.sh
- contrib/cirrus/prebuild.sh
- contrib/cirrus/runner.sh
The hardware used for podman-machine testing is fairly stable/predictable because it's bare-metal.  This is a nearly ideal environment for collection of benchmarking data.  Arrange for that to happen, and the resulting data to be collected.
```release-note
None
```
> Cirrus: Collect benchmarks on machine instances

- libpod/container_internal.go
- test/system/055-rm.bats
do not allow removing containers that are in the stopping state, otherwise it can lead to a race condition where a "podman rm" removes the container from the storage while another process is stopping the same container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2155828
(cherry picked from commit 6886e80b45caae27dda81a9b44d8dd179c414580)
```release-note
Fixed a race condition where a container being stopped could be removed from a separate process
```
> [v4.2.0] libpod: fix race condition rm'ing stopping containers

- pkg/domain/infra/tunnel/containers.go
- test/system/032-sig-proxy.bats
Signals were not proxied for attach and start for podman-remote. Now they are.
Fixes: #16662
```release-note
Sig-proxy is now supported for podman-remote attach and start
```
> Support sig-proxy for podman-remote attach and start

- docs/source/markdown/.gitignore
- docs/source/markdown/options/dir-compress.md
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-save.1.md.in
> [CI:DOCS] Add shared --compress to man pages

- pkg/machine/fedora.go
- pkg/machine/fedora_unix.go
- pkg/machine/fedora_windows.go
Works with both emulated x86_64  and native arm64 binaries (Windows includes a userspace emulation facility for x86 compatibility).
The underlying distro is hosted and generated by:
https://github.com/containers/podman-wsl-fedora-arm
Subsequent PRs will introduce native arm artifacts, including through the installer. However, these are not required since the existing x86 binaries will run after this PR.
Also note there is a minor installer issue, where it will direct the user to install WSL manually. A follow-up PR will address this.
```release-note
Add initial support for Windows on ARM64
```
> Add support for Windows on ARM64

- docs/source/markdown/options/volume.md
- pkg/domain/infra/abi/containers.go
- test/e2e/run_transient_test.go
Fixes: https://github.com/containers/podman/issues/16961
```release-note
Improved man pages describing volume options. 
```
> [CI:DOCS] Describe copy volume options

- test/e2e/run_volume_test.go
When SELinux is running in enforcing mode,
this test needs to add an suffix :Z to the volume mount.
```release-note
None
```
> e2e: fix run_volume_test

- hack/markdown-preprocess
Some (?) Python versions assume that text files are encoded as 7-bit ASCII and abort when encountering other encoding. Some of podman's markdown documentation files are encoded as UTF-8, and this needs to be specified explicitly when opening files.
Closes https://github.com/containers/podman/issues/16996.
Signed-off-by: Erik Schnetter <schnetter@gmail.com>
```release-note
None
```
In principle one could add a CI test for this (by investigating which Python versions or setups fail or succeed, and by running a test with one of these versions). This seems quite tedious and likely not worth the effort.
> [CI:DOCS] Preprocess files in UTF-8 mode

- libpod/container_log.go
- libpod/container_log_linux.go
- libpod/events/journal_linux.go
- test/system/035-logs.bats
see individual commits for details, I recommend you review this commit by commit and not the full diff at once.
```release-note
Fixed a bug where podman logs --since --follow would not follow and just exit with the journald driver.
Fixed a bug where podman logs --until --follow would not exit after the given until time.
The journald driver for both events and logs is now more efficient when --since is used, it will now seek directly to the correct time instead of reading all entries from he journal.
```
> several podman logs fixes

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
add a new failblock style, with light red background all across
the entire page, and use it for bats "FAIL" blocks.
Also highlight logrus level=(debug|info|warning|error|fatal)
messages in increasingly prominent styles
Also refactored a cluttery `print` sequence, because I thought I'd
be using it for this prettification. Turns out I didn't, but the
refactoring (first commit) still seems worth keeping.
```release-note
None
```
> logformatter: nicer formatting for bats failures

- Makefile
Updates win-sshproxy.exe to 0.5.0 to address issue reported in #16656
This PR solely addresses Windows, since Mac relies on an external package. The mac installer and the brew formula will require separate PRs against their respective repos. 
```release-note
Fixes output truncation with non-interactive `docker run` when using Docker Clients on Mac and Windows
```
> Update win-sshproxy to 0.5.0 gvisor tag

- libpod/container_api.go
in several top-level API functions. These are the first line of the function that contains them, which makes sense; we want to capture any error returned by the function. However, making this the first defer means that it is the last thing to run after the function returns - meaning that the container's `defer c.lock.Unlock()` has already fired, leading to a chance we modify the container without holding its lock.
We could move the function around so it's no longer the first defer, but then we'd have to call it twice (immediately after `defer c.lock.Unlock()` if the container is not batched, and a second time in a new `else` block right after the lock/sync call to make sure we handle batched containers). Seems simpler to just leave it like this.
[NO NEW TESTS NEEDED] Can't really test for …
> Fix a potential defer logic error around locking

- libpod/container_api.go
if the container has no pid namespace, they are not killed when the container process ends.  In this case, attempt to kill them in the same way.
The problem was noticed with toolbox where the exec'ed sessions are not terminated when the container is stopped, blocking the system shutdown.
```release-note
When a container that runs with --pid=host is terminated, Podman sends a SIGKILL to all the active exec sessions
```
> oci: terminate all container processes on cleanup

- go.mod
- go.sum
- test/e2e/network_test.go
- vendor/github.com/containers/common/libnetwork/cni/network.go
- vendor/github.com/containers/common/libnetwork/netavark/const.go
- vendor/github.com/containers/common/libnetwork/netavark/network.go
- vendor/modules.txt
```release-note
Network Lock file moved from network config directories to /run directory.
```
> Vendor in latest containers/common

- libpod/runtime_ctr.go
- libpod/service.go
- test/system/700-play.bats
Do not allow for removing the service container unless all associated
pods have been removed.  Previously, the service container could be
removed when all pods have exited which can lead to a number of issues.
Now, the service container is treated like an infra container and can
only be removed along with the pods.
Fixes: #16964
```release-note
Fix a bug where a pod couldn't be removed if its service container did not exist anymore.
```
> remove service container _after_ pods

- pkg/specgen/generate/oci_linux.go
- test/system/030-run.bats
if /sys is bind mounted from the host then also add an explicit mount for /sys/fs/cgroup so that 'ro' is honored.
```release-note
None
```
> linux: add /sys/fs/cgroup if /sys is a bind mount

- libpod/oci_conmon_common.go
- libpod/runtime_ctr.go
- test/system/055-rm.bats
follow-up to 6886e80b45caae27dda81a9b44d8dd179c414580
when "podman -rm -f" is used on a container in "stopping" state, also make sure it is terminated before removing it from the local storage.
```release-note
now podman rm -f also terminates containers in "stopping" state
```
> podman: podman rm -f doesn't leave processes

- libpod/oci_conmon_linux.go
- libpod/runtime_ctr.go
- test/system/055-rm.bats
follow-up to 6886e80b45caae27dda81a9b44d8dd179c414580
when "podman -rm -f" is used on a container in "stopping" state, also
make sure it is terminated before removing it from the local storage.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2155828
(cherry picked from commit 4cf06fe7e074cb9a09670f8308ade12f30bb958d)
```release-note
now podman rm -f also terminates containers in "stopping" state
```
> [v4.2.0-rhel] podman: podman rm -f doesn't leave processes

- cmd/podman/kube/play.go
- docs/source/markdown/podman-kube-play.1.md.in
- pkg/api/handlers/libpod/kube.go
- pkg/bindings/kube/types.go
- pkg/bindings/kube/types_play_options.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/tunnel/kube.go
- test/e2e/play_kube_test.go
Yes
```release-note
Kube Play - Add --publish flag to set or override port publishing
```
> Kube Play - allow setting and overriding published host ports

- contrib/pkginstaller/Makefile
This PR is the Mac installer portion of #16656
Windows is already handled by #17023 (merged)
Two more pieces remain (external repos)
1. brew package formula
2. rpm specfile for Linux
```release-note
NONE
```
> Update Mac installer to use gvproxy v0.5.0

- cmd/podman/root.go
- test/system/001-basic.bats
If the run errors, cobra does not execute post runs.  It is a somehow
known issue (https://github.com/spf13/cobra/issues/914) but problematic
for Podmand as the runtime is shutdown during post run.
Since some commands overwrite the post run and a general lack in cobra
of post runs on errors, move the shutting down the engines directly into
Execute.  Fixing the issue may fix a number of flakes.
Note that the shutdowns are NOPs for the remote client.
```release-note
Fix a bug where the runtime was not shutdown correctly on error.
```
> cobra: move engine shutdown to Execute

- pkg/api/handlers/compat/images_build.go
- test/apiv2/10-images.at
This is a backport of #16380 which also impacts podman 4.2, while I initially wrongly assumed the problem was only in podman >= 4.3. It seems we in Amadeus have upgraded our build machine during the holiday season and first day of 2023 many of our builds were broken. I have already internally patched podman, repackaged it, and pushed our own Amadeus podman to all our machine, but I wish to make this fix more official and shipped by Red Hat directly.
I have effectively cherry-picked the commit taken from the 4.3 backport done by @flouthoc in #16822.
Note, for the tracking side, I had opened a Red Hat case for the backport to branch 4.3. It was Red Hat customer case 03387104. This lead to the creation of this bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2152516
No …
> [release-v4.2.0-rhel] compat,build: handle docker's preconfigured cacheTo,cacheFrom

- contrib/cirrus/logformatter
This is to help me in my flake analysis.
Scenario: I'm looking at recent flakes, and see Flake X. I know
that Flake X was "fixed" two weeks ago. Did the fix not work?
Or is this just one of those PRs that was created three weeks
ago (or three months ago) and never rebased to pick up the fix?
This adds a one-click way for me to tell.
```release-note
None
```
> logformatter: include base SHA, with history link

- test/e2e/common_test.go
- test/e2e/run_networking_test.go
Much as we'd love to eat our dogfood, podman.io is not hosted
on reliable infrastructure; redhat.com is. Let's see if this
gets rid of CI flakes.
Closes: #17044
```release-note
None
```
> Network tests: ping redhat.com, not podman.io

- pkg/machine/qemu/options_windows_amd64.go
- pkg/machine/qemu/options_windows_arm64.go
These changes are extracted from #16872 draft. arm64 will not be supported as QEMU machine host, because there is no QEMU for that arch on Windows, but it will be needed to compile remote client on that arch (alternative is to introduce a bigger refactoring around machine related code).
Using "w" suffixed versions of QEMU binaries for correct background process handling and not bind it to lifecycle of command prompt window. Stub for arm64 version added to fix compilation issues of this target, when QEMU machine will be finally enabled.
Signed-off-by: Arthur Sengileyev <arthur.sengileyev@gmail.com>
```release-note
None
```
> Updated options for QEMU on Windows hosts

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/configmap.kube
- test/e2e/quadlet_test.go
For each instance of ConfigMap pass the path via --configmap Add tests
Add to doc
No
```release-note
None
```
> Quadlet: Add support for ConfigMap key in Kube section

- contrib/cirrus/win-installer-install.ps1
- contrib/cirrus/win-installer-main.ps1
Recent intermittent connectivity failures to the chocolatey repo caused a number of jobs to fail. This PR improves the robustness of the task in case this happens in the future.
```release-note
NONE
```
> Introduce pkg retry logic in win installer verify task

- test/system/252-quadlet.bats
- test/system/helpers.systemd.bash
> System tests: quadlet network test

- .cirrus.yml
> [v4.2.0-rhel] Cirrus: Strip only-main CI tasks

- .cirrus.yml
> [v4.3.1-rhel] Cirrus: Strip only-main CI tasks

- test/e2e/play_kube_test.go
When SELinux is enabled, e2e test could be failed
due to run a ls command in a running container.
```release-note
None
```
> e2e: fix play_kube_test

- cmd/podman/parse/net.go
- libpod/define/config.go
- libpod/options.go
- pkg/bindings/images/build.go
- pkg/systemd/quadlet/quadlet.go
Every podman command is paying the price for this compile even when they don't use the Regex, this will speed up start of podman by a little.
Existing tests should catch issues.
```release-note
None
```
> Compile regex on demand not in init

- pkg/api/handlers/compat/containers_create.go
- test/apiv2/20-containers.at
- test/apiv2/containers.host-netns.conf
Fixes #16915 (only the part about docker client).
```release-note
When creating a container with the Docker API, the `NetworkMode=default` is no longer rewritten to `NetworkMode=bridge` if the `containers.conf` configuration file overwrites `netns`.
```
> [docker compat] Don't overwrite the NetworkMode from "default" to "bridge" if containers.conf specifies a non-default configuration.

- pkg/util/utils_linux.go
- test/system/030-run.bats
While mounting virtual terminal devices in a systemd container is a
recipe for disaster (I experienced it first hand), mounting serial
console devices, modems, and others should still be done by default
for privileged systemd-based containers.
Closes #16925.
Fixes: 5a2405ae1b3a ("Don't mount /dev/tty* inside privileged...")
Signed-off-by: Martin Roukala (né Peres) <martin.roukala@mupuf.org>
```release-note
Privileged containers running systemd will once again mount /dev/tty* devices into the container, ignoring virtual terminals (/dev/tty[0-9]+) (https://github.com/containers/podman/issues/16925).
```
> Only prevent VTs to be mounted inside privileged systemd containers

- pkg/specgen/generate/kube/volume.go
Updates the error message for supported volume sources to include `Secret`
> Updated error message for supported VolumeSource types

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/ports.kube
- test/e2e/quadlet/ports_ipv6.kube
- test/e2e/quadlet_test.go
Move the handling of Publish key to a method
use --publish instead of -p
Use the new method for both .container and .kube files Adjust .container tests
Add .kube tests
Update the man page
No
```release-note
None
```
Resolves: #16595
> Quadlet Kube - add support for PublishPort key

- libpod/service.go
- test/system/700-play.bats
While manually playing with --service-container, I encountered a number of too verbose logs.  For instance, there's no need to error-log when the service-container has already been stopped.
For testing, add a new kube test with a multi-pod YAML which will implicitly show that #17024 is now working.
Fixes: #17024
```release-note
None
```
> service container: less verbose error logs

- libpod/container_internal.go
- test/e2e/run_test.go
The StoppedByUser variable indicates that the container was requested to stop by a user. It's used to prevent restart policy from firing (so that a restart=always container won't restart if the user does a `podman stop`. The problem is we were setting it *very* late in the stop() function. Originally, this was fine, but after the changes to add the new Stopping state, the logic that triggered restart policy was firing before StoppedByUser was even set - so the container would still restart.
Setting it earlier shouldn't hurt anything and guarantees that checks will see that the container was stopped manually.
Fixes #17069
```release-note
Fixed a bug where containers with a restart policy set could still restart even after a manual `podman stop`.
```
> Set StoppedByUser earlier in the process of stopping

- contrib/cirrus/CIModes.md
- contrib/cirrus/lib.sh
On occasion, developers need to run the latest or bleeding-edge netavark/aardvark-dns in the podman CI environment.  Enable this through use of magic strings in the PR title, but only if the PR is marked as a draft.  The intent being, when the PR is ready for review, the current CI VM package versions will be used.  Hopefully also reminding the PR author to remove the magic strings from the title.
```release-note
None
```
> [CI:DOCS] Cirrus: Support using updated/latest NV/AV in PRs

- test/e2e/play_kube_test.go
Do not test using an unreliable UDP connection
No
```release-note
None
```
Resolves: #17101
> E2E Tests: Use inspect instead of actual data to avoid UDP flake

- test/system/700-play.bats
The test file was a rat's nest of long complicated yaml strings
all differing only slightly. Clean it up, by adding a helper
function with optional parameters.
```release-note
None
```
> podman-play system test: refactor

- .cirrus.yml
There's no reason to maintain this task on a release-branch.  The environment is managed by Cirrus, no us.  Nobody will ever need/want/try to cross-compile an old podman version with the latest environment. Just remove the test.
```release-note
None
```
> [v4.1.1-rhel] [CI:BUILD] Cirrus: Stop building for OSX

- test/system/250-systemd.bats
Increase the loop range from 5 to 20 to make sure we give the service enough time to transition to inactive.  Other tests have the same range with 0.5 seconds sleeps, so I expect the new value to be sufficient and consistent.
Fixes: #17093
```release-note
None
```
> fix flake in kube system test

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
See: https://github.com/containers/podman/pull/16766#issuecomment-1378696111
```release-note
- Limit replicas to one when creating pods/containers from kubernetes YAML
```
This fixes: https://github.com/containers/podman/issues/16765
cc @vrothberg
> Warn about creating multiple replicas from kubernetes YAML

- pkg/domain/infra/abi/play.go
- test/system/700-play.bats
Make sure that the specs of containers generated by `kube play` are correctly completed.  They have not before which surfaced in default environment variables not being set.
Fixes: #17016
```release-note
Fix a bug in `kube play` where default environments variables have not been applied to containers.
```
> kube play: complete container spec

- .cirrus.yml
Prior to this commit, the podman-machine tests only ran for PRs. However, now that these tasks are also being used to capture a uniform set of performance benchmarks, they should probably run on branches as well.  This also fixes a stream of branch-CI run failures due to the artifacts-task failing to download/archive (missing) benchmark data.
```release-note
None
```
> Cirrus: Run machine tests on PR merge

- libpod/oci_conmon_common.go
- libpod/runtime_ctr.go
The container lock is released before stopping/killing which implies
certain race conditions with, for instance, the cleanup process changing
the container state to stopped, exited or other states.
The (remaining) flakes seen in #16142 and #15367 strongly indicate a
race in between the stopping/killing a container and the cleanup
process.  To fix the flake make sure to ignore invalid-state errors.
An alternative fix would be to change `KillContainer` to not return such
errors at all but commit c77691f06f61 indicates an explicit desire to
have these errors being reported in the sig proxy.
[NO NEW TESTS NEEDED] as it's a race already covered by the system
tests.
Fixes: #16142
Fixes: #15367
```release-note
Fix a race condition when …
```
> container kill: handle stopped/exited container

- docs/tutorials/mac_win_client.md
- docs/tutorials/podman-for-windows.md
Fix failures on `main`: https://cirrus-ci.com/task/5760364537708544?logs=main#L4216
```
docs/version-check
LATEST=v4.3.1
version-check: docs/tutorials/mac_win_client.md: needs updating.
version-check: Please run this script in an interactive shell, and I'll fix it.
version-check: docs/tutorials/podman-for-windows.md: needs updating.
version-check: Please run this script in an interactive shell, and I'll fix it.
```
```release-note
None
```
> Docs: version-check updates

- docs/source/markdown/options/privileged.md
- docs/source/markdown/options/systemd.md
- pkg/util/utils_linux.go
- test/system/030-run.bats
Until Podman v4.3, privileged rootfull containers would expose all the
host devices to the container while rootless ones would exclude
`/dev/ptmx` and `/dev/tty*`.
When 5a2405ae1b3a ("Don't mount /dev/tty* inside privileged containers
running systemd") landed, rootfull containers started excluding all the
`/dev/tty*` devices when the container would be running in systemd
mode, reducing the disparity between rootless and rootfull containers
when running in this mode.
However, this commit regressed some legitimate use cases: exposing
non-virtual-terminal tty devices (modems, arduinos, serial
consoles, ...) to the container, and the regression was addressed in
f4c81b0aa5fd ("Only prevent VTs to be mounted inside privileged
systemd containers").
This now calls into question why all tty …
> Make rootless privileged containers share the same tty devices as rootfull ones

- .cirrus.yml
OSX builds are no longer done on this branch. Remove them from the artifacts task as well.
```release-note
None
```
DO NOT MERGE until lgtm'd by @cevich
> [v4.1.1-rhel] [CI:BUILD] remove osx task from artifacts

- test/system/032-sig-proxy.bats
...and instrument with 'podman ps'es for debugging failures.
Test flakes pretty regularly in Fedora gating. If the increased
timeout doesn't help, at least we should be able to see if the
container is stopping or failed or something.
Closes: #16091
```release-note
None
```
> sig-proxy system test: bump timeout

- .cirrus.yml
- contrib/cirrus/win-podman-machine-main.ps1
- contrib/cirrus/win-podman-machine-verify.ps1
- contrib/cirrus/wsl-env-launch.ps1
Builds on containers/automation_images#249
Both PRs can be merged independently, but @cevich and @Luap99 are working on automation changes in parallel, so this should be merged in whatever order works best for them. 
Recently Microsoft switched from shipping WSL as part of each OS major version delivery stream to a common synchronized, and more current, one provided by the Windows store. Apps in the Windows Store are sandboxed, either as UWP native apps, or as Desktop bridge/centennial apps as is the case with WSL. Calls to launch their respective executables are intercepted and redirected to setup the appropriate silos and run the true app. However these facilities expect usage from an interactive Windows session.
In addition to user/kernel space separation, Windows has the notion of …
> Refactor windows CI to workaround WSL's recent switch to a Windows Store update stream

- contrib/podmanimage/stable/Containerfile
- contrib/podmanimage/testing/Containerfile
- contrib/podmanimage/upstream/Containerfile
The main goal is to provide ssh-agent, which is required by podman build --ssh.
closes #17117
```release-note
`ssh-agent` is now pre-installed in the podman official image, allowing the use of `podman build --ssh`.
```
> Add openssh-clients to podmanimage

- docs/source/markdown/podman-kube-generate.1.md
- libpod/container_internal_common.go
- libpod/kube.go
- pkg/annotations/annotations.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgenutil/specgen.go
- test/e2e/generate_kube_test.go
- test/system/710-kube.bats
Reserved annotations are used internally by Podman and would effect nothing when run with Kubernetes so we should not be generating these annotations.
Fixes: https://github.com/containers/podman/issues/17105
```release-note
Builtin Annotations will no longer show up in podman kube generate
```
> Remove ReservedAnnotations from kube generate specification

- test/e2e/build_test.go
July 2022: test was flaking on new VM images. We needed new
images, so I filed #15014 and skipped the test.
January 2023: no attention from anyone, so I'll try bumping up
a dd timeout from 10s to 30s. But in the interim, the test
has broken: it used to expect "Containerfile" in output (this
was deliberately added in #13655)... but #16810 changed that
so Containerfile no longer appears. @flouthoc argues that
this too is deliberate (#17059). Okay, so let's change the
test then. All I care about is not adding more regressions.
```release-note
None
```
> e2e tests: reenable long-skipped build test

- libpod/oci_conmon_common.go
Commit 067442b5701f improved stopping/killing a container by detecting
whether the cleanup process has already fired and changed the state of
the container.  Further improve on that by returning early instead of
trying to wait for the PID to finish.  At that point we know that the
container has exited but the previous PID may have been recycled
already by the kernel.
[NO NEW TESTS NEEDED] - the absence of the two flaking tests recorded
in #17142 will tell.
Fixes: #17142
@edsantiago PTAL
@containers/podman-maintainers 
Also did some minor refactoring in the function(s).
```release-note
None
```
> StopContainer: return if cleanup process changed state

- README.md
- cni/README.md
- docs/source/markdown/podman-network.1.md
- docs/source/markdown/podman-unshare.1.md
- docs/source/markdown/podman.1.md
- docs/tutorials/basic_networking.md
Where the terms CNI and cni are used in documentation like man pages, readme's, and tutorials, we have begun to add deprecation notices where applicable. In cases where netavark cannot do what CNI can, those have been left alone.
```release-note
* deprecation notices for CNI added to some documentation including man pages
```
> [CI:DOCS] Add CNI deprecation notices to documentation

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/logcollector.sh
- test/buildah-bud/buildah-tests.diff
- test/buildah-bud/run-buildah-bud-tests
Output from podman system service, on system tests, is
being saved... it just hasn't been collected as an artifact.
Start collecting it. And, remove obsolete-unused-misleading
code that made me think it _was_ being collected.
Also: log system-service output for bud tests
```release-note
None
```
> Cirrus: preserve podman-server logs

- .cirrus.yml
- Makefile
- contrib/cirrus/lib.sh
- contrib/cirrus/logcollector.sh
- contrib/cirrus/runner.sh
- test/e2e/run_networking_test.go
- test/system/505-networking-pasta.bats
Ref: https://github.com/containers/automation_images/pull/246
```release-note
None
```
> update CI images to include pasta

- test/README.md
- test/e2e/common_test.go
- test/e2e/create_staticip_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/libpod_suite_remote_test.go
- test/e2e/libpod_suite_test.go
- test/e2e/network_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_create_test.go
- test/e2e/pull_test.go
- test/e2e/push_test.go
- test/e2e/run_signal_test.go
- test/e2e/run_test.go
- test/e2e/run_userns_test.go
- test/e2e/run_volume_test.go
- test/e2e/save_test.go
- test/e2e/system_reset_test.go
- test/e2e/systemd_activate_test.go
- test/e2e/toolbox_test.go
- test/e2e/unshare_test.go
Unify the functions used to detect rootless to "isRootless()".
This function can detect to join the user namespace by mistake.
```release-note
None
```
> e2e: use isRootless() instead of rootless.IsRootless()

- pkg/domain/infra/abi/network.go
- test/e2e/network_create_test.go
`default` is already used as network mode, i.e. podman run --network default will choose the default mode not a network named `default`.
We already block names from other network modes, default was forgotten.
Fixes #17169
```release-note
`podman network create` no longer accepts `default` as valid name, it is impossible to use this network name in the `podman run/create` command because it was parsed as network mode instead.
```
> network create: do not allow `default` as name

- docs/kubernetes_support.md
- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/play_kube_test.go
Adds support for hostPID in Pod manifest for podman kube play
Closes #17157 
```release-note
- play-kube: add support for hostPID in pod.spec
```
Having some issues running the tests locally, hence the draft for now.
> kube-play: add support for HostPID

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] Change example target to default in doc

- hack/perf/README.md
- hack/perf/create.sh
- hack/perf/helpers.bash
- hack/perf/ps.sh
- hack/perf/rm.sh
- hack/perf/run.sh
- hack/perf/start.sh
- hack/perf/stop.sh
Add a set of scripts using hyperfine for comparing two container engines.  I am currently using the scripts for comparing Podman and Docker, and with older versions of Podman.
These scripts are not meant for production usage but to aid in tracking down performance regressions and bottlenecks.
Run the scripts via `sudo sh $script.sh`.
Use the following environment variables to change the default behavior:
* `ENGINE_A` to set container engine A (default `podman`)
* `ENGINE_B` to set container engine B (default `docker`)
* `RUNS` to change the runs/repetitions of each benchmarks (default `100`)
* `NUM_CONTAINERS` to change the number of created containers for some benchmarks (e.g., `ps`) (default `100`)
* `IMAGE` to change the default container image (default …
> [CI:DOCS] add hack/perf for comparing two container engines

- pkg/ps/ps.go
The user is only reading the config, so creating a copy turns out to be extremely expensive.  With this change, listing containers is 1.39 times faster than before.
[NO NEW TESTS NEEDED] as it is not a functional change.
```release-note
Improve the performance of `podman ps`.
```
> ps: do not create copy of container config

- docs/tutorials/rootless_tutorial.md
mount_program is in storage.options.overlay and not storage.options (see example in storage.conf)
Signed-off-by: Klaus Frank <agowa338@users.noreply.github.com>
```release-note
None
```
> (fix) mount_program is in storage.options.overlay

- libpod/container_internal_common.go
- test/e2e/pod_create_test.go
- test/system/170-run-userns.bats
Fixes: https://github.com/containers/podman/issues/17148
```release-note
Pods with --userns=keep-id will add entry including username to /etc/passwd within container.
```
> Get correct username in pod when using --userns=keep-id

- libpod/container_inspect_linux.go
- test/system/190-run-ipcns.bats
Fixes: https://github.com/containers/podman/issues/17189
```release-note
Fix output of podman inspect to correctly report the IPCMode of containers.
```
> Correct output when inspecting containers created with --ipc

- libpod/runtime_ctr.go
- test/e2e/search_test.go
[EDIT: backport of #14765, requested by @jnovy]
[EDIT: and one small part ( ae9a2d26d ) of #16464 to get e2e tests passing ]
the new version of runc has the same check in place and it automatically resume the container if it is paused.  So when Podman tries to resume it again, it fails since the container is not in the paused state.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2100740
[NO NEW TESTS NEEDED] the CI doesn't use a new runc on cgroup v1 systems.
```release-note
It solves a problem with new runc versions where it is not possible to remove a paused container.
```
> [v4.0-rhel] runtime: unpause the container before killing it

- cmd/podman/volumes/import.go
Fixes #17205
Changes --help **Example:** from `podman import volume` to `podman volume import`.
Signed-off-by: Trevor Benson <trevor.benson@scality.com>
```release-note
None
```
> [CI:DOCS] Example in volume import usage is backwards

- test/apiv2/python/rest_api/test_v2_0_0_container.py
The test was added in commit 1424f0958f6f, it can flake because the
attach test needs the message in the log. On slow CI systems this can
take longer. Add a retry logic which checks the container log every
second for up to 5 seconds. That should be plenty of time.
Fixes #17204
```release-note
None
```
> fix APIv2 python attach test flake

- libpod/healthcheck.go
- pkg/ps/ps.go
Also do not return (and immediately suppress) an error if no health check is defined for a given container.
Makes listing 100 containers around 10 percent faster.
```release-note
None
```
> ps: query health check in batch mode

- RELEASE_NOTES.md
- version/version.go
Release notes and bump to v4.4.0-RC3
```release-note
None
```
> [CI:DOCS] [v4.4] Bump to v4.4.0-RC3

- libpod/kube.go
- test/e2e/generate_kube_test.go
If the image being used has a user set that is a positive integer greater than 0, then set the securityContext.runAsNonRoot to true for the container in the generated kube yaml.
Fixes https://github.com/containers/podman/issues/15231
```release-note
Set runAsNonRoot=true in generated kube yaml when image has user set as a positive integer value.
```
> Set runAsNonRoot=true in gen kube

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/device-copy.volume
- test/e2e/quadlet/device.volume
- test/e2e/quadlet_test.go
The Device, Type, Copy and Options keys are now supported in quadlet  .volume files. This allows users to create filesystem based volumes with quadlets .volume files.
Signed-off-by: Ingo Becker <ingo@orgizm.net>
Resolves: #16896 
No
```release-note
None
```
> quadlet: Add device support for .volume files

- libpod/boltdb_state.go
- libpod/boltdb_state_internal.go
- libpod/container_api.go
- libpod/networking_linux.go
- libpod/runtime.go
- libpod/runtime_ctr.go
- libpod/runtime_img.go
- libpod/runtime_migrate.go
- libpod/runtime_renumber.go
- libpod/state.go
- libpod/state_test.go
- pkg/api/handlers/compat/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/ps/ps.go
Do not sync containers with the runtime and the database when listing containers.  It turns out to be extremely expensive and unnecessary.
The sync was needed since listing all containers from the database did not populate their state.  Doing that, however, is much faster since we already have a connection to the database.
This change makes listing 200 containers 2 times faster than before.
@baude @mheon PTAL, this in combination with yesterday's PR makes listing 200 containers 3 times faster.  I think there is still something left to squeeze.
```release-note
None
```
> ps: do not sync container

- pkg/api/handlers/compat/containers_create.go
This looks like the correct fix, but I have no idea how to test.
Fixes: https://github.com/containers/podman/issues/17106
Will have reporter verify if this fixes the problem.
```release-note
DeviceCgroupRules can now be used over Docker API.
```
> Allow --device-cgroup-rule to be passed in by docker API

- test/e2e/play_kube_test.go
containers/podman/pull/17186 and containers/podman/pull/17201 have been merged at roughly the same time.  Both work fine in isolation but the new kube test breaks in combination.
Fix the IPC kube test to make CI healthy.
```release-note
None
```
> fix CI: test fail due to merge

- test/e2e/common_test.go
"tempdir" in SynchronizedAftersuite and "LockTmpDir" can be removed.
```release-note
None
```
> e2e: Remove some directories at SynchronizedAfterSuite

- cmd/podman/containers/ps.go
- docs/source/markdown/podman-auto-update.1.md.in
- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-ps.1.md
- test/e2e/ps_test.go
Closes #17250
```release-note
Fix `podman ps` STATUS output to say "Up 3 seconds", if the container has been up and running for 3 seconds (removing the word "ago".
```
> fix: don't output "ago" when container is currently up and running

- pkg/machine/wsl/machine.go
If podman is set to the wsl default distribution, the (default) value is appended like podman-machine-default **(default)**.  
``` bat
> wsl --list --running
Linux용 Windows 하위 시스템 배포:
podman-machine-default(default)
```
Because of **(default)**, it determines that podman wsl deployment has not been executed.  
It can be solved simply by outputting only the wsl distribution name with the --quiet option.
``` bat
> wsl --list --running --quiet
podman-machine-default
```
Related to #17227, #17158  
Signed-off-by: shblue21 <jihunkimkw@gmail.com>
```release-note
Fixed a startup issue with podman machine when running under some locales of Windows. 
```
> fix: running check error when podman is default in wsl

- libpod/container_exec.go
- libpod/pod_internal.go
- libpod/runtime_ctr.go
- libpod/runtime_volume_linux.go
- test/e2e/common_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/events_test.go
- test/e2e/network_connect_disconnect_test.go
- test/e2e/network_create_test.go
- test/e2e/network_test.go
- test/e2e/pod_ps_test.go
- test/e2e/ps_test.go
- test/e2e/run_networking_test.go
- test/e2e/run_test.go
Cherry-pick #15788 to v3.0.1-rhel branch per RHBZ 2157930
As part of this, did a separate `git grep` pass to ensure that no instances of GenerateNonCryptoID existed in 3.0.1 that were not present when the original patch was made, which caught around 5 extra occurrances, mostly in tests.
```release-note
NONE
```
> Backport #15788 to v3.0.1-rhel

- test/e2e/common_test.go
If rootless, os.RemoveAll() is failed due to permission denied.
Therefore, we use "podman unshare rm" instead of os.RemoveAll().
---
Related to #17089
```release-note
None
```
> e2e: Remove the cache with "podman unshare rm" when a rootless user

- libpod/container_log_linux.go
- libpod/events/journal_linux.go
I noticed this while running some things in parallel, podman events
would show events from other users. Because all events are written to
the journal everybody can see them. So when we read the journal we must
filter events for only the current UID.
To reproduce run `podman events` as user then in another window create a
container as root for example. After this patch it will correctly ignore
these events from other users.
[NO NEW TESTS NEEDED] I don't think we can test with two users at the same
time.
journald: podman logs only show logs for current user
In the super rare case that there are two containers with the same ID
for two different users, podman logs with the journald driver would show
logs from both containers.
[NO NEW TESTS NEEDED] Impossible to reproduce.
```release-note …
```
> journald: podman events only show events for current user

- cmd/podman/common/create.go
- cmd/podman/common/create_opts.go
- cmd/podman/containers/create.go
- cmd/podman/containers/update.go
- test/e2e/update_test.go
I noticed container creation/run commands on podman remote were printing:
"Resource limits are not supported and ignored on cgroups V1 rootless systems"
The underlying cause was a problem with default handling introduced in the enhancement that added pids-limit for container update operations (479052af)
This also meant that updates for other values would unintentionally change the pids-limit back to the default value. This PR adds a test for that condition as well.
```release-note
none
```
> Fix default handling of pids-limit

- pkg/machine/pull.go
Fixes: #15995
Only assume that http(s) scheme URLs (only ones supported by http.Client anyway) are URLs. Treat everything else as a file path. (Windows paths can look like a URL scheme)
```release-note
Fixed usage of absolute image paths on Windows when specified with --image-path on machine init
```
> Fix usage of absolute windows paths with --image-path

- pkg/machine/ignition_linux.go
> fix #17244: use /etc/timezone where `timedatectl` is missing on Linux

- Makefile
- contrib/msi/podman.wxs
- contrib/win-installer/build.ps1
- contrib/win-installer/podman.wxs
- contrib/win-installer/process-release.ps1
- docs/remote-docs.sh
- docs/tutorials/qemu-remote-tutorial.md
- hack/markdown-preprocess
This adds gvproxy.exe (which is a requirement to use podman with Qemu on windows(https://github.com/containers/podman/issues/13006)) to Windows installers and zip builds.
Included changes:
* ~commit hash reference of gvisor-tap-vsock is bumped to latest (to include unix domain socket support on Windows);~ (was fixed already in upstream)
* wih-sshproxy build step is renamed to gvproxy (to match the repository name);
* gvproxy build step is responsible for both artifacts - win-sshproxy.exe and gvproxy.exe;
* gvproxy.exe added to zip archive;
* gvproxy.exe added to msi build;
* gvproxy.exe added to new Windows installer (unfortunately there is no fallback options as with win-sshproxy.exe, so, for packaging older versions - older version of script will be required);
* fixes for building on …
> Add gvproxy to windows packages

- docs/source/markdown/podman-events.1.md
issues.redhat.com/browse/RHELBU-1918 is mentioning the podman-events man page which are lacking notes on the verbose create events added by commit 71f92d263c7f.
@TomSweeneyRedHat PTAL
```release-note
None
```
> [DOCS:CI] podman-events: document verbose create events

- test/e2e/common_test.go
- test/e2e/config.go
- ImageCacheDir is hard-coded as "/tmp/podman/imagecachedir".
To avoid this hard-coding, I changed it to "os.TempDir()/imagecachedir".
- Change ImageCacheDir permissions from 0777 to 0700.
This directory should be used by per-user.
---
Related to #17089
```release-note
None
```
> e2e: Avoid hard-coding ImageCacheDir

- test/e2e/generate_kube_test.go
- test/e2e/pod_create_test.go
- test/e2e/run_userns_test.go
Ha ha. This was supposed to be a trivial little followup to #17174:
https://github.com/containers/podman/pull/17174#discussion_r1085963780
(safer username check when --userns=keep-id)
It got complicated. TL;DR we need to use User.Username, not User.Name.
The latter is GECOS! Tests were working because, on Fedora, GECOS
for root is "root". Found and fixed all 'u.Name' instances, but
if there are any references with a variable other than 'u', they
still need looking into.
```release-note
None
```
> e2e tests: fix incorrect os.User.Name

- pkg/bindings/errors.go
This should never happen with a consistent client/server, and we are seeing this show up with some hard-to-diagnose flakes: #16154 .
So, log details about failures. After we find the cause, we might remove this extra logging again.
```release-note
Added more (noisy) logging on unexpected remote client data parsing failures, to help debug them.
```
> Log data that we failed to unmarshal

- pkg/machine/pull.go
Cherry-pick of #17266 
```release-note
Fixed usage of absolute image paths on Windows when specified with --image-path on machine init
```
> [v4.4] Fix usage of absolute windows paths with --image-path

- libpod/container_exec.go
- libpod/runtime_ctr.go
Do not save the container each for changing the state and for removing running exec sessions.  Saving the container is expensive and avoiding the redundant save makes `container rm` 1.2 times faster on my workstation.
```release-note
None
```
> container rm: save once for exec removal and state change

- test/e2e/run_staticip_test.go
`http.Get()` could not recognize `no_proxy` with `ginkgo -nodes <any>`.
Therefore, we set `http.Client` not to use a proxy instead of `os.Setenv()`.
Fixes #17135
```release-note
None
```
> e2e: fix run_staticip_test about no_proxy

- hack/perf/bz-2162111.sh
Add a script with reproducers for bugzilla.redhat.com/show_bug.cgi?id=2162111. The results are not much different compared to the already existing scripts.  Podman is faster despite for container removal.
```release-note
None
```
> [CI:DOCS] hack/perf: add script for BZ 216111

- pkg/specgen/generate/ports.go
This PR fixes a small bug which comes from usage of the `--publish-all` command line flag when using `podman container create`. When choosing random ports for each of the exposed ports on the container the offending function did not add each port it was "generating" to the list of used ports. This would (on very rare occasions) cause a collision when two of the same ports were generated. This issue was found in a testing environment which repeatedly stood up containers, an example of the `Ports` portion of a `podman inspect` command run on a container with this issue is shown below:
```json
"Ports": {
"1999/tcp": [
{
"HostIp": "",
"HostPort": "37643"
}
],
"443/tcp": [
{
"HostIp": "",
"HostPort": "37643"
}
],
"444/tcp": [
{
"HostIp": "",
"HostPort": "39563"
}
],
"5432/tcp": [
{
"HostIp": …
```
> [NO NEW TESTS NEEDED] Fixes port collision issue on use of --publish-all

- docs/source/markdown/podman-build.1.md.in
When multiple files are specified buildah considers `FROM` instruction from the last file specified and so does `buildkit` and `docker` so lets specify that in docs.
Similar to: https://github.com/containers/buildah/pull/4546
```release-note
docs: specify order preference for FROM
```
> [CI:DOCS] docs: specify order preference for FROM

- pkg/util/utils_linux.go
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2165875
```release-note
Rootless privileged containers will not mount /dev/tty in the container
```
This PR should superseed https://github.com/containers/podman/pull/17301.
@giuseppe: This should address the regression, without needing to revert the commits (which were themselves fixing a regression).
> Do not mount /dev/tty into rootless containers

- test/system/252-quadlet.bats
...because systemd on RHEL8 is too old, has no -P
```release-note
None
```
> Emergency fix for RHEL8 gating tests

- pkg/util/utils_linux.go
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2165875
```release-note
```
> [4.4] fix regression with runc --privileged rootless containers

- libpod/container_exec.go
- libpod/pod_internal.go
- libpod/runtime_ctr.go
- libpod/runtime_volume_linux.go
- test/e2e/common_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/create_test.go
- test/e2e/diff_test.go
- test/e2e/events_test.go
- test/e2e/network_connect_disconnect_test.go
- test/e2e/network_create_test.go
- test/e2e/network_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_ps_test.go
- test/e2e/ps_test.go
- test/e2e/run_networking_test.go
- test/e2e/run_staticip_test.go
- test/e2e/run_test.go
- test/e2e/volume_exists_test.go
Cherry-pick #15788 to v4.0-rhel branch per RHBZ 2157930
In view of https://github.com/containers/storage/pull/1337, do this:
for f in $(git grep -l stringid.GenerateNonCryptoID | grep -v '^vendor/'); do
sed -i 's/stringid.GenerateNonCryptoID/stringid.GenerateRandomID/g' $f;
done
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
```release-note
none
```
> [v4.0-rhel] all: stop using deprecated GenerateNonCryptoID

- test/system/252-quadlet.bats
quadlet tests were using 'systemctl show -P', a shortcut
that doesn't exist on RHEL8. Translate to old-systemd
language.
And, minor tweaks to make future test diagnosing easier.
This is a frontport of #17311; bringing from release branch
to main. Except that was an emergency, so it was a one-line
fix. This is a better long-term fix, not as trivial to review.
```release-note
None
```
> system tests: minor fix for RHEL8 incompatibility

- libpod/container_exec.go
- libpod/pod_internal.go
- libpod/runtime_ctr.go
- libpod/runtime_volume_linux.go
- test/e2e/common_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/create_test.go
- test/e2e/diff_test.go
- test/e2e/events_test.go
- test/e2e/logs_test.go
- test/e2e/network_connect_disconnect_test.go
- test/e2e/network_create_test.go
- test/e2e/network_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_ps_test.go
- test/e2e/ps_test.go
- test/e2e/run_networking_test.go
- test/e2e/run_staticip_test.go
- test/e2e/run_test.go
- test/e2e/volume_exists_test.go
- test/e2e/volume_plugin_test.go
Cherry-pick #15788 to v4.2.0-rhel branch per RHBZ 2157930
In view of https://github.com/containers/storage/pull/1337, do this:
for f in $(git grep -l stringid.GenerateNonCryptoID | grep -v '^vendor/'); do
sed -i 's/stringid.GenerateNonCryptoID/stringid.GenerateRandomID/g' $f;
done
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
```release-note
None
```
> [v4.2.0-rhel] all: stop using deprecated GenerateNonCryptoID

- test/system/160-volumes.bats
The return code is "126" in the current version of runc.
---
<details>
<summary>podman info</summary>
```
host:
arch: amd64
buildahVersion: 1.27.1
cgroupControllers:
- cpuset
- cpu
- cpuacct
- blkio
- memory
- devices
- freezer
- net_cls
- perf_event
- net_prio
- hugetlb
- pids
- rdma
cgroupManager: systemd
cgroupVersion: v1
conmon:
package: conmon-2.1.4-1.module+el8.7.0+16772+33343656.x86_64
path: /usr/bin/conmon
version: 'conmon version 2.1.4, commit: 691ad93a4898a57af5788c41fa22a45fac3beaae'
cpuUtilization:
idlePercent: 99.63
systemPercent: 0.09
userPercent: 0.28
cpus: 4
distribution:
distribution: '"rhel"'
version: "8.7"
eventLogger: file
hostname: rhel87
idMappings:
gidmap: null
uidmap: null
kernel: 4.18.0-425.3.1.el8.x86_64 …
```
> system tests: fix volume exec/noexec test

- test/system/030-run.bats
when running on a cgroupv1 host validate that the memory controller is mounted ro.
```release-note
None
```
> test: adapt test to work on cgroupv1

- cmd/podman/system/reset.go
- go.mod
- go.sum
- test/e2e/build/cache/Dockerfilecacheread
- test/e2e/build/cache/Dockerfilecachewrite
- test/e2e/build_test.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/pkg/parse/parse.go
- vendor/modules.txt
Just like buildkit buildah must allow cleaning the buildcache and cache generated on host by --mount=type=cache just like buildkit's prune command.
See: https://github.com/moby/buildkit#cache
```release-note
podman system reset: use CleanCacheMount to clear build cache
```
> system-reset: use `CleanCacheMount` to clear build cache

- docs/source/markdown/options/userns.container.md
- pkg/specgen/generate/namespaces.go
- pkg/util/utils.go
- test/e2e/run_userns_test.go
- test/system/170-run-userns.bats
copy the current mapping into a new user namespace, and run into a separate user namespace.
Closes: https://github.com/containers/podman/issues/17337
```release-note
Now --userns=keep-id also works for root containers and it copies the current mapping into a new user namespace
```
> libpod: allow userns=keep-id for root

- libpod/kube.go
- pkg/k8s.io/api/core/v1/types.go
- pkg/specgen/generate/kube/kube.go
- test/system/700-play.bats
- test/system/helpers.bash
```release-note
podman kube generate and play now support SELinux filetype labels.
```
> Handle filetype field in kubernetes.yaml files

- pkg/machine/config.go
- pkg/machine/machine_windows.go
- pkg/machine/wsl/machine.go
Fixes #16860
`PodmanPipe` structure added to `ConnectionConfig`. Named pipe address is not full equivalent of a file, but 1) it can be represented as a UNC path; 2) internally in code it used with `os.Stat` API similar to files; 3) it is logically to add it with the same shape as `PodmanSocket`; 4) it is OS specific, but `PodmanSocket` in the moment of introduction was also OS specific and was present in Windows builds, where it was not used before, I considered that this sort of overhead is acceptable, so, it is modeled with VMFile and unconditionally added.
Additional refactoring was applied to promote some utility functions for named pipe to the machine common part instead of WSL: `PipeAvailable` and `WaitPipeExists`. There 100% will be need to use former in QEMU machine, but the …
> Expose Podman named pipe in Inspect output

- libpod/container_internal_linux.go
- pkg/specgen/namespaces.go
- test/e2e/run_test.go
Backports #15618 to v4.0-rhel per https://bugzilla.redhat.com/show_bug.cgi?id=2121541
```release-note
NONE
```
> Backport #15618 to v4.0-rhel

- test/system/410-selinux.bats
In the remote environment, this test will be failed,
because an error message is different from the local environment.
---
- Error message (local)
```
Error: OCI runtime error: runc: runc create failed: unable to start container process: error during container init: write /proc/self/attr/keycreate: invalid argument
```
- Error message (remote)
```
Error: preparing container <cid> for attach: runc: runc create failed: unable to start container process: error during container init: write /proc/self/attr/keycreate: invalid argument: OCI runtime error
```
<details>
<summary>test log in the remote environment</summary>
```
not ok 1 podman with nonexistent labels
```
</details>
```release-note
None
```
> system tests: fix noexistent labels test in the remote

- hack/markdown-preprocess
One of the tmpfiles was not uniquely named, resulting in
conflicts with parallel 'make docs'. Fix that.
A better solution would be to run only one instance of the
preprocess script, but the Makefile incantation for that
is beyond me. This approach is CPU-wasteful but good enough.
Fixes: #17322
```release-note
Fixes a bug in which parallel `make docs` crashed
```
> make hack/markdown-preprocess parallel-safe

- pkg/specgen/generate/oci_linux.go
when using --userns=auto or --userns=pod, we should bind mount /sys from the host instead of creating a new /sys in the container, otherwise we rely on the fallback provided by crun, which might not be available in other runtimes.
Also, in the last version of crun the fallback is stricter than it used to be before and it uses a recursive bind mount through the new mount API.  That can be missing on old kernel.
Closes: https://github.com/containers/crun/issues/1131
[NO NEW TESTS NEEDED] to trigger the failure, we need a specific combination of kernel, libc and OCI runtime.
```release-note
None
```
> oci: bind mount /sys with --userns=(auto|pod:)

- hack/perf/bz-2162111.sh
- hack/perf/create.sh
- hack/perf/ps.sh
- hack/perf/rm.sh
- hack/perf/run.sh
- hack/perf/start.sh
- hack/perf/stop.sh
Create the containers with a custom network.  It has an impact on the speed of container creation.
@baude @edsantiago PTAL
```release-note
None
```
> [CI:DOCS] hack/perf/bz-2162111.sh: use custom network

- Makefile
- docs/source/markdown/links/quadlet.5
- docs/source/markdown/podman-systemd.unit.5.md
- podman.spec.rpkg
Currently we are shipping no data about quadlet, since the
podman-systemd.unit file is not shipped. Also want to add the
quadlet name to the description of the man page so that
man -k quadlet
will help users find the man page.
Also add a link file such that if the user types in
man quadlet
man will show the podman-systemd.unit file.
Also eliminate the subpackage podman-quadlet
Fixes: https://github.com/containers/podman/issues/17349
```release-note
Add podman-systemd.unit man page
```
>  Install podman-systemd.unit man page, make quadlet discoverable 

- Makefile
When run make with muitiple jobs, `clean-binaries` could run after the `podman-remote` target thus delete the newly built `podman-remote` binary file. And this would cause the error later in the `docs/remote-docs.sh` script.
I feel like build podman-remote here is unnecessary, make should build it automatically if it's changed.
```release-note
None
```
> Move `clean-binaries` before `podman-remote` in podman-remote-docs target

- contrib/cirrus/prebuild.sh
All PRs are broken because this test fails, presumably due to a GraphQL API change.  Disable the test temporarily until a permanent solution can be found.
```release-note
None
```
> Cirrus: Emergency fix to un-stuck PRs

- pkg/api/handlers/compat/images.go
- pkg/api/handlers/compat/images_build.go
- pkg/api/handlers/libpod/containers.go
- pkg/api/handlers/libpod/networks.go
```release-note
None
```
[NO NEW TESTS NEEDED}
> Add missing return after utils.Error()

- docs/source/markdown/podman-systemd.unit.5.md
docs/podman-systemd.unit: Update example to work out of the box
- Don't order the container unit before local-fs.target as that creates
an ordering cycle that triggers other issues.
- Use the example network in the container unit
- Only use groups that exists by default for the volume
Signed-off-by: Timothée Ravier <tim@siosm.fr>
---
docs/podman-systemd.unit: Explicitely mention '.network' units
Make the relation between '.container' and '.network' units more
explicit at the beginning.
Signed-off-by: Timothée Ravier <tim@siosm.fr>
---
No, docs only.
```release-note
None
```
> [CI:DOCS] docs/podman-systemd.unit: Update example to work out of the box + Explicitely mention '.network' units

- pkg/api/handlers/compat/networks.go
Handle a race condition in the REST API when listing networks. In between listing all containers and inspecting them, they may have already been removed, so handle this case gracefully.
[NO TESTS NEEDED] as it's a race condition.
Fixes: #17341
```release-note
Fix a bug in the REST API when listing networks while a container has just been removed.
```
> network ls: handle removed container

- .github/actions/check_cirrus_cron/cron_failures.sh
- contrib/cirrus/prebuild.sh
A semantic change to a Cirrus-CI GraphQL API parameter caused a
unit-test to fail (as it should have) with the error:
```
Query result did not pass filter '.data.ownerRepository.cronSettings':
'{"data":{"ownerRepository":null}}'
```
As per Cirrus-support, a change was introduced in schema affecting certain
fields that were incorrectly marked Nullable.  They indicated the `platform`
field was set incorrectly, and should use the value `github`.
* Fix the platform field's value to `github` instead of `LINUX`.
* Change the unit-test to only execute as part of the 'main' cirrus-cron
job so it cannot impact PRs.
```release-note
None
```
> [CI:BUILD] Cirrus: Fix GraphQL ownerRepository:null error

- cmd/quadlet/main.go
- test/e2e/quadlet_test.go
Quadlet should not exit with failure if no files to process have been found.  Otherwise, even simple operations such as reloading systemd will fail as it retriggers generators.
Fixes: #17374
```release-note
None
```
> Quadlet: exit 0 when there are no files to process

- libpod/container_internal_linux_test.go
The tests for generating username/passwd entries assume that UID/GID 123/456 do not exist, which is not a safe assumption on Debian. If a /etc/passwd entry with that UID/GID already exists, the test will not add a new one with the same UID/GID, and will fail. Change UID and GID to be 6 digits, because we're a lot less likely to collide with UIDs and GIDs in use on the system that way. Could also go further and randomly generate the UID/GID, but that feels like overkill.
Fixes #17366
```release-note
NONE
```
> Fix a potential UID/GID collision in unit tests

- .github/actions/check_cirrus_cron/cron_failures.sh
- contrib/cirrus/prebuild.sh
These tests don't need to run for every PR, and the thing they're testing never runs on any branch except `main`.  Stop them from running on this branch.  In case someone decides to try and use them, also fix the errant API call which triggered the original problem.
Ref: https://github.com/containers/podman/pull/17383
```release-note
None
```
> [CI:BUILD] Cirrus: Fix & remove GraphQL API tests

- pkg/machine/qemu/options_darwin_arm64.go
Fixes https://github.com/containers/podman/issues/17026
Fixes https://github.com/NixOS/nixpkgs/issues/169118
Related: https://github.com/NixOS/nixpkgs/pull/163015
```release-note
None
```
> Resolve symlink path for qemu directory if possible

- test/system/505-networking-pasta.bats
See https://github.com/containers/podman/issues/17287. This is a mitigation I want to check against CI, at the moment.
```release-note
None
```
> tests: pasta: Mitigation for socat connect() getting EINTR and two other fixes

- cmd/podman/kube/play.go
- test/system/700-play.bats
Commit 2f29639bd3aa9 added a UX improvement to cleanup/teardown when running the specified YAML has failed.  However, the teardown happens unconditionally such that rerunning the same YAML file will teardown the previously created workload instead of just failing with a name-conflict error (e.g., "pod already exists").  The regression popped up testing the Ansible system role with Podman v4.4.0.
For now, do not teardown at all on error to quickly fix this regression for the upcoming Podman v4.4.1 release.  The UX improvement is still desired but must be conditional and only happen on newly created resources, which probably requires moving it down to the backend.
```release-note
Fix a regression in `kube play` where existing resources …
```
> kube play: do not teardown unconditionally on error

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
We already label the issue anyway and this results in reports without an actual title so remove it. This leaves more space for an actual useful title.
ref: https://github.com/containers/podman/discussions/17431
```release-note
None
```
> [CI:DOCS] github: remove prefix from bugs/features

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/secrets.container
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
Add E2E tests
Add system test
Add to man page
Yes
```release-note
Quadlet: Add support for the Secret key in Container group
```
> Quadlet: Add support for the Secret key in Container group

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
We currently name the container being created during kube play as ctrName-podName, but this is not how it is done in k8s. Since we can't change this at the CLI level as it will be a breaking change (it will be planned for podman 5.0), add only ctrName as an alias to the network of the pod.
Partially fixes https://github.com/containers/podman/issues/16544 - a follow up during podman 5.0 will be needed to make the breaking CLI change.
```release-note
Add ctrName as an alias to the pod network.
```
> Add ctrName to network alias during kube play

- docs/source/markdown/podman-auto-update.1.md.in
- docs/source/markdown/podman-container-inspect.1.md.in
- docs/source/markdown/podman-events.1.md
- docs/source/markdown/podman-history.1.md
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-network-inspect.1.md
- docs/source/markdown/podman-network-ls.1.md.in
- docs/source/markdown/podman-pod-ps.1.md.in
- docs/source/markdown/podman-ps.1.md
- docs/source/markdown/podman-secret-inspect.1.md
- hack/xref-helpmsgs-manpages
Very belated successor to #14046.
I don't know why this is so important to me. Probably because we're doing a halfhearted sloppy job of documenting, and new options get added, and not documented, and that's just wrong.
I've given up on documenting internal structs. This iteration has a $Format_Exceptions table defined at the top of the xref script, enumerating a hardcoded defined set of podman commands and fields that should remain undocumented.
This iteration also forgives completely-undocumented formats. If podman-foo has a --format, but podman-foo.1.md does not list *any* valid fields, the script warns but does not fail. This at least is better than documenting a random mix of fields.
This version of the xref script is much slower: 10s vs 4. I think we can live with that in a CI-only …
> [CI:DOCS] man-page checker: include --format (Go templates)

- pkg/domain/infra/abi/play.go
- test/system/250-systemd.bats
- test/system/252-quadlet.bats
- test/system/260-sdnotify.bats
Commit 4fa307f14923 fixed a number of issues in the sdnotify proxies. Whenever a container runs with a custom sdnotify policy, the proxies need to keep running which in turn required Podman to run and wait for the service container to stop.  Improve on that behavior and set the service container as the main PID (instead of Podman) when no container needs sdnotify.
Fixes: #17345
```release-note
None
```
@rhatdan @ygalblum @alexlarsson PTAL
This optimization will also benefit Quadlet.  If we plan on cutting a Podman v4.4.2, this may be a nice candidate.
> kube play: set service container as main PID when possible

- docs/source/markdown/podman-network.1.md
- docs/source/markdown/podman-system.1.md
- hack/xref-helpmsgs-manpages
command tables are chock full of duplication, hence they break.
Look for inconsistencies between the displayed man page name
and the actual man page name:
|  foo    | [podman-foo(1)](podman-cmd-foo.1.md) | ...
^^^
Inspired by #17474.
We can't actually check the subcommand name (the plain "foo")
because there are many existing subcommands whose name does
not match the man page: rmi vs image-rm, list vs podman-ps.
```release-note
None
```
> [CI:DOCS] man page xref: validate displayed man page names

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.container
Remove the container in ExecStop to make sure that Quadlet's adheres to Podman's customizable stop signal/timeout.  Certain programs ignore SIGTERM which renders the services generated by Quadlet less user friendly compared to the ones from podman-generate-systemd.
Previously, `systemctl stop` would just hang until systemd's stop timeout is hit.  Since `podman rm` also removes the CID file, the additional `rm` can be removed.  Note that `podman rm` will return immediately if the specified CID file isn't present.
I am working on a short tutorial on Quadlet and hit the issue with a simple container running `sleep`.  `sleep` ignores SIGTERM and stopping the service would take forever even with `PodmanArgs=--stop-timeout=0`. …
> quadlet: add ExecStop

- libpod/define/annotations.go
- libpod/kube.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/generate_kube_test.go
Add a podman ulimit annotation to kube generate and play. If a container has a container with ulimits set, kube gen will add those as an annotation to the generated yaml. If kube play encounters the ulimit annotation, it will set ulimits for the container being played.
Fixes https://github.com/containers/podman/issues/16404
```release-note
Add ulimit annotation to generated yaml file to be used by kube play.
```
> Add ulimit annotation to kube gen & play

- docs/source/markdown/podman-history.1.md
- docs/source/markdown/podman-machine-list.1.md.in
- docs/source/markdown/podman-network-inspect.1.md
- docs/source/markdown/podman-network-ls.1.md.in
- docs/source/markdown/podman-search.1.md.in
- docs/source/markdown/podman-system-connection-list.1.md
- hack/xref-helpmsgs-manpages
Followup to #17486: stricter checks on --format.
* If a subcommand offers autocompletion for templates,
it must also offer a '--format json' option.
* If a subcommand has a --format option that DOES NOT
offer autocompletion for templates, it must be listed
in a hardcoded grandparented-in table of commands
where that's not applicable. (Mostly commands
like build, commit, save, where "format" is used
in the context of "oci/docker").
Only likely to trigger on PRs which add new subcommands,
and is intended to catch oversights.
Also, test for alphanumeric order in man page tables.
Sort all existing tables.
```release-note
None
```
> [CI:DOCS] man page --format xref: tighten the autocompletion check

- libpod/kube.go
- pkg/domain/infra/abi/generate.go
- test/e2e/generate_kube_test.go
When generating a kube yaml with kube generate, do not set the hostPort in the pod spec if the service flag is set and we are generating a service kind too.
```release-note
When generating service kind, don't add hostPort to the pod spec.
```
> Don't set hostPort when generating a service

- pkg/domain/filters/volumes.go
- test/e2e/volume_prune_test.go
Signed-off-by: vyasgun <vyasgun20@gmail.com>
```release-note
None
```
> fix != filter in volume prune

- cmd/podman/common/create.go
- cmd/podman/containers/create.go
- docs/source/markdown/options/shm-size-systemd.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- libpod/container_config.go
- libpod/container_internal_linux.go
- libpod/options.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/podspecgen.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/pod_create_test.go
- test/e2e/run_test.go
Add support for limiting tmpfs size for systemd-specific mounts via `--shm-size-systemd`
Closes #17037 
```release-note
- Add support for limiting tmpfs size for systemd-specific mounts via `--shm-size-systemd`
```
> add support for limiting tmpfs size for systemd-specific mnts

- cmd/podman/images/build.go
- test/system/070-build.bats
Fixes: https://github.com/containers/podman/issues/17495
```release-note
`podman --remote build -f -` now works.
```
> Allow specification of podman --remote build -f -

- test/e2e/play_kube_test.go
Use `podmanTest.PodmanBinary` because podman-remote unshare
cannot be used.
```release-note
None
```
> e2e: adapt play kube test on remote rootless

- Makefile
- cmd/podman/machine/os.go
- cmd/podman/machine/os/apply.go
- cmd/podman/machine/os/manager.go
- cmd/podman/machine/os/os_unsupported.go
- cmd/podman/main.go
- cmd/podman/main_experimental.go
- docs/source/markdown/podman-machine-inspect.1.md
- docs/source/markdown/podman-machine-os-apply.1.md
- docs/source/markdown/podman-machine-os.1.md
- docs/source/markdown/podman-machine.1.md
- pkg/machine/e2e/config_os_apply_test.go
- pkg/machine/e2e/os_test.go
- pkg/machine/os/config.go
- pkg/machine/os/machine_os.go
- pkg/machine/os/ostree.go
Podman machine os apply takes a takes a OCI image with container native ostree functionality and rebases the machine os on that image. Currently, this requires the guest os inside the vm to use rpm-ostree.
When specifying an image, any container transport may be specified. If a container transport is not specified, OS apply will attempt to search the local containers-storage for the image, and if it is not found, it will then attempt to use the Docker transport to pull from a remote registry.
The architecture of OS apply is as follows:
podman machine os apply ssh's into the machine and calls podman machine os apply. on the secondary call to podman machine os apply, apply recognizes that it is inside the machine and does image operations, and finally calls rpm-ostree rebase.
Tests are …
> Introduce podman machine os apply

- contrib/cirrus/prebuild.sh
- test/system/020-tag.bats
- test/system/030-run.bats
- test/system/055-rm.bats
- test/system/065-cp.bats
- test/system/070-build.bats
- test/system/160-volumes.bats
- test/system/220-healthcheck.bats
- test/system/250-systemd.bats
- test/system/410-selinux.bats
- test/system/500-networking.bats
- test/system/700-play.bats
- test/system/800-config.bats
Replace existing tab indentations with spaces, and add
a test to CI to prevent new ones from sneaking in.
```release-note
None
```
> system tests: prevent leading tabs

- contrib/cirrus/setup_environment.sh
I can't find instances of the "lookup cdn03.quay.io" flake
in RHEL gating tests. RHEL does not use systemd-resolved.
Maybe pure coincidence. Maybe not.
```release-note
None
```
> Experimental workaround for cdn03.quay.io flake

- test/system/252-quadlet.bats
- test/system/helpers.bash
Tests constantly fail with zero indication of why. Fix that.
- add correct default for $QUADLET path
- add check to make sure it exists
- log quadlet commands and their output
```release-note
None
```
> quadlet system tests: add useful defaults, logging

- contrib/cirrus/lib.sh
The `localbenchmarks()` function stores a `.env` file containing current environment variables for benchmark-classification purposes.  However its naked use of `printenv` means it was logging the contents of library functions and (worse) trying to stort all the lines.  This results in an unusable mess inside `benchmarks.env`.  Fix this by re-using the purpose-built passthrough_envars() which is designed to only print useful, safe, env. vars.
Also
The `benchmarks.env` file is intended for machine consumption. Including things like a `kB` unit label (like `$MEMTOTAL`) make items difficult to parse.  Additionally, multi-value keys (like `$UNAME_RM`) make extra/unnecessary work for the interpreter.  Simplify these items and include a data-schema version marker so an interpreter can be made …
> Cirrus: Omit functions in env. file

- go.mod
- go.sum
- vendor/github.com/containers/image/v5/docker/body_reader.go
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Bump c/image to v5.24.1 in preparation of the RHEL 8.8 and 9.2 release.
```release-note
None
```
> [v4.4.1-rhel] Bump c/image to v5.24.1

- libpod/container_internal.go
- utils/utils.go
Backport #17528 to v4.4-rhel per RHBZ 2169617
```release-note
NONE
```
> [v4.0-rhel] Backport #17528

- .cirrus.yml
An ongoing issue with uploading artifacts is hindering development progress.  Temporarily disable all aflicted tasks until the problem is resolved.  Typical error message:
```
Uploading 1 artifacts for
Failed to upload artifacts: Put
...cut...
tls: server selected unsupported protocol version 303
Re-trying to artifacts upload...
```
Ref: https://github.com/containers/podman/issues/17537
```release-note
None
```
> CI: Temporarily disable all AWS EC2-based tasks

- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/pod_create.go
- test/e2e/play_kube_test.go
Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>
Fixes: #16711 
Yes
```release-note
Support sysctl options from Pod Spec via podman kube play CLI
```
> [FEAT] Support sysctl configurations from Pod Spec

- test/system/helpers.bash
- test/system/helpers.t
...safer, too: the big change is using 'mapfile' to split
multiline strings; this preserves empty lines, making it
easy to see spurious (or missing) blank lines in output.
Another change is to indent the expected-output string
consistently, for readability.
Then, to handle \r (CR) and other control characters, use
bash %q to format special chars. But %q makes\ it\ hard\ to
read\ lines\ with\ spaces, so strip off those backslashes.
This makes assert() much larger and uglier, but this is
code that shouldn't be touched often.
Finally, because these are big changes to critical code,
write a complicated regression test suite for assert().
Closes: #17509 
```release-note
None
```
> System tests: assert(): friendlier failure messages

- Makefile
- docs/source/markdown/options/secret.md
Somehow the options/secret.md file generated corrupt md which
then generated corrupt .man files. Fix, and add a Makefile
check to prevent this from happening again.
```release-note
Fix broken man pages
```
> Emergency fix for man pages: check for broken includes

- .cirrus.yml
- test/system/090-events.bats
Backport of https://github.com/containers/podman/pull/17451 to pass gating.
Backport of https://github.com/containers/podman/pull/17541 to get CI to work at all (@cevich PTAL).
```release-note
None
```
> V4.4.1 rhel backports

- cmd/podman/kube/play.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.kube
- test/e2e/quadlet_test.go
- test/system/250-systemd.bats
Only enforce the passthrough log driver for Quadlet. Commit 68fbebf introduced a regression on the `podman-kube@` template as `podman logs` stopped working and settings from containers.conf were ignored.
Fixes: #17482
```release-note
Fix a bug where containers started via the `podman-kube@` systemd template would always use the "passthrough" log driver.
```
> kube play: only enforce passthrough in Quadlet

- libpod/container_internal.go
- utils/utils.go
Backport #17528 to v4.4
CVE: https://access.redhat.com/security/cve/CVE-2023-0778
<MH: Cherry-pick to v4.4>
```release-note
NONE
```
> Backport #17528 to v4.4

- libpod/container_internal.go
- utils/utils.go
Cherry-pick #17528 to v4.4.1-rhel per RHBZ 2169618
```release-note
NONE
```
> [v4.4.1-rhel] Backport #17528

- .cirrus.yml
This reverts commit 7f8bc6f510979cc3787cd57fb8b06b86efd1833c.
Ref: https://github.com/containers/podman/issues/17537
```release-note
None
```
> [CI:BUILD] Revert "CI: Temporarily disable all AWS EC2-based tasks"

- docs/source/markdown/options/secret.md
This is a working theory fix.  The man pages including the secret.md option are not resolving properly.  The secret.md file is the only one with a text line with three back ticks on the start and end of the line.  Elsewhere we have the backticks on separate lines and the text in its own line.
This might not fix the issue, but at the very least it makes things consistent.
```release-note
None
```
> [v4.4.1-rhel] [CI:DOCS] Touch up secret man page

- libpod/container_log_linux.go
- libpod/container_log_unsupported.go
- libpod/runtime_ctr.go
This was added as hack in commit 6b06e9b77c because the journald logs code was not able to handle an empty journal. But since commit 767947ab88 this is no longer the case, we correctly use the sd_journal API and know when the journal is empty.
Therefore we no longer need this hack and it should be removed because it just adds overhead and an empty journal entry for no good reason.
```release-note
None
```
> journald: remove initializeJournal()

- docs/source/markdown/podman-systemd.unit.5.md
OCD get triggered :(
```release-note
None
```
> [CI:DOCS] Fix spacing typo & indent units in podman-systemd.unit(5)

- docs/source/markdown/options/README.md
Add a note about the restriction of the use of
three back-ticks in the md files in the options directory. If this is not done properly, it can quietly corrupt the compliled man pages.
```release-note
NO
```
> [CI:DOCS] Add restriction to option README

- docs/source/markdown/options/mount.md
- libpod/container_internal_common.go
- libpod/container_internal_test.go
we were previously using an experimental feature in crun, but we lost this capability once we moved to using the OCI runtime spec to specify the volume mappings in fdcc2257df0fb0cb72d3fbe1b5aa8625955e1219.
Add the same feature to libpod, so that we can support relative positions for the idmaps.
Closes: https://github.com/containers/podman/issues/17517
```release-note
It is possible to specify a relative mapping for volume mappings.
```
> libpod: support relative positions for idmaps

- test/system/252-quadlet.bats
- test/system/700-play.bats
...to deal with runc, cgroups v1, whatever is causing these failures on RHEL8.
```release-note
Gating test fixes
```
> RHEL8 gating-test skips and tweaks

- docs/tutorials/mac_win_client.md
- docs/tutorials/podman-for-windows.md
- docs/version-check
A conditional in `version-check` bypasses the test for PRs.  However, it appears it was intended to execute during the daily cirrus-cron runs. However, the cron-job it references (`nightly`) doesn't exist.  This is causing the test to run for every merge into `main`, and never run for `main` branch cirrus-cron job.  Fix the name so the test **ONLY** runs for the `main` branch cron-job.
Also, [since the test is currently failing](https://cirrus-ci.com/task/6183669669298176), update the docs as per the output instructions.
```release-note
None
```
> [CI:DOCS] Cirrus: Fix version-check to only run on `main` job

- Makefile
A recent commit to an included option file resulted in
completely broken man pages, where the markdown processor
just choked and sent the "included file blah blah" markdown
straight through to the nroff source. Hilarity ensued.
The string "included file options/" should never appear
in nroff. This adds a last-minute check to make sure
a similar error never happens again.
(As suggested by @Luap99 we should also add validators for
markdown and/or nroff.)
```release-note
None
```
> make docs: sanity check for broken man pages

- pkg/domain/utils/scp.go
Added forgotten "Identity" parameter to ssh.Exec
```
Fix a bug in image-scp to correctly use identity settings.
```
> podman image scp: added identity for ssh.Exec

- libpod/container_log.go
- libpod/container_log_linux.go
- libpod/container_log_unsupported.go
- libpod/logs/log.go
- test/system/250-systemd.bats
- test/system/252-quadlet.bats
The passthrough driver is designed for use in systemd units. By default
we can expect systemd to log the output on journald unless the unit sets
differen StandardOutput/StandardError settings.
At the moment podman logs just errors out when the passthrough driver is
used. With this change we will read the journald for the unit messages.
The logic is actually very similar to the existing one, we just need to
change the filter. We now filter by SYSTEMD_UNIT wich equals to the
contianer cgroup, this allows us the actually filter on a per contianer
basis even when multiple contianers are started in the same unit, i.e.
via podman-kube@.service.
The only difference a user will see is that journald will merge
stdout/err into one stream so we loose the separation there.
journald logs: simplify …
> podman logs: read journald with passthrough

- cmd/podman/machine/platform.go
- cmd/podman/machine/platform_windows.go
- pkg/machine/applehv/machine.go
- pkg/machine/config.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/fcos.go
- pkg/machine/fcos_test.go
- pkg/machine/pull.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/fedora.go
- pkg/machine/wsl/machine.go
before we can support hyperv as a virtualization option for podman machine, several areas in machine will require cleanup.  this is the first pass of these changes to keep the review burden low.  changes include:
* convert artifact, format (image format) and compression to enums with string methods
* rename Provider interface to VirtProvider
* change Provider implementation in QEMU to QEMUVirt
* change Provider implementation in WSL to WSLVirt
as mentioned earlier, there will be several more of these refactoring PRs because assumptions were made about associations of platforms and virt providers as well as compression and image formats.
```release-note
None
```
> machine refactoring preparations for hyperv

- pkg/api/handlers/compat/networks.go
- test/apiv2/35-networks.at
If the name already exists and CheckDuplicate is set we need to return 409, if CheckDuplicate is not set we return the network without error.
Fixes #17585
```release-note
The docker compat API now returns 409 if you try to create a network with the same name and CheckDuplicate is set to true.
```
> compat API: network create return 409 for duplicate

- libpod/container_internal_common.go
- test/system/500-networking.bats
Since commit 06241077cc we use the aardvark per container dns functionality. This means we should only have the aardvark ip in resolv.conf otherwise the client resolver could skip aardvark, thus ignoring the special dns option for this container.
Fixes #17499
```release-note
podman run --dns ... --network ... will no longer add host nameservers to resolv.conf when aardvark-dns is used.
```
> netavark: only use aardvark ip as nameserver

- libpod/container_internal.go
- libpod/container_internal_common.go
- libpod/container_internal_test.go
- test/e2e/run_userns_test.go
always use the direct mapping when writing the mappings for an idmapped mount.  crun was previously using the reverse mapping, which is not correct and it is being addressed here:
https://github.com/containers/crun/pull/1147
```release-note
podman now writes the mapping for idmapped mounts in the correct format
```
> libpod: always use direct mapping for idmapped mounts

- test/system/010-images.bats
- test/system/035-logs.bats
- test/system/170-run-userns.bats
- test/system/500-networking.bats
- test/system/700-play.bats
...in hopes of fixing a flake with podman-remote. It's still
possible that there's a real problem with logs under remote,
and this will just sweep that under the rug.
Also, fix a nasty-red test warning (add cleanup), refactor
uses of $(pause_image), and improve a few test assertions.
Closes: #17286
```release-note
None
```
> Logs follow-until tests: loosen checks

- .cirrus.yml
- Makefile
- contrib/cirrus/lib.sh
- contrib/cirrus/logcollector.sh
- contrib/cirrus/setup_environment.sh
- test/buildah-bud/apply-podman-deltas
- test/e2e/common_test.go
- test/e2e/play_kube_test.go
- test/e2e/run_userns_test.go
- test/system/070-build.bats
- test/system/252-quadlet.bats
- test/system/505-networking-pasta.bats
- test/system/700-play.bats
Ref: https://github.com/containers/automation_images/pull/250
```release-note
None
```
> Replace Ubuntu -> Debian SID

- cmd/podman/kube/play.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
> kube: rm secret on down, print secret on play

- podman.spec.rpkg
The `containers-common-extra` subpackage of `containers-common` handles all the dependencies common to podman and buildah. So, it's best to remove those from podman's spec.
```release-note
None
```
> [CI:BUILD] spec.rpkg: trim dependency list

- pkg/machine/applehv/config.go
- pkg/machine/applehv/machine.go
- pkg/machine/config.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/fcos.go
- pkg/machine/fcos_test.go
- pkg/machine/pull.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/fedora.go
- pkg/machine/wsl/machine.go
- pkg/machine/wsl/util_windows.go
in preparation for adding hyper as a machine option, several common functions needed to be moved specifically from qemu to a common area in pkg/machine.  this usually involved functions and variables related to using fcos as a machine image as well as its compression, artifact, and image format
```release-note
None
```
> Machine refactor for QEMU/AppleHV

- cmd/podman/system/service_abi.go
when running rootless on cgroupv1, Podman+OCI runtime do not setup a separate cgroup for the container.  Spawned containers will run in the same cgroup as the podman system service process, thus will be killed when the cgroup is destroyed, as it is the case when running as a systemd service.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2170444
```release-note
None
```
> system: add warning when running rootless on cgroupv1

- libpod/sqlite_state.go
- libpod/sqlite_state_internal.go
@mheon @baude PTAL
This PRs completes the Pod methods and adds a number of fixes.   I was chasing the failure in `test/system/220-healthcheck.bats` but ran out of time.  Many system and e2e tests are passing, so it's now in a state where we can play on the CLI.
```release-note
None
```
> sqlite: complete Pod methods

- .cirrus.yml
Run rootless bud tests as part of the nightly treadmill job.
Reason: #17480 could have been caught before release.
```release-note
None
```
> CI: new rootless buildah-bud tests (cron only)

- contrib/cirrus/runner.sh
The script is broken and the maintainer temporarily unavailable to help fix it.  Disable it for now, w/ reference to possible fix.
Ref: https://github.com/containers/podman/pull/17620
```release-note
None
```
> [CI:DOCS] Temporarily disable version-check

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/basic.container
Backport of https://github.com/containers/podman/pull/17601 to 4.4.
```release-note
Quadlet: .container file may be used with any runtime
```
> [v4.4] Quadlet - use the default runtime

- test/buildah-bud/run-buildah-bud-tests
For some weeks or longer, the buildah bud tests have been failing under cirrus-cron with the message:
```
+ git am --reject
Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for
<some30462dude@cirrus-task-5479994827210752.c.libpod-218412.internal>)
not allowed
```
Fix this by marking the clone directory "safe" when the script is running under CI.
```release-note
None
```
> Cirrus: Fix bud tests failing to apply patches

- pkg/machine/qemu/machine.go
- pkg/machine/qemu/machine_unix.go
- pkg/machine/qemu/machine_windows.go
Fixes #17098 
Was tested as part of https://github.com/containers/podman/issues/13006#issuecomment-1381000284 
Implementation demo isolated https://go.dev/play/p/Do-tBPHESLE (~[Original outdated version](https://go.dev/play/p/xUTMgZgD5fj)~)
There are 2 things added. First there is added support for handling drive letters while doing value split. If drive letter is detected, then max number of elements will be increased by one, but then first two will be concatenated to reconstruct the path. Second part is basic, but working conversion of Windows path to Unix to be used, when target path is not explicitly specified.
Used regex for drive letter detection, because init would be never used in the hotpath, so, performance wise it affordable.
Signed-off-by: Arthur Sengileyev …
> Support for Windows paths in the source position of the volume mounts

- .cirrus.yml
- test/system/505-networking-pasta.bats
This reverts commit 81f116c59c291793742e10ea84b77511902a0338: the passt package for Fedora 37 images is now fixed in the c20230223t153813z-f37f36d12 image.
```release-note
None
```
> Revert "Skip all pasta tests"

- docs/kubernetes_support.md
Support for this field has been effectively removed via https://github.com/containers/podman/pull/17082, this addresses the issue raised in https://github.com/containers/podman/pull/17082#issuecomment-1445314415
```release-note
None
```
> Remove replicas field from kubernetes deployment support doc

- docs/source/markdown/podman-network-create.1.md
Doc update to support docker-specific network create options via CLI
Closes: https://github.com/containers/podman/issues/15830
Signed-off-by: T K Chandra Hasan <t.k.chandra.hasan@ibm.com>
Yes
```
Support for following docker network options via CLI
1. com.docker.network.bridge.name
2. com.docker.network.driver.mtu
```
> [CI:DOCS] Document update for docker network options via CLI

- cmd/podman/common/create.go
- docs/source/markdown/options/group-entry.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- libpod/container_config.go
- libpod/container_internal_common.go
- libpod/options.go
- pkg/domain/entities/pods.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/run_passwd_test.go
Adds entry to /etc/group if specified via `--group-entry`
Closes: #14965
```release-note
add entry to /etc/group via `--group-entry`
```
> create: add entry to /etc/group via `--group-entry`

- contrib/pkginstaller/Makefile
this updates the Makefile qemu version to make use new qemu released at https://github.com/containers/podman-machine-qemu/releases/tag/v7.2.0-1
Fixes #17490 
```release-note
None
```
> pkginstaller: bump Qemu to version 7.2.0

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/mount.container
- test/e2e/quadlet_test.go
Handle the Mount key
Reuse code from the handling of the Volume key
Add E2E Test
E2E Test - Add checker for KeyValue string
Update man page
Yes
```release-note
Quadlet: Add support for the Mount key in .container files
```
Resolves: #17632
> Quadlet: Add support for the Mount key in .container files

- test/system/035-logs.bats
The test should make sure the logs --follow call will log entries that are created in the future when --since is used and doe not include the container start event. However it seems the timing is to tight. I think it was possible that CI logged the line before the logs call was made, thus it is missing because --since excluded it.
I cannot reproduce so I am not 100% on this but we can reopen the issue if it still happens.
Fixes #17616
```release-note
None
```
> fix "podman logs --since --follow" flake

- test/buildah-bud/run-buildah-bud-tests
Ref: #17643
The buildah bud tests run rootless, so attempting to bypass the ident-check with a `git config --system` fails with a permission denied error (as it should).  Update the command to use `--global` instead, which writes to `~/.gitconfig` and so works for regular users.
Also setup a fake identity for the CI-user and enable shell-debugging for the commands to inform humans of what is happening in the script.
```release-note
None
```
> Cirrus: Fix git config permission denied

- test/system/255-auto-update.bats
The symptoms in #17607 point to some race since it does not always flake on Debian (and Debian only).  Hence, wait for the service to be ready before building the image to make sure that the service is started with the old image and that everything's in order.
Fixes: #17607
```release-note
None
```
> auto-update test: wait for service to be ready

- cmd/podman/kube/down.go
- cmd/podman/kube/play.go
- docs/source/markdown/podman-kube-play.1.md.in
- libpod/service.go
- libpod/shutdown/handler.go
- pkg/api/handlers/libpod/kube.go
- pkg/api/server/register_kube.go
- pkg/bindings/kube/types.go
- pkg/bindings/kube/types_play_options.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/tunnel/kube.go
- test/system/700-play.bats
Add a way to keep play kube running in the foreground and terminating all pods
after receiving a a SIGINT or SIGTERM signal. The pods will also be
cleaned up after the containers in it have exited.
If an error occurrs during kube play, any resources created till the
error point will be cleane up also.
Add tests for the various scenarios.
Fixes https://github.com/containers/podman/issues/14522
Add new --wait flag to podman kube play command
```release-note
Add new --wait flag to podman kube play command that keeps workload running in foreground until killed with a sigkill or sigterm. The workloads are cleaned up and removed when killed.
```
> play kube: Add --wait option

- libpod/sqlite_state.go
- libpod/sqlite_state_internal.go
A number of commits to the WIP sqlite backend in libpod.  Please see the individual commits for details.
On my machine all but one system test pass.  There is one remaining issue with respect to network aliases.  Run the tests against `test/system/500-networking.bats --filter "connect/disconnect with port forwarding"` to reproduce the issue.  I am running out of time today, so I prefer to push the current state.
@mheon @baude PTAL
```release-note
None
```
> sqlite updates

- pkg/machine/ignition.go
This allows Chrony to update the system time when it has drifted far from NTP time. By default Chrony only makes slight adjustments, but in the case where a user's laptop lid has been shut for a while and then the machine is resumed, the VM system time could be hours or days behind real time, and it my never catch up if Chrony only makes slight changes.
Fixes #11541
```release-note
Fixed a bug where podman machine VMs could have their system time drift behind real time. New machines will no longer be affected by this.
```
> podman machine: Adjust Chrony makestep config

- cmd/podman/images/scp.go
- cmd/podman/main.go
- cmd/podman/registry/config.go
- cmd/podman/system/version.go
- pkg/rootless/rootless_linux.c
Closes: https://github.com/containers/podman/issues/17657
```release-note
podman version does not join the rootless user namespace
```
> cmd: do not require userns for "version"

- pkg/machine/wsl/machine.go
The wsl machine code was passing an erroneous "-q" with  a "--restore" rpm operation, which previously was ignored by rpm, but recent versions of F37 now favor the package query operation over the restore, leading to the restore operation being skipped. This leads to broken file perms on newuidmap.
The underlying issue blocks podman machine from updating to F37 on x86. 
```release-note
NONE
```
> Fix package restore of shadow-utils on Windows

- .gitignore
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/ip.container
- test/e2e/quadlet_test.go
Add support for `IP=` and `IP6=`.
```release-note
Added support for specifying static IPv4 and IPv6 addresses in Quadlet .container files via the IP= and IP6= options.
```
> Quadlet: add support for setting --ip and --ip6

- .cirrus.yml
Given that flakes inevitably occur as testing grows wider, position the system tests in parallel with the integration tests as much as possible. The thinking here is, flaking sooner is better than later.  This is because it provides an earlier opportunity for developers to re-run tasks.
```release-note
None
```
> Cirrus: Run system & integration tests in parallel

- .cirrus.yml
- test/system/505-networking-pasta.bats
This fixes #17074.
```release-note
None
```
> pasta: Re-enable "Local forwarder, IPv4" test now that packages in CI images are fixed

- podman.spec.rpkg
RHEL 8 and 9 don't have /usr/lib/modules-load.d yet.
Related dist-git commit:
https://src.fedoraproject.org/rpms/podman/c/c82d37a5b3c102088775e16bca817437e425b5d1
```release-note
None
```
> podman.spec.rpkg: distro conditionals for modulesloaddir

- libpod/networking_common.go
- test/apiv2/20-containers.at
- test/system/500-networking.bats
This will match Docker behaviour.
Fixes: https://github.com/containers/podman/issues/17385
```release-note
podman inspect lists networks on all network modes.
```
> podman inspect list network when using --net=host or none

- libpod/options.go
- libpod/pod.go
- libpod/runtime_ctr.go
- libpod/runtime_volume_common.go
- libpod/util_freebsd.go
- libpod/util_linux.go
- libpod/util_linux_test.go
- libpod/util_unsupported.go
- libpod/volume.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/volume.go
- test/system/160-volumes.bats
- test/system/700-play.bats
```release-note
If user modifies the filelabel security-opt, builtin volumes will now use the specified label.
```
> Must use mountlabel when creating builtin volumes

- docs/tutorials/podman-for-windows.md
- pkg/machine/wsl/machine.go
```release-note
None
```
---
I presume the commands provided are intended to be copy-pasted. In that case, the command to set `DOCKER_HOST` env variable in cmd context is incorrect.
> [CI:DOCS] fix cmd `set DOCKER_HOST` suggestion

- test/system/255-auto-update.bats
Two changes to help debug the flakes on Debian tracked in #17607.  Please refer to the individual commit messages for details.
@edsantiago PTAL
```release-note
None
```
> auto update system tests: help debug #17607

- test/system/505-networking-pasta.bats
This reverts commit e33f4e0bc7429038ba6aa82285ae8749c9037c88, going back to three connections (not two) for each range in TCP tests. I'm not sure yet what caused the original issue, but it might be fixed now. If it does, this fixes #17287.
```release-note
None
```
> Revert "pasta: Use two connections instead of three in TCP range forward tests"

- test/buildah-bud/buildah-tests.diff
Another followup to #17608. Nightly tests were hanging,
because /run/podman/podman.sock was hardcoded (bad idea
for rootless). Poor testing on my part.
```release-note
None
```
> bud tests: rootless remote: use correct socket path

- test/system/272-system-connection.bats
- test/system/helpers.network.bash
The goal of the wait_for_port() function is to return when the port is bound. This is to make sure we wait for application startup time. This can be seen in some comments of the callers.
Commit 7e3d04fb caused this regression while reworking the logic to read ports from /proc. I doesn't seem to cause problems in CI, properly because the function returns before the port is bound. I have not seen any flakes related to this but I only see the ones on PRs where I rerun tests so it is best to wait for Ed to take a look.
Also fixes the broken ipv4_to_procfs() which only passes one argument to
__ipv4_to_procfs(), this results in the ipv4 not beeing inverted.
Therefore all bind checks against a direct ipv4 did not work.
This function accepts only an ipv4 but one caller passes localhost
which is …
> test/system: fix wait_for_port() to wait for bind

- cmd/podman/system/events.go
- docs/source/markdown/podman-events.1.md
The --stream flag is being used extensively in the tests and some blog posts refer to it which has been causing some confusion on why the flag was hidden.  I do not see a good reason to hide it anymore, so unhide it and add some docs.
[NO NEW TESTS NEEDED] as it's already being tested.
```release-note
Document the podman-events --stream flag.
```
> podman events: unhide --stream

- pkg/api/server/handler_logging.go
- test/system/251-system-service.bats
When the service is running with trace log level it wraps the `http.ResponseWriter` to log extra information. The problem is that the new type does not keep all the functions from the embedded type. Instead we have to implement them ourselves, however only Write() was implemented. Thus `Hijack()`could not be called on the writer. To prevent these issues we would implement all the interfaces that the inner type supports (Header, WriteHeader, Flush, Hijack).
Fixes #17749
```release-note
`podman system service --log-level=trace` will now be able to hijack the client connection and thus make `podman-remote run/attach` work correctly.
```
> system service --log-level=trace: support hijack

- cmd/podman-mac-helper/main.go
We should return a proper exit code to signal the failure.
Fixes #17785
```release-note
podman-mac-helper now exits with 1 on error.
```
> podman-mac-helper: exit 1 on error

- libpod/events/logfile.go
- libpod/events/logfile_test.go
- test/system/090-events.bats
When streaming events, prevent returning duplicates after a log rotation by marking a beginning and an end for rotated events.  Before starting to stream, get a timestamp while holding the event lock.  The timestamp allows for detecting whether a rotation event happened while reading the log file and to skip all events between the begin and end rotation event.
In an ideal scenario, we could detect rotated events by enforcing a chronological order when reading and skip those detected to not be more recent than the last read event.  However, events are not always _written_ in chronological order.  While this can be changed, existing event files could not be read correctly anymore.
Fixes: #17665
```release-note
Fix a bug in podman-events where some events got returned more than once after a …
```
> events: no duplicates when streaming during a log rotation

- cmd/podman/containers/create.go
- docs/source/markdown/options/security-opt.md
- libpod/container_config.go
- libpod/container_internal_linux.go
- libpod/define/annotations.go
- libpod/options.go
- libpod/runtime_volume_common.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgenutil/specgen.go
- test/e2e/containers_conf_test.go
- test/system/410-selinux.bats
Currently Podman prevents SELinux container separation, when running within a container. This PR adds a new 
--security-opt label=nested
When setting this option, Podman unmasks and mountsi /sys/fs/selinux into the containers making /sys/fs/selinux fully exposed. Secondly Podman sets the attribute
run.oci.mount_context_type=rootcontext
This attribute tells crun to mount volumes with rootcontext=MOUNTLABEL as opposed to context=MOUNTLABEL.
With these two settings Podman inside the container is allowed to set its own SELinux labels on tmpfs file systems mounted into its parents container, while still being confined by SELinux. Thus you can have nested SELinux labeling inside of a container.
```release-note
Podman create/run now support new option --security-opt label=nested, which allows …
```
> Support running nested SELinux container separation

- docs/source/markdown/podman-image-inspect.1.md
- docs/source/markdown/podman-machine-info.1.md
- docs/source/markdown/podman-machine-inspect.1.md
- docs/source/markdown/podman-secret-inspect.1.md
- docs/source/markdown/podman-secret-ls.1.md.in
- docs/source/markdown/podman-system-df.1.md
- docs/source/markdown/podman-volume-inspect.1.md
- docs/source/markdown/podman-volume-ls.1.md.in
```release-note
Document --format in all man pages
```
Improves on https://github.com/containers/podman/issues/17472
> [CI:DOCS] Document --format for additional man pages

- pkg/domain/infra/abi/containers.go
The code was not using append() to add items to a slice.
Accessing non allocated elements of the slice failed with:
```
$ podman container restore -l
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/containers/podman/v4/pkg/domain/infra/abi.(*ContainerEngine).ContainerRestore(0xc00051a8b8, {0x1dbced0, 0xc0000440d0}, {0x2a31b30, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, ...})
/share/go/src/github.com/containers/podman/pkg/domain/infra/abi/containers.go:676 +0x39c
github.com/containers/podman/v4/cmd/podman/containers.restore(0x28fb6c0?, {0xc0002c9080, 0x0, 0x1?})
/share/go/src/github.com/containers/podman/cmd/podman/containers/restore.go:171 +0x4ef
github.com/spf13/cobra.(*Command).execute(0x28fb6c0, {0xc0000400b0, 0x1, 0x1}) …
```
> Use append() to add elements to a slice (restore)

- pkg/domain/infra/abi/containers.go
Backports #17755 from @adrianreber to fix an append issue.  Will be used for a ZeroDay delivery to RHEL 8.8/9.2.
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2177611
Original commit message:
The code was not using append() to add items to a slice.
Accessing non allocated elements of the slice failed with:
```
$ podman container restore -l
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/containers/podman/v4/pkg/domain/infra/abi.(*ContainerEngine).ContainerRestore(0xc00051a8b8, {0x1dbced0, 0xc0000440d0}, {0x2a31b30, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, ...})
/share/go/src/github.com/containers/podman/pkg/domain/infra/abi/containers.go:676 +0x39c
github.com/containers/podman/v4/cmd/podman/containers.restore(0x28fb6c0?, {0xc0002c9080, 0x0, …
```
> [v4.4.1-rhel] Use append() to add elements to a slice (restore)

- test/e2e/info_test.go
- test/system/001-basic.bats
- test/system/005-info.bats
Just like we do with RUNTIME and NETWORK. Skipped for now in
system tests because there's no way yet to actually set the
database backend.
Also, in system test oneliner (first test), include DB
```release-note
None
```
> CI: test and confirm DESIRED_DATABASE

- hack/buildah-vendor-treadmill
In February we started running rootless bud tests in cron (#17608).
That's nice, but nobody ever looks at cron results. The idea behind
adding a rootless task was to run it in the manual treadmill, too.
This PR enables that, and more clearly documents the how and why.
```release-note
None
```
> [SKIP CI] buildah treadmill: also run rootless tests

- pkg/api/handlers/libpod/containers_create.go
- pkg/specgen/generate/container_create.go
- pkg/specgenutil/specgen.go
- test/e2e/containers_conf_test.go
- test/system/030-run.bats
The default_ulimits field is currently ignored in podman run commands. This PR fixes this.
Fixes: https://github.com/containers/podman/issues/17396
```release-note
default_ulimits field in containers.conf is now supported
```
> Use default_ulimits field in containers.conf
