containers/podman

- docs/source/markdown/podman-volume-create.1.md
Fix typo in podman volume create man page.
```release-note
None
```
Found in https://github.com/containers/podman/discussions/17741
> Fix option --opts -> --opt

- pkg/specgen/generate/container_create.go
- test/e2e/config/containers.conf
- test/e2e/containers_conf_test.go
- test/system/030-run.bats
```release-note
oom_score_adj is now handled in containers.conf
```
> Add support for oom_score_adj value from containers.conf

- libpod/container_internal.go
- libpod/healthcheck.go
- test/system/220-healthcheck.bats
As described in #17777, the `restart` on-failure action did not behave correctly when the health check is being run by a transient systemd unit.  It ran just fine when being executed outside such a unit, for instance, manually or, as done in the system tests, in a scripted fashion.
There were two issue causing the `restart` on-failure action to misbehave:
1) The transient systemd units used the default `KillMode=cgroup` which
will nuke all processes in the specific cgroup including the recently
restarted container/conmon once the main `podman healthcheck run`
process exits.  Setting the kill mode to none addresses this problem.
2) Podman attempted to remove the transient systemd unit and timer
during restart.  That is perfectly fine when manually restarting the
container but not when the …
> fix --health-on-failure=restart in transient unit

- pkg/domain/infra/abi/play.go
- test/system/700-play.bats
Since we can't guarantee when the worker queue will come
and clean up the service container in the remote case when
podman kube play --wait is called, cleanup the service container
at the end of PlayKubeDown() to ensure that it is removed right
after all the containers, pods, volumes, etc are removed.
Fixes https://github.com/containers/podman/issues/17803
Foxes https://github.com/containers/podman/issues/17820
```release-note
None
```
> Add service ctr cleanup to PlayKubeDown

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/mount.container
- test/e2e/quadlet/volume.container
- test/e2e/quadlet_test.go
If the volume source starts with . resolve the path relative to the location of the unit file
Update the test code to allow verification of regex for the value in key value arguments
Add the usage of relative paths to the volume and mount test cases Update the man page
Yes
```release-note
Quadlet - add support for relative path in Volume key in .container file
```
Fixes: #17418
> Quadlet - add support for relative path in Volume key in .container file

- libpod/container_internal.go
- libpod/healthcheck.go
- test/system/220-healthcheck.bats
As described in #17777, the `restart` on-failure action did not behave correctly when the health check is being run by a transient systemd unit.  It ran just fine when being executed outside such a unit, for instance, manually or, as done in the system tests, in a scripted fashion.
There were two issue causing the `restart` on-failure action to misbehave:
1) The transient systemd units used the default `KillMode=cgroup` which
will nuke all processes in the specific cgroup including the recently
restarted container/conmon once the main `podman healthcheck run`
process exits.
2) Podman attempted to remove the transient systemd unit and timer
during restart.  That is perfectly fine when manually restarting the
container but not when the restart itself is being executed inside
such a …
> [v4.4] fix --health-on-failure=restart in transient unit

- libpod/container_internal.go
- libpod/healthcheck.go
- test/system/220-healthcheck.bats
As described in #17777, the `restart` on-failure action did not behave correctly when the health check is being run by a transient systemd unit.  It ran just fine when being executed outside such a unit, for instance, manually or, as done in the system tests, in a scripted fashion.
There were two issue causing the `restart` on-failure action to misbehave:
1) The transient systemd units used the default `KillMode=cgroup` which
will nuke all processes in the specific cgroup including the recently
restarted container/conmon once the main `podman healthcheck run`
process exits.
2) Podman attempted to remove the transient systemd unit and timer
during restart.  That is perfectly fine when manually restarting the
container but not when the restart itself is being executed inside
such a …
> [v4.4.1-rhel] fix --health-on-failure=restart in transient unit

- libpod/container_internal.go
- libpod/healthcheck.go
- test/system/220-healthcheck.bats
As described in #17777, the `restart` on-failure action did not behave correctly when the health check is being run by a transient systemd unit.  It ran just fine when being executed outside such a unit, for instance, manually or, as done in the system tests, in a scripted fashion.
There were two issue causing the `restart` on-failure action to misbehave:
1) The transient systemd units used the default `KillMode=cgroup` which
will nuke all processes in the specific cgroup including the recently
restarted container/conmon once the main `podman healthcheck run`
process exits.
2) Podman attempted to remove the transient systemd unit and timer
during restart.  That is perfectly fine when manually restarting the
container but not when the restart itself is being executed inside
such a …
> [v4.3.1-rhel] fix --health-on-failure=restart in transient unit

- test/system/252-quadlet.bats
- test/system/260-sdnotify.bats
skip in setup() if journald unavailable.
To be pedantic, this is overkill: some quadlet tests pass
because they don't run journald. Too bad.
```release-note
None
```
> quadlet tests: skip on RHEL8 rootless

- test/system/030-run.bats
...and add a comment explaining why. The minimum, determined via
binary search, is actually 27! Anything under that will barf:
$ bin/podman run --ulimit nofile=26:26 --rm quay.io/libpod/testimage:20221018 true
Error: OCI runtime error: crun: openat2 `proc/sysrq-trigger`: Too many open files
Play it safe, go with 30.
(Does this seem alarming to anyone else, or am I the only one??)
Fixes: #17860
```release-note
None
```
> New ulimit test: bump up minimum nfiles

- .cirrus.yml
- contrib/cirrus/cirrus_yaml_test.py
Future work will present podman-machine benchmark data in some useful
format for analysis.  However, this data is currently only stored as CI
artifacts.  When CI runs on the main branch, after a PR merges, utilize
a pair of purpose-built containers to retrieve then upload the data into
a GCE firestore database.  This operation should not be critical, such
that any faults will not cause the entire CI build to be marked as a
failure.
***Note***: This uses a container with [code from the containers/automation repo. to do the actual database insertion.](https://github.com/containers/automation/blob/main/bench_stuff/bench_stuff.py)
```release-note
None
```
> Cirrus: Store podman machine benchmark data

- libpod/sqlite_state.go
- libpod/sqlite_state_internal.go
Two fixes:
- Ensure that SQLite schema migration happens before we init any part of the database, so we never access a database with a bad schema.
- Fix a flake where we were getting database locked errors due to concurrent read/write of the same table.
```release-note
NONE
```
> Sqlite fixes

- go.mod
- go.sum
- pkg/api/handlers/compat/auth.go
- test/e2e/run_test.go
- vendor/github.com/containers/common/pkg/auth/auth.go
- vendor/github.com/containers/common/pkg/auth/cli.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
:cold_sweat: right on time before the 4.4.3 release.
@mheon @baude @ashley-cui @lsm5 PTAL
```release-note
Add SYS_CHROOT back to the default set of capabilities.
Fix a bug in the /auth REST API when logging into Docker Hub.
```
> 4.4 backports

- libpod/sqlite_state.go
> More sqlite fixes

- pkg/api/handlers/compat/containers_stats.go
- pkg/api/handlers/compat/types.go
- test/apiv2/20-containers.at
We use the same endpoint for libpod and docker compat API. However as reported docker returns "id" lowercase. Because we cannot break the libpod API right now keep the output for the libpod endpoint and only change the docker one.
To do so simply use two types that we can cast with different JSON tags.
Fixes #17869
```release-note
The docker compat API stats endpoint now returns the `Id` key as lowercase `id` to match docker.
```
> stats compat API: return "id" lowercase

- cmd/podman-mac-helper/install.go
- contrib/pkginstaller/scripts/postinstall
podman-mac-helper: install: do not error if already installed
Since commit https://github.com/containers/podman/commit/bae07b6ea2c29d113b21edcbcfbabd4e15296d60 we exit with 1 one errors. This caused problem
for the mac installer which fails because of the error now.
If the helper is already installed do not treat this as hard error and
just log it instead.
macos pkginstaller: do not fail when podman-mac-helper fails
Make sure we can install podman even when the podman-mac-helper install
command fails. This used to be the behavior but commit https://github.com/containers/podman/commit/bae07b6ea2c29d113b21edcbcfbabd4e15296d60 caused
the regression because the binary now returns 1 as exit code on errors.
Fixes https://github.com/containers/podman/issues/17910
```release-note
Fixed a …
```
> macos pkginstaller: fix regression which caused the installer to fail

- libpod/sqlite_state.go
- test/e2e/create_test.go
- test/e2e/pod_create_test.go
If a container with an ID starting with "db1" exists, and a container named "db1" also exists, and they are different containers - if I run `podman inspect db1` the container named "db1" should be inspected, and there should not be an error that multiple containers matched the name or id "db1". This was already handled by BoltDB, and now is properly managed by SQLite.
Fixes #17905
```release-note
NONE
```
> Ensure that SQLite state handles name-ID collisions

- contrib/cirrus/check_go_changes.sh
The os.IsNotExist() function comment mentions that new code should use `errors.Is(err, fs.ErrNotExist)` instead.
The check was already in CI but used the wrong function name (extra s.)
```release-note
None
```
> fix os.IsNotExist() CI check

- test/system/260-sdnotify.bats
Race introduced in #16709, which changed 'top' to 'true', so
there was only a narrow window in which '.State.ConmonPod'
would be valid. Remove the race.
Fixes: #17882
```release-note
None
```
> system tests: fix racey sdnotify test

- go.mod
- go.sum
- test/e2e/run_test.go
- test/system/005-info.bats
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Add yet another environment variable for loading containers.conf. When CONTAINERS_CONF_OVERRIDE is set, the specified config file will be loaded last - even when CONTAINERS_CONF is set.
This mechanism is needed to preserve system settings and other environment variables.  Setting CONTAINERS_CONF will load only the specified config file and ignore all system and user paths. That makes testing hard as many Podman tests use CONTAINERS_CONF for testing.
The intended use of CONTAINERS_CONF_OVERRIDE is to set it during tests and point it to a specific configuration of Podman (e.g., netavark with sqlite backend).
Similar needs have popped up talking to users in the automotive and high-performance computing space.  In a way, such a setting allows for specifying a specific "flavor" of Podman while …
> add CONTAINERS_CONF_OVERRIDE

- test/system/030-run.bats
- test/system/070-build.bats
- test/system/090-events.bats
- test/system/160-volumes.bats
- test/system/170-run-userns.bats
- test/system/200-pod.bats
- test/system/500-networking.bats
- test/system/700-play.bats
- test/system/800-config.bats
...not CONTAINERS_CONF. At least for most tests.
Nearly every system test currently using CONTAINERS_CONF=tmpfile
should be using CONTAINERS_CONF_OVERRIDE.
Simple reason: runtime (crun/runc), database_backend (bolt/sqlite),
logger, and other important settings from /etc/c.conf are not
usually written into the tmpfile. Those tests, therefore, are
not running podman as configured on the system.
Much more discussion: #15413
This PR is a prerequisite for enabling sqlite system tests. For
the sake of simplicity and sanity, I choose to submit the sqlite
switch as a separate PR once this passes and merges.
```release-note
None
```
> system tests: use CONTAINERS_CONF_OVERRIDE

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/env-file.container
- test/e2e/quadlet/volume.container
- test/system/252-quadlet.bats
If a path (Yaml, ConfigMap, EnvFile) starts with a systemd path specifier, treat the path as absolute
Add tests - unit, e2e and bats
Resolves: #17906 
Yes
```release-note
Quadlet - treat paths starting with systemd specifiers as absolute
```
> Quadlet - treat paths starting with systemd specifiers as absolute

- go.mod
- go.sum
- pkg/machine/hyperv/machine.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/error.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/memory_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/processor_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/summary.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/system_settings.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/system_settings_builder.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vmm.go
- vendor/github.com/containers/libhvee/pkg/wmiext/conversion.go
- vendor/github.com/containers/libhvee/pkg/wmiext/service.go
- vendor/modules.txt
add the ability to set cpu and processor counts on an existing vm.
```release-note
none
```
> implement podman machine set for hyperv

- libpod/sqlite_state.go
`Ping()` requires the DB lock, so we had to move it into a transaction to fix #17859. Since we try to access the DB directly afterwards, I prefer to let that fail instead of paying the cost of a transaction which would lock the DB for _all_ processes.
[NO NEW TESTS NEEDED] as it's a hard to reproduce race.
Fixes: #17859
```release-note
None
```
@mheon @baude @giuseppe @edsantiago PTAL
> sqlite: do not `Ping()` after connecting

- libpod/container_internal.go
- libpod/container_internal_common.go
- test/system/500-networking.bats
When a userns is set we setup the network after the bind mounts, at the point where resolv.conf is generated we do not yet know the subnet. Just like the other dns servers for bridge networks we need to add the ip later in completeNetworkSetup()
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2182052
```release-note
Add the correct slirp4netns dns ip in resolv.conf when the `cidr` option  and a custom userns is used.
```
> fix slirp4netns resolv.conf ip with a userns

- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
- pkg/util/utils.go
- test/buildah-bud/apply-podman-deltas
- test/e2e/build/containerignore-symlink/.dockerignore
- test/e2e/build/containerignore-symlink/Dockerfile
- test/e2e/build_test.go
Drop support for remote use-cases when `.containerignore` or `.dockerignore` is a symlink pointing to arbitrary location on host.
```release-note
remote,build: do not allow to process arbitrary symlinks on host for remote builds.
```
> remote,build: ignore if `.containerignore` or `.dockerignore` is a symlink outside of buildContext

- libpod/container_internal.go
- libpod/container_internal_common.go
- test/system/500-networking.bats
When a userns is set we setup the network after the bind mounts, at the point where resolv.conf is generated we do not yet know the subnet. Just like the other dns servers for bridge networks we need to add the ip later in completeNetworkSetup()
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2182492 and https://bugzilla.redhat.com/show_bug.cgi?id=2182491
This is targeted to RHEL 8.8 and 9.2 ZeroDay
```release-note
None
```
> [v4.4.1-rhel] fix slirp4netns resolv.conf ip with a userns

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/remap-keep-id.container
- test/e2e/quadlet/remap-keep-id2.container
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet - Support setting UID and GID for --userns=keep-id
```
Resolves: #17908
> Quadlet - Support setting UID and GID for --userns=keep-id

- test/e2e/image_sign_test.go
- test/e2e/save_test.go
By default go will not keep the stdout/err attach when executing commands via exec.Command(). It is required to explicitly pass the current stdout/err fds down to the child so we can see the error output in the logs to debug #17966.
```release-note
None
```
> test/e2e: gpg keep stdout/err attached

- test/e2e/volume_plugin_test.go
Wait for the socket to be ready befor trying to create a volume with the driver.
Fixes: #17956
```release-note
None
```
@edsantiago PTAL
> fix volume-plugin-test flake

- pkg/rootless/rootless_linux.c
the exec hooks already print the error message, so there is no need to print another one.
```release-note
None
```
> rootless: drop preexec hook error message

- libpod/container_internal.go
- libpod/container_internal_common.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
- pkg/specgen/generate/kube/kube.go
- pkg/util/mountOpts.go
- test/e2e/play_kube_test.go
add a function to securely mount a subpath inside a volume.  We cannot trust that the subpath is safe since it is beneath a volume that could be controlled by a separate container.  To avoid TOCTOU races between when we check the subpath and when the OCI runtime mounts it, we open the subpath, validate it, bind mount to a temporary directory and use it instead of the original path.
```release-note
None
```
> libpod: mount safely subpaths

- docs/source/markdown/podman-kube-play.1.md.in
> [CI:DOCS] Kube Play Doc: Document the support for K8S Secret

- docs/source/markdown/podman-systemd.unit.5.md
Fix the example for RemapGid from keep-id to keep-groups Reflect the chnages to the support for keep-id in Containers as well
No
```release-note
None
```
> [CI:DOCS] Quadlet: RemapUsers documentation fixes

- libpod/define/container_inspect.go
```release-note
None
```
Just a simple quick fix on the GoDoc for `HealthCheckResults.Status` to show that there is also the starting value
> [CI:DOCS] docs: add `starting` to `HealthCheckResults.Status`

- go.mod
- go.sum
- pkg/api/handlers/compat/auth.go
- test/e2e/run_test.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/pkg/auth/auth.go
- vendor/github.com/containers/common/pkg/auth/cli.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Use `auth.Login` as `podman login` does which parses and normalizes the input addresses correctly, especially for docker.io.
This Cherry Picks https://github.com/containers/podman/pull/17581 and brings in necessary changes to run_test.go from i
https://github.com/containers/podman/commit/5f86fae71fb5793de78a5dc09ffa357fb536771c
Addreses: https://bugzilla.redhat.com/show_bug.cgi?id=2183601 and https://bugzilla.redhat.com/show_bug.cgi?id=2183602 for the RHEL 8.8 and 9.2 ZeroDay
The original Fixed: #17571
```release-note
Fix a bug in the Docker-compatible REST APIs `/auth` endpoint to correctly log into Docker Hub.
```
> [v4.4.1-rhel] compat: /auth: parse server address correctly

- docs/tutorials/podman_tutorial.md
Finishing up the work started by @biergit in #17021
Updates the tutorial to explain the use of `-l/--latest` and converts many of the examples to use `<container_id>` as that works locally and remote while `-l` doesn't always.
Thanks for the start on this @biergit !
```release-note
None
```
> [CI:DOCS] Improve basic tutorial

- contrib/cirrus/win-installer-main.ps1
MSI Validation will fail if the process env is > 32k chars Remove CIRRUS_COMMIT_MESSAGE and CIRRUS_PR_BODY, which can easily exceed this limit
An example of this occuring is: #17473
```release-note
none
```
> Fix Win install task failures with large PR bodies

- test/system/032-sig-proxy.bats
One of our oldest most frustrating flakes is #16091, "Timed
out waiting for BYE".
In #17489 we added some debug output to see if the problem
was a container hang of some sort. It does not seem to be
(see #17675), and the debug output makes it hard to read
failure logs, so let's remove it.
```release-note
None
```
> System tests: unverbosify a flake log

- RELEASE_NOTES.md
- version/version.go
Cutting RC1 off main. Note that both c/common and Buildah are vendored in as main, and not a version. 
No release notes yet, coming in the next RC.
```release-note
None
```
> Bump to 4.5.0-rc1

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/system/252-quadlet.bats
This commit adds an quadlet option `Tmpfs` which can be used to mount a tmpfs in the container.
Closes #17907
```release-note
Quadlet container files now support a new `Tmpfs` option.
```
> quadlet: implement `Tmpfs` option

- test/e2e/healthcheck_run_test.go
Test has been flaking. Reason: container was run with -d, so
there's a small window in which podman-healthcheck ran on
a running container. Solution: remove -d
```release-note
None
```
> e2e: healthcheck on stopped container: fix flake

- libpod/networking_linux.go
I made a change in c/common[1] to prevent duplicates in netns names. This now causes problem in podman[2] where the rootless netns will no longer work after the netns got invalid but the underlying path still exists. AFAICT this happens when the podman pause process got killed and we are now in a different user namespace.
While I do not know what causes this, this commit should make it at least possible to recover from this situation automatically as it used to be before[1].
the problem with that is that containers started before it will not be able to talk to contianers started after this. A restart of the previous container will fix it but this was also the case before.
[1] https://github.com/containers/common/pull/1381
[2] https://github.com/containers/podman/issues/17903#issuecomment-1 …
> rootless netns: recover from invalid netns

- podman.spec.rpkg
```release-note
None
```
Fixed build: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5744558/ (ignore epel-9-next for now)
> Copr: fix build deps for /usr/bin/envsubst

- docs/source/markdown/options/creds.md
Mention that specified credentials are only used to authenticate against target registries (e.g., during `pull` or `build`) and are not used to authenticat against mirrors etc.
Closes: #17185
```release-note
Refine the man pages for the `--creds` CLI flag.
```
@mtrmac @rhatdan PTAL
> [CI:DOCS] --creds and registries

- contrib/cirrus/win-installer-main.ps1
- contrib/cirrus/win-podman-machine-main.ps1
Fixes #18048 
This is a regression from #18018: CIRRUS_PR_BODY doesn't exist on a non-PR run, so it wasn't triggered in PR verification. Change this and all other env removals to ignore non-existing entries.
```release-note
none
```
> Fix daily run CI failures on win installer task

- .cirrus.yml
Fixes: #18040
If the `build_aarch64` task happens to fail for any reason, it will cause the `curl` command in the `clone_script` for the aarch64 system test tasks to throw a 404.  This is because the
`local_system_test_aarch64_task` depends on `build` not `build_aarch64`. As discovered in another issue long ago, the Cirrus API depends on doing some dependency-resolution magic to function properly.  Fix this by correcting the dependencies.
```release-note
None
```
> Cirrus: Fix aarch64 clone_script 404 errors

- libpod/kube.go
- test/e2e/generate_kube_test.go
- test/system/710-kube.bats
Kube generate on pods was not checking for any underscores in the pod name so was creating a kube yaml with an invalid pod name when there were underscores present.
The hostname for the pod is set to the podname by default. There is no need to set that to the container's name or the pod name again in the generated yaml. So removed that field as well.
Fixes https://github.com/containers/podman/issues/18054
```release-note
Fix pod name when doing `kube generate [podname]`.
```
> Fix invalid pod name and hostname during kube generate

- test/e2e/common_test.go
...to silence runtime warning:
GinkgoParallelNode is deprecated and will be removed in Ginkgo V2.
Please use GinkgoParallelProcess instead.
Ref: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#renamed-ginkgoparallelnode
```release-note
None
```
> e2e: GinkgoParallelNode() -> ...Process()

- libpod/storage.go
When creating storage for a container using ID maps, read the ID maps that are assigned to the container from the returned container structure, rather than from the options structure that we passed to the storage library, which it previously modified in error.
```release-note
None
```
> libpod.storageService.CreateContainerStorage(): retrieve ID maps

- pkg/api/handlers/compat/images_build.go
- pkg/api/handlers/libpod/kube.go
- test/apiv2/80-kube.at
See individual commits for details.  Given the first DELETE didn't actually check if the pod was removed, we may get some better idea on the next flakes.
@edsantiago, that's the best thing I could come up with. PTAL
```release-note
None
```
> test updates to help debug #18041

- test/e2e/build_test.go
- test/e2e/common_test.go
- test/e2e/network_test.go
- test/e2e/prune_test.go
- test/e2e/system_reset_test.go
Since commit f250560a8043 the play kube command uses its own network. this is racy be disgn because we create the network followed by creating/running pod/containers. This means in the meantime another prune or reset process could wipe out the network config because we have to share the network config directory by desgin in the test.
The problem is we only have one host netns which is shared between tests. If the network config dir is not shared we cannot make conflict checks for interface names and ip address. This results in different tests trying to use the same interface and/or ip address which will cause runtime failures in CNI and netavark.
The only solution I see is to make sure only the reset/prune tests are using a custom network dir. This makes sure they do not wipe configs that …
> test/e2e: use custom network config dir where needed

- .cirrus.yml
In GCP, user specified VM names are required upon creation.  Cirrus-CI generates helpful names containing the task-ID.  Unfortunately in EC2 the VM ID's are auto-generated, and special permissions are required to allow secondary setting of a `Name` tag.  Since this permission has been granted, enable the `experimental` flag on EC2 tasks so that cirrus can update VM name-tags.  This is especially useful in troubleshooting orphaned VMs.
Ref:
https://github.com/containers/podman/issues/18065#issuecomment-1497779159
```release-note
None
```
> Cirrus: Enable labeling of EC2 VMs

- contrib/cirrus/postbuild.sh
Principally because 'make completion' fails if we transitively
bring in a new cobra, but also, none of the other tests are
meaningful under the treadmill.
```release-note
None
```
> [CI:BUILD] postbuild step: skip under nightly treadmill

- docs/source/markdown/podman-kube-play.1.md.in
- test/e2e/logs_test.go
- test/e2e/play_kube_test.go
...mostly just test code that wasn't doing the required waits.
My first approach in the kube-play test was to add "--wait".
Bit mistake! The --wait flag, counterintuitively and counter to
documentation, actually destroys all pods+containers+everything
on exit. (Or tries -- see #17803). Since this violates POLA
and is undocumented, I include here a fix to the man page.
Despite my best intentions, I can't reasonably check every single
test for missing waits, especially in kube-play where failing
containers will get retried forever so we can't wait. We'll
just have to fix flakes as we see them.
Fixes: #17958
Fixes: #18071
```release-note
None
```
> e2e tests: fix racy flakes

- pkg/specgenutil/specgen.go
- pkg/specgenutil/specgenutil_test.go
RLIMIT_* resources constants are converted to the proper format for the go-units module.
Fixes #18077
None
Signed-off-by: Alexander Gryanko <xpahos@gmail.com>
> The `--ulimit` option now also accepts the name with an `RLIMIT_` prefix both upper and lower case.

- pkg/domain/infra/abi/play.go
Ensure that we are actually looking up the service container ID and actually removing it during kube teardown for the --wait use case. This ensures that we don't have a service container waiting around in removing state before we return from kube play in the remote case.
Should fix https://github.com/containers/podman/issues/17803
```release-note
None
```
> Properly remove the service container during kube down

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/system/252-quadlet.bats
The `UserNS` key will replace the `RemapGid`, `RemapUid`, `RemapUidSize` and `RemapUsers` options which are therefore marked as deprecated by this commit.
Closes #17984
```release-note
Quadlet now supports the UserNS option replacing RemapGid, RemapUid, RemapUidSize and RemapUsers in a future release.
```
> quadlet: add `UserNS` option key

- .github/workflows/issue-labeler.yml
- .github/workflows/rerun_cirrus_cron.yml
- .github/workflows/stale.yml
It's nearly impossible for humans to tell semantic-version differences by looking at a commit sha.  Since all the actions in question come from github, there's little security/safety benefit to using SHAs.
```release-note
None
```
> [CI:DOCS] GHA: Use version instead of SHA for actions

- RELEASE_NOTES.md
The other half of the release notes for v4.5.0
```release-note
NONE
```
> [CI:DOCS] Add remaining release notes for v4.5.0-RC2

- test/system/252-quadlet.bats
Wait for the expected logs to appear in the journal before using 
`journalctl`.  #18132 is likely flaking because `journalctl` does
not yet see the container's logs.                                
Fixes: #18132
```release-note
None
```
> test/system/252-quadlet.bats: fix flake

- libpod/runtime.go
- libpod/runtime_migrate.go
- pkg/domain/infra/abi/system.go
- pkg/rootless/rootless_linux.c
- pkg/util/utils_supported.go
- pkg/util/utils_windows.go
- test/system/550-pause-process.bats
Currently --tmpdir changes the location of the pause.pid file. this causes issues because the c code in pkg/rootless does not know about that. I tried to fix this[1] by fixing the c code to not use the shortcut. While this fix worked it will result in many pause processes leaking in the integrration tests.
Commit ab88632 added this behavior but following the disccusion it was never the intention that we end up having more than one pause process. The issues that was trying to fix was caused by somthing else AFAICT, the main problem seems to be that the pause.pid file parent directory may not be created when we try to create the pid file so it failed with ENOENT. This patch fixes it by creating this directory always and revert the change to no longer depend on the tmpdir value.
With this …
> rootless: make sure we only use a single pause process

- cmd/podman/kube/generate.go
- pkg/api/handlers/libpod/generate.go
- test/e2e/config/containers.conf
- test/system/710-kube.bats
Use the kube_generate_type from the containers.conf as the default value for the --type flag for kube generate. Override the default when userexplicitly sets the --type flag.
```release-note
Use defaults from `kube_generate_type` in containers.conf for podman kube generate --type.
```
> Read kube_generate_type from containers.conf

- RELEASE_NOTES.md
- cmd/podman/networks/create.go
- docs/source/markdown/podman-network-create.1.md
- pkg/domain/entities/network.go
- test/e2e/network_create_test.go
- test/e2e/network_test.go
- test/e2e/run_networking_test.go
Add netavark plugins and netavark macvlan dhcp support (was already merged with c/common but this fixes tests and docs).
```release-note
Netavark plugin support is added, the netavark network backend now allows users to create custom network drivers. `podman network create -d <plugin>` can be used to create a network config for your plugin and then podman will use it like any other config and takes care of setup/teardown on container start/stop. This requires at least netavark version 1.6.
```
> add netavark plugin support

- RELEASE_NOTES.md
- version/rawversion/version.go
> Bump to v4.5.0-RC2

- docs/source/markdown/podman-events.1.md
- pkg/k8s.io/api/core/v1/types.go
- test/e2e/config.go
- test/e2e/manifest_test.go
- test/e2e/play_kube_test.go
- test/system/200-pod.bats
- test/system/700-play.bats
This change is a part of the bigger umbrella issue: https://github.com/kubernetes/k8s.io/issues/4780 
Currently, we need this change to get in https://github.com/cri-o/cri-o/pull/6742, which is failing in CI due to inconsistent vendoring.
```release-note
None
```
> *: migrate image registry to registry.k8s.io

- pkg/specgen/generate/validate.go
- test/system/700-play.bats
If resource limits is not set, do not display the following warning message:
`Resource limits are not supported and ignored on cgroups V1 rootless systems`
Ref: #17582
```release-note
None
```
> Do not display the resource limits warning message

- go.mod
- go.sum
- test/apiv2/60-auth.at
- vendor/github.com/containers/common/pkg/auth/auth.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
By pulling in the fixes from c/common.  Add regression tests to make sure it's not happening another time.  The error messages are not ideal and should probably be optimized in the `/auth` endpoints directly but it's already an improvement over a nil deref.
```release-note
Fix a potential nil deref in the auth REST endpoints.
```
> api: auth: fix nil deref

- test/e2e/systemd_activate_test.go
While debugging #17904 we found the test to be missing the common podman flags.  Add them to the podman invocations and remove some clutter.
```release-note
None
```
@edsantiago @Luap99 PTAL
Note that the test will now also run with sqlite (even without the containers.conf PR).
> test/e2e/systemd_activate_test.go: simplify test

- contrib/cirrus/setup_environment.sh
- test/system/005-info.bats
In setup, write a containers.conf.d file with db_backend
as specified in .cirrus.yml.
This is actually much scarier and more achy-breaky than
merely "sqlite system tests": it enables sqlite in e2e
tests. ("But wait, we already do that!" -- no, not really.
sqlite in e2e is being done via --db-backend option, and
some podman commands in e2e do not use the standard options.
See #17904.
This is unlikely to get merged any time soon (March, maybe
even April) because sqlite is still too fragile; this will
trigger more flakes than are currently acceptable. Also,
the nasty auto-update flake seems to trigger much more
reliably with sqlite. We need that one fixed.
```release-note
None
```
> CI: enable sqlite system tests

- test/python/docker/compat/test_containers.py
> test: enable test_wait_next_exit

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/basic.container
- test/e2e/quadlet/basic.kube
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
Update e2e tests not to expect the flag
System tests - explicitly set the log driver to be able to parse the output
Yes
```release-note
Quadlet no longer sets the log-driver by default
```
Resolves: #17692
> Quadlet - do not set log-driver by default

- test/system/070-build.bats
Possible cause: on Debian, maybe because of fuse-overlayfs(??),
we sometimes see unexpected inode numbers.
This PR tightens the test logic, so it runs one 'stat' command
in only one podman invocation, then cross-checks multiple lines
of output. I don't know if this will really fix the flake, but
even if it doesn't, it will at least give us much more useful
diagnostic output than before.
And, as long as I'm in here, clean up test, remove duplication,
make error messages distinct (hence more useful), and comment.
Fixes: #17979
```release-note
None
```
> system tests: address COPY-hardlink flake

- test/system/700-play.bats
Use --restart=no on all created containers. Without this, all
containers spin forever and it's impossible to get a
reliable exit status.
As a side effort, clean up tests, make more robust and maintainable.
Fixes: #18047
```release-note
None
```
> system tests: fix race in kube-play read-only

- .packit.sh
- .packit.yaml
- podman.spec.rpkg
This commit adds Packit configuration files which will trigger rpm builds on copr:`rhcontainerbot/packit-builds` on every PR as well as on copr:`rhcontainerbot/podman-next` on every commit to main branch.
This commit will ensure main branch is always buildable on all supported Fedora and CentOS Stream versions for aarch64 and x86_64. TODO: enable build checks for s390x and ppc64le while ensuring they don't take too long to build.
The packit builds reuse `buildah.spec.rpkg` present upstream and are thus independent of Fedora / CentOS dist-git.
This change will remove the need for the current webhook based triggering of rpm builds on rhcontainerbot/podman-next after commit to main. That will be instead handled by the `trigger: commit` action added in this PR. New builds will continue to get …
> [CI:BUILD] Packit: Initial Enablement

- pkg/api/handlers/compat/containers_top.go
- pkg/api/handlers/libpod/pods.go
- pkg/api/handlers/utils/containers.go
- test/apiv2/20-containers.at
Podman is attempting to split the headers returned by the ps
command into a list of headers. Problem is that some headers
are multi-word, and headers are not guaranteed to be split via
a tab. This PR splits the headers bases on white space, and for
the select group of CAPS headers which are multi-word, combines
them back together.
Fixes: https://github.com/containers/podman/issues/17524
```release-note
Fix top Titles return in compatible API.
```
> Return title fields as a list

- RELEASE_NOTES.md
- version/rawversion/version.go
```release-note
None
```
Depends on https://github.com/containers/podman/pull/18199 . Let's merge that first in case release notes need any updates.
@mheon @ashley-cui PTAL
> v4.5.0 release

- docs/tutorials/basic_networking.md
Add instructions on how to start the netavark dhcp proxy. Also list version requirements.
Fixes #17635
```release-note
Updated the basic_networking tutorial with netavark DHCP support.
```
> [CI:DOCS] docs: update network tutorial with netavark DHCP support

- .packit.sh
- .packit.yaml
This commit adds Packit configuration files which will trigger rpm
builds on copr:`rhcontainerbot/packit-builds` on every PR as well as on
copr:`rhcontainerbot/qm` on every commit to v4.5 branch.
This commit will ensure main branch is always buildable on all supported
Fedora and CentOS Stream versions for aarch64 and x86_64.
TODO: enable build checks for s390x and ppc64le while ensuring they
don't take too long to build.
The packit builds reuse `podman.spec.rpkg` present upstream and are
thus independent of Fedora / CentOS dist-git.
> [v4.5 backport] [CI:BUILD] Packit: Initial Enablement

- libpod/oci_conmon_common.go
- pkg/domain/infra/abi/play_test.go
The documentation says
> The new Buffer takes ownership of buf, and the
> caller should not use buf after this call.
so use the more directly applicable, and simpler, bytes.Reader instead, to avoid this potentially risky use.
```release-note
None
```
> Don't use bytes.NewBuffer to read data

- go.mod
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
- pkg/machine/hyperv/vsock.go
- pkg/machine/ignition.go
- pkg/machine/qemu/machine.go
Windows HyperV uses HVSocks (Windows adaptation of vsock) for communicating between vms and the host.  Podman machine in Qemu uses a virtual UDS to signal the host that the machine is booted.  In HyperV, we can use a HVSOCK for the same purpose.
One of the big aspects of using HVSOCK on Windows is that the HVSOCK must be entered into the Windows registry.  So now part of init and rm of a podman machine, entries must be added and removed respectively. Also duplicates are a no-no.
```release-note
none
```
> Add support for HVSOCK on hyperv

- go.mod
- go.sum
- pkg/machine/hyperv/machine.go
- pkg/machine/hyperv/vsock.go
- pkg/machine/ignition.go
- pkg/machine/qemu/machine.go
- pkg/machine/ssh.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm_config.go
- vendor/modules.txt
podman machine with Microsoft HyperV will use hvsock on the guest and vsock on the guest for its networking.  this pr enables the basics for this to happen as well as changes to ignition to automatically set this up with network manager.
the vm binary referenced in this pr is in containers/gvisor-tap-vsock and will need to be added to distributions.
```release-note
None
```
> Enabled network over vsock

- Makefile
- RELEASE_PROCESS.md
The current release artifacts generation process is still fairly manual with a bunch of steps. This commit bundles them all into a single convenient Makefile target.
The `clean-binaries` target ends up removing `bin/`. So, the artifact dir has been changed to `release/` instead of the current `bin/` to avoid breaking other Makefile targets.
```release-note
None
```
@mheon @ashley-cui PTAL
> Makefile: include `release-artifacts` target

- go.mod
- go.sum
- pkg/machine/hyperv/machine.go
- pkg/machine/ignition.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
- vendor/modules.txt
When using podman machine with hyperv, stop was releasing the terminal back top the user prematurely.  This resulted in users being able to run subsequent commands while the vm was still stopped.  Commands like machine stop were prone to failing.
```release-note
None
```
> HyperV: wait on stop

- libpod/networking_common.go
- libpod/networking_linux.go
Make sure to tear down the netns again on errors. This is needed when a
later call fails and we do not have already stored the netns in the
container state.
Fixes #18205
```release-note
Correctly tear down the network stack again when an error happened during the setup.
```
> libpod: configureNetNS() tear down on errors

- pkg/api/handlers/compat/info.go
- test/apiv2/python/rest_api/test_v2_0_0_system.py
The docker API reports running rootless and SELinux as security options  in the `GET /info` response, so podman should do the same for the compat API.
I'm not sure how to test this. Should I extend the python REST test? It currently only checks for status code.
```release-note
None
```
> Add missing security options to /info response

- test/e2e/common_test.go
- test/e2e/quadlet_test.go
Adapts to pass the test even if
podman binary path is not `/usr/local/bin/podman`.
```release-note
None
```
> e2e: quadlet uses PODMAN env for podman binary path

- test/e2e/pod_rm_test.go
A cgroup could have been deleted by the time WalkDir is trying to access it.  Ignore the error and continue.
Closes: https://github.com/containers/podman/issues/17989
```release-note
None
```
> test: fix race when listing cgroups

- libpod/container_api.go
- libpod/container_internal.go
Commit 1ab833fb73 improved the situation but it is still not enough. If you run short lived containers with --restart=always podman is basically permanently restarting them. To only way to stop this is podman stop. However podman stop does not do anything when the container is already in a not running state. While this makes sense we should still mark the container as explicitly stopped by the user.
Together with the change in shouldRestart() which now checks for StoppedByUser this makes sure the cleanup process is not going to start it back up again.
A simple reproducer is:
```
podman run --restart=always --name test -d alpine true
podman stop test
```
then check if the container is still running, the behavior is very flaky, it took me like 20 podman stop tries before I finally hit the …
> libpod: stop containers with --restart=always

- hack/fork_exec_snoop.bt
Added fork/exec snooper that can be used to facilitate performance tracing especially of the startup of Podman. It is based on the work @aktau did in the original [forkexecsnoop.bt](https://github.com/aktau/dotfiles/blob/f7a035f9fab0683bf449851058a46481ef998a38/bpftrace/forkexecsnoop.bt#LL1) which is Apache 2 licenced as can be seen [here](https://github.com/aktau/dotfiles/commit/f7a035f9fab0683bf449851058a46481ef998a38).
```release-note
None
```
> Add eBPF snooper that traces the entire fork/exec graph of podman

- pkg/api/handlers/compat/images_remove.go
- pkg/api/server/register_images.go
- test/apiv2/10-images.at
PR #15093 implemented support for NoPrune in the ImageRemoveOptions, this PR simply brings that also to the compat API along with regression tests.
```release-note
Add support for the `noprune` image-removal parameter in the compat API.
```
Replaces #18004. @ankon @mheon @Luap99 PTAL
> compat: Translate `noprune` into ImageRemoveOptions.NoPrune

- test/e2e/prune_test.go
- test/e2e/volume_prune_test.go
Adds two custom config dirs to tests that were missed in commit dc9a65e348.
Fixes #17946 (hopefully finally)
```release-note
None
```
> test/e2e: use custom network config v2

- libpod/container_commit.go
- test/system/010-images.bats
If user specifies commit --format, we were not setting it before commit, this caused warning messages that made no sense to be printed that made no sense.
Fixes: https://github.com/containers/podman/issues/17773
```release-note
Incorrect warning fixed, when committing images with docker format and -m options"
```
> Specify format to buildah before commit

- pkg/machine/config.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
on machine start, create a socket representing the machine's podman service socket so local (to the host) applications can take advanatge of it.
```release-note
None
```
> hyperv: add podman socket mapping

- test/e2e/build_test.go
- test/e2e/checkpoint_test.go
- test/e2e/commit_test.go
- test/e2e/common_test.go
- test/e2e/containers_conf_test.go
- test/e2e/generate_kube_test.go
- test/e2e/healthcheck_run_test.go
- test/e2e/libpod_suite_remote_test.go
- test/e2e/network_create_test.go
- test/e2e/network_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_create_test.go
- test/e2e/push_test.go
- test/e2e/run_volume_test.go
- test/e2e/run_working_dir_test.go
Split out some fixes from #18163 that can be merged without ginkgo v2.
this should make review easier.  Please see the individual commits for details.
```release-note
None
```
> Several e2e fixes

- .cirrus.yml
Packit copr build tasks take care of this already so this can be safely removed.
```release-note
None
```
@cevich PTAL
cc @containers/podman-maintainers
> [CI:BUILD] Cirrus: remove copr rpm build task

- .cirrus.yml
These aren't being generated anymore (https://github.com/containers/podman/pull/18163)
```release-note
None
```
> Cirrus: Drop benchmarks artifact collection

- RELEASE_PROCESS.md
Update the process. Added announcement section, removed obsolete steps, changed order of some steps for fewer PR's and simplification of process.
```release-note
None
```
> [CI:DOCS] Update RELEASE_PROCESS.md

- .cirrus.yml
- Makefile
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
- test/e2e/search_test.go
Change breaks on this branch which depends on an older toolchain:
https://cs.opensource.google/go/x/tools/+/master:internal/gocommand/invoke.go;bpv=1;bpt=0;drc=866a2000920cc5ae9d6650c27c4b14f4654938e7;dlc=5214f412aecffbca887fc0c26f8d59e3a2342d44
```release-note
None
```
> [v3.0.1-rhel] Fix attempt to use incompatible go tools

- cmd/podman/images/history.go
- test/e2e/history_test.go
- test/system/110-history.bats
Closes #17767
Closes #17768
```release-note
Fixes a format inconsistency where podman and docker return slightly different output for `history --format {{.CreatedAt}}` and `history --format {{.Size}}` (#17767, #17768)
```
> Fixes format inconsistencies with docker for certain history fields

- cmd/podman/images/push.go
- cmd/podman/manifest/push.go
- docs/source/markdown/options/digestfile.md
- pkg/api/handlers/compat/images_push.go
- pkg/api/handlers/libpod/images_push.go
- pkg/bindings/images/push.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_push_options.go
- pkg/domain/entities/engine_image.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/push_test.go
Wire in support for writing the digest of the pushed image to a
user-specified file.  Requires some massaging of _internal_ APIs
and the extension of the push endpoint to integrate the raw manifest
(i.e., in bytes) in the stream.
Closes: #18216
```release-note
Support the `--digestfile` flag for `podman push` on Mac OS and Windows.
```
> support `--digestfile` for remote push

- test/e2e/common_test.go
- test/e2e/containers_conf_test.go
- test/e2e/logs_test.go
If journald is unavailable, journald logging driver tests should be skipped.
```release-note
None
```
> e2e: skip journald test if journald is unavailable

- cmd/podman/pods/create.go
`sysinfo.NumCPU` already falls back to `runtime.NumCPU` in case the platform-specific `sysinfo.numCPU` returns 0, see
https://github.com/containers/common/blob/554799639fc82afeddb9e39ec27a7b85382a6db3/pkg/sysinfo/numcpu.go#L8-L13
Also omit a second call to `sysinfo.NumCPU` and use the result from the earlier call.
No
```release-note
None
```
> cmd/podman/pods: omit superfluous runtime.NumCPU call

- .cirrus.yml
- contrib/cirrus/setup_environment.sh
> Cirrus: Enable testing on Fedora rawhide

- docs/source/markdown/podman-systemd.unit.5.md
Highlight that existing user and system services may be overridden if they have same name as the Quadlet file.  Also point the user to systemctl and how to list existing files.
Closes: #18275
```release-note
None
```
> [CI:DOCS] Quadlet: clarify overriding user/system services

- pkg/machine/qemu/options_darwin_arm64.go
[This](This) reverts commit 6b6458916eaa51f0dbbcfeccd740706697697ad3 (Resolve
symlink path for qemu directory if possible).
Fully resolving the symlink to qemu solves some issues for
aarch64-darwin nix with regards to finding `edk2-aarch64-code.fd`, but
unfortunately the fully resolved path includes the version number,
making it so that even patch updates break the path to
homebrew-installed qemu files.
Fixes https://github.com/containers/podman/issues/18111
```release-note
Do not fully resolve symlinks in the path to `edk2-aarch64-code.fd` to prevent
breakage with qemu updates.
```
> Revert "Resolve symlink path for qemu directory if possible"

- test/e2e/create_staticip_test.go
Our friend #7096 is still not fixed: it continues to flake,
singletons only, and only in the "create" test (not "run").
My guess: maybe there's a race somewhere in IP assignment,
such that container1 can have an IP, but not yet be running,
and a container2 can sneak in and start with that IP, and
container1 is the one that fails?
Solution: tighten the logic so we wait for container1 to
truly be running before we start container2. And, when we
start container2, do so with -a so we get to see stdout.
(Am not expecting it to be helpful, but who knows).
Also very minor cleanup
```release-note
None
```
> e2e create same-IP: try to fix flake

- test/system/030-run.bats
- test/system/075-exec.bats
- test/system/130-kill.bats
- test/system/260-sdnotify.bats
- test/system/320-system-df.bats
- test/system/410-selinux.bats
- test/system/520-checkpoint.bats
Having a container spin-wait on a /stop file, then exit, is
unsafe: 'podman exec $ctr touch /stop' can get sucked into
container cleanup before the exec terminates, resulting in
the podman-exec failing and hence the test failing.
Most existing instances of this pattern are unnecessary.
Replace those with just 'podman rm -f'.
When necessary, use a variety of safer alternatives.
Re-Closes: #10825 (already closed; this addresses remaining cases)
```release-note
None
```
> system tests: safer container-stop signaling

- pkg/autoupdate/autoupdate.go
When checking for new images on registries, do not suppress            
and debug-log errors but return them.  Other images and units          
will still be processed.                                               
That is important to a) stop hiding flaky registries (see #18321)      
b) mark the updates as `failed` instead of `false`
Closes: #18321
```release-note
None
```
> auto-update: log errors checking for updates

- libpod/sqlite_state.go
- libpod/sqlite_state_internal.go
According to an old upstream issue [1]: "If the first statement after BEGIN DEFERRED is a SELECT, then a read transaction is started. Subsequent write statements will upgrade the transaction to a write transaction if possible, or return SQLITE_BUSY."
So let's move the first SELECT under the same transaction as the table initialization.
[NO NEW TESTS NEEDED] as it's a hard to cause race.
[1] https://github.com/mattn/go-sqlite3/issues/274#issuecomment-1429054597
Fixes: #17859
```release-note
Fix a bug in the sqlite database backend where the first read access may fail.
```
> sqlite: move first read into a transaction

- pkg/specgen/generate/namespaces.go
- test/system/195-run-namesapces.bats
The problem right now is that --ns contianer: syntax causes use to add the namespace path to the spec which means the runtime will try to call setns on that. This works fine for private namespaces but when the host namspace is used by the container a rootless user is not allowed to join that namespace so the setns call will return with permission denied.
The fix is to effectively switch the container to the `host` mode instead of `container:` when the mention container used the host ns. I tried to fix this deep into the libpod call when we assign these namespaces but the problem is that this does not work correctly because these namespace require much more setup. Mainly different kind of mount points to work correctly.
We already have similar work-arounds in place for pods because they …
> rootless: support joining containers that use host ns

- pkg/machine/qemu/machine.go
In rare instances, if podman machine start does not exit correctly, the machine can be left in a "Starting" state, when in reality the machine is stopped. This prevents the user from actually starting the machine. This commit makes sure that on `podman machine stop`, we check if this is the case, and correctly set the starting state to false, allowing the user to start their machine again.
since this is a concurrency/race/crash fix that's hard to reproduce
Fixes: https://github.com/containers/podman/issues/16945
```release-note
Fixed a bug where a podman machine could get stuck in the `starting` state
```
> Recover from failed podman machine start

- test/e2e/run_networking_test.go
Nasty test flake, "bad address nc-server.dns.podman"
Cause: "There is absolutely no guarantee that aardvark-dns
is ready before the container is started." (source: Paul).
"Solution" (not really): wait before doing a host lookup.
Closes: #16272   (I hope)
```release-note
None
```
> Netavark userns test: give aardvark time to come up

- pkg/rootless/rootless_linux.c
- test/system/950-preexec-hooks.bats
The long term goal was to provide the customer with a way to turn on the
preexec_hooks processing of scripts by having some kind of configuration
that could be read. I had tried putting it into containers.conf to
start, but that turned out to be unyieldly quickly, and time is of
the essence for this fix. That is mostly due to the fact that this
code is preexecution and in C, the containers.conf file is read in
Go much further down the stack.
After first trying this process using an ENVVAR, I have
thought it over and chatted with others, and will now look for a
/etc/containers/podman_preexec_hooks.txt file to exist. If the admin
had put one in there, we will then process the files in the
directories /usr/libexec/podman/pre-exec-hooks
and /etc/containers/pre-exec-hooks.
Thoughts/suggestions …
> [v4.4.1-rhel] Add file switch for pre-exec hooks

- cmd/podman/manifest/annotate.go
- cmd/podman/manifest/manifest.go
The podman manifest annote does not support the use of image tags. When tags are used, digest.Parse(image) will fail, but the examples in the help use tags, which will mislead users. I think the examples in the help should be changed to sha256:15352d97781ffdf357bf3459c037be3efac4133dc9070c2dce7eca7c05c3e736
```release-note
Podman manifest annotate help example should use image digest
```
> fix: podman manifest annotate help example should use image digest

- Makefile
- cmd/podman-wslkerninst/main.go
- cmd/podman/machine/init.go
- cmd/podman/machine/list.go
- cmd/podman/machine/set.go
- docs/source/markdown/.gitignore
- docs/source/markdown/options/user-mode-networking.md
- docs/source/markdown/podman-machine-init.1.md.in
- docs/source/markdown/podman-machine-inspect.1.md
- docs/source/markdown/podman-machine-list.1.md.in
- docs/source/markdown/podman-machine-set.1.md.in
- pkg/domain/entities/machine.go
- pkg/machine/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/filelock.go
- pkg/machine/wsl/machine.go
- pkg/machine/wsl/usermodenet.go
- pkg/machine/wsl/util_windows.go
- pkg/machine/wsl/wutil/wutil.go
Certain VPN setups or other specialized networking configs will block traffic from the virtual WSL networking device, resulting in the podman WSL backend from being unable to contact systems on the VPN, and potentially losing internet access altogether. While some VPN providers provide configuration options to allow traffic from VMs, users may be prevented by policy from changing these options, or they may require networking infrastructure changes that require time to implement.
This PR adds a user-mode networking capability to podman machine on Windows, that works around this issue by rerouting all traffic over a user-space process running on the host, similar to the setup in use on Linux and Mac. 
It adds  a `--user-mode-networking` flag to `podman machine init` and `podman machine set` …
> Add user-mode networking feature to Windows/WSL

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/devices.container
Systemd supports unit files with a prefix '-' which tells the system to check if the content exists before using it. This would allow the QM project to specify AddDevice=-/dev/kvm, which would add the /dev/kvm device to the container iff it exists on the host.
```release-note
Quadlet now supports optional devices in the unit file.
```
> Support systemd optional prefix '-' for devices.

- pkg/api/handlers/compat/images_history.go
- test/apiv2/10-images.at
- test/python/docker/compat/test_images.py
Fixes: https://github.com/containers/podman/issues/17762
```release-note
Docker compatibility images/history api returns id with sha256: prefix 
```
> Add sha256: to images history id for docker compatibility

- go.mod
- go.sum
- libpod/container_internal_common.go
- vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
- vendor/github.com/containers/common/pkg/umask/umask.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
We can now use the new API for creating files and directories without setting the umask to allow parallel usage of those methods.
This patch also bumps c/common for that.
```release-note
None
```
> Update c/common and avoid setting umask

- docs/source/markdown/podman-network-create.1.md
Found a typo today while reading documentation.
Changed wording for `podman-network-create`'s `--ipv6` option.
Simple enough change :-)
I don't think so?
> [CI:DOCS] Fix simple typo in podman-network-create.md

- pkg/domain/infra/tunnel/manifest.go
```release-note
podman will no longer incorrectly claim that an error encountered while pushing a manifest list was actually encountered while adding an item to the list.
```
> Fix a copy/paste error in an error message

- .cirrus.yml
...it never worked as intended. Cron job has been deleted.
(Note: this is not the same as the *buildah* treadmill, #13808,
which continues to be active and necessary)
```release-note
None
```
> Nightly dependency treadmill: remove

- .cirrus.yml
- libpod/runtime.go
- libpod/runtime_pre_go1.20.go
- libpod/runtime_test.go
- test/e2e/common_test.go
Bump F36 -> F37, and F37 -> F38
```release-note
None
```
> Cirrus: Update CI VM Image to F38

- test/e2e/push_test.go
Add actual tests (for expected errors, not just exit-status) to
the "push to local registry with authorization" test. As it is
now, if the registry is unreachable, the test passes a number
of steps and only fails later, with a misleading diagnostic.
Followup to, but does not fix, #18286
```release-note
None
```
> e2e cleanup: push with auth: add error checks

- cmd/podman/machine/info.go
- cmd/podman/machine/init.go
- cmd/podman/machine/inspect.go
- cmd/podman/machine/list.go
- cmd/podman/machine/machine.go
- cmd/podman/machine/os/manager.go
- cmd/podman/machine/platform.go
- cmd/podman/machine/platform_windows.go
- cmd/podman/machine/rm.go
- cmd/podman/machine/set.go
- cmd/podman/machine/ssh.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- cmd/podman/system/reset_machine.go
- pkg/machine/config.go
Fixes #17116 
GetSystemDefaultProvider reworked to accept input parameter with the desired virtualization provider. All callers adjusted to read this from the config before requesting virtualization provider instance.
Additional environment variable CONTAINERS_MACHINE_PROVIDER is supported to override the config for testing purposes.
Motivation for this signature is that it could be later extended to not only using config, but also to accept CLI switches. It could be changed to have config reading inside platform method to remove it from every caller, but this will not significantly reduce code lines in the callers, because this would change the signature of the method in platform to report possible errors and then callers should still check and handle the errors. …
> Implement machine provider selection

- cmd/podman/machine/rm.go
- pkg/machine/connection.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
The connection remove call must be done inside the function that is
returned so that we wait until the user confirmed it.
Fixes https://github.com/containers/podman/issues/18330
```release-note
podman machine rm with the qemu backend now correctly removes the machine connection after the confirmation message not before.
```
> machine: qemu only remove connection after confirmation

- cmd/podman/manifest/push.go
- test/e2e/manifest_test.go
- test/e2e/push_test.go
`manifest push <source>` must work as-is if `source` is actually a valid path and no destination is provided, `podman` must internally choose `source` as its `destination` just like `podman push`
See: https://github.com/containers/podman/blob/main/cmd/podman/images/push.go#L161
Closes: https://github.com/containers/podman/issues/18360
```release-note
manifest, push: use `source` as `destination` if not specified
```
> manifest, push: use `source` as `destination` if not specified

- pkg/domain/infra/tunnel/images.go
By default podman save tries to write to /dev/stdout, this file doe snot exists on windows and cannot be opened. Instead we should just use fd 1 in such case.
Fixes #18147
```release-note
podman save on windows can now write to stdout by default.
```
> windows: podman save allow the use of stdout

- troubleshooting.md
Fix incorrect number of required subuids in subuid example.
Fixes: https://github.com/containers/podman/issues/18400
```release-note
None
```
> [CI:DOCS] troubleshooting: fix subuid example

- .cirrus.yml
On 4-24-2023 the `Windows Smoke Test` suddenly started failing.  While it would be informative to find out why, this is a RHEL-centric release branch.  Therefore, Windows testing is unnecessary and unhelpful. Disable it.
```release-note
None
```
> [v4.4.1-rhel] Cirrus: Disable windows CI testing

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
It looks like tell/seek don't work in CI-land: important test log
information is being lost. Revert this commit, maybe some day I'll
come up with a better solution.
This reverts commit 1bff0108f6275cc8290e649833f3a194cd6e9ee1.
```release-note
None
```
> Revert "logformatter: anchors: link to test summary, not name"

- test/e2e/create_staticip_test.go
- test/e2e/create_staticmac_test.go
- test/e2e/run_staticip_test.go
This is not safe at all when run in parallel, CNI needs that directory to detect duplicated ips and also stores other important network info in it. Removing it while container network is setup is not safe at all and could cause a lot of weird flakes.
This "hack" was added in commit 55508c11 but provides zero context what this was supposed to fix so I don't know what the actual issue is or was.
Fixes #18399
```release-note
None
```
> test/e2e: do not remove CNI directory

- cmd/podman/common/create.go
- cmd/podman/containers/create.go
- cmd/podman/containers/ps.go
- cmd/podman/pods/create.go
- cmd/podman/pods/ps.go
- docs/source/markdown/options/restart.md
- docs/source/markdown/podman-pod-clone.1.md.in
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-pod-inspect.1.md.in
- docs/source/markdown/podman-pod-ps.1.md.in
- docs/source/markdown/podman-ps.1.md
- libpod/container.go
- libpod/define/pod_inspect.go
- libpod/kube.go
- libpod/options.go
- libpod/pod.go
- libpod/pod_api.go
- pkg/domain/entities/container_ps.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/abi/pods.go
- pkg/ps/ps.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/pod_create.go
- pkg/specgen/podspecgen.go
- pkg/specgenutil/specgen.go
- pkg/util/utils.go
- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_create_test.go
Add --restart flag to pod create to allow users to set the restart policy for the pod, which applies to all the containers in the pod. This reuses the restart policy already there for containers and has the same restart policy options. Add "never" to the restart policy options to match k8s syntax. It is a synonym for "no" and does the exact same thing where the containers are not restarted once exited.
Only the containers that have exited will be restarted based on the restart policy, running containers will not be restarted when an exited container is restarted in the same pod (same as is done in k8s).
Add Restarts column to the podman ps and podman pod ps output to show how many times a
container was restarted based on its restart policy when --format={{.Restarts}}.
Signed-off-by: …
> Add --restart flag to pod create

- pkg/api/handlers/compat/images.go
- test/apiv2/10-images.at
Podman and Docker clients split the filter map slightly different, so
account for that when parsing the filters in the image-listing endpoint.
Fixes: #18092
```release-note
Fix parsing multi-value filters in the REST API.
```
> api: fix parsing filters

- go.mod
- go.sum
- pkg/bindings/images/build.go
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/Makefile
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/internal/parse/parse.go
- vendor/github.com/containers/buildah/pkg/parse/parse.go
- vendor/modules.txt
In case of no `platform` , bindings should not add `platform` to parameters at all instead it adds `/` as platform string which is invalid.
Exsiting test should pass with new buildah from upstream.
Closes: https://github.com/containers/buildah/issues/4768
Closes: https://github.com/containers/buildah/issues/4769
```release-note
bindings, build: don't pass invalid platform in case of none
```
> bindings, build: don't pass invalid platform in case of none

- cmd/podman/system/reset.go
- docs/source/markdown/podman-system-reset.1.md
system reset it says it will delete containers, images, networks, etc... However it will also delete the graphRoot and runRoot directories. Normally this is not an issue, however in same cases these directories were set to the users home directory or some other important system directory.
As first step simply show the directories that are configured and thus will be deleted by reset. As future step we could implement some safeguard will will not delete some known important directories however I tried to keep it simple for now.
see #18349 and #18295
```release-note
Show the graphRoot and runRoot directories when running podman system reset before we ask for confirmation as these directories will be deleted.
```
> system reset: show graphRoot/runRoot before removal

- cmd/podman/machine/platform_darwin.go
- go.mod
- go.sum
- pkg/machine/applehv/config.go
- pkg/machine/applehv/machine.go
- pkg/machine/applehv/rest.go
- pkg/machine/applehv/rest_config.go
- pkg/machine/applehv/vfkit.go
- pkg/machine/config.go
- pkg/machine/errors.go
- pkg/machine/fcos.go
- pkg/machine/hyperv/machine.go
- vendor/github.com/crc-org/vfkit/LICENSE
- vendor/github.com/crc-org/vfkit/pkg/rest/define/config.go
- vendor/modules.txt
this pr is the first pass at enabling podman machine to use the apple hypervisor. there are still several TODO areas like host networking.  once the decision is handled on what host networking should look like, these TODOs should be fairly quick to resolve.  they also will impact the remove methods.
you must also have vfkit (https://github.com/crc-org/vfkit)
```release-note
None
```
> MVP for Podman Machine with AppleHV

- libpod/container.go
- pkg/bindings/test/exec_test.go
The remote API will wait 300s by default before conmon will call the cleanup. In the meantime when you inspect an exec session started with ExecStart() (so not attached) and it did exit we do not know that. If a caller inspects it they think it is still running. To prevent this we should sync the session based on the exec pid and update the state accordingly.
For a reproducer see the test in this commit or the issue.
Fixes #18424
```release-note
The remote API exec inspect call will now correctly displays updated information, e.g. when the exec process died.
```
> remote: exec inspect update exec session status

- Makefile
Also generate all docker man pages to match podman man pages including links.
```release-note
Adjusted list of Docker equivalent man pages.
```
> [CI:DOCS]  Add missing man page links for Docker man pages 

- cmd/podman/root.go
- pkg/bindings/connection.go
We have a spacial logic to create a better user error that hints at podman machine, however because we string matched it missed the case of the ssh connection.
Stop doing string comparison and return a proper error and match it with errors.As()
see https://github.com/containers/podman/discussions/18426
```release-note
None
```
> remote: return better connect error

- rootless.md
`redir` is a really useful tool for rootless networking! But I hardly ever see it mentioned and see e.g. SO answers involving complex iptables rules.So have added a quick line in here mentioning options for port forwarding to a rootless setup. 
`redir` lets you start a simple service (as root) that forwards traffic from e.g. a port 443 to a higher port, meaning you can just start podman normally on 8443, and leave redir running in the background as long as the system is up.
Not sure if any other docs would benefit from addition too.
```release-note
None
```
> [CI:DOCS] Add mention of redir to doc `rootless.md`

- libpod/container_api.go
- test/e2e/stop_test.go
If the container was already cleaned up we should not try to do it again. Podman stop will always try to call Cleanup() if you look at the podman event log and just keep calling podman stop --all you see a cleanup event every time. This is not wanted. Also in case of the host pidns we report a error every single time, see the linked issue.
Fixes #18460
```release-note
Containers created with --pid=host will no longer print errors on podman stop.
```
> libpod: do not Cleanup() more than once

- pkg/domain/infra/abi/play.go
- test/e2e/play_kube_test.go
initContainers in kubernetes deployments had no call to CompleteSpec in the generation, which means that the default environment is not configured for these. This causes issues with missing default environment variables like `$HOME` or `$PATH`.
This fixes https://github.com/containers/podman/issues/18384
```release-note
- ensure that initContainers in k8s deployments have a correctly setup default environment
```
> Run generate.CompleteSpec() for initContainers as well

- Makefile
Followup to #18422: disable --json-report except under CI, which
is where it's useful.
```release-note
None
```
> ginkgo json output: only in CI, not on laptop runs

- test/system/700-play.bats
Use --restart=no on all created containers. Without this, all containers spin forever and it's impossible to get a reliable exit status.
As a side effort, clean up tests, make more robust and maintainable.
This is a clean cherrypick of #18169 onto v4.5, because the flake is triggering often in CI.
```release-note
None
```
> [v4.5] system tests: fix race in kube-play read-only

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
- docs/source/markdown/podman-systemd.unit.5.md
I would like to allow admin to control quadlet containers in users homedirs.
If an admin sets a quadlet in
/etc/containers/systemd/users, then all users will run these quadlet services when they login.
If an admin places a quadlet in /etc/containers/systemd/users/$(USERNAME) then only the USERNAME will execute this quadlet service when they login.
```release-note
Rootless podman quadlet files can now be installed in /etc/containers/systemd/users/ directory.
```
> Allow user quadlets to be stored under /etc

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
- docs/source/markdown/podman-systemd.unit.5.md
If there's a container defined in multiple directories use the following precedence:
`$XDG_CONFIG_HOME/containers/systemd/` or `~/.config/containers/systemd/` takes precedence over `/etc/containers/systemd/users/$(UID)` and this takes precedence over `/etc/containers/systemd/users/`
None
```release-note
None
```
> Fix preference of user quadlets directories

- test/e2e/play_kube_test.go
Yet another case where tests expect play-kube to be synchronous.
There are probably dozens more of these.
```release-note
None
```
> e2e: fix race in a play-kube test

- test/system/252-quadlet.bats
In some tests use Notify=yes while in others remove the notification
Resolves: #18516
No
```release-note
None
```
> Quadlet system tests - fix socket notification

- contrib/cirrus/logformatter
With -p, ginkgo emits timing information on the first line
after dashes. Without -p, it's at the end.
Most tests use -p. Podman-machine does not. Deal with that.
```release-note
None
```
> logformatter: handle podman-machine test logs

- test/e2e/systemd_activate_test.go
Another low-hanging fruit: test flakes because podman-remote
trying to contact a server that hadn't come up.
Fixes: #17940
```release-note
None
```
> e2e: stop podman.service test: wait for server

- libpod/container_internal_common.go
- test/e2e/start_test.go
```release-note
Fixes an issue where the HOME environment variable would be configured inconsistently between container starts if a new passwd entry had to be created for the container
```
Podman sets the HOME environment variable to the home directory of the user executing the podman command (if it is mounted) only if a new passwd entry has to be added on start. After a container restart, HOME is set to the home directory of the user configured with the `--user` flag.
This impacts tools such as VSCode Dev Containers as they use this variable to decide where to place files (the vscode server in this case). This issue is particularly annoying for people using Dev Containers and toolbox as a restart causes VSCode to place the server in a different place, often `/root` where it does not have …
> Ensure the consistent setting of the HOME env variable on container start

- test/system/252-quadlet.bats
- test/system/helpers.systemd.bash
Run $QUADLET and all systemctl/journalctl commands using 'timeout'.
Nothing should ever, ever take more than the default 2 minutes.
Followup to #18514, in which quadlet tests are found to be
taking 9-10 minutes.
```release-note
None
```
> system tests: timeoutize quadlet, systemd

- test/e2e/logs_test.go
Yet another case of missing podman-wait. In these two, I see
no reason to run containers detached, so I just removed "-d"
```release-note
None
```
> e2e: logs test: fix flakes

- .github/ISSUE_TEMPLATE/bug_report.yaml
Mention that using `su` does not establish a proper login session required for running rootless Podman.  It is a common and reoccurring issue.  Mentioning that in the issue template may guide users into resolving the issue before opening an issue.
```release-note
None
```
> [CI:DOCS] issue template: mention `su`

- test/system/010-images.bats
- test/system/170-run-userns.bats
- test/system/410-selinux.bats
- test/system/500-networking.bats
- test/system/helpers.bash
Several tweaks to see if we can track down #17216, the unlinkat-ebusy
flake:
- teardown(): if a cleanup command fails, display it and its
output to the debug channel. This should never happen, but
it can and does (see #18180, dependent containers). We
need to know about it.
- selinux tests: use unique pod names. This should help when
scanning journal logs.
- many tests: add "-f -t0" to "pod rm"
And, several unrelated changes caught by accident:
- images-commit-with-comment test: was leaving a stray image
behind. Clean it up, and make a few more readability tweaks
- podman-remote-group-add test: add an explicit skip()
when not remote. (Otherwise, test passes cleanly on
podman local, which is misleading)
- lots of container cleanup and/or adding "--rm" to run commands,
to avoid leaving …
> system tests: instrument, to try to catch unlinkat-ebusy

- pkg/rootless/rootless_linux.c
- test/system/950-preexec-hooks.bats
The long term goal was to provide the customer with a way to turn on the
preexec_hooks processing of scripts by having some kind of configuration
that could be read.  I had tried putting it into containers.conf to
start, but that turned out to be unyieldly quickly, and time is of
the essence for this fix.  That is mostly due to the fact that this
code is preexecution and in C, the containers.conf file is read in
Go much further down the stack.
After first trying this process using an ENVVAR, I have
thought it over and chatted with others, and will now look for a
/etc/containers/podman_preexec_hooks.txt file to exist.  If the admin
had put one in there, we will then process the files in the
directories `/usr/libexec/podman/pre-exec-hooks`
and `/etc/containers/pre-exec-hooks`. …
> Add file switch for pre-exec hooks

- pkg/specgen/generate/container.go
- test/e2e/build/basicalpine/Containerfile.with_label
- test/e2e/run_test.go
These annotations can have security implications - crun, for example, allows rootless containers to preserve the user's groups through an annotation. We absolutely should not include annotations from an untrusted image off the internet by default.
We may consider whitelisting some annotations (e.g. the legacy WASM annotations), but given that there is now a more explicit way of specifying an image uses the WASM runtime in the OCI image spec, I'm just tearing this out entirely for now.
```release-note
Security: annotations from images are no longer applied to containers.
```
> Do not include image annotations when building spec

- docs/source/markdown/podman-run.1.md.in
- libpod/container_internal_common.go
- test/system/030-run.bats
Fixes: https://github.com/containers/podman/issues/18531
```release-note
/run/.containerenv file is created even when a tmpfs is mounted on /run.
```
> Fix handling of .containenv on tmpfs

- cmd/podman/root.go
- docs/source/markdown/podman.1.md
The `--network-cmd-path` CLI option only affects rootless networks using `slirp4netns(1)`, not `pasta(1)`.  Following #18568 Podman should rather use the more generic `r.config.FindHelperBinary()` method (and therefore honour the `helper_binaries_dir` config) to find the path to the `slirp4netns` binary and deprecate the misleading `--network-cmd-path` CLI option.  However, since this wasn't implemented yet we can't deprecate `--network-cmd-path` as of now.  Adding a note anyway.
Fixes #18560
```release-note
None
```
Cc: @Luap99
> [CI:DOCS] Fix documentation of `--network-cmd-path` CLI option

- pkg/api/handlers/libpod/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/save_test.go
Make sure that the directory formats are not just substituted with their archive counterparts but actually tar'ed up directories.  Also make sure that the clients don't get chown errors by setting rootless user and group ID instead of O when running in the user namespace.
Fixes: #15897
```release-note
Fix permissions and format errors when using the oci-dir and docker-dir format in the libpod/images/export REST API.
```
> remote-save: fix permissions and dir formats

- .cirrus.yml
RHEL release-branches potentially need to be maintained for a very long time.  Improve reliability and CI-speed by skipping tasks which are not needed for RHEL.  For example, there will (likely) never be RHEL releases of the MacOS or Windows versions of podman-remote.  Also, relocate the `win_installer_task` in the config. to better reflect it's sequence among CI tasks.
```release-note
None
```
> Skip rhel-release branch unnecessary CI tasks

- cmd/podman/machine/init.go
- cmd/podman/machine/rm.go
- cmd/podman/machine/ssh.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- docs/source/markdown/podman-machine-init.1.md.in
- docs/source/markdown/podman-machine-inspect.1.md
- docs/source/markdown/podman-machine-os-apply.1.md
- docs/source/markdown/podman-machine-rm.1.md
- docs/source/markdown/podman-machine-set.1.md.in
- docs/source/markdown/podman-machine-ssh.1.md
- docs/source/markdown/podman-machine-start.1.md
- docs/source/markdown/podman-machine-stop.1.md
When no name arg is given to Podman machine commands, Podman assumes the machine name is podman-machine-default. Document this behavior.
```release-note
None
```
Fixes: https://github.com/containers/podman/issues/17962
> [CI:DOCS] Document podman-machine-default behavior

- test/e2e/image_sign_test.go
Reason: gpg tests all run with a different GNUPGHOME, and gpg-agent
does not like that, and there's no longer any way to run gpg
without the agent. So, do not run these tests in parallel, and
clean up agent after each test.
Fixes: #17966 (I hope)
May also fix #18358 but it will take some time to be sure.
```release-note
None
```
> e2e: serialize gpg tests

- test/e2e/image_sign_test.go
Followup to #18578: move Serial to Describe(), in case new
tests get added to this module. And, explain the reasoning.
```release-note
None
```
> e2e: refactor and document serialization

- Makefile
- test/README.md
When running ginkgo tests locally we often only want to test a small subset. I think most people just add the `FIt` block but then you need to remember to undo that before pushing the changes.
With this change you can just run:
```
make localintegration FOCUS="test name here"
make localintegration FOCUS_FILE="some_test.go"
```
I updated the test Readme to use this new syntax.
The options just map to the ginkgo options, see the upstream docs linked in the readme for more information about syntax.
```release-note
None
```
> Makefile: add ginkgo FOCUS/FOCUS_FILE options

- pkg/machine/connection.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
gvproxy listens on 127.0.0.1, using localhost as hostname can result in the client trying to connect to the ipv6 localhost (`::1`). This will fail as shown in the issue. This switches the hostname in the system connection to 127.0.0.1 to fix this problem.
I switched the qemu, hyperV and WSL backend. I haven't touched the applehv code because it uses two different ips and I am not sure what is the correct thing there. I leave this to Brent to figure out.
[1] https://github.com/containers/gvisor-tap-vsock/blob/main/cmd/gvproxy/main.go#L197-L199
Fixes #16470
```release-note
Fixed a problem where podman machine connections would try to connect to the ipv6 localhost ipv6 (::1).
```
> machine: fix default connection URL to use 127.0.0.1

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
- test/system/070-build.bats
- test/system/helpers.bash
In run_podman(), display a nanosecond-level timestamp next to
each command and its output.
Because this clutters the results, teach logformatter to grok
these new timestamps, strip them, and display a more human-readable
time delta in the left-hand timestamp column. logformatter started off
as a mess and is now, well, 🤮. I'm sorry. I just hope its results
make it worthwhile.
```release-note
None
```
> system tests: add precision timestamps

- pkg/api/handlers/compat/images_build.go
- pkg/api/server/register_images.go
- test/apiv2/10-images.at
`pull` parameter in `build` must accept string just like docker.
Ref: https://docs.docker.com/engine/api/v1.42/#tag/Image/operation/ImageBuild
Closes: https://github.com/containers/podman/issues/17778
```release-note
compat,build: pull must accept string
```
> compat,build: pull must accept string

- docs/kubernetes_support.md
- docs/source/markdown/podman-container-clone.1.md.in
- docs/source/markdown/podman-pod-clone.1.md.in
'make docs' has been spitting out these warnings:
WARNING: go-md2man does not handle node type HTMLSpan
Warnings suck, they cost us important time and attention.
This warning is always caused by left-angle-brackets in markdown
but they are very hard to find. I've found them and fixed them.
Warnings are now gone.
```release-note
None
```
> [CI:DOCS] fix HTMLSpan warnings

- pkg/systemd/generate/containers.go
- pkg/systemd/generate/pods.go
- test/e2e/generate_systemd_test.go
Init containers are currently not properly supported in generate-systemd and there are no plans to do so since all focus lies on Quadlet going forward.
Hence, generate systemd should through an error.
Closes: #18585
```release-note
None
```
> generate systemd: error on init containers

- pkg/api/handlers/compat/images.go
- test/apiv2/10-images.at
- test/apiv2/test-apiv2
Accept a tag in the compat api endpoint. For the fromImage param we already parse it but for fromSrc we did not.
Fixes #18597
```release-note
The compat API now correctly accpets a tag in the images/create?fromSrc endpoint.
```
> compat: accept tag in /images/create?fromSrc

- test/e2e/login_logout_test.go
- test/e2e/push_test.go
We should not change selinux, in a parallel context this can change the behavior of other tests and we should never disable selinux anyway.
Lets see if this passes CI or not.
Fixes #18564
```release-note
None
```
> test/e2e: do not call setenforce

- docs/source/markdown/options/userns.container.md
- pkg/specgenutil/specgen.go
- test/e2e/run_userns_test.go
the combination --pod and --userns is already blocked.  The PODMAN_USERNS environment variable instead circumvents the check. Make sure the combination is also blocked, otherwise we end up creating containers in a different user namespace than their pod.
Ideally a container should be able to do that, but its user namespace must be a child of the pod user namespace, not a sibling.  Since nested user namespaces are not allowed in the OCI runtime specs, disallow this case, since the end result is just confusing for the user.
Closes: https://github.com/containers/podman/issues/18580
```release-note
Now PODMAN_USERNS is ignored if --pod is specified
```
> run: block PODMAN_USERNS and --pod

- .cirrus.yml
- contrib/cirrus/CIModes.md
- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
Rather than supporting a special-mode *just* for netavark/aardvark
testing [in podman CI], support testing with all the latest
`podman-next` COPR packages with a `[CI:NEXT]` magic string in ***DRAFT*** PRs.
The idea here is very similar to the netavark/aardvark special mode it
replaces.  Most podman-dependencies do not have the level of
comprehensive CI as exist here.  This new CI-mode allows testing
upstream updates to podman-dependencies without needing to roll out
a whole new package/release for them.
Also update documentation for this new mode.
```release-note
None
```
> Cirrus: Add support for podman-next magic

- cmd/podman/kube/play.go
- pkg/bindings/kube/kube.go
- test/e2e/play_kube_test.go
- test/system/700-play.bats
Enable the --configmap flag for the remote case of podman
kube play. Users can pass in the paths to the configmap files
for kube play to use when creating the pods and containers from
a kube yaml file. The configmap file is read and the contents are
appended to the contents of the main yaml file before passed to the
remote client.
Fixes https://github.com/containers/podman/issues/17513
```release-note
Add --configmap flag to podman-remote kube play.
```
> Add --configmap to podman-remote kube play

- libpod/stats_linux.go
- test/e2e/stats_test.go
b25b330306782019d7aaf7618cd4598a9ae87250 introduced this behaviour.
It was fine at the time because we didn't support "container update", so the limit could not be changed at runtime.  Since it is not possible to change the memory limit at runtime, read the limit as reported from the cgroup.
https://github.com/containers/crun/pull/1217 is required for crun.
[NO NEW TESTS NEEDED] needs a new crun release
Closes: https://github.com/containers/podman/issues/18621
```release-note
podman stats reads the memory limit from the cgroup
```
> stats: get mem limit from the cgroup

- cmd/podman/root.go
- docs/source/markdown/podman.1.md
- libpod/info_linux.go
- libpod/networking_linux.go
- libpod/networking_slirp4netns.go
Fixes: #18568
```release-note
If --network-cmd-path is not set, then slirp4netns binary will first be searched using the `helper_binaries_dir` option in `containers.conf`, and second using the `$ PATH` environment variable.
```
> podman: Added find slirp4netns binary file from helper_binaries_dir

- test/e2e/quadlet/socketactivated.container
- test/e2e/quadlet_test.go
These files
* _test/e2e/quadlet/device.volume_
* _test/e2e/quadlet/device-copy.volume_
were added in
https://github.com/containers/podman/pull/17217/files
but only the test for  _test/e2e/quadlet/device-copy.volume_
was enabled.
I assume that was a mistake. Let's enable 
_test/e2e/quadlet/device.volume_
too.
Remove unused file
_test/e2e/quadlet/socketactivated.container_
```release-note
None
```
> Quadlet tests: enable device.volume and remove socketactivated.container

- cmd/podman/networks/create.go
- cmd/podman/networks/update.go
- test/e2e/run_networking_test.go
The examples show that --dns-add 8.8.8.8,1.1.1.1 is valid but it fails, fix this by using StringSliceVar which splits at commas. Added tests to ensure it is working.
Fixes #18632
```release-note
Allow comma separate list of dns servers in `podman network create --dns` and podman network update --dns-add/--dns-drop` 
```
> network create/update: allow dns servers comma separated

- libpod/events/filters.go
- test/e2e/common_test.go
- test/e2e/events_test.go
- test/system/090-events.bats
Fixes: https://github.com/containers/podman/issues/18618
Yes
```release-note
None
```
> fix: event --filter volume=vol-name should compare the event name with volume name

- contrib/cirrus/timestamp.awk
- test/system/helpers.bash
Instrument system tests in hopes of tracking down #17216,
the unlinkat-ebusy-hosed flake.
Oh, also, timestamp.awk: timestamps have always been UTC, but                                                                                                   
add a 'Z' to make it unambiguous.
```release-note
None
```
> TEMPORARY(?) instrumentation for unlinkat-ebusy

- libpod/container_internal.go
- libpod/runtime_ctr.go
https://github.com/containers/podman/pull/18634/checks?check_run_id=13617533713 contains a failure with 
```
cleaning up container … storage: %!w(<nil>)
```
Fix that `nil` usage; then look at the pattern, and replace copy&pasted logic with helpers, at the cost of changing the error / log messages a bit.
See individual commits for more details. If you’d prefer just the two-line bug fix without the other changes, that’s fine with me too.
```release-note
None
```
> Fix, and reduce repetitiveness, in container cleanup error handling

- test/e2e/rmi_test.go
This test is intended to test concurrent removals, so don't risk a removal breaking a build.
Fixes #18659 .
(The situation that removals can break a build in progress is a real problem that should be fixed, but that's not a target of this test.)
Cc: @vrothberg , the test was added in #9266, to make sure I didn’t misunderstand the purpose.
```release-note
None
```
> In a concurrent removal test, don't remove concurrently with builds

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/podmanargs.kube
- test/e2e/quadlet/podmanargs.network
- test/e2e/quadlet/podmanargs.volume
- test/e2e/quadlet_test.go
PodmanArgs allows users to pass arguments not explicitly supported by Quadlet.
Yes
```release-note
Quadlet - add support for PodmanArgs to all groups
```
> Quadlet - add support for PodmanArgs to all groups

- cmd/podman/networks/create.go
- cmd/podman/networks/update.go
- libpod/container.go
- libpod/container_api.go
- libpod/container_internal.go
- libpod/networking_common.go
- libpod/networking_linux.go
- pkg/api/handlers/compat/containers_create.go
- pkg/api/handlers/compat/images.go
- pkg/bindings/containers/logs.go
- pkg/bindings/test/exec_test.go
- pkg/domain/infra/tunnel/images.go
- pkg/machine/connection.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
- test/apiv2/10-images.at
- test/apiv2/20-containers.at
- test/apiv2/test-apiv2
- test/e2e/logs_test.go
- test/e2e/run_networking_test.go
see commits
```release-note
Allow comma separate list of dns servers in `podman network create --dns` and podman network update --dns-add/--dns-drop` 
Fixed a problem where podman machine connections would try to connect to the ipv6 localhost ipv6 (::1).
The compat API now correctly accpets a tag in the images/create?fromSrc endpoint.
Fixed a bug in the compat container create endpoint which could result in a "duplicate mount destination" error when the volume path was not "clean", e.g. included a final slash at the end.
podman machine rm with the qemu backend now correctly removes the machine connection after the confirmation message not before.
podman save on windows can now write to stdout by default.
The remote API exec inspect call will now correctly displays updated information, …
```
> [v4.5] backport my fixes from the past few weeks

- test/system/255-auto-update.bats
RHEL gating tests failing, because (sigh) journalctl doesn't
work rootless on RHEL.
I think the flake is fixed anyway, so we don't need this.
This reverts commit ba141adce489a0188b91dad36f055607b23b72cc.
```release-note
None
```
> Revert "test/system/255-auto-update.bats: add debug logs"

- docs/source/markdown/podman-info.1.md
- libpod/define/info.go
- libpod/info_linux.go
- libpod/networking_pasta_linux.go
- test/system/005-info.bats
Fixes: #18561
```release-note
podman info will output information about the pasta if it exists in helper_binaries_dir or $PATH
```
> podman: Add pasta to podman info

- .packit.yaml
- rpm/Makefile
- rpm/podman.spec
- rpm/update-spec-provides.sh
- rpm/update-spec-version.sh
Also address review concerns in pr#18675.
```release-note
None
```
> [CI:BUILD] Packit: set propose-downstream action type to pre-sync

- cmd/podman/containers/pause.go
- cmd/podman/containers/ps.go
- cmd/podman/containers/restart.go
- cmd/podman/containers/rm.go
- cmd/podman/containers/start.go
- cmd/podman/containers/stop.go
- cmd/podman/containers/unpause.go
- cmd/podman/images/list.go
- cmd/podman/images/search.go
- cmd/podman/pods/ps.go
- cmd/podman/secrets/list.go
- cmd/podman/volumes/create.go
- cmd/podman/volumes/list.go
- test/e2e/images_test.go
- test/e2e/pause_test.go
- test/e2e/pod_ps_test.go
- test/e2e/ps_test.go
- test/e2e/restart_test.go
- test/e2e/rm_test.go
- test/e2e/secret_test.go
- test/e2e/start_test.go
- test/e2e/stop_test.go
- test/e2e/volume_ls_test.go
```release-note
User's won't be able to use `--filter label=a,label=b` but will need to specify multiple `--filter` flags
```
Currently using some complex filters (for example in `podman ps`) leads to parsing failures, for example:
```console
podman ps -q -a --filter label=dev.containers.id=devpod --filter 'label=devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/git:1"},{"id":"ghcr.io/devcontainers/features/go:1","customizations":{"vscode":{"extensions":["golang.Go"]}},"init":true,"capAdd":["SYS_PTRACE"],"securityOpt":["seccomp=unconfined"]},{"id":"ghcr.io/devcontainers/features/node:1","customizations":{"vscode":{"extensions":["dbaeumer.vscode-eslint"]}}},{"remoteUser":"vscode","customizations":{"vscode":{"extensions":["gol …
```
> fix: move filter flags from StringSliceVar to StringArrayVar

- Makefile
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-systemd.unit.5.md
- hack/man-page-table-check
Work around a go-md2man bug, and add a check script to make sure
this doesn't hit us again.
Background: go-md2man can't deal with a left-hand column > 31 chars.
It produces man pages that look like:
| Something With >31 Character |                |
|                              | ..description  |
(should be all on one row). It also has trouble when the vertical
bars are misaligned: it completely removes the right-hand side.
There's almost certainly a better solution: fix go-md2man, or
use a different conversion tool, or maybe even pre/postprocess.
But this is a quick interim solution.
Sorry for the perl. This could be done in bash/sed/awk/grep,
but not with any sort of sane error messages.
```release-note
Fix broken tables in man pages
```
> Man pages: fix broken tables

- pkg/rootless/rootless_linux.go
- test/system/032-sig-proxy.bats
- test/system/550-pause-process.bats
- test/system/helpers.sig-proxy.bash
There are quite a lot of places in podman were we have some signal
handlers, most notably libpod/shutdown/handler.go.
However when we rexec we do not want any of that and just send all
signals we get down to the child obviously. So before we install our
signal handler we must first reset all others with signal.Reset().
Also while at it fix a problem were the joinUserAndMountNS() code path
would not forward signals at all. This code path is used when you have
running containers but the pause process was killed.
Fixes https://github.com/containers/podman/issues/16091
Given that signal handlers run in different goroutines parallel it would
explain why it flakes sometimes in CI. However to my understanding this
flake can only happen when the pause process is dead before we run the
podman …
> pkg/rootless: correctly handle proxy signals on reexec

- docs/source/markdown/podman-network-create.1.md
- go.mod
- go.sum
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/types/const.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Addresses:
https://bugzilla.redhat.com/show_bug.cgi?id=2210113
https://bugzilla.redhat.com/show_bug.cgi?id=2210111
```release-note
None
```
> [v4.4.1-rhel] Add new bclim macvlan option

- cmd/podman/common/completion.go
- test/system/600-completion.bats
When we do path completion in images a user could try to complete a simple relative path, e.g. podman run $IMAGE e... should complete to etc if this path exists in the image. Right now we panic in this case as the current check didn't account for an empty string in simplePathJoinUnix(). In such a case return the path directly because we can not alter what the user typed on the cli and must return a path without slash as well in order for the shell to suggest the completion.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2209809
```release-note
Fixed a possible panic in the shell completion code when relative paths are completed. 
```
> completion: fix panic in simplePathJoinUnix()

- test/e2e/common_test.go
"image rm concurrent" test is still failing, even after #18664:
Error: no contents in "/tmp/podman_test967723851/Dockerfile"
Probable cause: the images are built in parallel, and p.BuildImage()
writes one single Dockerfile. (This almost certainly renders the
test less effective than intended, since the generated images
might end up being identical).
Solution: write and use a uniquely-named Dockerfile
```release-note
None
```
> e2e: make BuildImage parallel-safe

- docs/source/markdown/options/authfile.md
@rhatdan @mheon @vrothberg ptal.
I have not checked this is the location actually being used on Windows/macOS. I got the information from the Arch docs here: https://man.archlinux.org/man/containers-auth.json.5.
> [CI:DOCS] authfile.md: add default path of file for Windows/macOS.

- test/system/271-tcp-cors-server.bats
run_podman cannot be backgrounded. Use $PODMAN instead.
This is just a desperate attempt to fix a [port busy flake](https://api.cirrus-ci.com/v1/artifact/task/6020032262569984/html/sys-podman-fedora-38-rootless-host-sqlite.log.html#t--00378):
```
[+1281s] not ok 378 podman system service - tcp without CORS
...
<+053ms> # $ podman system service tcp:localhost:64512 -t 20
<+068ms> # Error: unable to create socket localhost:64512: listen tcp 127.0.0.1:64512: bind: address already in use
```
Regardless of whether this fixes the flake, it's a necessary action.
```release-note
None
```
> systests: fix improper backgrounding of run_podman

- libpod/container_internal_common.go
- libpod/rlimit_int64.go
- libpod/rlimit_uint64.go
- pkg/specgen/container_validate.go
- pkg/specgen/generate/oci.go
- test/e2e/inspect_test.go
- test/system/045-start.bats
Fixes #18714
```release-note
Fixed an issue where lowering the ulimit -u after a container got created will lead to the container failing to launch.
```
This touches a lot of code I'm not familiar with, so I'm playing it slow. Starting by adding tests that are supposed to fail on current main.
> fix ulimit issue

- test/system/252-quadlet.bats
Systemd doesn't support `never` and logs a warning, systemd uses no as default so we do not have to specify it at all.
Check systemd.service(5) for the systemd docs.
Fixes #18743
```release-note
None
```
> test/system: quadlet use correct systemd restart policy

- libpod/stats_common.go
- libpod/stats_freebsd.go
- libpod/stats_linux.go
- pkg/api/handlers/compat/containers_stats.go
- test/apiv2/19-stats.at
closes #15754 
```release-note
None
```
> Fix: display online_cpus in compat REST API

- libpod/container_internal_linux.go
- test/e2e/run_volume_test.go
if /run is on a volume do not create the file /run/.containerenv as it would leak outside of the container.
Closes: https://github.com/containers/podman/issues/14577
Backporting #14582 to v4.0-rhel to complete the backports to https://issues.redhat.com/browse/OCPBUGS-7522
```release-note
None
```
> [v4.0-rhel] container: do not create .containerenv with -v SRC:/run

- test/e2e/common_test.go
- test/e2e/search_test.go
Intended to fix an obscure, unlikely race condition in which (I
think) two parallel jobs called GetPort() and were assigned the
same port.
Also, add actual proper testing to two HTTP-registry tests, and
Skip a third that's a waste of cycles (filed #18768)
```release-note
None
```
> e2e: GetPort(): safer allocation of random ports

- test/e2e/generate_kube_test.go
Add a test for generate kube to verify that the ulimit
annotation is not set for the default case when the user
doesn't set any ulimits.
Fixes https://github.com/containers/podman/issues/18555
Implementation was done in https://github.com/containers/podman/pull/18721 and this PR adds a regression test.
```release-note
None
```
> Add default ulimit test for gen kube

- contrib/cirrus/logformatter
Fix an oops in my ginkgo-v2 handling: subtest-status was
getting re-reset back to "passed", resulting in incorrect
and misleading green titles on failed tests.
```release-note
None
```
> logformatter: proper status color for failed tests

- libpod/networking_pasta_linux.go
- test/system/505-networking-pasta.bats
setupPasta() has logic to handle forwarding of TCP or UDP ports.  It has what looks like logic to give an error if trying to forward ports of any other protocol.  However, there's a straightforward error in this that it will in fact only give the error if you try to use a protocol called "default".  Other unknown protocols will fall through and result in a nonsensical pasta command line which will almost certainly cause a cryptic error later on.
```release-note
None
```
> pasta: Correct handling of unknown protocols

- cmd/podman/containers/run.go
- cmd/podman/root.go
- docs/source/markdown/podman.1.md
- test/system/001-basic.bats
- test/system/030-run.bats
This adds an additional parameter, "--out", which can be used to capture the output of any part of podman. This is similar to the original "--noout", but instead of redirecting stdout to "/dev/null" it allows the user to choose the file that is being written to. Thus using the parameter as in `podman --out /dev/null ...` corresponds to the same logic. The original "--noout" parameter was left alone as I expect someone is already depending on this functionality. The original "--noout" parameter had a bug in that "/dev/null" was not being opened as writable. This results in an EBADF error being returned everytime the fd being written to gets used.
The PR adds the additional parameter using the same logic as "--noout", fixes the prior-mentioned issue with "--noout", and adds testcases for …
> Added the "--out" parameter and fixed an issue with "--noout" which prevented stdout from being written to.

- troubleshooting.md
Just update troubleshooting docs #13039, no other change.
```release-note
update troubleshooting for resolving insecure registry.
```
> [CI:DOCS] feat: add insecure registry troubleshooting solution

- libpod/pod.go
- libpod/stats.go
- pkg/api/handlers/compat/containers_stats.go
- pkg/domain/infra/abi/containers.go
When you run podman stats, the first interval always shows the wrong cpu
usage. To calculate cpu percentage we get the cpu time from the cgroup
and compare this against the system time between two stats. Since the
first time we do not have a previous stats an empty struct is used
instead. Thus we do not use the actual running time of the container but
the current unix timestamp (time since Jan 1 1970).
To fix this we make sure that the previous stats time is set to the
container start time, when it is empty.
[NO NEW TESTS NEEDED] No idea how I could create a test which would have
a predictable cpu usage.
See the linked bugzilla for a reproducer.
Addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2210139
```release-note
None
```
> [v3.0.1-rhel]  podman stats: calc CPU percentage correctly

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/disableselinux.container
- test/e2e/quadlet/nestedselinux.container
- test/e2e/quadlet_test.go
This flag will allow us to run nested containers within a quadlet service.
```release-note
Quadlet now supports Nested SELinux containers using the SecurityLabelNetsted=true flag.
```
> Add support for SecurityLabelNested flag in quadlet

- pkg/machine/applehv/machine.go
- pkg/machine/hyperv/machine.go
- pkg/machine/keys.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
- pkg/util/utils.go
- pkg/util/utils_test.go
> refactor: improve get identity path duplicate code

- cmd/podman/system/locks.go
- docs/source/markdown/podman-container-inspect.1.md.in
- docs/source/markdown/podman-pod-inspect.1.md.in
- docs/source/markdown/podman-volume-inspect.1.md
- docs/source/markdown/podman-volume-ls.1.md.in
- libpod/container_inspect.go
- libpod/define/container_inspect.go
- libpod/define/info.go
- libpod/define/pod_inspect.go
- libpod/define/volume_inspect.go
- libpod/info.go
- libpod/lock/file_lock_manager.go
- libpod/lock/in_memory_locks.go
- libpod/lock/lock.go
- libpod/lock/shm/shm_lock.c
- libpod/lock/shm/shm_lock.go
- libpod/lock/shm/shm_lock.h
- libpod/lock/shm/shm_lock_nocgo.go
- libpod/lock/shm_lock_manager_linux.go
- libpod/lock/shm_lock_manager_unsupported.go
- libpod/pod_api.go
- libpod/runtime.go
- libpod/volume_inspect.go
- pkg/domain/entities/engine_container.go
- pkg/domain/entities/system.go
- pkg/domain/infra/abi/system.go
- pkg/domain/infra/tunnel/system.go
- test/e2e/info_test.go
Deadlocks are among the most annoying parts of Podman to debug (second only to the intricacies of the REST attach endpoints, in my opinion). Part of this is that there wasn't really a good way to tell what was going on - all our locks are in-memory, so an strace just shows `futex` calls on inscrutable memory addresses (which blend into the `futex` calls that the Go runtime is doing on its own, making things extra fun).
This PR attempts to remedy this in 3 ways:
* Add the number of the lock used by a container/pod/volume to the output of `podman inspect` - allows for quick spot checks to verify that numbers assigned look sane
* Add the number of available locks to `podman info` - so we can easily see if the system has run entirely out of locks (usually because folks forget to prune …
> Add support for lock debugging

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
- test/e2e/common_test.go
Ginkgo test names can have more than two levels: there can be
a nested series of Describes() before the final It(). (e.g.,
quadlet_test.go). Handle that.
Before: we just assumed that the third-or-maybe-fourth line
after a "-----" divider was the test name.
Now: examine every line after the "-----" divider, until the
first empty line. Lines with /path/to/source/file are ignored,
lines with text strings are assembled together to make anchors.
This is still imperfect but it's much better than before.
SPECIAL NOTE: in order to allow linking to timing results
in the AfterSuite, I've changed the test name from Leaf to Full.
This will now be a much longer string, and hence much less
readable, but I'm inclined to think it's more correct. Please
review carefully and lmk if I should revert. …
> logformatter: better recognition of test names

- test/e2e/exec_test.go
- test/e2e/search_test.go
- test/e2e/trust_test.go
- trust_test: adding 'Ordered' seems to resolve a very common
flake. I've tested this for dozens of CI runs, and haven't
seen the flake recur (normally it fails every few runs).
- exec and search tests: add FlakeAttempts(3). This is a NOP
under our current CI setup, in which we run ginkgo with
a global --flake-attempts=3. I am submitting this as an
optimistic step toward a no-flake-attempts world (#17967)
Fixes: #18358
```release-note
None
```
> e2e: add ginkgo decorators to address flakes

- cmd/podman/pods/ps.go
- docs/source/markdown/podman-pause.1.md.in
- docs/source/markdown/podman-pod-ps.1.md.in
- docs/source/markdown/podman-ps.1.md
- docs/source/markdown/podman-restart.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-start.1.md.in
- docs/source/markdown/podman-stop.1.md.in
- docs/source/markdown/podman-unpause.1.md.in
- libpod/define/config.go
- pkg/domain/filters/containers.go
- pkg/domain/filters/pods.go
- test/system/040-ps.bats
- test/system/200-pod.bats
For filter=id=XXX:
if XXX is only hex characters, treat it as a PREFIX
otherwise, treat it as a REGEX
Fixes: #18471
```release-note
Filtering by 'id=xxx' will now treat xxx as a CID prefix, not a regular expression
```
> filters: better handling of id=

- .github/actions/check_cirrus_cron/cron_failures.sh
- .github/actions/check_cirrus_cron/make_email_body.sh
- .github/actions/check_cirrus_cron/rerun_failed_tasks.sh
- .github/actions/check_cirrus_cron/test.sh
- .github/workflows/check_cirrus_cron.yml
- .github/workflows/rerun_cirrus_cron.yml
Due to a bad file-format design, if a cirrus-cron job happened to have a name w/ spaces, the generated e-mail text would be broken.  [For example](https://github.com/containers/automation_images/actions/runs/5195573071/jobs/9368432815#step:3:31):
```
Cron build 'VM' Failed: https://cirrus-ci.com/build/Image Maintenance
5630822628196352
```
Fix this by flipping the field-order in an intermediate file, so the build ID comes first, then the job name.  This makes it much easier for `read` to process, since all words will be stored into the final variable (now the job name).
Also change all variables that reference this intermediate file such that they continue to reflect the expected field order.  Update script tests and add a new test to confirm expected file processing and output. …
> [CI:BUILD] GHA: Fix bad job-names & links in monitoring emails

- hack/podman-registry
- hack/podman-registry-go/registry.go
- hack/podman-registry-go/registry_test.go
- pkg/bindings/test/auth_test.go
- pkg/bindings/test/images_test.go
- pkg/bindings/test/manifests_test.go
- test/e2e/libpod_suite_remote_test.go
- test/e2e/manifest_test.go
First: fix podman-registry script so it preserves the initial $PODMAN,
so all subsequent invocations of ps, logs, and stop will use the
same binary and arguments. Until now we've handled this by requiring
that our caller manage $PODMAN (and keep it the same), but that's
just wrong.
Next, simplify the golang interface: move the $PODMAN setting into
registry.go, instead of requiring e2e callers to set it. (This
could use some work: the local/remote conditional is icky)
And, minor cleanup: comments, and add an actual error-message check
Reason for this PR is a recurring flake, #18355, whose multiple
failure modes I truly can't understand. I don't think this PR
is going to fix it, but this is still necessary work.
```release-note
None
```
> podman-registry: simpler, safer invocations

- Makefile
On FreeBSD, it usually lives in /usr/local/bin/bash. This uses the shell 'commmand' builtin to find the path which works in bash, dash and the FreeBSD /bin/sh.
```release-note
None
```
> Makefile: don't hard-code the path for bash

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/sysctl.container
- test/e2e/quadlet_test.go
AddSysctl allows to set namespaced kernel parameters for containers.
Closes  #18727.
Yes
```release-note
Quadlet - Add support for --sysctl via AddSysctl flag for containers.
```
Signed-off-by: Laurenz Kruty <git@laurenzkruty.de>
> Quadlet: Add support for --sysctl 

- Makefile
Address a build break on Ubuntu 20.04 in the Makefile whereby calling `command` fails
Fixes #18836
```release-note
None
```
Signed-off-by: Andy Edwards <andy.edwards@uk.ibm.com>
> Makefile to force a shell when running command

- pkg/specgen/generate/oci_linux.go
Fixes #18848
```release-note
Fixed index out of range error when unmask is set to empty
```
> fix(specgen): index out of range when unmask=[]

- test/system/250-systemd.bats
Remove an outdated comment on the absence of exit-code propagation when running K8s workloads in systemd.  The `podman-kube@` systemd template is using default restart policy of the system.  The exit-code propagation is tested in other tests, so we can keep the logic as is.
```release-note
None
```
> 250-systemd.bats: remove outdated comment

- libpod/container_internal_common.go
- pkg/checkpoint/checkpoint_restore.go
- pkg/criu/criu_linux.go
- pkg/criu/criu_unsupported.go
- test/e2e/checkpoint_image_test.go
- test/e2e/checkpoint_test.go
There is weird issue #18856 which causes the version check to fail. Return the underlying error in these cases so we can see it and debug it.
```release-note
None
```
> criu: return error when checking for min version

- docs/source/markdown/podman-info.1.md
- libpod/define/info.go
- libpod/info.go
- libpod/info_linux.go
- libpod/oci_conmon_common.go
- libpod/util.go
- test/e2e/info_test.go
- test/system/005-info.bats
podman info prints the network information about binary path,
package version, program version and DNS information.
Fixes: #18443
<details>
<summary>cni info</summary>
```yaml
networkBackendInfo:
backend: cni
dns:
package: podman-plugins-4.5.0-1.fc38.x86_64
path: /usr/libexec/cni/dnsname
version: |-
CNI dnsname plugin
version: 1.3.1
commit: unknown
package: |-
containernetworking-plugins-1.1.1-16.fc38.x86_64
podman-plugins-4.5.0-1.fc38.x86_64
path: /usr/libexec/cni
```
</details>
<details>
<summary>netavark info</summary>
```yaml
networkBackendInfo:
backend: netavark
dns:
package: aardvark-dns-1.6.0-1.fc38.x86_64
path: /usr/libexec/podman/aardvark-dns
version: aardvark-dns 1.6.0
package: netavark-1.6.0-2.fc38.x86_64
path: /usr/libexec/podman/netavark
version: netavark 1.6.0
```
</details> …
> libpod: Podman info output more network information

- Makefile
This simply uses GNU grep instead of the FreeBSD base grep.
```release-note
None
```
> Makefile: add support for 'make help' on FreeBSD

- docs/source/markdown/podman-network-create.1.md
see https://github.com/containers/common/pull/1474
```release-note
podman network create supports a new option called `bclim` for the `macvlan` driver.
```
> [CI:DOCS] network-create: document new bclim option

- libpod/container_api.go
When waiting for a container, there may be a time window where conmon has already exited but the container hasn't been fully cleaned up. In that case, we give the container at most 20 seconds to be fully cleaned up.  We cannot wait forever since conmon may have been killed or something else went wrong.
After the timeout, we optimistically assume the container to be cleaned up and its exit code to present.  If no exit code can be found, we return an error.
Indicate in the error whether the timeout kicked in to help debug (transient) errors and flakes (e.g., #18860).
```release-note
None
```
> container wait: indicate timeout in error

- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
Remote clients only support the docker transport which is mentioned in the destination table below.  So drop the redundant text on supported transports from the main description to avoid confusion.
Closes: #18357
```release-note
None
```
> [CI:DOCS] podman-push: rm confusion on supported transports

- contrib/cirrus/logformatter
- contrib/cirrus/logformatter.t
When an e2e test fails in AfterEach, ginkgo "helpfully" adds
a heading in that test log block:
TOP-LEVEL [AfterEach]
/path/to/source.go
Podman Desc Blah
That TOP-LEVEL line screws up our in-page links. Ignore it
both in the heading and in the bottom failure-summary lines.
Add test, including tests for bottom-summary.
```release-note
None
```
> logformatter: ignore 'TOP-LEVEL' headings

- troubleshooting.md
Add a section to the troubleshooting guide describing how to get secret mounts working in RHEL8, as discussed in
https://github.com/containers/buildah/issues/4228.
It took me a while to find this information, and a RHEL8 default setup isn't that uncommon, so I thought it would be worth the change.
> [CI:DOCS] Document how to get secret mounts working on RHEL8

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/autoupdate.container
- test/e2e/quadlet_test.go
```release-note
Quadlet .container format now supports AutoUpdate option.
```
> Add support for setting autoupdate in quadlet

- pkg/api/handlers/utils/containers.go
- test/apiv2/26-containersWait.at
The "removed" condition mapped to an undefined state which ultimately rendered the wait endpoint to return an incorrect exit code.  Instead, map "removed" to "exited" to make sure Podman returns the expected exit code.
Fixes: #18889
```release-note
Fix a bug in the wait endpoint of the compat API to correctly handle the "removed" condition.
```
> remote wait: fix "removed" condition

- test/e2e/checkpoint_image_test.go
- test/e2e/checkpoint_test.go
- test/e2e/common_test.go
- test/e2e/create_staticip_test.go
- test/e2e/pod_create_test.go
- test/e2e/run_staticip_test.go
For tests that use '--ip XX', random IP allocation is not
working well. Switch instead to a deterministic algorithm
with CPU affinity and a fudge factor for CNI.
Fixes: #18855 
```release-note
None
```
> e2e: GetSafeIPAddress() replaces GetRandomIPAddress

- cmd/podman/root.go
- docs/source/markdown/podman.1.md
- go.mod
- go.sum
- libpod/options.go
- pkg/domain/entities/engine.go
- pkg/domain/infra/runtime_libpod.go
- pkg/specgenutil/util.go
- test/e2e/pull_test.go
- vendor/github.com/containers/storage/.cirrus.yml
- vendor/github.com/containers/storage/check.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/store.go
- vendor/github.com/containers/storage/types/options.go
- vendor/modules.txt
Add support for `--imagestore` in podman which allows users to split the filesystem of containers vs image store, imagestore if configured will pull images in image storage instead of the graphRoot while keeping the other parts still in the originally configured graphRoot.
This is an implementation of
https://github.com/containers/storage/pull/1549 in podman.
```release-note
podman: add support for splitting imagestore using `--imagestore`
```
> podman: add support for splitting imagestore using `--imagestore`

- pkg/machine/applehv/machine.go
- pkg/machine/ssh.go
- pkg/machine/wsl/machine.go
Fix: https://github.com/containers/podman/issues/17403
```release-note
fix machine failed to start with exit status 255
```
Thanks, @chevdor reply: https://github.com/containers/podman/issues/17403#issuecomment-1511363735
I know this solution is not perfect as it does not really solve the problem in a true sense. However, it is the only quick solution for podman in the short term. Additionally, in the current scenario, adding the `IdentitiesOnly=yes` parameter makes logical sense because podman indeed does not need to read configurations from the `~/.ssh/config` file.
/cc @ashley-cui @baude 
> fix(ssh): machine failed to start with exit status 255

- cmd/podman/networks/create.go
- docs/source/markdown/podman-network-create.1.md
- docs/source/markdown/podman-systemd.unit.5.md
- test/e2e/network_create_test.go
The backend allows for any start/end ip in the subnet. There is no reason to limit the cli to only CIDR subnets. This allows for much more flexibility.
```release-note
`podman network create --ip-range` now accepts a new `<startIP>-<endIP>` syntax which allows more flexibility when limiting the ip range that Podman assigns.
```
> network create --ip-range allow for custom range

- cmd/podman/root.go
```release-note
Only update the help document.
```
w/o this patch
```
[ajia@Fedora36 podman]$ ./bin/podman --help
...ignore...
--imagestore image store      Path to the image store, different from `graph root`, use this to split storing the image into a separate `image store`, see `man containers-storage.conf` for details
---ignore...
```
w/ this patch
```
--imagestore string           Path to the 'image store', different from 'graph root', use this to split storing the image into a separate 'image store', see 'man containers-storage.conf' for details
```
> cmd/podman/root.go: fix help document issue of the image store

- .golangci.yml
- Makefile
- cmd/podman/system/connection/add.go
- cmd/quadlet/main.go
- libpod/container_internal_common.go
- libpod/container_internal_linux.go
- libpod/oci_conmon_common.go
- libpod/sqlite_state.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/e2e/list_test.go
- pkg/rootless/rootless_linux.go
- test/e2e/create_test.go
- test/e2e/generate_kube_test.go
- test/e2e/images_test.go
- test/e2e/inspect_test.go
- test/e2e/network_test.go
- test/e2e/pause_test.go
- test/e2e/play_kube_test.go
- test/e2e/pod_create_test.go
- test/e2e/prune_test.go
- test/e2e/restart_test.go
- test/e2e/rm_test.go
- test/e2e/start_test.go
- test/e2e/stop_test.go
- utils/utils_supported.go
Initially disable new linter (warnings).  Also fix some straight away as the warnings concerned me, especially the sql error checks.  Please refer to the individual commits for details.
```release-note
None
```
> bump golangci-lint to v1.53.3

- pkg/machine/applehv/vfkit.go
Add the functionality for a console to be dipslayed when the user runs `podman --log-level debug machine start` on MacOS. This mimics the behavior that currently exists on Linux.
Associated with: https://github.com/crc-org/vfkit/pull/44
```release-note
Adds the functionality for a user to create a console window to display the virtual machine while booting
```
> Add console mode to podman machine

- pkg/machine/ignition.go
- pkg/machine/qemu/machine_test.go
When the `machine start` command is executed, Podman automatically retrieves the current host's `*_PROXY` environment variable and assigns it directly to the virtual machine in QEMU. However, most `*_PROXY` variables are set with `127.0.0.1` or `localhost`, such as `127.0.0.1:8888`. This causes failures in network-related operations within the virtual machine due to incorrect proxy settings.
```release-note
Fix a bug proxy IP did not get properly translated when executing `machine start`
```
/cc @Luap99
> fix(machine): throw error `connection refused` after set proxy

- go.mod
- go.sum
- vendor/github.com/containers/common/libimage/image.go
- vendor/github.com/containers/common/libimage/manifest_list.go
- vendor/github.com/containers/common/libimage/manifests/manifests.go
- vendor/github.com/containers/common/libnetwork/cni/config.go
- vendor/github.com/containers/common/libnetwork/etchosts/hosts.go
- vendor/github.com/containers/common/libnetwork/internal/util/parse.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/netavark/ipam.go
- vendor/github.com/containers/common/pkg/cgroups/cpuset_linux.go
- vendor/github.com/containers/common/pkg/completion/completion.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/hooks/hooks.go
- vendor/github.com/containers/common/pkg/manifests/manifests.go
- vendor/github.com/containers/common/pkg/secrets/secrets.go
- vendor/github.com/containers/common/pkg/supplemented/supplemented.go
- vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
- vendor/github.com/onsi/ginkgo/v2/internal/focus.go
- vendor/github.com/onsi/ginkgo/v2/types/version.go
- vendor/modules.txt
To include export HostContainersInternal
Ref:
1. https://github.com/containers/common/pull/1516
2. https://github.com/containers/podman/pull/18936
```release-note
None
```
/cc @Luap99
> vendor in latests containers/common

- pkg/machine/ignition.go
- pkg/machine/qemu/machine_test.go
Use exported variables instead of hard-coded strings.
Ref: https://github.com/containers/common/pull/1516
```release-note
None
```
/cc @vrothberg @Luap99
> refactor(machine): remove hard code

- pkg/api/handlers/compat/containers_create.go
- test/apiv2/20-containers.at
The platform parameter has been ignored such that images have been looked up by name only.
Fixes: #18951
```release-note
Support the `platform` parameter in the compat API for container creation.
```
> compat API container create: handle platform parameter

- libpod/container_internal.go
- libpod/container_internal_common.go
My PR[1] to remove PostConfigureNetNS is blocked on other things I want to split this change out. It reduces the complexity when generating /etc/hosts and /etc/resolv.conf as now we always write this file after we setup the network. this means we can get the actual ip from the netns which is important.
[NO NEW TESTS NEEDED] This is just a rework.
[1] https://github.com/containers/podman/pull/18468
```release-note
None
```
> libpod: write /etc/{hosts,resolv.conf} once

- test/e2e/checkpoint_test.go
- test/e2e/common_test.go
Add header comment suggesting podman network create instead.
Stop using it in checkpoint tests. Turned out to be much more
complicated than expected.
And, remove obsolete f28-and-earlier code.
```release-note
None
```
> e2e: GetSafeIPAddress(): discourage its use

- test/e2e/logs_test.go
A few tests were doing "podman run -d" + "podman logs".
This is racy. Remove the unnecessary "-d".
And, as long as we're mucking around in here:
- remove the "-t" from the 800-lines test, so we get clean output without ^Ms
- remove unnecessary "sh", "-c" from simple echo commands
- add actual error-message checks to two places that were only checking exit status
Resolves one (not all) of the flakes tracked in #18501
```release-note
None
```
> e2e: fix one of the many log flakes

- go.mod
- pkg/api/handlers/compat/images.go
- pkg/api/handlers/compat/images_push.go
- test/apiv2/10-images.at
- test/apiv2/12-imagesMore.at
- test/apiv2/70-short-names.at
Please refer to the individual commits for details.  I am sure there are more such cases scattered across the compat and libpod API.  For now, I focus on reported issues to get the fixes out in time with the upcoming 4.6 release.
```release-note
Fix error handling in the Docker-compat API when pulling and pushing images.
```
> compat API create/pull/push: fix error handling

- test/system/helpers.bash
for #18514: if we get a timeout in teardown(), run and show
the output of podman system locks
for #18831: if we hit unmount/EINVAL, nothing will ever work
again, so signal all future tests to skip.
```release-note
None
```
> systests: test instrumentation

- test/e2e/pod_create_test.go
- test/e2e/run_device_test.go
- test/e2e/run_privileged_test.go
Replace /dev/foodevdir with unique paths, to avoid one
test's RemoveAll() from stepping on another test.
Closes: #18958
```release-note
None
```
> e2e: use parallel-safe /dev subdirectories

- Makefile
It's a bit cumbersome to manage a tooling version buried deep in a command, let alone one also buried deep in a `Makefile`.  Add a variable to hold the version number so renovate can easily manage it. This happens via a `regex` manager in the shared configuration include `containers/automation//renovate/defaults.json5`.  Also add a helpful note/reminder to humans who may want to manually change the version for some reason.
Depends on: https://github.com/containers/automation/pull/145
```release-note
None
```
> [CI:BUILD] Help Renovate manage the golangci-lint version

- libpod/oci_conmon_common.go
Resolves: #18865
[NO NEW TESTS NEEDED] -- it's a flake. Three successful runs on my no-retry PR, though, which is promising (this triggers every other run otherwise)
```release-note
None
```
> StopContainer(): ignore one more conmon warning

- cmd/podman/common/completion.go
- cmd/podman/containers/exec.go
- cmd/podman/containers/wait.go
- docs/source/markdown/podman-wait.1.md.in
- libpod/container_api.go
- pkg/api/handlers/compat/containers.go
- pkg/api/handlers/utils/containers.go
- pkg/api/server/register_containers.go
- pkg/bindings/containers/containers.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_wait_options.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/system/220-healthcheck.bats
Broken into 3 commits as it required some massaging in the backend.
```release-note
Support `--condition={healthy,unhealthy}` in `podman wait` allowing to wait to wait for successful health checks.
```
> podman wait: support healthy/unhealthy

- pkg/api/handlers/compat/containers_top.go
- pkg/api/server/handler_api.go
- test/apiv2/20-containers.at
Wait before sending status code 200 for the first top call and if that
fails return a proper error code.
This was leading to some confusion in [1] because podman just reported
200 but did not wirte anything back.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2215572
```release-note
The top API endpoint will now correctly report errors.
```
> pkg/api: top return error to client

- test/system/001-basic.bats
- test/system/010-images.bats
- test/system/011-image.bats
- test/system/120-load.bats
- test/system/255-auto-update.bats
- test/system/260-sdnotify.bats
- test/system/710-kube.bats
- test/system/helpers.bash
Add new _prefetch helper for fetching and caching images.
Use it in a few places, most importantly 120-load.bats
where our teardown() now runs 'rmi -af'.
Reason: in #17911 we discovered that podman save + load do
not actually preserve the image: annotations and other metadata
are lost. This means that a test which runs after 120-load.bats
is operating on a different $IMAGE than a test which runs before.
This is not a problem except in very obscure corner cases, like
one fixed in #18542, but it seems irresponsible to just handwave
that issue away
The _prefetch function uses skopeo for fetching and saving
images, because skopeo preserves digests and metadata.
[Side note for posterity: I tried amending basic_setup() to
always rmi -a + prefetch, instead of the current images -a +
rmi unwanted …
> system tests: add and use _prefetch

- .pre-commit-config.yaml
- Makefile
- pkg/systemd/parser/unitfile.go
- test/e2e/quadlet/remap-keep-id2.container
Fixes: https://github.com/containers/podman/issues/18979
```release-note
None
```
> Trim whitespace from unit files while parsing

- pkg/specgen/generate/oci_linux.go
- test/system/030-run.bats
we were silently ignoring --device-cgroup-rule in rootless mode.  Make sure an error is returned if the user tries to use it.
Closes: https://github.com/containers/podman/issues/18698
```release-note
Now --device-cgroup-rule causes an error when used in a user namespace instead of being silently ignored
```
> specgen: raise error with --device-cgroup-rule in a userns

- go.mod
- go.sum
- libpod/container_internal.go
- pkg/domain/infra/abi/images_list.go
- test/system/010-images.bats
- vendor/github.com/containers/common/libimage/image.go
- vendor/github.com/containers/common/libimage/layer_tree.go
- vendor/github.com/containers/common/libnetwork/slirp4netns/slirp4netns.go
- vendor/github.com/containers/common/pkg/hooks/exec/exec.go
- vendor/github.com/containers/common/pkg/hooks/exec/runtimeconfigfilter.go
- vendor/modules.txt
Handle more TOCTOUs operating on listed images.  Also pull in containers/common/pull/1520 which does the same on the internal layer tree.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2216700
```release-note
Make listing images more resilient towards concurrently running image removals.
```
> make image listing more resilient

- test/e2e/logs_test.go
Sometimes this tests flakes but in the CI log I see all expected lines printed but still for some reason the matcher fails. Right now it will truncate the array so it is not possible to verify what the matcher sees. Change this be removing the truncate limit for this specific test only.
see #18501
```release-note
None
```
> debug tail 800 lines flake

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/autoupdate.kube
```release-note
Kubernetes quadlets now supports auto update.
```
> Kube quadlets can support autoupdate as well as containers

- cmd/podman/machine/platform.go
- cmd/podman/machine/platform_darwin.go
- cmd/podman/machine/platform_windows.go
- pkg/machine/applehv/config.go
- pkg/machine/applehv/machine.go
- pkg/machine/config.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/config.go
- pkg/machine/wsl/machine.go
Ensures that for each hypervisor implementation, their `config.go` file deals with implementing the `VirtProvider` interface while the `machine.go` file is for implementing the `VM` interface.
Moves the `Virtualization` type into a common file and created wrappers for the individual hypervisors. Allows for shared functions that are exactly the same while providing the flexibility to create hypervisor-specific implementations of the functions.
```release-note
None
```
> Re-organize hypervisor implementations

- libpod/container_internal.go
- libpod/container_internal_test.go
Fixes #18907
This PR depends on https://github.com/containers/common/pull/1514 to be merged. Sorry first time contributor, I am not sure what's the correct workflow to make changes in upstream `common` repo. I assume I should create a new PR in common repo first, then wait for a new release from `common` then update the vendor file in this repo to make it depends on the changes I made in common?
```release-note
Hook executables invoked by podman run command now come with the correct working directory pointing to the container bundle directory
```
> Fixes #18907, pass in correct cwd value for hooks exe

- pkg/specgenutil/volumes.go
- test/system/060-mount.bats
There was a huge cut and paste of mount options which were not constent in parsing tmpfs, bind and volume mounts.  Consolidated into a single function to guarantee all parse the same.
Fixes: https://github.com/containers/podman/issues/18995
```release-note
Parse readonly=false on --mount options correctly.
```
> Fix readonly=false failure

- test/system/505-networking-pasta.bats
At various points the pasta bats tests need to know the name of the interface that pasta will use by default, and the host addresses it will use by default.  Currently we use the pre-existing helper functions ether_get_name and ipv[46]_get_addr_global to retreive that.
However, those just pick the first non-loopback interface or address, which may not be the one that pasta uses if there are multiple connected host interfaces.
Replace those helpers with local ones which examine the routing table to more closely match pasta's internal logic about which interface to select. This allows the tests to run successfully on a host with multiple interfaces.
Closes: https://github.com/containers/podman/issues/19007
```release-note
None
```
> pasta: Fix pasta tests to work on hosts with multiple interfaces

- cmd/podman/inspect/inspect.go
- test/system/700-play.bats
This is just useless noise and gets us closer to what Docker returns.
Inspired by: https://github.com/containers/podman/issues/19027
```release-note
None
```
> Remove 'inspecting object' from inspect errors

- cmd/podman/secrets/inspect.go
- docs/source/markdown/podman-secret-inspect.1.md
- docs/source/markdown/podman-secret-ls.1.md.in
- pkg/api/handlers/compat/secrets.go
- pkg/api/server/register_secrets.go
- pkg/bindings/secrets/secrets.go
- pkg/bindings/secrets/types.go
- pkg/bindings/secrets/types_inspect_options.go
- pkg/domain/entities/engine_container.go
- pkg/domain/entities/secrets.go
- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/tunnel/secrets.go
- test/e2e/secret_test.go
It is pretty complicated to display the secret on the host, but is not really secured. This patch makes it easier to examine the secret.
Partial fix for https://github.com/containers/podman/issues/18667
```release-note
podman secret inspect has a new options --showsecret which will output the actual secret.
```
> Display secret to user in inspect

- libpod/define/mount_freebsd.go
- libpod/define/mount_linux.go
- pkg/specgen/generate/storage.go
This adds define.BindOptions to declare the mount options for bind-like mounts (nullfs on FreeBSD). Note: this mirrors identical declarations in buildah and it may be preferable to use buildah's copies throughout podman.
```release-note
None
```
> pkg/specgen: add support for 'podman run --init' on FreeBSD

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/config/config_darwin.go
- vendor/github.com/containers/common/version/version.go
- vendor/github.com/containers/image/v5/internal/manifest/list.go
- vendor/github.com/containers/image/v5/internal/manifest/oci_index.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Bumping these two in preparation for Podman v4.6 and eventuall RHEL 8.9/9.3
```release-note
None
```
> Bump c/image to v5.26.0, c/common 0.54.0

- pkg/specgen/container_validate.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/generate/namespaces.go
- test/e2e/containers_conf_test.go
Make sure we use the config field to know if we should use pasta or slirp4netns as default.
While at it fix broken code which sets the default at two different places, also do not set in Validate() as this should not modify the specgen IMO, so set it directly before that.
```release-note
Podman now reads the default_rootless_network_cmd containers.conf option to get the default rootless network program.
```
> rootless: use default_rootless_network_cmd config

- test/system/505-networking-pasta.bats
https://github.com/containers/podman/pull/19021 fixed bugs with the pasta networking tests not working on hosts with multiple interfaces.  Alas, the patch left in some stale code that generates spurious error messages for the IPv6 case.  This is sort of harmless - later code overrides what's done here and the tests can pass anyway.  However if a test fails for some other reason it means we get a misleading irrelevant error message.
```release-note
None
```
> pasta: Remove some leftover code from pasta bats tests

- libpod/container_internal_common.go
- libpod/networking_freebsd.go
- libpod/networking_linux.go
- test/system/505-networking-pasta.bats
For pods with bridged and slirp4netns networking we create /etc/hosts entries to make it more convenient for the containers to address each other.  We omitted to do this for pasta networking, however.  Add the necessary code to do this.
Closes: https://github.com/containers/podman/issues/17922
```release-note
None
```
> pasta: Create /etc/hosts entries for pods using pasta networking

- Makefile
This flag is not supported on BSD-derived systems including FreeBSD and macos. We can get exactly the same symlink by passing the desired relative path as source argument to 'ln -sf'.
This fixes a build break on FreeBSD and if possible, I would like this to be merged to the v4.6 branch to simplify packaging v4.6.x releases in future.
```release-note
None
```
> Makefile: don't rely on the non-standard -r flag for ln

- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
When debugging #17403, the logs of sshd indicate that Podman tried to ssh into the machine too soon as the `core` user has not yet been fully set up:
> error: kex_exchange_identification: Connection closed by remote host
> fatal: Access denied for user core by PAM account configuration [preauth]
@dustymabe found that the we may have to wait for systemd-user sessions to be up.  Doing that reduces the flake rate on my M2 machine but does not entirely fix the issue.
Since I have seen multiple symptoms of flakiness, I think it does not hurt to add the systemd-user sessions to the dependencies of the ready service and continue investigating.
[NO NEW TESTS NEEDED] - once we have a fix out, I want to exercise frequent stop/start in the machine tests but they won't pass now.
```release-note …
```
> podman machine start: fix ready service

- cmd/podman/images/search.go
- test/e2e/search_test.go
Fix: https://github.com/containers/podman/issues/19033
```release-note
Fix ignore `--format` in `podman search --list-tags`
```
/cc @vrothberg
> fix(command): ignore `--format` in `podman search --list-tags`

- pkg/util/utils.go
GetKeepIDMapping never read the gid (as it intended) but reused the uid. Most likely a typo that never bothered anybody as uid and gid usually match.
I stumbled across this by accident and figured I can just fix it along the way, even though I was not hit by that bug :)
```release-note
None
```
> Use /proc/self/gid_map as intended, not uid_map

- docs/source/markdown/options/uidmap.container.md
The markdown-to-manpage sequence needs a long row of dashes, not a single dash. A single dash, as used in this one option, generates unreadable *roff.
Also, some tool somewhere doesn't like too-long columns. Shrtn thm.
Also, verify that there are no more three-or-fewer-dash columns:
$ ack '\|\s+-{1,3}\s' docs/source/markdown
Fixes: #19086
```release-note
Fixes corrupt uidmap tables in podman-create(1) and -run(1)
```
> [CI:DOCS] uidmap man pages: fix corrupt tables

- version/rawversion/version.go
Woke up in a cold sweat realizing I accidentally bumped to v4.6.0 instead of v4.6.0-rc1, glad I caught it before the I pushed the tag.... This is why I shouldn't rush a release in on a Friday.
```release-note
None
```
> Bump to v4.6.0-rc1

- libpod/oci_conmon_linux.go
libpod as it currently is is not compatible with newer tagged version of runc, as on that release branch the BlockIO fields are private. However, newer libpod need to use a newer version of runc (which happens to have the blockIO bits exported) to reduce the binary size of podman.
a compromise is libpod can use the constructors where applicable, so podman can build its own smaller binary (with a newer runc) as well as be compatible with the runc 1.1.z branch
```release-note
none
```
EDIT (@lsm5)
> libpod: use new libcontainer BlockIO constructors

- hack/podman-registry
- test/system/150-login.bats
- test/system/helpers.bash
- test/system/helpers.registry.bash
- test/system/setup_suite.bash
The podman-login tests have accumulated much cruft over the
years, because that's the only place where we run a local
registry, and the process was crufty: we actually start/stopped
the registry as the first & last tests of the file. Meaning,
you couldn't do 'hack/bats 150:just-one-test' because that
would skip the registry start. And just now, a completely
unrelated test has had to be shoved into the login file.
This PR revamps the whole thing, by adding a new registry helper
module that can be used anywhere. And, once the registry is
started, it just stays running until the end of tests. (This
requires BATS 1.7 or greater).
```release-note
None
```
> system tests: refactor registry code

- pkg/specgen/generate/oci_freebsd.go
When working on Linux emulation on FreeBSD, I assumed that SpecGenerator.ImageOS was always populated from the image's OS value but in fact, this value comes from the CLI --os flag if set, otherwise "". This broke running FreeBSD native containers unless --os=freebsd was also set. Fix the problem by falling back to runtime.GOOS if ImageOS is not set.
This is a strong incentive for me to complete a stalled project to enable podman system tests on FreeBSD.
```release-note
None
```
> pkg/specgen: properly identify image OS on FreeBSD

- cmd/podman/auto-update.go
- docs/source/markdown/options/tls-verify.md
- docs/source/markdown/podman-auto-update.1.md.in
- go.mod
- go.sum
- pkg/autoupdate/autoupdate.go
- pkg/domain/entities/auto-update.go
- test/system/255-auto-update.bats
- vendor/github.com/containers/common/libimage/image.go
- vendor/github.com/containers/common/pkg/secrets/secrets.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
The --authfile flag has been ignored.  Fix that and add a test to make
sure we won't regress another time.  Requires a new --tls-verify flag
to actually test the code.
Also bump c/common since common/pull/1538 is required to correctly check
for updates.  Note that I had to use the go-mod-edit-replace trick on
c/common as c/buildah would otherwise be moved back to 1.30.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2218315
```release-note
Fix a bug podman-auto-update to correctly use authentication files when contacting container registries.
```
> auto update: fix usage of --authfile

- .cirrus.yml
Many/most env. vars set by the `stdenvars` alias do not apply to the `osx_alt_build` task.  In case anybody debugging a job might be confused by them, use more meaningful values.
```release-note
None
```
> [CI:BUILD] Minor: Don't confuse osx-debugging

- test/e2e/toolbox_test.go
- test/utils/utils.go
1. toolbox UID/GID allocation: pick numbers < 1500. Otherwise
we run the risk of colliding with the Cirrus rootless user.
[sample failure](https://api.cirrus-ci.com/v1/artifact/task/4682721818050560/html/int-podman-fedora-38-rootless-host-boltdb.log.html#t--Toolbox-specific-testing-podman-create-userns-keep-id-entrypoint-modifying-existing-user-with-usermod-add-to-new-group--change-home-shell-uid--1)
2. WaitContainerReady(): check the results of the last "podman logs"
before timing out. Otherwise, the user will see "READY" followed
immediately by "Container is not ready".
(global bug, not just toolbox, but that's where I discovered it).
[sample failure](https://api.cirrus-ci.com/v1/artifact/task/6550789993267200/html/int-podman-debian-12-rootless-host-sqlite.log.html#t--Toolbox-specific-te …
> e2e: fix two toolbox flakes

- libpod/oci_conmon_linux.go
> [v4.5] libpod: use new libcontainer BlockIO constructors

- rpm/update-spec-provides.sh
One of the reasons the last propose-downstream task failed for Fedora was the `golist` tool wasn't available in the Packit environment.
This commit adds golist to the environment by downloading and extracting the golist rpm.
This dependency could've been added in packit's upstream config but there were a few blockers, so it's easiest to add them in our action script.
Ref: https://github.com/containers/podman/issues/19094
```release-note
None
```
> [CI:BUILD] Packit: fix pre-sync action for downstream tasks

- .cirrus.yml
- Makefile
- contrib/cirrus/CIModes.md
- contrib/cirrus/runner.sh
- docs/remote-docs.sh
This enables 'make podman-release' for FreeBSD and changes the Cirrus CI config to run that build in a FreeBSD VM so that the build can use CGO.
I attempted to add FreeBSD binaries to the artifacts task but this failed, apparently because the extra 50Mb of space exceeded a 1Gb limit in Cirrus.
```release-note
None
```
> Cirrus: change FreeBSD CI build to run in a VM

- libpod/container_internal_common.go
- libpod/container_internal_test.go
An empty range caused a panic as parseOptionIDs tried to check further down for an @ at index 0 without taking into account that the splitted out string could be empty.
```release-note
None
```
> bugfix: do not try to parse empty ranges

- docs/source/markdown/options/uidmap.container.md
[backport of #19088. No conflicts.]
The markdown-to-manpage sequence needs a long row of dashes, not a single dash. A single dash, as used in this one option, generates unreadable *roff.
Also, some tool somewhere doesn't like too-long columns. Shrtn thm.
Also, verify that there are no more three-or-fewer-dash columns:
$ ack '\|\s+-{1,3}\s' docs/source/markdown
Reference: #19086
Signed-off-by: Ed Santiago <santiago@redhat.com
```release-note
Fixes corrupt uidmap tables in podman-create(1) and -run(1)
```
> [v4.6] fix corrupt man tables 46

- cmd/podman/machine/init.go
- cmd/podman/machine/list.go
- cmd/podman/machine/set.go
- docs/source/markdown/podman-machine-init.1.md.in
- pkg/machine/e2e/config_init_test.go
Previously podman was using "MB" and "GB" (binary) for input but "MB" and "GB" (decimal) for output, which was causing confusion.
```release-note
None
```
Looks better (even numbers) in `podman machine list` now:
```
NAME                    VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        5 minutes ago  5 minutes ago  1           2GiB        100GiB
```
----
For instance in Podman Desktop you were getting some 5-7% "extra" size, compared to what you ordered.
* https://github.com/containers/podman-desktop/issues/3062#issuecomment-1613589034
> Use bytes size consistently instead of human size

- docs/source/markdown/podman-system-service.1.md
```release-note
None
```
(I didn't document how it works on macOS and Windows)
> [CI:DOCS] podman-system-service.1.md: document systemd usage

- docs/source/markdown/podman-systemd.unit.5.md
This change matches the list above in the same document, in the section `Podman user unit search path`. I also confirmed that this matches [the code](https://github.com/containers/podman/blob/60a5a59/cmd/quadlet/main.go#L119).
```release-note
None
```
> [CI:DOCS] Fixes typo in the path where quadlet looks for files

- docs/source/markdown/options/uidmap.container.md
The markdown-to-manpage sequence interprets
`_from_uid_` and `*from_uid*` differently.
Use the latter syntax to get the expected result.
Fixes: https://github.com/containers/podman/issues/19171
```release-note
None
```
> [CI:DOCS] uidmap man pages: fix corrupt italics

- pkg/api/handlers/compat/version.go
- test/e2e/common_test.go
- test/e2e/libpod_suite_remote_test.go
Do not use podman info/version as they are expensive and clutter the log
for no reason. Just checking if we can connect to the socket should be
good enough and much faster.
Also change the interval, why wait 2s for a retry lets take 100ms steps
instead.
Fixes #19010
api: fix slow version endpoint
This endpoint queried the same package versions twice causing it to be
slower than info. Because it already called info we can just reuse the
package versions from there.
```release-note
None
```
> test/e2e: wait for socket

- cmd/podman/syslog_common.go
Podman will always pass down --syslog to conmon since 13c2aca21. However there systems without syslog running, likely in container setups. As reported in this was already a problem before when debug level is used. Then conmon will pass down --syslog back to the podman container cleanup command causing it to fail without doing anything. Given that I think it is better to just ignore the error and log it on debug level, we need to make sure cleanup works consistently.
Fixes #19075
```release-note
podman --syslog will no longer return a fatal error when no syslog server is found and ignores the error. 
```
> make --syslog errors non fatal

- cmd/podman/manifest/inspect.go
- docs/source/markdown/options/authfile.md
- docs/source/markdown/podman-manifest-inspect.1.md.in
- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_inspect_options.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/login_logout_test.go
- test/system/012-manifest.bats
- test/system/150-login.bats
Previous tests have worked by pure chance since the client and server ran on the same host; the server picked up the credentials created by the client login.
Extend the gating tests and add a new integration test which is further capable of exercising the remote code.
Note that fixing authentication support requires adding a new `--authfile` CLi flag to `manifest inspect`.  This will at least allow for passing an authfile to be bindings.  Username and password are not yet supported.
```release-note
Support authentication in `podman manifest inspect`.
```
> manifest inspect: support authentication

- cmd/podman/secrets/create.go
- docs/source/markdown/podman-secret-create.1.md
- pkg/api/handlers/libpod/secrets.go
- pkg/bindings/secrets/types.go
- pkg/bindings/secrets/types_create_options.go
- pkg/domain/entities/secrets.go
- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/tunnel/secrets.go
- test/e2e/secret_test.go
Users may want to update the secret used within containers, without destroying the secret and recreating it.
Partial fix for https://github.com/containers/podman/issues/18667
```release-note
Podman secret create now has a --replace option, which allows you to modify secrets without replacing containers.
```
> Add --replace flag to podman secret create

- libpod/container_internal.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
This file has not been present in BSD systems since 2.9.1 BSD and as far as I remember /proc/mounts has never existed on BSD systems.
```release-note
None
```
> libpod: don't make a broken symlink for /etc/mtab on FreeBSD

- cmd/podman/kube/generate.go
- cmd/podman/kube/play.go
- docs/source/markdown/podman-kube-generate.1.md
- docs/source/markdown/podman-kube-play.1.md.in
- libpod/kube.go
- pkg/api/handlers/libpod/generate.go
- pkg/api/handlers/libpod/kube.go
- pkg/api/server/register_kube.go
- pkg/bindings/generate/types.go
- pkg/bindings/generate/types_kube_options.go
- pkg/bindings/kube/types.go
- pkg/bindings/kube/types_play_options.go
- pkg/domain/entities/generate.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/generate.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/tunnel/kube.go
- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
- test/system/700-play.bats
Adds a `--no-trunc` flag to `podman kube generate` preventing the
annotations from being trimmed at 63 characters. However, due to
the fact the annotations will not be trimmed, any annotation that is
longer than 63 characters means this YAML will no longer be Kubernetes
compatible. However, these YAML files can still be used with `podman
kube play` due to the addition of the new flag below.
Adds a `--no-trunc` flag to `podman kube play` supporting YAML files with
annotations that were not truncated to the Kubernetes maximum length of
63 characters.
```release-note
Adds a `--no-trunc` flag to `podman kube generate` that does not truncate > 63 char annotations. Adds a `--no-trunc` flag to `podman kube play` that suppors YAML files with annotations that are longer than 63 characters. …
```
> Add `--no-trunc` flag to maintain original annotation length

- test/e2e/play_kube_test.go
When fetching the user name, you need to use `User.Username`
instead of `User.Name` , as with other tests.
```release-note
None
```
> e2e: Fetch the correct user name

- test/system/505-networking-pasta.bats
...from the test name. Eliminates scary duplication.
Followup to #19053: instead of cross-checking pasta test args
against test name, eliminate the args entirely. Determine
them all from the @test name itself.
Example:
```
"TCP translated port range forwarding, IPv4, loopback"
|  |          |    |     |           |     +-- iftype=loopback
|  |          |    |     |           +-------- ip_ver=4
|  |          |    |     +-------------------- bytes=1
|  |          |    +-------------------------- range=3
|  |          +------------------------------- (ignored)
|  +------------------------------------------ delta=1
+--------------------------------------------- proto=tcp
```
```release-note
None
```
> pasta tests: automatically determine test parameters

- libpod/pod_internal_linux.go
Closes #19175
This PR fix the bug 'cgroup is not set: internal libpod error after os reboot' on system without systemd.
None
> Fix: cgroup is not set: internal libpod error after os reboot

- cmd/podman/system/service_abi.go
Disable leaking the LISTEN_* variables into containers which are
observed to be passed by systemd even without being socket activated as
described in https://access.redhat.com/solutions/6512011.
[NO NEW TESTS NEEDED] - Ultimately, the solution 6512011 should be updated.
Fixes: bugzilla.redhat.com/show_bug.cgi?id=2180483
@Luap99 PTAL.  test/e2e/systemd_activate_test.go does not set LISTEN_FDS, so there's no test I can plug into.
```release-note
Fix an issue in `system service` when listing on TCP and LISTEN_FDS are set.
```
> system service: unset listen fds on tcp

- Makefile
1.18 is EOL and we should not have to set this since the current versions should generate compatible go.sum files anyway.
This is an attempt to fix broken renovate PRs which create a different go.sum and thus do not pass CI checks.
```release-note
None
```
> go mod: no longer use 1.18

- cmd/quadlet/main.go
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/name.network
- test/e2e/quadlet/name.volume
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
This commit extends `Volume` and `Network` unit definitions with two additional parameters, `VolumeName` and `NetworkName`, which will, respectively, set a user-defined name for the corresponding volume and network. This is similar to how the `ContainerName` directive currently works, and should allow for smoother transitions to Quadlet-managed resources.
Closes: #19003
```release-note
Allow for setting user-defined names for Quadlet `Volume` and `Network` units via the `VolumeName` and `NetworkName` directives, respectively.
```
> Allow setting volume and network names in Quadlet

- libpod/oci_conmon_linux.go
needed for cri-o branch 1.26, no release needed
```release-note
none
```
> [4.3] libpod: use new libcontainer blockIO constructors

- libpod/oci_conmon_linux.go
needed for cri-o branch 1.26 (which no longer builds with 4.3 because we use a newer c/storage and c/image :cry: ), no release needed
```release-note
none
```
> [4.4] libpod: use new libcontainer blockIO constructors

- pkg/api/handlers/libpod/kube.go
- pkg/api/server/register_kube.go
- test/e2e/play_kube_test.go
Fix `podman play kube --userns` to work in remote environment.
Related: #17392
```release-note
The remote Podman client’s `podman play kube` command now work --userns option.
```
> remote: fix podman-remote play kube --userns

- pkg/api/handlers/libpod/pods.go
- test/apiv2/40-pods.at
- test/system/200-pod.bats
When I reworked pod removal to provide more detailed errors (including per-container errors, not just a single multierror with all errors squashed), I made it part of the struct returned by the REST API and assumed that would be enough to get errors through to clients. Unfortunately, in case of an overarching error removing the pod (as any error with any container would cause), we don't send the response struct that would include the container errors - we just send a standardized REST error. We could work around this with custom, potentially backwards incompatible error handling for the REST pod delete endpoint, or we could just do what was done before, and package up all the errors in a multierror to send to the other side. Of those options, the multierror seems far simpler.
Fixes #19159 …
> Fix container errors not being sent via pod removal API

- cmd/podman/login.go
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-secret-create.1.md
- test/system/150-login.bats
```release-note
Podman login can now read the secret for a registry from its secret database created with podman secret create.
```
Fixes: https://github.com/containers/podman/issues/18667
> Add secret support to podman login

- pkg/specgen/generate/oci_freebsd.go
When using 'podman run --rootfs ...', the image passed to SpecGenToOCI may be nil - in this case, fall back to "freebsd" for the container OS.
```release-note
None
```
> pkg/specgen: fix support for --rootfs on FreeBSD

- rpm/update-spec-provides.sh
The downstream `pre-sync` task action script needs GOPATH to be specified for the golist tool mentioned in the script to work.
```release-note
None
```
Doesn't affect upstream. Only needed for downstream Fedora tasks.
Would be good to have this in before v4.6.0
> [CI:BUILD] Packit: downstream task action fix

- pkg/machine/qemu/machine.go
During the exponential backoff waiting for the machine to be fully up and running, also make sure that SSH is ready.  The systemd dependencies of the ready.service include the sshd.service among others but that is not enough.
Other CoreOS users reported the same issue on IRC, so I feel fairly confident to use the pragmatic approach of making sure SSH works on the client side.  #17403 is quite old and there are other pressing machine issues that need attention.
Fixes: #17403
```release-note
Fix a bug of flaky podman-machine-start using QEMU.
```
> machine start: qemu: wait for SSH readiness

- docs/source/markdown/podman-network-create.1.md
When using --internal for macvlan/ipvlan networks we simply do not add a default gateway/route. Make this clear in the docs.
Fixes #18914
```release-note
None
```
> [CI:DOCS] network create: document --internal better

- pkg/api/handlers/libpod/pods.go
- test/apiv2/40-pods.at
> Add missing return after utils.InternalServerError()

- rpm/update-spec-provides.sh
The downstream `pre-sync` task action script needs GOPATH to be specified for the golist tool mentioned in the script to work.
(cherry picked from commit 12dc546fc1ba78a05bcc1695c886dbd11e4a76bf)
```release-note
None
```
Ok to miss v4.6.0-rc2. Would like to get this in by v4.6.0 release.
cherrypick command failed on https://github.com/containers/podman/pull/19216 so I'm doing it manually.
> [v4.6 backport] [CI:BUILD] Packit: downstream task action fix

- docs/source/markdown/podman-container-prune.1.md
Fixes an error in the `podman container prune` docs that provides an example of how to use the `--filter until=` flag/filter in an incorrect way.
Fixes: #19119
```release-note
Fixes an incorrect example in the `podman container prune` documentation for the `--filter until=` flag/filter
```
> [CI:DOCS] Fix `podman container prune` docs for `--filter`

- docs/source/markdown/options/network.md
- docs/source/markdown/podman-build.1.md.in
docs: podman run --network mention comma separted names
This syntax was used prior to 4.0 and is still supported for backwards
compatibility.
Fixes #19089
docs: podman-build --network add slirp and pasta
Support was added in buildah some weeks ago. [1]
[1] https://github.com/containers/buildah/pull/4877
```release-note
None
```
> [CI:DOCS] update --network docs

- libpod/container_path_resolution.go
This fixes the "podman cp file from host to container mount" system test on FreeBSD where binding host paths into containers uses the nullfs mount type.
```release-note
None
```
> libpod: use define.TypeBind when resolving container paths

- docs/source/markdown/options/userns.container.md
Better document which value `podman run --userns` has if no 
value is specified. Also improve documentation of "host" being an alias
for "".
Fixes #15764
None
> [CI:DOCS] Better document the default value of --userns

- go.mod
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/kube_test.go
- pkg/specgen/generate/kube/play_test.go
* Add support for using port names in Kubernetes probes
* Support TCPSocket probes without specifying any host names
Closes #18645
```release-note
From now on, you can also use containerPort names inside Kubernetes liveness probes to refer to the desired ports, which was not previously supported by podman.
```
> Better support for Kubernetes health probes

- .cirrus.yml
- Makefile
- contrib/cirrus/runner.sh
- docs/source/markdown/podman-pod-top.1.md.in
- docs/source/markdown/podman-top.1.md.in
- libpod/container_top_linux.c
- libpod/container_top_linux.go
- libpod/container_top_unsupported.go
- libpod/define/config.go
- pkg/api/handlers/libpod/pods.go
- pkg/api/server/register_containers.go
- pkg/api/server/register_pods.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_execstartandattach_options.go
- pkg/bindings/test/containers_test.go
- test/apiv2/20-containers.at
- test/e2e/top_test.go
This ended up more complicated then expected. Lets start first with the
problem to show why I am doing this:
Currently we simply execute ps(1) in the container. This has some
drawbacks. First, obviously you need to have ps(1) in the container
image. That is no always the case especially in small images. Second,
even if you do it will often be only busybox's ps which supports far
less options.
Now we also have psgo which is used by default but that only supports a
small subset of ps(1) options. Implementing all options there is way to
much work.
Docker on the other hand executes ps(1) directly on the host and tries
to filter pids with `-q` an option which is not supported by busybox's
ps and conflicts with other ps(1) arguments. That means they fall back
to full ps(1) on the host and then …
> top: do not depend on ps(1) in container 

- test/e2e/play_kube_test.go
- test/e2e/pod_create_test.go
- test/e2e/run_memory_test.go
- test/e2e/run_userns_test.go
- test/system/030-run.bats
- test/system/070-build.bats
- test/system/120-load.bats
- test/system/170-run-userns.bats
- test/system/250-systemd.bats
- test/system/252-quadlet.bats
- test/system/400-unprivileged-access.bats
- test/system/410-selinux.bats
- test/system/500-networking.bats
- test/system/520-checkpoint.bats
- test/system/helpers.bash
To silence my find-obsolete-skips script, remove the '#'
from the following issues in skip messages:
#11784 #15013 #15025 #17433 #17436 #17456
Also update the messages to reflect the fact that the issues
will never be fixed.
Also remove ubuntu skips: we no longer test ubuntu.
Also remove one buildah skip that is no longer applicable:
Fixes: #17520
```release-note
None
```
> Tests: remove/update obsolete skips

- libpod/container_inspect.go
- libpod/container_internal_common.go
- libpod/container_internal_linux.go
- libpod/container_path_resolution.go
- libpod/define/mount_linux.go
- libpod/networking_linux.go
- libpod/runtime_volume_common.go
- libpod/volume_internal_common.go
- pkg/api/handlers/compat/containers_create.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/container_validate.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/oci_freebsd.go
- pkg/specgen/generate/oci_linux.go
- pkg/specgen/generate/storage.go
- pkg/specgenutil/specgen.go
- pkg/specgenutil/volumes.go
- pkg/util/mountOpts.go
- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
- test/e2e/run_test.go
- test/e2e/toolbox_test.go
- test/e2e/volume_inspect_test.go
Inspired by https://github.com/containers/podman/pull/19238
```release-note
None
```
> Use constants for mount types

- RELEASE_NOTES.md
`package` and `package-install` targets have been renamed to `rpm` and `rpm-install` respectively.
Ref: https://github.com/containers/podman/pull/19226
```release-note
None
```
> [v4.6] [CI:DOCS] Update RELEASE_NOTES.md with Makefile change

- pkg/machine/applehv/claim.go
- pkg/machine/applehv/config.go
- pkg/machine/applehv/ignition.go
- pkg/machine/applehv/machine.go
- pkg/machine/applehv/rest.go
- pkg/machine/applehv/rest_config.go
- pkg/machine/applehv/vfkit.go
The apple hypervisor code works on Intel Macs with very recent operating system versions.
```release-note
none
```
> Enabled amd64 arch for podman applehv provider

- cmd/podman/kube/generate.go
- docs/source/markdown/podman-kube-generate.1.md
- libpod/kube.go
- pkg/api/handlers/libpod/generate.go
- pkg/api/server/register_kube.go
- pkg/bindings/generate/types.go
- pkg/bindings/generate/types_kube_options.go
- pkg/domain/entities/generate.go
- pkg/domain/infra/abi/generate.go
- pkg/domain/infra/tunnel/kube.go
- test/e2e/generate_kube_test.go
Adds a `--podman-only` flag to `podman generate kube` to allow for podman-only reserved annotations to be included in the generated YAML file. These annotations cannot be used by Kubernetes.
Associated with: #19102
```release-note
Adds `--podman-only` flag to `podman generate kube` to allow podman-only reserved annotations to be used in the generated YAML file. These annotations cannot be used by Kubernetes
```
> Add `--podman-only` flag to `podman generate kube`

- libpod/container_internal_common.go
Paul found this in https://github.com/containers/podman/pull/19241
```release-note
```
> Should be checking tmpfs versus type not source

- test/system/030-run.bats
- test/system/075-exec.bats
- test/system/helpers.bash
Emergency gating-test fixes for RHEL8
- the "podman {run,exec} /etc" test: runc now spits out "is a directory" instead of "permission denied". And, on exec, exits 255 instead of 126. Deal with it.
- workaround for https://github.com/containers/skopeo/issues/823 (skopeo XDG bug): always make sure XDG is defined for skopeo
Clean backport of #19259 
```release-note
None
```
> [v4.6] emergency gating test fix v4.6

- libpod/container_inspect.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/play_kube_test.go
- test/e2e/run_networking_test.go
Adds any required "wiring" to ensure the reserved annotations are supported by `podman kube play`.
Addtionally fixes a bug where, when inspected, containers created using the `--publish-all` flag had a field `.HostConfig.PublishAllPorts` whose value was only evaluated as `false`.
Associated with: #19102
Adding reserved annotations with `kube generate`:  #19211
```release-note
Adds support to `podman kube play` for the use of reserved annotations in the generated YAML. Fixes a bug where `.HostConfig.PublishAllPorts` always evaluates to `false` when inspecting a container created with `--publish-all`
```
> Add missing reserved annotation support to play 

- docs/source/markdown/podman-volume-ls.1.md.in
- pkg/api/handlers/compat/volumes.go
- pkg/api/handlers/libpod/volumes.go
- pkg/domain/filters/volumes.go
- pkg/domain/infra/abi/volumes.go
- test/e2e/volume_ls_test.go
Fixes a bug where `podman volume ls` with multiple `label` filters would return volumes that matched *any* of the filters, not *all* of them.
Fixes: #19219
```release-note
Fixes a bug where `podman volume ls` with multiple `label` filters would return volumes that matched any of the filters, not all of them
```
> Fix multiple filter options logic for `podman volume ls `

- cmd/podman/containers/exec.go
- cmd/podman/main.go
- docs/source/markdown/podmansh.1.md
- test/e2e/exec_test.go
- test/system/075-exec.bats
```release-note
Podmansh: Display a more useful error for timeouts
Podmansh: Increase timeout to 30s
```
> Podmansh: Useful timeout error, increase timeout to 30s

- docs/source/markdown/podman-network-create.1.md
Markdown was interpreting the angle brackets as HTML tags, causing them to display wrongly.
```release-note
None
```
> [CI:DOCS] Fix markdown in docs for podman-network-create

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/workingdir-service.kube
- test/e2e/quadlet/workingdir-unit.kube
- test/e2e/quadlet/workingdir-yaml-abs.kube
- test/e2e/quadlet/workingdir-yaml-rel.kube
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
Add key for Quadlet to set WorkingDirectory to the directory of the YAML or Unit file Add Doc
Add E2E tests
Add System test
Yes
```release-note
Quadlet - Allow the user to instruct Quadlet to set the service working directory relative to the YAML or Unit files
```
Resolves #17177
> Quadlet - Allow setting Service WorkingDirectory for Kube units

- cmd/podman/common/completion.go
- cmd/podman/inspect/inspect.go
- test/system/600-completion.bats
- test/system/610-format.bats
- test/system/README.md
Add tab-completion feature for podman inspect -f
The command:
```podman inspect <ContainerID> -f "{{."```
was not giving any output in console for bash-completion but the same was working fine for the command:
```podman container inspect <ContainerID> -f "{{."```
So added a flow to handle the former command and additionally handled all types of entities namely container, image, volume, pod and network.
This would ESSENTIALLY make the sub-commands such as follows OBSOLETE:
podman container inspect
podman image inspect
podman volume inspect
podman pod inspect
podman network inspect
```release-note
The following command is now enabled with tab-completion:
podman inspect {CONTAINER | IMAGE | VOLUME | POD | NETWORK} -f "{{." <tab>
where CONTAINER can be ContainerID or ContainerName and same …
```
> Podman inspect completion

- pkg/machine/pull.go
```release-note
Show progress bar when decompressing podman machine image
```
Closes #19240
> Add progress bar for decompress image

- docs/source/markdown/podman-volume-ls.1.md.in
- docs/source/markdown/podman-volume-prune.1.md
- pkg/api/handlers/compat/volumes.go
- pkg/api/handlers/libpod/volumes.go
- pkg/domain/filters/volumes.go
- pkg/domain/infra/abi/volumes.go
- test/e2e/volume_ls_test.go
- test/e2e/volume_prune_test.go
Adds support for `since` as a valid filter option for `podman volume ls` and `podman volume prune`.
Implements: #19228
Initially suggested from: #19119
```release-note
Adds `since` as valid filter option for `podman volume ls` and `podman volume prune`
```
> Add `since` as valid filter option for `volume` subcommands

- Makefile
Every so often we hear reports of a corrupt man page table,
where columns are misaligned in nonsensical ways. The
traditional symptom looks like:
|----------------|--------------|
| option name    |              |
|----------------|--------------|
|                | description  |
|----------------|--------------|
Cause: one of the tools in the man page generation chain,
maybe 'man' itself, has an undocumented length limit on
table cells, _and_ an undocumented page width as well.
If you exceed these undocumented limits, you get corrupt
man pages. Silently.
This adds a horrible test for those. And I mean horrible:
- unreadable
- unmaintainable
- unreliable (heuristic, no guarantees)
- slows down 'make docs' (less than a second, but still)
I've tested by adding long '| sdf sdf | dsf |' rows …
> [CI:DOCS] Man pages: check for corrupt tables

- test/system/252-quadlet.bats
Some quadlet tests are failing on RHEL8: test code was using journalctl to check output from containers. This fails on RHEL8, where default log driver is k8s-file.
Solution: use 'podman logs' instead. To do so, we need to keep the containers alive (otherwise, quadlet seems to delete them on exit). Do so by running 'top -b' (batch); the currently-used 'top' was failing because not-a-tty.
Cherry-pick of #19276, one minor conflict resolved.
```release-note
None
```
> [v4.6] systests: quadlet: fixes for RHEL8

- cmd/podman/system/service_abi.go
- docs/source/markdown/podman-system-service.1.md
- test/system/271-tcp-cors-server.bats
`podman system service` + TCP is not a configuration we should be recommending. There was already language about this in the manpages, but it was not sufficient in explaining how bad of an idea this is. Expand the manpage warnings, add a dedicated heading so people notice, and add a warning every time the service starts with a TCP URL that directs people to the manpage to see that explanation.
```release-note
Add a warning when `podman system service` binds to a TCP socket. This is not a secure configuration and the Podman team recommends against using it.
```
> Ensure that we appropriately warn that TCP is insecure

- .github/ISSUE_TEMPLATE/bug_report.yaml
The relative link seems flakey: depending where you're creating the issue this may not take you to the right place.
For example, from https://github.com/containers/podman/issues/new?assignees=&labels=kind%2Fbug%2Ctriage-needed&projects=&template=bug_report.yaml it takes you to https://github.com/containers/podman/README.md, which does not exist.
To fix this, I've replaced it with an absolute link to the README for people to find the version easily. Other places in the same issue template use absolute paths to places in the repo e.g. the wiki, so I think this is acceptable.
```release-note
None
```
> [CI:DOCS] Fix bug report issue template README link

- pkg/trust/policy.go
When running the `trust` command, only the global policy.json file was being taken into account.
Fixes #19073
```release-note
'trust' command can now use the local policy.json file
```
> Fix `trust` not using local policy file

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
- docs/source/markdown/podman-systemd.unit.5.md
- test/e2e/common_test.go
- test/e2e/quadlet/test_subdir/mysleep.container
- test/e2e/quadlet/test_subdir/sub_one/mysleep_1.container
- test/e2e/quadlet/test_subdir/sub_two/mysleep_2.container
- test/e2e/quadlet_test.go
Solves #18032 
```release-note
Recursively scans directories for unit files
----------------------
debian@debian:~/Projects/podman$ bin/quadlet -dryrun
quadlet-generator[2453]: No files to parse from [/etc/containers/systemd /usr/share/containers/systemd]
----------------------
debian@debian:~/Projects/podman$ bin/quadlet -dryrun -user
quadlet-generator[2475]: Loading source unit file /home/debian/.config/containers/systemd/test_subdir/sample.container
quadlet-generator[2475]: Loading source unit file /home/debian/.config/containers/systemd/test_subdir/sub_one/sample_two.container
quadlet-generator[2475]: Loading source unit file /home/debian/.config/containers/systemd/test_subdir/sub_two/sample_one.container
---sample.service---
[Unit]
Description=The sleep container …
```
> recursive call in user directories for unit files

- docs/source/markdown/podman-systemd.unit.5.md
> [CI:DOCS] Add note about QUADLET_UNIT_DIRS to simplify quadlet debug

- docs/kubernetes_support.md
Update the kubernetes_support table to correctly show that "volumes" is supported in the pod spec.
The kube play docs already specifies which types of volumes are curretnly supported, so no further documentation is needed on that.
Fixes https://github.com/containers/podman/issues/19318
```release-note
Update kubernetes support table to correctly show volumes support.
```
> [CI:DOCS] Update kube play volume support

- libpod/container_top_freebsd.go
use the 'pf -ef' compatible default when the `descriptor` argument of `Top()` is `[]string{""}` or `[]string{}`
the call to `Top()` in
[the REST API handler](https://github.com/containers/podman/blob/87f5a15d62506609a6079ff835651409036879d8/pkg/api/handlers/compat/containers_top.go#L62C3-L62C3)
does pass `[]string{""}` as `descriptors` whenever `ps_args` is empty (the default value for libpod request) because of golang `strings.Split()` semantics.
* output of `podman --url=$MachineWithFreeBSDocijailRuntime container top $MyContainer` will have the same fields as `podman container top $MyContainer`
* podman-tui will no longer panic in containers/podman-tui/pdcs/containers.Top when used
with a FreeBSD ocijail Runtime (the number of descriptor fields is hardcoded there).
```release-note
None …
```
> libpod: fix FreeBSD 'podman-remote top' default behaviour

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/shmsize.container
- test/e2e/quadlet_test.go
I am working on running android auto in a quadlet.
[Container]
AddDevice=/dev/dri/renderD128
AddDevice=/dev/kvm
DropCapability=all
Environment=PULSE_SERVER=$XDG_RUNTIME_DIR/pulse/native Environment=WAYLAND_DISPLAY=wayland-0
Environment=XDG_RUNTIME_DIR
Image=quay.io/slopezpa/qemu-aaos
ContainerName=Android
PodmanArgs=--shm-size=5g
SecurityLabelDisable=true
Volume=$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR
And I need to be able to set the --shm-size option.
```release-note
Podman quadlet now supports ShmSize option in unit files.
```
> Add support for ShmSize to quadlet

- rpm/podman.spec
Misc fixes to the spec file: add a missing ` and remove unnecessarily added files
```release-note
None
```
> podman rpm Spec fixes

- cmd/podman/compose.go
- docs/source/markdown/.gitignore
- docs/source/markdown/podman-compose.1.md.in
- docs/source/markdown/podman.1.md
- go.mod
- go.sum
- hack/man-page-checker
- hack/xref-helpmsgs-manpages
- pkg/rootless/rootless_linux.c
- test/compose/test-compose
- test/system/015-help.bats
- test/system/600-completion.bats
- test/system/610-format.bats
- test/system/850-compose.bats
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_local.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/github.com/containers/common/pkg/config/default_darwin.go
- vendor/github.com/containers/common/pkg/config/default_freebsd.go
- vendor/github.com/containers/common/pkg/config/default_linux.go
- vendor/github.com/containers/common/pkg/config/default_windows.go
- vendor/github.com/containers/common/pkg/util/util.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/modules.txt
**podman compose** is a thin wrapper around an external compose provider such as docker-compose or podman-compose.  This means that `podman compose` is executing another tool that implements the compose functionality but sets up the environment in a way to let the compose provider communicate transparently with the local Podman socket.  The specified options as well the command and argument are passed directly to the compose provider.
The default compose providers are `docker-compose` and `podman-compose`. If installed, `docker-compose` takes precedence since it is the original implementation of the Compose specification and is widely used on the supported platforms (i.e., Linux, Mac OS, Windows).
If you want to change the default behavior or have a custom installation path for your …
> add a podman-compose command

- libpod/info.go
Some distributions add extra quotes, even to fields like ID that doesn't really need them. Make sure to remove them too.
Closes #19340
```release-note
Extra quotes around the distribution name removed from podman info output
```
Tested with ubuntu and fedora coreos, that does not have quotes.
```
NAME="Fedora Linux"
VERSION="38.20230709.2.0 (CoreOS)"
ID=fedora
VERSION_ID=38
```
```yaml
distribution:
distribution: fedora
variant: coreos
version: "38"
```
And verified against centos stream, which does have extra quotes.
```
NAME="CentOS Stream"
VERSION="9"
ID="centos"
ID_LIKE="rhel fedora"
```
```yaml
distribution:
distribution: centos
version: "9"
```
> Remove any quotes around distribution id

- pkg/specgen/generate/config_linux.go
- pkg/specgen/generate/config_linux_test.go
This fixes a server-side crash for command lines like:
```
```
Fixes #19335.
```release-note
Fix a crash validating --device argument for create and run (#19335)
```
> pkg/specgen: Don't crash for device spec with empty destination path

- libpod/healthcheck_unsupported.go
Caller will just log the error which is confusing for the user. This matches the linux non-systemd behaviour.
It would be nice to have timer support for healthcheck on FreeBSD but the only pre-installed timer option is at which probably isn't a good fit here.
```release-note
None
```
> libpod: don't generate errors for createTimer etc.

- cmd/podman/common/completion.go
- docs/source/markdown/options/sdnotify.md
- libpod/container_api.go
- libpod/container_internal.go
- libpod/define/sdnotify.go
- libpod/oci_conmon_attach_common.go
- pkg/specgen/container_validate.go
- pkg/specgen/generate/container_create.go
- test/system/260-sdnotify.bats
Add a new "healthy" sdnotify policy that instructs Podman to send the READY message once the container has turned healthy.
Fixes: #6160
```release-note
Add a new --sdnotify=healthy policy where Podman sends the READY message once the container turns healthy.
```
For auto: @ygalblum @rhatdan PTAL
> add "healthy" sdnotify policy

- cmd/podman/auto-update.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- cmd/podman/containers/runlabel.go
- cmd/podman/images/build.go
- cmd/podman/images/pull.go
- cmd/podman/images/push.go
- cmd/podman/images/search.go
- cmd/podman/images/sign.go
- cmd/podman/kube/play.go
- cmd/podman/manifest/inspect.go
- test/e2e/create_test.go
- test/e2e/login_logout_test.go
- test/system/030-run.bats
- test/system/700-play.bats
Fixes: https://github.com/containers/podman/issues/18938
```release-note
If user specifies the authfile path in podman run or create, the command fails if path does not exists.
```
> Verify authfile exists if user specifies it

- cmd/podman/containers/stats.go
- pkg/api/handlers/libpod/containers_stats.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_stats_options.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/stats_test.go
Yes, by default it shows only running containers, unless `--all` is specified
closes #19252 
@vrothberg it looks odd that we didn't have `All` in `ContainerStatsOptions` and that we set the default to `queryAll`.
Maybe I should remove "--all" from stats? Let me know
> Fix: use --all in podman stats to get all containers stats

- .cirrus.yml
- Makefile
A small number of tests are assuming that TMPDIR == /tmp. These tests fail when that assumption does not hold.
Set TMPDIR=/var/tmp on prior-fedora, as a way to catch those. /dev/shm would be a slightly better choice, because the string "tmp" does not appear it in, but it's way too small to be of any use: it fills up in the e2e prefetch.
This PR exposed a nasty bug in our Makefile: using "TMPDIR" as temporary variable completely unrelated to (and inconsistent with) the actual established use of TMPDIR. Solution: rename that variable and make it lower case. Do the same with two other ALL-CAP variables.
```release-note
None
```
> CI: use different TMPDIR on prior-fedora

- Makefile
- rpm/podman.spec
go-md2man is fragile, especially around tables (#18678, #19278).
Podman man pages are finely tuned to look OK using v2.02, which
is what we vendor in test/tools, so we should really use it
instead of whatever is installed on the system.
This fixes 'make docs' on RHEL8, broken as of #19278.
```release-note
Fixes broken tables on some RHEL8 man pages
```
> [CI:DOCS] go-md2man: use vendored-in version, not system

- libpod/container_internal.go
We'd otherwise emit the start event much after the actual start of the container when --sdnotify=healthy.  I missed adding the change to commit 0cfd12786fd1.
```release-note
None
```
> start(): don't defer event

- cmd/quadlet/main.go
- test/system/252-quadlet.bats
If a user puts a quadlet file in his homedirectory with the same name as one in /etc/containers/systemd/user or /etc/containers/systemd/user/$UID, then only use the one in homedir and ignore the others.
```release-note
Quadlet will only use a single quadlet for a given name.
```
> If quadlets have same name, only use first

- test/system/252-quadlet.bats
Use "--wait" flag in "systemd start" for a one-shot container.
Should fix a CI failure I've been seeing sporadically, in which
the --==VALUE==-- string is not seen in journal.
And, should this not fix the bug, at least make the failure easier to understand.
```release-note
None
```
> System tests: quadlet: fix race in %T test

- docs/tutorials/socket_activation.md
The default socat timeout is 0.5 seconds.
Make the socket-activate-echo example in [socket_activation.md](https://github.com/containers/podman/blob/main/docs/tutorials/socket_activation.md) more robust by increasing the socat timeout.
Regarding the text: I'm not sure this is good understandable English:
```
The option `-t 30` configures socat to use a timeout of 30 seconds when socat reads from the socket awaiting to get an EOF (End-Of-File).
```
Fixes: https://github.com/containers/podman/issues/19373
```release-note
None
```
> [CI:DOCS] socket_activation.md: increase socat timeout

- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
Lock the VM on start.  If the machine is in the "starting" state we know that a previous start has failed and guide the user into resolving the issue.
Concurrent starts will busy wait and return the expected "already running" error.
NOTE: this change is only looking at the start issue (#18662).  Other commands such as stop and update should also lock and will be updated in a future change.  I expect the underlying issue to apply to all machine providers, not only QEMU.  It's desirable to aim for extending the machine interface to also allow to `Lock()` and `Unlock()`.  After acquiring the lock, the VM should automatically be reloaded/updated.
Fixes: #18662
```release-note
Fix a concurrency bug in `podman machine start` using the QEMU provider.
```
@n1hility @rhatdan …
> machine: QEMU: lock VM on start

- .cirrus.yml
- DOWNLOADS.md
Fixes #19383 (regression introduced by #19349)
```release-note
none
```
> Fix regression in CI artifacts script introduced by legacy msi removal

- cmd/podman/auto-update.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- cmd/podman/containers/runlabel.go
- cmd/podman/images/build.go
- cmd/podman/images/pull.go
- cmd/podman/images/push.go
- cmd/podman/images/search.go
- cmd/podman/images/sign.go
- cmd/podman/kube/play.go
- cmd/podman/manifest/add.go
- cmd/podman/manifest/inspect.go
- cmd/podman/manifest/push.go
- test/system/030-run.bats
In certain cases REGISTRY_AUTH_FILE is set but the auth file does not exists yet, do not throw error unless user specified a file directly using --authfile.
Fixes: https://github.com/containers/podman/issues/18405
```release-note
None
```
> Make sure users changes --authfile before checking

- docs/source/markdown/options/mount.md
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- pkg/specgenutil/volumes.go
- pkg/systemd/quadlet/quadlet.go
- test/system/060-mount.bats
HPC Community asked for this support specifically for using GPUs
within containers. Nvidia requires the correct shared library to
to be present in the directory that matches the device mounted
into the container. These libraries have random suffixes based
on versions of the installed libraries on the host.
podman run --mount type=glob:src=/usr/lib64/nvidia\*:ro=true. This helps
quadlets be more portable for this use case.
```release-note
Podman --mount option supports bind mounts passed as globs.
```
> Add glob support to podman run/create --mount

- pkg/machine/qemu/config.go
Breaks up some sections of code where we implement the  `VirtProvider` interface for QEMU that could be its own function.
```release-note
None
```
> Breakup qemu config funcs

- libpod/kube.go
On FreeBSD, config.Spec.Linux and config.Spec.Process.Capabilities are nil pointers so this just avoids dereferencing these pointers in that case.
```release-note
None
```
> libpod: fix 'podman kube generate' on FreeBSD

- .github/ISSUE_TEMPLATE/config.yml
Some issues reported in the podman github project contains a question instead of a bug report or  a feature request. Make it easier for users to find a place to ask questions.
This PR was inspired by
https://github.com/containers/podman/pull/18853
```release-note
None
```
> [SKIP CI] github: add issue type as link to podman github discussions

- test/apiv2/python/requirements.txt
- test/python/requirements.txt
Apparent Cython regression causing a warning and traceback when installing PyYAML with pip:
Ref. Upstream issue 601: https://github.com/yaml/pyyaml/issues/
Ref. warning message:
```
********************************************************************************
The license_file parameter is deprecated, use license_files instead.
By 2023-Oct-30, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
```
Ref. traceback snippet:
```
Traceback (most recent call last):
File "/var/tmp/go/src/github.com/containers/podman/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks …
```
> [v4.1.1-rhel] Fix AttributeError: cython_sources

- libpod/container_internal_freebsd.go
- libpod/container_top_freebsd.go
- libpod/pod_top_freebsd.go
- libpod/pod_top_unsupported.go
- libpod/stats_freebsd.go
This shares code with 'container top' which runs ps on the host, filtering for the containers that are part of the pod. (*Container).jailName is modified to take into account the possiblity that the container is in a pod - this also fixes stats reporting for pods on FreeBSD.
```release-note
None
```
> libpod: add 'pod top' support on FreeBSD

- hack/bats
- test/system/001-basic.bats
- test/system/030-run.bats
- test/system/032-sig-proxy.bats
- test/system/035-logs.bats
- test/system/070-build.bats
- test/system/075-exec.bats
- test/system/080-pause.bats
- test/system/090-events.bats
- test/system/130-kill.bats
- test/system/160-volumes.bats
- test/system/170-run-userns.bats
- test/system/180-blkio.bats
- test/system/190-run-ipcns.bats
- test/system/195-run-namespaces.bats
- test/system/260-sdnotify.bats
- test/system/410-selinux.bats
- test/system/500-networking.bats
BATS 1.8.0 introduces tags: metadata that can be applied to
a single test or one entire file, then used for filtering
in a test run.
Issue #19299 introduces the possibility of using OpenQA
for podman reverse dependency testing: continuous CI on
all packages that can affect podman, so we don't go two
months with no bodhi builds then get caught by surprise
when systemd or kernel or crun change in ways that break us.
This PR introduces one bats tag, "distro-integration". The intention
is for OpenQA (or other) tests to install the podman-tests package
and run:
bats --filter-tags distro-integration /usr/share/podman/test/system
Goal is to keep the test list short and sweet: we do not
need to test command-line option parsing. We *DO* need to
test interactions with systemd, kernel, nethack, and …
> System tests: add test tags

- test/python/requirements.txt
Apparent Cython regression causing a warning and traceback when
installing PyYAML with pip:
Ref. Upstream issue 601: https://github.com/yaml/pyyaml/issues/
Ref. warning message:
```
********************************************************************************
The license_file parameter is deprecated, use license_files instead.
By 2023-Oct-30, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************
```
Ref. traceback snippet:
```
Traceback (most recent call last):
File "/var/tmp/go/src/github.com/containers/podman/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks …
```
> [v4.0-rhel] Fix AttributeError: cython_sources

- .github/workflows/mac-pkg.yml
- RELEASE_PROCESS.md
Create a new GitHub Action that builds and signs the Mac pkginstaller. The action also uploads the installers to the release, and updates the shasums file.
This action is triggered on release creation, but it can also be triggered manually via a workflow dispatch.
```release-note
None
```
> [CI:DOCS] Build and Sign Mac Pkginstaller

- rpm/podman.spec
gvproxy doesn't currently build on rawhide because of go1.21. It  can be included as a standalone package on copr. It is currently open for review on bugzilla until which fedora releases can't include it. Official rawhide should be able to fetch the last active build of gvproxy, the min version requirement has been removed to allow it. Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2224434
```release-note
None
```
> [CI:BUILD] RPM: separate out gvproxy for copr and rawhide

- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
Re-names HyperV function that was copied from the applehv implementation and not changed.
```release-note
None
```
> Fix HyperV loadMachineFromJSON function name

- pkg/machine/hyperv/machine.go
The functions for HyperV's VM interface implementation (machine.go) had quite large functions. Pulls out some code that could be moved to its own function for easier readability.
```release-note
None
```
> Breakup hyperv machine funcs

- test/e2e/checkpoint_image_test.go
- test/e2e/checkpoint_test.go
And lo, a miracle occurred. Containerized checkpoint tests are
no longer hanging. Reenable them.
(Followup miracle: tests are still passing, after a year of not
running!)
Closes: #15015
```release-note
None
```
> CI: e2e: reenable containerized checkpoint tests

- docs/source/markdown/podman-systemd.unit.5.md
```release-note
Docs for TimeoutStartSec added to Quadlet man page.
```
> [CI:DOCS] Mention TimeoutStartSec in quadlet man page

- libpod/networking_common.go
- libpod/networking_freebsd.go
- libpod/networking_linux.go
- test/system/500-networking.bats
We do not use any special netns path for the netns=none case, however callers that inspect that may still wish to join the netns path directly without extra work to figure out /proc/$pid/ns/net.
Fixes #16716
```release-note
podman inspect will now show a `.NetworkSettings.SandboxKey` path for containers created with --net=none. 
```
> inspect with network=none show SandboxKey netns path

- pkg/api/handlers/compat/containers.go
- test/apiv2/20-containers.at
If the container isn't running, make sure to return 409 as specified in the Docker API [1] and the Podman reference.
[1] https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerKill
Fixes: #19368
```release-note
Fix a bug in the containers/kill rest API to correctly return 409 when a container is not running.
```
> API: kill: return 409 on invalid state

- docs/source/markdown/options/env-file.md
- pkg/env/env.go
- pkg/env/env_test.go
- pkg/env/env_unix.go
- pkg/env/env_windows.go
Close: https://github.com/containers/podman/issues/18724
```release-note
Support multiline in `--env-file`
```
/cc @Luap99 @vrothberg
> feat(env): support multiline in env-file

- pkg/bindings/images/build.go
- test/system/070-build.bats
Closes #15921.
I am not sure if you want to add a new test for this.
```release-note
`None`
```
> Don't log EOF error when using podman --remote build with an empty context directory.

- .github/workflows/mac-pkg.yml
- .github/workflows/upload-win-installer.yml
Having hard-coded versions burried under a hidden directory is ripe for maintenance headaches.  Use the latest 'stable' version, since this will be "close enough" to what we test in CI.
Ref: https://github.com/containers/podman/discussions/19404
***Note***: There's no simple way to test these changes, they're only effective after being merged into `main`.  However, I [double-checked the `actions/setup-go` docs](https://github.com/actions/setup-go) and am confident this change will work okay.
```release-note
None
```
> [CI:DOCS] GHA: Use stable go for Mac/Win builds

- cmd/quadlet/main.go
- test/system/252-quadlet.bats
If a user puts a quadlet file in his homedirectory with the same name as one in /etc/containers/systemd/user or /etc/containers/systemd/user/$UID, then only use the one in homedir and ignore the others.
```release-note
If quadlets have the same name found in different directories, prefer the first one found.
```
> [v4.6] If quadlets have same name, only use first

- rpm/podman.spec
The current gobuild macro doesn't account for build tags on both c9s and c8s. This is currently causing copr build failures for c9s.
Ref: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/6220412/
This commit will define gobuild for all those envs until gobuild is fixed by default.
Refs:
c9s bz: https://bugzilla.redhat.com/show_bug.cgi?id=2227328
c8s bz: https://bugzilla.redhat.com/show_bug.cgi?id=2227331
```release-note
None
```
> [CI:BUILD] RPM: define gobuild macro for rhel/centos stream

- rpm/podman.spec
gvproxy has now been approved as a standalone package on Fedora and will be included separately for fedora 38 and higher.
```release-note
None
```
> [v4.6] [CI:BUILD] RPM: separate out gvproxy for copr and fedora >= 38

- hack/bats
- test/system/001-basic.bats
- test/system/030-run.bats
- test/system/032-sig-proxy.bats
- test/system/035-logs.bats
- test/system/070-build.bats
- test/system/075-exec.bats
- test/system/080-pause.bats
- test/system/090-events.bats
- test/system/130-kill.bats
- test/system/160-volumes.bats
- test/system/170-run-userns.bats
- test/system/180-blkio.bats
- test/system/190-run-ipcns.bats
- test/system/195-run-namespaces.bats
- test/system/260-sdnotify.bats
- test/system/410-selinux.bats
- test/system/500-networking.bats
[
Clean cherry-pick of #19302. This is a low-risk change
with potentially very high ROI: the opportunity to catch
interaction problems with updates in other system components.
]
BATS 1.8.0 introduces tags: metadata that can be applied to a single test or one entire file, then used for filtering in a test run.
Issue #19299 introduces the possibility of using OpenQA for podman reverse dependency testing: continuous CI on all packages that can affect podman, so we don't go two months with no bodhi builds then get caught by surprise when systemd or kernel or crun change in ways that break us.
This PR introduces one bats tag, "distro-integration". The intention is for OpenQA (or other) tests to install the podman-tests package and run:
bats --filter-tags distro-integration …
> [v4.6] System tests: add test tags

- test/e2e/login_logout_test.go
As of #19391, REGISTRY_AUTH_FILE=/nonexistent no longer
causes 'podman run' to die.
```release-note
None
```
> CI: e2e: remove workaround for missing login file

- pkg/machine/applehv/machine.go
- pkg/machine/connection.go
- pkg/machine/hyperv/machine.go
- pkg/machine/machine_common.go
- pkg/machine/pull.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
Consolidates duplicate code across the various hypervisors' `machine.go` file and places it either in the proper file that already exists or in the new `pkg/machine/machine_common.go` file.
```release-note
None
```
> Consolidate `machine.go` duplicate code across hypervisors

- docs/source/markdown/options/cidfile.write.md
- docs/source/markdown/podman-ps.1.md
- pkg/domain/entities/container_ps.go
- pkg/domain/infra/tunnel/containers.go
- pkg/ps/ps.go
Currently the CIDFile is not removed with podman --remote run --rm if the client and server are on different machines.
[NO NEW TESTS NEEDED] i
There is currently a test for this that does not fail because the client and server are on the same machine.
If we run these tests on a MAC or Windows platform, they would start failing.
Fixes: https://github.com/containers/podman/issues/19420
```release-note
CID Files on remote clients will now be removed when container is removed
```
> Cleanup CIDFile on podman-remote run --rm command

- docs/source/markdown/podman-completion.1.md
Currently, due to sphinx smart quote features being enabled, fancy quotes are used in the commands. This means the docs are harder to use as the commands cannot be copy/pasted into a terminal.
Wrapping the code in code blocks fixes this. An alternative would be to disable smart quotes entirely, but this seems over-the-top (especially considering wrapping commands in code blocks harmonises this page with most of the other documentation)
```release-note
None
```
> [CI:DOCS] Use code blocks for commands in podman-completion

- cmd/podman/containers/run.go
- docs/source/markdown/podman-run.1.md.in
- test/system/030-run.bats
Forcing users to set --rm when setting --rmi is just bad UI. If I want the image to be removed, it implies that I want the container removed that I am creating.
Fixes: https://github.com/containers/podman/issues/15640
```release-note
podman run --rmi now implies --rm option.
```
> Make podman run --rmi automatically set --rm

- .github/workflows/mac-pkg.yml
- .github/workflows/upload-win-installer.yml
Neither `release` nor `workflow_dispatch` triggers may be tested inside a PR context.  The workflow steps always run from what's already committed to `main`.  Rather than waiting for a release to discover some unforeseen workflow problem, allow manual runs to optionally skip the release upload step (by default).
TODO:
```release-note
None
```
> [CI:DOCS] GHA: Support testing build/sign workflows

- cmd/podman/manifest/push.go
- docs/source/markdown/podman-manifest-push.1.md.in
- go.mod
- go.sum
- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_manifest.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_push_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
- test/system/012-manifest.bats
- vendor/github.com/containers/image/v5/copy/multiple.go
- vendor/modules.txt
This is a feature PR for containers/image feature merged in below PR:
* https://github.com/containers/image/pull/2023
* https://github.com/containers/image/pull/1987
* https://github.com/containers/image/pull/2029
Adds a new flag  **--add-compression <compression>**  to manifest push, which when added will push existing manifest on host while replicating the instances with required compression.
```release-note
manifest, push: implement --add-compression to push with compressed variants.
```
Similar implementation to: https://github.com/containers/buildah/pull/4912
> manifest, push: implement `--add-compression` to push with compressed variants.

- pkg/specgen/generate/config_common.go
- pkg/specgen/generate/config_common_test.go
- pkg/specgen/generate/config_freebsd.go
- pkg/specgen/generate/config_linux.go
- pkg/specgen/generate/config_linux_test.go
- pkg/specgen/generate/oci_freebsd.go
- pkg/specgen/generate/security_freebsd.go
On FreeBSD, each container has its own devfs instance with a ruleset that controls what the container can see. To expose devices to a container we add rules to its devfs to make the requested devices visible. For privileged containers, we use 'ruleset=0' which makes everything visible.
This shares the ParseDevice function with Linux so it moves to config_common.go from config_linux.go.
```release-note
Add support for 'podman run --device' on FreeBSD
```
> pkg/specgen: Add device support for FreeBSD

- pkg/machine/hyperv/machine.go
the method caller for creating the ignition file was accidently misordered for hyperv.  this regression was caused by aa6827a6.
```release-note
None
```
> Fix regression for hyperv

- cmd/podman/generate/systemd.go
- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-generate.1.md
- docs/source/markdown/podman-systemd.unit.5.md
- test/system/250-systemd.bats
Now that Quadlets are fully supported, it is time to Depracate podman generate systemd command.
```release-note
The `podman generate systemd` command is deprecated.  Use Quadlet for running containers and pods under systemd. 
```
> Deprecate podman generate systemd

- rpm/update-spec-version.sh
`git describe` is lagging on main so this commit updates `rpm/update-sepc-version.sh` to generate the expected version.
```release-note
None
```
No release note, given release branches won't be affected.
> [CI:BUILD] Makefile: rpm target generates correct version

- pkg/machine/keys.go
when init'ing a machine, if the ssh key already exists, then we get a somewhat oblique error.  here we make it clear what the problem was and early return.
```release-note
None
```
> Fail if ssh key exists

- contrib/cirrus/lib.sh
- libpod/define/info.go
- test/e2e/info_test.go
The `Exists` field of the `RemoteSocket` struct is marshaled to json with the `omitempty` setting. This has the disadvantage that by default `podman info` shows a `remotePath` entry (the remote path is set in `pkg/domain/infra/abi/systems.go`: `(*ContainerEngine).Info`) but not that this path does not exist:
```
❯ podman info --format json | jq .host.remoteSocket
{
"path": "/run/user/1000/podman/podman.sock"
}
```
By removing the `omitempty`, we ensure that the existence is always shown:
```
❯ bin/podman info --format json | jq .host.remoteSocket
{
"path": "/run/user/1000/podman/podman.sock",
"exists": false
}
```
```release-note
- always display the existence of the podman socket in `podman info`
```
> Always show RemoteSocket.Exists in json

- libpod/container.go
For containers using host networking, 'kube generate' crashed in (*Container).HostNetwork which dereferenced config.Spec.Linux without checking if its non-nil, which is the case for FreeBSD containers.
```release-note
None
```
> libpod: fix a crash in 'kube generate' on FreeBSD

- Makefile
The mandoc(1) utility is used for this on FreeBSD systems. This fixes a confusing (but harmless) series of error messages when building manpages on FreeBSD.
```release-note
None
```
> Makefile: work around the lack of 'man -l' on FreeBSD

- hack/xref-helpmsgs-manpages
Check for duplicate subcommands, flags, and format specifiers.
I assumed this would never be necessary, that code review would
catch dups, but it happened (#19462). Prevent future ones.
Also, make it a fatal error for a --format to be undocumented,
except for 'podman inspect'. So many exceptions ... :(
```release-note
None
```
> [CI:DOCS] man-page xref: check for duplicate entries

- .github/workflows/mac-pkg.yml
- .github/workflows/upload-win-installer.yml
Several comment/docs updates, and one small workflow change to include generated `shasums` file in workflow artifacts.
```release-note
None
```
> [CI:DOCS] Minor mac/windows GHA workflow updates

- cmd/podman/containers/restart.go
- cmd/podman/containers/rm.go
- cmd/podman/containers/stop.go
- cmd/podman/networks/rm.go
- cmd/podman/pods/rm.go
- cmd/podman/pods/stop.go
- cmd/podman/volumes/rm.go
- docs/source/markdown/options/stop-timeout.md
- docs/source/markdown/options/time.md
- docs/source/markdown/podman-network-rm.1.md
- docs/source/markdown/podman-volume-rm.1.md
- libpod/oci_conmon_common.go
- libpod/options.go
- pkg/api/handlers/compat/containers_stop.go
- pkg/domain/infra/tunnel/containers.go
- pkg/util/utils.go
- test/apiv2/22-stop.at
- test/e2e/pod_stop_test.go
- test/e2e/start_test.go
- test/system/030-run.bats
- test/system/160-volumes.bats
- test/system/200-pod.bats
- test/system/500-networking.bats
- test/system/700-play.bats
Add support for `podman stop --time -1`
Add support for `podman restart --time -1`
Add support for `podman rm --time -1`
Add support for `podman pod stop --time -1`
Add support for `podman pod rm --time -1`
Add support for `podman volume rm --time -1`
Add support for `podman network rm --time -1`
Fixes: https://github.com/containers/podman/issues/17542
```release-note
Compatibility API now accepts timeout=-1 for stopping containers.
```
> Add support for passing container stop timeout as -1 (infinite) 

- pkg/specgen/generate/storage.go
- test/e2e/run_test.go
We do not allow volumes and mounts to be placed at the same location in the container, with create-time checks to ensure this does not happen. User-added conflicts cannot be resolved (if the user adds two separate mounts to, say, /myapp, we can't resolve that contradiction and error), but for many other volume sources, we can solve the contradiction ourselves via a priority hierarchy. Image volumes come first, and are overridden by the `--volumes-from` flag, which are overridden by user-added mounts, etc, etc. The problem here is that we were not properly handling volumes-from overriding image volumes. An inherited volume from --volumes-from would supercede an image volume, but an inherited mount would not. Solution is fortunately simple - just clear out the map entry for the other type …
> Ensure volumes-from mounts override image volumes

- libpod/oci_conmon_common.go
Because it will cause memory leak if we do not stop timer when the function has completed.
```release-note
None
```
> Stop timer in function waitPidStop

- docs/source/markdown/podman-build.1.md.in
Fixed couple of typos that broke formatting in podman-build docs.
```release-note
None
```
> [CI:DOCS] fixed couple typos in build docs

- cmd/podman/containers/stop.go
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-stop.1.md.in
- test/system/050-stop.bats
Podman should ignore failures to find a cidfile when stoping the container if the user specified --ignore
Fixes: https://github.com/containers/podman/issues/19546
```release-note
Podman stop will ignore cidfile not existing when user specifies --ignore flag.
```
> podman stop --cidfile missing --ignore

- cmd/podman/common/completion.go
- docs/source/markdown/options/compression-format.md
Remove the references of the zstd:chunked encryption algorithm as this will not be supported in RHEL 8.9/9.3 in Podman v4.6.1.  Support is expected in Podman v4.7 and later.
```release-note
None
```
> [v4.6] Remove zstd:chunked reference

- pkg/env/env.go
- pkg/env/env_test.go
- pkg/env/env_unix.go
- pkg/env/env_windows.go
Fixed: https://github.com/containers/podman/pull/19096#issuecomment-1670164724
Fixed: https://github.com/containers/podman/pull/19096#issuecomment-1670613061
The root cause of this issue lies in the fact that the shell discards the quotes in the parameters, as shown in the following code snippet:
```shell
podman run -e K='a#b' alpine printenv aaa
podman run -e K=a#b alpine printenv aaa
```
This will result in problems with the current `parseEnv` implementation. Unfortunately, there is no way to change the behavior of the shell, so the only option is to fix it within `parseEnv`. In order to reduce code complexity, I have ported the previous `parseEnv` function back and renamed it as `parseEnvWithSlice`. Furthermore, this function will be used exclusively for the `--env` option, which will …
> fix(env): parsing --env incorrect in cli

- test/e2e/containers_conf_test.go
- test/e2e/logs_test.go
- test/e2e/play_kube_test.go
...to reduce flakes.
Reason: journald makes no guarantees. Just because a systemd job
has finished, or podman has written+flushed log entries, doesn't
mean that journald will actually know about them:
https://github.com/systemd/systemd/issues/28650
Workaround: Sleep(1) before every 'podman logs' or 'journalctl'.
Better ideas welcome.
This addresses, but does not close, #18501. That's a firehose,
with many more failures than I can possibly cross-reference.
I will leave it open, then keep monitoring missing-logs flakes
over time, and pick those off as they occur.
```release-note
None
```
> CI: e2e: add delay before podman logs or journalctl

- test/system/300-cli-parsing.bats
We've made rather a mess of those options, due to lack of testing.
Here we have a first step toward regression tests. --env is OK,
but there are three special-case exceptions in --env-file for
three incompatibilities introduced by #19096.
To be continued, but probably in future PRs. We need this ASAP
to prevent us from making any more regressions.
```release-note
None
```
> systests: tests for --env and --env-file

- .packit.yaml
Fedora ELN targets were removed in the switch to ephemeral coprs. Add them back.
Podman rpm doesn't depend on go-md2man package anymore and instead uses vendored go-md2man for building manpages, so that's no longer a reason for build failures on Fedora ELN.
```release-note
None
```
> [CI:BUILD] Packit: add back fedora-eln targets

- RELEASE_NOTES.md
```release-note
None
```
Closes https://github.com/containers/podman/issues/19594
> [CI:DOCS] [4.6] Update Release Notes

- docs/tutorials/performance.md
Without the verb 'shell', the invocation fails with:
Unknown command verb testuser@
```release-note
None
```
> [CI:DOCS] Add missing verb in machinectl example

- cmd/podman/parse/net.go
- cmd/podman/parse/net_test.go
This PR requires the changes of https://github.com/containers/common/pull/1549
```release-note
The `--add-host` option now accepts the special string `host-gateway` instead of an IP Address, which will be mapped to the host IP address. 
```
> Add support for host-gateway

- .cirrus.yml
The mechanism fueling the benchmarks job has long since been removed. Running the job is useless now, remove it.
```release-note
None
```
> [CI:BUILD] Cirrus: Prune defunct job + fix noop alias

- docs/source/markdown/options/rootfs.md
The newly introduced `idmap` section of rootfs lacked a header (comparable to Overlay Rootfs Mounts), had odd formatting, and wording that differed from other instances of idmap, e.g., the one in the --volume section. This commits addresses those issues.
```release-note
None
```
> Update rootfs.md: Fix formatting and wording of idmap option

- pkg/api/handlers/compat/changes.go
- pkg/api/handlers/compat/containers.go
- pkg/api/handlers/compat/containers_archive.go
- pkg/api/handlers/compat/containers_attach.go
- pkg/api/handlers/compat/containers_create.go
- pkg/api/handlers/compat/containers_logs.go
- pkg/api/handlers/compat/containers_restart.go
- pkg/api/handlers/compat/containers_start.go
- pkg/api/handlers/compat/containers_stats_linux.go
- pkg/api/handlers/compat/containers_stop.go
- pkg/api/handlers/compat/containers_top.go
- pkg/api/handlers/compat/events.go
- pkg/api/handlers/compat/images.go
- pkg/api/handlers/compat/images_build.go
- pkg/api/handlers/compat/images_push.go
- pkg/api/handlers/compat/images_remove.go
- pkg/api/handlers/compat/images_search.go
- pkg/api/handlers/compat/networks.go
- pkg/api/handlers/compat/resize.go
- pkg/api/handlers/compat/secrets.go
- pkg/api/handlers/compat/volumes.go
- pkg/api/handlers/decoder.go
- pkg/api/handlers/utils/handler.go
- pkg/api/server/register_images.go
- pkg/api/server/server.go
- pkg/api/types/types.go
- test/apiv2/10-images.at
- test/python/docker/compat/test_containers.py
Fixing Docker client incompatibility:
```
docker build . -t alpine-1000 --pull
Sending build context to Docker daemon  2.048kB
Error response from daemon: failed to parse query parameter 'pull': "1": invalid pull policy: "1"
```
* Revert https://github.com/containers/podman/pull/18583 since it breaks compatibility with standard docker client.
Previously it was believed the `pull` parameter is pull-policy since REST API doc says it is `string`, not `bool`. However it fact it is a boolean. Confusingly enough Docker indeed accept values like `always` or `never` but these values are interpreted as `true` by Docker. As matter of the fact it appears that there is no such a thing as `pull-policy` in Docker.
* Use custom boolean query param deserializer for all compat endpoints to get closer to …
> Fix pull parameter parsing for compat `/build` endpoint

- docs/source/conf.py
Tell sphinx not to process the "options" dir, those files
are not to be published.
Context: websearching for podman volume info, I stumbled upon:
https://docs.podman.io/en/latest/markdown/options/volume.html
...and panicked because I saw '<<container|pod>>', the options
include-file syntax that should never be seen by users. I thought
the filter script was broken.
```release-note
None
```
> [CI:DOCS] sphinx: skip options include dir

- .cirrus.yml
The VM-naming feature is now mainstream.
Ref: https://github.com/cirruslabs/cirrus-ci-docs/ issue 1051
Testing note:  Manually confirmed [the `Build for fedora-38-aarch64` task](https://cirrus-ci.com/task/6388501483094016) created an EC2 VM with the following tags:
Key | Value
-- | --
CIRRUS_REPO_FULL_NAME | containers/podman
CIRRUS_BUILD_ID | 6599283714031616
Name | cirrus-task-6388501483094016
```release-note
None
```
> Cirrus: Remove EC2 experimental flag

- pkg/api/handlers/compat/images_build.go
- test/python/docker/compat/test_containers.py
Fixing Docker client incompatibility where the `/build` endpoint cannot parse "1" as a boolean.
This PR makes the endpoint to accept string representing boolean which are booleanish by Go standard: string that can be parsed by `strconv.ParseBool()`.
The bug reproduction:
```
docker build . -t alpine-1000 --pull
Sending build context to Docker daemon  2.048kB
Error response from daemon: failed to parse query parameter 'pull': "1": invalid pull policy: "1"
```
```release-note
Correct parsing of the pull query parameter for the compat /build endpoint.
```
> [v4.6] fix: pull parma parsing for the /build compat ep

- test/e2e/manifest_test.go
Flake suppression: going with the one-basket model of egg storage,
switch manifest_test to use an image on quay.io (was: k8s.io).
Closes: #19148
```release-note
None
```
> CI: e2e manifest_test: use image from quay

- docs/source/markdown/podman-build.1.md.in
The git repo that was used for the example of a git build:
`podman build https://github.com/scollier/purpletest`
no longer exists.  Someone reached out to @rhatdan about this, and he suggested using the Podman Hello World repo.  However, that didn't exist until a little bit ago, so I've updated the man page with a pointer there.  That should be a lot more stable.
```release-note
None
```
> [CI:DOCS] Fix git build example in build page

- pkg/api/handlers/compat/images_build.go
- test/python/docker/compat/test_containers.py
The standard Docker client passes "1" for pull query parameter. This means our compat endpoint has to work with this. The endpoint was recently modified to accept pull-policy however this is not how Docker actually work. Docker actually treats `pull` as boolean.
For sake of compatibility I decide to preserve pull-policy parsing too. We can consider this podman's extension. I should not affect standard clients.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2232127
```release-note
None
```
> [v4.6.1-rhel] fix: pull param parsing for the /build compat ep

- Makefile
- pkg/machine/fcos.go
~~- add riscv64 linux static release build~~
~~- update the release-artifacts with riscv64~~
~~- bump containers/ocicrypt to v1.1.8~~
- adding a cross-compilation option for riscv64
- extending GetFcosArch with the riscv64 architecture parameter
> Add riscv64 support for cross compilation

- test/system/410-selinux.bats
- test/system/505-networking-pasta.bats
SELinux tests are failing in f37, f38, Rawhide. (Did I miss any?) Assume that the new container-selinux will never be available on any of those, so let's just skip those tests. #19376
Pasta ICMP test fails pretty consistently in Gating, and is even flaking in Cirrus, so let's skip that too. #19612
```release-note
None
```
> [v4.6] Skip tests that fail in gating

- cmd/podman/secrets/create.go
- docs/source/markdown/podman-secret-create.1.md
Closes #18387
Yes (minor text changes in `./bin/podman secret create --help` and `man podman-secret-create`, so release note may not be required after all)
> document available secret drivers

- pkg/specgen/generate/security_freebsd.go
This just sets the flag in the runtime spec - the actual implementation is in the OCI runtime.
```release-note
None
```
> pkg/specgen: add support for read-only root on FreeBSD

- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
- test/apiv2/python/requirements.txt
- test/e2e/build_test.go
- test/python/requirements.txt
Backport per RHBZ [2229749](https://bugzilla.redhat.com/show_bug.cgi?id=2229749)
Replaces #19416
```release-note
NONE
```
> Backport #18577 to v4.4.1-rhel

- docs/source/markdown/podmansh.1.md
Switch man page to user USERID instead of UID, since UID environment variable is set at login, and is not allowed to be changed.
UID=foobar
bash: UID: readonly variable
Fixes: https://github.com/containers/podman/issues/19646
```release-note
None
```
> [CI:DOCS] podmansh man page UID=3267 is not allowed

- test/system/505-networking-pasta.bats
IPv6 test has been hard-skipped for six months.
IPv4 test is flaking in Cirrus and hard-failing in Gating.
Absent a reliable way to test in CI and gating, and absent
a strong reason to test ICMP in pasta anyway, the solution
is simple.
Closes: #19612
```release-note
None
```
> CI: systests: remove pasta ICMP tests

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go
- vendor/modules.txt
port Commit 55397de (cgroups: use SessionBusPrivateNoAutoStartup) from cgroups.go to cgroups_linux.go
do not start up a dbus daemon if it is not already running.
[NO NEW TESTS NEEDED] the fix is in a dependency.
```release-note
None
```
> cgroups_linux: use SessionBusPrivateNoAutoStartup

- pkg/machine/applehv/machine.go
- pkg/machine/gvproxy.go
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
when we stop a machine, we need to also stop the gvproxy process that is running.
JIRA: RUN-1828
also, remove unused applehv function for ssh
```release-note
None
```
> Stop gvproxy on hyperv machine stop

- pkg/machine/wsl/machine.go
- pkg/machine/wsl/usermodenet.go
- pkg/machine/wsl/wutil/wutil.go
User-mode networking requires the current generation of WSL 2
Fail with a helpful message when an older version of WSL2 is installed and user-mode-networking is enabled.
```release-note
Detect and error with upgrade guidance when enabling user-mode-networking on an older WSL2 generation
```
> Validate current generation of WSL2 with user-mode-networking

- pkg/specgen/generate/container_create.go
- test/system/200-pod.bats
Fixes: https://github.com/containers/podman/issues/19671
```release-note
If restart policy is specified for container in a pod, then use it rather then the pods restart policy.
```
> use container restart policy if user specifies one

- docs/source/markdown/options/secret.md
- docs/source/markdown/podman-run.1.md.in
- libpod/container_internal_common.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
- libpod/runtime_ctr.go
- pkg/specgen/generate/storage.go
- pkg/specgen/generate/storage_freebsd.go
- pkg/specgen/generate/storage_linux.go
This changes /run to /var/run for .containerenv and secrets in FreeBSD containers for consistency with FreeBSD path conventions. Running Linux containers on FreeBSD hosts continue to use /run for compatibility.
```release-note
None
```
> libpod: use /var/run instead of /run on FreeBSD

- docs/source/markdown/options/mount.md
- libpod/define/mount.go
- pkg/specgenutil/volumes.go
- pkg/util/mountOpts.go
- test/system/060-mount.bats
Users want to mount a tmpfs file system with secrets, and make
sure the secret is never saved into swap. They can do this either
by using a ramfs tmpfs mount or by passing `noswap` option to
a tmpfs mount.
Fixes: https://github.com/containers/podman/issues/19659
```release-note
podman run and create --mount now support the `ramfs` type.
```
> Add support for ramfs as well as tmpfs in volume mounts

- pkg/specgen/generate/kube/kube.go
- test/e2e/play_kube_test.go
- test/system/700-play.bats
Fixes a bug where `podman kube play` fails to set a container's Umask to the default 0022, and sets it to 0000 instead.
```release-note
Fixes a bug where `podman kube play` fails to set a container's Umask to the default 0022
```
> Set default Umask for `podman kube play`

- .github/workflows/discussion_lock.yml
- CONTRIBUTING.md
Lock closed issues and PRs after a reasonable amount of time to prevent spamming engineers with irreverent notifications.  Should the workflow fail for some reason, notify the podman-monitor mailing list.
N/B: This PR includes a commit intended to help confirm this workflow functions w/o affecting potentially thousands of issues/PRs.  It's intended to be reverted by a future PR.
```release-note
None
```
> [skip-ci] Lock closed issues and PRs

- .github/workflows/discussion_lock.yml
This is intentional, it was needed for testing.  See 
https://github.com/containers/podman/pull/19691
```release-note
None
```
> [CI:DOCS] Revert "GHA: Closed issue/PR comment-lock test"

- pkg/machine/gvproxy.go
- pkg/machine/gvproxy_unix.go
- pkg/machine/gvproxy_windows.go
Paul found logic errors in my earlier code for finding processes and sending signals.  Some of the logic errors are associated with how methods behave on different operating systems.  Created a darwin and linux approach and a windows approach.
```release-note
None
```
> Fixups for stopping gvproxy

- pkg/machine/config.go
- pkg/machine/connection.go
- pkg/machine/ports.go
- pkg/machine/ports_unix.go
- pkg/machine/ports_windows.go
- pkg/machine/wsl/config.go
- pkg/machine/wsl/machine.go
Fixes containers/podman#19554
We have had reports of strange intermittent/infrequent connectivity problems with podman machine which vanish after reboot. While all OS's have the potential for collision in ports in the dynamic range, Windows is significantly more susceptible to them since it uses a number of them internally for various networking services. Further, they have a non-spec reservation mechanism that system services can use which blocks access to arbitrary port ranges in the dynamic space even when not in use. These registrations do not have standard/fixed addresses, and can be arbitrarily relocated (e.g. after a windows update) so can not be predetermined/avoided.
Since there is only 16K ports in the total range, with potentially random assignments > 1K in use (depending on …
> Implement automatic port reassignment on Windows

- pkg/specgen/generate/validate.go
This is a regression for #18052.
When podman ignores the resource limits, `s.ResourceLimits` needs to be nil.
---
e.g., podman creates the container with `--memory-reservation`.
- without `--memory-reservation`
```console
$ podman create --name testcon ubi9
606771d11b196b583259045931a69d461a22ac90bea8ab3dd939b42ff0556464
$ bin/podman inspect testcon --format {{.HostConfig.MemoryReservation}}
0
```
- before
```console
$ podman create --name testcon --memory-reservation 128m ubi9
Resource limits are not supported and ignored on cgroups V1 rootless systems
a8079a60305277b5c650a0b9f4a695a5ae205ebb3b41212900e77ad7965a27eb
$ podman inspect testcon --format {{.HostConfig.MemoryReservation}}
134217728
(expected 0)
```
- after
```console
$ podman create --name testcon …
```
> Ignore the resource limits on cgroups V1 rootless systems

- hack/perf/system-df.sh
The performance issue in #19467 drove me to add a benchmark for system-df to avoid regressing on it in the future.
Comparing current HEAD to v4.6.0 yields
```
/home/vrothberg/containers/podman/bin/podman system df ran
201.47 times faster than /usr/bin/podman system df
```
```release-note
None
```
> [CI:DOCS] hack/perf/system-df.sh: add `df` benchmarks

- .cirrus.yml
- contrib/hello/Containerfile
- contrib/hello/README.md
- contrib/hello/podman_hello_world.c
This reverts commit 7e0130f75cc27ae32d8843a8be8d2588aa2dcee9.
It broke CI, not just on podman but on Buildah too. Buildah bud
tests require the hello subdirectory.
```release-note
None
```
> Revert "Remove `hello` multi-arch image build"

- pkg/domain/infra/abi/play.go
- pkg/systemd/notifyproxy/notifyproxy.go
- test/system/260-sdnotify.bats
Do not close a notifyproxy more than once.  Also polish the backend a
bit to reflect ealier changes from commit 4fa307f.
Fixes: #19715
```release-note
None
```
> kube: notifyproxy: close once

- test/e2e/config_amd64.go
- test/e2e/config_arm64.go
...in hopes of addressing flake #18355
FWIW, I included this in #17831 and have let CI hammer away. Have not seen that flake. That doesn't mean too much, it could just be dumb luck, but even so I think this is low-risk and a good idea.
```release-note
None
```
> e2e tests: use registry:2.8.2 (was 2.8)

- .cirrus.yml
- contrib/hello/README.md
The `contrib/hello` directory is needed for some CI tests here and in
buildah.  Further, the build job that produces images from this
directory are currently broken.  Disable the build job, and updte
the README.md to point people at the replacement repo. for this content.
Ref: https://github.com/containers/podman/pull/19730
```release-note
None
```
> Cirrus: Disable only hello multiarch build

- pkg/machine/wsl/machine.go
- pkg/machine/wsl/usermodenet.go
Resolves #15190
Registers a rootless and rootful socket underneath /mnt/wsl/podman-sockets/[machine name]/ This allows podman remote clients on other Linux distributions to access podman.
This also registers the podman root socket under the wheel group, to allow for rootful linking against /var/run/docker.sock, a use case expected by some clients and APIs. While this is not recommended practice on a Linux host, a WSL guest is user-isolated and already enables escalation trivially.
```release-note
Registers shared socket bindings on Windows, to allow other WSL distributions easy remote access
```
> Share podman sock bindings with other WSL distros

- test/system/260-sdnotify.bats
- test/system/helpers.bash
Unexplained infrequent flakes in sdnotify system tests,
waiting for READY=1.
Hypothesis: race condition between the container sending
the READY string and that string making it through conmon
and socat into the log file.
Solution: don't just check once; keep trying in a loop.
Write a reusable wait_for_file_content() helper function,
and clean up a bunch more tests as long as we're at it.
Fixes: #19724
```release-note
None
```
> system tests: try to fix sdnotify flakes

- pkg/api/handlers/compat/containers_create.go
- pkg/domain/infra/abi/play.go
- test/apiv2/20-containers.at
- test/system/700-play.bats
Currently containers created via DOCKER API without specifying
StopTimeout are defaulting to 0 seconds. This change should
default them to setting in containers.conf normally 10 seconds.
Fixes: https://github.com/containers/podman/issues/19139
Set StopTimeout for service-container started under podman kube play
Fixes: https://github.com/containers/podman/issues/19139
Service containers are defaulting to 0 seconds for Timeout rather then
the settings in containers.conf.
```release-note
Containers created via compat API default to 10 seconds or containers.conf setting.
```
> Set StopTimeout for compat API if not set by client

- libpod/container_internal_common.go
- libpod/oci_conmon_exec_common.go
- test/system/075-exec.bats
Fixes: https://github.com/containers/podman/issues/19713
```release-note
Podman exec has the same umask as the container it is execing into.
```
> podman exec should set umask to match container

- pkg/machine/applehv/config.go
- pkg/machine/applehv/machine.go
- pkg/machine/config.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/fcos.go
- pkg/machine/fcos_test.go
- pkg/machine/hyperv/config.go
- pkg/machine/pull.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/config.go
As promised in #19596, this pr deduplicates and refactors image acquisition.  All virt providers that use FCOS as its default now use the same code.
```release-note
None
```
> Dedup and refactor image acquisition

- docs/source/markdown/podman-kube-generate.1.md
- docs/source/markdown/podman-kube-play.1.md.in
- libpod/define/annotations.go
- libpod/kube.go
- pkg/bindings/kube/types.go
- pkg/domain/infra/abi/play.go
- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
Add io.podman.annotations.infra.name annotation to kube play so
users can set the name of the infra container created.
When a pod is created with --infra-name set, the generated
kube yaml will have an infraName annotation set that will
be used when playing the generated yaml with podman.
Fixes https://github.com/containers/podman/issues/18312
```release-note
Set an infra name annotation in the generated yaml when the `pod create` command has --infra-name set.
This annotation can also be used with `kube play` when wanting to customize the infra container name.
```
> Add infra-name annotations to kube gen/play

- .packit.yaml
- plans/cockpit-podman.fmf
Please see the two individual commit messages for details. This will robustify the test against [unrelated non-fatal unexpected message checks](https://artifacts.dev.testing-farm.io/faf29d9a-0219-47fb-bef4-6d2a151de209/), seen in https://github.com/containers/podman/pull/19741.
```release-note
None
```
> [CI:BUILD] Packit: Adjustments for Cockpit reverse-dependency check

- docs/kubernetes_support.md
Added support for `security.Context.sysctls.name` and `security.Context.sysctls.value` fields in `v4.6`, documentation updated accordingly
See also: #16711, #17464
Commit: f9af496 "[FEAT] Support sysctl configurations from Pod Spec"
```release-note
None
```
> [CI:DOCS] Updated docs to reflect pod spec sysctls support added in v4.6

- docs/source/markdown/podman-machine-inspect.1.md
- pkg/machine/applehv/machine.go
- pkg/machine/config.go
- pkg/machine/e2e/config_init_test.go
- pkg/machine/e2e/config_set_test.go
- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/set_test.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
- pkg/machine/wsl/machine.go
Podman machine inspect now shows if the machine is rootful
Init/Set with --rootful
Init/Set  with --user-mode-networking
```release-note
None
```
> Update machine init and set tests

- pkg/domain/entities/volumes.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/abi/secrets.go
- pkg/domain/infra/abi/volumes.go
- test/e2e/play_kube_test.go
Make sure that `kube down` and `kube play --replace` do not error out when an object does not exist (or has already been removed).  Such kind of teardown should not be treated as an ordinary `rm` but as an `rm --ignore`.  It's purpose it to make sure that all objects in a YAML are removed; even if they existed only partially.
Fixes: #19711
```release-note
Fix a bug where `kube down` would error when an object did not exist.
```
> kube down/play --replace: handle absent objects

- libpod/oci_conmon_common.go
when the "kill" command fails, print the stderr from the OCI runtime only after we check the container state.
It also simplifies the code since we don't have to hard code the error messages we want to ignore.
Closes: https://github.com/containers/podman/issues/18452
[NO NEW TESTS NEEDED] it fixes a flake.
```release-note
None
```
> oci: print stderr only after checking state

- cmd/podman/images/push.go
- cmd/podman/manifest/push.go
- docs/source/markdown/options/force-compression.md
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
- pkg/api/handlers/libpod/images_push.go
- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_images.go
- pkg/api/server/register_manifest.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_push_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/images.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
- test/e2e/push_test.go
Adds support for --force-compression which allows end-users to force
push blobs with the selected compression in --compression option, in
order to make sure that blobs of other compression on registry are not
reused.
Is equivalent to: force-compression here: https://docs.docker.com/build/exporters/#compression
Closes: https://github.com/containers/podman/issues/18660
Similar to Buildah's: https://github.com/containers/buildah/pull/4973
```release-note
push/manifest-push: add support for `--force-compression` to prevent reusing other blobs
```
> push/manifest-push: add support for `--force-compression` to prevent reusing other blobs

- test/e2e/play_build_test.go
The usual bug that we always seem to forget about: "kube play"
needs "podman wait" before we can "podman logs". (And, reminder,
"kube play --wait" is worthless because it destroys containers).
Reference: #18074, the original PR that fixed a bunch of these flakes.
```release-note
None
```
> e2e: fix race condition (kube play + logs)

- pkg/domain/infra/abi/play.go
- pkg/domain/infra/abi/play_test.go
- pkg/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- test/e2e/play_kube_test.go
Flatten List into documents
Add List type to meta/v1
Add unittest
Yes
```release-note
Kube - add support for List kind
```
Resolves: #19052
> Kube - support List documents

- pkg/bindings/containers/attach.go
In `pkg/bindings/containers/ResizeExecTTY`, `sessionID` is the actual required parameter, instead of `nameOrId`.
```release-note
None
```
> Rename parameter in pkg/bindings

- pkg/api/handlers/compat/images.go
- pkg/api/handlers/types.go
`pkg/api/handlers` is used for type definitions by `pkg/bindings`, i.e. `podman-remote`; a `libimage` dependency means that `podman-remote` would also include `libimage`.
Instead, move the `ImageDataToImageInspect` function close to the only user (and make it private).
[NO NEW TESTS NEEDED]: Only moves unchanged code, should not change behavior.
This is a part of #19718 .
```release-note
None
```
> Remove a dependency on libimage from pkg/api/handlers

- pkg/specgen/generate/container.go
`getImageFromSpec` has just make exactly the same Inspect call.
[NO NEW TESTS NEEDED]: This adds no new functionality, and it's hard to test that a duplicate call didn't happen without (intrusive and hard-to-maintain) mocks.
This is a part of #19718 .
```release-note
None
```
> Don't re-inspect an image

- .cirrus.yml
- contrib/cirrus/CIModes.md
- contrib/cirrus/cirrus_yaml_test.py
These jobs have been failing since early August due to technical/scripting problems.  Disable/remove entirely since a fix is unlikely to be implemented anytime soon.
Ref: https://github.com/containers/podman/pull/19720 - I gave up trying to debug it.
```release-note
None
```
> Cirrus: Remove multi-arch podman image builds

- pkg/api/handlers/compat/ping.go
- test/apiv2/01-basic.at
The docker client expects to read the OSType header from the `/_ping` response in order to determine the OS type of the server, for example, when running `docker run --device=/dev/fuse ...`
https://github.com/moby/moby/blob/master/client/ping.go#L57
This addresses https://github.com/containers/podman/issues/19767
```release-note
None
```
> /_ping handler: return OSType http header

- go.mod
- go.sum
- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/manifests.go
- test/e2e/manifest_test.go
- vendor/github.com/containers/common/libimage/define/manifests.go
- vendor/github.com/containers/common/libimage/image.go
- vendor/github.com/containers/common/libimage/manifest_list.go
- vendor/modules.txt
`libimage.ManifestList{Descriptor,Data}` are (for better or worse) a part of Podman's API, so `podman-remote` needs to include the subpackage that defines them - which is all of `libimage` (and `c/image/v5/copy`) right now.
Instead, https://github.com/containers/common/pull/1629 moves them to libimage/define; this is an update + test for that change.
Alternatively, maybe Podman's API should not directly depend on (unstable) c/common types?! This PR just makes a mechanical change without considering that design question.
[NO NEW TESTS NEEDED]: Only moves unchanged code, should not change behavior.
This is a part of #19718 .
```release-note
None
```
> Update c/common to remove a dependency on libimage

- troubleshooting.md
> [CI:DOCS] Added an additional troubleshooting problem and solution

- pkg/machine/hyperv/machine.go
> Small fixes for hyperv

- cmd/podman/manifest/push.go
- test/e2e/manifest_test.go
Use `add_compression` field from `containers.conf` if found instead and `CLI` field `--add-compression` is not set.
```release-note
manifest,push: support add_compression from containers.conf
```
> manifest,push: support `add_compression` from `containers.conf`

- go.mod
- go.sum
- test/e2e/load_test.go
- test/e2e/pull_test.go
- vendor/github.com/containers/common/libimage/pull.go
- vendor/modules.txt
When pulling from an OCI source, make sure to preseve the optional name. 
For instance, a podman pull oci:/tmp/foo:quay.io/foo/bar:latest should   
pull the image and name it quay.io/foo/bar:latest.                       
While at it, also fix a bug when pulling an OCI without the optional     
name. Previously, we used the path to name the image which will error in 
most cases due to invalid characters (e.g., capital ones). Hence, apply  
the same trick as for the dir transport and generate a sha.              
```release-note
Pulling from an `oci` transport will use the optional name for naming the image.
```
> vendor containers/common@12405381ff45

- docs/source/markdown/options/uidmap.container.md
Since we do not want the mapping to be applied to uids, we should use the `g` flag in the mapping in the example as well. The main text (line 179) already includes the `g` flag, but I forgot to add it to the example.
Follow up of #18173
@giuseppe @TomSweeneyRedHat would you please mind a quick review?
```release-note
None
```
> [CI:DOCS] Fix gidmap command in example

- test/system/030-run.bats
- test/system/060-mount.bats
- test/system/170-run-userns.bats
- test/system/260-sdnotify.bats
- test/system/700-play.bats
Fix unquoted string vars. Something like this:
is $output "what we expect"
...will fail with a misleading error message if $output is "".
Also:
- ~~remove skip for #19407 (tar on rawhide, fixed)~~ EDIT: nope, our CI images still have broken tar
- fix typos in a diagnostic, which was causing unhelpful message
on failure
```release-note
None
```
> system tests: housekeeping: various small fixes

- go.mod
- go.sum
- pkg/machine/gvproxy.go
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
- vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
- vendor/modules.txt
Small fixes for bugs in the hyperv code that were made obvious when manually preparing to run pkg/machine/e2e with windows and hyperv.
Also includes vendoring a new libhvee and solves bug where json config was not being removed.
```release-note
None
```
> Tweaks and cleanups to prepare hyperv for CI

- test/e2e/config_amd64.go
- test/e2e/config_arm64.go
- test/e2e/config_ppc64le.go
- test/e2e/images_test.go
- test/e2e/play_build_test.go
- test/utils/matchers.go
e2e test logs are full of warning messages that we never see. Let's start looking for them.
This PR introduces a new gomega matcher, `ExitCleanly()`, with the purpose of replacing `Should(Exit(0))`. This matcher checks exit code _and_ that no unexpected messages are emitted on stderr. Checking stdout is still up to the test writer.
As proof of concept, use the new matcher in `play_build_test.go`. This resulted in tests failing, because all those `kube play` commands have been spitting out warnings for lo all these years:
time=.... level=warning msg="HEALTHCHECK is not supported for OCI image format and will be ignored. Must use `docker` format"
To remove that warning, use our standard system-test `libpod/testimage:YYYYMMDD` image instead of `alpine_nginx`. Image is now fetched and cached …
> e2e: new ExitCleanly matcher

- libpod/container_internal_common.go
- test/system/030-run.bats
fix the parsing of --hostuser to treat the input in base 10.
Closes: https://github.com/containers/podman/issues/19800
```release-note
Now --hostuser correctly parse the user id in base 10, not in base 8
```
> libpod: do not parse --hostuser in base 8

- .cirrus.yml
- .github/workflows/fcos-podman-next-build.yml
- .packit.sh
- .packit.yaml
- contrib/cirrus/runner.sh
- contrib/cirrus/setup_environment.sh
- contrib/podman-next/fcos-podmanimage/Containerfile
> [CI:BUILD] Podman FCOS image from main

- README.md
In README, a link from text "OCI Hooks Support" is broken, since the destination `pkg/hooks/README.md` has been moved to a separate project.
This PR just provides a fix to that issue.
```release-note
None
```
> [CI:DOCS] Fix a broken link in README

- cmd/podman/system/connection/remove.go
```release-note
None
```
From the Go specification:
> "3. If the map is nil, the number of iterations is 0." https://go.dev/ref/spec#For_range
Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/xzuA7WNrkF4
> Remove redundant nil checks in system connection remove

- docs/source/markdown/options/oom-score-adj.md
- pkg/specgen/generate/oci_linux.go
- test/system/030-run.bats
when running rootless, if the specified oom_score_adj for the container process is lower than the current value, clamp it to the current value and print a warning.
Closes: https://github.com/containers/podman/issues/19829
```release-note
When running rootless, if the oom-score-adj value is too low, then it is clamped to the current value
```
> linux, rootless: clamp oom_score_adj if it is too low

- pkg/machine/ignition.go
increase the number of inotify instances to 524288 instead of using the default value of 128.
Closes: https://github.com/containers/podman/issues/19848
```release-note
The limit of inotify instances was bumped to 524288 for the podman machine
```
> machine: increase max number of inotify instances

- test/system/012-manifest.bats
Primarily, build test images FROM scratch, not alpine, to
avoid image pulls and network flakes and potential pull-
the-rug-out errors if the base alpine image changes.
This was much more complicated than it should've been,
because creating unique arch-specific FROM-scratch images
triggered a weird manifest bug, filed as #19860.
Also:
- add a teardown() to clean up manifests
- remove test for skopeo (skopeo is required for sys tests)
- remove unnecessary intermediate tmpdir
- deduplicate, by looping over amd+arm
- fix indentation
- and, finally, clean up dangling images (this was the initial
reason behind my diving in here. Such a simple thing, I thought.)
```release-note
None
```
> systests: manifest zstd test: lots of tiny cleanups

- libpod/runtime_ctr.go
When removing a container's dependency, getting an error that the container has already been removed (ErrNoSuchCtr and ErrCtrRemoved) should not be fatal. We wanted the container gone, it's gone, no need to error out.
[NO NEW TESTS NEEDED] This is a race and thus hard to test for.
Fixes #18874
```release-note
Fixed a bug where `podman rm -af` could fail to remove containers under some circumstances ([#18874](https://github.com/containers/podman/issues/18874)).
```
> Ignore spurious container-removal errors

- pkg/machine/fcos_test.go
Allows tests to pass on i386 again
```release-note
None
```
> Restrict fcos_test to amd64, arm64

- cmd/podman/system/reset.go
- docs/source/markdown/podman-system-reset.1.md
Backport of commit 6aaf6a28435c.
system reset it says it will delete containers, images, networks, etc... However it will also delete the graphRoot and runRoot directories. Normally this is not an issue, however in same cases these directories were set to the users home directory or some other important system directory.
As first step simply show the directories that are configured and thus will be deleted by reset. As future step we could implement some safeguard will will not delete some known important directories however I tried to keep it simple for now.
see #18349, #18295, and #19870
```release-note
Show the graphRoot and runRoot directories when running podman system reset before we ask for confirmation as these directories will be deleted.
```
> [v3.4] system reset: show graphRoot/runRoot before removal

- cmd/podman/system/reset.go
- docs/source/markdown/podman-system-reset.1.md
```release-note
Show the graphRoot and runRoot directories when running podman system reset before we ask for confirmation as these directories will be deleted.
```
> [v4.4] system reset: show graphRoot/runRoot before removal

- cmd/podman/system/reset.go
- docs/source/markdown/podman-system-reset.1.md
Backport of commit 6aaf6a28435c.
system reset it says it will delete containers, images, networks, etc... However it will also delete the graphRoot and runRoot directories. Normally this is not an issue, however in same cases these directories were set to the users home directory or some other important system directory.
As first step simply show the directories that are configured and thus will be deleted by reset. As future step we could implement some safeguard will will not delete some known important directories however I tried to keep it simple for now.
see #18349 and #18295
```release-note
Show the graphRoot and runRoot directories when running podman system reset before we ask for confirmation as these directories will be deleted.
```
> [v4.3] system reset: show graphRoot/runRoot before removal

- pkg/specgen/generate/security_linux.go
- test/e2e/run_security_labels_test.go
allow the image to specify an empty list of capabilities, currently podman chokes when the io.containers.capabilities specified in an image does not contain at least one capability.
```release-note
Now the io.containers.capabilities LABEL in an image can be an empty string
```
> security: accept empty capabilities list

- docs/source/Introduction.rst
Fixes: https://github.com/containers/podman/issues/18910
```release-note
None
```
> [CI:DOCS] Some distros do not default to docker.io for shortname searches

- test/e2e/attach_test.go
- test/e2e/build_test.go
Small steps toward RUN-1907: replace Exit(0) with ExitCleanly()
in ginkgo tests in two test files. Also, when practical,
replace ALPINE with CITEST_IMAGE.
There are still many thousands of instances left to fix. I will
be submitting in reviewable chunks.
```release-note
None
```
> e2e: use ExitCleanly() in attach & build tests

- pkg/specgen/generate/storage.go
- test/system/700-play.bats
The logic here makes little sense, basically the /tmp and /var/tmp are always set noexec, while /run is not.  I don't see a reason to set any of the three noexec by default.
Fixes: https://github.com/containers/podman/issues/19886
```release-note
/tmp and /var/tmp inside of a podman kube play will no longer be `noexec`
```
> Tmpfs should not be mounted noexec

- libpod/container_api.go
- libpod/container_inspect.go
- libpod/define/container_inspect.go
- test/system/130-kill.bats
Also add a new `StoppedByUser` field to the container-inspect state which can be useful during debugging and is now also used in the regression test.  Note that I moved the `false` check one test above such that we can compare the previous Podman version which should just be stuck in the `wait $ctr` command since it will continue restarting.
```release-note
Do not restart containers after a `podman kill`.
```
Discovered while debugging https://github.com/containers/podman/issues/19815.
> podman: don't restart after kill

- test/upgrade/test-upgrade.bats
PR #19878 (checking for warnings in system tests) broke upgrade tests.
Reason: my long-ago "optimization" in which, if a PR touches only
tests in X, do not run tests in Y. Unfortunately, upgrade tests
rely on code in the system-test directory. I don't know if this
is fixable; nor if it's an acceptable tradeoff. Please discuss.
Sorry, everyone.
```release-note
None
```
> URGENT: fix broken CI

- libpod/oci_conmon_common.go
- test/system/030-run.bats
- test/upgrade/test-upgrade.bats
Under some circumstances podman tries to kill a container
using signal 37, for which unix.SignalName() returns "".
Not helpful. So, when that happens, show "(signal number)".
```release-note
None
```
> StopContainer: display signal num when name unknown

- docs/kubernetes_support.md
- libpod/container_inspect.go
- libpod/kube.go
- pkg/specgen/generate/kube/kube.go
- test/system/710-kube.bats
Fixes: https://github.com/containers/podman/issues/19881
```release-note
Podman kube play/generate now support     securityContext:      procMount: Unmasked
```
> Add support for kube  securityContext.procMount

- docs/tutorials/podman_tutorial.md
Remove the use of the "latest" flags because it cannot be used on windows or mac.
Fixes #17019
```release-note
None
```
> [CI:DOCS]Remove use of --latest|-l from tutorial

- test/e2e/checkpoint_image_test.go
- test/e2e/checkpoint_test.go
- test/utils/matchers.go
Clean command-line replace, with one manual reversion (commented)
```release-note
None
```
> e2e: use ExitCleanly() in checkpoint tests

- cmd/podman/pods/create.go
- test/system/200-pod.bats
If some volumes are specified in containers.conf, they are currently added twice to the containers spec causing the container to fail:
$ head -n2 ~/.config/containers/containers.conf
[containers]
volumes = ["/tmp:/tmp"]
$ podman pod create --name foo
7ac7f97f9b74a596332483e4a13e58cb9c8d997e9c5baae46804ae0acc26cbc6 $ podman run --pod=foo alpine true
Error: "/tmp": duplicate mount destination
The fix is to ignore the setting from containers.conf when setting the pod default configuration.
```release-note
running a container in a pod doesn't fail if volumes or mounts are specified in the containers.conf file
```
> pod: fix duplicate volumes from containers.conf

- cmd/podman/containers/run.go
- test/system/030-run.bats
- test/upgrade/test-upgrade.bats
When the "rmi" part of "run --rmi" fails due to image being in use
by another container (or for any reason, actually), issue a warning
message, not an error.
```release-note
None
```
> run --rmi: "cannot remove" is a warning, not an error

- .cirrus.yml
- contrib/cirrus/runner.sh
Split up the alt binaries build to better parallelize CI. Previously this section was taking 35-40 mins. After this change, it's a little under 10 mins. 
```release-note
none
```
> Split up alt binaries to speed up build

- cmd/podman/pods/create.go
- libpod/container_internal.go
- libpod/pod.go
- libpod/pod_api.go
- libpod/runtime_pod_common.go
- libpod/runtime_pod_freebsd.go
- libpod/runtime_pod_linux.go
- libpod/util_linux.go
- pkg/specgen/generate/pod_create.go
- test/system/200-pod.bats
- utils/utils_supported.go
while investigating 19175, I've found a bunch of issues with the way we handle the pod cgroup:
- The pod cgroup was not honoring the cgroup limits after a reboot
- The cgroup once created was leaked, even if the pod is stopped
- --infra=false was not creating any pod cgroup, and all the limits were ignored.
More details in the individual commits.  There is some space for improvements, e.g. not trying to guess the systemd path but we would need to fix it in c/common first, we can do this incrementally later.
Closes: https://github.com/containers/podman/issues/19175
```release-note
Now pod cgroup limits are honored after a reboot
```
> fix pod cgroup lifecycle

- libpod/container_internal_common.go
- pkg/specgen/generate/oci_linux.go
- test/e2e/run_test.go
commit 8b4a79a744ac3fd176ca4dc0e3ae40f75159e090 introduced oom_score_adj clamping when the container oom_score_adj value is lower than the current one in a rootless environment.  Move the check to init() time so it is performed every time the container starts and not only when it is created.  It is more robust if the oom_score_adj value is changed for the current user session.
```release-note
None
```
> libpod: move oom_score_adj clamp to init

- docs/kubernetes_support.md
- libpod/kube.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/kube.go
- test/e2e/generate_kube_test.go
- test/e2e/play_kube_test.go
Add support to kube play to support the TerminationGracePeriodSeconds fiels by sending the value of that to podman's stopTimeout. Add support to kube generate to generate TerminationGracePeriodSeconds if stopTimeout is set for a container (will ignore podman's default).
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2218061
```release-note
Add support to kube gen and play for k8s `TerminationGracePeriodSeconds`.
```
> Add support for kube TerminationGracePeriodSeconds

- test/e2e/container_clone_test.go
Clean command-line replace, with manual tweaks to two tests:
* clone to a pod: revert to just Exit(0), because podman issues
a namespace warning
* --destroy --force : run "top" in container, not default (shell),
to avoid the 10-second SIGKILL fallback warning
```release-note
None
```
> e2e: container_clone_test.go: use ExitCleanly()

- libpod/container_exec.go
- libpod/healthcheck.go
- test/e2e/healthcheck_run_test.go
HC events were firing as part of the `exec` call, before it had even been decided whether the HC succeeded or failed. As such, the status was not going to be correct any time there was a change (e.g. the first event after a container went healthy to unhealthy would still read healthy). Move the event into the actual Healthcheck function and throw it in a defer to make sure it happens at the very end, after logs are written.
Ignores several conditions that did not log previously (container in question does not have a healthcheck, or an internal failure that should not really happen).
Still not a perfect solution. This relies on the HC log being written, when instead we could just get the status straight from the function writing the event - so if we fail to write the log, we can still …
> Ensure HC events fire after logs are written

- test/e2e/cleanup_test.go
- test/utils/matchers.go
Clean command-line replace.
Also, fix up the Containerized and Debian exceptions in matcher.
I was in a huge rush Thursday night when I added the Debian
exception. This, I hope, makes it slightly easier to understand
the cases where we don't check stderr.
```release-note
None
```
> e2e: use ExitCleanly() in cleanup_test.go

- cmd/podman/main.go
- docs/source/markdown/podmansh.1.md
podmansh_timeout is now a configurable option in containers.conf.
```release-note
Podmansh timeout is now configurable using the `podmansh_timeout` option in containers.conf
```
> Podmansh: use podmansh_timeout

- test/e2e/container_create_volume_test.go
- test/e2e/container_inspect_test.go
- test/e2e/containers_conf_test.go
- test/e2e/cp_test.go
- test/e2e/create_staticip_test.go
- test/e2e/create_staticmac_test.go
A handful of test files with trivial command-line replacement,
and no manual muckery (aside from includes).
```release-note
None
```
> e2e: more ExitCleanly(): low-hanging fruit

- docs/source/markdown/podman-init.1.md.in
`podman init` is a debugging command for inspecting a container's OCI spec before it runs, to look for anything suspicious. It is not capable of supporting modifications to that spec, as it starts Conmon and thus the OCI runtime, so the spec has already been loaded by the time `podman init` is run.
```release-note
NONE
```
> [CI:DOCS] The `podman init` command cannot modify containers.

- cmd/podman/farm/remove.go
- contrib/cirrus/setup_environment.sh
- test/e2e/events_test.go
- test/e2e/exec_test.go
- test/e2e/farm_test.go
- test/e2e/generate_spec_test.go
- test/e2e/healthcheck_run_test.go
- test/e2e/history_test.go
- test/e2e/image_scp_test.go
- test/e2e/image_sign_test.go
- test/e2e/images_test.go
- test/e2e/import_test.go
- test/e2e/info_test.go
Trying a different approach. Instead of one-file-at-a-time, do a bunch of test files, but in two commits: one a simple string substitution of `Expect...Exit(0)` to `...ExitCleanly()`, and the second being manual fixes. The second commit is the important one to review.
```release-note
None
```
> e2e: more ExitCleanly() on more test files

- test/e2e/diff_test.go
One manual fix: adding -q to podman commit, to avoid progress messages
```release-note
None
```
> e2e: diff_test: use ExitCleanly()

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/pids-limit.container
QM needs to be able to specify the maximum number of PIDs within the QM environment to ensure FFI.
Picking a total of 10,000 Pids might be a rasonable constraint on the QM.
```release-note
Quadlet now supports seeing the PidsLimit option in a container.
```
> Add support for PidsLimit in quadlet

- docs/source/markdown/options/restart.md
The command `podman generate systemd` is deprecated since this PR:
* https://github.com/containers/podman/pull/19414
Rewrite _restart.md_ to refer to container units instead.
Fixes: https://github.com/containers/podman/issues/19968
```release-note
None
```
> [CI:DOCS] restart.md: migrate to container unit

- docs/source/markdown/options/ulimit.md
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/ulimit.container
QM needs to be able to specify the maximum number of open files within the QM environment to ensure FFI.
```release-note
Podman quadlet now supports setting Ulimit values.
```
> Add support for Ulimit in quadlet

- cmd/podman/common/completion.go
Also sorted all of the options in alphabetic order.
Fixes: https://github.com/containers/podman/issues/19967
```release-note
None
```
> Add --filter pod= autocompletion

- cmd/podman/compose.go
- cmd/podman/machine/info.go
- cmd/podman/machine/init.go
- cmd/podman/machine/inspect.go
- cmd/podman/machine/list.go
- cmd/podman/machine/machine.go
- cmd/podman/machine/os/manager.go
- cmd/podman/machine/rm.go
- cmd/podman/machine/set.go
- cmd/podman/machine/ssh.go
- cmd/podman/machine/start.go
- cmd/podman/machine/stop.go
- cmd/podman/system/reset_machine.go
- pkg/machine/e2e/README.md
- pkg/machine/e2e/config_linux_test.go
- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/config_windows_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/provider/platform.go
- pkg/machine/provider/platform_darwin.go
- pkg/machine/provider/platform_windows.go
this pr has the basic plumbing that allows the e2e machine tests to run with the hyperv provider.
it requires a special fcos image right now because gvforwarder was not in the upstream fcos images for hyperv.
```release-note
None
```
> Plumbing to run machine tests with hyperv

- pkg/machine/wsl/machine.go
When passing the force flag to machine rm, wsl needs to stop the VM if it is running before attempting to remove it.
```release-note
None
```
> Add ability for machine rm -f for WSL

- cmd/podman/common/completion.go
- docs/source/markdown/podman-events.1.md
- docs/source/markdown/podman-pause.1.md.in
- docs/source/markdown/podman-ps.1.md
- docs/source/markdown/podman-restart.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-start.1.md.in
- docs/source/markdown/podman-stop.1.md.in
- docs/source/markdown/podman-unpause.1.md.in
- docs/source/markdown/podman-volume-prune.1.md
- hack/xref-helpmsgs-manpages
For all commands with a --filter option, cross-reference
against man pages, and vice-versa.
I'm sorry. I know this script has gone off the deep end.
```release-note
None
```
> man page crossrefs: add --filter autocompletes

- docs/source/markdown/podman-container-prune.1.md
- docs/source/markdown/podman-image-prune.1.md
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-network-prune.1.md
- docs/source/markdown/podman-pod-ps.1.md.in
- docs/source/markdown/podman-system-prune.1.md
- docs/source/markdown/podman-volume-prune.1.md
- hack/xref-helpmsgs-manpages
Some --filter descriptions listed the filters with asterisks,
i.e. markdown italics. There were 60+ of those, 250+ without
asterisks, so I choose to de-asterisk them all. Update the
xref script to remove the allow-asterisk exception. (Except
for the column title, which is sometimes written with two
asterisks--boldface--and sometimes plain).
```release-note
None
```
> [CI:DOCS] consistentize filter options in man pages

- Makefile
- cmd/podman/registry/registry.go
- cmd/podman/system/service.go
- cmd/podman/system/service_abi.go
- hack/podman-socat
- test/e2e/common_test.go
- test/system/251-system-service.bats
Shortcuts like `unix:path` and `unix:/path` do not work everywhere,
so make sure to use `unix://path` when quoting the url (or address)
This avoids errors such as: (when trying to use it as the `DOCKER_HOST`)
`error during connect: Get "http://unix:2375/run/user/1000/podman/podman.sock/v1.24/version": dial tcp: lookup unix: no such host`
```release-note
None
```
Help before:
```
--url string                URL to access Podman service (CONTAINER_HOST) (default "unix:/run/user/1000/podman/podman.sock")
```
Help after:
```
--url string                URL to access Podman service (CONTAINER_HOST) (default "unix:///run/user/1000/podman/podman.sock")
```
> Use url with scheme and path for the unix address

- cmd/podman/registry/config.go
- cmd/podman/root.go
- docs/source/markdown/podman.1.md
- test/system/800-config.bats
The --module can only be parsed on the root level.  It cannot work on the command level, because it must be "manually" parsed on init() to make sure the specified configuration files/modules are loaded prior to parsing the flags via Cobra.
Hence move --module from the "persistent" to the "local" flags which will yield an error instead of doing nothing when being specified on the command level:
```
$ ./bin/podman run --module=foo.conf --rm alpine
Error: unknown flag: --module
See 'podman run --help'
```
Reported in #20000.
```release-note
None
```
Set release not to none as it'll go into 4.7 which ships the --module flag first.
> error when --module is specified on the command level

- RELEASE_PROCESS.md
Also includes:
- typo fixes
- links to maling lists and gh cli tool
```release-note
None
```
> [CI:DOCS] Include precheck to release process

- cmd/podman/common/create.go
- test/system/800-config.bats
As found while working on #20000, the `--env-host` flag should use the default from containers.conf.  Add a new "supported fields" test to the system tests to make sure we have a goto test for catching such regressions.  I suspect more flags to not use the defaults from containers.conf.
```release-note
The default value of --env-host can now be configured via containers.conf.
```
> --env-host: use default from containers.conf

- go.mod
- go.sum
- pkg/machine/applehv/machine.go
- pkg/machine/hyperv/machine.go
- pkg/machine/qemu/machine.go
- vendor/github.com/containers/gvisor-tap-vsock/LICENSE
- vendor/github.com/containers/gvisor-tap-vsock/pkg/types/configuration.go
- vendor/github.com/containers/gvisor-tap-vsock/pkg/types/gvproxy_command.go
- vendor/github.com/containers/gvisor-tap-vsock/pkg/types/handshake.go
- vendor/github.com/containers/gvisor-tap-vsock/pkg/types/paths.go
- vendor/modules.txt
Converts the host networking code in `podman machine` to use the `Command` type introduced in https://github.com/containers/gvisor-tap-vsock/pull/258
```release-note
None
```
> Implement gvproxy networking using cmdline wrapper

- docs/source/markdown/options/sig-proxy.md
Also, we don't proxy SIGURG (Golang uses it internally for waking threads, so Go processes get it constantly (see [1] for more details).
[1] https://github.com/golang/go/issues/37942
```release-note
NONE
```
> [CI:DOCS] Docs on sig-proxy are wrong, we support TTY

- docs/source/markdown/podman-farm-create.1.md
- docs/source/markdown/podman-farm.1.md
While doing a review of the farm man pages after they had been submitted, I found a few references to "podman" that should have been "Podman".  I have touched those up in this commit.
```release-note
None
```
> [CI:DOCS] Tweak podman to Podman in a few farm man pages

- .github/workflows/discussion_lock.yml
The closed issue & PR lock is working fine, but it has a built-in 50-item limit.  The limit is not configurable.  Since there are tens-of-thousands of issues/prs to go through, 50-per-day could take almost a year.  Speed things up 24x by running the job every hour instead of daily.
N/B: There's no easy way to test this change.  It won't be in effect until it exists on main.  
```release-note
None
```
> [skip-ci] GHA Workflow: Faster discussion-locking

- test/system/001-basic.bats
- test/system/010-images.bats
- test/system/030-run.bats
- test/system/045-start.bats
- test/system/050-stop.bats
- test/system/250-systemd.bats
- test/system/330-corrupt-images.bats
- test/system/450-interactive.bats
- test/system/500-networking.bats
- test/system/helpers.bash
Part of RUN-1906.
Followup to #19878 (check stderr in system tests): allow_warnings()
and require_warning() functions to make sure no unexpected messages
fall through the cracks.
```release-note
None
```
> systests: tighter checks for unwanted warnings

- cmd/podman/root.go
- pkg/domain/infra/runtime_abi.go
- test/system/001-basic.bats
- test/system/272-system-connection.bats
--connection flag couldn't override the active-destination when CONTAINER_HOST env variable was set. As a remedy, the precedence of --connection flag has been changed.
```release-note
For operating Podman remotely, the order of priority is:
1.  cli flags (--connection ,--url ,--context ,--host)
2.  Env variables (CONTAINER_HOST and CONTAINER_CONNECTION)
3.  ActiveService from containers.conf
4.  RemoteURI
```
Closes #15588 
Signed-off-by: Chetan Giradkar <cgiradka@redhat.com>
> Change priority for cli flags for remotely operating Podman

- test/system/255-auto-update.bats
The test started to fail in gating and on workstations.  It turned out that pushing the test image to the registry recompresses it which in turn may change the digest.  The digest now started to change; computing it depends on the toolchain so the test passed before by pure luck it seems.
```release-note
None
```
> fix --authfile auto-update test

- libpod/container.go
- pkg/api/handlers/compat/networks.go
The network list compat API requires us to include all containers with
their ip addresses for the selected networks. Because we have no network
-> container mapping in the db we have to go through all containers
every time. However the old code did it in the most ineffective way
possible, it quered the containers from the db for each individual
network. The of course is extremely expensive. Now the other expensive
call is calling Inspect() on the container each time. Inspect does for
more than we need.
To fix this we fist query containers only once for the API call, then
replace the inspect call with directly accessing the network status.
This will speed things up a lot!
The reported scenario includes 100 containers and 25 networks,
previously it took 1.5s for the API call not it takes …
> compat API: speed up network list

- cmd/podman/root.go
- cmd/podman/syslog_common.go
- cmd/podman/syslog_unsupported.go
- libpod/oci_conmon_common.go
- pkg/domain/entities/engine.go
- pkg/domain/infra/runtime_libpod.go
- test/system/030-run.bats
The --syslog flag has not been passed to the cleanup process (i.e., conmon's exit args) complicating debugging quite a bit.
```release-note
Fix a bug where the `--syslog` flag was not passed to the cleanup process.
```
Found while debugging https://github.com/containers/podman/issues/19938.  I decided to break this out into a separate PR as https://github.com/containers/podman/issues/19938 is slowly turning into a much bigger adventure than I wished.
> pass --syslog to the cleanup process

- pkg/strongunits/config.go
- pkg/strongunits/config_test.go
podman could benefit from stronger typing with some of our methods and functions where uint64s, for example, are used because the unit of measurement is unknown.  Also, the need to convert between storage units is critical in podman and this package supports easy conversion as needed.
to start, we implement the storage units (bytes, KiB, MiB, and GiB) only.
```release-note
None
```
> introduce pkg/strongunits

- pkg/machine/hyperv/machine.go
if you use the extra files function on exec commands, windows loses it's mind.
```release-note
None
```
> windows cannot "do" extra files

- pkg/machine/qemu/machine.go
- pkg/machine/qemu/machine_unix.go
- pkg/machine/qemu/machine_windows.go
- winmake.ps1
Makefile equiv Powershell script
Introduce a powershell script that mirrors Makefile capbilities on
Windows.
Syntax: ./winmake target [options]
```release-note
None
```
> Makefile equiv Powershell script

- test/e2e/generate_kube_test.go
Similar to #20065, but simpler. Three commits, and once again the third is the one worth reviewing.
```release-note
None
```
> e2e: ExitCleanly(): generate_kube_test.go

- contrib/podman-next/fcos-podmanimage/Containerfile
This commit installs `crun-wasm` and `wasmedge-rt` in the FCOS image at https://quay.io/repository/podman/fcos .
- crun-wasm is installed from rhcontainerbot/podman-next
- wasmedge-rt is installed from the official Fedora repos
Packages in Containerfile have also been rearranged in alphabetical order.
```release-note
None
```
> [CI:BUILD] FCOS + podman-next image: pull in wasm

- cmd/podman/machine/ssh.go
Small fix, which was missed initially in [PR #19997](https://github.com/containers/podman/pull/19997)
```release-note
None
```
> Use ActiveServiceDestination in ssh remoteConnectionUsername

- rpm/podman.spec
gvisor-tap-vsock is now a standalone package for Fedora 38 and higher so we can simplify the rpm spec a lot by removing all subpackage references.
If we need to bump podman on Fedora 37, that can be handled manually on Fedora itself. The Packit config can be left unchanged. Any packit PRs created on Fedora dist-git for Fedora 37 can simply be closed without merging. Fedora 37 will go EOL soon so not much of a point to changing packit config to exclude Fedora 37.
```release-note
None
```
> [CI:BUILD] rpm: remove gvproxy subpackage

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.container
If you are running a quadlet with anonymous volumes, then the volume will leak ever time you restart the service.  This change will cause the volume to be removed.
Fixes: https://github.com/containers/podman/issues/20070
```release-note
Podman quadlets now remove anonymous volumes
```
> Automatically remove anonymous volumes when removing a container

- test/e2e/config.go
> test: update fedoraMinimal version

- .packit.yaml
> [CI:BUILD] packit: tag @containers/packit-build team on copr build failure

- pkg/machine/config.go
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
some problems were found in machine tests on hyperv.
in the case of rootful, it is currently not implemented.  an issue #20092 has been created for that problem.
there also seems to be a timezone issue between ignition and fcos right now.  inquiries are in for that but no issue generated for that.  this problem is not exclusive to hyperv by any means.
both of the above have been skipped or commented out.
otherwise, this fixes machine state reporting for consistency.
```release-note
None
```
> fixes for pkg/machine/e2e on hyperv

- libpod/runtime_pod_common.go
- test/e2e/play_kube_test.go
This is not really an error, if the anonymous volume is still used then this likely means it was transferred to another container with --volumes-from. This is what the user wants and it is not like the user can act on the logged error anyway. Once the last user of the volume is removed it will be removed correctly.
see https://github.com/containers/podman/pull/19637
```release-note
None
```
> pod rm: do not log error if anonymous volume is still used

- go.mod
- go.sum
- pkg/machine/e2e/init_test.go
- pkg/machine/e2e/set_test.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/modules.txt
Machine cpu default has changed to cpus/2, so adjust the tests to reflect that.
```release-note
The amount of CPUs a podman machine has now defaults to using  available cores/2. https://github.com/containers/podman/issues/17066
```
> Adjust machine CPU tests

- pkg/machine/e2e/init_test.go
- pkg/machine/ignition.go
the timezone was being set with the wrong path separator for hyperv because it was being generated on Windows.
Fixes: coreos/fedora-coreos-tracker#1580
```release-note
None
```
> Fix setting timezone on HyperV

- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
When doing a machine rm -f (force removal of a machine) or a machine reset (force removal of all machines), there is no need to use a "polite/soft" stop.
this will also speed up pkg/machine/e2e tests.
```release-note
None
```
> hyperv: use StopWithForce with remove

- cmd/podman/machine/list.go
- pkg/machine/hyperv/config.go
- pkg/machine/hyperv/machine.go
the window for hyperv's "Starting" state is very narrow; so to more mimic qemu, we follow suit.  starting bools are set when the vm boots and when it communicates back on the read socket.
this allows pkg/machine/init_test.go to pass
[NO NEW TESTS ARE NEEDED]
```release-note
None
```
> hyperv: set more realistic starting state

- test/e2e/load_test.go
- test/e2e/login_logout_test.go
- test/e2e/pull_test.go
- test/e2e/push_test.go
- test/e2e/save_test.go
A few more files. Changes in Commit Two are a bit heavier than usual.
```release-note
None
```
> e2e: ExitCleanly(): a few more

- cmd/podman/common/build.go
- docs/source/markdown/podman-build.1.md.in
- test/system/070-build.bats
The default pull policy is "missing" not "always".
Fixes: #20125
```release-note
Fix a bug in the podman-build man pages and correct the default value of --pull to "missing".
```
> podman build: correct default pull policy

- cmd/podman/root.go
- go.mod
- go.sum
- libpod/oci_conmon_common.go
- libpod/options.go
- libpod/runtime.go
- libpod/sqlite_state.go
- pkg/domain/entities/engine.go
- pkg/domain/infra/runtime_libpod.go
- test/system/030-run.bats
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/modules.txt
The processing and setting of the static and volume directories was scattered across the code base (including c/common) leading to subtle errors that surfaced in #19938.
There were multiple issues that I try to summarize below:
- c/common loaded the graphroot from c/storage to set the defaults for static and volume dir.  That ignored Podman's --root flag and surfaced in #19938 and other bugs.  c/common does not set the defaults anymore which gives Podman the ability to detect when the user/admin configured a custom directory (not empty value).
- When parsing the CLI, Podman (ab)uses containers.conf structures to set the defaults but also to override them in case the user specified a flag.  The --root flag overrode the static dir which is wrong and broke a couple of use cases.  Now there …
> fix handling of static/volume dir

- test/e2e/config.go
- test/e2e/images_test.go
- test/e2e/pod_initcontainers_test.go
PR #20082 bumped fedora-minimal, from f34 to f39. This worked
fine for a few days, then all of a sudden CI started breaking
because the f39 minimal image got rebuilt and repushed without
adduser. #20127 was an emergency fix; this is a stabler fix.
We keep using not-under-our-control container images, and we
keep getting burned when those get updated in nasty ways. Here
we switch to using a tagged & versioned fedora-minimal image
that is under our control.
```release-note
None
```
> e2e: use safe fedora-minimal image

- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/set_test.go
The usermode networking scenario is only for WSL.  Hyperv cannot run it.
```release-note
None
```
> hyperv: machine e2e tests for set command

- .github/workflows/fcos-podman-next-build.yml
`wait-for-copr` is still very flaky and has failed more often than not. Ref: https://github.com/fedora-copr/copr/issues/2819
This change to the fcos GHA will allow nightly builds pulling in whatever packages exist on podman-next at that time without depending on wait-for-copr.
The commit id will still be recorded in podman version as well as the image tag, so auditing is not affected with this change.
```release-note
None
```
> [CI:BUILD] FCOS image: enable nightly build

- pkg/machine/e2e/proxy_test.go
Currently proxys are not supported on hyperV, skip the test and document it for now.
Opened https://github.com/containers/podman/issues/20129 to track the issue.
```release-note
None
```
> Skip proxy test for hyperV

- pkg/machine/e2e/rm_test.go
WSL does not use ignition therefore the test for the file is invalid.
```release-note
None
```
> wsl: machine tests for machine rm

- pkg/machine/wsl/machine.go
the emitted message for starting a machine that is is already started needed to be slightly altered for wsl.
```release-note
None
```
> wsl: machine start test

- pkg/machine/applehv/machine.go
- pkg/machine/e2e/README.md
- pkg/machine/e2e/config_darwin_test.go
- pkg/machine/e2e/config_linux_test.go
- pkg/machine/e2e/config_unix_test.go
This PR allows you to run the pkg/machine/e2e tests for the applehv PROVIDER.  This does not mean they pass, only that they can run.  There also appears to be leftover gvproxy processes at the conclusion of a single test.  This will need to be corrected.
```release-note
None
```
> Enable machine e2e test for applehv

- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/set_test.go
- pkg/machine/wsl/machine.go
wsl does not support changing the disk size, processor number, or memory allocation.
```release-note
None
```
> wsl machine tests: set

- .github/workflows/fcos-podman-next-build.yml
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-contexts
```release-note
None
```
> [skip-ci] [CI:BUILD] FCOS+podman-next: correct GHA conditional syntax

- pkg/machine/e2e/init_test.go
- pkg/machine/hyperv/machine.go
Fixed a bug where the rootful option to the podman machine init command would not be written to to the machine config, and the rootful docker sock would not be set.
Fixes: https://github.com/containers/podman/issues/20092
```release-note
None
```
> hyperV: Respect rootful option on machine init

- pkg/machine/applehv/machine.go
- pkg/machine/e2e/README.md
- pkg/machine/e2e/info_test.go
- pkg/machine/hyperv/machine.go
Add podman socket info to machine inspect
Fix podman machine info test for hyperV 
Update machine tests README 
```release-note
None
```
> hyperv: Fixes for info, inspect tests 

- pkg/machine/applehv/machine.go
leftover debug was breaking -q tests
```release-note
None
```
> applehv: enable machine tests for start

- libpod/oci_conmon_common.go
- libpod/oci_conmon_exec_common.go
- test/system/030-run.bats
Pass the _entire_ environment to conmon instead of selectively enabling only specific variables.  The main reasoning is to make sure that conmon and the podman-cleanup callback process operate in the exact same environment than the initial podman process.  Some configuration files may be passed via environment variables.  Podman not passing those down to conmon has led to subtle and hard to debug issues in the past, so passing all down will avoid such kinds of issues in the future.
```release-note
None
```
> libpod: pass entire environment to conmon

- pkg/machine/applehv/machine.go
- pkg/machine/applehv/rest.go
change behaviour of stopped a stopped/exited machine to match qemu in that stopping a stopped machine is NOT an error.
add condition to machine rm where rm is not run twice due to a logic error
```release-note
None
```
> applehv: machine tests for stop and rm

- contrib/cirrus/lib.sh
- test/README.md
- test/e2e/common_test.go
When you run e2e tests locally they use CNI unless the NETWORK_BACKEND
env was set to netavark. Because our main focus is on netavark we should
test it by default.
For local tests this should help to prevent CNI/netavark conflicts as I
assume most systems where people run tests on are on netavark by now.
For  CI testing we hardcode NETWORK_BACKEND there to test both netavark
(on current fedora) and CNI (prior fedora). MAke sure to switch the
logic in the CI setup to reflect that.
```release-note
None
```
> test/e2e: default to netavark

- Makefile
- winmake.ps1
Winmake file now builds win-sshproxy and gvproxy
```release-note
None
```
> [CI:DOCS] Add win-sshproxy target to winmake

- pkg/machine/e2e/init_test.go
many of wsl's attributes are not as configurable as other providers. small tweaks and conditional tests have been added.
```release-note
None
```
> wsl: enable machine init tests

- cmd/podman/kube/play.go
- docs/source/markdown/podman-kube-play.1.md.in
- pkg/bindings/kube/types.go
- pkg/bindings/kube/types_play_options.go
- pkg/domain/entities/play.go
- pkg/domain/infra/abi/play.go
- pkg/domain/infra/tunnel/kube.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/kube_test.go
- test/e2e/play_kube_test.go
- test/system/700-play.bats
Container ports defined with `containerPort` were exposed by default even though kubernetes interprets them as mostly informative. 
Closes #17028
```release-note
Fixed podman kube play exposing all container ports on host even if only specified as containerPort insteadof hostPort (#17028)
Added new flag --publish-all which allows to restore the old behaviour of "podman kube play" exposing all ports including those only defined as containerPort
```
> Fix all ports exposed on host by kube play

- test/e2e/export_test.go
- test/e2e/quadlet_test.go
- test/e2e/restart_test.go
- test/e2e/run_security_labels_test.go
- test/e2e/search_test.go
- test/e2e/system_connection_test.go
- test/e2e/systemd_activate_test.go
- test/e2e/systemd_test.go
- test/e2e/toolbox_test.go
Final step in RUN-1907. This is the last set of `*_test.go` files to be migrated to using `ExitCleanly()`.
As always, the first commit is long & uninteresting, the second commit is the important one.
```release-note
None
```
> e2e: ExitCleanly(): the final step

- pkg/specgenutil/volumes.go
- pkg/specgenutilexternal/mount.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/mount.container
- test/e2e/quadlet_test.go
Some keys, e.g. ro do not have values.
The current implementation crashed looking for the = sign
Externalize findMountType in a new package
Parse mount command using FindMountType    
Add test case and adjust the test framework
Yes
```release-note
Quadlet container mount - support non key=val options
```
Resolves: #20104
> Quadlet container mount - support non key=val options

- docs/source/markdown/podman-network-create.1.md
This pull request adds documentation for using the VRF option on the Netavark backend (https://github.com/containers/netavark/commit/4b6d5ab26316b007779e0a504ab9a90a21b2e2dc) . 
This depends on this pull request https://github.com/containers/common/pull/1673.
```release-note
Added a new vrf option to `podman network create --opt` for the bridge driver.
```
> [CI:DOCS] Add documentation for the vrf option on Netavark

- cmd/podman/README.md
[NO NEW TESTS NEEDED]  - This pull request only contains some fixes for links, paths, and code examples in the README file in the podman folder inside folder cmd.
None
> [CI:BUILD] fix: typos in links, path and code example

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
- test/e2e/logs_test.go
- test/e2e/stats_test.go
- test/system/505-networking-pasta.bats
...from f38 + f37.
Requires one minor e2e test change, to handle an error logging
change in conmon 2.1.8.
Also, this is important, requires crun-1.9.1 because of a kernel
symlink change; see https://github.com/containers/crun/pull/1309
The VM images here were carefully built to include that. By the
time the next VM images get built, it should be default.
```release-note
None
```
> CI VMs: bump to f39 + f38

- pkg/machine/wsl/machine.go
```release-note
Fixes the detection of systemd in WSL.
Users who use WSL with systemd must recreate their machine to apply this fix.
```
If WSL is configured to use systemd by setting `boot.systemd=true`in `/etc/wsl.conf`, WSL creates a Symlink from `/sbin/init` to `/usr/lib/systemd/systemd` and starts systemd via `/sbin/init`.  
`podman machine start`, `podman machine ssh` and other commands check if systemd is running via [isSystemdRunning()](https://github.com/containers/podman/blob/8a9f778e233a51b1896db80703957ef8f9a9d1c5/pkg/machine/wsl/machine.go#L1375) and fail if it is not detected.  
Because [isSystemdRunning()](https://github.com/containers/podman/blob/8a9f778e233a51b1896db80703957ef8f9a9d1c5/pkg/machine/wsl/machine.go#L1375) incorrectly checks for the command name …
> Fix WSL systemd detection

- cmd/podman/machine/list.go
- pkg/machine/applehv/machine.go
- pkg/machine/e2e/list_test.go
- pkg/machine/qemu/config.go
- pkg/machine/wsl/config.go
After creating a podman machine, and before starting it, the LastUp value for podman machine ls should display Never. Previously, the LastUp value was the same as creation time. This also changes the LastUp value for inspect to ZeroTime instead of creation time.
```release-note
Fixed a bug where the `podman machine ls` command would show Creation time as LastUp time for machines that have never been booted. Now, new machines show `Never`, with the json value being ZeroTime.
```
> New machines should show Never as LastUp

- contrib/pkginstaller/Makefile
This brings DNS improvements/bug fixes, and docker.internal DNS entries.
```release-note
This improves compatibility with container images hardcoding the host.docker.internal or gateway.docker.internal host names with podman-machine on macOS.
```
> Update mac installer to latest gvproxy release

- cmd/podman/containers/create.go
- cmd/podman/containers/rm.go
- test/e2e/run_test.go
```release-note
run --replace prints only the ID for the new container, instead of the ID if the old one was stopped
```
> podman: run --replace prints only the new container id

- docs/source/markdown/podman-machine-init.1.md.in
- pkg/machine/e2e/config_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/ignition.go
As explained in #21022, there are all kinds of downsides to a machine updating itself (via zincati) automatically, like interuption of service, lost mounts, etc.
disabling zincati will at least allow stop these downsides.  we are likely to contemplate if podman will take over the update process externally where interuption of services will not occur etc.
Fixes #20122
```release-note
Disable auto-updates in podman machine vms that use FCOS
```
> podman machine: disable zincati update service

- pkg/machine/applehv/machine.go
- pkg/machine/qemu/machine.go
Removes the `c.ExtraFiles` line in applehv and qemu `machine.go` file. These are remnants from #19723. This lines was written to add stdin, stdout, stderr as extra files, but that is not how `c.ExtraFiles` works (unlike `os.ProcAttr`).
go source: https://cs.opensource.google/go/go/+/go1.21.1:src/os/exec/exec.go;l=147
```release-note
None
```
> Remove `c.ExtraFiles` line in machine

- libpod/runtime_volume_common.go
- test/system/160-volumes.bats
No
```release-note
None
```
Resolves: #18782
> Volume create - fast exit when ignore is set and volume exists

- go.mod
- go.sum
- pkg/machine/applehv/vfkit.go
- vendor/github.com/crc-org/vfkit/pkg/config/json.go
- vendor/github.com/crc-org/vfkit/pkg/config/virtio.go
- vendor/modules.txt
upstream reversed width and height and now we get an unusable gui
```release-note
None
```
> update vfkit vendored code

- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/volume.go
- test/e2e/play_kube_test.go
Add support for DefaultMode for configMaps and secrets. This allows users to set the file permissions for files created with their volume mounts. Adheres to k8s defaults.
Fixes https://github.com/containers/podman/issues/19313
```release-note
Add support for DefaultMode to kube play volumes
```
> Add DefaultMode to kube play

- Makefile
- hack/selinux_tag.sh
```release-note
None
```
I'm not sure about `apparmor` tag. Atleast runc isn't using it anymore.
"apparmor (since runc v1.0.0-rc93 the feature is always enabled)" from https://github.com/opencontainers/runc
`containers-common` still seems to check for `apparmor`, so not touching it for now.
> remove selinux tag as not needed anymore

- go.mod
- go.sum
- pkg/domain/infra/abi/images_list.go
- test/e2e/images_test.go
- vendor/github.com/containers/common/libimage/filters.go
- vendor/github.com/containers/common/libimage/image.go
- vendor/github.com/containers/common/libimage/manifest_list.go
- vendor/github.com/containers/common/libimage/manifests/manifests.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/types/const.go
- vendor/github.com/containers/common/libnetwork/util/filters.go
- vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
- vendor/github.com/onsi/gomega/CHANGELOG.md
- vendor/github.com/onsi/gomega/gomega_dsl.go
- vendor/github.com/onsi/gomega/matchers.go
- vendor/github.com/onsi/gomega/matchers/have_http_body_matcher.go
- vendor/modules.txt
The id, digest, and intermediate filters were broken for podman images. Fix to match on substrings instead of the whole string for id and digest. Add the intermediate value correctly when set.
Fixes https://github.com/containers/podman/issues/19966
```release-note
Fix broken id, digest, and intermediate filters for podman images
```
> Fix broken podman images filters

- .github/workflows/discussion_lock.yml
This reverts commit 618f846edc5552abd6dbe10946de677a0c89a17c.
Once merged, closed issue & PRs will be processed for discussion-locking every day instead of every hour.
```release-note
None
```
> [skip-ci] Revert "GHA Workflow: Faster discussion-locking"

- Makefile
- winmake.ps1
Since gvisor-tap-vsock 0.7.1, the upstream project ships pre-built
Windows binaries for gvproxy and win-sshproxy. These binaries are built
with -Hwindowsgui as needed by podman.
This makes the same change in winmake.ps1, but I had to hardcode
gvisor-tap-vsock version in one more place.
```release-note
None
```
> windows: Use prebuilt gvproxy/win-sshproxy binaries

- pkg/machine/wsl/wutil/wutil.go
Fixes #20209
Since wsl --version triggers help, which triggers an error code, use that instead of text detection.
```release-note
Fix an issue on non-English locales of Windows where machine installs using user-mode networking were rejected due to erroneous version detection
```
> Fix locale issues with WSL version detection

- go.mod
- go.sum
- test/e2e/manifest_test.go
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/parse_action.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/modules.txt
Test: https://github.com/containers/common/pull/1666
```release-note
None
```
> test, manifest: test push retry

- pkg/machine/provider/platform.go
- pkg/machine/provider/platform_darwin.go
Changes build tags to allow the applehv code to be built for Intel Macs
```release-note
Allows those with Intel Macs to use the Apple Hypervisor for their machines.
```
> Build applehv for Intel Macs

- libpod/container_exec.go
- libpod/healthcheck_linux.go
- test/e2e/healthcheck_run_test.go
Filter health_check and exec events for logging in console
Podman server logs are mostly full of healthcheck output, making them hard to navigate. Hence, made healthcheck service to run with `LogLevelMax=notice,` this would remove the normal output, inclusive the started/stopped messages from systemd itself.
Fixes #17856 
```release-note
Podman events' logs in systemd will output limited events in following ways:
- Podman healthcheck run would not emit `exec` and `exec_died` events
```
> Change log level for health_check

- README.md
The link for podman-hello.png was replaced with a textual representation but a dangling pointer to dead link was still present. This PR removes the dead link to avoid hitting 404
closes [#168](https://github.com/containers/podman.io/issues/168)
```release-note
None
```
> [CI:DOCS] Remove dead link from README

- pkg/util/utils_linux.go
When we walk the /dev tree we need to lookup all device paths. Now in order to get the major and minor version we have to actually stat each device. This can again fail of course. There is at least a race between the readdir at stat call so it must ignore ENOENT errors to avoid the race condition as this is not a user problem. Second, we should also not return other errors and just log them instead, returning an error means stopping the walk and returning early which means inspect fails with an error which would be bad.
Also there seems to be cases were ENOENT will be returned all the time, e.g. when a device is forcefully removed. In the reported bug this is triggered with iSCSI devices.
Because the caller does already lookup the device from the created map it reports a warning there if …
> inspect: ignore ENOENT during device lookup

- docs/source/markdown/options/env-file.md
- pkg/env/env.go
- pkg/env/env_test.go
- pkg/env/env_unix.go
- pkg/env/env_windows.go
- test/system/300-cli-parsing.bats
This caused regressions for users, see https://github.com/containers/podman/issues/19565
Fixes #19565
```release-note
Fix regression in --env-file handling. 
```
> Revert --env-file changes

- rpm/podman.spec
We don't have a successful rhel build of gvforwarder so far on the podman-next copr, so any RHEL users of podman-next will have trouble installing podman if it's a gvforwarder is a hard dep.
Switching gvforwarder to a Recommends until that's resolved.
The ELN environment is an exception as it gets dependencies updated a lot quicker.
```release-note
None
```
> [CI:BUILD] rpm/copr: gvforwarder recommends for RHEL

- pkg/api/server/register_kube.go
Update the docs for the DELETE libpod/kube/play endpoint to mention the resources removed when ran.
Fixes https://github.com/containers/podman/issues/19945
```release-note
Update DELETE libpod/kube/play endpoint docs
```
> [CI:DOCS] update kube play delete endpoint docs

- pkg/machine/wsl/machine.go
This reverts commit 5b990c3835ac167cc7f5b51fae3f719edf031965. PR #19994
Causes wsl nsenter script to infinitely loop in standard operation. Reverting for now. 
Note this was not part of a release. Normal container operations would have worked fine, its only activating the WSL prompt that would trigger the issue.
```release-note
none
```
> Revert "Fix WSL systemd detection"

- pkg/machine/wsl/machine.go
Fixes #18911
Leaves the legacy name around for now
```release-note
none
```
> Adjust to path name change for resolved unit on WSL backend

- pkg/machine/qemu/command.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/qemu/machine_test.go
- pkg/machine/qemu/qemu_command_test.go
Creates a wrapper around the Qemu command line implementation to prevent the need to hard-code the different command line options in Init and Start.
```release-note
None
```
> Create Qemu command wrapper

- docs/source/Reference.rst
- docs/source/markdown/options/env-file.md
- libpod/container.go
- pkg/api/handlers/compat/networks.go
- pkg/env/env.go
- pkg/env/env_test.go
- pkg/env/env_unix.go
- pkg/env/env_windows.go
- pkg/util/utils_linux.go
- test/system/300-cli-parsing.bats
Backports of 
https://github.com/containers/podman/pull/20268
https://github.com/containers/podman/pull/20256
https://github.com/containers/podman/pull/20250
https://github.com/containers/podman/pull/20056
```release-note
Fix regression in --env-file handling.
Fixed a bug where podman inspect would fail when stat'ing a device failed.
The network list compat API endpoint is now much faster.
```
> [v4.7] Fix env-file regssion + more backports 
