containers/podman

cmd/podman/common/create.go
cmd/podman/containers/exec.go
docs/source/markdown/options/privileged.md
go.mod
go.sum
pkg/api/handlers/libpod/containers_create.go
test/system/800-config.bats
vendor/github.com/containers/common/libimage/copier.go
vendor/github.com/containers/common/libimage/filters.go
vendor/github.com/containers/common/libnetwork/netavark/network.go
vendor/github.com/containers/common/pkg/config/config.go
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
vendor/modules.txt

As requested in containers/podman/issues/20000, add a `privileged` field to the containers table in containers.conf.  I was hesitant to add such a field at first (for security reasons) but I understand that such a field can come in handy when using modules - certain workloads require a privileged container.
```release-note
Add a new `privileged` field to container.conf which sets the defaults for `--privileged` flag when creating, running or exec'ing into a container.
```

containers.conf: add `privileged` field to containers table

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/basic.container
test/e2e/quadlet/containersconfmodule.container
test/e2e/quadlet/containersconfmodule.image
test/e2e/quadlet/containersconfmodule.kube
test/e2e/quadlet/containersconfmodule.network
test/e2e/quadlet/containersconfmodule.volume
test/e2e/quadlet/globalargs.container
test/e2e/quadlet/globalargs.image
test/e2e/quadlet/globalargs.kube
test/e2e/quadlet/globalargs.network
test/e2e/quadlet/globalargs.volume
test/e2e/quadlet_test.go

Add support for adding podman level arguments before subcommand Add specific key for Containers Conf Modules
Adjust testing environment
Add tests
Add to man page
Yes
```release-note
Quadlet - add support for podman level arguments
```
Resolves: #20246

Quadlet - add support for global arguments

---

pkg/bindings/images/build.go
test/system/070-build.bats

Closes #20259 
```release-note
None
```

fix: don't ignore containerfiles outside of build context

---

pkg/api/handlers/compat/images.go
pkg/api/handlers/libpod/images_pull.go
pkg/api/handlers/utils/images.go
pkg/api/server/register_images.go
test/apiv2/10-images.at

Add a new `compatMode` parameter to libpod's pull endpoint. If set, the
streamed JSON payload is identical to the one of the Docker compat
endpoint and allows for a smooth integration into existing tooling such
as podman-py and Podman Desktop, some of which already have code for
rendering the compat progress data.
We may add a libpod-specific parameter in the future which will stream
differnt progress data.
Fixes: issues.redhat.com/browse/RUN-1936?
```release-note
Add a new `compatMode` parameter to libpod's pull endpoint. If set, the streamed JSON payload is identical to the one of the Docker compat endpoint.
```

api: add `compatMode` parameter to libpod's pull endpoint

---

.readthedocs.yaml

readthedocs has moved to a new build configuration and our builds are failing because we have exceeded the grace time.  this pr puts in compliance with their build system and should allow automatic builds of our documentation to resume
```release-note
None
```

[CI:DOCS]rtd: implement v2 build file

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/oneshot.kube
test/e2e/quadlet_test.go

Allow users to manually set the Service Type
Add test
Update README
Yes
```release-note
Quadlet - allow users to set the service type of a .kube file to oneshot to support yaml files without containers
```

Quadlet - support oneshot .kube files

---

pkg/machine/applehv/machine.go
pkg/machine/config.go
pkg/machine/hyperv/machine.go
pkg/machine/qemu/config.go
pkg/machine/qemu/machine.go
pkg/machine/wsl/config.go
pkg/machine/wsl/machine.go

Implements a shared `SetLock` function for all virtualization providers. Adds the function to the `VM` interface to require implementation.
```release-note
None
```

Implement SetLock for all virt providers

---

pkg/machine/applehv/machine.go
pkg/machine/cleanup.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/rm_test.go
pkg/machine/hyperv/machine.go
pkg/machine/qemu/machine.go
pkg/machine/wsl/machine.go

If init fails, podman machine should remove all files and configs created during the init. This includes config jsons, image files, ssh id's, and system connections. On windows, the VM instances are also removed. On Mac/Linux, the cleanup is also extended for SIGTERM.
```release-note
The `podman machine init` command now cleans up half-baked files on failure.
```

Machine: Teardown on init failure

---

cmd/podman/client.go
cmd/podman/client_supported.go
cmd/podman/client_unsupported.go
cmd/podman/root.go
test/e2e/info_test.go
test/system/272-system-connection.bats

When people report issues, we often ask for the result of `podman info`. However, if the problem is the remote connection, it will error out with no information at all.  This PR at least will report client information before disclosing the connection error.  For example on Windows:
> .\bin\windows\podman.exe info
client:
OS: windows/amd64
provider: hyperv
version: 4.8.0-dev
host: null
...
Satisfies: RUN-1720
```release-note
podman info now reports client information even if the remote connection is unreachable
```

Show client info even if remote connection fails

---

cmd/podman/common/create.go
docs/source/markdown/options/read-only-tmpfs.md
test/system/030-run.bats

Fixes: https://github.com/containers/podman/issues/20225
```release-note
podman run --read-only-tmpfs=true|false handled correctly when run with --read-only flag
```

Fix handling of --read-only-tmpfs flag

---

go.mod
go.sum
vendor/github.com/containers/buildah/internal/util/util.go
vendor/github.com/containers/common/libimage/copier.go
vendor/github.com/containers/common/libimage/define/platform.go
vendor/github.com/containers/common/libimage/image.go
vendor/github.com/containers/common/libimage/platform.go
vendor/github.com/containers/common/libimage/platform/platform.go
vendor/github.com/containers/common/libimage/runtime.go
vendor/modules.txt

Bump up the buildah and common vendors to pick up the move of the libimage/platform code.
This is needed for https://github.com/containers/podman/pull/20050
```release-note
Bump up common and buildah to pick up libimage/platform code move
```

Update common and buildah vendor

---

test/buildah-bud/apply-podman-deltas
test/system/070-build.bats

(buildah PR 5084). Should actually have been added as a bud.bats
test in that PR, but I didn't catch it in time.
Also, remove an obsolete bud-tests skip
```release-note
None
```

buildah-bud: test relative TMPDIR

---

docs/source/markdown/podman-systemd.unit.5.md
test/system/252-quadlet.bats

System Test - Quadlet kube oneshot

---

pkg/api/handlers/utils/images.go
test/apiv2/10-images.at

This is related to the issue #20013
I have not added another e2e test, because in the `pull_test.go` file the test called "podman pull bogus image" is checking that the response contains "unauthorized: access to the requested resource is not authorized"
One thing that I was not sure you agreed with is the modified  `jsonmessage.JSONMessage{}` type. That is used there but belongs to the Docker jsonmessage package inside the vendor folder. Maybe it is better to copy that type into the same package and modify it there.
This changes the error response message to the comment in the issue.

fix: pull error response docker rest api compatibility

---

libpod/container_internal.go
test/system/500-networking.bats

When a userns and netns is used we need to let the runtime create the netns otherwise the netns is not owned by the right userns and thus the capabilities would not be correct.
The current restart logic tries to reuse the netns which is fine if no userns is used but when one is used we setup a new netns (which is correct) but forgot to cleanup the old netns. This resulted in leaked network namespaces and because no teardown was ever called leaked ipam assignments, thus a quickly restarting container will run out of ip space very fast.
Fixes #18615
```release-note
Fixed a bug where a container with a custom user namespace and --restart always/on-failure would not correctly cleanup the netns on restart resulting in leaked ips and network namespaces. 
```

libpod: restart+userns cleanup netns correctly

---

Makefile

In case a future maintainer asks "why" all these weird looking four-letter architectures are present here and in CI.
```release-note
None
```

[CI:DOCS] Add cross-build target info.

---

libpod/networking_common.go
pkg/api/handlers/compat/networks.go
test/apiv2/35-networks.at

When trying to connect a container to a network and the connection already exists, an error might be raised. To ensure compatibility with the Docker API, this error is caught and "Ok" is returned.
This problem was discovered when trying to setup Nextcloud AIO which makes extensive use of the Docker Socket. There was an issue previously when trying to create networks that already existed as shown [here](https://github.com/nextcloud/all-in-one/discussions/471)
After this was fixed, I was still facing issues because the Podman Socket responded with 500 Internal Server Error when connecting to a container to a network and the connection already existed.
From what I found in the [Docker API](https://github.com/moby/moby/blob/master/daemon/container_operations.go#L676) it seems like Docker …

fix(API): Catch ErrNetworkConnected for compat

---

go.mod
go.sum
test/e2e/history_test.go
vendor/github.com/containers/common/libimage/history.go
vendor/modules.txt

libimage did not walk thte layers correctly which was probably inherited by old Podman code.  Fix that by vendoring in the corresponding changes in c/common.
Fixes: #20375
```release-note
Fix a bug in `podman history` not displaying the sizes of certain layers.
```

image history: fix walking layers

---

test/apiv2/20-containers.at

`NanoCpus` needs to set more than 10000000 on cgroups v1.
`NanoCpus` tests are failed on cgroups v1 because of the function `verifyContainerResourcesCgroupV1()`
which verifies the resource limits.
https://github.com/containers/podman/blob/b0a45a905b23054f4f3f5bdb46e015ad39fc28f8/pkg/specgen/generate/validate.go#L111-L113
```
not ok 563 [20-containers] POST containers/create [-d {"Image":"quay.io/libpod/alpine_labels:latest","HostConfig":{"NanoCpus":500000}}] : status
```
Also, I verified that the following script fail on cgroups v1:
```bash
#!/bin/bash
podman rm -f test
read -d '' sdef <<EOF
{
"Image": "alpine",
"Cmd": [
"sleep", "1000"
],
"HostConfig": {
"NanoCpus": 500000
}
}
EOF
echo "$sdef" | curl -sSLw "%{http_code}" -X POST -H "Content-Type: application/json" --unix-socket …
```

test/apiv2/20-containers.at: fix NanoCPUs tests on cgroups v1

---

libpod/container_exec.go
pkg/domain/infra/abi/containers.go
test/system/075-exec.bats
test/system/helpers.bash

always cleanup the exec session when the command specified to the "exec" is not found.
Closes: https://github.com/containers/podman/issues/20392
```release-note
exec sessions are not leaked when the specified command does not exist
```

exec: do not leak session IDs on errors

---

cmd/podman/common/create.go
cmd/podman/common/create_opts.go
go.mod
go.sum
libpod/info_linux.go
pkg/specgen/generate/container_create.go
pkg/specgen/generate/oci.go
pkg/specgen/generate/pause_image.go
pkg/specgen/generate/storage.go
vendor/github.com/containers/common/pkg/config/config.go
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
vendor/github.com/containers/common/pkg/config/default.go
vendor/modules.txt

Use the new FindInitBinary() function to lookup the init binary, this
allows the use of helper_binaries_dir in containers.conf[1]
[1] https://github.com/containers/common/issues/1110
```release-note
Podman now also uses the helper_binaries_dir option in containers.conf to lookup the init binary (catatonit).
```

use FindInitBinary() for init binary

---

pkg/machine/applehv/machine.go

In applehv, we were not killing gvproxy when stopping via podman machine rm with force.
```release-note
None
```

Kill gvproxy when machine rm -f

---

test/system/075-exec.bats

Skip new exec-leak test from #20394, it breaks under podman-remote. (How did it ever pass CI??)
```release-note
None
```

Emergency workaround for CI breakage

---

pkg/machine/qemu/config.go
pkg/machine/qemu/options_darwin_amd64.go
pkg/machine/qemu/options_darwin_arm64.go
pkg/machine/qemu/options_freebsd_amd64.go
pkg/machine/qemu/options_freebsd_arm64.go
pkg/machine/qemu/options_linux_amd64.go
pkg/machine/qemu/options_linux_arm64.go
pkg/machine/qemu/options_windows_amd64.go
pkg/machine/qemu/options_windows_arm64.go

On darwin arm64, we need to set the location of the ovmf vars. It should be put into the imageDir (also known as as dataDir).  But because qemu determines the image path late in Init(), the image path is set something like a stream marker.
Fixes #20361
```release-note
None
```

Fix path for omvf vars on Darwin/arm64

---

test/system/helpers.bash

Followup to #20394. For years (since BATS 1.5) we've been
seeing and ignoring nasty red warnings at the end of every
system test run. Thanks for fixing it, @giuseppe! But it
broke down in the '?' case when $expected_rc is empty:
test/system/helpers.bash: line 345: [: -eq: unary operator expected
Simple fix.
```release-note
None
```

System tests: fix broken silence127

---

libpod/container.go
pkg/api/handlers/compat/exec.go
pkg/domain/infra/abi/containers.go
pkg/util/utils.go
test/system/075-exec.bats

Fixes: https://github.com/containers/podman/issues/20334
```release-note
Podman exec -t will define TERM environment variable even if container is not running with a terminal.
```

Add TERM iff TERM not defined in container when podman exec -t

---

pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/group.container
test/e2e/quadlet/user1.container
test/e2e/quadlet/user2.container

Replaces: https://github.com/containers/podman/pull/18262
```release-note
Systemd specifiers now work with Quadlet User and Group keys
```

Allow systemd specifiers in User and Group Quadlet keys

---

docs/source/markdown/podman-systemd.unit.5.md
docs/tutorials/socket_activation.md

Units created with quadlet need cgroupv2 in order to work.
Fixes #19365
```release-note
None
```

[CI:DOCS] quadlet: document cgroupv2 requirement

---

docs/source/markdown/options/publish.md
docs/source/markdown/podman-network-create.1.md

The network backend will ignore ports for macvlan and ipvlan networks so they do not do anything. No warning or error is shown because containers may be later connected to a bridge network in which case they would be useful.
Fixes #17927
```release-note
None
```

[CI:DOCS] network: document ports and macvlan interaction

---

contrib/cirrus/lib.sh

Perl is still stuck in the 1980s. Try to override that.
```release-note
None
```

cirrus setup: special-case perl unicode

---

pkg/domain/entities/pods.go
pkg/domain/infra/abi/play.go
pkg/specgen/generate/kube/kube.go
test/e2e/play_kube_test.go

When the hostNetwork option is set to true in the k8s yaml, set the pod's hostname to the name of the machine/node as is done in k8s.
Fixes https://github.com/containers/podman/issues/19321
```release-note
Set pod hostname to node/machine name with kube play when hostNetwork=true in k8s yaml
```

Use node hostname in kube play when hostNetwork=true

---

pkg/machine/e2e/stop_test.go
pkg/machine/hyperv/machine.go

LastUp now correctly reports the lastUp time for podman machine on hyperv, for both inspect and list.
Closes: #18522
```release-note
Fixed a bug where the podman machine list and podman machine inspect commands  would not show the correct Last Up time on hyperV
```

hyperV: Update lastUp time

---

libpod/oci_conmon_common.go
test/system/030-run.bats

commit 7ade9721020468438e822b16ed7a65380cc7fbd2 introduced the change that caused an issue in crun since it forces the root user session instead of the system one when DBUS_SESSION_BUS_ADDRESS is set.
I am addressing it in crun, but for the time being, let's also not pass the variable down to conmon since the assumption is that when running as root the containers must be created on the system bus.
the crun PR: https://github.com/containers/crun/pull/1328
```release-note
None
```

libpod: skip DBUS_SESSION_BUS_ADDRESS in conmon

---

test/e2e/config.go
test/e2e/images_test.go
test/e2e/play_kube_test.go
test/system/200-pod.bats

It's flaky.
* fedora-38 : sys remote fedora-38 root host boltdb [remote]
* PR #20366
* [10-17 08:38](https://api.cirrus-ci.com/v1/artifact/task/6194048763953152/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00331) in [sys] podman pod create should fail when infra-name is already in use
* fedora-38-aarch64 : sys podman fedora-38-aarch64 root host sqlite
* PR #17831
* [05-24-2023 17:49](https://api.cirrus-ci.com/v1/artifact/task/5796819322535936/html/sys-podman-fedora-38-aarch64-root-host-sqlite.log.html#t--00308) in [sys] podman pod create should fail when infra-name is already in use
* fedora-39β : int podman fedora-39β root host sqlite
* PR #20161
* [10-17 07:52](https://api.cirrus-ci.com/v1/artifact/task/4730598787383296/html/int-podman-fedora-39β-root-host-sqlite.log.html#t---S …

CI: stop using registry.k8s.io

---

libpod/container_internal.go

There is a potential race condition we are seeing where we are seeing a message about a removed container which could be caused by a non mounted container, this change should clarify which is causing it.
Also if the container does not exists, just warn the user instead of reporting an error, not much the user can do.
Fixes: https://github.com/containers/podman/issues/19702
```release-note
None
```

not mounted layers should be reported as info not error

---

test/apiv2/20-containers.at
test/apiv2/25-containersMore.at
test/apiv2/40-pods.at

Some apiv2 tests are not support on cgroups v1 environment.
```release-note
None
```

test/apiv2: adapt apiv2 test on cgroups v1 environment

---

docs/source/markdown/podman-volume-create.1.md
libpod/runtime_volume_common.go
test/system/160-volumes.bats

Fixes: https://github.com/containers/podman/issues/20449
```release-note
podman volume create supports -opt o=size=XYZ on tmpfs file systems
```

Support size option when creating tmpfs volumes

---

docs/source/markdown/podman-kube-play.1.md.in
pkg/domain/infra/abi/play.go

Users can specify BUILDAH_ISOLATION environment variable to change the default.
Fixes: https://github.com/containers/podman/issues/20024
Currently podman play kube is defaulting to chroot, which is the least safe version of build, we should always default to secure whenever possible. Chroot should only be used when building within a container.
No great way to tests this.
```release-note
podman play kube --build now supports using BUILDAH_ISOLATION environment variable to change build isolation.
```

Use buildah default isolation when working with podman play kube

---

Makefile
test/README.md

Allow the user to control flake retry and color output
Update README
No
```release-note
None
```

Makefile - allow more control over Ginkgo parameters

---

pkg/domain/infra/abi/images.go
test/apiv2/10-images.at

Docker deals with the --all flag on the client side while Podman does it on the server side.  Hence, make sure to not set the dangling filter with two different values in the backend.
Fixes: #20469
```release-note
Fix a bug in the image/prune compat REST API when the dangling filter has been set to false by clients.
```

compat API: fix image-prune --all

---

pkg/api/handlers/swagger/errors.go
pkg/api/server/register_networks.go

The endpoints to (dis-)connect networks from/to a container are no longer no-ops. Furthermore, the 403 error handled since #20365 has been documented
```release-note
None
```

[CI:DOCS] (API): Fix compat network (dis-)connect

---

test/e2e/pod_infra_container_test.go
test/system/500-networking.bats
test/system/700-play.bats
test/system/helpers.network.bash

There's a whole slew of networking-related flakes whose common
element seems to be improper use of curl. Fix those by:
* add --retry --retry-connrefused; and/or
* add -S ("show errors". Plain -s silences everything!); and/or
* test exit status from curl; and/or
* add wait_for_port after "podman run -d", to avoid races
* log commands, to make debugging easier
Important note: wait_for_port() was not working with network
namespaces. Trivial proof:
$ podman run -d --name foo -p 8192:80 \
quay.io/libpod/testimage:20221018 \
/bin/busybox-extras httpd -f -p 80
$ grep :2000 /proc/net/tcp
[no results]
Solution: use ss tool; it seems to handle namespaces just fine.
There may be a better solution.
Oh, also, add -t1 to a podman restart, to shave 18s from test run.
Fixes: #20335 and, I think, a …

CI: try to fix more networking flakes

---

cmd/podman/compose.go

Closes #20373 
Add a check on the npipe if podman compose is run against a wsl vm and return the npipe path
```
fix podman compose command not working with wsl
```

fix: check npipe when executing podman compose on wsl vm

---

test/e2e/common_test.go

Problem: frequent CI flakes of the form:
Error: cannot listen on the TCP port: listen tcp4 :5355: bind: address already in use
Always 5355.
Cause: systemd-resolve listens on 5355, but not on 127.0.0.1. So
when GetPort() tries its is-it-in-use check by binding localhost,
it succeeds; but then podman binds * and fails.
Solution: GetPort(): test by binding 0.0.0.0.
Also, improve the failure message.
```release-note
None
```

CI: e2e: safer GetPort()

---

docs/source/Introduction.rst

This PR fixes the following defect in the documentation:
It is unclear whether this change warrants a release notes entry, so I added one regardless.
```release-note
Fixed a broken code block markup in the Introduction chapter of the documentation
```

[CI:DOCS] Fix broken code block markup in Introduction.rst

---

test/system/helpers.network.bash
test/system/helpers.t

Our aarch64 CI system uses 172.31.0.0/20. Because I was (and am)
lazy, my random_rfc1918_subnet() helper was only checking /24.
This causes flakes.
Solution is to actually do it right: binary arithmetic, prefix
matching. This is effectively impossible in bash, so, use a
hairy perl oneliner and add copious tests.
Note: I considered `ipcalc`, `ipcalc-ng`, `sipcalc`, various python packages. Given our system-test constraints where we need to run on fedora, debian, and RHEL, I believe this is the safest approach in terms of portability. There may be cleaner options I did not consider, so please speak up if you have better suggestions.
Fixes: #18693
```release-note
None
```

CI: systest: safer random_rfc1918_subnet

---

libpod/container_internal_common.go
libpod/container_internal_freebsd.go
libpod/container_internal_linux.go
test/e2e/run_test.go

I don't really like this solution because it can't be undone by `--security-opt unmask=all` but I don't see another way to make this retroactive. We can potentially change things up to do this the right way with 5.0 (actually have it in the list of masked paths, as opposed to adding at spec finalization as now).
```release-note
NONE
```

Mask /sys/devices/virtual/powercap

---

cmd/podman/compose.go

```release-note
fix podman compose command not working with wsl
```

[4.7] fix: check wsl npipe when executing podman compose

---

cmd/podman/compose.go

There is a number of paths to look for compose providers.  Hence, do not error out immediately if an error is different than `os.ErrNotExist` to make sure subsequent candidates are tried.  Instead, debug-log and collect the errors.  If no provider was found, return them.
Fixes: #20502
```release-note
Fix a bug in `podman compose` to try all configured providers before throwing an error.
```

compose: try all possible providers before throwing an error

---

docs/source/markdown/options/security-opt.md
libpod/container_internal_linux.go

This solves `--security-opt unmask=ALL` still masking the path.
[NO NEW TESTS NEEDED] Can't easily test this as we do not have access to it in CI.
```release-note
NONE
```

Do not add powercap mask if no paths are masked

---

cmd/podman/root.go
libpod/container_internal.go
test/system/030-run.bats

Updated the error message to suggest user to use --replace option to instruct Podman to replace the existsing external container with a newly created one.
closes #16759
```release-note
User will be suggested to use --external option to override if a name conflict with external container is detected.
```

Define better error message for container name conflicts with external storage

---

pkg/api/handlers/libpod/kube.go
pkg/api/server/register_kube.go
pkg/bindings/kube/types.go
pkg/bindings/kube/types_play_options.go
pkg/domain/infra/abi/play.go
pkg/domain/infra/tunnel/kube.go
test/system/700-play.bats

Fixes: https://github.com/containers/podman/issues/20025
```release-note
None
```

podman kube play --replace should force removal of pods and containers

---

pkg/api/handlers/compat/images_build.go
pkg/bindings/images/build.go
test/system/070-build.bats

Podman build --remote is translating https://path as if it was a file path. This change will leave it as a URL so it can be parsed on the server side.
Fixed: https://github.com/containers/podman/issues/20475
```release-note
Fix handling of https paths in podman --remote build
```

podman build --remote URI Dockerfile should not be treated as file

---

test/system/450-interactive.bats

I've seen the stty flake (#10710) twice in one day. Time to
add a retry.
```release-note
None
```

systests: stty test: retry once on flake

---

go.mod
go.sum
vendor/github.com/containers/buildah/.cirrus.yml
vendor/github.com/containers/buildah/CHANGELOG.md
vendor/github.com/containers/buildah/changelog.txt
vendor/github.com/containers/buildah/chroot/run_linux.go
vendor/github.com/containers/buildah/chroot/seccomp.go
vendor/github.com/containers/buildah/chroot/seccomp_freebsd.go
vendor/github.com/containers/buildah/chroot/seccomp_unsupported.go
vendor/github.com/containers/buildah/define/types.go
vendor/github.com/containers/buildah/run_linux.go
vendor/modules.txt

Update Buildah to v1.32.2
```release-note
Updated Buildah to v1.32.2
```

[v4.7] Vendor Buildah v1.32.2

---

test/system/505-networking-pasta.bats

Under some circumstances BATS tests hang, causing a CI timeout.
One prominent reason is pasta test failures: BATS will not
exit until all child processes are finished, and in some
environments the socat client can stay forever.
Workaround: run socat with a timeout, and with limited retries.
Tested on an f38 system with broken IPv6: without this fix,
bats hangs until I ^C. With this fix, bats exits as it should.
```release-note
None
```

systests: pasta: avoid hangs

---

libpod/container.go
test/system/500-networking.bats

when --uts=host is provided, the expectation is to use the hostname from the host not the container name.
Closes: https://github.com/containers/podman/issues/20448
```release-note
Now --uts=host --net=host fills /etc/hostname with the host's name
```

libpod: fix /etc/hostname with --uts=host

---

.github/workflows/scan-secrets.yml
contrib/cirrus/prebuild.sh

The podman in `ubuntu-latest` environment apparently is too old to support `--userns=keep-id:uid=1000,gid=1000`.  Employ workaround in GHA workflow and in `prebuild.sh` check.
```release-note
None
```

[CI:DOCS] Fix secrets scanning GHA Workflow

---

test/farm/001-farm.bats
test/farm/Containerfile
test/farm/helpers.bash
test/farm/setup_suite.bash

Followup from #20050. Lots of tiny problems in tests, all of
them adding up to significant maintainability problems.
These tests are currently impossible to run in a dev environment,
and super-painful to set up in 1mt, so I've just done a few hours
of cleanup and am giving up for the week.
This is ready for merge, in the sense that it's much better than
what exists now, but it still needs boatloads more work.
```release-note
None
```

CI: podman farm tests cleanup

---

pkg/machine/applehv/config.go
pkg/machine/applehv/machine.go
pkg/machine/e2e/rm_test.go

Fix machine not found error message on rm to be consistent with qemu.
Plus a small readability refactor. 
```release-note
None
```

AppleHV: Fix machine rm error message

---

pkg/api/handlers/compat/images.go
pkg/api/handlers/compat/images_build.go
pkg/api/handlers/libpod/images.go
pkg/api/server/register_images.go
pkg/bindings/containers/commit.go
pkg/bindings/containers/types.go
pkg/bindings/containers/types_commit_options.go
pkg/bindings/images/build.go
pkg/domain/infra/tunnel/containers.go
pkg/specgen/generate/config_linux.go
test/e2e/commit_test.go

Fixes: https://github.com/containers/podman/issues/19947
```release-note
podman --remote commit now shows additional information when committing.
```

Add status messages to podman --remote commit

---

ISSUE-EOL-POLICY.md

RUN-1721 [spike] create EOL policies for issues and PRs
```release-note
Define an End-of-Life policy for issues and PRs
```

[CI:DOCS] End-of-Life policy for github issues

---

cmd/podman/machine/stop.go
pkg/machine/config.go
pkg/machine/default.go
pkg/machine/e2e/machine_test.go
pkg/machine/fcos.go
pkg/machine/oci.go
pkg/machine/ocidir.go
pkg/machine/ocipull/pull.go
pkg/machine/ocipull/source.go
pkg/machine/pull.go
pkg/machine/qemu/machine.go

allow podman machine to extract its disk image from an oci registry or oci-dir locally.  for now, the image must be relatively inflexible. it must have 1 layer.  the layer must possess one image. so a dockerfile like:
FROM scratch
COPY ./myimage.xz /myimage.xz
when using an oci dir, the directory structure must adhere to the typical directory structure of a an oci image (with one layer).
── blobs
│   └── sha256
│       ├── 53735773573b3853bb1cae16dd21061beb416239ceb78d4ef1f2a0609f7e843b
│       ├── 80577866ec13c041693e17de61444b4696137623803c3d87f92e4f28a1f4e87b
│       └── af57637ac1ab12f833e3cfa886027cc9834a755a437d0e1cf48b5d4778af7a4e
├── index.json
└── oci-layout
in order to identify this new input, you must use a transport/schema to differentiate from current podman machine init …

Consume OCI images for machine image

---

test/e2e/build/containerignore-symlink/.dockerignore
test/e2e/build_test.go

It seems certain test infrastructure prevents cloning repo which contains symlink outside of the repo itself, generate symlink for such test by the testsuite itself just before running test and remove it when test is completed.
Following symlink was added to repo here: https://github.com/containers/podman/pull/16315
```release-note
None
```

remote,test: remove `.dockerignore` which is a symlink

---

pkg/machine/applehv/machine.go
pkg/machine/hyperv/vsock.go
pkg/machine/qemu/config.go
pkg/machine/qemu/machine.go
pkg/machine/sockets.go

Refactors machine socket mapping to prevent using similar/the same code paths. Moves the shared code to `pkg/machine/sockets.go`.
```release-note
None
```

Refactor machine socket mapping

---

.cirrus.yml
contrib/cirrus/lib.sh
contrib/cirrus/setup_environment.sh
test/README.md
test/e2e/common_test.go
test/system/005-info.bats

Followup to #20318: now that sqlite is the podman default,
enforce that in CI as well. Test boltdb only in Prior Fedora.
In the process, discovered & cleaned up some duplication
and unused YAML anchors.
```release-note
None
```

CI: default to sqlite

---

go.mod
go.sum
vendor/github.com/coreos/go-systemd/v22/internal/dlopen/dlopen.go
vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go
vendor/modules.txt

This fixes a CI flake. go-systemd was not handling the dlerror() function correctly which lead to wrong errors being reported.
Fixes #20569
```release-note
None
```

vendor: update github.com/coreos/go-systemd/v22 to latest main

---

cni/README.md
docs/source/markdown/podman-network-create.1.md
docs/source/markdown/podman-network.1.md
docs/source/markdown/podman.1.md

The docs were rather vague about the deprecation of CNI, make it clear that we are going to remove it with 5.0 as we decided to do that in our planning.
Also while looking at the podman network create docs I noticed --ipam-driver dhcp was still documented as not supported with netavark so I fixed that as well.
```release-note
Deprecation notice: CNI support will be removed in the next major version 5.0.
```

[CI:DOCS] docs: make CNI removal explicit

---

cmd/podman/images/push.go
test/system/800-config.bats

When using the local client, we should display the compression algorithm.
If the compression level is set, then show this also.
```release-note
podman push --help will show compression algorithm when run locally.
```

Podman push --help should reveal default compression

---

pkg/machine/applehv/machine.go

FCOS has a security limitation where new directories cannot be added to the root / directory of its filesystem.  This PR uses the work-around discussed in https://github.com/coreos/rpm-ostree/issues/337#issuecomment-1000923022 to temporarily disable the limitation, perform the mkdir, and then re-enable the limitation.
This PR allows mounts on the applehv to actually work.
```release-note
virtiofs volume shares are now functional on the `applehv` machine provider
```

applehv: allow virtiofs to mount to /

---

test/system/001-basic.bats
test/system/505-networking-pasta.bats
test/system/helpers.bash

This is something I've long wanted in logs: an indicator of
which bats file the test lives in. As of v1.7.0 there is
now a way to do that, BATS_TEST_NAME_PREFIX. Use it. Logs
now look like:
ok 14 [001] podman - shutdown engines
ok 15 [005] podman info - basic test
...
not ok 195 [065] podman cp - dot notation ....
(As a bonus, we can remove the super-long "test blah blah pasta"
duplication from 505.bats).
Also, removed no-longer-necessary (fingers crossed) debug code
for the recently fixed containers-storage umount/EINVAL flake.
```release-note
None
```

systests: add [NNN] prefix in logs, NNN = filename

---

test/system/005-info.bats
test/system/999-final.bats

This will only fail if someone ever adds a system test that
runs podman with "--db-backend boltdb", which nobody should
ever do, but this is a cheap way to make sure it never happens.
See #20563
```release-note
None
```

systests: add a last-minute check for db backend

---

rpm/podman.spec

GOPROXY is currently causing build issues like so:
```
go: github.com/containernetworking/cni@v0.7.1: GOPROXY list is not the empty string, but contains no entries
```
This commit sets `GOPROXY=direct` in rpm spec file.
Ref: https://download.copr.fedorainfracloud.org/results/packit/containers-podman-20627/centos-stream+epel-next-9-aarch64/06611633-podman/builder-live.log.gz
```release-note
None
```

Disable goproxy

---

pkg/machine/applehv/machine.go
pkg/machine/hyperv/vsock.go
pkg/machine/sockets.go

Fixes nits that were suggested in #20420. The caller of `ListenAndWaitOnSocket` did not use the value returned by the conn channel, therefore it was better to just close the conn in the `ListenAndWaitOnSocket` function instead.
```release-note
None
```

Fix socket mapping nits

---

pkg/machine/applehv/config.go
pkg/machine/applehv/machine.go
pkg/machine/hyperv/config.go
pkg/machine/hyperv/machine.go
pkg/machine/ignition.go
pkg/machine/qemu/config.go
pkg/machine/qemu/machine.go

Creates a common `SetIgnitionFile` function in `pkg/machine/ignition.go` which creates the new VMFile that will represent the machine's ignition file. It assigns the VMFile to the provided location.
Creates an `IgnitionBuilder` type to generate the ignition configuration for a given virt provider.
```release-note
None
```

Refactor Ignition configuration for virt providers

---

docs/source/markdown/options/ulimit.md
libpod/container_internal_common.go
libpod/oci_conmon_linux.go
pkg/specgen/generate/oci.go
pkg/specgen/generate/oci_freebsd.go
pkg/specgen/generate/oci_linux.go
test/e2e/inspect_test.go
test/system/030-run.bats

Docker allows the passing of -1 to indicate the maximum limit allowed for the current process.
Fixes: https://github.com/containers/podman/issues/19319
```release-note
Ulimits set to -1 sets the container processes limits to the current max (Unlimited)
```

Support passing of Ulimits as -1 to mean max

---

docs/source/markdown/podman-systemd.unit.5.md

Users fail to realize that they can use other systemd options within the quadlet files, like ExecStartPre. This change should make it clearer to the users.
https://github.com/containers/podman/discussions/20642
```release-note
None
```

[CI:DOCS] Improve the documentation of quadlet

---

cmd/podman/early_init_darwin.go
cmd/podman/early_init_unsupported.go

No.
```release-note
- fix max open files limit for qemu (mainly applicable to MacOS, issue: https://github.com/containers/podman/issues/16106 ) 
```
Fixes issue: https://github.com/containers/podman/issues/16106

fix max open files limit for qemu

---

test/e2e/create_test.go
test/e2e/run_test.go

...while Ed was napping:
- create/run based on remote image: was not actually testing anything
- create/run --tls-verify: ditto
- run --decryption-key: sort of testing but not really
- Fail(), not Skip(), if we can't start registry.
- never Skip() halfway through a test: emit a message, and return
The Skip-in-the-middle thing deserves to be shouted from the rooftops.
Let's please never do that again. Skip() says "this entire test was
skipped", which can be misleading to a spelunker trying to track
down a problem related to those tests.
Also, more minor:
- reduce use of port 5000
- rename a confusingly-named test
Ref: #11205, #12009
```release-note
None
```

CI: e2e: fix a smattering of test bugs that slipped in

---

test/e2e/quadlet/mount.container

Quadlet test - add case for multi = sign in mount

---

rpm/podman.spec

The `version_no_tilde` rpm macro correctly handles both `vX.Y.Z` and `vX.Y.Z-rcN` git tags. Using this macro instead of `version` will soon allow Packit to handle RC builds correctly.
Accompanying change in Packit to land soon:
https://github.com/packit/packit/pull/2149
```release-note
None
```

[CI:BUILD] packit: handle builds for RC releases

---

docs/source/markdown/podman-stats.1.md.in

```release-note
The description for uptime was "Same as upTime", changed it to be "same as Up", as up has a description, and saying that upTime does the same as upTime isn't particularly descriptive!
```

"[CI:DOCS]" Update podman-stats.1.md.in

---

cmd/podman/machine/init.go
cmd/podman/machine/set.go
docs/source/markdown/podman-machine-init.1.md.in
docs/source/markdown/podman-machine-set.1.md.in
pkg/machine/applehv/config.go
pkg/machine/applehv/machine.go
pkg/machine/config.go
pkg/machine/hyperv/config.go
pkg/machine/hyperv/machine.go
pkg/machine/qemu/command.go
pkg/machine/qemu/config.go
pkg/machine/qemu/config_test.go
pkg/machine/qemu/machine.go
pkg/machine/wsl/config.go
pkg/machine/wsl/machine.go

Hi,
This PR is a WIP related to the request in https://github.com/containers/podman/issues/16707
At this moment, the PR works for `QEMU` hypervisor and allows multiple USB devices to be passthrough to `podman machine`.
Example using `vendor:product`
```
toso@tapioca ~/s/podman (usb-host-passthrough)> ./bin/podman machine init tosovm1 --usb vendor=13d3,product=5406 --usb vendor=08ec,product=0016
toso@tapioca ~/s/podman (usb-host-passthrough)> ./bin/podman machine start tosovm1
toso@tapioca ~/s/podman (usb-host-passthrough)> ./bin/podman machine ssh tosovm1 dmesg | grep -i "13d3\|08ec"
[    1.382442] usb 1-1: New USB device found, idVendor=13d3, idProduct=5406, bcdDevice=60.01
[    1.877370] usb 1-2: New USB device found, idVendor=08ec, idProduct=0016, bcdDevice= 2.00
[   10.948755] usb …
```

qemu: add usb host passthrough

---

docs/source/markdown/options/volume.md

Fixes the `chcon` relabeling command in the podman volume options docs.
```release-note
None
```

[CI:DOCS] docs: fix relabeling command

---

pkg/machine/e2e/config_test.go

Introduce MACHINE_TEST_TIMEOUT, which sets the timeout for machine tests, in seconds.
```release-note
None
```

[CI:DOCS] Machine test timeout env var

---

contrib/podmanimage/stable/Containerfile
contrib/podmanimage/testing/Containerfile
contrib/podmanimage/upstream/Containerfile

This change will allow RHEL subscriptions from the host to flow to internal containers.
Fixes: https://github.com/containers/common/issues/1735
```release-note
RHEL Subscriptions from the host now flow through to quay.io/podman/* images
```

[CI:DOCS] Pass secrets from the host down to internal podman containers

---

.cirrus.yml
test/e2e/run_test.go
test/system/005-info.bats
test/system/505-networking-pasta.bats

No change in base, just newer packages (especially crun-1.11-1)
Then fix broken tests.
```release-note
None
```

VM images: bump to 2023-11-16

---

cmd/podman/machine/init.go
pkg/machine/config.go
pkg/machine/e2e/init_test.go

florent found a bug where he used "applehv" as a machine name.  it turns out when we use a vmtype name, esp. the active type, it really messes up directory structures for configuration and images alike.
```release-note
"applehv","qemu", "wsl", and "hyperv" are no longer valid podman machine names
```

vmtypes names cannot be used as machine names

---

docs/tutorials/rootless_tutorial.md

Followup to #20722:
- Fix missing "containers" subdirectory
- Indicate what podman uses as defaults for XDG envariables
- whitespace and quoting fixes (I actually ran pandoc this time)
```release-note
None
```

[CI:DOCS] More rootless-tutorial fixes

---

docs/source/markdown/options/mount.md
go.mod
go.sum
libpod/container_internal_common.go
pkg/specgenutil/volumes.go
pkg/util/mountOpts.go
test/system/060-mount.bats
vendor/github.com/containers/common/pkg/parse/parse.go
vendor/github.com/containers/common/version/version.go
vendor/modules.txt

Add a new `no-dereference` mount option supported by crun 1.11+ to     
re-create/copy a symlink if it's the source of a mount.  By default the
kernel will resolve the symlink on the host and mount the target.      
As reported in #20098, there are use cases where the symlink structure 
must be preserved by all means.                                        
Fixes: #20098
Fixes: issues.redhat.com/browse/RUN-1935
```release-note
// TODO
```

new 'no-dereference' mount option

---

pkg/machine/e2e/list_test.go

A follow up to https://github.com/containers/podman/commit/3d88f614f7ffb24417af6ce4776e96887f3c772c by @ashley-cui  This will honor the value configured via env var in the very specific "check if running while starting" test case, where session is started w/o wait.
```release-note
None
```

Use configured timeout in list_test.go

---

pkg/machine/qemu/config.go
pkg/machine/qemu/machine.go

Removes the `MachineVMV1` and `MonitorV1` structures that have been deprecated for a long enough period of time that it makes sense to no longer support them.
Results in the removal of deprecated `getSocketAndPid` as well.
The migration code was added in commit `6e0e1cbddd5e1c5dff51215ad2b41a99d890fad8` and made it into release `v4.1.0`
```release-note
Warning (action required): Users running a `podman` version earlier than `v4.1.0` will have machines using a now unsupported internal structure as of `v5.0.0`. There will be no way to migrate unless using a version of `podman` from `v4.1.0` to `v4.5.1` to do the migration. If a migration is not done, the user will not be able to remove the machine files using `podman machine rm` and will have to manually remove all files for the out-of-date …
```

No longer support deprecated legacy QEMU machine structures

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/notify-healthy.container
test/e2e/quadlet_test.go

This expands support for the (previously) boolean `Notify` directive, in support of healthcheck determined SD-NOTIFY event emission, as supported by Podman with the `--sdnotify=healthy` option.
Fixes: #18189
```release-note
Support `healthy` for `Notify` directives in Quadlet
```

quadlet: Support `healthy` for `Notify` directives

---

RELEASE_NOTES.md

Update release notes based off of comments from RC1 https://github.com/containers/podman/pull/20724
```release-note
None
```

[4.8] [CI:DOCS] Update release notes

---

docs/source/markdown/podman-systemd.unit.5.md

This PR fixes the syntax of the Ulimit option to match the expected syntax by podman itself. 
When using the previous syntax from the example, the following error shows: 
> Error: ulimit option "nofile:1000:10000" requires name=SOFT:HARD, failed to be parsed: invalid ulimit argument: nofile:1000:10000
```release-note
Correct Ulimit syntax in Podman systemd unit docs to match expected usage. 
```

[CI:DOCS] Correct Ulimit syntax in systemd unit docs. 

---

pkg/domain/infra/abi/play.go
test/apiv2/80-kube.at

Currently if user specifies podman kube play --replace, the pod is removed on the client side, not the server side.  If the API is called with replace=true, the pod was not being removed and this called the API to fail. This PR removes the pod if it exists and the caller specifies replace=true.
Fixes: https://github.com/containers/podman/discussions/20705
```release-note
Remote API for podman kube play now supports replace=true
```

If API calls for kube play --replace, then replace pod

---

pkg/domain/infra/abi/system.go

Previously, the setup only checked for the CAP_SYS_ADMIN capability, which could be not enough with containerized Podman where CAP_SYS_ADMIN might be set for an unprivileged user.
Closes: https://github.com/containers/podman/issues/20766
[NO NEW TESTS NEEDED] needs containerized Podman
```release-note
Fix crash when running in a containerized environment with euid != 0 and capabilities set
```

system: enhance check for re-exec into rootless userns

---

RELEASE_NOTES.md

The 5.0 release, which is coming up fast, will make a number of deprecations and removals. We can start giving folks a heads up on them now, so there is no confusion when 5.0 drops. We will also write some blogs about the transition over the coming weeks (after we have a better idea of what the final release will look like).
```release-note
NONE
```

[CI:DOCS] Add notes on upcoming deprecations to release notes

---

docs/source/markdown/options/add-host.md
docs/source/markdown/options/no-hostname.md
docs/source/markdown/podman-build.1.md.in
docs/source/markdown/podman-farm-build.1.md.in
docs/source/markdown/podman-farm-list.1.md
hack/xref-helpmsgs-manpages

Followup to #20051, which I didn't review in time.
[NO NEW TESTS NEEDED] -- I tested on my laptop, pinky promise
```release-note
None
```

Clean up farm-build miscommit

---

test/compose/test-compose

I noticed these old debug code while looking at a log. These were needed to debug a nasty flake[1] in the compose tests. However it has been fixed[2] for a while and I am not aware of any flakes around that logic so we are good to remove it.
I still leave the server logs in there as they may be useful for all kinds of issues and are only printed when the test fails so it does not clutter the logs.
[1] https://github.com/containers/podman/issues/10052
[2] https://github.com/containers/podman/pull/11091
```release-note
None
```

test/compose: remove debug leftovers

---

test/system/005-info.bats
test/system/010-images.bats
test/system/030-run.bats
test/system/065-cp.bats
test/system/075-exec.bats
test/system/110-history.bats
test/system/620-option-conflicts.bats
test/system/helpers.bash

Some system tests run deep loops:
for x in a b c; do
for y in d e f; do
.... check condition $x + $y
Normally, if one of these fails, game over. This can be frustrating to a developer looking for failure patterns.
Here we introduce a new defer-assertion-failure function, meant to be called before loops like these. Everything is the same, except that tests will continue running even after failure.
When test finishes, or if test runs immediate-assertion-failure, a new message indicates that multiple tests failed:
FAIL: X test assertions failed. Search for 'FAIL': above this line.
```release-note
None
```

[systests] new defer-assertion-failure

---

libpod/container_internal.go
libpod/container_internal_common.go

If we get an error chowning a file or directory to a UID/GID pair for something like ENOSUP or EPERM, then we should ignore as long as the UID/GID pair on disk is correct.
Fixes: https://github.com/containers/podman/issues/20801
Since this is difficult to test and existing tests should be sufficient to ensure no regression.
```release-note
None
```

Use idtools.SafeChown and SafeLchown everywhere

---

docs/source/markdown/options/mount.md

The default is OCI runtime specific, there is no way for Podman to know it.
[CI:DOCS]
Closes: https://github.com/containers/podman/issues/20754
```release-note
None
```

docs: drop default for tmpfs-mode

---

cmd/quadlet/main.go
docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/basic.pod
test/e2e/quadlet/name.pod
test/e2e/quadlet/pod.non-quadlet.container
test/e2e/quadlet/pod.not-found.container
test/e2e/quadlet/podmanargs.pod
test/e2e/quadlet_test.go
test/system/252-quadlet.bats
test/system/helpers.bash
test/system/helpers.systemd.bash

Add support for .pod unit files with only PodmanArgs, GlobalArgs, ContainersConfModule and PodName
Add support for linking .container units with .pod ones
Add e2e and system tests
Add to man page
Yes
```release-note
Quadlet - Add support for .pod unit files
```
Resolves: #17687

Quadlet - Add support for .pod units

---

libpod/sqlite_state.go

If a transaction is started it must either be committed or rolled back. The function uses defer to call `tx.Rollback()` if there is an error returned. However it also called `tx.Commit()` and afterwards further errors can be returned which means it tries to roll back a already committed transaction which cannot work.
This fix is to make sure tx.Commit() is the last call in that function. see https://github.com/containers/podman/issues/20731
```release-note
None
```

sqlite: fix issue in ValidateDBConfig()

---

libpod/sqlite_state.go

We have to Commit() the transaction. Note this is only in a rare pod remove code path and very unlikely to ever be used.
```release-note
None
```

sqlite: fix missing Commit() in RemovePodContainers()

---

libpod/container_exec.go
libpod/events.go
libpod/events/config.go
libpod/events/events.go
libpod/events/journal_linux.go
libpod/sqlite_state.go
pkg/api/handlers/utils/containers.go
pkg/domain/entities/events.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/tunnel/containers.go
test/apiv2/27-containersEvents.at

Added additional check for event type to be remove and set the correct exitcode by fetching it from runtime state
closes #19124
```release-note
Podman remove events now contain correct exit-code.
```

Set correct exitcode in remove events

---

docs/tutorials/performance.md

[CI:DOCS] performance: document sometimes slow native overlayfs

---

pkg/api/handlers/libpod/images.go
pkg/domain/infra/tunnel/images.go

Instead of relying on the remote server to create tar files with the right account IDs (which the remote server doesn't even know, when the client and server run under different accounts), have the remote client ignore the account IDs when unpacking.
Then just hard-code 0 in the remote server, so that the remote server's account identity does not leak in the tar file contents.
Compare https://github.com/containers/image/issues/1627 .
[NO NEW TESTS NEEDED] : https://github.com/containers/podman/pull/18563 suggests that existing tests already cover these code paths / properties.
https://github.com/containers/storage/pull/1765 will improve the privacy of the generated tar files further, but it is not a prerequisite.
```release-note
None
```

Fix transferring data using tar

---

utils/utils.go

`utils.Tar()` and `utils.TarWithChroot()` both return `ReadCloser`s, but when we called them from `utils.TarToFilesystem()` and `utils.TarChrootToFilesystem()` respectively, they were not being closed.
```release-note
None
```

utils: close a couple of ReadClosers

---

go.mod
go.sum
vendor/github.com/containers/common/libnetwork/netavark/exec.go
vendor/github.com/containers/common/libnetwork/netavark/network.go
vendor/github.com/containers/common/libnetwork/network/interface.go
vendor/github.com/containers/common/pkg/config/config.go
vendor/github.com/containers/common/pkg/config/config_darwin.go
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/default.go
vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md
vendor/github.com/onsi/ginkgo/v2/ginkgo/internal/test_suite.go
vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/dependencies.go
vendor/github.com/onsi/ginkgo/v2/ginkgo/watch/package_hash.go
vendor/github.com/onsi/ginkgo/v2/reporters/json_report.go
vendor/github.com/onsi/ginkgo/v2/types/code_location.go
vendor/github.com/onsi/ginkgo/v2/types/version.go
vendor/modules.txt

Vendor c/common@main
```release-note
Fixed a bug in the MacOS pkginstaller where Podman machine was using a different QEMU binary than the one installed using the installer, if it existed on the system
```

Vendor c/common

---

test/system/030-run.bats
test/system/272-system-connection.bats

Two newly-added tests, fail in gating:
- system connection: difference in how sockets are set up
between CI and gating
- ulimit: gating seems to run with ulimit -c -H 0. Test, and skip.
```release-note
None
```

Gating test fixes

---

cmd/quadlet/main.go
docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/parser/unitfile.go
test/e2e/quadlet/merged-override.container
test/e2e/quadlet/merged-override.container.d/10-first.conf
test/e2e/quadlet/merged-override.container.d/20-second.conf
test/e2e/quadlet/merged.container
test/e2e/quadlet/merged.container.d/10-first.conf
test/e2e/quadlet/merged.container.d/20-second.conf
test/e2e/quadlet_test.go

For a source file like `foo.container`, look for drop in named `foo.container.d/*.conf` and merged them into the main file.  The dropins are applied in alphabetical order, and files in earlier diretories override later files with same name.
This is similar to how systemd dropins work, see:
https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html
Also adds some tests for these
This seems useful for things like: 
https://github.com/containers/qm/issues/284
It also allows a non-auto-enabled quadlet, i.e. without an install section, to easily add one using a dropin.
```release-note
* Quadlet now support systemd-style dropins
```

quadlet: Support systemd style dropin files

---

libpod/container_internal_freebsd.go
libpod/networking_freebsd.go
pkg/specgen/generate/namespaces.go
pkg/specgen/generate/namespaces_freebsd.go
pkg/specgen/generate/namespaces_linux.go

In FreeBSD-14.0, it is possible to configure a jail's network settings from outside the jail using ifconfig and route's new '-j' option. This removes the need for a separate jail to own the container's vnet.
```release-note
None
```

libpod: Allow using just one jail per container on FreeBSD

---

test/system/030-run.bats
test/system/272-system-connection.bats

Two newly-added tests, fail in gating:
- system connection: difference in how sockets are set up between CI and gating
- ulimit: gating seems to run with ulimit -c -H 0. Check, and skip if ulimit is less than what we need
```release-note
None
```

[v4.8] Gating test fixes

---

contrib/podmanimage/upstream/Containerfile

See: https://developers.redhat.com/blog/2019/08/14/best-practices-for-running-buildah-in-a-container
See: https://github.com/containers/podman/blob/06c41b614db11382579ff2931b9dd145f241b485/docs/source/markdown/options/isolation.md
```release-note
Set `BUILDAH_ISOLATION=chroot` within Podman Containerfile 
```

Set `BUILDAH_ISOLATION=chroot` within Podman Containerfile

---

pkg/bindings/containers/exec.go
pkg/bindings/errors.go
pkg/domain/infra/tunnel/containers.go
pkg/machine/e2e/basic_test.go

Commit f48a706abc added a new API endpoint to remove exec session correctly. And the bindings try to call that endpoint for exec every time. Now since client and server must not be the same version this causes a problem if a new 4.8 client calls an older 4.7 server as it has no idea about such endpoint and throws an ugly error. This is a common scenario for podman machine setups.
The client does know the server version so it should make sure to not call such endpoint if the server is older than 4.8.
I added a exec test to the machine tests as this can be reproduced with podman machine as at the moment at least the VM image does not contain podman 4.8. And it should at least make sure podman exec keeps working for podman machine without regressions.
Fixes #20821
```release-note
Fixed a bug …
```

fix podman-remote exec regression with v4.8

---

libpod/container.go
libpod/container_internal_freebsd.go
libpod/container_internal_linux.go

Right now, we always use a private UTS namespace on FreeBSD. This should be made optional but implementing that cleanly needs a FreeBSD extension to the OCI runtime config. The process for that is starting (https://github.com/opencontainers/tob/pull/133) but in the meantime, assume that the UTS namespace is private on FreeBSD.
This moves the Linux-specific namespace logic to container_internal_linux.go and adds a FreeBSD stub.
```release-note
None
```

libpod: Detect whether we have a private UTS namespace on FreeBSD

---

cmd/podman/containers/commit.go
cmd/podman/containers/create.go
docs/source/markdown/options/volume.image.md
docs/source/markdown/podman-commit.1.md
libpod/container_commit.go
pkg/api/handlers/changes.go
pkg/api/handlers/changes_test.go
pkg/api/handlers/compat/images.go
pkg/api/handlers/libpod/images.go
pkg/bindings/containers/commit.go
pkg/bindings/containers/types.go
pkg/bindings/containers/types_commit_options.go
pkg/domain/entities/containers.go
pkg/domain/infra/abi/config.go
pkg/domain/infra/abi/config_test.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/tunnel/containers.go
test/apiv2/14-commit.at
test/e2e/commit_test.go

```release-note
`podman container commit` now features a `--config` option which accepts a filename containing a JSON-encoded container configuration to be merged in to the newly-created image.
```
Fixes #13770.

RHEL-14922: accept a config blob alongside the "changes" slice when committing

---

.cirrus.yml

It should depend on aarch64 *validate*, not just build.
(Noticed by accident while reviewing Macintosh CI graph)
```release-note
None
```

CI: fix system_test_aarch64 dependencies

---

docs/source/markdown/options/health-start-period.md

Update the health-start-period docs to clarify what exactly the health-start-period flag does based on whether the health check command succeeds or fails.
Fixes https://github.com/containers/podman/issues/19272
```release-note
Update --health-start-period docs clarifying exactly how it behaves
```

[CI:DOCS] Update health-start-periods docs

---

pkg/machine/qemu/options_windows_amd64.go

Originally `max` level with exceptions was used, because netavark could not work with `qemu64`, because there were needed SIMD instructions blocked. Now it works w/o any issues. What could have changed in between:
* qemu64 could have been adjusted to expose more features for this basic CPU;
* Rust compiler could have been improved to generate multiple versions of binary paths to choose the suitable most performant one available at runtime;
* Optimization flags might have changed for netavark;
* Some or all of the above.
This has been verified to work on:
* Windows 10, Intel Core i7 6700K
* Windows 11, Intel Core i7 11375H
* Windows 11 Insiders Preview, Hyper-V machine with nested virtualization on Windows 11 Intel Core i7 11375 host …

Change default QEMU CPU level to `qemu64` on Windows amd64

---

test/apiv2/27-containersEvents.at
test/apiv2/test-apiv2

Test flaking because (I think) one-second resolution isn't
good enough for --since. Use NS resolution.
Also, more test-name cleanup: strip off timestamps in 'since='.
This yields consistent test names in logs, which makes it easier
for me to categorize flakes.
Fixes: #20896
```release-note
None
```

apiv2 tests: fix race

---

test/system/250-systemd.bats
test/system/252-quadlet.bats
test/system/255-auto-update.bats
test/system/270-socket-activation.bats
test/system/helpers.systemd.bash

When a systemd-related system test fails, we usually get:
systemctl start foo
FAILED exit status 1, try 'systemctl --status' or 'journalctl -xe'
That makes it impossible to debug flakes.
Solution: new systemctl_start() [note underscore], to be used
instead of systemctl SPACE start. On failure, will run log
commands.
```release-note
None
```

systests: debug systemd failures

---

RELEASE_NOTES.md
version/rawversion/version.go

V4.8.1 bump

---

docs/source/markdown/podman-kube-play.1.md.in
libpod/define/annotations.go
pkg/domain/infra/abi/play.go

```release-note
Add support for the userns annotation in kube play 
To set userns of a pod, use the **io.podman.annotations.userns** annotation in the pod/deployment definition. This can be overridden with the `--userns` flag.
```
Fixes #20658

Add support for the userns annotation in kube play

---

contrib/cirrus/win-lib.ps1

For whatever reason (I don't understand this stuff well) the
`win-podman-machine-main.ps1` script exits successfully despite the
final `Check-Exit` showing a non-zero exit code was detected.  Attempt
to fix this by throwing an exception instead of calling `Exit`.
Ref: https://github.com/containers/podman/pull/20852#issuecomment-1834453550
```release-note
None
```

Fix command failure not resulting in task failure

---

.cirrus.yml
Makefile
contrib/cirrus/cirrus_yaml_test.py
contrib/cirrus/mac_cleanup.sh
contrib/cirrus/mac_env.sh
contrib/cirrus/mac_setup.sh
pkg/machine/e2e/README.md

***Depends on***: https://github.com/containers/podman/pull/20852
Setup and execute podman machine testing on bare-metal M1 Macs
using a pool of shared and semi-persistent hosts.  Automated
and manual processes outside this repository are responsible
for providing and maintaining all hosts.  Ref.
https://github.com/containers/automation/tree/main/mac_pw_pool
Update the `localmachine` make target to standardize execution
across platforms.  Update/simplify podman-machine e2e README to
reflect current reality.
Warning: This CI setup and supporting infrastructure was developed
in favor of expediency vs reliability and stability.  There are
many possible failure-modes (known and unknown) which may lead
to undefined test behaviors.  Future work may address some of
these as they are encountered …

Implement bare-metal Mac M1 podman-machine testing

---

pkg/domain/infra/abi/play.go
test/e2e/play_build_test.go
test/system/252-quadlet.bats

Add test for a specific crash
No
```release-note
None
```
Resolves: #20432

Kube Play - set ReportWriter when building an image

---

cmd/podman/containers/exec.go
cmd/podman/containers/run.go
docs/source/markdown/options/preserve-fd.md
docs/source/markdown/podman-exec.1.md.in
docs/source/markdown/podman-run.1.md.in
libpod/container_config.go
libpod/container_exec.go
libpod/oci.go
libpod/oci_conmon_common.go
libpod/oci_conmon_exec_common.go
libpod/options.go
pkg/domain/entities/containers.go
pkg/domain/entities/pods.go
pkg/domain/infra/abi/containers.go
pkg/specgen/generate/container_create.go
pkg/specgen/specgen.go
pkg/specgenutil/specgen.go
test/system/030-run.bats
test/system/075-exec.bats

add a new option --preserve-fd that allows to specify a list of FDs to pass down to the container.
It is similar to --preserve-fds but it allows to specify a list of FDs instead of the maximum FD number to preserve.
--preserve-fd and --preserve-fds are mutually exclusive.
It requires crun since runc would complain if any fd below --preserve-fds is not preserved.
Closes: https://github.com/containers/podman/issues/20844
```release-note
Now podman run and exec support --preserve-fd to specify the FDs to pass down to the container
```

podman: new option --preserve-fd

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/entrypoint.container
test/e2e/quadlet_test.go
test/system/252-quadlet.bats

This PR closes #20585
Add Inital support for Entrypoint on quadlets
Add e2e Tests for Entrypoint
Updates the documentation with one example to use the Entrypoint option
Yes
```release-note
Quadlets - Add support for Entrypoint Option 
```

Add support for Entrypoint in quadlet

---

test/system/065-cp.bats

Some of the tests were doing "podman run -d" without wait_for_ready.
This may be the cause of some of the CI flakes. Maybe even all?
It's not clear why the tests have been working reliably for years
under overlay, and only started failing under vfs, but shrug.
Thanks to Chris for making that astute observation.
Fixes: #20282  (I hope)
```release-note
None
```

systests: cp: add wait_for_ready

---

.github/labeler.yml

Commit ca66a90b87 was merged without fixing the config. Please read changelogs before merging renovate PRs, especially when it is a major version bump.
```release-note
None
```

[CI:DOCS] fix broken labeler.yml config

---

contrib/cirrus/win-lib.ps1

This is just a small change to improve Windows CI testing:
- Modified Check-Exit to take a relative stack postition so that reusing functions like Run-Command report on their callers as opposed to the source position of the wrapper.
- Record and print the last command executed as it likely scrolled off with test output.
```release-note
none
```

Improve error handling in win-lib.ps1

---

go.mod
go.sum
vendor/github.com/containers/common/pkg/config/config_darwin.go
vendor/github.com/containers/common/pkg/config/default.go
vendor/github.com/containers/common/version/version.go
vendor/modules.txt

Fixes #20808
```release-note
Fixed a bug in the MacOS pkginstaller where Podman machine was using a different QEMU binary than the one installed using the installer, if it existed on the system
```

[v4.8] bump c/common to v0.57.1

---

pkg/machine/wsl/machine.go

Fixes #20921 
Previously the WSL user-mode networking distribution was only installed as part of a change, when it should have been also applied installs. This mean that the init flag usage only worked after a previous set command.
```release-note
Fixed a bug on Windows (WSL) with the first-time install of user-mode networking when using the init command, as opposed to set (#20921)
```

Fix user-mode net init flag on first time install

---

pkg/api/server/register_containers.go

I replaced the buggy text with the corresponding text from podman api
https://github.com/containers/podman/blob/2710eaff6a041d9cdeb960c32ce34dcf0ac348aa/pkg/api/server/register_containers.go#L749-L764
The only difference is that I removed the line describing `pod`.
I found a command of how to generate the API web page in this Stackoverflow answer:
https://stackoverflow.com/a/77282199/757777
```
podman run --rm -v $PWD:/spec:Z  docker.io/redocly/cli build-docs pkg/api/swagger.yaml
```
I looked at generated web page and it seems this PR fixes the problem.
Fixes https://github.com/containers/podman/issues/20390
```release-note
None
```

[CI:DOCS] compat api: fix formatting syntax

---

test/system/035-logs.bats
test/system/helpers.bash

Very rare flake, probably caused by my nemesis, podman run -d
Solution: keep the sleep-1 (vs using nanosecond resolution), but make sure we first wait for the output from the container.
Also, bump down the iteration delay in wait_for_output, from 5s to 1. Thanks to Paul for noticing that.
Only [one instance](https://api.cirrus-ci.com/v1/artifact/task/6267658346168320/html/sys-podman-fedora-38-root-host-boltdb.log.html#t--00124) seen in my logs, over many years. Hardly seems worth it, but the fix is easy.
```release-note
None
```

CI: systests: fix flaking --since test

---

docs/tutorials/podman_tutorial.md
docs/tutorials/podman_tutorial_cn.md

the podman tutorial refers to an old httpd image based on Fedora 29.  It is x86_64 only so Apple Silicon Macs and RPI's cannot follow the tutorial.  Switch to nginx
Fixes #20916 
```release-note
None
```

[CI:DOCS]use nginx in podman tutorial

---

contrib/podman-next/fcos-podmanimage/Containerfile

crun-wasm depends on the same epoch:version-release as crun so overriding `crun` but not `crun-wasm` will cause installation issues like:
```
error: Could not depsolve transaction; 1 problem detected:
Problem: package crun-wasm-1.11.1-1.fc39.x86_64 from @System requires crun = 1.11.1-1.fc39, but none of the providers can be installed
- cannot install both crun-102:1.12-1.20231205201336970037.main.19.g90b21dd.fc39.x86_64 from @commandline and crun-1.11.1-1.fc39.x86_64 from @System
- cannot install both crun-102:1.12-1.20231205201336970037.main.19.g90b21dd.fc39.x86_64 from @commandline and crun-1.11.1-1.fc39.x86_64 from updates-archive
- conflicting requests
```
This commit overrides both crun and crun-wasm with what's found in podman-next.
```release-note
None
```

[CI:BUILD] override crun-wasm in fcos + podman-next image build

---

.cirrus.yml
hack/buildah-vendor-treadmill

There's a stanza in .cirrus.yml that only "runs" in
the treadmill cron job ... but that job is long gone.
The task actually runs in the buildah treadmill PR, #13808,
but that's not obvious to someone reading .cirrus.yml.
This is a maintenance burden. Remove it.
Because rootless bud tests are still important, and we
still want to run them in the treadmill PR, modify the
treadmill script itself so it (ugh) injects rootless jobs
into the buildah_bud test matrix. This is super fragile
but acceptable because I am the only one who ever runs
the treadmill script. I will notice if this breaks.
```release-note
None
```

buildah treadmill: cleaner YAML, uglier script

---

.cirrus.yml
contrib/cirrus/win-podman-machine-main.ps1
pkg/machine/e2e/config_test.go
pkg/machine/e2e/config_unix_test.go
pkg/machine/e2e/config_windows_test.go
pkg/machine/e2e/machine_test.go

A simple regression was introduced to the test suite that overrode the default image for hyperv testing.
```release-note
None
```

Fix regression in e2e machine test suite

---

cmd/podman/README.md
cmd/podman/common/create.go
cmd/podman/containers/exec.go
cmd/podman/registry/config.go
cmd/podman/root.go
test/e2e/create_test.go
test/e2e/logs_test.go
test/e2e/run_test.go
test/system/300-cli-parsing.bats
test/system/800-config.bats

see commits
This is only part 1 as there are much more to go but I wanted to keep the review size reasonable.
```release-note
The following cli options have been changed so that multiple values are no longer split by comma. This allows values with comma in them to be used:
podman --module
podman --hooks-dir
podman run/create --annotation
podman run/create --env-file
podman run/create --log-opt
podman run/create --chrootdirs
podman run/create --decryption-key
podman run/create --label-file
podman run/create --device
podman run/create --device-{read,write}-iops
podman run/create --device-{read,write}-bps
podman run/create --blkio-weight-device
podman exec --env-file
```

cli: use StringArray over StringSlice Part 1

---

docs/source/markdown/options/userns.container.md
pkg/domain/infra/runtime_libpod.go
pkg/namespaces/namespaces.go
pkg/util/utils.go
pkg/util/utils_test.go
test/system/170-run-userns.bats

In rootless mode, the host IDs in the `uidmapping` and `gidmapping` options of `--userns=auto` are mapped from an intermediate namespace, just like when using the `--uidmap` and `--gidmap` options.
This means that for a given _host ID_, the user first has to look up the _intermediate ID_ manually. 
The `--uidmap` and `--gidmap` options also support prefixing the _host ID_ in the mapping with the `@` symbol, which means that podman will look up the _intermediate ID_ corresponding to the given _host ID_ and it will map the found _intermediate ID_ to the given _container ID_.
This PR adds the functionality mentioned above to the `uidmapping` and `gidmapping` options in `--userns=auto`.
```release-note
`uidmapping` and `gidmapping` options of `--userns=auto` in rootless mode: 
Added the …
```

Support lookup of intermediate ID for uidmapping and gidmapping in `--userns=auto`

---

test/system/170-run-userns.bats

Broken by #20827.
```release-note
None
```

EMERGENCY: fix broken CI

---

.cirrus.yml
pkg/machine/e2e/init_test.go
pkg/machine/e2e/list_test.go

WSL is unable to set or change CPU/memory settings.  We should not test for them.
```release-note
None
```

Fix WSL machine test regressions

---

.cirrus.yml
contrib/cirrus/CIModes.md

Because the podman machine tests normally run at the end of the chain, it's time consuming for developers to validate machine-only changes. Support a special CI runtime mode, only when a PR is marked as a draft. Update related documentation
Also: Only run machine tests on PRs, never for branches or new tags.
```release-note
None
```

Support a CI-colon-MACHINE mode

---

go.mod
libpod/container.go
libpod/container_internal.go
libpod/container_internal_linux.go

The field `ContainerState.NetworkStatusOld` drags in a dependency on CNI and thereby blocks us from disabling CNI support via a build tag
```release-note
None
```

Remove deprecated field ContainerState.NetworkStatusOld

---

pkg/machine/e2e/config_init_test.go
pkg/machine/e2e/machine_test.go
pkg/machine/e2e/set_test.go

this default value for podman machine disk sizes is 100GB.  On CI platforms where the IO is slow and some operations are not done sparsely, this can really slow things down.
if no disk size is provided by the init command in the test suite, we set it to 11G.
```release-note
None
```

machine e2e : set default disk size to 11

---

test/system/272-system-connection.bats
test/system/330-corrupt-images.bats
test/system/520-checkpoint.bats
test/system/550-pause-process.bats
test/system/helpers.bash
test/system/helpers.registry.bash
test/system/setup_suite.bash

Our test registry (used for login & local registry tests)
was being run using the standard podman tmpdir, hence the
standard podman database, This was then getting clobbered
in the 330-corrupt-images test, which runs "system reset".
We just didn't know this was happening. Until we added
a registry test after the system reset. Oops.
Solution: new helper function podman_isolation_opts()
sets --root, --runroot, *and --tmpdir*. Refactor all
existing --root/--runroot usages. Document.
Next problem: the "network reload" test in 500-networking.bats
did not (could not) know about our registry port, so the
"iptables -F" command reverted that to DROP, so the subsequent
podman-auth in 700-play timed out.
Solution: add a podman-isolated "network reload" to start_registry().
Final problem, because, …

CI: systests: safer isolation in registry & tests

---

pkg/api/handlers/libpod/images_push.go
test/apiv2/12-imagesMore.at

The push binding endpoint wasn't actually writing the output data to the stream when quiet=false and there was no push error.
Do not hard code quiet=true anymore, take into account the user input.
```release-note
Fix a bug in the push binding endpoint where the output wasn't being added to the stream when the push was successful. 
```

Fix push endpoint stream

---

pkg/machine/hyperv/machine.go

After the VM has successfully started, check that gvproxy is still running. If it is not, throw an error and refuse to complete machine start.
[CI:DOCS] I don't think we can deliberately trigger a bad gvproxy start without a bad Podman binary. We could try and kill gvproxy after it starts but before the machine is booted but that's very prone to races.
```release-note
NONE
```

Error on HyperV VM start when gvproxy has failed to start

---

docs/source/markdown/options/device-cgroup-rule.md
docs/source/markdown/options/mount.md
docs/source/markdown/options/network.md
docs/source/markdown/options/volume.image.md
docs/source/markdown/options/volume.md

Began as a review of #20983, a community PR from @krumelmonster
for moving divisive-language footnotes closer to the point
where they're used. In the process, I noticed a lot of poor
markdown, mostly bad use of whitespace. Cleaned it up, added
some italic/bold/tty markdown to options, and cleaned up
some language I found confusing.
Thanks to @krumelmonster for initial PR.
```release-note
Minor documentation cleanup
```

[CI:DOCS] doc cleanup

---

test/e2e/common_test.go
test/e2e/prune_test.go
test/system/050-stop.bats

A number of tests start a container then immediately run podman stop.
This frequently flakes with:
StopSignal SIGTERM failed to stop [...] in 10 seconds, resorting to SIGKILL
Likely reason: container is still initializing, and its process
has not yet set up its signal handlers.
Solution: if possible (containers running "top"), wait for "Mem:"
to indicate that top is running. If not possible (pods / catatonit),
sleep half a second.
Intended to fix some of the flakes cataloged in #20196 but I'm
leaving that open in case we see more. These are hard to identify
just by looking in the code.
```release-note
None
```

CI: safer podman-stop tests

---

libpod/container_config.go
libpod/container_internal_common.go
libpod/options.go
pkg/api/handlers/compat/containers_create.go
pkg/specgen/generate/container_create.go
pkg/specgen/specgen.go
test/compose/etc_hosts/README.md
test/compose/etc_hosts/docker-compose.yml
test/compose/etc_hosts/hosts
test/compose/etc_hosts/setup.sh
test/compose/etc_hosts/teardown.sh
test/compose/etc_hosts/tests.sh
test/compose/test-compose

Fixes #17167
I fixed this issue by applying @Luap99's suggestions - https://github.com/containers/podman/issues/17167#issuecomment-1486959315
> This is needed for it to work:
> 1. Add the `base_hosts_file` option to the container spec and config so it can be set for specific containers.
> 2. Then make sure the docker compat api sets this field to `none` to match the docker behavior.
```release-note
Fix a bug in Docker API where the entries in /etc/hosts file are copied into the container resulting in incompatibility with network alias.
```

Fix Docker API compatibility with network alias

---

contrib/systemd/README.md

Fixes links to example files. Currently, only one link works, and the rest leads to 404.
```release-note
Fix path to example files in contrib/systemd/README.md
```

[CI:DOCS] Fix path to example files in contrib/systemd/README.md

---

docs/source/markdown/podman-save.1.md.in

The docs have this note for the `--compress` flag
> Note: This flag can only be set with --format=docker-dir.
Yet the provided example has `--compress` with `--format=oci-dir`
```release-note
Fix `podman save` command example to use correct image format with `--compress` flag
```

[CI:DOCS] Fix `podman save` command example to use correct image format with `--compress` flag

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/ulimit.container
test/e2e/quadlet_test.go

Add support for using multiple `Ulimit=` options in `.container` files. Before, only the last `Ulimit=` option was used in the podman command.
Update podman-systemd.unit.5 docs to reflect this change.
Add `test/e2e/quadlet/ulimit.container` to e2e tests.
Side note:
It took me a bit to figure out why when I was changing the `ulimit.container` file the quadlet test wasn't failing. It turns out that it hadn't been added to the list of entries in `test/e2e/quadlet_test.go`, so it hasn't actually been a part of the test suite since the `Ulimit=` option was added. I'm not sure if there is an automated way to check if all the files in the `test/e2e/quadlet/` directory are being tested, but it might be worth looking into.
```release-note
Quadlet - Add support for listing Ulimit multiple times in …
```

quadlet container support multiple Ulimit options

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/network.pod

Fixed: https://github.com/containers/podman/issues/21035
```release-note
[Pod] quadlets now support PublishPorts.
```

Allow PublishPorts to be used with [Pod] entry

---

pkg/domain/infra/abi/system_linux.go

it is the wrong check to do here since we need to setup the user namespace even in the case we are running as root without capabilities.
[NO NEW TEST NEEDED] this happens in nested podman
Closes: https://github.com/containers/podman/issues/20908
```release-note
podman running as euid=0 but without CAP_SYS_ADMIN doesn't crash if `podman info` is called multiple times
```

abi: drop check for IsRootless()

---

test/compose/simple_port_map/frontend/Dockerfile
test/compose/slirp4netns_opts/teardown.sh
test/compose/test-compose

@Luap99 raised a concern about test errors being ignored and not causing failures  https://github.com/containers/podman/pull/21013#discussion_r1426535202. cc @edsantiago
* Add traps to report setup, tests, and teardown errors as failures
* Pass through return code of podman commands
* Fix unset variables
* Fix simple_port_map image build when installing flask (PEP 668 - externally managed environment error)
* Ignore kill errors in slirp4netns_opts teardown steps
```release-note
None
```

Improve compose tests to report test errors as failures

---

hack/xref-helpmsgs-manpages
hack/xref-helpmsgs-manpages.t

In the process of adding new functionality to the xref script,
I realized it is much too fragile. It's too easy to make some
minor change that could break the crossrefs, giving us the
illusion of testing.
Solution: add a test suite for the script. Still incomplete,
but an important step toward building confidence.
Requires minor surgery to the script itself
(Note: this test suite is something for me to run. It can't run in CI due to missing dependencies)
```release-note
None
```

[CI:DOCS] Tests for xref-helpmsgs-manpages

---

test/e2e/common_test.go
test/e2e/systemd_test.go

Test "podman start container by systemd" is failed on the system in which rootless users don't have accessibility to journald. Therefore, skip the part that reads journal with journalctl.
```release-note
None
```

e2e: Skip journalctl if journald is unavailable

---

pkg/machine/qemu/machine.go

This is required for mmap'ing on mounted files on MacOS Host. Closes #19639, #20055.
```release-note
podman-machine: MacOS: Mount volumes with mmap enabled
```

Add mmap cache option to QEMU mount

---

pkg/specgen/generate/kube/kube.go

Verify that the separator ':' was found before splitting the string
No
```release-note
None
```
Resolves: #21080

Kube Generate - check options in bind-mount-options exist before accessing

---

.pre-commit-config.yaml
pkg/systemd/parser/unitfile.go
test/e2e/quadlet/line-continuation-whitespace.container
test/e2e/quadlet_test.go

Remove all trailing white spaces from all lines before the line by line processing
Add test
No
```release-note
None
```
Resolves: #21109

Quadlet - fix trailing whitespaces handling

---

pkg/machine/applehv/config.go

small correction to properly lookup a applehv vm on disk.
Fixes: #21090
```release-note
None
```

applehv - fix vm lookup

---

.cirrus.yml
pkg/bindings/test/images_test.go
test/e2e/search_test.go

Nightly crons are failing:
go install golang.org/x/tools/cmd/goimports@latest
...
note: module requires Go 1.18
The correct fix is to vendor goimports, not fetch it. This was done in #14098 and #15896, but those happened after v4.1. My gut feel, I mean careful risk analysis, is that it's safer to just disable Ubuntu than to backport those changes.
```release-note
None
```

[v4.1.1-rhel] CI: disable Ubuntu

---

build_osx.md

I think many podman-MacOS developers will fit into what this doc section describes.
```release-note
None
```

[CI:DOCS] docs/build_osx.md: Describe external gvproxy

---

.cirrus.yml
test/system/505-networking-pasta.bats

All VMs have pasta 2023-12-04, so, remove a skip.
```release-note
None
```

CI: bump VMs

---

pkg/api/handlers/libpod/kube.go
pkg/api/server/register_kube.go
test/e2e/play_kube_test.go

Fix `podman kube play --publish-all` to work in remote environment.
**Before this PR:**
podman-remote doesn't expose a host port (`PORTS`) corresponding to `containerPort` in k8s yaml if `--publish-all` is specified.
```
Pod:
3e5c844a6096f650bb5746415f5d70b5cff59a382d92538a3b6432b3eb4336bc
Container:
97f373367607259edbb1cec627617e518b690cb443a78b921c2aaa98ed1c7616
CONTAINER ID  IMAGE                                        COMMAND               CREATED         STATUS                     PORTS       NAMES
c827dd896efc  localhost/podman-pause:5.0.0-dev-1703821817                        37 seconds ago  Up 35 seconds                          3e5c844a6096-infra
97f373367607  quay.io/libpod/alpine_nginx:latest           nginx -g daemon o...  35 seconds ago  Up 35 seconds (unhealthy) …
```

remote: fix podman-remote kube play --publish-all

---

pkg/machine/provider/platform_darwin.go

Podman 5 will not support QEMU on darwin anymore.  This PR only changes the default from `qemu` to `applehv`.  Code changes to enforce not supporting qemu will come later.
```release-note
The default machine provider for MacOS is the apple hypervisor
```

Set applehv as default darwin provider

---

.github/labeler.yml

Because I want to track this sub-area myself.
BTW...any opinions on cleaning the labels up in this project?  I myself like the "area/XYZ" naming scheme.  It's used in Kubernetes ([example](https://github.com/kubernetes/kubernetes/pull/122557)) and in bootc, etc.
If agreed I'm happy to make the switch here.
```release-note
None
```

[CI:DOCS] ci: Automatically add "podman machine" label

---

pkg/machine/qemu/machine.go

I was trying to debug a failure which was seemingly related to gvproxy failing which I now can't reproduce, and added these while working on it.  Maybe they're useful in the future.
```release-note
None
```

machine/qemu: A few debugging prints

---

hack/xref-helpmsgs-manpages
hack/xref-helpmsgs-manpages.t

Followup to #21055: regression tests for the code that
reads man pages. These are not xref-related at all, just
simple consistency checks on the man page content.
In the process of writing these tests, I also fixed a
longstanding bug where warning messages could be emitted
multiple times, once for each time we read a man page file
(as happens with command aliases).
```release-note
None
```

[CI:DOCS] xref-manpages script: more regression tests

---

cmd/quadlet/main.go
test/e2e/quadlet_test.go

```release-note
Quadlet will not report errors on bogus quadlets.
```

Error messages not being reported unless more then one error present

---

cmd/podman/machine/rm.go
docs/source/locale/ja/LC_MESSAGES/markdown.po
docs/source/markdown/podman-machine-rm.1.md
pkg/machine/applehv/machine.go
pkg/machine/config.go
pkg/machine/define/config.go
pkg/machine/e2e/config_rm_test.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/rm_test.go
pkg/machine/hyperv/machine.go
pkg/machine/keys.go
pkg/machine/qemu/machine.go
pkg/machine/wsl/machine.go
pkg/util/utils.go
pkg/util/utils_test.go

Changes SSH key behavior such that there is a single persisted key for all
machines across all providers. If there is no key that is located at
`.local/share/containers/podman/machine/` then it is created. The keys are
not deleted when the last machine on the host is removed.
The main motivation for this change is it leads to fewer files created on the
host as a result of vm configuration. Having `n` machines on your system doesn't
result in `2n` machine-related files in `.ssh` on your system anymore.
As a result of ssh keys being persisted by default, the `--save-keys` flag on `podman machine rm` will no longer be supported.
Also fixes a bug where if a machine failed during init due to a bad ignition path,
it would not be properly torn down.
```release-note
All future machines created on …
```

machine: Use a single ssh key for all machines

---

pkg/machine/applehv/machine.go
pkg/machine/config.go
pkg/machine/config_test.go
pkg/machine/hyperv/machine.go
pkg/machine/qemu/machine.go
pkg/machine/wsl/machine.go
pkg/util/utils.go
pkg/util/utils_test.go

We shouldn't hardcode `~/.local` - we should use the internal config helper APIs which honor the XDG_DATA_DIR etc. standard environment variables.
```release-note
None
```

machine: use GlobalDataDir helper

---

cmd/podman/compose.go
pkg/machine/hyperv/machine.go
pkg/machine/machine_windows.go
pkg/machine/wsl/machine.go
pkg/machine/wsl/usermodenet.go
pkg/machine/wsl/util_windows.go

Provides Docker API client access, allowing compose to work by default for HyperV. Basically the HyperV equiv of the work done here by #12916.
Closes https://github.com/containers/podman/issues/20761
```release-note
Fixed a bug where Podman machine on HyperV did not allow API forwarding
```

Add API forwarding support for HyperV

---

test/e2e/checkpoint_test.go
test/e2e/exec_test.go
test/e2e/generate_spec_test.go
test/utils/matchers.go

Back when we introduced ExitCleanly(), we couldn't use it
on Debian because of too many runc bugs. Now, early 2024:
- #11784 has been closed-wontfix, so add a runc special-case
in the specific test that triggers it.
- #11785 seems to have gone away? Treat it as fixed.
- #19552 is languishing, so let's just close-wontfix it too and
add another runc special case.
- and, one new rootless-cgroupsV1 exception for a warning msg
that snuck in recently.
```release-note
None
```

e2e: reenable warning checks on Debian

---

cmd/podman/containers/checkpoint.go
cmd/podman/containers/cleanup.go
cmd/podman/containers/init.go
cmd/podman/containers/port.go
cmd/podman/containers/restart.go
cmd/podman/containers/restore.go
cmd/podman/containers/start.go
cmd/podman/containers/stop.go
cmd/podman/containers/top.go
cmd/podman/networks/reload.go
cmd/podman/pods/kill.go
cmd/podman/pods/pause.go
cmd/podman/pods/restart.go
cmd/podman/pods/start.go
cmd/podman/pods/stats.go
cmd/podman/pods/stop.go
cmd/podman/pods/top.go
cmd/podman/pods/unpause.go

Because --latest is not supported on podman-remote commands we should not be showing examples using podman-remote CMD --help with --latest usage, it confuses users. Rather then hacking up the code with if remote else --latest, it is better to just remove information in help messages.
Prevents: https://github.com/containers/podman/issues/21174
[NO NEW TESTS NEEDED] Since normal tests should cover this.
```release-note
None
```

Remove --latest from podman CMD --help output

---

docs/source/markdown/podman-kube-generate.1.md
docs/source/markdown/podman-run.1.md.in

No.
```release-note
None
```
MariaDB example was looking rather dated, and excessive environment variables that where mostly used at build time, and needed a volume to be meaningful. tty wasn't needed.

[CI:DOCS] docs: update mariadb example

---

cmd/podman/compose.go
pkg/machine/hyperv/machine.go
pkg/machine/machine_windows.go
pkg/machine/wsl/machine.go
pkg/machine/wsl/usermodenet.go
pkg/machine/wsl/util_windows.go

Backport of https://github.com/containers/podman/pull/20878 for v4.9.
Provides Docker API client access, allowing compose to work by default for HyperV. Basically the HyperV equiv of the work done here by #12916.
```release-note
Fixed a bug where Podman machine on HyperV did not allow API forwarding
```

[4.8] Add API forwarding support for HyperV

---

libpod/container_internal_common.go

Conditional expression duplicates the
code above, therefore, remove it
Found by Linux Verification Center (linuxtesting.org) with SVACE.
```release-note
None
```

Remove redundant code in generateSpec()

---

cmd/podman/machine/ssh.go

Fixes the error that occurs when executing a command without a machine name when using podman-machine-default.
Fixes: https://github.com/containers/podman/issues/21183 (and fix PR https://github.com/containers/podman/pull/21114)
```release-note
None
```

Ignore the error when running `podman machine ssh <command>`

---

pkg/machine/ignition/ignition.go

fix https://github.com/containers/podman-desktop/issues/5282
With FCOS we have a limit of 2048 files.
But when launching containers like kind containers, we're reaching easily the limit.
(kind create command is not providing
AFAIK as it's inside a dedicated machine, there should not be any limit
The limit should be only set when running a container.
default = unlimited
if using `--pids-limit=<something>` then it's using this value.
If I use docker I have the same behaviour:
```
docker run --rm -it fedora cat  /sys/fs/cgroup/pids.max                                                                                                                                
max
```
```release-note
feat: disable pids-limit inside a podman machine.
```

feat: disable pid max in the podman machine

---

cmd/podman/root.go
docs/source/markdown/podman.1.md
pkg/domain/entities/engine.go
test/system/001-basic.bats
test/system/150-login.bats

Let's support --config option by setting environment variable DOCKER_CONFIG instead of ignoring it for docker compatibility.
Add test case for config option.
```release-note
pdoman run --config option is now supported.
```

cmd: support --config option

---

test/system/060-mount.bats
test/system/250-systemd.bats
test/system/260-sdnotify.bats
test/system/700-play.bats
test/system/helpers.bash

- tmpfs + noswap test: requires noswap feature in kernel.
Check for it, and skip if unimplemented. (Root only.
Rootless test works regardless of kernel).
- podman generate systemd tests: always use --files option,
because otherwise the "DEPRECATED" warning gets written
to the systemd unit file.
- kube play tests: yikes. Fix longstanding bugs when checking
for containers running. This revealed a longstanding bug
in one test: multi-pod YAML never actually worked. Fixed now.
- run_podman(): that new check-for-warnings code we added
in #19878, duh, I skipped it on Debian but should've skipped
when *runc*. Do so now and update the comment. Requires
minor surgery to podman_runtime() helper to avoid
infinite recursion.
```release-note
None
```

System tests: fixes for RHEL8 gating failures

---

test/system/060-mount.bats
test/system/250-systemd.bats
test/system/260-sdnotify.bats
test/system/700-play.bats
test/system/helpers.bash

[manual backport of #21201 because cherrypickbot is napping. No conflicts.]
- tmpfs + noswap test: requires noswap feature in kernel. Check for it, and skip if unimplemented. (Root only. Rootless test works regardless of kernel).
- podman generate systemd tests: always use --files option, because otherwise the "DEPRECATED" warning gets written to the systemd unit file.
- kube play tests: yikes. Fix longstanding bugs when checking for containers running. This revealed a longstanding bug in one test: multi-pod YAML never actually worked. Fixed now.
- run_podman(): that new check-for-warnings code we added in #19878, duh, I skipped it on Debian but should've skipped when *runc*. Do so now and update the comment. Requires minor surgery to podman_runtime() helper to avoid infinite recursion. …

[v4.8] System tests: fixes for RHEL8 gating failures

---

pkg/machine/ignition.go

This is a backport of PR https://github.com/containers/podman/pull/21061 to 4.8 branch for 4.9 release
fix https://github.com/containers/podman-desktop/issues/5282
With FCOS we have a limit of 2048 files.
But when launching containers like kind containers, we're reaching easily the limit.
(kind create command is not providing
AFAIK as it's inside a dedicated machine, there should not be any limit
The limit should be only set when running a container.
default = unlimited
if using `--pids-limit=<something>` then it's using this value.
If I use docker I have the same behaviour:
```
docker run --rm -it fedora cat  /sys/fs/cgroup/pids.max                                                                                                                                
max
``` …

[v4.8] feat: disable pid max in the podman machine

---

libpod/container_internal_common.go
test/system/030-run.bats

Like stated in [PR for crun](https://github.com/containers/crun/pull/1372)
that HostID is what being mapped here, so we should be checking `HostID` instead of `ContainerID`. `v.ContainerID` here is the id of owner of files on filesystem, that can be totally unrelated to the uid maps.
Yes, but this should make more sense?
```release-note
Relative id mapped mount will check which segment of uidmap to use based on host id instead of filesystem id.
```

fix checking of relative idmapped mount

---

pkg/machine/applehv/config.go
pkg/machine/applehv/machine.go
pkg/machine/e2e/config_inspect_test.go
pkg/machine/e2e/config_test.go
pkg/machine/e2e/start_test.go

Fixes: https://github.com/containers/podman/issues/21115
```release-note
Fixed a bug where podman machine commands were not relayed to the correct machine on AppleHV.
```

Assign separate ports for each appleHV machine

---

.cirrus.yml

Port from https://github.com/containers/podman/pull/21224
This is needed to support an upcoming management script change. I've already updated all the workers to be sensitive to this label.
Ref:
https://github.com/cirruslabs/cirrus-cli/blob/master/PERSISTENT-WORKERS.md#reserved-labels
```release-note
none
```

[machine-dev-5] Run mac jobs on labeled hosts

---

.cirrus.yml

This is needed to support an upcoming management script change. I've already updated all the workers to be sensitive to this value.
Ref:
https://github.com/cirruslabs/cirrus-cli/blob/master/PERSISTENT-WORKERS.md#reserved-labels
```release-note
None
```

Run mac jobs on labeled hosts

---

cmd/podman/kube/play.go
test/system/700-play.bats

If a user did not set an equal sign in the annotation that old code
would panic when accessing the second element in the slice.
Picked from main https://github.com/containers/podman/pull/20976/commits/48ab4aec31e6e9db162e6d9bfd32f61a6f367a38.
Partially addresses: https://issues.redhat.com/browse/RHEL-21422
```release-note
None
```

[v4.8] podman kube play: fix broken annotation parsing

---

test/system/260-sdnotify.bats

Add a wait_for_ready() to one kube-play test, to make sure
container output has made it to the journal.
Probably does not fix #18501, but I think it might fix its
most common presentation.
```release-note
None
```

systests: kube with policies test: fix race

---

libpod/container_inspect.go

When preparing container inspection output, ensure we actually have masked paths to work with.
These will only be available on Linux, which is no longer always true as we also support FreeBSD now.
Fixes #21117
```release-note
None
```

[FreeBSD] Fix crash when running podman inspect

---

go.mod
go.sum
vendor/go.mongodb.org/mongo-driver/bson/bsoncodec/registry.go
vendor/modules.txt

The v1.13.0 has been retracted and causes issues when using it. Hence, update to v1.13.1 as suggested upstream [1].
[1] https://github.com/mongodb/mongo-go-driver/releases/tag/v1.13.
```release-note
None
```

fix mongo-driver dependency

---

test/system/125-import.bats
test/system/180-blkio.bats
test/system/200-pod.bats
test/system/280-update.bats

- #15074 ("subtree_control" flake). The flake is NOT FIXED, I
saw it six months ago on my (non-aarch64) laptop. However,
it looks like the frequent-flake-on-aarch64 bug is resolved.
I've been testing in #17831 and have not seen it. So,
tentatively remove the skip and see what happens.
- Closes: #19407 (broken tar, "duplicates of file paths")
All Fedoras now have a fixed tar. Debian DOES NOT, but
we're handling that in our build-ci-vm code. I.e., the
Debian VM we're using has a working tar even though there's
currently a broken tar out in the wild.
Added distro-integration tag so we can catch future problems
like this in OpenQA.
- Closes: #19471 (brq / blkio / loopbackfs in rawhide)
Bug appears to be fixed in rawhide, at least in the VMs we're
using now.
Added distro-integration tag …

CI: reenable tests that are working again

---

docs/source/markdown/podman-container-inspect.1.md.in
docs/source/markdown/podman-events.1.md
docs/source/markdown/podman-image-inspect.1.md
docs/source/markdown/podman-images.1.md.in
docs/source/markdown/podman-machine-inspect.1.md
docs/source/markdown/podman-network-inspect.1.md
docs/source/markdown/podman-network-ls.1.md.in
docs/source/markdown/podman-pod-inspect.1.md.in
docs/source/markdown/podman-pod-ps.1.md.in
docs/source/markdown/podman-ps.1.md
docs/source/markdown/podman-secret-inspect.1.md
docs/source/markdown/podman-secret-ls.1.md.in
docs/source/markdown/podman-volume-inspect.1.md
docs/source/markdown/podman-volume-ls.1.md.in
hack/xref-helpmsgs-manpages
hack/xref-helpmsgs-manpages.t
libpod/events/events.go

Initial impetus was #20958 (ps --format .Label abc). This is
a complicated solution to a simple-seeming problem.
The problem: .Label is a cobra *function*, something I did not
know about nor handle.
Solution: recognize cobra functions. Switch to __complete,
not __completeNoDesc, so we can see the number of arguments
required. Invent new man-page format for documenting functions.
And, finally, start enforcing how functions (and cobra structs)
are documented.
This discovered a never-used completion function, .Recycle(),
in podman-events. Remove it.
```release-note
None
```

Man pages: tighter documenting of --format fields

---

pkg/machine/ignition/ignition.go
pkg/machine/qemu/machine.go
pkg/machine/qemu/options_darwin.go
pkg/machine/qemu/options_freebsd.go
pkg/machine/qemu/options_linux.go
pkg/machine/qemu/options_windows.go

There is a network stability issue in qemu + virtio, affecting some users after long periods of usage, which can lead to suspended queue delivery. Until the issue is resolved, add a temporary recovery service which restarts networking when host communication becomes inoperable. Only qemu based machines on mac activate this service as the issue is understood to be qemu specific. 
Works around issue in #20639
How to verify:
```
export CONTAINERS_MACHINE_PROVIDER=qemu
podman machine rm
podman machine init
podman machine start
podman machine ssh
ifconfig enp0s1 down
```
```release-note
Add a net recovery service to detect and recover from an inoperable host networking issue experienced by some mac qemu users when ran for long periods of time
```

Add a net health recovery service to qemu machines

---

pkg/machine/applehv/machine.go
pkg/machine/hyperv/machine.go
pkg/machine/ignition/ignition.go
pkg/machine/qemu/machine.go

The remote user functionality was not quite correct.  This PR breaks out the accumulation of user descriptions into a separate function.  One odditiy is ignition must be told to NOT create the core user (or it will by default) by "adding" the core user with a set bool.
```release-note
None
```

Set up podman machine remote user correctly

---

cmd/podman/containers/create.go
cmd/podman/containers/run.go
test/system/030-run.bats

Currently, if the container creation failed with
either run or create and you've used --pod with new:
the pod would be created nonetheless. This change ensures
the pod just created is also cleaned up in case
of container creation failure
Fixes #21228
```release-note
Fix a bug (21228) wherein `run --pod new:foo` could leave behind stray containers even if pod creation fails
```

rm pod with run, create if ctr creation failed with --pod new:

---

pkg/machine/applehv/machine.go

When starting podman machine with applehv, this warning is printed: 
WARN[0025] API socket failed ping test
This is due to a bug in applehv.setupAPIForwarding which is not returning
the path to the socket, which causes `WaitAndPingAPI` to be called with
`""` as the socket path, triggering the warning.
This commit changes setupAPIForwarding to be similar to the implementation
in the other machine implementations.
```release-note
none
```

applehv: return socket path from setupAPIForwarding

---

pkg/machine/ignition.go
pkg/machine/qemu/machine.go
pkg/machine/qemu/options_darwin.go
pkg/machine/qemu/options_freebsd.go
pkg/machine/qemu/options_linux.go
pkg/machine/qemu/options_windows.go

Backport of #21262
```release-note
Add a net recovery service to detect and recover from an inoperable host networking issue experienced by some mac qemu users when ran for long periods of time
```

[v4.9] Add a net health recovery service to qemu machines

---

pkg/specgen/generate/container_create.go

[MakeContainer](https://github.com/containers/podman/blob/20b22f8f100c4465ad15db33e8b09f2337327cb6/pkg/specgen/generate/container_create.go#L33) checks many things for error conditions, but for some reason not [the call to SpecGenToOCI](https://github.com/containers/podman/blob/20b22f8f100c4465ad15db33e8b09f2337327cb6/pkg/specgen/generate/container_create.go#L252).
This PR adds the missing check, thus avoiding nil pointer dereference exceptions in the subsequent code that tries to access the `runtimeSpec` returned from `SpecGenToOCI`. With this check in place, if `SpecGenToOCI` fails, one gets much more useful error messages.
```release-note
None
```

Add missing check for errors returned from SpecGenToOCI to MakeContainer

---

pkg/machine/applehv/machine.go

`getRuntimeDir()` (which is also responsible for creating TMPDIR if it doesn't exist) was being called on `Init()` but not on `Start()` which meant that after the host was restarted and TMPDIR was wiped, `startHostNetworking()` would try to start gvproxy and immediately bail.
Fixes #21288 
```release-note
None
```

Ensure podman temp directory is created on Start as well.

---

pkg/machine/applehv/machine.go

While this is potentially a security problem, it solves the issues of users sharing content from the host into containers and attempting to relabel it. From a security point of view this means all content volume mounted from the host into the podman machine on apple hypervisor is read/write from an SELinux point of view if it is volume mounted into the container. If the user attempts to use :Z or :z it will work and relabel the content to be only usable bu the specify container. 
Helps Fix: https://github.com/containers/podman/issues/21269
```release-note
Default labeling for content in podman machines on apple hypervisor is now container_file_t so it can be shared with all containers from an SELinux point of view.
```

Label host volume mounted content in machine as nfs_t 

---

hack/xref-helpmsgs-manpages

[CI:DOCS] podman farm is no longer hidden. Enable doc checks.

---

pkg/specgen/generate/container_create.go
pkg/specgen/generate/oci.go
test/e2e/run_entrypoint_test.go
test/system/030-run.bats

Some OCI runtimes (cf. [1]) may tolerate container images that don't specify an entrypoint together with no entrypoint being specified in the command line. In those cases, it's annoying for the user to have to pass a "" argument to podman.
[1] https://github.com/containers/crun-vm
```release-note
podman-create and podman-run no longer require specifying an entrypoint on the command line when the container image does not define one. In this case, an empty command will be passed to the OCI runtime, and the resulting behavior is runtime-specific.
```

Allow passing the OCI runtime an empty command

---

docs/source/markdown/podman.1.md

Fixes: https://github.com/containers/podman/issues/21071
```release-note
None
```

[CI:DOCS] Warn about whitespace in /etc/subuid and /etc/subgid files

---

libpod/boltdb_state.go
libpod/state_test.go
test/e2e/info_test.go
test/e2e/systemd_activate_test.go
test/system/005-info.bats
test/system/120-load.bats

This is one of the breaking changes in Podman 5.0: removing the ability to create new instances of the old Bolt database. This does not remove support for the database entirely, as existing Bolt databases will still be usable, but all new installs will use SQLite after this point - if Bolt is forced by config, we'll just error.
We don't have plans to outright remove the Bolt code. If that were to happen, it'd be Podman 6.0 at least, and a significant enough change it'd warrant a lot of discussion and planning. We do intend to start winding down support of BoltDB, though, and new features may be added only to SQLite from here on.
I have added an escape hatch via an undocumented environment variable that allows us to continue testing BoltDB in CI (and, if necessary, locally) but I don't …

Deprecate BoltDB, preventing creation of new databases.

---

rpm/podman.spec

The macros in ELN and c10s have the necessary support.
c10s scratch build: https://kojihub.stream.rdu2.redhat.com/koji/taskinfo?taskID=3418218
```release-note
None
```

[CI:BUILD] rpm: use go-rpm-macros on RHEL 10

---

docs/source/markdown/podman-kube-play.1.md.in
pkg/domain/infra/abi/play.go
pkg/util/kube.go
test/e2e/play_kube_test.go

Add volume.podman.io/image annotation to allow setting the source image
Yes
```release-note
Kube Play add support for creating image based volume with K8S PVC
```

Kube Play - allow creating image based volumes

---

.packit.yaml

Podman5 will be shipped only on f40 and higher, so packit downstream tasks should be enabled only for those.
Using `CI:DOCS` as the change only affects downstream Fedora, nothing worth spending CI minutes on.
```release-note
None
```

[CI:DOCS] Packit: podman5 downstream for f40+

---

cmd/podman/machine/info.go
cmd/podman/machine/init.go
cmd/podman/machine/inspect.go
cmd/podman/machine/list.go
cmd/podman/machine/machine.go
cmd/podman/machine/os/apply.go
cmd/podman/machine/os/manager.go
cmd/podman/machine/rm.go
cmd/podman/machine/set.go
cmd/podman/machine/ssh.go
cmd/podman/machine/start.go
cmd/podman/machine/stop.go
cmd/podman/system/reset_machine.go
pkg/machine/e2e/machine_test.go
pkg/machine/os/machine_os.go
pkg/machine/provider/platform.go
pkg/machine/qemu/stubber.go
pkg/machine/shim/claim_darwin.go
pkg/machine/shim/claim_unsupported.go
pkg/machine/shim/host.go
pkg/machine/shim/networking.go
pkg/machine/vmconfigs/config.go

The intial refactor used specifically qemu for testing and infra bring up.  But the whole point was to have things interfaced.  This PR results in an interface experience like podman 4 using the same term `provider` to generically represent 'a provider' like qemu/applehv/etc.
This PR is required to move forward with new providers.
Also renamed pkg/machine/p5 to pkg/machine/shim.
[NO NEW TESTS REQUIRED]
```release-note
None
```

Implement generic providers

---

docs/source/markdown/podman.1.md

The past tense here doesn't make sense.
```release-note
None
```

[CI:DOCS] man: Minor wording tweak for host/connection

---

cmd/podman/farm/create.go
cmd/podman/farm/list.go
cmd/podman/farm/remove.go
cmd/podman/farm/update.go

Don't require the need to connect to an engine/podman machine when doing the farm create, ls, rm, and update commands.
Connection to the engine is required for the farm build command.
Fixes https://github.com/containers/podman/issues/21383
```release-note
Don't require connection to engine for some of the farm subcommands
```

Don't require engine connection for farm

---

cmd/podman/common/create.go
cmd/podman/containers/run.go
docs/source/markdown/options/gpus.md
docs/source/markdown/podman-create.1.md.in
docs/source/markdown/podman-pod-clone.1.md.in
docs/source/markdown/podman-pod-create.1.md.in
docs/source/markdown/podman-run.1.md.in
pkg/domain/entities/pods.go
pkg/specgenutil/specgen.go
test/e2e/run_device_test.go

Somewhat documented here:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html https://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container
Fixes: https://github.com/containers/podman/issues/21156
Don't have access to nvidia GPUS, relying on contributor testing.
```release-note
--gpus will now work with nvidia gpus.
```

Make --gpus work with nvidia gpus

---

pkg/domain/utils/scp.go

While working on #21420 , I noticed that the tag command failed when using `--ssh=native`.  Tracing the process showed:
`execve("/usr/bin/ssh", ["/usr/bin/ssh", "-F", "/home/gordon/.ssh/config", "root@", "podman", "image", "tag", "docker.io/library/alpine:latest", "alpine"], `
Changing url.Hostname() to url.String() is consistent with the previous use, on line 230, and appears to fix that problem.
```release-note
None
```

Fix SSH Host argument in tag command during scp.

---

.cirrus.yml
contrib/cirrus/cirrus_yaml_test.py

This reverts commit f9e8585c5354748b2a77ed65d214adfe7c6ae5fe.
```release-note
None
```

Revert "Enable win podman-machine test failure"

---

pkg/machine/applehv/config.go
pkg/machine/applehv/machine.go
pkg/machine/e2e/config_inspect_test.go
pkg/machine/e2e/config_test.go
pkg/machine/e2e/start_test.go

```release-note
Fixed a bug where podman machine commands were not relayed to the correct machine on AppleHV.
Fixed a bug where the podman machine list and podman machine inspect commands would not show the correct Last Up time on AppleHV
```

[v4.9] AppleHV Backports

---

contrib/pkginstaller/Makefile

this updates the Makefile qemu version to use the qemu 8.2.1 build released at:
https://github.com/containers/podman-machine-qemu/releases/tag/v8.2.1-1
```release-note
None
```

pkginstaller: bump Qemu version to 8.2.1

---

libpod/container_inspect.go
libpod/define/container_inspect.go
pkg/api/handlers/compat/containers.go
test/e2e/healthcheck_run_test.go

When inspecting a container that does not define any health check, the health field should return nil. This matches docker behavior.
```release-note
The `podman inspect` command now returns nil health when inspecting containers without healthchecks.
```

Return nil health when inspecting containers without healthchecks

---

pkg/api/handlers/libpod/images.go
pkg/api/handlers/types.go
pkg/api/server/register_images.go
test/apiv2/10-images.at
test/apiv2/test-apiv2
test/registries.conf

Podman Desktop [1] is looking into improving the user experience which requires to know the source of an image.  Consider the user triggers an image pull and Podman Desktop wants to figure out whether the image name refers to a Red Hat registry, for instance, to prompt installing the RH auth extension.
Since the input values of images may be a short name [2], Podman Desktop has no means to figure out the (potential) source of the image.  Hence, add a new `/resolve` endpoint to allow external callers to figure out the (potential) fully-qualified image name of a given value.
With the new endpoint, Podman Desktop can ask Podman directly to resolve the image name and then make an informed decision whether to prompt the user to perform certain tasks or not.  This for sure can also be used for …

add new libpod/images/$name/resolve endpoint

---

.github/workflows/scan-secrets.yml

Previously when a leak was detected under any circumstance, the workflow would splat out a giant wall of gray, unreadable git-log text.  This often enormous text might contain, somewhere, possibly, maybe, a little tiny snippet of code that leaks a secret.
Improve the situation greatly by providing easy-to-use URLs that covers the relevant changes based on the triggering context (new pr, force-push, or merge).  Store the former (often) giant git-log output into a file and stuff it into the artifacts in case it's ever useful.
```release-note
None
```

[skip-ci] Make leak-detection readable by humans

---

RELEASE_NOTES.md
version/rawversion/version.go

As title says. 
Release notes, version bump, dev bump. 
```release-note
None
```

Bump to v4.9.1

---

cmd/podman/farm/build.go
pkg/domain/entities/types/types.go
pkg/farm/list_builder.go
test/farm/001-farm.bats
test/farm/setup_suite.bash

Fix the way we set skipTLSVerify on the client side to ensure that the push stage in farm build takes into account the configuration in the farm node's registries.conf when the user hasn't set it on the client side.
Fixes https://github.com/containers/podman/issues/21352
```release-note
Only set skipTLSVerfiy for farm build on client side when changed by user.
```

Farm build should read server registries.conf

---

pkg/systemd/parser/unitfile.go
test/e2e/quadlet/health.container
test/e2e/quadlet/hostname.container
test/e2e/quadlet/quotes.container
test/e2e/quadlet_test.go

```release-note
quadlet will strips quotes around values in quadlets.
```
Fixes: https://github.com/containers/podman/issues/20992

Strip key/values of external quotes

---

cmd/quadlet/main.go
docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/parser/unitfile.go
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/template@.container
test/e2e/quadlet/template@.container.d/10-env.conf
test/e2e/quadlet/template@instance.container
test/e2e/quadlet/template@instance.container.d/10-image.conf
test/e2e/quadlet_test.go

As discussed in https://github.com/containers/podman/discussions/17744 we would like to support template systemd unit, and also have a good way to enable them.
This PR makes the service files work, and adds support for `[Install]` to handle enabling default instances as well as individual instances by using symlinks.
```release-note
* support template units in quadlet
```

Support templates in quadlet

---

test/system/030-run.bats

```release-note
Podman in podman will not longer warn on missing content in mounts.conf
```

Add tests to make sure mounts.conf does not warn on missing content

---

.cirrus.yml
pkg/bindings/test/images_test.go
test/e2e/search_test.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/paths.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go

We can't bump runc in this branch, it brings in too many other things that won't build on this old Golang (this branch is still on v1.16).
So, instead, backport the runc patches to this older runc.
The good news: We vendor very little of runc, so this was not all that difficult.
```release-note
NONE
```

[v4.2.0-rhel] Manually patch vendor/ to address CVE-2024-21626

---

.cirrus.yml
hack/golangci-lint.sh

EXPERIMENTAL DO NOT MERGE
```release-note
None
```

Run lint for mac builds

---

pkg/machine/config.go

in various use cases, the required machine dirs are not created.  the machine dirs are runtimedir, datadir, and configdir.  example in Linux would be:
configDir /<HOME>/.config/containers/podman/machine/<provider>
dataDir /<HOME>/.local/share/containers/podman/machine/<provider>
runtimeDir /run/user/1000/podman/machine
now we blindly create them without checking for their existence (because it is faster).
this fixes a bug where runtimedir does not exist on macos after a reboot
```release-note
None
```

create machine dirs at discovery

---

docs/source/markdown/podman-search.1.md.in

The `--stars` option was incorrectly documented as meaning the number of stars to filter by, instead of the minimum number of stars to filter by.
This addresses [Issue #21346](https://github.com/containers/podman/issues/21346).
Yes, the markdown documentation used.
```release-note
Documentation Correction: `--stars` Option in Podman
The documentation for the `--stars` option in the Markdown section has been updated for clarity. Previously, the option was incorrectly described as filtering by the exact number of stars, when it is actually used to specify the minimum number of stars to filter by.
```

[CI:DOCS] Corrected markdown documentation for `--stars`

---

.cirrus.yml
pkg/machine/compression/decompress.go
pkg/machine/e2e/README.md
pkg/machine/e2e/machine_test.go
pkg/machine/e2e/proxy_test.go
pkg/machine/stdpull/local.go
pkg/machine/stdpull/url.go

This PR contains several fixes that allow the applehv podman tests run to completion.
```release-note
None
```

Podman Machine AppleHV CI fixes

---

libpod/container_inspect.go
libpod/pod.go
pkg/specgen/generate/oci_freebsd.go
pkg/specgen/generate/oci_linux.go
test/e2e/container_inspect_test.go
test/e2e/generate_kube_test.go

The current field separator comma of the inspect annotation conflicts with the mount options of --volumes-from as the mount options itself can be comma separated.
When a volumes-from value is ctr1:z,ro, the container inspect shows the following:
```
"VolumesFrom": [
"f91dc2fa04d6cd3997c7b3f5c300ceca39bc37e5c5dbb847e89d342d8141c663:z",
"ro"
],
```
```release-note
None
```

Use semi-colon as the field separator for internal volumes-from inspect annotation

---

.cirrus.yml

Irrespective of reason/cause, a commit was merged into main that broke podman-machine, and went unnoticed for several days.  Improve the situation by including podman-machine testing in the daily cirrus-cron builds.  These are monitored by e-mail when `Total Success` reports a failure.
Also: Add a comment for Windows & Mac build tasks, documenting the reason they don't execute on RHEL release branches.
```release-note
None
```

Include machine-tests in cirrus-cron jobs

---

cmd/podman/machine/set.go
pkg/machine/applehv/stubber.go
pkg/machine/e2e/set_test.go
pkg/machine/hyperv/stubber.go
pkg/machine/qemu/stubber.go
pkg/machine/shim/host.go
pkg/machine/vmconfigs/config.go
pkg/machine/vmconfigs/machine.go

Adds the functionality for `podman machine set --rootful` for AppleHV, QEMU, and HyperV. Abstracts the functionality out to a method of `MachineConfig`. WSL currently uses a function `SetRootful` that is provided by the `machine` package, which will eventually get changed when WSL moves to the refactored structure.
Re-enables the "set rootful with docker sock change" test.
```release-note
None
```

Add functionality for `podman machine set --rootful`

---

test/e2e/network_test.go

These should all work with the latest netavark. The ipvlan case needs a subnet because it does not support DHCP.
```release-note
None
```

test/e2e: unskip netavark macvlan/ipvlan tests

---

pkg/specgen/generate/kube/kube.go
pkg/specgen/generate/kube/volume.go
pkg/specgen/generate/kube/volume_test.go

Implements #21367
```release-note
Added support for memory-backed emptyDir volumes to `podman play kube`. Example:
- name: "myvolume"
emptyDir:
medium: "Memory"
```

Use tmpfs mounts when creating a memory-backed emptyDir volume

---

rpm/podman.spec

With CNI going away in v5, there's no need for dnsname in the rpm.
```release-note
None
```

[CI:BUILD] rpm: remove dnsname

---

.github/workflows/scan-secrets.yml

Original https://github.com/containers/podman/pull/21459
This PR fixes problems observed after merging 21459.  Since testing github-actions was never considered an important aspect of its architecture, we merge and fix afterwards for expediency :confounded:
Note: I realize there _are_ ways to test them, but they're neither easy nor native.
```release-note
None
```

Secret-scanning followup fixes

---

libpod/container_internal.go
test/system/500-networking.bats

Currently we deadlock in the slirp4netns setup code as we try to configure an non exissting netns. The problem happens because we tear down the netns in the userns case correctly since commit bbd6281ecc but that introduces this slirp4netns problem. The code does a proper new network setup later so we should only use the short cut when not in a userns.
Fixes #21477
```release-note
Fix a deadlock in podman container cleanup when the slirp4netns network mode was used with a restart policy of always/unless-stopped/on-failure and a user namespace.
```

fix userns + restart policy with slirp4netns

---

cmd/podman/common/inspect.go
cmd/podman/inspect/inspect.go
cmd/podman/pods/inspect.go
docs/source/markdown/podman-pod-inspect.1.md.in
test/e2e/common_test.go
test/e2e/pod_inspect_test.go
test/system/200-pod.bats

Just like all the other inspect commands that accept multiple args we should just make podman pod inspect output a json array. This makes the code more consistent and removes the extra workaround which was needed before to support this.
```release-note
podman pod inspect now outputs a json array by default just like all the other inspect commands.
```

make podman pod inspect output a json array

---

libpod/networking_common.go
libpod/runtime_ctr.go
test/e2e/container_iface_name_test.go

When interface_name attribute in containers.conf file is set to "device", then set interface names inside containers same as the network_interface names of the respective network.
The change applies to macvlan and ipvlan networks only. The interface_name attribute value has no impact on any other types of networks.
If the interface name is set in the user request, then that takes precedence.
The interface_name attribute in the containers.conf file was added via https://github.com/containers/common/pull/1814.
Fixes: #21313
```release-note
A new global attribute interface_name has been added to the containers.conf file. The default value of the attribute is "". The attribute value can be overridden to "device". This setting is effective for macvlan and ipvlan networks only. When set to …
```

Set interface name to the network_interface name for macvlan and ipvlan networks

---

libpod/container_internal.go
libpod/container_internal_common.go
vendor/github.com/containers/common/pkg/timezone/timezone.go
vendor/github.com/containers/common/pkg/timezone/timezone_linux.go
vendor/github.com/containers/common/pkg/timezone/timezone_unix.go
vendor/github.com/containers/common/pkg/timezone/timezone_windows.go
vendor/modules.txt

Replaces: https://github.com/containers/podman/pull/21077
[NO NEW TESTS NEEDED] Existing tests should handle this.
```release-note
None
```

Reuse timezone code from containers/common

---

pkg/domain/entities/events.go
test/e2e/events_test.go

Fixes: https://github.com/containers/podman/issues/21311
```release-note
podman -remote network events now show network name
```

Show network name network events with podman -remote events

---

cmd/podman/containers/stats.go
docs/source/markdown/podman-stats.1.md.in
libpod/define/containerstate.go
libpod/networking_freebsd.go
libpod/networking_linux.go
libpod/stats_common.go
libpod/stats_freebsd.go
libpod/stats_linux.go
pkg/api/handlers/compat/containers_stats_linux.go
pkg/domain/infra/abi/pods_stats.go
test/apiv2/19-stats.at

This mirrors how the Docker API handles things, allowing us to be
more compatible with Docker and more verbose on the Libpod API.
Stats are given as per network interface in the container, but
still aggregated for `podman stats` and `podman pod stats`
display (so the CLI does not change, only the Libpod and Compat
APIs).
```release-note
BREAKING: API: Container network statistics are now per-interface, and not aggregated. CLI is not affected.
```

Send container stats over API on a per-interface basis

---

cmd/podman/common/netflags.go
cmd/podman/containers/create.go
cmd/podman/pods/create.go
docs/source/markdown/options/network.md
docs/source/markdown/podman-network-create.1.md
pkg/api/handlers/compat/containers_create.go
pkg/domain/infra/abi/network.go
pkg/domain/infra/abi/play.go
pkg/specgen/generate/namespaces.go
pkg/specgen/namespaces.go
pkg/specgen/namespaces_test.go
test/e2e/network_create_test.go

The pasta network mode has been added in podman v4.4 and this causes a conflict with named networks that could also be called "pasta". To not break anything we had special logic to prefer the named network over the network mode. Now with 5.0 we can break this and remove this awkward special handling from the code.
Containers created with 4.X that use a named network pasta will also continue to work fine, this chnage will only effect the creation of new containers with a named network pasta and instead always used the network mode pasta. We now also block the creation of networks with the name "pasta".
```release-note
A named network with the name `pasta` is no longer supported with `--network`, instead it will always use the actual network mode `pasta` (i.e. the pasta binary) to setup the …
```

drop support for "pasta" as a network name

---

.cirrus.yml
contrib/cirrus/setup_environment.sh
test/upgrade/README.md
test/upgrade/helpers.bash
test/upgrade/test-upgrade.bats

No longer bother testing any 2.x or 3.x. Only 4.1 and above.
Remove all CNI-related code. CNI is gone.
Add DatabaseBackend tests, confirming that we can handle
both boltdb and sqlite.
Require BATS >= 1.8.0, and use "run -0" to do exit-status checks.
Update docs.
[ marked WIP because this is going to fail. I need help figuring out what to do.]
```release-note
None
```

Upgrade tests: reenable, but revamped

---

docs/source/markdown/podman-systemd.unit.5.md

Quadlet `[Network]` does not accept `Options=key` for `podman network create --opt key`. Options have to be provided in `key=value` format, where the `=` is required even though the value may be empty.
One usage example is `Options=isolate=true`. In this case, passing `netavark` an empty `isolate` value may be a valid/parseable setting: `Options=isolate=`, equivalent to `Options=isolate=false`.
This commit documents the explicit `Options=key=value` usage. Compare to `[Network]` tests, which use `key=value`.
Usage verified locally by inspecting the generated network in `/run/user/${UID}/systemd/generator/example-network.service` and `podman network inspect systemd-example` using podman v4.9.2 and netavark v1.10.2.
See
- https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#ne …

[CI:DOCS] Fix Quadlet Options=key=value documentation/example

---

pkg/systemd/parser/unitfile.go
test/e2e/quadlet/comment-with-continuation.container
test/e2e/quadlet_test.go

No
```release-note
None
```
Resolves: #21555

Quadlet - do not look for line continuation in comment lines

---

test/apiv2/10-images.at
test/apiv2/20-containers.at
test/e2e/config.go
test/e2e/config_amd64.go
test/e2e/config_arm64.go
test/e2e/config_ppc64le.go
test/e2e/images_test.go
test/e2e/rmi_test.go
test/system/125-import.bats
test/system/220-healthcheck.bats
test/system/250-systemd.bats
test/system/320-system-df.bats
test/system/build-systemd-image
test/system/build-testimage
test/system/helpers.bash

Simply because it's been a while since the last testimage
build, and I want to confirm that our image build process
still works.
Added /home/podman/healthcheck. This saves us having to
podman-build on each healthcheck test. Removed now-
unneeded _build_health_check_image helper.
testimage: bump alpine 3.16.2 to 3.19.0
systemd-image: f38 to f39
- tzdata now requires dnf **install**, not reinstall
(this is exactly the sort of thing I was looking for)
PROBLEMS DISCOVERED:
- in e2e, fedoraMinimal is now == SYSTEMD_IMAGE. This
screws up some of the image-count tests (CACHE_IMAGES).
- "alter tarball" system test now barfs with tar < 1.35.
TODO: completely replace fedoraMinimal with SYSTEMD_IMAGE in all tests.
```release-note
None
```

new testimage and systemd-image

---

cmd/podman/machine/set.go
pkg/machine/applehv/stubber.go
pkg/machine/config.go
pkg/machine/define/setopts.go
pkg/machine/hyperv/stubber.go
pkg/machine/qemu/stubber.go
pkg/machine/shim/host.go
pkg/machine/vmconfigs/config.go
pkg/machine/vmconfigs/machine.go
pkg/machine/wsl/machine.go

Sets up USB passthrough for machine. Additionally moves `SetOptions` out from `pkg/machine/config.go` to its own file in
`pkg/machine/define/setopts.go`.
```release-note
Users on QEMU can now take advantage of usb passthrough using `podman machine init --usb` and `podman machine set --usb`
```

machine: USB passthrough

---

pkg/machine/applehv/stubber.go
pkg/machine/applehv/vfkit.go

Changes the signature for `getDefaultDevices` to take a `vmconfigs.MachineConfig`.
```release-note
None
```

machine: change getDefaultDevices signature

---

contrib/cirrus/runner.sh
hack/golangci-lint.sh

**Depends on:** https://github.com/containers/podman/pull/21372
Performing native linting on Windows is quite complex and will require updating the `winmake` PS script.  As a stop-gap, and until we have an entirely native build -> test chain, run Windows linting prior to the cross-build (on Linux).  This isn't a perfect solution, but it does find lots of lint that requires cleaning.  To that end, enforcement of cleanliness is temporarily bypassed by in a single revert-friendly commit.
```release-note
None
```

Windows-cross linting

---

pkg/machine/e2e/config_init_test.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/init_windows_test.go
pkg/machine/hyperv/stubber.go

Fix a bug where if a vm exists, created by some other process/user, and you attempt to make a podman machine with the same name.
```release-note
None
```

Fail if vm exists in hyperv already

---

.cirrus.yml

we were fighting a flake earlier, so the mac test was removed again and the suspected commit was removed.  this turns the test back on so we can see if we pass cleanly.  Also lets turn on as much windows as possible and hyperv.
```release-note
None
```

Re-enable testing

---

pkg/machine/define/errors.go
pkg/machine/e2e/config_test.go
pkg/machine/e2e/init_test.go
pkg/machine/shim/host.go
pkg/machine/vmconfigs/config.go
pkg/machine/vmconfigs/machine.go

we should not panic podman when it has to deal with a podman4 machine config.  instead, we throw a soft error for `machine ls` and in all other cases, we throw a hard error stating that the machine config is incompatible.
a future PR will provide instructions on how to recover from this. current idea is something like `podman machine reset` which blows everything away machine-wise.
```release-note
None
```

Don't panic on podman4 machine configs

---

pkg/domain/utils/scp.go

This PR fixes #21239 
This change requires changes to the containers-common repo, and I will send that PR shortly.  To support CI, those changes are included in a separate commit which I will remove before this PR is merged.
```release-note
None
```

podman-image-scp: Load images without the use of a temporary file.

---

docs/source/markdown/podman-build.1.md.in

Closes: https://github.com/containers/podman/issues/21605
[CI:DOCS] clarify podman build git repo handling
```release-note
None
```

docs: clarify when a URL is treated as a git repo

---

pkg/domain/utils/scp.go

SSH uses 22 as default so it is really not necessary to require the port. The backend code already does this but the parsing in the frontend always tried to parse the port.
[NO NEW TESTS NEEDED] This would require actual remote host ssh setup in CI so it is not possible to be check but I verified it locally.
Fixes https://issues.redhat.com/browse/RHEL-17776
```release-note
podman image scp no longer requires a ssh port in the remote location URL and correctly defaults to port 22.
```

image scp: don't require port for ssh URL

---

libpod/container_exec.go
libpod/container_internal.go
libpod/oci.go
libpod/oci_conmon_common.go
libpod/oci_conmon_exec_common.go
libpod/oci_missing.go
test/e2e/run_memory_test.go

Conmon writes the exit file and oom file (if container
was oom killed) to the persist directory. This directory
is retained across reboots as well.
Update podman to create a persist-dir/ctr-id for the exit
and oom files for each container to be written to. The oom
state of container is set after reading the files
from the persist-dir/ctr-id directory.
The exit code still continues to read the exit file from
the exits directory.
Fixes https://github.com/containers/podman/issues/13102
```release-note
Use the conmon persist-dir for reading the container's oom file if oom killed.
```

Use persist dir for oom file

---

.cirrus.yml
contrib/cirrus/cirrus_yaml_test.py

***Depends on https://github.com/containers/podman/pull/21551***
```release-note
None
```

Enforcing mac tests

---

.cirrus.yml
test/e2e/play_kube_test.go
test/e2e/run_networking_test.go
test/e2e/run_test.go

Package diffs [here](https://github.com/containers/automation_images/pull/327#issuecomment-1938711328)
And, runc-1.12 broke our seccomp e2e tests (runc now calls getcwd(),
which is the dummy syscall blocked for testing seccomp). Switch
to blocking link() instead.
Also, disable v4.1.0 upgrade tests. They're hanging, and I have
no idea why, and have wasted most of a day debugging.
Fixes: #21546
New rawhide kernel. Everyone please cross fingers in hopes that #21504 is gone. [EDIT: nope. Still hangs.]
```release-note
None
```

Bump CI VMs to ones with netavark 1.10.3

---

libpod/container_internal_common.go
test/e2e/run_userns_test.go

Closes: #21608
```release-note
Now Podman chowns an existing volume to the correct uid/gid when the target path already exists in the container
```

libpod: correctly map UID/GID for existing dirs

---

.cirrus.yml
pkg/machine/e2e/machine_test.go

**Depends on:**
- https://github.com/containers/podman/pull/21551
- https://github.com/containers/podman/pull/21562
```release-note
None
```

Enable windows and PM windows testing

---

pkg/machine/applehv/stubber.go
pkg/machine/e2e/set_test.go
pkg/machine/hyperv/stubber.go
pkg/machine/qemu/stubber.go
pkg/machine/wsl/stubber.go

Adds a check for all providers that will only allow the user to execute the `podman machine set` command if the machine is in the `Stopped` state. 
Additionally made the following WSL changes:
- re-enables the `opts.USBs` check in `SetProviderAttrs` to prevent the user from modifying unsupported settings 
- removes a TODO for a check on init to see if the user passed a USB device. This check is already done higher up the stack in a generic fashion. 
```release-note
Users will no longer be able to execute `podman machine set --<setting>` if the machine is not in the `Stopped` state.
```

machine: `machine set` only in `Stopped` state

---

.cirrus.yml

**Depends on:**
- https://github.com/containers/podman/pull/21551
- https://github.com/containers/podman/pull/21562
- https://github.com/containers/podman/pull/21564
```release-note
None
```

Enable freebsd + release-testing tasks

---

docs/source/markdown/podman-kube-play.1.md.in
libpod/container_inspect.go
libpod/define/annotations.go
libpod/pod.go
pkg/domain/infra/abi/play.go
pkg/specgen/generate/kube/kube.go
pkg/specgen/generate/oci_freebsd.go
pkg/specgen/generate/oci_linux.go
test/e2e/container_inspect_test.go
test/e2e/generate_kube_test.go
test/e2e/play_kube_test.go

The reserved annotation io.podman.annotations.volumes-from is made public to let user define volumes-from to have one container mount volumes of other containers.
The annotation format is: io.podman.annotations.volumes-from/tgtCtr: "srcCtr1:mntOpts1;srcCtr2:mntOpts;..."
Fixes: containers#16819
```release-note
Annotation io.podman.annotations.volumes-from can be used to define list of volumes-from to have one container mount volumes of other containers. The format of the annotation is io.podman.annotations.volumes-from/targetContainer: "sourceContainer1:mntOptions1;sourceContainer2:mntOptions;...".
```

Add volumes-from support using annotation in kube yaml

---

pkg/machine/ocipull/ociartifact.go
pkg/machine/ocipull/pull.go
pkg/machine/ocipull/source.go

This PR fixes a small bug in pulling disk artifacts where the machine os was accidently being set to GOOS instead of "linux".  Also removed the manifest type verification because it served no purpose.
```release-note
None
```

Fix small bug in ocipull

---

contrib/cirrus/mac_cleanup.sh

According to https://go.dev/ref/mod#module-cache golang will leave
behind read-only bits.  It was observed that these cause the find/rm
cleanup operations to fail fail with `permission denied` on thousands
of files.  This is preventing cleanup of cruft from unrelated Cirrus-tasks
leading to unnecessary occupation of critical, local-ssd storage space.
Fix this by ensuring the user has at least write access to the entire
contents of `$TMPDIR` and `$HOME`, `ci` subdirs.
```release-note
None
```

Allow CI user to cleanup own files

---

test/e2e/events_test.go
test/e2e/prune_test.go
test/e2e/restart_test.go
test/e2e/rm_test.go
test/e2e/run_test.go
test/system/050-stop.bats
test/system/160-volumes.bats

Continuing to see CI failures of the form "StopSignal SIGTERM
failed to stop container in 10 seconds". Work around those,
either by adding "-t0" to podman stop, or by using Expect(Exit(0))
instead of ExitCleanly().
Addresses, but does not close, #20196
```release-note
None
```

More test tweaks to avoid "StopSignal ... 10 seconds" warning

---

test/e2e/checkpoint_test.go
test/e2e/common_test.go
test/e2e/events_test.go
test/e2e/exec_test.go
test/e2e/healthcheck_run_test.go
test/e2e/mount_test.go
test/e2e/pod_initcontainers_test.go
test/e2e/prune_test.go
test/e2e/restart_test.go
test/e2e/run_cleanup_test.go
test/e2e/run_test.go
test/e2e/run_volume_test.go
test/e2e/volume_plugin_test.go

This removes a lot of boilerplate, but also ensures that every stop test that is not directly testing podman stop or podman pod stop uses `-t0` for quick, error-free stopping.
```release-note
NONE
```

Add a helper for stopping pods and containers in E2E

---

pkg/machine/ocipull/pull.go

If users cancel the image download with CTRL-C for example then the blob dir will stay around. The next time we run the download we should just start the download again and not complain about the existing directory.
[NO NEW TEST NEEDED]
```release-note
None
```

machine: ocipull do not error if downloaddir exists

---

docs/source/markdown/podman-stats.1.md.in
hack/xref-helpmsgs-manpages

Followup to:
- #21060, where I added new struct checks (but did not make them fatal)
- #21534, which added per-interface stats and a .Network field,
but its documentation was slightly off
```release-note
Very minor tweak to the .Network format field in podman-stats, not worth mentioning in release notes IMO
```

[CI:DOCS] man-page xref: make nested-structure warnings fatal

---

cmd/podman/machine/init.go
pkg/machine/config_test.go
pkg/machine/connection/add.go
pkg/machine/connection/connection.go
pkg/machine/connection/connection_test.go
pkg/machine/e2e/init_test.go

Validate the names with our name regex that we also use for
containers/pods. While we technically do not need to be that strict, I
think it makes sense to match containers. The most important bit of this
validation is that we exclude the use of / and \ which breaks all our
file paths as we just use this in the name an when machine write the
file it ends up being in a subdir which breaks the reading side. Also
other special characters could cause trouble for the URL parsing in the
machine connection URL.
also see the other cleanup commits
```release-note
The podman machine name and remote username must match this regex: `[a-zA-Z0-9][a-zA-Z0-9_.-]*`
```

machine init: validate machine name and username

---

cmd/podman/machine/reset.go
docs/source/markdown/podman-machine-reset.1.md
docs/source/markdown/podman-machine.1.md
pkg/machine/config.go
pkg/machine/e2e/config_reset_test.go
pkg/machine/e2e/reset_test.go
pkg/machine/shim/host.go

Podman machine reset is a new command that will "reset" your podman machine environment.  Reset is defined as:
* Stop and Remove all VMs
* Remove the following directories: - configuration dir i.e. ~/.config/containers/podman/machine/qemu - data dir i.e. ~/.local/.share/containers/podman/machine/qemu
When deleting, if errors are encountered, they will be batched and spit out at the end.  Podman will try to proceed even in error in doing what it was told.
```release-note
Introduce `podman machine reset` command for cleaning podman machine environment
```

Introduce Podman machine reset

---

pkg/machine/qemu/machine.go
pkg/machine/qemu/machine_unix.go
pkg/machine/qemu/options_windows_amd64.go
pkg/machine/qemu/options_windows_arm64.go
pkg/machine/qemu/stubber.go

Bugfixes extracted from a bigger change https://github.com/containers/podman/pull/21594
This change:
* cleanups some old Windows bits used in machine 4 times;
* converts socket path into cross platform compatible in gvproxy command
* fixes typo in log
* resolves QEMU settings from machine config QEMUHypervisor part instead of QEMUStubber. In my testing it was always resulting in {nil} QMP socket and incorrect machine termination on Windows. I haven't yet checked it on Linux.
```release-note
None
```

Improve cross platform support in QEMU machine sources

---

cmd/podman-mac-helper/uninstall.go

Fixed to remove not only plist but also `/var/run/docker.sock`(symlink) when `podman-mac-helper uninstall` command is executed.
Fix: https://github.com/containers/podman/issues/20650 and https://github.com/containers/podman-desktop/issues/5324 .
```release-note
Fix `podman-mac-helper uninstall` command does not remove docker.sock symlink.
```

Fixed `podman-mac-helper uninstall` to remove docker.sock symlink

---

docs/source/markdown/podman-unshare.1.md

[CI:DOCS] Fix up example description of podman-unshare.1.md

---

cmd/podman/images/pull.go
docs/source/markdown/options/retry-delay.md
docs/source/markdown/options/retry.md
docs/source/markdown/podman-pull.1.md.in
pkg/api/handlers/compat/images.go
pkg/api/handlers/libpod/images_pull.go
pkg/bindings/images/types.go
pkg/bindings/images/types_pull_options.go
pkg/domain/entities/images.go
pkg/domain/infra/abi/images.go
pkg/domain/infra/tunnel/images.go
test/system/150-login.bats
test/system/helpers.registry.bash

Fixes: https://github.com/containers/podman/issues/19770
```release-note
podman pull now supports --retry and --retry-delay.
```

Allow podman pull to specify --retry and --retry-delay

---

pkg/machine/define/usb.go
pkg/machine/qemu/command/command.go
pkg/machine/qemu/command/command_test.go
pkg/machine/qemu/command/helpers.go
pkg/machine/qemu/command/qemu_command_test.go
pkg/machine/qemu/config.go
pkg/machine/qemu/config_test.go
pkg/machine/qemu/machine.go
pkg/machine/qemu/machine_unsupported.go
pkg/machine/qemu/machine_windows.go
pkg/machine/qemu/options_freebsd.go
pkg/machine/qemu/options_freebsd_amd64.go
pkg/machine/qemu/options_freebsd_arm64.go
pkg/machine/qemu/options_linux_amd64.go
pkg/machine/qemu/options_linux_arm64.go
pkg/machine/qemu/options_windows.go
pkg/machine/qemu/options_windows_amd64.go
pkg/machine/qemu/options_windows_arm64.go
pkg/machine/qemu/stubber.go
pkg/machine/vmconfigs/config.go
pkg/machine/vmconfigs/machine.go

Macs no longer support QEMU as a provider, build tag it out.
```release-note
Podman machine on Mac no longer supports QEMU as a provider. Instead, AppleHV is used. 
```

Build tag out QEMU for Darwin

---

.packit.yaml

When I added commit b73eec88, I was under the impression that the packit config for a downstream Fedora branch should only contain the tasks for that particular branch. But, that's not quite the case.
For all downstream tasks like `koji builds` and `bodhi updates`, Packit now uses the config from the `rawhide` branch on dist-git https://src.fedoraproject.org/rpms/podman/tree/rawhide . So, this means all downstream tasks including the ones for F38 and F39 which use a different version of Podman, need to be specified in the packit config file that lands in the `rawhide` branch.
This commit re-enables koji and bodhi tasks for all Fedora branches. Enabling F38 and F39 koji and bodhi will still end up building from the sources in dist-git, so it's not a conflict to have them enabled on an …

[skip-ci] Packit: Update downstream task targets

---

.packit.yaml

For downstream tasks like koji and bodhi, the packit config is pulled
from the `rawhide` branch of dist-git. So, these tasks shouldn't be
specified in places which won't end up in rawhide.
Ref: https://github.com/containers/podman/pull/21743
Labelling as [skip-ci] as this doesn't need to go through upstream CI.
Thanks to @majamassarini.
```release-note
None
```

[v4.9] [skip-ci] Packit: remove koji and bodhi tasks for v4.9

---

test/system/040-ps.bats
test/system/070-build.bats

There's currently no way to inspect failures of the
parallel-remove test (#21742). Add debugging ability.
Also, clean up nasty red warnings
```release-note
None
```

System tests: enable debugging for parallel-rm test

---

libpod/container_internal_common.go

This effectively fix errors like "unable to upgrade to tcp, received 409" like #19930 in the special case where podman itself is running rootful but inside a container which itself is rootless.
Here is how to reproduce my variant of #19930 which this pull request tries to fix:
- podman must be configured to run container in rootless mode
- start a first "podman server" container, which will run a rootful podman inside a rootless container:
```
> podman run -t -i --rm --pull=always --privileged --name=podman-server -v /shared-volume quay️️.io/podman/stable podman system service -t 0 unix:///shared-volume/podman.sock 
Trying to pull quay.io/podman/stable:latest...
️Getting image source signatures
Copying blob sha256:511a60f584271fcdbcda6b21445093519de4eb54ee41c3f46823dc3799ab485d
Copying …
```

Fix running container from docker client with rootful in rootless podman

---

contrib/cirrus/logcollector.sh

aardvark-dns, netavark and passt are installed on both debian and fedora. cri-o-runc is not installed anymore and it just uses the normal runc package on debian. This makes sure we correctly log all the package versions on debian as well.
```release-note
None
```

cirrus logcollector: update package list

---

pkg/machine/compression/sparse_file_writer.go
pkg/machine/compression/sparse_file_writer_test.go

machine: add sparse file writer

---

Makefile

This is needed until there is netavark support on FreeBSD
```release-note
None
```

Build with CNI support on FreeBSD

---

cmd/podman-wslkerninst/main.go
cmd/winpath/main.go
contrib/cirrus/runner.sh
hack/golangci-lint.sh
pkg/bindings/containers/term_windows.go
pkg/machine/e2e/config_test.go
pkg/machine/e2e/init_windows_test.go
pkg/machine/fedora_windows.go
pkg/machine/gvproxy.go
pkg/machine/gvproxy_unix.go
pkg/machine/gvproxy_windows.go
pkg/machine/hyperv/stubber.go
pkg/machine/hyperv/volumes.go
pkg/machine/hyperv/vsock/vsock.go
pkg/machine/machine_windows.go
pkg/machine/shim/claim_unsupported.go
pkg/machine/wsl/declares.go
pkg/machine/wsl/machine.go
pkg/machine/wsl/stubber.go
pkg/machine/wsl/usermodenet.go
pkg/machine/wsl/util_windows.go
pkg/specgen/winpath_windows.go
pkg/systemd/notifyproxy/notifyproxy.go
pkg/systemd/notifyproxy/notifyproxy_test.go
pkg/terminal/console_windows.go

Fix lint on Windows.
This may not pass CI initially, I don't know if we can make this work as cross-compile; we need CGo.
```release-note
NONE
```

Fix Lint on Windows and enable the job

---

go.mod
pkg/machine/compression/compression_test.go
pkg/machine/compression/config.go
pkg/machine/compression/decompress.go
pkg/machine/define/image_format.go
pkg/machine/define/image_format_test.go
pkg/machine/ignition/ignition.go
pkg/machine/ocipull/ociartifact.go

given that we are moving to building our own machine images, we have decided to use zstd compression as it is superior in speed to the alternatives.  as such, this pr adds zstd to our machine code; and also has to account for dealing with sparseness on darwin; which the default zstd golang library does not.
```release-note
None
```

zstd now default compression for podman machine

---

cmd/podman/machine/inspect.go
docs/source/markdown/podman-machine-inspect.1.md
pkg/machine/config.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/inspect_test.go
pkg/machine/vmconfigs/machine.go

Adds `ConnectionInfo()` to the `MachineConfig` and fills out `InspectInfo` accordingly. Additionally fixes the "inspect with go format" test.
```release-note
`ConnectionInfo` is now properly displayed in `machine inspect`
```

machine: Add `ConnectionInfo` to inspect

---

cmd/podman/machine/inspect.go
pkg/machine/applehv/machine.go
pkg/machine/shim/host.go

Remove TODO to swap `Rootful` in Inspect with `HostUser`
Additionally removes the following TODOs:
It is unnecessary to remove the vfkit logfile in the provider-specific `Remove` function. Vfkit is fed the default logfile provided by `mc.LogFile` which is removed by the generic `Remove` function.
Removes TODO regarding moving the location of Stop. False TODO.
```release-note
None
```

machine: Remove unnecessary TODOs

---

pkg/machine/gvproxy.go
pkg/machine/shim/host.go

When gvproxy exits it will delete the pidfile itself so we need to account for that and juts ignore the case, it just means gvproxy was able to exit successfully on its own.
Also remove the useless defer and return the error so we can get an error exit code not just a print on stderr.
Currently it shows this error which is not helpful to any user: unable to clean up gvproxy: "unable to read gvproxy pid file /run/user/1000/podman/gvproxy.pid: open /run/user/1000/podman/gvproxy.pid: no such file or directory"
[NO NEW TESTS NEEDED] TODO: make machine tests check stderr for such things.
```release-note
None
```

pkg/machine: ignore gvproxy pidfile not exists error

---

cmd/podman/system/events.go
docs/source/markdown/podman-events.1.md
libpod/events.go
libpod/events/config.go
test/apiv2/27-containersEvents.at
test/e2e/events_test.go
test/system/090-events.bats

taken over https://github.com/containers/podman/pull/21047 + extra commit for fixes
```release-note
`podman events --format "{{json .}}"` output should more now more docker compatible and include the time and timeNano fields. 
```

make podman events json output more docker compatible

---

.cirrus.yml
contrib/cirrus/cirrus_yaml_test.py

There's are sometimes conflicting purposes in podman CI:
1. Have the pipeline proceed in an orderly and progressive manner
to sometimes save resources and unnecessary runtime.
2. Complete all testing as quickly as possible in support of
human-developers moving on to other areas of work.
3. Ideally/hopefully, accomplish both items above safely,
preventing untested and/or unintended changes from merging.
This commit shifts the balance of these slightly more toward the second
point.  It rearranges most CI tasks into essentially three buckets with
a single (new) aggregation task in-between the first two:
1. Build + Verify all the things
2. Test all the things
3. Minor/accessory things
The intention is that while we may unnecessarily spin some number of
testing tasks while others have failed, …

Rearrange CI tasks for safety + efficiency

---

cmd/podman/machine/inspect.go
cmd/podman/machine/rm.go
docs/source/markdown/podman-machine-inspect.1.md
pkg/machine/config.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/rm_test.go
pkg/machine/qemu/machine.go
pkg/machine/vmconfigs/machine.go

Addresses the following TODOs that were found in the podman 5 machine refactor code:
- We no longer care about the image provenance in `InspectInfo`, so remove the `Image` field
- Address whether `providerRm` failures should be a hard error
- Address whether a failure to remove machine files should be a hard error
- Implement QEMU-specific file removal
- Remove system connections first and remove machine config files last, this allows us to "see" the machine still in `podman machine list` if there was an error removing any prior files
```release-note
`ConfigPath` and `Image` are not longer provided to the user when they execute `podman machine inspect`. Users can also no longer use `{{ .ConfigPath }}` or `{{ .Image }}` when doing `podman machine inspect --format`
```

machine: Address some QEMU TODOs

---

test/e2e/manifest_test.go
test/e2e/push_test.go
test/system/012-manifest.bats

These are immediately-applicable parts of #21571 , so that tests which require gzip compression to be used don’t rely on the `containers.conf` default.
That this does work with Zstd can be verified in #21571.
```release-note
None
```

Adjust some tests to work with Zstd in containers.conf

---

pkg/machine/hyperv/stubber.go
pkg/machine/hyperv/vsock/vsock.go
pkg/machine/ignition/ready.go

```release-note
none
```
Addresses two race conditions:
1. Listen / connect wait by listen before starting the VM
2. Device initialization race where the vsock protocol is not yet initialized

Fix race conditions in hyperv backend

---

docs/source/markdown/podman-secret-create.1.md

[CI:DOCS] Adds example for secret creation from environment variable

---

pkg/machine/compression/sparse_file_writer.go
pkg/machine/compression/sparse_file_writer_test.go

Instead of using a state machine, use a more straight-line code; also document and enforce various invariants.
The net effect of this code is exactly the same as the previous implementation,  except:
- the operation after Write() returns an error might differ
- If the file ends with zeroes, we don't `Seek(-1)`, and we don't create a hole at all if it is too small, preferring to save a syscall.
But this formulation is hopefully easier to prove correct.
Also adds more tests, to see behavior in more cases, and to actually test that this does create holes.
---
Alternatively, see https://github.com/mtrmac/libpod/tree/sparse for a commit series that ends with exactly the same code, but justifies every step individually.
But in this case I think it’s easier to just read the end product with its …

Reformulate sparseWriter

---

pkg/api/handlers/compat/containers_create.go
test/apiv2/20-containers.at

Closes #21754
See the discussion in the above mentionned issue.
```release-note
None
```

Ignore docker's end point config when the final network mode isn't bridge

---

.cirrus.yml

Broken by #21777: "set -u" causes clone_script to barf with
CIRRUS_PR: unbound variable
See [log](https://cirrus-ci.com/task/6607825602871296)
```release-note
None
```

Fix nightly cron checks

---

pkg/machine/qemu/command/command.go
pkg/machine/qemu/command/qemu_command_test.go
pkg/machine/qemu/stubber.go

Fixes https://github.com/containers/podman/issues/21544
This change migrates to new QEMU stream netdev added in 7.2.0. It also unifies how gvproxy is used in QEMU and AppleHV.
This change will require manual fixes to QEMU machine configurations migrated from 4.x, but 5.0 version is the only good point to do so. My previous work was with preserving old FD code, but it makes the codebase really messy.
It replaces my previous work from:
https://github.com/containers/podman/pull/21252
https://github.com/containers/podman/pull/17473
https://github.com/containers/podman/pull/18488
```release-note
QEMU machine uses Unix domain socket netdev device type
```

Change QEMU netdev to Unix domain socket

---

pkg/util/utils.go
pkg/util/utils_test.go
test/system/030-run.bats

Currently if a user specifies a negative time to stop a container the code ends up specifying the negative time to time.Duration which treats it as 0. By settine the default to max.Unint32 we end up with a positive number which indicates > 68 years which is probably close enough to infinity for our use case.
Fixes: https://github.com/containers/podman/issues/21811
```release-note
None
```

Fix podman stop -t -1 CID

---

test/e2e/common_test.go
test/e2e/generate_kube_test.go
test/e2e/manifest_test.go
test/e2e/port_test.go
test/e2e/pull_test.go
test/e2e/push_test.go
test/e2e/run_test.go
test/e2e/save_test.go
test/e2e/testdata/sigstore-registries.d-fragment.yaml

Too many tests use port 5000. Although there's a putative GetPortLock()
it seems to be unreliable, and we often get what appear to be collisions
between tests.
A proper solution would be to pseudorandomly allocate ports, verify
that they're not being reused, Sprintf() these everywhere that
needs them, and sprinkle some powdered cinnamon on top.
This is not that proper solution.
Fixes: #20655 
(Being tested in #17831 also. Three runs so far, no flakes)
```release-note
None
```

CI: e2e: use distinct ports, not just 5000

---

cmd/podman/machine/info.go
go.mod

There is no reason for us to use v2 here, we use v3 already in most places. The go-openapi dependency still uses v2 so we do not get rid of it yet but it looks like they migrated upstream so once a new version is released there and finds our way to us then we should get some nice binary size reduction.
```release-note
None
```

vendor update gopkg.in/yaml.v2 to v3

---

Makefile
contrib/pkginstaller/Makefile
contrib/pkginstaller/package.sh
pkg/machine/ocipull/policy.go
pkg/machine/ocipull/policy.json
pkg/machine/ocipull/policy_unix.go
pkg/machine/ocipull/policy_windows.go
pkg/machine/ocipull/pull.go

see commits
```release-note
podman machine init requires a policy.json file to pull images from the container registry. A default policy.json file is located in our repo at pkg/machine/ocipull/policy.json which should be installed for the user. When building podman via Makefile `MACHINE_POLICY_JSON_DIR` should be used to set the directory where the installed policy.json file will be located. This can be relative directory from the podman binary.
```

pkg/machine: add custom policy.json logic

---

contrib/pkginstaller/Makefile
contrib/pkginstaller/hvf.entitlements
contrib/pkginstaller/package.sh
contrib/pkginstaller/vfkit.entitlements

The vfkit binary shipped with podman 5.0-rc3 can't start virtual machines, see
https://github.com/containers/podman/issues/21842
The entitlements are overwritten during the signing process.
```release-note
This fixes an issue with the `vfkit` hypervisor causing this problem on Apple hardware:
$ podman machine start
Starting machine "podman-machine-default"
Error: vfkit exited unexpectedly with exit code 1
```

Add missing vfkit entitlement

---

.cirrus.yml
contrib/win-installer/build.ps1

Source: https://github.com/containers/automation_images/pull/331#issuecomment-1966677347
Kludgy VM build, because rawhide rc6 kernel is still not stable.
I would like to merge this anyway, because the rawhide hang is
hurting us badly. (I am not guaranteeing that this fixes the hang).
```release-note
None
```

new vms, with rc6 rawhide kernel

---

.cirrus.yml
DOWNLOADS.md

This is needed by podman desktop CI, to ensure their 'latest' testing jobs continuously and exactly match the podman repository state + related binaries.
```release-note
None
```

[CI:BUILD] Expose as-tested Mac/Windows repository state

---

cmd/podman/machine/client9p.go
pkg/machine/e2e/basic_test.go
pkg/machine/hyperv/stubber.go
pkg/machine/hyperv/volumes.go

Before, we required that the mount target exist and be a directory for the 9p mount to successfully complete, which is not how things are supposed to work - the user should be able to mount anywhere. This should just be a simple mkdir, but with FCOS the root directory is immutable so we need to undo that before we can mkdir, and unfortunately we don't have a library that can do chattr (and I didn't want to drag in a new dependency just for that), so let's be gross and add it to the SSH command. I aggressively dislike this but it does work.
[NO NEW TESTS NEEDED] Can worry about getting a more generic mount test together for Machine later.
```release-note
Fixed a bug where HyperV could not mount volumes to some directories.
```

Ensure HyperV 9p mounts work when a dir doesn't exist

---

pkg/machine/vmconfigs/machine.go

As indicated in #21849, loading the machine config can flake/fail with an EOF JSON error indicating an incomplete file.  Address the issue by atomically writing the config.  This way, it is not possible to load an incomplete or partially written file.  The lock can be acquired later on to sync state.
[NO NEW TESTS NEEDED] as it's a hard-to-hit race.
Fixes: #21849
```release-note
Fix a race condition in podman machine to avoid loading an incomplete config file.
```

machine config: make write atomic

---

pkg/machine/cleanup.go
pkg/machine/hyperv/stubber.go
pkg/machine/shim/host.go
pkg/machine/wsl/stubber.go

Matt found a bug where if a machine start did not run to completion, a gvproxy was left around running.  This gvproxy then subsequently stopped the next attempt to start.
```release-note
None
```

Clean up gvproxy if machine start fails

---

rpm/podman.spec

```release-note
None
```
Ref: https://src.fedoraproject.org/rpms/podman/pull-request/131#commit_list

[CI:BUILD] rpm: spec file updates from Fedora dist-git

---

cmd/podman/common/completion.go
cmd/podman/networks/inspect.go
docs/source/markdown/podman-network-inspect.1.md
pkg/api/handlers/compat/networks.go
pkg/api/handlers/swagger/responses.go
pkg/bindings/network/network.go
pkg/domain/entities/engine_container.go
pkg/domain/entities/network.go
pkg/domain/entities/types/network.go
pkg/domain/infra/abi/network.go
pkg/domain/infra/tunnel/network.go
test/e2e/network_create_test.go
test/e2e/network_test.go
test/e2e/run_networking_test.go
test/system/500-networking.bats

Like docker podman network inspect should output the information of running container with their ip/mac address on this network. However the output format is not docker compatible as this cannot include all the info we have and the previous output was already not compatible so this is not new.
New example output:
```
[
{
...
"containers": {
"7c0d295779cee4a6db7adc07a99e635909413a390eeab9f951edbc4aac406bf1": {
"name": "c2",
"interfaces": {
"eth0": {
"subnets": [
{
"ipnet": "10.89.0.4/24",
"gateway": "10.89.0.1"
},
{
"ipnet": "fda3:b4da:da1e:7e9d::4/64",
"gateway": "fda3:b4da:da1e:7e9d::1"
}
],
"mac_address": "1a:bd:ca:ea:4b:3a"
}
}
},
"b17c6651ae6d9cc7d5825968e01d6b1e67f44460bb0c140bcc32bd9d436ac11d": {
"name": "c1",
"interfaces": {
"eth0": {
"subnets": [
{
"ipnet": "10.89.0.3/24", …
```

podman network inspect: include running containers

---

.cirrus.yml
contrib/cirrus/mac_setup.sh
contrib/cirrus/win-podman-machine-test.ps1
pkg/machine/e2e/machine_pull_test.go
pkg/machine/e2e/machine_test.go
pkg/machine/e2e/machine_wsl_test.go
pkg/machine/gvproxy_unix.go
pkg/machine/ignition/ignition.go
pkg/machine/ocipull/ociartifact.go

We used to use ignition to perform any customization required for podman machine because our input was a generic FCOS image.  Now that we are building our own images, some of this customization can be migrated to the Containerfile itself and be less of a burden in our code at boot up.
At the time of this PR, the Containerfile can be found at https://github.com/baude/podman-machine-images/tree/main.  It is only present for a so-called daily image.  There is little liklihood that this would the final location for the Containerfile so consider it a working version only.
Note: the change to the pull image name is so PRs are not immediately broken that are already in the queue.
[NO NEW TESTS REQUIRED]
```release-note
None
```

Move ignition functions into Containerfiles

---

.cirrus.yml
test/upgrade/test-upgrade.bats

Upgrade-from-v4.1 was temporarily disabled in #21618: we brought
in new CI VMs, and v4.1 setup no longer works. Nobody quite
understands why, and we've hit diminishing returns in the
investigation (#21863). The current thinking is that it
is related to netavark, and versions < 1.3 do not work
in the current f39 VMs. (No clue why, because f39 kernel
did not change in #21618).
Anyhow, reenable the pre-4.8 upgrade test, using v4.3.1
which has netavark-1.4.0 which seems to work fine. For now.
Also, some upgrade test cleanup:
- Skip, not fail, if initial setup fails. Makes for less noisy logs.
- Remove duplicate --pid=host
- Ports: 808x -> 909x, because 8081 is used by restraint on 1mt
```release-note
None
```

Reenable boltdb upgrade tests

---

.cirrus.yml
contrib/cirrus/mac_runner.sh

It works (verified in #17831). Imperfectly, because Macs don't have a useful awk, so we can't get timestamps. I will, in time, look into adding the timestamp functionality to logformatter itself.
Also imperfect because it's not linkifying: source code paths are dead text. I need to fix that, too, in logformatter, by having it recognize /Users/Mac paths.
Imperfect as it may be, it was quick, and I think could provide good bang for the buck in these Mac-intensive debugging days.
```release-note
None
```

CI: run logformatter on mac

---

pkg/machine/ocipull/ociartifact.go

If we hit an error here, it will be really useful to know
- That we're trying to fetch a container image
- Which image we're trying to fetch
```release-note
None
```

machine/ociartifact: Include image name in error

---

cmd/podman/common/completion.go
cmd/podman/containers/create.go
cmd/podman/containers/run.go
docs/source/markdown/options/log-driver.md
libpod/container_api.go
libpod/define/config.go
libpod/oci_conmon_attach_common.go
libpod/oci_conmon_common.go
libpod/options.go
test/system/450-interactive.bats

it works in a similar way to passthrough but it allows to be used also on a TTY.
conmon support: https://github.com/containers/conmon/pull/465
Closes: https://github.com/containers/podman/issues/20767
```release-note
Add a new logging mode --passthrough-tty that works like passthrough but can be used with TTYs
```

logging: new mode -l passthrough-tty

---

cmd/podman/machine/rm.go
cmd/podman/machine/set.go
pkg/machine/applehv/machine.go
pkg/machine/applehv/stubber.go
pkg/machine/hyperv/stubber.go
pkg/machine/qemu/machine.go
pkg/machine/qemu/stubber.go
pkg/machine/shim/host.go
pkg/machine/vmconfigs/machine.go
pkg/machine/wsl/stubber.go

Previously, the locks were on the provider layer, which doesn't make a vm operation with a config file update atomic. Move them up a layer, so the entire function locks while doing provider and config operations.
This adds a Remove and a Set function to the shim layer.
[NO NEW TESTS NEEDED] Unsure how to test this
```release-note
None
```

Move locks to shim layer

---

test/system/060-mount.bats

Checking for the mountdir is not relevent, a recent c/storage change[1] no longer deletes the mount point directory so the check will cause a false positive. findmnt exits 1 when the given path is not a mountpoint so let's use that to check.
[1] https://github.com/containers/storage/pull/1828/commits/3f2e81abb38926d9b908528412c25fa2e199b6b9
```release-note
None
```

test/system: fix mount external container test

---

test/e2e/manifest_test.go

fix an assumption in the test, that the --compression-format is unchanged from the original image.
Instead validate that all the required architectures are part of the manifest.
```release-note
None
```

test: fix manifest e2e test assumption

---

cmd/podman/machine/init.go
docs/source/markdown/podman-machine-init.1.md.in
pkg/machine/define/initopts.go
pkg/machine/e2e/basic_test.go
pkg/machine/e2e/config_init_test.go
pkg/machine/e2e/info_test.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/init_windows_test.go
pkg/machine/e2e/inspect_test.go
pkg/machine/e2e/list_test.go
pkg/machine/e2e/machine_pull_test.go
pkg/machine/e2e/os_test.go
pkg/machine/e2e/proxy_test.go
pkg/machine/e2e/reset_test.go
pkg/machine/e2e/rm_test.go
pkg/machine/e2e/set_test.go
pkg/machine/e2e/ssh_test.go
pkg/machine/e2e/start_test.go
pkg/machine/e2e/stop_test.go
pkg/machine/ocipull/ociartifact.go
pkg/machine/shim/diskpull/diskpull.go
pkg/machine/shim/host.go
pkg/machine/wsl/stubber.go

Use machine image as specified in containers.conf
For podman machine init, deprecate the --image-path option for --image.
--image now accepts the correct image from containers.conf
Also, add the ability to specify an OCI image from the --image flag using the docker:// transport.
```release-note
The --image flag replaces the now deprecated --image-path flag for podman machine init.
```

Use machine image as specified in containers.conf

---

go.mod
go.sum
libpod/events/config.go
libpod/events/events.go
libpod/events/journal_linux.go
libpod/networking_linux.go
libpod/runtime.go
test/apiv2/20-containers.at
test/e2e/unshare_test.go
test/system/250-systemd.bats
test/system/252-quadlet.bats
test/system/270-socket-activation.bats
test/system/500-networking.bats
test/system/505-networking-pasta.bats
test/system/550-pause-process.bats
test/system/helpers.network.bash
vendor/github.com/containers/common/libimage/events.go
vendor/github.com/containers/common/libimage/pull.go
vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/default.go
vendor/modules.txt

Test swapping the default from Slirp4netns to Pasta
```release-note
Connectivity for rootless containers is now provided by Pasta by default, instead of slirp4netns
```

Vendor c/common pasta branch for testing

---

CONTRIBUTING.md
contrib/cirrus/pr-should-include-tests
contrib/cirrus/pr-should-include-tests.t

Old way: edit commit message, add magic string, re-push
New way: repo maintainer adds a Github label to PR, hits Rerun
I've looked and looked for the history behind this script
and why I didn't do it this way in the first place. I've
concluded that I just never thought of it.
```release-note
None
```

CI: must-add-tests check: use GH label, not text

---

libpod/reset.go
test/e2e/system_reset_test.go

when performing a system reset with containers that run somewhere where a soft kill wont work (like sleep), containers will wait 10 seconds before terminating with a sigkill.  But for a forceful action like system reset, we should outright set no timeout so containers stop quickly and are not waiting on a timeout
Fixes #21874
```release-note
podman system reset stops containers immediately instead of waiting on a possible timeout
```

Use stop timeout of zero for system reset

---

.cirrus.yml

Without this CI fails on FreeBSD build since 13.2 image family no longer exists in cloud
```release-note
none
```

Fix CI: Bump to FreeBSD 13.3 (13.2 vanished)

---

test/e2e/common_test.go

Note I really do not expect this to pass, I only submit in order to gather some data and see if this shows us more bugs. In the long term something like this should be included. There are many code paths which only do logrus but still exit 0 so this should catch more bugs.
```release-note
None
```

test/e2e: check for stderr errors in cleanup()

---

pkg/machine/ocipull/ociartifact.go

As outlined in #21856, it can take a number of seconds until an image gets pulled.  That is because init is hitting the registry first to look up the image.  To improve the UX, add a new line indicating what happens.
Fixes: #21856
```release-note
None
```

machine init: print output to improve UX

---

Makefile
contrib/cirrus/logformatter
pkg/machine/e2e/config_init_test.go
pkg/machine/e2e/machine_test.go

Lots of small special-case tweaks to logformatter because Macs
have to be different.
Also fix:
- Wrong slash in printf-newline, leading to gray [It] blocks
- echo gitCommit, so we can link to sources
- --image-path is deprecated
```release-note
None
```

logformatter: fixes for Macintosh

---

cmd/podman/common/completion.go
cmd/podman/system/events.go
docs/source/markdown/podman-events.1.md
libpod/events/config.go
libpod/events/events.go
libpod/events/journal_linux.go
libpod/runtime.go
pkg/domain/entities/events.go
test/apiv2/10-images.at
test/system/090-events.bats

Commit 03f6589f3 added basic support for pull-error event from libimage but it contains several problems:
1. storing the error as error type prevents it from being unmarshalled, thus change it to a string
2. the error was never propagated from the libimage event to the podman event struct
3. the error message was not wired into the cli and API
This commit fixes these problems.
Fixes #21458
```release-note
podman events now supports a new pull-error event
```

properly implement pull-error event status

---

test/e2e/checkpoint_test.go

Two test flakes in the past month. Looks like the usual race
between "run -d" and "assume the container is ready". I don't
know if this will resolve them, but it's still a good idea.
* fedora-38 : int podman fedora-38 root host boltdb
* [03-04 12:22](https://api.cirrus-ci.com/v1/artifact/task/6542391172136960/html/int-podman-fedora-38-root-host-boltdb.log.html#t--Podman-checkpoint-podman-checkpoint-and-restore-container-with-file-locks--1)
* [02-14 16:27](https://api.cirrus-ci.com/v1/artifact/task/5004742884065280/html/int-podman-fedora-38-root-host-boltdb.log.html#t--Podman-checkpoint-podman-checkpoint-and-restore-container-with-file-locks--1)
```release-note
None
```

e2e: fix potential race in file-locks test

---

.cirrus.yml
DOWNLOADS.md

Fix [artifacts task error](https://cirrus-ci.com/task/6595797815394304):
```
Failed to upload artifacts:
rpc error: code = FailedPrecondition
desc = Artifacts size is too big!
```
This reverts commit 698219cf9882ff0d229cd10bab0afd03ba09884b.
```release-note
None
```

Revert "Expose as-tested Mac/Windows repository state"

---

rpm/podman.spec

Currently, the `podmansh(1)` manual is shipped by the `podman` package.  It
makes one wonder where the binary is, since they can read the manual.
Fixes: 3efaffae43cb1650 ("New command: podmansh")
Signed-off-by: Debarshi Ray <rishi@fedoraproject.org>
```release-note
The podmansh(1) manual is now in the podmansh sub-package.
```

[CI:BUILD] rpm: Put the podmansh(1) manual in the podmansh sub-package

---

cmd/podman/machine/list.go
pkg/machine/config.go
pkg/machine/e2e/list_test.go
pkg/machine/shim/host.go

units.BytesSize expects byte size as argument.
Therefore, added code to convert vm.Memory and vm.DiskSize to byte size using strongunits.
Fix: https://github.com/containers/podman/issues/21917
```release-note
Fix problem with `podman machine list` returning wrong units for Memory and Disk size
```

Fix problem with `podman machine list` returning wrong units for Memory and Disk size

---

test/e2e/manifest_test.go
test/system/520-checkpoint.bats
test/system/700-play.bats

Most of them look like our usual "assume too much about run -d".
One of them is just an unexpected warning, a push retry. Remove
the ExitCleanly() from that test, just rely on Exit(0).
The other two have to do with podman logs, which we know can lag.
Add a short 1-second retry loop.
```release-note
None
```

CI: try to fix more flakes

---

.cirrus.yml
go.mod
go.sum
vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
vendor/modules.txt

Commit 3e7ca842a (PR #21483) manually patched runc/libcontainer in vendor, which is OK but creates a maintenance problem down the line.
Instead, let's
- create [a branch](https://github.com/projectatomic/runc/tree/podman-v4.2.0-rhel) based on runc commit used here;
- backport the CVE-2024-21626 fixes;
- vendor the above branch here.
As a side note, all this mess could have been avoided if https://github.com/opencontainers/runc/pull/3508 was backported to a stable runc branch. Alas, this was never requested.
Also, re-enable the CI task which was disabled due to manual vendor changes (commit 47b995b10).
```release-note
NONE
```

[v4.2.0-rhel] Use a branched runc instead of manual vendor changes

---

pkg/machine/ocipull/policy.go

When we set a relative path (i.e. ".") it should be resolved next to binary so we need to get the base dir. If we join it directly like it did before you get a path like .../podman/policy.json where podman is the podman executable so it is not a directory and thus could not contain the policy.json file.
ref #21964
```release-note
None
```

pkg/machine: fix relative DefaultPolicyJSONPath

---

pkg/machine/compression/decompress.go
pkg/machine/compression/generic.go
pkg/machine/compression/gzip.go
pkg/machine/compression/sparse_file_writer.go
pkg/machine/compression/sparse_file_writer_test.go
pkg/machine/compression/uncompressed.go
pkg/machine/compression/xz.go
pkg/machine/compression/zip.go
pkg/machine/compression/zstd.go
pkg/machine/e2e/machine_test.go

- Fix spurious reports about failures to close a destination underlying `SparseWriter`, fixing https://github.com/containers/podman/pull/21936#issuecomment-1981567103
- Modify `SparseWriter` not to motivate callers to rely on `ErrClosed`, in the first place; first mentioned in https://github.com/containers/podman/pull/21592#discussion_r1496744844
- Fail on more errors, don’t just ignore/log them, to be more certain we got the full contents we need.
Cc: @l0rd 
```release-note
None
```

Close error handling

---

docs/source/Commands.rst

Add the farm command to the commands list so
that it is rendered correctly in readthedocs.
```release-note
Add farm command to command list for readthedocs
```

[CI:DOCS] Add farm command to commands list

---

.cirrus.yml
.github/workflows/mac-pkg.yml
contrib/pkginstaller/.gitignore
contrib/pkginstaller/Makefile
contrib/pkginstaller/README.md
contrib/pkginstaller/package.sh

Build universal Podman binary and installer for Mac. Update GitHub action to build it too.
```release-note
None
```

[CI:BUILD] Build universal Podman binary for Mac installer

---

Makefile
contrib/win-installer/build.ps1
contrib/win-installer/podman.wxs
contrib/win-installer/process-release.ps1

- Sets default search location to always be the peer directory
+ make podman-remote now creates binaries that work the same as release zips
- Updates release zip to match expected search location
- Updates win installer to include the file if present in the repo cross-build archive
```release-note
none
```

Complete policy.json inclusion (Also add to win installer)

---

.cirrus.yml
version/rawversion/version.go

Replaces https://github.com/containers/podman/pull/21970 
```release-note
None
```

Bump to 5.0.0-rc5

---

libpod/container_internal_common.go
pkg/api/handlers/compat/containers_create.go
test/apiv2/20-containers.at

Picked from #21820 
this backports in branch 4.9 (which apparently is the last version fedora 38 and 39 will get) two docker CLI compatibility fixes merged recently in podman 5:
https://github.com/containers/podman/pull/21487
https://github.com/containers/podman/pull/21789
Note that I would also hope to see this in RHEL's 4.9 branch as we would need these two fix in the next podman upgrade in RHEL too.
Addresses:
https://issues.redhat.com/browse/RHEL-26664 - RHEL 8.10 0day [v4.9] Backport two docker CLI compatibility fixes
https://issues.redhat.com/browse/RHEL-28636 - RHEL 9.4 0day [v4.9] Backport two docker CLI compatibility fixes
```release-note
None
```

Backport two docker CLI compatibility fixes

---

docs/tutorials/performance.md

Add note for RHEL 8.5 overlay fs support.
Yes, documentation only.
```release-note
Update performance.md tutorial to include RHEL 8.5 support for native overlayfs.
```

Add note to performance.md for RHEL 8.5 overlayfs support

---

.cirrus.yml

The container image build automation no longer lives here, it was moved to containers/image_build.
Also strip out a few lingering comments referencing gitleaks, which was removed from automation use.
```release-note
None
```

[CI:DOCS] Remove outdated references

---

docs/source/markdown/podman-generate-systemd.1.md
docs/source/markdown/podman-systemd.unit.5.md

docs: quadlet: improve docs on root/rootless dirs
Make the docs more explicit on which directories are read for root and
rootless users to avoid confusion [1].
[1] https://github.com/containers/podman/discussions/20218#discussioncomment-8721351
---
docs: generate-systemd: add clarification statement
Based on user feedback, I think it's time to clarify that there are no
plans to remove generate-systemd.  Deprecation here means that the
command will not receive new features but only urgent bug fixes.
---
```release-note
Improve documentation of Quadlet and generate-systemd.
```

Quadlet docs

---

docs/source/Reference.rst
pkg/api/server/doc.go

Also update the website to display the correct swagger doc for the right version, the 5.0 swagger file will not exist until we branch but I added it anyway so we do not forget it.
```release-note
None
```

[CI:DOCS] update API doc version to 5.0.0

---

pkg/machine/ocipull/ociartifact.go

Adding the final machine endpoint as quay.io/podman/machine-os in the Podman code.  As a reminder, we decided we would set this in containers conf once things settle down and this code would then be removed.
```release-note
None
```

Add final machine endpoint

---

contrib/cirrus/pr-should-include-tests
winmake.ps1

For consistency with [linux/osx makefile](https://github.com/containers/podman/blob/main/Makefile#L788) I have added the `win-gvproxy` target as an alias of the already existing `win-sshproxy`.
```release-note
NONE
```

Add target win-gvproxy in winmake.ps1

---

Makefile
contrib/pkginstaller/Makefile
contrib/pkginstaller/package.sh
contrib/win-installer/build.ps1
contrib/win-installer/podman.wxs
contrib/win-installer/process-release.ps1
pkg/machine/ocipull/policy.go
pkg/machine/ocipull/pull.go

we are having second thoughts about *requiring* a policy.json on podman machine hosts.  we are concerned that we need to work out some more use cases to be sure we do not make choices now that limit us in the near term future. for example, should the policy files be the same for container images and machine images? And should one live on the host machine and the other live in the machine?
therefore, if a policy.json *is* present in the correct location, we will use and honor it; however, if it does not, we will allow the machine image to be pulled without a policy.
```release-note
policy.json is not required for podman machines, though if present, will be honored in pulling
```

do not require policy.json

---

RELEASE_NOTES.md

Took a lot longer than it should have, but we have release notes.
```release-note
NONE
```

[CI:DOCS] Add release notes for v5.0.0

---

pkg/machine/e2e/inspect_test.go
pkg/machine/env/dir.go
pkg/machine/machine_common.go
pkg/machine/machine_windows.go
pkg/machine/shim/networking.go
pkg/machine/shim/networking_unix.go
pkg/machine/shim/networking_windows.go
pkg/machine/vmconfigs/machine.go
pkg/machine/vmconfigs/sockets.go
pkg/machine/vmconfigs/sockets_darwin.go
pkg/machine/wsl/machine.go
pkg/machine/wsl/stubber.go
pkg/machine/wsl/usermodenet.go

Fixes  #21899
Change API socket to be machine name isolated
- Fixes conflicts such as removal of second machine deleting a socket of a the first machine while it's running
- Move API socket into runtime directory for consistency
- Add API and gvproxy sockets to removal list
- Cleanup related logic
```release-note
Fixes a problem where podman machine rm removes a socket used by other machines - #21899
```

Change API socket to be machine name isolated

---

pkg/domain/infra/abi/play.go
pkg/specgen/generate/kube/kube.go
pkg/specgen/generate/kube/play_test.go

```release-note
When using a `RestartPolicy` together with a `livenessProbe`, the policy is now passed
down to the individual containers. Previously, this wasn't the case. (#20903)
```
---
Healthchecks, defined in a .yaml file as livenessProbe did not had any effect. They were executing as intended, containers were marked as unhealthy, yet no action was taken. This was never the intended behaviour, as observed by the following comment:
> if restart policy is in place, ensure the health check enforces it
A minimal example is tracked in #20903 with the following YAML:
```yaml
apiVersion: v1
kind: Pod
metadata:
name: ubi-httpd-24
spec:
restartPolicy: Always
containers:
- name: ubi8-httpd
image: registry.access.redhat.com/rhscl/httpd-24-rhel7:2.4-217
livenessProbe:
httpGet:
path: "/"
port: …
```

Pass pod restart policy to individual containers

---

rpm/podman.spec

This commit bumps containers-common dep such that passt and netavark become hard deps for podman on fedora 40+.
Ref: https://bugzilla.redhat.com/show_bug.cgi?id=2269148
With this commit, f40+ envs will use the min name-version-release for containers-common-extra while other deps will use whatever's available. This change can be reverted after a few releases to keep conditionals to a minimum.
```release-note
None
```

[skip-ci] rpm: update containers-common dep on f40+

---

go.mod
pkg/bindings/images/build.go

This switches the gzip implementation over to using a faster version for context compression which gives a 3x speed up for a largish context
For a build context of around 3GiB send to a remote over Unix socket.
```
time podman build  ...
...
real	3m19.866s
user	2m31.238s
sys	0m16.211s
```
```
time podman-patched build  ...
...
real	1m8.367s
user	0m56.179s
sys	0m1.099s
```
This matches docker performance on my machine.
So I initially started this investigation by stracing the podman process on the client side. I noticed a large amount of `write` calls with a small  buffer (246bytes). It seems that the gzip module in GoLang seems to aggressively call flush for every block that is encoded causing a much large syscall overhead. I tried adding buffers but the flush propagates down. So in …

Use faster gzip for compression for 3x build speedup for large context send to remote 

---

libpod/util.go
test/apiv2/20-containers.at
test/apiv2/test-apiv2

The issue is a regression in an interactive exec session (/exec/{id}/start endpoint) where the values for the HTTP headers are incorrect:
Content-type: tcp
Upgrade: application/vnd.docker.raw-stream
Expected:
Content-type: application/vnd.docker.raw-stream
Upgrade: tcp
```release-note
Fixed a bug that caused incorrect header values when upgrading a connection for an interactive exec session.
```

fix invalid HTTP header values when hijacking a connection

---

build_windows.md

Updated build_windows.md with a new section that documents how to build and run the windows podman client without requiring MSYS.
```release-note
None
```

[CI:DOCS] Add doc to build podman on windows without MSYS

---

pkg/machine/wsl/fedora.go
pkg/machine/wsl/machine.go
pkg/machine/wsl/usermodenet.go

- Switches from the current wsl-fedora images used by the 4.x stream to a 5.x WSL machine os stream produced by https://github.com/containers/podman-machine-wsl-os
- Adds subscription-manager and qemu-user-static
- Also Includes a switch from XZ to ZSTD for significantly improved fetch performance 
+ The increase in packages brought  xz extraction to almost 10 minutes (the xz golang is significantly less efficient than xz utils) , now 10 secs with zstd
The ultimate goal is to move from http to an oci pull, but this is targeted for 5.1
```release-note
none
```

Switch to 5.x WSL machine os stream using new automation

---

Makefile

This allows to build a static `podman-remote` binary for the host architecture.
```release-note
None
```

Makefile: add target `podman-remote-static`

---

libpod/runtime_ctr.go

Cherry pick from #20329
Addresses: https://issues.redhat.com/browse/RHEL-14744 and https://issues.redhat.com/browse/RHEL-14743
When containers are created with a named volume it can deadlock because the create logic tried to lock all volumes in a loop, this is fine if it only ever creates a single container at any given time. However because we multiple containers can be created at the same time they can cause a deadlock between the volumes. This is because the order of the loop is not stable, in fact it is based on the order of how the volumes were specified on the cli.
So if you create two containers at the same time with `-v vol1:/dir2 -v vol2:/dir2` and the other one with `-v vol2:/dir2 -v vol1:/dir1` then there is chance for a deadlock.
Now one solution could be to order the volumes …

[v4.4.1-rhel] libpod: fix deadlock while parallel container create

---

go.mod
go.sum
vendor/github.com/containers/buildah/CHANGELOG.md
vendor/github.com/containers/buildah/changelog.txt
vendor/github.com/containers/buildah/define/types.go
vendor/github.com/containers/buildah/internal/volumes/volumes.go
vendor/modules.txt

As the title says.  Bumping to v1.35.1 in preparation of Podman v5.0.
Addresses: CVE-2024-1753
```release-note
A fix was created to address CVE-2024-1753
```

[v5.0] Bump Buildah to v1.35.1

---

pkg/machine/e2e/machine_wsl_test.go

Small leftover @Luap99 noticed. Doesn't actually affect behavior but makes code match reality.
```release-note
none
```

Use correct extension in suite

---

pkg/util/utils.go
pkg/util/utils_test.go

do not generate a duplicated range when --userns=keep-id:uid=0 or --userns=keep-id:gid=0 are used.
Closes: https://github.com/containers/podman/issues/22078
```release-note
Generate the correct mapping when --userns=keep-id:uid=0 is used 
```

utils: do not generate duplicate range

---

contrib/cirrus/logformatter

C-colon and backslashes and ^Ms oh my
Tested on sample failure and success logs, seems to work.
```release-note
None
```

logformatter: handle Windows logs

---

test/minikube/001-kube.bats
test/minikube/helpers.bash

New run_minikube() helper, modeled after run_podman(). Echoes
each command being run and its output. On failure, runs minikube logs.
Addresses (does not close) #21931 which is hitting us hard in CI.
Probably quay flakes, but it's impossible to tell without logs.
Also: bug fix: one "run podman" fixed to run_podman
```release-note
None
```

minikube: instrument tests, to allow debugging failures

---

libpod/kube.go
pkg/annotations/annotations.go
test/e2e/generate_kube_test.go

The annotations should be maintained by CRI-O itself to decouple the projects from a dependency perspective.
Alternative to https://github.com/containers/common/pull/1902
```release-note
Removed CRI-O specific annotations from `pkg/annotations`.
```

Remove CRI-O related annotations

---

cmd/podman/common/build.go
pkg/api/handlers/compat/images_build.go
pkg/machine/e2e/basic_test.go

I am really not sure why the caller even should have the option to set this. We should always use the correct isolation type based on the privileges the server runs under never the client. podman-remote build seems to send the default based on its local privs which was wrong as well. To fix this I also changed the client to send the default if the isolation flag is not set.
Fixes #22109
```release-note
Fixed a bug that prevent podman-remote build to work properly when connecting from a rootless client to a rootful server
```

fix remote build isolation when server runs as root

---

pkg/api/handlers/compat/images_build.go

This PR removes the temporary saving to a tarfile when remote build context is sent to the podman daemon. 
* reduces the file system space needed by half
* time taken reduced by up to half
* halves CPU load
Running `podman build`  connecting to rootfull socket with a large build context (8GiB) and placeholder Dockerfile 
```
$ time podman build .
...
real	0m56.539s
user	2m29.012s
sys	0m3.002s
```
```
$ time podman build .
...
real	0m34.121s
user	1m27.898s
sys	0m2.625s
```
None
```release-note
streams and extracts remote build context instead of writing to tmp file and extracting
```

Dont save remote build context in temp file but stream and extract

---

cmd/podman/common/build.go

Follow up to 493179be45 which only fixed the issue on the server despite me trying to fix it on the client as well, with this change here we always correctly unset the default on the remote client as the root/rootless status will be wrong.
This means it is enough for users to either have a new server or client with the bug fix which should make the update process easier.
```release-note
None
```

fix remote build isolation on client side

---

RELEASE_NOTES.md

The cgroupv1 warning uses PODMAN_IGNORE_CGROUPSV1_WARNING in the code while the text says PODMAN_CGROUPSV1_WARNING.
```release-note
None
```

[CI:DOCS] 5.0 release note fix typo in cgroupv1 env var

---

libpod/container_inspect.go
libpod/define/container_inspect.go
pkg/api/handlers/compat/containers_create.go
test/apiv2/28-containersAnnotations.at

In addition to the issue in docker-compose and the corresponding CL:
https://github.com/docker/compose/issues/11644
https://github.com/docker/compose/pull/11645
Compose doesn't send Annotations as part of the HostConfig to the docker/podman socket.
On the other hand, podman also ignores Annotations received from the create container API handle.
This CL fix that.
```release-note
None
```

Add support for annotations

---

libpod/runtime.go
libpod/runtime_freebsd.go
libpod/runtime_linux.go

This factors out the check for cgroupsv2 unified mode into a platform-specific file and stops podman from generating a (harmless) warning every time it is run on FreeBSD.
```release-note
None
```

libpod: don't warn about cgroupsv1 on FreeBSD

---

pkg/machine/provider/platform_windows.go
pkg/machine/wsl/machine.go
pkg/machine/wsl/util_windows.go

creating vsocks in windows requires admin privileges.  there could be some workarounds made in the future,but the general deal has always been, you need to be admin.  lets enforce this with an error until those work-arounds can be implemented.
```release-note
Hard error when using podman machine with hyperv and user is not admin
```

hyperv: error if not admin

---

libpod/oci_conmon_common.go

I believe the previous code meant to use cmd.Run instead of cmd.Start. The issue is that cmd.Start returns before the command has finished executing, so the conditional body checking for the stderr of the command never gets executed.
Raise the cmd.Start up into it's own conditional, which is checking for whether the process could be started. Then we consume stderr, check for some specific strings in the output, and then finally continue on with the rest of the code.
This may be a (partial?) fix for: https://github.com/containers/podman/issues/22159
```release-note
None
```

Properly parse stderr when updating container status

---

go.mod
go.sum
pkg/machine/hyperv/stubber.go
vendor/github.com/containers/libhvee/pkg/hypervctl/vm.go
vendor/modules.txt

this pr fixes two hyperv bugs.  previous podman 5 versions of hyperv failed to actually remove the vm from hyperv when machine rm -f was called.
also fixes an annoying bug where removal of the hyperv ignition entries were failing because this can only be done (with the current api) when the vm is running.  new api in latest libhvee fixes this.
```release-note
Fixes bug where virtual machines were not deleted on hyperv when using rm -f on an active vm
```

hyperv: fix machine rm -r

---

libpod/define/info.go
libpod/info.go
test/system/005-info.bats

Useful to tell whether containers are being made with pasta or slirp4netns by default. Info is bloated enough already that I don't really have concerns about shoving more into it.
Fixes #22172
```release-note
The `podman info` command now reports the default rootless network command (Pasta or slirp4netns)
```

Add rootless network command to `podman info`

---

RELEASE_PROCESS.md

This process is easy/quick to do but critically important.  It ensures that CI will always remain available in the event a CVE (or otherwise) backport is required.  These jobs are all actively monitored daily, and their execution ensures the CI VM images are forever preserved.
```release-note
None
```

[CI:DOCS] Document CI-maintenance job addition

---

go.mod

This is needed on the off-chance that some tool or a human suggests updating the minimum version to 1.21 or later. Since doing so would cause Fedora and Debian to start behaving differently WRT builds.
Ref: https://github.com/containers/automation/pull/187
```release-note
None
```

[CI:BUILD] Add golang 1.21 update warning

---

.packit.yaml

Packit now has recently added support to enable downstream PR updates to CentOS Stream packages.
Ref:
https://packit.dev/docs/configuration/upstream/propose_downstream#syncing-the-release-to-centos-stream
CentOS Stream support is still in its early stages but this change should be safe to add to upstream packit config.
Whenever there's a new Podman release, the rpm maintainer would need to run `packit propose-downstream` using the packit CLI (not github comment) to actually create the downstream update PR.
```release-note
None
```

[skip-ci] Packit: Enable CentOS Stream 10 update job

---

pkg/machine/applehv/stubber.go

There has been various issues with vfkit exiting with
"Error: vfkit exited unexpectedly with exit code 1"
Among other reasons, this can be caused by vfkit being
built without the com.apple.security.virtualization
entitlement, and this can also happen when running
vfkit.x86_64 on Apple silicon hardware.
At the moment, the vfkit logs are not available, so there is no easy way
to know what's happening. This PR redirects vfkit stdout/stderr to
podman's log when --log-level debug is used.
```release-note
None
```

applehv: Print vfkit logs in --log-level debug

---

.cirrus.yml
contrib/cirrus/win-lib.ps1
winmake.ps1

That's to address the windows part of https://github.com/containers/podman/issues/21760
```release-note
None
```

CI: Run logformatter for podman_machine_windows_task

---

pkg/domain/infra/abi/play.go
test/e2e/play_kube_test.go

Align the behaviour of `podman kube play file.yaml` to Kubernetes' by forcing an image pull when `imagePullPolicy` is omitted and the container image does not specify a tag.
Fixes #21211 
```release-note
None
```

kube play: always pull when both imagePullPolicy and tag are missing

---

.github/workflows/upload-win-installer.yml
contrib/win-installer/build.ps1

Since all 4.9 versions expect 3.11 of the wix toolset, upgrading to 3.14 breaks builds of all other 4.9 podmans. Keep the v4.9 branch on 3.11 so we can build any of the 4.9 versions.
```release-note
None
```

[CI:DOCS] [v4.9] Force WiX 3.11

---

.github/workflows/upload-win-installer.yml

This restores the checkout to use the installer build at the same branch version as the action. This allows us to update the installer process for releases that have already tagged (sometimes necessary to adapt / adjust to toolchain changes). As an example v4.9.4 is using wix 3.11 but we need to use 3.14.
```release-note
none
```

[CI:DOCS] Switch back to checking out the same branch the action script runs in

---

.cirrus.yml
test/e2e/run_device_test.go
test/e2e/systemd_test.go

Emergency update to get pasta 03-26. Also gives us crun 1.14.4.
One unexplained difference: fc39 and rawhide now create:
/run/log/journal/SOMETHING/system.journal
...and the SOMETHING is o-rwx. This triggers journalctl to spit out a warning:
Hint: You are currently not seeing messages from the system.
Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
Pass -q to turn off this notice.
...which in turn causes ExitCleanly() to fail.
It is not clear who/what is creating this journal directory, or
why it allofasudden started just now. Workaround is to add -q
to journalctl in one test.
One more difference, another test now requires SYSLOG capability.
VM package info:
https://github.com/containers/automation_images/pull/342 …

CI: Bump VMs to 2024-03-28

---

docs/source/markdown/podman-login.1.md.in

The way `podman login` works by default is fundamentally different from `docker login` and this causes a lot of confusion, and I have seen multiple bad suggestions for ways to address this such as setting `XDG_RUNTIME_DIR`.
Let's document up front how to write to the persistent path.
```release-note
None
```

docs/podman-login: Give an example of writing the persistent path

---

go.mod
go.sum
libpod/container.go
libpod/container_internal.go
libpod/container_internal_common.go
libpod/container_internal_freebsd.go
libpod/container_internal_linux.go
libpod/networking_freebsd.go
libpod/networking_linux.go
libpod/networking_pasta_linux.go
test/system/505-networking-pasta.bats
vendor/github.com/containers/buildah/CHANGELOG.md
vendor/github.com/containers/buildah/changelog.txt
vendor/github.com/containers/buildah/define/types.go
vendor/github.com/containers/buildah/run.go
vendor/github.com/containers/buildah/run_common.go
vendor/github.com/containers/buildah/run_freebsd.go
vendor/github.com/containers/buildah/run_linux.go
vendor/github.com/containers/common/libnetwork/etchosts/ip.go
vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
vendor/github.com/containers/common/libnetwork/pasta/pasta_linux.go
vendor/github.com/containers/common/libnetwork/pasta/types.go
vendor/github.com/containers/common/libnetwork/slirp4netns/const.go
vendor/github.com/containers/common/libnetwork/slirp4netns/slirp4netns.go
vendor/github.com/containers/common/libnetwork/util/ip.go
vendor/github.com/containers/common/version/version.go
vendor/modules.txt

As the title says, bumping to Buildah v1.35.3 in preparation of Podman v5.0.1
```release-note
None
```

[v5.0] Bump Buildah to v1.35.3

---

.cirrus.yml

This release branch is tracking RHEL 8.6/9.0 and therefore has no need to execute any CI testing on F35/Ubuntu.  Worse, going forward these releases contain golang versions incompatible with future CVE backports. Remove them.
```release-note
None
```

[v4.2.0-rhel] CI: Remove F35 and Ubuntu

---

libpod/container_internal_common.go
test/system/030-run.bats

if the volume is mounted with "idmap", there should not be any mapping using the user namespace mappings since this is done at runtime using the "idmap" kernel feature.
Closes: https://github.com/containers/podman/issues/22228
```release-note
If a volume is used with `:idmap`, do not map the volume owner to the mappings inside the user namespace
```

libpod: use original IDs if idmap is provided

---

Makefile

This allows distros to easily add buildtags without patching the Makefile or duplicating it in their build recipes
```release-note
None
```

Inject additional build tags from the environment

---

test/system/250-systemd.bats
test/system/700-play.bats
test/system/helpers.registry.bash

Three infrequent flakes. Add debug code to help track
down if/when they happen again.
And, one of them, fix a logic bug that will save us 8-10s
on system tests runs.
```release-note
None
```

CI: systests: instrument flaky tests

---

test/system/500-networking.bats
test/system/700-play.bats
test/system/helpers.network.bash

As of podman 5.0, slirp4netns is a soft dependency. It might
not be installed on a host (and, in gating tests, is not).
Deal with it.
Use podman itself, not 'which', to tell us if slirp4netns
is available. We don't want to duplicate podman's path-check
logic. Since this check is expensive, cache the result.
(Change the has_pasta check similarly)
```release-note
None
```

systests: conditionalize slirp4netns tests

---

Makefile

The man-page-check target requires up-to-date man pages.
Closes: #22025
```release-note
`make validate` was not rebuilding or requiring `docs`, possibly leading to inaccurate/misleading errors
```

[CI:DOCS] build deps: make-validate needs docs

---

libpod/container_internal_common.go
test/e2e/run_volume_test.go

```release-note
When the 'U' option is provided, the mount destination is not chown to the destination target in the image
```
Closes: https://github.com/containers/podman/issues/22224

container: do not chown to dest target with U

---

pkg/util/utils_linux.go

This is racy by design, if you walk a tree and the directory was removed between listing and then opening we get an ENOENT error. Simply ignore that case and do not log it.
Fixes #21782
```release-note
None
```

pkg/util: FindDeviceNodes() ignore ENOENT errors

---

.github/workflows/update-podmanio.yml

Introduce a new GitHub action that will update Podman.io to the newest version of Podman. This action will run on a release being published to GitHub, or by clicking the run workflow button on GitHub. The action will check if the release version is higher than the current version on the website, and open a PR to update the version if a PR does not already exist. The commit will be signed off by the user who triggered the action, so whoever creates the release or presses the run workflow button. The PR will be opened by the podmanbot GitHub account.
```release-note
None
```

[CI:DOCS] Add GitHub action to update version on Podman.io

---

.golangci.yml
hack/golangci-lint.sh

Per https://golangci-lint.run/product/changelog/#v1570
- Replace run.skip-xxx options by issues.exclude-xxx options
```release-note
None
```

[CI:DOCS] golangci-lint: update deprecated flags

---

docs/source/markdown/podman-kube.1.md

Update kube docs stating the support of moving to and from k8s in podman and explicitly stating that we are not replicating the kubectl cli.
Fixes https://github.com/containers/podman/issues/21076.
```release-note
None
```

[CI:DOCS] Update kube docs

---

cmd/podman/containers/rm.go
cmd/podman/images/rm.go
cmd/podman/pods/rm.go
pkg/domain/infra/tunnel/helpers.go
pkg/domain/infra/tunnel/pods.go
test/system/010-images.bats
test/system/055-rm.bats
test/system/160-volumes.bats
test/system/200-pod.bats
test/system/500-networking.bats

When we remove with --force we do not return a error if the input does not exists, however if we get more than on input we must try to remove all and not just NOP out and not remove anything just because one arg did not exists.
Also make the code simpler for commands that do have the --ignore option and just make --force imply --ignore which reduces the ugly error handling.
Fixes #21529
```release-note
Fixed a bug where removing multiple container/image/pod with --force did not work when multiple args where given to the command and one of them did not exists.
```

rm --force work for more than one arg

---

pkg/util/utils_linux.go

When we walk the /dev tree we need to lookup all device paths. Now in order to get the major and minor version we have to actually stat each device. This can again fail of course. There is at least a race between the readdir at stat call so it must ignore ENOENT errors to avoid the race condition as this is not a user problem. Second, we should also not return other errors and just log them instead, returning an error means stopping the walk and returning early which means inspect fails with an error which would be bad.
Also there seems to be cases were ENOENT will be returned all the time, e.g. when a device is forcefully removed. In the reported bug this is triggered with iSCSI devices.
Because the caller does already lookup the device from the created map it reports a warning there if …

[v4.6.1-rhel] inspect: ignore ENOENT during device lookup

---

pkg/util/utils_linux.go

When we walk the /dev tree we need to lookup all device paths. Now in order to get the major and minor version we have to actually stat each device. This can again fail of course. There is at least a race between the readdir at stat call so it must ignore ENOENT errors to avoid the race condition as this is not a user problem. Second, we should also not return other errors and just log them instead, returning an error means stopping the walk and returning early which means inspect fails with an error which would be bad.
Also there seems to be cases were ENOENT will be returned all the time, e.g. when a device is forcefully removed. In the reported bug this is triggered with iSCSI devices.
Because the caller does already lookup the device from the created map it reports a warning there if …

[v4.4.1-rhel] inspect: ignore ENOENT during device lookup

---

pkg/domain/infra/runtime_libpod.go
test/system/setup_suite.bash

This was added ages ago in commit c65b3599cc, however in the meantime both podman and conmon can support longer socket paths as they use a workaround to open the path via /proc/self/fd, see openUnixSocket() in libpod/oci_conmon_attach_linux.go
Thus this restriction is not needed anymore and we can drop a workaround in the tests.
Fixes #22272
```release-note
The --runroot option now can use paths longer than 50 characters.
```

podman --runroot: remove 50 char length restriction

---

Makefile

Currently when we run make docs we will see 100+ lines of `grep: docs/build/man/links: Is a directory` printed. This makes no sense as we should only try to validate the man page.
The manpage target is structured in a way that it runs the generation for each file individually. As such the current way of grep'ing the entire directory for each page is wrong. It should only validate the on page that was created by the command above.
To fix this first define a OUTFILE var for the target to not have to call the substitution every time we use the path and then only grep this one file and not everything in the dir.
```release-note
None
```

Makefile: fix annoying errors in docs generation

---

test/system/160-volumes.bats
test/system/200-pod.bats
test/system/250-systemd.bats
test/system/251-system-service.bats
test/system/410-selinux.bats

Various fixes for gating tests on RHEL8.6: either skip tests that are N/A with runc, or adjust tests to expect the appropriate output. All of these changes are brought in from earlier fixes on `main`.
```release-note
None
```

[v4.2.0-rhel] Gating-test fixes

---

.github/workflows/issue_pr_lock.yml

Periodically, the discussion-lock workflow throws the error: `Resource
not accessible by integration`
This was identified in the [upstream](https://github.com/dessant/lock-threads) issue 47, as caused by a version-5 change that adds support for management of discussions but requires additional permissions and possibly settings.  Given the low notification traffic from discussions, old discussions may remain valid for a long while, and are a useful community-interface:  Disable management of discussions.
```release-note
None
```

[skip-ci] GHA: Fix intermittent workflow error

---

pkg/machine/applehv/machine.go
pkg/machine/e2e/basic_test.go

Fixes #19852
Non-Linux systems, such as BSD derived kernels, constrain selinux xatter updates according to file permissions. This is in contrast to Linux selinux attr writes, which are governed by an selinux policy. By dafault this policy apllows users to relabel files owned by themselves even if file perms would otherwise disallow write.
This results in robust container relabeling results on Linux, and fragile results everywhere else. Therefore, change the mac policy to force the nfs_t context on all files, and ignore all relabel events.
As a side-effect, this will disallow any ability to store custom selinux contexts on files. However, this is of limited use in a machine context with host volumes, since files in these volumes are externally managed on systems which do not support …

Fix relabeling failures with Z/z volumes on Mac

---

test/e2e/info_test.go
test/e2e/run_volume_test.go

As of April 2024, it's no longer included in rawhide by default.
We could force-install it, but it's 2024 and it seems likely
that all systems on which Podman 5 will run will have kernels
that support native overlay.
I also added two debugging printfs to the 'podman info' test
that initially failed on an (unpublished) rawhide VM. Without
these printfs it was impossible to diagnose the failure.
Updating docs is left as a future exercise.
```release-note
None
```

e2e tests: remove requirement for fuse-overlayfs

---

.github/workflows/issue_pr_lock.yml

A simple file rename quickly broke the same workflow in both the Buildah and Skopeo repos.  Add a big-fat warning comment to prevent this from happening again.
```release-note
None
```

[skip-ci] Add big warning to GHA workflow

---

.cirrus.yml

Source: https://github.com/containers/automation_images/pull/345
@mheon yesterday in standup you mentioned that you needed new aardvark-dns packages for (something). Are those packages available anywhere? If so, this VM build didn't get them.
```release-note
None
```

New CI VMs, to give us pasta 2024-04-05

---

libpod/info_linux.go
pkg/rootless/rootless_freebsd.go
pkg/rootless/rootless_linux.go
pkg/rootless/rootless_unsupported.go
pkg/util/utils.go

use the equivalent GetHostIDMappings from the storage unshare package.
```release-note
None
```

rootless: drop function ReadMappingsProc

---

test/README.md
test/e2e/attach_test.go
test/e2e/checkpoint_image_test.go
test/e2e/checkpoint_test.go
test/e2e/commit_test.go
test/e2e/containers_conf_test.go
test/e2e/cp_test.go
test/e2e/create_staticip_test.go
test/e2e/create_test.go
test/e2e/exec_test.go
test/e2e/export_test.go
test/e2e/farm_test.go
test/e2e/generate_kube_test.go
test/e2e/generate_spec_test.go
test/e2e/generate_systemd_test.go
test/e2e/healthcheck_run_test.go
test/utils/matchers.go

...and an optional error-message string, to be checked against stderr.
This is a starting point and baby-steps progress toward #18188. There are 249 ExitWithError() checks in test/e2e. It will take weeks to fix them all. This commit enables new functionality:
Expect(ExitWithError(125, "expected substring"))
...while also allowing the current empty-args form. Once all 249 empty-args uses are modernized, the matcher code will be cleaned up.
I expect it will take several months of light effort to get all e2e tests transitioned to the new form. I am choosing to do so in pieces, for (relative) ease of review. This PR:
1) makes the initial changes described above; and
2) updates a small subset of e2e _test.go files such that:
a) ExitWithError() is given an exit code and error string; and
b) …

e2e: redefine ExitWithError() to require exit code

---

pkg/api/handlers/compat/networks.go
test/apiv2/35-networks.at

Not sure why this only triggers now but this code was broken for a while. It is racy as reported on the issue but because it changes the actual map part of the network backend it means it can also alter the behavior of the network which is very bad.
Fixes #22330
```release-note
Fixed a bug in the compat network list endpoint that could crash the server with "concurrent map writes".
```

fix "concurrent map writes" in network ls compat endpoint

---

.cirrus.yml

This release was originally built around Fedora 35 and golang 1.16.
However the RHEL platform this branch feeds has since moved on to golang
1.17 out of necessity to support security backports.  Given the
difficulty/complexity of updating the CI platform to F36 (golang 1.18),
and the age of this branch, place it into a slimmed-down
"maintenance-only" mode.
Note: This implies a heavier reliance on downstream QE/QA.
Ref: https://github.com/containers/podman/pull/22269
```release-note
None
```

[v4.0-rhel] CI maintenance mode

---

Makefile
contrib/validatepr/Containerfile
contrib/validatepr/validatepr.sh

This PR is only a first step towards being able to validate developer code locally prior to pushing a PR and using CI.  Right now, we have a prepared image in a temporary spot (will change when done).  That image can be used to exercise various podman builds, make validate, and DCO check.
The idea here is we have a make target that spins a podman container (or machine) and then execute a small script to perform the actual builds. Note, these builds are to verify code, not make production binaries so corners are cut.  As of now, we choose to not build cross-arch binaries because most of our problems thus far have been operating system builds and not arch.
Of course this can be expanded in the future.  This is just step one to start getting some of it in place.  The rest of the work is …

[CI:DOCS]Initial PR validation

---

hack/xref-helpmsgs-manpages
pkg/api/handlers/compat/images.go
pkg/domain/entities/images.go
pkg/domain/entities/types/images.go
pkg/domain/infra/abi/images_list.go
test/apiv2/12-imagesMore.at

when listing images through the restful service, consumers want to know if the image they are listing is a manifest or not because the libpod endpoint returns both images and manifest lists.
in addition, we now add `arch` and `os` as fields in the libpod endpoint for image listing as well.
Fixes: #22184
Fixes: #22185
```release-note
on libpod/images/json endpoint, added isManifestList(string) to all returned entries.  If the item is an image (not a manifest list), then we also added Arch (string) and Os (string)
```

Add os, arch, and ismanifest to libpod image list

---

Makefile
pkg/api/Makefile

* Replace redoc with swagger javascript engine. redoc was causing an error. Only used when debugging swagger output.
Reported-by: Brent Baude <bbaude@redhat.com>
```release-note
None
```

[CI:DOCS] Swap out javascript engine

---

test/system/030-run.bats

Two system tests were relying on $SYSTEMD_IMAGE but were not
running _prefetch. This led to baffling flakes that wasted
my time. (Quay flakes, of course. New manifestation.)
```release-note
None
```

(minor) prefetch systemd image before use

---

libpod/define/exec_codes.go
test/e2e/exec_test.go
test/system/075-exec.bats

Fixes: 
```release-note
None
```

podman exec CID without command should exit 125

---

go.mod
go.sum
vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
vendor/github.com/containers/common/libnetwork/netavark/config.go
vendor/github.com/containers/common/libnetwork/netavark/ipam.go
vendor/github.com/containers/common/libnetwork/netavark/network.go
vendor/github.com/containers/common/version/version.go
vendor/modules.txt

Bumping c/common to v0.58.2 in preparation for
Podman v5.0.2
```release-note
Fixed a bug that leaked ipam entries when the network was removed. [#22034](https://github.com/containers/podman/issues/22034)
Fixed a bug which caused the rootless-netns to not be cleaned up on setup errors resulting in a weird resolv.conf missing error message later.  [#22168](https://github.com/containers/podman/issues/22168)
Fixed a bug to no longer use the rootless-netns logic in nested containers [#22218](https://github.com/containers/podman/issues/22218)
```

[v5.0] Bump c/common to v0.58.2

---

pkg/api/server/register_manifest.go

The manifest name is part of the path in the URL.
Fixes #22255
```release-note
None
```

[CI:DOCS] fix swagger doc for manifest create

---

docs/source/markdown/options/network.md

[CI:DOCS] options/network: fix markdown lists

---

test/buildah-bud/apply-podman-deltas

nixery registry has been down all day. Disable test.
Someone will need to fix this on the buildah end.
```release-note
None
```

Emergency fix (well, skip) for failing bud tests

---

cmd/podman/networks/list.go
test/system/500-networking.bats

this makes it consistent with other commands (like image and container),
but also makes the example actually work
Signed-off-by: Evgeni Golov <evgeni@golov.de>
```release-note
None
```

add `list` as an alias to list networks

---

.github/workflows/upload-win-installer.yml

We temporarily installed wixtoolset using chocolatey, when 3.14 wasn't in GHA yet. Now it's there by default, so remove the install. This prevents the downgrade error. Note: If we change the minir version of WiX that we use, then we may need to install wix again. But for now, removing this step will allow us to use the latest 3.14 patch.
```release-note
None
```

[CI:DOCS] Fix windows installer action

---

.cirrus.yml
contrib/cirrus/runner.sh
contrib/cirrus/setup_environment.sh
test/compose/README.md
test/compose/etc_hosts/tests.sh
test/compose/ipam_set_ip/tests.sh
test/compose/two_networks/tests.sh
test/compose/uptwice/tests.sh

compose v1 has been deprecated for some time now, since July 2023 it no
longer receives any updates[1]. As such testing it on every PR is
pointless, it also does not provide any more coverage then compose v2.
At least I never saw only compose v1 test fails (except for flakes) so
it doesn't help us to catch regressions.
We tried to remove it before but decided against it at that time[2].
[1] https://docs.docker.com/compose/migrate/
[2] https://github.com/containers/podman/issues/18688
```release-note
None
```

CI: remove compose v1 tests

---

docs/source/markdown/podman-kube-play.1.md.in

[CI:DOCS] Add more annnotation information to podman kupe play man page

---

docs/source/markdown/podman-pod-restart.1.md

Small typographical error:
"an restarted" -> "and restarted"
```release-note
None
```

[CI:DOCS] fix podman-pod-restart.1.md typo

---

.packit.yaml

- EPEL is the recommended target for further testing with rpm builds.
- Fix EL9 builds.
- Do not change c8s for now as it will be removed soon anyway.
```release-note
None
```

[skip-ci] Packit: switch to EPEL instead of centos-stream+epel-next

---

.github/workflows/release-artifacts.yml
.github/workflows/upload-win-installer.yml

Add a new GitHub Action that builds and uploads release artifacts. This action is triggered by publishing a release on GitHub. The action will only build if the specfic artifact is missing.
This action also triggers the Windows installer action, since the Windows installer action depends on an uploaded artifact.
Note that the action runs on ubuntu-22.04
```release-note
None
```

[CI:DOCS] Build & upload release artifacts with GitHub Actions

---

cmd/podman/common/completion.go
cmd/podman/common/create.go
cmd/podman/containers/update.go
docs/source/markdown/options/restart.md
docs/source/markdown/podman-events.1.md
docs/source/markdown/podman-update.1.md.in
docs/source/markdown/podman.1.md
libpod/container_api.go
libpod/container_inspect.go
libpod/container_internal.go
libpod/define/container.go
libpod/events/config.go
libpod/events/events.go
libpod/options.go
pkg/api/handlers/compat/containers.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/swagger/models.go
pkg/api/server/register_containers.go
pkg/bindings/containers/update.go
pkg/domain/infra/abi/containers.go
pkg/specgen/generate/container_create.go
test/apiv2/20-containers.at
test/e2e/common_test.go
test/e2e/update_test.go
test/system/280-update.bats

Now that SQLite is the default store, we can persist changes to containers made with the `podman update` command. The actual logic is very simple, as that was never really what was holding us back; it was the BoltDB database not supporting it.
Also, make update emit events. Docker does it, we should as well.
```release-note
Changes made by `podman update` are now persistent as long as the SQLite database backend is in use.
Updating containers with `podman update` now emits an event.
A Docker-compatible Update endpoint for Containers has been added to the remote API.
The `podman update` command now includes a new option, "--restart", to update the restart policy of existing containers.
```

Make `podman update` changes persistent

---

libpod/runtime.go

In cases where we fail to configure the error is returned as it and may be missing useful context. Make sure we know the error happened as part of the storage setup.
```release-note
None
```

libpod: wrap store setup error message

---

go.mod
go.sum
libpod/events.go
libpod/healthcheck.go
libpod/runtime_ctr.go
test/e2e/healthcheck_run_test.go
vendor/github.com/containers/common/pkg/config/config.go
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
vendor/github.com/containers/common/pkg/config/default.go
vendor/modules.txt

When the field is set to false we should never log healthcheck events.
Fixes https://issues.redhat.com/browse/RHEL-18987
also included some further cleanup commits
```release-note
A new healthcheck_events containers.conf has been added under the [engine] section to allow users to disable the generation of health_status events.
```

add containers.conf healthcheck_events support

---

.packit.yaml

CentOS 10 Stream rpm builds are now active, so we should add jobs for
those on PRs.
These have to be centos-stream for now and not epel as epel will be
created only after RHEL-10 is released AFAIK, while the centos-stream-10
targets are available in copr now.
```release-note
None
```

[skip-ci] Packit: enable CentOS 10 Stream build jobs

---

CONTRIBUTING.md

This PR consists of two commits:
* Adds the installation instructions for openSUSE, similar to the present ones for Fedora and Debian/Ubuntu (Tested on openSUSE Tumbleweed and Leap 15.6)
* Remove the `PKG_CONFIG_PATH` configuration, which appears to not be needed anymore
```release-note
None
```

[CI:DOCS] Add installation instructions for openSUSE

---

.github/workflows/release-artifacts.yml

Fix a bug where the check uploads section didn't actually mark the os/arch to be built.
```release-note
None
```

[CI:DOCS] Fix artifact action

---

CONTRIBUTING.md

The contents of the "Prerequisite before buil"d section are given already in a link in its "Prepare your environment" parent section and therefore redundant. Let's remove it.
This is a followup of https://github.com/containers/podman/pull/22464 as suggested in https://github.com/containers/podman/pull/22464#discussion_r1575990476
The "Prepare your environment" section already links to https://podman.io/getting-started/installation#build-and-run-dependencies, where the required dependencies are much better documented.
Following the previous suggestion from @Luap99, the whole "Prerequisite before build" section is redundant, likely will be outdated and should be removed in favor of the actual installation docs.
```release-note
None
```

[CI:DOCS] Remove redundant Prerequisite before build section

---

test/e2e/image_scp_test.go
test/e2e/kill_test.go
test/e2e/load_test.go

Because #22346 is stalled, these are some trivial easy-to-review
changes that get us closer to the goal.
```release-note
None
```

ExitWithError() - low-hanging fruit

---

test/e2e/login_logout_test.go

More low-hanging fruit: small reviewable chunks
```release-note
None
```

ExitWithError() - more low-hanging fruit

---

test/e2e/logs_test.go
test/e2e/mount_rootless_test.go
test/e2e/mount_test.go
test/e2e/negative_test.go

Followup to [1]#22270: wherever possible/practical, extend command
Just trying to shrink down #22346 to a manageable, reviewable size.
```release-note
None
```

ExitWithError() - yet more low-hanging fruit

---

docs/source/markdown/options/mount.md
docs/source/markdown/podman-kube-play.1.md.in
libpod/container.go
libpod/container_internal_common.go
libpod/define/annotations.go
libpod/options.go
pkg/domain/infra/abi/play.go
pkg/specgen/generate/container_create.go
pkg/specgen/generate/kube/kube.go
pkg/specgen/volumes.go
pkg/specgenutil/volumes.go
test/e2e/run_volume_test.go
test/system/700-play.bats

Effectively, this is an ability to take an image already pulled to the system, and automatically mount it into one or more containers defined in Kubernetes YAML accepted by `podman play`.
Requirements:
- The image must already exist in storage.
- The image must have a single Volume directive. We will mount to the path defined in the Volume directive.
- More than one image can be specified, but the paths they mount to (the Volume directives) must be different for all images mounted into a single container.
- The images are always mounted read-only
- Images to mount are defined in the annotation "io.podman.annotations.kube.image.automount/$ctrname" as a semicolon-separated list. They are mounted into a single container in the pod, not the whole pod.
As we're using a nonstandard annotation, …

Add the ability to automount images as volumes via play

---

docs/source/markdown/options/network.md

Also, properly capitalize.
```release-note
None
```

Correct network option name `ip` -> `ip6`

---

Makefile
contrib/cirrus/runner.sh
contrib/cirrus/setup_environment.sh
test/e2e/common_test.go
test/e2e/run_test.go
test/e2e/run_volume_test.go

see commits
Fixes #22474
```release-note
None
```

test/e2e: fixes to make test pass locally

---

Makefile

The fedora image reviewers wanted to use for make validatepr is not being being built as a multiarch image.  Use quay.io/libpod/validatepr instead.
```release-note
None
```

Use custom image for make validatepr

---

pkg/machine/e2e/machine_pull_test.go
pkg/machine/ocipull/ociartifact.go
pkg/machine/shim/diskpull/diskpull.go
pkg/machine/stdpull/url.go
pkg/machine/wsl/stubber.go

Cache cleanups only happen if there is a cache miss, and we need to pull a new image
For quay.io/podman/machine-os, we remove all old images from the cache dir. This means we will delete any file that exists in the cache dir; this should be safe to do since the machine pull code should be the only thing touching this cache dir. OCI machine images will always have a different manifest, and won’t be updated with the same manifest, so if the version moves on, there isn’t a reason to keep the old version in the cache, it really doesn’t change.
For Fedora (WSL), we use the cache, so we go through the cache dir and remove any old cached images, on a cache miss. We also switch to using ~/.local/share/containers/podman/machine/wsl/cache as the cache dir rather than …

Clean machine pull cache

---

rpm/podman.spec

The package summary for builds like [podman-5.0.2-1.fc40](https://koji.fedoraproject.org/koji/buildinfo?buildID=2440335) currently includes the following line:
```
%{repo} Simple management tool for pods, containers and images
```
Older package builds like [podman-3.0.1-1.fc33](https://koji.fedoraproject.org/koji/buildinfo?buildID=1712552) have the following:
```
podman Simple management tool for pods, containers and images
```
The `%{repo}` macro seems to be fairly common across Containers projects:
https://github.com/search?q=org%3Acontainers%20%25%7Brepo%7D&type=code
I don't see this macro defined anywhere in the podman repo anymore though.
It appears that `%{repo}` was once defined as a synonym of `%{name}` when looking at an older spec file: …

[skip-ci] Remove unncessary lines at the end of specfile summary

---

test/e2e/build_test.go
test/e2e/mount_rootless_test.go
test/e2e/play_kube_test.go

see commits
```release-note
None
```

test/e2e: more fixes to not leak tmp files/dirs

---

.cirrus.yml
contrib/cirrus/cirrus_yaml_test.py

Older versions of podman machine do not support being run against the
latest version of the machine VM images.  As there is no built-in
provision to pin older machine VM image versions, these tests will
simply fail forever.  Disable them.
Also disable 'bench_stuff' as it is everywhere else.
```release-note
None
```

[v4.6.1-rhel] CI Maintenance: Disable machine tests

---

.cirrus.yml

Older versions of podman machine do not support being run against the latest version of the machine VM images.  As there is no built-in provision to pin older machine VM image versions, these tests will simply fail forever.  Disable them.
Also cleanup a long since disabled task.
```release-note
None
```

[v4.4.1-rhel] CI Maintenance: Disable machine tests

---

pkg/machine/apple/apple.go
pkg/machine/e2e/init_test.go
pkg/machine/volumes.go
pkg/systemd/parser/split.go
pkg/systemd/parser/unitfile.go

AppleHV accepts a max 36 bytes for mount tags. Instead of using the fully qualified path for the mount tag, use the sha256 of the path. 
Fixes: #22226
Fixes: https://github.com/containers/podman/issues/22505
```release-note
Fixed a bug where podman machine start would fail if the machine had a volume with a long target path. 
Fixed a bug where  podman machine mounted paths that included dashes in the wrong location.
```

Fix machine volumes with long path

---

.github/workflows/issue_pr_lock.yml

Frequent but intermittently, the stale issue and PR locking workflow generates the error:
```
You have exceeded a secondary rate limit. Please wait a few minutes
before you try again. If you reach out to GitHub Support for help,
please include the request ID XYZ
```
According to [upstream `dessant/lock-threads` issue 48](https://github.com/dessant/lock-threads/issues/48), this seems to be coming from the GitHub side (bug/feature/limitation), since the action uses an official github API rate-limiting library.  It's unlikely related to which style/syntax of github token is used, nor if the action is executed concurrently across multiple repos.
According to the rate-limiting docs:
https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#about-secon …

[skip-ci] GHA: Attempt fix exceeded a secondary rate limit

---

test/e2e/pod_create_test.go
test/e2e/pod_infra_container_test.go
test/e2e/pod_inspect_test.go
test/e2e/pod_kill_test.go
test/e2e/pod_pause_test.go
test/e2e/pod_ps_test.go
test/e2e/pod_rm_test.go

This commit handles a subset of test/e2e/pod_xxxx_test.go
(I stopped before this grew too huge for review)
```release-note
None
```

ExitWithError() - pod_xxx tests

---

pkg/machine/applehv/machine.go
pkg/machine/e2e/init_test.go
pkg/machine/volumes.go
pkg/systemd/parser/split.go
pkg/systemd/parser/unitfile.go
test/buildah-bud/apply-podman-deltas

AppleHV accepts a max 36 bytes for mount tags. Instead of using the fully qualified path for the mount tag, SHA256 the path, and truncate the shasum to 36 bytes. Also correctly escape dashes in mounted paths.
Fixes: https://github.com/containers/podman/issues/22226
Fixes: https://github.com/containers/podman/issues/22505
```release-note
Fixed a bug where podman machine start would fail if the machine had a volume with a long target path. 
Fixed a bug where  podman machine mounted paths that included dashes in the wrong location.
```

[v5.0] Fix machine volumes with long path and paths with dashes

---

cmd/podman/common/create.go

The `podman run --sdnotify=healthy` option was implemented some time ago. It's correctly mentioned in the documentation but was missing in the usage text of `podman run --help`.
I'm not sure if this is a valid `[CI:DOCS]` PR or not because it's technically in the code but it's also just a single line usage text change.
```release-note
None
```

[CI:DOCS]Add missing option 'healthy' to output of `podman run --help`

---

pkg/util/utils_supported.go
pkg/util/utils_test.go

commit b3014c1c69d5870104aa45f7caae7af041094171 changed GetRootlessRuntimeDir() to return an empty string for root, so that its value is not exported as XDG_RUNTIME_DIR, and other programs like crun can use a better default.
Now GetRootlessPauseProcessPidPath() uses homedir.GetRuntimeDir(). The homedir.GetRuntimeDir() function returns a value also when running as root so it can be used inside a nested Podman.
Closes: https://github.com/containers/podman/issues/22327
```release-note
None
```

util: specify a not empty pause dir for root too

---

.cirrus.yml
test/buildah-bud/apply-podman-deltas

Older versions of podman machine do not support being run against the latest version of the machine VM images.  As there is no built-in provision to pin older machine VM image versions, these tests will simply fail forever.  Disable them.
```release-note
None
```

[v4.9] CI Maintenance: Disable machine tests

---

contrib/cirrus/runner.sh

Followup to #13936 : add an exclusion to localmachine tests
so we can avoid running those on test- or doc-only PRs.
Reason: #22551, the machine-start-timeout flake, is causing
hours of wasted time.
```release-note
None
```

Skip machine tests if they don't need to be run

---

libpod/container.go
libpod/container_internal.go
libpod/healthcheck_linux.go

Systemd dislikes it when we rapidly create and remove a transient unit. Solution: If we change the name every time, it's different enough that systemd is satisfied and we stop having errors trying to restart the healthcheck.
Do this by maintaining a count of how many times we've run the healthcheck, and appending that counter to the end of the unit name. The counter increments every time we destroy the previous healthcheck.
Should resolve [RHEL-26105](https://issues.redhat.com/browse/RHEL-26105)
```release-note
Fixed a bug where rapidly-restarting containers with healthchecks could sometimes fail to start their healthchecks after restarting.
```

Add a run counter to healthcheck unit names

---

test/e2e/volume_create_test.go
test/e2e/volume_plugin_test.go
test/e2e/volume_rm_test.go

This commit handles test/e2e/v*_test.go
```release-note
None
```

ExitWithError() - v files

---

.cirrus.yml

PR https://github.com/containers/podman/pull/22540 removed the job that generated the (useless) benchmark data
generation.  However it neglected to stop addition of the data to the
output artifacts.  Fix this.
Ref: [Example of failing cirrus-cron job](https://cirrus-ci.com/task/5937026929786880).
```release-note
None
```

[v4.4.1-rhel] Fix artifacts task failure

---

pkg/machine/provider/platform.go
pkg/machine/provider/platform_darwin.go
pkg/machine/provider/platform_test.go
pkg/machine/provider/platform_windows.go

Extends the `pkg/machine/provider` package to add an API which includes provider detection based on the host operating system.
```release-note
None
```

machine: Add provider detection API

---

rpm/podman.spec

The `bats` package is not present on RHEL environments. It should be conditionalized only for Fedora to avoid `installibility` test failures.
C9S Ref: https://gitlab.com/redhat/centos-stream/rpms/podman/-/blob/c9s/podman.spec?ref_type=heads#L130
```release-note
None
```

[skip-ci] RPM: `bats` required only on Fedora

---

test/e2e/run_test.go

check if the file path exists instead of using the env variable.
I hit the problem in the crun CI: https://github.com/containers/crun/actions/runs/8986352255/job/24682255111?pr=1465
```release-note
None
```

test: improve test for powercap presence

---

contrib/cirrus/lib.sh

A long time ago, `passthrough_envars()` was defined in `lib.sh`.  It has since been moved, but the related comments were never updated.  Update the env. var. comments pointing future maintainers to the function that relies on them.  Otherwise a simple search w/in this repo. won't turn up anything.
```release-note
None
```

[CI:DOCS] Clarify passthrough_envars() comments

---

test/e2e/common_test.go
test/e2e/config.go
test/e2e/config_amd64.go
test/e2e/config_arm64.go
test/e2e/toolbox_test.go

The image is way to big (over 800MB) that slows tests down as we always have to pull this, the tests itself are also super slow due the entrypoint logic that we don't care about. We should be testing for features needed and not specific tools.
I think the current changes should have a similar coverage in terms of podman features, it no longer tests toolbox but IMO this never was a task for podman CI tests.
The main driver for this is to make the tests run entirely based on tmpfs and this image is just to much[1].
[1] https://github.com/containers/podman/pull/22533
```release-note
None
```

test/e2e: remove toolbox image

---

.golangci.yml
Makefile

disable linters:
- mnd (magic number checker): it seems to complain about almost anything, while there might be a few valid findings most of them are useless
- canonicalheader: HTTP header syntax, most of the header are given by docker and are stable so we cannot change them anyway
- execinquery: it has been deprecated
goerr113 was renamed to err113
```release-note
None
```

[CI:DOCS] update golangci-lint to 1.58

---

test/e2e/import_test.go
test/e2e/inspect_test.go
test/e2e/manifest_test.go
test/e2e/network_connect_disconnect_test.go
test/e2e/network_create_test.go
test/e2e/network_test.go

Followup to #22270 : wherever possible/practical, extend command
A small number of tests were broken, as in, not actually testing
what they claimed to be testing. I've done my best to fix those.
```release-note
None
```

ExitWithError() - continue tightening

---

pkg/api/handlers/compat/images_build.go
pkg/bindings/images/build.go
pkg/util/utils.go
test/buildah-bud/apply-podman-deltas
test/e2e/build/containerignore-symlink/.dockerignore
test/e2e/build/containerignore-symlink/Dockerfile
test/e2e/build_test.go

Drop support for remote use-cases when `.containerignore` or `.dockerignore` is a symlink pointing to arbitrary location on host.
This backport addresses: CVE-2022-4122
https://issues.redhat.com/browse/RHEL-13467
```release-note
None
```

[v4.0-rhel] remote,build: error if containerignore is symlink

---

pkg/machine/provider/platform_darwin.go
pkg/machine/provider/platform_test.go

Adds provider detection for LibKrun in `pkg/provider/platform_darwin.go`.
Changes the macOS version check to 13 instead of 11, and now uses the `semver` package to verify current version.
```release-note
None
```

machine: Add LibKrun provider detection

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/group-add.container
test/e2e/quadlet_test.go

```release-note
Quadlet/Container: Add GroupAdd option
```
I have not written anything in Go before and did not manage to run the test I added locally.

Quadlet/Container: Add GroupAdd option

---

test/e2e/pause_test.go
test/e2e/pod_stats_test.go
test/e2e/port_test.go
test/e2e/prune_test.go
test/e2e/ps_test.go
test/e2e/pull_test.go
test/e2e/push_test.go

This commit handles all remaining test/e2e/p*_test.go
```release-note
None
```

ExitWithError() - rest of the p files

---

.github/workflows/release-artifacts.yml
.github/workflows/upload-win-installer.yml

As title says. For future 5.0.x releases this needs to be in the branch for the action to be automatically run.
```release-note
None
```

[v5.0] [CI:DOCS] Backport release actions

---

libpod/container_internal.go

the code was added 5 years ago.  It is safe to assume such ancient conmon versions are not used anymore.
```release-note
None
```

Revert "container stop: kill conmon"

---

libpod/container_internal.go
test/system/030-run.bats

The scenario for inducing this is as follows:
1. Start a container with a long stop timeout and a PID1 that ignores SIGTERM
2. Use `podman stop` to stop that container
3. Simultaneously, in another terminal, kill -9 `pidof podman` (the container is now in ContainerStateStopping)
4. Now kill that container's Conmon with SIGKILL.
5. No commands are able to move the container from Stopping to Stopped now.
The cause is a logic bug in our exit-file handling logic. Conmon being dead without an exit file causes no change to the state. Add handling for this case that tries to clean up, including stopping the container if it still seems to be running.
Fixes #19629
```release-note
Fixed a bug where Systemd-managed containers could be stuck in the Stopping state, unable to be restarted, if systemd …
```

Ensure that containers do not get stuck in stopping

---

.github/workflows/check_cirrus_cron.yml
.github/workflows/mac-pkg.yml
.github/workflows/release-artifacts.yml
.github/workflows/rerun_cirrus_cron.yml
.github/workflows/upload-win-installer.yml

This change will minimize renovate PR's.
Checkout is an action maintained by GitHub, so using the latest v4 action shouldn't have stability consequences.
Replaces: https://github.com/containers/podman/pull/22456
```release-note
None
```

[CI:DOCS] Use checkout@v4 in GH Actions

---

test/e2e/run_apparmor_test.go
test/e2e/run_cpu_test.go
test/e2e/run_device_test.go
test/e2e/run_dns_test.go
test/e2e/run_memory_test.go
test/e2e/run_ns_test.go
test/e2e/run_passwd_test.go
test/e2e/run_seccomp_test.go

This commit handles a subset of test/e2e/run_xxx_test.go
```release-note
None
```

ExitWithError() - more run_xxx tests

---

test/e2e/save_test.go
test/e2e/search_test.go
test/e2e/secret_test.go
test/e2e/start_test.go
test/e2e/stats_test.go
test/e2e/system_df_test.go

This commit handles test/e2e/s*_test.go
```release-note
None
```

ExitWithError() - s files

---

test/e2e/rename_test.go
test/e2e/run_networking_test.go
test/e2e/run_signal_test.go
test/e2e/run_staticip_test.go
test/e2e/run_volume_test.go

This commit handles all remaining test/e2e/r*_test.go
```release-note
None
```

ExitWithError() - more r files

---

test/e2e/rmi_test.go

This commit handles only one file, test/e2e/rmi_test.go , because
my changes are significant enough to merit individual review.
```release-note
None
```

ExitWithError() - rmi_test

---

pkg/domain/infra/abi/play.go
test/e2e/play_kube_test.go

Fixes #22397
Yes
```release-note
Fixed a bug where `podman kube down` would not respect the StopTimeout and StopSignal of containers that it stopped
```

Graceful shutdown during podman kube down 

---

.cirrus.yml
contrib/cirrus/runner.sh
test/e2e/common_test.go

Follow up to commit eaf60c7fe7, lets see how bad things are going to break.
```release-note
None
```

run e2e test on tmpfs

---

Makefile

Follow-up of https://github.com/containers/podman/pull/22060#issuecomment-2009960603
```release-note
None
```

Makefile: do not hardcode `GOOS` in `podman-remote-static` target

---

pkg/api/handlers/compat/info.go

https://github.com/containers/podman/issues/22561
```release-note
Fix panic when a runtime was configured without executable paths.
```

Don't panic if a runtime was configured without paths

---

CONTRIBUTING.md
Makefile
contrib/validatepr/validatepr.sh

Small usability improvements for our containerized validate target.
- Responds to SIGINT
- Exits if build fails, only validate if builds succeed
- Warns about potential of insufficient memory
- Document `make validatepr`
```release-note
None
```

[CI:DOCS] Improvements to make validatepr

---

test/e2e/checkpoint_test.go
test/e2e/play_kube_test.go
test/e2e/run_device_test.go
test/e2e/run_memory_test.go
test/e2e/run_seccomp_test.go
test/e2e/run_staticip_test.go
test/e2e/runlabel_test.go
test/e2e/start_test.go
test/utils/matchers.go

Final followup to #22270. That PR added a temporary convention
allowing a new form of ExitWithError(), one with an exit code
and stderr substring. In order to allow bite-size progress,
the old no-args form was still allowed. This PR removes
support for no-args ExitWithError().
This PR also adds one piece of new functionality: passing ""
(empty string) as the stderr arg means "expect exit code
but fail if there's anything at all in stderr".
And, one small commit because I seem to have missed a few.
```release-note
None
```

ExitWithError() - final push to strict mode

---

pkg/rootless/rootless_linux.c
test/system/550-pause-process.bats

Under some circumstances podman might be executed with a different argv0 than the actual path to the podman binary. This breaks the reexec logic as it tried to exec argv0 which failed.
This is visible when using podmansh as login shell which get's the special -podmansh on argv0 to signal the shell it is a login shell.
To fix this we can simply use /proc/self/exe as command path which is much more robust and the argv array is still passed correctly.
Fixes #22672
```release-note
Fixed a bug where rootless podman could fail to reexeute itself when run with a custom argv0 that is not a valid command path.
```

rootless: fix reexec to use /proc/self/exe

---

cmd/podman/common/build.go
pkg/domain/infra/tunnel/manifest.go
test/farm/001-farm.bats

Fix https://github.com/containers/podman/issues/22647
```release-note
Fixed a problem with `podman farm build` command in podman-remote not updating manifests on the registry that have already been pushed
```

Fix podman-remote support for `podman farm build`

---

.packit.yaml

Without this key, there are duplicate copr jobs being created on podman-next copr for `podman-fedora` and `podman-centos`.
Picking just one of `podman-fedora` / `podman-centos` should trigger builds for all targets specified on the podman-next copr.
```release-note
None
```

[skip-ci] Packit: use only one value for `packages` key for `trigger: commit` copr builds

---

cmd/podman/system/events.go
pkg/api/handlers/compat/events.go
pkg/bindings/system/system.go
test/system/090-events.bats

```release-note
`podman events` should be able to diagnose invalid values being passed as arguments to its `--since` and `--until` flags.
```

`podman events`: check for an error after we finish reading events

---

pkg/api/handlers/utils/errors.go
test/e2e/volume_rm_test.go

Fixes #22616
```release-note
None
```

Return StatusNotFound when multiple volumes matching occurs

---

libpod/container_api.go
libpod/container_internal.go
libpod/oci_conmon_attach_common.go
pkg/domain/infra/abi/containers.go
test/system/260-sdnotify.bats

wait for the healthy status on the thread where the container lock is held.  Otherwise, if it is performed from a go routine, a different thread is used (since the runtime.LockOSThread() call doesn't have any effect), causing pthread_mutex_unlock() to fail with EPERM.
Closes: https://github.com/containers/podman/issues/22651
```release-note
None
```

libpod: wait for healthy on main thread

---

pkg/machine/e2e/README.md
pkg/machine/e2e/machine_test.go

Fix https://github.com/containers/podman/issues/22360
```release-note
Fixed an error starting Podman machine when running e2e localmachine tests on macOS.
```
The fixes are only to the e2e test file and Doc, no additional tests.

Change tmpDir when running e2e localmachine test on macOS

---

DOWNLOADS.md

Fix download link to CI mac pkg and include universal pkg.
Fixes: #22699 
```release-note
None
```

[CI:DOCS] Fix Mac pkg link

---

pkg/machine/ocipull/source.go

Use `specV1.AnnotationTitle` instead of hard-coding its value when we go looking for podman-machine images.
```release-note
None
```

Use a defined constant instead of a hard-coded magic value

---

cmd/podman/machine/inspect.go
docs/source/markdown/podman-machine-inspect.1.md
pkg/machine/apple/vfkit.go
pkg/machine/apple/vfkit/helper.go
pkg/machine/applehv/stubber.go
pkg/machine/config.go
pkg/machine/define/config.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/machine_test.go
pkg/machine/hyperv/stubber.go
pkg/machine/ignition/ignition.go
pkg/machine/libkrun/stubber.go
pkg/machine/qemu/stubber.go
pkg/machine/vmconfigs/config.go
pkg/machine/wsl/stubber.go

This PR adds Rosetta support to the AppleHV Podman machine(only v5).
Rosetta is only available on macOS with Apple Silicon.
With Rosetta, the execution performance is several times better than QEMU emulation.
https://developer.apple.com/documentation/virtualization/running_intel_binaries_in_linux_vms_with_rosetta
Todo
> [!NOTE] 
> [SELinux context] > resolved
> ~~Perhaps because of the use of vfkit, the SELinux context needs to be with `*exec_t` when mounting the Rosetta directory.~~
> ~~On lima and UTM which support Rosetta, it can be executed with `nfs_t` without error.~~
> 
> ~~https://github.com/lima-vm/lima/blob/88c89165273d87b33753a593af867b20c1d1c67d/pkg/cidata/cidata.TEMPLATE.d/boot/05-rosetta-volume.sh#L22~~
```release-note
Podman machine can now use Rosetta 2 (a.k.a Rosetta) on …
```

applehv: Rosetta support

---

.cirrus.yml

Use 4 core VM vompred to the standard 2 cores, integration tests scale
almost linear with extra cores, as such doubling the cores makes the
tests almost twice as fast. This brings the test time down to 15-17 min
in CI.
```release-note
None
```

cirrus: use faster VM's for integration tests

---

Makefile

This PR adds the podman-clean-transient.service to the list of installed user services. According to the issue #22317 there should be no reason this would not work in user mode. This seems like it was just forgotten in the original PR: https://github.com/containers/podman/pull/16892
```release-note
- Add podman-clean-transient.service as a user service.
```
Closes #22317

add podman-clean-transient.service service to rootless mode

---

pkg/machine/apple/vfkit.go

In GetDefaultDevices(), make sure MachineConfig has an AppleHypervisor instance before attempting to access it. This fixes a SIGSEGV when running with libkrun as machine provider.
```release-note
None
```

Check AppleHypervisor before accessing it

---

test/system/helpers.network.bash

The default_addr shell function in test/system/helpers.network is used to get the host's default address, which is used in a number of pasta networking tests.  However, in certain circumstances it can incorrectly pick a deprecated address as the primary address.  Correct it to exclude those.
```release-note
No
```

test, pasta: Ignore deprecated addresses in tests

---

.github/workflows/release-artifacts.yml

Give the artifact action the permission to trigger the windows installer action
```release-note
None
```

[CI:DOCS] Fix windows action trigger

---

libpod/define/container_inspect.go
pkg/api/handlers/libpod/containers.go
test/apiv2/25-containersMore.at
test/apiv2/test-apiv2

The v5 API made a breaking chnage for podman inspect, this means that old client could not longer parse the result from the new 5.X server. The other way around new client and old server were already fixed.
In order to keep the API working we now have a version check and return the old v4 compatiable payload so the old remote client can still work against a newer server.
Fixes #22657
```release-note
The remote API now return compatible v4.X container inspect output when a request with v4.0.0 is made. This makes old 4.X clients work with a new 5.X server. 
```

remote API: restore v4 payload in container inspect

---

.cirrus.yml

It's been flaking heavily since March. I don't see any new
development going on in minikube-land. If anyone decides
to care about minikube again, they can reenable this.
```release-note
None
```

CI: disable minikube task

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/parser/unitfile.go
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/basic.container
test/e2e/quadlet/basic.image
test/e2e/quadlet/mount.container
test/e2e/quadlet/network.quadlet.container
test/e2e/quadlet/unit-after-override.container
test/e2e/quadlet/unit-after-override.image
test/e2e/quadlet_test.go

If a container unit starts on boot with a dependency on `default.target`
the image unit may start too soon, before network is ready. This cause
the unit to fail to pull the image.
Add a dependency on `network-online.target` to make sure image pulls
don't fail.
yes 
```release-note
Image oneshot units generated through quadlet will now have a dependency on `network-online.target`
```
Fixes https://github.com/containers/podman/issues/21873

quadlet: Add a network requirement on .image and .containers units

---

docs/source/markdown/podman-volume-inspect.1.md
libpod/container_internal.go
libpod/container_internal_common.go
libpod/volume.go
libpod/volume_internal.go
test/e2e/run_volume_test.go
test/system/160-volumes.bats

This is done to better match Docker's behavior. Our current behavior is to only chown a volume once, the first time it is mounted into a container; that doesn't match what Docker does. Docker chowns every time a container mounts a volume, to ensure it is always accessible to the last container to mount it.
Fortunately, this is a relatively easy fix. We have a bool in volume state as to whether a volume needs to be chowned, which we set to false when the volume was first chowned; so just stop doing that.
I was really hoping to eliminate the NeedsChown bool entirely, but things are a bit of a mess. There are some cases where we do want to completely inhibit chowning, like when the user explicitly requests that a volume be a specific UID and GID. Unfortunately, those are both ints, not *int, …

Always chown volumes when mounting into a container

---

docs/kubernetes_support.md

It seems like podman kube play already supports the field since version 4.4.0 but the documentation was not yet updated.
```release-note
None
```

[CI:DOCS] kubernetes_support.md: Mark volumeMounts.subPath as supported

---

.golangci.yml
Makefile
pkg/util/utils.go

Remove deactivated linters from the config as they will be removed in the future and thorw warnings, all of them were disabled already anyway so this is no functional change.
Second, fix one new lint warning for fmt.Scanln() error checking.
```release-note
None
```

update golangci-lint to v1.59.0

---

contrib/cirrus/mac_setup.sh
pkg/machine/e2e/machine_test.go

Previously, the mac podman-machine tests installed rosetta before
executing any tests.  As a best-practice (and because the Macs in CI are
shared) tests should never permanently modify the system.  As of this
commit, the system setup script used for the CI Macs does the rosetta
installation.  Remove the test setup code that installed rosetta and
add a CI-level confirmation that it's been pre-installed.
Ref:
- https://github.com/containers/podman/pull/21670
- https://github.com/containers/automation/pull/196
TODO:
```release-note
None
```

Mac PM test: Require pre-installed rosetta

---

.cirrus.yml
test/buildah-bud/apply-podman-deltas
test/e2e/container_iface_name_test.go
test/e2e/run_test.go
test/e2e/toolbox_test.go
test/e2e/update_test.go
test/system/260-sdnotify.bats
test/system/280-update.bats
test/system/520-checkpoint.bats

As agreed in Planning meeting of 2024-03-20, Podman 5.x will
drop support for cgroups v1 and for runc. Make it so.
CI images built in https://github.com/containers/automation_images/pull/338
```release-note
Podman no longer supports runc nor cgroups v1 
```

Debian: switch to crun and cgroups v2

---

go.mod
go.sum
libpod/reset.go
vendor/github.com/containers/image/v5/pkg/blobinfocache/default.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Closes: https://github.com/containers/podman/issues/22825
```release-note
None
```

libpod: cleanup default cache on system reset

---

.cirrus.yml

Another new-VM import from
https://github.com/containers/automation_images/pull/338
...because the usual conflict dealio in that repo. This
should mostly be a NOP. All the major work was done in #22706.
```release-note
None
```

Sigh, new VMs again

---

test/e2e/run_seccomp_test.go

the condition doesn't work when the runtime to use is specified through its absolute path as the error message contains that.
Simplify the check and just look for "read from the init process".
Hitting this issue in the crun CI
```release-note
None
```

tests: simplify expected output

---

README.md
RELEASE_NOTES.md

Also adds in 5.0.1 - 5.0.3 which were missing.
```release-note
NONE
```

[CI:DOCS] Update release notes on Main to v5.1.0

---

contrib/podmanimage/stable/README.md

The path mentioned above is linked in the sysadmin article on running podman inside containers. The content has since been moved and users are getting a 404 there now. Add the path back with a readme pointing to the new location of the content.
Not sure if the article can be updated, but this seems like a good workaround for the time being. Link to article is https://www.redhat.com/sysadmin/podman-inside-container.
```release-note
None
```

[CI:DOCS] Add contrib/podmanimage/stable path back in repo

---

test/e2e/manifest_test.go

The e2e tests already depend on skopeo anyway and pulling a over 300 MB image is not helpful for flakes but most importantly we see ENOSPC flakes. I see them around the skopeo test so I assume the big image is pushing the tmpfs limits so other tests running in parallel can start failing because of it.
```release-note
None
```

test/e2e: use local skopeo not image

---

RELEASE_NOTES.md

runlabel` should be `podman container runlabel`.  Note: I am not fixing past references before this on purpose.
Fixes #22871
```release-note
None
```

Fix 5.1 release note re: runlabel

---

contrib/cirrus/mac_setup.sh
pkg/machine/e2e/machine_test.go

Cherry-pick from PR #22773
Previously, the mac podman-machine tests installed rosetta before executing any tests.  As a best-practice (and because the Macs in CI are shared) tests should never permanently modify the system.  As of this commit, the system setup script used for the CI Macs does the rosetta installation.  Remove the test setup code that installed rosetta and add a CI-level confirmation that it's been pre-installed.
Also ref: [#22865](https://github.com/containers/podman/pull/22865#issuecomment-2145753387)
```release-note
None
```

[v5.1] Mac PM test: Require pre-installed rosetta

---

libpod/container_internal_linux.go
test/e2e/run_dns_test.go

Closes #22729 
```release-note
None
```

libpod: hostname written to /etc/hostname ends with a newline character

---

go.mod
go.sum
pkg/rootless/rootless_linux.c
vendor/github.com/containers/common/libimage/manifests/manifests.go
vendor/github.com/containers/common/libnetwork/cni/network.go
vendor/github.com/containers/common/libnetwork/netavark/network.go
vendor/github.com/containers/common/pkg/config/config_bsd.go
vendor/github.com/containers/common/pkg/config/config_windows.go
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/default_bsd.go
vendor/github.com/containers/common/pkg/config/default_common.go
vendor/github.com/containers/common/pkg/password/password_supported.go
vendor/github.com/containers/common/pkg/version/version.go
vendor/github.com/containers/common/version/version.go
vendor/modules.txt

This is a bit weird and I admit I don't understand exactly how the init
value is used but this seems wrong. When podman reexec itself it then
gets the wrong init value and because rootless_uid() will be 0 the
init() function in rootless_linux.go will not set it either because of
that. Thus the first reexec has the wrong env.
Now that I make use of it in c/common[1] this turns out top be a real
issue and is failing all first podman commands. To reproduce make sure
to kill the pause process then just run any podman command with the new
c/common vendor and without this patch.
[1] https://github.com/containers/common/pull/2020
```release-note
None
```

pkg/rootless: set _CONTAINERS_USERNS_CONFIGURED correctly

---

libpod/container_internal.go
libpod/healthcheck.go
libpod/healthcheck_linux.go
libpod/healthcheck_nosystemd_linux.go
libpod/healthcheck_unsupported.go
test/system/220-healthcheck.bats

This fixes a regression added in commit 4fd84190b8, because the name was overwritten by the createTimer() timer call the removeTransientFiles() call removed the new timer and not the startup healthcheck. And then when the container was stopped we leaked it as the wrong unit name was in the state.
A new test has been added to ensure the logic works and we never leak the system timers.
Fixes #22884
```release-note
Fixed a regression from v5.1.0 which caused systemd startup healthcheck timer units to be leaked even after the container is stopped.
```

libpod: do not leak systemd hc startup unit timer

---

rootless.md

add information about pasta and how its behaviour changes the way a user needs to think about inter-container connections, as without configuration they aren't able to reach each other (assuming single interface)
```release-note
None
```

[CI:DOCS] podman 5, pasta and inter-container networking

---

CONTRIBUTING.md

Fix a couple of references to main branch in CONTRIBUTING.md
```release-note
None
```

[CI:DOCS] Rename master to main in CONTRIBUTING.md

---

cmd/podman/common/build.go
test/e2e/build_test.go
test/system/070-build.bats

This is the same as what --squash-all is doing, and we already support --squash with --layers=true since this is the default.
```release-note
You can now use `podman build --squash --layers=false` at the same time.
```

--squash --layers=false should be allowed

---

libpod/container_internal_linux.go
test/e2e/restart_test.go
test/system/045-start.bats

If a container was stopped and we try to start it before we called cleanup it tried to reuse the network which caused a panic as the pasta code cannot deal with that. It is also never correct as the netns must be created by the runtime in case of custom user namespaces used. As such the proper thing is to clean the netns up first.
```release-note
Fixed a small race where podman start could panic when it tried to start a container in the stopped state.  
```

libpod: do not reuse networking on start

---

pkg/machine/apple/apple.go
pkg/machine/apple/vfkit.go

When running with "log-level=debug" and libkrun as machine provider, spawn a Terminal to execute "krunkit" to enable users to have full access to the VMs console for debugging purposes.
Users obtain an interactive, text console with scrollback. It's possible to interact with both the kernel and GRUB2. To obtain even additional debugging information, users can add "console=hvc0" to the linux kernel command line through GRUB2 (it may be worth considering extending the initial configuration of the VM to add that argument by default).
```release-note
None
```

Enable libkrun provider to open a debug console

---

cmd/podman/root.go
libpod/options.go
pkg/domain/entities/engine.go
pkg/domain/infra/runtime_libpod.go

add a new flag that allows to override the pull options configured in the storage.conf file.
e.g.: --pull-option="enable_partial_images=false" can be specified to Podman to disable partial pulls even if enabled.
Leave it as a hidden configuration flag for now since the API itself is marked as experimental in c/storage.
Currently c/storage doesn't honor the overrides, being fixed with https://github.com/containers/storage/pull/1966
```release-note
None
```

podman: add new hidden flag --pull-option

---

test/e2e/healthcheck_run_test.go
test/e2e/manifest_test.go
test/e2e/network_test.go
test/e2e/play_kube_test.go
test/e2e/pod_create_test.go
test/e2e/pull_test.go
test/e2e/run_networking_test.go
test/e2e/untag_test.go
test/e2e/volume_exists_test.go

Low-hanging fruit: Exit(X) with no error message
is now ExitWithError(X, "")
```release-note
None
```

ExitWithError, continued

---

.github/workflows/release-artifacts.yml

Rather than manually crafting what ends up being nearly identical
release e-mails, do it automatically whenever a release is created.
Note: At the time of this commit, there is a possible race condition
with the `mac-pkg.yml` workflow, since it runs in parallel.  It could
fail, or fail to complete prior to the e-mail content being generated.
This should be unlikely, if `release-artifacts.yml` goes through and
compiles every artifact, but it's not guaranteed.
```release-note
None
```

[skip-ci] GHA: Send release notification mail

---

.github/workflows/release-artifacts.yml

Assist humans by indicating clearly whe a release announcement is pertaining to a candidate.  Otherwise, it's possible someone may overlook the `-rcX` version suffix.
```release-note
None
```

[skip-ci] Release workflow: Include candidate descriptor

---

contrib/cirrus/setup_environment.sh

No idea why we need them, it passes without them so I just remove them.
Currently CI is broken as this install is failing on rawhide for some
reason. I don't know what changed there but this is working and unblocks
CI so I like to get this in.
```release-note
None
```

CI: do not install python packages at runtime

---

docs/source/markdown/podman-systemd.unit.5.md

No
```release-note
None
```
Resolves: #19125

[CI:DOCS] Quadlet - add note about relative path resolution

---

pkg/machine/wsl/machine.go
pkg/machine/wsl/stubber.go
pkg/machine/wsl/wutil/wutil.go

First of some commands ignored cmd.Wait() error which means it was impossible to notice any command errors. And other just returned the wait error as it which is when a command fails just `exit status <code>` which is not helpful at all.
This commit should add proper error wrapping with stderr to get useful strings back hopefully.
```release-note
None
```

pkg/machine/wsl: wrap command errors

---

libpod/sqlite_state.go
test/system/760-system-renumber.bats

The `VolumeConfig` table does not have an `ID` column, thus use the `Name` column to update it. This will fix #23052.
```release-note
Fixed podman system renumber if a volume exists.
```

sqlite_state: Fix RewriteVolumeConfig

---

.cirrus.yml
contrib/cirrus/CIModes.md
contrib/cirrus/cirrus_yaml_test.py

We do not have to test everything for each PR, we can know based on the source if we changed (i.e. machine code) and only run the tests then.
This implements it as skip conditions, due to the nature of yaml files we unfortunately cannot deduplicate everything, i.e. the is PR check and danger files apply to everything but as skip is only a single yaml string we cannot deduplicate parts of that string. If anyone knows a way to achieve this I like to hear it.
For now I implemented this for int, system, bud and machine tests. Once we are more comfortable with this I plan on adding it to other tests as well.
This will replace the current _bail_if_test_can_be_skipped logic as it covers more, marks tasks actually skipped in the github UI and works even for the windows/macos machine tests. …

cirrus.yml: implement skips based on source changes

---

pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/template@.container
test/e2e/quadlet/template@instance.container

<!--
Yes
```release-note
Quadlet - use un-escaped prefix and instance names for container name in a template
```

Quadlet - use specifier for unescaped values for templated container name

---

.cirrus.yml

Built in: https://github.com/containers/automation_images/pull/361
Main changes:
- lots of package bumps, see link above. Most important is debian systemd, which should fix the XDG bug in 256-rc3
- workaround for rawhide IMA (signed rpms) issue
- rawhide now includes composefs
```release-note
None
```

CI VMs: bump

---

test/system/700-play.bats

PR #22821 (CI speedup) was overly aggressive in one kube test.
It's flaking. Bump up timeout from 3s to 4.
```release-note
None
```

systests: kube: bump up a timeout

---

pkg/checkpoint/checkpoint_restore.go
test/e2e/checkpoint_test.go

Currently, when Podman restores a container into a Pod, it always fails with the following error:
Error: cannot add container f96670b26e53e70f7f451191ea39a093c940c6c48b47218aeeef1396cb860042 to pod h2-pod: no such pod
```console
podman pod create --name=test
podman run -d --pod=test --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
podman container checkpoint -l --export=/tmp/test.tar.gz
podman rm -a
podman pod rm -a
podman pod create --name=test
podman container restore --pod=test --import=/tmp/test.tar.gz
```
This error occurs because [`r.state.Pod()`](https://github.com/containers/podman/blob/b8d95a5893572b37c8257407e964ad06ba87ade6/libpod/boltdb_state.go#L2087) is called in [`setupContainer()`](https://github.com/containers/podman/blob/b8d9 …

restore: fix container restore into pod

---

pkg/api/server/register_images.go

Closes #23040 
Looks like these parameters have been implemented for some time on the api handler functions, just missed documentation originally. I mostly erred towards copying existing documentation for these properties with some minor edits to work better in API docs specifically. I also modified the description format for some of the existing parameters on the two endpoints I updated so that the formats would match.
Updated docs
```release-note
Updates OpenAPI list of parameters accepted to Push Image endpoints to match full list accepted by the API.
```

[CI:DOCS] Adds all PushImage supported paramters to openapi docs

---

cmd/podman/root.go
pkg/domain/entities/engine.go
test/system/272-system-connection.bats

When a user specifies a invalid connection in CONTAINER_CONNECTION then podman should return a proper error saying so. Currently it ignored the error and in rootFlags() just exited early with defining any flags. This caused a panic then when trying to use the flags later.
In order to address this first store the connection error in the PodmanConfig struct and not abort right away during flag setup. This is important as the user might have specified a flag with a valid remote connection. As such we check all flags and only when none were given we return the connection error.
Also while at it I noticed that the default connection reported via podman --help was wrong as it only used the old containers.conf field for it and did not consider the podman-connections.json default.
New regression …

remote: fix incorrect CONTAINER_CONNECTION parsing

---

cmd/podman/common/build.go
docs/source/markdown/options/pull.image.md
docs/source/markdown/podman-build.1.md.in
test/system/070-build.bats

```release-note
Fix documentation on default --pull value for podman build.
```

Remove references to --pull=true and --pull=false 

---

libpod/container_internal.go
libpod/container_internal_common.go
libpod/oci_conmon_common.go
libpod/oci_conmon_freebsd.go
libpod/oci_conmon_linux.go

with the new mount API is available, the OCI runtime doesn't require that each parent directory for a bind mount must be accessible. Instead it is opened in the initial user namespace and passed down to the container init process.
This requires that the kernel supports the new mount API and that the OCI runtime uses it.
Closes: https://github.com/containers/podman/issues/23028
```release-note
Now Podman requires the new kernel mount API (available since Linux 5.2) to configure containers in a new user namespace where the current user is not part of the mapping
```

libpod: do not chmod bind mounts

---

libpod/container_config.go
libpod/container_internal_common.go
test/system/250-systemd.bats

```release-note
Now Podman specifies the StopTimeout to systemd, so that it is honored when systemd stops the scope
```

container: pass StopTimeout to the systemd slice

---

cmd/podman/diff/diff.go
test/e2e/diff_test.go

When running `diff` with no args in `podman-remote`, the error message suggested the `--latest` flag.
However, this flag does not exist in `podman-remote`, so the error message was modified to improve usability.
Closes: https://github.com/containers/podman/issues/23038
```release-note
Improve error message in `podman-remote diff`. No longer suggesting flags that are not provided.
```

fix(diff): do not suggest `--latest` when runs on remote with no args

---

test/e2e/pod_initcontainers_test.go
test/e2e/pod_restart_test.go
test/e2e/pod_start_test.go
test/e2e/pod_stop_test.go
test/e2e/pod_top_test.go

Add error-message checks to pod_xxxx_test.go
```release-note
None
```

ExitWithError() - more upgrades from Exit()

---

docs/source/markdown/podman-systemd.unit.5.md

Add information about Type=oneshot units as suggested in https://github.com/containers/podman/issues/22233
```None```

[CI:DOCS] Add information about Type=oneshot units in podman-systemd.unit.5.md (fixes #22233)

---

pkg/machine/e2e/machine_test.go

Stop copying the pre-pulled uncompressed machine disk into the individual test dir. The machine pull code already makes a copy of the disk into the test's HOMEDIR/.local/share/containers/podman/machine, and works off that copy.
Before the change: `TESTDIR/<image>` is copied to `TESTDIR/podman_test/<image>` by the test, and then podman machine copies the image to `TESTDIR/podman_test/.local/share/containers/podman/machine/provider/<image>`
After the change: `TESTDIR/<image>` is copied to `TESTDIR/podman_test/.local/share/containers/podman/machine/provider/<image>` by podman machine
The image that is actually run is at `TESTDIR/podman_test/.local/share/containers/podman/machine/provider/<image>` in both instances.
```release-note
None
```

pkg/machine/e2e: Remove unnecessary copy of machine image.

---

contrib/cirrus/setup_environment.sh
pkg/machine/apple/apple.go
pkg/machine/e2e/basic_test.go
pkg/machine/provider/platform.go
pkg/machine/qemu/command/command.go
pkg/machine/qemu/command/qemu_command_test.go
pkg/machine/qemu/machine.go
pkg/machine/qemu/options_linux_amd64.go
pkg/machine/qemu/options_linux_arm64.go
pkg/machine/qemu/stubber.go
pkg/machine/qemu/virtiofsd.go
pkg/machine/volumes.go

machine/linux: Use memory-backend-memfd by default
This is prep for using virtiofsd; it has no real
impact otherwise.
Signed-off-by: Colin Walters <walters@verbum.org>
---
machine: Also initialize virtiofs mounts
I'm hitting a bug with 9p when trying to transfer large files.
In RHEL at least 9p isn't supported because it's known to have a
lot of design flaws; virtiofsd is the supported and recommended
way to share files between a host and guest.
This patch somewhat hackily sets up parallel virtiofsd mounts
alongside the 9p mounts (just on the host side, but one
can then easily mount in the guest).
This is allowing me to do some side-by-side comparisons
with the exact same machine.
I think what we can do in the short term is make
this a hidden option to enable (both "alongside" and also …

machine/linux: Switch to virtiofs by default

---

cmd/podman/common/create.go
cmd/podman/kube/play.go
pkg/specgenutil/specgen.go
test/e2e/run_userns_test.go

The pod was set after we checked the namespace and the namespace code only checked the --pod flag but didn't consider --pod-id-file option. As such fix the check to first set the pod option on the spec then use that for the namespace. Also make sure we always use an empty default otherwise it would be impossible in the backend to know if a user requested a specific userns or not, i.e. even in case of a set PODMAN_USERNS env a container should still get the userns from the pod and not use the var in this case. Therefore unset it from the default cli value.
There are more issues here around --pod-id-file and cli validation that does not consider the option as conflicting with --userns like --pod does but I decided to fix the bug at hand and don't try to fix the entire mess which most likely …

podman run use pod userns even with --pod-id-file

---

test/system/252-quadlet.bats

This test is used to ensure the default configuration for quadlets generated service files is sending stdout/stderr/syslog to the journald.
```NONE
```

test/system: Add test for journald log check in quadlet

---

libpod/container_internal_common.go
test/system/520-checkpoint.bats

The restore code path never called completeNetworkSetup() and this means that hosts/resolv.conf files were not populated. This fix is simply to call this function. There is a big catch here. Technically this is suposed to be called after the container is created but before it is started. There is no such thing for restore, the container runs right away. This means that if we do the call afterwards there is a short interval where the file is still empty. Thus I decided to call it before which makes it not working with PostConfigureNetNS (userns) but as this does not work anyway today so  I don't see it as problem.
Fixes #22901
```release-note
Fixed a bug where /etc/hosts and /etc/resolv.conf in the container were empty after checkpoint restore.
```

restore: fix missing network setup

---

pkg/machine/apple/vfkit/helper.go

The current timeout was not long enough. Systemd default is 90s so we should wait for at least that long. Also it really doesn't make sense to throw an error we saying we failed waiting for stop. We should hard terminate the VM in case a graceful shutdown did not happen.
Fixes #22515
```release-note
Podman machine on apple now wait 90s for the machine to stop then performs a hard shutdown.
```

pkg/machine/apple: machine stop timeout

---

Makefile
contrib/cirrus/lib.sh
contrib/cirrus/logformatter
contrib/cirrus/runner.sh

Two enormous misunderstandings:
1. $CIRRUS_BASE_SHA is worthless. I thought it was, you know, the BASE SHA of the current commit, but (as best I can tell) it seems to be the SHA of the most recent commit on the destination branch. Cirrus docs are unhelpful. Anyhow, it's clearly not anything useful. Stop using it.
2. $EPOCH_TEST_COMMIT is closer to what we want. It is defined in Makefile as the git merge-base. But for unknown reasons it was being clobbered in CI scripts, and it doesn't seem to work in all contexts, so, eliminate it from CI setup scripts. Leave it only in Makefile.
This leaves us with no option other than defining our own merge-base variable, PR_BASE_SHA. Do so and pass it along to rootless jobs.
```release-note
None
```

CI: logformatter: link to correct PR base

---

pkg/api/handlers/compat/images_build.go
pkg/api/server/register_images.go
test/apiv2/10-images.at

The docker API uses only a single arg for platform and multiple platforms are given as comma separated list.
Fixes #22071
```release-note
The build API now accepts platform values comma separated to better match docker.
```

build API: accept platform comma separated

---

libpod/container_top_linux.c
libpod/container_top_linux.go
test/e2e/top_test.go

When we execute ps(1) in the container and the container uses a userns with a different id mapping the user id field will be wrong.
To fix this we must join the userns in such case.
Fixes #22293
```release-note
Fix cases where podman top would show the incorrect uid for the processes when the container is using a user namespace.
```

podman top: join the container userns

---

.cirrus.yml
Makefile
contrib/cirrus/runner.sh
contrib/cirrus/setup_environment.sh

Linting code changes with golangci-lint is a very slow and resource
intensive process.  However, it does not depend on compiling anything.
This means it may run in parallel with the build tasks for
a modest perceived runtime duration improvement.
Additionally, the former validation make targets that **do** require a
build execute faster than CI is able to provision a VM, simply tack them
onto the end of all build operations.
```release-note
None
```

Run linting in parallel with building

---

.cirrus.yml

For many months this task has not been cross-compiling, it's building natively on a Mac.  Avoid any possible confusion by renaming the task.
```release-note
None
```

[CI:BUILD] Minor: Rename the OSX Cross task

---

rpm/podman.spec

All our active envs except centos stream 9 support autochangelog and the only place we're building rpms via packit on centos stream 9 is on COPR where we don't really care about changelogs.
Commit also removes a couple of unnecessary slashes from install paths.
```release-note
None
```

[skip-ci] Remove conditionals from changelog

---

.cirrus.yml
contrib/cirrus/runner.sh

cirrus: remove redundant skip logic
As of commit https://github.com/containers/podman/commit/d9183f0587950b8bdaebbc1ffe321965cb026397 we use the cirrus.yml skip logic to skip based
on source changes. As such the add hoc logic inside our test setup can
be removed. However as I did not yet implement the skip logic for all
tests task in cirrus.yml it must remain for the other tasks for now.
I plan to migrate the other in a week or two once we are confident that
the cirrus.yml logic works well for us.
--- 
cirrus: reduce int tests timeout
Integration tests run around 15-20 mins now. Lower the timeout to 30m,
if we hit this something is very wrong and needs to be looked at and
there is no point in waiting much longer in case of a hang.
```release-note
None
```

cirrus: remove redundant skip logic and lower int timeout

---

libpod/container_top_linux.c

As this file uses open it needs to include fcntl.h. This should fix the build error seen on epel9[1], not sure why it works on the other platforms.
[1] https://download.copr.fedorainfracloud.org/results/packit/containers-podman-23113/epel-9-aarch64/07672197-podman/builder-live.log.gz
Fixes 65ed96585d ("podman top: join the container userns")
```release-note
None
```

libpod/container_top_linux.c: fix missing header

---

.cirrus.yml
pkg/machine/apple/apple.go

One problem on FCOS is that the root directory is immutable, as such in
order to mount arbitrary paths from the host we must make it mutable
again and create these dir on boot in order to be able to mount there.
The current logic was racy as it used one unit for each path and they
all did chattr -i /; mkdir -p $path; chattr -i / and systemd can run
these units in parallel. That means it was possible for another unit to
make / immutable before the unit could do the mkdir. I pointed this out
on the original PR[1] but we never followed up on it...
Now this here changes several things. First have one unit that does the
chattr -i / (immutable-root-off.service), it is hooked into
remote-fs-pre.target which means it is executed before the network
mounts (virtiofs) are done.
Then we have another …

apple virtiofs: fix racy mount setup 

---

.cirrus.yml

Previously it was easy for a maintainer to change a Cirrus-CI task name w/o realizing it would (later) cause a downstream task or the `artifacts` task to fail.  This is due to duplication of task names in URLencoded format.  Worse, `artifacts` task failures are inconsequential in PRs, and not all tasks are executed for every PR context (i.e. due to `skip` or `only_if` exclusions).  So induced name change failures may not be noticed until after a PR merges.
Improve the visibility of the situation by adding comments to all consequential names.  That is, task names where there is a URLencoded duplicate reference elsewhere.
Ref: https://github.com/containers/podman/pull/23105#issuecomment-2194270973
```release-note
None
```

Clearly indicate names w/ URLencoded duplicates

---

libpod/container_internal.go
test/system/030-run.bats

The scenario for inducing this is as follows:
1. Start a container with a long stop timeout and a PID1 that ignores SIGTERM
2. Use `podman stop` to stop that container
3. Simultaneously, in another terminal, kill -9 `pidof podman` (the container is now in ContainerStateStopping)
4. Now kill that container's Conmon with SIGKILL.
5. No commands are able to move the container from Stopping to Stopped now.
The cause is a logic bug in our exit-file handling logic. Conmon being dead without an exit file causes no change to the state. Add handling for this case that tries to clean up, including stopping the container if it still seems to be running.
Fixes #19629
Addresses: https://issues.redhat.com/browse/ACCELFIX-250
```release-note
None
```

[v4.4.1-rhel] Ensure that containers do not get stuck in stopping

---

contrib/cirrus/runner.sh

Followup to #23081, which broke this test on nightly cron.
```release-note
None
```

CI: Build-Each-Commit test: run only on PRs

---

pkg/machine/shim/networking.go

The logs are not verbose if `--debug` is not set, and very useful to
have if gvproxy exits unexpectedly.
```release-note
None
```

machine: Always use --log-file with gvproxy

---

cmd/podman/machine/init.go
cmd/podman/machine/set.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/set_test.go

Close loophole that would allow you to assign more memory than the system has to a podman machine
Fixes: #18206
```release-note
Fixed bug where user could assign more memory to a Podman machine than existed on the host.
```

Error when machine memory exceeds system memory

---

docs/source/markdown/options/network.md
pkg/specgen/generate/oci_linux.go
pkg/util/utils_linux.go
test/e2e/run_test.go

When a users asks for specific devices we should still add them and not
ignore them just because privileged adds all of them.
Most notably if you set --device /dev/null:/dev/test you expect
/dev/test in the container, however as we ignored them this was not the
case. Another side effect is that the input was not validated at at all.
This leads to confusion as descriped in the issue.
Fixes https://github.com/containers/podman/issues/23132
```release-note
The podman create/run `--device` option is no longer ignored when `--privileged` is used.
```

specgen: parse devices even with privileged set

---

cmd/podman/machine/reset.go
pkg/machine/provider/platform.go
pkg/machine/provider/platform_darwin.go
pkg/machine/provider/platform_windows.go
pkg/machine/shim/host.go

Podman machine reset now removes and resets machines from all providers availabe on the platform.
On windows, if the user is does not have admin privs, machine will only reset WSL, but will emit a warning that it is unable to remove hyperV machines without elevated privs.
```release-note
The `podman machine reset` command now removes machines from all providers. 
```

Podman machine resets all providers

---

pkg/machine/e2e/basic_test.go
pkg/machine/e2e/config_init_test.go
pkg/machine/e2e/info_test.go
pkg/machine/e2e/init_test.go
pkg/machine/e2e/init_windows_test.go
pkg/machine/e2e/inspect_test.go
pkg/machine/e2e/list_test.go
pkg/machine/e2e/machine_test.go
pkg/machine/e2e/os_test.go
pkg/machine/e2e/proxy_test.go
pkg/machine/e2e/reset_test.go
pkg/machine/e2e/rm_test.go
pkg/machine/e2e/set_test.go
pkg/machine/e2e/ssh_test.go
pkg/machine/e2e/start_test.go
pkg/machine/e2e/stop_test.go

pkg/machine/e2e: use tmp file for connections
On linux and macos the connections are stored under the home dir by
default so it is not a problem there but on windows we first check
the APPDATA env and use this dir as config storage. This has the problem
that it is not cleaned up after each test as such connections might leak
into the following test causing failues there.
Fixes https://github.com/containers/podman/issues/22844
---
pkg/machine/e2e: fix broken cleanup
Currently all podman machine rm errors in AfterEach were ignored.
This means some leaked and caused issues later on, see https://github.com/containers/podman/issues/22844.
To fix it first rework the logic to only remove machines when needed at
the place were they are created using DeferCleanup(), however
DeferCleanup() does not …

pkg/machine/e2e: fix broken cleanup

---

pkg/machine/e2e/machine_test.go
pkg/machine/shim/host.go

This PR is a couple of small fixes so that our CI would be capable of running the machine test suite on the libkrun provider.
RUN-2172
```release-note
None
```

Small fixes for testing libkrun

---

.cirrus.yml

Specifically, the included Debian image should not fail all networking tests.
Ref: https://github.com/containers/automation_images/pull/363
```release-note
None
```

Update CI VM images

---

cmd/podman/common/build.go
test/e2e/build_test.go

When the user specifies a Containerfile or Dockfile with the -f flag in podman build, if the file does not exist, the error should be intuitive to the user.
Fixed: #22940
```release-note
Improve error message when file specified by -f does not exist in build command
```

refactor(build): improve err when file specified by -f does not exist

---

contrib/cirrus/lib.sh
contrib/cirrus/setup_environment.sh
test/system/160-volumes.bats

Try to speed up the CI test by using tmpfs as container storage.
No idea if this works or will make a measurable difference but let's find out. 
```release-note
None
```

CI: mount tmpfs for container storage

---

test/system/030-run.bats
test/system/060-mount.bats
test/system/250-systemd.bats
test/system/252-quadlet.bats
test/system/280-update.bats
test/system/420-cgroups.bats
test/system/700-play.bats

- fix test name to reflect that it's not pasta-only
(followup from #21563)
- in one podman-update test run in OpenQA, defer assertion
failures so we can gather better data on regressions.
This would've been helpful in diagnosing bz2281805.
- add an error-message check to one test that needed it
(found by accident)
- add distro-integration test tag to a handful of new tests,
so they run in OpenQA. Found via 'git diff 33891e8 test/system'
and scanning for '^\+@test '. I only added tests that IMO
have some risk of interacting poorly with kernel or systemd
updates, e.g. quadlet, modules, tmpfs+noswap.
```release-note
None
```

System test fixes

---

.cirrus.yml
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
contrib/cirrus/CIModes.md
contrib/cirrus/cirrus_yaml_test.py

As we want to get rid of the special titles convert the existing skips to the only_if condition, this makes it more readable as we do not need to negate so much.
Then add similar conditions for all test tasks, this removes the need to a special title such as CI:DOCS as the logic is smart enough to only docs changes when no source code was changed.
```release-note
None
```

cirrus.yml: automatic skips based on source

---

pkg/machine/e2e/config_test.go
pkg/machine/e2e/machine_test.go

There seems to be a very bad flake where podman machine init takes to
long. It doesn't seem to be deadlocked it just has to copy the entire
image which is super slow in CI for some reason.
As such increase the timeout by 1m to 5m total. Hopefully this is good
enough for now. Second in case we still hit a timeout send SIGABRT which
makes go dump the stack trace sow e know if it seems to be doing
something or hangs on lock.
```release-note
None
```

pkg/machine/e2e: improve timeout handling

---

.cirrus.yml
contrib/cirrus/CIModes.md
contrib/cirrus/cirrus_yaml_test.py

This directory contains important tools such as ginkgo as such updates there should run through all testing and not skip anything.
Technically we do not need to run system tests as it doesn't use any tool from there but that
a) might change in the future and
b) would make the only_if rules much more complicated if we try to
exclude it and
c) updates in test/tools are rare and/or automated so it does not cause
inconveniences to run all anyway
```release-note
None
```

cirrus: add missing test/tools to danger files

---

pkg/domain/infra/abi/system_linux.go
pkg/rootless/rootless.go
pkg/rootless/rootless_freebsd.go
pkg/rootless/rootless_linux.c
pkg/rootless/rootless_linux.go
pkg/rootless/rootless_unsupported.go
test/system/550-pause-process.bats

The code currently tried to avoid joining the userns from conmon directly and rather joined to only read the pid file and then send this back to use so we could join the userns. From the comment this was done because we could not read the pid file. However this is no longer true as of commit 49eb5af301 and file is no always owned by the real user.
This means we can just remove this special logic and join the namespace directly there. A test has been added to check the rejoin logic with a custom uidmapping.
```release-note
None
```

pkg/rootless: simplify reexec for container code

---

libpod/runtime.go
libpod/runtime_worker.go

This is an attempt at fixing #22984.
It seems that if some background tasks are queued in libpod's `Runtime` **before** the [worker's channel](https://github.com/containers/podman/blob/4e9486dbc63c24bfe109066abbb54d5d8dc2489e/libpod/runtime_worker.go#L6) is set up (eg. in the refresh phase), they are not executed later on, but the workerGroup's counter is still ticked up. This leads podman to hang when the imageEngine is shutdown, since it [waits](https://github.com/containers/podman/blob/4e9486dbc63c24bfe109066abbb54d5d8dc2489e/libpod/runtime.go#L758) for the workerGroup to be done.
I'm not really sure why the function to queue a job works, as the queue object shouldn't exist, but I think that might be caused by my very sparse Go knowledge.
I would probably need some guidance to write a …

Fix hang boot podman

---

pkg/machine/e2e/config_test.go

The commands only make sense on macos so do not clutter the logs on linux/windows with the output.
```release-note
None
```

pkg/machine/e2e: run debug command only for macos

---

pkg/bindings/containers/attach.go

See:
- https://github.com/containers/podman-bootc/pull/59#issuecomment-2216051946
- https://github.com/containers/podman-bootc/pull/61
Sorry for not trying to fix this, but I am not aware of a remotely straightforward way to do so.
```release-note
None
```

containers/attach: Note bug around goroutine leak

---

.cirrus.yml
contrib/cirrus/setup_environment.sh

I'm happy to hear arguments for keeping this (and perhaps the one on main also?) and/or pointer at someone who is willing to debug and maintain it.  Otherwise IMO this task is just a waste of resources.
---
--**_OR_**--
---
At the time of this commit, on main this task includes:
```yaml
skip: $CI == $CI
```
Disable the test entirely on this branch due to multiple failures, difficulty debugging, lack of team expertise, and willpower to care.
Ref: https://cirrus-ci.com/task/4712403315720192
```release-note
None
```

[v5.1] Drop minikube CI test

---

.cirrus.yml
contrib/cirrus/lib.sh
contrib/cirrus/logformatter
contrib/cirrus/setup_environment.sh
docs/source/markdown/podman.1.md
test/e2e/common_test.go
test/e2e/config_amd64.go
test/e2e/config_arm64.go
test/e2e/config_ppc64le.go
test/e2e/info_test.go
test/system/005-info.bats
test/system/010-images.bats

Run root e2e & system tests using composefs on rawhide.
Write magic settings to storage.conf. That part is easy.
e2e tests, however, ignore storage.conf. They require everything
to be specified on the command line. And "everything", in the
case of composefs, includes a long complicated --pull-options
string which in turn requires containers-storage PR 1966
which, as of this writing, is finally vendored into podman.
```release-note
None
```

test composefs on rawhide

---

build_windows.md
contrib/cirrus/win-installer-main.ps1
contrib/win-installer/build-hooks.bat
contrib/win-installer/build-hooks.ps1
contrib/win-installer/build.ps1
contrib/win-installer/test-installer.ps1
winmake.ps1

Building the [MSI hook on Windows](`contrib/win-installer/podman-msihooks/check.c) currently requires [MinGW CC](https://www.mingw-w64.org/). This commit updates the build script (build-hooks.bat is now build-hooks.ps1) so that, when MinGW is absent but the C compiler included in Visual Studio BuildTools is installed, the latter is used to build the MSI hook.
Documentation in `build_windows.md` has been updated with the instructions to install VS BuildTools (not MSYS2/MinGW).
Another change included in the PR is the `installertest` target in windows Makefile (`winmake.ps1`) to run the Windows installer tests that are part of Cirrus CI.
```release-note
None
```

Using Visual Studio BuildTools as a MinGW alternative

---

.cirrus.yml
contrib/cirrus/get-local-registry-script
contrib/cirrus/lib.sh
contrib/cirrus/runner.sh
contrib/cirrus/setup_environment.sh
hack/podman-registry
pkg/bindings/test/images_test.go
test/NEW-IMAGES
test/apiv2/10-images.at
test/apiv2/20-containers.at
test/apiv2/test-apiv2
test/e2e/common_test.go
test/e2e/config.go
test/e2e/info_test.go
test/e2e/libpod_suite_remote_test.go
test/e2e/libpod_suite_test.go
test/e2e/load_test.go
test/e2e/pull_test.go
test/e2e/run_seccomp_test.go
test/registries-cached.conf
test/system/helpers.registry.bash

As of https://github.com/containers/automation_images/pull/357 our CI VMs include a local registry preloaded with all(*) images used in tests.
(*) where "all" means "most".
This PR sets up CI such that it will use that registry.
```release-note
None
```

CI: Use local cache registry

---

libpod/boltdb_state_internal.go
libpod/sqlite_state.go
libpod/util.go

When the path does not exist, filepath.EvalSymlinks returns an empty string - so we can't just ignore ENOENT, we have to discard the result if an ENOENT is returned.
Should fix Jira issue [RHEL-37948](https://issues.redhat.com/browse/RHEL-37948)
```release-note
Fixed a bug where Podman could throw errors about a database configuration mismatch if certain paths did not yet exist on the host.
```

Ignore result of EvalSymlinks on ENOENT

---

contrib/cirrus/setup_environment.sh
test/e2e/run_networking_test.go
test/system/500-networking.bats
test/upgrade/test-upgrade.bats

Make sure this passes podman CI before push out a default change.
ref: https://fedoraproject.org/wiki/Changes/NetavarkNftablesDefault
```release-note
None
```

test netavark nftables driver

---

contrib/cirrus/setup_environment.sh

contrib: use a distinct --pull-option= for each flag

---

cmd/podman/compose.go
docs/source/markdown/podman-compose.1.md.in

This PR is meant to fix https://github.com/containers/podman/issues/22904. It makes the warning message emitted by podman-compose when using an external provider point to podman-compose(1) which is also updated to include instructions on how to disable said message.
```release-note
Changed the warning message emitted by `podman-compose` when using an external compose provider. Instead of referring to "the documentation" it now refers to the man page of `podman-compose(1)` which is also updated to contain the relevant information.
```

Make podman-compose refer to podman-compose(1) when using an external provider

---

docs/source/markdown/podman-systemd.unit.5.md
pkg/systemd/quadlet/quadlet.go
test/e2e/quadlet/network-alias.container
test/e2e/quadlet/network-alias.pod
test/e2e/quadlet_test.go

Noticed this was missing while porting a compose file to a quadlet system.
```release-note
Add NetworkAlias= support for quadlet .container and .pod files.
```

Add NetworkAlias= support for quadlet .container and .pod files

---

libpod/container_api.go
libpod/container_internal.go
libpod/define/errors.go
libpod/oci_conmon_attach_common.go
pkg/api/handlers/compat/containers_start.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/abi/terminal/terminal_common.go

The current code did something like this:
lock()
getState()
unlock()
if state != running
lock()
getState() == running -> error
unlock()
This of course is wrong because between the first unlock() and second lock() call another process could have modified the state. This meant that sometimes you would get a weird error on start because the internal setup errored as the container was already running.
In general any state check without holding the lock is incorrect and will result in race conditions. As such refactor the code to combine both StartAndAttach and Attach() into one function that can handle both. With that we can move the running check into the locked code.
Also use typed error for this specific error case then the callers can check and ignore the specific error when needed. This …

fix race conditions in start/attach logic

---

cmd/podman/root.go
libpod/runtime.go
libpod/shutdown/handler.go
test/e2e/common_test.go
test/e2e/libpod_suite_remote_test.go
test/system/001-basic.bats

```release-note
Now "podman system service" does not leak a mount when it is terminated
```

test: podman system service doesn't leak mount on termination

---

cmd/podman/machine/init.go
docs/source/markdown/podman-machine-init.1.md.in
pkg/machine/define/initopts.go

The driver is now hardcoded again, and there can only be one type of mounts at a time (which one changes over time)
Revert "Make it possible to select the volume driver" This reverts commit 6630e5cf66cf76aefcfe9caebe5df4f37dd0bdd5.
The driver is now always virtiofs(d).
Previously it was always virtfs (9p).
```release-note
Remove the --volume-driver flag from podman machine init.
```
/cc @baude 
----
The flag was introduced, so that users could choose between sshfs and virtfs drivers:
* https://github.com/containers/podman/pull/12584
Mostly because some operating systems do not support 9p filesystems, such as RHEL
The real name should have been "reverse-sshfs", since it is calling back (to sftp on host)

Remove the unused machine volume-driver

---

test/system/010-images.bats
test/system/030-run.bats
test/system/helpers.bash

Many system tests use hardcoded names for containers, images,
and everything. This has worked because system tests run
serially. It will not work if we ever run in parallel.
Create a new safename() helper, and use it as follows:
myctr=c_$(safename)
myvol1=v1_$(safename)
...
Find current instances of hardcoded names, and replace
with safe ones.
Whether or not we ever end up parallelizing system tests,
this is simply good practice.
There are far too many instances to fix in one (reviewable) PR.
This is commit 1 of N.
```release-note
None
```

System tests: safe container/image/volume/etc names

---

go.mod
go.sum
pkg/domain/infra/tunnel/images.go
test/system/010-images.bats
vendor/github.com/containers/common/libimage/filters.go
vendor/modules.txt

Fixes https://github.com/containers/podman/issues/23120
```release-note
None
```

Do not crash on invalid filters

---

pkg/autoupdate/autoupdate.go
pkg/domain/infra/abi/system.go

If a container is removed during the loop we should just ignore it. No
reason to log this as error to the user.
Fixes https://github.com/containers/podman/issues/23279
```release-note
Fixed a race in podman auto-update and podman system df that would cause them to fail with an error if a container was removed at the same time.
```

podman auto-update/system df: fix ErrNoSuchCtr/Volume race

---

cmd/podman/system/connection/remove.go

Using the ExactArgs(1) function is better because we have less duplication of the error text and the ValidArgsFunction uses that to suggest shell completion. The command before this commit would suggest connection names even if there was already one arg on the cli set.
```release-note
None
```

system connection remove: use Args function to validate
