containers/podman

- pkg/farm/farm.go
Ensure that the map of builders we create links the builder name and not the farm name to the image engine of that node. This was a regression introduced during the farm conf rework.
There is no way to add a test for this as we will have to emulate remote nodes of different architectures.
```release-note
None
```
> Fix name for builder in farm connection

- test/system/500-networking.bats
nmap-ncat has been downgraded on Fedora, to 7.92.
nc -l -p PORT requires 7.95. Switch to nc -l ADDR PORT.
```release-note
None
```
> nc -p considered harmful

- test/system/700-play.bats
- test/system/helpers.bash
The short version: use unique pod/container/image names in
all kube tests. Also, eliminate all "podman rm anything -a" in tests,
and any tests that expect "ps -a" to be empty.
The long version: trying to review this as one blob. It will not go well.
The Goldilocks version (I hope): I've split this into six commits, each with a
general theme. Each of those is pretty long, but their content is fairly repetitious
hence easier to review.
```release-note
None
```
> CI: 700-play.bats: huge cleanup, with goal of making parallel-safe

- pkg/domain/infra/abi/pods_stats.go
- pkg/ps/ps.go
The pod name was queried without holding the container lock, thus it was possible that the pod was deleted in the meantime and podman just failed with "no such pod" as the errors.Is() check matched the wrong error.
Move it into the locked code this should prevent anyone from removing the pod while the container is part of it. Also fix the returned error, there is no reason to special case one specific error just wrap any error here so callers at least know where it happened.
Fixes #23282
```release-note
Fixed a race condition that could make podman ps --pod fail.
```
> podman ps: fix racy pod name query

- pkg/machine/compression/decompress.go
- test/system/610-format.bats
When the file is empty it is possible our code panics as bar.ProxyReader returns nil when the bar is finished which is the case for 0 size as it doesn't have to read anything from there. However as this happens on different goroutines it is race and most of the time still works.
To fix this simply skip the progress bar setup for empty files.
While at it fix the deprecated argument in the tests.
Fixes #23281
```release-note
None
```
> pkg/machine/compression: skip decompress bar for empty file

- test/system/500-networking.bats
Clean backport of #23310 
nmap-ncat has been downgraded on Fedora, to 7.92.
nc -l -p PORT requires 7.95. Switch to nc -l ADDR PORT.
```release-note
Fixes broken gating tests
```
> [v5.2] nc -p considered harmful

- contrib/pkginstaller/Makefile
Bump the bundled krunkit version from 0.1.1 to 0.1.2.
Fixes: #23194
None yet, as this is a fix for a feature that isn't present in a release.
> Bump bundled krunkit to 0.1.2

- pkg/machine/e2e/basic_test.go
- pkg/machine/qemu/stubber.go
- pkg/machine/shim/volume.go
Fixes #22364 
This PR adds specific handling of the command line arguments `-v ""` - special handling for empty string. `-v` being present suppresses defaults from the config, so, it is sufficient to implement it as no-op to achieve empty mounts. This happens as early as possible (before any machine specific logic would be called).
Additional change is to allow using QEMU w/o virtiofsd binary if there are no mounts needed and the binary will not be used to run additional daemon.
And the final change is to disable default mounts for e2e tests, which are not supposed to have any mounts. Implementation is a bit hacky it checks if the command is `machine init` and then traverses args to see if there are mounts requested, if no mounts in the list it will inject empty mount arguments and …
> Implement disable default mounts via command line

- libpod/pod.go
- pkg/domain/infra/abi/pods_stats.go
Like commit 55749af0c7 but for podman *pod* stats not the normal podman stats. We must ignore ErrCtrStopped here as well as this will happen when the container process exited.
While at it remove a useless argument from the function as it was always nil and restructure the logic flow to make it easier to read.
Fixes #23334
```release-note
Fixed a race in podman pod stats that could cause it to exit with a "container is stopped" error when showing all pod containers.
```
> podman pod stats: fix race when ctr process exits

- libpod/healthcheck.go
- test/e2e/healthcheck_run_test.go
- test/system/220-healthcheck.bats
Using the scanner is just unnecessary complicated an buggy as it will not read the final line with a newline. There is also the problem that it happens in a separate goroutine so it could loose output if we read the array before the scanner was done.
The API accepts a Writer so we can just directly use a bytes.Buffer which captures all output in memory without the need of another goroutine.
This also means that now we always include the final newline in the output. I checked with docker and they do the same so this is good.
Fixes #23332
```release-note
Fixed a bug that resulted in the healtcheck output not being correctly captured when it didn't include a final newline.
```
> libpod: correctly capture healthcheck output

- test/e2e/run_networking_test.go
These tests are flaking for unknown reasons. One problem could be ncat did not bound the port before we connect to it. Simple fix do not use ncat and just use the golang API to listen on the port without the extra ncat process. This should be race free in theory. Also do not run the nc container in the background, we want to see the errors from the ncat process in the container.
And because both tests do the same thing deduplicate them into one that just uses a loop to create both tests.
Fixes #23263
```release-note
None
```
> test/e2e: fix ncat tests

- contrib/cirrus/logformatter
Plus, I think my ampersand-quot change earlier this month
caused problems for firefox. We no longer need it (pull-option
does not need the funky double-quoted curly-brace string),
so, remove it.
```release-note
None
```
> logformatter: tweaks to pass html tidy

- build_windows.md
- contrib/cirrus/win-installer-main.ps1
- contrib/win-installer/README.md
- contrib/win-installer/burn.wxs
- contrib/win-installer/podman.wxs
- contrib/win-installer/test-installer.ps1
- winmake.ps1
This PR fixes #23244
A few things are included in this PR:
- The fix for [#23244](#23244) by changing the condition for setting the property `CREATE_MACHINE_PROVIDER_CONFIG_FILE` in `contrib/win-installer/podman.wxs`
- The fix for a regression in `contrib/win-installer/podman.wxs` that prevented finding a pre-existing `podman.exe` due to the check in the wrong folder (`ProgramFiles6432FolderSearch` instead of `ProgramFiles64FolderSearch`)
- The fix for a regression in `contrib/win-installer/burn.wxs` that made the Variable `SkipConfigFileCreation` not overridable
- A big refactoring of `contrib/win-installer/test-installer.ps1` to add automated tests of the scenarios that got broken above and more  
```release-note
None
```
> Fix windows installer deleting machine provider config file

- Makefile
No code changes. Just updates the commend for the build step to reflect actual process.
```release-note
None
```
> Fix outdated comment for the build step win-gvproxy

- pkg/machine/qemu/stubber.go
- pkg/machine/sockets/sockets.go
This adds generic utility to convert file system path into URL structure. Instead of string manipulation it uses URL parsing and building routines. Appending absolute path to `unix:///` URL out of the box correctly handles URL format on Windows platform, where filepath should be prepended by additional `/` before drive letter.
Example that it works correctly on Unix platforms https://go.dev/play/p/OgiwK3E_-KM
This utility could be reused in the future if Hyper-V Podman machine (or generally speaking any Podman machine on Windows platform, which utilizes `gvproxy` for networking) would publish AF_UNIX socket for API access in addition to npipe:// API access points.
Comparing to the old implementation it mandates that the Path should be absolute, but using relative paths for creating socket …
> Add utility to convert VMFile to URL for UNIX sockets

- Makefile
- build_windows.md
- contrib/cirrus/setup_environment.sh
- docs/source/markdown/podman-systemd.unit.5.md
- libpod/container_api.go
- pkg/api/handlers/compat/images_build.go
- pkg/machine/apple/apple.go
- pkg/machine/ocipull/ociartifact.go
- test/system/160-volumes.bats
> Run codespell on source

- test/system/040-ps.bats
- test/system/260-sdnotify.bats
Two tests failing in gating but never CI; add some debug
instrumentation to make it possible to find out what
is going on
```release-note
None
```
> CI: system tests: instrument to allow failure analysis

- test/system/250-systemd.bats
- test/system/505-networking-pasta.bats
see the commits
```release-note
None
```
> test/system: two networking test fixes

- Makefile
- contrib/pkginstaller/Makefile
- go.mod
- go.sum
- vendor/modules.txt
This contains a fix for a gvproxy crash on macos on fast connections with heavy network load.
This should fix https://github.com/containers/podman/issues/23114
```release-note
Update gvisor-tap-vsock to 0.7.4. This release contains a fix for a gvproxy crash on macOS when there is heavy network traffic on a fast link.
```
> build: Update gvisor-tap-vsock to 0.7.4

- libpod/kube.go
- pkg/api/handlers/libpod/pods.go
- pkg/domain/infra/abi/play.go
- pkg/specgenutil/specgen.go
- pkg/specgenutil/specgenutil_test.go
- test/system/700-play.bats
a few fixes to improve how "kube generate" and "kube apply" deal with user namespaces.
Now the yaml generated by "kube generate" stores the user namespace configuration for the pod, which is later used by "kube apply"
Closes: https://issues.redhat.com/browse/RHEL-13033
```release-note
Now "kube generate" stores the user namespace configuration that is used by "kube apply"
```
> kube generate/play restores the user namespace configuration

- test/e2e/pull_test.go
- test/e2e/push_test.go
- test/e2e/run_test.go
- Fix a test of encrypted pulls to actually test the right thing
- Update tests to be ready for future https://github.com/containers/image/pull/2321 , so that we can later vendor c/image without seeing test failures.
```release-note
None
```
> Prepare tests for better reuse with zstd:chunked pulls

- rpm/podman.spec
RHEL10 defaults to nftables and doesn't need
/usr/lib/modules-load.d/podman-iptables.conf so this should be Fedora only.
```release-note
None
```
> [skip-ci] RPM: podman-iptables.conf only on Fedora

- libpod/container.go
- libpod/container_internal.go
- libpod/healthcheck.go
- libpod/healthcheck_linux.go
- libpod/healthcheck_nosystemd_linux.go
- libpod/healthcheck_unsupported.go
- test/system/220-healthcheck.bats
Addresses: https://issues.redhat.com/browse/ACCELFIX-263,
https://issues.redhat.com/browse/RHEL-50506, and
https://issues.redhat.com/browse/RHEL-50507
Backports:  https://github.com/containers/podman/pull/22589 and
https://github.com/containers/podman/pull/22895 
```release-note
None
```
> [v4.9-rhel] Backport of healthcheck timers

- pkg/api/handlers/libpod/containers_create.go
- test/apiv2/25-containersMore.at
The value of the pointer might be changed while creating the container causing unexpected side effects.
```release-note
None
```
> pkg/api: do not leak config pointers into specgen

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/disableselinux.container
- test/e2e/quadlet/nestedselinux.container
Fixes: https://github.com/containers/podman/issues/23432
```release-note
None
```
> Use new syntax for selinux options in quadlet

- test/e2e/quadlet_test.go
Split the table to three based on the expected outcome
Use helper functions to reduce the amount of parameter required in each entry
No
```release-note
None
```
> Quadlet test - Split between success, warning and error cases

- cmd/podman/compose.go
- test/compose/test-compose
- Fixes: #23441
- Related: #23074
Also adds an alias `COMPOSE_WARNING_LOGS`, which is parsed as fallback if `PODMAN_COMPOSE_WARNING_LOGS` is not defined.
If neither is defined, previous behavior is retained.
```release-note
Respect the PODMAN_COMPOSE_WARNING_LOGS environment variable, which is equivalent to engines.compose_warning_logs in containers.conf.
```
> fix: disable compose_warning_logs if PODMAN_COMPOSE_WARNING_LOGS=false

- test/system/helpers.bash
BATS teardown logs are unreadable, making it almost impossible
to see tiny "Leaked this-or-that" messages.
Solution: new _run_podman_quiet() helper, replaces run_podman
in a small number of cases within teardown. Clunky, and
duplicative, sorry.
New helper for leak_check, basically spits out warnings (and
bumps error count) if it sees any output whatsoever from
individual "podman XXX ls" commands.
```release-note
None
```
> System tests: leak_test: readable output

- .github/workflows/release-artifacts.yml
Step `Trigger Windows Installer` fails if checkout is skipped
```release-note
None
```
> Never skip checkout step in release workflow

- libpod/container_internal.go
- test/system/030-run.bats
Closes: https://github.com/containers/podman/issues/23467
```release-note
Now volume copy-up honors the "idmap" option
```
> libpod: fix volume copyup with idmap

- .cirrus.yml
- contrib/cirrus/mac_runner.sh
- pkg/machine/e2e/basic_test.go
***Depends on:*** https://github.com/containers/automation/pull/208 + deployment into worker pool.
```release-note
None
```
> Add libkrun Mac task

- contrib/win-installer/test-installer.ps1
The test that checked that, on Windows, file `99-podman-machine-provider.conf` is not overridden when Podman is updated is failing after the release of Podman v5.2.0. 
This PR temporarily disables the test to unblock PR checks on main branch.
```release-note
None
```
> Temporarily disable failing Windows Installer CI test

- pkg/ps/ps.go
Race condition between listing containers and figuring out if it is a buildah container.
Fixe: https://github.com/containers/podman/issues/23492
```release-note
None
```
> Ignore missing containers when calling GetExternalContainerLists

- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
It's too difficult to keep the podman-machine image up-to-date.
And, we can't use the cache on Mac/Windows, so if quay is down
we're hosed no matter what.
Add a "nocache" mechanism to install_test_configs() and use that
in machine test setup.
```release-note
None
```
> CI: podman-machine: do not use cache registry

- contrib/win-installer/podman.wxs
- contrib/win-installer/test-installer.ps1
Use Schedule "afterInstallExecute" (instead of the default "afterInstallValidate") in the Windows
installer MajorUpgrade element. With that upgrades don't override eventual users changes to the podman
machine configuration file.
- [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/msi/removeexistingproducts-action)
- [WiX MajorUpgrade documentation](https://wixtoolset.org/docs/schema/wxs/majorupgrade/#attributes)
Fixes #23502
Related to #23495
```release-note
None
```
> Change Windows installer MajorUpgrade Schedule

- build_windows.md
- pkg/bindings/images/build.go
- pkg/bindings/images/build_test.go
- pkg/machine/e2e/README.md
- pkg/machine/e2e/basic_test.go
This PR partially fixes issues with the option `--build-context <label>=<path>` of `podman build`. 
This is enough to fix https://github.com/containers/podman/issues/17313 on macOS and Windows WSL with the default machine mounts. 
A complete fix of the option `--build-context` would require packaging the additional build contexts in some additional tars and update the `/libpod/build` endpoint to accept multi-part HTTP requests. But that's outside the scope of this PR.
```release-note
Fix VisualStudio Dev Containers Features on Windows
```
> Convert additional build context paths on Windows

- libpod/container_internal.go
The network cleanup can handle it when it is killed half way through as it spits out a bunch of error in that case on the next cleanup attempt. Try to avoid getting into such a state and ignore sigterm during this section.
Of course we stil can get SIGKILL so we should work on fixing the underlying problems in network cleanup but let's see if this helps us with the CI flakes in the meantime.
```release-note
None
```
> libpod: inhibit SIGTERM during cleanup()

- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/images.go
Fixes: https://github.com/containers/podman/issues/23507
```release-note
None
```
Very difficult to test, so no tests added.
> Remove another race condition when mounting containers or images

- .cirrus.yml
- pkg/machine/e2e/basic_test.go
- test/e2e/pull_test.go
- test/e2e/run_test.go
Source: https://github.com/containers/automation_images/pull/371
Also fix some small test bug where the exit code was not checked and add a work around for a new pasta issue.
```release-note
None
```
> Update CI images

- go.mod
- go.sum
- libpod/reset.go
- vendor/github.com/containers/image/v5/pkg/blobinfocache/default.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Cherry-picks #22830 into the Podman v4.9-rhel branch
Addresses:  https://issues.redhat.com/browse/ACCELFIX-267
```release-note
None
```
> [v4.9-rhel] libpod: cleanup default cache on system reset 

- pkg/machine/gvproxy.go
- pkg/machine/gvproxy_unix.go
- pkg/machine/gvproxy_windows.go
When removing the gvproxy pid file, under CI conditions we could hit a case where the PID file being removed seemed to have an open handle on it still.  I could not find anything in podman that left an open handle and gvproxy would have quit before this, so we think it is likely another process holding it.  I could not find root cause with CI because I could not trip the flake.
this new code allows windows (specifically hyperv bc WSL does not use GVProxy) to ignore an ERROR_SHARING_VIOLATION.
```release-note
None
```
> Ignore ERROR_SHARING_VIOLATION error on windows

- libpod/runtime.go
- test/system/005-info.bats
Strictly speaking we don't need the path yet, but it existing prevents a lot of strangeness in our path-checking logic to validate the current Podman configuration, as it was the only path that might not exist this early in init.
Fixes #23515
```release-note
Fixed a bug where rootless Podman could fail to validate the runtime's volume path on systems with a symlinked `/home` ([#23515](https://github.com/containers/podman/issues/23515)).
```
> Create volume path before state initialization

- pkg/domain/infra/abi/containers.go
- test/e2e/cleanup_test.go
The podman container cleanup command is not really intended for human use. Instead each conmon will spawn this command after the container exit to make sure we can cleanup resources asynchronously. However this command will always race against other foreground process such as podman rm -fa. Therefore it is possible that the ctr was already removed and we should not log errors in this case.
While these errors are normally not seen as the command is int he background you can see it if you enable syslog logging and then they just spam the log with useless errors so just ignore them.
```release-note
podman container cleanup command now ignore the error when the container does not exists 
```
> podman container cleanup: ignore common errors

- .cirrus.yml
- contrib/cirrus/cirrus_yaml_test.py
- test/python/docker/__init__.py
Previously these tests pulled some test images from quay, opening them up to networking-flake induced failures.  As has already been done for other tests, update to utilize the locally running registry server.
Also: Add `test/python/**` into the apiv2 task conditions as referenced
by the `Makefile` `localapiv2-python` target.
---
This is a guess at fixing flakes like https://api.cirrus-ci.com/v1/artifact/task/6485548934627328/html/apiv2-podman-fedora-40-root-host-sqlite.log.html
But also an update these tests should receive regardless.
```release-note
None
```
> Reduce python APIv2 test net dependency

- test/utils/utils.go
Basically commit ada4e1a8c1 for e2e tests. The timeout does not kill the process so if it is stucked it hangs forever. So make sure we kill it via SIGABRT.
```release-note
None
```
> test/e2e: improve command timeout handling

- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
Return the error not just log as the caller can then decide to log this and exit > 0. I also removed the c.valid check as I do not see what the purpose of this would be. c.valid is only false when the ctr was removed but then we should never get there as Cleanup() will not work on a container in removing state.
```release-note
None
```
> libpod: cleanupNetwork() return error

- hack/podmansnoop
```release-note
None
```
While working on `crun` appearing as `3` and checking podman code too, I spotted this and wanted to clarify that.
> chore(podmansnoop): explain why crun comm is 3

- test/apiv2/python/rest_api/fixtures/podman.py
- test/python/docker/__init__.py
**Depends on PR #23538**
CNI is no longer needed/supported.
```release-note
None
```
> Drop APIv2 CNI configuration

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
Rootless unit placed in `/etc/containers/systemd/users/$(UID)` will be loaded for root when `/etc/containers/systemd` is a symlink.
Fix: #23483
Try evaluate the path of `UnitDirAdmin` as a symbolic link.
```release-note
None
```
> Quadlet: Fix `userLevelFilter` when `UnitDirAdmin` is a symlink

- Makefile
- contrib/cirrus/setup_environment.sh
- test/python/requirements.txt
Previously there were two CI tasks that ended up both testing docker-py compatibility.  Remove the duplicate from the `localapiv2-python` make target, and symlink the identical requirements file.
```release-note
None
```
> De-duplicate docker-py testing

- libpod/sqlite_state.go
- test/system/760-system-renumber.bats
The VolumeConfig table does not have an ID column, thus use the Name column to update it.
Fixes #23052
This fixes an error when `podman system renumber` would fail if a volume existed.
Addresses: https://issues.redhat.com/browse/RHEL-50230 https://issues.redhat.com/browse/RHEL-50231
```release-note
None
```
> [v4.9-rhel] sqlite_state: Fix RewriteVolumeConfig

- README.md
GPG is the GNU tooling, PGP is the standard format.
```release-note
None
```
> [CI:DOCS] readme: replace GPG with PGP

- libpod/container_api.go
- libpod/container_internal.go
- test/e2e/inspect_test.go
We cannot unlock then lock again without syncing the state as this will
then save a potentially old state causing very bad things, such as
double netns cleanup issues.
The fix here is simple move the saveContainerError() under the same
lock. The comment about the re-lock is just wrong. Not doing this under
the same lock would cause us to update the error after something else
changed the container alreayd.
Most likely this was caused by a misunderstanding on how go defer's work.
Given they run Last In - First Out (LIFO) it is safe as long as out
defer function is after the defer unlock() call.
I think this issue is very bad and might have caused a variety of other
weird flakes. As fact I am confident that this fixes the double cleanup
errors.
Fixes …
> libpod: fix broken saveContainerError()

- docs/source/markdown/podman-systemd.unit.5.md
In podman-systemd we are intersecting the worlds of containers and systemd, and I had to stop and think to understand what `Exec=` does.
I tried to clarify things more here.
I found it especially confusing because the example at the very top of the file does:
```
Image=quay.io/fedora/fedora
Exec=sleep 10
```
But that only makes sense because the fedora base image (being generic) doesn't define an `ENTRYPOINT`, just a `CMD`.
But IMO by far the most common usage for podman-systemd is "app images" which conventionally should use `ENTRYPOINT` in general. Maybe we should change the default example, but I'm leaving that for a later followup.
(It perhaps would have been less confusing if this field
had been called `Args=` to make clear it's quite different
in practice from systemd `ExecStart=`) …
> [ci:docs] docs/podman-systemd: Try to clarify `Exec=` more

- cmd/podman/manifest/inspect.go
- pkg/api/handlers/libpod/manifests.go
- pkg/domain/entities/engine_image.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/system/012-manifest.bats
Fixes: https://github.com/containers/podman/issues/23163
```release-note
podman manifest inspect now includes annoations.
```
> Should not force conversion of manifest type to DockerV2ListMediaType

- cmd/quadlet/main.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/build.quadlet.servicename.volume
- test/e2e/quadlet/image.quadlet.servicename.volume
- test/e2e/quadlet/mount.container
- test/e2e/quadlet/mount.servicename.container
- test/e2e/quadlet/network.quadlet.servicename.build
- test/e2e/quadlet/network.quadlet.servicename.container
- test/e2e/quadlet/network.quadlet.servicename.kube
- test/e2e/quadlet/network.servicename.quadlet.pod
- test/e2e/quadlet/service-name.build
- test/e2e/quadlet/service-name.container
- test/e2e/quadlet/service-name.image
- test/e2e/quadlet/service-name.kube
- test/e2e/quadlet/service-name.network
- test/e2e/quadlet/service-name.pod
- test/e2e/quadlet/service-name.volume
- test/e2e/quadlet/volume.build
- test/e2e/quadlet/volume.container
- test/e2e/quadlet/volume.pod
- test/e2e/quadlet/volume.quadlet.servicename.build
- test/e2e/quadlet/volume.servicename.container
- test/e2e/quadlet/volume.servicename.pod
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
Yes
```release-note
Allow overriding the service name on all Quadlet unit types
Due to dependency enforcement, all referenced Quadlet files must exist even on dryrun 
```
> Quadlet override service name

- .github/renovate.json5
* The main change is a global "packageRules" config that encompasses all
rules instead of configuring them as options to a manager. [This is
a recommended change by the config-validation tool].
* The previous [header] comment included way too many details.  It also referenced
a docker-hub container image which is not accessible under all
circumstances.  Switch to the GitHub container registry and include
mention of the pre-commit hook that's available.
**N/B:** There's no good way to test this configuration other than running it through the validator (which I did).  If the python management needs adjusting, it can be done in a followup PR.
```release-note
None
```
> [skip-ci] Maintain renovate configuration

- pkg/util/utils.go
- pkg/util/utils_linux.go
Also replace os.IsNotExist(err) with errors.Is(err, fs.ErrNotExist)
Fixes: https://github.com/containers/podman/issues/23582
```release-note
None
```
> Fix race condition when listing /dev

- pkg/bindings/containers/containers.go
- pkg/domain/infra/tunnel/helpers.go
- test/system/050-stop.bats
When the cidfile does not exists and ignore is set the cli parser skips
the file without error and we call into the backend code without any
names at all. This should logically be a NOP but on remote it caused all
containers to be returned which caused podman stop to stop everything in
this case.
Fixes https://github.com/containers/podman/issues/23554
---
pkg/bindings/containers: handle ignore for stop
When the client gets a 404 back we know the container does not exists,
if ignore is set as well we should just ignore the error client side.
seen in https://github.com/containers/podman/issues/23554
```release-note
Fixed a bug that causes podman-remote --cidfile doesnotexists --ignore to stop all containers.
```
> remote: fix invalid --cidfile + --ignore

- contrib/cirrus/pr-should-include-tests
- contrib/cirrus/pr-should-include-tests.t
CI:DOCS is no more.
```release-note
None
```
> pr-should-include-tests: no more CI:DOCS override

- .github/renovate.json5
- contrib/cirrus/prebuild.sh
Fix a syntax error, also perform renovate config validation during CI.
Fixes #23586
```release-note
None
```
> [CI:ALL] Fix and validate renovate config

- libpod/lock/file/file_lock.go
> Additional potential race condition on os.Readdir

- test/system/050-stop.bats
Very few changes needed, all of them simple.
It is impossible to parallelize this entire file, because "stop -a".
Add tags to tests that can be parallelized, and comments to those
that can't.
```release-note
None
```
> CI: 050-stop.bats: make parallel-safe

- test/system/505-networking-pasta.bats
Do not rely on an arbitrary delay in order to ensure the port was bound in the container. Instead this approach checks if the port is bound in the netns and only then starts the client. This speeds up the entire test file by 50% but more importantly in parallel testing it solves hangs as the timeout there was unreliable.
Fixes #23471
```release-note
None
```
> test/system: pasta_test_do add explicit port check

- contrib/cirrus/prebuild.sh
CI will fail if quay is down, but a build-time check does not
help us in any way. It just introduces another pain point
where we have to hit the Rerun button.
```release-note
None
```
> CI: remove build-time quay check

- pkg/machine/ssh.go
By enabling UserKnownHostsFile=/dev/null option to the defaults in podman machine ssh we prevent the user from adding the host key multiple times.
Resolves: https://github.com/containers/podman/issues/23505
```release-note
None
```
> Fix known_hosts file clogging and remote host id

- docs/source/markdown/podman-wait.1.md.in
- libpod/container_api.go
- libpod/container_internal.go
- libpod/container_internal_linux.go
- libpod/runtime_volume.go
- libpod/runtime_volume_common.go
- test/system/030-run.bats
- test/system/500-networking.bats
The current code did several complicated state checks that simply do not work properly on a fast restarting container. It uses a special case for --restart=always but forgot to take care of --restart=on-failure which always hang for 20s until it run into the timeout.
The old logic also used to call CheckConmonRunning() but synced the state before which means it may check a new conmon every time and thus misses exits.
To fix the new the code is much simpler. Check the conmon pid, if it is no longer running then get then check exit file and get exit code.
This is related to #23473 but I am not sure if this fixes it because we cannot reproduce.
```release-note
Fixes a bug where `podman wait` would exit only after 20s on a fast restarting container with a restart policy of on-failure.  
```
> libpod: simplify WaitForExit()

- test/system/610-format.bats
Use safename instead of hardcoded object names. Requires moving
a test table down, into the function itself instead of global,
because the table needs to know object names.
Also: sneak in a workaround for dealing with quay flakes (in
image search). The local registry is allowing almost all tests
to pass even when quay is down, but this one test still needs
to hit quay.
```release-note
None
```
> CI: format test: make parallel-safe

- test/system/252-quadlet.bats
The usual, safename instead of hardcoded names or random_string.
And remove some rmi statements: we no longer clean up pause_image.
Been working great in #23275 all week.
```release-note
None
```
> CI: quadlet tests: make parallel-safe

- test/system/helpers.bash
- test/system/helpers.network.bash
- test/system/helpers.t
...by using a crude port lock-and-reserve mechanism. This is
a small cherrypick from code that has been working in #23275
over dozens of CI runs. Am separating out into a small PR
because it's stable, harmless to serial runs, and will
simplify the eventual review of #23275.
Closes: #23488
```release-note
None
```
> CI: system tests: make random_free_port() parallel-safe

- pkg/domain/infra/abi/containers.go
When we create a container we first create it in the storage then in the libpod db so there is a tiny window where it is seen as storage ctr but then by the time we mount it we see it was a libpod container.
Fixes #23637
```release-note
None
```
> podman mount: fix storage/libpod ctr race

- libpod/oci.go
- libpod/oci_conmon_common.go
- libpod/oci_missing.go
There are two major problems with UpdateContainerStatus() First, it can deadlock when the the state json is to big as it tries to read stderr until EOF but it will never hit EOF as long as the runtime process is alive. This means if the runtime json is to big to git into the pipe buffer we deadlock ourselves.
Second, the function modifies the container state struct and even adds and exit code to the db however when it is called from the stop() code path we will be unlocked here.
While the first problem is easy to fix the second one not so much. And when we cannot update the state there is no point in reading the from runtime in the first place as such remove the function as it does more harm then good.
And add some warnings the the functions that might be called unlocked.
Fixes #22246 …
> libpod: remove UpdateContainerStatus()

- docs/source/markdown/podman-wait.1.md.in
- libpod/container_api.go
- test/system/800-config.bats
By default wait only waits for the exit of a container, there is really no way to make it wait for the removal too when the container was created with --rm. I though I found a clever way in 8a943311db but this is not working race free. While it works most of the time any other parallel process might call syncContainer() before the cleanup process holds the lock until it removes it. As such the wait hack to only update the state and not sync the exit file did not work so we can drop that.
However the test wants to wait for the removal to happen by the cleanup process and we can already say --condition=removing to do this but this will throw an error if the ctr was removed instead of counting this as success so fix that as well.
Fixes #23640
```release-note
podman wait --condition=removing …
```
> podman wait: allow waiting for removal of containers

- go.mod
- go.sum
- vendor/github.com/checkpoint-restore/go-criu/v7/.gitignore
- vendor/github.com/checkpoint-restore/go-criu/v7/Makefile
- vendor/github.com/checkpoint-restore/go-criu/v7/main.go
- vendor/modules.txt
There is no new version yet but we like to use the new code[1] to debug a flake[2] in the podman CI. It will not fix it but the new error might give us a better idea what is going on.
[1] https://github.com/checkpoint-restore/go-criu/pull/175
[2] https://github.com/containers/podman/issues/18856
```release-note
None
```
> vendor: update go-criu to latest

- test/e2e/systemd_test.go
We have a lot of systemd and quadlet based tests in the system tests. This test doesn't seem very useful and it seems to flake so just remove it.
Fixes #23480
```release-note
None
```
> test/e2e: rm systemd start test

- Makefile
- test/README.md
As discussed in Aug 13 Cabal, we are almost at a point where
e2e tests are reliably passing on the first try. Let's try to
keep things that way, and not hide future flakes.
Closes: #17967
```release-note
None
```
> CI: disable ginkgo flake retries

- pkg/machine/apple/vfkit/helper.go
Podman machine on MAC can segfault on hard stop.
Fixes: #23654
```release-note
None
```
> Do not segfault on hard stop

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/cgroups-mode.container
- test/e2e/quadlet_test.go
Fixes #23664.
```release-note
Added a new key `CgroupsMode` to Quadlet container unit file.
```
> Add key CgroupsMode in Quadlet container unit

- .packit.yaml
When a new Fedora target (41 currently), is branched from rawhide, `fedora-latest` packit target will point to fedora-41, while `fedora-latest-stable` will point to `fedora-40`. Once fedora-41 has released, `fedora-latest` and `fedora-latest-stable` will both point to fedora-41.
So, to have Packit continue to create PRs for Fedora 40 once Fedora 41 has released, it's best to set the target back to `fedora-all`.
Caution: `fedora-all` will create v5.x PRs for Fedora-39 until it goes EOL. Since dist-git PRs need to be merged manually, we can just manually close F39 PRs.
```release-note
None
```
> [skip-ci] Packit: update targets for propose-downstream

- cmd/podman/containers/run.go
- libpod/container.go
- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/annotations.go
- libpod/define/container_inspect.go
- libpod/oci_conmon_common.go
- pkg/api/handlers/compat/exec.go
- pkg/domain/infra/abi/containers.go
- pkg/specgen/generate/oci_linux.go
- pkg/specgen/specgen.go
- pkg/specgenutil/util.go
- test/system/030-run.bats
This started off as an attempt to make `podman stop` on a container started with `--rm` actually remove the container, instead of just cleaning it up and waiting for the cleanup process to finish the removal.
In the process, I realized that `podman run --rmi` was rather broken. It was only done as part of the Podman CLI, not the cleanup process (meaning it only worked with attached containers) and the way it was wired meant that I was fairly confident that it wouldn't work if I did a `podman stop` on an attached container run with `--rmi`. I rewired it to use the same mechanism that `podman run --rm` uses, so it should be a lot more durable now, and I also wired it into `podman inspect` so you can tell that a container will remove its image.
Tests have been added for the changes to …
> Fix `podman stop` and `podman run --rmi`

- cmd/podman/containers/exec.go
- docs/source/markdown/podman-exec.1.md.in
Fixes: https://github.com/containers/podman/issues/22849
```release-note
None
```
> command is not optional to podman exec

- Makefile
- contrib/cirrus/pr-should-link-jira
- contrib/cirrus/pr-should-link-jira.t
- contrib/cirrus/prebuild.sh
- contrib/cirrus/runner.sh
In the RHEL specific branches we want to ensure that all MRs link to at least one downstream Jira ticket. To do this we add a new test in validate-source similar to the existing pr-should-include-tests. This test only runs on actual pull requests.
The syntax for linking to a Jira is "Fixes " followed by one jira links, like so:  
```
Fixes https://issues.redhat.com/browse/RHEL-50506
```
Note: This is the same syntax as for a regular github issue reference.
> CI: On vX.Y-rhel branches, ensure that some downstream Jira issue is linked

- cmd/quadlet/main.go
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/remap-auto.pod
- test/e2e/quadlet/remap-auto2.pod
- test/e2e/quadlet/remap-keep-id.pod
- test/e2e/quadlet/remap-manual.pod
- test/e2e/quadlet_test.go
```release-note
Added keys related to user mappings (e.g. `UserNS`) to Quadlet pod unit file.
```
> quadlet: support user mapping in pod unit

- test/system/170-run-userns.bats
- use safename
- add ci:parallel tags where possible
- where not possible, document why
```release-note
None
```
> CI: parallel-safe userns test

- RELEASE_NOTES.md
Missed that in the release PR for v5.2.2
```release-note
None
```
> [CI:DOCS] Add v5.2.2 lib updates to RELEASE_NOTES.md

- pkg/bindings/connection.go
- test/e2e/system_connection_test.go
Currently `podman system connection add` allows providing TCP connections with paths. However, these paths are not actually used.
```
➤ podman system connection list
Name        URI         Identity    Default     ReadWrite
➤ podman system connection add foo tcp://localhost:8080/some/prefix
➤ podman system connection list
Name        URI                               Identity    Default     ReadWrite
foo         tcp://localhost:8080/some/prefix              true        true
➤ podman --log-level debug --connection foo ps
INFO[0000] podman filtering at log level debug
DEBU[0000] Called ps.PersistentPreRunE(podman --log-level debug --connection foo ps)
DEBU[0000] DoRequest Method: GET URI: http://d/v5.1.2/libpod/_ping
...
```
_NB: The `d` value for host is an ignored placeholder value, …
> Use HTTP path prefix of TCP connections to match Docker context behavior

- pkg/machine/e2e/proxy_test.go
- pkg/machine/proxyenv/env.go
- pkg/machine/proxyenv/env_test.go
Quote systemd DefaultEnvironment Proxy values, as documented in systemd.conf man page:
```
Example:
DefaultEnvironment="VAR1=word1 word2" VAR2=word3 "VAR3=word 5 6" Sets three variables "VAR1", "VAR2", "VAR3".
```
Double quote is not escaped, as there is no chance it appears in a proxy value. User can still espace it if really necessary
Fixes #23277 
Fixes https://github.com/containers/podman-desktop/issues/7894
1. Declare proxy env vars in `containers.conf` file, with comma special character in `no_proxy`, for example (please replace proxy IP/port with your own):
```
env = [
'https_proxy=http://192.168.1.21:3128',
'http_proxy=http://192.168.1.21:3128',
'no_proxy=localhost,quay.io',
]
```
2. Create and start a new podman machine, and ssh to it
3. Check that no_proxy and NO_PROXY values …
> Quote systemd DefaultEnvironment Proxy values

- Makefile
- contrib/pkginstaller/Makefile
This should fix the regression reported in
https://github.com/containers/podman/issues/23616
```release-note
Update to gvproxy 0.7.5 to fix https://github.com/containers/podman/issues/23616
```
> build: Update gvisor-tap-vsock to 0.7.5

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/host.container
- test/e2e/quadlet/host.pod
- test/e2e/quadlet/ip.pod
- test/e2e/quadlet_test.go
Fixes: https://github.com/containers/podman/issues/23692
- Add support for --add-host for Pod and Container units. It is possible to specify multiple hosts for a single IP. 
- Add support for IP and IP6 for Pod units.
```release-note
Podman Quadlet Pod and Containers now supports AddHost
Podman Quadlet Pod now supports  IP and IP6
```
> Quadlet add support for --add-host --ip and --ip6

- libpod/container_internal.go
- test/system/500-networking.bats
Currently we deadlock in the slirp4netns setup code as we try to configure an non exissting netns. The problem happens because we tear down the netns in the userns case correctly since commit bbd6281ecc but that introduces this slirp4netns problem. The code does a proper new network setup later so we should only use the short cut when not in a userns.
Fixes #21477
Addresses: https://issues.redhat.com/browse/ACCELFIX-279
```release-note
None
```
> [v4.9-rhel] fix userns + restart policy with slirp4netns

- cmd/podman/containers/run.go
Since commit 458ba5a8af the cleanup process now removes the image as well, thus the removal is racy and it will cause an error here.
The code tried to ignore the error with errors.Is() but this never works across the remote API. However the API already has a ignore option so juts use that and fix the error message so that we can easily find the root cause and I do not have to guess where the log was written.
Fixes #23719
```release-note
None
```
> podman run: ignore image rm error

- .cirrus.yml
We already exclude the build jobs this is causing the machine tasks to fail as noticed in #23764. Given we do not need windows/macos testing for RHEL we have to skip them there.
While we try to only use only_if the problem here is that we would need to duplicate the big only_if_machine_test string and work the rhel condition into it which doesn't work with the current logic either so we would need to change the logic flow there which then doesn't work with our cirrus_yaml_test.py selftest. Therefore I think using skip here is easier.
```release-note
None
```
> cirrus: skip windows/macos machine task on RHEL branches

- test/system/505-networking-pasta.bats
Workaround (NOT A FIX) for pasta issue #23482, wherein
podman logs includes a waitpid: ESRCH warning. Consensus
seems to be that this is a bug in socat.
I have not seen the flake in my || PR since adding this, but now the flake is [in the wild](https://api.cirrus-ci.com/v1/artifact/task/4981562419183616/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00611) so am filing a small PR.
I hate this, because there's no timebomb or other mechanism to know if the socat bug is ever fixed, so this little workaround will stick around forever, annoying future maintainers.
```release-note
None
```
> CI: flake workaround: ignore socat waitpid warnings

- libpod/sqlite_state.go
This looks like a case of boilerplate error handling making it too easy to miss a legitimately ignored error, which is annoying. In a more featureful language most of the SQL code here could be macros (at the very least, Rust would have forced us to handle all error cases, not just the one seen here).
Found while looking through the Libpod DB code, no actual bug I can think of associated with this.
```release-note
NONE
```
> Fix an improperly ignored error in SQLite

- cmd/podman/containers/cleanup.go
- libpod/container_api.go
- libpod/pod_api.go
- pkg/api/handlers/compat/containers_attach.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/specgenutil/util.go
This is very similar to commit 3280da0500, we cannot check the state then unlock to then lock again and do the action. Everything must happen under one lock. To fix this move the code into the HTTPAttach function in libpod. Th elocking here is a bit weird because attach blocks for the lifetime of attach which can be very long so we must unlock before performing the attach.
Fixes #23757
```release-note
Fixed a race condition in the remote HTTP attach API that may cause it to fail
```
> fix races in the HTTP attach API

- Makefile
- docs/Makefile
- docs/source/markdown/.gitignore
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-commit.1.md
- docs/source/markdown/podman-images.1.md.in
- docs/source/markdown/podman-machine.1.md
- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-pull.1.md.in
- docs/source/markdown/podman-push.1.md.in
- docs/source/markdown/podman-remote.1.md
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman.1.md
- hack/xref-helpmsgs-manpages
- rpm/podman.spec
Generated at build time from troubleshooting.md. Purpose is
to ship an actual man page to end users.
Much more complicated than initial guess, because there was
a bug in my Makefile man page filtering, the sed expression
that cleans up markdown that does not translate to roff.
All I've done here is reorder some of the expressions,
stripping off https links *before* we process
podman man page links.
```release-note
Distribute podman-troubleshooting(7) man page
```
> Create a podman-troubleshooting man page

- .cirrus.yml
- DOWNLOADS.md
- Makefile
- contrib/cirrus/prebuild.sh
- contrib/cirrus/required_host_ports.txt
- contrib/cirrus/runner.sh
see commits
```release-note
None
```
> CI: some cirrus setup improvements/speedups 

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/build.multiple-tags.container
- test/e2e/quadlet/multiple-tags.build
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet - support multiple image tags for .build files
```
Resolves: #23781
> Quadlet - Support multiple image tags in .build files

- docs/source/conf.py
Read the Docs does some update by October 7, 2024 which will effect our builds per[1]. As such apply the recommended changes from there to our conf.py file so we do not get broken builds after that date hopefully.
[1] https://about.readthedocs.com/blog/2024/07/addons-by-default/#how-does-it-affect-my-projects
```release-note
None
```
> docs: update read the docs changes

- libpod/container_inspect_freebsd.go
This changes the value emitted for HostConfig.Devices from 'null' to '[]'. The 'null' value was preventing ansible's podman module from working correctly on FreeBSD.
```release-note
On FreeBSD hosts, fix the 'HostConfig.Device' value emitted by 'podman inspect'. This makes Ansible's podman module usable on FreeBSD.
```
> libpod: fix HostConfig.Devices output from 'podman inspect' on FreeBSD

- CONTRIBUTING.md
Per discussion within the team, we would like all bugfixes to be referenced in commit messages as "Fixes:" (or "Fixes" with no colon, for those who would like to type one less character). We are going to add CI to enforce this on our LTS branches as we should only be backporting bugfixes there.
```release-note
NONE
```
> Specify format to use for referencing fixed bugs.

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/network.reuse.container
- test/e2e/quadlet/network.reuse.name.container
- test/e2e/quadlet_test.go
```release-note
A container created by Quadlet can now reuse the network of another container by setting `Network=another.container`
```
> quadlet: support container network reusing

- test/system/015-help.bats
- test/system/065-cp.bats
- test/system/075-exec.bats
- test/system/271-tcp-cors-server.bats
- test/system/420-cgroups.bats
- test/system/600-completion.bats
- test/system/620-option-conflicts.bats
Add 'ci:parallel' tags to a few easy places. And, two
small easily-reviewed safename or random-port additions.
These have been working fine in #23275. I want to stop
carrying them there so I can work on simplifying my PR.
```release-note
None
```
> CI: system tests: parallelize low-hanging fruit

- docs/source/markdown/options/compat-auth-file.md
- docs/source/markdown/options/sign-by-sigstore.md
- docs/source/markdown/podman-login.1.md.in
- docs/source/markdown/podman-logout.1.md.in
- docs/source/markdown/podman-manifest-push.1.md.in
- docs/source/markdown/podman-push.1.md.in
We're supposed to catch duplicate man-page options in review,
but once in a while they sneak in. These are two dups that
are 100% identical, and were auto-refactored by a script
that I have. A few more options have snuck in (--dns, --usb)
but those have different text so they can't be handled by
my script. If anyone feels like refactoring those, go ahead.
```release-note
None
```
> man pages: refactor two more options

- test/system/055-rm.bats
Use safename, and add ci:parallel tags to all tests. (One
test was running "podman wait -l", which cannot work in
parallel. I choose to change it to "wait $cname", and
lose the -l testing)
```release-note
None
```
> CI: make 055-rm parallel-safe

- docs/source/markdown/podman-machine-info.1.md
- pkg/domain/entities/machine.go
Adds a note in the `podman machine info` manpage that clarifies
that `defaultmachine` in the `podman machine info` output does
not suggest that a user can set a default podman machine via
system connections.
Additionally adds a Podman 6.0 TODO comment to change the name of the
field to `ActiveMachineConnection` to better describe its purpose.
```release-note
Added a note in the `podman machine info` manpage to clarify the meaning of the `defaultmachine` output
```
> Add disclaimer in `podman machine info` manpage

- libpod/util_linux.go
The cgroup path following /sys/fs/cgroup/user.slice is not named user, but rather it is named after the parent slice.
Fixes #23780
```release-note
Fixed a bug where rootless Podman could fail to start container with option --cgroup-parent ([#23780](https://github.com/containers/podman/issues/23780)).
```
> libpod: fix rootless cgroup path with --cgroup-parent

- docs/source/markdown/podman.1.md
Mentions allowed `policy.json` location in $HOME, and links to further documentation.
Fixes: #23849
```release-note
podman.1.md: improve policy.json section
```
> podman.1.md: improve policy.json section

- test/e2e/common_test.go
- test/e2e/network_test.go
Creating networks in a different dir is not parallel safe when running containers on them as the network configs may end up using the same bridge names which then causes conflicts on the host.
Fixes #23876
```release-note
None
```
> test/e2e: fix network prune flake

- cmd/podman/images/prune.go
- docs/source/markdown/podman-image-prune.1.md
- pkg/api/handlers/libpod/images.go
- pkg/api/server/register_images.go
- pkg/bindings/images/types.go
- pkg/bindings/images/types_prune_options.go
- pkg/domain/entities/images.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- test/e2e/build/buildkit-mount/Containerfilecacheread
- test/e2e/build/buildkit-mount/Containerfilecachewrite
- test/e2e/build_test.go
`podman builder prune` and `podman image prune` should also support cleaning build cache using buildah's public `CleanCacheMount` API.
Reference: https://docs.docker.com/reference/cli/docker/builder/prune/
Fixes: https://github.com/containers/podman/discussions/15612#discussioncomment-10532721
Context: https://github.com/containers/buildah/pull/4490
```release-note
podman builder prune and podman image prune now cleans build cache as well using a new flag `--build-cache`
```
> prune: add `--build-cache` to support clearing build cache using `CleanCacheMount`

- .codespellrc
- .github/renovate.json5
- .github/workflows/check_cirrus_cron.yml
- .github/workflows/issue_pr_lock.yml
- .github/workflows/rerun_cirrus_cron.yml
- .github/workflows/update-podmanio.yml
- .pre-commit-config.yaml
- Makefile
- RELEASE_PROCESS.md
- docs/source/markdown/podman-manifest-add.1.md.in
- pkg/specgen/specgen.go
- test/apiv2/25-containersMore.at
codespell is not new to this project but not really part of the automated workflow(s) (precommit, CI).
There is `Makefile` rule but had hardcoded settings into it, so people had to use `make` and could not `pre-commit` or directly -- I moved configuration into `pyproject.yaml` so now if you have codespell (and tomli) installed - you can just codespell. 
CI workflow has 'permissions' set only to 'read' so also should be safe.
Also added pre-commit hook for it so no new typos would sneak in.
attn @rhatdan as I believe the codespell user ;)
> Add codespell support (config, workflow to detect/not fix) and make it fix few typos

- Makefile
- docs/Makefile
- docs/source/markdown/.gitignore
- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman-create.1.md.in
- docs/source/markdown/podman-run.1.md.in
- docs/source/markdown/podman.1.md
This is a follow up to 5389eee7376cf81fbfdaf58cd58d38b287f5da23 to add rooltess.md information to man pages to help users discover solutions to troubleshooting and rooless issues.
Specicifally I was surprised when binding to ports < 1024 was not covered in podman-troubleshooting.7 man page.
```release-note
podman-rootless.7 man page for troubleshooting rootless issues added.
```
> Add podman-rootless.7 man page

- contrib/cirrus/lib.sh
- contrib/cirrus/setup_environment.sh
It's too difficult to keep the podman-machine image up-to-date. And, we can't use the cache on Mac/Windows, so if quay is down we're hosed no matter what.
Add a "nocache" mechanism to install_test_configs() and use that in machine test setup.
Manual cherrypick of #23461 from main, one trivial conflict.
```release-note
None
```
> [v5.2] CI: podman-machine: do not use cache registry

- go.mod
- go.sum
- libpod/container_internal_common.go
- libpod/container_internal_linux.go
- test/system/505-networking-pasta.bats
- vendor/github.com/containers/common/libimage/filters.go
- vendor/github.com/containers/common/libimage/search.go
- vendor/github.com/containers/common/libnetwork/cni/run.go
- vendor/github.com/containers/common/libnetwork/etchosts/hosts.go
- vendor/github.com/containers/common/libnetwork/etchosts/ip.go
- vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
- vendor/github.com/containers/common/libnetwork/internal/util/util.go
- vendor/github.com/containers/common/libnetwork/internal/util/validate.go
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/pasta/pasta_linux.go
- vendor/github.com/containers/common/libnetwork/pasta/types.go
- vendor/github.com/containers/common/libnetwork/slirp4netns/slirp4netns.go
- vendor/github.com/containers/common/libnetwork/types/network.go
- vendor/github.com/containers/common/pkg/cgroups/systemd_linux.go
- vendor/github.com/containers/common/pkg/config/default_linux.go
- vendor/github.com/containers/common/pkg/hooks/exec/runtimeconfigfilter.go
- vendor/github.com/containers/common/pkg/netns/netns_linux.go
- vendor/github.com/containers/common/pkg/report/camelcase/camelcase.go
- vendor/github.com/containers/common/pkg/report/template.go
- vendor/github.com/containers/common/pkg/systemd/systemd_linux.go
- vendor/modules.txt
pasta added a new --map-guest-addr to option that maps a to the actual
host ip. This is exactly what we need for host.containers.internal
entry. So we now make use of this option by default but still have to
keep the exclude fallback because the option is very new and some
users/distros will not have it yet.
This also fixes an issue where the --dns-forward ip were not used when
using the bridge network mode, only useful when not using aardvark-dns
as this used the proper ips there already from the rootless netns
resolv.conf file.
Fixes https://github.com/containers/podman/issues/19213
```release-note
Podman now uses the pasta --map-guest-addr option by default which is used for the host.containers.internal entry to allow the container to reach the host by default. 
```
> libpod: make use of new pasta option from c/common

- cmd/podman/images/list.go
- docs/source/markdown/podman-images.1.md.in
- test/system/020-tag.bats
When you sort by repository a user most likely also want the tags to be sorted as well. At the very least to get a stable output as the order could be changed pull podman tag/pull even if they keep using the same tag name.
Fixes #23803
```release-note
podman images --sort repository now also sorts the tags as well
```
> podman images: sort repository with tags

- test/system/410-selinux.bats
Use safename for containers and pods. Add ci:parallel tags.
And reenable distro-integration tests that had been skipped
due to a container-selinux bug that is now fixed.
```release-note
None
```
> CI: make 410-selinux parallel-safe

- test/system/020-tag.bats
Use safename, with guaranteed-adjacent image names
```release-note
None
```
> CI: make 020-tag parallel-safe

- pkg/bindings/connection.go
The ssh options needs some weird parameters like (the raw) uri and machine (insecure), so it is not enough with url and identity.
i.e. it is not the generic "[ssh](https://pkg.go.dev/golang.org/x/crypto/ssh)", but the containers/common "[ssh](https://github.com/containers/common/tree/main/pkg/ssh)"
The "secure" query parameter was removed in Podman v4.3, it is now replaced with the "machine" option parameter (InsecureIgnoreHostKey)
commit 280f5d8cb01d115618d5ef131c718496a3b4900e
I think that url.Parse will fail to add any url.Port that is not an integer, so the strconv.Atoi error probably can never happen?
But since it is only a validation error and not a connection error, it cannot be wrapped in a ConnectError so that goes into function.
```release-note
None
```
> refactor: add sshClient function

- .cirrus.yml
- contrib/cirrus/prebuild.sh
- test/e2e/container_iface_name_test.go
Minor bump. Fedora VMs now include ShellCheck, so we can
remove the 'dnf install' at CI run time.
Also, FWIW, Debian *vark are now at 1.12 (from 1.9)
VMs built in https://github.com/containers/automation_images/pull/385
```release-note
None
```
> Bump VMs. ShellCheck is now built-in

- docs/source/markdown/podman-kube-play.1.md.in
- pkg/domain/infra/abi/play.go
- pkg/k8s.io/api/core/v1/types.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/volume.go
- test/system/700-play.bats
- test/system/README.md
Add the support for [Kubernetes volumes of type image](https://kubernetes.io/blog/2024/08/16/kubernetes-1-31-image-volume-source/). 
```release-note
kube play supports Kubernetes volumes of type image, introduced as an alpha feature in v1.31 
```
Resolves: https://github.com/containers/podman/issues/23775
> Add `kube play` support for volumes of type image 

- test/system/320-system-df.bats
...because it requires 100% control and knowledge of the
state of all images, containers, and volumes.
Use safename anyway, just in case we ever have a leak from here.
I'm finding safename sooooooo helpful when reading journal.
```release-note
None
```
> CI: mark 320-system-df *NOT* parallel safe

- test/system/500-networking.bats
- test/system/505-networking-pasta.bats
Add ci:parallel tags; move one non-parallel-safe test to
another networking-test file; and a few drive-by fixes
```release-note
None
```
> CI: make 505-pasta parallel safe

- test/system/710-kube.bats
Use safename. Add ci:parallel tags. Use a random port, not
hardcoded 9999. Do not remove pause image. And especially
do not "rm -a" anything.
```release-note
None
```
> CI: make 710-kube parallel-safe

- build_windows.md
- contrib/win-installer/podman-theme.wxl
- contrib/win-installer/podman-theme.xml
Fixes #22492
The last screenshot is when a previous version of podman is found, and we don't want the user to select the provider):
```release-note
The Windows installer has a new radio button to select the virtualization provider (WSLv2 or Hyper-V)
```
> Add radio buttons to select WSL or Hyper-V in windows setup.exe

- pkg/machine/e2e/start_test.go
- pkg/machine/shim/host.go
Not much can be done when multiple machines are started but a help message is definitely of help in some instances
Resolves: https://github.com/containers/podman/issues/23436
```release-note
Output of podman machine start now gives a suggestion if a machine is already running
```
> Add help message when starting multiple machines

- cmd/quadlet/main.go
There is no point in logging them, the directories not existing is fine and expected and logging these by default when useing -dryrun just causes confusion.
Fixes #23620
```release-note
Do not log ENOENT errors in quadlet when resolving the unit dirs
```
> quadlet: do not log ENOENT errors

- test/system/260-sdnotify.bats
Use safename. Add ci:parallel tags. Do not remove pause image
nor kube network.
```release-note
None
```
> CI: make 260-sdnotify parallel-safe

- pkg/bindings/images/build.go
- pkg/machine/e2e/basic_test.go
Fixes https://github.com/containers/buildah/issues/4749
```release-note
Windows paths passed as volumes `HOST-DIR` in the podman build command are converted into a valid path inside the machine VM.
```
> Convert windows paths in volume arg of the build command

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
> Quadlet - Split getUnitDirs to small functions

- pkg/specgen/namespaces.go
pasta doesn't switch to nobody when we already run in a userns so we can use it there. The unshare package checks the same condition and returns true even if uid 0 in this case so we can directly call this.
ref https://github.com/containers/podman/issues/17840#issuecomment-2343251014
```release-note
Allow the pasta network mode to be used when running as uid 0 but already ina userns (container). 
```
> pkg/specgen: allow pasta when running inside userns

- libpod/container_internal_common.go
- libpod/runtime_ctr.go
- test/system/030-run.bats
convert the owner UID and GID into the user namespace only when ":idmap" mount is used.
This changes the behaviour of :idmap with an empty volume.  Now the existing directory ownership is copied up as in the other case.
Closes: https://github.com/containers/podman/issues/23347
```release-note
Now copyup keeps the original directory ownership for the directory when ":idmap" is used and the volume is empty
```
> libpod: convert owner IDs only with :idmap

- test/e2e/events_test.go
podman-remote events are not flushed, so order is not guaranteed.
This results in CI flakes. Only on Debian, for reasons unknown.
Make the network-connection events test more lenient when remote.
Closes: #23634 (but does not actually fix it)
```release-note
None
```
> CI: e2e: workaround for events out-of-sequence flake

- cmd/podman/parse/net.go
- cmd/podman/parse/net_test.go
- docs/source/locale/ja/LC_MESSAGES/markdown.po
- docs/source/markdown/options/add-host.md
Hello, 
Fixes https://github.com/containers/podman/issues/23770
I didn't update any tests because I don't know which one I should update and how to update them without breaking them.
It would be nice if someone creates the tests for me or give me some explanation on where and how I can create a test case. 
```release-note
--add-host option now supports multiple hostnames
```
> Podman CLI --add-host with multiple host for a single IP

- libpod/container_inspect.go
- test/e2e/container_inspect_test.go
Secret mounted as an env variables are exposed by the `podman container inspect` command.
This change replaces the content of the env var by `*******`.
To reproduce this, follow the commands reported by the original issue:
```bash
printf 'secret value' | podman secret create mysecret -
podman container run --rm --secret mysecret,type=env -d alpine sleep 300
podman container inspect -l --format '{{ .Config.Env }}'
```
Fixes #23788
```release-note
Fixed secrets being exposed by `podman container inspect` when mounted as an env var
```
> Hide secrets from container inspect command

- test/system/012-manifest.bats
> CI: make 012-manifest parallel-safe

- cmd/podman/common/completion.go
- cmd/podman/manifest/remove.go
- docs/source/markdown/podman-manifest-remove.1.md
- docs/source/markdown/podman-manifest.1.md
* `podman manifest remove` doesn't accept references as descriptions of what to remove from a list or index; only use digests in the man page
* `podman manifest remove` only removes one thing at a time; correct the man page examples
```release-note
None
```
> podman-manifest-remove: update docs and help output

- pkg/api/handlers/compat/containers_top.go
- test/apiv2/20-containers.at
We were only splitting on tabs, not spaces, so we returned just a single line most of the time, not an array of the fields in the output of `ps`. Unfortunately, some of these fields are allowed to contain spaces themselves, which makes things complicated, but we got lucky in that Docker took the simplest possible solution and just assumed that only one field would contain spaces and it would always be the last one, which is easy enough to duplicate on our end.
Fixes #23981
```release-note
Fixed a bug where the output for the Compat Top API for Containers did not properly split the output into an array.
```
> Match output of Compat Top API to Docker

- .cirrus.yml
- Makefile
- contrib/cirrus/logformatter
- hack/bats
- test/system/000-TEMPLATE
- test/system/030-run.bats
- test/system/055-rm.bats
- test/system/060-mount.bats
- test/system/220-healthcheck.bats
- test/system/252-quadlet.bats
- test/system/500-networking.bats
- test/system/README.md
- test/system/helpers.bash
- test/system/helpers.registry.bash
- test/system/setup_suite.bash
Well, here goes. Let's try enabling parallel system tests. 
There's still a ton of work left to do, but I think we're ready enough. The remaining work is in #23275, and I will continue submitting piecemeal PRs over time. 
We're gonna see flakes. Sorry. The remaining flakes are really hard to track down. OTOH rerun time will be shorter.
Note to reviewers: the only way to handle this is by looking at individual commits.
```release-note
None
```
> CI: system tests: enable parallel tests

- .cirrus.yml
- test/e2e/run_test.go
- test/system/120-load.bats
...and remove a bunch of old skip()s for older debian
~Do not merge, because crun-1.17 seems broken (https://github.com/containers/crun/issues/1560)~ That bug is not new in 1.17.
```release-note
None
```
> New VMs: test crun 1.17

- cmd/podman/containers/container.go
- cmd/podman/generate/generate.go
- cmd/podman/images/load.go
- cmd/podman/networks/network.go
- cmd/podman/pods/pod.go
- cmd/podman/volumes/volume.go
- libpod/kube.go
- pkg/api/handlers/compat/images_build.go
- pkg/api/handlers/libpod/generate.go
- pkg/api/handlers/utils/images.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/namespaces.go
- pkg/specgen/pod_validate.go
- pkg/util/utils.go
> Remove containers/common/pkg/config from pkg/util

- .packit.yaml
manual backport of https://github.com/containers/podman/pull/23927
```release-note
None
```
> [skip-ci] v5.2 packit backports - sidetag enablement

- libpod/container_api.go
- test/e2e/wait_test.go
- test/system/035-logs.bats
As it turns on things are not so simple after all...
In podman-py it was reported[1] that waiting might hang, per our docs wait
on multiple conditions should exit once the first one is hit and not all
of them. However because the new wait logic never checked if the context
was cancelled the goroutine kept running until conmon exited and because
we used a waitgroup to wait for all of them to finish it blocked until
that happened.
First we can remove the waitgroup as we only need to wait for one of
them anyway via the channel. While this alone fixes the hang it would
still leak the other goroutine. As there is no way to cancel a goroutine
all the code must check for a cancelled context in the wait loop to no
leak.
Fixes https://github.com/containers/podman/commit/8a943311db5b686af231ddc026b7 …
> wait: fix handling of multiple conditions with exited

- pkg/specgen/generate/ports.go
- test/e2e/container_inspect_test.go
There is no reason to disallow exposed sctp ports at all. As root we can publish them find and as rootless it should error later anyway.
And for the case mentioned in the issue it doesn't make sense as the port is not even published thus it is just part of the metadata which is totally in all cases.
Fixes #23911
```release-note
Podman no longer errors out when trying to expose sctp ports or when they are part of the image config.
```
> allow exposed sctp ports

- test/system/090-events.bats
...or at least as much as possible. Some tests cannot
be run in parallel due to #23750: "--events-backend=file"
does not actually work the way a naïve user would intuit.
Stop/die events are asynchronous, and can be gathered
by *ANY OTHER* podman process running after it, and if
that process has the default events-backend=journal,
that's where the event will be logged. See #23987 for
further discussion.
```release-note
None
```
> CI: make 090-events parallel-safe

- test/system/000-TEMPLATE
- test/system/055-rm.bats
- test/system/252-quadlet.bats
- test/system/helpers.bash
Mostly to minimize flakes in parallel mode. And some documentation.
```release-note
None
```
> CI: system tests: various small cleanups

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/cgroups/memory_linux.go
- vendor/github.com/containers/common/version/version.go
- vendor/github.com/containers/image/v5/copy/copy.go
- vendor/github.com/containers/image/v5/copy/progress_bars.go
- vendor/github.com/containers/image/v5/directory/directory_dest.go
- vendor/github.com/containers/image/v5/directory/directory_src.go
- vendor/github.com/containers/image/v5/directory/directory_transport.go
- vendor/github.com/containers/image/v5/docker/body_reader.go
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go
- vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go
- vendor/github.com/containers/image/v5/docker/registries_d.go
- vendor/github.com/containers/image/v5/openshift/openshift_src.go
- vendor/github.com/containers/image/v5/ostree/ostree_dest.go
- vendor/github.com/containers/image/v5/ostree/ostree_src.go
- vendor/github.com/containers/image/v5/pkg/blobcache/blobcache.go
- vendor/github.com/containers/image/v5/pkg/blobcache/dest.go
- vendor/github.com/containers/image/v5/pkg/blobcache/src.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/github.com/containers/image/v5/storage/storage_image.go
- vendor/github.com/containers/image/v5/storage/storage_reference.go
- vendor/github.com/containers/image/v5/storage/storage_src.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/modules.txt
Addresses CVE-2024-3727 and Podman stats takes pagecache into account
Fixes: https://issues.redhat.com/browse/OCPBUGS-37008
https://issues.redhat.com/browse/OCPBUGS-37010
https://issues.redhat.com/browse/OCPBUGS-37011
Also addresses #1642 in the v4.4.1-rhel branch
Fixes: https://issues.redhat.com/browse/RHEL-16376
```release-note
None
```
> [v4.4.1-rhel] CVE-2024-3727 & stats

- test/system/252-quadlet.bats
Test was written to use / (root). This is not parallel-safe.
Fixes: #23909
```release-note
None
```
> CI: Quadlet rootfs test: use container image as rootfs

- go.mod
- go.sum
- libpod/networking_linux.go
- test/system/550-pause-process.bats
- vendor/github.com/containers/common/libimage/copier.go
- vendor/github.com/containers/common/libimage/import.go
- vendor/github.com/containers/common/libimage/manifest_list.go
- vendor/github.com/containers/common/libimage/manifests/manifests.go
- vendor/github.com/containers/common/libimage/pull.go
- vendor/github.com/containers/common/libimage/push.go
- vendor/github.com/containers/common/libimage/save.go
- vendor/github.com/containers/common/pkg/netns/netns_linux.go
- vendor/modules.txt
The netns dir has a special logic to bind mout itself and make itslef
shared. This code here didn't which lead to catastrophic bug during
netns unmounting as we were unable to unmount the netns as the mount got
duplicated and had the wrong parent mount. This caused us to loop forever
trying to remove the file.
Fixes https://issues.redhat.com/browse/RHEL-59620
Fixes https://github.com/containers/podman/issues/23685
```release-note
Fixed a bug that made it impossible to unmount our netns on cleanup which causes our commands to hang.
```
> libpod: setupNetNS() correctly mount netns

- docs/source/markdown/podman-build.1.md.in
> docs: remove usage of deprecated `--storage` in the doc of podman-build

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
- docs/source/markdown/podman-systemd.unit.5.md
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet now support symbolic links also inside the search path
```
Resolves: #23755
> Quadlet - add full support for Symlinks

- docs/source/markdown/podman-build.1.md.in
Fixes: 32c2cea0f9 ("Remove future tense from man pages")
```release-note
None
```
> docs: Fix missing negation

- docs/source/conf.py
- go.mod
- go.sum
- libpod/container_internal_common.go
- libpod/networking_linux.go
- libpod/runtime_ctr.go
- pkg/specgen/generate/ports.go
- pkg/specgen/namespaces.go
- test/e2e/container_inspect_test.go
- test/system/030-run.bats
- test/system/550-pause-process.bats
- vendor/github.com/containers/common/pkg/netns/netns_linux.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
```release-note
Fixed a bug that made it impossible to unmount our netns on cleanup which causes our commands to hang.
Podman no longer errors out when trying to expose sctp ports or when they are part of the image config.
Allow the pasta network mode to be used when running as uid 0 but already in a userns (container).
Now copyup keeps the original directory ownership for the directory when ":idmap" is used and the volume is empty
```
> [v5.2] Backports for v5.2

- test/system/505-networking-pasta.bats
I've had intermittent problems with the pasta DNS tests in podman.  Here are some fixes that address at least some of them.
/cc @sbrivio-rh @Luap99 
```release-note
None
```
> Fix several reliability problems with pasta DNS handling tests

- test/system/700-play.bats
(where possible. Not all tests are parallelizable).
And, refactor two complicated tests into one. This one
is hard to review, sorry.
```release-note
None
```
> CI: make 700-play parallel-safe

- test/system/610-format.bats
The format test flakes when quay is down, because we've
been doing 'podman search $IMAGE', which is a quay image.
Solution: check if local registry is running, and use it.
We don't need a real image.
```release-note
None
```
> CI: format test: use local registry if available

- go.mod
- go.sum
- libpod/networking_linux.go
- test/system/550-pause-process.bats
- vendor/github.com/containers/common/pkg/netns/netns_linux.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
The netns dir has a special logic to bind mout itself and make itslef
shared. This code here didn't which lead to catastrophic bug during
netns unmounting as we were unable to unmount the netns as the mount got
duplicated and had the wrong parent mount. This caused us to loop forever
trying to remove the file.
Fixes https://issues.redhat.com/browse/RHEL-59703 (backport)
```release-note
None
```
> [v5.2-rhel] Fix netns mounting with userns

- test/system/250-systemd.bats
Mostly just switch to safename. Rewrite setup() to guarantee
unique service file names, atomically created.
* IMPORTANT NOTE: enabling parallelization on these tests
triggers #24010 ("fragment file" flake), but only on my
f40 laptop. I have never seen the flake in Cirrus despite
many many runs in #23275. I am submitting this for review
and merging because even though _something_ is broken,
this breakage is unlikely to affect our CI.
```release-note
None
```
> CI: make systemd tests parallel-safe (*)

- test/system/252-quadlet.bats
> CI: skip the flaking quadlet test (temporary)

- .cirrus.yml
- .gitignore
- contrib/cirrus/runner.sh
- hack/podman_cleanup_tracer.bt
See commits, I just want to check if this even works. Hopefully this allows me to properly understand cleanup errors.
```release-note
None
```
> add epbf program to trace podman cleanup errors in CI

- troubleshooting.md
Modify the home dir path to make the troubleshooting tip more robust against mistakes.
`userdel` with force argument tries to remove home dir path "/" according to
* https://github.com/shadow-maint/shadow/issues/1050
(I haven't tried it myself)
```release-note
None
```
> troubleshooting: adjust home path in tip 44

- test/system/505-networking-pasta.bats
The various pasta port forwarding tests run a socat server inside a container, then connect to it from a socat client on the host.  Currently we have the server bind to the same specific address within the container as we connect to on the host.
That's not quite what we want.  For "tap" tests where the traffic goes over pasta's L2 link to the container it's fine, though unnecessary.  For "loopback" tests where traffic is forwarded by pasta at the L4 socket level, however, it's not quite right.  In this case the address used is either 127.0.0.1 or ::.  That's correct and as needed for the host side address we're connecting to.  However on the container side, this only works because of an odd and arguably undesirable behaviour of pasta: we use the fact that we have an L4 socket within the …
> test/system: For pasta port forwarding tests don't bind socat server

- test/system/150-login.bats
- test/system/550-pause-process.bats
- test/system/helpers.bash
- test/system/helpers.systemd.bash
Yield to reality: if $XDG_RUNTIME_DIR is unset, assume a
reasonable default (rootless only). This clears up a
common failure in Fedora gating tests, and will probably
prevent future time wasters.
```release-note
None
```
> System tests: set a default XDG_RUNTIME_DIR

- .packit.yaml
The go version there is only go 1.22.5 but we need go 1.22.6 as of https://github.com/containers/podman/pull/24054
It is not clear to me how to best monitor the repos there to see when they get the update. And then there is the fear that podman keeps updating faster then these envs which makes testing there immposible[1]
[1] https://github.com/containers/image/pull/2550#discussion_r1743588062
```release-note
None
```
> packit: disable Centos Stream/fedora ELN teasks

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
No
```release-note
None
```
Resolves: #24047
> Quadlet - make sure the order of the UnitsDir is deterministic

- test/system/271-tcp-cors-server.bats
Primary motivator: 'curl -v' format changes in f42
Drive-bys:
* 127.0.0.1, not localhost
* use wait_for_port, not sleep
* show curl commands and their output, to ease debugging failures
* better failure assertions
```release-note
None
```
> CORS system test: clean up

- pkg/api/handlers/libpod/kube.go
- pkg/api/handlers/libpod/kube_test.go
- pkg/api/server/register_kube.go
- test/apiv2/80-kube.at
Part of https://github.com/containers/podman/issues/14527
```release-note
Operation PlayKubeLibpodapi support Content-Type `application/x-tar`
```
Create a test directory with the following structure
```
.
└── example/
├── play.yaml
└── foobar/
└── Containerfile
```
```yaml
apiVersion: v1
kind: Pod
metadata:
name: demo-build-remote
spec:
containers:
- name: container
image: foobar
```
````dockerfile
FROM docker.io/library/alpine:latest
````
1. `make binaries`
Create a podman system service
3. `./bin/podman system service --time=0 tcp://localhost:8888`
Create a tar file `example.tar` with our example content
4. `cd ./example && tar cvf example.tar *`
```bash
$: curl --location 'http://localhost:8888/v5.0.0/libpod/kube/play' \
--header 'Content-Type: application/x-tar' \
--data …
```
> feat(libpod): support kube play tar content-type

- cmd/podman/machine/init.go
- cmd/podman/machine/os/manager.go
- cmd/podman/system/reset_machine.go
- pkg/machine/config.go
- pkg/machine/connection/connection.go
- pkg/machine/define/config.go
- pkg/machine/e2e/rm_test.go
- pkg/machine/machine_common.go
- pkg/machine/provider/platform.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/machine.go
Changes system connection removal so the following case now works as expected:
- Rootless podman machine 1 is initialized and running.
- Rootful podman machine 2 is initialized.
- Delete podman machine 1.
- The **rootful** system connection associated with podman machine 2 now becomes the default, not the rootless.
Fixes: #22577
```release-note
When a user has a rootless machine running and another rootful podman machine initialized, and the rootless machine is removed, the rootful system connection associated with the podman machine now becomes the default as expected.
```
> Handle default system connection transfer properly on machine removal

- libpod/container_inspect.go
- libpod/networking_common.go
- libpod/options.go
- libpod/util.go
- pkg/specgen/generate/namespaces.go
- test/e2e/run_networking_test.go
Previously, we didn't bother including exposed ports in the container config when creating a container with --net=host. Per Docker this isn't really correct; host-net containers are still considered to have exposed ports, even though that specific container can be guaranteed to never use them.
The change itself is quite simple. Introduce a simpler way to get exposed ports into the Libpod config (previously only possible via the overarching netns setup function) and use it when making a net=host container. Testing is similarly straightforward.
Fixes https://issues.redhat.com/browse/RHEL-60382
```release-note
Fixed a bug where Podman did not include exposed ports from containers created with `--net=host` in the output of `podman inspect`.
```
> Include exposed ports in inspect output when net=host

- docs/source/markdown/options/add-host.md
- docs/source/markdown/options/hostname.container.md
- docs/source/markdown/options/hostname.pod.md
- docs/source/markdown/options/name.container.md
- docs/source/markdown/options/no-hosts.md
Document the special *host-gateway* flag of the `--add-host` option introduced with #19152, mention the special `host.containers.internal` and `host.docker.internal` hostnames, and clarify the option's usage in general. Also update resp. cross-reference the related `--no-hosts`, `--hostname`, and `--name` options.
See #19152 and https://github.com/containers/podman/issues/22653#issuecomment-2368179986
```release-note
None
```
Cc: @Luap99
> [CI:DOCS] Update documentation of CLI options affecting `/etc/hosts`

- cmd/podman/root.go
- docs/source/markdown/podman.1.md
Fixes: #23711 
```release-note
None
```
> update docs for network-cmd-path

- docs/source/markdown/options/compression-format.md
A part of https://github.com/containers/common/issues/2117 .
```release-note
None
```
> Document that zstd:chunked is downgraded to zstd when encrypting

- rpm/podman.spec
As we started to default to nftables on f41[1,2] we no longer have to load legacy iptables modules.
[1] https://fedoraproject.org/wiki/Changes/NetavarkNftablesDefault
[2] https://github.com/containers/netavark/pull/1038
```release-note
None
```
> rpm: do not load iptables modules on f41+

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/ports.container
- test/e2e/quadlet/ports.kube
There is no reason to validate the args here, first podman may change the syntax so this is just duplication that may hurt us long term. It also added special handling of some options that just do not make sense, i.e. removing 0.0.0.0, podman should really be the only parser here. And more importantly this prevents variables from being used.
Fixes #24081
```release-note
quadlet: Allow variables to be used in PublishPort
```
> quadlet: allow variables in PublishPort

- libpod/container_internal_linux.go
- libpod/runtime.go
- libpod/shutdown/handler.go
- pkg/api/server/server.go
libpod: ensure we are not killed during netns creation
When we are killed during netns setup it will leak the netns path as it
was not commited in the db. This is rather common if you run systemctl
stop on a podman systemd unit. Of course we cannot protect against
SIGKILL but in systemd case we get SIGTERM and we really should not exit
in a critical section like this.
Fixes https://github.com/containers/podman/issues/24044
---
libpod: rework shutdown handler flow
Currently podman run -d can exit 0 if we send SIGTERM during startup
even though the contianer was never started. That just doesn't make any
sense is horribly confusing for a external job manager like systemd.
The original motivation was to exit 0 for the podman.service in commit …
> Fix netns leak on container creation and exit code 1 on SIGTERM.

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Update c/common to fix CVE-2024-9341
Fixes CVE-2024-9341
```release-note
Fixes CVE-2024-9341
```
> [v5.2] vendor: update c/common to v0.60.4

- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/container_inspect.go
- pkg/api/handlers/compat/containers.go
- test/e2e/container_inspect_test.go
A field we missed versus Docker. Matches the format of our existing Ports list in the NetworkConfig, but only includes exposed ports (and maps these to struct{}, as they never go to real ports on the host).
Fixes https://issues.redhat.com/browse/RHEL-60382
```release-note
Added a new field to the output of inspect for containers, `Config.ExposedPorts`, which includes all exposed ports from the container, improving our Docker compatibility.
```
> Add ExposedPorts to Inspect's ContainerConfig

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Fixes CVE-2024-9341
Fixes https://issues.redhat.com/browse/RHEL-60964
Fixes https://issues.redhat.com/browse/RHEL-60962
```release-note
None
```
> [4.9-rhel] vendor: update c/common to v0.57.7

- go.mod
- go.sum
- vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Update c/common to fix CVE-2024-9341
Fixes CVE-2024-9341
Fixes https://issues.redhat.com/browse/RHEL-60963
Fixes https://issues.redhat.com/browse/RHEL-60961
```release-note
Fixes CVE-2024-9341
```
> [v5.2-rhel] vendor: update c/common to v0.60.4

- go.mod
- libpod/container_inspect_linux.go
- test/e2e/run_privileged_test.go
github.com/moby/sys/capability is a fork of the (no longer maintained) github.com/syndtr/gocapability package.
For changes since the fork took place, see https://github.com/moby/sys/blob/main/capability/CHANGELOG.md
Related:
* https://github.com/containers/common/pull/2167
* https://github.com/containers/storage/pull/2103
* https://github.com/containers/buildah/pull/5754
* https://github.com/opencontainers/runtime-tools/pull/777
```release-note
none
```
> vendor: switch to moby/sys/capability

- Makefile
> Makefile - silence skipped tests when focusing on a file

- pkg/specgenutil/volumes.go
- test/e2e/run_volume_test.go
Similar to github.com/containers/buildah/pull/5761 but not security critical as Podman does not have an expectation that mounts are scoped (the ability to write a --mount option is already the ability to mount arbitrary content into the container so sneaking arbitrary options into the mount doesn't have security implications). Still, bad practice to let users inject anything into the mount command line so let's not do that.
```release-note
NONE
```
> Validate the bind-propagation option to `--mount`

- libpod/oci_conmon_common.go
- test/system/170-run-userns.bats
the kernel checks that both the uid and the gid are mapped inside the user namespace, not only the uid:
/**
* privileged_wrt_inode_uidgid - Do capabilities in the namespace work over the inode?
* @ns: The user namespace in question
* @idmap: idmap of the mount @inode was found from
* @inode: The inode in question *
* Return true if the inode uid and gid are within the namespace. */ bool privileged_wrt_inode_uidgid(struct user_namespace *ns,
struct mnt_idmap *idmap,
const struct inode *inode)
{
return vfsuid_has_mapping(ns, i_uid_into_vfsuid(idmap, inode)) &&
vfsgid_has_mapping(ns, i_gid_into_vfsgid(idmap, inode));
}
for this reason, improve the check for hasCurrentUserMapped to verify that the gid is also mapped, and if it is not, use an intermediate mount for the container rootfs. …
> libpod: hasCurrentUserMapped checks for gid too

- docs/source/markdown/options/add-host.md
- docs/source/markdown/options/no-hosts.md
Also mention the `no_hosts` and `base_hosts_file` configs of `containers.conf` in the docs of the `--add-hosts` and `--no-hosts` CLI options.
Follow-up to #24043 
Related: https://github.com/containers/common/pull/2184
Cc: @Luap99 (feel free to also ping @‎mheon and @‎edsantiago)
```release-note
None
```
> Mention `no_hosts` and `base_hosts_file` configs in CLI option docs

- libpod/container_inspect.go
- test/e2e/run_networking_test.go
Undoing some of my own work here from #24090 now that we have the ExposedPorts field implemented in inspect. I considered a revert of that patch, but it's still needed as without it we'd be including exposed ports when --net=container which is not correct.
Basically, exposed ports for a container should always go in the new ExposedPorts field we added. They sometimes go in the Ports field in NetworkSettings, but only when the container is not net=host and not net=container. We were always including exposed ports, which was not correct, but is an easy logical fix.
Also required is a test change to correct the expected behavior as we were testing for incorrect behavior.
Fixes https://issues.redhat.com/browse/RHEL-60382
```release-note
NONE
```
> Exposed ports are only included when not --net=host

- docs/source/locale/ja/LC_MESSAGES/markdown.po
- docs/source/markdown/podman-systemd.unit.5.md
Use the reserved domain name example.com in the examples. For details, see RFC 2606
https://datatracker.ietf.org/doc/html/rfc2606#section-3
Modify PublishPort examples to make them reflect more common scenarios.
Fixes: https://github.com/containers/podman/issues/23954
```release-note
None
```
> podman-systemd.unit.5: adjust example options

- docs/source/locale/ja/LC_MESSAGES/markdown.po
- docs/source/markdown/podman-systemd.unit.5.md
- docs/tutorials/basic_networking.md
The option --network is the more official option as it is listed in
podman run --help
podman kube play --help
```release-note
None
```
> docs: prefer --network to --net

- Makefile
- cmd/podman/system/service_abi.go
- pkg/domain/infra/abi/system.go
- test/e2e/systemd_activate_test.go
When we are activated by systemd the code assumed that we had a valid URL
which was not the case so it failed to parse the URL which causes the
info call to fail all the time.
This fixes two problems first add the schema to the systemd activated
listener URL so it can be parsed correctly but second simply do not
parse it as url as all we care about in the info call is if it is unix
and the file path exists.
Fixes #24152
```release-note
Fixed a problem that caused the info API endpoint to fail when running the podman system service on systemd activated tcp socket. 
```
> server: fix url parsing in info

- RELEASE_NOTES.md
- go.mod
- go.sum
- pkg/specgenutil/volumes.go
- test/e2e/run_volume_test.go
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/internal/volumes/volumes.go
- vendor/modules.txt
- version/rawversion/version.go
Addresses our recent CVEs in Buildah and Common.
```release-note
NONE
```
> Bump to v5.2.4

- contrib/pkginstaller/Makefile
- pkg/machine/e2e/basic_test.go
Bump the bundled krunkit version from 0.1.2 to 0.1.3.
Fixes: #23296
```release-note
Update krunkit in the macos installer to 0.1.3
```
> Bump bundled krunkit to 0.1.3

- libpod/runtime.go
- pkg/api/handlers/utils/containers.go
- pkg/domain/infra/tunnel/containers.go
- pkg/domain/infra/tunnel/events.go
podman-remote run: improve how we get the exit code
Call the wait endpoint right away when a container is started and not
only when attach is done, this allows us for wait to work when the
container has been removed otherwise (i.e. podman-remote run --rm). In
that case it was possible that wait failed and we then fall back to
reading events. However based on some reports there seems to be the
chance that the event readin is not working for them either and returns
a bad error "Cannot get exit code: <nil>" which does not help anybody.
libpod API: make wait endpoint better against rm races
In the common scenario of podman-remote run --rm the API is required to
attach + start + wait to get exit code. This has the problem that the
wait call races against the container removal from the cleanup …
> Improve podman-remote run --rm exit code handling

- test/system/252-quadlet.bats
This command sequence causes SizeRootFs to change on foo:
podman tag foo newimagename
podman save ... newimagename
podman load ...
Solution: get foo completely out of the picture. Use an
airgapped image: new image, new digest, new everything.
Fixes: #23756
```release-note
None
```
> CI: quadlet system tests: use airgapped testimage

- .cirrus.yml
- test/e2e/checkpoint_test.go
- test/e2e/containers_conf_test.go
- test/system/030-run.bats
Images from https://github.com/containers/automation_images/pull/387
```release-note
None
```
> cirrus: update CI images

- pkg/machine/e2e/api_test.go
- pkg/machine/e2e/inspect_test.go
- pkg/machine/machine_windows.go
- pkg/machine/shim/networking_windows.go
- pkg/machine/vmconfigs/machine.go
- pkg/machine/vmconfigs/machine_unix.go
- pkg/machine/vmconfigs/machine_windows.go
- pkg/machine/wsl/stubber.go
Fixes #23408
gvproxy and win-sshproxy have capabilities to serve this type of enpoint. This change only adds one additional API enpoint publishing by appending proxy command lines.
Originally developed within https://github.com/containers/podman/issues/13006 but could be generalized to any VM using `gvproxy` or `win-sshproxy`.  This has been verified to work for Hyper-V and WSL machines.
Example how it looks for WSL machine.
commands
* podman machine list (to show what kind of machine it is)
* podman machine inspect (to demo published endpoint in info)
* where curl (to verify it will use Windows one)
* curl to call the enpoint
```
C:\qcw-utils\shells>podman machine list
NAME                     VM TYPE     CREATED         LAST UP            CPUS        MEMORY      DISK SIZE …
```
> Implement publishing API UNIX socket on Windows platforms

- contrib/cirrus/setup_environment.sh
This reverts commit 43f6173cc6050cd07348d8e0532a27ec0f24a774.
The netavark version with nftables default is in f41 and rawhide already so this is no longer needed. While we do not yet test f41 in CI we have rawhide which is good enough until we update.
```release-note
None
```
> Revert "CI: test nftables driver on fedora"

- .packit.yaml
We now have golang 1.23.1 in centos stream 10.
This reverts commit f47abd8e1e9f46e43acf1cd10e3ee7521bf32b31.
```release-note
None
```
> [skip-ci] Packit: re-enable CentOS Stream 10/Fedora ELN tasks

- pkg/machine/apple/apple.go
Recently was trying to start podman machine with krunkit and got:
Error: krunkit exited unexpectedly with exit code 1
which isn't very descriptive. Although this doesn't solve the issue, it increases the debugability of this error.
> Make error messages more descriptive

- .cirrus.yml
- Makefile
- contrib/cirrus/postbuild.sh
- contrib/cirrus/runner.sh
- contrib/cirrus/win-installer-main.ps1
- contrib/cirrus/win-podman-machine-test.ps1
Builds now take over 10 mins, given golang compilation is parallelized by default we can give more cores to speed it up.
```release-note
None
```
> cirrus: use fastvm for builds

- cmd/podman/containers/run.go
- libpod/container.go
- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/annotations.go
- libpod/define/container_inspect.go
- libpod/oci_conmon_common.go
- pkg/api/handlers/compat/exec.go
- pkg/domain/infra/abi/containers.go
- pkg/specgen/generate/oci_linux.go
- pkg/specgen/specgen.go
- pkg/specgenutil/util.go
- test/system/030-run.bats
This started off as an attempt to make `podman stop` on a container started with `--rm` actually remove the container, instead of just cleaning it up and waiting for the cleanup process to finish the removal.
In the process, I realized that `podman run --rmi` was rather broken. It was only done as part of the Podman CLI, not the cleanup process (meaning it only worked with attached containers) and the way it was wired meant that I was fairly confident that it wouldn't work if I did a `podman stop` on an attached container run with `--rmi`. I rewired it to use the same mechanism that `podman run --rm` uses, so it should be a lot more durable now, and I also wired it into `podman inspect` so you can tell that a container will remove its image.
Tests have been added for the changes to …
> [v5.2-rhel] Fix `podman stop` and `podman run --rmi`

- README.md
- pkg/domain/infra/abi/containers.go
mapMutex is initialized in the ContainerRm function and cannot be released from outside,
thus unlock mutex before returning from function.
```release-note
None
```
> Unlock mutex before returning from function

- test/e2e/run_signal_test.go
By default golang programs exit 2 on special exit signals that can be cought and produce a stack trace. However this is behavior that can be modfied via GOTRACEBACK=crash[1], in that case it does not exit(2) but rather sends itself SIGABRT to the parent sees the signal exit and out test sees that es exit code 134, 128 + 6 (SIGABRT), like most shells do.
As it turns out GOTRACEBACK=crash is the default mode on all fedora and RHEL rpm builds as they patch the build with a special "rpm_crashtraceback" go build tag.
While that change is old and existing for a very long time it was never caught until commit 5e240ab1f5, which switched the old ExitWithError() check that accepted anything > 0, to just accept 2. And as CI only test upstream builds that are build without rpm_crashtraceback we did …
> test/e2e: fix default signal exit code test

- docs/source/markdown/podman-machine-init.1.md.in
- docs/source/markdown/podman-machine-set.1.md.in
- docs/source/markdown/podman-machine.1.md
```release-note
containers.conf is now mentioned in podman machine man pages.
```
> Mention containers.conf settings for podman machine commands

- cmd/podman/images/scp.go
- pkg/api/handlers/libpod/images.go
- pkg/domain/entities/engine_image.go
- pkg/domain/entities/images.go
- pkg/domain/entities/scp.go
- pkg/domain/infra/abi/images.go
- pkg/domain/infra/tunnel/images.go
- pkg/domain/utils/scp.go
- pkg/domain/utils/scp_test.go
- pkg/domain/utils/utils_test.go
Prior to this commit, many scp functions existed without option structs, which would make extending functionality (adding new options) impossible without breaking changes, or without adding redundant wrapper functions.
This commit adds in new option types for various scp related functions, and changes those functions' signatures to use the new options.
This commit also modifies the `ImageEngine.Scp()` function's interface to use the new opts.
The commit also renames the existing `ImageScpOptions` entity type to `ScpTransferImageOptions`. This is because the previous `ImageScpOptions` was inaccurate, as it is not the actual options for `ImageEngine.Scp()`. `ImageEngine.Scp()` should instead receive `ImageScpOptions`.
This commit should not change any behavior, however it will break the …
> scp: add option types

- test/system/090-events.bats
- test/system/252-quadlet.bats
(Second try). Use an airgapped image in the inspect-data tests.
Fixes: #23756
```release-note
None
```
> CI: fix changing-rootFsSize flake

- pkg/machine/hyperv/stubber.go
This PR concerns a small edge case when using podman on windows under Hyper V with a poorly named user profile.
When the user does not have control over the profile name, they will be unable to init a new podman machine.
For some user profile name `SomeUser(SomeIdentifier)`, and the target machine path.
```
C:\Users\SomeUser(SomeIdentifier)\.local\share\containers\podman\machine\hyperv\podman-machine-default-amd64.vhdx
```
Podman creates this machine, however, execution will fail when invoking a `powershell` command to resize the disk. `powershell` interprets the contents contained in brackets (in this case `(SomeIdentifier)`) as a grouping expression, attempts to execute it:
```
time="2024-10-16T11:51:17+11:00" level=debug msg="[powershell -command Resize-VHD …
```
> Added escaping to invoked powershell command for hyperv stubber.

- test/system/helpers.bash
The current mypod hack breaks down when running individual tests:
$ hack/bats 010   <<< barfs because it does not want pause-image!
Reason: Bats does not provide any official way to tell if tests
are being run in parallel.
Workaround: use an undocumented way.
```release-note
None
```
> System tests: safer pause-image creation

- CONTRIBUTING.md
The doc has been reorganized and reordered. New sections have been added as necessary to cover things not covered by the old guide. Some sections were expanded (e.g. detailing differences between E2E and System tests). Some sections that we did not actually follow were removed.
Fixes https://issues.redhat.com/browse/RUN-2281
```release-note
NONE
```
> Thorough overhaul of CONTRIBUTING doc.

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet_test.go
This is simply wrong, as of commit https://github.com/containers/podman/commit/de63ad70442585790d34693169558fc6e897b3fd --userns=keep-id is also
allowed as root.
Also enable quadlet test to run as root/rootless 
```release-note
None
```
> quadlet: do not reject RemapUsers=keep-id as root

- test/e2e/checkpoint_test.go
Two flakes seen in the last three months. One of them was in
August, so it's not related to ongoing criu-4.0 problems.
Suspected cause: race waiting for "podman run --rm" container
to transition from stopped to removed.
Solution: allow a 5-second grace period, retrying every second.
Also: add explanations to the Expect()s, remove unnecessary
code, and tighten up the CID check.
* fedora-39 : int podman fedora-39 root container boltdb
* PR #23706
* [08-22-2024 07:26](https://api.cirrus-ci.com/v1/artifact/task/4615576243404800/html/int-podman-fedora-39-root-container-boltdb.log.html#t--Podman-checkpoint-podman-checkpoint-and-restore-container-with-root-file-system-changes-using-ignore-rootfs-during-restore--1)
* fedora-40 : int remote fedora-40 root host boltdb [remote]
* PR #24238
* [10-16 …
> CI: e2e: fix checkpoint flake

- test/system/330-corrupt-images.bats
With https://github.com/containers/storage/pull/2118 and https://github.com/containers/image/pull/2589 , the `convert_images` (i.e. “disallow non-partial pulls”) option fails with VFS.
The 330-corrupt-images tests were temporarily switching to VFS, possibly within a composefs test run with `convert_images` set, without disabling it. That is going to fail after we update c/image and c/storage; update the tests for the changed behavior.
```release-note
None
```
> Update 330-corrupt-images.bats for composefs behavior change

- pkg/checkpoint/crutils/checkpoint_restore_utils.go
`CRRuntimeSupportsPodCheckpointRestore()` is used to check if the current container runtime (e.g., runc or crun) can restore a container into an existing Pod. It does this by processing output message to check if the `--lsm-mount-context` option is supported.  This option was [recently added to crun](https://github.com/containers/crun/pull/1578), however, crun and runc have slightly different output messages:
```
$ crun restore --lsm-mount-contextt
restore: option '--lsm-mount-context' requires an argument
Try `restore --help' or `restore --usage' for more information.
```
```
$ runc restore --lsm-mount-context
ERRO[0000] flag needs an argument: -lsm-mount-context
```
This pull request updates the `CRRuntimeSupportsPodCheckpointRestore()` function to support both runtimes.
> Enable pod restore with crun

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/internal/volumes/volumes.go
- vendor/modules.txt
Bump Buildah to v1.33.10.  This will address
CVE-2024-9675, CVE-2024-9407
Fixes: https://issues.redhat.com/browse/RHEL-61154, https://issues.redhat.com/browse/RHEL-61151,
https://issues.redhat.com/browse/OCPBUGS-42896,
https://issues.redhat.com/browse/RHEL-61837,
https://issues.redhat.com/browse/RHEL-61850
```release-note
None
```
> [v4.9-rhel] Bump Buildah 1.33.10, CVE-2024-9675

- pkg/api/handlers/utils/containers.go
- test/apiv2/26-containersWait.at
The special handling to return the exit code after the container has been removed should only be done if there are no special conditions requested. If a user asked for running or nay other state returning the exit code immediately with a success response is just wrong. We only want to allow that so the remote client can fetch the exit code without races.
Fixes b3829a2932 ("libpod API: make wait endpoint better against rm races")
```release-note
None
```
> libpod API: only return exit code without conditions

- test/system/030-run.bats
when the current soft limit is higher than the new value, ulimit fails to set the hard limit as (tested on Rawhide):
[root@rawhide ~]# ulimit -n -H 1048575
-bash: ulimit: open files: cannot modify limit: Invalid argument
to avoid the problem, set also the soft limit:
[root@rawhide ~]# ulimit -n -H
12345678
[root@rawhide ~]# ulimit -n -H 1048575
-bash: ulimit: open files: cannot modify limit: Invalid argument [root@rawhide ~]# ulimit -n -SH 1048575
[root@rawhide ~]# ulimit -n -H
1048575
commit 71d5ee0e04eb61802b7c59166d88eac19c563ff7 introduced the issue.
```release-note
None
```
> test: set soft ulimit

- test/system/010-images.bats
- test/system/120-load.bats
- test/system/150-login.bats
- test/system/helpers.bash
- Compare image configs, not IDs, when checking image identity from different way of pulling them
- Try to make the additional image store test a bit more robust
- Remove an image identity assumption from the “load by URL” test.
Working on test failures as discussed in https://github.com/containers/storage/pull/2130 .
<s>At this point absolutely untested, and</s> I don’t really know what I’m doing.
Cc: @edsantiago — perhaps read this only later after this is at least minimally shown to be working.
```release-note
None
```
> Update system tests to handle zstd:chunked images

- test/system/505-networking-pasta.bats
As an internal consistency check, the pasta tests check for duplicated test cases by grepping a log file for a parsed test id.  However it uses grep -F for the purpose which will not perform an exact match, but a substring match.  There are some tests which generate an id which is a substring of the id for other tests, so when test order is randomised, this can cause a spurious failure.  This can happen in practice when running the test in parallel with very high concurrency (e.g. -j 100).
Fix this by adding the -x option to grep, which only checks for full line exact matches.
Fixes: #24342 
```release-note
None
```
> test/system: Fix spurious "duplicate tests" failures in pasta tests

- cmd/podman/containers/ps.go
- cmd/podman/containers/ps_test.go
- test/e2e/run_networking_test.go
This fixes two problems, first if a port is published and exposed it
should not be shown twice. It is enough to show the published one.
Second, if there is a huge range the ports were no grouped causing the
output to be unreadable basically. Now we group exposed ports like we do
with the normal published ports.
Fixes #23317
```release-note
Exposed ports in the output of podman ps are now correctly group and not duplicated when they are already published,
```
> ps: fix display of exposed ports

- libpod/container_inspect.go
- libpod/define/container_inspect.go
- test/system/220-healthcheck.bats
This PR adds the startup HealtCheck configuration to the output of the `podman inspect` command.
For RHEL-60561 testing purposes.
Fixes: https://issues.redhat.com/browse/RHEL-60561
```release-note
The `podman inspect` command now includes startup HealthCheck configuration.
```
> Show Startup HealthCheck configuration with `podman inspect`

- test/system/500-networking.bats
The recent fedora kernel 6.11.4 has a problem with ipv6 networks [1]. This is not a podman bug at all but rather a kernel regression. I can reproduce the issue easily by running this test.
Given many users were hit by this add it to the distro level gating which runs in the fedora openQA framework and then we should catch a bad kernel like this hopefully in the future and prevent it from going into stable.
[1] https://github.com/containers/podman/issues/24374
```release-note
None
```
> test/system: add podman network reload test to distro gating

- test/system/450-interactive.bats
This has been running reliably for weeks in #23275
```release-note
None
```
> CI: parallelize 450-interactive system tests

- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/container_inspect.go
- libpod/networking_common.go
- libpod/options.go
- libpod/util.go
- pkg/api/handlers/compat/containers.go
- pkg/specgen/generate/namespaces.go
- test/e2e/container_inspect_test.go
- test/e2e/run_networking_test.go
This fixes an exposed ports issue in RHEL 5.2-rhel for RHEL 9.5.
FIxes: https://issues.redhat.com/browse/RHEL-62566
This includes the fixes from the following PRs:
First PR: #24090
Second PR: #24110
Third PR: #24164
With an additional tweak from @Luap99 in https://github.com/containers/podman/pull/24333/commits/0889c74497b80a5205d35965170afd617ebb1590 
regarding the looping in libpod/container_inspect.go.
These changes are needed in the 5.2-rhel branch to ensure a successful
upgrades as the same patches have been used for the following issues
in the Podman v4.9-rhel branch for these issues:
Fixes: https://issues.redhat.com/browse/ACCELFIX-299
Fixes: https://issues.redhat.com/browse/ACCELFIX-300
```release-note
None
```
> [v5.2-rhel] Fix exposed ports

- libpod/container_inspect.go
- libpod/container_validate.go
- libpod/define/container_inspect.go
- libpod/networking_common.go
- libpod/options.go
- libpod/util.go
- pkg/api/handlers/compat/containers.go
- pkg/specgen/generate/namespaces.go
- test/e2e/container_inspect_test.go
- test/e2e/run_networking_test.go
This fixes an exposed ports issue in RHEL 4.9-rhel for RHEL 8.10 and 9.4.
This includes the fixes from the following PRs:
First PR:      https://github.com/containers/podman/pull/24090
Second PR: https://github.com/containers/podman/pull/24110
Third PR:    https://github.com/containers/podman/pull/24164/ 
Fixes: https://issues.redhat.com/browse/ACCELFIX-299
Fixes: https://issues.redhat.com/browse/ACCELFIX-300
```release-note
None
```
> [v4.9-rhel] Fix exposed ports

- docs/tutorials/rootless_tutorial.md
- rework the slirp4netns section into a general 'Networking configuration' one
- integrate pasta as the new default tool for rootless networking since v5.0
- touch upon the user-facing differences between the two available backends and provide links to further documentation, including how to choose between one and the other and how to install them
Fixes: #24393
```release-note
None
```
> fix(docs): Integrate pasta in rootless tutorial

- contrib/cirrus/logformatter
I had a few cases where this is super handy in CI and if I can access the link without one extra click it safes me some time and hopefully makes it more discoverable for other to see how useful it can be sometimes.
```release-note
None
```
> logformatter: add cleanup tracer log link

- docs/source/markdown/podman-machine-init.1.md.in
In coreos /mnt is a symlink to /vat/mnt and systemd does not like do use the symlink for some reason. Simply fix the example to use /Users which now works as we always create the directories even on /.
Fixes #24281
```release-note
None
```
> docs: fix broken example

- .readthedocs.yaml
- docs/source/Reference.rst
Make our docs available in extra formats to download, ref
https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
Also add the missing swagger links for the other branches.
Fixes #24354
```release-note
None
```
> readthedocs: build extra formats

- hack/podman_cleanup_tracer.bt
- test/system/600-completion.bats
Debug for #23913, I though if we have no idea which process is nuking the volume then we need to figure this out. As there is no reproducer we can (ab)use the cleanup tracer. Simply trace all unlink syscalls to see which process deletes our special named volume. Given the volume name is used as path on the fs and is deleted on volume rm we should know exactly which process deleted it the next time hopefully.
```release-note
None
```
> Instrument cleanup tracer to log weird volume removal flake

- libpod/container.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
- libpod/networking_common.go
- libpod/oci_conmon_common.go
- libpod/oci_util.go
- test/system/500-networking.bats
We bind ports to ensure there are no conflicts and we leak them into conmon to keep them open. However we bound the ports after the network was set up so it was possible for a second network setup to overwrite the firewall configs of a previous container as it failed only later when binding the port. As such we must ensure we bind before the network is set up.
This is not so simple because we still have to take care of PostConfigureNetNS bool in which case the network set up happens after we launch conmon. Thus we end up with two different conditions.
Also it is possible that we "leak" the ports that are set on the container until the garbage collector will close them. This is not perfect but the alternative is adding special error handling on each function exit after prepare until we …
> [v4.9-rhel] libpod: bind ports before network setup

- libpod/container_api.go
When running `podman kube play --wait pod.yaml` the podman process invoked on the commandline will use 100% of a single CPU waiting for the pod to exit.
This can be reproduced with the following file and then opening another terminal and observing the CPU load of the process.
```yaml
apiVersion: v1
kind: Pod
metadata:
name: "high-cpu-load"
namespace: default
labels:
app: "high-cpu-load"
spec:
containers:
- name: high-cpu-load
image: docker.io/library/debian:bookworm-slim
command: ["bash"]
args: ["-c", "handler() { exit 0; } ; trap handler TERM; sleep infinity& wait"]
restartPolicy: Never
```
This is fixed by adding a proper `Interval` value to the options given to `ContainerWait`. Previously the default value of `time.Duration` was used which is 0 thus creating a busy-wait.
I have set it …
> stop podman kube play --wait from using 100% CPU

- cmd/podman/common/create.go
- cmd/podman/containers/exec.go
- cmd/podman/containers/start.go
- docs/source/markdown/options/interactive.md
Clarifies the behavior of --interactive in both attached and unattached scenarios.
Adds a caveat and explanation for --interactive being hungry as described in https://github.com/containers/podman/issues/24370.
Fixes #24370
```release-note
Clarified the --interactive flag in the documentation
```
> doc: explain --interactive in more detail

- Makefile
In the user session there is no boot-complete.target so the Requires= fails. We do not need it and I am not sure if we need it for the root unit either but I deicded to keep it there to not change anything and for the user session we patch it out.
I patched this in the Makefile, while we could try to define two different source files for that it would make the Makefile logic even more complicated. In particular as this file is a .in we would need to add it to PODMAN_GENERATED_UNIT_FILES and then somehow fix the loop. To much work IMO so the sed trick to patch the user file is simpler.
Fixes #23790
```release-note
podman-clean-transient.service can now be used in the user session correctly (only needed when podman is run with --transient-store)
```
> make podman-clean-transient.service work as user

- Makefile
- contrib/cirrus/postbuild.sh
- go.mod
- test/tools/Makefile
- test/tools/go.mod
> go.mod vendor: ensure we never have the toolchain directive set

- test/system/050-stop.bats
Just bump up a timeout when running parallel, because of high load.
```release-note
None
```
> CI: systests: workaround for parallel podman-stop flake

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.build
- test/e2e/quadlet/ipv6.network
- test/e2e/quadlet/network.build
- test/e2e/quadlet/uid.volume
- test/e2e/quadlet/volume.build
Fixes: https://github.com/containers/podman/issues/24322
```release-note
Service section of quadlets now take precedence over built in defaults.
Quadlet build units no longer use RemainAfterExit=yes by default.
```
> Honor users requests in quadlet files

- libpod/events/journal_linux.go
This is not needed and was added by during debugging but it turned out to be something else. We should not lock the thread unless needed because this just raises question why it is here otherwise. Also the lock would not do much as we spawn a goroutine below anyway so it runs on another thread no matter what.
From the review comment by Miloslav but it was merged before I had the chance to fix it:
https://github.com/containers/podman/pull/24406#discussion_r1828102666
```release-note
None
```
> libpod: journald do not lock thread

- pkg/api/handlers/compat/volumes.go
- pkg/api/handlers/libpod/volumes.go
- pkg/domain/infra/abi/volumes.go
If volume ls was called while another volume was removed at the right time it could have failed with "no such volume" as we did not ignore such error during listing. As we list things and this no longer exists the correct thing is to ignore the error and continue like we do with containers, pods, etc...
This was pretty easy to reproduce with these two commands running in different terminals:
```
while :; do bin/podman volume create test && bin/podman volume rm test || break; done
while :; do bin/podman volume ls || break ; done
```
I have a slight feeling that this might solve #23913 but I am not to sure there so I am not adding a Fixes here.
```release-note
Fixed a race condition that caused podman volume ls to fail when another volume was removed at the same time.
```
> volume ls: fix race that caused it to fail

- libpod/events.go
- libpod/events/events.go
- pkg/domain/infra/abi/network.go
- test/e2e/events_test.go
Fixes :  #24032
Yes
```release-note
Podman events now support logging for network creation and removal events.
```
> Fix: To print create and remove network in podman events

- .cirrus.yml
- contrib/cirrus/setup_environment.sh
Built in https://github.com/containers/automation_images/pull/392
```release-note
None
```
> CI VMs: bump to f41

- Makefile
- contrib/pkginstaller/Makefile
- pkg/machine/e2e/init_windows_test.go
- pkg/machine/wsl/usermodenet.go
- winmake.ps1
This fixes https://github.com/containers/podman/issues/20327. 
This change will pass `-1` to the `-ssh-port` flag of `gvproxy` to disable port forwarding on wsl which will prevent port conflict with crc.
No
```release-note
None
```
> Update gvproxy to v0.8.0 and disable ssh port forwarding on wsl

- pkg/api/handlers/libpod/images.go
The close is moved in the body of the error condition.
Found by Linux Verification Center (linuxtesting.org) with SVACE.
```release-note
None
```
> api: Move close function in condition body

- .pre-commit-config.yaml
Git on Windows clones the symlink `test/python/requirements.txt` as a regular file. That's not a big deal except that `pre-commit`, executed by `winmake.ps1 lint`, complains because there is no new line at end of the file.
To fix `winmake.ps1 lint` we exclude the symlink in `pre-commit` hook `end-of-file-fixer` configuration.
```release-note
None
```
> Excluse symlink from pre-commit end-of-file-fixer

- test/system/700-play.bats
Up to now this test has been run using:
PODMAN_TIMEOUT=2 run_podman kube play ...
...and this gives podman time to start the pod before getting
the signal.
When run in parallel, under heavy load, the above command seems
to time out before podman has gotten its act together. Weird
things happen, like weird exit status and (most crucially)
zombie containers.
Solution: wait for container to actually start before we kill it.
```release-note
None
```
> kube SIGINT system test: fix race in timeout handling

- .pre-commit-config.yaml
- test/e2e/system_connection_test.go
- test/system/800-config.bats
⚠️  This PR is a draft as it uses my `containers/common` fork (until https://github.com/containers/common/pull/2212 get merged)
The changes included:
- Updates `containers/common` to include containers/common#2212
- Update `codespell` so that the new tests can use `AfterAll(func() { // codespell:ignore afterall`
- Introduce new e2e tests that add a new SSH connection with different `known_hosts` files
```shell
❯ ./test/tools/build/ginkgo -vv  --tags "systemd libsubid exclude_graphdriver_devicemapper seccomp  remote" -timeout=90m --flake-attempts 0 \
--trace  \
-p \
--focus "sshd and API services required" --silence-skips \
--focus-file "system_connection_test.go" --silence-skips test/e2e/.
Running Suite: Libpod Suite - /home/mariolet/github/podman/test/e2e …
```
> New `system connection add` test

- .cirrus.yml
- contrib/cirrus/setup_environment.sh
- **Yet another bump, f41 with fixed kernel**
- **Reapply "cirrus: test only on f40/rawhide"**
- **Revert "Reapply "CI: test nftables driver on fedora""**
```release-note
None
```
> Yet another bump, to fixed f41 kernel

- hack/buildah-vendor-treadmill
- test/buildah-bud/apply-podman-deltas
- test/buildah-bud/buildah-tests.diff
* treadmill script: handle an obscure corner case
wherein the script would bail because it thought
there were no buildah-vendor changes.
* two new test skips
* update the diffs; line-number changes due to buildah
PRs touching helpers.bash
```release-note
None
```
> Buildah treadmill tweaks

- test/system/helpers.systemd.bash
(Import from #23275, where it has been working for weeks. More importantly, I tested it on 1mt)
Previous version was badly broken: it relied on 'make' rebuilding a file under cwd, which is a no-no; and, in the case where we don't have a source directory, just blindly hoped that there'd be a system-installed .service file with the correct path to podman.
Solution:
. if running in source directory, run sed directly into
destination service file in $UNIT_DIR. This is ugly
duplication of a line in Makefile.
. if NOT running in a source directory, check $PODMAN:
. if it's /usr/bin/podman, continue
. otherwise skip, because we don't know what we're testing
```release-note
None
```
> system tests: safer install_kube_template()

- libpod/container.go
This PR refactors the `LinuxNS` type definition and its `String()` method for improved readability and maintainability.
- **Removed redundant** `iota` assignments for each constant. Using `iota` automatically increments the value, so there's no need to repeat `LinuxNS = iota`.
- **Simplified the `String()` method** by using an array instead of a switch-case statement, reducing repetitive code and making it easier to maintain. Besides, improved the time complexity from O(n) to O(1)
- **Improved readability** by using a centralized array for namespace name mapping.
```release-note
None
```
> refactor: simplify LinuxNS type definition and String method

- libpod/container_internal_common.go
commit 5ebba75dbd4462da47283b3f018804b7361d52bf implemented this behaviour for rootless users, but the same limitation exists for any user in a user namespace.  Change the check to use the clamp to the current values anytime podman runs in a user namespace.
Closes: https://github.com/containers/podman/issues/24508
```release-note
None
```
> spec: clamp rlimits in a userns

- libpod/container.go
- pkg/specgenutil/volumes.go
- test/e2e/run_volume_test.go
All the backend work was done a while back for image volumes, so this is effectively just plumbing the option in for volumes in the parser logic. It's a little uglier than I'd like because our volume mount parser produces an OCI Spec mount struct, which doesn't have a field for subpath, so we have to pass through the options array and parse it back out after, which is a little gross. But not gross enough to rewrite that parsing logic.
Fixes #20661
```release-note
The `--mount type=volume` option to `podman run`, `podman create`, and `podman volume create` now supports a new option, `subpath=`, to make only a subset of the volume visible in the container ([#20661](https://github.com/containers/podman/issues/20661)). 
```
> Add subpath support to volumes in `--mount` option

- docs/source/markdown/options/network.md
- go.mod
- go.sum
- pkg/specgen/namespaces.go
- pkg/specgen/namespaces_test.go
- test/e2e/network_test.go
- vendor/github.com/containers/common/libnetwork/types/network.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
This way has a huge disadvantage: The user will not see an error when he uses a non-existent option. Another disadvantage is, that if we add more options within podman, they might collide with the names chosen by plugins. Such issues might be hard to debug.
The advantage is that the usage is very nice:
`--network bridge:opt1=val1,opt2=val2`.
Alternatively, we could put this behind `opt=`, which is harder to use, but would solve all issues above:
`--network bridge:opt=opt1=val1,opt=opt2=val2`
```release-note
A new `host_interface_name` option was added for bridge networks to specify the host side veth name, requires netavark >= 1.14.
```
Depends on: https://github.com/containers/common/pull/2245
Required by: https://github.com/containers/netavark/pull/1125
> add support for driver-specific options during container creation

- pkg/machine/e2e/config_init_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/shim/host.go
This bug was first described in https://github.com/containers/podman/issues/23544, and @cheesesashimi did most of the detective work to find the error!
Signed-off-by: Graceson Aufderheide <gracesonphoto@gmail.com>
Fixes #23544
```release-note
None
```
> Fix for podman machine init not creating necessary JSON file when an ignition-path is passed

- contrib/pkginstaller/Makefile
Bump the bundled krunkit version from 0.1.3 to 0.1.4.
Fixes: #24559
```release-note
Update krunkit in the macos installer to 0.1.4 to fix an issue where libkrun machines failed to start.
```
> Bump bundled krunkit to 0.1.4

- libpod/container_internal_common.go
- libpod/container_internal_linux.go
In theory RootlessNetnsInfo() should never return nil here. However that was actually only true when the rootless netns was set up before and wrote the right cache file with the ip addresses.
Given this cache file is a new feature just added in 5.3 if you updated from 5.2 or earlier the file will not exists thus cause failures for all following started containers.
The fix for this is to stop all containers and make sure the rootless-netns was removed so the next start creates it new with the proper 5.3 cache file. However as there is no way to rely on users doing that and it is also not requirement so simply handle the nil deref here.
The only way to test this would be to run the old version then the new version which we cannot really do in CI. We do have upgrade test for that but they …
> libpod: addHosts() prevent nil deref

- go.mod
- go.sum
- libpod/runtime_img.go
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/.codespellrc
- vendor/github.com/containers/buildah/Makefile
- vendor/github.com/containers/buildah/copier/syscall_unix.go
- vendor/github.com/containers/buildah/define/build.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/executor.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/install.md
- vendor/modules.txt
Closes: https://github.com/containers/podman/issues/24546
```release-note
Now `podman build` honors the `no_pivot_root` setting from `containers.conf` file
```
> libpod: pass down NoPivotRoot to Buildah

- .cirrus.yml
- docs/source/Reference.rst
- libpod/container_internal_common.go
- pkg/bindings/connection.go
- pkg/machine/e2e/machine_test.go
Backports of 
https://github.com/containers/podman/pull/24547
https://github.com/containers/podman/pull/24568
https://github.com/containers/podman/pull/24607
And fix the DEST_BRANCH so the bloat check works.
```release-note
Fixes podman remote connection issue with certain ssh config settings. https://github.com/containers/podman/issues/24567
Do not increase resource limits when running in a user namespace. https://github.com/containers/podman/issues/24508 
```
> [v5.3] v5.3 backports

- pkg/specgen/generate/storage.go
- test/e2e/run_volume_test.go
This matches the behavior of other volume and mount types. Image volumes and volumes/mounts from the `--volumes-from` flag should be overridden by actual user-specified named volumes and mounts, but this was not true for overlay mounts. Fortunately, our duplicate-mount detection logic still works, so we got a good error message at least.
The fix is simple - extend our supersede logic, which currently only works with named volumes and mounts, to also work with overlay mounts.
Fixes #24555
```release-note
Fixed a bug where overlay mounts could not be made at paths where the image specifies a volume ([#24555](https://github.com/containers/podman/issues/24555)).
```
> Overlay mounts supersede image volumes & volumes-from

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/pull.build
- test/system/252-quadlet.bats
- test/system/helpers.systemd.bash
No
```release-note
None
```
Fixes #24599
> Quadlet - Use = sign when setting the pull arg for build

- contrib/win-installer/test-installer.ps1
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/pull.build
- test/system/252-quadlet.bats
- test/system/helpers.systemd.bash
Backport of
https://github.com/containers/podman/pull/24653
https://github.com/containers/podman/pull/24643
```release-note
Fixes an issue where quadlet build files created an invalid podman command line when `Pull=` was used. https://github.com/containers/podman/issues/24599
```
> [v5.3] fix CI and backport quadlet build fix

- libpod/events/config.go
- libpod/events/events.go
- libpod/events/events_freebsd.go
- libpod/events/events_linux.go
- libpod/events/journal_linux.go
- libpod/events/journal_unsupported.go
In the original implementation in `libpod/events/config.go`, `iota` was used to design `EventerType`. 
However, in `libpod/events/events_freebsd.go` and `libpod/events/events_linux.go`, the `NewEventer` function still relies on string comparisons to determine which `EventerType` to use.
1. Completed the `EventerType` comment.
2. Changed `EventerType` to be represented as a `string`.
3. Since `EventerType` is designed to be entirely lowercase, changed the comparison to use lowercase instead of uppercase.
4. Renamed `newEventJournalD` to `newJournalDEventer`, similar to the functions `newLogFileEventer` and `newNullEventer`
5. Removed redundant error-checking steps in `events_linux.go`.
```release-note
None
```
> refact: EventerType and improve consistency

- docs/source/markdown/podman-network-create.1.md
- go.mod
- go.sum
- vendor/github.com/containers/common/libnetwork/netavark/config.go
- vendor/github.com/containers/common/libnetwork/types/const.go
- vendor/modules.txt
This simply updates `common`, as there is nothing to do from the podman side. I added documentation for this new option and improved the `--internal` documentation.
Related:
- https://github.com/containers/netavark/pull/1126
- https://github.com/containers/common/pull/2247
```release-note
None
```
> Add support for bridge mode

- Makefile
Completely my fault, and I'm so sorry.
Untested because I use podman on my home system (for real stuff) and can't afford a `make remotesystem` nuke.
```release-note
None
```
> make remotesystem: fail early if serial tests fail

- libpod/container_internal_common.go
commit 5ebba75dbd4462da47283b3f018804b7361d52bf implemented this behaviour for rootless users and later commit
0a69aefa41d55d2aa30333d6a4ce76b178d1ed5b changed it when in a user namespace, but the same limitation exists for root without CAP_SYS_RESOURCE.  Change the check to use the clamp to the current values if running without CAP_SYS_RESOURCE.
Closes: https://github.com/containers/podman/issues/24692
```release-note
Now default ulimits are clamped also for root when running without CAP_SYS_RESOURCE
```
> spec: clamp rlimits without CAP_SYS_RESOURCE

- libpod/container_commit.go
Move error checking of possible null returned value before its dereference in importBuilder.Format
Found by Linux Verification Center (linuxtesting.org) with SVACE.
```release-note
None
```
> api: Error checking before NULL dereference

- contrib/systemd/user/podman-user-wait-network-online.service
This is broken on e.g. NixOS as systemd only searches a small set of directories for command binary, which does not include `/bin` [1].
[1]: https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Command%20lines
```release-note
None
```
> Fixes missing binary in systemd.

- libpod/info.go
In the `libpod/info.go`, within the `uptime` anonymous struct, there's a `minutes` field, but `seconds` are being used for processing. This PR refactors this issue.
```release-note
None
```
> refact: use uptime.minutes instead of uptime.seconds

- go.mod
- go.sum
- test/e2e/push_test.go
- vendor/github.com/containers/common/libimage/push.go
- vendor/github.com/containers/common/libnetwork/types/network.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/modules.txt
This highlights a bug in common where the compression format is reset if the format is v2s2, even if its a valid compression format.
```release-note
None
```
> Allow forcing compression with v2s2 format

- rpm/podman.spec
The ExclusiveArch spec macro is parsed only on spec parsing level. In this particular case that means that podman-machine is generated on all arches despite of ExclusiveArch present in a subpackage. It is confusing indeed. In order to assure podman-machine is built only on certain arches we need to use ifarch spec macro, as presented in this PR. I verified it with a scratch build.
```release-note
None
```
> [skip-ci] Replace ExclusiveArch with ifarch

- pkg/api/handlers/libpod/images.go
If err != nil then inspect is nil thus here it is better to use name when outputting the error instead of inspectID.
Found by Linux Verification Center (linuxtesting.org) with SVACE.
```release-note
None
```
> api: replace inspectID with name

- libpod/info.go
- test/system/005-info.bats
The command `podman info` returned only one imagestore in `store.graphOptions.<driver>.imagestore` even if multiple
image stores were configured.
This change replaces the field `<driver>.imagestore` with the field `<driver>.additionalImageStores`, that is an array of strings that includes all the configured additional image stores.
Fix containers/storage#2094
```release-note
Fix `podman info` when there are multiple additional image stores
```
> Fix additional image stores in podman info

- pkg/machine/e2e/inspect_test.go
Since 5.3 Unix sockets for Podman API are also available on Windows platforms. This extends existing test to cover for this change. It also slightly changes semantics from provider specifics to OS specifics, but this sounds right, because the expectation is that this is sort of common capability for every expected provider for the platform.
```release-note
None
```
> Cover Unix socket in inpect test on Windows platform

- cmd/podman/compose_machine.go
- cmd/podman/compose_machine_unix.go
- cmd/podman/compose_machine_windows.go
- pkg/machine/e2e/compose_test.go
- pkg/machine/e2e/config_compose_test.go
- pkg/machine/e2e/machine_test.go
- pkg/machine/e2e/scripts/fake_compose
- pkg/machine/e2e/scripts/fake_compose.bat
Use filepath utility instead of generic string replace to convert path on Windows. This also separates OS specific implementations to separate compilation sources and removes redundant check for virtualization provider on Windows platform.
Decision to use transport protocol is based on platform, not virtualization provider. `podman-compose` and `docker-compose` are external tools, which are virtualization provider agnostic. It is logical to separate the implementation into exclusive compilation units.
filepath transformation with prepend of the protocol looks more in line with how the thing is implemented for Unix sockets,
There should be no functional changes, so, no new tests provided. It should be regression tested if `podman compose` for machines was previously covered by e2e tests. …
> Improve platform specific URL handling in `podman compose` for machines

- pkg/machine/qemu/command/command.go
- pkg/machine/qemu/command/command_unix.go
- pkg/machine/qemu/command/command_windows.go
- pkg/machine/qemu/config.go
- pkg/machine/qemu/machine.go
- pkg/machine/qemu/machine_unsupported.go
- pkg/machine/qemu/options_windows_amd64.go
- pkg/machine/qemu/stubber.go
- pkg/machine/qemu/virtiofsd.go
- pkg/machine/vmconfigs/config_windows.go
There are QEMU machine parts related to Windows platform, which were "fast patched" during 5.0 version development with disabling compilation for a part of them and making them unattended. These files accumulated some amount of code rot.  This PR addresses only the code rot issues w/o enabling the actual QEMU Windows support. It does this in a way that also prevents any new warnings in VSCode.
There is expectation that at some point the whole Windows specific parts could be dropped, but I believe that fixing code rot before would not make any harm (especially with a limited scope and changes being compact). The only ugly part is that shared memory backend for virtiofs has to be handled, because this is not supported on Windows. This could count towards added complexity, but I hope this …
> RFC: Fix compilation issues in QEMU machine files (Windows platform)

- cmd/podman/manifest/annotate.go
- pkg/api/handlers/libpod/manifests.go
- pkg/bindings/manifests/types.go
- pkg/bindings/manifests/types_modify_options.go
- pkg/domain/entities/manifest.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/e2e/manifest_test.go
When the --index flag is used, `manifest annotate` shouldn't be expecting a second non-flag argument.
Fixes #24750.
```release-note
`podman manifest annotate` no longer panics when the `--index` flag is used.
```
> Fix panic in `manifest annotate --index`

- contrib/win-installer/build-hooks.ps1
When one or more versions of VS Build tools are installed the script .\winmake.ps1 installer does not finish with error.
...
Done!
Invoke-Expression: C:\...\podman\contrib\cirrus\win-lib.ps1:101:5 Line |
101 |      Invoke-Expression $command -OutVariable unformattedLog | Write-Output
|      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot process argument transformation on parameter 'vsinstance'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type
| "Microsoft.VisualStudio.Setup.Instance".
```release-note
None
```
cc: @l0rd
> Use latest version of VS BuildTools

- contrib/pkginstaller/package.sh
- contrib/pkginstaller/scripts/postinstall
- contrib/pkginstaller/scripts/preinstall
This PR adds the man1 pages to the mac installer.  It also sticks a small configuration file into `/usr/local/etc/man.d` that allows macos and the man binary to look for the podman pages in `/opt/podman/docs/man`.
Fixes #24756
```release-note
Add man1 pages to Mac installer
```
> Add man pages to Mac installer

- cmd/quadlet/main.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/a.network.reuse.container
- test/e2e/quadlet/a.network.reuse.name.container
- test/e2e/quadlet_test.go
This PR fixes a bug introduced by #23814.
Unlike network quadlet units, which are sorted before container quadlet units so that the `ResourceName` of which are guaranteed to be present when used in `addNetworks()`, there is no guaranteed resolving order between containers. As a result, `ResourceName` of a container when used in `addNetworks()` may be empty because the container is not resolved (i.e. `ConventContainer()` is not called for it) yet.
This PR fixes this by adding special handling to resolve the resource name in `addNetworks()` for containers.
@ygalblum PTAL
```release-note
Fix a bug that when reusing another container's network in Quadlet, an error of "cannot get the resource name" may appear.
```
> quadlet: fix inter-dependency of containers in `Network=`

- pkg/systemd/parser/unitfile.go
- pkg/systemd/parser/unitfile_test.go
- test/e2e/quadlet/emptyline.container
This commit simplifies the systemd parser logic, and it solves an infinite loop when using a continuation line.
Closes: https://github.com/containers/podman/issues/24810
```release-note
Solves an infinite loop when parsing quadlet files with a continuation line
```
> systemd: simplify parser and fix infinite loop

- Makefile
- contrib/pkginstaller/Makefile
The gvisor-tap-vsock and vfkit binaries were updated to their latest version, but the binaries were still older ones.
This PR updates these binaries to the latest releases.
```release-note
podman-machine now uses gvproxy 0.8.1 and vfkit 0.6.0
```
> Update gvproxy and vfkit binaries

- build_windows.md
- contrib/cirrus/win-installer-main.ps1
- contrib/win-installer/README.md
- contrib/win-installer/build.ps1
- contrib/win-installer/burn.wxs
- contrib/win-installer/podman-patch.wxs
- contrib/win-installer/podman-setup.wixproj
- contrib/win-installer/podman.wixproj
- contrib/win-installer/podman.wxs
- contrib/win-installer/test-installer.ps1
- contrib/win-installer/utils.ps1
When upgrading from v5.3.1 to a new version on a Windows machine without WSL, the installer asks to reboot. This problem doesn't impact users because v5.3.1 is the last release, but it is blocking the release v5.3.2.
The `ForceReboot` action in the v5.3.1 package is executed during a "major upgrade" to a new version (if WSL is not installed).
- Fix the `ForceReboot` action condition to avoid it during updates
- Add a [Windows Installer patch](https://wixtoolset.org/docs/tools/patches/) for the already released `v5.3.1` so that updates from that version don't trigger an unrequested reboot.
- Bump the WiX version to 5.0.2
- Add tests for upgrades to next version
- Add tests for upgrades from v5.3.1 (minor upgrade)
⚠️ To build the Windows installer from this PR branch (to test the PR), build …
> Add a Windows Installer patch to avoid unrequested reboots

- test/e2e/quadlet/emptyline.container
- test/e2e/quadlet_test.go
follow-up for commit 64e94efb95e099db93ee8a28735549268490190f
```release-note
None
```
> test: enable newly added test

- libpod/kube.go
- test/system/710-kube.bats
Fixes: https://github.com/containers/podman/issues/16542
Kubernetes only allows lower case persistent volume names.
```release-note
Persistent volume names will be lowercase with podman kube generate
```
> When generating host volumes for k8s, force to lowercase

- cmd/podman/containers/update.go
- libpod/define/container.go
- pkg/api/handlers/libpod/containers.go
- pkg/api/handlers/swagger/responses.go
- pkg/api/handlers/types.go
- pkg/api/server/register_containers.go
- pkg/bindings/containers/update.go
- pkg/domain/entities/types/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- pkg/specgenutil/specgen.go
- test/apiv2/20-containers.at
This PR fixes device limitations using `podman-remote update` on remote systems. The cause of the problem was that the major and minor numbers were loaded on the client system and then sent to the remote system, where there could be different major and minor numbers for each device. 
Reproducer in Issue: #24734
Fixes: https://issues.redhat.com/browse/RUN-2381
Fixes: https://github.com/containers/podman/issues/24734
```release-note
Fix device limitations in `podman-remote update` on remote systems
```
> Fix device limitations in `podman-remote update` on remote systems

- cmd/podman/common/completion.go
- cmd/podman/common/registries.go
- cmd/podman/login.go
- cmd/podman/logout.go
- test/e2e/common_test.go
- test/e2e/system_dial_stdio_test.go
- test/system/600-completion.bats
- test/system/700-play.bats
see commits, a few fixes to make the test work in the default debian package environment
```release-note
None
```
> Some debian test fixes

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/shmsize.pod
- test/e2e/quadlet_test.go
This closes #22915
Add support for ShmSize in Pods created with Quadlet.
Add e2e tests.
Add new Docs entry.
```release-note
Users are now able to define the ShmSize value on Pod Units for containers created with quadlets.
```
> Add support to ShmSize in Pods with Quadlet

- libpod/container.go
- libpod/networking_common.go
- test/e2e/containers_conf_test.go
Passing the hostname allows netavark to include it in DHCP lease
requests which, in an environment where DDNS is used, can cause
DNS entries to be created automatically.
* The current Hostname() function in container.go was updated to
check the new `container_name_as_hostname` option in the
CONTAINERS table of containers.conf.  If set and no hostname
was configured for the container, it causes the hostname to be
set to a version of the container's name with the characters not
valid for a hostname removed.  If not set (the default), the original
behavior of setting the hostname to the short container ID is
preserved.
* Because the Hostname() function can return the host's hostname
if the container isn't running in a private UTS namespace, and we'd
NEVER want to send _that_ in a DHCP …
> Pass container hostname to netavark

- libpod/kube.go
- test/system/710-kube.bats
Need to substiture all _ to - for k8s support.
```release-note
None
```
> Kube volumes can not contain _

- docs/tutorials/podman-install-certificate-authority.md
```release-note
None
```
Add a small hint to the tutorial about Install Certificate Authority that a restart of the Podman machine might be necessary to really accept the newly added certificates.
This fixes #24593.
> Add hint to restart Podman machine to really accept new certificates

- Makefile
- cmd/quadlet/main_test.go
- libpod/events/logfile_test.go
- libpod/runtime.go
- pkg/api/handlers/compat/networks.go
- pkg/api/handlers/libpod/manifests.go
- pkg/auth/auth_test.go
- pkg/ctime/ctime_test.go
- pkg/env/env.go
- pkg/machine/compression/copy_test.go
Fix new issues found by usetesting, mainly we should use t.TempDir() in test which makes the code better as this will be removed on test end automatically so no need for defer or any error checking. Also fix issues reported by exptostd, these mainly show where we can switch the imports to the std maps/slices packages instead of the golang.org/x/exp/... packages.
```release-note
None
```
> update golangci/golangci-lint to v1.63.4

- cmd/quadlet/main.go
- cmd/quadlet/main_test.go
No
```release-note
None
```
Resolves: #24783
> Quadlet - make sure the /etc/containers/systemd/users is traversed in rootless

- pkg/specgenutil/volumes.go
- test/e2e/run_test.go
Fix typo: ptxmode -> ptmxmode
Reference: https://github.com/containers/podman/discussions/24921
```release-note
Fix parsing of mount option ptmxmode
```
> specgenutil: Fix parsing of mount option ptmxmode

- cmd/podman/completion/completion.go
Update the description for completion command.
It misses `powershell` in the `valid arguments` list.
```release-note
None
```
> docs: Update description for completion

- libpod/container_copy_common.go
- libpod/container_copy_freebsd.go
- libpod/container_copy_linux.go
- libpod/container_internal_common.go
- libpod/container_path_resolution.go
- libpod/container_stat_common.go
- libpod/shutdown/handler.go
- test/e2e/cp_test.go
This solves several problems with copying into volumes on a container that is not running.
The first, and most obvious, is that we were previously entirely unable to copy into a volume that required mounting - like image volumes, volume plugins, and volumes that specified mount options.
The second is that this fixed several permissions and content issues with a fresh volume and a container that has not been run before. A copy-up will not have occurred, so permissions on the volume root will not have been set and content will not have been copied into the volume.
If the container is running, this is very low cost - we maintain a mount counter for named volumes, so it's just an increment in the DB if the volume actually needs mounting, and a no-op if it doesn't.
```release-note
Fixed a bug …
```
> Mount volumes before copying into a container

- docs/source/markdown/options/userns.container.md
- pkg/namespaces/namespaces.go
- pkg/specgen/namespaces.go
- pkg/util/utils.go
- pkg/util/utils_test.go
- test/e2e/run_userns_test.go
Introduce a new option "size" to configure the maximum size of the user namespace configured by keep-id.
Closes: https://github.com/containers/podman/issues/24837
```release-note
Now --userns=keep-id supports a new option `size` to configure the size of the user namespace
```
> namespaces: allow configuring keep-id userns size

- test/e2e/attach_test.go
- test/e2e/common_test.go
- test/utils/matchers.go
This significantly simplifies the ceromony of running a Podman command in integration tests, from
```go
session := p.Podman([]string{"stop", id})
session.WaitWithDefaultTimeout()
Expect(session).Should(ExitCleanly())
```
to
```go
p.PodmanCleanly("stop", id)
```
There are >4650 instances of `ExitCleanly()` in the tests, and many could be migrated; this does not do that.
@containers/podman-maintainers RFC. While writing integration tests, I find the ever-present repetitive boilerplate hard to read/maintain, and generally off-putting; OTOH the `PodmanCleanly` call does not show explicitly that any testing is happening. I’m also, short-term, not able to migrate everything, so introducing this would make tests less consistent for now.
It’s also very possible there’s already a much better way …
> RFC: Introduce PodmanTestIntegration.PodmanCleanly

- pkg/systemd/parser/unitfile.go
- pkg/systemd/parser/unitfile_test.go
- test/e2e/quadlet/comment-with-continuation.container
Currently the unit file parser supports `#` and `:` characters to define comments. But, the documentation states that the characters used for comments are `#` and `;` [Systemd Documentation](https://www.freedesktop.org/software/systemd/man/latest/systemd.syntax.html)
This PR aims to add support to `;` for comments in unit files as per systemd documentation. ~~without breaking changes by leaving `:` as a supported character for commenting.~~
~~The character `:` should eventually not be supported anymore and does not cause problems at the moment because systemd ignores lines with wrong syntax.~~
An example of a systemd service:
```ini
[Unit]
Description=Hello World Service
After=systemd-user-sessions.service
; another comment
: a bad comment
[Service]
Type=simple …
```
> add support to ; for comments in unit files as per systemd documentation

- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/kube/play_test.go
We now handle CDI qualified names being passed to resources.limits. The
support for that was already in libpod as of ab7f6095a17bd50477c30fc8c127a8604b5693a6
when passed via the devices list. this just hooks the kube yaml parser
up to it.
Additionally we introduce `podman.io/device` that accepts device paths
as names and is transparently translated to mimick --device. This allows
bringing arbitrary devices into the container via similar, although
incompatible with, k8s mechanics:
```yaml
resources:
requests:
podman.io/device=/dev/kmsg: 1
```
Fixes: https://github.com/containers/podman/issues/17833
```release-note
kube-play now supports CDI strings
```
Signed-off-by: Robert Günzler <r@gnzler.io>
> Add kube play support for CDI resource allocation

- pkg/systemd/parser/split.go
- pkg/systemd/parser/split_test.go
- test/e2e/quadlet/escapes.container
Currently the unit file parser can unescape any escape sequences present in values looked up using the following lookup functions in the `UnitFile` struct: `LookupAllArgs`, `LookupAllKeyVal` and `LookupLastArgs`.
This operation is done though the utility function [ `cUnescapeOne` ](https://github.com/containers/podman/blob/ec6b0355bf9c9b90b774707b6adc49a743cbebd4/pkg/systemd/parser/split.go#L57). This function was incorrectly ported from the systemd code base in this file: [escape.c](https://github.com/systemd/systemd/blob/bbe9e03f8066d1001497494ee862cf45f986b854/src/basic/escape.c#L106).
This PR aims to fix the implementation of `cUnescapeOne` we have in Podman as it does not work properly when unescaping octal escape sequences.
Example:
```c
'\110ello \127orld' gets unescaped to …
```
> Fix unescaping octal escape sequence in values of Quadlet unit files

- docs/source/markdown/podman-systemd.unit.5.md
Reference: https://github.com/containers/podman/discussions/24891
I could also have mentioned
```
QUADLET_UNIT_DIRS=<Directory> systemd-analyze {--user} --generators=true verify example.service
```
but I left it out as I didn't come up with a good way to document it. 
```release-note
None
```
> docs: Add quadlet debug method systemd-analyze

- cmd/podman/root.go
- pkg/machine/e2e/config_help_test.go
- pkg/machine/e2e/help_test.go
In shell completion, there is `.exe` suffix on Windows and this break several shells.
Relates to #16499.
It seems didn't fix at the time but waiting for a fix in cobra.
```release-note
Fixed a bug that prevents shell completion on Windows under some circumstances.
```
> Remove `.exe` suffix if any in completion

- docs/source/markdown/podman-pause.1.md.in
- docs/source/markdown/podman-ps.1.md
- docs/source/markdown/podman-restart.1.md.in
- docs/source/markdown/podman-rm.1.md.in
- docs/source/markdown/podman-start.1.md.in
- docs/source/markdown/podman-stop.1.md.in
- docs/source/markdown/podman-unpause.1.md.in
Previously, the 'initialized' state was not documented as an available filter for various Podman commands.
This commit documents 'initialized' as a valid state that can be used to filter the start, stop, restart, rm, pause, unpause, and ps commands.
Fixes #25017
I have quickly investigated the presence of other places (other than filters) where the 'initialized' status might be missing, but didn't find any.
```release-note
None
```
> docs: add 'initialized' state to status filters

- contrib/cirrus/setup_environment.sh
- libpod/container_internal.go
- libpod/container_internal_common.go
- libpod/runtime_ctr.go
- test/e2e/pod_create_test.go
- test/e2e/run_userns_test.go
- test/system/030-run.bats
backport of:
- 3ae15689333ce4d1dd6f9fec70f8297ccc39f931
- 7bb3b83c17fb9412ad33ad3be3810bebed8c3f03
- 432325236b7d195045edb9a4cc47be00f71d407f
Fixes: https://issues.redhat.com/browse/RHEL-67842
> [5.2-rhel] libpod: fix volume copyup with idmap | convert owner IDs only with :idmap

- contrib/cirrus/setup_environment.sh
- libpod/networking_common.go
- test/apiv2/20-containers.at
- test/apiv2/python/rest_api/test_v2_0_0_network.py
- test/compose/ipam_set_ip/docker-compose.yml
- test/compose/uptwice/docker-compose.yml
- test/compose/uptwice/tests.sh
- test/compose/uptwice_idempotent/docker-compose.yml
- test/compose/uptwice_idempotent/tests.sh
- test/e2e/network_test.go
```release-note
Properly return NetworkID during container inspect reports for docker-compose compatibility.
```
> Set network ID if available during container inspect. Fixes #24910

- .cirrus.yml
- pkg/machine/e2e/help_test.go
- pkg/machine/e2e/list_test.go
> Bump timeout in machine tests

- libpod/container_config.go
This did not have a JSON tag prior to being added by #25008. By adding one we risk a breaking change in the DB (particularly given the change in case - useImageHosts vs UseImageHosts) which we should try to avoid.
Remove the tag given this.
```release-note
NONE
```
> Remove JSON tag from UseImageHosts in ContainerConfig

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/Makefile
- vendor/github.com/containers/buildah/add.go
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/internal/open/open.go
- vendor/github.com/containers/buildah/internal/open/open_linux.go
- vendor/github.com/containers/buildah/internal/open/open_types.go
- vendor/github.com/containers/buildah/internal/open/open_unix.go
- vendor/github.com/containers/buildah/internal/open/open_unsupported.go
- vendor/github.com/containers/buildah/internal/types.go
- vendor/github.com/containers/buildah/internal/volumes/bind_linux.go
- vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go
- vendor/github.com/containers/buildah/internal/volumes/volumes.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay_linux.go
- vendor/github.com/containers/buildah/run.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
Bump Buildah to v1.38.1 which addresses CVE-2024-11218.
```release-note
None
```
> [v5.3] Bump Buildah to v1.38.1 with CVE-2024-11218

- go.mod
- go.sum
- test/e2e/pull_test.go
- test/e2e/run_test.go
- test/system/010-images.bats
- test/system/120-load.bats
- test/system/150-login.bats
- test/system/helpers.bash
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/storage/storage_dest.go
- vendor/github.com/containers/image/v5/version/version.go
- vendor/github.com/vbatts/tar-split/archive/tar/format.go
- vendor/github.com/vbatts/tar-split/archive/tar/reader.go
- vendor/modules.txt
This is a subset of #25007, without the newly-added tests (discussed there); filed separately to allow updating c/image, so that others don’t have to resolve the test failures.
```release-note
Partial pulls (pulling zstd:chunked images) now only happen for images that have RootFS.DiffID entry
in the config, and require the layer contents to match.
```
> Update c/image + existing tests to resolve the signing ambiguity

- test/e2e/checkpoint_test.go
- test/e2e/common_test.go
- test/e2e/exec_test.go
- test/e2e/libpod_suite_remote_test.go
- test/e2e/libpod_suite_test.go
- test/e2e/manifest_test.go
- test/e2e/mount_rootless_test.go
- test/e2e/run_cleanup_test.go
- test/e2e/run_test.go
- test/e2e/systemd_activate_test.go
- test/utils/utils.go
- test/utils/utils_suite_test.go
This, primarily, replaces `PodmanAsUserBase` (called with 9 parameters) with `PodmanExecBaseWithOptions` called with `PodmanExecOptions`, where the caller can only specify the relevant options, and by name; and it threads `PodmanExecOptions` through the call stack, so that E2E tests can set these options directly.
This simplifies the call stack and eliminates the need for various helpers. My primary motivation is that, for https://github.com/containers/podman/pull/25007#discussion_r1925240002 , I want to add a “do not log Podman output to the Ginkgo log” option, and this will allow doing that without adding a one more (unnamed) boolean parameter, or perhaps a new set of helpers, throughout the call stack.
Tests can now, in addition to `Podman()`, call `PodmanWithOptions()`, and also …
> Refactor Podman E2E helpers to allow passing/adding more options to the low-level executor

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/internal/open/open.go
- vendor/github.com/containers/buildah/internal/open/open_linux.go
- vendor/github.com/containers/buildah/internal/open/open_types.go
- vendor/github.com/containers/buildah/internal/open/open_unix.go
- vendor/github.com/containers/buildah/internal/open/open_unsupported.go
- vendor/github.com/containers/buildah/internal/types.go
- vendor/github.com/containers/buildah/internal/volumes/bind_linux.go
- vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go
- vendor/github.com/containers/buildah/internal/volumes/volumes.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay_linux.go
- vendor/github.com/containers/buildah/run.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
This addresses CVE-2024-11218, a Buildah based CVE.
Fixes: https://issues.redhat.com/browse/RHEL-67606
```release-note
None
```
> [v5.2-rhel] CVE-2024-11218, Bump Buildah to v1.37.6

- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- pkg/api/handlers/libpod/pods.go
- pkg/specgenutil/specgen.go
- test/apiv2/20-containers.at
This should be set only by podman as it is used for the podman generate systemd --new command. For the api it was set to the system service command which is simply pointless. It must be empty in these cases.
Fixes #25026
```release-note
None
```
> do not set the CreateCommand for API users

- docs/source/locale/ja/LC_MESSAGES/markdown.po
- docs/source/markdown/podman-auto-update.1.md.in
- docs/source/markdown/podmansh.1.md
Fixes: #25063
Yes.
```release-note
Documentation references to the quadlet(5) alias now point directly to the underlying podman-systemd.unit(5) page so that links will work in the HTML renderings where symlinks don't work and in distributions where the symlink isn't present at all, as with the current Brew `podman` package.
```
> Quadlet 5 symlink bypass

- docs/source/markdown/options/mount.md
As reported in #24918 and clarified in https://github.com/containers/crun/issues/1632#issuecomment-2567991631
```release-note
None
```
> docs: mount.md - idmapped mounts only work for root user

- cmd/podman/manifest/rm.go
- docs/source/markdown/podman-manifest-rm.1.md
- pkg/api/handlers/compat/images_remove.go
- pkg/api/handlers/libpod/images.go
- pkg/api/handlers/libpod/manifests.go
- pkg/api/server/register_manifest.go
- pkg/domain/entities/engine_image.go
- pkg/domain/infra/abi/manifest.go
- pkg/domain/infra/tunnel/manifest.go
- test/apiv2/15-manifest.at
- test/system/012-manifest.bats
When removing manifests, users should be allowed to ignore ones that no longer exists.
```release-note
podman manifest rm --ignore option added to ignore missing manifests.
```
> Add podman manifest rm --ignore

- cmd/podman/system/prune.go
- docs/source/markdown/podman-system-prune.1.md
- libpod/runtime.go
- pkg/api/handlers/libpod/system.go
- pkg/bindings/system/types.go
- pkg/bindings/system/types_prune_options.go
- pkg/domain/entities/types/system.go
- pkg/domain/infra/abi/system.go
- pkg/domain/infra/tunnel/system.go
- test/e2e/prune_test.go
The `podman system prune` command can remove build containers that were created during the build but were not removed because the build terminated unexpectedly. 
By default, build containers are not removed to prevent interference with builds in progress. Use the **--build** flag when running the command to remove build containers as well.
- Containerfile:
```Dockerfile
FROM ubi8/ubi
RUN truncate -s 10G out
RUN echo "Hi"
RUN sleep infinity
```
- Test script `run.sh`:
```bash
#!/usr/bin/env bash
podman build -f Containerfile -t podmanleaker &
sleep 60 && kill -9 $! 
```
- measure the size of current images, containers, etc... Before build
```bash
podman unshare du -sh ~/.local/share/containers/
```
- Test script (Note: requires disk space of about 32 GB)
```bash
./run.sh
```
- measure the …
> Clean up after unexpectedly terminated build

- contrib/systemd/system/podman-restart.service.in
If no containers need to be restarted, podman-restart prints "Error: you must provide at least one name or id" then fails.
Update the service file to handle start and stop symmetrically.
This is an alternate solution to the one proposed in https://github.com/containers/podman/pull/25131.
That one is closer to the previous implementation, this one seems more obviously correct.
I have no preference between them - please accept one and reject the other.
Yes
```release-note
Fixed podman-restart.service: now exits successfully when no containers need restarting
```
> Fix podman-restart.service when there are no containers

- test/system/410-selinux.bats
The test `podman selinux: check unsupported relabel` has been failing recently on Fedora rawhide.
This is due to a regression in the `ls` command itself. Workaround for now is to switch to `getfattr -n security.selinux ...`.
Ref: https://github.com/containers/podman/issues/25132#issuecomment-2615744915
Fixes: #25132
```release-note
None
```
> system-tests: switch ls with getfattr for selinux tests

- contrib/cirrus/win-installer-main.ps1
- contrib/win-installer/burn.wxs
- contrib/win-installer/podman.wxs
- contrib/win-installer/test-installer.ps1
This PR adds a condition in the Windows WiX bundle that prevents upgrades from v5.3.1 and recommends the user to upgrade to v5.3.2 first.
Version 5.3.1 of the installer had [a bug](https://github.com/containers/podman/issues/24735) that got patched in v5.3.x. The patch won't be included in the installer for v5.4.0 ([see here for details](https://github.com/containers/podman/pull/25021)), and we can't allow direct upgrades from v5.3.1 to v5.4.x anymore. 
```release-note
None
```
> Avoid upgrading from v5.3.1 on Windows

- Makefile
- docs/source/markdown/options/secret.image.md
- docs/source/markdown/podman-build.1.md.in
**TL;DR:**
1. Enhance the `podman build --secret` documentation and add examples.
2. Add `validatepr` to `make help` output.
<details>
**Details:** After struggling to find a way to build an image without writing a secret to disk first, I did some hunting. This PR is basically a copy/paste from [buildah-build.1], with some tweaks to appease the podman project linter and with the addition of some Examples. (I plan to submit a similar PR to [containers/buildah] to update the `--secret` help output and add the examples there as well).
**Note:** This "Fixes" #23388 if you go strictly by the Title. However, if you read the comments, it looks like the OP is looking for something more along the lines of using `--secret` WITHOUT needing `--mount=type=secret` modifications to a Containerfile. This …
> Improve podman build secrets docs / Makefile validatepr description

- cmd/podman/machine/machine.go
- pkg/machine/provider/platform_darwin.go
libkrun is not supported on Intel.  We should error.
```release-note
Emit an error when trying to use libkrun on Intel-based Macs
```
> error with libkrun on intel-based machines

- pkg/machine/machine_windows.go
- pkg/machine/machine_windows_test.go
The behavior of function `path/filepath.EvalSymlinks()` has changed in Go v1.23:
- https://go-review.googlesource.com/c/go/+/565136
- https://go.dev/doc/go1.23#minor_library_changes
- https://tip.golang.org/doc/godebug
As a consequence, starting with Podman 5.3.0, when installing on Windows (WSL) using [Scoop](https://scoop.sh/#/), Podman fails to start because it fails to find helper binaries. Scoop copies Podman binaries in a folder of type Junction and `EvalSymlinks` returns an error. The problem is described in #24557.
To address this problem, we check if a path is a `Symlink` before calling `EvalSymlinks`, and if it's not (hard links, mount points, or canonical files), we call `path/filepath.Clean` for consistency. In fact, `path/filepath.EvalSymlinks`, after evaluating a path, calls …
> Safer use of `filepath.EvalSymlinks()` on Windows

- cmd/podman/machine/reset.go
- pkg/machine/define/errors.go
- pkg/machine/e2e/start_test.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/machine.go
Prevent two podman machines running on darwin
As issue #25112 points out, it was possible to start a machine on one of the darwin providers and then switch providers and start another one with a different name.  This PR firstly prevents that use which is a forbidden use case.
Secondarily, performed some minor cleanup on the error messages being used so that the error would be specific to this condition.
This bug fix is for darwin only.  In the case of Windows, we probably need to answer the question I raised in #24067 first, which is whether we want to stop allowing WSL to run multiple machines.
Fixes #25112
```release-note
Fix bug that allowed users to run a machine on both the `applehv` and `libkrun` providers on darwin
```
> Prevent  multiple machines running on different providers on darwin

- pkg/rootless/rootless_linux.c
`argv[0]`, ie: the full buffer allocated by `get_cmd_line_args`, was going to be freed only if `can_use_shortcut()` was called. Since that is not always the case, add a fallback cleanup method.
Spotted using `-fsanitize=address`: 
```
==1050100==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 512 byte(s) in 1 object(s) allocated from:
#0 0x70591a2fd9c7 in malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
#1 0x705915490406 in get_cmd_line_args /home/federico/go/pkg/mod/github.com/containers/podman/v5@v5.2.5/pkg/rootless/rootless_linux.c:313
```
Fix was tested by running once again (after applying the patch) with asan.
```release-note
None
```
> fix(pkg/rootless): avoid memleak during init() contructor

- RELEASE_NOTES.md
- version/rawversion/version.go
Now including full release notes
```release-note
NONE
```
> [CI:ALL] Bump to v5.4.0-RC2

- cmd/podman/machine/machine.go
- pkg/machine/provider/platform_darwin.go
A review comment post merge suggested I move the detection of libkrun and intel into the provider.Get()
```release-note
None
```
> Move detection of libkrun and intel

- pkg/api/handlers/compat/containers_create.go
- test/compose/cdi_device/README.md
- test/compose/cdi_device/device.json
- test/compose/cdi_device/docker-compose.yml
- test/compose/cdi_device/setup.sh
- test/compose/cdi_device/teardown.sh
- test/compose/cdi_device/tests.sh
Disclaimer: I am not very familiar with all the details of CDI, so there might still be something missing, but the following patch seems to be enough for the test cases that were reported so I open a PR to gather some feedback.
Pass down the devices specifies in the resources block so that CDI devices in the compose file are honored.
Tested manually with the following compose file:
services:
testgpupodman_count:
image: ubuntu:latest
command: ["nvidia-smi"]
profiles: [gpu]
deploy:
resources:
reservations:
devices:
- driver: nvidia
count: 1
capabilities: [gpu]
testgpupodman_deviceid:
image: docker.io/ubuntu:latest
command: ["nvidia-smi"]
deploy:
resources:
reservations:
devices:
- driver: cdi
device_ids: ['nvidia.com/gpu=all']
capabilities: [gpu]
```release-note
Now Podman honors CDI …
```
> pkg/api: honor cdi devices from the hostconfig

- rpm/podman.spec
This commit adjusts qemu dependency to be Fedora only.
```release-note
None
```
> [skip-ci] RPM: no qemu on RHEL

- cmd/podman/artifact/add.go
- docs/source/markdown/.gitignore
- docs/source/markdown/options/annotation.manifest.md
- docs/source/markdown/podman-artifact-add.1.md.in
- pkg/api/handlers/libpod/manifests.go
- pkg/domain/entities/artifact.go
- pkg/domain/entities/engine_image.go
- pkg/domain/infra/abi/artifact.go
- pkg/domain/infra/tunnel/artifact.go
- pkg/domain/utils/utils.go
- pkg/libartifact/store/store.go
- pkg/libartifact/types/config.go
- test/e2e/artifact_test.go
podman artifact add now supports two new command line switches.
--type string that describes the type of artifact
--annotation string slice in the form of key=val
These new options allow users to "tag" information in on their artifacts for any number of purposes down the line
RUN-2446
```release-note
`podman artifact add` has new options: `--type` and `--annotation`
```
> Add type and annotations to artifact add

- cmd/podman/artifact/list.go
- docs/source/markdown/.gitignore
- docs/source/markdown/options/no-trunc.md
- docs/source/markdown/podman-artifact-ls.1.md.in
- docs/source/markdown/podman-images.1.md.in
- test/e2e/artifact_test.go
added a --no-trunc flag to artifact ls, which follows what images has done.  by default now, the ls output will have the shortened 12 character digest.  the --no-trunc will output the full digest.
```release-note
Added `no-trunc` option to artifact ls and shortened digests in default ls output to 12 characters.
```
> Add --no-trunc to artifact ls

- libpod/container_exec.go
- libpod/util.go
- pkg/api/handlers/compat/exec.go
- pkg/domain/infra/tunnel/containers.go
podman exec support detaching early via the detach key sequence. In that
case the podman process should exit successfully but the container exec
process keeps running.
Now I wrote automated test for both podman run and exec detach but this
uncovered several larger issues:
- detach sequence parsing is broken[1]
- podman-remote exec detach is broken[2]
- detach in general seems to be buggy/racy, seeing lot of flakes that
fail to restore the terminal and get an EIO instead, i.e.
"Unable to restore terminal: input/output error"
Thus I cannot add tests for now but this commit should at least fix the
obvoius case as reported by the user so I like to get this in regardless
and I will work through the other issues once I have more time.
Fixes https://github.com/containers/podman/issues/24895
[1] …
> podman exec: correctly support detaching

- contrib/pkginstaller/Makefile
- go.mod
- go.sum
- vendor/modules.txt
- winmake.ps1
The current macos installer gvproxy version has a number of issues around dns handling[1,2]. They should be fixed now in 0.8.3 as they reverted the dns changes back to the 0.7.5 code. This should make it work like it used to be. Our 5.3.2 installer ships the 0.7.5 version so users of the podman installer never noticed that but we got plenty of reports from brew users. This needs to be backported into v5.4 to make sure we do not ship the broken version as part of the installer.
[1] https://github.com/containers/gvisor-tap-vsock/issues/462
[2] https://github.com/containers/gvisor-tap-vsock/issues/466
```release-note
Update the bundled gvproxy version to 0.8.3
```
> update gvproxy version

- rpm/podman.spec
Since commit 06c103469d we are using getfattr in system tests, that caused failures in gating tests[1] as getfattr was not installed. So add attr as dependency.
[1] https://artifacts.dev.testing-farm.io/d93b6849-e526-46e9-a7c3-874bad4217a9/work-tests.yml8_p4nfkf/tests-n75vnz0u/test.podman-root.bats.log
```release-note
None
```
> rpm: add attr as dependency for podman-tests

- go.mod
- go.sum
- vendor/github.com/containers/buildah/.cirrus.yml
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/modules.txt
Bump Buildah to v1.39.0 in preparation for Podman v5.4.
```release-note
None
```
> [v5.4] Bump Buildah to v1.39.0

- pkg/machine/wsl/declares.go
This is a workaround for #25201 and helps with
upgrading the WSL image to Fedora 41.
```release-note
None
```
> Force use of iptables on Windows WSL

- cmd/podman/artifact/list.go
- docs/source/markdown/options/noheading.md
- docs/source/markdown/podman-artifact-ls.1.md.in
- test/e2e/artifact_test.go
like images and containers, it could be handy to have a --noheading option that removes the headings on the output.
```release-note
Add --noheading to `podman artifact ls`
```
> Add --noheading to artifact ls

- test/system/080-pause.bats
This PR fixes flake test: `podman pause/unpause with HealthCheck interval`. 
Checking of service and timer caused unexpected exit code `3` of `systemctl status`. Since the status check can be executed when HealthCheck was exited, this caused a termination error code `3` for `systemctl status`. Because service was in dead state because HealthCheck exited.
Fixes: https://github.com/containers/podman/issues/25204
```release-note
None
```
> Fix flake test: `podman pause/unpause with HealthCheck interval`

- version/rawversion/version.go
> Bump version to 5.5.0-dev

- test/e2e/common_test.go
- test/e2e/pull_chunked_test.go
- test/e2e/pull_test.go
- test/e2e/run_transient_test.go
- test/utils/utils.go
This adds Podman tests of chunked pulls.
```release-note
None
```
> Zstd:chunked podman-side tests

- pkg/rootless/rootless_linux.c
avoid using the glibc fork() function after using directly the clone() syscall, as it confuses glibc causing the fork() to hang in some cases.
The issue has been observed only on s390x, and the fix was confirmed in the issue discussion.
Closes: https://github.com/containers/podman/issues/25184
```release-note
Fix a potential hang on s390x when running as rootless and Podman needs to reexecute itself
```
> rootless: fix hang on s390x

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/Makefile
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/internal/open/open.go
- vendor/github.com/containers/buildah/internal/open/open_linux.go
- vendor/github.com/containers/buildah/internal/open/open_types.go
- vendor/github.com/containers/buildah/internal/open/open_unix.go
- vendor/github.com/containers/buildah/internal/open/open_unsupported.go
- vendor/github.com/containers/buildah/internal/parse/parse.go
- vendor/github.com/containers/buildah/internal/types.go
- vendor/github.com/containers/buildah/internal/volumes/bind_linux.go
- vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay.go
- vendor/github.com/containers/buildah/run.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
This fixes CVE-2024-11218 by vendoring in Buidlah v1.29.5 which has the actual fixes within it.
Fixes: https://issues.redhat.com/browse/OCPBUGS-44538, https://issues.redhat.com/browse/OCPBUGS-44537,
https://issues.redhat.com/browse/OCPBUGS-44539,
https://issues.redhat.com/browse/RHEL-67603, https://issues.redhat.com/browse/RHEL-67597
```release-note
None
```
> [v4.4.1-rhel] CVE-2024-11218 Fix

- rpm/podman.spec
The default `gobuild` macro on CentOS Stream 9 now includes support for `BUILDTAGS`.
CentOS Stream envs now also define `_user_tmpfilesdir` macro by default.
Both these definitions are no longer needed here.
```release-note
None
```
> [skip-ci] RPM: cleanup macro defs

- test/apiv2/test-apiv2
In our CI env we use a special registries.conf file (test/registries.conf) to redirect some parts but it also defines: 
```
[[registry]]
location="localhost:5000"
insecure=true
```
That means that port 5000 is trusted by default so the /v1.40/images/localhost:5000/myrepo/push?tag=mytag test in 12-imagesMore fails when the test registry uses port 5000.
Example failure:
```
not ok 360 [12-imagesMore] POST /v1.40/images/localhost:5000/myrepo/push?tag=mytag [-d {}] : status
{"status":"mytag: digest: sha256:d40f8191d6dae366339e318d1004258022f56bd8c649720a72060fad20019c9d size: 758"}
```
To avoid using port 5000 simply start at 5001.
```release-note
None
```
> test/apiv2: fix registry push flake

- rpm/podman.spec
For Copr builds, it will mention the Copr info from where the rpm is
installed.
For non-copr builds, it will mention the value of the packager macro
if set, and skip this field altogether if not.
On local rpm builds, this shows:
```
Build Origin:  Lokesh Mandvekar <lsm5@fedoraproject.org>
```
On koji rpm builds, this shows:
```
Build Origin: Fedora Project
```
On copr rpm builds (for eg. rhcontainerbot/playground), this shows:
```
Build Origin: Copr: rhcontainerbot/playground
```
```release-note
None
```
> [skip-ci] RPM: set BUILD_ORIGIN

- libpod/container_internal_common.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
I'm not sure if there is an equivalent to CAP_SYS_RESOURCE on FreeBSD but for now, I have added a no-op stub which returns false.
```release-note
None
```
> libpod: make hasCapSysResource platform-specific

- .cirrus.yml
The FreeBSD build is broken due to missing FreeBSD 13.3 image, for example https://cirrus-ci.com/task/4915570123997184
Version 13.3 is EOL. See https://www.freebsd.org/releases/
```release-note
None
```
> [CI] Bump FreeBSD version to 13.4

- libpod/sqlite_state.go
- test/system/005-info.bats
As part of our database init, we perform a check of the current values for a few fields (graph driver, graph root, static dir, and a few more) to validate that Libpod is being started with a sane & sensible config, and the user's containers can actually be expected to work. Basically, we take the current runtime config and compare against values cached in the database from the first time Podman was run.
We've had some issues with this logic before this year around symlink resolution, but this is a new edge case. Somehow, the database is being loaded with the empty string for some fields (at least graph driver) which is causing comparisons to fail because we will never compare against "" for those fields - we insert the default value instead, assuming we have one.
Having a value of "" in …
> In SQLite state, use defaults for empty-string checks

- .cirrus.yml
- RELEASE_NOTES.md
- docs/source/Reference.rst
- libpod/sqlite_state.go
- test/system/005-info.bats
- version/rawversion/version.go
Only three backports, quiet final release.
```release-note
NONE
```
> Bump to v5.4.0

- cmd/podman/artifact/extract.go
- docs/source/markdown/podman-artifact-extract.1.md
- docs/source/markdown/podman-artifact.1.md
- pkg/domain/entities/artifact.go
- pkg/domain/entities/engine_image.go
- pkg/domain/infra/abi/artifact.go
- pkg/domain/infra/tunnel/artifact.go
- pkg/libartifact/store/store.go
- pkg/libartifact/types/config.go
- test/e2e/artifact_test.go
- test/e2e/common_test.go
Add a new command to extract the blob content of the artifact store to a local path.
Fixes https://issues.redhat.com/browse/RUN-2445
```release-note
Added a new podman artifact extract command.
```
> add podman artifact extract

- libpod/container_internal.go
- libpod/oci.go
- libpod/oci_conmon_common.go
- libpod/oci_missing.go
This seems to have been added as part of the cleanup of our handling of OOM files, but code was never added to remove it, so we leaked a single directory with an exit file and OOM file per container run. Apparently have been doing this for a while - I'd guess since March of '23 - so I'm surprised more people didn't notice.
Fixes #25291
Marking No New Tests as I didn't say any existing exit file tests, but I could add one if folks want.
```release-note
Fixed a bug where Podman would leak a file and directory for every container created.
```
> Remove persist directory when cleaning up Conmon files

- cmd/podman/artifact/add.go
- docs/source/markdown/podman-artifact-add.1.md.in
- pkg/domain/entities/artifact.go
- pkg/domain/infra/abi/artifact.go
- pkg/libartifact/store/store.go
- pkg/libartifact/types/config.go
- test/e2e/artifact_test.go
- test/e2e/common_test.go
This PR creates a  `--append` flag to add a file to an existing artifact using the `podman artifact add` command.
Fixes: https://issues.redhat.com/browse/RUN-2444
```release-note
`podman artifact add` has new option: `--append`
```
> Create `--append` flag to add file to existing artifact using `podman artifact add` command

- libpod/container_exec.go
- libpod/healthcheck.go
- test/system/220-healthcheck.bats
This PR creates a method to run the HealthCheck command without creating and deleting an `ExecSession` in the database. 
When HealthCheck is run using the original `exec` method, an `ExecSession` is created and deleted. This approach causes unexpectedly higher IO usage when synchronizing the container and creating and deleting `ExecSession` in the database. 
The new `healthCheckExec` function locks the container and creates the `ExecSession` locally without writing to the database. Executes a local `ExecSession`.  As a result, the number of writes in the database has been reduced to zero. 
- Start 30 containers with `/bin/true` as a health check that runs every 10 seconds.
- Monitor writes for two mins: `timeout 120 stap check.stp 0x23 > stap.out` 
- > Note: you will probably need to …
> Run HealthCheck without saving the `ExecSession` to the database

- .cirrus.yml
- contrib/cirrus/lib.sh
- contrib/cirrus/prebuild.sh
Instead of us forgetting to update it on each new branch push.
Also bump the mac machine timeout to try to avoid the timeout flakes.
```release-note
None
```
> cirrus: figure out DEST_BRANCH automatically

- .cirrus.yml
- test/buildah-bud/apply-podman-deltas
- test/buildah-bud/buildah-tests.diff
- test/buildah-bud/run-buildah-bud-tests
To speed up CI times
```release-note
None
```
> test/buildah-bud: run in parallel

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/memory.container
- test/e2e/quadlet_test.go
Maps to the `--memory=` flag.
```release-note
Support for `Memory=` in `[Container]` units.
```
> quadlet: support `Memory=` in `[Container]` sections

- libpod/container_graph.go
- pkg/syncmap/syncmap.go
This greatly simplifies the locking around these two functions, and things end up looking a lot more elegant. This should prevent the race flakes we were seeing before.
Fixes #25289
First time I've worked with Go generics - nice to finally have the ability to do generic data structures.
```release-note
NONE
```
> Add SyncMap package and use it for graph stop/remove

- go.mod
- go.sum
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/Makefile
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/internal/open/open.go
- vendor/github.com/containers/buildah/internal/open/open_linux.go
- vendor/github.com/containers/buildah/internal/open/open_types.go
- vendor/github.com/containers/buildah/internal/open/open_unix.go
- vendor/github.com/containers/buildah/internal/open/open_unsupported.go
- vendor/github.com/containers/buildah/internal/parse/parse.go
- vendor/github.com/containers/buildah/internal/types.go
- vendor/github.com/containers/buildah/internal/volumes/bind_linux.go
- vendor/github.com/containers/buildah/internal/volumes/bind_notlinux.go
- vendor/github.com/containers/buildah/pkg/overlay/overlay.go
- vendor/github.com/containers/buildah/run.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/github.com/containers/buildah/run_freebsd.go
- vendor/github.com/containers/buildah/run_linux.go
- vendor/modules.txt
This addresses the Buildah CVE-2024-11218 issue in the v4.4.1-crio branch.
Fixes: https://issues.redhat.com/browse/OCPBUGS-44536
```release-note
None
```
> [v4.4.1-crio] CVE-2024-11218 Fix

- pkg/bindings/containers/attach.go
closes https://github.com/containers/podman/issues/25344
```release-note
Silenced an error from the go bindings that may caused pkg/bindings/containers.ExecStartAndAttach() to report erroneous errors when stdin was consumed after the exec session was stopped.
```
cc @mesaglio
> fix: reduce logs noise when attach input on `ExecStartAndAttach`

- docs/source/markdown/options/cap-add.md
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=2345676
```release-note
None
```
> docs: warn about adding capabilities

- libpod/oci_util.go
- test/e2e/exec_test.go
- test/e2e/run_entrypoint_test.go
- test/e2e/run_exit_test.go
- test/system/030-run.bats
unify the error codes returned by runc and crun.
Fix the tests to work with both runtimes, as well as the https://github.com/containers/crun/pull/1672 changes in progress for crun.
Follow-up for https://github.com/containers/podman/pull/25340
```release-note
None
```
> oci: report empty exec path as ENOENT

- .packit.sh
- rpm/podman.spec
Additional rpm patching to show upstream short sha in `podman --version` caused podman-machine-os tests to fail.
This commit gets rid of that patching and instead sets define.gitCommit LDFLAG for Copr rpms.
```release-note
None
```
> [skip-ci] Packit/Copr: Fix `podman version` in rpm

- cmd/podman/artifact/rm.go
- docs/source/markdown/podman-artifact-rm.1.md
- pkg/domain/entities/artifact.go
- pkg/domain/infra/abi/artifact.go
- test/e2e/artifact_test.go
Add the ability to remove all artifacts with a --all|-a option in podman artifact rm.
Fixes: https://issues.redhat.com/browse/RUN-2512
```release-note
Add ability to remove all artifacts in the local store
```
> Add --all to artifact rm

- cmd/podman/containers/create.go
gSince commit c25cc7230 ("Allow a value of -1 to set unlimited pids limit", PR #11794) podman converts the pids-limit value of -1 to 0 for OCI spec.
Unfortunately, different runtimes (crun and runc) treat pids.limit=0 differently, and the runtime-spec definition is somewhat vague (see [1]).
Long term fix belongs to runtime-spec and then runtimes should follow it.
Short term fix is do not convert -1 to 0 (as all runtimes treat -1 as unlimited).
[NO TESTS NEEDED] -- this is covered by test added in commit 553e53d44.
Fixes: https://issues.redhat.com/browse/RHEL-80973
```release-note
podman run/update: fix --pid-limit -1 for runc case
```
> podman run: fix --pids-limit -1 wrt runc

- pkg/api/handlers/compat/system.go
- test/apiv2/45-system.at
```release-note
Fixed reporting summed image size when using compat endpoint in disk usage
```
> Fix reporting summed image size for compat endpoint

- go.mod
- go.sum
- vendor/github.com/go-jose/go-jose/v3/jwe.go
- vendor/github.com/go-jose/go-jose/v3/jws.go
- vendor/modules.txt
Contains a fix for CVE-2025-27144
```release-note
None
```
> vendor: update github.com/go-jose/go-jose/v3 to v3.0.4

- cmd/podman/machine/cp.go
- cmd/podman/machine/machine.go
- docs/source/markdown/podman-machine-cp.1.md
- docs/source/markdown/podman-machine.1.md
- pkg/machine/e2e/config_cp_test.go
- pkg/machine/e2e/cp_test.go
- pkg/machine/ssh.go
- pkg/specgen/volumes.go
- pkg/specgen/winpath.go
Adds a new `podman machine cp` subcommand. This will allow users to copy files or directories between a running Podman Machine and their host.
```release-note
Add a new `podman machine cp` subcommand
```
> Add `podman machine cp` subcommand

- cmd/podman/common/completion.go
- docs/source/markdown/podman-events.1.md
- libpod/events.go
- libpod/events/config.go
- libpod/events/events.go
- libpod/events/logfile.go
- pkg/domain/infra/abi/secrets.go
- test/e2e/secret_test.go
This PR adds the "secret" Event type and emits it with "create" and "remove" statuses when Secret is created or removed.
This can be used for example by podman interfaces to view and manage secrets.
Fixes: #24030
```release-note
The podman-events command now supports the "secret" type with "create" and "remove" statuses.
```
> Add "create" and "remove" events for secrets.

- pkg/domain/infra/abi/images.go
- pkg/domain/infra/abi/manifest.go
- pkg/libartifact/store/store.go
- pkg/machine/ocipull/ociartifact.go
- pkg/machine/ocipull/source.go
... to validate that the manifests match expected digests, if any.
Do this everywhere, even where we read local storage which is mostly trusted, because it is cheap enough and being consistent makes it less likely for the code to be copied into other contexts where the sources are not trusted.
```release-note
None
```
> Use UnparsedInstance.Manifest instead of ImageSource.GetManifest

- docs/source/markdown/podman-kube-play.1.md.in
Closes: https://github.com/containers/podman/issues/25436
```release-note
None
```
> docs,kube: add configMap as supported volume option

- docs/source/markdown/podman-machine-os-apply.1.md
A user reported that it was a surprise to receive an unsupported os error when trying to use `podman machine os apply` with WSL machines. This is intentional however the documentation needed to be updated to explicitly state why (it is not based on FCOS).
Fixes: #25435
```release-note
None
```
> Update documentation for podman-machine-os-apply

- .packit-copr-rpm.sh
- .packit-rpm-git-commit.sh
- .packit.yaml
- rpm/podman.spec
Packit's `pre-sync` action allows modification of spec file prior to dist-git PR creation. This is already being done on containers-common rpm to update c/storage and c/image verions tags in spec.
This commit will allow `podman version` to show `Git Commit: $SHA` for all copr as well as koji builds.
```release-note
None
```
> [skip-ci] Packit/RPM: Display upstream commit SHA in all rpm builds

- libpod/container_internal.go
- libpod/healthcheck.go
- libpod/healthcheck_linux.go
- test/system/220-healthcheck.bats
When starting a container consider healthcheck errors fatal. That way user know when systemd-run failed to setup the timer to run the healthcheck and we don't get into a state where the container is running but not the healthcheck.
This also fixes the broken error reporting from the systemd-run exec, if the binary could not be run the output was just empty leaving the users with no idea what failed.
Fixes #25034
```release-note
If podman fails to setup the healthcheck on with systemd-run on container start proper errors are now being reported.
```
> report healthcheck start errors

- .packit.yaml
- CONTRIBUTING.md
> [CI:DOCS] Packit: clarify secondary status in CI

- pkg/domain/infra/abi/play.go
- test/system/252-quadlet.bats
When no containers could be started we need to make sure the unit status
reflects this. This means we should not send the READ=1 message and not
keep the service container running when we were unable to start any
container.
There is the question what should happen when only a subset was started.
For systemd we can only be either running or failed. And as podman kube
play also just keeps the partial started pods running I opted to let
systemd keep considering this as success.
Fixes https://github.com/containers/podman/issues/20667
Fixes https://issues.redhat.com/browse/RHEL-80471
And two more minor fixes, see the first two commits
```release-note
Fixes an issue where kube quadlet units would not report an error (and stay running) even when the pod failed to start.
```
> quadlet kube: correctly mark unit as failed

- docs/source/Introduction.rst
A user has reported that a previously used URL in our Introduction documentation is no longer working.  It apparently has missing files and so forth.  We now use a Containerfile that is more reliable and less chance of change.
Fixes: #25449
```release-note
None
```
> Replace old nginx image with podman hello

- cmd/podman/artifact/pull.go
- pkg/domain/infra/abi/artifact.go
- test/e2e/artifact_test.go
fixed a bug in the artifact code where --retry-delay was being discarded.
Fixes: https://issues.redhat.com/browse/RUN-2511
Fixes: https://issues.redhat.com/browse/RHEL-80259, https://issues.redhat.com/browse/RHEL-80260
This was initially put into the v5.4 branch, but it also needs to be in this branch.
```release-note
None
```
> [v5.4-rhel] wire up --retry-delay for artifact pull

- libpod/container_api.go
```release-note
Fixed a race condition between wait and remove for containers started with autoremove
```
> Wait race with rm

- cmd/podman/containers/create.go
Since commit c25cc7230 ("Allow a value of -1 to set unlimited pids limit") podman converts the pids-limit value of -1 to 0 for OCI spec.
Unfortunately, different runtimes (crun and runc) treat pids.limit=0 differently, and the runtime-spec definition is somewhat vague (see [1]).
Long term fix belongs to runtime-spec and then runtimes should follow it.
Short term fix is do not convert -1 to 0 (as all runtimes treat -1 as unlimited).
[NO NEW TESTS NEEDED] -- this is covered by test added in commit 553e53d44.
Fixes: https://issues.redhat.com/browse/RHEL-80973
[1]: https://github.com/opencontainers/runc/issues/4014#issuecomment-1888185352
Fixes: https://issues.redhat.com/browse/RHEL-82424, https://issues.redhat.com/browse/RHEL-82425
In the RHEL 9.6 and 10.0 ZeroDay streams
```release-note …
```
> [v5.4-rhel] podman run: fix --pids-limit -1 wrt runc

- pkg/util/utils.go
We can use the built-in `min` and `max` functions since Go 1.21.
Reference: https://go.dev/ref/spec#Min_and_max
```release-note
None
```
> pkg/util: remove redundant min/max helper functions

- docs/source/markdown/podman-machine-init.1.md.in
- pkg/machine/e2e/init_test.go
- pkg/machine/shim/host.go
- pkg/machine/shim/host_test.go
the destination machine mount overwrote /tmp.  Here I have added a sanity check.  I also moved the volume parsing and check earlier in the init function so that one does not have to endure the decompression and clean up of the machine image for cli parsing.
Fixes: #18230
```release-note
Fixed bug #18230 where mounting to machine mount to /tmp causes unexpected results.
```
> Do not allow mounting to machine dir /tmp

- cmd/podman/containers/cp.go
- pkg/machine/e2e/basic_test.go
- pkg/machine/e2e/config_test.go
```release-note
None
```
Resolves #25472
Calling `copy.ResolveHostPath` fails when copying from stdin on Windows as /dev/stdin isn't a real folder. The result of `copy.ResolveHostPath` isn't actually used in the stdin code flow, so an easy fix is to condition the call on whether isStdin is true or false. The only potential behavior change is that, if for some unlikely reason /dev/stdin was missing on Linux or MacOS, the copy command would fail with a different error than it did previously.
> Don't try to resolve host path if copying from stdin

- libpod/runtime_volume_common.go
- rpm/podman.spec
- test/system/161-volume-quotas.bats
- test/system/README.md
Backport of #25417 minus the c/storage update to v5.4-rhel branch.
Fixes https://issues.redhat.com/browse/RHEL-82198
Fixes https://issues.redhat.com/browse/RHEL-82199
```release-note
NONE
```
> [v5.4-rhel] Create quota before _data dir for volumes

- Makefile
- contrib/pkginstaller/Makefile
- go.mod
- go.sum
- vendor/github.com/containers/gvisor-tap-vsock/pkg/types/gvproxy_command.go
- vendor/modules.txt
- winmake.ps1
The 0.8.4 has one important fix[1], which could improve #25121.
Also it set all places to use same version of gvisor-tap-vsock 
[1]https://github.com/containers/gvisor-tap-vsock/issues/474
```release-note
Update the bundled gvproxy version to 0.8.4
```
> update gvproxy version to 0.8.4

- cmd/podman/system/reset.go
- cmd/podman/system/reset_machine.go
- docs/source/markdown/podman-system-reset.1.md
- utils/utils.go
This PR prevents the removal of the `podman.sock` file using the `podman system reset` command.
The `podman system reset` removes the `RunDirectory` directory as part of the podman machine reset, where `podman.sock` is usually stored.  
Fixes: https://issues.redhat.com/browse/RHEL-71320
```release-note
The `podman system reset` command does not remove the `podman.sock` file.
```
> Fix `podman system reset` deletes the `podman.sock`

- version/rawversion/version.go
As the title says. All backports already complete, so this is just a version number change.
```release-note
NONE
```
> Bump to v5.4.1

- .packit-rpm-git-commit.sh
This fixes multiple trailing quotes after the commit and also ensures the older commit id will be correctly replaced by the newer id.
```release-note
None
```
> [skip-ci] Packit: Fix action script for updating upstream commit id in rpm spec

- contrib/cirrus/win-installer-main.ps1
To avoid problems when automatically downloading `latest` podman windows installer (e.g. the windows installer hasn't been included in the GH release because of an issue with the keys to sign it), we are now hardcoding the version of Podman that is
used to test the upgrade from latest to current version.
```release-note
None
```
> Windows installer test: hardcode the ID of the latest GH release

- docs/source/markdown/options/mount.md
- libpod/container.go
- libpod/container_config.go
- libpod/container_internal_common.go
- libpod/container_internal_freebsd.go
- libpod/container_internal_linux.go
- libpod/options.go
- libpod/runtime.go
- pkg/domain/infra/abi/artifact.go
- pkg/libartifact/store/store.go
- pkg/libartifact/types/config.go
- pkg/specgen/generate/container_create.go
- pkg/specgen/specgen.go
- pkg/specgen/volumes.go
- pkg/specgenutil/specgen.go
- pkg/specgenutil/volumes.go
- test/e2e/artifact_mount_test.go
- test/e2e/artifact_test.go
- test/e2e/common_test.go
Add support for mounting artifacts with `type=artifact,src=quay.io/libpod/testartifact:20250206-single,dst=/data`
see commits
```release-note
The --mount option accepts a new mount type `artifact` to mount a artifact into a container. 
```
> add artifact mount support

- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/events.go
- libpod/healthcheck.go
- libpod/options.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/generate.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/pod_create.go
- pkg/specgen/specgen.go
- test/apiv2/20-containers.at
- test/system/220-healthcheck.bats
- test/upgrade/test-upgrade.bats
This PR changes `HealthLogDestination`, `HealthMaxLogCount`, `HealthMaxLogSize` of `ContainerMiscConfig` to pointers.  And it removes omitempty from `HealthLogDestination`, `HealthMaxLogCount`, `HealthMaxLogSize` of `SpecGenerator.ContainerHealthCheckConfig`. 
GoLang sets unset values to the default value of the type. This means that the destination of the log is an empty string and the count and size are set to 0. However, this means that size and count are unbounded, and this is not the default behavior.
Fixes: https://github.com/containers/podman/issues/25473
Fixes: https://issues.redhat.com/browse/RHEL-83262
```release-note
Fixed a bug where the default values of the HealthCheck logs were not set correctly, causing the logs to have no restrictions. 
```
> Fix HealthCheck log destination, count, and size defaults

- .packit.yaml
Silly mistake on my end, of course we want to build on both arches.
Fixes: 9eb4d27c5c ("packit: only build F41+")
```release-note
None
```
> [skip-ci] packit: fix missing fedora arches

- libpod/container_copy_common.go
- libpod/container_internal_common.go
- test/e2e/cp_test.go
Have one function without a `defer lock.unlock()` as one of the commands in it calls a function that also takes the same lock, so the unlock has to happen prior to function completion. Unfortunately, this is prone to errors, like the one here: I missed a case, and we could return without unlocking, causing a deadlock later in the cleanup code as we tried to take the same lock again.
Fix is simple enough - add the missing unlock.
Fixes #25585
```release-note
Fixed a bug where the `podman cp` command could deadlock when copying into a non-empty volume on a container that is not running ([#25585](https://github.com/containers/podman/issues/25585)).
```
> Fix a potential deadlock during `podman cp`

- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/container_internal.go
- libpod/events.go
- libpod/healthcheck.go
- libpod/options.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/generate.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/pod_create.go
- pkg/specgen/specgen.go
- test/apiv2/20-containers.at
- test/system/220-healthcheck.bats
- test/upgrade/test-upgrade.bats
This PR changes `HealthLogDestination`, `HealthMaxLogCount`, `HealthMaxLogSize` of `ContainerMiscConfig` to pointers.  And it removes omitempty from `HealthLogDestination`, `HealthMaxLogCount`, `HealthMaxLogSize` of `SpecGenerator.ContainerHealthCheckConfig`. 
GoLang sets unset values to the default value of the type. This means that the destination of the log is an empty string and the count and size are set to 0. However, this means that size and count are unbounded, and this is not the default behavior.
Fixes: https://github.com/containers/podman/issues/25473
Fixes: https://issues.redhat.com/browse/RHEL-83262
Fixes: https://issues.redhat.com/browse/RHEL-83557
Fixes: https://issues.redhat.com/browse/RHEL-83556
(cherry picked from commit fff42ac232ecdece93b0ea6053a84f5c3318ea72) …
> [v5.4] Fix HealthCheck log destination, count, and size defaults

- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/events.go
- libpod/healthcheck.go
- libpod/options.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/domain/entities/pods.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/abi/generate.go
- pkg/specgen/generate/container.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/pod_create.go
- pkg/specgen/specgen.go
- test/apiv2/20-containers.at
- test/system/220-healthcheck.bats
- test/upgrade/test-upgrade.bats
This PR changes `HealthLogDestination`, `HealthMaxLogCount`, `HealthMaxLogSize` of `ContainerMiscConfig` to pointers.  And it removes omitempty from `HealthLogDestination`, `HealthMaxLogCount`, `HealthMaxLogSize` of `SpecGenerator.ContainerHealthCheckConfig`. 
GoLang sets unset values to the default value of the type. This means that the destination of the log is an empty string and the count and size are set to 0. However, this means that size and count are unbounded, and this is not the default behavior.
Fixes: https://github.com/containers/podman/issues/25473
Fixes: https://issues.redhat.com/browse/RHEL-83558
(cherry picked from commit fff42ac232ecdece93b0ea6053a84f5c3318ea72)
```release-note
Fixed a bug where the default values of the HealthCheck logs were not set correctly, causing …
```
> [v5.2-rhel] Fix HealthCheck log destination, count, and size defaults

- rpm/podman.spec
podman-5.4.1 as found in rawhide , builds and seems to work without issues on currently available riscv64 machines
No
```release-note
```
> [skip-ci] RPM: Add riscv64 to ExclusiveArch-es

- docs/source/markdown/podman-system-df.1.md
- go.mod
- go.sum
- test/system/030-run.bats
- test/system/320-system-df.bats
- test/system/400-unprivileged-access.bats
- vendor/github.com/containers/common/libimage/disk_usage.go
- vendor/github.com/containers/common/libimage/layer_tree.go
- vendor/modules.txt
```release-note
Fixed a bug in podman system df where a negative size for RECLAIMABLE was shown.
```
> Fix system df negative reclaimable size bug

- libpod/container_internal_linux.go
- test/e2e/play_kube_test.go
when the code was first added, there was no securejoin.OpenInRoot(). Since there is a function already provided by a dependency and already used in libpod, replace the custom code with securejoin.OpenInRoot().
The new version does not report a symlink that points outside the root, but it is still resolved relative to the specified mountpoint, since that is the openat2 semantic.  It does not affect the security of the function.
```release-note
None
```
> container: replace code with securejoin.OpenInRoot()

- pkg/machine/e2e/cp_test.go
Explicitly close file to avoid machine e2e test to fail on CI from time to time.
Fixes #25614
```release-note
None
```
> Fix flake on machine cp e2e test

- .cirrus.yml
- contrib/cirrus/setup_environment.sh
This RHEL release branch has a very short lifespan remaining, but the original date set in the CI scripts was wrong.  Fix that and reduce CI to the absolute bare-minimum needed for any remaining backports.
```release-note
None
```
> [v3.2.3-rhel] Update EOL date + Simplify CI

- cmd/podman/common/create.go
- cmd/podman/containers/update.go
- docs/source/markdown/options/env.update.md
- docs/source/markdown/options/unsetenv.update.md
- docs/source/markdown/podman-update.1.md.in
- libpod/container_api.go
- libpod/container_internal.go
- pkg/api/handlers/compat/containers.go
- pkg/api/handlers/libpod/containers.go
- pkg/api/handlers/types.go
- pkg/bindings/containers/update.go
- pkg/domain/entities/types/containers.go
- pkg/domain/infra/abi/containers.go
- test/e2e/update_test.go
The --env is used to add new environment variable to container or override the existing one. The --unsetenv is used to remove the environment variable.
It is done by sharing "env" and "unsetenv" flags between both "update" and "create" commands and later handling these flags in the "update" command handler.
The lists of environment variables to add/remove are stored in newly added variables in the ContainerUpdateOptions.
The Container.Update API call is extended to take these two lists of environment variables and handle them in the internal update method using the envLib package.
Fixes: #24875
```release-note
The `podman update` command now supports `--env` and `--unsetenv` arguments.
```
> Add --env and --unsetenv to podman update.

- go.mod
- go.sum
- vendor/github.com/containers/common/libimage/copier.go
- vendor/github.com/containers/common/libimage/import.go
- vendor/github.com/containers/common/libimage/load.go
- vendor/github.com/containers/common/libimage/manifest_list.go
- vendor/github.com/containers/common/libimage/pull.go
- vendor/github.com/containers/common/libimage/push.go
- vendor/github.com/containers/common/libimage/save.go
- vendor/modules.txt
> vendor: bump c/common to `dbeb17e40c80`

- contrib/cirrus/win-lib.ps1
Setting the arch to amd64 breaks arm64 windows builds.
```release-note
None
```
> Do not set arch for windows to amd64

- docs/source/markdown/options/health-timeout.md
Fixes: https://issues.redhat.com/browse/RHEL-84682
```release-note
None
```
> Clarify behavior of --health-timeout in man page

- test/buildah-bud/apply-podman-deltas
Following test needs unique cache in TMPDIR so cache of this test does not conflicts with other tests however for this specific test there is no convenient way to pass custom TMPDIR.
Skipping this as test similar to this already exists in tests/bud.bats but covers `--mount=type=cache,sharing=locked`
Read more discussion here: https://github.com/containers/podman/issues/25414
Closes: https://github.com/containers/podman/issues/25414
```release-note
None
```
> buildah-bud,remote: skip `bud-with-mount-cache-like-buildkit` for `podman-remote`

- libpod/kube.go
- test/e2e/generate_kube_test.go
Hi,
While learning about using Podman to run services, I've realized that trying to generate the Pod.yaml for `--mount`  of volume type using SubPath would not pass that information to the generated Pod. Just a one liner, decided to write the test just to be sure we don't have regressions in the future.
```
$ podman run --rm -it \
--mount type=volume,source=test,volume-subpath=/etc/etcfile,target=/etc/file1 \
--mount type=volume,source=test,volume-subpath=/var/varfile,target=/var/file2 \
docker.io/library/httpd
$ podman generate kube $ctrl
```
The diff will add the SubPath now
```diff
volumeMounts:
- mountPath: /etc/file1
name: test-pvc
+       subPath: /etc/etcfile
- mountPath: /var/file2
name: test-pvc
+       subPath: /var/varfile
volumes:
- name: test-pvc
```
Note that `kube play` can …
> Add volume SubPath in generate kube

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/retry.build
- test/e2e/quadlet/retry.container
- test/e2e/quadlet/retry.image
- test/e2e/quadlet_test.go
This commit adds new Retry= and RetryDelay= options to quadlet.go which result in --retry and --retry-delay usage in podman run command.
This allows configuring the retry logic in .container systemd files.
Fixes: #25109
```release-note
The Retry= and RetryDelay= options are now supported in the systemd .container files.
```
> Add support for Retry= and RetryDelay= to Podman Quadlet.

- pkg/domain/infra/abi/containers.go
- pkg/specgen/generate/container.go
- test/e2e/container_clone_test.go
This PR fixes a bug where the Healthcheck was not copied to the cloned container.
Fixes: https://github.com/containers/podman/issues/21630
Fixes: https://issues.redhat.com/browse/RUN-2632
```release-note
Fixed: `podman container clone` now correctly copies health check settings.
```
> Fix container clone with configured Healthcheck

- docs/source/markdown/podman-kube-play.1.md.in
- libpod/define/annotations.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgenutil/specgen.go
- test/e2e/play_kube_test.go
This commit adds new annotation called:
io.podman.annotations.pids-limit/$ctrname
This annotation is used to define the PIDsLimit for a particular pod. It is also automatically defined when newly added --pids-limit option is used.
Fixes: #24418
```release-note
The `podman kube play` now supports the `--pids-limit` command line option to define the PIDsLimit for pod.
```
> Add support for --pids-limit in podman kube play.

- .cirrus.yml
- contrib/cirrus/win-podman-machine-test.ps1
- pkg/machine/e2e/init_test.go
This one has two local NVMe's attached so we should be able to use fast
local storage to hopefully speed the test up. The NVMe are not mounted
by default so we have to format and mount them. I have choosen Z as
drive letter as I guess it seems most likely that it is free.
Then we need to set the TMPDIR envs to make the machine tests use the
new location.
```release-note
None
```
> CI: use z1d instance for windows machine testing

- pkg/api/handlers/libpod/pods.go
```go
if err := json.NewDecoder(r.Body).Decode(&psg); err != nil {
utils.Error(w, http.StatusInternalServerError, fmt.Errorf("%v: %w", failedToDecodeSpecgen, err))
return
}
if err != nil {
utils.Error(w, http.StatusInternalServerError, fmt.Errorf("%v: %w", failedToDecodeSpecgen, err))
return
}
```
```release-note
delete unnecessary err check in create pod 
```
> fix remove unnecessary err check

- pkg/machine/e2e/basic_test.go
- pkg/specgen/volumes.go
- pkg/specgen/volumes_linux_test.go
- pkg/specgen/volumes_windows_test.go
- test/e2e/run_volume_test.go
Fixes https://github.com/containers/podman/issues/25218
```release-note
None
```
cc @l0rd
> fix: mounting issue with single character volume on windows

- .packit.yaml
ELN and CS buildroots currently have an older golang build causing lots of annoyance.
Ref: https://github.com/containers/podman/pull/25694#discussion_r2016587671
This commit disables those jobs until golang is updated on them.
```release-note
None
```
> [skip-ci] Packit: Ignore ELN and CS jobs

- .cirrus.yml
- contrib/cirrus/win-podman-machine-test.ps1
- test/compose/slirp4netns_opts/setup.sh
- test/e2e/common_test.go
- test/e2e/pod_create_test.go
- test/system/252-quadlet.bats
- test/system/500-networking.bats
Backports of
https://github.com/containers/podman/pull/25561
https://github.com/containers/podman/pull/25658
https://github.com/containers/podman/pull/25673 (Only one commit because the machine test does not exist here)
These should result in less flakes and faster windows machine testing so the next release should be able to get out a bit faster.
Also the ncat changes are needed to pass test in rawhide so we need them for gating as well.
```release-note
None
```
> [v5.4] some CI backports + test fixes for rawhide

- test/system/030-run.bats
Fix issue with 030-run test on systems with runc on openSUSE Tumbleweed 20250326 with podman 5.4.1 & runc 1.2.5.
```
#not ok 122 [030] podman run - no entrypoint
#
```
> test: Fix runc error message

- cmd/quadlet/main.go
- docs/source/markdown/podman-systemd.unit.5.md
- test/e2e/quadlet/install.container
This adds support for the UpheldBy option in quadlet files. The UpheldBy option is the counterpart to the Upholds option added in systemd v249 and is similar to the existing WantedBy and RequiredBy options.
See https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Upholds=.
```release-note
Quadlet files now support the `UpheldBy` key in the `Install` section.
```
> quadlet: add support for the UpheldBy option in the Install section

- cmd/podman/root.go
- docs/source/markdown/podman.1.md
- libpod/container_internal_common.go
- libpod/options.go
- pkg/domain/entities/engine.go
- pkg/domain/infra/runtime_libpod.go
- pkg/specgen/generate/config_freebsd.go
- pkg/specgen/generate/config_linux.go
- pkg/specgen/generate/oci_freebsd.go
- pkg/specgen/generate/oci_linux.go
- test/e2e/run_device_test.go
Based on PR #21448. I've just fixed the propagation of --cdi-spec-dir to container image and added tests and documentation.
Original PR description:
One of the primary benefits of podman is that its possible run without altering the host system. By allowing cdi directories to be passed via command line it maintains this feature.
I'm particularly interested in running podman in a nix-shell with nvidia GPU passthough. Podman and all its dependencies (including nvidia-container-toolkit) come from nix and the host system again doesn't need altering. The one problem with that right now is that I have to write /etc/cdi/nvidia.yaml to be able to use the GPU. Note that the old nvidia-runtime-hook does not work for my use case (which involves vulkan passthrough).
With this change it will be …
> Add cdi-spec-dir option to top level options

- cmd/podman/containers/logs.go
- cmd/podman/pods/logs.go
- test/e2e/logs_test.go
- test/system/035-logs.bats
Do not use the interspersed option for logs, it is not needed and just restricts valid use cases.
Fixes #25653
```release-note
None
```
> podman logs: allow options after argument

- test/compose/cdi_device/setup.sh
- test/compose/cdi_device/teardown.sh
- test/compose/test-compose
Don't mess with a system dir and some minor test script cleanups, see commits.
```release-note
None
```
> test/compose: use --cdi-spec-dir not /etc/cdi

- docs/source/markdown/options/security-opt.image.md
It seems support was added into Buildah for no-new-privileges [1] however the Podman build documentation was not updated.
Fixes #25731
[1] https://github.com/containers/buildah/commit/d4c661a7746fd8e309bfa0b0b5fd7d13d05846ed
```release-note
None
```
> docs: Update `podman build` security options

- RELEASE_NOTES.md
- libpod/container_copy_common.go
- libpod/container_internal_common.go
- test/e2e/cp_test.go
- version/rawversion/version.go
> Bump to v5.4.2

- docs/source/markdown/podman-build.1.md.in
- docs/source/markdown/podman.1.md
- Fix links to other man-pages in podman-build.1.md.in
- Fix markup and add link to oci-hooks manpage in podman.1.md
```release-note
None
```
> Update links and markup in man pages

- GOVERNANCE.md
- MAINTAINERS.md
- OWNERS
- REVIEWING.md
This is the initial version of the governance model we're looking to implement. It is still very early, and comments and suggestions are very welcome!
DO NOT MERGE THIS until we have a broad agreement that the current version is acceptable.
```release-note
NONE
```
> Add initial draft of Podman project Governance

- .github/workflows/needs-info-labeler.yaml
When a reviewer of an issue determines that an issue is incompleted, a `needs-info` label can be added to the issue.  This will trigger a GH action with an automated response.  The reviewer should also have told the user what is needed or asked a question.  Also, we have no automated way to remove the label when a response is provided, so this still needs to be managed.
```release-note
None
```
> Add autocomment for `needs-info` label

- hack/install_golangci.sh
_(Those used to be separate commits but are now squashed.)_
This will allow to simplify renovate rule at [1].
In golangci-lint v2 they've switched from master to main,
and it's not clear what will happen to master over time,
so let's just switch to main prophylactically.
Instead of relying on an undocumented feature of having BINDIR,
let's use -b option as recommended by the official docs at [2].
Before:
[kir@kir-tp1 podman]$ VERSION=2.0.2 ./hack/install_golangci.sh
golangci-lint has version 2.0.2 built with go1.24.1 from 2b224c2c on 2025-03-25T21:36:18Z
Using existing ./bin/golangci-lint has version 2.0.2 built with go1.24.1 from 2b224c2c on 2025-03-25T21:36:18Z
After:
[kir@kir-tp1 podman]$ VERSION=2.0.2 ./hack/install_golangci.sh
golangci-lint has version 2.0.2 built with go1.24.1 from …
> Assorted minor fixes to hack/install_golangci.sh

- libpod/container_internal.go
- test/e2e/run_test.go
This is related to #23292 and is needed to replace pause image container with pause container based
on the rootfs.
Without this change, the GIDs and UIDs are not mapped in the rootfs container which use overlay if --userns=auto is used. This leads to an error mounting /dev/pts with gid=5, becuase GID 5 simply does not exist in the pause container using rootfs.
All the tests pass with this change, but I have to admit I did not find out why the original code has been introduced.
```release-note
None
```
> Set the IDMappings also when RootfsOverlay is used.

- .cirrus.yml
This shaves off some time from golangci-lint run.
For linux, it's down from 5 to 3 minutes (for the whole task, not just
the golangci-lint runs), and the cache is only ~7MB (according to
golangci-lint, probably uncompressed) or ~2MB (according to cirrus CI,
probably compressed).
For Mac, due to remote build tag we don't lint much so linting takes
less than a minute, so it is not worth optimizing.
For Windows, similar.
```release-note
NONE
```
> cirrus: save/restore golangci-lint cache for linux

- cmd/podman/common/create.go
- cmd/podman/containers/create.go
- cmd/podman/containers/run.go
- docs/source/markdown/options/health-cmd.md
- docs/source/markdown/options/health-interval.md
- docs/source/markdown/options/health-retries.md
- docs/source/markdown/options/health-start-period.md
- docs/source/markdown/options/health-timeout.md
- pkg/specgen/generate/container.go
- test/e2e/healthcheck_run_test.go
This PR fixes overwriting the Healthcheck configuration from the image. If the `--health-cmd` flag is not specified, other flags such as `--health-interval`, `--health-timeout`, `--health-retries`, and `--health-start-period` are ignored if the image contains a Healthcheck. This makes it impossible to modify these Healthcheck configurations when a container is created.
Fixes: https://github.com/containers/podman/issues/20212
Fixes: https://issues.redhat.com/browse/RUN-2629
```release-note
Users can now override HealthCheck information provided via container images.
```
> Fix overwriting the Healthcheck configuration from the image

- docs/source/markdown/options/network.md
First, remove wrong sentence that says ports are forwarded dynamically by default. That is wrong and contradicts what is written below. Second, document that we also set --dns-forward and --map-guest-addr by default. And lastly document the containers.conf field so users know they are not forced to set the options on each command.
```release-note
None
```
> docs: update pasta options description

- Makefile
For some reason, freebsd build was using `seccomp` tag which makes no sense.
Remove it.
Originally part of #25743 
```release-note
NONE
```
> Makefile: exclude seccomp build tag for !linux

- test/system/500-networking.bats
A recent change[1] in netavark makes it so we no longer set the default dns.podman search domain. As such we must no longer test for it.
[1] https://github.com/containers/netavark/pull/1214
```release-note
Podman custom networks when using netavark v1.15+ no longer set the default search domain dns.podman. Queries resolving such names will still work. 
```
> test/system: do not check dns.podman

- libpod/networking_common.go
- test/system/500-networking.bats
Networks are stored in two ways in the DB, first a static network list which holds all the network with its option for the container. Second, the network status which hold the actual network result from netavark but only when the container is running.
If the container is running they must be in sync and podman inspect has checks to ensure that as well it errors out of there is a desync between the two.
As the adding to the db and doing actual networking configuration are diffeent parts it possible that one worked while the other failed which triggers the desync. To avoid this make the network connect/disconnect code more robust against partial failures. When the network calls fail we update the db again to remove/add the network back.
Fixes: https://issues.redhat.com/browse/RHEL-78037 …
> fix network DB desync after failed connect/disconnect

- libpod/container_internal_common.go
- libpod/container_internal_linux_test.go
- test/e2e/run_passwd_test.go
- test/system/030-run.bats
create the /etc/passwd and /etc/group files before any user/group lookup so that the entries added dynamically are found by --user.
Closes: https://github.com/containers/podman/issues/25805
```release-note
Now --user finds groups added by --hostuser
```
> libpod: --user works with  --hostuser entries

- pkg/bindings/containers/update.go
- pkg/bindings/test/containers_test.go
Right now, if you call Update with only part of the options struct added, it panics. This fixes that by only adding them if they are not nil.
<!--
If no, just write `None` in the release-note block below. If yes, a release note
is required: Enter your extended release note in the block below. If the PR
requires additional action from users switching to the new release, include the
string "action required".
For more information on release notes, please follow the Kubernetes model:
https://git.k8s.io/community/contributors/guide/release-notes.md
```release-note
None
```
> Make Go not panic on a partial update

- libpod/container_internal.go
- libpod/oci.go
- libpod/oci_conmon_common.go
- libpod/oci_missing.go
This seems to have been added as part of the cleanup of our handling of OOM files, but code was never added to remove it, so we leaked a single directory with an exit file and OOM file per container run. Apparently have been doing this for a while - I'd guess since March of '23 - so I'm surprised more people didn't notice.
Fixes #25291
Fixes: https://issues.redhat.com/browse/RHEL-86544, https://issues.redhat.com/browse/RHEL-86550
```release-note
None
```
> [v5.4-rhel] Remove persist directory when cleaning up Conmon files

- .github/labeler.yml
- MAINTAINERS.md
- OWNERS
MAINTAINERS.md: sort by role 
This should make it easier to read, most people likely care about the
roles.
---
OWNERS: add nalind
He is a core maintainer and was not listed here by mistake.
---
.github/labeler: add governance label automatically
We don't have anything CI wise to enforce proper reviews for governance
changes but we can easily label a PR so that should raise more
awareness.
```release-note
None
```
> MAINTAINERS.md: sort by role and add nalind to OWNERS

- cmd/podman/root.go
- pkg/domain/entities/engine.go
- test/e2e/run_test.go
This `--config` option was initially added here:
https://github.com/containers/podman/commit/4e4c3e3dbffd6c8fc2c1a8674a581aed61f2d629
Under the hood this simply modifies env to set DOCKER_CONFIG=<passed in string>
The DOCKER_CONFIG env var is used as a directory that contains multiple config files... of which podman and container libs probably only use `$DIR/config.json`.
See: https://docs.docker.com/reference/cli/docker/#environment-variables
The old CMD and help text was misleading... if we point the at a regular file we can see errors like:
```
$ touch /tmp/foo/tmpcr9zrx71
$ /bin/podman --config /tmp/foo/tmpcr9zrx71 build -t foobar:latest
Error: creating build container: initializing source docker://quay.io/centos/centos:stream9: getting username and password: reading JSON file …
```
> cmd: Fix help text. --config specifies a dir not a regular file

- pkg/domain/entities/pods.go
- pkg/specgen/podspecgen.go
No change in functionality.
I might be missing something here, but it appears to be either unfinished or abandoned.
Fixes: bbd085ad1e ("Podman Pod Create --cpus and --cpuset-cpus flags", PR #10716)
Fixes: 2d86051893 ("Pod Device-Read-BPS support", PR #11686)
Cc @cdoern 
```release-note
NONE
```
> Remove unused code and data structures

- cmd/podman/machine/init.go
- pkg/machine/e2e/init_test.go
When trying to initialize a machine with more memory that the system has we were outputting an error message in the wrong unit.  It should have been in MB and B. This was found as part of #25803 but is not the solution for that issue.
```release-note
Fixed error with `podman machine init` where the memory was reported in the wrong unit.
```
> Correct units in init error message

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/reloadboth.container
- test/e2e/quadlet/reloadcmd.container
- test/e2e/quadlet/reloadsignal.container
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet - add support for adding ExecReload command by either sending a signal or running exec
```
Resolves: #22036
> Quadlet - Add support for adding ExecReload command

- cmd/podman/containers/cp.go
- pkg/copy/fileinfo.go
- pkg/copy/parse.go
- pkg/machine/e2e/basic_test.go
- pkg/machine/e2e/cp_test.go
This PR fixes a handful of Windows path bugs in `podman container cp` that prevented copying files from (or to) a Windows host.
* The Windows drive letter was being treated as a container ID/name, which is fixed by using `filepath.IsAbs` to determine if a given path is an absolute path on the system (on Windows, this is true for paths starting with a single drive letter and a colon).
* The code used `/` as the root folder path, even on Windows (should be `<drive letter>:\` (i.e. `C:\`), which caused `copier` to reject the given path. This was fixed by depending on the behavior of `filepath.VolumeName` and `os.PathSeparator` to build the correct root path for a given OS.
* There was logic that was hardcoded to use `/` as the path separator rather than `os.PathSeparator` which caused path …
> Fix windows path handling in `podman cp`

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/delete.network
- test/e2e/quadlet_test.go
- test/system/252-quadlet.bats
Yes
```release-note
Quadlet - Allow deleting the network when stopping the service
```
Resolves: #23678
> Quadlet - allow deleting the network when stopping the service

- GOVERNANCE.md
Firstly, include both subprojects in the model and link to them. Ensures complete clarity on what is part of the Podman Project in CNCF.
Secondly, add that Community Managers are expected to take notes on Core Maintainer meetings and make those notes available to the public.
Requires a 2/3 vote of Core Maintainers to merge.
```release-note
NONE
```
> Two small updates to the Governance model

- Makefile
- pkg/api/handlers/compat/events.go
- pkg/api/handlers/libpod/pods.go
- pkg/bindings/manifests/manifests.go
Fixes three new issues found by nilnesserr.
```release-note
None
```
> update golangci-lint to v2.1.1

- libpod/container_internal_linux.go
The openDirectory function is missing the unix.O_CLOEXEC flag. As a result, this file descriptor can leak into the aardvark-dns process which can then block the umount of rootfs - in this case, the umount fails with "Device or Resource busy" error message.
This commits adds the unix.O_CLOEXEC to unix.Open call, resulting in this fd to be closed on aardvark-dns exec.
```release-note
None
```
> Fix the fd leaking to aardvark-dns.

- .golangci.yml
- cmd/podman/pods/create.go
- pkg/bindings/containers/term_windows.go
This fixes ~~one~~ two issues caught by staticcheck, and removes two exception presets from .golangci.yml. See commits for details.
Makes sense to merge this one before #25874.
```release-note
none
```
> ci: fix two issues, remove unused exceptions

- docs/source/markdown/options/security-opt.md
Fixes: #25853
The below is found on the matching [systemd docs](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#NoNewPrivileges=) which I don't think applies to Podman. Is it correct to leave it out?
> In case the service will be run in a new mount namespace anyway and SELinux is disabled, all file systems are mounted with MS_NOSUID flag. [...]
>
> Note that this setting only has an effect on the unit's processes themselves (or any processes directly or indirectly forked off them). It has no effect on processes potentially invoked on request of them through tools such as [at(1)](https://man7.org/linux/man-pages/man1/at.1.html), [crontab(1)](https://man7.org/linux/man-pages/man1/crontab.1.html), [systemd-run(1)](https://www.freedesktop.org/software/systemd/man/late …
> docs: Expand description of no-new-privileges

- test/e2e/config_arm64.go
This PR fixes `golangci-lint` on ARM64 machines. 
Fixes:
- `directive `//nolint:revive` is unused for linter "revive" (nolintlint)`
```release-note
None
```
> CI: Fix directive `//nolint:revive` is unused for linter "revive" on ARM

- libpod/container.go
- libpod/container_config.go
- libpod/container_internal_common.go
- libpod/container_validate.go
- libpod/kube.go
- libpod/options.go
- libpod/runtime_ctr.go
- pkg/domain/infra/abi/play.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgen/generate/pause_image.go
- pkg/specgen/generate/pod_create.go
- test/system/010-images.bats
- test/system/020-tag.bats
- test/system/040-ps.bats
- test/system/255-auto-update.bats
- test/system/700-play.bats
- test/system/helpers.bash
This commit removes the code to build a local pause image from the Containerfile and keeps just a code to PullInfraImage.
In case the user-defined infra image is not set, the PrepareInfraSpec is called to find out the catatonit binary and use it using the rootfs with overlay.
This removes the need to build a local pause container image.
The same logic is also applied to createServiceContainer which is originally also based on the pause image.
Fixes: #23292
```release-note
None
```
> Replace podman pause image with rootfs.

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/dependent.container
No
```release-note
None
```
Not adding release notes because this PR is an addition to https://github.com/containers/podman/pull/25899
> Quadlet - support additional systemd unit relationship keys

- test/system/195-run-namespaces.bats
Fix issue with 195-run-namespaces test with runc. When run as rootless, runc issues an extra warning on podman:
https://github.com/opencontainers/runc/issues/4732
Verification run: https://openqa.opensuse.org/tests/5002299/file/podman-bats-user-local.tap
> test: Fix expected output for runc on namespaces

- pkg/api/handlers/compat/containers_create.go
- test/apiv2/20-containers.at
This PR fixes a bug where the Compat API ignores ulimits in rootless mode.
Fixes: https://github.com/containers/podman/issues/25881
```release-note
Fixed a bug where the Compat API API ignores ulimits in rootless mode.
```
> Fix: Compat API in rootless mode ignores ulimits

- GOVERNANCE.md
I noticed that the GOVERNANCE.md file did not have links to the MAINTAINERS.md file.
This change just adds links and does not change any wording.
```release-note
None
```
> [CI:DOCS] Add link to MAINTAINERS.md file in GOVERNANCE.md

- test/system/161-volume-quotas.bats
- test/system/520-checkpoint.bats
When using a custom --root it will not have the image present and as such cause a pull. We can however use our own local cache if present to avoid the pull if we give the right podman options via _PODMAN_TEST_OPTS.
I saw the volume quota test fail during the pull in openQA thus I noticed this issue.
```release-note
None
```
> test/system: add prefetch users to use cache image

- contrib/pkginstaller/Makefile
```release-note
update vfkit binary to v0.6.1 in macOS installer
```
I built the installer using `make ARCH=aarch64 NO_CODESIGN=1 pkginstaller`
then I was able to init/start a machine
> feat: update vfkit binary to v0.6.1 in macOS installer

- test/buildah-bud/README.md
The README.md in test/buildah-bud had the old directory name for the apply-podman-deltas file.  This change removes the `/` and adds a `-` in that file name.
```release-note
None
```
> [CI DOCS] Touchup buildah-bud README.md

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/hostname.pod
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet Pod - add support for HostName key
```
This PR fixes https://github.com/containers/podman/issues/25639
> Add HostName to quadlet pod

- Makefile
- contrib/pkginstaller/Makefile
- winmake.ps1
Discussion there https://github.com/containers/gvisor-tap-vsock/issues/475
```release-note
None
```
> Use gvisor-tap-vsock version from go.mod file

- cmd/podman/artifact/add.go
- docs/source/markdown/podman-artifact-add.1.md.in
- pkg/domain/entities/artifact.go
- pkg/domain/infra/abi/artifact.go
- pkg/libartifact/store/store.go
- pkg/libartifact/types/config.go
- test/e2e/artifact_test.go
in #25884, it was pointed out that the standard detection used to determine the artifact's file type can be wrong.  in those cases, it would be handy for the user to be able to override the media type of the layer.  as such, added a new option called `--file-type`, which is optional, and allows users to do just that.
`podman artifact add --file-type text/yaml
quay.io/artifact/config:latest ./config.yaml `
Fixes: #25884
```release-note
Added `file-type` option to allow override of an artifact's file type (media type)
```
> Add ability to set layer media type for artifacts

- Makefile
- contrib/pkginstaller/Makefile
```release-note
None
```
Trying to build the podman installer after https://github.com/containers/podman/pull/25688 I noticed that the gvproxy is not downloaded (there is a v in the VERSION property then as in the URL another v was added, it was fetching a "not found" content binary.
I saw that we should use another script, so switch to the new script. Need to add GO variable at the beginning of the Makefile as well to reuse the same script
I also tested `make win-gvproxy`
```
mkdir -p bin/windows/
curl -sSL -o bin/windows/gvproxy.exe --retry 5 https://github.com/containers/gvisor-tap-vsock/releases/download/v0.8.5/gvproxy-windowsgui.exe
curl -sSL -o bin/windows/win-sshproxy.exe --retry 5 https://github.com/containers/gvisor-tap-vsock/releases/download/v0.8.5/win-sshproxy.exe
```
and it …
> chore: use another script to get the version of gvproxy + fix download link

- hack/bats
Allow specifying `PODMAN_ROOTLESS_USER` when calling `hack/bats` as root, otherwise it gets assigned `root` and fails.
Verification run: https://openqa.opensuse.org/tests/5014237#external
> hack/bats: Allow specifying PODMAN_ROOTLESS_USER

- hack/bats
Fix `hack/bats` to allow specifying multiple tests.
Verification run:
- https://openqa.opensuse.org/tests/5014462/logfile?filename=serial_terminal.txt
- https://openqa.opensuse.org/tests/5014462/logfile?filename=serial_terminal_user.txt
The above VR calls `hack/bats` with `--root`, `--rootless` & `--remote` on `120-load 195-run-namespaces`.
```release-note
NONE
```
> hack/bats: Fix to allow multiple tests

- hack/bats
Fix `hack/bats` to accept `--tap` (`-t`) option so we can get TAP output from bats.
In our tests we have to [patch it](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/containers/bats/podman.pm#L91) and I think this can be avoided. 
```release-note
None
```
> hack/bats: Pass --tap (-t) option to bats

- cmd/quadlet/main.go
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/label.pod
- test/e2e/quadlet_test.go
Yes
```release-note
Quadlet Pod - add support for Label key
```
Fixes #25961
> Add Label to quadlet pod

- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/system/045-start.bats
This looks like debug leftover, in any case this is not an error so simply remove the line.
Fixes #25965
```release-note
Fixed a bug where podman-remote start --attach would print a bogus error when the container was created with --rm.
```
> remote: don't print bogus error when starting container attached

- pkg/util/mount_opts.go
- pkg/util/utils_test.go
- test/e2e/play_kube_test.go
- test/python/docker/compat/test_containers.py
- test/system/252-quadlet.bats
Podman is currently using the default mount option for the volumes as `rw` if not specified by the user. This can lead to the permission issues if the mount point is `ro`. In this PR, I removed setting up any default mount flag, so the underlying run time can handle it.
```release-note
None
```
> Remove using `rw` as a default mount option

- MAINTAINERS.md
This PR nominates Mohan Boddu as a new Community Manager for the Podman Container Tools project. Merges with 4 Core Maintainer LGTMs, with mine assumed as I opened the PR.
@baude @Luap99 @mtrmac @giuseppe @nalind PTAL
```release-note
NONE
```
> Add Mohan Boddu as community manager

- pkg/machine/e2e/basic_test.go
The test is checking that named volumes could be used. FS mount is not needed and there is no code testing anything around it.
This makes this test pass in env, where virtiofs is not available for QEMU.
```release-note
None
```
> Disable FS mount in volume only test

- pkg/systemd/quadlet/podmancmdline.go
- pkg/systemd/quadlet/quadlet.go
No
```release-note
None
```
No new tests were added on purpose. The change is supposed to be seamless to the tests
> Quadlet - use helper function for handling key=val type keys

- OWNERS
The `OWNERS` file contains an incorrect GitHub handle `honny1`. The correct GitHub handle is `Honny1`. This causes `/approve` comments to have no effect on PR. The `MAINTAINERS.md` file contains the correct GitHub handle.
```release-note
None
```
> OWNERS: Fix GitHub handle

- pkg/api/handlers/libpod/containers_create.go
- test/apiv2/20-containers.at
- test/system/030-run.bats
The JSON decoder correctly cannot decode (overflow) negative values (e.g., `-1`) for fields of type `uint64`, as `-1` is used to represent `max` in `POSIXRlimit`. To handle this, the request body is first decoded into a map to process the `r_limits` field separately. Logic has been added to parse the `soft` and `hard` limits, casting `-1` to `uint64` to represent `max` while rejecting other invalid negative values.
This approach ensures compatibility with the Podman CLI and remote API, which already handle `-1` by casting it to `uint64` (`uint64(-1)` equals `MaxUint64`) to signify `max`.
Fixes: https://issues.redhat.com/browse/RUN-2859
Fixes: https://github.com/containers/podman/issues/24886
>  I'm not sure how to test the `max` value of `ulimit` for rootless APIs. Because it sets the …
> Fix handling of "r_limits" in Podman REST API /libpod/containers/create

- contrib/win-installer/podman-msihooks/check.c
Fixes compilation errors with GCC 15.
GCC 15 defaults to C23 standard, which introduced new keywords (including `bool`): https://gcc.gnu.org/gcc-15/porting_to.html#c23
Alternative fix would be to change build script to use lower C standard version.
It seems that at some point this file might be removed, because installer would not be responsible for installing dependencies anymore, but for now this fix would allow to build Podman installer with msys2 tooling (they upgraded
GCC to 15).
```release-note
None
```
> Update "check.c" to be C23 compliant

- pkg/bindings/images/pull.go
- pkg/bindings/images/push.go
In the case of an Decoder error which is not EOF we loop forever, as the
Decoder stores some errors each next Decode() call will keep returning
the same error. Thus we loop forever until we run out of memory as each
error was stored in pullErrors array as described in [1].
Note this does not actually fix whatever causes the underlying
connection error in the issue, it just fixes the loop/memory leak.
---
pkg/bindings: wrap image push decode error
If this fails we should know exactly what failed. The underlying
connection error might just be unexpected EOF or somthing which is not
helpful.
```release-note
Fixes potential infinite loop/memory leak in podman-remote pull when the server connection is closed unexpectedly 
```
> pkg/bindings: fix infinite loop/memory leak in image pull

- version/rawversion/version.go
- version/version.go
Also remove the outdated comment that said to update the version in the README.md file, that is no longer there since commit 8e7f98ae65 ("docs(readme): add status badges and remove hardcoded release info").
```release-note
None
```
> bump main to 5.6-dev

- Makefile
Otherwise we evaluate NATIVE_GOOS before it is set, which breaks the FreeBSD build.
Fixes: #26006
```release-note
None
```
> Makefile: move some Go-related variable definitions up

- Makefile
- hack/btrfs_tag.sh
- pkg/machine/e2e/README.md
- rpm/podman.spec
- winmake.ps1
c/storage no longer uses this tag after
https://github.com/containers/storage/pull/2308.
```release-note
None
```
> Stop setting btrfs_noversion build tag

- cmd/quadlet/main.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basepodman.container
- test/e2e/quadlet/basic.container
- test/e2e/quadlet/basic.pod
- test/e2e/quadlet/reloadcmd.container
- test/e2e/quadlet/reloadsignal.container
Yes
```release-note
Quadlet - remove the usage of cid and podid, stop the container or pod by their names instead
```
> Quadlet - remove the usage of cid and podid for container and pod files

- pkg/machine/ignition/ignition.go
- pkg/machine/ignition/ignition_linux.go
In cases where systemd was not available, podman machine was erroring out using timedatectl (it requires systemd).  on other providers like windows, we don't do any timezone detection so it seems valid to return a "" for timezone.  This fixes the first problem described #25950.
Fixes: https://github.com/containers/podman/issues/25950
```release-note
None
```
> Do not error on tz detection

- contrib/cirrus/setup_environment.sh
- libpod/container_inspect.go
- libpod/container_inspect_linux.go
- pkg/util/utils_linux.go
- pkg/util/utils_unsupported.go
- test/apiv2/20-containers.at
- test/e2e/common_test.go
- test/e2e/run_test.go
- test/e2e/update_test.go
- test/system/030-run.bats
- test/system/280-update.bats
change the device used for block I/O limits (read/write BPS and IOPS).
Since `/dev/zero` is not a block device, it's unsuitable for testing cgroup controls designed for block devices.
```release-note
None
```
> test: use block devices for I/O limit tests

- .github/workflows/machine-os-pr.yml
- RELEASE_NOTES.md
- pkg/machine/shim/host.go
Release bump will be done separately
```release-note
NONE
```
> Update release notes for v5.5.0-rc2

- cmd/podman/machine/init.go
- cmd/podman/machine/list.go
- docs/source/markdown/podman-machine-init.1.md.in
- docs/source/markdown/podman-machine-list.1.md.in
- pkg/domain/entities/machine.go
- pkg/machine/config.go
- pkg/machine/define/initopts.go
- pkg/machine/e2e/config_init_test.go
- pkg/machine/e2e/init_test.go
- pkg/machine/ignition/ignition.go
- pkg/machine/shim/host.go
- pkg/machine/vmconfigs/config.go
- pkg/machine/vmconfigs/machine.go
Add `--swap` argument to `podman machine init` command.
Passing an int64 value to this flag will trigger the Podman machine
ignition file to be generated with a zram-generator.conf file containing
the --swap value as the zram-size argument.
This file is read by the zram-generator systemd service on boot
resulting in a zram swap device being created.
Fixes: https://github.com/containers/podman/issues/15980
```release-note
Add new --swap argument to `podman machine init` command to enable and configure swap
```
> feat: Add support for configuring swap in Podman machine

- contrib/win-installer/build.ps1
- contrib/win-installer/podman-setup.wixproj
- contrib/win-installer/podman.wixproj
- contrib/win-installer/podman.wxs
- winmake.ps1
Winmake could only build AMD64 artifacts (podman-remote, gvproxy, win-sshproxy, podman.msi and podman-setup.exe).
This commit makes the necessary change to winmake so that it:
1) builds ARM64 artifacts when executed on arm64
2) cross-compiles to ARM64/AMD64 with the  `-architecture` (or `-arch`) parameter
It depends on https://github.com/containers/podman/pull/26023, which removes the need to build `check.c` code (which is not used anyway).
```release-note
None
```
> Update winmake.ps1 to build arm64 artifacts

- pkg/machine/e2e/init_test.go
- pkg/machine/ignition/ignition.go
- pkg/machine/ignition/ignition_linux.go
pkg/machine: do not add broken localtime symlink
The timezone might be empty so the zoneinfo link would then be invalid.
---
pkg/machine: properly setup zoneinfo symlink
If you run timedatectl inside it will not show the correct timezone, it
seems systemd really wants a relative link which is also documented by
coreos[1]. Also we can just use path.Join() directly and don't have to
convert the path again on windows.
[1] https://docs.fedoraproject.org/en-US/fedora-coreos/time-zone/#_setting_the_time_zone_via_ignition
---
pkg/machine: rework getLocalTimeZone on linux
Get the timezone off the localtime symlink like systemd does it.
It is more efficient then fork/exec another command for it that may or
may not exits and the /etc/timezone files doesn't exist on most distros
so that is not a …
> pkg/machine: more timezone fixes

- pkg/api/handlers/compat/containers.go
- test/apiv2/20-containers.at
Fixes https://github.com/containers/podman/issues/25851
```release-note
None
```
> update podman socket output to include also exposed ports

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.pod
Yes
```release-note
Quadlet - Pod name is defined using the generated service name as documented
```
Resolves: #26062
> Quadlet - fix pod name to depend on the name of the generate service

- .github/workflows/release.yml
- Makefile
- contrib/win-installer/build.ps1
- contrib/win-installer/process-release.ps1
- winmake.ps1
Updates that are necessary to include the Windows arm64 installer in the release process.
The PR is split into 3 commits:
- an important fix to the `ps1` scripts to pick the right zip file (amd64/arm64) based on the value of `$PODMAN_ARCH`
- updates to the `Makefile` to build the `windows_arm64.zip` as part of `release-artifacts`
- updates to the `release` GitHub workflow to build and upload both AMD64 and ARM64 Windows installers
NOTE: to cherry-pick this to the 5.5 branch, we also need #26048 and #26023
```release-note
None
```
> Release win arm64 artifacts

- cmd/podman-wslkerninst/main.go
- pkg/machine/e2e/config_windows_test.go
- pkg/machine/e2e/init_windows_test.go
- pkg/machine/wsl/machine.go
- pkg/machine/wsl/stubber.go
- pkg/machine/wsl/wutil/wutil.go
None
```release-note
Podman on Windows now prefers the WSL executable in “C:\Program Files\Windows Subsystem for Linux\wsl.exe” over the one in WindowsApps, avoiding common “access denied” issues.
```
According to issue https://github.com/containers/podman/issues/25787 podman is trying to use WindowsApps wsl.exe first, but that one can have access issues
We can first search on Program Files for the proper .exe for wsl, this corrects issues with WindowsApps folder executables not being accessible
> Take WSL path from PATH instead of forcing it to WindowsApps

- cmd/podman/common/create.go
- docs/source/markdown/options/health-timeout.md
- libpod/container_exec.go
- libpod/define/errors.go
- libpod/healthcheck.go
- libpod/oci_conmon_exec_common.go
- test/e2e/healthcheck_run_test.go
Previously, the HealthCheck exec session would not terminate on timeout, allowing the healthcheck to run indefinitely.
Because Docker does that, Podman should kill the HealthCheck when it reaches the timeout.
Fixes: https://issues.redhat.com/browse/RHEL-86096
Depends on: https://github.com/containers/podman/pull/25906
```release-note
Fixed a bug where healthchecks exceeding their timeout were not properly terminated; they now receive SIGTERM then SIGKILL, aligning with Docker and preventing indefinite execution.
```
> Fix: Ensure HealthCheck exec session terminates on timeout

- pkg/specgenutil/specgen.go
- test/e2e/run_test.go
This fixes an issue where multiple paths separated by a colon were treated as a single path, contrary to what docs say and unlike how mask option works.
```release-note
Fixed a bug where multiple paths could not be set in --security-opt=unmask
```
> Fix parsing of paths for unmask

- docker/podman-docker.sh
Error: SHELLCHECK_WARNING (CWE-156): [#def2]
/etc/profile.d/podman-docker.sh:4:10: warning[SC2046]: Quote this to prevent word splitting.
2|
3|   if [ -z "${DOCKER_HOST-}" ]; then
4|->     if [ $(id -u) -eq 0 ]; then
5|   	export DOCKER_HOST=unix:///run/podman/podman.sock
6|       else
Resolves: https://openscanhub.fedoraproject.org/task/52458/log/podman-5.4.2-1.fc43/scan-results.html#def2
```release-note
None
```
> Fix a shellcheck warning about word splitting

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.pod
Update the docs to reflect the default naming of resources
Yes
```release-note
Quadlet - do not use systemd specifier in pod names
```
Resolves: https://github.com/containers/podman/issues/26105
> Quadlet - restore pod name to not use systemd specifiers

- contrib/pkginstaller/Makefile
Bump the bundled krunkit version from 0.2.0 to 0.2.1.
cc/ @jakecorrenti 
```release-note
Bump the bundled krunkit version from 0.2.0 to 0.2.1.
```
> Bump bundled krunkit to 0.2.1

- go.mod
- go.sum
- vendor/github.com/ebitengine/purego/dlfcn.go
- vendor/github.com/ebitengine/purego/dlfcn_darwin.go
- vendor/github.com/ebitengine/purego/internal/fakecgo/symbols.go
- vendor/modules.txt
Some changes in go broke purego and that causes a compile error on macos. This update fixes it.
```release-note
Fixed a compile error on macos with go 1.24.3. 
```
> fix macos compile issue with go 1.24.3

- cmd/podman/volumes/prune.go
- libpod/container_internal_common.go
- libpod/runtime_pod_common.go
- pkg/domain/infra/abi/images.go
- pkg/machine/ocipull/source.go
The conditions are always true so they can be removed. And in the case of exportCheckpoint() the scope means addToTarFiles was overwritten and thus when it looped over it later the slice was always empty.
```release-note
None
```
> fix issues found by nilness

- pkg/specgenutil/util.go
- test/system/030-run.bats
- test/system/500-networking.bats
- test/system/helpers.bash
When podman restarts config values within the Engine are lost. Add --hook-dirs arguments as appropriate to the cleanup command so that hooks are preserved on restarts due to the on-restart setting
Fixes: #17935
I've confirmed this works with my reproducer, and it's probably the smallest change that'd work for us so opening PR with that for feedback.
Thanks!
```release-note
Fix hooks not being run properly after first restart if a non-default --hooks-dir setting was used
```
(happy to remove this note as I don't think it's a critical bug, but it's technically user-facing so wrote it in doubt)
> podman: remember hooks-dir on restarts

- pkg/api/handlers/compat/containers.go
- pkg/api/handlers/compat/containers_create.go
- test/apiv2/python/rest_api/test_v2_0_0_container.py
```release-note
compat: POST /containers/create accepts HostConfig.CgroupnsMode
```
@Luap99 same here, I think I need some guidance with testing. (works locally though)
> compat: Add CgroupnsMode to POST /containers/create

- cmd/podman/machine/cp.go
- cmd/podman/machine/ssh.go
- pkg/machine/hyperv/volumes.go
- pkg/machine/os/machine_os.go
- pkg/machine/proxyenv/env.go
- pkg/machine/qemu/stubber.go
- pkg/machine/shim/host.go
- pkg/machine/shim/networking.go
- pkg/machine/ssh.go
- pkg/machine/update.go
... and warn loudly against generalization.
Should not change behavior.
```release-note
None
```
An outcome of #26087 .
> Be explicit about ssh configs suitable only for localhost

- libpod/util.go
- libpod/util_test.go
The count function for / and /proc results in the same value so the order is not guaranteed. We must ensure that a / mount is always first in the spec so that other mounts are not overshadowed by it.
Fixes: #26161
```release-note
Fixes a bug when mounting a volume to / where the mount order of the volumes was not correct and it would overmount important directories such as /proc causing start and/or runtime failures.
```
> libpod: fix mount order for "/" volume

- CONTRIBUTING.md
- pkg/api/handlers/compat/containers.go
- test/apiv2/20-containers.at
This mirrors the conversion currently being done in `LibpodToContainer` into `LibpodToContainerJSON`, converting podman style statuses to docker style statuses as defined in their OpenAPI definition:
https://docs.docker.com/reference/api/engine/version/v1.49/#tag/Container/operation/ContainerInspect
Fixes: #17728
Fixes: https://github.com/containers/podman/issues/17728
```release-note
Fixed a bug where the Compat endpoints for Containers would return `ContainerState.Status` using podman statuses instead of docker statuses (#17728).
```
> compat: fix ContainerState.Status JSON values

- .packit.yaml
- plans/system.fmf
- plans/tmt.fmf
- plans/toolbox.fmf
- rpm/gating.yaml
- rpm/podman.spec
- test/tmt/system.fmf
- test/tmt/system.sh
- test/tmt/tmt.fmf
This commit introduces TMT test jobs triggered via packit to run system tests on testing-farm infrastructure. Tests are run for Fedora 41, 42 and rawhide on x86_64. The same test plan will be reused by Fedora for bodhi, zuul and fedora-ci gating tests. Packit will handle syncing of test plan and sources from upstream to downstream.
TODO:
1. Enable jobs for CentOS Stream and aarch64 envs.
2. Enable separate set of jobs for release branches as they need to be
tested with official distro packages, not with bleeding-edge
packages.
```release-note
None
```
> [skip-ci] TMT: run system tests on Fedora

- docs/source/markdown/podman-container-checkpoint.1.md
runc is not the only runtime supporting --pre-checkpoint
crun commit 0683fec8b mentions
"This commit takes the interface as implemented in runc and implements it for crun. "
See also discussion thread:
https://github.com/containers/podman/discussions/26154
```release-note
None
```
> docs: drop --pre-checkpoint requirement

- test/e2e/run_networking_test.go
A recent change[1] in netavark makes it so we no longer set the default dns.podman search domain. As such we must no longer test for it.
Follow up to 254ab3b90f ("test/system: do not check dns.podman")
[1] https://github.com/containers/netavark/pull/1214
```release-note
None
```
> test/e2e: do not check dns.podman

- RELEASE_NOTES.md
We are apparently really behind, I knew 5.5 wasn't added but apparently 5.4 also wasn't done.
```release-note
NONE
```
> Update release notes on main

- README.md
> README.md: add openssf passing badge

- libpod/container_internal.go
- test/e2e/run_test.go
getAllDependencies() skips recursing into dependencies that are already running, but BuildContainerGraph() expects a *complete* set of inputs and returns an error if any are missing. Thus, podman will fail to start a container with already-running direct dependencies that, in turn, have their own dependencies.
None of the other callers of BuildContainerGraph() omit anything from their list of containers, so follow the same approach here, and just let startNode figure out if a start is actually needed.
Fixes: containers/podman-compose#921
```release-note
Fixed a bug where starting a container with already-running dependencies would fail with `container [...] depends on container [...] not found in input list`.
```
> libpod: Don't exclude running deps from the container graph inputs

- pkg/api/handlers/compat/containers_create.go
- test/apiv2/20-containers.at
Hard coding to none without checking containers.conf is not a good idea as users who liked the previous behavior and the podman default behavior of keeping the hosts entries can no longer do that.
With this commit they can set base_hosts_file = "/etc/hosts" to restore the previous behavior.
Fixes: https://issues.redhat.com/browse/RHEL-92995
```release-note
The docker compat API now respects the base_hosts_file option instead of hard coding it to none.
```
> compat API: respect base_hosts_file containers.conf option

- pkg/machine/e2e/basic_test.go
- pkg/specgenutil/volumes.go
The Windows source folder path was not converted in the corresponding machine folder path when the volume was of type overlay as it does for other bind mount volumes.
Fix #25988
Overlay volumes provide faster I/O access to the local folder (but changes are ephemeral). For example, building podman from sources took 1m30s vs 2m48s with a normal volume.
```pwsh
> .\bin\windows\podman.exe build -t podman-build -f .\.devcontainer\Dockerfile .
> Measure-Command {Start-Process "C:\Users\mario\git\podman\bin\windows\podman.exe" -WorkingDirectory "C:\Users\mario\git\podman\" -ArgumentList "run -ti --rm -v C:\Users\mario\git\podman\:/podman:O -w /podman podman-build make podman" -NoNewWindow -Wait}
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 30
Milliseconds …
```
> Fix overlay volumes on Windows

- libpod/container_internal.go
- libpod/container_internal_common.go
- libpod/runtime_ctr.go
- test/e2e/run_test.go
After the system reboot, the Rootfs for infra-container can be removed. This can happen when it is stored on tmpfs.
This commit recreates the infra-container directory which is used for Rootfs for infra-container before mounting it.
Fixes: #26190
```release-note
Fixes a regression when pod units failed to start with `/run/libpod/infra-container: no such file or directory` error.
```
> Recreate the Rootfs in mountStorage for infra-container.

- libpod/sqlite_state.go
- test/e2e/volume_rm_test.go
Specifically, this does two things:
1. Turn on case-sensitive LIKE queries. Technically, this is not specific to volumes, as it will also affect container and pod lookups - but there, it only affects IDs. So `podman rm abc123` will not be the same as `podman rm ABC123` but I don't think anyone was manually entering uppercase SHA256 hash IDs so it shouldn't matter.
2. Escape the _ and % characters in volume lookup queries. These are SQLite wildcards, and meant that `podman volume rm test_1` would also match `podman volume rm testa2` (or any character in place of the underscore). This isn't done with pod and container lookups, but again those just use LIKE for IDs - so technically `podman volume rm abc_123` probably works and removes containers with an ID matching that pattern... I don't …
> Fix SQLite volume lookup queries matching too liberally

- pkg/api/handlers/compat/containers_create.go
- test/apiv2/20-containers.at
- test/apiv2/test-apiv2
When using `docker compose run --entrypoint ''`, docker sends `"Entrypoint": []` in the JSON. Podman currently treats that as `nil` and fallbacks to default image entrypoint.
This is not what is expected by the user. Instead, it should not use any entrypoint.
This commit fixes it by properly propagating the `[]` downstream to libpod.
Fixes: #26078
```release-note
None
```
> Handle "Entrypoint":[] in compat containers/create API.

- test/e2e/checkpoint_test.go
Followup on #26234.
```release-note
None
```
> e2e: ref full URL for aarch64 criu precheckpoint issues

- docs/source/markdown/podman-kube-play.1.md.in
- libpod/define/annotations.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgenutil/specgen.go
- test/e2e/play_kube_test.go
This commit adds two new annotations named `io.podman.annotations.cpuset/$ctrname` and `io.podman.annotations.memory-nodes/$ctrname`
The first one allows restricting a container's execution to specific CPU cores while the second one restricts memory allocations to specific NUMA memory nodes. They are also added automatically when the `--cpuset-cpus` and `--cpuset-mems` options are used.
This is largely inspired by previous work from Jan Kaluza (f15b0887c7fe0fc722a24fa3b2a8ed188f136707) to add support for `--pids-limit` in podman kube play.
Fixes: containers#26172
```release-note
- The `podman kube play` command can now restrict container execution to specific CPU cores using the `io.podman.annotations.cpuset/$ctrname` annotation.
- The `podman kube play` command can now restrict container …
```
> Support --cpuset-cpus and --cpuset-mems in podman kube play

- docs/source/markdown/podman-systemd.unit.5.md
Remove no longer correct statement that quadlet that does not translate our own custom unit types
Fixes: e498c652 ("Quadlet - translate dependencies on other quadlet units")
Fixes: #26243
```release-note
None
```
> docs: quadlet can translate names now

- docs/source/markdown/options/mount.md
- pkg/specgenutil/volumes.go
- pkg/specgenutilexternal/mount.go
- test/e2e/run_volume_test.go
Docker does not require `--type` to be passed, defaulting to `type=volume` in cases where it's not passed. Do the same in our volume parsing, and add a test to verify this works as expected.
Fixes #26101
```release-note
The `--mount` option to `podman create` and `podman run` now supports `dest=` as a valid alias for `destination=`.
Fixed a bug where the `--mount` option to `podman create` and `podman run`  required the `type=` option to be specified, instead of defaulting to `volume` when it was not present.
```
> Allow not specifying type with --mount flag

- rpm/podman.spec
We are not opting into the ostree backend, and it doesn't build: https://github.com/containers/image/pull/2821 . So, stop referencing the dependency.
Should not change behavior.
@lsm5 @jnovy PTAL.
```release-note
None
```
> Don't BuildRequires: ostree-devel

- cmd/podman/common/build.go
- test/system/070-build.bats
podman's logic to parse excludes from `--ignorefile` is not consistent with buildah, use code directly from buildah.
Closes: https://github.com/containers/podman/issues/25746
```release-note
build: behavior of --ignorefile is consistent with buildah
```
> build: reuse `parse.ContainerIgnoreFile` from buildah

- go.mod
- go.sum
- libpod/container_internal_common.go
- test/e2e/run_networking_test.go
- test/system/500-networking.bats
- vendor/github.com/containers/common/libnetwork/resolvconf/resolv.go
- vendor/modules.txt
We like to append the host servers in that case so that we do not only
force dns.podman.
Fixes: https://github.com/containers/podman/issues/24713
Fixes: https://issues.redhat.com/browse/RHEL-83787
Also:
We should fully replace the options, now that we vendored the
libnetwork/resolvconf changes into podman this just works.
Fixes: https://github.com/containers/podman/issues/22399
```release-note
When using a network with dns enabled (i.e. aardvark-dns) the host search domains are now still appended. (#24713)
When using podman run/create --dns-option the options are now correctly replaced instead of appended. (#22399)
```
> libpod: don't force only network search domains

- cmd/podman/system/check.go
- cmd/podman/system/df.go
- docs/source/markdown/podman-systemd.unit.5.md
- go.mod
- go.sum
- libpod/container_internal_common.go
- libpod/sqlite_state.go
- pkg/api/handlers/compat/containers_create.go
- pkg/api/handlers/libpod/containers_create.go
- pkg/domain/infra/abi/play.go
- pkg/machine/e2e/basic_test.go
- pkg/specgen/generate/container.go
- pkg/specgenutil/volumes.go
- test/apiv2/20-containers.at
- test/apiv2/test-apiv2
- test/e2e/containers_conf_test.go
- test/e2e/run_networking_test.go
- test/e2e/volume_rm_test.go
- test/system/030-run.bats
- test/system/320-system-df.bats
- test/system/500-networking.bats
- vendor/github.com/containers/common/libnetwork/resolvconf/resolv.go
- vendor/github.com/containers/common/version/version.go
- vendor/modules.txt
Backports of:
89b8e23385 75dc508e98 #26221
c87a761e05 #26252
da95bbdd5d #26264
f2d941b241 #26245
415668c802 #26225
a17f8afbbc #26237
e66ff395b7 #25986
3a981915f0 #26230
b276e7ef21 #26217
f25cefcb1b #26200
```release-note
See release notes of the original PRs for each fix
```
> [v5.5] Backports and c/common v0.63.1 bump

- pkg/machine/e2e/init_test.go
- pkg/machine/ignition/ignition.go
- pkg/machine/wsl/declares.go
- pkg/machine/wsl/machine.go
see commits
```release-note
Fixed a problem where podman machine would not have lingering enabled when a custom username was specified on init.
```
> pkg/machine: setup lingering for custom username and remove unnecessary sleep service 

- cmd/podman/artifact/add.go
- pkg/api/handlers/libpod/artifacts.go
- pkg/api/handlers/swagger/errors.go
- pkg/api/handlers/swagger/responses.go
- pkg/api/handlers/utils/errors.go
- pkg/api/server/register_artifacts.go
- pkg/api/server/server.go
- pkg/domain/entities/artifact.go
- pkg/domain/entities/engine_image.go
- pkg/domain/entities/types/artifacts.go
- pkg/domain/infra/abi/artifact.go
- pkg/domain/infra/tunnel/artifact.go
- pkg/libartifact/store/store.go
- test/apiv2/python/rest_api/fixtures/api_testcase.py
- test/apiv2/python/rest_api/test_v2_0_0_artifact.py
This patch adds a new endpoint to the REST API called "artifacts" with the following methods:
- Add
- Extract
- Inspect
- List
- Pull
- Push
- Remove
This API will be utilised by the Podman bindings to add OCI Artifact support to our remote clients.
Jira: https://issues.redhat.com/browse/RUN-2711
```release-note
Added artifacts endpoint to Podman REST API
```
> feat: Add OCI Artifact support to the Podman REST API

- .github/workflows/update-podmanio.yml
> Make podman.io update action reusable

- pkg/machine/e2e/init_test.go
- pkg/machine/ignition/ignition.go
We disabled it in the machine os image so it can no longer be used currently.
```release-note
None
```
> pkg/machine/e2e: skip rosetta test

- pkg/machine/ignition/ignition.go
pkg/machine: remove old fw_cfg service
It has not been in use since commit https://github.com/containers/podman/commit/f218f8430aa092ec45c4b7868f6d51b0bba4052b and should have been
removed there. It seems somehow it is causing a bug since our env file
is empty. In that case it triggers a segfault and since that happens
from within pam we are unable to login in any way.
I reported the issue[1] but because we don't need this just remove it so
we don't have to wait for a fix.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=2370858
Revert "podman machine: fix proxy test"
This reverts commit https://github.com/containers/podman/commit/0b8dd9084010b1d444d7362c5be6704843c21aba.
pkg/machine: remove unsused net recover file
This is not used in the code so it can be deleted.
```release-note
None …
```
> pkg/machine: remove some unsused services and add the /etc/environment.d SSL vars back

- docs/source/markdown/podmansh.1.md
Git commit 0c3b5e433e26d6a8a99a0967be91be897bbdc068 added a comment that `RemapUsers` is [deprecated](https://github.com/containers/podman/blob/246a688ee04a12795bfe624c54ce862fd12fc852/pkg/systemd/quadlet/quadlet.go#L149).
Use `UserNS=keep-id` instead.
```release-note
None
```
> docs: replace `RemapUsers=keep-id` with `UserNS=keep-id`

- Makefile
This exclusion has been there since the make target was added[1]. I wasn't able to find the reason but this runs on Darwin today and is useful to be able to run when you are developing bindings on a Mac.
[1] https://github.com/containers/podman/pull/8956
```release-note
None
```
> Allow generate-bindings on darwin

- Makefile
- contrib/validatepr/Containerfile
changing the validate-in-container make target to use quay.io/libpod/validatepr:latest.  this allows `make validate` to run to completion doing linting, ed's perl checks, and pre-commit.]
The image is now based on F42 `awk` is not part of the base image, so I added `awk`.
```release-note
None
```
> make validate-in-container changes

- pkg/machine/ocipull/ociartifact.go
Starting with [1] we now build and publish the wsl image from the machine-os repo, as such this special case is no longer needed.
[1] https://github.com/containers/podman-machine-os/pull/142
```release-note
podman machine for wsl pull now its image from quay.io/podman/machine-os just like the other providers.
```
> podman machine: pull wsl image from machine-os

- cmd/podman/images/import.go
- cmd/podman/kube/play.go
- cmd/podman/parse/net.go
- cmd/podman/parse/net_test.go
Fixes https://github.com/containers/podman/issues/26350
```release-note
Fixes absolute path usage for kube play on Windows
```
cc @l0rd
> fix: absolute path usage for kube play on Windows

- MAINTAINERS.md
As title suggests, this PR is to add Craig as a reviewer role to the Podman project.  Craig is an expert in Windows and WSL.  His collaboration in issues, discussions, and pull requests should be an asset to the project.
```release-note
None
```
> Add Craig Loewen to Reviewer role

- docs/source/markdown/podman-machine-init.1.md.in
- Add `podman machine init --now` example in manpages. 
Fixes: https://github.com/containers/podman/issues/26376
None
<!--
If no, just write `None` in the release-note block below. If yes, a release note
is required: Enter your extended release note in the block below. If the PR
requires additional action from users switching to the new release, include the
string "action required".
> Manpages: podman machine init add example with --now

- docs/source/markdown/podman-init.1.md.in
- docs/source/markdown/podman-pod-pause.1.md
- docs/source/markdown/podman-secret-rm.1.md
- docs/source/markdown/podman-system-connection-remove.1.md
- docs/source/markdown/podman-system-prune.1.md
The following manpages were missing examples of the `--all` flag:
* podman init
* podman pod pause
* podman secret rm
* podman system connection remove
* podman system prune
Added examples of all.
Fixes #26354
```release-note
NONE
```
> Add examples of `--all` flag

- cmd/podman/machine/init.go
- pkg/machine/define/errors.go
- pkg/machine/shim/host.go
- pkg/machine/wsl/declares.go
- pkg/machine/wsl/machine.go
- pkg/machine/wsl/stubber.go
- pkg/machine/wsl/util_windows.go
- pkg/machine/wsl/wutil/wutil.go
this patch changes how the detection of wsl works. The old way of using wsl --status command output to detect some missing features required by WSL is not fully reliable. WSL checks if the wsl feature is enabled and if the vmcompute service do exist. However, this is not enough to identify if the virtual machine platform feature is enabled. The vmcompute service could exist because it has been installed by other tools or it could exist but being stopped.
The way proposed by this patch is to try execute the import command and, if it fails, check the error and if it is related to the Host Compute Service try to install all features required by WSL.
The flow is the same as before, the user is asked to execute the podman machine init command with elevated privileges. Eventually, after …
> fix wsl install workflow on machine init command

- docs/source/markdown/podman-pod-create.1.md.in
- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/basic.pod
- test/system/252-quadlet.bats
Add ExitPolicy key to pod quadlets with logic to default to stop.
Docs updated with clarifcation on default value and usage example.
Simple assert added to bats to verify default constraint exists.
Addresses #25596
See Also: https://github.com/containers/podman/discussions/26453
```release-note
Added ExitPolicy for [Pod] in systemd quadlets
```
> pkg/systemd: expose [Pod] ExitPolicy key for pod create --exit-policy

- cmd/podman/common/create.go
- docs/source/markdown/options/health-timeout.md
- libpod/container_exec.go
- libpod/define/errors.go
- libpod/healthcheck.go
- libpod/oci_conmon_exec_common.go
- test/e2e/healthcheck_run_test.go
- test/system/220-healthcheck.bats
Previously, the HealthCheck exec session would not terminate on timeout, allowing the healthcheck to run indefinitely.
Because Docker does that, Podman should kill the HealthCheck when it reaches the timeout.
In order to backport this patch, you need to backport this patch as well (It is included in this PR):
- https://github.com/containers/podman/pull/25003 
This Backport contains: 
- https://github.com/containers/podman/pull/25003
- https://github.com/containers/podman/pull/26086 [commit](https://github.com/containers/podman/pull/26086/commits/499ea1168bd52a36e98927222a987a6b959f0b50)
- https://github.com/containers/podman/pull/26086 [commit](https://github.com/containers/podman/pull/26086/commits/077649f9d0c53583654a61c94ebca0f4fa15b877)
> Comparing …
> [v5.4-rhel] Fix: Ensure HealthCheck exec session terminates on timeout

- GOVERNANCE.md
When I worked up changes to Buildah's Governance, I found that Podman's version was missing a few links, and there were a few minor grammatical tweaks needed.
This addresses those.
For reference, Buildah's Governance Update PR: https://github.com/containers/buildah/pull/6124
```release-note
None
```
> [CI:DOCS] Tweak Governance slightly

- docs/source/markdown/podman-system-check.1.md
- libpod/runtime.go
podman system check --quick currently only skips layer contents, but practically it's not much quicker than without the flag.
This changes the flag to also skip checking layer digests which speed up the check significantly.
In some cases, it is useful to opt for a quicker check if we prioritize detecting and fixing severe corruption and can tolerate minor damage.
The check option is derived from CRI-O's internal repair: https://github.com/cri-o/cri-o/blob/9e4d86d82370ad44c14649f28ebdd8f94aaa28ca/internal/lib/container_server.go#L860
Fixes: https://issues.redhat.com/browse/OCPBUGS-57981
```release-note
None
```
> [v5.4-rhel] Skip layer digests for podman system check --quick

- docs/source/markdown/options/volume.md
add documentation to clarify when a volume is chowned.
Closes: https://github.com/containers/podman/issues/26474
```release-note
None
```
> docs: document when a volume is chowned

- cmd/podman/containers/update.go
- docs/source/markdown/options/latest.md
- docs/source/markdown/podman-update.1.md.in
- pkg/domain/entities/types/containers.go
- pkg/domain/infra/abi/containers.go
- test/e2e/update_test.go
Allow users to target the most recently created container with `podman update --latest` (short `-l`). The same option already exists on many other commands, so this brings update in line with the rest of the CLI and saves users from typing or looking up the newest container.
Fixes: #26380
```release-note
Added `--latest` option to `podman update` saves users from typing or looking up the most recently created container.
```
> cmd/podman: add --latest option to update #26380

- cmd/podman/images/pull.go
- docs/source/markdown/podman-pull.1.md.in
- test/system/156-pull-policy.bats
Yes
```release-note
Add policy argument to image pull 
```
> Podman pull - add policy flag

- MAINTAINERS.md
This PR updates Neil Smith's GitHub username from 'Neil-Smith' to 'actionmancan' in the MAINTAINERS.md file.
- Changed GitHub username from 'Neil-Smith' to 'actionmancan'
- Maintains Neil Smith's role as Community Manager
- No functional changes, just updating the GitHub handle
Does this PR introduce a user-facing change?
None
```release-note
None
```
Signed-off-by: G A Neil Smith <nesmith@redhat.com>
> Update Neil Smith's GitHub username in MAINTAINERS.md

- pkg/systemd/parser/unitfile.go
- pkg/systemd/quadlet/podmancmdline.go
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/env.container
Fixes: #26247
```release-note
This fix allows the user to use Podman's default logic for propagating environment variables from the host to the container in the Quadlet generator
```
> quadlet: handle generate environment params that inherit from host

- cmd/podman/root.go
Given container logs end up in syslog by default, somewhat-clarify that `--syslog` is about podman logs, not container logs.
```release-note
`--syslog` hints that it does not apply to container logs
```
> Clarify meaning of --syslog

- libpod/container.go
- libpod/container_config.go
- libpod/container_inspect.go
- libpod/oci_conmon_common.go
- test/system/030-run.bats
When generating Conmon's command line, we read containers.conf to get log_size_max and used it if the container didn't override it. However, `podman inspect` only reads from the container's own config, and ignores containers.conf. Unify the way we determine maximum log size with a single function and use it for both inspect and containers.conf, and add a test for this behavior.
Fixes https://issues.redhat.com/browse/RHEL-96776
```release-note
Fixed a bug where `podman inspect` did not correctly display log size for containers when `log_size_max` was set in containers.conf.
```
> Fix `podman inspect` to correctly handle log_size_max

- pkg/api/server/register_images.go
Add `headers` for `/libpod/build`
Closes: https://github.com/containers/podman/issues/26440
```release-note
Add headers to `/libpod/build` swagger documentation
```
> [docs] libpod/build: add headers

- hack/podman_cleanup_tracer.bt
On f42, rawhide and debian sid the script no longer logs anything as if failed to compile. Fix it it up to make it work again as it can be a powerful debug tool for flakes. I am currently trying to figure out how to instrument it for the missing podman exec/attach output flake.
```release-note
None
```
> hack/podman_cleanup_tracer.bt: fixes to make it work on newer versions

- docs/source/markdown/podman-run.1.md.in
The fuse-overlayfs example was misleading as setting fuse-overlayfs will cause a persistent storage configuration change rather than a one-time option.
Closes: https://github.com/containers/podman/issues/26590
```release-note
None
```
> docs: replace fuse-overlayfs example with additionalimagestore

- pkg/specgen/generate/kube/volume.go
- test/e2e/play_kube_test.go
Using an improperly formatted secret with kube returns a generic error message
`Error: failed to create volume "my-volume": error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.Secret`
This PR updates the error message to include why the failure occured:
`Error: failed to create volume "my-volume": only secrets created via the kube yaml file are supported: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type v1.Secret`
Closes: #26561 
```release-note
Clarified error message when using an improperly formatted secret with kube
```
> Clarifiy error message when using an improperly formatted secret with kube

- pkg/specgenutil/specgen.go
- pkg/specgenutil/specgenutil_windows_test.go
Call `specgen.ConvertWinMountPath()` on seccomp profile paths provided via security-opt parameter.
Fixes https://github.com/containers/podman/issues/26558
```release-note
None
```
> Fix seccomp profile path on Windows

- pkg/bindings/containers/attach.go
- pkg/bindings/containers/logs.go
- pkg/bindings/test/containers_test.go
- test/e2e/update_test.go
They don't really explain flakes to me but when looking at where we can loose remote output this is what I found. I don't think it fixes whatever flake we are seeing but the changes itself should be correct and in my many debug runs in https://github.com/containers/podman/pull/26596 I have not observed flakes with this.
```release-note
None
```
> pkg/bindings/containers: some attach/logs handling fixes

- CONTRIBUTING.md
- docs/CODE_STRUCTURE.md
Document most important directories when trying to understand our project.
Comments welcome, this is mostly meant as quick getting started guide for new folks trying to understand the codebase.
```release-note
None
```
> docs: add description about our code structure

- docs/source/markdown/podman-auto-update.1.md.in
added missing state "pending" for updated is avialable. im not sure if others missing, i just found this missing while creating a script
```release-note
None
```
> added updated state in podman-auto-update.1.md.in

- pkg/api/handlers/compat/images_build.go
- pkg/api/server/register_images.go
- pkg/bindings/images/build.go
- pkg/machine/e2e/basic_test.go
- test/e2e/build_test.go
Fixed the --build-context flag to properly send files for remote builds. Previously only the main context was sent over as a tar while additional contexts were passed as local paths and this would cause builds to fail since the files wouldn't exist.
New changes modifies the Build API to use multipart HTTP requests allowing multiple build contexts to be sent as tar files. Each additional context is packaged and transferred based on its type:
- Local Directories: Sent as tar archives
- Git Repositories: URL sent to the server, which then clones it
- Container Images: Image reference sent to the server, which pulls the image
- URLs/archives: URL sent to the server, which handles the download
Skip("Waiting for VM images with Podman > 5.5.2 for multipart build context support") is in place …
> Feat: send additional build contexts as tar files for remote builds

- test/e2e/diff_test.go
I hastily commented out some tests that were problematic for the vendor of Buildah v1.41 into Podman main (5.6 to be) in #26666.
@luap99 noted that I should have skipped them, this PR removes the comments and puts the Skip into play.
```release-note
None
```
> Skip rather than comment bad diff tests

- docs/source/markdown/podman-pod-clone.1.md.in
```release-note
None
```
issue fixes : #26372
Adds missing examples for setting resource limits when cloning pods in the `podman pod clone` manpage.
- Added example for memory limits: `--memory=1g --memory-swap=2g`
- Added example for CPU limits: `--cpus=2.5 --cpu-shares=1024`
The original manpage only had one resource limit example (`--cpus=5` with `--destroy`). 
This PR adds focused examples for the most commonly used resource limits (memory and CPU)
to help users understand how to set resource limits when cloning pods.
> docs: add resource limit examples to podman pod clone manpage

- docs/tutorials/rootless_tutorial.md
> Fix link in rootless_tutorial.md

- pkg/api/handlers/compat/images.go
- test/apiv2/10-images.at
```release-note
compat: GET /images/json returns [] instead of <none>:<none> in RepoTags and RepoDigest
```
> compat: GET /images/json returns [] instead of <none>:<none> in RepoTags and RepoDigest

- test/system/001-basic.bats
- test/system/helpers.bash
Unfortunately on a number of occasions, Podman has been released officially with a `-dev` suffix in the version number.  Assist in catching this mistake at release time by the addition of a simple conditional test.  Note that it must be positively enabled by a magic env. var. before executing the system tests.
Ref. original PR: https://github.com/containers/podman/pull/26540
***Note:*** Backport created with AI assistance.
```release-note
None
```
> [v3.2.3-rhel] Add conditional release-checking system test

- pkg/api/handlers/compat/images.go
- pkg/api/handlers/compat/ping.go
- pkg/api/handlers/compat/system.go
- test/apiv2/10-images.at
This PR introduces 3 changes:
`GET /images/json` now returns `SharedSize` when `shared-size` is passed. Returns -1 Otherwise
`GET /system/df` does not return `BuilderSize` 
`GET /_ping` now returns Builder-Version=1
Related: https://issues.redhat.com/browse/RUN-2698
```release-note
compat: add SharedSize to GET /images/json
compat: remove GET /system/df BuilderSize
compat: GET /_ping return Builder-Version: 1
```
> compat: Partial implementatino of compat api to Docker v1.42

- pkg/domain/filters/containers.go
- test/e2e/ps_test.go
The ancestor filter was previously using regex matching which caused partial image digest filters like `ancestor=bee55555` to fail when trying to match containers with full image IDs like `sha256:bee55555...`. This change implements a hybrid approach that supports exact match for performance, substring match for Docker compatibility, and regex match for advanced use cases. The fix ensures that partial image digest matching works as expected while maintaining backward compatibility with existing regex functionality. All existing tests pass and no breaking changes are introduced. This resolves the Docker compatibility issue where `podman ps -a -f ancestor=bee55555` previously returned no results but now correctly matches containers with the specified image digest pattern.
```release-note …
```
> Fix ancestor filter to support Docker-compatible substring matching

- pkg/api/handlers/compat/images.go
- pkg/api/handlers/compat/system.go
- pkg/domain/entities/types/images.go
- test/apiv2/10-images.at
- test/apiv2/45-system.at
Since compat version 1.43 the VirtualSize field in the GET /images/{name}/json, GET /images/json, and
GET /system/df responses is deprecated and will no longer be included in API v1.44. Use the Size field instead, which contains the same information.
```release-note
compat: deprecate VirtualSize in version 1.43 and remove it in 1.44
```
> compat: remove deprecated VirtualSize

- .packit.yaml
podman-next failure notifications are mostly if not totally ignored so there's no point keeping them.
While these notifications ideally shouldn't be ignored, some builds on podman-next frequently fail because of older toolchain and end up causing a lot of noise.
```release-note
None
```
> Packit: do not notify on podman-next failures

- pkg/machine/e2e/basic_test.go
The machine images should contain a new enough podman on the server side to support this so the skips can be removed.
```release-note
None
```
> pkg/machine/e2e: remove build context skip

- docs/source/markdown/podman-artifact-add.1.md.in
- docs/source/markdown/podman-artifact-extract.1.md
- docs/source/markdown/podman-artifact-inspect.1.md
- docs/source/markdown/podman-artifact-ls.1.md.in
- docs/source/markdown/podman-artifact-pull.1.md.in
- docs/source/markdown/podman-artifact-push.1.md.in
- docs/source/markdown/podman-artifact-rm.1.md
- docs/source/markdown/podman-artifact.1.md
Remove the "Experimental" stanza from the Podman Artifact commands in time for Podman v5.6 and RHEL 9.7/10.1
```release-note
None
```
> [CI:DOCS] Remove Experimental from Artifacts man pages

- go.mod
- go.sum
- test/buildah-bud/apply-podman-deltas
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/copier/copier.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/image.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/github.com/containers/buildah/imagebuildah/util.go
- vendor/github.com/containers/buildah/pkg/cli/build.go
- vendor/github.com/containers/buildah/pkg/cli/common.go
- vendor/github.com/containers/buildah/pkg/parse/parse.go
- vendor/github.com/containers/buildah/run_common.go
- vendor/modules.txt
Bump Buildah to v1.41.1 in preparation for Podman
v5.6 RC2.  The c/* projects were bumped in https://github.com/containers/podman/pull/25752
```release-note
None
```
> [v5.6] Bump Buildah to v1.41.1

- go.mod
- go.sum
- libpod/options.go
- libpod/util.go
- pkg/specgen/generate/kube/kube.go
- pkg/specgenutil/specgen.go
- test/e2e/play_kube_test.go
- test/e2e/run_test.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config_local.go
- vendor/github.com/containers/common/pkg/config/config_remote.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
- vendor/github.com/containers/common/pkg/config/pull_policy.go
- vendor/github.com/containers/common/pkg/filters/filters.go
- vendor/github.com/containers/common/pkg/util/util.go
- vendor/github.com/containers/common/version/version.go
- vendor/github.com/seccomp/libseccomp-golang/CHANGELOG
- vendor/github.com/seccomp/libseccomp-golang/seccomp.go
- vendor/github.com/spf13/pflag/README.md
- vendor/github.com/spf13/pflag/bool_func.go
- vendor/github.com/spf13/pflag/count.go
- vendor/github.com/spf13/pflag/errors.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/github.com/spf13/pflag/func.go
- vendor/github.com/spf13/pflag/golangflag.go
- vendor/github.com/spf13/pflag/ipnet_slice.go
- vendor/github.com/spf13/pflag/text.go
- vendor/github.com/spf13/pflag/time.go
- vendor/modules.txt
Added support for log_path option in containers.conf, this allows users to set a default logging directory from the container configuration file. A log path is read from `[containers]` section in the .conf file. For each container a sub-directory is created using the container id as the name and a ctr.log file is created within that sub-directory. This option can be overridden if set, `--log-opt` flag will take priority.
This pr also includes some vendor updates.
/kind feature
**This PR depends on containers/common#2491**
```release-note
Add log_path configuration option to containers.conf allowing users to specify custom directories for container log files. Container logs are organized in subdirectories named by container ID with ctr.log files.
```
> feat: added log_path support for configuration files

- cmd/podman/machine/init.go
- docs/source/markdown/options/tls-verify.md
- docs/source/markdown/podman-machine-init.1.md.in
- pkg/machine/define/initopts.go
- pkg/machine/e2e/basic_test.go
- pkg/machine/e2e/config_init_test.go
- pkg/machine/e2e/machine_pull_test.go
- pkg/machine/ocipull/ociartifact.go
- pkg/machine/shim/diskpull/diskpull.go
- pkg/machine/shim/host.go
This patch adds a new --tls-verify flag to the `podman machine init` sub command which matches many of our other commands. This allows the user to optionally control whether TLS verification is enabled or disabled for download of the machine image.
The default remains to leave the TLS verification decision to the backend library which defaults to enabling it, this patch just allows the user to explicitly set it on the CLI.
```release-note
A new flag `--tls-verify` has been added to the `podman machine init` command to allow explicit control over TLS validation when fetching the machine image. The default continues to be using TLS validation. 
```
Fixes #26517
> Add support for configuring tls verification with machine init

- docs/source/markdown/podman-pod-create.1.md.in
This PR adds comprehensive examples to the `podman pod create` manpage to demonstrate the newer features where resource limits and volume mounts are shared with all containers in a pod.
```release-note
docs: add examples with resource limits and mounts 
```
fixes : #26371
> docs: add examples with resource limits and mounts 

- libpod/boltdb_state.go
Right now, only log-level=info, so not shown by default. We can continue to up this in subsequent releases to convince folks of the urgency of switching.
Resolves https://issues.redhat.com/browse/RUN-3343
```release-note
The BoltDB database, deprecated since Podman 5.0's release last year, will be removed in next year's Podman 6.0 release. A warning has been added for users of this database to indicate the need to migrate.
```
> Add BoltDB deprecation notice

- docs/source/markdown/options/user-mode-networking.md
The docs were outdated mentioning the qemu backed for Mac and I find the way they are written to be a bit confusing.
I think it is best to start with that this option is not supported on all the providers except WSL.
Fixes: #26780
```release-note
None
```
> make machine --user-mode-networking docs more clear

- go.mod
- go.sum
- test/buildah-bud/apply-podman-deltas
- test/e2e/diff_test.go
- vendor/github.com/containers/buildah/CHANGELOG.md
- vendor/github.com/containers/buildah/changelog.txt
- vendor/github.com/containers/buildah/copier/copier.go
- vendor/github.com/containers/buildah/define/types.go
- vendor/github.com/containers/buildah/image.go
- vendor/github.com/containers/buildah/imagebuildah/executor.go
- vendor/github.com/containers/buildah/imagebuildah/stage_executor.go
- vendor/modules.txt
Bump Buildah to v1.41.3 in preparation for Podman v5.6.0. This also cures a last minute issue in the build code.
```release-note
None
```
> [v5.6] Bump to Buildah v1.41.3

- docs/source/markdown/podman-top.1.md.in
This PR adds the missing `groups` and `hgroups` format descriptors to the podmantop documentation. 
```release-note
docs: add missing groups and hgroups descriptors to podman top documentation
```
fixes : #25932
> docs: add missing groups and hgroups descriptors to podman top documentation

- README.md
This adds the LFX Health score and 2 contributor badges to the README. Nice work on scoring an excellent!
[![LFX Health Score](https://insights.linuxfoundation.org/api/badge/health-score?project=containers-podman)](https://insights.linuxfoundation.org/project/containers-podman)
[![LFX Contributors](https://insights.linuxfoundation.org/api/badge/contributors?project=containers-podman)](https://insights.linuxfoundation.org/project/containers-podman)
[![LFX Active Contributors](https://insights.linuxfoundation.org/api/badge/active-contributors?project=containers-podman)](https://insights.linuxfoundation.org/project/containers-podman)
```release-note
None
```
> docs: add LFX Insights badges

- libpod/events/journal_linux.go
- test/system/500-networking.bats
In the journald driver there is a bug where the network event attributes are not preserved. This causes the network driver to be missing and that in turn causes the ToHumanReadable() function to print an empty line. Fix it by making sure we preserve the network driver in the event attributes.
Fixes: https://issues.redhat.com/browse/RHEL-109790
```release-note
Correctly display the network create/remove events when using the journald event driver.
```
> podman events: show network create/remove event with journald

- RELEASE_NOTES.md
Also includes v5.5.1 and v5.5.2, which I evidently forgot.
```release-note
NONE
```
> Update release notes on main to reflect v5.6 release

- RELEASE_NOTES.md
Add this into the release notes so we have a clear message on what happened to Rosetta.
```release-note
NONE
```
> Add a release note for 5.6 Rosetta being disabled-by-default

- cmd/podman/containers/restore.go
- docs/source/markdown/podman-container-restore.1.md
- libpod/container_api.go
- libpod/oci_conmon_common.go
- pkg/api/handlers/libpod/containers.go
- pkg/api/server/register_containers.go
- pkg/bindings/containers/types.go
- pkg/bindings/containers/types_restore_options.go
- pkg/domain/entities/containers.go
- pkg/domain/infra/abi/containers.go
- pkg/domain/infra/tunnel/containers.go
- test/e2e/checkpoint_test.go
Fixes: #26676
```release-note
Add `--tcp-close` option to container restore to allow restoring multiple copies of a container with tcp connections
```
[PR to enable --tcp-close in crun](https://github.com/containers/crun/pull/1835)
> Add support for criu's tcp-close functionality.

- cmd/podman/images/import.go
- cmd/podman/volumes/import.go
- docs/source/markdown/podman-kube-play.1.md.in
The `podman-import` man page already mentions support for zstd compressed tarball support but the cli output didn't.
```release-note
None
```
> Mention zstandard tarball import support

- docs/source/markdown/podman-systemd.unit.5.md
- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/httpproxy-false.container
- test/e2e/quadlet/httpproxy-true.container
- test/e2e/quadlet_test.go
Add support for HttpProxy key in quadlet Container sections to control proxy environment variable inheritance during image pulls and builds.
- Add `HttpProxy` key support to quadlet Container sections
- `HttpProxy=true` enables proxy inheritance (default podman behavior)  
- `HttpProxy=false` disables proxy inheritance
- When omitted, uses podman's default behavior
- Add test cases for both scenarios
- Update documentation with usage examples
This addresses the need for declarative control over proxy settings for container image pulls without requiring manual workarounds with `PodmanArgs=--http-proxy=false`.
```ini
[Container]
Image=registry.example.com/myapp:latest
HttpProxy=false
[Service]
Environment=HTTP_PROXY=http://proxy.example.com:8080
```
- Follows existing quadlet boolean key …
> quadlet: add HttpProxy option for Container sections

- libpod/container_internal_common.go
- libpod/runtime_ctr.go
- test/e2e/run_volume_test.go
do not pass volume-opt as bind mounts options to runtime
Starting with runc 1.3.0 it errors when we pass unknown mount options to
the runtime, the volume-opt options are specific to the volume we create
and should not be passed to the mount in the oci spec.
Fixes: https://github.com/containers/podman/issues/26938
---
do not pass [no]copy as bind mounts options to runtime
Starting with runc 1.3.0 it errors when we pass unknown mount options to
the runtime, the copy/nocopy options are specific to podman when we
mount the volume and are not valid mount options for the runtime.
Fixes: https://github.com/containers/podman/issues/26938
```release-note
Fixed incorrect passing of volume option issues to the OCI runtime that started failing with runc 1.3.0. …
```
> do not pass volume options as bind mounts options to runtime

- hack/bats
- test/system/001-basic.bats
- test/system/030-run.bats
- test/system/032-sig-proxy.bats
- test/system/035-logs.bats
- test/system/060-mount.bats
- test/system/070-build.bats
- test/system/075-exec.bats
- test/system/080-pause.bats
- test/system/090-events.bats
- test/system/120-load.bats
- test/system/125-import.bats
- test/system/130-kill.bats
- test/system/160-volumes.bats
- test/system/161-volume-quotas.bats
- test/system/170-run-userns.bats
- test/system/180-blkio.bats
- test/system/190-run-ipcns.bats
- test/system/195-run-namespaces.bats
- test/system/252-quadlet.bats
- test/system/260-sdnotify.bats
- test/system/280-update.bats
- test/system/410-selinux.bats
- test/system/420-cgroups.bats
- test/system/500-networking.bats
see commits
```release-note
None
```
> test/system: some small fixes

- Makefile
This reverts commit c45b27ffb094cc09e88bf9dd9dcebfacc80e574f.
This commit was just wrong, local-cross depends on this target as it calls a target like "bin/podman.cross.linux.amd64". Without this it is just broken as there is no matching target.
$ make bin/podman.cross.linux.amd64
make: *** No rule to make target 'bin/podman.cross.linux.amd64'.  Stop.
```release-note
None
```
> Revert "Remove bin/podman.cross Make target"

- contrib/tmpfile/podman.conf
We already used `x` in tmpfiles, to ensure systemd did not remove our directories or clean their contents (we really need them to be left unmodified). However, systemd-tmpfiles lets us use more than one directive per line, which means we can safely add an R! (recursive remove on reboot) to these lines to ensure that, if /tmp is not a tmpfs, systemd-tmpfiles will still remove our temporary files, ensuring reboots are still accurately detected.
```release-note
Adjusted the systemd-tmpfiles script to recursively remove temporary files directories placed in `/tmp`, ensuring proper operation of Podman after a reboot if `/tmp` is not a tmpfs.
```
> Add R! to systemd-tmpfiles script for all /tmp dirs

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/mount-source-missing.container
- test/e2e/quadlet_test.go
If the `Mount` option inside a quadlet is missing the source=... part, the code today panics with the following message.
```
panic: runtime error: index out of range [0] with length 0
goroutine 1 [running]:
github.com/containers/podman/v5/pkg/systemd/quadlet.handleStorageSource(0xc000140de0?, 0x1d?, {0x0?, 0x1?}, 0x5634e39e233e?, 0x10?)
...
```
This commit checks for the missing source and returns an error to avoid the panic.
I added the check in two places, in handleStorageSource and in resolveContainerMountParams. The actual panic happens due to a unchecked index access in the former function while the porblematic configuration should already be detected before calling that function.
```release-note
Fix panic when a quadlet `Mount` option is missing a `source=...` value. Podman now …
```
> quadlet: fix runtime error for invalid Mount value

- docs/source/markdown/links/podman-systemd.unit.5
- docs/source/markdown/links/quadlet.5
- docs/source/markdown/podman-auto-update.1.md.in
- docs/source/markdown/podman-generate-systemd.1.md
- docs/source/markdown/podman-systemd.unit.5.md
- docs/source/markdown/podmansh.1.md
- hack/xref-quadlet-docs
There are endless of links pointing to this document we should not get rid of that.
Also I find having two podman-quadlet with different numbers rather confusing, while I understand the motivation I think for most users this is not intuitive. Most people will not type the man section numbers.
```release-note
None
```
> docs: restore podman-systemd.unit.5

- cmd/podman/compose.go
- cmd/podman/registry/config.go
- cmd/podman/registry/remote.go
- go.mod
- go.sum
- pkg/systemd/generate/containers.go
- pkg/systemd/generate/pods.go
- vendor/github.com/spf13/pflag/flag.go
- vendor/modules.txt
spf13/pflag: replace deprecated ParseErrorsWhitelist
Use ParseErrorsAllowlist instead, should still work the exact same.
```release-note
None
```
> update module github.com/spf13/pflag to v1.0.10

- pkg/systemd/quadlet/quadlet.go
- test/e2e/quadlet/no-workingdirectory-systemd-specifier.build
- test/e2e/quadlet_test.go
No
```release-note
None
```
Fixes: https://github.com/containers/podman/issues/26746
> Quadlet build - consider File path that starts with a systemd specifier as absolute

- internal/remote_build_helpers/utils.go
- internal/remote_build_helpers/utils_test.go
- pkg/bindings/images/build.go
- Split the monolithic Build() function into focused helper functions.
- Add a TempFileManager for proper temporary file lifecycle management.
This refactoring is in preparation for implementing a local build API. (https://github.com/containers/podman/issues/26321)
```release-note
None
```
> refactor: Modularize binding build functions

- contrib/design-docs/README.md
- contrib/design-docs/TEMPLATE.md
Add a new directory, which I'm currently dubbing "Features", in which will live design documents - descriptions of Podman features that will be implemented or are being implemented. Add a README and template to this directory to make the purpose clear and enable easy addition of new design documents.
This includes our first upstream design document, for a potential Conmon rewrite we're calling Conmon v3.
```release-note
NONE
```
> Add a directory for design documents

- .github/workflows/first_contrib_cert_generator.yml
This github action uses the certficate_generator.html from automation repo to generate the badge for first time contributors and commits the badge to the same repo which will be commented on the PR once its get merged.
```release-note
None
```
> Adding github action to generate a badge for first time contributor

- docs/source/markdown/options/chrootdirs.md
In explanation of chrootdirs option, leading / is dropped from podman managed file path (/etc/hostname). So this PR adds leading /.
```release-note
None
```
> fix: Correct typo in chrootdirs option

- docs/source/markdown/options/build-context.md
- test/buildah-bud/apply-podman-deltas
- Removal of a note in the build-context documentation about remote Podman client limitations
- Removal of skip statements for build-context tests in the test suite
Pull request #26628 adds support for --build-context for the remote client.
```release-note
None
```
> docs: remove remote limitation note for --build-context option

- .cirrus.yml
Do not use reupload_on_changes, this will make the cache grow unbound and I have seen the cache become so large then restoring it and uploading it took several minutes thus making the task time worse compared to no cache. I manually cleaned the cache a few times to fix this but it need to properly be fixed here.
To not have a stale cache for to long also use date +%U which will create a new cache once a week. This is in line with the offical golangci-lint github action which invalidates the cache every 7 days by default[1].
[1] https://github.com/golangci/golangci-lint-action/blob/main/README.md#cache-invalidation-interval
```release-note
None
```
> cirrus: fix golangci-lint cache leak + update freebsd version

- test/system/075-exec.bats
On very slow systems it can be that it takes over 5s after the sleep process was started and until the find_exec_pid_files function finds the file. This was observed on a ppc64le machine by Red Hat QE.
Just making the sleep longer should fix that problem and it doesn't really effect the total test time because we stop the container afterwards so there is no extra delay added with this either.
```release-note
None
```
> test/system: fix test race in exec leak check

- libpod/stats_freebsd.go
- pkg/api/handlers/compat/containers_stats_freebsd.go
> A couple of minor stats improvements for FreeBSD

- test/e2e/volume_plugin_test.go
Fixed #27116
```release-note
None
```
> test: remove hack workaround in 'use plugin in containers'

- docs/source/markdown/options/userns.container.md
Currently, the docs state that the `--userns=keep-id` option maps the rootless user's UID/GID to the same values inside the container, but they don’t make explicit that the **container's init process itself runs as that mapped UID/GID**.
This behaviour has caused some confusion (see #24934). In practice:
- Without `--userns=keep-id`, rootless containers default to running as `root` inside the container (mapped to the host UID externally).
- With `--userns=keep-id`, the init process runs as the host UID/GID inside the container, overriding the image’s `USER` instruction unless `--user` is explicitly set.
This PR updates the documentation to make that behaviour clear.
```release-note
None
```
> docs: clarify that `--userns=keep-id` runs container as host UID

- docs/source/Introduction.rst
- docs/source/includes.rst
Adds a link to the [Containerfile](https://github.com/containers/container-libs/blob/main/common/docs/Containerfile.5.md) documentation from the podman docs "Introduction" section
Fixes: #27086
```release-note
None
```
>  docs: add Containerfile doc link

- contrib/design-docs/podman6hld.md
Adding a design document for Podman 6.  it is a high level design that tries to encompasses proposed changes to Podman and its runtime environment.  It should highlight major changes and features; but you will also find nitty detailed changes that have been idenitified.  It is quite possible things in this document will change but it allows for open, transparent communication.
```release-note
None
```
> Add Podman 6 HLD

- cmd/podman/system/migrate.go
- cmd/podman/system/renumber.go
- Change function signatures to return error instead of calling os.Exit()
- Update cobra commands to use RunE instead of Run for proper error handling
- Remove unused imports (fmt, os, define)
- Remove FIXME comments about error handling inconsistency
This allows defer statements to run properly and improves testability.
```release-note
None
```
> cmd/podman/system: fix error handling in renumber and migrate commands

- cmd/podman/artifact/list.go
- docs/source/markdown/podman-artifact-ls.1.md.in
- test/e2e/artifact_test.go
Yes, added the option to format the list showing the virtual size `podman artifact ls --format '{{ .VirtualSize }}'`
Closes #27085
```release-note
Added virtual size option for artifact list --format
```
> Added virtual size option in artifact ls format

- docs/source/markdown/options/mount.md
Support for the subpath option was added the named volume mount type in [1] however this was missed from the docs.
[1] https://github.com/containers/podman/pull/24532
```release-note
None
```
> [DOCS] Update volume mount docs for subpath support

- pkg/bindings/test/containers_test.go
Fixed https://github.com/containers/podman/issues/27118
```release-note
None
```
> test: fix "run healthcheck" bindings test

- cmd/podman/artifact/rm.go
- docs/source/markdown/podman-artifact-rm.1.md
- pkg/api/handlers/libpod/artifacts.go
- pkg/api/server/register_artifacts.go
- pkg/bindings/artifacts/types.go
- pkg/bindings/artifacts/types_remove_options.go
- pkg/domain/entities/artifact.go
- pkg/domain/infra/abi/artifact.go
- pkg/domain/infra/tunnel/artifact.go
- test/apiv2/python/rest_api/test_v2_0_0_artifact.py
- test/e2e/artifact_test.go
Yes, --ignore flag.
Closes #27084
```release-note
Added flag --ignore for "podman artifact rm" to ignoring errors when trying to remove artifacts that does not exists.
```
> Feat artifact rm ignore

- cmd/podman/common/build.go
- pkg/api/handlers/compat/images_build.go
- pkg/bindings/images/build.go
- test/e2e/build_test.go
SBOM flags are not respected while podman build command.
At the same time buildah build command works as expected.
Fixes #23915 
With the following Containerfile:
```
FROM ubuntu:22.04
WORKDIR /app
```
Run the following podman build:
```
podman build -t sbom-img --sbom=trivy-spdx \
--sbom-image-output=/app/sbom-spdx.json \
--sbom-output=sbom-spdx.json \
--sbom-scanner-image=ghcr.io/aquasecurity/trivy \
--sbom-scanner-command="trivy filesystem -q {ROOTFS} --format spdx-json --output {OUTPUT}" \
--sbom-scanner-command="trivy filesystem -q {CONTEXT} --format spdx-json --output {OUTPUT}" \
--sbom-merge-strategy=merge-spdx-by-package-name-and-versioninfo \
-f Containerfile
```
Create a container with the image built in the previous step and check if the file sbom-spdx.json is inside of the …
> fix: #23915 podman build is not parsing sbom command line arguments

- cmd/quadlet/main.go
- pkg/systemd/quadlet/quadlet.go
> quadlet: remove unused 'name' parameter from ConvertNetwork and ConvertVolume

- test/system/030-run.bats
- test/system/130-kill.bats
Follow up to https://github.com/containers/podman/pull/27230
```release-note
None
```
> test/system: two small fixes
