libpod/container_attach.go

This fixes the integration tests

Fix trivial import issue

---

libpod/container.go
libpod/sql_state.go
libpod/sql_state_test.go

Minor changes to container.go and sql_state.go to fix issues
identified by the tests

Add tests for SQL-backed state impl

---

cmd/kpod/create.go
test/kpod_create.bats
test/kpod_pause.bats

Split off from #78 where the first commit was causing problems.

Make 'kpod create' also create the container in runc

---

cmd/kpod/history.go
cmd/kpod/images.go

Update the output of kpod images to match that of docker images
Signed-off-by: umohnani8 <umohnani@redhat.com>

Fix output of kpod images

---

cmd/kpod/attach.go
cmd/kpod/ps.go
cmd/kpod/run.go
cmd/kpod/spec.go
cmd/kpod/start.go
libpod/container_attach.go

Signed-off-by: Suraj Deshmukh <surajd.service@gmail.com>

Use debugf to allow parsing of format specifier

---

Makefile

updating the gitvalidation epoch to speed up
git validations.

update gitvalidation epoch

---

libpod/container.go
libpod/container_top.go
libpod/options.go

Add backend for CGroup Parent and SHM Size for containers

Wire up API for CGroup Parent

---

Makefile
docker
docs/dckrman.sh

Simple scripts to allow easier transition from Docker package to podman.

Add support for mimicing docker CLI

---

test/podman_import.bats

Update the podman_import test to use podman run, and update the
check method for string check method.

Update podman_import test to use podman

---

cmd/podman/create.go
libpod/runtime_img.go

When trying to determine if a user-provided string that describes
an image (ID, fq name, shortname, tagged), there were some
inefficiencies where we looked up images multiple times to derive
information about local images.

Streamline image resolution

---

cmd/podman/ps.go

Because the podman ps command has to collection a lot of information
from various places, many of which are controlled by locks, it is a
good candidate for doing batch operations under a single lock.

Use batched operations in ps

---

cmd/podman/main.go
cmd/podman/port.go
commands.md
completions/bash/podman
docs/podman-port.1.md
test/podman_port.bats

podman port reports the port mappings per container.  it can be used
to report the ports ofa single container or latest container or all
containers.
in the case of a single container, the user can add an option filter for
port and protocol.

podman port

---

docs/podman-inspect.1.md
docs/tutorials/podman_tutorial.md

sudo is not required when running as root, and # indicates
that you are already root.  $ indicates you are not root.

Change sudo examples to use $ instead of $

---

docs/podman-build.1.md
docs/podman-login.1.md
docs/podman-pull.1.md
docs/podman-push.1.md
vendor.conf
vendor/github.com/containers/image/docker/docker_client.go

Updated man pages to reflect the change
Fixes https://github.com/projectatomic/libpod/issues/38 and https://github.com/projectatomic/libpod/issues/39
Signed-off-by: umohnani8 <umohnani@redhat.com>

Change default certs dir to /etc/containers/certs.d

---

package_specs/podman.spec

Taking the fedora spec file and adding it to the git repo
for copr

Add the spec file to podman

---

.copr/Makefile
contrib/spec/podman.spec

COPR needed slight tweaks to our spec file.

Spec file changes for COPR

---

version/version.go

First commit will be tagged v0.2.2, second bumps version for future development

Bump version to 0.2.2 and dev version to 0.2.3-dev

---

.copr/Makefile

account for a shift in copr builds that need to use an exact commit

copr make file change

---

.copr/Makefile
.copr/prepare.sh
Makefile
contrib/spec/podman.spec.in

New structure for copr builds which hopefully is more stable

Re-enable copr builds

---

.copr/Makefile

copr outdir

---

libpod/networking.go

Until https://github.com/containernetworking/plugins/pull/75 is merged
upstream, we are using iptables to manually allow DNS resolution in
containers that run bridged mode networking.  We also remove the rule
in the networkwork tear down.
Resolves issue: #390

allow DNS resolution in containers

---

Makefile
contrib/spec/podman.spec.in
version/version.go

Will tag v0.3.2 as a release once merged

Bump to v0.3.2 and again to v0.3.3-dev

---

Makefile

Maintaining a changelog for each new version or release of Podman helps
users to quickly skim for new changes.  Add a `make changelog` target to
facilitate creating a new log.
There are two env variables to control the base and target commit for
the new log.  The output gets prepended to the changelog.txt file, which
is a textfile in following format:
- Changelog for $(CHANGELOG_TARGET) (ISO-8601 DATE):
* Commit subject
* Commit subject...
Notice that the list of commit subjects excludes merge commits, and can
be manually modified after generation if needed.
`CHANGELOG_BASE=v0.3.2 CHANGELOG_TARGET=v0.3.3 make changelog` would
generate the following shortened output to the changelog.txt file:
Changelog for v0.3.3 (2018-03-17):
* Bump to v0.3.3
* Fix build after c/image changes
* Update …

Makefile: add changelog target

---

Makefile
contrib/spec/podman.spec.in
docs/libpod.conf.5.md

saw this todo open, thought i'd take a whack at it. anything i should add (e.g. SEE ALSO section, or...)?

add libpod.conf man page (closes #537)

---

contrib/python/podman/libs/__init__.py
contrib/python/podman/libs/_containers_attach.py
contrib/python/podman/libs/containers.py
contrib/python/test/podman_testcase.py
contrib/python/test/test_containers.py

Implement container attach

---

libpod/pod.go

Signed-off-by: haircommander <pehunt@redhat.com>
Fixes: #907

Added a defer to an Unlock that immediately followed a Lock

---

contrib/python/podman/client.py
contrib/python/podman/libs/tunnel.py
contrib/python/requirements.txt
contrib/python/test/test_runner.sh
contrib/python/test/test_system.py

* client currently forks ssh client pending finding a well
maintained ssh library for python.  Including support for
AF_UNIX forwarding.

Implement SSH tunnels between client and podman server

---

cmd/podman/utils.go

issue introduced with c82166afabd63f6271990be89ffa6609d3dc6712

utils: fix endless write of resize event

---

transfer.md

[trivial] - fix typo in transfer.md

---

vendor.conf
vendor/github.com/containers/psgo/ps/ps.go
vendor/github.com/containers/psgo/vendor.conf

Pick up changes to user handling in psgo

Update psgo vendor

---

cmd/podman/pod.go
cmd/podman/pod_rm.go
cmd/podman/pod_start.go
cmd/podman/pod_stop.go
cmd/podman/utils.go
commands.md
completions/bash/podman
docs/podman-pod-rm.1.md
docs/podman-pod-start.1.md
docs/podman-pod-stop.1.md
docs/podman-pod.1.md
test/e2e/pod_start_test.go
test/e2e/pod_stop_test.go

As well as added tests, man pages, and completions.
Also reformat and refactor a couple of other small things in the other pod commands.
Signed-off-by: haircommander <pehunt@redhat.com>

Add pod start and stop

---

libpod/boltdb_state.go
libpod/boltdb_state_internal.go

Per https://www.sqlite.org/src/artifact/c230a7a24?ln=994-1081, POSIX file advisory locks are unsafe to use within a single process if multiple file descriptors are open for the same file. Unfortunately, this has a strong potential to happen for multithreaded usage of libpod, and could result in DB corruption.
To prevent this, wrap all access to BoltDB within a single libpod instance in a mutex to ensure concurrent access cannot occur.

Add a mutex to BoltDB state to prevent lock issues

---

docs/podman-export.1.md
docs/podman-varlink.1.md
docs/podman-version.1.md

Man page fixes found by https://pagure.io/ManualPageScan

---

contrib/spec/podman.spec.in

update copr spec, lets get it building again

---

.copr/prepare.sh
contrib/spec/podman.spec.in

Change tarball filename in copr prepare and match short-commit length

---

Makefile
contrib/python/podman/test/podman_testcase.py
contrib/python/podman/test/test_runner.sh
libpod.conf
libpod/runtime.go
test/e2e/libpod_suite_test.go

As the name says. CI will be forced to cgroupfs because of a lack of systemd in a container for testing.

Switch default CGroup manager to systemd

---

cmd/podman/common.go
cmd/podman/create.go
completions/bash/podman
docs/podman-create.1.md
docs/podman-run.1.md
pkg/spec/createconfig.go
pkg/spec/spec.go

Add proper support for systemd inside of podman

---

RELEASE_NOTES.md

Signed-off-by: Matthew Heon <matthew.heon@gmail.com>

Update RELEASE_NOTES for 0.9.1 release

---

test/e2e/search_test.go

change search test to look for fedora and not fedora-minimal

---

pkg/spec/spec.go

Don't mount /dev/* if user mounted /dev

---

Dockerfile.Fedora.openshift

Add python-varlink to the Fedora openshift image

---

test/e2e/run_test.go

podman runs disabled containers and privileged containers as spc_t

---

libpod/runtime.go

runtime: fix message which assumes the runtime is runc

---

cmd/podman/kill.go
completions/bash/podman
docs/podman-kill.1.md
docs/podman-stop.1.md

Add --all flag to podman kill

---

pkg/spec/config_linux.go
pkg/spec/spec.go

https://github.com/containers/libpod/issues/1429#issuecomment-424040416

rootless: raise an error when trying to use cgroups

---

libpod/container_internal.go

Should help fix https://github.com/containers/libpod/issues/1564#issuecomment-425773423

Need to allocate memory for hook struct

---

API.md
cmd/podman/varlink/io.podman.varlink
contrib/python/podman/.pylintrc
contrib/python/podman/podman/__init__.py
contrib/python/podman/podman/client.py
contrib/python/podman/podman/libs/__init__.py
contrib/python/podman/podman/libs/errors.py
contrib/python/podman/podman/libs/images.py
contrib/python/podman/podman/libs/pods.py
contrib/python/podman/test/test_pods_ctnrs.py
contrib/python/podman/test/test_pods_no_ctnrs.py
contrib/python/podman/test/test_runner.sh
contrib/python/pypodman/pypodman/lib/podman_parser.py
pkg/varlinkapi/pods.go

* Update varlink document
* Add NoContainersInPod error in go and python
* Add support for varlink pod interface
* New code passes pylint
* Fix bug in test_runner.sh

Implement pod varlink bindings

---

cmd/podman/create.go
test/e2e/run_selinux_test.go
test/e2e/run_test.go

Disable SELinux labeling if --privileged

---

pkg/spec/spec.go

Don't tmpcopyup on systemd cgroup

---

.papr.sh

skip userns tests on non-fedora distributions for now

---

README.md

Testing CI with a  call out to the blogs.

added links to buildah.io and podman.io to README.md

---

.copr/prepare.sh
contrib/spec/podman.spec.in

re-add BR for golang compiler to contrib/spec/podman.spec.in

---

vendor.conf
vendor/github.com/containers/buildah/README.md
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/chroot/run.go
vendor/github.com/containers/buildah/commit.go
vendor/github.com/containers/buildah/common.go
vendor/github.com/containers/buildah/imagebuildah/build.go
vendor/github.com/containers/buildah/new.go
vendor/github.com/containers/buildah/pkg/cli/common.go
vendor/github.com/containers/buildah/pkg/parse/parse.go
vendor/github.com/containers/buildah/pull.go
vendor/github.com/containers/buildah/unshare/unshare.c
vendor/github.com/containers/buildah/unshare/unshare.go
vendor/github.com/containers/buildah/util.go
vendor/github.com/containers/buildah/vendor.conf
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/pkg/tlsclientconfig/tlsclientconfig.go
vendor/github.com/containers/storage/drivers/chown_unix.go

Grab latest fixes from subpackages
Including fixes for usernamespace chowning retaining file attributes
Better logging of error messages.

Vendor in latest github.com/containers/storage,image, buildah

---

vendor.conf
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/openshift/openshift.go
vendor/github.com/containers/image/pkg/docker/config/config.go

Catches more errors when checking for login credentials.

Vendor latest containers/image

---

cmd/podman/runlabel.go
cmd/podman/shared/funcs.go
docs/podman-container-runlabel.1.md

fix runlabel functions based on QA feedback

---

docs/podman-create.1.md
docs/podman-run.1.md

Document --net as an alias of --network in podman run & create

---

cmd/podman/utils.go

We were encountering sync issues with the map, so swap to a thread-safe channel and convert into a map when we output

Swap from map to channels for podman stop workers

---

RELEASE_NOTES.md

Signed-off-by: Matthew Heon <matthew.heon@gmail.com>

Add release notes for 0.10.1

---

cmd/podman/common.go
cmd/podman/login.go
cmd/podman/logout.go
cmd/podman/pull.go
cmd/podman/push.go
cmd/podman/runlabel.go
cmd/podman/search.go
docs/podman-build.1.md
docs/podman-container-runlabel.1.md
docs/podman-login.1.md
docs/podman-logout.1.md
docs/podman-pull.1.md
docs/podman-push.1.md
docs/podman-search.1.md
vendor/github.com/containers/buildah/pkg/cli/common.go

This commit fixes #1340 when podman pull

Support auth file environment variable in related podman commands & add change to man pages

---

.papr_prepare.sh
contrib/python/podman/test/test_runner.sh
test/e2e/run_test.go

papr_prepare: remove double process for starting up .papr.sh

---

libpod/container_internal.go

One char change to fix up a typo in an error message.

Touchup fileo typo

---

README.md
RELEASE_NOTES.md

Update release notes for 0.10.1.1

---

libpod/container_internal_linux.go

We already have functions for retrieving the container's CGroup path, so use them instead of manually generating a path.

Fix CGroup paths used for systemd CGroup mount

---

README.md
RELEASE_NOTES.md

Update release notes for 0.10.1.2

---

.papr_prepare.sh

Fix podman in podman

---

.papr.yml
.papr_prepare.sh
Dockerfile.Fedora
test/e2e/run_passwd_test.go
test/e2e/run_test.go

fix NOTIFY_SOCKET in e2e testfix NOTIFY_SOCKET in e2e tests

---

cmd/podman/libpodruntime/runtime.go
libpod/oci.go
libpod/runtime.go
pkg/util/utils.go

This should allow us to share this code with buildah.

Move rootless directory handling to the libpod/pkg/util directory

---

docs/podman.1.md
pkg/util/utils.go

Fix man page to show info on storage

---

.papr.yml

re-enable f29 testing

---

cmd/podman/ps.go
cmd/podman/shared/container.go
libpod/container_api.go
test/e2e/libpod_suite_test.go
test/e2e/logs_test.go
test/e2e/pod_create_test.go
test/e2e/pod_infra_container_test.go
test/e2e/pod_top_test.go
test/e2e/run_entrypoint_test.go
test/e2e/run_privileged_test.go
test/e2e/version_test.go

Like Ricky Bobby, we want to go fast.

Make podman ps fast

---

.cirrus.yml

Ref: https://github.com/containers/buildah/pull/1109

Cirrus: Use images w/ buildah fix

---

libpod.conf

In the default `libpod.conf` configuration

Add support for /usr/local installation

---

vendor.conf
vendor/github.com/containers/storage/drivers/overlay/overlay.go

vendor: update container/storage

---

docs/podman-create.1.md
docs/podman-run.1.md

Explain the device format in man pages

---

Makefile

Switch all tests to use podman installed on the system, or Docker if podman
does not exist.

Eat our own dogfood

---

cmd/podman/build.go

Support auth file environment variable in podman build

---

cmd/podman/ps.go

fix bug in rm -fa parallel deletes

---

test/e2e/run_selinux_test.go

Add tests for selinux labels

---

contrib/python/podman/test/test_images.py
contrib/python/podman/test/test_runner.sh

* Save storage if tests fail
Fixes #1643

Ensure test container in running state

---

libpod/runtime.go

Only changed libpod.conf file, which might not even be in use.
(follow up from 21458369a1d67d0ee6c2a00656e641d96e3b9d36 and #1707)

Sync default config with libpod.conf

---

libpod/container_api.go

Only return `ErrCtrStateInvalid` errors when the mount counter is equal
to 1.  Also fix the "can't unmount [...] last mount[..]" error which
hasn't been returned when the error passed to `errors.Errorf()` is nil.
Fixes: #1695
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

unmount: fix error logic

---

libpod/container_api.go
libpod/container_internal.go
libpod/container_internal_linux.go
pkg/lookup/lookup.go

get user and group information using securejoin and runc's user library

---

libpod/networking_linux.go

If for any reason slirp4netns fails at startup, podman waits
indefinitely.  Check every second if the process is still running so
that we avoid to hang.
I've noticed this issue while I was playing with slirp4netns and setting
an option that is not supported.

rootless: avoid hang on failed slirp4netns

---

contrib/python/pypodman/pypodman/lib/actions/history_action.py
contrib/python/pypodman/pypodman/lib/actions/images_action.py

Change humanize to use MB vs MiB.

---

contrib/python/pypodman/pypodman/lib/actions/images_action.py
contrib/python/pypodman/pypodman/lib/report.py

* Fixed issue where podman printed '<none>' and pypodman
skipped the image
* Fixed issue where port was printed in place of tags
Fixes #1655 

Fix long image name handling

---

Makefile

Similar to https://github.com/containers/skopeo/pull/566
🍔

Do never override podman with docker

---

libpod/runtime_pod_linux.go

For pods using cgroupfs, we were seeing some error messages in CI from an inability to remove the pod CGroup, which was traced down to the conmon cgroup still being present as a child. Try to
remove these error messages and ensure successful CGroup deletion by removing the conmon CGroup first, then the pod cgroup.

Remove conmon cgroup before pod cgroup for cgroupfs

---

libpod/container_api.go
libpod/container_internal.go
libpod/container_internal_linux.go

move defer'd function declaration ahead of prepare error return

---

RELEASE_NOTES.md

Update release notes for 0.11.1

---

contrib/cirrus/lib.sh

Cirrus: Ignore any error from the IRC messenger

---

libpod/container_internal_linux.go
libpod/networking_linux.go

We are seeing some issues where, when part of prepare() fails
(originally noticed due to a bad static IP), the other half does
not successfully clean up, and the state can be left in a bad
place (not knowing about an active SHM mount for example).

Accurately update state if prepare() partially fails

---

docs/podman-container.1.md

Signed-off-by: Xavier Krantz <xakraz@gmail.com>

docs: Fix duplicated entry for pod-container-unmount

---

troubleshooting.md

troubleshooting.md: add a recipe for rootless ping

---

cmd/podman/images.go
docs/podman-images.1.md

Add space between num & unit in images output

---

vendor.conf
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/builtin.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/builtin.go.h
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/cat.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/checkout.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/checksum.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/commit.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/config.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/diff.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/export.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/fsck.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/gpgsign.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/init.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/log.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/ls.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/prune.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/pull.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/pulllocal.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/refs.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/remote.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/reset.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/revparse.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/show.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/staticdelta.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/summary.go
vendor/github.com/ostreedev/ostree-go/pkg/otbuiltin/trivialhttpd.go

it fixes some warnings with cgo

vendor: update ostree-go

---

OWNERS

Can't see any reason for a difference here. If you can review, you can approve.

Make list of approvers same as reviewers

---

README.md
RELEASE_NOTES.md

As the title says - document the planned release

Add release notes for 0.11.1.1

---

contrib/python/podman/podman/libs/_containers_attach.py
contrib/python/pypodman/pypodman/lib/actions/__init__.py
contrib/python/pypodman/pypodman/lib/actions/start_action.py
contrib/python/pypodman/pypodman/lib/parser_actions.py

* Improve error messages from argparse Actions
* Silence more pylint errors when supporting a given API
* Refactor BooleanAction to support lower and mixed case input
* Remove spurious print()

Implement pypodman start command

---

contrib/python/podman/podman/libs/containers.py

* Clean up code in containers.py
* Pass pylint tests
* Pass tox tests

Improve speed of containers.list()

---

test/e2e/create_staticip_test.go
test/e2e/run_staticip_test.go

Add one test for run command:
- Two containers can not run with the same given IP address
And also add test cases for create command which are the same with run command.

Add some tests for --ip flag with run and create command

---

test/e2e/create_staticip_test.go
test/e2e/run_staticip_test.go

issue introduced with:
https://github.com/containers/libpod/pull/1871

test: cleanup CNI network used by the tests

---

pkg/util/utils.go

do not store the entire file but only the subset of what we have
modified.  Also, we were not writing the correct data.  Since it is
not trivial to serialize storage.conf correctly and all the various
supported options, serialize only what we care about.

rootless: store only subset of storage.conf

---

libpod/container_api.go
libpod/util.go

a couple of improvements for exec:
- we use fsnotify to take advantage of inotify on Linux so we don't poll for the file being created
- if the OCI runtime exited don't let the timeout expire first, but return an error immediately.
We recently bumped the timeout value, that means we could block the container lock for 60s if the runtime failed

exec: remove polling for PID file

---

contrib/python/podman/podman/libs/containers.py
contrib/python/podman/test/test_containers.py
contrib/python/pypodman/pypodman/lib/actions/commit_action.py

* Some items included in the CLI and currently not supported by the API.
Fixes #1867

Fixes #1867

---

cmd/podman/ps.go
completions/bash/podman
docs/podman-ps.1.md

podman ps has a flag --pod; simply adding a short option of -p

add pod short option to ps

---

test/e2e/create_test.go

The test cases are the same as podman run with --mount.

Add create test with --mount flag

---

.cirrus.yml
Dockerfile
contrib/cirrus/lib.sh
contrib/cirrus/packer/ubuntu_setup.sh
contrib/cirrus/setup_environment.sh
libpod/oci.go

variant of: https://github.com/containers/libpod/pull/1901

tests: fix rootless tests on Ubuntu

---

test/e2e/rmi_test.go

test for rmi with children

---

.papr.yml

set .54 version for f28 due to memory error

---

contrib/python/podman/podman/libs/images.py
contrib/python/podman/test/test_images.py

Invert tlsverify default in API

---

docs/tutorials/podman_tutorial.md

tutorial: add ostree dependency

---

README.md
RELEASE_NOTES.md

Update release notes for 0.12.1

---

RELEASE_NOTES.md

Update release notes for v0.12.1.1

---

API.md
cmd/podman/varlink/io.podman.varlink
pkg/varlinkapi/images.go

add more example usage to varlink endpoints

---

contrib/cirrus/README.md

Mostly minor tweaks and clarifications.  Though there was
one missing (required) make value I fixed.

Cirrus: Update base-image build docs

---

libpod/kube.go

Using the default capabilities, we can determine which caps were
added and dropped.  Now added them to the security context structure.

Add capabilities to generate kube

---

libpod/options.go

If one of storage GraphRoot or RunRoot are specified, but the other is not, c/storage will not use the default, and will throw an error instead. Ensure that in cases where this would happen, we populate the fields with the c/storage defaults ourselves.

Ensure storage options are properly initialized

---

cmd/podman/generate_kube.go

fix typo in kubernetes

---

README.md
contrib/cirrus/README.md

Cirrus: Add/fix documentation links

---

RELEASE_NOTES.md

Add release notes for 0.12.1.2

---

cmd/podman/rmi.go

when deleting infra containers, we were not checking the error of the
image deletion and therefore resulting in not reporting the error.
Fixes #1991

display proper error when rmi -fa with infra containers

---

contrib/python/podman/test/test_runner.sh

all flakes must die

---

.cirrus.yml
Makefile

it is very useful when using git bisect that at least the commit can
build.
got inspiration from: https://twitter.com/pid_eins/status/1072797993760423941

Makefile: validate that each commit can at least build

---

cmd/podman/image.go
cmd/podman/trust.go
docs/podman-image-trust.1.md
docs/podman-image.1.md
libpod/image/utils.go
libpod/runtime.go
pkg/trust/trust.go
test/e2e/trust_test.go

implemented:
```
$ podman image trust show --json
$ podman image trust show --raw
$ podman image trust show
$ podman image trust set --type <type> --pubkeysfile <filepath> <registryname>
```

Support podman image trust command

---

contrib/gate/Dockerfile
test/install/Dockerfile.Fedora

prepare for move to validate on 1.11 only

---

docs/tutorials/podman_tutorial.md

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

docs/tutorials: add a basic network config

---

contrib/cirrus/lib.sh

This reverts commit dd81a8fe7dcc532f78d03291223806a877f820c7.
Now that the CRIU socket has the correct SELinux label checkpointing and
restoring works again on F28 and F29.
Related to #1962 #1891 #1890

Use existing CRIU packages for testing instead of building from git

---

vendor.conf
vendor/github.com/containers/psgo/internal/capabilities/capabilities.go
vendor/github.com/containers/psgo/internal/dev/tty.go
vendor/github.com/containers/psgo/internal/host/host.go
vendor/github.com/containers/psgo/internal/proc/attr.go
vendor/github.com/containers/psgo/internal/proc/cmdline.go
vendor/github.com/containers/psgo/internal/proc/ns.go
vendor/github.com/containers/psgo/internal/proc/pids.go
vendor/github.com/containers/psgo/internal/proc/stat.go
vendor/github.com/containers/psgo/internal/proc/status.go
vendor/github.com/containers/psgo/internal/process/process.go
vendor/github.com/containers/psgo/internal/types/types.go
vendor/github.com/containers/psgo/psgo.go

There is a race condition in psgo, that can cause some tests
to flake.

Vendor in latest psgo code

---

.cirrus.yml
contrib/cirrus/lib.sh

Followup to #1998
/cc @adrianreber

Use new VM images with updated CRIU

---

pkg/util/utils.go

ParseIDMap function was extracted to idtools in
https://github.com/containers/storage/pull/236
it is already used in containers/storage and buildah, it should be used in
libpod as well.
Signed-off-by: Šimon Lukašík <isimluk@fedoraproject.org>

Refactor: use idtools.ParseIDMap instead of bundling own version

---

pkg/spec/config_linux.go

Fix handling of symbolic links

---

CONTRIBUTING.md

[skip ci] Docs: Add Bot Interactions section

---

cmd/podman/login.go

* Do not try to login with existing credentials when the user specifies a
username or password on the CLI.
* Improve error messages.
* Use specified tls-verify switch and cert-dir for all requests.
Fixes: #2092

podman-login: adhere to user input

---

libpod/lock/lock.go
libpod/lock/shm/shm_lock.go
libpod/lock/shm/shm_lock_test.go
libpod/lock/shm_lock_manager_linux.go

Should also have a fix for a nasty test flake

Address lingering review comments from SHM locking PR

---

vendor.conf
vendor/github.com/containers/buildah/imagebuildah/build.go
vendor/github.com/containers/buildah/pkg/blobcache/blobcache.go

Allow parallel copying from the blobcache.

vendor latest buildah

---

libpod/runtime.go

If you fail to open shm lock then attempt to create it

---

cmd/podman/sign.go

a couple of fixes that were noticed during the review but we decided to fix as follow ups

sign: some fixes

---

cmd/podman/sign.go
completions/bash/podman
docs/podman-image-sign.1.md

Add completions
Fix man pages
fix code in sign to answer PR Comments.

Fix up image sign and trust

---

README.md

Some trivial Readme updates, mostly submitted to force the tests to run against latest master

Trivial readme updates

---

contrib/cirrus/lib.sh
contrib/cirrus/setup_environment.sh

Also record into a file in case a later reference is required

Cirrus: (Minor) Print timestamp

---

cmd/podman/trust.go
pkg/trust/trust.go

continue PR #1899 Support podman image trust command

Fix 'image trust' from PR1899

---

.cirrus.yml

Cirrus: Post-Merge Testing for v1.0 Branch

---

cmd/podman/imagefilters/filters.go
cmd/podman/images.go
cmd/podman/varlink/io.podman.varlink
libpod/adapter/images_remote.go
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
libpod/image/image.go
libpod/image/parts.go
libpod/image/parts_test.go
libpod/image/pull.go
libpod/image/utils.go
pkg/varlinkapi/images.go

remote-client support for images

---

README.md
RELEASE_NOTES.md

Update release notes for v1.0

---

test/test_podman_baseline.sh
test/test_podman_pods.sh

Fixes: #1992 
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

Use multi-arch images in test cases

---

troubleshooting.md

Add local storage.conf example to troubleshoot

---

RELEASE_NOTES.md
changelog.txt
contrib/spec/podman.spec.in
version/version.go

Grab release notes, changelog, and version changes so master is up to date.

Update master branch with v1.0 changes from 1.0 branch

---

cmd/podman/rmi.go
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
test/e2e/exists_test.go
test/e2e/libpod_suite_remoteclient_test.go
test/e2e/libpod_suite_test.go
test/e2e/rmi_test.go

allow the podman remote client to delete images

podman remote client -- add rmi

---

cmd/podman/exists.go
cmd/podman/images.go
cmd/podman/info.go
cmd/podman/pull.go
cmd/podman/tag.go

Rename localRuntime to runtime in cmd/podman

---

install.md

Add documentation on how to install a packaged version of podman

Installing podman

---

cmd/podman/mount.go
cmd/podman/umount.go
completions/bash/podman
docs/podman-mount.1.md
docs/podman-rm.1.md
docs/podman-umount.1.md

I find these useful for playing around with containers.

 Add --latest and --all to podman mount/umount 

---

API.md
cmd/podman/inspect.go
cmd/podman/shared/container.go
cmd/podman/varlink/io.podman.varlink
libpod/adapter/containers_remote.go
libpod/adapter/images_remote.go
libpod/adapter/runtime_remote.go
libpod/boltdb_state.go
libpod/boltdb_state_linux.go
libpod/boltdb_state_unsupported.go
libpod/common_test.go
libpod/container.go
libpod/container_internal.go
libpod/container_internal_test.go
libpod/runtime_ctr.go
pkg/varlinkapi/containers.go
test/e2e/common_test.go
test/e2e/inspect_test.go
test/e2e/libpod_suite_remoteclient_test.go
test/e2e/libpod_suite_test.go

base enablement of the inspect command.

podman-remote inspect

---

docs/tutorials/podman_tutorial.md

@vorburger was asking in https://github.com/containers/libpod/issues/1973#issuecomment-454989393 about Bodhi. Add some explanation about this to our documentation.

tutorials: describe how to use podman in updates-testing

---

README.md

Just to clarify where the name came from. We also now manage
volumes so add that to the description.

add Pod Manager References

---

cmd/podman/trust.go
pkg/trust/trust.go

fix #2108 
- move Unmarshal policy.json form cmd/trust.go to pkg/trust
- GetGPGId methods with single argument instead of array
- move formatter methods(func getPolicyOutput()) from pkg/trust to cmd/trust.go 
- move variable declaration to the top of the functoin 

Fix up `image sign` in PR 2108

---

Makefile
test/e2e/common_test.go
test/e2e/libpod_suite_remoteclient_test.go
test/e2e/libpod_suite_test.go

first step to start playing with other OCI runtimes.

tests: allow to override the OCI runtime

---

pkg/spec/spec.go

when running in rootless mode we were unconditionally overriding
/dev/pts to take ride of gid=5.  This is not needed when multiple gids
are present in the namespace, which is always the case except when
running the tests suite with only one mapping.  So change it to check
how many gids are present before overriding the default mount.

rootless: do not override /dev/pts if not needed

---

Makefile
install.md

* add a section about vendoring and how to troubleshoot it to the install.md
* make sure that `make vendor` always uses the latest `vndr` to avoid potential inconsistencies with the CI
Cc: @baude @cevich @edsantiago

Vendor docs

---

docs/podman-image-trust.1.md

After the last update, @mtrmac had some great suggestions which I've incorporated.  I've updated the Google doc and have added this PR in case it's easier to see the diffs.

Update image-trust man with further comments

---

docs/podman-create.1.md
docs/podman-run.1.md
troubleshooting.md

Add a problem statement about shadow-utils and missing entries from
/etc/subuid and /etc/subgid.

Add troubleshooting information about running a rootless containers.

---

cmd/podman/commands_remoteclient.go
cmd/podman/varlink/io.podman.varlink
cmd/podman/volume_create.go
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
pkg/varlinkapi/volumes.go

create a volume using the remote client over varlink

podman-remote volume create

---

cmd/podman/commands_remoteclient.go
cmd/podman/varlink/io.podman.varlink
cmd/podman/volume_rm.go
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
libpod/runtime_volume.go
pkg/varlinkapi/volumes.go

add the ability to remove/delete volumes with the podman remote
client.

podman-remote volume rm

---

Makefile
cmd/podman/varlink.go
cmd/podman/varlink/io.podman.varlink
libpod/adapter/runtime_remote.go
pkg/varlinkapi/containers.go
pkg/varlinkapi/images.go
pkg/varlinkapi/system.go
pkg/varlinkapi/util.go

See individual commits. This is a first round of fixes I've found when I started working with this API for [cockpit-podman](https://github.com/cockpit-project/cockpit-podman). I have some more, but these were the ones I could easily implement.
I hope that you don't consider the varlink API to be stable, yet? As far as I know, cockpit-podman is the only user so far and I'm fine updating that on the next release.

Make varlink API more idiomatic

---

API.md
cmd/podman/commands_remoteclient.go
cmd/podman/varlink/io.podman.varlink
cmd/podman/volume_inspect.go
cmd/podman/volume_ls.go
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
libpod/adapter/volumes_remote.go
pkg/varlinkapi/volumes.go

add the ability to list and inspect volumes using the remote
client and varlink

podman-remote volume inspect|ls

---

completions/bash/podman

completions: add --pod to run/create

---

API.md
cmd/podman/build.go
cmd/podman/varlink/io.podman.varlink
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
pkg/varlinkapi/images.go
pkg/varlinkapi/transfers.go
pkg/varlinkapi/util.go

add the ability to build images using files local to the remote-client
but over a varlink interface to a "remote" server.

podman-remote build

---

cmd/podman/commit.go
cmd/podman/common.go
cmd/podman/create.go
cmd/podman/exists.go
cmd/podman/info.go
cmd/podman/inspect.go
cmd/podman/login.go
cmd/podman/pod_inspect.go
cmd/podman/pod_rm.go
docs/podman-commit.1.md
docs/podman-create.1.md

First pass of entries for the Examples listed in the Cobra Help.  Will add others in following PR's.

Add examples for Cobra

---

cmd/podman/libpodruntime/runtime.go

possibly a regression after we moved to Cobra

podman: honor --storage-opt again

---

cmd/podman/attach.go
cmd/podman/checkpoint.go
cmd/podman/diff.go
cmd/podman/exec.go
cmd/podman/export.go
cmd/podman/import.go
cmd/podman/kill.go
cmd/podman/logout.go
cmd/podman/pause.go
cmd/podman/pod_start.go
cmd/podman/pod_stats.go
cmd/podman/pod_top.go
cmd/podman/ps.go
cmd/podman/sign.go
cmd/podman/trust_set_show.go
cmd/podman/umount.go
cmd/podman/unpause.go
cmd/podman/volume_create.go
cmd/podman/volume_inspect.go
docs/podman-exec.1.md

Adds examples to Cobra help for a second chunk of commands.  More to come.

Second chunk of Cobra help

---

cmd/podman/build.go
cmd/podman/play_kube.go
cmd/podman/pod_stop.go
cmd/podman/pull.go
cmd/podman/push.go
cmd/podman/rm.go
cmd/podman/rmi.go
cmd/podman/run.go
cmd/podman/start.go
cmd/podman/stop.go
docs/podman-start.1.md
docs/podman-stop.1.md

Adds the third chunk of Cobra examples to the cli help.
As we're putting together a release tomorrow, tried to
hit the heavy commands with this PR.

Add 3rd chunk of Cobra examples

---

cmd/podman/cleanup.go
cmd/podman/restart.go
cmd/podman/restore.go
cmd/podman/runlabel.go
cmd/podman/save.go
cmd/podman/search.go
cmd/podman/stats.go
cmd/podman/tag.go
cmd/podman/top.go
cmd/podman/varlink.go

Adds the 4th chunk of Cobra Examples to the CLI help.
One more chunk of 10 to complete.

Add 4th chunk of Cobra Examples

---

libpod/container_internal.go

Before, a container being run or started in a pod always restarted the infra container. This was because we didn't take running dependencies into account. Fix this by filtering for dependencies in the running state.

Don't start running dependencies

---

API.md
cmd/podman/varlink/io.podman.varlink
libpod/adapter/runtime_remote.go
pkg/varlinkapi/images.go

Add status for remote users and podman remote-client pull.

podman-remote pull

---

cmd/podman/generate_kube.go
cmd/podman/images.go
cmd/podman/logs.go
cmd/podman/pod_kill.go
cmd/podman/pod_pause.go
cmd/podman/pod_restart.go
cmd/podman/pod_unpause.go
cmd/podman/port.go
cmd/podman/volume_rm.go
cmd/podman/wait.go
docs/podman-logs.1.md
docs/podman-pod-restart.1.md
docs/podman-port.1.md

The fifth and final chunk of examples for the Cobra
examples in the CLI help output.
Also includes a few man page touchups.

Fifth chunk of Cobra Examples

---

API.md
cmd/podman/commands.go
cmd/podman/image.go
cmd/podman/main.go
cmd/podman/save.go
cmd/podman/varlink/io.podman.varlink
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
libpod/image/image.go
libpod/image/utils.go
pkg/varlinkapi/images.go
test/e2e/save_test.go
utils/utils.go

Add the ability to save an image from the remote-host to the
remote-client.

podman-remote save [image]

---

cmd/podman/commands.go
cmd/podman/image.go
cmd/podman/load.go
cmd/podman/main.go
cmd/podman/varlink/io.podman.varlink
libpod/adapter/runtime.go
libpod/adapter/runtime_remote.go
libpod/image/image.go
libpod/runtime_img.go
pkg/varlinkapi/images.go
test/e2e/load_test.go

enable the ability to load an image into remote storage
using the remote client.

podman-remote load image

---

cmd/podman/build.go
docs/podman-build.1.md
libpod/container_commit.go
vendor.conf
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/imagebuildah/build.go
vendor/github.com/containers/buildah/new.go
vendor/github.com/containers/buildah/pkg/cli/common.go
vendor/github.com/containers/buildah/pkg/parse/parse.go
vendor/github.com/containers/buildah/pull.go
vendor/github.com/containers/buildah/unshare/unshare.c
vendor/github.com/containers/buildah/unshare/unshare.go
vendor/github.com/containers/buildah/util/util.go
vendor/github.com/containers/buildah/vendor.conf
vendor/github.com/openshift/imagebuilder/README.md
vendor/github.com/openshift/imagebuilder/builder.go
vendor/github.com/openshift/imagebuilder/dispatchers.go

Vendors in Buildah 1.7 into Podman.

Vendor Buildah v1.7

---

cmd/podman/build.go

Switch defaults for --layers, --force-rm and --pull-always
from buildah to podman.
Only override default values.

Switch defaults for podman build versus buildah

---

libpod/container_internal_linux.go

We should just bind mount the original containers /etc/resolv.conf and /etchosts
into the new container.  Changes in the resolv.conf and hosts should be seen
by all containers,  This matches Docker behaviour.
In order to make this work the labels on these files need to have a shared
SELinux label.

In shared networkNS /etc/resolv.conf&/etc/hosts should be shared

---

README.md

Rephrase the description of Buildah to make some core attributes
(e.g., rootless, Dockerfile-less build, etc.) more obvious.
Addresses: [#1349 (comment)](https://github.com/containers/buildah/issues/1349#issuecomment-466096550)
Cherry-pick-from: https://github.com/containers/buildah/pull/1362

[skip-ci] README.md: rephrase Buildah description

---

cmd/podman/commands.go
cmd/podman/pod.go
cmd/podman/pod_create.go
cmd/podman/pod_ps.go
cmd/podman/shared/pod.go
cmd/podman/utils.go
pkg/adapter/containers_remote.go
pkg/adapter/pods.go
pkg/adapter/pods_remote.go
pkg/varlinkapi/pods.go

enable the podman-remote client to be able to create and list
pods on a remote system.

podman-remote create|ps

---

README.md
docs/podman-generate-kube.1.md
docs/podman-play-kube.1.md

* Refine the "Out of scope" section regarding `docker-compose`.
* Cross reference generate/play manpages.
@conan-kudo @mheon @rhatdan @TomSweeneyRedHat PTAL

[skip ci] readme/docs update

---

CONTRIBUTING.md

Introduce a new part inside the contribution guide who explain how to start to hack on libpod:
- setup environment
- install tools
- using make
- building podman
- test your changes locally
Signed-off-by: Hervé Beraud <hberaud@redhat.com>

[skip ci]Introduce how to start to hack on libpod.

---

vendor.conf
vendor/github.com/containers/buildah/README.md
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/new.go
vendor/github.com/containers/buildah/pkg/cli/common.go
vendor/github.com/containers/buildah/pkg/secrets/secrets.go
vendor/github.com/containers/buildah/pull.go
vendor/github.com/containers/buildah/run.go
vendor/github.com/containers/buildah/unshare/unshare_unsupported.go
vendor/github.com/containers/buildah/vendor.conf

This release updates buildah to use containers/image v1.5
Which fixes a crash issue when pulling container images.

Vendor in buildah v1.7.1

---

RELEASE_NOTES.md

If we land anything else before cutting a tag we'll need to update more, so make sure the last few PRs are merged before we merge this.

Update release notes for v1.1.0

---

README.md
remote_client.md

addition of a remote-client readme.

podman remote-client readme

---

cmd/podman/rmi.go
pkg/adapter/runtime.go
pkg/adapter/runtime_remote.go

Fix build for non-Varlink-tagged Podman

---

pkg/secrets/secrets.go

When using a user namespace, we create the mount point under
`mountPrefix` so that the uid != 0 can access that directory.
Change the addFIPSModeSecret code to honor that, and also ensure we
are creating the directories with the right ownership.

secrets: fix fips-mode with user namespaces

---

cmd/podman/cliconfig/commands.go
cmd/podman/common.go
cmd/podman/create.go
cmd/podman/restart.go
cmd/podman/stop.go

Also add some extra debug information to help figure out what's going on when stop goes bad.

Fix ignored --stop-timeout flag to 'podman create'

---

docs/podman-container.1.md
docs/podman-image.1.md

No podman container ps command exists

---

CONTRIBUTING.md

[ci skip] Add critical note about skip-ci and merge bot

---

cmd/podman/play_kube.go

when podman generate kube runs, it names the pod based on the first
container it finds. the resulting yaml file is perfectly acceptable
in a kubernetes environment.  But when replaying the YAML file
with podman, we cannot have a container and pod with the same name.
therefore, we rename the pod if find a collision to name_pod.

rename pod when we have a name collision with a container

---

RELEASE_NOTES.md

Update release notes for v1.1.1

---

API.md
cmd/podman/commands.go
cmd/podman/errors.go
cmd/podman/errors_remote.go
cmd/podman/main.go
cmd/podman/stop.go
cmd/podman/varlink/io.podman.varlink
pkg/adapter/containers.go
pkg/adapter/containers_remote.go
pkg/adapter/runtime.go
pkg/adapter/runtime_remote.go
pkg/adapter/shortcuts/shortcuts.go
pkg/varlinkapi/containers.go

Support podman-remote stop container

---

cmd/podman/container.go
cmd/podman/pod_start.go
cmd/podman/system_prune.go

Minor stuff, but it corrects some errors in usage messages.

A few more usage-message tweaks

---

cmd/podman/common.go

Add missing short flag -l for run/create

---

RELEASE_NOTES.md

Update release notes for v1.1.2

---

Makefile
contrib/cirrus/integration_test.sh

Globally increase test timeout to 90-minutes

---

.cirrus.yml
Makefile
contrib/cirrus/integration_test.sh
contrib/cirrus/lib.sh
contrib/cirrus/packer/centos_setup.sh
contrib/cirrus/packer/fedora_setup.sh
contrib/cirrus/packer/rhel_setup.sh
contrib/cirrus/packer/ubuntu_setup.sh
contrib/cirrus/setup_environment.sh

***NOTE:*** THIS PR DISABLES TESTING ON RHEL

Cirrus: Add BATS package for all platforms

---

cmd/podman/kill.go
pkg/adapter/containers.go
pkg/adapter/containers_remote.go

Support podman-remote kill container(s)

---

cmd/podman/commands.go
cmd/podman/commands_remoteclient.go
cmd/podman/pod.go
cmd/podman/pod_stats.go
cmd/podman/pod_top.go
cmd/podman/varlink/io.podman.varlink
pkg/adapter/pods.go
pkg/adapter/pods_remote.go
pkg/varlinkapi/containers.go
pkg/varlinkapi/pods.go

this is the final enablement for the pod subcommand.  it includes the
ability to run podman-remote pod top and stats.

podman-remote pod top|stats

---

API.md
cmd/podman/commands.go
cmd/podman/main.go
cmd/podman/varlink/io.podman.varlink
cmd/podman/wait.go
pkg/adapter/containers.go
pkg/adapter/containers_remote.go
pkg/varlinkapi/containers.go

Implement podman-remote wait command and container subcommand

---

test/README.md
test/system/TODO.md

[ci skip] System-test: Begin list of needed high-level tests

---

troubleshooting.md

We have some bug reports about people moving containers storage to new
directories and this troubleshooter should help them fix this.

Add troublshoot information about SELinux labeling of containers/storage

---

libpod/container_internal_linux.go
libpod/runtime_pod_infra_linux.go

Fix a segfault and an issue where we were deleting the pod's /etc/hosts

Misc pod fixes

---

pkg/varlinkapi/system.go

Initialize field in InfoHost struct

---

libpod/runtime_img.go

When importing an image from a file somewhere, we already know how to download data from a URL to a file, so do the same for stdin, in case it's unexpectedly large.

Buffer stdin to a file when importing "-"

---

libpod/container_internal_linux.go

When mounting a tmpfs, runc attempts to make the directory it will be mounted at. Unfortunately, Golang's os.MkdirAll deals very poorly with symlinks being part of the path. I looked into fixing this in runc, but it's honestly much easier to just ensure we don't trigger the issue on our end.
Fixes BZ #1686610

Ensure that tmpfs mounts do not have symlinks

---

cmd/podman/varlink/io.podman.varlink

Link to InspectImage was broken.

Fix broken link in API.md

---

cmd/podman/top.go

minor typo fix in 'podman top' usage

---

cmd/podman/events.go
docs/podman.1.md

Add 'podman events' to podman(1)

---

cmd/podman/common.go
docs/podman-attach.1.md
docs/podman-create.1.md
docs/podman-run.1.md
docs/podman-start.1.md
utils/utils.go

* Updated documentation to match code
Fixes #1959

Corrected detach man pages and code comments

---

libpod/networking_linux.go

Closes: https://github.com/containers/libpod/issues/2642

slirp4netns: use --disable-host-loopback

---

libpod/networking_linux.go

Older versions of slirp4netns do not have the --disable-host-loopback
flag.
Remove the check once we are sure the updated version is available
everywhere.

rootless: fix CI regression when using slirp4netns

---

contrib/cirrus/setup_environment.sh

cirrus: upgrade slirp4netns

---

test/e2e/info_test.go

Fix a timeout issue in one of our tests.
More commits potentially coming as I look at other flakes

Fix a few flakes

---

cmd/podman/cliconfig/config.go
cmd/podman/runlabel.go
completions/bash/podman
docs/podman-container-runlabel.1.md

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1677908

Add --replace flag to "podman container runlabel"

---

docs/podman-ps.1.md

example added in man page as suggested in review  https://github.com/containers/libpod/pull/2664#pullrequestreview-215007446
Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

output of port grouping in ps command added as example

---

.cirrus.yml
contrib/cirrus/setup_environment.sh

Cirrus: Update VM Cache images

---

docs/podman-run.1.md

Signed-off-by: Cleber Rosa <crosa@redhat.com>

docs/podman-run.1.md: remove extra whitespace in --read-only

---

docs/podman-logs.1.md

Also modify man page to talk about podman-container-logs as well as podman-logs.

Fix man page to mention race condition

---

cmd/podman/ps.go

Make "stopped" a valid state that maps to "exited"

---

cmd/podman/cliconfig/config.go
cmd/podman/commands.go
cmd/podman/system_df.go
completions/bash/podman
docs/podman-system-df.1.md
docs/podman-system.1.md
test/e2e/system_df_test.go
transfer.md

implement `podman system df` command showing podman disk usage
```
$ bin/podman system df
TYPE            TOTAL   ACTIVE   SIZE    RECLAIMABLE
Images          6       2        281MB   168MB (59%)
Containers      3       1        0B      0B (0%)
Local Volumes   1       1        22B     0B (0%)
```

podman system df- show podman disk usage

---

.cirrus.yml
contrib/gate/entrypoint.sh

Cirrus: Verify manpages for all subcommands exist

---

test/system/200-pod-top.bats

Sigh; disable pod-top test, it's unreliable (#2780)

---

cmd/podman/system_df.go

system df: reject invalid arguments

---

libpod/oci.go
libpod/runtime.go
pkg/util/utils.go

it prevents the directory to be auto pruned, according to the XDG specifications.

rootless: set sticky bit on rundir

---

vendor.conf
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/unshare/unshare.go

Vendor Buildah 1.7.2

---

RELEASE_NOTES.md

Update release notes for v1.2.0

---

docs/podman-inspect.1.md

Signed-off-by: Robert P. J. Day <rpjday@crashcourse.ca>

docs/podman-inspect.1.md: add missing option hyphen for "-t"

---

README.md

Update README with current version

---

Dockerfile.fedora

Cirrus: Update F28 -> F29 container image

---

cmd/podman/run_test.go

Hey there, I would skip these tests if not supported by the running platform.

Update run_test to be more robust

---

test/e2e/healthcheck_run_test.go

rootless: enable healthcheck

---

contrib/cirrus/rootless_test.sh
test/e2e/libpod_suite_remoteclient_test.go
test/e2e/run_ns_test.go
test/e2e/run_userns_test.go

test: enable userns and remote e2e tests for rootless

---

cmd/podman/commands.go
cmd/podman/commands_remoteclient.go
cmd/podman/healthcheck.go
completions/bash/podman
docs/podman-healthcheck-run.1.md
libpod/container.go
libpod/healthcheck.go

(minor): fix misspelled 'Healthcheck'

---

commands.md

Add a pointer to the script and asciinema cast for the
images command to the commands.md file.

Add demo script and cast to images

---

README.md

Fix README.md -> rootless.md link

---

cmd/podman/commands.go
cmd/podman/generate.go
cmd/podman/generate_kube.go
cmd/podman/main.go
cmd/podman/shared/container.go
cmd/podman/varlink/io.podman.varlink
pkg/adapter/runtime.go
pkg/adapter/runtime_remote.go
pkg/varlinkapi/generate.go

Allow the ability to generate kube YAML from the podman remote-client.

podman-remote generate kube

---

cmd/podman/pull.go
test/e2e/pull_test.go

Closes: https://github.com/containers/libpod/issues/2785
Closes: https://github.com/containers/libpod/issues/2710

pull: fix a couple of issues

---

install.md

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>
This is (another) small PR to add the install of uidmap for Ubuntu users. Without it, the user will see a warning about not having a range of uid/gids:
```bash
$ podman pull docker://fedora:latest
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding subids 
Trying to pull docker://fedora:latest...Getting image source signatures
Copying blob 01eb078129a0 done
Copying config d09302f77c done
Writing manifest to image destination
Storing signatures
ERRO[0010] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: there might not be enough IDs available in the namespace (requested 192:192 for /run/systemd/netif): lchown /run/systemd/netif: …
```

Adding uidmap to install steps for ubuntu

---

libpod/container_internal_linux.go

The SELinux label for the CRIU dump.log was explicitly set in Podman.
The label for the restore.log, however, not. This just moves the code
to label the log file into a function and calls that functions during
checkpoint and restore.
Signed-off-by: Adrian Reber <areber@redhat.com>

Use the same SELinux label for CRIU log files

---

cmd/podman/play_kube.go
cmd/podman/shared/create.go

Also put Environment variable parsing from image data into a helper function

Incorporate image and default environment variables in play kube

---

cmd/podman/play_kube.go

Both File and FileOrCreate options are supported.

Add File mounts to play kube

---

contrib/cirrus/lib.sh
contrib/cirrus/setup_environment.sh

Also, undo oooooold runc package hack

Cirrus: Temp. override container-selinux on F29

---

README.md

Signed-off-by: alsadi <alsadi@gmail.com>

point to 3rd party tools for compose

---

libpod/events.go
libpod/events/config.go
libpod/events/events.go
libpod/events/events_linux.go
libpod/events/journal_linux.go
libpod/events/logfile.go
libpod/runtime.go
libpod/runtime_renumber.go

Also, re-add locking to file eventer Write() to protect against concurrent events.

Add System event type and renumber, refresh events

---

contrib/cirrus/setup_environment.sh

remove manual install of libsystemd-dev

---

vendor.conf
vendor/github.com/containers/buildah/add.go
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/chroot/run.go
vendor/github.com/containers/buildah/chroot/selinux.go
vendor/github.com/containers/buildah/commit.go
vendor/github.com/containers/buildah/image.go
vendor/github.com/containers/buildah/imagebuildah/build.go
vendor/github.com/containers/buildah/imagebuildah/chroot_symlink.go
vendor/github.com/containers/buildah/imagebuildah/errors.go
vendor/github.com/containers/buildah/pkg/cli/common.go
vendor/github.com/containers/buildah/pkg/parse/parse.go
vendor/github.com/containers/buildah/pkg/unshare/unshare.go
vendor/github.com/containers/buildah/pkg/unshare/unshare_unsupported.go
vendor/github.com/containers/buildah/run.go
vendor/github.com/containers/buildah/selinux.go
vendor/github.com/containers/buildah/util/util.go
vendor/github.com/containers/buildah/vendor.conf
vendor/github.com/containers/storage/drivers/overlay/overlay.go

Should fix the issue on Windows platform.
Lots of other fixes and enhancements.

Vendor in latest containers/storage and containers/buildah

---

vendor/github.com/containers/psgo/go.mod
vendor/github.com/fsouza/go-dockerclient/go.mod
vendor/github.com/hashicorp/errwrap/go.mod
vendor/github.com/hashicorp/go-multierror/go.mod
vendor/github.com/stretchr/testify/go.mod
vendor/golang.org/x/text/go.mod
vendor/gopkg.in/yaml.v2/go.mod

correct upstream vndr issues

---

.cirrus.yml

Cirrus: Collect audit log on success and failure

---

docs/tutorials/podman_tutorial.md

Obsolete #2958 so we can start clearing the queue of open PRs

Use 'sudo tee' in tutorial so install works as non-root

---

README.md

We didn't really talk about it at all, and it's an exciting feature

Add details on rootless Podman to the readme

---

cmd/podman/common.go
cmd/podman/shared/create.go
cmd/podman/shared/intermediate.go
completions/bash/podman
docs/podman-create.1.md
docs/podman-run.1.md
pkg/spec/createconfig.go
pkg/spec/spec.go
test/e2e/run_test.go

similar to https://github.com/containers/buildah/pull/1525
As-is, the command line flag does not work, but I've been pulling out my hair trying to make it work.  If I remove the option and do the new thing unconditionally, it works as expected.

Auto http proxy

---

cmd/podman/common.go
docs/podman-create.1.md
docs/podman-run.1.md

http-proxy: improve docs

---

docs/podman-create.1.md
docs/podman-run.1.md

Replaces #2988.  Want to get this is for v1.3.

docs: Fix typo "healthcheck" pt2

---

install.md

- related to issue #3030
- including pointer to new section in README.md provided by #3038

add arch linux rootless hints to install.md

---

cmd/podman/build.go
vendor.conf
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/imagebuildah/build.go
vendor/github.com/containers/buildah/pkg/cli/common.go
vendor/github.com/containers/buildah/pkg/parse/parse.go
vendor/github.com/containers/buildah/run_linux.go
vendor/github.com/containers/buildah/util/util.go
vendor/github.com/openshift/imagebuilder/vendor.conf

Bump Buildah to v1.8.1, ImageBuilder to v1.1.0

---

vendor.conf
vendor/github.com/containers/storage/drivers/driver.go
vendor/github.com/containers/storage/drivers/overlay/overlay.go
vendor/github.com/containers/storage/drivers/vfs/driver.go
vendor/github.com/containers/storage/layers.go

Update c/storage to v1.12.6

---

docs/libpod.conf.5.md

Document events logger options in libpod.conf manpage

---

vendor.conf
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/pkg/parse/parse.go
vendor/github.com/containers/buildah/vendor.conf

Bump to Buildah v1.8.2

---

RELEASE_NOTES.md

Update release notes for 1.3.0 release

---

.cirrus.yml
API.md
hack/tree_status.sh

Cirrus: Add check for make varlink_api_generate

---

pkg/systemdgen/systemdgen_test.go

it looks like i forgot to add the unit tests for generate systemd

add unit tests for generate systemd

---

libpod/healthcheck_linux.go

clean up the reporting of a benign error that can occur when a container
is first stopped and then removed.

healthcheck benign error

---

vendor.conf
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/opts.go
vendor/github.com/containerd/cgroups/paths.go

Update containerd/cgroups to 4994991857f9b0ae

---

cmd/podman/events.go

make it uppercase as all the other ones.

podman: fix events help string

---

.cirrus.yml
Makefile
contrib/cirrus/integration_test.sh
contrib/cirrus/setup_environment.sh
contrib/spec/podman.spec.in
test/e2e/info_test.go
test/e2e/libpod_suite_remoteclient_test.go

split remote tests from distro tests

---

RELEASE_NOTES.md

Release notes for 1.3.1

---

RELEASE_NOTES.md

More release notes for 1.3.1

---

.cirrus.yml
contrib/cirrus/required_host_ports.txt

Cirrus: Confirm networking is working

---

README.md
install.md

there were some leftover unattended to installation guides

Fixup conmon documentation

---

pkg/spec/spec.go

Don't set apparmor if --priviliged

---

OWNERS

@jwhonce is one of the core contributors to remote client work, so let's make sure he has the ability to merge things.

Add Jhon Honce (@jwhonce on github) to OWNERS

---

cmd/podman/images.go
test/e2e/images_test.go

Added test to avoid future regressions
Fix #3163

Minor fix filtering images by label

---

hack/get_ci_vm.sh

Useful for accessing it from other terminals.

hack: Display IP address of VM from script

---

API.md
docs/varlink/apidoc.go

the varlink doc generator was ignoring all nullable types when
generating its documentation

document nullable types

---

test/e2e/cp_test.go

Instead of using the working directory, use a subdirectory of the temporary directory created for the individual test, to prevent a potential EEXIST for shared working directory.

Fix a potential flake in the tests for podman cp

---

install.md

Add more Debian dependencies that I needed in Debian 9.9.

Update install.md ostree Debian dependencies.

---

.copr/prepare.sh
Dockerfile
Dockerfile.centos
Dockerfile.fedora
contrib/spec/podman.spec.in

bump conmon to v0.2.0

---

RELEASE_NOTES.md
contrib/spec/podman.spec.in
version/version.go

As the title says. Targetted against v1.3 branch

Release v1.3.2

---

docs/podman-build.1.md

Added same dns flags from buildah documentation to podman
documents https://github.com/containers/libpod/issues/2755
Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

add dns flags to docs

---

pkg/spec/storage.go

Do not set tmpcopyup on /dev

---

pkg/adapter/containers_remote.go
pkg/varlinkapi/attach.go
pkg/varlinkapi/transfers.go

Fix for the varlink upgraded calls.

Fix for varlink upgrade connections

---

README.md
test/e2e/cp_test.go

Tests against master are broken. Let's make them not broken.
First change is a small readme fix to convince CI to run said tests.

Small fix to readme to force tests to run

---

docs/podman.1.md

Manpage: fix podman-varlink and -version mixup

---

pkg/rootless/rootless_linux.c

we are allowed to use only signal safe functions between a fork of a
multithreaded application and the next execve.  Since setenv(3) is not
signal safe, block signals.  We are already doing it for creating a
new namespace.
This is mostly a cleanup since reexec_in_user_namespace_wait is used
only only to join existing namespaces when we have not a pause.pid
file.

rootless: block signals on re-exec

---

pkg/varlinkapi/virtwriter/virtwriter.go

pkg/varlinkapi/virtwriter/virtwriter.go: simplify func Reader

---

cmd/podman/cp.go
vendor.conf
vendor/github.com/containers/buildah/add.go
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/chroot/run.go
vendor/github.com/containers/buildah/config.go
vendor/github.com/containers/buildah/imagebuildah/build.go
vendor/github.com/containers/buildah/imagebuildah/util.go
vendor/github.com/containers/buildah/pkg/chrootuser/user.go
vendor/github.com/containers/buildah/pkg/chrootuser/user_basic.go
vendor/github.com/containers/buildah/pkg/chrootuser/user_linux.go
vendor/github.com/containers/buildah/pkg/secrets/secrets.go
vendor/github.com/containers/buildah/pkg/unshare/unshare.go
vendor/github.com/containers/buildah/run_linux.go

Vendor Buildah v1.8.3

---

.cirrus.yml

Cirrus: Disable testing on F28 (EOL)

---

cmd/podman/main_remote.go

remove -c for podman remote global options

---

RELEASE_NOTES.md

Update release notes for v1.4.0

---

.cirrus.yml
contrib/cirrus/README.md

:smile: Actually, just docs and task-dependency cleanup then removing a long-disused "optional" task.

Cirrus: Minor cleanup of dependencies and docs

---

pkg/rootless/rootless_linux.go

closes #3284
Signed-off-by: Cameron Nemo <cnemo@tutanota.com>

Fix cgo includes for musl

---

contrib/podmanimage/upstream/Dockerfile

The upstream/Dockerfile had a few issues that this
cleans up.  A few files were misplaced, wrong installs
and removes.  This corrects those issues.

Touchup upstream Dockerfile

---

CONTRIBUTING.md

docs: Add CI section and links

---

.cirrus.yml
Dockerfile
Dockerfile.centos
Dockerfile.fedora
contrib/cirrus/packer/fedora_setup.sh
contrib/cirrus/packer/ubuntu_setup.sh
contrib/gate/Dockerfile

Remove source-built buildah from CI

---

libpod/container_inspect.go
libpod/options.go

Add OCI Runtime path, and change our Mounts output to match Docker.
Probably could use a test or two, will add tomorrow.

Further fixes for podman inspect

---

CONTRIBUTING.md
README.md
RELEASE_NOTES.md

Also, update README with latest release

Update 1.4.0 release notes with ID -> Id in inspect

---

.cirrus.yml
.copr/prepare.sh
Dockerfile
Dockerfile.centos
Dockerfile.fedora
contrib/spec/podman.spec.in

bump conmon to 0.3.0

---

docs/podman-exec.1.md
docs/podman-run.1.md
docs/podman.1.md

Also fix podman run exit codes to show real messages when failures
happen.

Document exit codes for podman exec

---

RELEASE_NOTES.md

Update release notes for 1.4.1

---

test/e2e/logs_test.go

discussion here:
https://github.com/containers/libpod/issues/3325#issuecomment-502214492

test: add test for logs -f

---

API.md
CONTRIBUTING.md
cmd/podman/varlink/io.podman.varlink
docs/podman.1.md

I have spoted some typos in few *.md files.

Fix some typos in few *.md files

---

libpod/image/pull.go

Adds a warning if another image with the same name exists and is going to be untagged
fixes #2821

Add warning while untagging an image podman-load

---

cmd/podman/commit.go
cmd/podman/shared/container.go
cmd/podman/shared/container_inspect.go
cmd/podman/system_df.go
docs/podman-build.1.md
docs/podman-commit.1.md
docs/podman-create.1.md
docs/podman-generate-kube.1.md
docs/podman-run.1.md
test/utils/utils.go

cmd, docs, test: fix some typos

---

vendor.conf
vendor/github.com/containers/buildah/buildah.go
vendor/github.com/containers/buildah/run_linux.go

Bump Buildah to v1.9.0

---

RELEASE_NOTES.md

Update release notes for Podman 1.4.2

---

.cirrus.yml
Dockerfile.fedora
contrib/cirrus/README.md
contrib/cirrus/integration_test.sh
contrib/cirrus/lib.sh
contrib/cirrus/packer/cloud-init/fedora/cloud-init.service
contrib/cirrus/packer/fedora_base-setup.sh
contrib/cirrus/packer/libpod_base_images.yml
contrib/cirrus/packer/libpod_images.yml
contrib/cirrus/setup_environment.sh
contrib/gate/Dockerfile
hack/get_ci_vm.sh
test/install/Dockerfile.Fedora

Test and incorporate new F30 image and a fix for a very ugly google vs cloud-init race post-build.

Cirrus F30

---

test/test_podman_build.sh

Update build test to include test for RUN with a priv'd command.
Not part of CI.
Signed-off-by: TomSweeneyRedHat  <tsweeney@redhat.com>

Add RUN with priv'd command build test

---

README.md

Mostly I want to fire the CI and see if master if passing

Minor roadmap adjustment in README

---

docs/tutorials/rootless_tutorial.md

First pass of the rootless tutorial.  This may be come the basis
for a User Guide of the same.

First pass rootless tutorial

---

libpod/boltdb_state_internal.go

If there are missing fields, we still require a commit, but that should not happen often.

Make configuration validation not require a DB commit

---

README.md

Really I just want to fire the CI. But add some missing periods to make this section of the readme consistent.

Add some missing periods to the readme

---

.cirrus.yml
.copr/prepare.sh
Dockerfile
Dockerfile.centos
Dockerfile.fedora
contrib/spec/podman.spec.in

Update conmon to include attach socket unlink

---

cmd/podman/exec.go
docs/podman-exec.1.md
docs/podman-run.1.md
docs/podman.1.md
libpod/boltdb_state.go
libpod/boltdb_state_internal.go
libpod/container_api.go
vendor.conf
vendor/github.com/containers/storage/drivers/aufs/aufs.go
vendor/github.com/containers/storage/drivers/btrfs/btrfs.go
vendor/github.com/containers/storage/drivers/devmapper/driver.go
vendor/github.com/containers/storage/drivers/driver.go
vendor/github.com/containers/storage/drivers/overlay/overlay.go
vendor/github.com/containers/storage/drivers/vfs/driver.go
vendor/github.com/containers/storage/drivers/windows/windows.go
vendor/github.com/containers/storage/drivers/zfs/zfs.go
vendor/github.com/containers/storage/store.go

Backports for the Openstack team. Currently missing a revendor of c/storage. Trying to figure out how to handle that.

Openstack backports

---

RELEASE_NOTES.md

Update release notes for 1.4.3 release

---

contrib/spec/podman.spec.in
version/version.go

Bump to v1.0.2

---

RELEASE_NOTES.md

Update release notes for 1.4.4

---

libpod/stats.go
pkg/cgroups/cgroups.go
pkg/cgroups/cpu.go

a fix for showing the CPU stats when using cgroupsv2

cgroups v2: fix cpu time

---

README.md

Bump current version in README

---

cmd/podman/ps.go

when not using --size with ps, we do not need a store.  this should make
ps more effecient when the system is under heavy load.
also, prune unused ps functions as no longer needed.

ps should use nostore when possible

---

cmd/podman/build.go
cmd/podman/cp.go
cmd/podman/history.go
cmd/podman/images.go
cmd/podman/pod_kill.go
cmd/podman/pod_stats.go
cmd/podman/pull.go
cmd/podman/run.go
cmd/podman/shared/container.go
cmd/podman/shared/container_inspect.go
cmd/podman/tree.go
libpod/container_internal.go
libpod/image/pull.go
libpod/lock/shm/shm_lock.go
pkg/hooks/0.1.0/hook.go
pkg/hooks/1.0.0/when_test.go
pkg/logs/logs.go
pkg/rootless/rootless_linux.go
pkg/sysinfo/sysinfo_test.go
pkg/tracing/tracing.go
pkg/trust/trust.go

the results of a code cleanup performed by the goland IDE.

trivial cleanups from golang

---

test/e2e/run_cleanup_test.go
test/e2e/run_staticip_test.go

attempts to correct three of our flakey integration tests

fix integration flake tests

---

test/e2e/common_test.go

When we're waiting for a container to come up with healthchecks, and it's not even running, there's no point to waiting further. Instead, let's restart the container and continue waiting.
This may fix some flakes we're seeing with 'podman port' tests. Then again, all the tests there seem to fail, not just a single test flaking - so I bet there's some other underlying cause.

Restart failed containers in tests

---

cmd/podman/pod_ps.go
cmd/podman/ps.go
cmd/podman/shared/container.go
cmd/podman/shared/create.go
cmd/podman/shared/create_cli.go
cmd/podman/stats.go
cmd/podman/tree.go
libpod/container.go
libpod/container_api.go
libpod/container_graph.go
libpod/container_inspect.go
libpod/container_internal.go
libpod/events/filters.go
libpod/events/nullout.go
libpod/healthcheck_linux.go
libpod/image/image.go
libpod/image/pull.go
libpod/kube.go
libpod/logs/log.go
libpod/networking_linux.go
libpod/oci.go
libpod/oci_linux.go
libpod/options.go
pkg/adapter/checkpoint_restore.go
pkg/adapter/containers.go
pkg/adapter/pods.go
pkg/adapter/runtime.go
pkg/adapter/terminal_linux.go
pkg/netns/netns_linux.go
pkg/rootless/rootless_linux.go

clean up and prepare to migrate to the golangci-linter

golangci-lint pass number 2

---

pkg/spec/spec.go

when the container is running in a user namespace, check if gid=5 is
available, otherwise drop the option gid=5 for /dev/pts.

spec: fix userns with less than 5 gids

---

libpod/runtime.go

Ensure we have a valid store when we refresh

---

pkg/spec/config_linux.go
pkg/spec/spec.go
test/e2e/run_device_test.go

when --privileged is specified, add all the devices that are usable by
the user.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1730773

rootless: add host devices with --privileged

---

libpod/container_api.go

Backport Exec memory leak fix

---

contrib/spec/podman.spec.in
version/version.go

Bump to v1.0.3

---

libpod/image/pull.go

Currently the pull message on failure is UGLY.  This patch removes a lot of the noice
when pulling an image from multiple registries to make the user experience better.
Our current messages are way too verbose and need to be dampened down.  Still has
verbose mode if you turn on log-level=debug.
Currently if pull ubi8 in fedora you see:
```
$ podman pull ubi8
Trying to pull docker.io/library/ubi8...
ERRO[0000] Error pulling image ref //ubi8:latest: Error initializing source docker://ubi8:latest: Error reading manifest latest in docker.io/library/ubi8: errors:
denied: requested access to the resource is denied
unauthorized: authentication required 
Failed
Trying to pull registry.fedoraproject.org/ubi8...
ERRO[0001] Error pulling image ref …
```

Cleanup Pull Message

---

pkg/varlinkapi/images.go

Remove debug message

---

cmd/podman/shared/container.go

I think I got most of it, let me know if you see something you don't like.

Fixes issue #3577.

---

cmd/podman/build.go

fix build --network=container

---

install.md

install.md: mention all build tags

---

.gitignore
Makefile
docs/links/podman-container-cp.1
docs/links/podman-container-init.1
docs/links/podman-help.1
docs/podman-remote.1.md
docs/podman-remote.sh

Created shell script to automatically compile remote-only docs & rename
Added `make brew-pkg` to automatically package files needed for homebrew
Add missing docs
Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

Documenation & make tar.gz for remote

---

cmd/podman/shared/create.go
docs/podman-create.1.md
docs/podman-run.1.md
libpod/container_internal_linux.go
libpod/options.go
pkg/adapter/pods.go
pkg/namespaces/namespaces.go
pkg/spec/createconfig.go
pkg/spec/spec.go
test/e2e/run_userns_test.go

allow to join the user namespace of another container.
Closes: https://github.com/containers/libpod/issues/3629

podman: support --userns=ns|container

---

commands.md

Update the links for the asciinema casts and the demo for the
`podman pause` and `podman unpause` commands on the commands.md
page.

Update pause/unpause video links and demo

---

libpod/stats.go

* Fixes #3664.
Signed-off-by: Pete Johanson <peter@peterjohanson.com>

Build fix for 32-bit systems.

---

test/e2e/common_test.go

Check the exit codes of pull, save and inspect to avoid masking those
errors.  We've hit a case where a corrupted/broken image has been pulled
which then surfaced for some tests later.

e2e test: check exit codes for pull, save, inspect

---

Makefile

Go 1.13.x isn't sensitive to the GO111MODULE environment variable
causing builds to not use the vendored sources in ./vendor. Force builds
of module-supporting go versions to use the vendored sources by setting
-mod=vendor.
Verified in a fedora:rawhide container.

go build: use `-mod=vendor` for go >= 1.11.x

---

docs/podman-events.1.md
libpod/events/config.go
pkg/adapter/runtime.go
pkg/adapter/runtime_remote.go
test/e2e/events_test.go

Enable podman events to format the output as jsonlines
close #3159 

podman events format json

---

libpod/container_internal.go

Old versions of conmon have a bug where they create the exit file before
closing open file descriptors causing a race condition when restarting
containers with open ports since we cannot bind the ports as they're not
yet closed by conmon.
Killing the old conmon PID is ~okay since it forces the FDs of old
conmons to be closed, while it's a NOP for newer versions which should
have exited already.

container stop: kill conmon

---

pkg/varlinkapi/images.go

when using build, require a "more" connection to get logs.
when pulling a non-existent image, do not crash varlink connection.
Fixes: #3714
Fixes: #3715

various fixes for varlink endpoints

---

.cirrus.yml

Cirrus: Adjust destination branch name

---

cmd/podman/rm.go
completions/bash/podman
contrib/spec/podman.spec.in
docs/podman-rm.1.md
libpod/runtime_cstorage.go
version/version.go

Backport rm --storage and bump to v1.0.4

Bump to v1.0.4

---

libpod/container_internal_linux.go
libpod/networking_linux.go
libpod/oci_internal_linux.go
libpod/oci_linux.go
libpod/runtime_pod_infra_linux.go
pkg/netns/netns_linux.go
pkg/spec/createconfig.go

This reverts commit 80dcd4bebcdc8e280f6b43228561d09c194c328b.

Revert "rootless: Rearrange setup of rootless containers"

---

libpod/define/errors.go
libpod/runtime.go

Now, when a user's conmon is out of date, podman will tell them

Add conmon probe to runtime construction

---

RELEASE_NOTES.md

Add release notes for v1.5.0

---

cmd/podman/shared/create.go

Improve dns-search validation, empty domains now return an error

---

docs/podman-build.1.md

Touchup the build man page with a few options
and extra verbiage from Buildah's variant.

Touch up build man page

---

contrib/cirrus/packer/fedora_setup.sh

Cirrus: Enable updates-testing repo for Fedora

---

pkg/rootless/rootless_linux.c

Fix a couple of errors descovered by coverity

---

.cirrus.yml
contrib/cirrus/setup_environment.sh
pkg/adapter/containers.go
test/e2e/exec_test.go
test/e2e/libpod_suite_remoteclient_test.go
test/e2e/libpod_suite_test.go
test/e2e/run_exit_test.go
test/e2e/run_test.go
test/e2e/start_test.go

cirrus: run tests with crun

---

Makefile
install.md

Add brew installation instructions to docs & small fix to brew makefile
Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

Homebrew installation in install.md

---

contrib/spec/podman.spec.in
vendor.conf
vendor/github.com/containers/storage/drivers/overlay/overlay.go
version/version.go

Backport some changes to c/storage to fix a potential unusable container store if the system restarts during certain c/storage ops.

Bump to v1.0.5

---

libpod/runtime_pod_infra_linux.go

Fixes https://github.com/containers/libpod/issues/3732
Signed-off-by: Chen Zhiwei <zhiweik@gmail.com>

Set Pod hostname as Pod name

---

.cirrus.yml
contrib/cirrus/networking.sh
contrib/cirrus/required_host_ports.txt

Cirrus: Confirm networking more

---

cmd/podman/cliconfig/config.go
cmd/podman/pod_create.go
libpod/options.go
libpod/pod.go
libpod/runtime_pod_infra_linux.go
libpod/runtime_pod_linux.go
pkg/adapter/pods.go
test/e2e/play_kube_test.go

* set hostname in pod yaml file
* set --hostname in pod create command
Fixes https://github.com/containers/libpod/issues/3732
Follow up PR of: https://github.com/containers/libpod/pull/3818
Signed-off-by: Chen Zhiwei <zhiweik@gmail.com>

Allow customizing pod hostname

---

docs/podman-build.1.md
docs/podman-create.1.md
docs/podman-run.1.md
go.mod
go.sum
test/e2e/run_selinux_test.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/modules.txt

Add tests to make sure users can change file types

Add support & documentation to run containers with different file types

---

.github/ISSUE_TEMPLATE.md

Issue template update to Include package info

---

.cirrus.yml
libpod.conf
libpod/oci_internal_linux.go
pkg/adapter/containers.go
test/e2e/exec_test.go
test/e2e/libpod_suite_remoteclient_test.go
test/e2e/libpod_suite_test.go
test/e2e/run_exit_test.go
test/e2e/run_test.go
test/e2e/start_test.go

the crun development version implementation got some changes to make it behave like runc and pass all the e2e tests.

tests: enable all tests for crun

---

test/system/070-build.bats

The priv test added to the build test in June runs an 'apk'
command which, unavoidably, has to fetch stuff from the net.
This is slow and unreliable, and periodically leads to
timeout failures. Worse, when this happens, some sort of
invisible buildah-only container gets left behind that leads
to failures in subsequent tests when trying to reset to
known state.
Imperfect workaround: try a 240-second timeout (up from 60)
when running apk. As backup, add a custom teardown() which
attempts to force-remove all containers and any new images.

Flake fix: build test timeout

---

cmd/podman/shared/funcs.go
cmd/podman/varlink.go
libpod/oci.go
libpod/oci_internal_linux.go
libpod/oci_linux.go
libpod/runtime.go
pkg/util/utils_supported.go
pkg/util/utils_windows.go

Use GetRuntimeDir to setup auth.json for login

---

Dockerfile
Dockerfile.centos
Dockerfile.fedora

Dockerfile.*: bump CNI plugins commit

---

README.md

Adding the verbiage from the Buildah README.md
to Podmans.  Original PR by @vrothberg at:
https://github.com/containers/buildah/pull/1801/files

Touchup README with Buildah build usage

---

Dockerfile
Dockerfile.centos
Dockerfile.fedora

Dockerfile*: fix build for CNI plugins

---

cni/README.md
install.md
test/README.md

Update the CNI configuration instructions to line up with
the changes introduced in #3868.  Also do a bit less documentation
of the configuration and point to the GitHub project so we won't
get out of sync in the future.

Update cni config instructions

---

API.md
cmd/podman/shared/create.go
cmd/podman/varlink/io.podman.varlink
pkg/varlinkapi/images.go

* Improved error message
* Added documentation
* Updated messages to include missing data
This PR is required before it's peer can be merged in python-podman

Update varlink doc and code for images

---

.cirrus.yml
contrib/imgprune/entrypoint.sh

Cirrus: Enable VM image housekeeping

---

docs/links/podman-container-umount.1
docs/links/podman-container-unmount.1

This fixes an error when trying to read or cache (mandb) these manpages.
Signed-off-by: Ryan Whalen <rj.whalen@gmail.com>

Fix links to manpages

---

troubleshooting.md

Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1747933

docs: add note about failing rhel7 systemd on cgroups v2

---

.cirrus.yml
contrib/imgprune/entrypoint.sh

* One suggestion from Ed
* One un-workaround (issue fixed in Cirrus-CI since 78b0773f7d544e4fd28fc786f9a754e6352f8307

Cirrus: imgprune fixes

---

libpod/container_internal_linux.go

when cni plugins return a list of DNS servers to use, we should honor
them and they should be inserted to the "top" of the list of servers to
resolve with.  this is needed eventually for the dnsmasq cni plugin.

handle dns response from cni

---

test/system/030-run.bats

crun emits wildly different error messages than runc in
two cases:
podman run ... /no/such/path   (enoent)
podman run ... /etc            (trying to exec a directory)
Deal with it by getting the runtime from 'podman info' and,
if crun, changing what we expect.
There may be more tweaks needed to get system tests working
with crun, but right now podman rawhide is too broken to
have any hope of finding them all.

System tests: support for crun on f31/rawhide

---

README.md

Fixup README.md to give proper information

---

libpod/info.go
libpod/oci_linux.go
libpod/util.go
pkg/varlinkapi/system.go

We want to get podman info to tell us about the version of
the mount program to help us diagnose issues users are having.

Return information about mount_program (fuse-overlayfs)

---

mac_client.md

add doc explaining setup for podman on mac in current stage of dev
Signed-off-by: Ashley Cui <ashleycui16@gmail.com>

mac_client docs

---

libpod/image/prune.go

Podman is not the only user of containers/storage, and as such we cannot rely on our database as the sole source of truth when pruning images. If images do not show as in use from Podman's perspective, but subsequently fail to remove because they are being used by a container, they're probably being used by Buildah or another c/storage client.
Since the images in question are in use, we shouldn't error on failure to prune them - we weren't supposed to prune them in the first place.
Fixes: #3983

Do not prune images being used by a container

---

pkg/spec/storage.go

We identify and resolve conflicts in paths using destination path matches. We require exact matches, largely for performance reasons (we use maps to efficiently access, keyed by destination). This usually works fine, until you get mounts that are targetted at /output and /output/ - the same path, but not the same string.
Use filepath.Clean() aggressively to try and solve this.

Clean destination paths during mount generation

---

.cirrus.yml
Makefile
contrib/msi/podman.bat
contrib/msi/podman.wxs
docs/links-to-html.lua
docs/podman-remote.sh

* Update scipts to produce darwin and windows output
* Update batch file to re-direct help requests to browser
* Add pandoc filter for markdown to html links

Support podman-remote help on windows

---

libpod/runtime.go

fix trivial type for event logger

---

.cirrus.yml
contrib/cirrus/integration_test.sh

tests: use crun package

---

.cirrus.yml
contrib/cirrus/success.sh

Cirrus: Update podbot credentials

---

libpod/runtime.go

If a user upgrades to a machine that defaults to a cgroups V2 machine
and has a libpod.conf file in their homedir that defaults to OCI Runtime runc,
then we want to change it one time to crun.
runc as of this point does not work on cgroupV2 systems.  This patch will
eventually be removed but is needed until runc has support.

We need to convert libpod.conf files in user homedir for cgroupv2

---

docs/podman-events.1.md

Document the 'system' event types for 'podman events'

---

RELEASE_NOTES.md

Add release notes for new-in-RC2 changes

---

Dockerfile.fedora

Needed to update the CI images for #4090.

Dockerfile.fedora: install packages to build catatonit

---

docs/podman-derivative-api.md

https://github.com/debarshiray/toolbox/ was planning to vendor
libpod which I disagreed with.  Let's document the advantages/disadvantages
as they exist today.

docs/podman-derivative-api.md: New file

---

.cirrus.yml
contrib/cirrus/build_release.sh
contrib/cirrus/packer/fedora_setup.sh
contrib/cirrus/upload_release_archive.sh
contrib/upldrel/entrypoint.sh
hack/get_release_info.sh

Automate production of MSI release files

---

README.md

Add README note about security reporting process.

---

contrib/cirrus/README.md

Cirrus: VM Image accounting doc update

---

RELEASE_NOTES.md

Finalize release notes for v1.6.0 final

---

Dockerfile
Dockerfile.centos
Dockerfile.fedora
contrib/cirrus/packer/fedora_setup.sh
contrib/cirrus/packer/ubuntu_setup.sh
hack/install_catatonit.sh

Build catatonit

---

install.md

Original-author: @hugelgupf
Replaces: #4050

install.md: add libbtrfs-dev for Debian build

---

README.md

Podman 1.6.0 has been released, update the README

---

libpod/runtime_ctr.go

This ensures that containers that didn't require an evict will be dealt with normally, and we only break out evict for containers that refuse to be removed by normal means.

When evicting containers, perform a normal remove first

---

libpod/info.go
pkg/rootless/rootless_linux.go
pkg/rootless/rootless_unsupported.go

show uid_map in podman info
close #4067 

show uid_map in podman info

---

cmd/podman/shared/container.go
test/e2e/ps_test.go

it solves:
$ podman ps --format=json
null

container: initialize results list

---

pkg/spec/createconfig.go

For non-Podman users of Libpod, we don't want to force the exit command to use ARGV[0], which probably does not support a cleanup command.

Allow giving path to Podman for cleanup command

---

pkg/hooks/docs/oci-hooks.5.md

Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>

Fix sample's JSON syntax error in oci-hooks.5.md

---

RELEASE_NOTES.md

Add release notes for Podman 1.6.2

---

pkg/rootless/rootless_linux.go

use directly the definition in "syscall".

rootless: drop dependency on docker

---

RELEASE_NOTES.md

Finalize release notes for v1.6.2

---

libpod/runtime.go
pkg/rootless/rootless_linux.go
pkg/rootless/rootless_unsupported.go
troubleshooting.md

do not automatically enable lingering mode.
Closes: https://github.com/containers/libpod/issues/4224

rootless: do not enable lingering mode

---

cmd/podman/run.go
pkg/adapter/containers_remote.go
pkg/varlinkapi/attach.go
pkg/varlinkapi/virtwriter/virtwriter.go

Add ability to redirect bash for run -i

---

libpod/oci_conmon_linux.go

exec: remove unused var

---

Makefile
docs/rtd/Makefile
docs/rtd/make.bat
docs/rtd/source/conf.py
docs/rtd/source/index.rst

Initial checking for readthedocs

---

libpod/options.go

Closes: https://github.com/containers/libpod/issues/4332

rootless: raise an error with --network=

---

docs/podman-create.1.md
docs/podman-run.1.md

Mention how to pass multiple networks option, because it wasn't clear enough
Closes #4341

Add multiple networks explanation to docs

---

libpod/networking_linux.go

read the slirp4netns stderr and propagate it in the error when the
process fails.
Replace: https://github.com/containers/libpod/pull/4338/files

libpod: if slirp4netns fails, return its stderr

---

pkg/adapter/containers.go

Fix spelling mistakes

---

Makefile

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>

Makefile: fix embedding gitCommit

---

cmd/podman/import.go
pkg/adapter/containers_remote.go
pkg/network/subnet.go
test/e2e/create_test.go

just ran the autocorrect code corrections from goland and it found a few
nits.

goland autocorrections

---

.cirrus.yml

This should only be temporary, until #3901 is ready.

Cirrus: Disable F29 testing

---

cmd/podman/utils.go

Refactor test to prevent panic

---

.cirrus.yml

skips certain aspects of prs for testing.

[CI:DOCS] make docsonly prs

---

rootless.md

Update rootless shortcomings with cgroup V2 information

---

cmd/podman/shared/create.go

Unless explicitely overridden, check the image's OS and architecture
and throw an errors in case of a mismatch.

container create: os/arch check

---

libpod/config/config.go

if systemd is not available, use the file events logger backend.

config: use EventsLogger=file without systemd

---

docs/source/markdown/podman-create.1.md
docs/source/markdown/podman-run.1.md

Document other bind options on --volumes flag

---

pkg/serviceapi/handler_containers.go
pkg/serviceapi/handler_containers_create.go
pkg/serviceapi/types.go

enabling the base container create tests which allow us to get more into
the stop, kill, etc tests.

[CI:DOCS]enabled base container create tests

---

.gitignore
contrib/build_rpm.sh

- assure we use bash strict mode to avoid missing errors
- added untracked artifacts to gitignore

Improved build_rpm.sh

---

pkg/serviceapi/errors.go
pkg/serviceapi/handler_containers.go
pkg/serviceapi/types.go

[CI:DOCS] apiv2: error handling and container prune

---

install.md

https://github.com/containers/libpod/issues/1234

install.md: added slirp4netns dependency to ubuntu

---

pkg/adapter/containers.go

Ignore ErrCtrRemoved when removing a container

---

rootless.md

Documents: https://github.com/containers/libpod/issues/4619

Add comment on rootless containers creating device nodes

---

rootless.md

just a quick couple of grammar adjustments to a doc page.

Quick grammar touchup in rootless.md

---

Makefile

Fixes: #4632
Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>

Attempt to install go-md2man only if missing

---

pkg/rootless/rootless_linux.c

the renameat2 syscall might be defined in the C library but lacking
support in the kernel.
In such case, let it fallback to open(O_CREAT)+rename as it does on
systems lacking the definition for renameat2.
Closes: https://github.com/containers/libpod/issues/4570

rootless: add fallback for renameat2 at runtime

---

cmd/podman/tree.go
libpod/image/image.go
pkg/adapter/images.go
pkg/adapter/images_remote.go
pkg/api/handlers/containers_create.go
pkg/api/handlers/images.go
pkg/api/handlers/types.go
pkg/api/server/register_images.go
pkg/util/utils.go

[CI:DOCS]enabled more tests

---

contrib/build_rpm.sh

- Fix bug failing to detect dnf in various locations
- Add missing sudo to yum/dnf calls
- Fix bug where pkg_manager may endup with a multi-line value

Improve dnf tests inside build_rpm.sh

---

pkg/api/handlers/containers.go
pkg/api/handlers/errors.go
pkg/api/handlers/generic/containers.go
pkg/api/handlers/generic/containers_create.go
pkg/api/handlers/generic/containers_stats.go
pkg/api/handlers/generic/containers_top.go
pkg/api/handlers/generic/images.go
pkg/api/handlers/generic/info.go
pkg/api/handlers/generic/ping.go
pkg/api/handlers/generic/system.go
pkg/api/handlers/generic/version.go
pkg/api/handlers/images.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/libpod/pods.go
pkg/api/handlers/utils/containers.go
pkg/api/server/register_containers.go
pkg/api/server/register_images.go
pkg/api/server/register_info.go
pkg/api/server/register_ping.go
pkg/api/server/register_pods.go
pkg/api/server/register_system.go
pkg/api/server/register_version.go

small refactor for libpod inclusion and began adding endpoints.

[CI:DOCS]libpod endpoints

---

cmd/podman/cliconfig/config.go
cmd/podman/network_create.go
completions/bash/podman
docs/source/markdown/podman-network-create.1.md
pkg/adapter/network.go
pkg/network/config.go
pkg/network/netconflist.go

add the ability to a macvlan network with podman network create.

macvlan networks

---

.cirrus.yml
cmd/podman/main_local.go
libpod/config/config.go
libpod/container_internal.go
libpod/events/journal_linux.go
libpod/events/logfile.go
libpod/runtime.go
libpod/volume_internal.go

We're looking to cut a 1.6.4 including a fresh c/storage version with Valentin's patches for RHEL/Cent 8.2. These are the backports we want for that branch.
This is NOT targetted against master and is NOT our next master release - this is a separate one for RHEL.

Backports for v1.6.4

---

libpod/config/config.go

In the process, make everything in the config omitempty in TOML. We're seeing issues (notably [1]) where, after rewriting libpod.conf, fields that were not previously populated are written - and, because they were not previously written, they are included as empty. This is unfortunately different from not included at all - it means that we need to assume the user explicitly unset the value, and we can't use defaults. Setting omitempty prevents us from writing things that should not be written as they were not set originally.
[1] https://github.com/containers/libpod/issues/4210

Re-add Fedora 31 migration code.

---

RELEASE_NOTES.md

We still want a c/storage revendor to pick up the pull fixes Valentin has been working on, which will require a small update here. Could do it in another PR.

Update release notes for 1.7.0

---

cmd/podman/build.go
go.mod
go.sum
libpod/runtime_img.go
pkg/adapter/runtime.go
pkg/adapter/runtime_remote.go
pkg/api/handlers/containers.go
pkg/api/handlers/events.go
pkg/api/handlers/generic/info.go
pkg/api/handlers/handler.go
pkg/api/handlers/images_build.go
pkg/api/handlers/types.go
pkg/api/server/handler_api.go
pkg/api/server/register_events.go
pkg/api/server/register_images.go
pkg/api/server/register_info.go
pkg/api/server/server.go
pkg/varlinkapi/images.go

* Include crypto libraries for future ssh work
* Add helpers to handler.go

[CI:DOCS]Implement /build and /events

---

install.md

Adds documentation about how to install dependencies on openSUSE
Signed-off-by: José Guilherme Vanz <jvanz@jvanz.com>

install.md: openSUSE dependencies

---

cmd/podman/shared/create_cli.go

drop the arbitrary limit of 4M for creating a container.
4M are not enough for runc to run, on Fedora it seems to require at least 7M, and it is too much for crun that requires less than 1 Mb.

libpod: drop arbitrary memory limit of 4M

---

pkg/api/handlers/libpod/containers.go
pkg/api/handlers/libpod/pods.go
pkg/api/server/register_ping.go
pkg/api/server/register_pods.go
pkg/bindings/containers.go
pkg/bindings/generate.go
pkg/bindings/healthcheck.go
pkg/bindings/info.go
pkg/bindings/mount.go
pkg/bindings/network.go
pkg/bindings/play.go
pkg/bindings/pods.go
pkg/bindings/port.go
pkg/bindings/search.go
pkg/bindings/version.go
pkg/bindings/volumes.go

[CI:DOCS]add bindings for golang

---

pkg/api/handlers/libpod/volumes.go
pkg/api/handlers/types.go
pkg/api/handlers/utils/errors.go
pkg/api/server/register_volumes.go
pkg/api/server/server.go
pkg/bindings/volumes.go

create, inspect, ls, prune, and rm

[CI:DOCS]add volume endpoints for libpod

---

test/system/130-kill.bats

When you open a FIFO for reading, but there's no writer, you hang.
This is just one of those obscure UNIXisms we all know but just
forget all too often.
My last PR was guilty of introducing such a condition; I caught
it by accident while testing other stuff. In short, the signal
container was doing 'echo DONE' as its last step, and we (BATS)
were reading the FIFO to check for it; but if the container
exited before we opened the FIFO for read, the open would hang.
This is not a hang that we can catch in the test: it would hang
the entire job forever. CI would presumably time out eventually,
but with no useful indication of the cause of the error.
Solution: use 'exec' to open the FIFO early and keep it open,
and use 'read -u FD' instead of 'read <$fifo': the former
reads from an open FD, …

Fix race condition in kill test leading to hang

---

pkg/api/handlers/libpod/healthcheck.go
pkg/api/server/register_healthcheck.go
pkg/api/server/server.go
pkg/bindings/healthcheck.go

wire up container healthchecks for the api.

[CI:DOCS]apiv2 healthcheck enablement

---

pkg/api/handlers/libpod/containers.go
pkg/api/server/register_containers.go
pkg/bindings/mount.go

via the api, allow ability to mount a container and list container
mounts.

[CI:DOCS]Add mount endpoints

---

pkg/api/handlers/images.go
pkg/api/server/register_images.go
pkg/bindings/search.go

add search endpoint with golang bindings

[CI:DOCS]Add search endpoint

---

pkg/api/handlers/containers.go
pkg/api/handlers/types.go
pkg/api/handlers/utils/errors.go
pkg/bindings/containers.go
pkg/bindings/network.go
pkg/network/config.go
pkg/network/files.go

also, add some initial error handling and convenience functions for
standard endpoints.

[CI:DOCS]add more network endpoints

---

pkg/bindings/containers.go
pkg/bindings/healthcheck.go
pkg/bindings/mount.go
pkg/bindings/network.go
pkg/bindings/pods.go
pkg/bindings/search.go
pkg/bindings/volumes.go

use the methods developed to make writing bindings less duplicative and
easier to use.

[CI:DOCS]use helper funcs for bindings

---

pkg/api/handlers/generic/containers.go
pkg/api/handlers/generic/containers_create.go
pkg/api/handlers/generic/containers_stats.go
pkg/api/handlers/generic/images.go
pkg/api/handlers/generic/info.go
pkg/api/handlers/generic/version.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/libpod/healthcheck.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/libpod/pods.go
pkg/api/handlers/libpod/volumes.go
pkg/api/handlers/utils/errors.go
pkg/api/server/register_volumes.go

begin to add return info and status codes for errors so that we can
review the apiv2

[CI:DOCS]add return info for prereview

---

pkg/api/handlers/generic/containers.go
pkg/api/handlers/generic/containers_create.go
pkg/api/handlers/generic/images.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/libpod/images.go
pkg/api/server/register_containers.go
pkg/api/server/register_images.go
pkg/bindings/mount.go

[CI:DOCS]first pass at adding swagger docs for api

---

commands.md

Updates the inspect command demo with an up to date
variant and adds a link to script that ran it.

Update demo for the inspect command

---

Makefile
pkg/api/handlers/libpod/pods.go
pkg/api/handlers/libpod/volumes.go
pkg/api/handlers/swagger.go
pkg/api/handlers/utils/errors.go
pkg/api/server/register_containers.go
pkg/api/server/register_images.go
pkg/api/server/register_pods.go
pkg/api/server/register_volumes.go
pkg/api/server/swagger.go

[CI:DOCS]update apiv2 documentation with swagger goods

---

docs/source/markdown/podman-create.1.md
docs/source/markdown/podman-exec.1.md
docs/source/markdown/podman-run.1.md

As discussed in https://github.com/containers/libpod/issues/4840

docs: --privileged docs completeness, consistency

---

pkg/api/handlers/generic/swagger.go
pkg/api/server/register_images.go
pkg/api/server/register_pods.go

[CI:DOCS]swagger corrections

---

pkg/api/handlers/generic/containers_stats.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/utils/handler.go
pkg/api/server/register_containers.go

This PR includes a series of commits to:
* Clean up.
* Comment the code.
* Fix errors and perform rigorous error checks instead of ignoring some.
* Enable the libpod endpoint (uses the generic one).
* Expect that the container is running and error out otherwise.

v2 api: stats improvements

---

Makefile
pkg/api/server/server.go

@baude @jwhonce @mheon @TomSweeneyRedHat @rhatdan PTAL

v2: don't block sigterm and add the service to `make binaries`

---

install.md

update install instructions for Debian, Raspbian and Ubuntu

---

contrib/cirrus/upload_release_archive.sh
docs/source/Reference.rst
docs/source/_static/api.html

[CI:DOCS]Connect API docs and RTD

---

docs/source/Reference.rst

[CI:DOCS] Correct link syntax

---

docs/source/Reference.rst

[CI:DOCS]static files end up in _static on rtd

---

pkg/api/handlers/images.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/libpod/pods.go
pkg/api/handlers/swagger.go
pkg/api/handlers/utils/errors.go
pkg/api/server/register_containers.go
pkg/api/server/register_images.go
pkg/api/server/register_pods.go

Tackling the first comments in the review pass.  More to come.

[CI:DOCS]First pass at review comments

---

.cirrus.yml

[CI:DOCS] Cirrus: Fix logic typo

---

RELEASE_NOTES.md

Update RELEASE_NOTES for v1.7.1

---

install.md

correct search-and-replace error

---

docs/source/markdown/podman-system-migrate.1.md

Signed-off-by: Robert P. J. Day <rpjday@crashcourse.ca>

markdown: remove erroneous spaces after '**'

---

README.md

1.7.0 should be referenced in the README.md

Update README.md to reference latest version

---

pkg/api/handlers/decoder.go

* Added helper function ParseDateTime() to allow parsing of filters

[CI:DOCS] Refactor time parsing to be more liberal in accepted values

---

docs/source/markdown/podman-system-prune.1.md

In addition to tweaking markdown, reword the explanation of
the "--volumes" option for clarity.
Signed-off-by: Robert P. J. Day <rpjday@crashcourse.ca>

docs: fix system-prune markdown; reword for clarity

---

docs/source/markdown/podman-history.1.md

Signed-off-by: Robert P. J. Day <rpjday@crashcourse.ca>

docs: add boolean values and defaults to "man podman-history" options

---

test/apiv2/00-TEMPLATE
test/apiv2/01-basic.at
test/apiv2/10-images.at
test/apiv2/20-containers.at
test/apiv2/30-volumes.at
test/apiv2/40-pods.at
test/apiv2/README.md
test/apiv2/test-apiv2

Initial framework for testing the version 2 (HTTP) API.
Includes a collection of tests for some of the existing
endpoints. Not all tests are currently passing.

Tests for API v2

---

Makefile
contrib/systemd/system/podman-docker.conf

Add link from docker.sock to podman.sock

---

docs/tutorials/remote_client.md

* Add PODMAN_VARLINK_BRIDGE examples.

Update remote client bridge documentation.

---

pkg/bindings/connection.go
pkg/bindings/test/common_test.go
pkg/bindings/test/images_test.go
pkg/bindings/test/test_suite_test.go

a recent refactor in the bindings broke the tests.  quick fixes to get them working again.

apiv2 binding test fixes

---

Makefile
contrib/systemd/README.md
install.md
pkg/api/Makefile

Fixed issue where lint was not run on CI, so we missed to prevent regressions.

Assure validate includes lint

---

pkg/bindings/test/common_test.go
pkg/rootless/rootless_linux.c

Bindingtestrootless

---

RELEASE_NOTES.md

We merged something else worthy of mention before the release notes PR landed

[CI:DOCS] Minor update to release notes

---

cmd/podman/service.go
pkg/api/handlers/containers.go
pkg/api/handlers/containers_attach.go
pkg/api/handlers/containers_top.go
pkg/api/handlers/generic/containers.go
pkg/api/handlers/generic/containers_stats.go
pkg/api/handlers/generic/images.go
pkg/api/handlers/handler.go
pkg/api/handlers/images.go
pkg/api/handlers/libpod/containers.go
pkg/api/handlers/libpod/healthcheck.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/libpod/networks.go
pkg/api/handlers/libpod/pods.go
pkg/api/handlers/libpod/volumes.go
pkg/api/handlers/utils/containers.go
pkg/api/handlers/utils/handler.go
pkg/api/server/server.go
pkg/bindings/connection.go
pkg/bindings/test/images_test.go

the api needs to account for image input where the image is encoded as a fqd image name.

fix longname handling for bindings

---

changelog.txt
contrib/spec/podman.spec.in
version/version.go

Bump to v1.8.0-rc1

---

contrib/msi/podman.wxs
docs/links-to-html.lua

* Remove the unsupported commend in lua script
Fixes #4335

Update XML to not embed quote in PATH on windows

---

libpod/image/image.go

This should increase the debug-ability when encountering this kind of issue.

Wrap error for failing ImageSize calls

---

pkg/bindings/errors.go
pkg/bindings/test/images_test.go

Include test cases to validate tag api responses and check if 
all the image instances are shown list command.
Also, Update the binding process and the response

Adding test to check Tag and list images endpoints in apis.

---

libpod/image/pull.go

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1797599

Close tarSource when finished using it

---

test/e2e/build_test.go

As a follow up of the location fix in #5080 we now add an e2e test for
that use case.

Add Containerfile location e2e test

---

.cirrus.yml
pkg/api/server/register_images.go

fix swagger docs and make sure docs validation runs

---

libpod/runtime_pod_linux.go

If there are no running containers - for example, if the pod was just created - the cgroup in question may not exist (under certain circumstances that we're not 100% sure about). However, regardless, we don't need to set a PID limit, as nothing will be making cleanup processes (no running conmon processes), so not changing the cgroup is safe regardless.
Fixes #5072

Only modify conmon cgroup if we have running containers

---

RELEASE_NOTES.md

[CI:DOCS] Update release notes for final release of v1.8.0

---

contrib/systemd/user/podman.service

[CI:DOCS]update contrib systemd user

---

changelog.txt
contrib/spec/podman.spec.in
version/version.go

Bump to v1.8.0

---

pkg/varlinkapi/images.go

When we finish building an image, we try to look up its ID by looking up the image using the name that we were asked to assign to the image.  If we weren't asked to assign a name to the image, that would produce an error.  The BuildImage() API we're using returns the image's ID anyway, so we can skip the lookup and just return the ID directly.

LibpodAPI.BuildImage: don't require a name for the new image

---

cmd/podman/libpodruntime/runtime.go

This makes the code easier to read but should not change the overall
behavior.

Refactor runtime functions to pass options structure

---

README.md

[CI:DOCS] Update readme to 1.8.0 release

---

vendor.conf
vendor/github.com/containers/image/docker/docker_client.go
vendor/github.com/containers/image/docker/docker_image_dest.go
vendor/github.com/containers/image/docker/docker_image_src.go
vendor/github.com/containers/image/docker/tarfile/dest.go
vendor/github.com/containers/image/docker/tarfile/src.go
vendor/github.com/containers/image/image/docker_schema2.go
vendor/github.com/containers/image/image/oci.go
vendor/github.com/containers/image/internal/iolimits/iolimits.go
vendor/github.com/containers/image/openshift/openshift.go

Fixes for https://bugzilla.redhat.com/show_bug.cgi?id=1792796

[1.0] update containers/image

---

.cirrus.yml
contrib/spec/podman.spec.in

this is a container-based approach to verifying we can build an rpm based on the contrib spec.

replace prow images test

---

cmd/podman/pull.go

Refactor and simplify the code in cmd/podman/pull.go to address a couple
of issues w.r.t. how the arguments were passed.  Also make sure to
always use the c/image API for parsing instead of working around it.

cmd/podman/pull: refactor code

---

pkg/api/handlers/libpod/images.go

[CI:DOCS] api: pull: fix reference parsing

---

libpod/container_internal.go
test/e2e/run_volume_test.go

When Docker performs a copy up, it first verifies that the volume being copied into is empty; thus, for volumes that have been modified elsewhere (e.g. manually copying into then), the copy up will not be performed at all. Duplicate this behavior in Podman by checking if the volume is empty before copying.
Furthermore, move setting copyup to false further up. This will prevent a potential race where copy up could happen more than once if Podman was killed after some files had been copied but before the DB was updated.

Do not copy up when volume is not empty

---

libpod/image/image_test.go
test/e2e/config.go
test/e2e/load_test.go
test/endpoint/endpoint.go

use quay.io/libpod/fedora-minimal for reliability

---

libpod/stats.go
libpod/stats_config.go
pkg/api/handlers/generic/containers_stats.go
pkg/cgroups/cgroups.go
pkg/cgroups/cpu.go

api: fix the CPU stats reported

---

README.md

[CI:DOCS] README: fix docs links

---

cmd/podman/logs.go
docs/source/markdown/podman-logs.1.md
libpod/container_log_linux.go

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

Misc typo fixes

---

test/system/150-login.bats

Test podman login/logout, login with wrong credentials,
auth file contents, auth file path override, push/pull,
and, if skopeo is installed, credentials sharing
Fixes: #4283

New login and push tests

---

cmd/podman/pod_create.go
completions/bash/podman
docs/source/markdown/podman-pod-create.1.md
libpod/container_internal_linux.go
libpod/options.go
libpod/pod.go
libpod/runtime_pod_infra_linux.go
pkg/adapter/pods.go
pkg/adapter/pods_remote.go
pkg/varlinkapi/pods.go
test/e2e/pod_create_test.go

Still needs tests, but this adds a large group of network options to `podman pod create`

Add network opts to pods

---

pkg/api/handlers/decoder.go

fixes `INFO[0057] Request Failed(Internal Server Error): failed to kill Container: schema: error converting value for "signal" `

APIv2: Fixed syscall.Signal not convertable by decoder

---

test/e2e/create_staticip_test.go

The "create two containers with the same IP" test failed:
https://api.cirrus-ci.com/v1/task/5992323062431744/logs/integration_test.log#t--Podman-create-two-containers-with-the-same-IP
...
(basically, expected error exit code, got 0)
Analysis: the sequence is 'start test1, start test2'. Perhaps it's
possible that 'podman start' exits before the test1 container has
an IP address assigned? There are no checks in the test, so it's
impossible to know what happened.
Solution: add a wait-loop invoking 'podman inspect', waiting
for a nonempty IP address on test 1; then assert that it's
what we expect it to be.

Flake fix: race condition in same-IP test

---

RELEASE_NOTES.md

[CI:DOCS] Update release notes for v1.8.1

---

docs/source/markdown/podman-build.1.md
docs/source/markdown/podman-create.1.md
docs/source/markdown/podman-run.1.md

Also apply changes from commit 3fd9f0c028f9dab7c8923629d4dc5d38e594db1a
to the other two commands that have the --device option.
Documents #4550
Signed-off-by: Stefan Becker <chemobejk@gmail.com>

docs: symlink to host device is resolved

---

cmd/podman/port.go
pkg/adapter/containers.go
test/system/500-networking.bats

code was erronously misinterpretting the port as a containername.
Fixes: #1791832

fix port list by container with port

---

pkg/api/handlers/images.go
pkg/bindings/test/images_test.go

add two additional bindings tests for image usage.
add ability to use search filter on the endpoint.

more image binding tests

---

.cirrus.yml
contrib/cirrus/integration_test.sh
contrib/cirrus/setup_environment.sh
contrib/cirrus/unit_test.sh
pkg/bindings/errors.go
pkg/bindings/test/pods_test.go

enable ci on go binding tests

---

pkg/rootless/rootless_linux.c

if there are more than FD_SETSIZE open fds passed down to the Podman process, the initialization code could crash as it attempts to store them into a fd_set.  Use an array of fd_set structs, each of them holding only FD_SETSIZE file descriptors.

rootless: fix segfault when open fd >= FD_SETSIZE

---

pkg/bindings/test/containers_test.go

fix trivial typo

---

libpod/volume.go
pkg/api/handlers/libpod/volumes.go
pkg/api/handlers/types.go
pkg/api/server/register_volumes.go
pkg/api/server/swagger.go
pkg/bindings/containers/create.go
pkg/bindings/test/volumes_test.go
pkg/bindings/volumes/volumes.go

add binding tests for volumes: inspect(get), create, remove, prune, and list
implement filters ability for volumes

binding tests for volumes

---

libpod/pod.go
libpod/pod_api.go
pkg/bindings/test/pods_test.go

Includes test to validate all, no or few pods are pruned,
if the pods are in exited state.

Add test to validate prune pod apiv2 binding.

---

pkg/bindings/containers/containers.go

container Exists: fix URL

---

pkg/api/server/register_volumes.go

more swagger fixes

---

test/apiv2/20-containers.at
test/apiv2/22-stop.at

...and allow status 'stopped' in addition to 'exited'.
Fixes: #5336

APIv2 tests: add tests for stop

---

.cirrus.yml
.dockerignore
CONTRIBUTING.md
contrib/cirrus/lib.sh
contrib/gate/Dockerfile
contrib/gate/README.md
contrib/gate/entrypoint.sh
hack/get_release_info.sh
hack/install_golangci.sh

Cirrus: Fix gate image & false-positive exits

---

RELEASE_NOTES.md

[CI:DOCS] Update release notes for v1.8.1-RC3

---

Makefile
cmd/podman/shared/create.go
contrib/cirrus/packer/libpod_base_images.yml
docs/source/markdown/podman-build.1.md
libpod/config/config.go
libpod/container_api.go
libpod/container_inspect.go
libpod/container_internal.go
libpod/oci.go
pkg/api/handlers/generic/images.go
pkg/api/handlers/libpod/pods.go
pkg/api/tags.yaml
pkg/bindings/test/images_test.go
pkg/bindings/test/pods_test.go
pkg/spec/security.go

Fix spelling mistakes in code found by codespell

---

cmd/podman/remoteclientconfig/config_darwin.go
cmd/podman/remoteclientconfig/config_linux.go
cmd/podman/remoteclientconfig/config_windows.go
pkg/resolvconf/resolvconf.go

Use c/storage packages instead of docker/docker ones where possible.

use c/storage instead of docker/docker

---

RELEASE_NOTES.md

[CI:DOCS] Update release notes for v1.8.1 final release

---

cmd/podman/main_local.go
docs/source/markdown/podman.1.md

* clarify that --syslog and --trace expects arguments
* mention defaults in --help text
* add --trace to docs

docs: clarify bools in `podman --help`

---

changelog.txt
contrib/spec/podman.spec.in
version/version.go

[CI:DOCS]Bump to v1.8.1

---

README.md

[CI:DOCS] Update version in README to v1.8.1

---

pkg/api/handlers/libpod/pods.go

Update the start and stop api to validate pod status based on status functions
rather than iterating over all the containers in the pod. (Addressing the TODO)

Update start stop api to use pod status function.

---

pkg/api/server/register_events.go

add an endpoint for events on the libpod side of the house.

[CI:DOCS]Add libpod event endpoint

---

libpod/logs/log.go

Code review change suggested by jwhonce in
https://github.com/containers/libpod/pull/5244#pullrequestreview-366574431
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Bugfix Pull Request
libpod/logs/log.go

Follow up change from #5244

---

pkg/rootlessport/rootlessport_linux.go

otherwise the rootless parent process might wait indefinitely when the
rootless-child process exits early.

rootlessport: detect rootless-child exit

---

test/system/030-run.bats

The recently-added 'run --rmi' test was not actually doing
what it thinks it was doing: for one, 'run_podman | grep'
is never going to work; also, the test was leaving behind
stray images.
Rework to do what I believe the intention was; and, combine
into one test (down from two) for readability.

run --rmi test: make it work

---

libpod/reset.go

In some older systems, we point the temporary directory to /run/user/1000 which leads podman system reset to clear unrelated files under XDG_RUNTIME_DIR. This patch only removes TmoDir if it is not the same as the XDG_RUNTIME_DIR.
fix #4831 

Fix bug podman reset to not remove $XDG_RUNTIME_DIR 

---

RELEASE_NOTES.md

[CI:DOCS] Update release notes for v1.8.2-RC1

---

vendor/github.com/containers/buildah/pkg/supplemented/supplemented.go

It looks like something snuck in and now make vendor fails on master. This should make things happy.

Fix vendoring on master

---

pkg/api/handlers/libpod/swagger.go
pkg/api/server/register_swagger.go
pkg/api/server/server.go

register the swagger endpoint and add some error handling for when the swagger file does not exist

serve swagger when present

---

pkg/api/server/server.go
pkg/bindings/test/common_test.go
pkg/bindings/test/volumes_test.go
pkg/varlinkapi/system.go
test/e2e/search_test.go

* Add second go routine for when a Timer is not needed.
* goimports updated some project files
Fixes #5531

Reduce CPU usage when --timeout=0

---

changelog.txt
contrib/spec/podman.spec.in
version/version.go

Bump to v1.8.2

---

cmd/podmanV2/README.md

[CI:DOCS] Add guidelines for writing podman V2 CLI commands

---

pkg/api/handlers/compat/containers.go
pkg/api/server/register_events.go
pkg/bindings/bindings.go
pkg/bindings/containers/containers.go
pkg/bindings/containers/logs.go
pkg/bindings/containers/types.go
pkg/bindings/system/system.go
pkg/bindings/test/common_test.go
pkg/bindings/test/containers_test.go
pkg/bindings/test/images_test.go
pkg/bindings/test/pods_test.go
pkg/bindings/test/system_test.go
pkg/bindings/test/volumes_test.go

add go-bindings for logs and events. tests were also added.

apiv2 add bindings for logs|events

---

pkg/bindings/test/pods_test.go

[CI:DOCS]fix type issue in pod binding test

---

.gitignore
cmd/podmanV2/containers/exists.go
cmd/podmanV2/containers/inspect.go
cmd/podmanV2/containers/wait.go
cmd/podmanV2/images/inspect.go
cmd/podmanV2/main.go
cmd/podmanV2/registry/registry.go
cmd/podmanV2/root.go
pkg/api/handlers/libpod/containers.go
pkg/bindings/connection.go
pkg/bindings/containers/containers.go
pkg/bindings/test/common_test.go
pkg/bindings/test/containers_test.go
pkg/bindings/test/pods_test.go
pkg/domain/entities/containers.go
pkg/domain/entities/engine.go
pkg/domain/entities/engine_container.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/abi/runtime.go
pkg/domain/infra/runtime_abi.go
pkg/domain/infra/runtime_image_proxy.go
pkg/domain/infra/runtime_libpod.go
pkg/domain/infra/runtime_proxy.go
pkg/domain/infra/runtime_tunnel.go
pkg/domain/infra/tunnel/containers.go
pkg/domain/infra/tunnel/helpers.go
pkg/domain/infra/tunnel/runtime.go

enable container exists and wait for podmanv2

podmanv2 container exists|wait

---

cmd/podmanV2/containers/exists.go
cmd/podmanV2/pods/exists.go
pkg/domain/entities/engine_container.go
pkg/domain/infra/abi/pods.go
pkg/domain/infra/tunnel/pods.go

podmanv2 pod exists

---

cmd/podmanV2/parse/parse.go
cmd/podmanV2/parse/parse_test.go
cmd/podmanV2/volumes/create.go
cmd/podmanV2/volumes/volume.go
pkg/api/handlers/libpod/volumes.go
pkg/api/handlers/types.go
pkg/api/server/swagger.go
pkg/bindings/test/volumes_test.go
pkg/bindings/volumes/volumes.go
pkg/domain/entities/engine_container.go
pkg/domain/entities/volumes.go
pkg/domain/infra/abi/parse/parse.go
pkg/domain/infra/abi/volumes.go
pkg/domain/infra/tunnel/volumes.go

podmanv2 volume create

---

pkg/rootlessport/rootlessport_linux.go

when a sigpipe is received the stdout/stderr pipe was closed, so
reopen them with /dev/null.
Closes: https://github.com/containers/libpod/issues/5541

rootlessport: handle SIGPIPE

---

cmd/podman/images.go
test/system/010-images.bats

Changes made in json output to improve readability of
podman images output.
Fixes: https://github.com/containers/libpod/issues/5001
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

Improved readability in image json output

---

docs/dckrman.sh

Fix docker man page links

---

.copr/Makefile
contrib/spec/podman.spec.in
hack/build-rpms.sh
hack/lib/build/binaries.sh
hack/lib/build/rpm.sh
hack/lib/build/version.sh
hack/lib/constants.sh
hack/lib/init.sh
hack/lib/log/output.sh
hack/lib/log/stacktrace.sh
hack/lib/log/system.sh
hack/lib/util/ensure.sh
hack/lib/util/environment.sh
hack/lib/util/find.sh
hack/lib/util/misc.sh
hack/lib/util/text.sh
hack/lib/util/trap.sh
images/os/Dockerfile

Add a build-rpms.sh script and Dockerfile that will
be used to enable the openshift aws test suites.
Will open the corresponding PR in openshift/release once this is in.

Add logic for enabling the openshift test suite

---

docs/tutorials/README.md
docs/tutorials/image_signing.md

If you want, then we could also publish this as little blog post on podman.io. I'll opened the PR here (https://github.com/containers/podman.io/pull/205) and leave it up to you to decide if we want to publish it as blog too :)
Refers to https://github.com/containers/libpod/issues/5378

Add image signing with GPG tutorial

---

cmd/podmanV2/containers/kill.go
cmd/podmanV2/containers/pause.go
cmd/podmanV2/containers/restart.go
cmd/podmanV2/containers/rm.go
cmd/podmanV2/containers/stop.go
cmd/podmanV2/containers/unpause.go
cmd/podmanV2/containers/utils.go
cmd/podmanV2/containers/wait.go
cmd/podmanV2/parse/parse.go
cmd/podmanV2/root.go
cmd/podmanV2/utils/error.go
cmd/podmanV2/utils/remote.go
pkg/api/handlers/compat/containers.go
pkg/api/handlers/compat/containers_restart.go
pkg/bindings/containers/containers.go
pkg/bindings/test/volumes_test.go
pkg/domain/entities/containers.go
pkg/domain/entities/engine_container.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/tunnel/containers.go
pkg/domain/infra/tunnel/helpers.go
pkg/signal/signal_linux.go
pkg/signal/signal_unsupported.go
pkg/util/utils.go

add core container commands for podmanv2: kill, pause, restart, rm, stop, unpause

podmanv2 add core container commands

---

cmd/podmanV2/registry/registry.go
cmd/podmanV2/root.go

add ability to set and get exit code.

podmanv2 exit code

---

cmd/podmanV2/images/history.go
pkg/domain/entities/images.go

* All format options now implemented

Complete podmanV2 history command

---

pkg/rootlessport/rootlessport_linux.go

Dup2 is not defined on arm64 in the syscall package.
Closes: https://github.com/containers/libpod/issues/5587

rootlessport: use x/sys/unix instead of syscall

---

cmd/podmanV2/volumes/inspect.go
cmd/podmanV2/volumes/list.go
cmd/podmanV2/volumes/prune.go
cmd/podmanV2/volumes/rm.go
go.mod
libpod/runtime_volume.go
pkg/adapter/runtime.go
pkg/api/handlers/libpod/volumes.go
pkg/api/server/register_volumes.go
pkg/api/server/swagger.go
pkg/bindings/volumes/volumes.go
pkg/domain/entities/engine_container.go
pkg/domain/entities/types.go
pkg/domain/entities/volumes.go
pkg/domain/filters/volumes.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/abi/volumes.go
pkg/domain/infra/tunnel/containers.go
pkg/domain/infra/tunnel/runtime.go
pkg/domain/infra/tunnel/volumes.go
pkg/varlinkapi/volumes.go

add volume commands: create, inspect, ls, prune, and rm

podmanv2 volumes

---

cmd/podmanV2/images/images.go
cmd/podmanV2/images/list.go
cmd/podmanV2/registry/registry.go
cmd/podmanV2/report/templates.go
pkg/api/handlers/compat/images.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/types.go
pkg/api/server/swagger.go
pkg/bindings/images/images.go
pkg/domain/entities/engine_image.go
pkg/domain/entities/images.go
pkg/domain/entities/set.go
pkg/domain/infra/abi/images.go
pkg/domain/infra/abi/images_list.go
pkg/domain/infra/tunnel/images.go

* Updated entities to support flags/options
* Updated bindings caused by entities changes
* Removed handlers.ImageSummary in favor of entities.ImageSummary
* Introduced StringSet() container object to simply error checking

V2 podman images/image list

---

.golangci.yml
pkg/domain/infra/abi/pods.go
pkg/domain/infra/abi/volumes.go

enable linting on v2

---

libpod/networking_linux.go

add a check for --enable-seccomp support in slirp4netns.  If it is
supported, always enable it.

slirp: enable seccomp filter

---

pkg/specgen/validate.go

when a network is not provided, we should set a default mode based on rootless or rootfull.
Fixes: #5366

apiv2 add default network in specgen

---

cmd/podmanV2/containers/inspect.go
libpod/container_inspect.go
libpod/define/container_inspect.go
libpod/healthcheck.go
libpod/networking_linux.go
libpod/networking_unsupported.go
pkg/adapter/containers_remote.go
pkg/api/handlers/swagger.go
pkg/api/server/swagger.go
pkg/bindings/containers/containers.go
pkg/bindings/containers/healthcheck.go
pkg/domain/entities/containers.go
pkg/domain/entities/engine_container.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/tunnel/containers.go
test/e2e/common_test.go

add ability to inspect a container

podmanv2 container inspect

---

contrib/cirrus/logcollector.sh

Log libseccomp package version

---

cmd/podmanV2/containers/commit.go
pkg/domain/entities/containers.go
pkg/domain/entities/engine_container.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/tunnel/containers.go

add commit of a container to a container-image

podmanv2 commit

---

cmd/podmanV2/pods/top.go
libpod/pod_top_linux.go
pkg/api/handlers/libpod/pods.go
pkg/api/handlers/swagger.go
pkg/api/handlers/types.go
pkg/api/server/register_containers.go
pkg/api/server/register_pods.go
pkg/bindings/pods/pods.go
pkg/bindings/test/containers_test.go
pkg/bindings/test/pods_test.go
pkg/domain/entities/engine_container.go
pkg/domain/entities/pods.go
pkg/domain/infra/abi/pods.go
pkg/domain/infra/tunnel/pods.go

The v2 endpoint for pod-top was missing, so we're first adding this endpoint and then do the plumbing for podmanV2.
While CI is cooking, I'll look into ending some tests for the endpoint but I was born after the war and don't speak perl.

V2 pod top

---

pkg/api/server/register_pods.go

I'm getting really tired of doing this manually.

fix more swagger inconsistencies

---

cmd/podmanV2/healthcheck/healthcheck.go
cmd/podmanV2/healthcheck/run.go
cmd/podmanV2/main.go
pkg/domain/entities/engine_container.go
pkg/domain/entities/healthcheck.go
pkg/domain/infra/abi/healthcheck.go
pkg/domain/infra/tunnel/healthcheck.go

podmanv2 enable healthcheck run

---

cmd/podmanV2/pods/pod.go
cmd/podmanV2/pods/ps.go
cmd/podmanV2/report/templates.go
libpod/podfilters/pods.go
pkg/api/handlers/utils/pods.go
pkg/domain/entities/engine_container.go
pkg/domain/entities/pods.go
pkg/domain/infra/abi/pods.go
pkg/domain/infra/tunnel/pods.go

add the ability to list pods in podmanv2

podmanv2 pod ps

---

cmd/podmanV2/images/tag.go
cmd/podmanV2/images/untag.go
pkg/api/handlers/libpod/images.go
pkg/api/server/register_images.go
pkg/bindings/images/images.go
pkg/domain/entities/engine_image.go
pkg/domain/entities/images.go
pkg/domain/infra/abi/images.go
pkg/domain/infra/tunnel/images.go

add the ability to tag and untag images in podmanv2

podman v2 image tag and untag

---

cmd/podmanV2/Makefile
cmd/podmanV2/images/load.go
cmd/podmanV2/main.go
libpod/image/image.go
libpod/image/image_test.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/swagger.go
pkg/bindings/images/images.go
pkg/bindings/test/images_test.go
pkg/domain/entities/engine_image.go
pkg/domain/entities/images.go
pkg/domain/infra/abi/images.go
pkg/domain/infra/tunnel/images.go

enable podman load for v2
add reexec into main
add systemd build flag to v2 makefile

podmanv2 load

---

cmd/podmanV2/containers/export.go
pkg/api/handlers/compat/containers_export.go
pkg/api/server/register_containers.go
pkg/bindings/containers/containers.go
pkg/domain/entities/containers.go
pkg/domain/entities/engine_container.go
pkg/domain/infra/abi/containers.go
pkg/domain/infra/tunnel/containers.go

add ability to export a container to a tarball

podmanv2 export

---

README.md

Touch up mailing list address in README.md

---

cmd/podmanV2/images/import.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/swagger.go
pkg/api/handlers/types.go
pkg/bindings/images/images.go
pkg/domain/entities/engine_image.go
pkg/domain/entities/images.go
pkg/domain/infra/abi/images.go
pkg/domain/infra/tunnel/images.go

add the ability to import a container image from a container export

podmanv2 import

---

cmd/podman/shared/create.go
go.sum
pkg/spec/spec.go
test/e2e/build/basicalpine/Containerfile.path
test/e2e/build_test.go

Fix environment handling from containers.conf

---

libpod/oci_conmon_linux.go

Pass path environment down to the OCI runtime

---

cmd/podmanV2/images/save.go
libpod/define/config.go
pkg/api/handlers/libpod/images.go
pkg/api/handlers/utils/handler.go
pkg/api/server/register_images.go
pkg/bindings/images/images.go
pkg/domain/entities/engine_image.go
pkg/domain/entities/images.go
pkg/domain/infra/abi/images.go
pkg/domain/infra/tunnel/images.go

add ability to save an image for podman v2

podmanv2 save image
