cmd/podmanV2/main.go, cmd/podmanV2/system/version.go, pkg/domain/infra/tunnel/system.go
this is only for the abi side and does not print out the remote information yet.  the remote information will need to be worked on and agreed upon later.
=> podmanv2 version

cmd/podmanV2/common/create.go, cmd/podmanV2/common/default.go, cmd/podmanV2/containers/attach.go, cmd/podmanV2/containers/exec.go, libpod/container_api.go, libpod/container_exec.go, libpod/container_top_linux.go, libpod/define/config.go, libpod/healthcheck.go, libpod/oci.go, libpod/oci_attach_linux.go, libpod/oci_attach_unsupported.go, pkg/adapter/containers.go, pkg/adapter/terminal_unsupported.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/abi/terminal/sigproxy_linux.go, pkg/domain/infra/abi/terminal/terminal.go, pkg/domain/infra/abi/terminal/terminal_linux.go, pkg/domain/infra/tunnel/containers.go, pkg/varlinkapi/attach.go
add the ability to attach to a running container.  the tunnel side of this is not enabled yet as we have work on the endpoints and plumbing to do yet.
=> v2podman attach

cmd/podmanV2/pods/inspect.go, go.sum, pkg/api/handlers/libpod/pods.go, pkg/bindings/pods/pods.go, pkg/domain/entities/engine_container.go, pkg/domain/entities/pods.go, pkg/domain/infra/abi/pods.go, pkg/domain/infra/tunnel/pods.go
Add the ability to inspect pod in podmanv2
=> podmanv2 pod inspect

cmd/podmanV2/containers/start.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/tunnel/containers.go
add the ability to start containers
=> podmanv2 start

cmd/podman/main_local.go
=> Cleanup whether to enter user namespace

cmd/podmanV2/common/create.go, cmd/podmanV2/containers/run.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/tunnel/containers.go
add the ability to run a container
=> v2podman run

cmd/podmanV2/system/info.go, pkg/bindings/system/info.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/system.go
add ability to run info for v2
=> podmanv2 info

test/e2e/login_logout_test.go
fix rootless login/logout tests. Since c/image can support peruser certs directory, this path uses $HOME dir as certs.d to avoid permission deny failures.
fix #5006 
=> fix rootless login/logout tests

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/copy.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/version/version.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/modules.txt
=> Bump containers/image to v5.4.3

docs/source/markdown/podman-generate-systemd.1.md
=> man page: add note about issue with SELinux

README.md
PR updates the latest version number to be in sync with the linked latest release https://github.com/containers/libpod/releases/latest
=> update the latest version to 1.8.2

RELEASE_NOTES.md
=> [CI:DOCS] Update release notes for v1.9.0-RC1

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> Bump to v1.9.0-RC1

cmd/podmanV2/containers/kill.go, cmd/podmanV2/containers/wait.go, cmd/podmanV2/images/load.go, cmd/podmanV2/images/tag.go, cmd/podmanV2/pods/create.go, pkg/domain/entities/pods.go, pkg/domain/infra/abi/images.go, pkg/signal/signal_linux.go, pkg/specgen/pod_validate.go, test/system/120-load.bats
=> Fixes for load and other system tests

cmd/podmanV2/containers/init.go, pkg/api/handlers/libpod/containers.go, pkg/api/server/register_containers.go, pkg/bindings/containers/containers.go, pkg/bindings/test/containers_test.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/tunnel/containers.go
add the ability to init a container both local and remote
=> v2podman add container init

cmd/podman/shared/create.go
=> Need to set security options even if user does not specify options

cmd/podmanV2/containers/mount.go, cmd/podmanV2/containers/unmount.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/tunnel/containers.go
add the ability to mount and unmount containers for the local client only
=> podmanv2 mount and umount

RELEASE_NOTES.md
=> [CI:DOCS] Update release notes for v1.9.0-RC2

cmd/podmanV2/containers/mount.go, cmd/podmanV2/containers/stop.go, cmd/podmanV2/containers/wait.go, cmd/podmanV2/main.go, cmd/podmanV2/registry/config.go, cmd/podmanV2/registry/registry.go, cmd/podmanV2/registry/remote.go, cmd/podmanV2/root.go, pkg/domain/entities/engine.go, pkg/domain/entities/engine_container.go, pkg/domain/entities/engine_image.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/abi/images.go, pkg/domain/infra/abi/system.go, pkg/domain/infra/runtime_abi.go, pkg/domain/infra/runtime_image_proxy.go, pkg/domain/infra/runtime_libpod.go, pkg/domain/infra/runtime_proxy.go, pkg/domain/infra/runtime_tunnel.go, pkg/domain/infra/tunnel/containers.go, pkg/domain/infra/tunnel/images.go, pkg/util/utils.go
Note: This PR doesn't provide full rootless support that will be
addressed in a future PR
=> Add support for the global flags and config files

cmd/podmanV2/images/history.go, cmd/podmanV2/images/inspect.go, cmd/podmanV2/images/rm.go, cmd/podmanV2/images/rmi.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images.go
Fix more regressions between v1 and v2
=> More system test fixes on regressions

cmd/podmanV2/system/events.go, pkg/api/handlers/types.go, pkg/domain/entities/engine_container.go, pkg/domain/entities/types.go, pkg/domain/infra/abi/events.go, pkg/domain/infra/tunnel/events.go
add the ability to monitor events
=> podmanv2 events

README.md
=> [CI:DOCS] Update README to reflect that latest version is v1.9.0

pkg/autoupdate/autoupdate.go
Fix a bug in the auto-update logic causing all images to be checked and
not only the ones of containers with the specific auto-update policy.
=> auto update: skip non-image policies

cmd/podmanV2/Makefile, libpod/runtime.go, pkg/specgen/container_validate.go, pkg/specgen/generate/container.go, pkg/specgen/security.go, pkg/specgen/specgen.go
SELinux label options processing fixes, should allow system tests to pass.
=> Fix up SELinux labeling

cmd/podman/runlabel.go, cmd/podmanV2/common/create.go, cmd/podmanV2/common/default.go, pkg/api/handlers/compat/containers_prune.go, pkg/api/handlers/libpod/volumes.go, pkg/api/handlers/utils/containers.go, pkg/api/handlers/utils/pods.go, pkg/domain/entities/container_ps.go, pkg/domain/infra/abi/containers.go, pkg/ps/define/types.go, pkg/ps/ps.go, pkg/util/utils.go
this is second phase of removing unneeded bloat in the remote client. this is important to be able to reduce the client size as well as possible native compilation for windows/mac.
=> v2 bloat pruning phase 2

libpod/define/info.go, libpod/info.go
=> Add version to podman info command

contrib/cirrus/logformatter, contrib/gate/Dockerfile, test/apiv2/test-apiv2
Fixes to address container image build failures at 
https://quay.io/repository/libpod/gate?tab=builds
=> Cirrus: Fix gate container build failure

.cirrus.yml, contrib/cirrus/lib.sh, contrib/cirrus/logformatter, contrib/gate/Dockerfile, test/apiv2/test-apiv2
=> Cirrus: Necessary changes for v1.9 branch automation

.gitignore
=> [CI:DOCS] .gitignore: ignore v2 remote

cmd/podman/common/create.go, cmd/podman/containers/stop.go, cmd/podman/containers/wait.go, cmd/podman/main.go, cmd/podman/registry/config.go, cmd/podman/registry/registry.go, cmd/podman/registry/remote.go, cmd/podman/root.go, pkg/domain/infra/runtime_abi.go, pkg/domain/infra/runtime_image_proxy.go, pkg/domain/infra/runtime_libpod.go, pkg/domain/infra/runtime_proxy.go, pkg/domain/infra/runtime_tunnel.go
* registry.PodmanConfig() now returns a pointer to the source of truth
=> Fix bug where two configurations had been created

libpod/networking_linux.go
When creating a network we pass down a name which end up in the K8S_POD_NAME argument to cni plugins. Currently this name is always filled with the container name, so for pods it is the name of the infra container, not really what one would expect.
This mess up with the dnsname plugin as it doesn't receive the pod name in K8S_POD_NAME, see https://github.com/containers/dnsname/issues/11. To fix this pass the pod name when the container is part of a pod, otherwise use the container name like before.
=> Fix the pod name passed to cni

.cirrus.yml, cmd/podman/root.go
=> Enable some testing

cmd/podman/containers/run.go, cmd/podman/images/list.go, cmd/podman/inspect.go, pkg/api/handlers/libpod/images.go, pkg/api/handlers/types.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/abi/images_list.go, test/system/005-info.bats
=> Fixes for system tests

cmd/podman/common/specgen.go
With this patch we can get run_passwd_test.go to pass
=> We were not handling the user option on create

.cirrus.yml, cmd/podman/volumes/inspect.go, cmd/podman/volumes/list.go
=> enable integration testing

libpod/define/pod_inspect.go, libpod/pod_api.go, pkg/bindings/test/pods_test.go
Added status field in pod inspect report.
Fixed pod tests to use it.
=> Update pod inspect report to hold current pod status.

cmd/podman/containers/diff.go, cmd/podman/diff.go, cmd/podman/images/diff.go
* --latest now forces container diff
* diff options now passed into domain layer
* updated help/usage messages
=> V2 Fix --latest for podman diff commands

cmd/podman/common/specgen.go
fix some cgroups related integration tests.
=> common: setting cgroup resources correctly

cmd/podman/system/service.go
=> V2 Remove existing unix domain socket on startup

cmd/podman/common/specgen.go, cmd/podman/images/inspect.go, pkg/specgen/generate/container.go
Fix Entrypoints, Inspect and Annotations.
=> More fixes for podman create tests

cmd/podman/containers/port.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/tunnel/containers.go
=> v2podman port

cmd/podman/containers/attach.go, cmd/podman/containers/commit.go, cmd/podman/containers/create.go, cmd/podman/containers/exec.go, cmd/podman/containers/export.go, cmd/podman/containers/kill.go, cmd/podman/containers/mount.go, cmd/podman/containers/pause.go, cmd/podman/containers/restart.go, cmd/podman/containers/rm.go, cmd/podman/containers/run.go, cmd/podman/containers/start.go, cmd/podman/containers/stop.go, cmd/podman/containers/top.go, cmd/podman/containers/unmount.go, cmd/podman/containers/unpause.go, cmd/podman/containers/wait.go
add container subcommands with example text that has proper context.
=> podmanv2 container subcommands

pkg/specgen/generate/oci.go
=> v2, pkg: implement rlimits

pkg/specgen/generate/container.go
if the image specifies both the image and entrypoint, we need to account for that and preprend the entrypoint to the command.  this only happens if no user command and entrypoint were supplied.
=> add entrypoint from image where needed

cmd/podman/containers/cp.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/cp.go, pkg/domain/infra/tunnel/containers.go
enable podman to copy files between container and host, local mode only. this is a straight port of v1 code to v2.
=> podmanv2 cp

cmd/podman/login.go, cmd/podman/logout.go, vendor/github.com/containers/common/pkg/auth/auth.go, vendor/github.com/containers/common/pkg/auth/cli.go, vendor/modules.txt
Implement podman login and logout.  Smoke tests were successful but the
system tests are currently failing as we seem unable to run a registry
at the moment.
=> v2: implement log{in,out}

pkg/domain/infra/runtime_libpod.go
=> v2, podman: plug --userns=auto

go.mod, go.sum, test/e2e/create_staticip_test.go, test/e2e/run_device_test.go, test/e2e/run_selinux_test.go, vendor/github.com/containers/common/pkg/config/default.go, vendor/modules.txt
This will change the default of UserNS to false
Also turn on tests for create_staticip_test.go
run_device_test.go, run_selinux_test.go
=> vendor in containers/common v0.9.4

test/e2e/info_test.go
=> Fix v2 test podman info

cmd/podman/containers/exists.go, cmd/podman/images/exists.go, cmd/podman/pods/create.go, cmd/podman/pods/exists.go, test/e2e/exists_test.go
* Fix setting exit code in */exists.go
=> V2 Restore exists E2E tests

pkg/domain/infra/abi/images.go, pkg/domain/infra/tunnel/images.go, test/e2e/untag_test.go
=> Fix integration tests for untag

cmd/podman/system/info.go, pkg/api/server/server.go
* currently wired to localhost:8888 to prevent access from off machine
=> Instrumentation to answer #5765

cmd/podman/root.go, pkg/domain/entities/engine_container.go, pkg/domain/entities/engine_image.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/abi/images.go, pkg/domain/infra/abi/runtime.go, pkg/domain/infra/runtime_libpod.go, pkg/domain/infra/tunnel/containers.go, pkg/domain/infra/tunnel/images.go
=> V2 restore libpod.Shutdown() when exiting podman commands

cmd/podman/common/create.go, cmd/podman/common/specgen.go, cmd/podman/containers/create.go, pkg/specgen/container_validate.go, pkg/specgen/generate/namespaces.go, pkg/specgen/namespaces.go
and handle differently the user namespace as it supports additional options.
=> podman, v2: handle namespaces specified on the CLI

libpod/image/docker_registry_options.go
=> set bigfilestemporarydir for pull

pkg/rootless/rootless_linux.c, pkg/rootless/rootless_linux.go
open the namespace file descriptors inside of the child process.
Closes: https://github.com/containers/libpod/issues/5873
(cherry picked from commit 788fdc685b00dee5ccb594bef845204250c4c123)
=> [1.9] rootless: move join namespace inside child process

test/e2e/run_cgroup_parent_test.go
=> v2, test: enable cgroup parent tests

cmd/podman/common/specgen.go, cmd/podman/containers/create.go, cmd/podman/containers/run.go, pkg/specgen/container_validate.go, pkg/specgen/generate/config_linux_cgo.go, pkg/specgen/generate/container.go, pkg/specgen/generate/container_create.go, pkg/specgen/specgen.go, test/e2e/run_test.go
=> v2, tests: fix various run_test.go failures

test/e2e/commit_test.go
=> V2 tests: enables commit tests

cmd/podman/common/specgen.go, pkg/namespaces/namespaces.go, pkg/specgen/generate/namespaces.go, pkg/specgen/namespaces.go, pkg/util/utils.go, test/e2e/run_userns_test.go
=> v2, podman: fix and enable all run_userns_test.go tests

test/e2e/container_inspect_test.go
=> Enable container inspect integration tests

test/e2e/run_signal_test.go
=> enable run_signal integration tests

cmd/podman/containers/start.go, test/e2e/run_restart_test.go
also, correct arg processing mistake in start
=> enable run_restart integration tests

test/e2e/run_ns_test.go
=> enable run_ns integration tests

test/e2e/pause_test.go, test/e2e/pod_inspect_test.go, test/e2e/pod_kill_test.go, test/e2e/pod_prune_test.go, test/e2e/pod_top_test.go, test/e2e/run_dns_test.go, test/e2e/run_ns_test.go, test/e2e/run_passwd_test.go, test/e2e/run_signal_test.go
These tests are passing locally.
=> Enable these tests

libpod/pod.go, pkg/api/handlers/swagger/swagger.go, test/e2e/common_test.go, test/e2e/pod_inspect_test.go
=> Enable pod inspect integration test

test/e2e/pod_prune_test.go
=> Enable pod prune integration test

cmd/podman/cliconfig/config.go, cmd/podman/main.go, libpod/runtime.go
=> Don't check configuration until user input is applied

cmd/podman/common/specgen.go, pkg/domain/infra/abi/pods.go, pkg/specgen/generate/pod_create.go, pkg/specgen/pod_validate.go, test/e2e/pod_create_test.go, test/e2e/pod_restart_test.go, test/e2e/pod_rm_test.go, test/e2e/pod_stop_test.go
=> v2, podman: fix a bunch of "podman pod *" tests

cmd/podman/common/specgen.go, pkg/specgen/generate/container.go, test/e2e/healthcheck_run_test.go
=> v2, podman: fix healthchecks

cmd/podman/containers/ps.go, test/e2e/pause_test.go, test/e2e/pod_pause_test.go
adapt the tests to work with Podman v2.
=> [v2] tests: fix pause tests

cmd/podman/images/load.go, pkg/api/handlers/libpod/images.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images.go, test/e2e/load_test.go
fix bug where multiple images can be loaded and have to be able to handle the return of multiple names
=> enable load integration tests

libpod/container_internal_linux.go, pkg/domain/entities/container_ps.go, pkg/specgen/namespaces.go, test/e2e/pod_infra_container_test.go, test/e2e/pod_pod_namespaces.go, test/e2e/pod_start_test.go
fix remaining failures with pod tests.
Only pause and pod stats are not addressed in this PR, since we are already tracking pause and pod stats in:
https://github.com/containers/libpod/pull/5975
https://github.com/containers/libpod/pull/5966
=> v2, podman: fix pod tests

pkg/bindings/test/common_test.go, pkg/bindings/test/containers_test.go, pkg/bindings/test/create_test.go, pkg/bindings/test/info_test.go
@baude @vrothberg @giuseppe PTAL
=> Fix NewSpecGenerator args in pkg/bindings/test

cmd/podman/common/ports.go, cmd/podman/common/specgen.go, cmd/podman/containers/list.go, cmd/podman/containers/ps.go, pkg/domain/entities/container_ps.go, pkg/ps/ps.go, test/e2e/ps_test.go
Also make
podman create -p PUBLISHPorts
work.
This PR fixes ps_test.go
=> Make podman container list == podman ps

install.md
This PR fixes a typo on the install.md.
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> install.md: Fix typo

pkg/api/handlers/compat/containers_prune.go, pkg/api/handlers/libpod/pods.go, pkg/api/handlers/libpod/system.go, pkg/api/handlers/libpod/volumes.go, pkg/api/server/register_system.go, pkg/bindings/system/system.go, pkg/bindings/test/system_test.go, pkg/domain/entities/system.go, pkg/domain/infra/abi/images.go
Register system prune routes, handler to support system prune
Adds testcase to validate the system prune flow.
=> Adding system prune for podman v2

cmd/podman/common/specgen.go, cmd/podman/containers/exec.go, pkg/specgen/generate/container.go, test/e2e/exec_test.go
=> v2, podman: fix create tests

.cirrus.yml, cmd/podman/common/util.go, cmd/podman/containers/exists.go, cmd/podman/containers/list.go, cmd/podman/containers/port.go, cmd/podman/containers/ps.go, cmd/podman/images/exists.go, cmd/podman/images/images.go, cmd/podman/images/list.go, cmd/podman/images/prune.go, cmd/podman/main.go, cmd/podman/manifest/add.go, cmd/podman/manifest/create.go, cmd/podman/manifest/inspect.go, cmd/podman/networks/network.go, cmd/podman/pods/create.go, cmd/podman/pods/exists.go, cmd/podman/pods/ps.go, cmd/podman/root.go, cmd/podman/system/events.go, cmd/podman/system/info.go, cmd/podman/system/version.go, cmd/podman/volumes/list.go, cmd/podman/volumes/prune.go, pkg/domain/infra/abi/containers.go, test/apiv2/10-images.at, test/system/005-info.bats, test/system/150-login.bats
=> system tests must pass

changelog.txt, version/version.go
=> Bump to v1.9.1

cmd/podman/generate/generate.go, cmd/podman/generate/systemd.go, cmd/podman/main.go, pkg/domain/entities/engine_container.go, pkg/domain/entities/generate.go, pkg/domain/infra/abi/generate.go, pkg/domain/infra/tunnel/generate.go, pkg/specgen/generate/container_create.go, test/e2e/generate_systemd_test.go, test/system/250-generate-systemd.bats
Implement `podman generate systemd` for Podman v2 and enable associated
tests.
=> generate systemd

pkg/rootless/rootless_linux.c
commit 788fdc685b00dee5ccb594bef845204250c4c123 introduced a race
where the target process dies before the child process opens the
namespace files.  Move the open before the fork so if it fails the
parent process can attempt to join a different container instead of
failing.
=> rootless: move ns open before fork

README.md, RELEASE_NOTES.md
Mirror the release notes from the v1.9 branch, and update README as well
=> Update release notes and README for 1.9.1 release

cmd/podman/images/push.go, pkg/bindings/images/images.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images.go, test/e2e/push_test.go, test/system/150-login.bats
A couple of fixes to make push work. Mostly related to parsing and translating --tls-verify.
=> Enable push tests

cmd/podman/images/pull.go, cmd/podman/images/search.go, pkg/bindings/images/images.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images.go, test/e2e/search_test.go
* fix up the tls-verify hiccups as done for push
* clean up a couple of search things
* enable search tests
=> Enable search tests

cmd/podman/images/history.go, cmd/podman/images/list.go, cmd/podman/images/rm.go, cmd/podman/root.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images.go, pkg/domain/infra/abi/images_list.go, test/e2e/common_test.go, test/e2e/images_test.go, test/e2e/rmi_test.go, test/utils/utils.go
* Fix history --quiet formatting
* Fix image inspect --format=json
* Fix image list --sort
=> V2 Restore images list tests

test/system/150-login.bats
=> enable final system test

pkg/rootless/rootless_linux.c, pkg/rootlessport/rootlessport_linux.go
=> [1.9] rootless: backport two patches

cmd/podman/containers/attach.go, pkg/domain/infra/abi/containers.go, test/e2e/attach_test.go
=> testv2: enable attach test

cmd/podman/containers/unmount.go, cmd/podman/main.go
* Updated unmount to require ParentNS
=> V2 Commands that require ParentNS (rootful) are report error

cmd/podman/common/create.go, cmd/podman/common/create_opts.go, cmd/podman/common/specgen.go, cmd/podman/containers/create.go, cmd/podman/containers/run.go, cmd/podman/containers/start.go, pkg/domain/entities/containers.go, pkg/domain/infra/abi/containers.go, pkg/specgen/generate/container_create.go, pkg/specgen/generate/oci.go, test/e2e/create_test.go, test/e2e/run_entrypoint_test.go, test/e2e/run_test.go, test/e2e/start_test.go
=> v2, podman: fix create and entrypoint tests

cmd/podman/images/search.go, docs/source/markdown/podman-search.1.md
Check --limit range and update --limit manpage explanation.
=> search --limit compatible with docker

cmd/podman/README.md, cmd/podman/containers/ps.go, pkg/domain/infra/abi/containers.go
* Add notes on helper functions
* Update example
=> [CI:DOC] Bring README.md up to date

cmd/podman/containers/prune.go, cmd/podman/images/prune.go, cmd/podman/pods/prune.go, cmd/podman/system/prune.go, cmd/podman/utils/utils.go, cmd/podman/volumes/prune.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/abi/images.go, pkg/domain/infra/abi/pods.go, pkg/domain/infra/abi/system.go, pkg/domain/infra/abi/volumes.go, pkg/domain/infra/tunnel/system.go, test/e2e/prune_test.go, test/e2e/volume_prune_test.go
Adds podman system prune for v2.
Refactoring for code reuse from pods containers images and volume prune.
Adds and enables testcases to support the added feature.
=> And system prune feature for v2.

libpod/container_inspect.go, libpod/oci_conmon_linux.go, libpod/runtime_pod_linux.go, pkg/util/mountOpts.go
=> Fix errors found in coverity scan

test/e2e/systemd_test.go
All functionality these require should be ported.
=> Reenable systemd E2E tests and one build E2E test

cmd/podman/containers/port.go, cmd/podman/parse/common.go, test/e2e/port_test.go
Adds port subcommand for containers
Updates check for no args when all flag is set.
=> Enables port test

cmd/podman/images/trust.go, cmd/podman/images/trust_set.go, cmd/podman/images/trust_show.go, pkg/domain/entities/engine_image.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/trust.go, pkg/domain/infra/tunnel/trust.go, pkg/trust/config.go, test/e2e/trust_test.go
add podman image trust set and show
=> v2trust set and show

cmd/podman/manifest/manifest.go, cmd/podman/manifest/push.go, cmd/podman/manifest/remove.go, completions/bash/podman, docs/source/markdown/podman-manifest-add.1.md, docs/source/markdown/podman-manifest-create.1.md, docs/source/markdown/podman-manifest-inspect.1.md, docs/source/markdown/podman-manifest-push.1.md, docs/source/markdown/podman-manifest-remove.1.md, docs/source/markdown/podman-manifest.1.md, pkg/domain/entities/engine_image.go, pkg/domain/entities/manifest.go, pkg/domain/infra/abi/manifest.go, pkg/domain/infra/tunnel/manifest.go, test/e2e/manifest_test.go
Implements podman manifest remove and podman manifest push.
=> Manifest remove, push

cmd/podman/login.go, cmd/podman/logout.go, go.mod, go.sum, test/e2e/login_logout_test.go, vendor/github.com/containers/common/pkg/auth/auth.go, vendor/github.com/containers/common/pkg/auth/cli.go, vendor/github.com/containers/common/pkg/config/default.go, vendor/modules.txt
import auth pkg to support empty login argument and enable login_logout tests
import c/common auth pkg PR https://github.com/containers/common/pull/135
=> auth pkg support emtpy argument & enable login test

contrib/cirrus/README.md, docs/Readme.md
=> CI:DOCS: Document API docs + CORS maintenance

rootless.md
Updated the link in ```rootless.md``` pointing 5th heading to 6th heading in the ```troubleshooting.md```
Signed-off-by: pr0PM <pmprateek88@gmail.com>
=> Hope it helps to keep the docs updated

cmd/podman/containers/runlabel.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers_runlabel.go, pkg/domain/infra/tunnel/containers.go, test/e2e/runlabel_test.go
Implement container runlabel for v2.  Local client only.
=> container runlabel

cmd/podman/auto-update.go, pkg/domain/entities/auto-update.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/auto-update.go, pkg/domain/infra/tunnel/auto-update.go
Add the `podman auto-update` command. There have been no tests in v1, so
there are no in v2 either ... for now :)
=> auto-update

.cirrus.yml, cmd/podman/containers/stats.go, cmd/podman/manifest/annotate.go, contrib/cirrus/setup_environment.sh, pkg/bindings/manifests/manifests.go, pkg/bindings/test/containers_test.go, pkg/bindings/test/manifests_test.go, pkg/bindings/test/pods_test.go, pkg/bindings/test/system_test.go, pkg/domain/infra/tunnel/manifest.go, pkg/specgen/generate/container.go, test/e2e/stats_test.go
some small fix ups for binding tests and then make them required.
Signed-off-by: bbaude <bbaude@redhat.com>
=> set binding tests to required

go.mod, go.sum, libpod/runtime.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/modules.txt
=> Update containers/common to v0.8.3

cmd/podman/images/search.go
enable the search command for rootless
=> v2 podman search rootless

cmd/podman/system/version.go, libpod/define/version.go, pkg/api/handlers/compat/version.go, pkg/api/handlers/types.go, pkg/api/server/register_version.go, pkg/api/server/swagger.go, pkg/bindings/system/system.go, pkg/domain/entities/engine_container.go, pkg/domain/entities/system.go, pkg/domain/infra/abi/system.go, pkg/domain/infra/tunnel/system.go
=> V2 Implement tunnelled podman version

pkg/bindings/test/containers_test.go
@baude @edsantiago @vrothberg PTAL
=> bindings tests for container remove and inspect

.cirrus.yml, test/e2e/events_test.go, test/e2e/generate_kube_test.go, test/e2e/libpod_suite_test.go, test/e2e/mount_test.go, test/e2e/play_kube_test.go, test/e2e/run_networking_test.go
=> enable rootless integration testing

SECURITY.md
=> [CI:DOCS] Add Security Policy

libpod/lock/shm/shm_lock_test.go
=> shm_lock_test: add nil check

test/system/030-run.bats, test/system/250-systemd.bats
run test: run positive test before negative; and actually
implement real negative tests. Note that '--conmon-pidfile'
will happily clobber an existing file; I don't know if that
is desired behavior. Also, add confirmation tests for
cidfile/pidfile, not just 'exit status is good'.
systemd test: enable rootless, and again add actual content
testing.
=> Some BATS cleanup: run and systemd tests

cmd/podman/system/reset.go, pkg/api/handlers/libpod/system.go, pkg/api/server/register_system.go, pkg/bindings/system/system.go, pkg/bindings/test/system_test.go, pkg/domain/entities/engine_system.go, pkg/domain/infra/abi/system.go, pkg/domain/infra/tunnel/runtime.go, pkg/domain/infra/tunnel/system.go
Adds tunnel route for system reset.
Adds relevant test cases and swagger docs.
=> Adds tunnel routes for system reset.

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/modules.txt
=> [1.9] vendor github.com/containers/common@v0.8.4

go.mod, go.sum, vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go, vendor/modules.txt
=> vendor crio/ocicni@v0.2.0

cmd/podman/containers/port.go, pkg/domain/infra/tunnel/containers.go
=> add port to podman remote command

cmd/podman/images/sign.go, pkg/domain/entities/engine_image.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images.go, pkg/domain/infra/tunnel/images.go
this is a straight port to add the podman image sign command. no improvements or refactoring done
=> v2podman image sign

cmd/podman/system/df.go, pkg/api/handlers/libpod/system.go, pkg/api/server/register_system.go, pkg/api/server/swagger.go, pkg/bindings/system/system.go, pkg/domain/infra/tunnel/system.go
=> add podman remote system df

cmd/podman/common/specgen.go, cmd/podman/containers/create.go, test/e2e/events_test.go, test/e2e/run_networking_test.go
=> rootless: do not set pids limits with cgroupfs

test/system/160-volumes.bats
=> system tests: add volume tests

cmd/podman/networks/create.go, cmd/podman/networks/inspect.go, cmd/podman/networks/list.go, cmd/podman/networks/network.go, cmd/podman/networks/rm.go, pkg/api/handlers/libpod/containers_create.go, pkg/api/handlers/libpod/networks.go, pkg/api/handlers/libpod/swagger.go, pkg/api/server/register_networks.go, pkg/api/server/server.go, pkg/api/server/swagger.go, pkg/api/tags.yaml, pkg/bindings/network/network.go, pkg/domain/entities/network.go, pkg/domain/infra/tunnel/network.go
=> enable podman v2 networking for remote client

changelog.txt, version/version.go
=> Bump to v1.9.2

pkg/api/handlers/libpod/images.go, pkg/bindings/images/images.go, pkg/domain/infra/tunnel/images.go
=> enable remote image tree

pkg/bindings/connection.go, pkg/bindings/containers/containers.go, pkg/bindings/test/attach_test.go
=> V2 Update attach bindings to use Readers/Writers vs chan

pkg/bindings/bindings.go, pkg/bindings/containers/containers.go, pkg/bindings/test/attach_test.go, pkg/bindings/test/containers_test.go, pkg/bindings/test/exec_test.go, pkg/bindings/test/images_test.go, pkg/bindings/test/pods_test.go, pkg/bindings/test/system_test.go, pkg/bindings/test/volumes_test.go, pkg/domain/infra/tunnel/helpers.go, pkg/domain/infra/tunnel/images.go
Small improvement for working with the API bindings.
* changed PFalse to &false
* changed PTrue to &true
=> Make convenience boxed true/false easier to use

.cirrus.yml, Dockerfile.ubuntu, contrib/cirrus/lib.sh, contrib/cirrus/packer/libpod_images.yml, contrib/cirrus/packer/ubuntu_packaging.sh, hack/get_ci_vm.sh
=> Cirrus: Update Ubuntu 18 to 20

go.mod, go.sum, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/modules.txt
=> vendor to containers/buildah 1.14.9

hack/podman-registry, hack/podman-registry-go/registry.go, hack/podman-registry-go/registry_test.go
Based on https://github.com/containers/libpod/pull/6269. Adding go-bindings.
=> Registry helper : go bindings

cmd/podman/containers/create.go, cmd/podman/containers/rm.go, pkg/bindings/images/images.go, pkg/domain/infra/tunnel/images.go, pkg/domain/infra/tunnel/manifest.go, test/e2e/common_test.go, test/e2e/create_test.go, test/e2e/images_test.go, test/e2e/kill_test.go, test/e2e/manifest_test.go, test/e2e/pause_test.go, test/e2e/save_test.go, test/e2e/stop_test.go, test/e2e/untag_test.go
=> Test fixes for remote integration

pkg/domain/infra/tunnel/containers.go, test/e2e/init_test.go
=> enable remote integration tests for init

libpod/container_internal.go, libpod/define/healthchecks.go, libpod/healthcheck.go, pkg/api/handlers/libpod/healthcheck.go, pkg/domain/infra/abi/healthcheck.go, pkg/varlinkapi/containers.go, test/e2e/healthcheck_run_test.go
the one remaining test that is still skipped do to missing exec function
=> Fix remote integration for healthchecks

cmd/podman/images/list.go, cmd/podman/images/prune.go, libpod/image/filters.go, pkg/api/handlers/utils/images.go, pkg/domain/entities/images.go, pkg/domain/infra/abi/images_list.go, pkg/domain/infra/tunnel/images.go, test/e2e/images_test.go
Enable three more tests
Fix handling of image filters
=> Fix remote handling of podman images calls

test/e2e/untag_test.go
=> remote untag test

cmd/podman/pods/create.go, test/e2e/pod_create_test.go
prints pod id pod create --pod-id-file and adds relevant test cases
=> Fixes podman pod create --pod-id-file #6292

.cirrus.yml, cmd/podman/pods/create.go, cmd/podman/system/service.go, docs/source/markdown/links/podman-image-diff.1, docs/source/markdown/links/podman-image-search.1, pkg/bindings/containers/containers.go, pkg/specgen/namespaces.go
=> Start testing with cross compilation

pkg/domain/infra/tunnel/containers.go, test/e2e/stop_test.go
=> Fix podman-remote stop --all to handle not running containers

test/e2e/images_test.go, test/e2e/pause_test.go, test/e2e/rm_test.go
=> Turn on more remote tests

cmd/podman/system/version.go, docs/source/markdown/podman-info.1.md, docs/source/markdown/podman-version.1.md, libpod/define/version.go, pkg/bindings/system/system.go, pkg/varlinkapi/system.go, test/system/001-basic.bats, version/version.go
Currently we are displaying the Seconds since EPOCH
this will change to displaying date, similar to `podman version`
=> Display human build date in podman info

cni/87-podman-bridge.conflist, pkg/network/netconflist.go
This may resolve some issues with routing traffic between containers using the host's IP.
=> Add HairpinMode to our CNI configs

test/system/200-pod.bats
=> Enables iidfile test as issue fixed now

.cirrus.yml
=> Attempt to turn on rpmbuild tests

.cirrus.yml
=> Attempt to turn on varlink tests

.cirrus.yml
=> Attempt to turn on special_testing_endpoint tests

docs/source/Commands.rst, docs/source/Introduction.rst, docs/source/Reference.rst, docs/source/Search.rst, docs/source/Tutorials.rst, docs/source/_static/api.html, docs/source/includes.rst, docs/source/index.rst
* Rewrote the Home and Introduction pages.
* Created a dedicated Search page
* Rewrote the Tutorials page to have native links in RTD/Shpinx
* Added iframe to Reference page to display API reference docs inline
Signed-off-by: Scott McCarty <scott.mccarty@gmail.com>
=> [CI:DOCS] Docs revamp.

.cirrus.yml
=> Attempt to turn on integration tests

.cirrus.yml
=> Enable rootless tests for podman remote

contrib/gate/Dockerfile
the gating image now needs conmon to perform the commands check
=> [CI:DOCS]Add conmon to gating image

changelog.txt, version/version.go
=> Bump to v1.9.3

commands-demo.md, pkg/domain/infra/abi/system_varlink.go
=> Follow up PR to fix issues found in #6341

pkg/api/server/server.go
=> Add MethodNotAllowedHandler() to add in debugging

contrib/dependencies.txt, contrib/gate/Dockerfile
=> [CI:DOCS] Prepare image to turn on podman-commands test

.cirrus.yml
=> Turn on Fedora31 testing.

contrib/gate/Dockerfile
=> Fix Dockerfile

pkg/bindings/connection.go, pkg/bindings/containers/containers.go, pkg/bindings/containers/logs.go, test/e2e/attach_test.go
Bugs fixes:
* Accept connections from services that don't provide version header
* Fix interface parameter nil checks. See https://golang.org/doc/faq#nil_error
=> V2 Fix interface nil checks

cmd/podman/pods/inspect.go, completions/bash/podman, docs/source/markdown/podman-pod-inspect.1.md, pkg/domain/entities/pods.go, test/system/200-pod.bats
=> Add --format to pod inspect

pkg/specgen/container_validate.go
=> Add invalid value to error message

cmd/podman/system/migrate.go, cmd/podman/system/renumber.go, cmd/podman/system/reset.go, cmd/podman/system/service.go, cmd/podman/system/service_abi.go, cmd/podman/system/service_unsupported.go, cmd/podman/system/varlink.go
=> Don't build code on remoteclient

test/system/075-exec.bats, test/system/200-pod.bats, test/system/500-networking.bats
- exec: add test for #5046, in which conmon swallowed chars
on a large byte transfer
- pod: add 'pod exists' tests, both positive and negative;
consolidate tests; add '--label', and check in 'pod inspect'
add 'pod ps' tests
- networking: add test for #5466, in which detached run
with --userns=keep-id would not forward a port
=> system tests : more tests

troubleshooting.md
=> Add information on detach-keys

go.mod, go.sum, vendor/github.com/containers/psgo/SECURITY.md, vendor/github.com/containers/psgo/psgo.go, vendor/modules.txt
Replacing Valentin's PR so we can get this merged.
=> Update vendor containers/psgo

pkg/domain/infra/tunnel/containers.go, test/e2e/rm_test.go
Turn on remote rm_test --cidfile
=> Turn on remote rm_test 

cmd/podman/containers/wait.go, test/e2e/create_test.go, test/e2e/diff_test.go, test/e2e/exists_test.go, test/e2e/healthcheck_run_test.go, test/e2e/inspect_test.go, test/e2e/pod_create_test.go, test/e2e/ps_test.go, test/e2e/pull_test.go, test/e2e/volume_rm_test.go
=> Add more Remote tests

pkg/domain/infra/tunnel/containers.go, test/e2e/stop_test.go
=> turn on remote stop_test

.cirrus.yml
=> Turn on the podman-commands script to verify man pages

.cirrus.yml, contrib/cirrus/integration_test.sh
=> Attempt to turn on special_testing_in_podman tests

libpod/container_log.go
Closes  #5302
Signed-off-by: Will Haines <william.haines@colorado.edu>
=> Fixed bug where 'podman log <container>' would truncate some lines.

contrib/spec/podman.spec.in
=> Fix builds for RDO

cmd/podman/common/specgen.go, test/e2e/images_test.go
Fixes https://github.com/containers/libpod/issues/6585
=> Do not default WorkingDir to / on client side

Dockerfile
=> Fix missing code during in_podman build

pkg/api/handlers/types.go
=> Add some additional fields to imageinspect

test/apiv2/40-pods.at
Add some tests for podman pods subcommand:
restart
rm
start
stas
stop
top
unpause
=> APIv2 tests: Add some tests for podman pods

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/modules.txt
=> Vendor containers/common v0.14.0

pkg/api/server/register_ping.go
* Update swagger documentation
=> [CI:DOCS] Fixes #6548

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/copy.go, vendor/github.com/containers/image/v5/oci/layout/oci_dest.go, vendor/github.com/containers/image/v5/types/types.go, vendor/github.com/containers/image/v5/version/version.go, vendor/github.com/klauspost/compress/fse/bitreader.go, vendor/github.com/klauspost/compress/fse/bytereader.go, vendor/github.com/klauspost/compress/huff0/README.md, vendor/github.com/klauspost/compress/huff0/bitreader.go, vendor/github.com/klauspost/compress/huff0/decompress.go, vendor/github.com/klauspost/compress/zstd/bitreader.go, vendor/github.com/klauspost/compress/zstd/blockdec.go, vendor/github.com/klauspost/compress/zstd/bytereader.go, vendor/github.com/klauspost/compress/zstd/decoder.go, vendor/github.com/klauspost/compress/zstd/fse_decoder.go, vendor/modules.txt
=> vendor github.com/containers/image/v5@v5.5.1

pkg/api/handlers/compat/images_build.go, pkg/api/server/register_images.go, pkg/bindings/images/images.go, pkg/domain/infra/tunnel/images.go
address problem when multiple -t were sent.  and rework remote build's tarball if a context dir is given other than ".".
Fixes: #6578
Fixes: #6577
=> fix misc remote build issues

pkg/specgen/generate/security.go, test/e2e/run_test.go, test/system/030-run.bats
=> Handle dropping capabilities correctly when running as non root user

pkg/bindings/containers/attach.go
* Move check for requesting output into case statement
reference #6574 
=> Correct logic for demux'ing channels

RELEASE_NOTES.md
=> [CI:DOCS] Update release notes for v2.0.0

README.md, changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v2.0.0

cmd/podman/images/build.go, test/e2e/build_test.go
Also fixed a todo for handling of cgroup manager while I was in there.
=> Fix podman build handling of --http-proxy flag

cmd/podman/main.go, cmd/podman/registry/config.go, cmd/podman/registry/config_tunnel.go, cmd/podman/root.go, cmd/podman/system/connection.go, docs/source/markdown/podman-system-connection.1.md, docs/source/markdown/podman-system.1.md, docs/source/markdown/podman.1.md, pkg/bindings/bindings.go, pkg/bindings/connection.go, pkg/domain/entities/engine.go, pkg/domain/infra/runtime_abi.go, pkg/domain/infra/runtime_tunnel.go, pkg/terminal/util.go
* Implement command
* Refactor podman to pull from containers.conf/connections.conf by default
* Write podman-system-connection.1.md
=> V2 podman system connection

go.mod, go.sum, vendor/github.com/containers/common/pkg/apparmor/apparmor.go, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Includes several fixes for config parsing and AppArmor.
=> vendor github.com/containers/common@v0.14.3

go.mod, go.sum, vendor/github.com/containers/common/pkg/apparmor/apparmor.go, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Includes several fixes for config parsing and AppArmor.
=> [2.0] vendor github.com/containers/common@v0.14.3

cmd/podman/registry/config_tunnel.go
* quick --remote fix, sent --remote to ctnrs as argument
=> Revert sending --remote flag to containers

RELEASE_NOTES.md, cmd/podman/common/specgen.go, cmd/podman/containers/create.go, cmd/podman/containers/run.go, cmd/podman/registry/config_tunnel.go, pkg/api/handlers/compat/exec.go, pkg/ps/ps.go, pkg/specgen/generate/container_create.go, pkg/specgen/specgen.go, pkg/systemd/generate/containers.go, pkg/systemd/generate/containers_test.go, test/e2e/ps_test.go, test/system/030-run.bats
As the title says - check individual commits for details.
=> Even more v2.0.1 backports

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v2.0.1

test/e2e/inspect_test.go
Make sure that all specified security options are displayed in a
container's inspect data.
=> e2e inspect: HostConfig.SecurityOpt

cmd/podman/shared/create.go, cni/87-podman-bridge.conflist, libpod/container_api.go, libpod/container_internal.go, libpod/container_internal_linux.go, libpod/healthcheck.go, libpod/oci_conmon_linux.go, pkg/network/netconflist.go, test/e2e/exec_test.go, test/e2e/run_volume_test.go, vendor/github.com/containers/buildah/imagebuildah/util.go, vendor/github.com/containers/buildah/pkg/secrets/secrets.go, vendor/github.com/containers/buildah/run_linux.go, vendor/github.com/containers/storage/store.go
This is everything, minus a c/image CVE fix from @vrothberg that had a truly stupendous amount of conflicts in vendor/, plus a fix for `--security-opt` issues encountered by the Openstack team
=> Lots of Podman 1.6 backports

cmd/podman/shared/create.go
Currenty if the user specifies --pid=host or --ipc=host or --privileged
then we disable SELinux labeling. If the user however specifies
--security-opt label:...  Then we assume they want to leave SELinux enabled
and know what they are doing.
This PR will leave SELinux enabled if a user specifies a --security-opt label
option.
=> Don't disable selinux labels if user specifies a security opt

go.mod, go.sum, vendor/github.com/openshift/imagebuilder/builder.go, vendor/github.com/openshift/imagebuilder/imagebuilder.spec, vendor/github.com/openshift/imagebuilder/internals.go, vendor/modules.txt
As the title says, but for the v2.0 branch
=> Bump to imagebuilder v1.1.6 on v2 branch

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> Vendor containers/common v0.14.4

libpod/events.go
Fix a race that could cause read errors to be masked.  Masking such
errors is likely to report red herrings since users don't see that
reading failed for some reasons but that a given event could not be
found.
=> fix race condition in `libpod.GetEvents(...)`

RELEASE_NOTES.md
=> [CI:DOCS] Finalize release notes for Podman v2.0.2

libpod/events.go
Fix a race that could cause read errors to be masked.  Masking such
errors is likely to report red herrings since users don't see that
reading failed for some reasons but that a given event could not be
found.
Backport-of: commit f4a2d25c0fca
=> [2.0] fix race condition in `libpod.GetEvents(...)`

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v2.0.2

.cirrus.yml
=> Cirrus: Rotate keys post repo. rename

.cirrus.yml, Dockerfile, Dockerfile.ubuntu
=> CI:DOCS Minor: Remove two inaccurate comments

README.md, RELEASE_NOTES.md
Also update README to reflect the new release.
=> [CI:DOCS] Update release notes on Master for v2.0.2

cmd/podman/images/list.go
Follow-up to https://github.com/containers/podman/pull/6872 (Rebranched)
Uses reference package to parse as requested by @vrothberg 
Signed-off-by: Parker Van Roy <pvanroy@redhat.com>
=> using reference package to parse

rootless.md
Replaces https://github.com/containers/podman/pull/6682
Signed-off-by: James Cassell <code@james.cassell.me>
=> document CAP_SYS_ADMIN required for systemd PrivateNetwork

cmd/podman/common/specgen.go, cmd/podman/common/volumes.go, docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-run.1.md, libpod/container.go, libpod/container_internal.go, libpod/container_internal_linux.go, libpod/container_internal_unsupported.go, libpod/container_validate.go, libpod/options.go, libpod/runtime.go, pkg/specgen/generate/container_create.go, pkg/specgen/specgen.go, pkg/util/mountOpts.go, test/e2e/run_volume_test.go
Add support for overlay volume mounts in podman.
=> Add support for overlay volume mounts in podman.

test/system/015-help.bats
The error messages from the 'podman xxx --help' cross-check
test are unhelpful, and cause much wasted time when they trigger.
Solution: instead of using the built-in exit-status check
in run_podman, do an explicit check outside of run_podman.
This lets us die() with a custom, hopefully useful, message.
=> BATS help-message test: improve diagnostics

libpod/events/journal_linux.go, libpod/events/logfile.go, pkg/api/handlers/compat/events.go, pkg/bindings/test/system_test.go, test/e2e/events_test.go
Backports of: https://github.com/containers/podman/pull/6902
=> [2.0] events fixes

pkg/domain/infra/abi/play.go, test/e2e/play_kube_test.go
fix https://github.com/containers/podman/issues/6995 https://github.com/containers/podman/issues/5730 https://github.com/containers/podman/issues/7019
=> fix podman play kube doesn't override dockerfile ENTRYPOINT

test/e2e/attach_test.go, test/e2e/build_test.go, test/e2e/common_test.go, test/e2e/generate_kube_test.go, test/e2e/libpod_suite_remote_test.go, test/e2e/libpod_suite_test.go, test/e2e/load_test.go, test/e2e/pull_test.go, test/e2e/run_passwd_test.go, test/e2e/run_privileged_test.go, test/e2e/run_test.go, test/e2e/search_test.go
=> Enable a bunch of remote tests

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/systemd.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> Bump github.com/containers/common to v0.14.6

cmd/podman/registry/config.go
=> Enable --remote flag

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> Bump to v2.0.3

README.md, RELEASE_NOTES.md
Update the Master release notes and README to reflect the release of v2.0.3
=> [CI:DOCS] Update release notes and README on master for v2.0.3

docs/source/markdown/podman-run.1.md
=> [CI:DOCS] Fix exit code example in podman-run.1.md

pkg/api/handlers/compat/events.go, test/apiv2/01-basic.at
=> [2.0] events parsing fix #7078

libpod/container_internal.go
=> When chowning we should not follow symbolic link

cmd/podman/containers/ps.go, test/e2e/ps_test.go
For docker compatibility
#5535
=> add {{.RunningFor}} placeholder in ps --format

libpod/oci_conmon_linux.go
Test flakes mentioned in #6987 might be caused by uncorrect closing of file descriptor.
Remove the code to close file descriptors for `podman run` since it may close those used by other processes.
@giuseppe PTAL. The same flakes happened to podman exec once and got fixed, but does not work for `podman run`, is this a feasible fix?
=> Fix close fds of run --preserve-fds

RELEASE_NOTES.md
=> [CI:DOCS] Update release notes for v2.0.4

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v2.0.4

README.md, RELEASE_NOTES.md
Ensure that master includes information on the new v2.0.4 release.
=> [CI:DOCS] Update master README and release notes for v2.0.4

pkg/api/server/register_ping.go, test/apiv2/01-basic.at, test/apiv2/rest_api/test_rest_v1_0_0.py
Add versioned _ping endpoints
Fixes #7008
=> Add versioned _ping endpoint

Makefile, contrib/spec/podman.spec.in
Continuation of https://github.com/containers/podman/pull/6885 installing also for users.
=> Systemd: install auto-update service and timer

go.mod, go.sum, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/.gitignore, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/chroot/run.go, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/github.com/containers/buildah/imagebuildah/stage_executor.go, vendor/github.com/containers/buildah/pkg/parse/parse.go, vendor/github.com/containers/buildah/run_linux.go, vendor/modules.txt
=> Bump Buildah to v1.15.1 on v2.0 branch

Makefile, contrib/remote/containers.conf, pkg/domain/infra/abi/play.go, test/e2e/play_kube_test.go
KubeIP and Default conf didn't get put in last version
=> v2.0 Backports

cmd/podman/common/create.go, cmd/podman/containers/create.go, cmd/podman/containers/run.go
We have duplicated alias handling, removing.
=> Remove duplicated code

pkg/network/network.go, test/apiv2/35-networks.at
In the absence of parameter verification, an incorrect network will be created https://github.com/containers/podman/issues/7262#issuecomment-670967217
=> Add parameter verification for api creation network

contrib/cirrus/lib.sh, seccomp.json
Fix the Ci for our 2.0.x branch.
=> Fix v2.0.x CI

docs/source/Tutorials.rst, docs/tutorials/README.md, docs/tutorials/podman-go-bindings.md
Include the Go bindings blog post as a tutorial
@TomSweeneyRedHat
=> [CI:DOCS] docs: include Go bindings tutorial

.cirrus.yml, nix/nixpkgs.json
Signed-off-by: Wong Hoi Sing Edison <hswong3i@gmail.com>
=> Update nix pin with `make nixpkgs`

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/config_darwin.go, vendor/github.com/containers/common/pkg/config/config_linux.go, vendor/github.com/containers/common/pkg/config/config_windows.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
This will fix the localions of the containers.conf file
on Windows and MacOS Boxes.
=> Vendor in containers/common v0.14.9

docs/remote-docs.sh, docs/source/markdown/podman-remote.1.md
Add support for multi level subcommands.
e.g. podman system connection.
Update the flags and add note for containers.conf.
=> [CI:DOCS] Update podman-remote docs

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config_windows.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> Bump c/common to v0.14.10 and c/conmon to v2.0.20

docs/remote-docs.sh, docs/source/markdown/podman-remote.1.md
add remote docs to be built
allow docs to be properly built on macs
=> [CI:DOCS] remote doc fixes

RELEASE_NOTES.md, changelog.txt, version/version.go
=> Bump to v2.0.6-rc1

README.md, RELEASE_NOTES.md
Adds release notes and updates current version in README.
=> [CI:DOCS] Update Master to reflect v2.0.5 release

cmd/podman/registry/config.go
Backport #7042
Somehow this got missed.
=> Enable --remote flag v2.0

libpod/reset.go
Check if storage.conf exists and display a message that
this file should be removed if it has not been modified.
Fixes #7447
=> Don't remove config files with podman system reset

libpod/kube.go, test/e2e/generate_kube_test.go
Fixes: https://github.com/containers/podman/issues/7468
=> fix podman generate kube with HostAliases

pkg/domain/infra/abi/play.go, pkg/spec/createconfig.go, test/e2e/play_kube_test.go
Fixes: https://github.com/containers/podman/issues/7442
=> handle play kube with pod.spec.hostAliases

RELEASE_NOTES.md, changelog.txt, contrib/spec/podman.spec.in, libpod/container_internal.go, libpod/container_internal_linux.go, libpod/util.go, test/e2e/run_passwd_test.go, version/version.go
Two final backports, minor release notes updates, and a release bump.
=> Bump to v2.0.6 Final

README.md, RELEASE_NOTES.md
Also update README to reflect the new release.
=> [CI:DOCS] Update master with release notes for v2.0.6

.cirrus.yml
Adding a mac build to ci for native builds
=> [CI:DOCS]  Add macos build to ci

pkg/api/handlers/libpod/pods.go, test/apiv2/40-pods.at
Fixes: https://github.com/containers/podman/issues/6514
=> fix APIv2 pods top of non-exist pod gets two response value

cmd/podman/images/build.go, test/e2e/build_test.go
Currently this command blows up because it closes the file descriptor before
doing the build.
Add tests to make sure we don't regress.
=> Fix podman build --logfile

OWNERS
I keep forgetting to /approve PRs as Ed really doesn't need an explicit
approval.
Note: the first commit sorts the items.
=> add @edsantiago to OWNERS file

troubleshooting.md
Add entry to troubleshooting to document how to setup a read-only rootfs to
use with Podman.
Fixes: https://github.com/containers/podman/issues/5895
=> [CI:DOCS] Document --read-only --rootfs requirements

cmd/podman/images/build.go, cmd/podman/root.go, docs/source/markdown/podman-build.1.md, docs/source/markdown/podman.1.md, libpod/oci_conmon_linux.go, libpod/oci_conmon_unsupported.go, libpod/options.go, libpod/runtime.go, pkg/domain/entities/engine.go, pkg/domain/infra/runtime_libpod.go, test/system/030-run.bats, test/system/070-build.bats
Add global options --runtime-flags for setting options to container runtime.
close #6986
=> Add global options --runtime-flags

completions/bash/podman
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1873650
=> Fix completions for namespaces

go.mod, vendor/modules.txt
No code changes as we vendored a pre-release commit.
=> vendor github.com/containers/image/v5@v5.6.0

pkg/api/handlers/compat/events.go
Do not wait for events to occur before writing the OK header.
Events can take an unknown amount of time to occur and clients
do not need to wait until then to know if the connection is
good.
Fixes: #7263
=> events endpoint: header: do not wait for events

docs/source/markdown/podman-remote.1.md, docs/source/markdown/podman.1.md
=> Document the connection path for podman --remote

completions/bash/podman
Fixes: https://github.com/containers/podman/issues/7668
=> fix missing completion in podman run

Makefile
* Use the BUILDFLAGS variable for all Go builds
* Use `go install` instead of manually specifying the GOBIN path
Signed-off-by: Jordan Christiansen <xordspar0@gmail.com>
=> Make Go builds more consistent

Makefile
The configuration for this container has moved to the
containers/automation_images repository.  Leverage the
new location to guarantee synchronization with containers
used in CI.
=> Makefile: Remove broken targets

test/system/010-images.bats
Regression test for rhbz1879622, in which 'podman pull' of
an image by @sha would cause subsequent 'podman images -a'
to crash and burn.
=> [v2.0.5-rhel] System tests: new test for 'pull @sha' + 'images -a'

pkg/api/handlers/compat/containers_stats.go
* Write OK header once
* Detect closed client connections
@baude @jwhonce PTAL
=> remote stats fixes

libpod/container_exec.go, test/e2e/exec_test.go
=> [v2.0.5-rhel] Preserve groups in exec sessions in ctrs with --user

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v2.1.0

pkg/api/server/handler_api.go
Aids in reading logs of different services
=> Add Server header to API service responses

README.md
=> [CI:DOCS] Bump version in README to v2.1.0

test/e2e/systemd_test.go
=> Systemd should be able to run as rootless

cmd/podman/containers/stats.go, pkg/api/handlers/libpod/containers_stats.go, pkg/api/server/register_containers.go, pkg/bindings/containers/containers.go, pkg/domain/entities/containers.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/containers.go, pkg/domain/infra/tunnel/containers.go, test/e2e/stats_test.go
I want to throw it at CI. I'm on F33 (and need to setup a F32 VM for testing).
=> remote stats

.cirrus.yml, contrib/spec/podman.spec.in, version/version.go
Bump the development version of the new v2.1 branch
=> Bump to v2.1.1-dev

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v2.1.1

test/system/030-run.bats
Test that the journald log driver writes to journald and
that we can read it with journalctl.
=> Journald log driver test

README.md
Adds missing . to README.md file.
Signed-off-by: Fredrik Lindqvist <landrash@mail.com>
=> [CI:DOCS] Adds missing . to README.md file.

transfer.md
There are some differences in behaviour between docker and podman which should be documented to help developers while transitioning.
=> [CI:DOCS] Add section about current differences

test/e2e/common_test.go, test/e2e/exec_test.go, test/e2e/systemd_test.go
These tests are failing due to slightly wider coverage in #6784 but otherwise should be fixed anyway.
=> Fix two e2e tests

test/e2e/mount_test.go, test/e2e/network_test.go, test/e2e/run_memory_test.go
=> Attempt to test all Broken SkipIfRootless FIXME

test/e2e/network_test.go
The network test created config files with random filenames
but the network name was static. Since the tests can run in
parallel podman was not able to distinguish the networks.
We need to make sure that each test has its own config file
and network name. This helps to prevent unnecessary flakes.
I believe this should fix the flakes described in this comment: https://github.com/containers/podman/issues/7808#issuecomment-700283694
=> Fix some flakes in the e2e network tests.

test/e2e/run_security_labels.go, test/e2e/run_test.go
some small fixes for testing on fedora 33 (non-btrfs)
=> misc fixes for f33 integration tests

pkg/rootless/rootless_linux.go
when newidmap is not installed the code would hit the
reexec_in_user_namespace_wait code and wait for the child process to
be terminated.  The child process is blocked waiting on the w pipe.
So make sure to unblock the child process first and then clean it up.
Closes: https://github.com/containers/podman/issues/7776
Signed-off-by: Giuseppe Scrivano <giuseppe@scrivano.org>
(cherry picked from commit 7147c935aa29dca2f89083bfbe2c058a0ca69857)
=> [2.1] rootless: fix hang when newidmap is not installed

cmd/podman/common/createparse.go, cmd/podman/common/specgen.go, completions/bash/podman, test/e2e/run_test.go
FIxes: https://github.com/containers/podman/issues/7878
=> [podman run] --rm option shold conflicts with --restart

cmd/podman/inspect/inspect.go, cmd/podman/pods/inspect.go
* podman xyz inspect
* Add regex for mapping spaces in {{ *.Id *}} -> {{.ID}}
=> Restore --format 'table...' to commands

pkg/api/handlers/compat/containers_create.go
when using the compatibility mode as rootless, containers that were created were not setting their host names correctly due to the netmode not being set.
Fixes: #7934
=> APIv2 compatibility rootless network fix

CONTRIBUTING.md
Hi people,
I started using Podman some times ago, and like it. Also I'm looking for a OSS project where I can stay longer.
So... I went through CONTRIBUTING.md, but I couldn't run make binaries. I missed some libs/PATH, resolving this issue taken some time. Maybe this section will be helpful for newcomers like me.
Signed-off-by: 3sky 3sky@protonmail.com
=> add prerequisite section before building binaries

cmd/podman/containers/ps.go, cmd/podman/volumes/list.go, test/e2e/ps_test.go, test/e2e/volume_ls_test.go
* volume ls
* container ps
* updated broken tests when skip removed
=> Port V1 --format table to V2 podman

pkg/api/handlers/compat/events.go
=> Monitor for client closing stream

docs/source/Introduction.rst
Signed-off-by: Stefan Rua <stefan.rua@iki.fi>
=> [CI:DOCS] Fix documentation link and typo

cmd/podman/containers/stats.go, cmd/podman/pods/ps.go, docs/source/markdown/podman-pod-ps.1.md, docs/source/markdown/podman-stats.1.md
Restore formatting for stats
Fix formatting for pod ps
=> Restore --format: container stats & pod ps

.cirrus.yml
=> Cirrus: Execute docker-py tests on a VM

docs/source/markdown/podman-container-exists.1.md, docs/source/markdown/podman-container-prune.1.md, docs/source/markdown/podman-container-runlabel.1.md, docs/source/markdown/podman-generate-kube.1.md, docs/source/markdown/podman-generate-systemd.1.md, docs/source/markdown/podman-image-exists.1.md, docs/source/markdown/podman-image-prune.1.md, docs/source/markdown/podman-play-kube.1.md, docs/source/markdown/podman-pod-exists.1.md, docs/source/markdown/podman-restart.1.md
Signed-off-by: Jordan Christiansen <xordspar0@gmail.com>
=> [CI:DOCS] Make man page headings more consistent

cmd/podman/containers/ps.go, test/e2e/ps_test.go
When defining multiple ports (same src/dst) like `-p 80:80 -p 443:443`
then podman will not show the complete output on `podman ps` (only
`0.0.0.0:80->80/tcp` in the example). This also applies to port ranges.
This patch refactors the port loop by pre-checking for ranges and
displaying them correctly to the end user.
=> Fix ps port output

libpod/container_log_linux.go, pkg/api/handlers/compat/images.go, test/apiv2/10-images.at, test/e2e/logs_test.go, test/system/035-logs.bats
Backports for a couple fixes that were approved but never made it into the branch.
=> V2.1.1 RHEL backports

pkg/domain/infra/abi/cp.go, test/e2e/cp_test.go
Signed-off-by: Matej Vasek <mvasek@redhat.com>
=> fix: respect "--extract" flag for podman cp

.cirrus.yml
Fixes https://cirrus-ci.com/task/5111794769330176
=> Cirrus: Simplify CI for minimal testing

test/apiv2/30-volumes.at
Add test cases to cover below podman volume subcommand:
create
ls
inspect
rm
prune
Signed-off-by: Yuhui Jiang <yujiang@redhat.com>
=> Add test cases to cover podman volume

cmd/podman/registry/registry.go, cmd/podman/system/service.go
=> Create the default root API address path

CONTRIBUTING.md, README.md, docs/Readme.md
=> [CI:DOCS] Fix broken CI readme links

go.mod, go.sum, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/mount.go, vendor/modules.txt
Bump Buildah to v1.17.0 on Master.
=> Bump Buildah to v1.17.0

test/e2e/toolbox_test.go
When --userns=keep-id is used, Podman is supposed to set up the home
directory of the user inside the container to match that on the host
as long as the home directory or any of its parents are marked as
volumes to be bind mounted into the container.
Currently, the test only considers the case where the home directory
itself is bind mounted into the container. It doesn't cover the Podman
code that walks through all the bind mounts looking for ancestors in
case the home directory itself wasn't specified as a bind mount.
Therefore, this improves the existing test added in commit
6ca8067956128585 ("Setup HOME environment when using --userns=keep-id")
Signed-off-by: Debarshi Ray <rishi@fedoraproject.org>
=> Test $HOME when it's parent is bind mounted with --userns=keep-id

docs/source/markdown/containers-mounts.conf.5.md
Signed-off-by: Ralf Haferkamp <rhafer@suse.com>
=> docs: Mention mounts.conf location for non-root users

OWNERS
Lets add Urvashi to podman OWNERS so she can review and merge PRs.
=> [CI:DOCS]Add Urvashi to podman OWNERS

docs/source/markdown/podman-import.1.md, docs/source/markdown/podman-pull.1.md
See individual commit messages, hopefully this is self-explanatory.
=> [CI:DOCS] man pages: add an example, tweak formatting

test/e2e/logs_test.go
Fixes: https://github.com/containers/podman/issues/7942
=> Test podman-remote logs works the same as podman logs

docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-run.1.md
=> [CI:DOCS] Explain the relation between --pod and --network

cmd/podman/networks/list.go
=> Fix missing headers in `network ls`

RELEASE_NOTES.md
As the title says. Also includes v2.1.1, which apparently never made it to master from the branch.
=> [CI:DOCS] Add release notes for v2.2.0-RC1

hack/release.sh
=> Fix sed regex to update version in version/version.go

contrib/systemd/system/podman.service, docs/source/conf.py, docs/source/markdown/podman-system-service.1.md, pkg/api/server/handler_api.go, pkg/api/server/listener_api.go, pkg/api/server/server.go
* Log endpoint calls at level Info
* Ensure API server started at level Info
Fixes #8390
=> Make podman service log events

pkg/domain/entities/images.go
fixes https://github.com/containers/podman/issues/8418
=> REST API v2 - list of images - mandatory Created attribute

cmd/podman/common/completion.go, cmd/podman/root.go
The problem is that we always unconditionally setup up the
`ContainerEngine/ImageEngine`. This requires an running
endpoint. Most completions (e.g. flag names) do not need
them and should not fail. This commit makes sure we only
setup the engines as needed in the completions.
=> Enable remote shell completion without a running endpoint

cmd/podman/common/create_opts.go, libpod/networking_linux.go, pkg/api/handlers/compat/containers_create.go, pkg/api/handlers/types.go, test/apiv2/rest_api/__init__.py, test/apiv2/rest_api/test_rest_v2_0_0.py, test/apiv2/rest_api/v1_test_rest_v1_0_0.py, test/python/docker/__init__.py, test/python/docker/common.py, test/python/docker/test_containers.py, test/python/docker/test_images.py
=> Jhoncompat

cmd/podman/common/completion.go, cmd/podman/containers/top.go, cmd/podman/pods/top.go
=> Implement shell completion for podman top

libpod/image/manifests.go
Avoid using the image from load storage for `manifest create` and `manifest add`
since the local image does not include other entries of the list from the registry.
`--all` flag of `manifest create` and `manifest add` can not add all of the lists as expected.
=> Not use local image create/add manifest 

test/apiv2/25-containersMore.at
Signed-off-by: Edward Shen <weshen@redhat.com>
=> Add APIv2 tests for kube generate

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> Bump to v2.2.0

README.md
=> [CI:DOCS] Bump version in README to v2.2.0

libpod/runtime_pod_infra_linux.go
It looks like this was previously removed because the default hard-coded `/pause` so we would never take into account the image config. I've removed the default in c/common and re-added support to check config files.
While we're at it, fix ENTRYPOINT support - we should not be setting this if we got ENTRYPOINT from the image.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1853455
=> Do not ignore infra command from config files

troubleshooting.md
See https://github.com/containers/podman/issues/8592
=> [CI:DOCS] Clarify uid range requirements

pkg/domain/infra/abi/images.go
Previously close rawSouce in the middle makes future use of rawSource invalid.
Move the rawSource.Close() to the end of each loop.
Close #8583 
=> Close image rawSource when each loop ends

go.mod, go.sum, libpod/networking_linux.go, test/e2e/config/containers.conf, test/e2e/containers_conf_test.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Wire in containers.conf options for slirp
Vendor in containers/common v0.30.0 
Closes https://github.com/containers/podman/issues/7888
=>  Add ability to set system wide options for slirp4netns

test/apiv2/25-containersMore.at
Signed-off-by: Edward Shen <weshen@redhat.com>
=> Add APIv2 test for containers-prune

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> Bump to v2.2.1

cmd/podman/inspect/inspect.go, test/e2e/inspect_test.go, test/utils/utils.go
* Add template func to inspect template processing
* Added test using repro from #8444
Fixes #8444
=> Restore json format for fields as well as whole structs

docs/source/markdown/podman-auto-update.1.md
=> auto updates: document systemd unit and timer

cmd/podman/system/prune.go, docs/source/markdown/podman-container-prune.1.md, docs/source/markdown/podman-image-prune.1.md, docs/source/markdown/podman-system-prune.1.md, pkg/domain/entities/system.go, pkg/domain/infra/abi/system.go
Also document the allowable filters in podman system prune, podman image prune
and podman container prune.
=> Add --filter to podman system prune

cmd/podman/common/completion.go, cmd/podman/common/netflags.go, cmd/podman/play/kube.go
Complete all the options e.g. `container:`,`ns:`,`host`, etc...
=> shell completion for the network flag

libpod/util.go
- refactor package query logic to be package manager agnostic.
- `pacman -Qo` is the equivalent to `rpm -qf` [1].
[1] https://wiki.archlinux.org/index.php/Pacman/Rosetta#Querying_specific_packages
----
Changes are tested on my local box (Arch) and a Ubuntu 20.04 container. See below for details.
```
$ make binaries
go build -mod=vendor  -gcflags 'all=-trimpath=/home/xatier/tmp/podman' -asmflags 'all=-trimpath=/home/xatier/tmp/podman' -ldflags '-X github.com/containers/podman/v2/libpod/define.gitCommit=e4e9a139024c771c70a429e9d818fdfe3e63dcbe-dirty -X github.com/containers/podman/v2/libpod/define.buildInfo=1608062677 -X github.com/containers/podman/v2/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v2/libpod/config._etcDir=/etc ' -tags "    systemd …
```
=> Add support for pacman package version query

pkg/api/handlers/compat/resize.go
=> Expose Height/Width fields to decoder

libpod/oci_conmon_exec_linux.go, libpod/oci_conmon_linux.go, test/e2e/exec_test.go, test/e2e/run_privileged_test.go
write the capabilities to the configuration passed to the OCI
runtime.
=> exec: honor --privileged

go.mod, go.sum, vendor/github.com/containers/psgo/internal/capabilities/capabilities.go, vendor/github.com/containers/psgo/internal/dev/tty.go, vendor/github.com/containers/psgo/internal/proc/status.go, vendor/github.com/containers/psgo/internal/process/process.go, vendor/github.com/containers/psgo/psgo.go, vendor/modules.txt
=> vendor containers/psgo@v1.5.2

libpod/runtime_pod_infra_linux.go, pkg/specgen/generate/security.go
The existing code prevents containers.conf default sysctls from being added if the container uses a host namespace. This patch expands that to not just host namespaces, but also *shared* namespaces - so we never modify another container's (or a pod's) namespaces without being explicitly directed to do so by the user.
=> Ignore containers.conf sysctls when sharing namespaces

.cirrus.yml, contrib/cirrus/runner.sh
=> Cirrus: Skip most tests on tag-push

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/retry/retry.go, vendor/github.com/containers/common/pkg/retry/retry_linux.go, vendor/github.com/containers/common/pkg/retry/retry_unsupported.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> Vendor in common 0.33.1

cmd/podman/containers/rename.go, docs/source/markdown/links/podman-container-rename.1, pkg/bindings/containers/rename.go, pkg/bindings/containers/types.go, pkg/bindings/containers/types_rename_options.go, pkg/domain/infra/tunnel/containers.go, test/e2e/rename_test.go
Add bindings and podman-remote support for container rename.
=> Container rename bindings

pkg/bindings/images/build.go, test/e2e/build_test.go
It'is a pr about the issue #8374
=> podman remote send tar

pkg/bindings/README.md
Add a brief description of the golang bindings and provide examples on
how to use them
=> [CI:DOCS]Add README.md for golang bindings

RELEASE_NOTES.md
=> [ci:docs] Create release notes for V3.0.0

.cirrus.yml, changelog.txt, version/version.go
=> Bump to v3.0.0-rc1

cmd/podman/networks/exists.go, docs/source/markdown/podman-network-exists.1.md, docs/source/markdown/podman-network.1.md, docs/source/network.rst, pkg/api/handlers/libpod/networks.go, pkg/api/server/register_networks.go, pkg/bindings/network/network.go, pkg/bindings/network/types.go, pkg/bindings/network/types_exists_options.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/network.go, pkg/domain/infra/tunnel/network.go, test/e2e/network_test.go
Add podman network exists command with remote support.
=> podman network exists

cmd/podman/volumes/exists.go, docs/source/markdown/podman-network-exists.1.md, docs/source/markdown/podman-volume-exists.1.md, docs/source/markdown/podman-volume.1.md, docs/source/volume.rst, pkg/api/handlers/libpod/volumes.go, pkg/api/server/register_volumes.go, pkg/bindings/volumes/types.go, pkg/bindings/volumes/types_exists_options.go, pkg/bindings/volumes/volumes.go, pkg/domain/entities/engine_container.go, pkg/domain/infra/abi/volumes.go, pkg/domain/infra/tunnel/volumes.go, test/e2e/volume_exists_test.go
Add podman volume exists command with remote support.
=> Podman volume exists

test/e2e/images_test.go, test/e2e/prune_test.go, test/e2e/rmi_test.go
Just running through the tests that have SkipIfRemote("FIXME")
and attempting to not skip. Found these tests now work.
=> Turn on some remote test

cmd/podman/manifest/exists.go, docs/source/manifest.rst, docs/source/markdown/podman-manifest-exists.1.md, docs/source/markdown/podman-manifest.1.md, libpod/image/manifests.go, pkg/api/handlers/libpod/manifests.go, pkg/api/server/register_manifest.go, pkg/bindings/manifests/manifests.go, pkg/bindings/manifests/types.go, pkg/bindings/manifests/types_exists_options.go, pkg/domain/entities/engine_image.go, pkg/domain/infra/abi/manifest.go, pkg/domain/infra/tunnel/manifest.go, test/e2e/manifest_test.go
Add podman manifest exists command with remote support.
=> podman manifest exists

test/apiv2/rest_api/test_rest_v2_0_0.py
Signed-off-by: Milivoje Legenovic <m.legenovic@gmail.com>
=> Small API test improvement for compatibility search endpoint

test/system/400-unprivileged-access.bats
Backport one component of #9091 in hopes of fixing RHEL8
gating test failures.
=> [v3.0] fix RHEL gating test: the /sys thing

cmd/podman/images/build.go, docs/source/markdown/podman-build.1.md, test/system/070-build.bats
Also correct the help message and docs.
@TomSweeneyRedHat @rhatdan @baude PTAL
=> Revert "podman build --pull: use correct policy"

go.mod, go.sum, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/github.com/containers/buildah/imagebuildah/stage_executor.go, vendor/github.com/containers/buildah/new.go, vendor/github.com/containers/buildah/util/types.go, vendor/github.com/containers/buildah/util/util.go, vendor/modules.txt
=> Vendor in containers/buildah v1.19.3

.cirrus.yml, contrib/cirrus/required_host_ports.txt, contrib/cirrus/runner.sh, nix/default.nix, nix/nixpkgs.json
=> [v3.0] Use cachix for static build & include podman-remote build

RELEASE_NOTES.md
Update release notes for v3.0. I'll need this for my presentation at the community meeting tomorrow.
As a side note, we really need to do releases more often. I was digging out commits from back in November for this.
=> [CI:DOCS] Update release notes for v3.0.0

cmd/podman/images/build.go, test/system/070-build.bats
=> [v2.2.1-rhel] Fix podman build --logfile

docs/tutorials/rootless_tutorial.md
=> [CI:DOCS] typo

go.mod, go.sum, vendor/github.com/containers/common/pkg/report/doc.go, vendor/github.com/containers/common/pkg/report/template.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> [v2.2.1-rhel] Update vendor of c/common to v0.29.1

go.mod, go.sum, vendor/github.com/containers/common/pkg/report/template.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> Bump to containers/common v0.33.4

cmd/podman/images/build.go, go.mod, go.sum, pkg/domain/infra/tunnel/images.go, test/e2e/build_test.go, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/buildah.go, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/commit.go, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/github.com/containers/buildah/imagebuildah/executor.go, vendor/github.com/containers/buildah/imagebuildah/stage_executor.go, vendor/github.com/containers/buildah/run_linux.go, vendor/modules.txt
=> Bump containers/buildah to v1.19.4

go.mod, go.sum, vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go, vendor/github.com/containers/image/v5/version/version.go, vendor/modules.txt
=> vendor github.com/containers/image v5.10.2

go.mod, go.sum, vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go, vendor/github.com/containers/image/v5/version/version.go, vendor/modules.txt
=> [3.0] vendor github.com/containers/image v5.10.2

pkg/api/handlers/compat/images_push.go, test/apiv2/12-imagesMore.at
Push endpoint will return message containing image digest.
Signed-off-by: Matej Vasek <mvasek@redhat.com>
=> Docker [APIv2] push sends digest in response body

version/version.go
Given we branched for 3.0 already, bumping the version in the main
branch will help prevent confusion in case users report issues on main
versus the v3.0 branch.
@mheon PTAL
=> bump to v3.1.0-dev

RELEASE_NOTES.md, changelog.txt, cmd/podman/common/completion.go, contrib/spec/podman.spec.in, libpod/container_inspect.go, libpod/container_internal.go, libpod/container_internal_linux.go, libpod/define/container_inspect.go, libpod/volume.go, pkg/domain/infra/abi/images.go, test/e2e/inspect_test.go, test/e2e/rmi_test.go, test/e2e/run_volume_test.go, version/version.go
Just sorting out the last backports for now - will push the release commit once we're satisfied there.
=> Bump to v3.0 Final

README.md, RELEASE_NOTES.md
Bump Readme and Release Notes for v3.0 release
=> [CI:DOCS] Update Master to reflect the 3.0 release

cmd/podman/containers/ps.go
change from unixnano to unix for ps created --format json
=> change ps Created to unix

cmd/podman/containers/ps.go, test/e2e/ps_test.go
=> V3unixts [3.0 Backports]

pkg/spec/spec.go
As the title says. Make CI happy again.
=> Fix lint on v1.6.4-rhel branch

pkg/api/handlers/decoder.go, pkg/bindings/util/util.go, test/apiv2/20-containers.at
=> API: fix libpod's container wait endpoint condition conversion

docs/tutorials/rootless_tutorial.md
=> [ci:docs] Update rootless_tutorial.md

cmd/podman/containers/cp.go, test/system/065-cp.bats
They shouldn't be treated specially to remain compatible with Docker.
Fixes: #9362
=> podman cp: /dev/std{in,out} fixes

libpod/image/layer_tree.go
The storage can easily be corrupted when a build or pull process (or any
process *writing* to the storage) has been killed.  The corruption
surfaces in Podman reporting that a given layer could not be found in
the layer tree.  Those errors must not be fatal but only logged, such
that the image removal may continue.  Otherwise, a user may be unable to
remove an image.
[NO TESTS NEEDED] as I do not yet have a reliable way to cause such a
storage corruption.
Reported-in: https://github.com/containers/podman/issues/8148#issuecomment-787598940
@containers/podman-maintainers
=> podman rmi: handle corrupted storage better

RELEASE_PROCESS.md
Import the release process docs from a private google-doc for accessibility and ease of maintenance.
=> [CI:DOCS]First pass at release process

test/apiv2/20-containers.at, test/apiv2/30-volumes.at, test/apiv2/35-networks.at, test/apiv2/45-system.at, test/apiv2/50-secrets.at, test/apiv2/test-apiv2
While I wasn't looking, some completely unreadable cruft
crept in here, and it's totally my fault: I never knew
you could pass JSON to a GET query. Everyone who DID
know that, did so, but had to URL-escape it into a
completely gobbledygook mess to make curl happy.
Solution: trivial, do the URL-escaping in 't' itself. I
just never realized that was needed.
I'm so sorry. I hope this helps.
=> APIv2 tests: make more maintainable

pkg/api/server/register_archive.go
=> [NO TESTS NEEDED] swagger: update the libpodPutArchive verb

cmd/podman/images/build.go
Make sure we check for errors before trying to write the iidfile.
Ref #9594
=> Fix possible panic with podman build --iidfile

pkg/domain/infra/abi/images.go
[NO TESTS NEEDED] as I have absolutely no idea how to force a reliable
reproducer.
Fixes: #9588
=> image removal: ignore unknown-layer errors

go.mod, go.sum, vendor/github.com/coreos/go-iptables/iptables/iptables.go, vendor/modules.txt
Bumps containersnetworking/plugins to v0.9.1 to address the issue in https://bugzilla.redhat.com/show_bug.cgi?id=1932399.
=> Bump  github.com/containernetworking/plugins to v0.9.1

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v3.1.0-RC1

docs/source/markdown/podman.1.md, hack/podman-socat, libpod/runtime_img_test.go, pkg/registries/registries.go, test/apiv2/rest_api/__init__.py, test/e2e/libpod_suite_remote_test.go, test/e2e/libpod_suite_test.go, test/e2e/login_logout_test.go, test/python/docker/__init__.py
Fixes: https://github.com/containers/podman/issues/9656
=> Document CONTAINERS_CONF/CONTAINERS_STORAGE_CONF Env variables

cmd/podman/containers/cp.go, libpod/container.go, libpod/container_api.go, libpod/container_copy_linux.go, libpod/container_copy_unsupported.go, libpod/container_internal.go, libpod/container_path_resolution.go, libpod/container_stat_linux.go, libpod/container_stat_unsupported.go, libpod/define/fileinfo.go, pkg/copy/fileinfo.go, pkg/domain/entities/containers.go, pkg/domain/infra/abi/archive.go, pkg/domain/infra/abi/containers_stat.go, test/e2e/cp_test.go, test/system/065-cp.bats
A number of backports to fix https://bugzilla.redhat.com/show_bug.cgi?id=1936927.
@TomSweeneyRedHat @rhatdan PTAL
=> [v3.0.1-rhel] backport `podman cp` fixes

pkg/api/server/register_networks.go
Signed-off-by: Jakub Guzik <jakubmguzik@gmail.com>
Fixes #9691
Closes #9691
Code moved to give priority to list matching.
The test will be added after merging (it depends on this fix): #9695
/hold
=> [NO TESTS NEEDED] create endpoint for querying libpod networks

.cirrus.yml, contrib/cirrus/runner.sh, contrib/cirrus/setup_environment.sh, test/buildah-bud/README.md, test/buildah-bud/buildah-tests.diff, test/buildah-bud/make-new-buildah-diffs, test/buildah-bud/run-buildah-bud-tests
Proof of concept, guaranteed to fail in CI (if it even makes it
as far as CI, which I doubt, because my .cirrus.yml changes
are a wild guess.)
Checking in just to get the conversation started.
=> run buildah bud tests using podman

libpod/container_internal_linux.go, test/e2e/run_test.go
Erik Sjolund reported an issue where a badly formated file
could be passed into the `--tz` option and then the date in the container
would be badly messed up:
```
erik@laptop:~$ echo Hello > file.txt
erik@laptop:~$ podman run --tz=../../../home/erik/file.txt --rm -ti
docker.io/library/alpine cat /etc/localtime
Hello
erik@laptop:~$ podman --version
podman version 3.0.0-rc1
erik@laptop:~$
```
This fix checks to make sure the TZ passed in is a valid
value and then proceeds with the rest of the processing.
This was first reported as a potential security issue, but it
was thought not to be.   However, I thought closing the hole
sooner rather than later would be good.
=> Validate passed in timezone from tz option

libpod/container_internal_linux.go
I have an embedded device for which the kernel was compiled without `CONFIG_USER_NS`.
Podman 2.2. was working fine with `runc` in root mode, but Podman 3.x is breaking due to a change introduced by https://github.com/containers/podman/commit/ecedda63a6488162c9aad2a99c1ada172340ac7f:
https://github.com/containers/podman/blob/ecedda63a6488162c9aad2a99c1ada172340ac7f/libpod/container_internal_linux.go#L532-L537
The root cause is that the code added above crashing at line 532 due to `/proc/self/uid_map` and `/proc/self/gid_map` not exists in the embedded kernel I'm using.
Here is an example where `runc` handles such kernel without userns support:
https://github.com/containers/podman/blob/c81e273835303664d62c4e958a7f34877c05ed49/vendor/github.com/opencontainers/runc/libcontainer/system/linux.go …
=> [NO TESTS NEEDED] Fix for kernel without CONFIG_USER_NS

pkg/api/handlers/compat/images_remove.go
Make sure fixes that go into local podman commands also work in
podman-remote, by using the same function.
Since this is just a rewrite of existing code, existing tests should
handle it.
=> [NO TESTS NEEDED] Use same function podman-remote rmi as podman

cmd/podman/images/build.go, libpod/events/logfile.go, libpod/runtime_img.go, pkg/api/handlers/compat/images_build.go, pkg/api/handlers/compat/version.go, pkg/api/handlers/types.go, pkg/api/handlers/types/types.go, pkg/bindings/images/build.go, pkg/bindings/images/images.go, pkg/bindings/images/rm.go, pkg/bindings/images/types.go, pkg/domain/entities/images.go, pkg/domain/entities/system.go, pkg/domain/entities/types.go, pkg/domain/entities/types/auth.go, pkg/domain/entities/types/types.go, pkg/domain/entities/volumes.go, pkg/domain/infra/runtime_libpod.go, pkg/namespaces/namespaces.go, pkg/rootless/rootless.go, pkg/specgen/generate/container_create.go, pkg/specgen/specgen.go, pkg/util/utils.go
=> [NO TESTS NEEDED] Shrink the size of podman bindings

cmd/podman/system/service_abi.go, pkg/rootless/rootless_linux.c
if LISTEN_FDS is specified by systemd, we need to use the first fd after the std files (so fd=3) to read from the activation socket
instead of manually opening the UNIX socket.
Closes: https://github.com/containers/podman/issues/9251
=> service: use LISTEN_FDS

contrib/spec/podman.spec.in, test/apiv2/01-basic.at, version/version.go
Bump version to reflect that we now have a v3.1 branch.
=> Bump to v3.2.0-dev

changelog.txt, contrib/spec/podman.spec.in, test/apiv2/01-basic.at, version/version.go
=> [CI:DOCS] Bump to v3.1.0

README.md, RELEASE_NOTES.md
Add release notes and bump version in README.
=> [CI:DOCS] Update main branch to reflect the release of v3.1.0

pkg/api/handlers/libpod/play.go
Signed-off-by: Kellen Dunham <kellen@oneaib.com>
=> Fix #9698 Updated reference to network

test/apiv2/35-networks.at
Adding more tests with until filter.
=> Http api tests for network prune with until filter

hack/swagger-check, pkg/api/server/register_containers.go, pkg/api/server/register_play.go, pkg/api/server/register_pods.go
Renamed 4 IDs to be consistent with other endpoints.
Fixes #9951
=> [CI:DOCS] Polish swagger OperationIDs

go.mod, go.sum, pkg/api/handlers/compat/images_build.go, pkg/bindings/images/build.go, test/buildah-bud/buildah-tests.diff, test/buildah-bud/run-buildah-bud-tests, test/e2e/build_test.go, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/Makefile, vendor/github.com/containers/buildah/chroot/run.go, vendor/github.com/containers/buildah/define/types.go, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/github.com/containers/buildah/pkg/blobcache/blobcache.go, vendor/github.com/containers/buildah/pkg/parse/parse.go, vendor/github.com/containers/buildah/run_linux.go, vendor/github.com/containers/buildah/util/util.go, vendor/modules.txt
Attempt to hijack #9896. My buildah-diffs script was a mess, and
made it impossible to produce clean diffs.
=> Handle podman-remote --arch, --platform, --os

hack/swagger-check, pkg/api/server/register_generate.go, pkg/api/server/register_healthcheck.go, pkg/api/server/register_images.go, pkg/api/server/register_manifest.go
=> [NO TESTS NEEDED] swagger: remove name wildcards

cmd/podman/images/save.go, test/e2e/save_test.go
Fixes: https://github.com/containers/podman/issues/10024
=> Fix invalid expression in save command

pkg/bindings/test/networks_test.go, pkg/bindings/test/volumes_test.go
Missing tests: network remove and list interactions.
=> Add network bindings tests: remove and list

RELEASE_NOTES.md, changelog.txt, contrib/spec/podman.spec.in, docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-import.1.md, docs/source/markdown/podman-run.1.md, libpod/image/image.go, libpod/runtime_img.go, pkg/api/handlers/libpod/images.go, pkg/domain/infra/abi/images.go, pkg/specgen/generate/storage.go, test/e2e/play_kube_test.go, test/e2e/save_test.go, test/system/330-corrupt-images.bats, version/version.go
@vrothberg found a fairly serious issue in the containers/image version we shipping in v3.1.1, so we're releasing a quick bump with that and some other small fixes.
=> Bump to v3.1.2

pkg/api/handlers/compat/containers.go
It is possible that a container is removed between fetching the initial list of containers and the second access during conversion. In that case it can just be dropped from the returned list.
A similar issue was previously fixed with 3fbc2c5cd21a344819a0636f08487cee805dd8d9
We might want to change from preallocating the slice of containers to just appending because adding an offset makes the code less readable.
I tried to add a test to `pkg/bindings/test/containers_test.go`, but creating and deleting containers in parallel caused unrelated errors. The test I provided in #10120  passes with this fix.
Closes #10120
=> Fix removal race condition in ListContainers

docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-run.1.md
* Add missing backticks to mark the end
of the code block.
=> [CI:DOCS] Fix Markdown layout bugs

docs/source/markdown/podman-container-cleanup.1.md, docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-generate-systemd.1.md, docs/source/markdown/podman-run.1.md, docs/source/markdown/podman.1.md
=> [CI:DOCS] Add more documentation on conmon

pkg/domain/entities/volumes.go
[NO TESTS NEEDED] since we are just removing unused code.
Replaces: https://github.com/containers/podman/pull/9558
=> Remove unused VolumeList* structs

troubleshooting.md
Fixes: https://github.com/containers/podman/issues/10166
=> [CI:DOCS] Fix troubleshooting documentation on handling supplemental groups.

cmd/podman/common/create_opts.go, test/compose/ipam_set_ip/docker-compose.yml, test/compose/ipam_set_ip/tests.sh
Fixes: https://github.com/containers/podman/issues/10245
FIXes: https://github.com/containers/podman/issues/10240
=> Fixes docker-compose cannot set static ip when use ipam

pkg/channel/writer.go
do not use recover() to prevent writing to a closed channel.  There is
already a lock, use it as well for Close and let Write check if the
channel is still active.
=> channel: simplify implementation

hack/bats
Well, new to you. It's been something I've used for years.
Simple, but it takes care of a lot of housekeeping, and
makes it ever-so-much-more pleasant to invoke bats tests.
And when it's easier to run tests, tests get run.
=> [CI:DOCS] hack/bats - new helper for running system tests

test/upgrade/test-upgrade.bats
Fix many FIXMEs in the upgrade tests. Also add a basic test for pods.
=> fix system upgrade tests

changelog.txt, version/version.go
=> [CI:DOCS] Bump to v3.2.0-RC2

pkg/bindings/images/build.go, test/system/070-build.bats
Fixes: https://github.com/containers/podman/issues/10444
=> Handle hard links in different directories

libpod/runtime.go
Fix a data race between creating and using the libimage-events channel.
[NO TESTS NEEDED] since it really depends on the scheduler and we
couldn't hit the race so far.
Fixes: #10459
=> libimage-events channel: fix data race

transfer.md
=> [CI:DOCS] Update a way out of date transfer document

pkg/api/handlers/compat/images.go
This fixes a goroutine leak.
Previously if a request was cancelled the image pulling goroutine kept running regardless.
Signed-off-by: Matej Vasek <mvasek@redhat.com>
=> Use request context instead of background context

pkg/api/handlers/compat/images.go
If server cannot resolve short name due to enforcing policy send
non-2xx status code.
Signed-off-by: Matej Vasek <mvasek@redhat.com>
=> Better error handing for images/create compat api

rootless.md
After all, maybe using numbers in the FAQ is not such a good idea for having persistent links… :wink:
=> [CI:DOCS] Fix link error

docs/source/machine.rst
=> [CI:DOCS] Fix spacing in buildthedocs

README.md, RELEASE_NOTES.md
=> [CI:DOCS] Update main branch to reflect 3.2.0 release

test/system/255-auto-update.bats
Add some tests for podman auto-update and also fix one bug in basic_setup().
=> System test: Add tests for podman auto-update

contrib/spec/podman.spec.in, version/version.go
@baude @mheon @vrothberg @rhatdan PTAL.
=> Version bump: 3.3.0-dev

pkg/api/handlers/compat/images_build.go, test/e2e/build_test.go
Fixes: https://github.com/containers/podman/issues/10614
=> Fix handling of podman-remote build --device

pkg/bindings/images/build.go, test/system/070-build.bats
Fixes: https://github.com/containers/podman/issues/10621
=> Add support for podman remote build -f - .

pkg/cgroups/cgroups.go
Fixes: https://github.com/containers/podman/issues/10666
=> [NO TESTS NEEDED] Fixes panic condition in cgroups.getAvailableControllers

go.mod, go.sum, vendor/github.com/coreos/go-iptables/iptables/iptables.go, vendor/modules.txt
Addresses https://bugzilla.redhat.com/show_bug.cgi?id=1942753 for RHEL 8.4
=> Bump github.com/containernetworking/plugins to v0.9.1 v3.0.1-rhel

docs/MANPAGE_SYNTAX.md, docs/source/markdown/podman-container-prune.1.md, docs/source/markdown/podman-container-restore.1.md
See [PR 10676](https://github.com/containers/podman/pull/10676).
=> [CI:DOCS] Follow-up to PR 10676

OWNERS
With great power comes great `/lgtm`.
=> [CI:DOCS] add @mtrmac to OWNERS

docs/source/markdown/podman-save.1.md
Mention all supports --format values and put them into the context of
supported transports.
=> [CI:DOCS] podman save: clarify formats and transports

README.md, changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v3.2.2

go.mod, go.sum, vendor/github.com/containers/common/libimage/image.go, vendor/github.com/containers/common/libimage/load.go, vendor/github.com/containers/common/libimage/manifest_list.go, vendor/github.com/containers/common/libimage/pull.go, vendor/github.com/containers/common/libimage/push.go, vendor/github.com/containers/common/libimage/save.go, vendor/github.com/containers/common/pkg/sysinfo/numcpu_linux.go, vendor/github.com/containers/common/pkg/sysinfo/nummem_linux.go, vendor/github.com/containers/common/pkg/sysinfo/nummem_unsupported.go, vendor/modules.txt
Make sure that image events are written *after* execution.
Fixes: #10812
=> vendor containers/common@7482cf851dcc

go.mod, go.sum, vendor/github.com/containers/common/libimage/image.go, vendor/github.com/containers/common/libimage/load.go, vendor/github.com/containers/common/libimage/manifest_list.go, vendor/github.com/containers/common/libimage/pull.go, vendor/github.com/containers/common/libimage/push.go, vendor/github.com/containers/common/libimage/save.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
* libimage: events: deferred write
Fixes: bugzilla.redhat.com/show_bug.cgi?id=1977673
=> [3.2] vendor containers/common@v0.38.13

cmd/podman/images/pull.go, docs/source/markdown/podman-pull.1.md, test/e2e/pull_test.go
Closes #10726 
Adds support for pulling multiple images sequentially. 
Signed-off-by: Mehul Arora <aroram18@mcmaster.ca>
=> support pulling multiple images sequentially in a single podman pull 

.cirrus.yml, contrib/cirrus/lib.sh
Mainly this is a fix for https://cirrus-ci.com/task/5528097173798912?logs=setup#L1
=> [CI:DOCS] Cirrus: Branch maintenance

docs/tutorials/basic_networking.md
=> [CI:DOCS] Correct a typo in documentation

go.mod, go.sum, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/chroot/run.go, vendor/github.com/containers/buildah/define/types.go, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/modules.txt
=> [3.2] vendor containers/buildah@v1.21.3

go.mod, go.sum, vendor/github.com/containers/common/libimage/pull.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> [v3.2] vendor containers/common@v0.38.16

go.mod, go.sum, vendor/github.com/containers/common/libimage/image_tree.go, vendor/github.com/containers/common/libimage/pull.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> vendor containers/common@main

RELEASE_NOTES.md
=> [CI:DOCS] Release notes for v3.2.3

README.md, changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v3.2.3

README.md, RELEASE_NOTES.md
=> [CI:DOCS] Update Release Notes and README for 3.2.3

pkg/specgen/generate/kube/kube.go, test/e2e/play_kube_test.go
Liveness probes are backed by native podman/systemd healthchecks instead of kubelet and supports all the available handlers supported by kubernetes.
Example spec
```yaml
spec:
restartPolicy: Always
containers:
- name: nginx
image: nginx:1.14.2
ports:
- containerPort: 80
livenessProbe:
exec:
command:
- echo
- hello
initialDelaySeconds: 5
periodSeconds: 5
```
=> Kube: Add liveness probe for containers backed by native (systemd) healthchecks instead of kubelet.

troubleshooting.md
=> [CI:DOCS] Fix broken remote client link

test/system/271-tcp-cors-server.bats
closes #8645 and related to #10546
//cc @rhatdan @edsantiago
=> Add tests to verify CORs is enabled

pkg/rootless/rootless_linux.go
if the root mount '/' is not mounted as MS_SHARED, print a
warning, otherwise new mounts that are created in the host won't be
propagated to the rootless mount namespace.
Closes: https://github.com/containers/podman/issues/10946
=> rootless: check that / is mounted as shared

docs/source/markdown/podman-cp.1.md
Removed personal pronouns like "you" and added relevant links.
Signed-off-by: Mehul Arora <aroram18@mcmaster.ca>
=> [CI:DOCS] Update podman-cp manpage

test/system/050-stop.bats
In the unlock/timeout test, on slow systems, 'podman ps' could
catch the container before the just-backgrounded 'podman stop'
sends the signal. Wait for signal ack from container before
we inspect it.
Also: If I understand the test correctly, it wasn't actually
checking that 'ps' could grab the lock while the container
was exiting. Add a check.
=> system tests: fix race in stop test

.github/workflows/multi-arch-build.yaml
This mirrors changes from
https://github.com/containers/buildah/pull/3381
=> [CI:DOCS] Multi-arch image build: Daily version-tag push

test/e2e/run_cgroup_parent_test.go
move the container to a sub-cgroup before creating a sibling hierarchy.
=> test: move container process to a sub-cgroup

.cirrus.yml
=> Cirrus: CI Support for v3.3 Branch

pkg/api/handlers/compat/containers.go, test/apiv2/python/rest_api/test_v2_0_0_container.py
Fixes:
- Do not show healthcheck status if not available or if container status is "created" (Docker behaviour)
- Show healthcheck configuration if present (Config.Healthcheck)
Tests:
- Ensure State.Health is not present if container status is "created"
- Ensure Config.Healthcheck is present and values correct
- Ensure State.Health is present if container started
Signed-off-by: Milivoje Legenovic <m.legenovic@gmail.com>
=> Compat API: Fix healthcheck status and healthcheck config

pkg/api/handlers/libpod/containers_stats.go, pkg/api/server/register_containers.go, test/apiv2/20-containers.at
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1988252
=> Only support containers stats using cgroups v2

docs/source/markdown/podman-network-connect.1.md, docs/source/markdown/podman-network-disconnect.1.md, docs/source/markdown/podman-network-reload.1.md, go.mod, go.sum, libpod/networking_linux.go, libpod/networking_slirp4netns.go, pkg/rootlessport/rootlessport_linux.go, test/system/500-networking.bats, vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/parent.go, vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/tcp/tcp.go, vendor/github.com/rootless-containers/rootlesskit/pkg/port/builtin/parent/udp/udp.go, vendor/modules.txt
Backport https://github.com/containers/podman/pull/11091 and https://github.com/containers/podman/pull/11125
=> [v3.3] fix rootless port forwarding with network dis-/connect

RELEASE_NOTES.md, changelog.txt, version/version.go
=> [CI:DOCS] Bump to v3.3.0-RC3

libpod/runtime.go, pkg/api/handlers/compat/version.go, test/apiv2/python/rest_api/test_v2_0_0_system.py
* Include OCI and conmon information as components
Fixes #11227
=> Update /version endpoint to add components

changelog.txt, contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v3.3.0

README.md, RELEASE_NOTES.md
Also add release notes for v3.3.0
=> Update README for 3.3.0 release

test/e2e/common_test.go
Fixes: https://github.com/containers/podman/issues/11201
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
=> e2e tests: fix overlay: Unknown option vfs.imagestore

.cirrus.yml
Add a new reference point against which to test upgrades.
And, remove some FIXME comments, thanks to @cevich for
clarifying those questions (offline, some months ago).
=> Upgrade test: add new baseline

go.mod, go.sum, vendor/github.com/vbauerster/mpb/v7/bar.go, vendor/modules.txt
```
go mod edit -replace github.com/vbauerster/mpb/v7=github.com/mtrmac/mpb/v7@abort-deadlock
make vendor
```
See https://github.com/vbauerster/mpb/issues/100 and https://github.com/vbauerster/mpb/pull/101 .
=> Use UNMERGED vbauerster/mpb PR to fix a pull deadlock

README.md, RELEASE_NOTES.md
Signed-off-by: jesperpedersen <jesper.pedersen@redhat.com>
=> Bump release to 3.3.1

docs/tutorials/podman_tutorial.md
=> [CI:DOCS] Example says there is not IP then in the next command suggests to use it

test/system/150-login.bats, test/system/200-pod.bats, test/system/271-tcp-cors-server.bats, test/system/500-networking.bats, test/system/helpers.bash, test/system/helpers.t
Picks a pseudorandom open port within a range. Refactor existing
instances of such code.
=> system tests: new random_free_port helper

docs/source/markdown/podman-info.1.md, libpod/define/info.go, libpod/info.go, test/system/005-info.bats
=> Add logDriver to podman info

test/upgrade/helpers.bash, test/upgrade/test-upgrade.bats
Test basic networking functionality in the upgrade tests.
=> podman upgrade tests for networking

libpod/container_internal_linux.go, test/e2e/run_cgroup_parent_test.go
=> test: enable --cgroup-parent test

.cirrus.yml
Ref: https://github.com/containers/automation_images/pull/88
Closes #11123
=> Cirrus: NM/CNI workaround + Remove prior-Ubuntu

go.mod, go.sum, test/e2e/search_test.go, vendor/github.com/containers/common/libimage/disk_usage.go, vendor/github.com/containers/common/libimage/image.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/pkg/config/default_linux.go, vendor/github.com/containers/common/pkg/config/default_unsupported.go, vendor/github.com/containers/common/pkg/config/util_supported.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> [v3.3] Bump c/common to v0.42.2

docs/source/markdown/podman-machine-init.1.md
=> [CI:DOCS] Fix example in podman machine init man page

cmd/podman/root.go, contrib/tmpfile/podman.conf, docs/source/markdown/podman-info.1.md, go.mod, go.sum, libpod/define/info.go, libpod/info.go, test/e2e/containers_conf_test.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Fixes: https://github.com/containers/podman/issues/11107
=> Set default storage from containers.conf for temporary images

contrib/spec/podman.spec.in, version/version.go
=> [CI:DOCS] Bump to v3.4.0-RC1

go.mod, go.sum, pkg/autoupdate/autoupdate.go, vendor/github.com/containers/common/libimage/image.go, vendor/github.com/containers/common/libimage/pull.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/mitchellh/mapstructure/CHANGELOG.md, vendor/github.com/mitchellh/mapstructure/decode_hooks.go, vendor/github.com/mitchellh/mapstructure/mapstructure.go, vendor/modules.txt
Finalizes the linked BZ to fix passing down custom authfiles during auto
updates.  Also fixes the if-newer pull policy.
BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
=> vendor c/common@main

.cirrus.yml, go.mod, go.sum, pkg/autoupdate/autoupdate.go, vendor/github.com/containers/common/libimage/disk_usage.go, vendor/github.com/containers/common/libimage/image.go, vendor/github.com/containers/common/libimage/pull.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/pkg/config/default_linux.go, vendor/github.com/containers/common/pkg/config/default_unsupported.go, vendor/github.com/containers/common/pkg/config/util_supported.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Vendor containers/common@v0.42.3 to pull in fixes for setting custom
authfiles during auto updates.
[NO TESTS NEEDED] must be tested manually.  The main branch will receive
a new system test shortly.
BZ: bugzilla.redhat.com/show_bug.cgi?id=2000943
@rhatdan @TomSweeneyRedHat PTAL
=> [3.3] auto update: fix custom authfiles

cmd/podman/images/inspect.go, cmd/podman/networks/inspect.go, docs/source/markdown/links/podman-container-inspect.1, docs/source/markdown/links/podman-image-inspect.1, docs/source/markdown/podman-container-inspect.1.md, docs/source/markdown/podman-container.1.md, docs/source/markdown/podman-image-inspect.1.md, docs/source/markdown/podman-image.1.md, docs/source/markdown/podman-inspect.1.md, docs/source/markdown/podman-pod-inspect.1.md, docs/source/markdown/podman-volume-inspect.1.md
[NO TESTS NEEDED] since this is really a docs change.
Concludes: https://github.com/containers/podman/pull/11620
=> Add podman image/container inspect man pages

libpod/container_internal_linux.go, test/e2e/run_volume_test.go
Following PR allows containers to create and mount overlays on top of
named volumes instead of mounting actual volumes via already documented `:O`.
Closes: https://github.com/containers/podman/issues/11640
=> volume: Add support for overlay on named volumes

docs/source/markdown/podman-build.1.md
Update the descriptions of the --arch, --os, --variant, and --platform options, since the last of those hasn't been a no-op for some time, and it was recently extended to accept multiple values.
=> [CI:DOCS] update docs for --platform in podman-build.1

cmd/podman/images/prune.go, cmd/podman/system/prune.go
Google docs found this while writing Podman in Action book.
=> Fix english on prune prompt

cmd/podman/machine/init.go, go.mod, go.sum, test/system/120-load.bats, vendor/github.com/containers/common/libimage/load.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
Fixes: https://github.com/containers/podman/issues/11745
[NO TESTS NEEDED] Since this is just a revendor and a one line
change for the revendor
=> Vendor in containers/common v0.46.0

cmd/podman/machine/init.go, go.mod, go.sum, vendor/github.com/containers/buildah/.cirrus.yml, vendor/github.com/containers/buildah/CHANGELOG.md, vendor/github.com/containers/buildah/changelog.txt, vendor/github.com/containers/buildah/define/types.go, vendor/github.com/containers/buildah/go.mod, vendor/github.com/containers/buildah/go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> [3.4] Vendor common v0.44.2 and buildah v1.23.1

pkg/machine/qemu/machine.go
Try to cleanup dandling pid and machine socket if possible silently
before `rm`.
Closes: https://github.com/containers/podman/issues/11393
=> machine: silently cleanup dangling sockets before `rm` if possible

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
This fixes a bug where podman machine could create a broken config file.
run `podman machine init` and check the the machine section in containers.conf is still empty
Fixes #11824
=> [v3.4] bump c/common to v0.44.3

contrib/podmanimage/upstream/Dockerfile
Fixes #11380
Replaces https://github.com/containers/podman/pull/11385
Originally subbmitted by @mattymo
=> Add podman-plugins to upstream image

libpod/container_api.go, libpod/container_internal.go
=> Backports for v3.0.1-rhel

docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-run.1.md
Fixes: https://github.com/containers/podman/issues/12008
=> [CI:DOCS] Add information on how to discover default log driver

docs/source/markdown/podman-build.1.md, docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-pull.1.md, docs/source/markdown/podman-run.1.md
=> [ci:docs] Add links to podman build see also

README.md
[NO NEW TEST NEEDED]
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> [ci:docs] Add Static Build download instructions to README

.cirrus.yml
Necessary to make Cirrus happy.
=> [NO NEW TESTS NEEDED] Fix destination branch for v3.4.2-rhel

pkg/rootless/rootless_linux.c
simplify code using auto cleanup functions
[NO NEW TESTS NEEDED] it is a refactoring of existing code
=> rootless: use auto cleanup functions

docs/tutorials/podman_tutorial_cn.md
it is a simplified chinese translation editon for the podman_tutorial.md
None
None
None
=> [CI:DOCS] upload a translation file

contrib/fedora-minimal/Dockerfile, contrib/fedora-minimal/README.md, test/e2e/config.go, test/e2e/images_test.go, test/e2e/run_test.go, test/system/500-networking.bats, utils/utils.go, utils/utils_supported.go
Backport #12323 and #12297 [EDIT: and #12343] to fix bodhi gating-test failures
=> [v3.4] backport Flake fixes

docs/source/markdown/podman-run.1.md
Follow up from https://github.com/containers/podman/pull/12373/files.
=> [CI:DOCS] Update notes on java TZ in man page

.cirrus.yml, RELEASE_PROCESS.md
Unfortunately the maintainer of this is no longer available
CI wIll pass
None
None
=> [CI:DOCS] Cirrus: Strip out static nix build

docs/tutorials/basic_networking.md
Correct a missing link in basic networking tutorial.
To correct a missing link in docs/tutorials/basic_networking.md.
Just change docs. No need to verify.
None
=> [CI:DOCS] Update basic_networking.md

libpod/oci_conmon_linux.go
failed to send a signal to the container's PID1, but ignored the results of that update. That's generally bad practice, since even
if we can't directly take action on an error, we should still make an effort to report it for debugging purposes. I used Infof instead of something more serious to avoid duplicate reporting to the user if something has gone seriously wrong.
[NO TESTS NEEDED] this is just adding additional error reporting.
=> Warn on failing to update container status

OWNERS
=> [CI:DOCS] Add ashley-cui, lsm5 and floutoc to owners

docs/tutorials/remote_client.md
Looks like many people stumble upon this issue https://github.com/containers/podman/issues/8323 (so do I), maybe it worth to mention it in the doc the ssh key pair is ed25519.
Fixes [#8323](https://github.com/containers/podman/issues/8323 )
=> [CI:DOCS] Update doc to explictly mention using ed25519 in ssh keys

pkg/api/handlers/compat/images_push.go
We don't yet have a local registry running in the APIv2 tests.
Tested manually.
Fixes: https://github.com/containers/podman/issues/12468
@rhatdan PTAL
=> compat API: push: report size of manifest

docs/source/markdown/podman-save.1.md
Improve documentation of `podman image save`, partially motivated by https://github.com/containers/common/pull/820 .
N/A
None
=> Improve documentation of (podman image save)

libpod/container.go, libpod/container_internal_linux.go, pkg/specgen/generate/container_create.go, pkg/specgen/specgen.go, pkg/specgenutil/specgen.go, test/e2e/run_test.go, test/system/035-logs.bats, test/system/130-kill.bats
Backport #12294 and #12118 to v3.4.2-rhel
=> Backports for v3.4.2-rhel

README.md, contrib/cirrus/runner.sh
Simply a readme update and dead-code cleanup.
Manual review required.
None
None
=> [CI:DOCS] Cirrus: Remove remnants of nix-based static build

docs/tutorials/mac_win_client.md
Updates the Windows install doc to make it more clear.
Fixes: #11382
=> [CI:DOCS] Update Windows Install Doc

libpod/runtime_img.go, test/system/010-images.bats
Force removal of images will also remove associated containers.
Historically, infra containers have been excluded resulting in
rather annoying errors, for instance, when running `rmi -af`.
Since there is not reasons to exclude infra containers, allow for
removing the entire pod when an infra image is force removed.
@containers/podman-maintainers 
I will tackle the ~same issue for `container rm` in another PR.
=> image rm: allow for force-remove infra images

contrib/cirrus/setup_environment.sh
force a version with this fix: https://github.com/containers/crun/pull/819
=> ci: force scratch build for crun

libpod/network/internal/util/util.go
Signed-off-by: ye.sijun <junnplus@gmail.com>
=> [CI:DOCS] fix doc typo

pkg/api/server/docs.go
=> Update swagger documentation

libpod/healthcheck_linux.go
Prodding bz #2024229 a little more, it turns out the service file is NOT
deleted when it is in a failed state (i.e the healtch check has failed
for some reason).  The state must be reset before the service is stopped
on container removal and then the files will be removed properly.
BZ#:2024229
=> .service file removal on failure

test/e2e/pod_initcontainers_test.go, test/e2e/run_test.go
See individual commits for details.
=> Fix test flake in test/e2e/pod_initcontainers

test/system/180-blkio.bats, test/system/helpers.bash
Fixes: https://github.com/containers/podman/issues/12740
=> Change Tests to ignore missing containers when removing --all

pkg/api/server/register_networks.go, pkg/api/server/register_volumes.go
"for creating a container" appears for networks and volumes
Signed-off-by: David Marshall <dmarshall@gmail.com>
=> [CI:DOCS] correct typo words in docs

docker
Check for any existing system object in docker script to clear warning message (Resolving PR comments)
Signed-off-by: Stephen Person <stephen.person.12@cnu.edu>
Replaces https://github.com/containers/podman/pull/12478
=> Update docker cli message for case where user creates directory

test/system/035-logs.bats
Add a fix for RHEL8 gating tests. This resolves yet another
journald/file events/logger mismatch bug.
=> [v3.4] System tests: fix RHEL8 gating tests

cmd/podman/machine/list.go, docs/source/markdown/podman-machine-list.1.md, pkg/machine/config.go, pkg/machine/qemu/machine.go
=> add additional fields to podman machine ls --json

cmd/podman/root.go, docs/source/markdown/podman.1.md, pkg/domain/entities/engine.go, test/system/030-run.bats, test/system/050-stop.bats, test/system/080-pause.bats, test/system/200-pod.bats, test/system/500-networking.bats
Fixes: https://github.com/containers/podman/issues/11515
=> Add --noout option to prevent the output of ids

libpod/options.go, libpod/runtime.go, test/system/090-events.bats
=> use events_logfile_path from containers.conf for events log.

.github/ISSUE_TEMPLATE.md
Update links in issue template to point to main branch
Signed-off-by: fredr <fredrik@enestad.com>
=> [CI:DOCS] troubleshooting links to main branch

test/system/030-run.bats
This test case is used for covering rhbz#1902979.
Signed-off-by: Alex Jia <ajia@redhat.com>
Replaces https://github.com/containers/podman/pull/12219
=> test/system: podman run update /etc/hosts

docs/source/markdown/podman-run.1.md
=> [CI:DOCS] Fix typo in --env

pkg/machine/ignition.go
This PR changes the SSL certificates copying mechanism to also include certificates in subdirectories.
I couldn't compile it on (and for) Mac, but I've verified the change works from logs by running `bin/podman machine init --log-level=debug` on Ubuntu.
Closes: #12799
=> ignition: recursively copy cert files

rootless.md
=> [CI:DOCS] Unprivileged native overlayfs is now supported

go.mod, go.sum, vendor/github.com/containers/common/libnetwork/network/interface.go, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/modules.txt
This contains changes that are needed to enable netavark e2e testing.
=> update c/common to latest

SECURITY.md
=> [CI:DOCS] SECURITY.md: fix the project name

pkg/api/handlers/compat/images.go, test/apiv2/20-containers.at
Fixes: https://github.com/containers/podman/issues/12830
=> Handle changes in docker compat mode

RELEASE_NOTES.md
Our largest release so far by a significant margin, in terms of release notes (I think 2.0 probably has us beat in terms of diffstat, but I haven't verified that).
=> [CI:DOCS] Update release notes for Podman v4.0.0

RELEASE_NOTES.md, version/version.go
=> Bump to v4.0.0-RC2

Makefile, docs/source/markdown/podman-machine-list.1.md, libpod/container_inspect.go, pkg/auth/auth_test.go, pkg/bindings/test/containers_test.go, pkg/machine/wsl/machine.go, pkg/specgen/podspecgen.go, pkg/specgen/specgen.go, pkg/specgenutil/specgen.go, test/e2e/play_build_test.go, test/e2e/volume_create_test.go, test/system/160-volumes.bats, troubleshooting.md
=> Run codespell

docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-run.1.md
=> [CI:DOCS] fix typo subpordinate

docs/source/markdown/podman-attach.1.md, docs/source/markdown/podman-build.1.md, docs/source/markdown/podman-container-exists.1.md, docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-generate-kube.1.md, docs/source/markdown/podman-image-sign.1.md, docs/source/markdown/podman-logs.1.md, docs/source/markdown/podman-machine-list.1.md, docs/source/markdown/podman-manifest-push.1.md, docs/source/markdown/podman-mount.1.md, docs/source/markdown/podman-network-create.1.md, docs/source/markdown/podman-network-exists.1.md, docs/source/markdown/podman-play-kube.1.md, docs/source/markdown/podman-pod-logs.1.md, docs/source/markdown/podman-pull.1.md, docs/source/markdown/podman-run.1.md, docs/source/markdown/podman-untag.1.md, docs/source/markdown/podman-volume-exists.1.md, docs/source/markdown/podman.1.md
Suggestions to improve the PR are welcome. (I'm not a native English speaker)
=> [CI:DOCS] Fix typos and improve language

docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-pod-create.1.md
Add a few fixes (3 changes) that were unintentionally left out from 
8099a61b648a1cfc862461487f1db9ecd47d065e
earlier today. The changes are of the same type as before.
=> [CI:DOCS] Fix typos and improve language (add 3 missing)

docs/source/markdown/podman-container-prune.1.md, docs/source/markdown/podman-image-prune.1.md, docs/source/markdown/podman-network-prune.1.md, docs/source/markdown/podman-system-prune.1.md, docs/source/markdown/podman-volume-prune.1.md
=> CI:DOCS: Unify podman prune filter description: volumes, networks, system

troubleshooting.md
=> CI:DOCS: Add troublshooting info on podman machine remove followed by podman machine init

.cirrus.yml
Necessary to get CI working on the new v4.0 branch
=> Fix Cirrus destination branch

RELEASE_NOTES.md, version/version.go
=> [CI:DOCS] Bump to v4.0.0-RC3

pkg/specgenutil/specgen.go, test/e2e/containers_conf_test.go, vendor/github.com/docker/docker/opts/address_pools.go, vendor/github.com/docker/docker/opts/env.go, vendor/github.com/docker/docker/opts/hosts.go, vendor/github.com/docker/docker/opts/hosts_unix.go, vendor/github.com/docker/docker/opts/hosts_windows.go, vendor/github.com/docker/docker/opts/ip.go, vendor/github.com/docker/docker/opts/opts.go, vendor/github.com/docker/docker/opts/quotedstring.go, vendor/github.com/docker/docker/opts/runtime.go, vendor/github.com/docker/docker/opts/ulimit.go, vendor/github.com/docker/libnetwork/ipamutils/utils.go, vendor/modules.txt
Fixes: https://github.com/containers/podman/issues/13096
=> Fix size to match Docker selection

contrib/helloimage/Containerfile, contrib/helloimage/README.md, contrib/helloimage/podman_hello_world.bash
This commit describes how to run the quay.io/podman/hello
image.  It also contains the files necessary to build that
image localy, and a README.md explaining the image and how
to build it.
=> [CI:DOCS] Add a hello world image to quay.io

docs/source/markdown/podman-stats.1.md
follow-up for https://github.com/containers/podman/pull/13101
[CI:DOCS]
=> [CI:DOCS] docs: clarify rootless net stats

cmd/podman/common/netflags.go, pkg/resolvconf/resolvconf.go, test/system/500-networking.bats
Fixes: https://github.com/containers/podman/issues/13065
=> Only change network fields if they were actually changed by the user

hack/bats
=> hack/bats: fix broken usage message

Makefile, cmd/podman/networks/list.go, test/e2e/common_test.go, test/e2e/create_staticip_test.go, test/e2e/create_staticmac_test.go, test/e2e/create_test.go, test/e2e/libpod_suite_remote_test.go, test/e2e/login_logout_test.go, test/e2e/network_connect_disconnect_test.go, test/e2e/network_create_test.go, test/e2e/network_test.go, test/e2e/play_kube_test.go, test/e2e/pod_create_test.go, test/e2e/pod_ps_test.go, test/e2e/ps_test.go, test/e2e/run_networking_test.go, test/e2e/run_staticip_test.go, test/e2e/search_test.go, test/utils/utils.go
enable the e2e tests to run with netavark
=> Enable e2e tests with netavark

pkg/specgen/generate/kube/kube.go, pkg/specgen/generate/kube/play_test.go
add support for env vars values from container resources
see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#envvarsource-v1-core
relates to issue https://github.com/containers/podman/issues/12756
relates to bug https://github.com/containers/podman/issues/13115
Signed-off-by: Yaron Dayagi <ydayagi@redhat.com>
=> play kube envVar.valueFrom.resourceFieldRef

.cirrus.yml, contrib/cirrus/lib.sh, contrib/cirrus/logcollector.sh, contrib/cirrus/setup_environment.sh, test/system/005-info.bats, test/system/500-networking.bats, test/system/README.md, test/system/helpers.bash
=> Cirrus: Add netavark/aardvark system test task

libpod/container_internal_linux.go, test/system/500-networking.bats
Append the podman dns seach domain to the host search domains when we
use the dnsname/aardvark server. Previously it would only use podman
seach domains and discard the host domains.
Fixes #13103
=> append podman dns search domain

libpod/container_log_linux.go
foramtError was written as err
Signed-off-by: myml <wurongjie1@gmail.com>
=> Fix: Do not print error when parsing journald log fails

pkg/api/server/register_images.go
Attempt at fixing https://github.com/containers/podman/issues/12927.
@jwhonce ptal.
=> [CI:DOCS] Add schema for ImageCreate 200 response.

go.mod, go.sum, vendor/github.com/containers/common/libimage/copier.go, vendor/github.com/containers/common/libimage/manifests/manifests.go, vendor/github.com/containers/common/libnetwork/cni/cni_conversion.go, vendor/github.com/containers/common/libnetwork/cni/config.go, vendor/github.com/containers/common/libnetwork/internal/util/validate.go, vendor/github.com/containers/common/libnetwork/netavark/config.go, vendor/github.com/containers/common/libnetwork/netavark/network.go, vendor/github.com/containers/common/pkg/auth/auth.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
=> Bump c/common to v0.47.4

pkg/api/server/register_networks.go
When attempting to create a network with a name that already exists,
a 409 status code will be returned
=> Add 409 response to swagger godoc

test/e2e/common_test.go, test/e2e/network_create_test.go, test/e2e/network_test.go, test/e2e/run_networking_test.go
=> enable netavark specific tests

cmd/podman/common/create.go
Signed-off-by: Morten Linderud <morten@linderud.pw>
=> create: Fix key=value annotation in the flag output

docs/source/markdown/podman-network-ls.1.md, docs/source/markdown/podman-pod-ps.1.md
Signed-off-by: Patrycja Guzik <patrycja.k.guzik@gmail.com>
#13078 follow-up
=> [CI:DOCS] Unify ls --filter docs for networks and pods

contrib/podmanimage/stable/Dockerfile, contrib/podmanimage/testing/Dockerfile, contrib/podmanimage/upstream/Dockerfile
increase the number of ids available to the podman user inside the container image when running as rootless.
=> increase subuid and subgid in image

docs/tutorials/basic_networking.md
With netavark being the default networking implementation for Podman v4,
the tutorial needed some updating.
[NO NEW TESTS]
=> [CI:DOCS]Update networking tutorial for netavark

contrib/cirrus/logformatter, contrib/cirrus/logformatter.t, test/e2e/images_test.go, test/python/docker/compat/test_images.py
=> [V3.4.2-rhel] Fix AssertionError: 'alpine' not found in 'docker.io/docker/desktop-kubernetes'

contrib/cirrus/logformatter, contrib/cirrus/logformatter.t, test/e2e/images_test.go, test/python/docker/compat/test_images.py
=> [V3.3.1-rhel] Fix AssertionError: 'alpine' not found in 'docker.io/docker/desktop-kubernetes'

Makefile, contrib/cirrus/runner.sh, contrib/cirrus/setup_environment.sh, test/apiv2/12-imagesMore.at, test/apiv2/python/conftest.py, test/apiv2/python/requirements.txt, test/apiv2/test-apiv2
* Add configuration to add report header for python client used in tests
=> Move all python tests to pytest

pkg/machine/qemu/machine.go
=> `podman machine rm` removes the mounted socket file on macOS

RELEASE_PROCESS.md
Follow up to pr#13416
Insert line break to get rid of the horizontal scroll bar.
Resolves: https://github.com/containers/podman/pull/13416#discussion_r818991807
@rhatdan @ashley-cui @mheon @cevich PTAL
=> [CI:DOCS] RELEASE_PROCESS.md: cosmetic fix

DISTRO_PACKAGE.md
=> [CI:DOCS] DISTRO_PACKAGE.md: List the packaging changes for v4

troubleshooting.md
=> [CI:DOCS] troubleshooting.md: Improve language and fix typos

Makefile
Go 1.17 compiler got faster
Signed-off-by: Pascal Bourdier <pascal.bourdier@gmail.com>
=> Bump golang to 1.17

test/e2e/common_test.go, test/e2e/run_aardvark_test.go
=> test/e2e: add aardvark specific tests

Makefile
Resolves: #13557
@Luap99 @afbjorklund @mheon @rhatdan PTAL
=> Makefile: build podman-remote-static with cgo disabled

troubleshooting.md
Closes: https://github.com/containers/podman/issues/13003
=> [CI:DOCS] troubleshooting: document rm in image stores

docs/source/markdown/podman-unshare.1.md
=> [CI:DOCS] podman unshare: document that command cannot be used with remote

pkg/api/handlers/compat/networks.go, pkg/api/server/register_exec.go, pkg/api/server/register_networks.go, pkg/api/server/swagger.go, pkg/domain/entities/types.go
Improve swagger and handler code compatibility.
Fixes #12804
=> Update swagger to improve compatibility

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
Resolves: CVE-2022-21698
While dependabot should fix this at some point, the module in question has been released for over a month but there hasn't been an update yet, that's why the manual PR.
@vrothberg @Luap99 @mheon @rhatdan PTAL
=> Bump github.com/prometheus/client_golang to v1.11.1

docs/source/markdown/podman-create.1.md, docs/source/markdown/podman-run.1.md
it was released more than two years ago.
=> [CI:DOCS] docs: drop note about upcoming RHEL 7.7

test/e2e/run_test.go
aafa80918a245edcbdaceb1191d749570f1872d0 introduced the regression.
=> test: fix podman run test as rootless

cmd/podman-mac-helper/install.go, cmd/podman/machine/init.go, contrib/helloimage/README.md, hack/xref-helpmsgs-manpages, libpod/networking_slirp4netns.go, pkg/k8s.io/api/core/v1/types.go, pkg/specgen/generate/container.go, test/buildah-bud/apply-podman-deltas, test/e2e/run_networking_test.go, test/system/005-info.bats, test/system/500-networking.bats
=> Run codespell to cleanup typos

cmd/podman/machine/init.go, pkg/machine/config.go, pkg/machine/config_test.go, pkg/machine/qemu/config.go, pkg/machine/qemu/config_test.go, pkg/machine/qemu/machine.go
the way machine was written was very adjunct and as such is in dire need
of refactoring to better structures and structure methods where
appropriate.  the weekest part is specifically around all the files that
machine requires and how some are just dynamically built on the fly.
this pr defines a new machinefile type which allows us to work with the
file and also takes into account the use of symlinks which are going to
be needed on macos due to its relatively short file length restriction.
also, added unit tests for new methods as well as anywhere else I saw a
need.
=> Machine refactor - part 1

pkg/machine/qemu/config.go, pkg/machine/qemu/machine.go
If podman detects a Machinev1 config, it will automatically migrate it
to the new format.
=> Migrate machine configs

pkg/specgen/generate/container_create.go, test/e2e/systemd_test.go
Fixes: https://github.com/containers/podman/issues/13324
=> Set systemd mode if entrypoint begins with /bin/sh -c

pkg/machine/qemu/config.go, pkg/machine/qemu/machine.go, pkg/machine/qemu/options_darwin_arm64.go
This PR further implements a more structured approach to handling the
files needed by machine.  More files are now made as MachineFile which
can then have a symlink (using a shorter path) to them.  Also added Set
and Get methods for many of the files.
The next part of the refactor will implement the use of symlinks on
MacOS.
=> Machine refactor part 2

README.md, RELEASE_NOTES.md, version/version.go
=> [CI:DOCS] Bump to v4.0.3

pkg/machine/qemu/config.go, pkg/machine/qemu/config_test.go, pkg/machine/qemu/machine.go
to avoid errors on macos, we use symlinks to long socket names.
Fixes: #12751
Fixes: #13609
=> machine refactor 3: add symlinks for sockets

pkg/machine/qemu/machine.go
=> Prevent set command from updating a running instance

pkg/machine/qemu/machine.go
Small adjustment to the docker socket link handling code to be compatible with the recent machine file refactor (#13750) 
=> Fix mac docker socket handling

README.md
As the title says.  Adds a Podman hello image
to the home page.  I ran it on windows, so had to have
a blue screen to honor that!
=> [CI:DOCS] Add Podman Hello to readme.md

cmd/podman/machine/inspect.go, docs/source/markdown/podman-machine-inspect.1.md, docs/source/markdown/podman-machine.1.md, pkg/machine/config.go, pkg/machine/qemu/machine.go, pkg/machine/wsl/machine.go
Allow users to inspect their podman virtual machines. This will be
helpful for debug and development alike, because more details about the
machine can be collected.
=> Introduce machine inspect

docs/source/markdown/podman-container-clone.1.md
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
=> [CI:DOCS] fix typo in podman-container-clone.1.md

go.mod, go.sum, vendor/github.com/containers/common/pkg/config/config.go, vendor/github.com/containers/common/pkg/config/containers.conf, vendor/github.com/containers/common/pkg/config/default.go, vendor/modules.txt
Want to add support for Machine.Volumes
=> Update containers/common to main branch

pkg/machine/wsl/machine.go
Backport of #13885 and #13655 
See #13873 
=> [v4.0] Respect "Rootful" when starting WSL API Forwarding

troubleshooting.md
- Consistent code block highlighting
- Minor spelling, formatting.
=> [CI:DOCS] Update troubleshooting.md

go.mod, go.sum, vendor/github.com/containerd/stargz-snapshotter/estargz/build.go, vendor/github.com/containerd/stargz-snapshotter/estargz/estargz.go, vendor/github.com/containerd/stargz-snapshotter/estargz/testutil.go, vendor/github.com/containers/storage/drivers/overlay/check.go, vendor/github.com/containers/storage/drivers/overlay/idmapped_utils.go, vendor/github.com/containers/storage/drivers/overlay/overlay.go, vendor/github.com/containers/storage/go.mod, vendor/github.com/containers/storage/go.sum, vendor/github.com/containers/storage/layers.go, vendor/github.com/containers/storage/store.go, vendor/github.com/containers/storage/utils.go, vendor/github.com/moby/sys/mountinfo/mounted_unix.go, vendor/modules.txt
=> Update vendor of storage,common

docs/source/markdown/podman-generate-kube.1.md, docs/source/markdown/podman-play-kube.1.md
This PR is related to https://github.com/containers/podman/issues/13840.
=> [CI:DOCS] Fix selinux docs for kubernetes yaml

RELEASE_NOTES.md, version/version.go
Hopefully our last CVE fix for the foreseeable future.
=> Bump to v3.4.7

hack/buildah-vendor-treadmill
This is the script I've been using (and tweaking) for the past
two weeks. It's ready for general review and use, with the
proviso that there are still corner cases I haven't tested.
See https://github.com/containers/podman/wiki/Buildah-Vendor-Treadmill
for an overview and instructions.
=> Buildah Vendor Treadmill: the script

docs/source/markdown/podman-image-unmount.1.md, pkg/specgen/generate/container.go, pkg/specgen/generate/container_create.go, test/system/090-events.bats
=> [CI:DOCS] Run codespell on code

test/system/500-networking.bats
=> Update test to run network check in both rootless and rootfull mode

cmd/podman/root.go, docs/source/markdown/podman.1.md, pkg/domain/infra/runtime_libpod.go, pkg/specgenutil/util.go, test/system/005-info.bats
Fixes: https://github.com/containers/podman/issues/13860
=> Add support for passing --volumepath

libpod/kube.go, test/e2e/generate_kube_test.go
Fixes: #13985 
Signed-off-by: wufan <1991849113@qq.com>
=> Modify the pod name suffix '_pod' to '-pod'

.golangci.yml, cmd/podman/containers/create.go, cmd/podman/containers/run.go, cmd/podman/system/connection/add.go, libpod/container_api.go, libpod/container_copy_linux.go, libpod/container_internal_linux.go, libpod/container_internal_linux_test.go, libpod/container_stat_linux.go, libpod/networking_linux.go, libpod/networking_linux_test.go, libpod/oci_conmon_exec_linux.go, libpod/oci_conmon_linux.go, libpod/runtime.go, libpod/runtime_ctr.go, libpod/runtime_migrate.go, libpod/runtime_volume_linux.go, pkg/autoupdate/autoupdate.go, pkg/domain/infra/abi/play.go, pkg/machine/fcos.go, pkg/specgen/generate/container_create.go, pkg/specgen/generate/namespaces.go, pkg/specgen/generate/oci.go, pkg/specgen/generate/pod_create.go, pkg/specgen/generate/ports.go, pkg/specgenutil/specgen.go, test/e2e/common_test.go, test/e2e/play_kube_test.go, test/e2e/run_aardvark_test.go, test/testvol/main.go
The unparam linter is useful to detect unused function parameters and
return values.
=> enable unparam linter
